zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/inittab.c File Reference
inittab.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/ioctl.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <regex.h>
#include <ctype.h>
#include <libubox/utils.h>
#include <libubox/list.h>
#include "utils/utils.h"
#include "procd.h"
#include "rcS.h"
Classes
struct init_handler
struct init_action
Macros
#define _GNU_SOURCE
#define O_PATH 010000000
#define TAG_ID 0
#define TAG_RUNLVL 1
#define TAG_ACTION 2
#define TAG_PROCESS 3
#define MAX_ARGS 8
#define LINE_LEN 128
Functions
static LIST_HEAD (actions)
static int dev_exist (const char *dev)
static void fork_worker (struct init_action *a)
static void child_exit (struct uloop_process *proc, int ret)
static void respawn (struct uloop_timeout *tout)
static void rcdone (struct runqueue *q)
static void runrc (struct init_action *a)
static void askfirst (struct init_action *a)
static void askconsole (struct init_action *a)
static void rcrespawn (struct init_action *a)
static int add_action (struct init_action *a, const char *name)
void procd_inittab_run (const char *handler)
void procd_inittab_kill (void)
void procd_inittab (void)
Variables
char * console = NULL
static const char * tab = "/etc/inittab"
static char * ask = "/sbin/askfirst"
static struct init_handler handlers []
Class Documentation
init_handler
struct init_handler
Definition at line 48 of file inittab.c.
Class Members
void(*)(struct init_action *a) cb
int multi
const char * name
init_action
struct init_action
Definition at line 54 of file inittab.c.
Class Members
char * argv[MAX_ARGS]
struct init_handler * handler
char * id
char * line
struct list_head list
struct uloop_process proc
int respawn
struct uloop_timeout tout
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 15 of file inittab.c.
LINE_LEN
#define LINE_LEN 128
Referenced by procd_inittab().
MAX_ARGS
#define MAX_ARGS 8
Definition at line 43 of file inittab.c.
Referenced by askconsole(), askfirst(), and procd_inittab().
O_PATH
#define O_PATH 010000000
Definition at line 35 of file inittab.c.
Referenced by dev_exist().
TAG_ACTION
#define TAG_ACTION 2
Definition at line 40 of file inittab.c.
Referenced by procd_inittab().
TAG_ID
#define TAG_ID 0
Definition at line 38 of file inittab.c.
Referenced by procd_inittab().
TAG_PROCESS
#define TAG_PROCESS 3
Definition at line 41 of file inittab.c.
Referenced by procd_inittab().
TAG_RUNLVL
#define TAG_RUNLVL 1
Definition at line 39 of file inittab.c.
Function Documentation
add_action()
static int add_action (struct init_action * a, const char * name) static
Definition at line 274 of file inittab.c.
{
    int i;
    for (i = 0; i < ARRAY_SIZE(handlers); i++)
        if (!strcmp(handlers[i].name, name)) {
            a->handler = &handlers[i];
            list_add_tail(&a->list, &actions);
            return 0;
        }
    ERROR("Unknown init handler %s\n", name);
    return -1;
}
References ARRAY_SIZE, ERROR, init_action::handler, handlers, init_action::list, list_add_tail(), and init_handler::name.
Referenced by procd_inittab().
askconsole()
static void askconsole (struct init_action * a) static
Definition at line 184 of file inittab.c.
{
    char line[256], *tty, *split;
    int i;
    /* First, try console= on the kernel command line,
     * then fallback to /sys/class/tty/console/active,
     * which should work when linux,stdout-path (or equivalent)
     * is in the device tree
     */
    tty = get_cmdline_val("console", line, sizeof(line));
    if (tty == NULL ||
        get_cmdline_val_offset("console", line, sizeof(line), 1)) {
        if (dev_exist("console"))
            tty = "console";
        else
            tty = get_active_console(line, sizeof(line));
    }
    if (tty != NULL) {
        split = strchr(tty, ',');
        if (split != NULL)
            *split = '\0';
        if (!dev_exist(tty)) {
            DEBUG(4, "skipping %s\n", tty);
            return;
        }
        console = strdup(tty);
        a->id = strdup(tty);
    }
    else {
        console = NULL;
        a->id = NULL;
    }
    a->tout.cb = respawn;
    /* shift arguments only if not yet done */
    if (a->argv[0] != ask) {
        for (i = MAX_ARGS - 1; i >= 1; i--)
            a->argv[i] = a->argv[i - 1];
        a->argv[0] = ask;
    }
    a->respawn = 500;
    a->proc.cb = child_exit;
    if (!a->proc.pid)
        fork_worker(a);
}
References init_action::argv, ask, uloop_process::cb, uloop_timeout::cb, child_exit(), console, DEBUG, dev_exist(), fork_worker(), get_active_console(), get_cmdline_val, get_cmdline_val_offset(), init_action::id, init_action::line, MAX_ARGS, uloop_process::pid, init_action::proc, init_action::respawn, respawn, and init_action::tout.
askfirst()
static void askfirst (struct init_action * a) static
Definition at line 161 of file inittab.c.
{
    int i;
    if (!dev_exist(a->id) || (console && !strcmp(console, a->id))) {
        DEBUG(4, "Skipping %s\n", a->id);
        return;
    }
    a->tout.cb = respawn;
    /* shift arguments only if not yet done */
    if (a->argv[0] != ask) {
        for (i = MAX_ARGS - 1; i >= 1; i--)
            a->argv[i] = a->argv[i - 1];
        a->argv[0] = ask;
    }
    a->respawn = 500;
    a->proc.cb = child_exit;
    if (!a->proc.pid)
        fork_worker(a);
}
References init_action::argv, ask, uloop_process::cb, uloop_timeout::cb, child_exit(), console, DEBUG, dev_exist(), fork_worker(), init_action::id, MAX_ARGS, uloop_process::pid, init_action::proc, init_action::respawn, respawn, and init_action::tout.
child_exit()
static void child_exit (struct uloop_process * proc, int ret) static
Definition at line 119 of file inittab.c.
{
    struct init_action *a = container_of(proc, struct init_action, proc);
    DEBUG(4, "pid:%d, exitcode:%d\n", proc->pid, ret);
    proc->pid = 0;
    if (a->respawn < 0)
        return;
    if (!dev_exist(a->id)) {
        DEBUG(4, "Skipping respawn: device '%s' does not exist anymore\n", a->id);
        return;
    }
    uloop_timeout_set(&a->tout, a->respawn);
}
References container_of, DEBUG, dev_exist(), init_action::id, uloop_process::pid, init_action::proc, init_action::respawn, init_action::tout, and uloop_timeout_set().
Referenced by askconsole(), askfirst(), and rcrespawn().
dev_exist()
static int dev_exist (const char * dev) static
Definition at line 73 of file inittab.c.
{
    int dfd, fd;
    dfd = open("/dev", O_PATH|O_DIRECTORY);
    if (dfd < 0)
        return 0;
    fd = openat(dfd, dev, O_RDONLY);
    close(dfd);
    if (fd < 0)
        return 0;
    close(fd);
    return 1;
}
References O_PATH.
Referenced by askconsole(), askfirst(), and child_exit().
fork_worker()
static void fork_worker (struct init_action * a) static
Definition at line 92 of file inittab.c.
{
    pid_t p;
    a->proc.pid = fork();
    if (!a->proc.pid) {
        p = setsid();
        if (patch_stdio(a->id))
            ERROR("Failed to setup i/o redirection\n");
        ioctl(STDIN_FILENO, TIOCSCTTY, 1);
        tcsetpgrp(STDIN_FILENO, p);
        execvp(a->argv[0], a->argv);
        ERROR("Failed to execute %s: %m\n", a->argv[0]);
        exit(-1);
    }
    if (a->proc.pid > 0) {
        DEBUG(4, "Launched new %s action, pid=%d\n",
                    a->handler->name,
                    (int) a->proc.pid);
        uloop_process_add(&a->proc);
    }
}
References init_action::argv, DEBUG, ERROR, init_action::handler, init_action::id, init_handler::name, patch_stdio(), uloop_process::pid, init_action::proc, and uloop_process_add().
Referenced by askconsole(), askfirst(), rcrespawn(), and respawn().
LIST_HEAD()
static LIST_HEAD (actions) static
procd_inittab()
void procd_inittab (void)
Definition at line 311 of file inittab.c.
{
#define LINE_LEN    128
    FILE *fp = fopen(tab, "r");
    struct init_action *a;
    regex_t pat_inittab;
    regmatch_t matches[5];
    char *line;
    if (!fp) {
        ERROR("Failed to open %s: %m\n", tab);
        return;
    }
    regcomp(&pat_inittab, "([a-zA-Z0-9]*):([a-zA-Z0-9]*):([a-zA-Z0-9]*):(.*)", REG_EXTENDED);
    line = malloc(LINE_LEN);
    a = calloc(1, sizeof(struct init_action));
    while (fgets(line, LINE_LEN, fp)) {
        char *tags[TAG_PROCESS + 1];
        char *tok;
        int i;
        int len = strlen(line);
        while (isspace(line[len - 1]))
            len--;
        line[len] = 0;
        if (*line == '#')
            continue;
        if (regexec(&pat_inittab, line, 5, matches, 0))
            continue;
        DEBUG(4, "Parsing inittab - %s\n", line);
        for (i = TAG_ID; i <= TAG_PROCESS; i++) {
            line[matches[i].rm_eo] = '\0';
            tags[i] = &line[matches[i + 1].rm_so];
        };
        tok = strtok(tags[TAG_PROCESS], " ");
        for (i = 0; i < (MAX_ARGS - 1) && tok; i++) {
            a->argv[i] = tok;
            tok = strtok(NULL, " ");
        }
        a->argv[i] = NULL;
        a->id = tags[TAG_ID];
        a->line = line;
        if (add_action(a, tags[TAG_ACTION]))
            continue;
        line = malloc(LINE_LEN);
        a = calloc(1, sizeof(struct init_action));
    }
    fclose(fp);
    free(line);
    free(a);
    regfree(&pat_inittab);
}
References add_action(), init_action::argv, DEBUG, ERROR, init_action::id, init_action::line, LINE_LEN, MAX_ARGS, tab, TAG_ACTION, TAG_ID, and TAG_PROCESS.
Referenced by state_enter().
procd_inittab_kill()
void procd_inittab_kill (void)
Definition at line 300 of file inittab.c.
{
    struct init_action *a;
    list_for_each_entry(a, &actions, list) {
        a->respawn = -1;
        if (a->proc.pid)
            kill(a->proc.pid, SIGKILL);
    }
}
References init_action::list, list_for_each_entry, uloop_process::pid, init_action::proc, and init_action::respawn.
Referenced by service_stop_all().
procd_inittab_run()
void procd_inittab_run (const char * handler)
Definition at line 288 of file inittab.c.
{
    struct init_action *a;
    list_for_each_entry(a, &actions, list)
        if (!strcmp(a->handler->name, handler)) {
            a->handler->cb(a);
            if (!a->handler->multi)
                break;
        }
}
References init_handler::cb, init_action::handler, init_action::list, list_for_each_entry, init_handler::multi, and init_handler::name.
Referenced by handle_start_console(), and state_enter().
rcdone()
static void rcdone (struct runqueue * q) static
Definition at line 144 of file inittab.c.
{
    procd_state_next();
}
References procd_state_next().
Referenced by runrc().
rcrespawn()
static void rcrespawn (struct init_action * a) static
Definition at line 234 of file inittab.c.
{
    a->tout.cb = respawn;
    a->respawn = 500;
    a->proc.cb = child_exit;
    if (!a->proc.pid)
        fork_worker(a);
}
References uloop_process::cb, uloop_timeout::cb, child_exit(), fork_worker(), uloop_process::pid, init_action::proc, init_action::respawn, respawn, and init_action::tout.
respawn()
static void respawn (struct uloop_timeout * tout) static
Definition at line 137 of file inittab.c.
{
    struct init_action *a = container_of(tout, struct init_action, tout);
    if (!a->proc.pid)
        fork_worker(a);
}
References container_of, fork_worker(), uloop_process::pid, init_action::proc, and init_action::tout.
runrc()
static void runrc (struct init_action * a) static
Definition at line 149 of file inittab.c.
{
    if (!a->argv[1] || !a->argv[2]) {
        ERROR("valid format is rcS <S|K> <param>\n");
        return;
    }
    /* proceed even if no init or shutdown scripts run */
    if (rcS(a->argv[1], a->argv[2], rcdone))
        rcdone(NULL);
}
References init_action::argv, ERROR, rcdone(), and rcS().
Variable Documentation
ask
char* ask = "/sbin/askfirst" static
Definition at line 69 of file inittab.c.
Referenced by askconsole(), and askfirst().
console
char* console = NULL
Definition at line 46 of file inittab.c.
Referenced by askconsole(), askfirst(), instance_console(), main(), and uxc_start().
handlers
struct init_handler handlers[] static
Initial value:
= {
    {
        .name = "sysinit",
        .cb = runrc,
    }, {
        .name = "shutdown",
        .cb = runrc,
    }, {
        .name = "askfirst",
        .cb = askfirst,
        .multi = 1,
    }, {
        .name = "askconsole",
        .cb = askconsole,
        .multi = 1,
    }, {
        .name = "respawn",
        .cb = rcrespawn,
        .multi = 1,
    }, {
        .name = "askconsolelate",
        .cb = askconsole,
        .multi = 1,
    }, {
        .name = "respawnlate",
        .cb = rcrespawn,
        .multi = 1,
    }
}
Definition at line 244 of file inittab.c.
{
    {
        .name = "sysinit",
        .cb = runrc,
    }, {
        .name = "shutdown",
        .cb = runrc,
    }, {
        .name = "askfirst",
        .cb = askfirst,
        .multi = 1,
    }, {
        .name = "askconsole",
        .cb = askconsole,
        .multi = 1,
    }, {
        .name = "respawn",
        .cb = rcrespawn,
        .multi = 1,
    }, {
        .name = "askconsolelate",
        .cb = askconsole,
        .multi = 1,
    }, {
        .name = "respawnlate",
        .cb = rcrespawn,
        .multi = 1,
    }
};
Referenced by add_action().
tab
const char* tab = "/etc/inittab" static
Definition at line 68 of file inittab.c.
Referenced by procd_inittab().