zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/utils/utils.c File Reference
utils.c File Reference
#include <libubox/avl.h>
#include <libubox/avl-cmp.h>
#include "utils.h"
#include <regex.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <string.h>
#include <errno.h>
#include "../log.h"
Macros
#define _GNU_SOURCE
#define O_PATH 010000000
Functions
void __blobmsg_list_init (struct blobmsg_list *list, int offset, int len, blobmsg_list_cmp cmp)
int blobmsg_list_fill (struct blobmsg_list *list, void *data, int len, bool array)
void blobmsg_list_move (struct blobmsg_list *list, struct blobmsg_list *src)
void blobmsg_list_free (struct blobmsg_list *list)
bool blobmsg_list_equal (struct blobmsg_list *l1, struct blobmsg_list *l2)
char * get_active_console (char *out, int len)
char * get_cmdline_val_offset (const char *name, char *out, int len, int offset)
int patch_fd (const char *device, int fd, int flags)
int patch_stdio (const char *device)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 15 of file utils.c.
O_PATH
#define O_PATH 010000000
Definition at line 30 of file utils.c.
Referenced by patch_fd().
Function Documentation
__blobmsg_list_init()
void __blobmsg_list_init (struct blobmsg_list * list, int offset, int len, blobmsg_list_cmp cmp)
Definition at line 34 of file utils.c.
{
    avl_init(&list->avl, avl_strcmp, false, NULL);
    list->node_offset = offset;
    list->node_len = len;
    list->cmp = cmp;
}
References blobmsg_list::avl, avl_init(), avl_strcmp(), blobmsg_list::cmp, cmp, blobmsg_list::node_len, and blobmsg_list::node_offset.
blobmsg_list_equal()
bool blobmsg_list_equal (struct blobmsg_list * l1, struct blobmsg_list * l2)
Definition at line 104 of file utils.c.
{
    struct blobmsg_list_node *n1, *n2;
    int count = l1->avl.count;
    if (count != l2->avl.count)
        return false;
    n1 = avl_first_element(&l1->avl, n1, avl);
    n2 = avl_first_element(&l2->avl, n2, avl);
    while (count-- > 0) {
        int len;
        len = blob_len(n1->data);
        if (len != blob_len(n2->data))
            return false;
        if (memcmp(n1->data, n2->data, len) != 0)
            return false;
        if (l1->cmp && !l1->cmp(n1, n2))
            return false;
        if (!count)
            break;
        n1 = avl_next_element(n1, avl);
        n2 = avl_next_element(n2, avl);
    }
    return true;
}
References blobmsg_list::avl, blobmsg_list_node::avl, avl_first_element, avl_next_element, blob_len(), blobmsg_list::cmp, avl_tree::count, and blobmsg_list_node::data.
Referenced by instance_config_changed().
blobmsg_list_fill()
int blobmsg_list_fill (struct blobmsg_list * list, void * data, int len, bool array)
Definition at line 43 of file utils.c.
{
    struct avl_tree *tree = &list->avl;
    struct blobmsg_list_node *node;
    struct blob_attr *cur;
    void *ptr;
    int count = 0;
    int rem = len;
    __blob_for_each_attr(cur, data, rem) {
        if (!blobmsg_check_attr(cur, !array))
            continue;
        ptr = calloc(1, list->node_len);
        if (!ptr)
            return -1;
        node = (void *) ((char *)ptr + list->node_offset);
        if (array)
            node->avl.key = blobmsg_data(cur);
        else
            node->avl.key = blobmsg_name(cur);
        node->data = cur;
        if (avl_insert(tree, &node->avl)) {
            free(ptr);
            continue;
        }
        count++;
    }
    return count;
}
References __blob_for_each_attr, blobmsg_list::avl, node::avl, avl_insert(), blobmsg_check_attr(), blobmsg_data(), blobmsg_name(), blob_attr::data, avl_node::key, blobmsg_list::node_len, and blobmsg_list::node_offset.
Referenced by instance_fill_any(), instance_fill_array(), instance_jail_parse(), and service_update().
blobmsg_list_free()
void blobmsg_list_free (struct blobmsg_list * list)
Definition at line 92 of file utils.c.
{
    struct blobmsg_list_node *node, *tmp;
    void *ptr;
    avl_remove_all_elements(&list->avl, node, avl, tmp) {
        ptr = ((char *) node - list->node_offset);
        free(ptr);
    }
}
References blobmsg_list::avl, blobmsg_list_node::avl, avl_remove_all_elements, and blobmsg_list::node_offset.
Referenced by instance_config_cleanup(), service_delete(), and service_update().
blobmsg_list_move()
void blobmsg_list_move (struct blobmsg_list * list, struct blobmsg_list * src)
Definition at line 78 of file utils.c.
{
    struct blobmsg_list_node *node, *tmp;
    void *ptr;
    avl_remove_all_elements(&src->avl, node, avl, tmp) {
        if (avl_insert(&list->avl, &node->avl)) {
            ptr = ((char *) node - list->node_offset);
            free(ptr);
        }
    }
}
References blobmsg_list::avl, blobmsg_list_node::avl, node::avl, avl_insert(), avl_remove_all_elements, and blobmsg_list::node_offset.
Referenced by instance_config_move().
get_active_console()
char * get_active_console (char * out, int len)
Definition at line 138 of file utils.c.
{
    char line[CMDLINE_SIZE + 1];
    int fd = open("/sys/class/tty/console/active", O_RDONLY);
    ssize_t r;
    if (fd < 0)
        return NULL;
    r = read(fd, line, sizeof(line) - 1);
    line[CMDLINE_SIZE] = '\0';
    close(fd);
    if (r <= 0)
        return NULL;
    /* The active file is terminated by a newline which we need to strip */
    char *newline = strtok(line, "\n");
    if (newline != NULL) {
        strlcpy(out, newline, len);
        return out;
    }
    return NULL;
}
References CMDLINE_SIZE, r, and strlcpy.
Referenced by askconsole().
get_cmdline_val_offset()
char * get_cmdline_val_offset (const char * name, char * out, int len, int offset)
Definition at line 166 of file utils.c.
{
    char line[CMDLINE_SIZE + 1], *c, *sptr;
    int i, fd = open("/proc/cmdline", O_RDONLY);
    ssize_t r;
    if (fd < 0)
        return NULL;
    r = read(fd, line, sizeof(line) - 1);
    close(fd);
    if (r <= 0)
        return NULL;
    line[r] = 0;
    for (i = 0, c = strtok_r(line, " \t\n", &sptr); c;
            c = strtok_r(NULL, " \t\n", &sptr)) {
        char *sep = strchr(c, '=');
        if (sep == NULL)
            continue;
        ssize_t klen = sep - c;
        if (strncmp(name, c, klen) || name[klen] != 0)
            continue;
        if (i++ < offset)
            continue;
        strlcpy(out, &sep[1], len);
        return out;
    }
    return NULL;
}
References CMDLINE_SIZE, r, and strlcpy.
Referenced by askconsole().
patch_fd()
int patch_fd (const char * device, int fd, int flags)
Definition at line 202 of file utils.c.
{
    int dfd, nfd;
    if (device == NULL)
        device = "/dev/null";
    if (*device != '/') {
        dfd = open("/dev", O_PATH|O_DIRECTORY);
        if (dfd < 0)
            return -1;
        nfd = openat(dfd, device, flags);
        close(dfd);
    } else {
        nfd = open(device, flags);
    }
    if (nfd < 0 && strcmp(device, "/dev/null"))
        nfd = open("/dev/null", flags);
    if (nfd < 0)
        return -1;
    fd = dup2(nfd, fd);
    if (nfd > STDERR_FILENO)
        close(nfd);
    return (fd < 0) ? -1 : 0;
}
References O_PATH.
Referenced by patch_stdio().
patch_stdio()
int patch_stdio (const char * device)
Definition at line 236 of file utils.c.
{
    int fd, rv = 0;
    const char *fdname[3] = { "stdin", "stdout", "stderr" };
    for (fd = STDIN_FILENO; fd <= STDERR_FILENO; fd++) {
        if (patch_fd(device, fd, fd ? O_WRONLY : O_RDONLY)) {
            ERROR("Failed to redirect %s to %s: %m\n",
                  fdname[fd], device);
            rv = -1;
        }
    }
    return rv;
}
References ERROR, and patch_fd().
Referenced by early_console(), fork_worker(), and main().