zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/ustp/packet.h File Reference
packet.h File Reference
#include <sys/uio.h>
Functions
void packet_send (int ifindex, const struct iovec *iov, int iov_count, int len)
int packet_sock_init (void)
void packet_rcv ()
Function Documentation
packet_rcv()
void packet_rcv ()
Definition at line 114 of file packet.c.
{
    unsigned char buf[2048];
    struct sockaddr_ll sl;
    socklen_t salen = sizeof sl;
    int cc;
    while (1) {
        cc = recvfrom(ufd.fd, &buf, sizeof(buf), 0, (struct sockaddr *) &sl, &salen);
        if (cc < 0) {
            switch (errno) {
            case EINTR:
                continue;
            case EAGAIN:
                return;
            default:
                cc = 0;
            }
        }
        if (cc == 0) {
            ERROR("recvfrom failed: %m");
            uloop_fd_delete(&ufd);
            return;
        }
#ifdef PACKET_DEBUG
        printf("Receive Src ifindex %d %02x:%02x:%02x:%02x:%02x:%02x\n",
               sl.sll_ifindex,
               sl.sll_addr[0], sl.sll_addr[1], sl.sll_addr[2],
               sl.sll_addr[3], sl.sll_addr[4], sl.sll_addr[5]);
        dump_packet(buf, cc);
#endif
        bridge_bpdu_rcv(sl.sll_ifindex, buf, cc);
    }
}
References bridge_bpdu_rcv(), buf, ERROR, uloop_fd::fd, ufd, and uloop_fd_delete().
Referenced by handle_worker_event().
packet_send()
void packet_send (int ifindex, const struct iovec * iov, int iov_count, int len)
Definition at line 66 of file packet.c.
{
    int l;
    struct sockaddr_ll sl =
    {
        .sll_family = AF_PACKET,
        .sll_protocol = __constant_cpu_to_be16(ETH_P_802_2),
        .sll_ifindex = ifindex,
        .sll_halen = ETH_ALEN,
    };
    if(iov_count > 0 && iov[0].iov_len > ETH_ALEN)
        memcpy(&sl.sll_addr, iov[0].iov_base, ETH_ALEN);
    struct msghdr msg =
    {
        .msg_name = &sl,
        .msg_namelen = sizeof(sl),
        .msg_iov = (struct iovec *)iov,
        .msg_iovlen = iov_count,
        .msg_control = NULL,
        .msg_controllen = 0,
        .msg_flags = 0,
    };
#ifdef PACKET_DEBUG
    printf("Transmit Dst index %d %02x:%02x:%02x:%02x:%02x:%02x\n",
           sl.sll_ifindex,
           sl.sll_addr[0], sl.sll_addr[1], sl.sll_addr[2],
           sl.sll_addr[3], sl.sll_addr[4], sl.sll_addr[5]);
    {
        int i;
        for(i = 0; i < iov_count; ++i)
            dump_packet(iov[i].iov_base, iov[i].iov_len);
    }
#endif
    l = sendmsg(ufd.fd, &msg, 0);
    if(l < 0)
    {
        if(errno != EWOULDBLOCK)
            ERROR("send failed: %m");
    }
    else if(l != len)
        ERROR("short write in sendto: %d instead of %d", l, len);
}
References ERROR, uloop_fd::fd, and ufd.
Referenced by MSTP_OUT_tx_bpdu().
packet_sock_init()
int packet_sock_init (void)
Definition at line 182 of file packet.c.
{
    struct sock_fprog prog =
    {
        .len = sizeof(stp_filter) / sizeof(stp_filter[0]),
        .filter = stp_filter,
    };
    int s;
    s = socket(PF_PACKET, SOCK_RAW, htons(ETH_P_802_2));
    if(s < 0)
    {
        ERROR("socket failed: %m");
        return -1;
    }
    if (setsockopt(s, SOL_SOCKET, SO_ATTACH_FILTER, &prog, sizeof(prog)) < 0) {
        ERROR("setsockopt packet filter failed: %m");
        goto out;
    }
    if (fcntl(s, F_SETFL, O_NONBLOCK) < 0) {
        ERROR("fcntl set nonblock failed: %m");
        goto out;
    }
    ufd.fd = s;
    ufd.cb = packet_event;
    uloop_fd_add(&ufd, ULOOP_READ | ULOOP_EDGE_TRIGGER);
    return 0;
out:
    close(s);
    return -1;
}
References uloop_fd::cb, ERROR, uloop_fd::fd, packet_event(), stp_filter, ufd, ULOOP_EDGE_TRIGGER, uloop_fd_add(), and ULOOP_READ.
Referenced by main().