zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/libubox/tests/test-blob-parse.c File Reference
test-blob-parse.c File Reference
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include <libgen.h>
#include "blob.h"
#include "list.h"
#include "blobmsg_json.h"
Classes
struct cert_object
Macros
#define CERT_BUF_LEN 4096
Enumerations
enum cert_attr { CERT_ATTR_SIGNATURE , CERT_ATTR_PAYLOAD , CERT_ATTR_MAX }
enum cert_cont_attr { CERT_CT_ATTR_PAYLOAD , CERT_CT_ATTR_MAX }
enum cert_payload_attr {
CERT_PL_ATTR_CERTTYPE , CERT_PL_ATTR_CERTID , CERT_PL_ATTR_VALIDFROMTIME , CERT_PL_ATTR_EXPIRETIME ,
CERT_PL_ATTR_PUBKEY , CERT_PL_ATTR_KEY_FINGERPRINT , CERT_PL_ATTR_MAX
}
enum certtype_id { CERTTYPE_UNSPEC , CERTTYPE_AUTH , CERTTYPE_REVOKE }
Functions
static int cert_load (const char *certfile, struct list_head *chain)
static void cert_dump_blob (struct blob_attr *cert[CERT_ATTR_MAX])
static int cert_dump (const char *certfile)
int main (int argc, char *argv[])
Variables
static const struct blob_attr_info cert_policy [CERT_ATTR_MAX]
Class Documentation
cert_object
struct cert_object
Definition at line 60 of file test-blob-parse.c.
Class Members
struct blob_attr * cert[CERT_ATTR_MAX]
struct list_head list
Macro Definition Documentation
CERT_BUF_LEN
#define CERT_BUF_LEN 4096
Definition at line 18 of file test-blob-parse.c.
Referenced by cert_load().
Enumeration Type Documentation
cert_attr
enum cert_attr
Enumerator
CERT_ATTR_SIGNATURE
CERT_ATTR_PAYLOAD
CERT_ATTR_MAX
Definition at line 27 of file test-blob-parse.c.
               {
    CERT_ATTR_SIGNATURE,
    CERT_ATTR_PAYLOAD,
    CERT_ATTR_MAX
};
cert_cont_attr
enum cert_cont_attr
Enumerator
CERT_CT_ATTR_PAYLOAD
CERT_CT_ATTR_MAX
Definition at line 38 of file test-blob-parse.c.
                    {
    CERT_CT_ATTR_PAYLOAD,
    CERT_CT_ATTR_MAX
};
cert_payload_attr
enum cert_payload_attr
Enumerator
CERT_PL_ATTR_CERTTYPE
CERT_PL_ATTR_CERTID
CERT_PL_ATTR_VALIDFROMTIME
CERT_PL_ATTR_EXPIRETIME
CERT_PL_ATTR_PUBKEY
CERT_PL_ATTR_KEY_FINGERPRINT
CERT_PL_ATTR_MAX
Definition at line 43 of file test-blob-parse.c.
                       {
    CERT_PL_ATTR_CERTTYPE,
    CERT_PL_ATTR_CERTID,
    CERT_PL_ATTR_VALIDFROMTIME,
    CERT_PL_ATTR_EXPIRETIME,
    CERT_PL_ATTR_PUBKEY,
    CERT_PL_ATTR_KEY_FINGERPRINT,
    CERT_PL_ATTR_MAX
};
certtype_id
enum certtype_id
Enumerator
CERTTYPE_UNSPEC
CERTTYPE_AUTH
CERTTYPE_REVOKE
Definition at line 53 of file test-blob-parse.c.
                 {
    CERTTYPE_UNSPEC,
    CERTTYPE_AUTH,
    CERTTYPE_REVOKE
};
Function Documentation
cert_dump()
static int cert_dump (const char * certfile) static
Definition at line 155 of file test-blob-parse.c.
{
    struct cert_object *cobj;
    static LIST_HEAD(certchain);
    unsigned int count = 0;
    if (cert_load(certfile, &certchain)) {
        fprintf(stderr, "cannot parse cert %s\n", basename((char *) certfile));
        return 1;
    }
    list_for_each_entry(cobj, &certchain, list) {
        fprintf(stdout, "=== CHAIN ELEMENT %02u ===\n", ++count);
        cert_dump_blob(cobj->cert);
    }
    return 0;
}
References cert_object::cert, cert_dump_blob(), cert_load(), cert_object::list, list_for_each_entry, and LIST_HEAD.
Referenced by main().
cert_dump_blob()
static void cert_dump_blob (struct blob_attr * cert[CERT_ATTR_MAX]) static
Definition at line 128 of file test-blob-parse.c.
{
    int i;
    char *json = NULL;
    for (i = 0; i < CERT_ATTR_MAX; i++) {
        struct blob_attr *v = cert[i];
        if (!v)
            continue;
        switch(cert_policy[i].type) {
        case BLOB_ATTR_BINARY:
            fprintf(stdout, "signature:\n---\n%s---\n", (char *) blob_data(v));
            break;
        case BLOB_ATTR_NESTED:
            json = blobmsg_format_json_indent(blob_data(v), false, 0);
            if (!json)
                continue;
            fprintf(stdout, "payload:\n---\n%s\n---\n", json);
            free(json);
            break;
        }
    }
}
References BLOB_ATTR_BINARY, BLOB_ATTR_NESTED, blob_data(), blobmsg_format_json_indent(), CERT_ATTR_MAX, cert_policy, json, and type.
Referenced by cert_dump().
cert_load()
static int cert_load (const char * certfile, struct list_head * chain) static
Definition at line 65 of file test-blob-parse.c.
{
    FILE *f;
    struct blob_attr *certtb[CERT_ATTR_MAX];
    struct blob_attr *bufpt;
    struct cert_object *cobj;
    char *filebuf = NULL;
    int ret = 0, pret = 0;
    size_t len, pos = 0;
    f = fopen(certfile, "r");
    if (!f)
        return 1;
    filebuf = malloc(CERT_BUF_LEN+1);
    if (!filebuf)
        return 1;
    len = fread(filebuf, 1, CERT_BUF_LEN, f);
    if (len < 64) {
        free(filebuf);
        return 1;
    }
    ret = ferror(f) || !feof(f);
    fclose(f);
    if (ret) {
        free(filebuf);
        return 1;
    }
    bufpt = (struct blob_attr *)filebuf;
    do {
        pret = blob_parse_untrusted(bufpt, len, certtb, cert_policy, CERT_ATTR_MAX);
        if (pret <= 0)
            /* no attributes found */
            break;
        if (pos + blob_pad_len(bufpt) > len)
            /* blob exceeds filebuffer */
            break;
        else
            pos += blob_pad_len(bufpt);
        if (!certtb[CERT_ATTR_SIGNATURE])
            /* no signature -> drop */
            break;
        cobj = calloc(1, sizeof(*cobj));
        cobj->cert[CERT_ATTR_SIGNATURE] = blob_memdup(certtb[CERT_ATTR_SIGNATURE]);
        if (certtb[CERT_ATTR_PAYLOAD])
            cobj->cert[CERT_ATTR_PAYLOAD] = blob_memdup(certtb[CERT_ATTR_PAYLOAD]);
        list_add_tail(&cobj->list, chain);
        ret += pret;
    /* repeat parsing while there is still enough remaining data in buffer */
    } while(len > pos + sizeof(struct blob_attr) && (bufpt = blob_next(bufpt)));
    free(filebuf);
    return (ret <= 0);
}
References blob_memdup(), blob_next(), blob_pad_len(), blob_parse_untrusted(), cert_object::cert, CERT_ATTR_MAX, CERT_ATTR_PAYLOAD, CERT_ATTR_SIGNATURE, CERT_BUF_LEN, cert_policy, cert_object::list, and list_add_tail().
Referenced by cert_dump().
main()
int main (int argc, char * argv[])
Definition at line 174 of file test-blob-parse.c.
{
    if (argc != 2) {
        fprintf(stderr, "Usage: %s <cert.ucert>\n", argv[0]);
        return 3;
    }
    cert_dump(argv[1]);
    return 0;
}
References cert_dump().
Variable Documentation
cert_policy
const struct blob_attr_info cert_policy[CERT_ATTR_MAX] static
Initial value:
= {
    [CERT_ATTR_SIGNATURE] = { .type = BLOB_ATTR_BINARY },
    [CERT_ATTR_PAYLOAD] = { .type = BLOB_ATTR_NESTED },
}
Definition at line 33 of file test-blob-parse.c.
{
    [CERT_ATTR_SIGNATURE] = { .type = BLOB_ATTR_BINARY },
    [CERT_ATTR_PAYLOAD] = { .type = BLOB_ATTR_NESTED },
};
Referenced by cert_dump_blob(), and cert_load().