zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/libubox/uloop.c File Reference
uloop.c File Reference
#include <sys/time.h>
#include <sys/types.h>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <poll.h>
#include <string.h>
#include <fcntl.h>
#include <stdbool.h>
#include <limits.h>
#include "uloop.h"
#include "utils.h"
#include <sys/epoll.h>
#include <sys/timerfd.h>
#include <sys/wait.h>
#include "uloop-epoll.c"
Classes
struct uloop_fd_event
struct uloop_fd_stack
Macros
#define ULOOP_MAX_EVENTS 10
Functions
int uloop_fd_add (struct uloop_fd *sock, unsigned int flags)
static void set_signo (uint64_t *signums, int signo)
static bool get_signo (uint64_t signums, int signo)
static void signal_consume (struct uloop_fd *fd, unsigned int events)
static void waker_init_fd (int fd)
static int waker_init (void)
static void uloop_setup_signals (bool add)
int uloop_init (void)
static bool uloop_fd_stack_event (struct uloop_fd *fd, int events)
static void uloop_run_events (int64_t timeout)
int uloop_fd_delete (struct uloop_fd *fd)
static int64_t tv_diff (struct timeval *t1, struct timeval *t2)
int uloop_timeout_add (struct uloop_timeout *timeout)
static void uloop_gettime (struct timeval *tv)
int uloop_timeout_set (struct uloop_timeout *timeout, int msecs)
int uloop_timeout_cancel (struct uloop_timeout *timeout)
int uloop_timeout_remaining (struct uloop_timeout *timeout)
int64_t uloop_timeout_remaining64 (struct uloop_timeout *timeout)
int uloop_process_add (struct uloop_process *p)
int uloop_process_delete (struct uloop_process *p)
static void uloop_handle_processes (void)
int uloop_interval_set (struct uloop_interval *timer, unsigned int msecs)
int uloop_interval_cancel (struct uloop_interval *timer)
int64_t uloop_interval_remaining (struct uloop_interval *timer)
static void uloop_signal_wake (int signo)
static void uloop_handle_sigint (int signo)
static void uloop_install_handler (int signum, void(*handler)(int), struct sigaction *old, bool add)
static void uloop_ignore_signal (int signum, bool ignore)
int uloop_signal_add (struct uloop_signal *s)
int uloop_signal_delete (struct uloop_signal *s)
int uloop_get_next_timeout (void)
static void uloop_process_timeouts (void)
static void uloop_clear_timeouts (void)
static void uloop_clear_processes (void)
bool uloop_cancelling (void)
int uloop_run_timeout (int timeout)
void uloop_done (void)
Variables
static struct uloop_fd_stack * fd_stack = NULL
static struct list_head timeouts = LIST_HEAD_INIT(timeouts)
static struct list_head processes = LIST_HEAD_INIT(processes)
static struct list_head signals = LIST_HEAD_INIT(signals)
static int poll_fd = -1
bool uloop_cancelled = false
bool uloop_handle_sigchld = true
static int uloop_status = 0
static bool do_sigchld = false
static struct uloop_fd_event cur_fds [ULOOP_MAX_EVENTS]
static int cur_fd
static int cur_nfds
static int uloop_run_depth = 0
uloop_fd_handler uloop_fd_set_cb = NULL
static int waker_pipe = -1
static struct uloop_fd waker_fd
Class Documentation
uloop_fd_event
struct uloop_fd_event
Definition at line 43 of file uloop.c.
Class Members
unsigned int events
struct uloop_fd * fd
uloop_fd_stack
struct uloop_fd_stack
Definition at line 48 of file uloop.c.
Class Members
unsigned int events
struct uloop_fd * fd
struct uloop_fd_stack * next
Macro Definition Documentation
ULOOP_MAX_EVENTS
#define ULOOP_MAX_EVENTS 10
Definition at line 56 of file uloop.c.
Function Documentation
get_signo()
static bool get_signo (uint64_t signums, int signo) static
Definition at line 90 of file uloop.c.
{
    return (signo >= 1) && (signo <= 64) && (signums & (1u << (signo - 1)));
}
Referenced by signal_consume().
set_signo()
static void set_signo (uint64_t * signums, int signo) static
Definition at line 84 of file uloop.c.
{
    if (signo >= 1 && signo <= 64)
        *signums |= (1u << (signo - 1));
}
Referenced by signal_consume().
signal_consume()
static void signal_consume (struct uloop_fd * fd, unsigned int events) static
Definition at line 95 of file uloop.c.
{
    struct uloop_signal *usig, *usig_next;
    uint64_t signums = 0;
    uint8_t buf[32];
    ssize_t nsigs;
    do {
        nsigs = read(fd->fd, buf, sizeof(buf));
        for (ssize_t i = 0; i < nsigs; i++)
            set_signo(&signums, buf[i]);
    }
    while (nsigs > 0);
    list_for_each_entry_safe(usig, usig_next, &signals, list)
        if (get_signo(signums, usig->signo))
            usig->cb(usig);
}
References buf, uloop_signal::cb, uloop_fd::fd, get_signo(), uloop_signal::list, list_for_each_entry_safe, set_signo(), signals, and uloop_signal::signo.
Referenced by waker_init().
tv_diff()
static int64_t tv_diff (struct timeval * t1, struct timeval * t2) static
Definition at line 291 of file uloop.c.
{
    return
        (t1->tv_sec - t2->tv_sec) * 1000 +
        (t1->tv_usec - t2->tv_usec) / 1000;
}
Referenced by uloop_get_next_timeout(), uloop_process_timeouts(), uloop_timeout_add(), uloop_timeout_remaining(), and uloop_timeout_remaining64().
uloop_cancelling()
bool uloop_cancelling (void)
Definition at line 653 of file uloop.c.
{
    return uloop_run_depth > 0 && uloop_cancelled;
}
References uloop_cancelled, and uloop_run_depth.
Referenced by ubus_handle_data().
uloop_clear_processes()
static void uloop_clear_processes (void) static
Definition at line 645 of file uloop.c.
{
    struct uloop_process *p, *tmp;
    list_for_each_entry_safe(p, tmp, &processes, list)
        uloop_process_delete(p);
}
References uloop_process::list, list_for_each_entry_safe, processes, and uloop_process_delete().
Referenced by uloop_done().
uloop_clear_timeouts()
static void uloop_clear_timeouts (void) static
Definition at line 637 of file uloop.c.
{
    struct uloop_timeout *t, *tmp;
    list_for_each_entry_safe(t, tmp, &timeouts, list)
        uloop_timeout_cancel(t);
}
References uloop_timeout::list, list_for_each_entry_safe, timeouts, and uloop_timeout_cancel().
Referenced by uloop_done().
uloop_done()
void uloop_done (void)
Definition at line 686 of file uloop.c.
{
    uloop_setup_signals(false);
    if (poll_fd >= 0) {
        close(poll_fd);
        poll_fd = -1;
    }
    if (waker_pipe >= 0) {
        uloop_fd_delete(&waker_fd);
        close(waker_pipe);
        close(waker_fd.fd);
        waker_pipe = -1;
    }
    uloop_clear_timeouts();
    uloop_clear_processes();
}
References uloop_fd::fd, poll_fd, uloop_clear_processes(), uloop_clear_timeouts(), uloop_fd_delete(), uloop_setup_signals(), waker_fd, and waker_pipe.
Referenced by do_listen(), instance_start(), main(), main(), main(), post_poststart(), queue_next(), rpc_cgi_password_set(), rpc_exec(), rpc_file_exec_run(), ubus_cli_monitor(), ubus_cli_wait_for(), and uloop_init().
uloop_fd_add()
int uloop_fd_add (struct uloop_fd * sock, unsigned int flags)
Definition at line 235 of file uloop.c.
{
    unsigned int fl;
    int ret;
    if (!(flags & (ULOOP_READ | ULOOP_WRITE)))
        return uloop_fd_delete(sock);
    if (!sock->registered && !(flags & ULOOP_BLOCKING)) {
        fl = fcntl(sock->fd, F_GETFL, 0);
        fl |= O_NONBLOCK;
        fcntl(sock->fd, F_SETFL, fl);
    }
    ret = register_poll(sock, flags);
    if (ret < 0)
        goto out;
    if (uloop_fd_set_cb)
        uloop_fd_set_cb(sock, flags);
    sock->flags = flags;
    sock->registered = true;
    sock->eof = false;
    sock->error = false;
out:
    return ret;
}
References uloop_fd::eof, uloop_fd::error, uloop_fd::fd, uloop_fd::flags, register_poll(), uloop_fd::registered, ULOOP_BLOCKING, uloop_fd_delete(), uloop_fd_set_cb, ULOOP_READ, and ULOOP_WRITE.
Referenced by client_cb(), create_raw_event_socket(), get_next_connection(), hotplug(), init_bridge_ops(), jail_network_start(), main(), packet_sock_init(), run_server(), timer_register(), ubus_add_uloop(), ubus_init_hotplug(), ubus_msg_send(), udebug_add_uloop(), ul_ufd_add(), ustream_fd_set_uloop(), waker_init(), and wireless_device_run_handler().
uloop_fd_delete()
int uloop_fd_delete (struct uloop_fd * fd)
Definition at line 265 of file uloop.c.
{
    int ret;
    int i;
    for (i = 0; i < cur_nfds; i++) {
        if (cur_fds[cur_fd + i].fd != fd)
            continue;
        cur_fds[cur_fd + i].fd = NULL;
    }
    if (!fd->registered)
        return 0;
    if (uloop_fd_set_cb)
        uloop_fd_set_cb(fd, 0);
    fd->registered = false;
    uloop_fd_stack_event(fd, -1);
    ret = __uloop_fd_delete(fd);
    fd->flags = 0;
    return ret;
}
References __uloop_fd_delete(), cur_fd, cur_fds, cur_nfds, uloop_fd_event::fd, uloop_fd_stack::fd, uloop_fd::flags, uloop_fd::registered, uloop_fd_set_cb, and uloop_fd_stack_event().
Referenced by __udebug_disconnect(), handle_client_disconnect(), handle_hotplug_event(), handler_nl_event(), hotplug_shutdown(), packet_rcv(), run_netifd(), timer_register(), ubus_reconnect(), ubus_shutdown(), ul_ufd_delete(), uloop_done(), uloop_fd_add(), uloop_fetch_events(), uloop_fetch_events(), ustream_fd_free(), and wireless_close_script_proc_fd().
uloop_fd_stack_event()
static bool uloop_fd_stack_event (struct uloop_fd * fd, int events) static
Definition at line 165 of file uloop.c.
{
    struct uloop_fd_stack *cur;
    /*
     * Do not buffer events for level-triggered fds, they will keep firing.
     * Caller needs to take care of recursion issues.
     */
    if (!(fd->flags & ULOOP_EDGE_TRIGGER))
        return false;
    for (cur = fd_stack; cur; cur = cur->next) {
        if (cur->fd != fd)
            continue;
        if (events < 0)
            cur->fd = NULL;
        else
            cur->events |= events | ULOOP_EVENT_BUFFERED;
        return true;
    }
    return false;
}
References events, uloop_fd_stack::events, uloop_fd_stack::fd, fd_stack, uloop_fd::flags, uloop_fd_stack::next, ULOOP_EDGE_TRIGGER, and ULOOP_EVENT_BUFFERED.
Referenced by uloop_fd_delete(), and uloop_run_events().
uloop_get_next_timeout()
int uloop_get_next_timeout (void)
Definition at line 595 of file uloop.c.
{
    struct uloop_timeout *timeout;
    struct timeval tv;
    int64_t diff;
    if (list_empty(&timeouts))
        return -1;
    uloop_gettime(&tv);
    timeout = list_first_entry(&timeouts, struct uloop_timeout, list);
    diff = tv_diff(&timeout->time, &tv);
    if (diff < 0)
        return 0;
    if (diff > INT_MAX)
        return INT_MAX;
    return diff;
}
References list_empty(), list_first_entry, timeout, timeouts, tv_diff(), and uloop_gettime().
Referenced by uloop_run_timeout().
uloop_gettime()
static void uloop_gettime (struct timeval * tv) static
Definition at line 319 of file uloop.c.
{
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    tv->tv_sec = ts.tv_sec;
    tv->tv_usec = ts.tv_nsec / 1000;
}
Referenced by uloop_get_next_timeout(), uloop_process_timeouts(), uloop_timeout_remaining(), uloop_timeout_remaining64(), and uloop_timeout_set().
uloop_handle_processes()
static void uloop_handle_processes (void) static
Definition at line 423 of file uloop.c.
{
    struct uloop_process *p, *tmp;
    pid_t pid;
    int ret;
    do_sigchld = false;
    while (1) {
        pid = waitpid(-1, &ret, WNOHANG);
        if (pid < 0 && errno == EINTR)
            continue;
        if (pid <= 0)
            return;
        list_for_each_entry_safe(p, tmp, &processes, list) {
            if (p->pid < pid)
                continue;
            if (p->pid > pid)
                break;
            uloop_process_delete(p);
            p->cb(p, ret);
        }
    }
}
References uloop_process::cb, do_sigchld, uloop_process::list, list_for_each_entry_safe, uloop_process::pid, processes, and uloop_process_delete().
Referenced by uloop_run_timeout().
uloop_handle_sigint()
static void uloop_handle_sigint (int signo) static
Definition at line 484 of file uloop.c.
{
    uloop_status = signo;
    uloop_cancelled = true;
    uloop_signal_wake(signo);
}
References uloop_cancelled, uloop_signal_wake(), and uloop_status.
Referenced by uloop_setup_signals().
uloop_ignore_signal()
static void uloop_ignore_signal (int signum, bool ignore) static
Definition at line 515 of file uloop.c.
{
    struct sigaction s;
    void *new_handler = NULL;
    sigaction(signum, NULL, &s);
    if (ignore) {
        if (s.sa_handler == SIG_DFL) /* Ignore only if there isn't any custom handler */
            new_handler = SIG_IGN;
    } else {
        if (s.sa_handler == SIG_IGN) /* Restore only if noone modified our SIG_IGN */
            new_handler = SIG_DFL;
    }
    if (new_handler) {
        s.sa_handler = new_handler;
        s.sa_flags = 0;
        sigaction(signum, &s, NULL);
    }
}
References ignore.
Referenced by uloop_setup_signals().
uloop_init()
int uloop_init (void)
Definition at line 150 of file uloop.c.
{
    if (uloop_init_pollfd() < 0)
        return -1;
    if (waker_init() < 0) {
        uloop_done();
        return -1;
    }
    uloop_setup_signals(true);
    return 0;
}
References uloop_done(), uloop_init_pollfd(), uloop_setup_signals(), and waker_init().
Referenced by do_listen(), exec_jail(), hotplug_run(), main(), main(), main(), run_server(), ubus_cli_monitor(), ubus_cli_wait_for(), ubus_connect_ctx(), ul_init(), and uxc_attach().
uloop_install_handler()
static void uloop_install_handler (int signum, void(* handler)(int), struct sigaction * old, bool add) static
Definition at line 491 of file uloop.c.
{
    struct sigaction s;
    struct sigaction *act;
    act = NULL;
    sigaction(signum, NULL, &s);
    if (add) {
        if (s.sa_handler == SIG_DFL) { /* Do not override existing custom signal handlers */
            memcpy(old, &s, sizeof(struct sigaction));
            s.sa_handler = handler;
            s.sa_flags = 0;
            act = &s;
        }
    }
    else if (s.sa_handler == handler) { /* Do not restore if someone modified our handler */
            act = old;
    }
    if (act != NULL)
        sigaction(signum, act, NULL);
}
Referenced by uloop_setup_signals().
uloop_interval_cancel()
int uloop_interval_cancel (struct uloop_interval * timer)
Definition at line 458 of file uloop.c.
{
    return timer_remove(timer);
}
References timer_remove().
Referenced by ul_interval_free().
uloop_interval_remaining()
int64_t uloop_interval_remaining (struct uloop_interval * timer)
Definition at line 463 of file uloop.c.
{
    return timer_next(timer);
}
References timer_next().
Referenced by ul_interval_remaining().
uloop_interval_set()
int uloop_interval_set (struct uloop_interval * timer, unsigned int msecs)
Definition at line 453 of file uloop.c.
{
    return timer_register(timer, msecs);
}
References timer_register().
Referenced by ul_interval(), and ul_interval_set().
uloop_process_add()
int uloop_process_add (struct uloop_process * p)
Definition at line 391 of file uloop.c.
{
    struct uloop_process *tmp;
    struct list_head *h = &processes;
    if (p->pending)
        return -1;
    list_for_each_entry(tmp, &processes, list) {
        if (tmp->pid > p->pid) {
            h = &tmp->list;
            break;
        }
    }
    list_add_tail(&p->list, h);
    p->pending = true;
    return 0;
}
References uloop_process::list, list_add_tail(), list_for_each_entry, uloop_process::pending, uloop_process::pid, and processes.
Referenced by fork_worker(), hotplug_exec(), instance_start(), main(), netifd_start_process(), post_main(), preinit(), procd_coldplug(), queue_next(), rc_init(), rc_list_exec(), rpc_exec(), rpc_file_exec_run(), run_cmd(), run_hooklist(), runqueue_process_add(), sysupgrade(), tracer_cb(), and ul_process().
uloop_process_delete()
int uloop_process_delete (struct uloop_process * p)
Definition at line 412 of file uloop.c.
{
    if (!p->pending)
        return -1;
    list_del(&p->list);
    p->pending = false;
    return 0;
}
References uloop_process::list, list_del(), and uloop_process::pending.
Referenced by instance_free(), netifd_kill_process(), rc_list_exec(), rpc_exec_reply(), rpc_file_exec_reply(), rpc_list_exec_timeout_cb(), runqueue_process_kill_cb(), ul_process_free(), uloop_clear_processes(), and uloop_handle_processes().
uloop_process_timeouts()
static void uloop_process_timeouts (void) static
Definition at line 616 of file uloop.c.
{
    struct uloop_timeout *t;
    struct timeval tv;
    if (list_empty(&timeouts))
        return;
    uloop_gettime(&tv);
    while (!list_empty(&timeouts)) {
        t = list_first_entry(&timeouts, struct uloop_timeout, list);
        if (tv_diff(&t->time, &tv) > 0)
            break;
        uloop_timeout_cancel(t);
        if (t->cb)
            t->cb(t);
    }
}
References uloop_timeout::cb, list_empty(), list_first_entry, uloop_timeout::time, timeouts, tv_diff(), uloop_gettime(), and uloop_timeout_cancel().
Referenced by uloop_run_timeout().
uloop_run_events()
static void uloop_run_events (int64_t timeout) static
Definition at line 191 of file uloop.c.
{
    struct uloop_fd_event *cur;
    struct uloop_fd *fd;
    if (!cur_nfds) {
        cur_fd = 0;
        cur_nfds = uloop_fetch_events(timeout);
        if (cur_nfds < 0)
            cur_nfds = 0;
    }
    while (cur_nfds > 0) {
        struct uloop_fd_stack stack_cur;
        unsigned int events;
        cur = &cur_fds[cur_fd++];
        cur_nfds--;
        fd = cur->fd;
        events = cur->events;
        if (!fd)
            continue;
        if (!fd->cb)
            continue;
        if (uloop_fd_stack_event(fd, cur->events))
            continue;
        stack_cur.next = fd_stack;
        stack_cur.fd = fd;
        fd_stack = &stack_cur;
        do {
            stack_cur.events = 0;
            fd->cb(fd, events);
            events = stack_cur.events & ULOOP_EVENT_MASK;
        } while (stack_cur.fd && events);
        fd_stack = stack_cur.next;
        return;
    }
}
References uloop_fd::cb, cur_fd, cur_fds, cur_nfds, events, uloop_fd_event::events, uloop_fd_stack::events, uloop_fd::fd, uloop_fd_event::fd, uloop_fd_stack::fd, fd_stack, uloop_fd_stack::next, timeout, ULOOP_EVENT_MASK, uloop_fd_stack_event(), and uloop_fetch_events().
Referenced by uloop_run_timeout().
uloop_run_timeout()
int uloop_run_timeout (int timeout)
Definition at line 658 of file uloop.c.
{
    int next_time = 0;
    uloop_run_depth++;
    uloop_status = 0;
    uloop_cancelled = false;
    do {
        uloop_process_timeouts();
        if (do_sigchld)
            uloop_handle_processes();
        if (uloop_cancelled)
            break;
        next_time = uloop_get_next_timeout();
        if (timeout >= 0 && (next_time < 0 || timeout < next_time))
                next_time = timeout;
        uloop_run_events(next_time);
    } while (!uloop_cancelled && timeout < 0);
    --uloop_run_depth;
    return uloop_status;
}
References do_sigchld, timeout, uloop_cancelled, uloop_get_next_timeout(), uloop_handle_processes(), uloop_process_timeouts(), uloop_run_depth, uloop_run_events(), and uloop_status.
Referenced by uloop_run().
uloop_setup_signals()
static void uloop_setup_signals (bool add) static
Definition at line 537 of file uloop.c.
{
    static struct sigaction old_sigint, old_sigchld, old_sigterm;
    uloop_install_handler(SIGINT, uloop_handle_sigint, &old_sigint, add);
    uloop_install_handler(SIGTERM, uloop_handle_sigint, &old_sigterm, add);
    if (uloop_handle_sigchld)
        uloop_install_handler(SIGCHLD, uloop_signal_wake, &old_sigchld, add);
    uloop_ignore_signal(SIGPIPE, add);
}
References uloop_handle_sigchld, uloop_handle_sigint(), uloop_ignore_signal(), uloop_install_handler(), and uloop_signal_wake().
Referenced by uloop_done(), and uloop_init().
uloop_signal_add()
int uloop_signal_add (struct uloop_signal * s)
Definition at line 550 of file uloop.c.
{
    struct list_head *h = &signals;
    struct uloop_signal *tmp;
    struct sigaction sa;
    if (s->pending)
        return -1;
    list_for_each_entry(tmp, &signals, list) {
        if (tmp->signo > s->signo) {
            h = &tmp->list;
            break;
        }
    }
    list_add_tail(&s->list, h);
    s->pending = true;
    sigaction(s->signo, NULL, &s->orig);
    if (s->orig.sa_handler != uloop_signal_wake) {
        sa.sa_handler = uloop_signal_wake;
        sa.sa_flags = 0;
        sigemptyset(&sa.sa_mask);
        sigaction(s->signo, &sa, NULL);
    }
    return 0;
}
References uloop_signal::list, list_add_tail(), list_for_each_entry, uloop_signal::orig, uloop_signal::pending, signals, uloop_signal::signo, and uloop_signal_wake().
Referenced by ul_signal().
uloop_signal_delete()
int uloop_signal_delete (struct uloop_signal * s)
Definition at line 581 of file uloop.c.
{
    if (!s->pending)
        return -1;
    list_del(&s->list);
    s->pending = false;
    if (s->orig.sa_handler != uloop_signal_wake)
        sigaction(s->signo, &s->orig, NULL);
    return 0;
}
References uloop_signal::list, list_del(), uloop_signal::orig, uloop_signal::pending, uloop_signal::signo, and uloop_signal_wake().
Referenced by ul_signal_free().
uloop_signal_wake()
static void uloop_signal_wake (int signo) static
Definition at line 468 of file uloop.c.
{
    uint8_t sigbyte = signo;
    if (signo == SIGCHLD)
        do_sigchld = true;
    do {
        if (write(waker_pipe, &sigbyte, 1) < 0) {
            if (errno == EINTR)
                continue;
        }
        break;
    } while (1);
}
References do_sigchld, and waker_pipe.
Referenced by uloop_handle_sigint(), uloop_setup_signals(), uloop_signal_add(), and uloop_signal_delete().
uloop_timeout_add()
int uloop_timeout_add (struct uloop_timeout * timeout)
Definition at line 298 of file uloop.c.
{
    struct uloop_timeout *tmp;
    struct list_head *h = &timeouts;
    if (timeout->pending)
        return -1;
    list_for_each_entry(tmp, &timeouts, list) {
        if (tv_diff(&tmp->time, &timeout->time) > 0) {
            h = &tmp->list;
            break;
        }
    }
    list_add_tail(&timeout->list, h);
    timeout->pending = true;
    return 0;
}
References uloop_timeout::list, list_add_tail(), list_for_each_entry, uloop_timeout::time, timeout, timeouts, and tv_diff().
Referenced by add_sleeper(), config_watch_notify_cb(), exec_jail(), handle_start(), inotify_read_handler(), jail_network_start(), main(), and uloop_timeout_set().
uloop_timeout_cancel()
int uloop_timeout_cancel (struct uloop_timeout * timeout)
Definition at line 348 of file uloop.c.
{
    if (!timeout->pending)
        return -1;
    list_del(&timeout->list);
    timeout->pending = false;
    return 0;
}
References list_del(), and timeout.
Referenced by __bridge_reload(), bridge_free_member(), button_free(), hook_process_handler(), hotplug_last_event(), instance_exit(), instance_free(), interface_cleanup(), jail_process_handler(), proto_shell_free(), proto_shell_task_finish(), rc_list_exec_running_cb(), rpc_exec_reply(), rpc_file_exec_reply(), rpc_session_destroy(), rpc_uci_confirm(), rpc_uci_do_rollback(), rpc_ucode_request_gc(), runqueue_kill(), runqueue_task_complete(), service_handle_watchdog(), ubus_auto_shutdown(), ubus_shutdown(), udebug_free(), ul_timer_free(), uloop_clear_timeouts(), uloop_process_timeouts(), uloop_timeout_set(), ustream_free(), watchdog_set_stopped(), wireless_device_free_state(), and wireless_start_pending().
uloop_timeout_remaining()
int uloop_timeout_remaining (struct uloop_timeout * timeout)
Definition at line 359 of file uloop.c.
{
    int64_t td;
    struct timeval now;
    if (!timeout->pending)
        return -1;
    uloop_gettime(&now);
    td = tv_diff(&timeout->time, &now);
    if (td > INT_MAX)
        return INT_MAX;
    else if (td < INT_MIN)
        return INT_MIN;
    else
        return (int)td;
}
References timeout, tv_diff(), and uloop_gettime().
uloop_timeout_remaining64()
int64_t uloop_timeout_remaining64 (struct uloop_timeout * timeout)
Definition at line 379 of file uloop.c.
{
    struct timeval now;
    if (!timeout->pending)
        return -1;
    uloop_gettime(&now);
    return tv_diff(&timeout->time, &now);
}
References timeout, tv_diff(), and uloop_gettime().
Referenced by rpc_session_to_blob(), trigger_command_add(), and ul_timer_remaining().
uloop_timeout_set()
int uloop_timeout_set (struct uloop_timeout * timeout, int msecs)
Definition at line 328 of file uloop.c.
{
    struct timeval *time = &timeout->time;
    if (timeout->pending)
        uloop_timeout_cancel(timeout);
    uloop_gettime(time);
    time->tv_sec += msecs / 1000;
    time->tv_usec += (msecs % 1000) * 1000;
    if (time->tv_usec > 1000000) {
        time->tv_sec++;
        time->tv_usec -= 1000000;
    }
    return uloop_timeout_add(timeout);
}
References timeout, uloop_gettime(), uloop_timeout_add(), and uloop_timeout_cancel().
Referenced by __bridge_reload(), __runqueue_start_next(), __udebug_disconnect(), add_sleeper(), bonding_config_init(), bonding_set_up(), bridge_check_retry(), bridge_member_cb(), child_exit(), client_main(), device_free_unused(), do_listen(), extdev_bridge_check_retry(), handle_button_complete(), hotplug_call(), hotplug_done(), hotplug_last_event(), instance_exit(), instance_restart(), instance_start(), instance_stop(), interface_ip_init_worker(), interface_ip_valid_until_handler(), jail_handle_signal(), netifd_device_remove_cb(), netifd_iface_remove(), netifd_restart(), netifd_sub_cb(), netifd_ubus_reconnect_timer(), post_poststart(), proto_shell_handler(), proto_shell_task_finish(), rc_list_exec(), rpc_exec(), rpc_file_exec_run(), rpc_session_from_blob(), rpc_touch_session(), rpc_uci_apply(), rpc_ucode_script_call(), rule_handle_command(), run_hooklist(), runqueue_start_next(), runqueue_task_cancel(), service_handle_watchdog(), test_client_notify_cb(), test_count(), test_hello(), test_hello_fd_reply(), timeout_retry(), trigger_command_add(), ubus_auto_connect_cb(), ubus_auto_disconnect_cb(), ubus_auto_reconnect_cb(), ubus_cli_wait_for(), ubus_connect_handler(), ubus_queue_msg(), udebug_reconnect_cb(), ul_timer(), ul_timer_set(), ustream_state_change(), watchdog_timeout_cb(), wireless_device_add_process(), wireless_device_check_script_tasks(), wireless_device_setup_cancel(), wireless_proc_poll_fd(), wireless_start_pending(), worker_init(), and worker_timer_cb().
waker_init()
static int waker_init (void) static
Definition at line 127 of file uloop.c.
{
    int fds[2];
    if (waker_pipe >= 0)
        return 0;
    if (pipe(fds) < 0)
        return -1;
    waker_init_fd(fds[0]);
    waker_init_fd(fds[1]);
    waker_pipe = fds[1];
    waker_fd.fd = fds[0];
    waker_fd.cb = signal_consume;
    uloop_fd_add(&waker_fd, ULOOP_READ);
    return 0;
}
References uloop_fd::cb, uloop_fd::fd, signal_consume(), uloop_fd_add(), ULOOP_READ, waker_fd, waker_init_fd(), and waker_pipe.
Referenced by uloop_init().
waker_init_fd()
static void waker_init_fd (int fd) static
Definition at line 121 of file uloop.c.
{
    fcntl(fd, F_SETFD, fcntl(fd, F_GETFD) | FD_CLOEXEC);
    fcntl(fd, F_SETFL, fcntl(fd, F_GETFL) | O_NONBLOCK);
}
References uloop_fd::fd.
Referenced by waker_init().
Variable Documentation
cur_fd
int cur_fd static
Definition at line 69 of file uloop.c.
Referenced by uloop_fd_delete(), and uloop_run_events().
cur_fds
struct uloop_fd_event cur_fds[ULOOP_MAX_EVENTS] static
Definition at line 68 of file uloop.c.
Referenced by uloop_fd_delete(), uloop_fetch_events(), uloop_fetch_events(), and uloop_run_events().
cur_nfds
int cur_nfds static
Definition at line 69 of file uloop.c.
Referenced by uloop_fd_delete(), and uloop_run_events().
do_sigchld
bool do_sigchld = false static
Definition at line 66 of file uloop.c.
Referenced by uloop_handle_processes(), uloop_run_timeout(), and uloop_signal_wake().
fd_stack
struct uloop_fd_stack* fd_stack = NULL static
Definition at line 54 of file uloop.c.
Referenced by uloop_fd_stack_event(), and uloop_run_events().
poll_fd
int poll_fd = -1 static
Definition at line 62 of file uloop.c.
Referenced by __uloop_fd_delete(), register_kevent(), register_poll(), timer_register(), timer_remove(), uloop_done(), uloop_fetch_events(), uloop_fetch_events(), uloop_init_pollfd(), and uloop_init_pollfd().
processes
struct list_head processes = LIST_HEAD_INIT(processes) static
Definition at line 59 of file uloop.c.
Referenced by uloop_clear_processes(), uloop_handle_processes(), and uloop_process_add().
signals
struct list_head signals = LIST_HEAD_INIT(signals) static
Definition at line 60 of file uloop.c.
Referenced by signal_consume(), and uloop_signal_add().
timeouts
struct list_head timeouts = LIST_HEAD_INIT(timeouts) static
Definition at line 58 of file uloop.c.
Referenced by uloop_clear_timeouts(), uloop_get_next_timeout(), uloop_process_timeouts(), and uloop_timeout_add().
uloop_cancelled
bool uloop_cancelled = false
Definition at line 63 of file uloop.c.
Referenced by handle_signal(), uloop_cancelling(), uloop_end(), uloop_handle_sigint(), and uloop_run_timeout().
uloop_fd_set_cb
uloop_fd_handler uloop_fd_set_cb = NULL
Definition at line 72 of file uloop.c.
Referenced by uloop_fd_add(), and uloop_fd_delete().
uloop_handle_sigchld
bool uloop_handle_sigchld = true
Definition at line 64 of file uloop.c.
Referenced by uloop_setup_signals().
uloop_run_depth
int uloop_run_depth = 0 static
Definition at line 70 of file uloop.c.
Referenced by uloop_cancelling(), and uloop_run_timeout().
uloop_status
int uloop_status = 0 static
Definition at line 65 of file uloop.c.
Referenced by uloop_handle_sigint(), and uloop_run_timeout().
waker_fd
struct uloop_fd waker_fd static
Initial value:
= {
    .fd = -1,
    .cb = signal_consume,
}
Definition at line 116 of file uloop.c.
{
    .fd = -1,
    .cb = signal_consume,
};
Referenced by uloop_done(), and waker_init().
waker_pipe
int waker_pipe = -1 static
Definition at line 115 of file uloop.c.
Referenced by uloop_done(), uloop_signal_wake(), and waker_init().