zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/libubox/list.h File Reference
list.h File Reference
#include <stddef.h>
#include <stdbool.h>
Classes
struct list_head
Macros
#define prefetch(x)
#define container_of(ptr, type, member)
#define container_of_safe(ptr, type, member)
#define LIST_HEAD_INIT(name)
#define LIST_HEAD(name)
#define list_entry(ptr, type, field)
#define list_first_entry(ptr, type, field)
#define list_last_entry(ptr, type, field)
#define list_next_entry(pos, member)
#define list_entry_is_h(p, h, field)
#define list_for_each(p, head)
#define list_for_each_safe(p, n, head)
#define list_for_each_entry(p, h, field)
#define list_for_each_entry_continue(p, h, field)
#define list_for_each_entry_continue_reverse(p, h, field)
#define list_for_each_entry_safe(p, n, h, field)
#define list_for_each_entry_reverse(p, h, field)
#define list_for_each_prev(p, h)
#define list_for_each_prev_safe(p, n, h)
Functions
static void INIT_LIST_HEAD (struct list_head *list)
static bool list_empty (const struct list_head *head)
static bool list_is_first (const struct list_head *list, const struct list_head *head)
static bool list_is_last (const struct list_head *list, const struct list_head *head)
static void _list_del (struct list_head *entry)
static void list_del (struct list_head *entry)
static void _list_add (struct list_head *_new, struct list_head *prev, struct list_head *next)
static void list_del_init (struct list_head *entry)
static void list_add (struct list_head *_new, struct list_head *head)
static void list_add_tail (struct list_head *_new, struct list_head *head)
static void list_move (struct list_head *list, struct list_head *head)
static void list_move_tail (struct list_head *entry, struct list_head *head)
static void _list_splice (const struct list_head *list, struct list_head *prev, struct list_head *next)
static void list_splice (const struct list_head *list, struct list_head *head)
static void list_splice_tail (struct list_head *list, struct list_head *head)
static void list_splice_init (struct list_head *list, struct list_head *head)
static void list_splice_tail_init (struct list_head *list, struct list_head *head)
Class Documentation
list_head
struct list_head
Definition at line 53 of file list.h.
Class Members
struct list_head * next
struct list_head * prev
Macro Definition Documentation
container_of
#define container_of (ptr, type, member)
Value:
    ({                              \
        const __typeof__(((type *) NULL)->member) *__mptr = (ptr);  \
        (type *) ((char *) __mptr - offsetof(type, member));    \
    })
Definition at line 38 of file list.h.
#define container_of(ptr, type, member)                 \
    ({                              \
        const __typeof__(((type *) NULL)->member) *__mptr = (ptr);  \
        (type *) ((char *) __mptr - offsetof(type, member));    \
    })
Referenced by __bridge_create(), __create(), __interface_update_route(), __runqueue_cancel(), __runqueue_empty_cb(), __runqueue_proc_cb(), __runqueue_start_next(), __runqueue_task_timeout(), __vlan_hotplug_op(), __vlandev_hotplug_op(), alias_check_state(), alias_device_cb(), alias_device_free(), alias_device_set_state(), bonding_config_init(), bonding_free(), bonding_hotplug_add(), bonding_hotplug_del(), bonding_hotplug_prepare(), bonding_port_cb(), bonding_port_update(), bonding_reload(), bonding_retry_ports(), bonding_set_state(), bridge_config_init(), bridge_dependency_retry(), bridge_dev_vlan_update(), bridge_dump_info(), bridge_free(), bridge_hotplug_add(), bridge_hotplug_del(), bridge_hotplug_prepare(), bridge_member_cb(), bridge_member_check_cb(), bridge_member_update(), bridge_reload(), bridge_retry_members(), bridge_set_state(), bridge_stp_init(), bridge_vlan_update(), child_exit(), client_cb(), client_close(), client_notify_state(), client_read_cb(), device_broadcast_cb(), device_cleanup_cb(), device_release_cb(), dispatch_timer(), dump_cb(), extdev_bridge_member_cb(), extdev_bridge_member_update(), extdev_bridge_retry_enable_members(), extdev_bridge_set_state(), extdev_config_init(), extdev_create(), extdev_dump(), extdev_ext_handler_remove_cb(), extdev_free(), extdev_hotplug_add(), extdev_hotplug_prepare(), extdev_hotplug_remove(), extdev_reload(), extdev_wait_ev_cb(), free_vlan_if(), get_vlan_device(), handle_button_timeout(), handle_hotplug_event(), handler_nl_event(), hotplug_done(), hotplug_exec(), instance_console(), instance_console_client(), instance_exit(), instance_file_cmp(), instance_file_update(), instance_netdev_cmp(), instance_netdev_update(), instance_stderr(), instance_stdout(), instance_timeout(), instance_watchdog(), interface_alias_cb(), interface_l3_dev_cb(), interface_main_dev_cb(), interface_update(), interface_update_host_route(), interface_update_prefix(), interface_update_proto_addr(), interface_update_proto_neighbor(), interface_update_proto_route(), iprule_update_rule(), macvlan_base_cb(), macvlan_config_init(), macvlan_dump_info(), macvlan_free(), macvlan_reload(), macvlan_set_state(), my_runqueue_process_kill_cb(), netifd_handle_down(), netifd_handle_iface_prepare(), netifd_handle_renew(), netifd_handle_set_data(), netifd_handle_status(), netifd_handle_up(), netifd_iface_do_remove(), netifd_iface_handle_device(), netifd_iface_notify_proto(), netifd_iface_remove(), netifd_process_cb(), netifd_process_log_read_cb(), pipe_cb(), proto_shell_attach(), proto_shell_checkup_timeout_cb(), proto_shell_free(), proto_shell_handler(), proto_shell_if_down_cb(), proto_shell_if_up_cb(), proto_shell_notify(), proto_shell_script_cb(), proto_shell_task_cb(), proto_shell_teardown_timeout_cb(), q_initd_complete(), q_initd_run(), q_sleep_cancel(), q_sleep_complete(), q_sleep_run(), rc_init_cb(), rc_list_exec_running_cb(), respawn(), rpc_exec_epipe_read_cb(), rpc_exec_epipe_state_cb(), rpc_exec_ipipe_write_cb(), rpc_exec_opipe_read_cb(), rpc_exec_opipe_state_cb(), rpc_exec_process_cb(), rpc_exec_timeout_cb(), rpc_file_exec_epipe_read_cb(), rpc_file_exec_epipe_state_cb(), rpc_file_exec_opipe_read_cb(), rpc_file_exec_opipe_state_cb(), rpc_file_exec_process_cb(), rpc_file_exec_timeout_cb(), rpc_list_exec_timeout_cb(), rpc_session_timeout(), rpc_ucode_obj_to_script(), rpc_ucode_obj_to_signature(), rpc_ucode_request_timeout(), rule_handle_command(), rule_in_cb(), rule_load_script(), rule_out_cb(), runqueue_process_cancel_cb(), runqueue_process_kill_cb(), service_instance_update(), static_free(), static_handler(), station_update(), test_hello_fd_reply(), test_hello_reply(), timer_cb(), tracer_cb(), trigger_command_complete(), trigger_command_run(), trigger_command_start(), tunnel_free(), tunnel_set_state(), ubus_auto_connect_cb(), ubus_auto_disconnect_cb(), ubus_auto_reconnect_cb(), ubus_cli_listen_timeout(), ubus_event_cb(), ubus_event_handler(), ubus_find_id(), ubus_find_request(), ubus_get_obj_type(), ubus_handle_data(), ubus_lookup_cb(), ubus_method_handler(), ubus_new_sub_cb(), ubus_notify_complete_cb(), ubus_notify_data_cb(), ubus_process_notify_status(), ubus_process_pending_msg(), ubus_process_unsubscribe(), ubus_sub_notify_handler(), ubus_sub_remove_handler(), ubus_subscriber_cb(), ubusd_acl_update_cb(), ubusd_find_object(), ubusd_get_client_by_id(), ubusd_handle_invoke(), ubusd_handle_notify(), udebug_fd_cb(), udebug_reconnect_cb(), ul_interval_cb(), ul_process_cb(), ul_signal_cb(), ul_timer_cb(), ul_ufd_cb(), ustream_fd_free(), ustream_fd_poll(), ustream_fd_set_uloop(), ustream_fd_write(), ustream_state_change_cb(), ustream_uloop_cb(), veth_dump_info(), veth_free(), veth_reload(), veth_set_state(), vif_update(), vlan_config_init(), vlan_dev_cb(), vlan_hotplug_prepare(), vlan_set_device_state(), vlan_update(), vlandev_base_cb(), vlandev_config_init(), vlandev_dump_info(), vlandev_free(), vlandev_hotplug_prepare(), vlandev_reload(), vlandev_set_state(), vlist_add(), wait_event_cb(), wdev_update(), wireless_device_check_script_tasks(), wireless_device_script_task_cb(), wireless_device_setup_timeout(), and wireless_proc_poll_fd().
container_of_safe
#define container_of_safe (ptr, type, member)
Value:
    ({                                      \
        const __typeof__(((type *) NULL)->member) *__mptr = (ptr);      \
        __mptr ? (type *)((char *) __mptr - offsetof(type, member)) : NULL; \
    })
Definition at line 46 of file list.h.
#define container_of_safe(ptr, type, member)                        \
    ({                                      \
        const __typeof__(((type *) NULL)->member) *__mptr = (ptr);      \
        __mptr ? (type *)((char *) __mptr - offsetof(type, member)) : NULL; \
    })
Referenced by station_update(), and vlan_update().
list_entry
#define list_entry (ptr, type, field)
Value:
container_of(ptr, type, field)
Definition at line 120 of file list.h.
Referenced by __safe_list_set_iterator(), avl_next(), safe_list_del(), and safe_list_for_each().
list_entry_is_h
#define list_entry_is_h (p, h, field)
Value:
(&p->field == (h))
Definition at line 124 of file list.h.
list_first_entry
#define list_first_entry (ptr, type, field)
Value:
list_entry((ptr)->next, type, field)
Definition at line 121 of file list.h.
Referenced by __runqueue_start_next(), call_hotplug(), device_replace(), interface_clear_assignment_classes(), interface_merge_assignment_data(), interface_update_prefix_assignments(), queue_next(), runqueue_kill(), test_basics(), test_while_list_empty(), ubus_process_pending_msg(), udebug_free(), uloop_get_next_timeout(), uloop_process_timeouts(), wireless_handler_next(), and worker_next_event().
list_for_each
#define list_for_each (p, head)
Value:
    for (p = (head)->next; p != (head); p = p->next)
Definition at line 126 of file list.h.
#define list_for_each(p, head)                      \
    for (p = (head)->next; p != (head); p = p->next)
Referenced by device_refcount().
list_for_each_entry
#define list_for_each_entry (p, h, field)
Value:
    for (p = list_first_entry(h, __typeof__(*p), field); &p->field != (h); \
        p = list_entry(p->field.next, __typeof__(*p), field))
Definition at line 132 of file list.h.
#define list_for_each_entry(p, h, field)                \
    for (p = list_first_entry(h, __typeof__(*p), field); &p->field != (h); \
        p = list_entry(p->field.next, __typeof__(*p), field))
Referenced by __attribute__(), bridge_bpdu_rcv(), bridge_create(), bridge_dump_vlan(), bridge_find_vlan_member_port(), bridge_hotplug_get_vlan_port(), bridge_one_second(), bridge_track_fini(), bridge_vlan_check_attr(), cert_dump(), device_type_get(), find_br(), find_if(), get_vlan_device(), interface_ip_dump_prefix_assignment_list(), interface_ip_dump_prefix_list(), interface_ip_set_enabled(), interface_merge_assignment_data(), interface_prefix_assign(), interface_refresh_assignments(), interface_update_prefix(), interface_update_prefix_assignments(), lib_open(), main(), netifd_add_interface_errors(), parseOCIlinuxcgroups_devices(), parseOCImountopts(), procd_inittab_kill(), procd_inittab_run(), proto_shell_check_dependencies(), rpc_session_create(), rpc_session_destroy(), service_validate_dump(), system_bridge_vlan_check(), test_basics(), trigger_event(), ubus_auto_sub_event_handler_cb(), ubus_auto_sub_lookup(), ubus_find_request(), ubusd_handle_notify(), ubusd_handle_remove_watch(), ubusd_monitor_message(), ubusd_reply_query(), ubusd_send_obj(), udebug_connect(), uloop_process_add(), uloop_signal_add(), uloop_timeout_add(), and watch_subscribe_cb().
list_for_each_entry_continue
#define list_for_each_entry_continue (p, h, field)
Value:
    for (p = list_next_entry(p, field);             \
         !list_entry_is_h(p, h, field);             \
         p = list_next_entry(p, field))
Definition at line 136 of file list.h.
#define list_for_each_entry_continue(p, h, field)           \
    for (p = list_next_entry(p, field);             \
         !list_entry_is_h(p, h, field);             \
         p = list_next_entry(p, field))
Referenced by PTSM_run(), PTSM_to_TRANSMIT_PERIODIC(), recordAgreement(), recordDispute(), recordMastered(), recordProposal(), reselectMSTIs(), setRcvdMsgs(), setTcFlags(), syncMaster(), and txMstp().
list_for_each_entry_continue_reverse
#define list_for_each_entry_continue_reverse (p, h, field)
Value:
    for (p = list_prev_entry(p, field);             \
         !list_entry_is_h(p, h, field);             \
         p = list_prev_entry(p, field))
Definition at line 141 of file list.h.
#define list_for_each_entry_continue_reverse(p, h, field)       \
    for (p = list_prev_entry(p, field);             \
         !list_entry_is_h(p, h, field);             \
         p = list_prev_entry(p, field))
list_for_each_entry_reverse
#define list_for_each_entry_reverse (p, h, field)
Value:
    for (p = list_last_entry(h, __typeof__(*p), field); &p->field != (h); \
        p = list_entry(p->field.prev, __typeof__(*p), field))
Definition at line 151 of file list.h.
#define list_for_each_entry_reverse(p, h, field)            \
    for (p = list_last_entry(h, __typeof__(*p), field); &p->field != (h); \
        p = list_entry(p->field.prev, __typeof__(*p), field))
Referenced by test_basics().
list_for_each_entry_safe
#define list_for_each_entry_safe (p, n, h, field)
Value:
    for (p = list_first_entry(h, __typeof__(*p), field),        \
        n = list_entry(p->field.next, __typeof__(*p), field); &p->field != (h);\
        p = n, n = list_entry(n->field.next, __typeof__(*n), field))
Definition at line 146 of file list.h.
#define list_for_each_entry_safe(p, n, h, field)            \
    for (p = list_first_entry(h, __typeof__(*p), field),        \
        n = list_entry(p->field.next, __typeof__(*p), field); &p->field != (h);\
        p = n, n = list_entry(n->field.next, __typeof__(*n), field))
Referenced by __ubus_process_req_data(), bridge_create(), bridge_free_member(), bridge_vlan_free(), button_timeout_remove(), client_cb(), flush_exceptions(), free_library_search(), handle_client_disconnect(), interface_cleanup(), interface_error_flush(), interface_event(), main(), MSTP_IN_create_msti(), MSTP_IN_delete_bridge(), MSTP_IN_delete_msti(), MSTP_IN_delete_port(), MSTP_IN_port_create_and_add_tail(), netifd_kill_processes(), parseOCImountopts(), proto_shell_clear_host_dep(), remove_subsystem(), service_validate_del(), signal_consume(), test_basics(), trigger_del(), ubus_client_cmd_queue_process(), ubus_unref_object_type(), ubusd_acl_file_free(), ubusd_event_cleanup_object(), ubusd_free_object(), ubusd_monitor_find(), ubusd_proto_free_client(), uloop_clear_processes(), uloop_clear_timeouts(), uloop_handle_processes(), vlist_simple_flush(), vlist_simple_replace(), watch_del(), wireless_device_check_script_tasks(), and wireless_process_kill_all().
list_for_each_prev
#define list_for_each_prev (p, h)
Value:
for (p = (h)->prev; p != (h); p = p->prev)
Definition at line 155 of file list.h.
list_for_each_prev_safe
#define list_for_each_prev_safe (p, n, h)
Value:
for (p = (h)->prev, n = p->prev; p != (h); p = n, n = p->prev)
Definition at line 156 of file list.h.
list_for_each_safe
#define list_for_each_safe (p, n, head)
Value:
    for (p = (head)->next, n = p->next; p != (head); p = n, n = p->next)
Definition at line 129 of file list.h.
#define list_for_each_safe(p, n, head)                  \
    for (p = (head)->next, n = p->next; p != (head); p = n, n = p->next)
LIST_HEAD
#define LIST_HEAD (name)
Value:
struct list_head name = LIST_HEAD_INIT(name)
Definition at line 60 of file list.h.
Referenced by cert_dump().
LIST_HEAD_INIT
#define LIST_HEAD_INIT (name)
Value:
{ &(name), &(name) }
Definition at line 58 of file list.h.
Referenced by main(), parseOCImountopts(), test_basics(), and test_while_list_empty().
list_last_entry
#define list_last_entry (ptr, type, field)
Value:
list_entry((ptr)->prev, type, field)
Definition at line 122 of file list.h.
Referenced by test_basics().
list_next_entry
#define list_next_entry (pos, member)
Value:
list_entry((pos)->member.next, typeof(*(pos)), member)
Definition at line 123 of file list.h.
prefetch
#define prefetch (x)
Definition at line 35 of file list.h.
Function Documentation
_list_add()
static void _list_add (struct list_head * _new, struct list_head * prev, struct list_head * next) inline static
Definition at line 103 of file list.h.
{
    next->prev = _new;
    _new->next = next;
    _new->prev = prev;
    prev->next = _new;
}
References list_head::next, and list_head::prev.
Referenced by list_add(), and list_add_tail().
_list_del()
static void _list_del (struct list_head * entry) inline static
Definition at line 89 of file list.h.
{
    entry->next->prev = entry->prev;
    entry->prev->next = entry->next;
}
References list_head::next, and list_head::prev.
Referenced by list_del(), list_del_init(), list_move(), and list_move_tail().
_list_splice()
static void _list_splice (const struct list_head * list, struct list_head * prev, struct list_head * next) inline static
Definition at line 185 of file list.h.
{
    struct list_head *first;
    struct list_head *last;
    if (list_empty(list))
        return;
    first = list->next;
    last = list->prev;
    first->prev = prev;
    prev->next = first;
    last->next = next;
    next->prev = last;
}
References list_empty(), list_head::next, and list_head::prev.
Referenced by list_splice(), list_splice_init(), list_splice_tail(), and list_splice_tail_init().
INIT_LIST_HEAD()
static void INIT_LIST_HEAD (struct list_head * list) inline static
Definition at line 63 of file list.h.
{
    list->next = list->prev = list;
}
References list_head::next, and list_head::prev.
Referenced by __ubus_start_request(), __vlist_simple_init(), avl_init(), bridge_hotplug_get_vlan(), config_parse_vlan(), create_tree(), interface_alloc(), interface_ip_add_device_prefix(), list_del_init(), list_splice_init(), list_splice_tail_init(), MSTP_IN_bridge_create(), MSTP_IN_port_create_and_add_tail(), parseOCIlinuxcgroups_devices(), proto_shell_attach(), service_alloc(), ubus_connect_ctx(), ubus_create_obj_type(), ubus_msg_enqueue(), ubus_register_subscriber(), ubusd_acl_load_file(), ubusd_create_object_internal(), ubusd_proto_new_client(), udebug_buf_init(), udebug_buf_open(), udebug_init(), and wireless_device_create().
list_add()
static void list_add (struct list_head * _new, struct list_head * head) inline static
Definition at line 159 of file list.h.
{
    _list_add(_new, head, head->next);
}
References _list_add(), and list_head::next.
Referenced by _trigger_add(), add_default_exceptions(), add_subsystem(), avl_insert(), avl_insert_after(), device_type_add(), handle_button_complete(), interface_add_assignment_classes(), interface_add_user(), interface_update_prefix(), interface_update_prefix_assignments(), interface_update_prefix_delegation(), list_move(), MSTP_IN_create_msti(), parseOCIlinuxcgroups_devices(), proto_shell_add_host_dependency(), rpc_plugin_register_library(), rpc_session_create_cb(), rpc_session_destroy_cb(), rpc_ucode_init_script(), rpc_ucode_script_register(), safe_list_add_first(), service_validate_add(), ubus_complete_request_async(), ubus_process_req_data(), ubus_register_subscriber(), ubus_subscribe(), ubusd_acl_alloc_obj(), ubusd_alloc_event_pattern(), ubusd_create_object(), watch_add(), and wireless_device_add_process().
list_add_tail()
static void list_add_tail (struct list_head * _new, struct list_head * head) inline static
Definition at line 165 of file list.h.
{
    _list_add(_new, head->prev, head);
}
References _list_add(), and list_head::prev.
Referenced by add_action(), alloc_library_path(), avl_insert_before(), bridge_hotplug_set_member_vlans(), cert_load(), create_br(), init_list(), interface_add_error(), interface_prefix_assign(), interface_queue_event(), list_move_tail(), main(), MSTP_IN_bridge_create(), MSTP_IN_create_msti(), MSTP_IN_port_create_and_add_tail(), netifd_start_process(), parseOCImountopts(), queue_add(), safe_list_add(), ubus_client_cmd_queue_add(), ubus_create_obj_method(), ubus_msg_enqueue(), ubus_queue_msg(), ubusd_monitor_connect(), udebug_buf_add(), uloop_process_add(), uloop_signal_add(), uloop_timeout_add(), vlist_simple_add(), wireless_device_run_handler(), and worker_queue_event().
list_del()
static void list_del (struct list_head * entry) inline static
Definition at line 96 of file list.h.
{
    _list_del(entry);
    entry->next = entry->prev = NULL;
}
References _list_del(), list_head::next, and list_head::prev.
Referenced by __ubus_process_req_data(), avl_remove(), bridge_free_member(), bridge_hotplug_set_member_vlans(), button_free(), delete_br_byindex(), flush_exceptions(), interface_clear_assignment_classes(), interface_error_flush(), interface_merge_assignment_data(), interface_update_prefix(), interface_update_prefix_assignments(), interface_update_prefix_delegation(), main(), MSTP_IN_create_msti(), MSTP_IN_delete_bridge(), MSTP_IN_delete_msti(), MSTP_IN_delete_port(), MSTP_IN_port_create_and_add_tail(), netifd_delete_process(), parseOCImountopts(), proto_shell_clear_host_dep(), queue_next(), remove_subsystem(), safe_list_del(), service_validate_del(), test_basics(), test_while_list_empty(), trigger_free(), ubus_client_cmd_free(), ubus_process_pending_msg(), ubus_unref_object_type(), ubus_unsubscribe(), ubusd_acl_file_free(), ubusd_delete_event_source(), ubusd_free_object(), ubusd_monitor_free(), udebug_buf_free(), uloop_process_delete(), uloop_signal_delete(), uloop_timeout_cancel(), vlist_simple_delete(), vlist_simple_replace(), watch_del(), wireless_device_setup_timeout(), wireless_handler_next(), wireless_handler_stop(), wireless_process_free(), and worker_next_event().
list_del_init()
static void list_del_init (struct list_head * entry) inline static
Definition at line 114 of file list.h.
{
    _list_del(entry);
    INIT_LIST_HEAD(entry);
}
References _list_del(), and INIT_LIST_HEAD().
Referenced by call_hotplug(), interface_dequeue_event(), interface_remove_user(), ubus_abort_request(), ubus_msg_list_free(), ubus_set_req_status(), and ubus_unregister_subscriber().
list_empty()
static bool list_empty (const struct list_head * head) inline static
Definition at line 69 of file list.h.
{
    return (head->next == head);
}
References list_head::next.
Referenced by __runqueue_start_next(), __ubusd_handle_lookup(), _list_splice(), bridge_free_member(), button_timeout_remove(), call_hotplug(), client_cb(), device_replace(), flush_exceptions(), init_list(), interface_clear_assignment_classes(), interface_dequeue_event(), interface_merge_assignment_data(), interface_queue_event(), interface_update_prefix_assignments(), main(), netifd_dump_status(), queue_next(), runqueue_kill(), safe_list_empty(), service_dump(), service_validate_del(), test_basics(), test_while_list_empty(), ubus_abort_request(), ubus_complete_request_async(), ubus_msg_send(), ubus_notify_subscription(), ubus_process_pending_msg(), ubus_refresh_auto_subscribe(), ubus_set_req_status(), ubus_subscribe(), ubus_unregister_subscriber(), ubus_unsubscribe(), ubusd_free_object(), ubusd_handle_lookup(), ubusd_monitor_message(), udebug_buf_free(), udebug_free(), uloop_get_next_timeout(), uloop_process_timeouts(), wireless_device_process_kill_all(), wireless_handler_next(), wireless_process_free(), and worker_next_event().
list_is_first()
static bool list_is_first (const struct list_head * list, const struct list_head * head) inline static
Definition at line 75 of file list.h.
{
    return list->prev == head;
}
References list_head::prev.
Referenced by avl_find_greaterequal(), avl_find_lessequal(), and test_basics().
list_is_last()
static bool list_is_last (const struct list_head * list, const struct list_head * head) inline static
Definition at line 82 of file list.h.
{
    return list->next == head;
}
References list_head::next.
Referenced by avl_delete(), avl_find_greaterequal(), avl_find_lessequal(), avl_insert(), and test_basics().
list_move()
static void list_move (struct list_head * list, struct list_head * head) inline static
Definition at line 171 of file list.h.
{
    _list_del(list);
    list_add(list, head);
}
References _list_del(), and list_add().
list_move_tail()
static void list_move_tail (struct list_head * entry, struct list_head * head) inline static
Definition at line 178 of file list.h.
{
    _list_del(entry);
    list_add_tail(entry, head);
}
References _list_del(), and list_add_tail().
Referenced by test_basics().
list_splice()
static void list_splice (const struct list_head * list, struct list_head * head) inline static
Definition at line 203 of file list.h.
{
    _list_splice(list, head, head->next);
}
References _list_splice(), and list_head::next.
Referenced by interface_update_prefix().
list_splice_init()
static void list_splice_init (struct list_head * list, struct list_head * head) inline static
Definition at line 215 of file list.h.
{
    _list_splice(list, head, head->next);
    INIT_LIST_HEAD(list);
}
References _list_splice(), INIT_LIST_HEAD(), and list_head::next.
Referenced by bridge_vlan_update(), and interface_merge_assignment_data().
list_splice_tail()
static void list_splice_tail (struct list_head * list, struct list_head * head) inline static
Definition at line 209 of file list.h.
{
    _list_splice(list, head->prev, head);
}
References _list_splice(), and list_head::prev.
list_splice_tail_init()
static void list_splice_tail_init (struct list_head * list, struct list_head * head) inline static
Definition at line 222 of file list.h.
{
    _list_splice(list, head->prev, head);
    INIT_LIST_HEAD(list);
}
References _list_splice(), INIT_LIST_HEAD(), and list_head::prev.