zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/libubox/uloop-epoll.c File Reference
uloop-epoll.c File Reference
Macros
#define EPOLLRDHUP 0x2000
Functions
static int uloop_init_pollfd (void)
static int register_poll (struct uloop_fd *fd, unsigned int flags)
static int __uloop_fd_delete (struct uloop_fd *sock)
static int uloop_fetch_events (int timeout)
static void dispatch_timer (struct uloop_fd *u, unsigned int events)
static int timer_register (struct uloop_interval *tm, unsigned int msecs)
static int timer_remove (struct uloop_interval *tm)
static int64_t timer_next (struct uloop_interval *tm)
Variables
static struct epoll_event events [ULOOP_MAX_EVENTS]
Macro Definition Documentation
EPOLLRDHUP
#define EPOLLRDHUP 0x2000
FIXME: uClibc < 0.9.30.3 does not define EPOLLRDHUP for Linux >= 2.6.17
Definition at line 23 of file uloop-epoll.c.
Referenced by register_poll(), and uloop_fetch_events().
Function Documentation
__uloop_fd_delete()
static int __uloop_fd_delete (struct uloop_fd * sock) static
Definition at line 62 of file uloop-epoll.c.
{
    sock->flags = 0;
    return epoll_ctl(poll_fd, EPOLL_CTL_DEL, sock->fd, 0);
}
References uloop_fd::fd, uloop_fd::flags, and poll_fd.
Referenced by timer_remove(), and uloop_fd_delete().
dispatch_timer()
static void dispatch_timer (struct uloop_fd * u, unsigned int events) static
Definition at line 108 of file uloop-epoll.c.
{
    if (!(events & ULOOP_READ))
        return;
    uint64_t fired;
    if (read(u->fd, &fired, sizeof(fired)) != sizeof(fired))
        return;
    struct uloop_interval *tm = container_of(u, struct uloop_interval, priv.ufd);
    tm->expirations += fired;
    tm->cb(tm);
}
References uloop_interval::cb, container_of, events, uloop_interval::expirations, uloop_fd::fd, uloop_interval::priv, and ULOOP_READ.
Referenced by timer_register().
register_poll()
static int register_poll (struct uloop_fd * fd, unsigned int flags) static
Definition at line 39 of file uloop-epoll.c.
{
    struct epoll_event ev;
    int op = fd->registered ? EPOLL_CTL_MOD : EPOLL_CTL_ADD;
    memset(&ev, 0, sizeof(struct epoll_event));
    if (flags & ULOOP_READ)
        ev.events |= EPOLLIN | EPOLLRDHUP;
    if (flags & ULOOP_WRITE)
        ev.events |= EPOLLOUT;
    if (flags & ULOOP_EDGE_TRIGGER)
        ev.events |= EPOLLET;
    ev.data.ptr = fd;
    return epoll_ctl(poll_fd, op, fd->fd, &ev);
}
References EPOLLRDHUP, uloop_fd::fd, poll_fd, uloop_fd::registered, ULOOP_EDGE_TRIGGER, ULOOP_READ, and ULOOP_WRITE.
Referenced by uloop_fd_add().
timer_next()
static int64_t timer_next (struct uloop_interval * tm) static
Definition at line 175 of file uloop-epoll.c.
{
    struct itimerspec spec;
    if (!tm->priv.ufd.registered)
        return -1;
    if (timerfd_gettime(tm->priv.ufd.fd, &spec) == -1)
        return -1;
    return spec.it_value.tv_sec * 1000 + spec.it_value.tv_nsec / 1000000;
}
References uloop_interval::priv.
Referenced by uloop_interval_remaining().
timer_register()
static int timer_register (struct uloop_interval * tm, unsigned int msecs) static
Definition at line 124 of file uloop-epoll.c.
{
    if (!tm->priv.ufd.registered) {
        int fd = timerfd_create(CLOCK_MONOTONIC, TFD_CLOEXEC|TFD_NONBLOCK);
        if (fd == -1)
            return -1;
        tm->priv.ufd.fd = fd;
        tm->priv.ufd.cb = dispatch_timer;
    }
    struct itimerspec spec = {
        .it_value = {
            .tv_sec = msecs / 1000,
            .tv_nsec = (msecs % 1000) * 1000000
        },
        .it_interval = {
            .tv_sec = msecs / 1000,
            .tv_nsec = (msecs % 1000) * 1000000
        }
    };
    if (timerfd_settime(tm->priv.ufd.fd, 0, &spec, NULL) == -1)
        goto err;
    if (uloop_fd_add(&tm->priv.ufd, ULOOP_READ) == -1)
        goto err;
    return 0;
err:
    uloop_fd_delete(&tm->priv.ufd);
    close(tm->priv.ufd.fd);
    memset(&tm->priv.ufd, 0, sizeof(tm->priv.ufd));
    return -1;
}
References uloop_interval::cb, dispatch_timer(), err, uloop_interval::priv, uloop_fd_add(), uloop_fd_delete(), and ULOOP_READ.
Referenced by uloop_interval_set().
timer_remove()
static int timer_remove (struct uloop_interval * tm) static
Definition at line 163 of file uloop-epoll.c.
{
    int ret = __uloop_fd_delete(&tm->priv.ufd);
    if (ret == 0) {
        close(tm->priv.ufd.fd);
        memset(&tm->priv.ufd, 0, sizeof(tm->priv.ufd));
    }
    return ret;
}
References __uloop_fd_delete(), and uloop_interval::priv.
Referenced by uloop_interval_cancel().
uloop_fetch_events()
static int uloop_fetch_events (int timeout) static
Definition at line 68 of file uloop-epoll.c.
{
    int n, nfds;
    nfds = epoll_wait(poll_fd, events, ARRAY_SIZE(events), timeout);
    for (n = 0; n < nfds; ++n) {
        struct uloop_fd_event *cur = &cur_fds[n];
        struct uloop_fd *u = events[n].data.ptr;
        unsigned int ev = 0;
        cur->fd = u;
        if (!u)
            continue;
        if (events[n].events & (EPOLLERR|EPOLLHUP)) {
            u->error = true;
            if (!(u->flags & ULOOP_ERROR_CB))
                uloop_fd_delete(u);
        }
        if(!(events[n].events & (EPOLLRDHUP|EPOLLIN|EPOLLOUT|EPOLLERR|EPOLLHUP))) {
            cur->fd = NULL;
            continue;
        }
        if(events[n].events & EPOLLRDHUP)
            u->eof = true;
        if(events[n].events & EPOLLIN)
            ev |= ULOOP_READ;
        if(events[n].events & EPOLLOUT)
            ev |= ULOOP_WRITE;
        cur->events = ev;
    }
    return nfds;
}
References ARRAY_SIZE, cur_fds, uloop_fd::eof, EPOLLRDHUP, uloop_fd::error, events, uloop_fd_event::events, uloop_fd_event::fd, uloop_fd::flags, poll_fd, timeout, ULOOP_ERROR_CB, uloop_fd_delete(), ULOOP_READ, and ULOOP_WRITE.
Referenced by uloop_run_events().
uloop_init_pollfd()
static int uloop_init_pollfd (void) static
Definition at line 26 of file uloop-epoll.c.
{
    if (poll_fd >= 0)
        return 0;
    poll_fd = epoll_create(32);
    if (poll_fd < 0)
        return -1;
    fcntl(poll_fd, F_SETFD, fcntl(poll_fd, F_GETFD) | FD_CLOEXEC);
    return 0;
}
References poll_fd.
Referenced by uloop_init().
Variable Documentation
events
struct epoll_event events[ULOOP_MAX_EVENTS] static
Definition at line 60 of file uloop-epoll.c.
Referenced by __ustream_fd_poll(), client_cb(), dispatch_timer(), ul_ufd_cb(), uloop_fd_stack_event(), uloop_fetch_events(), uloop_run_events(), and ustream_uloop_cb().