zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/netifd/main.c File Reference
main.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <getopt.h>
#include <signal.h>
#include <stdarg.h>
#include <syslog.h>
#include "netifd.h"
#include "ubus.h"
#include "config.h"
#include "system.h"
#include "interface.h"
#include "wireless.h"
#include "proto.h"
#include "extdev.h"
Macros
#define DEFAULT_LOG_LEVEL L_NOTICE
Functions
static void netifd_delete_process (struct netifd_process *proc)
static void netifd_udebug_vprintf (const char *format, va_list ap)
void netifd_udebug_printf (const char *format,...)
void netifd_udebug_config (struct udebug_ubus *ctx, struct blob_attr *data, bool enabled)
void __attribute__ ((format(printf, 2, 0)))
static void netifd_process_log_read_cb (struct ustream *s, int bytes)
static void netifd_process_cb (struct uloop_process *proc, int ret)
int netifd_start_process (const char **argv, char **env, struct netifd_process *proc)
void netifd_kill_process (struct netifd_process *proc)
static void netifd_do_restart (struct uloop_timeout *timeout)
int netifd_reload (void)
void netifd_restart (void)
static int usage (const char *progname)
static void netifd_handle_signal (int signo)
static void netifd_setup_signals (void)
static void netifd_kill_processes (void)
int main (int argc, char **argv)
Variables
unsigned int debug_mask = 0
const char * main_path = DEFAULT_MAIN_PATH
const char * config_path = DEFAULT_CONFIG_PATH
const char * resolv_conf = DEFAULT_RESOLV_CONF
static char ** global_argv
static struct list_head process_list = LIST_HEAD_INIT(process_list)
static struct udebug ud
static struct udebug_buf udb_log
struct udebug_buf udb_nl
static const struct udebug_buf_meta meta_log
static const struct udebug_buf_meta meta_nl
static struct udebug_ubus_ring rings []
static int log_level = DEFAULT_LOG_LEVEL
static const int log_class []
static bool use_syslog = true
Macro Definition Documentation
DEFAULT_LOG_LEVEL
#define DEFAULT_LOG_LEVEL L_NOTICE
Definition at line 65 of file main.c.
Referenced by usage().
Function Documentation
__attribute__()
void __attribute__ ((format(printf, 2, 0)))
Definition at line 119 of file main.c.
{
    va_list vl;
    va_start(vl, format);
    netifd_udebug_vprintf(format, vl);
    va_end(vl);
    if (priority > log_level)
        return;
    va_start(vl, format);
    if (use_syslog)
        vsyslog(log_class[priority], format, vl);
    else
        vfprintf(stderr, format, vl);
    va_end(vl);
}
References log_class, log_level, netifd_udebug_vprintf(), priority, and use_syslog.
main()
int main (int argc, char ** argv)
Definition at line 335 of file main.c.
{
    const char *socket = NULL;
    int ch;
    global_argv = argv;
    while ((ch = getopt(argc, argv, "d:s:p:c:h:r:l:S")) != -1) {
        switch(ch) {
        case 'd':
            debug_mask = strtoul(optarg, NULL, 0);
            break;
        case 's':
            socket = optarg;
            break;
        case 'p':
            main_path = optarg;
            break;
        case 'c':
            config_path = optarg;
            break;
        case 'h':
            hotplug_cmd_path = optarg;
            break;
        case 'r':
            resolv_conf = optarg;
            break;
        case 'l':
            log_level = atoi(optarg);
            if (log_level >= (int)ARRAY_SIZE(log_class))
                log_level = (int)ARRAY_SIZE(log_class) - 1;
            break;
#ifndef DUMMY_MODE
        case 'S':
            use_syslog = false;
            break;
#endif
        default:
            return usage(argv[0]);
        }
    }
    if (use_syslog)
        openlog("netifd", 0, LOG_DAEMON);
    netifd_setup_signals();
    uloop_init();
    udebug_init(&ud);
    udebug_auto_connect(&ud, NULL);
    for (size_t i = 0; i < ARRAY_SIZE(rings); i++)
        udebug_ubus_ring_init(&ud, &rings[i]);
    if (netifd_ubus_init(socket) < 0) {
        fprintf(stderr, "Failed to connect to ubus\n");
        return 1;
    }
    proto_shell_init();
    extdev_init();
    wireless_init();
    if (system_init()) {
        fprintf(stderr, "Failed to initialize system control\n");
        return 1;
    }
    config_init_all();
    uloop_run();
    netifd_kill_processes();
    netifd_ubus_done();
    if (use_syslog)
        closelog();
    return 0;
}
References ARRAY_SIZE, config_init_all(), config_path, debug_mask, extdev_init(), global_argv, hotplug_cmd_path, log_class, log_level, main_path, netifd_kill_processes(), netifd_setup_signals(), netifd_ubus_done(), netifd_ubus_init(), proto_shell_init(), resolv_conf, rings, system_init(), ud, udebug_auto_connect(), udebug_init(), uloop_init(), uloop_run(), usage(), use_syslog, and wireless_init().
netifd_delete_process()
static void netifd_delete_process (struct netifd_process * proc) static
Definition at line 84 of file main.c.
{
    while (ustream_poll(&proc->log.stream));
    list_del(&proc->list);
    ustream_free(&proc->log.stream);
    close(proc->log.fd.fd);
}
References uloop_fd::fd, ustream_fd::fd, netifd_process::list, list_del(), netifd_process::log, ustream_fd::stream, ustream_free(), and ustream_poll().
Referenced by netifd_kill_process(), and netifd_process_cb().
netifd_do_restart()
static void netifd_do_restart (struct uloop_timeout * timeout) static
Definition at line 265 of file main.c.
{
    execvp(global_argv[0], global_argv);
}
References global_argv.
Referenced by netifd_restart().
netifd_handle_signal()
static void netifd_handle_signal (int signo) static
Definition at line 304 of file main.c.
{
    uloop_end();
}
References uloop_end().
Referenced by netifd_setup_signals().
netifd_kill_process()
void netifd_kill_process (struct netifd_process * proc)
Definition at line 255 of file main.c.
{
    if (!proc->uloop.pending)
        return;
    kill(proc->uloop.pid, SIGKILL);
    uloop_process_delete(&proc->uloop);
    netifd_delete_process(proc);
}
References netifd_delete_process(), uloop_process::pending, uloop_process::pid, netifd_process::uloop, and uloop_process_delete().
Referenced by netifd_kill_processes(), netifd_start_process(), proto_shell_free(), proto_shell_teardown_timeout_cb(), and wireless_device_setup_timeout().
netifd_kill_processes()
static void netifd_kill_processes (void) static
Definition at line 327 of file main.c.
{
    struct netifd_process *proc, *tmp;
    list_for_each_entry_safe(proc, tmp, &process_list, list)
        netifd_kill_process(proc);
}
References netifd_process::list, list_for_each_entry_safe, netifd_kill_process(), and process_list.
Referenced by main().
netifd_process_cb()
static void netifd_process_cb (struct uloop_process * proc, int ret) static
Definition at line 183 of file main.c.
{
    struct netifd_process *np;
    np = container_of(proc, struct netifd_process, uloop);
    netifd_delete_process(np);
    np->cb(np, ret);
    return;
}
References netifd_process::cb, container_of, netifd_delete_process(), and netifd_process::uloop.
Referenced by netifd_start_process().
netifd_process_log_read_cb()
static void netifd_process_log_read_cb (struct ustream * s, int bytes) static
Definition at line 140 of file main.c.
{
    struct netifd_process *proc;
    const char *log_prefix;
    char *data;
    int len = 0;
    proc = container_of(s, struct netifd_process, log.stream);
    log_prefix = proc->log_prefix;
    if (!log_prefix)
        log_prefix = "process";
    do {
        char *newline;
        data = ustream_get_read_buf(s, &len);
        if (!len)
            break;
        newline = strchr(data, '\n');
        if (proc->log_overflow) {
            if (newline) {
                len = newline + 1 - data;
                proc->log_overflow = false;
            }
        } else if (newline) {
            *newline = 0;
            len = newline + 1 - data;
            netifd_log_message(L_NOTICE, "%s (%d): %s\n",
                log_prefix, proc->uloop.pid, data);
        } else if (len == s->r.buffer_len) {
            netifd_log_message(L_NOTICE, "%s (%d): %s [...]\n",
                log_prefix, proc->uloop.pid, data);
            proc->log_overflow = true;
        } else
            break;
        ustream_consume(s, len);
    } while (1);
}
References container_of, L_NOTICE, netifd_process::log, netifd_process::log_overflow, netifd_process::log_prefix, netifd_log_message(), uloop_process::pid, ustream_fd::stream, netifd_process::uloop, ustream_consume(), and ustream_get_read_buf().
Referenced by netifd_start_process().
netifd_reload()
int netifd_reload (void)
Definition at line 270 of file main.c.
{
    return config_init_all();
}
References config_init_all().
Referenced by netifd_handle_reload().
netifd_restart()
void netifd_restart (void)
Definition at line 275 of file main.c.
{
    static struct uloop_timeout main_timer = {
        .cb = netifd_do_restart
    };
    interface_set_down(NULL);
    uloop_timeout_set(&main_timer, 1000);
}
References interface_set_down(), netifd_do_restart(), and uloop_timeout_set().
Referenced by netifd_handle_restart().
netifd_setup_signals()
static void netifd_setup_signals (void) static
Definition at line 310 of file main.c.
{
    struct sigaction s;
    memset(&s, 0, sizeof(s));
    s.sa_handler = netifd_handle_signal;
    s.sa_flags = 0;
    sigaction(SIGINT, &s, NULL);
    sigaction(SIGTERM, &s, NULL);
    sigaction(SIGUSR1, &s, NULL);
    sigaction(SIGUSR2, &s, NULL);
    s.sa_handler = SIG_IGN;
    sigaction(SIGPIPE, &s, NULL);
}
References netifd_handle_signal().
Referenced by main().
netifd_start_process()
int netifd_start_process (const char ** argv, char ** env, struct netifd_process * proc)
Definition at line 194 of file main.c.
{
    int pfds[2];
    int pid;
    netifd_kill_process(proc);
    if (pipe(pfds) < 0)
        return -1;
    if ((pid = fork()) < 0)
        goto error;
    if (!pid) {
        int i;
        if (env) {
            while (*env) {
                putenv(*env);
                env++;
            }
        }
        if (proc->dir_fd >= 0)
            if (fchdir(proc->dir_fd)) {}
        close(pfds[0]);
        for (i = 0; i <= 2; i++) {
            if (pfds[1] == i)
                continue;
            dup2(pfds[1], i);
        }
        if (pfds[1] > 2)
            close(pfds[1]);
        execvp(argv[0], (char **) argv);
        exit(127);
    }
    close(pfds[1]);
    proc->uloop.cb = netifd_process_cb;
    proc->uloop.pid = pid;
    uloop_process_add(&proc->uloop);
    list_add_tail(&proc->list, &process_list);
    system_fd_set_cloexec(pfds[0]);
    proc->log.stream.string_data = true;
    proc->log.stream.notify_read = netifd_process_log_read_cb;
    ustream_fd_init(&proc->log, pfds[0]);
    return 0;
error:
    close(pfds[0]);
    close(pfds[1]);
    return -1;
}
References uloop_process::cb, netifd_process::dir_fd, netifd_process::list, list_add_tail(), netifd_process::log, netifd_kill_process(), netifd_process_cb(), netifd_process_log_read_cb(), ustream::notify_read, uloop_process::pid, process_list, ustream_fd::stream, ustream::string_data, system_fd_set_cloexec(), netifd_process::uloop, uloop_process_add(), and ustream_fd_init().
Referenced by proto_shell_handler(), proto_shell_run_command(), and wireless_device_run_handler().
netifd_udebug_config()
void netifd_udebug_config (struct udebug_ubus * ctx, struct blob_attr * data, bool enabled)
Definition at line 112 of file main.c.
{
    udebug_ubus_apply_config(&ud, rings, ARRAY_SIZE(rings), data, enabled);
}
References ARRAY_SIZE, rings, and ud.
Referenced by netifd_ubus_init().
netifd_udebug_printf()
void netifd_udebug_printf (const char * format, ...)
Definition at line 103 of file main.c.
{
    va_list ap;
    va_start(ap, format);
    netifd_udebug_vprintf(format, ap);
    va_end(ap);
}
References netifd_udebug_vprintf().
netifd_udebug_vprintf()
static void netifd_udebug_vprintf (const char * format, va_list ap) static
Definition at line 93 of file main.c.
{
    if (!udebug_buf_valid(&udb_log))
        return;
    udebug_entry_init(&udb_log);
    udebug_entry_vprintf(&udb_log, format, ap);
    udebug_entry_add(&udb_log);
}
References udb_log, udebug_buf_valid(), udebug_entry_add(), udebug_entry_init(), and udebug_entry_vprintf().
Referenced by __attribute__(), and netifd_udebug_printf().
usage()
static int usage (const char * progname) static
Definition at line 285 of file main.c.
{
    fprintf(stderr, "Usage: %s [options]\n"
        "Options:\n"
        " -d <mask>:        Mask for debug messages\n"
        " -s <path>:        Path to the ubus socket\n"
        " -p <path>:        Path to netifd addons (default: %s)\n"
        " -c <path>:        Path to UCI configuration\n"
        " -h <path>:        Path to the hotplug script\n"
        "           (default: "DEFAULT_HOTPLUG_PATH")\n"
        " -r <path>:        Path to resolv.conf\n"
        " -l <level>:       Log output level (default: %d)\n"
        " -S:           Use stderr instead of syslog for log messages\n"
        "\n", progname, main_path, DEFAULT_LOG_LEVEL);
    return 1;
}
References DEFAULT_HOTPLUG_PATH, DEFAULT_LOG_LEVEL, and main_path.
Variable Documentation
config_path
const char* config_path = DEFAULT_CONFIG_PATH
Definition at line 33 of file main.c.
Referenced by config_init_package(), and main().
debug_mask
unsigned int debug_mask = 0
Definition at line 31 of file main.c.
Referenced by main().
global_argv
char** global_argv static
Definition at line 35 of file main.c.
Referenced by main(), and netifd_do_restart().
log_class
const int log_class[] static
Initial value:
= {
    [L_CRIT] = LOG_CRIT,
    [L_WARNING] = LOG_WARNING,
    [L_NOTICE] = LOG_NOTICE,
    [L_INFO] = LOG_INFO,
    [L_DEBUG] = LOG_DEBUG
}
Definition at line 68 of file main.c.
{
    [L_CRIT] = LOG_CRIT,
    [L_WARNING] = LOG_WARNING,
    [L_NOTICE] = LOG_NOTICE,
    [L_INFO] = LOG_INFO,
    [L_DEBUG] = LOG_DEBUG
};
Referenced by __attribute__(), and main().
log_level
int log_level = DEFAULT_LOG_LEVEL static
Definition at line 67 of file main.c.
Referenced by __attribute__(), main(), main(), and vDprintf().
main_path
const char* main_path = DEFAULT_MAIN_PATH
Definition at line 32 of file main.c.
Referenced by main(), netifd_open_subdir(), and usage().
meta_log
const struct udebug_buf_meta meta_log static
Initial value:
= {
    .name = "netifd_log",
    .format = UDEBUG_FORMAT_STRING,
}
Definition at line 41 of file main.c.
{
    .name = "netifd_log",
    .format = UDEBUG_FORMAT_STRING,
};
meta_nl
const struct udebug_buf_meta meta_nl static
Initial value:
= {
    .name = "netifd_nl",
    .format = UDEBUG_FORMAT_PACKET,
    .sub_format = UDEBUG_DLT_NETLINK,
}
Definition at line 45 of file main.c.
{
    .name = "netifd_nl",
    .format = UDEBUG_FORMAT_PACKET,
    .sub_format = UDEBUG_DLT_NETLINK,
};
process_list
struct list_head process_list = LIST_HEAD_INIT(process_list) static
Definition at line 37 of file main.c.
Referenced by netifd_kill_processes(), and netifd_start_process().
resolv_conf
const char* resolv_conf = DEFAULT_RESOLV_CONF
Definition at line 34 of file main.c.
Referenced by interface_write_resolv_conf(), and main().
rings
struct udebug_ubus_ring rings[] static
Initial value:
= {
    {
        .buf = &udb_log,
        .meta = &meta_log,
        .default_entries = 1024,
        .default_size = 64 * 1024,
    },
    {
        .buf = &udb_nl,
        .meta = &meta_nl,
        .default_entries = 1024,
        .default_size = 64 * 1024,
    },
}
Definition at line 50 of file main.c.
{
    {
        .buf = &udb_log,
        .meta = &meta_log,
        .default_entries = 1024,
        .default_size = 64 * 1024,
    },
    {
        .buf = &udb_nl,
        .meta = &meta_nl,
        .default_entries = 1024,
        .default_size = 64 * 1024,
    },
};
Referenced by main(), and netifd_udebug_config().
ud
struct udebug ud static
Definition at line 38 of file main.c.
Referenced by applyOCIcapabilities(), main(), netifd_udebug_config(), and rpc_ucode_request_gc().
udb_log
struct udebug_buf udb_log static
Definition at line 39 of file main.c.
Referenced by netifd_udebug_vprintf().
udb_nl
struct udebug_buf udb_nl
Definition at line 40 of file main.c.
Referenced by create_socket().
use_syslog
bool use_syslog = true static
Definition at line 79 of file main.c.
Referenced by __attribute__(), and main().