zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/netifd/ubus.c File Reference
ubus.c File Reference
#include <arpa/inet.h>
#include <string.h>
#include <stdio.h>
#include "netifd.h"
#include "interface.h"
#include "proto.h"
#include "ubus.h"
#include "system.h"
#include "wireless.h"
Macros
#define _GNU_SOURCE
Enumerations
enum {
HR_TARGET , HR_V6 , HR_INTERFACE , HR_EXCLUDE ,
__HR_MAX
}
enum { DI_NAME , __DI_MAX }
enum { NETNS_UPDOWN_JAIL , NETNS_UPDOWN_START , __NETNS_UPDOWN_MAX }
enum { DEV_NAME , __DEV_MAX }
enum { ALIAS_ATTR_ALIAS , ALIAS_ATTR_DEV , __ALIAS_ATTR_MAX }
enum {
DEV_STATE_NAME , DEV_STATE_DEFER , DEV_STATE_AUTH_STATUS , DEV_STATE_AUTH_VLANS ,
__DEV_STATE_MAX
}
enum { DEV_LINK_NAME , DEV_LINK_EXT , DEV_LINK_VLAN , __DEV_LINK_MAX }
Functions
static int netifd_handle_restart (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int netifd_handle_reload (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int netifd_add_host_route (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int netifd_get_proto_handlers (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int netifd_add_dynamic (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int netifd_netns_updown (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int netifd_dev_status (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int netifd_handle_alias (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int netifd_handle_set_state (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int netifd_handle_stp_init (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static void netifd_ubus_add_fd (void)
void netifd_ubus_device_notify (const char *event, struct blob_attr *data, int timeout)
static void netifd_ubus_reconnect_timer (struct uloop_timeout *timeout)
static void netifd_ubus_connection_lost (struct ubus_context *ctx)
static int netifd_handle_up (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int netifd_handle_down (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int netifd_handle_renew (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static void netifd_add_interface_errors (struct blob_buf *b, struct interface *iface)
static void interface_ip_dump_address_list (struct interface_ip_settings *ip, bool v6, bool enabled)
static void interface_ip_dump_neighbor_list (struct interface_ip_settings *ip, bool enabled)
static void interface_ip_dump_route_list (struct interface_ip_settings *ip, bool enabled)
static void interface_ip_dump_prefix_list (struct interface_ip_settings *ip)
static void interface_ip_dump_prefix_assignment_list (struct interface *iface)
static void interface_ip_dump_dns_server_list (struct interface_ip_settings *ip, bool enabled)
static void interface_ip_dump_dns_search_list (struct interface_ip_settings *ip, bool enabled)
static void netifd_dump_status (struct interface *iface)
static int netifd_handle_status (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int netifd_handle_dump (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int netifd_iface_handle_device (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int netifd_iface_notify_proto (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static void netifd_iface_do_remove (struct uloop_timeout *timeout)
static int netifd_iface_remove (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int netifd_handle_iface_prepare (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int netifd_handle_set_data (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static void netifd_add_object (struct ubus_object *obj)
static int netifd_handle_iface (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static void netifd_add_iface_object (void)
static struct wireless_device * get_wdev (struct blob_attr *msg, int *ret)
static int netifd_handle_wdev_reconf (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int netifd_handle_wdev_up (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int netifd_handle_wdev_down (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int netifd_handle_wdev_status (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int netifd_handle_wdev_get_validate (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int netifd_handle_wdev_notify (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
int netifd_extdev_invoke (uint32_t id, const char *method, struct blob_attr *msg, ubus_data_handler_t data_cb, void *data)
int netifd_ubus_init (const char *path)
void netifd_ubus_done (void)
void netifd_ubus_interface_event (struct interface *iface, bool up)
void netifd_ubus_interface_notify (struct interface *iface, bool up)
void netifd_ubus_add_interface (struct interface *iface)
void netifd_ubus_remove_interface (struct interface *iface)
static void netifd_ubus_data_cb (struct ubus_request *req, int type, struct blob_attr *msg)
void netifd_ubus_get_procd_data (const char *type, procd_data_cb cb)
Variables
struct ubus_context * ubus_ctx = NULL
static struct blob_buf b
static const char * ubus_path
static struct udebug_ubus udebug
static const struct blobmsg_policy route_policy [__HR_MAX]
static const struct blobmsg_policy dynamic_policy [__DI_MAX]
static const struct blobmsg_policy netns_updown_policy [__NETNS_UPDOWN_MAX]
static struct ubus_method main_object_methods []
static struct ubus_object_type main_object_type
static struct ubus_object main_object
static const struct blobmsg_policy dev_policy [__DEV_MAX]
static const struct blobmsg_policy alias_attrs [__ALIAS_ATTR_MAX]
static const struct blobmsg_policy dev_state_policy [__DEV_STATE_MAX]
static struct ubus_method dev_object_methods []
static struct ubus_object_type dev_object_type
static struct ubus_object dev_object
static const struct blobmsg_policy dev_link_policy [__DEV_LINK_MAX]
static struct ubus_method iface_object_methods []
static struct ubus_object_type iface_object_type
static struct ubus_object iface_object
static const struct blobmsg_policy iface_policy
static struct ubus_method wireless_object_methods []
static struct ubus_object_type wireless_object_type
static struct ubus_object wireless_object
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 14 of file ubus.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
HR_TARGET
HR_V6
HR_INTERFACE
HR_EXCLUDE
__HR_MAX
Definition at line 54 of file ubus.c.
     {
    HR_TARGET,
    HR_V6,
    HR_INTERFACE,
    HR_EXCLUDE,
    __HR_MAX
};
anonymous enum
anonymous enum
Enumerator
DI_NAME
__DI_MAX
Definition at line 121 of file ubus.c.
     {
    DI_NAME,
    __DI_MAX
};
anonymous enum
anonymous enum
Enumerator
NETNS_UPDOWN_JAIL
NETNS_UPDOWN_START
__NETNS_UPDOWN_MAX
Definition at line 166 of file ubus.c.
     {
    NETNS_UPDOWN_JAIL,
    NETNS_UPDOWN_START,
    __NETNS_UPDOWN_MAX
};
anonymous enum
anonymous enum
Enumerator
DEV_NAME
__DEV_MAX
Definition at line 225 of file ubus.c.
     {
    DEV_NAME,
    __DEV_MAX,
};
anonymous enum
anonymous enum
Enumerator
ALIAS_ATTR_ALIAS
ALIAS_ATTR_DEV
__ALIAS_ATTR_MAX
Definition at line 257 of file ubus.c.
     {
    ALIAS_ATTR_ALIAS,
    ALIAS_ATTR_DEV,
    __ALIAS_ATTR_MAX,
};
anonymous enum
anonymous enum
Enumerator
DEV_STATE_NAME
DEV_STATE_DEFER
DEV_STATE_AUTH_STATUS
DEV_STATE_AUTH_VLANS
__DEV_STATE_MAX
Definition at line 305 of file ubus.c.
     {
    DEV_STATE_NAME,
    DEV_STATE_DEFER,
    DEV_STATE_AUTH_STATUS,
    DEV_STATE_AUTH_VLANS,
    __DEV_STATE_MAX,
};
anonymous enum
anonymous enum
Enumerator
DEV_LINK_NAME
DEV_LINK_EXT
DEV_LINK_VLAN
__DEV_LINK_MAX
Definition at line 977 of file ubus.c.
     {
    DEV_LINK_NAME,
    DEV_LINK_EXT,
    DEV_LINK_VLAN,
    __DEV_LINK_MAX,
};
Function Documentation
get_wdev()
static struct wireless_device * get_wdev (struct blob_attr * msg, int * ret) static
Definition at line 1189 of file ubus.c.
{
    struct blobmsg_policy wdev_policy = {
        .name = "device",
        .type = BLOBMSG_TYPE_STRING,
    };
    struct blob_attr *dev_attr;
    struct wireless_device *wdev = NULL;
    blobmsg_parse(&wdev_policy, 1, &dev_attr, blob_data(msg), blob_len(msg));
    if (!dev_attr) {
        *ret = UBUS_STATUS_INVALID_ARGUMENT;
        return NULL;
    }
    wdev = vlist_find(&wireless_devices, blobmsg_data(dev_attr), wdev, node);
    if (!wdev) {
        *ret = UBUS_STATUS_NOT_FOUND;
        return NULL;
    }
    *ret = 0;
    return wdev;
}
References blob_data(), blob_len(), blobmsg_data(), blobmsg_parse(), BLOBMSG_TYPE_STRING, UBUS_STATUS_INVALID_ARGUMENT, UBUS_STATUS_NOT_FOUND, vlist_find, wdev_policy, and wireless_devices.
Referenced by netifd_handle_wdev_down(), netifd_handle_wdev_get_validate(), netifd_handle_wdev_notify(), netifd_handle_wdev_reconf(), netifd_handle_wdev_status(), and netifd_handle_wdev_up().
interface_ip_dump_address_list()
static void interface_ip_dump_address_list (struct interface_ip_settings * ip, bool v6, bool enabled) static
Definition at line 520 of file ubus.c.
{
    struct device_addr *addr;
    char *buf;
    void *a;
    int buflen = 128;
    int af;
    time_t now = system_get_rtime();
    vlist_for_each_element(&ip->addr, addr, node) {
        if (addr->enabled != enabled)
            continue;
        if ((addr->flags & DEVADDR_FAMILY) == DEVADDR_INET4)
            af = AF_INET;
        else
            af = AF_INET6;
        if (af != (v6 ? AF_INET6 : AF_INET))
            continue;
        a = blobmsg_open_table(&b, NULL);
        buf = blobmsg_alloc_string_buffer(&b, "address", buflen);
        inet_ntop(af, &addr->addr, buf, buflen);
        blobmsg_add_string_buffer(&b);
        blobmsg_add_u32(&b, "mask", addr->mask);
        if (addr->point_to_point) {
            buf = blobmsg_alloc_string_buffer(&b, "ptpaddress", buflen);
            inet_ntop(af, &addr->point_to_point, buf, buflen);
            blobmsg_add_string_buffer(&b);
        }
        if (addr->preferred_until) {
            int preferred = addr->preferred_until - now;
            if (preferred < 0)
                preferred = 0;
            blobmsg_add_u32(&b, "preferred", preferred);
        }
        if (addr->valid_until)
            blobmsg_add_u32(&b, "valid", addr->valid_until - now);
        if (addr->pclass)
            blobmsg_add_string(&b, "class", addr->pclass);
        blobmsg_close_table(&b, a);
    }
}
References device_addr::addr, interface_ip_settings::addr, b, blobmsg_add_string(), blobmsg_add_string_buffer(), blobmsg_add_u32(), blobmsg_alloc_string_buffer(), blobmsg_close_table(), blobmsg_open_table(), buf, DEVADDR_FAMILY, DEVADDR_INET4, device_addr::enabled, system_get_rtime(), and vlist_for_each_element.
Referenced by netifd_dump_status().
interface_ip_dump_dns_search_list()
static void interface_ip_dump_dns_search_list (struct interface_ip_settings * ip, bool enabled) static
Definition at line 796 of file ubus.c.
{
    struct dns_search_domain *dns;
    vlist_simple_for_each_element(&ip->dns_search, dns, node) {
        if (ip->no_dns == enabled)
            continue;
        blobmsg_add_string(&b, NULL, dns->name);
    }
}
References b, blobmsg_add_string(), interface_ip_settings::dns_search, dns_search_domain::name, interface_ip_settings::no_dns, and vlist_simple_for_each_element.
Referenced by netifd_dump_status().
interface_ip_dump_dns_server_list()
static void interface_ip_dump_dns_server_list (struct interface_ip_settings * ip, bool enabled) static
Definition at line 779 of file ubus.c.
{
    struct dns_server *dns;
    int buflen = 128;
    char *buf;
    vlist_simple_for_each_element(&ip->dns_servers, dns, node) {
        if (ip->no_dns == enabled)
            continue;
        buf = blobmsg_alloc_string_buffer(&b, NULL, buflen);
        inet_ntop(dns->af, &dns->addr, buf, buflen);
        blobmsg_add_string_buffer(&b);
    }
}
References dns_server::addr, dns_server::af, b, blobmsg_add_string_buffer(), blobmsg_alloc_string_buffer(), buf, interface_ip_settings::dns_servers, interface_ip_settings::no_dns, and vlist_simple_for_each_element.
Referenced by netifd_dump_status().
interface_ip_dump_neighbor_list()
static void interface_ip_dump_neighbor_list (struct interface_ip_settings * ip, bool enabled) static
Definition at line 573 of file ubus.c.
{
    struct device_neighbor *neighbor;
    int buflen = 128;
    char *buf;
    void *r;
    int af;
    vlist_for_each_element(&ip->neighbor, neighbor, node) {
        if (neighbor->enabled != enabled)
            continue;
        if ((neighbor->flags & DEVADDR_FAMILY) == DEVADDR_INET4)
            af = AF_INET;
        else
            af = AF_INET6;
        r = blobmsg_open_table(&b, NULL);
        if (neighbor->flags & DEVNEIGH_MAC)
            blobmsg_add_string(&b, "mac", format_macaddr(neighbor->macaddr));
        buf = blobmsg_alloc_string_buffer(&b , "address", buflen);
        inet_ntop(af, &neighbor->addr, buf, buflen);
        blobmsg_add_string_buffer(&b);
        if (neighbor->proxy)
            blobmsg_add_u32(&b, "proxy", neighbor->proxy);
        if (neighbor->router)
            blobmsg_add_u32(&b, "router", neighbor->router);
        blobmsg_close_table(&b, r);
    }
}
References device_neighbor::addr, b, blobmsg_add_string(), blobmsg_add_string_buffer(), blobmsg_add_u32(), blobmsg_alloc_string_buffer(), blobmsg_close_table(), blobmsg_open_table(), buf, DEVADDR_FAMILY, DEVADDR_INET4, DEVNEIGH_MAC, device_neighbor::enabled, device_neighbor::flags, format_macaddr(), device_neighbor::macaddr, interface_ip_settings::neighbor, device_neighbor::proxy, r, device_neighbor::router, and vlist_for_each_element.
Referenced by netifd_dump_status().
interface_ip_dump_prefix_assignment_list()
static void interface_ip_dump_prefix_assignment_list (struct interface * iface) static
Definition at line 728 of file ubus.c.
{
    void *a;
    char *buf;
    const int buflen = INET6_ADDRSTRLEN;
    time_t now = system_get_rtime();
    struct device_prefix *prefix;
    list_for_each_entry(prefix, &prefixes, head) {
        struct device_prefix_assignment *assign;
        list_for_each_entry(assign, &prefix->assignments, head) {
            if (strcmp(assign->name, iface->name))
                continue;
            struct in6_addr addr = prefix->addr;
            addr.s6_addr32[1] |= htonl(assign->assigned);
            a = blobmsg_open_table(&b, NULL);
            buf = blobmsg_alloc_string_buffer(&b, "address", buflen);
            inet_ntop(AF_INET6, &addr, buf, buflen);
            blobmsg_add_string_buffer(&b);
            blobmsg_add_u32(&b, "mask", assign->length);
            if (prefix->preferred_until) {
                int preferred = prefix->preferred_until - now;
                if (preferred < 0)
                    preferred = 0;
                blobmsg_add_u32(&b, "preferred", preferred);
            }
            if (prefix->valid_until)
                blobmsg_add_u32(&b, "valid", prefix->valid_until - now);
            void *c = blobmsg_open_table(&b, "local-address");
            if (assign->enabled) {
                buf = blobmsg_alloc_string_buffer(&b, "address", buflen);
                inet_ntop(AF_INET6, &assign->addr, buf, buflen);
                blobmsg_add_string_buffer(&b);
                blobmsg_add_u32(&b, "mask", assign->length);
            }
            blobmsg_close_table(&b, c);
            blobmsg_close_table(&b, a);
        }
    }
}
References device_prefix::addr, assign, device_prefix::assignments, b, blobmsg_add_string_buffer(), blobmsg_add_u32(), blobmsg_alloc_string_buffer(), blobmsg_close_table(), blobmsg_open_table(), buf, device_prefix::head, device_prefix_assignment::head, list_for_each_entry, interface::name, device_prefix::preferred_until, prefixes, system_get_rtime(), and device_prefix::valid_until.
Referenced by netifd_dump_status().
interface_ip_dump_prefix_list()
static void interface_ip_dump_prefix_list (struct interface_ip_settings * ip) static
Definition at line 672 of file ubus.c.
{
    struct device_prefix *prefix;
    char *buf;
    void *a, *c;
    const int buflen = INET6_ADDRSTRLEN;
    time_t now = system_get_rtime();
    vlist_for_each_element(&ip->prefix, prefix, node) {
        a = blobmsg_open_table(&b, NULL);
        buf = blobmsg_alloc_string_buffer(&b, "address", buflen);
        inet_ntop(AF_INET6, &prefix->addr, buf, buflen);
        blobmsg_add_string_buffer(&b);
        blobmsg_add_u32(&b, "mask", prefix->length);
        if (prefix->preferred_until) {
            int preferred = prefix->preferred_until - now;
            if (preferred < 0)
                preferred = 0;
            blobmsg_add_u32(&b, "preferred", preferred);
        }
        if (prefix->valid_until)
            blobmsg_add_u32(&b, "valid", prefix->valid_until - now);
        blobmsg_add_string(&b, "class", prefix->pclass);
        c = blobmsg_open_table(&b, "assigned");
        struct device_prefix_assignment *assign;
        list_for_each_entry(assign, &prefix->assignments, head) {
            if (!assign->name[0])
                continue;
            struct in6_addr addr = prefix->addr;
            addr.s6_addr32[1] |= htonl(assign->assigned);
            void *d = blobmsg_open_table(&b, assign->name);
            buf = blobmsg_alloc_string_buffer(&b, "address", buflen);
            inet_ntop(AF_INET6, &addr, buf, buflen);
            blobmsg_add_string_buffer(&b);
            blobmsg_add_u32(&b, "mask", assign->length);
            blobmsg_close_table(&b, d);
        }
        blobmsg_close_table(&b, c);
        blobmsg_close_table(&b, a);
    }
}
References device_prefix::addr, assign, device_prefix::assignments, b, blobmsg_add_string(), blobmsg_add_string_buffer(), blobmsg_add_u32(), blobmsg_alloc_string_buffer(), blobmsg_close_table(), blobmsg_open_table(), buf, device_prefix_assignment::head, device_prefix::length, list_for_each_entry, device_prefix::pclass, device_prefix::preferred_until, interface_ip_settings::prefix, system_get_rtime(), device_prefix::valid_until, and vlist_for_each_element.
Referenced by netifd_dump_status().
interface_ip_dump_route_list()
static void interface_ip_dump_route_list (struct interface_ip_settings * ip, bool enabled) static
Definition at line 610 of file ubus.c.
{
    struct device_route *route;
    int buflen = 128;
    char *buf;
    void *r;
    int af;
    time_t now = system_get_rtime();
    vlist_for_each_element(&ip->route, route, node) {
        if (route->enabled != enabled)
            continue;
        if ((ip->no_defaultroute == enabled) && !route->mask)
            continue;
        if ((route->flags & DEVADDR_FAMILY) == DEVADDR_INET4)
            af = AF_INET;
        else
            af = AF_INET6;
        r = blobmsg_open_table(&b, NULL);
        buf = blobmsg_alloc_string_buffer(&b, "target", buflen);
        inet_ntop(af, &route->addr, buf, buflen);
        blobmsg_add_string_buffer(&b);
        blobmsg_add_u32(&b, "mask", route->mask);
        buf = blobmsg_alloc_string_buffer(&b, "nexthop", buflen);
        inet_ntop(af, &route->nexthop, buf, buflen);
        blobmsg_add_string_buffer(&b);
        if (route->flags & DEVROUTE_TYPE)
            blobmsg_add_u32(&b, "type", route->type);
        if (route->flags & DEVROUTE_PROTO)
            blobmsg_add_u32(&b, "proto", route->proto);
        if (route->flags & DEVROUTE_MTU)
            blobmsg_add_u32(&b, "mtu", route->mtu);
        if (route->flags & DEVROUTE_METRIC)
            blobmsg_add_u32(&b, "metric", route->metric);
        if (route->flags & DEVROUTE_TABLE)
            blobmsg_add_u32(&b, "table", route->table);
        if (route->valid_until)
            blobmsg_add_u32(&b, "valid", route->valid_until - now);
        buf = blobmsg_alloc_string_buffer(&b, "source", buflen);
        inet_ntop(af, &route->source, buf, buflen);
        snprintf(buf + strlen(buf), buflen - strlen(buf), "/%u", route->sourcemask);
        blobmsg_add_string_buffer(&b);
        blobmsg_close_table(&b, r);
    }
}
References device_route::addr, b, blobmsg_add_string_buffer(), blobmsg_add_u32(), blobmsg_alloc_string_buffer(), blobmsg_close_table(), blobmsg_open_table(), buf, DEVADDR_FAMILY, DEVADDR_INET4, DEVROUTE_METRIC, DEVROUTE_MTU, DEVROUTE_PROTO, DEVROUTE_TABLE, DEVROUTE_TYPE, device_route::enabled, device_route::flags, device_route::mask, device_route::metric, device_route::mtu, device_route::nexthop, interface_ip_settings::no_defaultroute, device_route::proto, r, interface_ip_settings::route, device_route::source, device_route::sourcemask, system_get_rtime(), device_route::table, device_route::type, device_route::valid_until, and vlist_for_each_element.
Referenced by netifd_dump_status().
netifd_add_dynamic()
static int netifd_add_dynamic (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 131 of file ubus.c.
{
    struct blob_attr *tb[__DI_MAX];
    struct interface *iface;
    struct blob_attr *config;
    blobmsg_parse(dynamic_policy, __DI_MAX, tb, blob_data(msg), blob_len(msg));
    if (!tb[DI_NAME])
        return UBUS_STATUS_INVALID_ARGUMENT;
    const char *name = blobmsg_get_string(tb[DI_NAME]);
    iface = interface_alloc(name, msg, true);
    if (!iface)
        return UBUS_STATUS_UNKNOWN_ERROR;
    config = blob_memdup(msg);
    if (!config)
        goto error;
    if (!interface_add(iface, config))
        goto error_free_config;
    return UBUS_STATUS_OK;
error_free_config:
    free(config);
error:
    free(iface);
    return UBUS_STATUS_UNKNOWN_ERROR;
}
References __DI_MAX, blob_data(), blob_len(), blob_memdup(), blobmsg_get_string(), blobmsg_parse(), config, DI_NAME, dynamic_policy, interface_add(), interface_alloc(), UBUS_STATUS_INVALID_ARGUMENT, UBUS_STATUS_OK, and UBUS_STATUS_UNKNOWN_ERROR.
netifd_add_host_route()
static int netifd_add_host_route (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 70 of file ubus.c.
{
    struct blob_attr *tb[__HR_MAX];
    struct interface *iface = NULL;
    union if_addr a;
    bool v6 = false;
    bool exclude = false;
    blobmsg_parse(route_policy, __HR_MAX, tb, blob_data(msg), blob_len(msg));
    if (!tb[HR_TARGET])
        return UBUS_STATUS_INVALID_ARGUMENT;
    if (tb[HR_V6])
        v6 = blobmsg_get_bool(tb[HR_V6]);
    if (tb[HR_EXCLUDE])
        exclude = blobmsg_get_bool(tb[HR_EXCLUDE]);
    if (tb[HR_INTERFACE])
        iface = vlist_find(&interfaces, blobmsg_data(tb[HR_INTERFACE]), iface, node);
    memset(&a, 0, sizeof(a));
    if (!inet_pton(v6 ? AF_INET6 : AF_INET, blobmsg_data(tb[HR_TARGET]), &a))
        return UBUS_STATUS_INVALID_ARGUMENT;
    iface = interface_ip_add_target_route(&a, v6, iface, exclude);
    if (!iface)
        return UBUS_STATUS_NOT_FOUND;
    blob_buf_init(&b, 0);
    blobmsg_add_string(&b, "interface", iface->name);
    ubus_send_reply(ctx, req, b.head);
    return 0;
}
References __HR_MAX, b, blob_buf_init(), blob_data(), blob_len(), blobmsg_add_string(), blobmsg_data(), blobmsg_get_bool(), blobmsg_parse(), ctx, blob_buf::head, HR_EXCLUDE, HR_INTERFACE, HR_TARGET, HR_V6, interface_ip_add_target_route(), interfaces, interface::name, route_policy, ubus_send_reply(), UBUS_STATUS_INVALID_ARGUMENT, UBUS_STATUS_NOT_FOUND, and vlist_find.
netifd_add_iface_object()
static void netifd_add_iface_object (void) static
Definition at line 1165 of file ubus.c.
{
    struct ubus_method *methods;
    size_t i;
    methods = calloc(1, sizeof(iface_object_methods));
    if (!methods)
        return;
    memcpy(methods, iface_object_methods, sizeof(iface_object_methods));
    iface_object.methods = methods;
    for (i = 0; i < ARRAY_SIZE(iface_object_methods); i++) {
        if (methods[i].handler == netifd_handle_dump)
            continue;
        methods[i].handler = netifd_handle_iface;
        methods[i].policy = &iface_policy;
        methods[i].n_policy = 1;
    }
    netifd_add_object(&iface_object);
}
References ARRAY_SIZE, ubus_method::handler, iface_object, iface_object_methods, iface_policy, ubus_object::methods, ubus_method::n_policy, netifd_add_object(), netifd_handle_dump(), netifd_handle_iface(), and ubus_method::policy.
Referenced by netifd_ubus_init().
netifd_add_interface_errors()
static void netifd_add_interface_errors (struct blob_buf * b, struct interface * iface) static
Definition at line 495 of file ubus.c.
{
    struct interface_error *error;
    void *e, *e2, *e3;
    int i;
    e = blobmsg_open_array(b, "errors");
    list_for_each_entry(error, &iface->errors, list) {
        e2 = blobmsg_open_table(b, NULL);
        blobmsg_add_string(b, "subsystem", error->subsystem);
        blobmsg_add_string(b, "code", error->code);
        if (error->data[0]) {
            e3 = blobmsg_open_array(b, "data");
            for (i = 0; error->data[i]; i++)
                blobmsg_add_string(b, NULL, error->data[i]);
            blobmsg_close_array(b, e3);
        }
        blobmsg_close_table(b, e2);
    }
    blobmsg_close_array(b, e);
}
References b, blobmsg_add_string(), blobmsg_close_array(), blobmsg_close_table(), blobmsg_open_array(), blobmsg_open_table(), interface_error::code, interface_error::data, interface::errors, interface_error::list, list_for_each_entry, and interface_error::subsystem.
Referenced by netifd_dump_status().
netifd_add_object()
static void netifd_add_object (struct ubus_object * obj) static
Definition at line 1122 of file ubus.c.
{
    int ret = ubus_add_object(ubus_ctx, obj);
    if (ret != 0)
        fprintf(stderr, "Failed to publish object '%s': %s\n", obj->name, ubus_strerror(ret));
}
References ubus_object::name, ubus_add_object(), ubus_ctx, and ubus_strerror().
Referenced by netifd_add_iface_object(), and netifd_ubus_init().
netifd_dev_status()
static int netifd_dev_status (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 235 of file ubus.c.
{
    struct device *dev = NULL;
    struct blob_attr *tb[__DEV_MAX];
    blobmsg_parse(dev_policy, __DEV_MAX, tb, blob_data(msg), blob_len(msg));
    if (tb[DEV_NAME]) {
        dev = device_find(blobmsg_data(tb[DEV_NAME]));
        if (!dev)
            return UBUS_STATUS_INVALID_ARGUMENT;
    }
    blob_buf_init(&b, 0);
    device_dump_status(&b, dev);
    ubus_send_reply(ctx, req, b.head);
    return 0;
}
References __DEV_MAX, b, blob_buf_init(), blob_data(), blob_len(), blobmsg_data(), blobmsg_parse(), ctx, DEV_NAME, dev_policy, device_dump_status(), device_find(), blob_buf::head, ubus_send_reply(), and UBUS_STATUS_INVALID_ARGUMENT.
netifd_dump_status()
static void netifd_dump_status (struct interface * iface) static
Definition at line 809 of file ubus.c.
{
    struct interface_data *data;
    struct device *dev;
    void *a, *inactive;
    blobmsg_add_u8(&b, "up", iface->state == IFS_UP);
    blobmsg_add_u8(&b, "pending", iface->state == IFS_SETUP);
    blobmsg_add_u8(&b, "available", iface->available);
    blobmsg_add_u8(&b, "autostart", iface->autostart);
    blobmsg_add_u8(&b, "dynamic", iface->dynamic);
    if (iface->state == IFS_UP) {
        time_t cur = system_get_rtime();
        blobmsg_add_u32(&b, "uptime", cur - iface->start_time);
        if (iface->l3_dev.dev)
            blobmsg_add_string(&b, "l3_device", iface->l3_dev.dev->ifname);
    }
    if (iface->proto_handler)
        blobmsg_add_string(&b, "proto", iface->proto_handler->name);
    dev = iface->main_dev.dev;
    if (dev && !dev->hidden && iface->proto_handler &&
        !(iface->proto_handler->flags & PROTO_FLAG_NODEV))
        blobmsg_add_string(&b, "device", dev->ifname);
    if (iface->jail)
        blobmsg_add_string(&b, "jail", iface->jail);
    if (iface->jail_device)
        blobmsg_add_string(&b, "jail_device", iface->jail_device);
    if (iface->state == IFS_UP) {
        if (iface->updated) {
            a = blobmsg_open_array(&b, "updated");
            if (iface->updated & IUF_ADDRESS)
                blobmsg_add_string(&b, NULL, "addresses");
            if (iface->updated & IUF_ROUTE)
                blobmsg_add_string(&b, NULL, "routes");
            if (iface->updated & IUF_PREFIX)
                blobmsg_add_string(&b, NULL, "prefixes");
            if (iface->updated & IUF_DATA)
                blobmsg_add_string(&b, NULL, "data");
            blobmsg_close_array(&b, a);
        }
        if (iface->ip4table)
            blobmsg_add_u32(&b, "ip4table", iface->ip4table);
        if (iface->ip6table)
            blobmsg_add_u32(&b, "ip6table", iface->ip6table);
        blobmsg_add_u32(&b, "metric", iface->metric);
        blobmsg_add_u32(&b, "dns_metric", iface->dns_metric);
        blobmsg_add_u8(&b, "delegation", !iface->proto_ip.no_delegation);
        if (iface->assignment_weight)
            blobmsg_add_u32(&b, "ip6weight", iface->assignment_weight);
        a = blobmsg_open_array(&b, "ipv4-address");
        interface_ip_dump_address_list(&iface->config_ip, false, true);
        interface_ip_dump_address_list(&iface->proto_ip, false, true);
        blobmsg_close_array(&b, a);
        a = blobmsg_open_array(&b, "ipv6-address");
        interface_ip_dump_address_list(&iface->config_ip, true, true);
        interface_ip_dump_address_list(&iface->proto_ip, true, true);
        blobmsg_close_array(&b, a);
        a = blobmsg_open_array(&b, "ipv6-prefix");
        interface_ip_dump_prefix_list(&iface->config_ip);
        interface_ip_dump_prefix_list(&iface->proto_ip);
        blobmsg_close_array(&b, a);
        a = blobmsg_open_array(&b, "ipv6-prefix-assignment");
        interface_ip_dump_prefix_assignment_list(iface);
        blobmsg_close_array(&b, a);
        a = blobmsg_open_array(&b, "route");
        interface_ip_dump_route_list(&iface->config_ip, true);
        interface_ip_dump_route_list(&iface->proto_ip, true);
        blobmsg_close_array(&b, a);
        a = blobmsg_open_array(&b, "dns-server");
        interface_ip_dump_dns_server_list(&iface->config_ip, true);
        interface_ip_dump_dns_server_list(&iface->proto_ip, true);
        blobmsg_close_array(&b, a);
        a = blobmsg_open_array(&b, "dns-search");
        interface_ip_dump_dns_search_list(&iface->config_ip, true);
        interface_ip_dump_dns_search_list(&iface->proto_ip, true);
        blobmsg_close_array(&b, a);
        a = blobmsg_open_array(&b, "neighbors");
        interface_ip_dump_neighbor_list(&iface->config_ip, true);
        interface_ip_dump_neighbor_list(&iface->proto_ip, true);
        blobmsg_close_array(&b, a);
        inactive = blobmsg_open_table(&b, "inactive");
        a = blobmsg_open_array(&b, "ipv4-address");
        interface_ip_dump_address_list(&iface->config_ip, false, false);
        interface_ip_dump_address_list(&iface->proto_ip, false, false);
        blobmsg_close_array(&b, a);
        a = blobmsg_open_array(&b, "ipv6-address");
        interface_ip_dump_address_list(&iface->config_ip, true, false);
        interface_ip_dump_address_list(&iface->proto_ip, true, false);
        blobmsg_close_array(&b, a);
        a = blobmsg_open_array(&b, "route");
        interface_ip_dump_route_list(&iface->config_ip, false);
        interface_ip_dump_route_list(&iface->proto_ip, false);
        blobmsg_close_array(&b, a);
        a = blobmsg_open_array(&b, "dns-server");
        interface_ip_dump_dns_server_list(&iface->config_ip, false);
        interface_ip_dump_dns_server_list(&iface->proto_ip, false);
        blobmsg_close_array(&b, a);
        a = blobmsg_open_array(&b, "dns-search");
        interface_ip_dump_dns_search_list(&iface->config_ip, false);
        interface_ip_dump_dns_search_list(&iface->proto_ip, false);
        blobmsg_close_array(&b, a);
        a = blobmsg_open_array(&b, "neighbors");
        interface_ip_dump_neighbor_list(&iface->config_ip, false);
        interface_ip_dump_neighbor_list(&iface->proto_ip, false);
        blobmsg_close_array(&b, a);
        blobmsg_close_table(&b, inactive);
    }
    a = blobmsg_open_table(&b, "data");
    if (iface->zone)
        blobmsg_add_string(&b, "zone", iface->zone);
    avl_for_each_element(&iface->data, data, node)
        blobmsg_add_blob(&b, data->data);
    blobmsg_close_table(&b, a);
    if (!list_empty(&iface->errors))
        netifd_add_interface_errors(&b, iface);
}
References interface::assignment_weight, interface::autostart, interface::available, avl_for_each_element, b, blobmsg_add_blob(), blobmsg_add_string(), blobmsg_add_u32(), blobmsg_add_u8(), blobmsg_close_array(), blobmsg_close_table(), blobmsg_open_array(), blobmsg_open_table(), interface::config_ip, interface::data, interface_data::data, device_user::dev, interface::dns_metric, interface::dynamic, interface::errors, proto_handler::flags, device::hidden, device::ifname, IFS_SETUP, IFS_UP, interface_ip_dump_address_list(), interface_ip_dump_dns_search_list(), interface_ip_dump_dns_server_list(), interface_ip_dump_neighbor_list(), interface_ip_dump_prefix_assignment_list(), interface_ip_dump_prefix_list(), interface_ip_dump_route_list(), interface::ip4table, interface::ip6table, IUF_ADDRESS, IUF_DATA, IUF_PREFIX, IUF_ROUTE, interface::jail, interface::jail_device, interface::l3_dev, list_empty(), interface::main_dev, interface::metric, proto_handler::name, netifd_add_interface_errors(), interface_ip_settings::no_delegation, PROTO_FLAG_NODEV, interface::proto_handler, interface::proto_ip, interface::start_time, interface::state, system_get_rtime(), interface::updated, and interface::zone.
Referenced by netifd_handle_dump(), netifd_handle_status(), and netifd_ubus_interface_notify().
netifd_extdev_invoke()
int netifd_extdev_invoke (uint32_t id, const char * method, struct blob_attr * msg, ubus_data_handler_t data_cb, void * data)
Definition at line 1363 of file ubus.c.
{
    return ubus_invoke(ubus_ctx, id, method, msg, data_cb, data, 3000);
}
References ubus_ctx, and ubus_invoke().
Referenced by extdev_dump(), netifd_extdev_add(), netifd_extdev_create(), netifd_extdev_free(), netifd_extdev_prepare(), netifd_extdev_reload(), and netifd_extdev_remove().
netifd_get_proto_handlers()
static int netifd_get_proto_handlers (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 109 of file ubus.c.
{
    blob_buf_init(&b, 0);
    proto_dump_handlers(&b);
    ubus_send_reply(ctx, req, b.head);
    return 0;
}
References b, blob_buf_init(), ctx, blob_buf::head, proto_dump_handlers(), and ubus_send_reply().
netifd_handle_alias()
static int netifd_handle_alias (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 269 of file ubus.c.
{
    struct device *dev = NULL;
    struct blob_attr *tb[__ALIAS_ATTR_MAX];
    struct blob_attr *cur;
    size_t rem;
    blobmsg_parse(alias_attrs, __ALIAS_ATTR_MAX, tb, blob_data(msg), blob_len(msg));
    if (!tb[ALIAS_ATTR_ALIAS])
        return UBUS_STATUS_INVALID_ARGUMENT;
    if ((cur = tb[ALIAS_ATTR_DEV]) != NULL) {
        dev = device_get(blobmsg_data(cur), true);
        if (!dev)
            return UBUS_STATUS_NOT_FOUND;
    }
    blobmsg_for_each_attr(cur, tb[ALIAS_ATTR_ALIAS], rem) {
        if (blobmsg_type(cur) != BLOBMSG_TYPE_STRING)
            goto error;
        if (!blobmsg_check_attr(cur, false))
            goto error;
        alias_notify_device(blobmsg_data(cur), dev);
    }
    return 0;
error:
    device_free_unused();
    return UBUS_STATUS_INVALID_ARGUMENT;
}
References __ALIAS_ATTR_MAX, ALIAS_ATTR_ALIAS, ALIAS_ATTR_DEV, alias_attrs, alias_notify_device(), blob_data(), blob_len(), blobmsg_check_attr(), blobmsg_data(), blobmsg_for_each_attr, blobmsg_parse(), BLOBMSG_TYPE_STRING, device_free_unused(), device_get(), UBUS_STATUS_INVALID_ARGUMENT, and UBUS_STATUS_NOT_FOUND.
netifd_handle_down()
static int netifd_handle_down (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 469 of file ubus.c.
{
    struct interface *iface;
    iface = container_of(obj, struct interface, ubus);
    interface_set_down(iface);
    return 0;
}
References container_of, interface_set_down(), and ubus.
netifd_handle_dump()
static int netifd_handle_dump (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 956 of file ubus.c.
{
    blob_buf_init(&b, 0);
    void *a = blobmsg_open_array(&b, "interface");
    struct interface *iface;
    vlist_for_each_element(&interfaces, iface, node) {
        void *i = blobmsg_open_table(&b, NULL);
        blobmsg_add_string(&b, "interface", iface->name);
        netifd_dump_status(iface);
        blobmsg_close_table(&b, i);
    }
    blobmsg_close_array(&b, a);
    ubus_send_reply(ctx, req, b.head);
    return 0;
}
References b, blob_buf_init(), blobmsg_add_string(), blobmsg_close_array(), blobmsg_close_table(), blobmsg_open_array(), blobmsg_open_table(), ctx, blob_buf::head, interfaces, interface::name, netifd_dump_status(), ubus_send_reply(), and vlist_for_each_element.
Referenced by netifd_add_iface_object().
netifd_handle_iface()
static int netifd_handle_iface (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 1136 of file ubus.c.
{
    struct interface *iface;
    struct blob_attr *tb;
    size_t i;
    blobmsg_parse(&iface_policy, 1, &tb, blob_data(msg), blob_len(msg));
    if (!tb)
        return UBUS_STATUS_INVALID_ARGUMENT;
    iface = vlist_find(&interfaces, blobmsg_data(tb), iface, node);
    if (!iface)
        return UBUS_STATUS_NOT_FOUND;
    for (i = 0; i < ARRAY_SIZE(iface_object_methods); i++) {
        ubus_handler_t cb;
        if (strcmp(method, iface_object_methods[i].name) != 0)
            continue;
        cb = iface_object_methods[i].handler;
        return cb(ctx, &iface->ubus, req, method, msg);
    }
    return UBUS_STATUS_INVALID_ARGUMENT;
}
References ARRAY_SIZE, blob_data(), blob_len(), blobmsg_data(), blobmsg_parse(), ctx, ubus_method::handler, iface_object_methods, iface_policy, interfaces, interface::ubus, UBUS_STATUS_INVALID_ARGUMENT, UBUS_STATUS_NOT_FOUND, and vlist_find.
Referenced by netifd_add_iface_object().
netifd_handle_iface_prepare()
static int netifd_handle_iface_prepare (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 1058 of file ubus.c.
{
    struct interface *iface;
    struct device *dev, *bridge_dev = NULL;
    const struct device_hotplug_ops *ops;
    iface = container_of(obj, struct interface, ubus);
    dev = iface->main_dev.dev;
    if (!dev)
        goto out;
    ops = dev->hotplug_ops;
    if (!ops)
        goto out;
    ops->prepare(dev, &bridge_dev);
out:
    blob_buf_init(&b, 0);
    if (bridge_dev)
        blobmsg_add_string(&b, "bridge", bridge_dev->ifname);
    ubus_send_reply(ctx, req, b.head);
    return 0;
}
References b, blob_buf_init(), blobmsg_add_string(), container_of, ctx, device_user::dev, blob_buf::head, device::hotplug_ops, device::ifname, interface::main_dev, ops, ubus, and ubus_send_reply().
netifd_handle_reload()
static int netifd_handle_reload (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 44 of file ubus.c.
{
    if (netifd_reload())
        return UBUS_STATUS_NOT_FOUND;
    return UBUS_STATUS_OK;
}
References netifd_reload(), UBUS_STATUS_NOT_FOUND, and UBUS_STATUS_OK.
netifd_handle_renew()
static int netifd_handle_renew (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 482 of file ubus.c.
{
    struct interface *iface;
    iface = container_of(obj, struct interface, ubus);
    interface_renew(iface);
    return 0;
}
References container_of, interface_renew(), and ubus.
netifd_handle_restart()
static int netifd_handle_restart (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 35 of file ubus.c.
{
    netifd_restart();
    return 0;
}
References netifd_restart().
netifd_handle_set_data()
static int netifd_handle_set_data (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 1087 of file ubus.c.
{
    struct interface *iface;
    iface = container_of(obj, struct interface, ubus);
    return interface_parse_data(iface, msg);
}
References container_of, interface_parse_data(), and ubus.
netifd_handle_set_state()
static int netifd_handle_set_state (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 321 of file ubus.c.
{
    struct device *dev = NULL;
    struct blob_attr *tb[__DEV_STATE_MAX];
    struct blob_attr *cur;
    bool auth_status;
    blobmsg_parse(dev_state_policy, __DEV_STATE_MAX, tb, blob_data(msg), blob_len(msg));
    cur = tb[DEV_STATE_NAME];
    if (!cur)
        return UBUS_STATUS_INVALID_ARGUMENT;
    dev = device_find(blobmsg_data(cur));
    if (!dev)
        return UBUS_STATUS_NOT_FOUND;
    cur = tb[DEV_STATE_DEFER];
    if (cur)
        device_set_deferred(dev, !!blobmsg_get_u8(cur));
    if ((cur = tb[DEV_STATE_AUTH_STATUS]) != NULL)
        auth_status = blobmsg_get_bool(cur);
    else
        auth_status = dev->auth_status;
    if (tb[DEV_STATE_AUTH_STATUS] || tb[DEV_STATE_AUTH_VLANS])
        device_set_auth_status(dev, auth_status, tb[DEV_STATE_AUTH_VLANS]);
    return 0;
}
References __DEV_STATE_MAX, device::auth_status, blob_data(), blob_len(), blobmsg_data(), blobmsg_get_bool(), blobmsg_get_u8(), blobmsg_parse(), DEV_STATE_AUTH_STATUS, DEV_STATE_AUTH_VLANS, DEV_STATE_DEFER, DEV_STATE_NAME, dev_state_policy, device_find(), device_set_auth_status(), device_set_deferred(), UBUS_STATUS_INVALID_ARGUMENT, and UBUS_STATUS_NOT_FOUND.
netifd_handle_status()
static int netifd_handle_status (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 941 of file ubus.c.
{
    struct interface *iface = container_of(obj, struct interface, ubus);
    blob_buf_init(&b, 0);
    netifd_dump_status(iface);
    ubus_send_reply(ctx, req, b.head);
    return 0;
}
References b, blob_buf_init(), container_of, ctx, blob_buf::head, netifd_dump_status(), ubus, and ubus_send_reply().
netifd_handle_stp_init()
static int netifd_handle_stp_init (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 388 of file ubus.c.
{
    device_stp_init();
    return 0;
}
References device_stp_init().
netifd_handle_up()
static int netifd_handle_up (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 456 of file ubus.c.
{
    struct interface *iface;
    iface = container_of(obj, struct interface, ubus);
    interface_set_up(iface);
    return 0;
}
References container_of, interface_set_up(), and ubus.
netifd_handle_wdev_down()
static int netifd_handle_wdev_down (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 1260 of file ubus.c.
{
    struct wireless_device *wdev;
    int ret;
    wdev = get_wdev(msg, &ret);
    if (ret == UBUS_STATUS_NOT_FOUND)
        return ret;
    if (wdev) {
        wireless_device_set_down(wdev);
    } else {
        vlist_for_each_element(&wireless_devices, wdev, node)
            wireless_device_set_down(wdev);
    }
    return 0;
}
References get_wdev(), UBUS_STATUS_NOT_FOUND, vlist_for_each_element, wireless_device_set_down(), and wireless_devices.
netifd_handle_wdev_get_validate()
static int netifd_handle_wdev_get_validate (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 1305 of file ubus.c.
{
    struct wireless_device *wdev;
    int ret;
    wdev = get_wdev(msg, &ret);
    if (ret == UBUS_STATUS_NOT_FOUND)
        return ret;
    blob_buf_init(&b, 0);
    if (wdev) {
        wireless_device_get_validate(wdev, &b);
    } else {
        vlist_for_each_element(&wireless_devices, wdev, node)
            wireless_device_get_validate(wdev, &b);
    }
    ubus_send_reply(ctx, req, b.head);
    return 0;
}
References b, blob_buf_init(), ctx, get_wdev(), blob_buf::head, ubus_send_reply(), UBUS_STATUS_NOT_FOUND, vlist_for_each_element, wireless_device_get_validate(), and wireless_devices.
netifd_handle_wdev_notify()
static int netifd_handle_wdev_notify (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 1328 of file ubus.c.
{
    struct wireless_device *wdev;
    int ret;
    wdev = get_wdev(msg, &ret);
    if (!wdev)
        return ret;
    return wireless_device_notify(wdev, msg, req);
}
References get_wdev(), and wireless_device_notify().
netifd_handle_wdev_reconf()
static int netifd_handle_wdev_reconf (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 1216 of file ubus.c.
{
    struct wireless_device *wdev;
    int ret;
    wdev = get_wdev(msg, &ret);
    if (ret == UBUS_STATUS_NOT_FOUND)
        return ret;
    if (wdev) {
        wireless_device_reconf(wdev);
    } else {
        vlist_for_each_element(&wireless_devices, wdev, node)
            wireless_device_reconf(wdev);
    }
    return 0;
}
References get_wdev(), UBUS_STATUS_NOT_FOUND, vlist_for_each_element, wireless_device_reconf(), and wireless_devices.
netifd_handle_wdev_status()
static int netifd_handle_wdev_status (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 1282 of file ubus.c.
{
    struct wireless_device *wdev;
    int ret;
    wdev = get_wdev(msg, &ret);
    if (ret == UBUS_STATUS_NOT_FOUND)
        return ret;
    blob_buf_init(&b, 0);
    if (wdev) {
        wireless_device_status(wdev, &b);
    } else {
        vlist_for_each_element(&wireless_devices, wdev, node)
            wireless_device_status(wdev, &b);
    }
    ubus_send_reply(ctx, req, b.head);
    return 0;
}
References b, blob_buf_init(), ctx, get_wdev(), blob_buf::head, ubus_send_reply(), UBUS_STATUS_NOT_FOUND, vlist_for_each_element, wireless_device_status(), and wireless_devices.
netifd_handle_wdev_up()
static int netifd_handle_wdev_up (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 1238 of file ubus.c.
{
    struct wireless_device *wdev;
    int ret;
    wdev = get_wdev(msg, &ret);
    if (ret == UBUS_STATUS_NOT_FOUND)
        return ret;
    if (wdev) {
        wireless_device_set_up(wdev);
    } else {
        vlist_for_each_element(&wireless_devices, wdev, node)
            wireless_device_set_up(wdev);
    }
    return 0;
}
References get_wdev(), UBUS_STATUS_NOT_FOUND, vlist_for_each_element, wireless_device_set_up(), and wireless_devices.
netifd_iface_do_remove()
static void netifd_iface_do_remove (struct uloop_timeout * timeout) static
Definition at line 1033 of file ubus.c.
{
    struct interface *iface;
    iface = container_of(timeout, struct interface, remove_timer);
    vlist_delete(&interfaces, &iface->node);
}
References container_of, interfaces, interface::node, interface::remove_timer, timeout, and vlist_delete().
Referenced by netifd_iface_remove().
netifd_iface_handle_device()
static int netifd_iface_handle_device (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 991 of file ubus.c.
{
    struct blob_attr *tb[__DEV_LINK_MAX];
    struct blob_attr *cur;
    struct interface *iface;
    bool add = !strncmp(method, "add", 3);
    bool link_ext = true;
    iface = container_of(obj, struct interface, ubus);
    blobmsg_parse(dev_link_policy, __DEV_LINK_MAX, tb, blob_data(msg), blob_len(msg));
    if (!tb[DEV_LINK_NAME])
        return UBUS_STATUS_INVALID_ARGUMENT;
    cur = tb[DEV_LINK_EXT];
    if (cur)
        link_ext = blobmsg_get_bool(cur);
    return interface_handle_link(iface, blobmsg_data(tb[DEV_LINK_NAME]),
                     tb[DEV_LINK_VLAN], add, link_ext);
}
References __DEV_LINK_MAX, blob_data(), blob_len(), blobmsg_data(), blobmsg_get_bool(), blobmsg_parse(), container_of, DEV_LINK_EXT, DEV_LINK_NAME, dev_link_policy, DEV_LINK_VLAN, interface_handle_link(), ubus, and UBUS_STATUS_INVALID_ARGUMENT.
netifd_iface_notify_proto()
static int netifd_iface_notify_proto (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 1018 of file ubus.c.
{
    struct interface *iface;
    iface = container_of(obj, struct interface, ubus);
    if (!iface->proto || !iface->proto->notify)
        return UBUS_STATUS_NOT_SUPPORTED;
    return iface->proto->notify(iface->proto, msg);
}
References container_of, interface_proto_state::notify, interface::proto, ubus, and UBUS_STATUS_NOT_SUPPORTED.
netifd_iface_remove()
static int netifd_iface_remove (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 1042 of file ubus.c.
{
    struct interface *iface;
    iface = container_of(obj, struct interface, ubus);
    if (iface->remove_timer.cb)
        return UBUS_STATUS_INVALID_ARGUMENT;
    iface->remove_timer.cb = netifd_iface_do_remove;
    uloop_timeout_set(&iface->remove_timer, 100);
    return 0;
}
References uloop_timeout::cb, container_of, netifd_iface_do_remove(), interface::remove_timer, ubus, UBUS_STATUS_INVALID_ARGUMENT, and uloop_timeout_set().
netifd_netns_updown()
static int netifd_netns_updown (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 178 of file ubus.c.
{
    int target_netns_fd = ubus_request_get_caller_fd(req);
    struct blob_attr *tb[__NETNS_UPDOWN_MAX];
    bool start;
    if (target_netns_fd < 0)
        return UBUS_STATUS_INVALID_ARGUMENT;
    blobmsg_parse(netns_updown_policy, __NETNS_UPDOWN_MAX, tb, blob_data(msg), blob_len(msg));
    start = tb[NETNS_UPDOWN_START] && blobmsg_get_bool(tb[NETNS_UPDOWN_START]);
    if (start) {
        if (!tb[NETNS_UPDOWN_JAIL])
            return UBUS_STATUS_INVALID_ARGUMENT;
        interface_start_jail(target_netns_fd, blobmsg_get_string(tb[NETNS_UPDOWN_JAIL]));
    } else {
        interface_stop_jail(target_netns_fd);
    }
    close(target_netns_fd);
    return UBUS_STATUS_OK;
}
References __NETNS_UPDOWN_MAX, blob_data(), blob_len(), blobmsg_get_bool(), blobmsg_get_string(), blobmsg_parse(), interface_start_jail(), interface_stop_jail(), NETNS_UPDOWN_JAIL, netns_updown_policy, NETNS_UPDOWN_START, ubus_request_get_caller_fd(), UBUS_STATUS_INVALID_ARGUMENT, and UBUS_STATUS_OK.
netifd_ubus_add_fd()
static void netifd_ubus_add_fd (void) static
Definition at line 418 of file ubus.c.
{
    ubus_add_uloop(ubus_ctx);
    system_fd_set_cloexec(ubus_ctx->sock.fd);
}
References uloop_fd::fd, ubus_context::sock, system_fd_set_cloexec(), ubus_add_uloop(), and ubus_ctx.
Referenced by netifd_ubus_init(), and netifd_ubus_reconnect_timer().
netifd_ubus_add_interface()
void netifd_ubus_add_interface (struct interface * iface)
Definition at line 1420 of file ubus.c.
{
    struct ubus_object *obj = &iface->ubus;
    char *name = NULL;
    if (asprintf(&name, "%s.interface.%s", main_object.name, iface->name) == -1)
        return;
    obj->name = name;
    obj->type = &iface_object_type;
    obj->methods = iface_object_methods;
    obj->n_methods = ARRAY_SIZE(iface_object_methods);
    if (ubus_add_object(ubus_ctx, &iface->ubus)) {
        D(SYSTEM, "failed to publish ubus object for interface '%s'", iface->name);
        free(name);
        obj->name = NULL;
    }
}
References ARRAY_SIZE, D, iface_object_methods, iface_object_type, main_object, ubus_object::methods, ubus_object::n_methods, interface::name, ubus_object::name, ubus_object::type, interface::ubus, ubus_add_object(), and ubus_ctx.
Referenced by interface_update().
netifd_ubus_connection_lost()
static void netifd_ubus_connection_lost (struct ubus_context * ctx) static
Definition at line 448 of file ubus.c.
{
    netifd_ubus_reconnect_timer(NULL);
}
References netifd_ubus_reconnect_timer().
Referenced by netifd_ubus_init().
netifd_ubus_data_cb()
static void netifd_ubus_data_cb (struct ubus_request * req, int type, struct blob_attr * msg) static
Definition at line 1450 of file ubus.c.
{
    struct blob_attr *srv, *in, *t, *data;
    procd_data_cb cb = req->priv;
    int rem, rem2, rem3, rem4;
    blobmsg_for_each_attr(srv, msg, rem) {
        if (!blobmsg_check_attr(srv, true) ||
            blobmsg_type(srv) != BLOBMSG_TYPE_TABLE)
            continue;
        blobmsg_for_each_attr(in, srv, rem2) {
            if (!blobmsg_check_attr(in , true) ||
                blobmsg_type(in) != BLOBMSG_TYPE_TABLE)
                continue;
            blobmsg_for_each_attr(t, in, rem3) {
                if (!blobmsg_check_attr(t, true) ||
                    blobmsg_type(t) != BLOBMSG_TYPE_TABLE)
                    continue;
                blobmsg_for_each_attr(data, t, rem4) {
                    if (!blobmsg_check_attr(t, true) ||
                        blobmsg_type(t) != BLOBMSG_TYPE_TABLE)
                        continue;
                    cb(data);
                }
            }
        }
    }
}
References blobmsg_check_attr(), blobmsg_for_each_attr, BLOBMSG_TYPE_TABLE, blob_attr::data, and ubus_request::priv.
Referenced by netifd_ubus_get_procd_data().
netifd_ubus_device_notify()
void netifd_ubus_device_notify (const char * event, struct blob_attr * data, int timeout)
Definition at line 424 of file ubus.c.
{
    ubus_notify(ubus_ctx, &dev_object, event, data, timeout);
}
References dev_object, timeout, ubus_ctx, and ubus_notify().
Referenced by __device_broadcast_event(), and bridge_stp_notify().
netifd_ubus_done()
void netifd_ubus_done (void)
Definition at line 1393 of file ubus.c.
{
    udebug_ubus_free(&udebug);
    ubus_free(ubus_ctx);
}
References ubus_ctx, and ubus_free().
Referenced by main().
netifd_ubus_get_procd_data()
void netifd_ubus_get_procd_data (const char * type, procd_data_cb cb)
Definition at line 1479 of file ubus.c.
{
    uint32_t id;
    if (ubus_lookup_id(ubus_ctx, "service", &id))
        return;
    blob_buf_init(&b, 0);
    blobmsg_add_string(&b, "type", type);
    ubus_invoke(ubus_ctx, id, "get_data", b.head, netifd_ubus_data_cb, cb, 30000);
}
References b, blob_buf_init(), blobmsg_add_string(), blob_buf::head, id, netifd_ubus_data_cb(), type, ubus_ctx, ubus_invoke(), and ubus_lookup_id().
Referenced by config_init_wireless().
netifd_ubus_init()
int netifd_ubus_init (const char * path)
Definition at line 1370 of file ubus.c.
{
    ubus_path = path;
    ubus_ctx = ubus_connect(path);
    if (!ubus_ctx)
        return -EIO;
    D(SYSTEM, "connected as %08x", ubus_ctx->local_id);
    ubus_ctx->connection_lost = netifd_ubus_connection_lost;
    netifd_ubus_add_fd();
    netifd_add_object(&main_object);
    netifd_add_object(&dev_object);
    netifd_add_object(&wireless_object);
    netifd_add_iface_object();
    udebug_ubus_init(&udebug, ubus_ctx, "netifd", netifd_udebug_config);
    return 0;
}
References ubus_context::connection_lost, D, dev_object, ubus_context::local_id, main_object, netifd_add_iface_object(), netifd_add_object(), netifd_ubus_add_fd(), netifd_ubus_connection_lost(), netifd_udebug_config(), path, ubus_connect(), ubus_ctx, and wireless_object.
Referenced by main().
netifd_ubus_interface_event()
void netifd_ubus_interface_event (struct interface * iface, bool up)
Definition at line 1400 of file ubus.c.
{
    blob_buf_init(&b, 0);
    blobmsg_add_string(&b, "action", up ? "ifup" : "ifdown");
    blobmsg_add_string(&b, "interface", iface->name);
    ubus_send_event(ubus_ctx, "network.interface", b.head);
}
References b, blob_buf_init(), blobmsg_add_string(), blob_buf::head, interface::name, ubus_ctx, and ubus_send_event().
Referenced by interface_queue_event().
netifd_ubus_interface_notify()
void netifd_ubus_interface_notify (struct interface * iface, bool up)
Definition at line 1409 of file ubus.c.
{
    const char *event = (up) ? "interface.update" : "interface.down";
    blob_buf_init(&b, 0);
    blobmsg_add_string(&b, "interface", iface->name);
    netifd_dump_status(iface);
    ubus_notify(ubus_ctx, &iface_object, event, b.head, -1);
    ubus_notify(ubus_ctx, &iface->ubus, event, b.head, -1);
}
References b, blob_buf_init(), blobmsg_add_string(), blob_buf::head, iface_object, interface::name, netifd_dump_status(), interface::ubus, ubus_ctx, and ubus_notify().
Referenced by interface_queue_event().
netifd_ubus_reconnect_timer()
static void netifd_ubus_reconnect_timer (struct uloop_timeout * timeout) static
Definition at line 430 of file ubus.c.
{
    static struct uloop_timeout retry = {
        .cb = netifd_ubus_reconnect_timer,
    };
    int t = 2;
    if (ubus_reconnect(ubus_ctx, ubus_path) != 0) {
        D(SYSTEM, "failed to reconnect, trying again in %d seconds", t);
        uloop_timeout_set(&retry, t * 1000);
        return;
    }
    D(SYSTEM, "reconnected to ubus, new id: %08x", ubus_ctx->local_id);
    netifd_ubus_add_fd();
}
References D, ubus_context::local_id, netifd_ubus_add_fd(), netifd_ubus_reconnect_timer(), ubus_ctx, ubus_reconnect(), and uloop_timeout_set().
Referenced by netifd_ubus_connection_lost(), and netifd_ubus_reconnect_timer().
netifd_ubus_remove_interface()
void netifd_ubus_remove_interface (struct interface * iface)
Definition at line 1440 of file ubus.c.
{
    if (!iface->ubus.name)
        return;
    ubus_remove_object(ubus_ctx, &iface->ubus);
    free((void *) iface->ubus.name);
}
References ubus_object::name, interface::ubus, ubus_ctx, and ubus_remove_object().
Referenced by interface_do_free().
Variable Documentation
alias_attrs
const struct blobmsg_policy alias_attrs[__ALIAS_ATTR_MAX] static
Initial value:
= {
    [ALIAS_ATTR_ALIAS] = { "alias", BLOBMSG_TYPE_ARRAY },
    [ALIAS_ATTR_DEV] = { "device", BLOBMSG_TYPE_STRING },
}
Definition at line 263 of file ubus.c.
{
    [ALIAS_ATTR_ALIAS] = { "alias", BLOBMSG_TYPE_ARRAY },
    [ALIAS_ATTR_DEV] = { "device", BLOBMSG_TYPE_STRING },
};
Referenced by netifd_handle_alias().
b
struct blob_buf b static
Definition at line 28 of file ubus.c.
Referenced by interface_ip_dump_address_list(), interface_ip_dump_dns_search_list(), interface_ip_dump_dns_server_list(), interface_ip_dump_neighbor_list(), interface_ip_dump_prefix_assignment_list(), interface_ip_dump_prefix_list(), interface_ip_dump_route_list(), netifd_add_host_route(), netifd_add_interface_errors(), netifd_dev_status(), netifd_dump_status(), netifd_get_proto_handlers(), netifd_handle_dump(), netifd_handle_iface_prepare(), netifd_handle_status(), netifd_handle_wdev_get_validate(), netifd_handle_wdev_status(), netifd_sub_cb(), netifd_ubus_get_procd_data(), netifd_ubus_interface_event(), netifd_ubus_interface_notify(), ubus_lua_format_blob(), ubus_lua_format_blob_array(), and ustp_ubus_exit().
dev_link_policy
const struct blobmsg_policy dev_link_policy[__DEV_LINK_MAX] static
Initial value:
= {
    [DEV_LINK_NAME] = { .name = "name", .type = BLOBMSG_TYPE_STRING },
    [DEV_LINK_EXT] = { .name = "link-ext", .type = BLOBMSG_TYPE_BOOL },
    [DEV_LINK_VLAN] = { .name = "vlan", .type = BLOBMSG_TYPE_ARRAY },
}
Definition at line 984 of file ubus.c.
{
    [DEV_LINK_NAME] = { .name = "name", .type = BLOBMSG_TYPE_STRING },
    [DEV_LINK_EXT] = { .name = "link-ext", .type = BLOBMSG_TYPE_BOOL },
    [DEV_LINK_VLAN] = { .name = "vlan", .type = BLOBMSG_TYPE_ARRAY },
};
Referenced by netifd_iface_handle_device().
dev_object
struct ubus_object dev_object static
Initial value:
= {
    .name = "network.device",
    .type = &dev_object_type,
    .methods = dev_object_methods,
    .n_methods = ARRAY_SIZE(dev_object_methods),
}
Definition at line 410 of file ubus.c.
{
    .name = "network.device",
    .type = &dev_object_type,
    .methods = dev_object_methods,
    .n_methods = ARRAY_SIZE(dev_object_methods),
};
Referenced by netifd_ubus_device_notify(), and netifd_ubus_init().
dev_object_methods
struct ubus_method dev_object_methods[] static
Initial value:
= {
    UBUS_METHOD("status", netifd_dev_status, dev_policy),
    UBUS_METHOD("set_alias", netifd_handle_alias, alias_attrs),
    UBUS_METHOD("set_state", netifd_handle_set_state, dev_state_policy),
}
Definition at line 397 of file ubus.c.
{
    UBUS_METHOD("status", netifd_dev_status, dev_policy),
    UBUS_METHOD("set_alias", netifd_handle_alias, alias_attrs),
    UBUS_METHOD("set_state", netifd_handle_set_state, dev_state_policy),
#ifdef DUMMY_MODE
    UBUS_METHOD("hotplug_event", netifd_handle_dev_hotplug, dev_hotplug_policy),
#endif
    UBUS_METHOD_NOARG("stp_init", netifd_handle_stp_init)
};
dev_object_type
struct ubus_object_type dev_object_type static
Initial value:
=
    UBUS_OBJECT_TYPE("device", dev_object_methods)
Definition at line 407 of file ubus.c.
dev_policy
const struct blobmsg_policy dev_policy[__DEV_MAX] static
Initial value:
= {
    [DEV_NAME] = { .name = "name", .type = BLOBMSG_TYPE_STRING },
}
Definition at line 230 of file ubus.c.
{
    [DEV_NAME] = { .name = "name", .type = BLOBMSG_TYPE_STRING },
};
Referenced by netifd_dev_status().
dev_state_policy
const struct blobmsg_policy dev_state_policy[__DEV_STATE_MAX] static
Initial value:
= {
    [DEV_STATE_NAME] = { .name = "name", .type = BLOBMSG_TYPE_STRING },
    [DEV_STATE_DEFER] = { .name = "defer", .type = BLOBMSG_TYPE_BOOL },
    [DEV_STATE_AUTH_STATUS] = { .name = "auth_status", .type = BLOBMSG_TYPE_BOOL },
    [DEV_STATE_AUTH_VLANS] = { .name = "auth_vlans", BLOBMSG_TYPE_ARRAY },
}
Definition at line 313 of file ubus.c.
{
    [DEV_STATE_NAME] = { .name = "name", .type = BLOBMSG_TYPE_STRING },
    [DEV_STATE_DEFER] = { .name = "defer", .type = BLOBMSG_TYPE_BOOL },
    [DEV_STATE_AUTH_STATUS] = { .name = "auth_status", .type = BLOBMSG_TYPE_BOOL },
    [DEV_STATE_AUTH_VLANS] = { .name = "auth_vlans", BLOBMSG_TYPE_ARRAY },
};
Referenced by netifd_handle_set_state().
dynamic_policy
const struct blobmsg_policy dynamic_policy[__DI_MAX] static
Initial value:
= {
    [DI_NAME] = { .name = "name", .type = BLOBMSG_TYPE_STRING },
}
Definition at line 126 of file ubus.c.
{
    [DI_NAME] = { .name = "name", .type = BLOBMSG_TYPE_STRING },
};
Referenced by netifd_add_dynamic().
iface_object
struct ubus_object iface_object static
Initial value:
= {
    .name = "network.interface",
    .type = &iface_object_type,
    .n_methods = ARRAY_SIZE(iface_object_methods),
}
Definition at line 1116 of file ubus.c.
{
    .name = "network.interface",
    .type = &iface_object_type,
    .n_methods = ARRAY_SIZE(iface_object_methods),
};
Referenced by netifd_add_iface_object(), and netifd_ubus_interface_notify().
iface_object_methods
struct ubus_method iface_object_methods[] static
Initial value:
= {
    { .name = "up", .handler = netifd_handle_up },
    { .name = "down", .handler = netifd_handle_down },
    { .name = "renew", .handler = netifd_handle_renew },
    { .name = "status", .handler = netifd_handle_status },
    { .name = "prepare", .handler = netifd_handle_iface_prepare },
    { .name = "dump", .handler = netifd_handle_dump },
    UBUS_METHOD("add_device", netifd_iface_handle_device, dev_link_policy ),
    UBUS_METHOD("remove_device", netifd_iface_handle_device, dev_link_policy ),
    { .name = "notify_proto", .handler = netifd_iface_notify_proto },
    { .name = "remove", .handler = netifd_iface_remove },
    { .name = "set_data", .handler = netifd_handle_set_data },
}
Definition at line 1098 of file ubus.c.
{
    { .name = "up", .handler = netifd_handle_up },
    { .name = "down", .handler = netifd_handle_down },
    { .name = "renew", .handler = netifd_handle_renew },
    { .name = "status", .handler = netifd_handle_status },
    { .name = "prepare", .handler = netifd_handle_iface_prepare },
    { .name = "dump", .handler = netifd_handle_dump },
    UBUS_METHOD("add_device", netifd_iface_handle_device, dev_link_policy ),
    UBUS_METHOD("remove_device", netifd_iface_handle_device, dev_link_policy ),
    { .name = "notify_proto", .handler = netifd_iface_notify_proto },
    { .name = "remove", .handler = netifd_iface_remove },
    { .name = "set_data", .handler = netifd_handle_set_data },
};
Referenced by netifd_add_iface_object(), netifd_handle_iface(), and netifd_ubus_add_interface().
iface_object_type
struct ubus_object_type iface_object_type static
Initial value:
=
    UBUS_OBJECT_TYPE("netifd_iface", iface_object_methods)
Definition at line 1112 of file ubus.c.
Referenced by netifd_ubus_add_interface().
iface_policy
const struct blobmsg_policy iface_policy static
Initial value:
= {
    .name = "interface",
    .type = BLOBMSG_TYPE_STRING,
}
Definition at line 1130 of file ubus.c.
{
    .name = "interface",
    .type = BLOBMSG_TYPE_STRING,
};
Referenced by netifd_add_iface_object(), and netifd_handle_iface().
main_object
struct ubus_object main_object static
Initial value:
= {
    .name = "network",
    .type = &main_object_type,
    .methods = main_object_methods,
    .n_methods = ARRAY_SIZE(main_object_methods),
}
Definition at line 218 of file ubus.c.
{
    .name = "network",
    .type = &main_object_type,
    .methods = main_object_methods,
    .n_methods = ARRAY_SIZE(main_object_methods),
};
Referenced by netifd_ubus_add_interface(), and netifd_ubus_init().
main_object_methods
struct ubus_method main_object_methods[] static
Initial value:
= {
    { .name = "restart", .handler = netifd_handle_restart },
    { .name = "reload", .handler = netifd_handle_reload },
    UBUS_METHOD("add_host_route", netifd_add_host_route, route_policy),
    { .name = "get_proto_handlers", .handler = netifd_get_proto_handlers },
    UBUS_METHOD("add_dynamic", netifd_add_dynamic, dynamic_policy),
    UBUS_METHOD("netns_updown", netifd_netns_updown, netns_updown_policy),
}
Definition at line 206 of file ubus.c.
{
    { .name = "restart", .handler = netifd_handle_restart },
    { .name = "reload", .handler = netifd_handle_reload },
    UBUS_METHOD("add_host_route", netifd_add_host_route, route_policy),
    { .name = "get_proto_handlers", .handler = netifd_get_proto_handlers },
    UBUS_METHOD("add_dynamic", netifd_add_dynamic, dynamic_policy),
    UBUS_METHOD("netns_updown", netifd_netns_updown, netns_updown_policy),
};
main_object_type
struct ubus_object_type main_object_type static
Initial value:
=
    UBUS_OBJECT_TYPE("netifd", main_object_methods)
Definition at line 215 of file ubus.c.
netns_updown_policy
const struct blobmsg_policy netns_updown_policy[__NETNS_UPDOWN_MAX] static
Initial value:
= {
    [NETNS_UPDOWN_JAIL] = { .name = "jail", .type = BLOBMSG_TYPE_STRING },
    [NETNS_UPDOWN_START] = { .name = "start", .type = BLOBMSG_TYPE_BOOL },
}
Definition at line 172 of file ubus.c.
{
    [NETNS_UPDOWN_JAIL] = { .name = "jail", .type = BLOBMSG_TYPE_STRING },
    [NETNS_UPDOWN_START] = { .name = "start", .type = BLOBMSG_TYPE_BOOL },
};
Referenced by netifd_netns_updown().
route_policy
const struct blobmsg_policy route_policy[__HR_MAX] static
Initial value:
= {
    [HR_TARGET] = { .name = "target", .type = BLOBMSG_TYPE_STRING },
    [HR_V6] = { .name = "v6", .type = BLOBMSG_TYPE_BOOL },
    [HR_INTERFACE] = { .name = "interface", .type = BLOBMSG_TYPE_STRING },
    [HR_EXCLUDE] = { .name = "exclude", .type = BLOBMSG_TYPE_BOOL },
}
Definition at line 62 of file ubus.c.
{
    [HR_TARGET] = { .name = "target", .type = BLOBMSG_TYPE_STRING },
    [HR_V6] = { .name = "v6", .type = BLOBMSG_TYPE_BOOL },
    [HR_INTERFACE] = { .name = "interface", .type = BLOBMSG_TYPE_STRING },
    [HR_EXCLUDE] = { .name = "exclude", .type = BLOBMSG_TYPE_BOOL },
};
Referenced by netifd_add_host_route().
ubus_ctx
struct ubus_context* ubus_ctx = NULL
Definition at line 27 of file ubus.c.
Referenced by extdev_add_devtype(), extdev_ext_ubus_obj_wait(), extdev_lookup_id(), extdev_subscribe(), netifd_add_object(), netifd_extdev_invoke(), netifd_ubus_add_fd(), netifd_ubus_add_interface(), netifd_ubus_device_notify(), netifd_ubus_done(), netifd_ubus_get_procd_data(), netifd_ubus_init(), netifd_ubus_interface_event(), netifd_ubus_interface_notify(), netifd_ubus_reconnect_timer(), netifd_ubus_remove_interface(), wireless_complete_kill_request(), and wireless_device_process_kill_all().
ubus_path
const char* ubus_path static
Definition at line 29 of file ubus.c.
udebug
struct udebug_ubus udebug static
Definition at line 30 of file ubus.c.
wireless_object
struct ubus_object wireless_object static
Initial value:
= {
    .name = "network.wireless",
    .type = &wireless_object_type,
    .methods = wireless_object_methods,
    .n_methods = ARRAY_SIZE(wireless_object_methods),
}
Definition at line 1355 of file ubus.c.
{
    .name = "network.wireless",
    .type = &wireless_object_type,
    .methods = wireless_object_methods,
    .n_methods = ARRAY_SIZE(wireless_object_methods),
};
Referenced by netifd_ubus_init().
wireless_object_methods
struct ubus_method wireless_object_methods[] static
Initial value:
= {
    { .name = "up", .handler = netifd_handle_wdev_up },
    { .name = "down", .handler = netifd_handle_wdev_down },
    { .name = "reconf", .handler = netifd_handle_wdev_reconf },
    { .name = "status", .handler = netifd_handle_wdev_status },
    { .name = "notify", .handler = netifd_handle_wdev_notify },
    { .name = "get_validate", .handler = netifd_handle_wdev_get_validate },
}
Definition at line 1342 of file ubus.c.
{
    { .name = "up", .handler = netifd_handle_wdev_up },
    { .name = "down", .handler = netifd_handle_wdev_down },
    { .name = "reconf", .handler = netifd_handle_wdev_reconf },
    { .name = "status", .handler = netifd_handle_wdev_status },
    { .name = "notify", .handler = netifd_handle_wdev_notify },
    { .name = "get_validate", .handler = netifd_handle_wdev_get_validate },
};
wireless_object_type
struct ubus_object_type wireless_object_type static
Initial value:
=
    UBUS_OBJECT_TYPE("netifd_iface", wireless_object_methods)
Definition at line 1351 of file ubus.c.