zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/ubus/ubusd_monitor.c File Reference
ubusd_monitor.c File Reference
#include "ubusd.h"
Classes
struct ubus_monitor
Functions
static LIST_HEAD (monitors)
static void ubusd_monitor_free (struct ubus_monitor *m)
static bool ubusd_monitor_connect (struct ubus_client *cl, struct ubus_msg_buf *ub)
static struct ubus_monitor * ubusd_monitor_find (struct ubus_client *cl)
void ubusd_monitor_disconnect (struct ubus_client *cl)
void ubusd_monitor_message (struct ubus_client *cl, struct ubus_msg_buf *ub, bool send)
static int ubusd_monitor_recv (struct ubus_client *cl, struct ubus_msg_buf *ub, const char *method, struct blob_attr *msg)
void ubusd_monitor_init (void)
Variables
static struct ubus_object * monitor_obj
Class Documentation
ubus_monitor
struct ubus_monitor
Definition at line 19 of file ubusd_monitor.c.
Class Members
struct ubus_client * cl
struct list_head list
uint32_t seq
Function Documentation
LIST_HEAD()
static LIST_HEAD (monitors) static
ubusd_monitor_connect()
static bool ubusd_monitor_connect (struct ubus_client * cl, struct ubus_msg_buf * ub) static
Definition at line 33 of file ubusd_monitor.c.
{
    struct ubus_monitor *m;
    ubusd_monitor_disconnect(cl);
    m = calloc(1, sizeof(*m));
    if (!m)
        return false;
    m->cl = cl;
    list_add_tail(&m->list, &monitors);
    return true;
}
References ubus_monitor::cl, ubus_monitor::list, list_add_tail(), and ubusd_monitor_disconnect().
Referenced by ubusd_monitor_recv().
ubusd_monitor_disconnect()
void ubusd_monitor_disconnect (struct ubus_client * cl)
Definition at line 65 of file ubusd_monitor.c.
{
    struct ubus_monitor *m;
    m = ubusd_monitor_find(cl);
    if (!m)
        return;
    ubusd_monitor_free(m);
}
References ubus_monitor::cl, ubusd_monitor_find(), and ubusd_monitor_free().
Referenced by handle_client_disconnect(), ubusd_monitor_connect(), and ubusd_monitor_recv().
ubusd_monitor_find()
static struct ubus_monitor * ubusd_monitor_find (struct ubus_client * cl) static
Definition at line 50 of file ubusd_monitor.c.
{
    struct ubus_monitor *m, *tmp;
    list_for_each_entry_safe(m, tmp, &monitors, list) {
        if (m->cl != cl)
            continue;
        return m;
    }
    return NULL;
}
References ubus_monitor::cl, ubus_monitor::list, and list_for_each_entry_safe.
Referenced by ubusd_monitor_disconnect().
ubusd_monitor_free()
static void ubusd_monitor_free (struct ubus_monitor * m) static
Definition at line 26 of file ubusd_monitor.c.
{
    list_del(&m->list);
    free(m);
}
References ubus_monitor::list, and list_del().
Referenced by ubusd_monitor_disconnect().
ubusd_monitor_init()
void ubusd_monitor_init (void)
Definition at line 128 of file ubusd_monitor.c.
{
    monitor_obj = ubusd_create_object_internal(NULL, UBUS_SYSTEM_OBJECT_MONITOR);
    if (monitor_obj != NULL)
        monitor_obj->recv_msg = ubusd_monitor_recv;
}
References monitor_obj, ubus_object::recv_msg, UBUS_SYSTEM_OBJECT_MONITOR, ubusd_create_object_internal(), and ubusd_monitor_recv().
Referenced by ubusd_obj_init().
ubusd_monitor_message()
void ubusd_monitor_message (struct ubus_client * cl, struct ubus_msg_buf * ub, bool send)
Definition at line 77 of file ubusd_monitor.c.
{
    static struct blob_buf mb;
    struct ubus_monitor *m;
    if (list_empty(&monitors))
        return;
    blob_buf_init(&mb, 0);
    blob_put_int32(&mb, UBUS_MONITOR_CLIENT, cl->id.id);
    blob_put_int32(&mb, UBUS_MONITOR_PEER, ub->hdr.peer);
    blob_put_int32(&mb, UBUS_MONITOR_SEQ, ub->hdr.seq);
    blob_put_int32(&mb, UBUS_MONITOR_TYPE, ub->hdr.type);
    blob_put_int8(&mb, UBUS_MONITOR_SEND, send);
    blob_put(&mb, UBUS_MONITOR_DATA, blob_data(ub->data), blob_len(ub->data));
    ub = ubus_msg_new(mb.head, blob_raw_len(mb.head), true);
    ub->hdr.type = UBUS_MSG_MONITOR;
    list_for_each_entry(m, &monitors, list) {
        ub->hdr.seq = ++m->seq;
        ubus_msg_send(m->cl, ub);
    }
    ubus_msg_free(ub);
}
References blob_buf_init(), blob_data(), blob_len(), blob_put(), blob_put_int32, blob_put_int8, blob_raw_len(), ubus_monitor::cl, ubus_msg_buf::data, ubus_msg_buf::hdr, blob_buf::head, ubus_client::id, ubus_id::id, ubus_monitor::list, list_empty(), list_for_each_entry, ubus_msghdr::peer, ubus_monitor::seq, ubus_msghdr::seq, ubus_msghdr::type, UBUS_MONITOR_CLIENT, UBUS_MONITOR_DATA, UBUS_MONITOR_PEER, UBUS_MONITOR_SEND, UBUS_MONITOR_SEQ, UBUS_MONITOR_TYPE, ubus_msg_free(), UBUS_MSG_MONITOR, ubus_msg_new(), and ubus_msg_send().
Referenced by client_cb(), and ubus_msg_send().
ubusd_monitor_recv()
static int ubusd_monitor_recv (struct ubus_client * cl, struct ubus_msg_buf * ub, const char * method, struct blob_attr * msg) static
Definition at line 105 of file ubusd_monitor.c.
{
    /* Only root is allowed for now */
    if (cl->uid != 0 || cl->gid != 0)
        return UBUS_STATUS_PERMISSION_DENIED;
    if (!strcmp(method, "add")) {
        if (!ubusd_monitor_connect(cl, ub))
            return UBUS_STATUS_UNKNOWN_ERROR;
        return UBUS_STATUS_OK;
    }
    if (!strcmp(method, "remove")) {
        ubusd_monitor_disconnect(cl);
        return UBUS_STATUS_OK;
    }
    return UBUS_STATUS_METHOD_NOT_FOUND;
}
References ubus_monitor::cl, ubus_client::gid, UBUS_STATUS_METHOD_NOT_FOUND, UBUS_STATUS_OK, UBUS_STATUS_PERMISSION_DENIED, UBUS_STATUS_UNKNOWN_ERROR, ubusd_monitor_connect(), ubusd_monitor_disconnect(), and ubus_client::uid.
Referenced by ubusd_monitor_init().
Variable Documentation
monitor_obj
struct ubus_object* monitor_obj static
Definition at line 16 of file ubusd_monitor.c.
Referenced by ubusd_monitor_init().