zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/service/service.h File Reference
service.h File Reference
#include <libubox/avl.h>
#include <libubox/vlist.h>
#include <libubox/list.h>
#include "../utils/utils.h"
Classes
struct vrule
struct validate
struct service
Functions
void service_validate_add (struct service *s, struct blob_attr *attr)
void service_validate_dump (struct blob_buf *b, struct service *s)
void service_validate_dump_all (struct blob_buf *b, char *p, char *s)
int service_start_early (char *name, char *cmdline, char *user, char *group)
void service_stopped (struct service *s)
void service_validate_del (struct service *s)
void service_event (const char *type, const char *service, const char *instance)
void service_stop_all (void)
Variables
struct avl_tree services
struct avl_tree containers
Class Documentation
vrule
struct vrule
Definition at line 26 of file service.h.
Class Members
struct avl_node avl
char * option
char * rule
validate
struct validate
Definition at line 32 of file service.h.
Class Members
struct avl_node avl
struct list_head list
char * package
struct avl_tree rules
char * type
service
struct service
Definition at line 42 of file service.h.
Class Members
bool autostart
struct avl_node avl
bool container
struct blob_attr * data
struct blobmsg_list data_blob
bool deleted
struct vlist_tree instances
const char * name
struct blob_attr * trigger
struct list_head validators
Function Documentation
service_event()
void service_event (const char * type, const char * service, const char * instance)
Definition at line 1055 of file service.c.
{
    ubus_event_bcast(type, "service", service, "instance", instance);
}
References type, and ubus_event_bcast().
Referenced by instance_exit(), instance_start(), service_handle_set(), and service_stopped().
service_start_early()
int service_start_early (char * name, char * cmdline, char * user, char * group)
Definition at line 1006 of file service.c.
{
    void *instances, *instance, *command, *respawn;
    char *t;
    blob_buf_init(&b, 0);
    blobmsg_add_string(&b, "name", name);
    instances = blobmsg_open_table(&b, "instances");
    instance = blobmsg_open_table(&b, "instance1");
    command = blobmsg_open_array(&b, "command");
    t = strtok(cmdline, " ");
    while (t) {
        blobmsg_add_string(&b, NULL, t);
        t = strtok(NULL, " ");
    }
    blobmsg_close_array(&b, command);
    respawn = blobmsg_open_array(&b, "respawn");
    blobmsg_add_string(&b, NULL, "3600");
    blobmsg_add_string(&b, NULL, "1");
    blobmsg_add_string(&b, NULL, "0");
    blobmsg_close_array(&b, respawn);
    if (user)
        blobmsg_add_string(&b, "user", user);
    if (group)
        blobmsg_add_string(&b, "group", group);
    blobmsg_close_table(&b, instance);
    blobmsg_close_table(&b, instances);
    return service_handle_set(NULL, NULL, NULL, "add", b.head);
}
References b, blob_buf_init(), blobmsg_add_string(), blobmsg_close_array(), blobmsg_close_table(), blobmsg_open_array(), blobmsg_open_table(), cmdline(), blob_buf::head, ubus_object::name, respawn, and service_handle_set().
Referenced by state_enter().
service_stop_all()
void service_stop_all (void)
Definition at line 673 of file service.c.
{
    unsigned int term_timeout = 0;
    service_avl_stop_all(&containers, &term_timeout);
    service_avl_stop_all(&services, &term_timeout);
    procd_inittab_kill();
    sleep(term_timeout);
}
References containers, procd_inittab_kill(), service_avl_stop_all(), services, and service_instance::term_timeout.
Referenced by sysupgrade().
service_stopped()
void service_stopped (struct service * s)
Definition at line 1038 of file service.c.
{
    if (s->deleted && avl_is_empty(&s->instances.avl)) {
        if (s->container) {
            service_event("container.stop", s->name, NULL);
            avl_delete(&containers, &s->avl);
        } else {
            service_event("service.stop", s->name, NULL);
            avl_delete(&services, &s->avl);
        }
        trigger_del(s);
        service_validate_del(s);
        free(s->trigger);
        free(s);
    }
}
References service::avl, vlist_tree::avl, avl_delete(), avl_is_empty(), service::container, containers, service::deleted, service::instances, service::name, service_event(), service_validate_del(), services, service::trigger, and trigger_del().
Referenced by instance_delete(), and service_delete().
service_validate_add()
void service_validate_add (struct service * s, struct blob_attr * attr)
Definition at line 115 of file validate.c.
{
    struct blob_attr *tb[__SERVICE_VAL_MAX];
    struct validate *v;
    char *type, *package;
    struct blob_attr *cur;
    int rem;
    blobmsg_parse(service_validate_attrs, __SERVICE_VAL_MAX, tb, blobmsg_data(msg), blobmsg_data_len(msg));
    if (!tb[SERVICE_VAL_PACKAGE] || !tb[SERVICE_VAL_TYPE] || !tb[SERVICE_VAL_DATA])
        return;
    v = calloc_a(sizeof(*v), &package, blobmsg_data_len(tb[SERVICE_VAL_PACKAGE]) + 1,
             &type, blobmsg_data_len(tb[SERVICE_VAL_TYPE]) + 1);
    if (!v)
        return;
    v->type = type;
    v->avl.key = v->package = package;
    strcpy(v->package, blobmsg_get_string(tb[SERVICE_VAL_PACKAGE]));
    strcpy(v->type, blobmsg_get_string(tb[SERVICE_VAL_TYPE]));
    list_add(&v->list, &s->validators);
    if (avl_insert(&validators, &v->avl)) {
        free(v);
        return;
    }
    avl_init(&v->rules, avl_strcmp, false, NULL);
    blobmsg_for_each_attr(cur, tb[SERVICE_VAL_DATA], rem) {
        char *option;
        char *rule;
        struct vrule *vr = calloc_a(sizeof(*vr), &option, strlen(blobmsg_name(cur)) + 1,
            &rule, strlen(blobmsg_get_string(cur)) + 1);
        vr->avl.key = vr->option = option;
        vr->rule = rule;
        strcpy(vr->option, blobmsg_name(cur));
        strcpy(vr->rule, blobmsg_get_string(cur));
        if (avl_insert(&v->rules, &vr->avl))
            free(vr);
    }
}
References __SERVICE_VAL_MAX, validate::avl, vrule::avl, avl_init(), avl_insert(), avl_strcmp(), blobmsg_data(), blobmsg_data_len(), blobmsg_for_each_attr, blobmsg_get_string(), blobmsg_name(), blobmsg_parse(), calloc_a, avl_node::key, validate::list, list_add(), vrule::option, validate::package, vrule::rule, validate::rules, SERVICE_VAL_DATA, SERVICE_VAL_PACKAGE, SERVICE_VAL_TYPE, service_validate_attrs, type, validate::type, and service::validators.
Referenced by service_update().
service_validate_del()
void service_validate_del (struct service * s)
Definition at line 95 of file validate.c.
{
    struct validate *v, *n;
    if (list_empty(&s->validators))
        return;
        list_for_each_entry_safe(v, n, &s->validators, list) {
        struct vrule *vr, *a;
        avl_remove_all_elements(&v->rules, vr, avl, a)
            free(vr);
        avl_delete(&validators, &v->avl);
        list_del(&v->list);
        free(v);
    }
}
References validate::avl, vrule::avl, avl_delete(), avl_remove_all_elements, validate::list, list_del(), list_empty(), list_for_each_entry_safe, validate::rules, and service::validators.
Referenced by service_stopped(), and service_update().
service_validate_dump()
void service_validate_dump (struct blob_buf * b, struct service * s)
Definition at line 74 of file validate.c.
{
    struct validate *v;
    void *i = blobmsg_open_array(b, "validate");
        list_for_each_entry(v, &s->validators, list) {
        struct vrule *vr;
        void *k, *j = blobmsg_open_table(b, "validate");
        blobmsg_add_string(b, "package", v->package);
                blobmsg_add_string(b, "type", v->type);
        k = blobmsg_open_table(b, "rules");
        avl_for_each_element(&v->rules, vr, avl)
                    blobmsg_add_string(b, vr->option, vr->rule);
        blobmsg_close_table(b, k);
        blobmsg_close_table(b, j);
    }
    blobmsg_close_array(b, i);
}
References vrule::avl, avl_for_each_element, b, blobmsg_add_string(), blobmsg_close_array(), blobmsg_close_table(), blobmsg_open_array(), blobmsg_open_table(), validate::list, list_for_each_entry, vrule::option, validate::package, vrule::rule, validate::rules, validate::type, and service::validators.
Referenced by service_dump().
service_validate_dump_all()
void service_validate_dump_all (struct blob_buf * b, char * p, char * s)
Definition at line 38 of file validate.c.
{
    struct json_object *r = json_object_new_object();
    struct validate *v;
    if (!r)
        return;
    avl_for_each_element(&validators, v, avl) {
        struct json_object *o, *t;
        struct vrule *vr;
        if (p && strcmp(p, v->package))
            continue;
        if (s && strcmp(s, v->type))
            continue;
        json_object_object_get_ex(r, v->package, &o);
        if (!o) {
            o = json_object_new_object();
            json_object_object_add(r, v->package, o);
        }
        json_object_object_get_ex(o, v->type, &t);
        if (!t) {
            t = json_object_new_object();
            json_object_object_add(o, v->type, t);
        }
        avl_for_each_element(&v->rules, vr, avl)
            json_object_object_add(t, vr->option, json_object_new_string(vr->rule));
    }
    blobmsg_add_object(b, r);
    json_object_put(r);
}
References validate::avl, vrule::avl, avl_for_each_element, b, blobmsg_add_object(), vrule::option, validate::package, r, vrule::rule, validate::rules, and validate::type.
Referenced by service_handle_validate().
Variable Documentation
containers
struct avl_tree containers extern
Referenced by container_handle_console(), service_handle_delete(), service_handle_list(), service_handle_set(), service_handle_signal(), service_handle_state(), service_handle_update(), service_stop_all(), and service_stopped().
services
struct avl_tree services extern
Referenced by service_get_data(), service_handle_delete(), service_handle_list(), service_handle_set(), service_handle_signal(), service_handle_state(), service_handle_update(), service_handle_watchdog(), service_stop_all(), and service_stopped().