zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/jail/preload.c File Reference
preload.c File Reference
#include <sys/types.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <dlfcn.h>
#include "log.h"
#include "seccomp.h"
#include "../preload.h"
Macros
#define _GNU_SOURCE
Functions
static int __preload_main__ (int argc, char **argv, char **envp)
int __libc_start_main (main_t main, int argc, char **argv, ElfW(auxv_t) *auxvec, __typeof(main) init, void(*fini)(void), void(*rtld_fini)(void), void *stack_end)
void __uClibc_main (main_t main, int argc, char **argv, void(*app_init)(void), void(*app_fini)(void), void(*rtld_fini)(void), void *stack_end attribute_unused)
Variables
static main_t __main__
int debug
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 14 of file preload.c.
Function Documentation
__libc_start_main()
int __libc_start_main (main_t main, int argc, char ** argv, ElfW(auxv_t) * auxvec, __typeof(main) init, void(* fini)(void), void(* rtld_fini)(void), void * stack_end)
Definition at line 53 of file preload.c.
{
    start_main_t __start_main__;
    __start_main__ = dlsym(RTLD_NEXT, "__libc_start_main");
    if (!__start_main__) {
        INFO("failed to find __libc_start_main %s\n", dlerror());
        return -1;
    }
    __main__ = main;
    return (*__start_main__)(__preload_main__, argc, argv, auxvec,
        init, fini, rtld_fini, stack_end);
}
References __main__, __preload_main__(), INFO, and main().
__preload_main__()
static int __preload_main__ (int argc, char ** argv, char ** envp) static
Definition at line 28 of file preload.c.
{
    char *env_file = getenv("SECCOMP_FILE");
    char *env_debug = getenv("SECCOMP_DEBUG");
    if (!env_file || !env_file[0]) {
        ERROR("SECCOMP_FILE not specified\n");
        return -1;
    }
    if (env_debug)
        debug = atoi(env_debug);
    else
        debug = 0;
    if (install_syscall_filter(*argv, env_file))
        return -1;
    unsetenv("LD_PRELOAD");
    unsetenv("SECCOMP_DEBUG");
    unsetenv("SECCOMP_FILE");
    return (*__main__)(argc, argv, envp);
}
References __main__, debug, ERROR, and install_syscall_filter().
Referenced by __libc_start_main(), and __uClibc_main().
__uClibc_main()
void __uClibc_main (main_t main, int argc, char ** argv, void(* app_init)(void), void(* app_fini)(void), void(* rtld_fini)(void), void *stack_end attribute_unused)
Definition at line 76 of file preload.c.
{
    uClibc_main __start_main__;
    __start_main__ = dlsym(RTLD_NEXT, "__uClibc_main");
    if (!__start_main__) {
        INFO("failed to find __uClibc_main %s\n", dlerror());
        return;
    }
    __main__ = main;
    return (*__start_main__)(__preload_main__, argc, argv,
        app_init, app_fini, rtld_fini, stack_end);
}
References __main__, __preload_main__(), INFO, and main().
Variable Documentation
__main__
main_t __main__ static
Definition at line 25 of file preload.c.
Referenced by __libc_start_main(), __preload_main__(), and __uClibc_main().
debug
int debug
Definition at line 26 of file preload.c.
Referenced by __preload_main__().