zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/ubus/examples/client.c File Reference
client.c File Reference
#include <sys/time.h>
#include <unistd.h>
#include <libubox/ustream.h>
#include "libubus.h"
#include "count.h"
Enumerations
enum { RETURN_CODE , __RETURN_MAX }
Functions
static void test_client_subscribe_cb (struct ubus_context *ctx, struct ubus_object *obj)
static void test_client_notify_cb (struct uloop_timeout *timeout)
static void test_count_data_cb (struct ubus_request *req, int type, struct blob_attr *msg)
static void test_count (struct uloop_timeout *timeout)
static void test_client_fd_data_cb (struct ustream *s, int bytes)
static void test_client_fd_cb (struct ubus_request *req, int fd)
static void test_client_complete_cb (struct ubus_request *req, int ret)
static void client_main (void)
int main (int argc, char **argv)
Variables
static struct ubus_context * ctx
static struct blob_buf b
static struct ubus_object test_client_object
static const struct blobmsg_policy return_policy [__RETURN_MAX]
static struct uloop_timeout notify_timer
static struct uloop_timeout count_timer
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
RETURN_CODE
__RETURN_MAX
Definition at line 59 of file client.c.
     {
    RETURN_CODE,
    __RETURN_MAX,
};
Function Documentation
client_main()
static void client_main (void) static
Definition at line 174 of file client.c.
{
    static struct ubus_request req;
    uint32_t id;
    int ret;
    ret = ubus_add_object(ctx, &test_client_object);
    if (ret) {
        fprintf(stderr, "Failed to add_object object: %s\n", ubus_strerror(ret));
        return;
    }
    if (ubus_lookup_id(ctx, "test", &id)) {
        fprintf(stderr, "Failed to look up test object\n");
        return;
    }
    blob_buf_init(&b, 0);
    blobmsg_add_u32(&b, "id", test_client_object.id);
    ubus_invoke(ctx, id, "watch", b.head, NULL, 0, 3000);
    test_client_notify_cb(&notify_timer);
    blob_buf_init(&b, 0);
    blobmsg_add_string(&b, "msg", "blah");
    ubus_invoke_async(ctx, id, "hello", b.head, &req);
    req.fd_cb = test_client_fd_cb;
    req.complete_cb = test_client_complete_cb;
    ubus_complete_request_async(ctx, &req);
    uloop_timeout_set(&count_timer, 2000);
    uloop_run();
}
References b, blob_buf_init(), blobmsg_add_string(), blobmsg_add_u32(), ubus_request::complete_cb, count_timer, ctx, ubus_request::fd_cb, blob_buf::head, id, ubus_object::id, notify_timer, test_client_complete_cb(), test_client_fd_cb(), test_client_notify_cb(), test_client_object, ubus_add_object(), ubus_complete_request_async(), ubus_invoke(), ubus_invoke_async(), ubus_lookup_id(), ubus_strerror(), uloop_run(), and uloop_timeout_set().
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 208 of file client.c.
{
    const char *ubus_socket = NULL;
    int ch;
    while ((ch = getopt(argc, argv, "cs:")) != -1) {
        switch (ch) {
        case 's':
            ubus_socket = optarg;
            break;
        default:
            break;
        }
    }
    uloop_init();
    ctx = ubus_connect(ubus_socket);
    if (!ctx) {
        fprintf(stderr, "Failed to connect to ubus\n");
        return -1;
    }
    ubus_add_uloop(ctx);
    client_main();
    ubus_free(ctx);
    uloop_done();
    return 0;
}
References client_main(), ctx, ubus_add_uloop(), ubus_connect(), ubus_free(), ubus_socket, uloop_done(), and uloop_init().
test_client_complete_cb()
static void test_client_complete_cb (struct ubus_request * req, int ret) static
Definition at line 169 of file client.c.
{
    fprintf(stderr, "completed request, ret: %d\n", ret);
}
Referenced by client_main().
test_client_fd_cb()
static void test_client_fd_cb (struct ubus_request * req, int fd) static
Definition at line 159 of file client.c.
{
    static struct ustream_fd test_fd;
    fprintf(stderr, "Got fd from the server, watching...\n");
    test_fd.stream.notify_read = test_client_fd_data_cb;
    ustream_fd_init(&test_fd, fd);
}
References ustream_fd::fd, ustream::notify_read, ustream_fd::stream, test_client_fd_data_cb(), and ustream_fd_init().
Referenced by client_main().
test_client_fd_data_cb()
static void test_client_fd_data_cb (struct ustream * s, int bytes) static
Definition at line 141 of file client.c.
{
    char *data, *sep;
    int len;
    data = ustream_get_read_buf(s, &len);
    if (len < 1)
        return;
    sep = strchr(data, '\n');
    if (!sep)
        return;
    *sep = 0;
    fprintf(stderr, "Got line: %s\n", data);
    ustream_consume(s, sep + 1 - data);
}
References ustream_consume(), and ustream_get_read_buf().
Referenced by test_client_fd_cb().
test_client_notify_cb()
static void test_client_notify_cb (struct uloop_timeout * timeout) static
Definition at line 34 of file client.c.
{
    static int counter = 0;
    int err;
    struct timeval tv1, tv2;
    int max = 1000;
    long delta;
    int i = 0;
    blob_buf_init(&b, 0);
    blobmsg_add_u32(&b, "counter", counter++);
    gettimeofday(&tv1, NULL);
    for (i = 0; i < max; i++)
        err = ubus_notify(ctx, &test_client_object, "ping", b.head, 1000);
    gettimeofday(&tv2, NULL);
    if (err)
        fprintf(stderr, "Notify failed: %s\n", ubus_strerror(err));
    delta = (tv2.tv_sec - tv1.tv_sec) * 1000000 + (tv2.tv_usec - tv1.tv_usec);
    fprintf(stderr, "Avg time per iteration: %ld usec\n", delta / max);
    uloop_timeout_set(timeout, 1000);
}
References b, blob_buf_init(), blobmsg_add_u32(), ctx, err, blob_buf::head, test_client_object, timeout, ubus_notify(), ubus_strerror(), and uloop_timeout_set().
Referenced by client_main().
test_client_subscribe_cb()
static void test_client_subscribe_cb (struct ubus_context * ctx, struct ubus_object * obj) static
Definition at line 25 of file client.c.
{
    fprintf(stderr, "Subscribers active: %d\n", obj->has_subscribers);
}
References ubus_object::has_subscribers.
test_count()
static void test_count (struct uloop_timeout * timeout) static
Definition at line 88 of file client.c.
{
    enum {
        COUNT_TO_MIN = 10000,
        COUNT_TO_MAX = 1000000,
        PROGRESSION  = 100,
    };
    uint32_t id;
    static uint32_t count_to = 100000;
    static int count_progression = PROGRESSION;
    char *s;
    if (count_to <= COUNT_TO_MIN)
        count_progression = PROGRESSION;
    else if (count_to >= COUNT_TO_MAX)
        count_progression = -PROGRESSION;
    count_to += count_progression;
    s = count_to_number(count_to);
    if (!s) {
        fprintf(stderr, "Could not allocate memory to count up to '%u'\n", count_to);
        return;
    }
    fprintf(stderr, "Sending count up to '%u'; string has length '%u'\n",
            count_to, (uint32_t)strlen(s));
    blob_buf_init(&b, 0);
    blobmsg_add_u32(&b, "to", count_to);
    blobmsg_add_string(&b, "string", s);
    if (ubus_lookup_id(ctx, "test", &id)) {
        free(s);
        fprintf(stderr, "Failed to look up test object\n");
        return;
    }
    ubus_invoke(ctx, id, "count", b.head, test_count_data_cb, &count_to, 5000);
    free(s);
    uloop_timeout_set(timeout, 2000);
}
References b, blob_buf_init(), blobmsg_add_string(), blobmsg_add_u32(), count_to_number(), ctx, blob_buf::head, id, test_count_data_cb(), timeout, ubus_invoke(), ubus_lookup_id(), and uloop_timeout_set().
test_count_data_cb()
static void test_count_data_cb (struct ubus_request * req, int type, struct blob_attr * msg) static
Definition at line 68 of file client.c.
{
    struct blob_attr *tb[__RETURN_MAX];
    int rc;
    uint32_t count_to = *(uint32_t *)req->priv;
    blobmsg_parse(return_policy, __RETURN_MAX, tb, blob_data(msg), blob_len(msg));
    if (!tb[RETURN_CODE]) {
        fprintf(stderr, "No return code received from server\n");
        return;
    }
    rc = blobmsg_get_u32(tb[RETURN_CODE]);
    if (rc)
        fprintf(stderr, "Corruption of data with count up to '%u'\n", count_to);
    else
        fprintf(stderr, "Server validated our count up to '%u'\n", count_to);
}
References __RETURN_MAX, blob_data(), blob_len(), blobmsg_get_u32(), blobmsg_parse(), ubus_request::priv, rc(), RETURN_CODE, and return_policy.
Referenced by test_count().
Variable Documentation
b
struct blob_buf b static
Definition at line 23 of file client.c.
Referenced by client_main(), test_client_notify_cb(), and test_count().
count_timer
struct uloop_timeout count_timer static
Initial value:
= {
    .cb = test_count,
}
Definition at line 137 of file client.c.
{
    .cb = test_count,
};
Referenced by client_main().
ctx
struct ubus_context* ctx static
Definition at line 22 of file client.c.
Referenced by client_main(), main(), test_client_notify_cb(), and test_count().
notify_timer
struct uloop_timeout notify_timer static
Initial value:
= {
    .cb = test_client_notify_cb,
}
Definition at line 133 of file client.c.
{
    .cb = test_client_notify_cb,
};
Referenced by client_main().
return_policy
const struct blobmsg_policy return_policy[__RETURN_MAX] static
Initial value:
= {
    [RETURN_CODE] = { .name = "rc", .type = BLOBMSG_TYPE_INT32 },
}
Definition at line 64 of file client.c.
{
    [RETURN_CODE] = { .name = "rc", .type = BLOBMSG_TYPE_INT32 },
};
Referenced by test_count_data_cb().
test_client_object
struct ubus_object test_client_object static
Initial value:
= {
    .subscribe_cb = test_client_subscribe_cb,
}
Definition at line 30 of file client.c.
{
    .subscribe_cb = test_client_subscribe_cb,
};
Referenced by client_main(), and test_client_notify_cb().