zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/netifd/iprule.c File Reference
iprule.c File Reference
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <arpa/inet.h>
#include "netifd.h"
#include "device.h"
#include "interface.h"
#include "iprule.h"
#include "proto.h"
#include "ubus.h"
#include "system.h"
Enumerations
enum {
RULE_INTERFACE_IN , RULE_INTERFACE_OUT , RULE_INVERT , RULE_SRC ,
RULE_DEST , RULE_PRIORITY , RULE_TOS , RULE_FWMARK ,
RULE_LOOKUP , RULE_ACTION , RULE_GOTO , RULE_SUP_PREFIXLEN ,
RULE_UIDRANGE , RULE_DISABLED , __RULE_MAX
}
Functions
static bool rule_ready (struct iprule *rule)
static bool iprule_parse_mark (const char *mark, struct iprule *rule)
static void rule_in_cb (struct interface_user *dep, struct interface *iface, enum interface_event ev)
static void rule_out_cb (struct interface_user *dep, struct interface *iface, enum interface_event ev)
static void generic_interface_cb (struct interface_user *dep, struct interface *iface, enum interface_event ev)
void iprule_add (struct blob_attr *attr, bool v6)
void iprule_update_start (void)
void iprule_update_complete (void)
static int rule_cmp (const void *k1, const void *k2, void *ptr)
static void deregister_interfaces (struct iprule *rule)
static void register_interfaces (struct iprule *rule)
static void iprule_update_rule (struct vlist_tree *tree, struct vlist_node *node_new, struct vlist_node *node_old)
static void __init iprule_init_list (void)
Variables
struct vlist_tree iprules
static bool iprules_flushed = false
static unsigned int iprules_counter [2]
static const struct blobmsg_policy rule_attr [__RULE_MAX]
const struct uci_blob_param_list rule_attr_list
struct interface_user generic_listener
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
RULE_INTERFACE_IN
RULE_INTERFACE_OUT
RULE_INVERT
RULE_SRC
RULE_DEST
RULE_PRIORITY
RULE_TOS
RULE_FWMARK
RULE_LOOKUP
RULE_ACTION
RULE_GOTO
RULE_SUP_PREFIXLEN
RULE_UIDRANGE
RULE_DISABLED
__RULE_MAX
Definition at line 34 of file iprule.c.
     {
    RULE_INTERFACE_IN,
    RULE_INTERFACE_OUT,
    RULE_INVERT,
    RULE_SRC,
    RULE_DEST,
    RULE_PRIORITY,
    RULE_TOS,
    RULE_FWMARK,
    RULE_LOOKUP,
    RULE_ACTION,
    RULE_GOTO,
    RULE_SUP_PREFIXLEN,
    RULE_UIDRANGE,
    RULE_DISABLED,
    __RULE_MAX
};
Function Documentation
deregister_interfaces()
static void deregister_interfaces (struct iprule * rule) static
Definition at line 370 of file iprule.c.
{
    if (rule->flags & IPRULE_IN && rule->in_iface_user.iface)
        interface_remove_user(&rule->in_iface_user);
    if (rule->flags & IPRULE_OUT && rule->out_iface_user.iface)
        interface_remove_user(&rule->out_iface_user);
}
References iprule::flags, interface_user::iface, iprule::in_iface_user, interface_remove_user(), IPRULE_IN, IPRULE_OUT, and iprule::out_iface_user.
Referenced by iprule_update_rule().
generic_interface_cb()
static void generic_interface_cb (struct interface_user * dep, struct interface * iface, enum interface_event ev) static
Definition at line 175 of file iprule.c.
{
    struct iprule *rule;
    if (ev != IFEV_CREATE)
        return;
    /* add new interfaces to rules */
    vlist_for_each_element(&iprules, rule, node) {
        if (rule_ready(rule))
            continue;
        if ((rule->flags & IPRULE_OUT) && !strcmp(rule->out_iface, iface->name))
            interface_add_user(&rule->out_iface_user, iface);
        if ((rule->flags & IPRULE_IN) && !strcmp(rule->in_iface, iface->name))
            interface_add_user(&rule->in_iface_user, iface);
    }
}
References iprule::flags, IFEV_CREATE, iprule::in_iface, iprule::in_iface_user, interface_add_user(), IPRULE_IN, IPRULE_OUT, iprules, interface::name, iprule::out_iface, iprule::out_iface_user, rule_ready(), and vlist_for_each_element.
iprule_add()
void iprule_add (struct blob_attr * attr, bool v6)
Definition at line 201 of file iprule.c.
{
    struct blob_attr *tb[__RULE_MAX], *cur;
    struct iprule *rule;
    char *iface_name;
    int af = v6 ? AF_INET6 : AF_INET;
    blobmsg_parse(rule_attr, __RULE_MAX, tb, blobmsg_data(attr), blobmsg_data_len(attr));
    if ((cur = tb[RULE_DISABLED]) != NULL && blobmsg_get_bool(cur))
        return;
    rule = calloc(1, sizeof(*rule));
    if (!rule)
        return;
    rule->flags = v6 ? IPRULE_INET6 : IPRULE_INET4;
    rule->order = iprules_counter[rule->flags]++;
    if ((cur = tb[RULE_INVERT]) != NULL)
        rule->invert = blobmsg_get_bool(cur);
    if ((cur = tb[RULE_INTERFACE_IN]) != NULL) {
        iface_name = calloc(1, strlen(blobmsg_data(cur)) + 1);
        rule->in_iface = strcpy(iface_name, blobmsg_data(cur));
        rule->in_iface_user.cb = &rule_in_cb;
        rule->flags |= IPRULE_IN;
    }
    if ((cur = tb[RULE_INTERFACE_OUT]) != NULL) {
        iface_name = calloc(1, strlen(blobmsg_data(cur)) + 1);
        rule->out_iface = strcpy(iface_name, blobmsg_data(cur));
        rule->out_iface_user.cb = &rule_out_cb;
        rule->flags |= IPRULE_OUT;
    }
    if ((cur = tb[RULE_SRC]) != NULL) {
        if (!parse_ip_and_netmask(af, blobmsg_data(cur), &rule->src_addr, &rule->src_mask)) {
            D(INTERFACE, "Failed to parse rule source: %s", (char *) blobmsg_data(cur));
            goto error;
        }
        rule->flags |= IPRULE_SRC;
    }
    if ((cur = tb[RULE_DEST]) != NULL) {
        if (!parse_ip_and_netmask(af, blobmsg_data(cur), &rule->dest_addr, &rule->dest_mask)) {
            D(INTERFACE, "Failed to parse rule destination: %s", (char *) blobmsg_data(cur));
            goto error;
        }
        rule->flags |= IPRULE_DEST;
    }
    if ((cur = tb[RULE_PRIORITY]) != NULL) {
        rule->priority = blobmsg_get_u32(cur);
        rule->flags |= IPRULE_PRIORITY;
    }
    if ((cur = tb[RULE_TOS]) != NULL) {
        if ((rule->tos = blobmsg_get_u32(cur)) > 255) {
            D(INTERFACE, "Invalid TOS value: %u", blobmsg_get_u32(cur));
            goto error;
        }
        rule->flags |= IPRULE_TOS;
    }
    if ((cur = tb[RULE_FWMARK]) != NULL) {
        if (!iprule_parse_mark(blobmsg_data(cur), rule)) {
            D(INTERFACE, "Failed to parse rule fwmark: %s", (char *) blobmsg_data(cur));
            goto error;
        }
        /* flags set by iprule_parse_mark() */
    }
    if ((cur = tb[RULE_LOOKUP]) != NULL) {
        if (!system_resolve_rt_table(blobmsg_data(cur), &rule->lookup)) {
            D(INTERFACE, "Failed to parse rule lookup table: %s", (char *) blobmsg_data(cur));
            goto error;
        }
        rule->flags |= IPRULE_LOOKUP;
    }
    if ((cur = tb[RULE_SUP_PREFIXLEN]) != NULL) {
        rule->sup_prefixlen = blobmsg_get_u32(cur);
        rule->flags |= IPRULE_SUP_PREFIXLEN;
    }
    if ((cur = tb[RULE_UIDRANGE]) != NULL) {
        int ret = sscanf(blobmsg_get_string(cur), "%u-%u", &rule->uidrange_start, &rule->uidrange_end);
        if (ret == 1)
            rule->uidrange_end = rule->uidrange_start;
        else if (ret != 2) {
            D(INTERFACE, "Failed to parse UID range: %s", (char *) blobmsg_data(cur));
            goto error;
        }
        rule->flags |= IPRULE_UIDRANGE;
    }
    if ((cur = tb[RULE_ACTION]) != NULL) {
        if (!system_resolve_iprule_action(blobmsg_data(cur), &rule->action)) {
            D(INTERFACE, "Failed to parse rule action: %s", (char *) blobmsg_data(cur));
            goto error;
        }
        rule->flags |= IPRULE_ACTION;
    }
    if ((cur = tb[RULE_GOTO]) != NULL) {
        rule->gotoid = blobmsg_get_u32(cur);
        rule->flags |= IPRULE_GOTO;
    }
    vlist_add(&iprules, &rule->node, rule);
    return;
error:
    free(rule);
}
References __RULE_MAX, iprule::action, blobmsg_data(), blobmsg_data_len(), blobmsg_get_bool(), blobmsg_get_string(), blobmsg_get_u32(), blobmsg_parse(), interface_user::cb, D, iprule::dest_addr, iprule::dest_mask, iprule::flags, iprule::gotoid, iprule::in_iface, iprule::in_iface_user, iprule::invert, IPRULE_ACTION, IPRULE_DEST, IPRULE_GOTO, IPRULE_IN, IPRULE_INET4, IPRULE_INET6, IPRULE_LOOKUP, IPRULE_OUT, iprule_parse_mark(), IPRULE_PRIORITY, IPRULE_SRC, IPRULE_SUP_PREFIXLEN, IPRULE_TOS, IPRULE_UIDRANGE, iprules, iprules_counter, iprule::lookup, iprule::node, iprule::order, iprule::out_iface, iprule::out_iface_user, parse_ip_and_netmask(), iprule::priority, RULE_ACTION, rule_attr, RULE_DEST, RULE_DISABLED, RULE_FWMARK, RULE_GOTO, rule_in_cb(), RULE_INTERFACE_IN, RULE_INTERFACE_OUT, RULE_INVERT, RULE_LOOKUP, rule_out_cb(), RULE_PRIORITY, RULE_SRC, RULE_SUP_PREFIXLEN, RULE_TOS, RULE_UIDRANGE, iprule::src_addr, iprule::src_mask, iprule::sup_prefixlen, system_resolve_iprule_action(), system_resolve_rt_table(), iprule::tos, iprule::uidrange_end, iprule::uidrange_start, and vlist_add().
Referenced by config_parse_rule().
iprule_init_list()
static void __init iprule_init_list (void) static
Definition at line 431 of file iprule.c.
{
    vlist_init(&iprules, rule_cmp, iprule_update_rule);
    interface_add_user(&generic_listener, NULL);
}
References generic_listener, interface_add_user(), iprule_update_rule(), iprules, rule_cmp(), and vlist_init().
iprule_parse_mark()
static bool iprule_parse_mark (const char * mark, struct iprule * rule) static
Definition at line 88 of file iprule.c.
{
    char *s, *e;
    unsigned int n;
    if ((s = strchr(mark, '/')) != NULL)
        *s++ = 0;
    n = strtoul(mark, &e, 0);
    if (e == mark || *e)
        return false;
    rule->fwmark = n;
    rule->flags |= IPRULE_FWMARK;
    if (s) {
        n = strtoul(s, &e, 0);
        if (e == s || *e)
            return false;
        rule->fwmask = n;
        rule->flags |= IPRULE_FWMASK;
    }
    return true;
}
References iprule::flags, iprule::fwmark, iprule::fwmask, IPRULE_FWMARK, and IPRULE_FWMASK.
Referenced by iprule_add().
iprule_update_complete()
void iprule_update_complete (void)
Definition at line 333 of file iprule.c.
{
    vlist_flush(&iprules);
}
References iprules, and vlist_flush().
Referenced by config_init_rules().
iprule_update_rule()
static void iprule_update_rule (struct vlist_tree * tree, struct vlist_node * node_new, struct vlist_node * node_old) static
Definition at line 396 of file iprule.c.
{
    struct iprule *rule_old, *rule_new;
    rule_old = container_of(node_old, struct iprule, node);
    rule_new = container_of(node_new, struct iprule, node);
    if (node_old) {
        if (rule_ready(rule_old))
            system_del_iprule(rule_old);
        if (rule_old->flags & (IPRULE_IN | IPRULE_OUT))
            deregister_interfaces(rule_old);
        if (rule_old->in_iface)
            free(rule_old->in_iface);
        if (rule_old->out_iface)
            free(rule_old->out_iface);
        free(rule_old);
    }
    if (node_new) {
        /* interface based rules calls system_add_iprule over the event cb */
        if (rule_new->flags & (IPRULE_IN | IPRULE_OUT)) {
            register_interfaces(rule_new);
        } else {
            system_add_iprule(rule_new);
        }
    }
}
References container_of, deregister_interfaces(), iprule::flags, iprule::in_iface, IPRULE_IN, IPRULE_OUT, iprule::out_iface, register_interfaces(), rule_ready(), system_add_iprule(), and system_del_iprule().
Referenced by iprule_init_list().
iprule_update_start()
void iprule_update_start (void)
Definition at line 320 of file iprule.c.
{
    if (!iprules_flushed) {
        system_flush_iprules();
        iprules_flushed = true;
    }
    iprules_counter[0] = 1;
    iprules_counter[1] = 1;
    vlist_update(&iprules);
}
References iprules, iprules_counter, iprules_flushed, system_flush_iprules(), and vlist_update().
Referenced by config_init_rules().
register_interfaces()
static void register_interfaces (struct iprule * rule) static
Definition at line 379 of file iprule.c.
{
    struct interface *iface, *tmp;
    if (rule->flags & IPRULE_IN) {
        tmp = vlist_find(&interfaces, rule->in_iface, iface, node);
        if (tmp)
            interface_add_user(&rule->in_iface_user, tmp);
    }
    if (rule->flags & IPRULE_OUT) {
        tmp = vlist_find(&interfaces, rule->out_iface, iface, node);
        if (tmp)
            interface_add_user(&rule->out_iface_user, tmp);
    }
}
References iprule::flags, iprule::in_iface, iprule::in_iface_user, interface_add_user(), interfaces, IPRULE_IN, IPRULE_OUT, iprule::out_iface, iprule::out_iface_user, and vlist_find.
Referenced by iprule_update_rule().
rule_cmp()
static int rule_cmp (const void * k1, const void * k2, void * ptr) static
Definition at line 340 of file iprule.c.
{
    const struct iprule *r1 = k1, *r2 = k2;
    int ret;
    /* First compare the interface names */
    if (r1->flags & IPRULE_IN || r2->flags & IPRULE_IN) {
        char *str1 = r1->flags & IPRULE_IN ? r1->in_iface : "";
        char *str2 = r2->flags & IPRULE_IN ? r2->in_iface : "";
        ret = strcmp(str1, str2);
        if (ret)
            return ret;
    }
    if (r1->flags & IPRULE_OUT || r2->flags & IPRULE_OUT) {
        char *str1 = r1->flags & IPRULE_OUT ? r1->out_iface : "";
        char *str2 = r2->flags & IPRULE_OUT ? r2->out_iface : "";
        ret = strcmp(str1, str2);
        if (ret)
            return ret;
    }
    /* Next compare everything after the flags field */
    return memcmp(k1 + offsetof(struct iprule, flags),
              k2 + offsetof(struct iprule, flags),
              sizeof(struct iprule) - offsetof(struct iprule, flags));
}
References iprule::flags, iprule::in_iface, IPRULE_IN, IPRULE_OUT, and iprule::out_iface.
Referenced by iprule_init_list().
rule_in_cb()
static void rule_in_cb (struct interface_user * dep, struct interface * iface, enum interface_event ev) static
Definition at line 119 of file iprule.c.
{
    struct iprule *rule = container_of(dep, struct iprule, in_iface_user);
    switch (ev) {
    case IFEV_UP:
        if (!iface->l3_dev.dev)
            break;
        strcpy(rule->in_dev, iface->l3_dev.dev->ifname);
        if (rule_ready(rule))
            system_add_iprule(rule);
        break;
    case IFEV_DOWN:
    case IFEV_UP_FAILED:
    case IFEV_FREE:
        if (rule_ready(rule))
            system_del_iprule(rule);
        rule->in_dev[0] = 0;
        break;
    default:
        break;
    }
}
References container_of, device_user::dev, IFEV_DOWN, IFEV_FREE, IFEV_UP, IFEV_UP_FAILED, device::ifname, iprule::in_dev, iprule::in_iface_user, interface::l3_dev, rule_ready(), system_add_iprule(), and system_del_iprule().
Referenced by iprule_add().
rule_out_cb()
static void rule_out_cb (struct interface_user * dep, struct interface * iface, enum interface_event ev) static
Definition at line 147 of file iprule.c.
{
    struct iprule *rule = container_of(dep, struct iprule, out_iface_user);
    switch (ev) {
    case IFEV_UP:
        if (!iface->l3_dev.dev)
            break;
        strcpy(rule->out_dev, iface->l3_dev.dev->ifname);
        if (rule_ready(rule))
            system_add_iprule(rule);
        break;
    case IFEV_DOWN:
    case IFEV_UP_FAILED:
    case IFEV_FREE:
        if (rule_ready(rule))
            system_del_iprule(rule);
        rule->out_dev[0] = 0;
        break;
    default:
        break;
    }
}
References container_of, device_user::dev, IFEV_DOWN, IFEV_FREE, IFEV_UP, IFEV_UP_FAILED, device::ifname, interface::l3_dev, iprule::out_dev, iprule::out_iface_user, rule_ready(), system_add_iprule(), and system_del_iprule().
Referenced by iprule_add().
rule_ready()
static bool rule_ready (struct iprule * rule) static
Definition at line 76 of file iprule.c.
{
    if (rule->flags & IPRULE_OUT && !rule->out_dev[0])
        return false;
    if (rule->flags & IPRULE_IN && !rule->in_dev[0])
        return false;
    return true;
}
References iprule::flags, iprule::in_dev, IPRULE_IN, IPRULE_OUT, and iprule::out_dev.
Referenced by generic_interface_cb(), iprule_update_rule(), rule_in_cb(), and rule_out_cb().
Variable Documentation
generic_listener
struct interface_user generic_listener
Initial value:
= {
    .cb = generic_interface_cb
}
Definition at line 196 of file iprule.c.
{
    .cb = generic_interface_cb
};
Referenced by iprule_init_list().
iprules
struct vlist_tree iprules
Definition at line 30 of file iprule.c.
Referenced by generic_interface_cb(), iprule_add(), iprule_init_list(), iprule_update_complete(), and iprule_update_start().
iprules_counter
unsigned int iprules_counter[2] static
Definition at line 32 of file iprule.c.
Referenced by iprule_add(), and iprule_update_start().
iprules_flushed
bool iprules_flushed = false static
Definition at line 31 of file iprule.c.
Referenced by iprule_update_start().
rule_attr
const struct blobmsg_policy rule_attr[__RULE_MAX] static
Initial value:
= {
    [RULE_INTERFACE_IN] = { .name = "in", .type = BLOBMSG_TYPE_STRING },
    [RULE_INTERFACE_OUT] = { .name = "out", .type = BLOBMSG_TYPE_STRING },
    [RULE_INVERT] = { .name = "invert", .type = BLOBMSG_TYPE_BOOL },
    [RULE_SRC] = { .name = "src", .type = BLOBMSG_TYPE_STRING },
    [RULE_DEST] = { .name = "dest", .type = BLOBMSG_TYPE_STRING },
    [RULE_PRIORITY] = { .name = "priority", .type = BLOBMSG_TYPE_INT32 },
    [RULE_TOS] = { .name = "tos", .type = BLOBMSG_TYPE_INT32 },
    [RULE_FWMARK] = { .name = "mark", .type = BLOBMSG_TYPE_STRING },
    [RULE_LOOKUP] = { .name = "lookup", .type = BLOBMSG_TYPE_STRING },
    [RULE_SUP_PREFIXLEN] = { .name = "suppress_prefixlength", .type = BLOBMSG_TYPE_INT32 },
    [RULE_UIDRANGE] = { .name = "uidrange", .type = BLOBMSG_TYPE_STRING },
    [RULE_ACTION] = { .name = "action", .type = BLOBMSG_TYPE_STRING },
    [RULE_GOTO]   = { .name = "goto", .type = BLOBMSG_TYPE_INT32 },
    [RULE_DISABLED] = { .name = "disabled", .type = BLOBMSG_TYPE_BOOL },
}
Definition at line 52 of file iprule.c.
{
    [RULE_INTERFACE_IN] = { .name = "in", .type = BLOBMSG_TYPE_STRING },
    [RULE_INTERFACE_OUT] = { .name = "out", .type = BLOBMSG_TYPE_STRING },
    [RULE_INVERT] = { .name = "invert", .type = BLOBMSG_TYPE_BOOL },
    [RULE_SRC] = { .name = "src", .type = BLOBMSG_TYPE_STRING },
    [RULE_DEST] = { .name = "dest", .type = BLOBMSG_TYPE_STRING },
    [RULE_PRIORITY] = { .name = "priority", .type = BLOBMSG_TYPE_INT32 },
    [RULE_TOS] = { .name = "tos", .type = BLOBMSG_TYPE_INT32 },
    [RULE_FWMARK] = { .name = "mark", .type = BLOBMSG_TYPE_STRING },
    [RULE_LOOKUP] = { .name = "lookup", .type = BLOBMSG_TYPE_STRING },
    [RULE_SUP_PREFIXLEN] = { .name = "suppress_prefixlength", .type = BLOBMSG_TYPE_INT32 },
    [RULE_UIDRANGE] = { .name = "uidrange", .type = BLOBMSG_TYPE_STRING },
    [RULE_ACTION] = { .name = "action", .type = BLOBMSG_TYPE_STRING },
    [RULE_GOTO]   = { .name = "goto", .type = BLOBMSG_TYPE_INT32 },
    [RULE_DISABLED] = { .name = "disabled", .type = BLOBMSG_TYPE_BOOL },
};
Referenced by iprule_add().
rule_attr_list
const struct uci_blob_param_list rule_attr_list
Initial value:
= {
    .n_params = __RULE_MAX,
    .params = rule_attr,
}
Definition at line 69 of file iprule.c.
{
    .n_params = __RULE_MAX,
    .params = rule_attr,
};
Referenced by config_parse_rule().