zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/libubox/blobmsg_json.h File Reference
blobmsg_json.h File Reference
#include <stdbool.h>
#include "blobmsg.h"
Typedefs
typedef const char *(* blobmsg_json_format_t) (void *priv, struct blob_attr *attr)
Functions
bool blobmsg_add_object (struct blob_buf *b, struct json_object *obj)
bool blobmsg_add_json_element (struct blob_buf *b, const char *name, struct json_object *obj)
bool blobmsg_add_json_from_string (struct blob_buf *b, const char *str)
bool blobmsg_add_json_from_file (struct blob_buf *b, const char *file)
char * blobmsg_format_json_with_cb (struct blob_attr *attr, bool list, blobmsg_json_format_t cb, void *priv, int indent)
static char * blobmsg_format_json (struct blob_attr *attr, bool list)
static char * blobmsg_format_json_indent (struct blob_attr *attr, bool list, int indent)
char * blobmsg_format_json_value_with_cb (struct blob_attr *attr, blobmsg_json_format_t cb, void *priv, int indent)
static char * blobmsg_format_json_value (struct blob_attr *attr)
static char * blobmsg_format_json_value_indent (struct blob_attr *attr, int indent)
Typedef Documentation
blobmsg_json_format_t
typedef const char *(* blobmsg_json_format_t) (void *priv, struct blob_attr *attr)
Definition at line 29 of file blobmsg_json.h.
Function Documentation
blobmsg_add_json_element()
bool blobmsg_add_json_element (struct blob_buf * b, const char * name, struct json_object * obj)
Definition at line 47 of file blobmsg_json.c.
{
    bool ret = true;
    void *c;
    switch (json_object_get_type(obj)) {
    case json_type_object:
        c = blobmsg_open_table(b, name);
        ret = blobmsg_add_object(b, obj);
        blobmsg_close_table(b, c);
        break;
    case json_type_array:
        c = blobmsg_open_array(b, name);
        ret = blobmsg_add_array(b, json_object_get_array(obj));
        blobmsg_close_array(b, c);
        break;
    case json_type_string:
        blobmsg_add_string(b, name, json_object_get_string(obj));
        break;
    case json_type_boolean:
        blobmsg_add_u8(b, name, json_object_get_boolean(obj));
        break;
    case json_type_int: {
        int64_t i64 = json_object_get_int64(obj);
        if (i64 >= INT32_MIN && i64 <= INT32_MAX) {
            blobmsg_add_u32(b, name, (uint32_t)i64);
        } else {
            blobmsg_add_u64(b, name, (uint64_t)i64);
        }
        break;
    }
    case json_type_double:
        blobmsg_add_double(b, name, json_object_get_double(obj));
        break;
    case json_type_null:
        blobmsg_add_field(b, BLOBMSG_TYPE_UNSPEC, name, NULL, 0);
        break;
    default:
        return false;
    }
    return ret;
}
References b, blobmsg_add_array(), blobmsg_add_double(), blobmsg_add_field(), blobmsg_add_object(), blobmsg_add_string(), blobmsg_add_u32(), blobmsg_add_u64(), blobmsg_add_u8(), blobmsg_close_array(), blobmsg_close_table(), blobmsg_open_array(), blobmsg_open_table(), and BLOBMSG_TYPE_UNSPEC.
Referenced by blobmsg_add_array(), blobmsg_add_object(), handle_file(), handle_file(), and rule_handle_file().
blobmsg_add_json_from_file()
bool blobmsg_add_json_from_file (struct blob_buf * b, const char * file)
Definition at line 107 of file blobmsg_json.c.
{
    return __blobmsg_add_json(b, json_object_from_file(file));
}
References __blobmsg_add_json(), and b.
Referenced by conf_load(), config_init_board(), install_syscall_filter(), parseOCI(), parseOCIcapabilities_from_file(), rpc_login_setup_acl_file(), and ubusd_acl_load_file().
blobmsg_add_json_from_string()
bool blobmsg_add_json_from_string (struct blob_buf * b, const char * str)
Definition at line 112 of file blobmsg_json.c.
{
    return __blobmsg_add_json(b, json_tokener_parse(str));
}
References __blobmsg_add_json(), and b.
Referenced by jshn_format(), main(), ubus_cli_call(), and ubus_cli_send().
blobmsg_add_object()
bool blobmsg_add_object (struct blob_buf * b, struct json_object * obj)
Definition at line 26 of file blobmsg_json.c.
{
    json_object_object_foreach(obj, key, val) {
        if (!blobmsg_add_json_element(b, key, val))
            return false;
    }
    return true;
}
References b, and blobmsg_add_json_element().
Referenced by __blobmsg_add_json(), blobmsg_add_json_element(), rpc_plugin_parse_exec(), service_validate_dump_all(), and vjson_parse_token().
blobmsg_format_json()
static char * blobmsg_format_json (struct blob_attr * attr, bool list) inline static
Definition at line 35 of file blobmsg_json.h.
{
    return blobmsg_format_json_with_cb(attr, list, NULL, NULL, -1);
}
References blobmsg_format_json_with_cb().
Referenced by hotplug_handler_debug(), main(), print_event(), proto_shell_handler(), rpc_plugin_call(), rule_handle_error(), rule_handle_error(), test_notify(), ubus_cli_get_monitor_data(), watch_notify_cb(), and wireless_device_run_handler().
blobmsg_format_json_indent()
static char * blobmsg_format_json_indent (struct blob_attr * attr, bool list, int indent) inline static
Definition at line 40 of file blobmsg_json.h.
{
    return blobmsg_format_json_with_cb(attr, list, NULL, NULL, indent);
}
References blobmsg_format_json_with_cb().
Referenced by cert_dump_blob(), jshn_format(), print_syscalls(), receive_call_result_data(), uxc_create(), uxc_list(), uxc_set(), and uxc_state().
blobmsg_format_json_value()
static char * blobmsg_format_json_value (struct blob_attr * attr) inline static
Definition at line 49 of file blobmsg_json.h.
{
    return blobmsg_format_json_value_with_cb(attr, NULL, NULL, -1);
}
References blobmsg_format_json_value_with_cb().
blobmsg_format_json_value_indent()
static char * blobmsg_format_json_value_indent (struct blob_attr * attr, int indent) inline static
Definition at line 54 of file blobmsg_json.h.
{
    return blobmsg_format_json_value_with_cb(attr, NULL, NULL, indent);
}
References blobmsg_format_json_value_with_cb().
blobmsg_format_json_value_with_cb()
char * blobmsg_format_json_value_with_cb (struct blob_attr * attr, blobmsg_json_format_t cb, void * priv, int indent)
Definition at line 356 of file blobmsg_json.c.
{
    struct strbuf s = {0};
    char *ret;
    setup_strbuf(&s, attr, cb, priv, indent);
    if (!s.buf)
        return NULL;
    blobmsg_format_element(&s, attr, true, false);
    if (!s.len) {
        free(s.buf);
        return NULL;
    }
    ret = realloc(s.buf, s.pos + 1);
    if (!ret) {
        free(s.buf);
        return NULL;
    }
    ret[s.pos] = 0;
    return ret;
}
References blobmsg_format_element(), strbuf::buf, strbuf::indent, strbuf::len, strbuf::pos, strbuf::priv, and setup_strbuf().
Referenced by blobmsg_format_json_value(), and blobmsg_format_json_value_indent().
blobmsg_format_json_with_cb()
char * blobmsg_format_json_with_cb (struct blob_attr * attr, bool list, blobmsg_json_format_t cb, void * priv, int indent)
Definition at line 322 of file blobmsg_json.c.
{
    struct strbuf s = {0};
    bool array;
    char *ret;
    setup_strbuf(&s, attr, cb, priv, indent);
    if (!s.buf)
        return NULL;
    array = blob_is_extended(attr) &&
        blobmsg_type(attr) == BLOBMSG_TYPE_ARRAY;
    if (list)
        blobmsg_format_json_list(&s, blobmsg_data(attr), blobmsg_data_len(attr), array);
    else
        blobmsg_format_element(&s, attr, false, false);
    if (!s.len) {
        free(s.buf);
        return NULL;
    }
    ret = realloc(s.buf, s.pos + 1);
    if (!ret) {
        free(s.buf);
        return NULL;
    }
    ret[s.pos] = 0;
    return ret;
}
References blob_is_extended(), blobmsg_data(), blobmsg_data_len(), blobmsg_format_element(), blobmsg_format_json_list(), BLOBMSG_TYPE_ARRAY, strbuf::buf, strbuf::indent, strbuf::len, strbuf::pos, strbuf::priv, and setup_strbuf().
Referenced by blobmsg_format_json(), blobmsg_format_json_indent(), and receive_list_result().