zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/ustp/ubus.c File Reference
ubus.c File Reference
#include <libubus.h>
#include <libubox/uloop.h>
#include "config.h"
#include "mstp.h"
#include "worker.h"
#include "ubus.h"
Enumerations
enum bridge_config_attr {
BRIDGE_CONFIG_NAME , BRIDGE_CONFIG_PROTO , BRIDGE_CONFIG_FWD_DELAY , BRIDGE_CONFIG_HELLO_TIME ,
BRIDGE_CONFIG_MAX_AGE , BRIDGE_CONFIG_AGEING_TIME , __BRIDGE_CONFIG_MAX
}
enum bridge_state_attr { BRIDGE_STATE_NAME , BRIDGE_STATE_ENABLED , __BRIDGE_STATE_MAX }
Functions
static bool ubus_set_bridge_config (struct blob_attr *attr)
static int ubus_add_bridge (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int ubus_bridge_state (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int netifd_device_cb (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static void netifd_sub_cb (struct uloop_timeout *t)
static void netifd_device_remove_cb (struct ubus_context *ctx, struct ubus_subscriber *obj, uint32_t id)
static void ubus_connect_handler (struct ubus_context *ctx)
void ustp_ubus_init (void)
void ustp_ubus_exit (void)
Variables
struct blob_buf b
static const struct blobmsg_policy bridge_config_policy [__BRIDGE_CONFIG_MAX]
static const struct blobmsg_policy bridge_state_policy [__BRIDGE_STATE_MAX]
static const struct ubus_method ustp_methods []
static struct ubus_object_type ustp_object_type
static struct ubus_object ustp_object
static struct ubus_auto_conn conn
static struct ubus_subscriber netifd_sub
static struct uloop_timeout netifd_sub_timer
Enumeration Type Documentation
bridge_config_attr
enum bridge_config_attr
Enumerator
BRIDGE_CONFIG_NAME
BRIDGE_CONFIG_PROTO
BRIDGE_CONFIG_FWD_DELAY
BRIDGE_CONFIG_HELLO_TIME
BRIDGE_CONFIG_MAX_AGE
BRIDGE_CONFIG_AGEING_TIME
__BRIDGE_CONFIG_MAX
Definition at line 23 of file ubus.c.
{
    BRIDGE_CONFIG_NAME,
    BRIDGE_CONFIG_PROTO,
    BRIDGE_CONFIG_FWD_DELAY,
    BRIDGE_CONFIG_HELLO_TIME,
    BRIDGE_CONFIG_MAX_AGE,
    BRIDGE_CONFIG_AGEING_TIME,
    __BRIDGE_CONFIG_MAX
};
bridge_state_attr
enum bridge_state_attr
Enumerator
BRIDGE_STATE_NAME
BRIDGE_STATE_ENABLED
__BRIDGE_STATE_MAX
Definition at line 105 of file ubus.c.
                       {
    BRIDGE_STATE_NAME,
    BRIDGE_STATE_ENABLED,
    __BRIDGE_STATE_MAX
};
Function Documentation
netifd_device_cb()
static int netifd_device_cb (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 169 of file ubus.c.
{
    if (strcmp(method, "stp_init") != 0)
        return 0;
    ubus_set_bridge_config(msg);
    return 0;
}
References ubus_set_bridge_config().
netifd_device_remove_cb()
static void netifd_device_remove_cb (struct ubus_context * ctx, struct ubus_subscriber * obj, uint32_t id) static
Definition at line 203 of file ubus.c.
{
    uloop_timeout_set(&netifd_sub_timer, 1000);
}
References netifd_sub_timer, and uloop_timeout_set().
netifd_sub_cb()
static void netifd_sub_cb (struct uloop_timeout * t) static
Definition at line 184 of file ubus.c.
{
    uint32_t id;
    if (ubus_lookup_id(&conn.ctx, "network.device", &id) != 0 ||
        ubus_subscribe(&conn.ctx, &netifd_sub, id) != 0) {
        uloop_timeout_set(t, 1000);
        return;
    }
    blob_buf_init(&b, 0);
    ubus_invoke(&conn.ctx, id, "stp_init", b.head, NULL, NULL, 1000);
}
References b, blob_buf_init(), conn, ubus_auto_conn::ctx, blob_buf::head, id, netifd_sub, ubus_invoke(), ubus_lookup_id(), ubus_subscribe(), and uloop_timeout_set().
ubus_add_bridge()
static int ubus_add_bridge (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 95 of file ubus.c.
{
    if (!ubus_set_bridge_config(msg))
        return UBUS_STATUS_INVALID_ARGUMENT;
    return 0;
}
References ubus_set_bridge_config(), and UBUS_STATUS_INVALID_ARGUMENT.
ubus_bridge_state()
static int ubus_bridge_state (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 117 of file ubus.c.
{
    struct blob_attr *tb[__BRIDGE_STATE_MAX];
    struct bridge_config *cfg;
    const char *bridge_name;
    struct worker_event ev = {};
    blobmsg_parse(bridge_state_policy, __BRIDGE_STATE_MAX, tb,
              blobmsg_data(msg), blobmsg_len(msg));
    if (!tb[BRIDGE_STATE_NAME] || !tb[BRIDGE_STATE_ENABLED])
        return UBUS_STATUS_INVALID_ARGUMENT;
    bridge_name = blobmsg_get_string(tb[BRIDGE_STATE_NAME]);
    ev.bridge_idx = if_nametoindex(bridge_name);
    if (!ev.bridge_idx)
        return UBUS_STATUS_NOT_FOUND;
    if (blobmsg_get_bool(tb[BRIDGE_STATE_ENABLED])) {
        cfg = bridge_config_get(bridge_name, false);
        if (!cfg)
            return UBUS_STATUS_NOT_FOUND;
        ev.type = WORKER_EV_BRIDGE_ADD;
        ev.bridge_config = cfg->config;
    } else {
        ev.type = WORKER_EV_BRIDGE_REMOVE;
    }
    worker_queue_event(&ev);
    return 0;
}
References __BRIDGE_STATE_MAX, blobmsg_data(), blobmsg_get_bool(), blobmsg_get_string(), blobmsg_len(), blobmsg_parse(), worker_event::bridge_config, bridge_config_get(), worker_event::bridge_idx, BRIDGE_STATE_ENABLED, BRIDGE_STATE_NAME, bridge_state_policy, bridge_config::config, worker_event::type, UBUS_STATUS_INVALID_ARGUMENT, UBUS_STATUS_NOT_FOUND, WORKER_EV_BRIDGE_ADD, WORKER_EV_BRIDGE_REMOVE, and worker_queue_event().
ubus_connect_handler()
static void ubus_connect_handler (struct ubus_context * ctx) static
Definition at line 215 of file ubus.c.
{
    ubus_add_object(ctx, &ustp_object);
    ubus_register_subscriber(ctx, &netifd_sub);
    uloop_timeout_set(&netifd_sub_timer, 1);
}
References ctx, netifd_sub, netifd_sub_timer, ubus_add_object(), ubus_register_subscriber(), uloop_timeout_set(), and ustp_object.
Referenced by ustp_ubus_init().
ubus_set_bridge_config()
static bool ubus_set_bridge_config (struct blob_attr * attr) static
Definition at line 43 of file ubus.c.
{
    struct blob_attr *tb[__BRIDGE_CONFIG_MAX], *cur;
    struct bridge_config *cfg;
    CIST_BridgeConfig *bc;
    blobmsg_parse(bridge_config_policy, __BRIDGE_CONFIG_MAX, tb,
              blobmsg_data(attr), blobmsg_len(attr));
    cur = tb[BRIDGE_CONFIG_NAME];
    if (!cur)
        return false;
    cfg = bridge_config_get(blobmsg_get_string(cur), true);
    bc = &cfg->config;
    bc->protocol_version = protoRSTP;
    bc->set_protocol_version = true;
    if ((cur = tb[BRIDGE_CONFIG_PROTO]) != NULL) {
        const char *proto = blobmsg_get_string(cur);
        if (!strcmp(proto, "mstp"))
            bc->protocol_version = protoMSTP;
        else if (!strcmp(proto, "stp"))
            bc->protocol_version = protoSTP;
    }
    if ((cur = tb[BRIDGE_CONFIG_FWD_DELAY]) != NULL) {
        bc->bridge_forward_delay = blobmsg_get_u32(cur);
        bc->set_bridge_forward_delay = true;
    }
    if ((cur = tb[BRIDGE_CONFIG_HELLO_TIME]) != NULL) {
        bc->bridge_hello_time = blobmsg_get_u32(cur);
        bc->set_bridge_hello_time = true;
    }
    if ((cur = tb[BRIDGE_CONFIG_AGEING_TIME]) != NULL) {
        bc->bridge_ageing_time = blobmsg_get_u32(cur);
        bc->set_bridge_ageing_time = true;
    }
    if ((cur = tb[BRIDGE_CONFIG_MAX_AGE]) != NULL) {
        bc->bridge_max_age = blobmsg_get_u32(cur);
        bc->set_bridge_max_age = true;
    }
    return true;
}
References __BRIDGE_CONFIG_MAX, blobmsg_data(), blobmsg_get_string(), blobmsg_get_u32(), blobmsg_len(), blobmsg_parse(), CIST_BridgeConfig::bridge_ageing_time, BRIDGE_CONFIG_AGEING_TIME, BRIDGE_CONFIG_FWD_DELAY, bridge_config_get(), BRIDGE_CONFIG_HELLO_TIME, BRIDGE_CONFIG_MAX_AGE, BRIDGE_CONFIG_NAME, bridge_config_policy, BRIDGE_CONFIG_PROTO, CIST_BridgeConfig::bridge_forward_delay, CIST_BridgeConfig::bridge_hello_time, CIST_BridgeConfig::bridge_max_age, bridge_config::config, CIST_BridgeConfig::protocol_version, protoMSTP, protoRSTP, protoSTP, CIST_BridgeConfig::set_bridge_ageing_time, CIST_BridgeConfig::set_bridge_forward_delay, CIST_BridgeConfig::set_bridge_hello_time, CIST_BridgeConfig::set_bridge_max_age, and CIST_BridgeConfig::set_protocol_version.
Referenced by netifd_device_cb(), and ubus_add_bridge().
ustp_ubus_exit()
void ustp_ubus_exit (void)
Definition at line 228 of file ubus.c.
{
    uint32_t id;
    ubus_remove_object(&conn.ctx, &ustp_object);
    ubus_unregister_subscriber(&conn.ctx, &netifd_sub);
    blob_buf_init(&b, 0);
    if (ubus_lookup_id(&conn.ctx, "network.device", &id) == 0)
        ubus_invoke(&conn.ctx, id, "stp_init", b.head, NULL, NULL, 1000);
    ubus_auto_shutdown(&conn);
}
References b, blob_buf_init(), conn, ubus_auto_conn::ctx, blob_buf::head, id, netifd_sub, ubus_auto_shutdown(), ubus_invoke(), ubus_lookup_id(), ubus_remove_object(), ubus_unregister_subscriber(), and ustp_object.
Referenced by main().
ustp_ubus_init()
void ustp_ubus_init (void)
Definition at line 222 of file ubus.c.
{
    conn.cb = ubus_connect_handler;
    ubus_auto_connect(&conn);
}
References ubus_auto_conn::cb, conn, ubus_auto_connect(), and ubus_connect_handler().
Referenced by main().
Variable Documentation
b
struct blob_buf b
Definition at line 21 of file ubus.c.
bridge_config_policy
const struct blobmsg_policy bridge_config_policy[__BRIDGE_CONFIG_MAX] static
Initial value:
= {
    [BRIDGE_CONFIG_NAME] = { "name", BLOBMSG_TYPE_STRING },
    [BRIDGE_CONFIG_PROTO] = { "proto", BLOBMSG_TYPE_STRING },
    [BRIDGE_CONFIG_FWD_DELAY] = { "forward_delay", BLOBMSG_TYPE_INT32 },
    [BRIDGE_CONFIG_HELLO_TIME] = { "hello_time", BLOBMSG_TYPE_INT32 },
    [BRIDGE_CONFIG_MAX_AGE] = { "max_age", BLOBMSG_TYPE_INT32 },
    [BRIDGE_CONFIG_AGEING_TIME] = { "ageing_time", BLOBMSG_TYPE_INT32 },
}
Definition at line 33 of file ubus.c.
{
    [BRIDGE_CONFIG_NAME] = { "name", BLOBMSG_TYPE_STRING },
    [BRIDGE_CONFIG_PROTO] = { "proto", BLOBMSG_TYPE_STRING },
    [BRIDGE_CONFIG_FWD_DELAY] = { "forward_delay", BLOBMSG_TYPE_INT32 },
    [BRIDGE_CONFIG_HELLO_TIME] = { "hello_time", BLOBMSG_TYPE_INT32 },
    [BRIDGE_CONFIG_MAX_AGE] = { "max_age", BLOBMSG_TYPE_INT32 },
    [BRIDGE_CONFIG_AGEING_TIME] = { "ageing_time", BLOBMSG_TYPE_INT32 },
};
Referenced by ubus_set_bridge_config().
bridge_state_policy
const struct blobmsg_policy bridge_state_policy[__BRIDGE_STATE_MAX] static
Initial value:
= {
    [BRIDGE_STATE_NAME] = { "name", BLOBMSG_TYPE_STRING },
    [BRIDGE_STATE_ENABLED] = { "enabled", BLOBMSG_TYPE_BOOL },
}
Definition at line 111 of file ubus.c.
{
    [BRIDGE_STATE_NAME] = { "name", BLOBMSG_TYPE_STRING },
    [BRIDGE_STATE_ENABLED] = { "enabled", BLOBMSG_TYPE_BOOL },
};
Referenced by ubus_bridge_state().
conn
struct ubus_auto_conn conn static
Definition at line 181 of file ubus.c.
Referenced by netifd_sub_cb(), ubus_auto_connect(), ubus_auto_connect_cb(), ubus_auto_disconnect_cb(), ubus_auto_reconnect_cb(), ubus_auto_shutdown(), ustp_ubus_exit(), and ustp_ubus_init().
netifd_sub
static struct ubus_subscriber netifd_sub static
Initial value:
= {
    .cb = netifd_device_cb,
    .remove_cb = netifd_device_remove_cb,
}
Definition at line 182 of file ubus.c.
Referenced by netifd_sub_cb(), ubus_connect_handler(), and ustp_ubus_exit().
netifd_sub_timer
struct uloop_timeout netifd_sub_timer static
Initial value:
= {
    .cb = netifd_sub_cb,
}
Definition at line 198 of file ubus.c.
{
    .cb = netifd_sub_cb,
};
Referenced by netifd_device_remove_cb(), and ubus_connect_handler().
ustp_methods
const struct ubus_method ustp_methods[] static
Initial value:
= {
    UBUS_METHOD("add_bridge", ubus_add_bridge, bridge_config_policy),
    UBUS_METHOD("bridge_state", ubus_bridge_state, bridge_state_policy),
}
Definition at line 153 of file ubus.c.
{
    UBUS_METHOD("add_bridge", ubus_add_bridge, bridge_config_policy),
    UBUS_METHOD("bridge_state", ubus_bridge_state, bridge_state_policy),
};
ustp_object
struct ubus_object ustp_object static
Initial value:
= {
    .name = "ustp",
    .type = &ustp_object_type,
    .methods = ustp_methods,
    .n_methods = ARRAY_SIZE(ustp_methods),
}
Definition at line 161 of file ubus.c.
{
    .name = "ustp",
    .type = &ustp_object_type,
    .methods = ustp_methods,
    .n_methods = ARRAY_SIZE(ustp_methods),
};
Referenced by ubus_connect_handler(), and ustp_ubus_exit().
ustp_object_type
struct ubus_object_type ustp_object_type static
Initial value:
=
    UBUS_OBJECT_TYPE("ustp", ustp_methods)
Definition at line 158 of file ubus.c.