zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/rpcd/include/rpcd/uci.h File Reference
uci.h File Reference
#include <glob.h>
#include <limits.h>
#include <dirent.h>
#include <unistd.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <inttypes.h>
#include <libubus.h>
#include <uci.h>
Macros
#define RPC_UCI_DIR_PREFIX "/var/run/rpcd"
#define RPC_UCI_SAVEDIR_PREFIX RPC_UCI_DIR_PREFIX "/uci-"
#define RPC_SNAPSHOT_FILES RPC_UCI_DIR_PREFIX "/snapshot-files/"
#define RPC_SNAPSHOT_DELTA RPC_UCI_DIR_PREFIX "/snapshot-delta/"
#define RPC_UCI_DIR "/etc/config/"
#define RPC_APPLY_TIMEOUT 60
Functions
int rpc_uci_api_init (struct ubus_context *ctx)
void rpc_uci_purge_savedirs (void)
Macro Definition Documentation
RPC_APPLY_TIMEOUT
#define RPC_APPLY_TIMEOUT 60
Definition at line 38 of file uci.h.
Referenced by rpc_uci_apply().
RPC_SNAPSHOT_DELTA
#define RPC_SNAPSHOT_DELTA RPC_UCI_DIR_PREFIX "/snapshot-delta/"
Definition at line 36 of file uci.h.
Referenced by rpc_uci_apply(), rpc_uci_confirm(), and rpc_uci_do_rollback().
RPC_SNAPSHOT_FILES
#define RPC_SNAPSHOT_FILES RPC_UCI_DIR_PREFIX "/snapshot-files/"
Definition at line 35 of file uci.h.
Referenced by rpc_uci_apply(), rpc_uci_apply_timeout(), rpc_uci_confirm(), rpc_uci_do_rollback(), and rpc_uci_rollback().
RPC_UCI_DIR
#define RPC_UCI_DIR "/etc/config/"
Definition at line 37 of file uci.h.
Referenced by rpc_uci_apply(), and rpc_uci_do_rollback().
RPC_UCI_DIR_PREFIX
#define RPC_UCI_DIR_PREFIX "/var/run/rpcd"
Definition at line 33 of file uci.h.
Referenced by main().
RPC_UCI_SAVEDIR_PREFIX
#define RPC_UCI_SAVEDIR_PREFIX RPC_UCI_DIR_PREFIX "/uci-"
Definition at line 34 of file uci.h.
Referenced by rpc_uci_apply(), rpc_uci_do_rollback(), rpc_uci_purge_savedir_cb(), rpc_uci_purge_savedirs(), and rpc_uci_set_savedir().
Function Documentation
rpc_uci_api_init()
int rpc_uci_api_init (struct ubus_context * ctx)
Definition at line 1760 of file uci.c.
{
    static const struct ubus_method uci_methods[] = {
        { .name = "configs", .handler = rpc_uci_configs },
        UBUS_METHOD("get",      rpc_uci_get,      rpc_uci_get_policy),
        UBUS_METHOD("state",    rpc_uci_state,    rpc_uci_get_policy),
        UBUS_METHOD("add",      rpc_uci_add,      rpc_uci_add_policy),
        UBUS_METHOD("set",      rpc_uci_set,      rpc_uci_set_policy),
        UBUS_METHOD("delete",   rpc_uci_delete,   rpc_uci_delete_policy),
        UBUS_METHOD("rename",   rpc_uci_rename,   rpc_uci_rename_policy),
        UBUS_METHOD("order",    rpc_uci_order,    rpc_uci_order_policy),
        UBUS_METHOD("changes",  rpc_uci_changes,  rpc_uci_config_policy),
        UBUS_METHOD("revert",   rpc_uci_revert,   rpc_uci_config_policy),
        UBUS_METHOD("commit",   rpc_uci_commit,   rpc_uci_config_policy),
        UBUS_METHOD("apply",    rpc_uci_apply,    rpc_uci_apply_policy),
        UBUS_METHOD("confirm",  rpc_uci_confirm,  rpc_uci_rollback_policy),
        UBUS_METHOD("rollback", rpc_uci_rollback, rpc_uci_rollback_policy),
        UBUS_METHOD_NOARG("reload_config", rpc_uci_reload),
    };
    static struct ubus_object_type uci_type =
        UBUS_OBJECT_TYPE("rpcd-plugin-uci", uci_methods);
    static struct ubus_object obj = {
        .name = "uci",
        .type = &uci_type,
        .methods = uci_methods,
        .n_methods = ARRAY_SIZE(uci_methods),
    };
    static struct rpc_session_cb cb = {
        .cb = rpc_uci_purge_savedir_cb
    };
    cursor = uci_alloc_context();
    if (!cursor)
        return UBUS_STATUS_UNKNOWN_ERROR;
    rpc_session_destroy_cb(&cb);
    return ubus_add_object(ctx, &obj);
}
References ARRAY_SIZE, rpc_session_cb::cb, ctx, cursor, ubus_object_type::methods, rpc_session_destroy_cb(), rpc_uci_add(), rpc_uci_add_policy, rpc_uci_apply(), rpc_uci_apply_policy, rpc_uci_changes(), rpc_uci_commit(), rpc_uci_config_policy, rpc_uci_configs(), rpc_uci_confirm(), rpc_uci_delete(), rpc_uci_delete_policy, rpc_uci_get(), rpc_uci_get_policy, rpc_uci_order(), rpc_uci_order_policy, rpc_uci_purge_savedir_cb(), rpc_uci_reload(), rpc_uci_rename(), rpc_uci_rename_policy, rpc_uci_revert(), rpc_uci_rollback(), rpc_uci_rollback_policy, rpc_uci_set(), rpc_uci_set_policy, rpc_uci_state(), ubus_add_object(), UBUS_METHOD, UBUS_METHOD_NOARG, UBUS_OBJECT_TYPE, and UBUS_STATUS_UNKNOWN_ERROR.
Referenced by main().
rpc_uci_purge_savedirs()
void rpc_uci_purge_savedirs (void)
Definition at line 1746 of file uci.c.
{
    int i;
    glob_t gl;
    if (!glob(RPC_UCI_SAVEDIR_PREFIX "*", 0, NULL, &gl))
    {
        for (i = 0; i < gl.gl_pathc; i++)
            rpc_uci_purge_dir(gl.gl_pathv[i]);
        globfree(&gl);
    }
}
References rpc_uci_purge_dir(), and RPC_UCI_SAVEDIR_PREFIX.
Referenced by main().