zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/libubox/ustream-fd.c File Reference
ustream-fd.c File Reference
#include <unistd.h>
#include <errno.h>
#include <stdio.h>
#include "ustream.h"
Functions
static void ustream_fd_set_uloop (struct ustream *s, bool write)
static void ustream_fd_set_read_blocked (struct ustream *s)
static void ustream_fd_read_pending (struct ustream_fd *sf, bool *more)
static int ustream_fd_write (struct ustream *s, const char *buf, int buflen, bool more)
static bool __ustream_fd_poll (struct ustream_fd *sf, unsigned int events)
static bool ustream_fd_poll (struct ustream *s)
static void ustream_uloop_cb (struct uloop_fd *fd, unsigned int events)
static void ustream_fd_free (struct ustream *s)
void ustream_fd_init (struct ustream_fd *sf, int fd)
Function Documentation
__ustream_fd_poll()
static bool __ustream_fd_poll (struct ustream_fd * sf, unsigned int events) static
Definition at line 116 of file ustream-fd.c.
{
    struct ustream *s = &sf->stream;
    bool more = false;
    if (events & ULOOP_READ)
        ustream_fd_read_pending(sf, &more);
    if (events & ULOOP_WRITE) {
        bool no_more = ustream_write_pending(s);
        if (no_more)
            ustream_fd_set_uloop(s, false);
    }
    if (sf->fd.error && !s->write_error) {
        ustream_state_change(s);
        s->write_error = true;
        ustream_fd_set_uloop(s, false);
    }
    return more;
}
References uloop_fd::error, events, ustream_fd::fd, ustream_fd::stream, ULOOP_READ, ULOOP_WRITE, ustream_fd_read_pending(), ustream_fd_set_uloop(), ustream_state_change(), ustream_write_pending(), and ustream::write_error.
Referenced by ustream_fd_poll(), and ustream_uloop_cb().
ustream_fd_free()
static void ustream_fd_free (struct ustream * s) static
Definition at line 153 of file ustream-fd.c.
{
    struct ustream_fd *sf = container_of(s, struct ustream_fd, stream);
    uloop_fd_delete(&sf->fd);
}
References container_of, ustream_fd::fd, ustream_fd::stream, and uloop_fd_delete().
Referenced by ustream_fd_init().
ustream_fd_init()
void ustream_fd_init (struct ustream_fd * sf, int fd)
Definition at line 160 of file ustream-fd.c.
{
    struct ustream *s = &sf->stream;
    ustream_init_defaults(s);
    sf->fd.fd = fd;
    sf->fd.cb = ustream_uloop_cb;
    s->set_read_blocked = ustream_fd_set_read_blocked;
    s->write = ustream_fd_write;
    s->free = ustream_fd_free;
    s->poll = ustream_fd_poll;
    ustream_fd_set_uloop(s, false);
}
References uloop_fd::cb, uloop_fd::fd, ustream_fd::fd, ustream::free, ustream::poll, ustream::set_read_blocked, ustream_fd::stream, ustream_fd_free(), ustream_fd_poll(), ustream_fd_set_read_blocked(), ustream_fd_set_uloop(), ustream_fd_write(), ustream_init_defaults(), ustream_uloop_cb(), and ustream::write.
Referenced by container_handle_console(), instance_start(), netifd_start_process(), q_initd_run(), server_cb(), test_client_fd_cb(), and uxc_attach().
ustream_fd_poll()
static bool ustream_fd_poll (struct ustream * s) static
Definition at line 139 of file ustream-fd.c.
{
    struct ustream_fd *sf = container_of(s, struct ustream_fd, stream);
    return __ustream_fd_poll(sf, ULOOP_READ | ULOOP_WRITE);
}
References __ustream_fd_poll(), container_of, ustream_fd::stream, ULOOP_READ, and ULOOP_WRITE.
Referenced by ustream_fd_init().
ustream_fd_read_pending()
static void ustream_fd_read_pending (struct ustream_fd * sf, bool * more) static
Definition at line 45 of file ustream-fd.c.
{
    struct ustream *s = &sf->stream;
    int buflen = 0;
    ssize_t len;
    char *buf;
    do {
        if (s->read_blocked)
            break;
        buf = ustream_reserve(s, 1, &buflen);
        if (!buf)
            break;
        len = read(sf->fd.fd, buf, buflen);
        if (len < 0) {
            if (errno == EINTR)
                continue;
            if (errno == EAGAIN || errno == ENOTCONN)
                return;
            len = 0;
        }
        if (!len) {
            if (!s->eof)
                ustream_state_change(s);
            s->eof = true;
            ustream_fd_set_uloop(s, false);
            return;
        }
        ustream_fill_read(s, len);
        *more = true;
    } while (1);
}
References buf, ustream::eof, uloop_fd::fd, ustream_fd::fd, ustream::read_blocked, ustream_fd::stream, ustream_fd_set_uloop(), ustream_fill_read(), ustream_reserve(), and ustream_state_change().
Referenced by __ustream_fd_poll().
ustream_fd_set_read_blocked()
static void ustream_fd_set_read_blocked (struct ustream * s) static
Definition at line 40 of file ustream-fd.c.
{
    ustream_fd_set_uloop(s, false);
}
References ustream_fd_set_uloop().
Referenced by ustream_fd_init().
ustream_fd_set_uloop()
static void ustream_fd_set_uloop (struct ustream * s, bool write) static
Definition at line 24 of file ustream-fd.c.
{
    struct ustream_fd *sf = container_of(s, struct ustream_fd, stream);
    struct ustream_buf *buf;
    unsigned int flags = ULOOP_EDGE_TRIGGER | ULOOP_ERROR_CB;
    if (!s->read_blocked && !s->eof)
        flags |= ULOOP_READ;
    buf = s->w.head;
    if (write || (buf && s->w.data_bytes && !s->write_error))
        flags |= ULOOP_WRITE;
    uloop_fd_add(&sf->fd, flags);
}
References buf, container_of, ustream_buf_list::data_bytes, ustream::eof, ustream_fd::fd, ustream_buf_list::head, ustream::read_blocked, ustream_fd::stream, ULOOP_EDGE_TRIGGER, ULOOP_ERROR_CB, uloop_fd_add(), ULOOP_READ, ULOOP_WRITE, ustream::w, and ustream::write_error.
Referenced by __ustream_fd_poll(), ustream_fd_init(), ustream_fd_read_pending(), ustream_fd_set_read_blocked(), and ustream_fd_write().
ustream_fd_write()
static int ustream_fd_write (struct ustream * s, const char * buf, int buflen, bool more) static
Definition at line 84 of file ustream-fd.c.
{
    struct ustream_fd *sf = container_of(s, struct ustream_fd, stream);
    ssize_t ret = 0, len;
    if (!buflen)
        return 0;
    while (buflen) {
        len = write(sf->fd.fd, buf, buflen);
        if (len < 0) {
            if (errno == EINTR)
                continue;
            if (errno == EAGAIN || errno == EWOULDBLOCK || errno == ENOTCONN)
                break;
            return -1;
        }
        ret += len;
        buf += len;
        buflen -= len;
    }
    if (buflen)
        ustream_fd_set_uloop(s, true);
    return ret;
}
References buf, container_of, uloop_fd::fd, ustream_fd::fd, ustream_fd::stream, and ustream_fd_set_uloop().
Referenced by ustream_fd_init().
ustream_uloop_cb()
static void ustream_uloop_cb (struct uloop_fd * fd, unsigned int events) static
Definition at line 146 of file ustream-fd.c.
{
    struct ustream_fd *sf = container_of(fd, struct ustream_fd, fd);
    __ustream_fd_poll(sf, events);
}
References __ustream_fd_poll(), container_of, events, and ustream_fd::fd.
Referenced by ustream_fd_init().