zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/libubox/runqueue.c File Reference
runqueue.c File Reference
#include <string.h>
#include <stdio.h>
#include "runqueue.h"
Functions
static void __runqueue_empty_cb (struct uloop_timeout *timeout)
void runqueue_init (struct runqueue *q)
static void __runqueue_start_next (struct uloop_timeout *timeout)
static void runqueue_start_next (struct runqueue *q)
static int __runqueue_cancel (void *ctx, struct safe_list *list)
void runqueue_cancel_active (struct runqueue *q)
void runqueue_cancel_pending (struct runqueue *q)
void runqueue_cancel (struct runqueue *q)
void runqueue_kill (struct runqueue *q)
void runqueue_task_cancel (struct runqueue_task *t, int type)
static void __runqueue_task_timeout (struct uloop_timeout *timeout)
static void _runqueue_task_add (struct runqueue *q, struct runqueue_task *t, bool running, bool first)
void runqueue_task_add (struct runqueue *q, struct runqueue_task *t, bool running)
void runqueue_task_add_first (struct runqueue *q, struct runqueue_task *t, bool running)
void runqueue_task_kill (struct runqueue_task *t)
void runqueue_stop (struct runqueue *q)
void runqueue_resume (struct runqueue *q)
void runqueue_task_complete (struct runqueue_task *t)
static void __runqueue_proc_cb (struct uloop_process *p, int ret)
void runqueue_process_cancel_cb (struct runqueue *q, struct runqueue_task *t, int type)
void runqueue_process_kill_cb (struct runqueue *q, struct runqueue_task *t)
void runqueue_process_add (struct runqueue *q, struct runqueue_process *p, pid_t pid)
Variables
static const struct runqueue_task_type runqueue_proc_type
Function Documentation
__runqueue_cancel()
static int __runqueue_cancel (void * ctx, struct safe_list * list) static
Definition at line 82 of file runqueue.c.
{
    struct runqueue_task *t;
    t = container_of(list, struct runqueue_task, list);
    runqueue_task_cancel(t, 0);
    return 0;
}
References container_of, runqueue_task::list, and runqueue_task_cancel().
Referenced by runqueue_cancel_active(), and runqueue_cancel_pending().
__runqueue_empty_cb()
static void __runqueue_empty_cb (struct uloop_timeout * timeout) static
Definition at line 24 of file runqueue.c.
{
    struct runqueue *q = container_of(timeout, struct runqueue, timeout);
    q->empty_cb(q);
}
References container_of, runqueue::empty_cb, q, and timeout.
Referenced by __runqueue_start_next().
__runqueue_proc_cb()
static void __runqueue_proc_cb (struct uloop_process * p, int ret) static
Definition at line 238 of file runqueue.c.
{
    struct runqueue_process *t = container_of(p, struct runqueue_process, proc);
    runqueue_task_complete(&t->task);
}
References container_of, runqueue_process::proc, runqueue_task_complete(), and runqueue_process::task.
Referenced by runqueue_process_add().
__runqueue_start_next()
static void __runqueue_start_next (struct uloop_timeout * timeout) static
Definition at line 37 of file runqueue.c.
{
    struct runqueue *q = container_of(timeout, struct runqueue, timeout);
    struct runqueue_task *t;
    do {
        if (q->stopped)
            break;
        if (list_empty(&q->tasks_inactive.list))
            break;
        if (q->max_running_tasks && q->running_tasks >= q->max_running_tasks)
            break;
        t = list_first_entry(&q->tasks_inactive.list, struct runqueue_task, list.list);
        safe_list_del(&t->list);
        safe_list_add(&t->list, &q->tasks_active);
        t->running = true;
        q->running_tasks++;
        if (t->run_timeout)
            uloop_timeout_set(&t->timeout, t->run_timeout);
        t->type->run(q, t);
    } while (1);
    if (!q->empty &&
        list_empty(&q->tasks_active.list) &&
        list_empty(&q->tasks_inactive.list)) {
        q->empty = true;
        if (q->empty_cb) {
            q->timeout.cb = __runqueue_empty_cb;
            uloop_timeout_set(&q->timeout, 1);
        }
    }
}
References __runqueue_empty_cb(), uloop_timeout::cb, container_of, runqueue::empty, runqueue::empty_cb, runqueue_task::list, safe_list::list, list_empty(), list_first_entry, runqueue::max_running_tasks, q, runqueue_task_type::run, runqueue_task::run_timeout, runqueue_task::running, runqueue::running_tasks, safe_list_add(), safe_list_del(), runqueue::stopped, runqueue::tasks_active, runqueue::tasks_inactive, runqueue::timeout, runqueue_task::timeout, timeout, runqueue_task::type, and uloop_timeout_set().
Referenced by runqueue_start_next().
__runqueue_task_timeout()
static void __runqueue_task_timeout (struct uloop_timeout * timeout) static
Definition at line 138 of file runqueue.c.
{
    struct runqueue_task *t = container_of(timeout, struct runqueue_task, timeout);
    if (t->cancelled)
        runqueue_task_kill(t);
    else
        runqueue_task_cancel(t, t->cancel_type);
}
References runqueue_task::cancel_type, runqueue_task::cancelled, container_of, runqueue_task_cancel(), runqueue_task_kill(), and timeout.
Referenced by _runqueue_task_add().
_runqueue_task_add()
static void _runqueue_task_add (struct runqueue * q, struct runqueue_task * t, bool running, bool first) static
Definition at line 148 of file runqueue.c.
{
    struct safe_list *head;
    if (t->queued)
        return;
    if (!t->type->run && !running) {
        fprintf(stderr, "BUG: inactive task added without run() callback\n");
        return;
    }
    if (running) {
        q->running_tasks++;
        head = &q->tasks_active;
    } else {
        head = &q->tasks_inactive;
    }
    t->timeout.cb = __runqueue_task_timeout;
    t->q = q;
    if (first)
        safe_list_add_first(&t->list, head);
    else
        safe_list_add(&t->list, head);
    t->cancelled = false;
    t->queued = true;
    t->running = running;
    q->empty = false;
    runqueue_start_next(q);
}
References __runqueue_task_timeout(), runqueue_task::cancelled, uloop_timeout::cb, runqueue::empty, runqueue_task::list, q, runqueue_task::q, runqueue_task::queued, runqueue_task_type::run, runqueue_task::running, runqueue::running_tasks, runqueue_start_next(), safe_list_add(), safe_list_add_first(), runqueue::tasks_active, runqueue::tasks_inactive, runqueue_task::timeout, and runqueue_task::type.
Referenced by runqueue_task_add(), and runqueue_task_add_first().
runqueue_cancel()
void runqueue_cancel (struct runqueue * q)
Definition at line 102 of file runqueue.c.
{
    runqueue_cancel_pending(q);
    runqueue_cancel_active(q);
}
References q, runqueue_cancel_active(), and runqueue_cancel_pending().
runqueue_cancel_active()
void runqueue_cancel_active (struct runqueue * q)
Definition at line 92 of file runqueue.c.
{
    safe_list_for_each(&q->tasks_active, __runqueue_cancel, NULL);
}
References __runqueue_cancel(), q, safe_list_for_each(), and runqueue::tasks_active.
Referenced by runqueue_cancel().
runqueue_cancel_pending()
void runqueue_cancel_pending (struct runqueue * q)
Definition at line 97 of file runqueue.c.
{
    safe_list_for_each(&q->tasks_inactive, __runqueue_cancel, NULL);
}
References __runqueue_cancel(), q, safe_list_for_each(), and runqueue::tasks_inactive.
Referenced by runqueue_cancel(), and runqueue_kill().
runqueue_init()
void runqueue_init (struct runqueue * q)
Definition at line 31 of file runqueue.c.
{
    INIT_SAFE_LIST(&q->tasks_active);
    INIT_SAFE_LIST(&q->tasks_inactive);
}
References INIT_SAFE_LIST, q, runqueue::tasks_active, and runqueue::tasks_inactive.
Referenced by __attribute__(), main(), and rcS().
runqueue_kill()
void runqueue_kill (struct runqueue * q)
Definition at line 108 of file runqueue.c.
{
    struct runqueue_task *t;
    while (!list_empty(&q->tasks_active.list)) {
        t = list_first_entry(&q->tasks_active.list, struct runqueue_task, list.list);
        runqueue_task_kill(t);
    }
    runqueue_cancel_pending(q);
    uloop_timeout_cancel(&q->timeout);
}
References runqueue_task::list, safe_list::list, list_empty(), list_first_entry, q, runqueue_cancel_pending(), runqueue_task_kill(), runqueue::tasks_active, runqueue::timeout, and uloop_timeout_cancel().
runqueue_process_add()
void runqueue_process_add (struct runqueue * q, struct runqueue_process * p, pid_t pid)
Definition at line 269 of file runqueue.c.
{
    if (p->proc.pending)
        return;
    p->proc.pid = pid;
    p->proc.cb = __runqueue_proc_cb;
    if (!p->task.type)
        p->task.type = &runqueue_proc_type;
    uloop_process_add(&p->proc);
    if (!p->task.running)
        runqueue_task_add(q, &p->task, true);
}
References __runqueue_proc_cb(), uloop_process::cb, uloop_process::pending, uloop_process::pid, runqueue_process::proc, q, runqueue_task::running, runqueue_proc_type, runqueue_task_add(), runqueue_process::task, runqueue_task::type, and uloop_process_add().
Referenced by q_initd_run(), q_sleep_run(), and trigger_command_run().
runqueue_process_cancel_cb()
void runqueue_process_cancel_cb (struct runqueue * q, struct runqueue_task * t, int type)
Definition at line 245 of file runqueue.c.
{
    struct runqueue_process *p = container_of(t, struct runqueue_process, task);
    if (!type)
        type = SIGTERM;
    kill(p->proc.pid, type);
}
References container_of, uloop_process::pid, runqueue_process::proc, task, and type.
Referenced by add_initd(), q_sleep_cancel(), and trigger_command_start().
runqueue_process_kill_cb()
void runqueue_process_kill_cb (struct runqueue * q, struct runqueue_task * t)
Definition at line 255 of file runqueue.c.
{
    struct runqueue_process *p = container_of(t, struct runqueue_process, task);
    uloop_process_delete(&p->proc);
    kill(p->proc.pid, SIGKILL);
}
References container_of, uloop_process::pid, runqueue_process::proc, task, and uloop_process_delete().
Referenced by add_initd(), add_sleeper(), my_runqueue_process_kill_cb(), and trigger_command_start().
runqueue_resume()
void runqueue_resume (struct runqueue * q)
Definition at line 210 of file runqueue.c.
{
    q->stopped = false;
    runqueue_start_next(q);
}
References q, runqueue_start_next(), and runqueue::stopped.
runqueue_start_next()
static void runqueue_start_next (struct runqueue * q) static
Definition at line 73 of file runqueue.c.
{
    if (q->empty)
        return;
    q->timeout.cb = __runqueue_start_next;
    uloop_timeout_set(&q->timeout, 1);
}
References __runqueue_start_next(), uloop_timeout::cb, runqueue::empty, q, runqueue::timeout, and uloop_timeout_set().
Referenced by _runqueue_task_add(), runqueue_resume(), and runqueue_task_complete().
runqueue_stop()
void runqueue_stop (struct runqueue * q)
Definition at line 205 of file runqueue.c.
{
    q->stopped = true;
}
References q, and runqueue::stopped.
runqueue_task_add()
void runqueue_task_add (struct runqueue * q, struct runqueue_task * t, bool running)
Definition at line 181 of file runqueue.c.
{
    _runqueue_task_add(q, t, running, 0);
}
References _runqueue_task_add(), and q.
Referenced by add_initd(), add_sleeper(), runqueue_process_add(), trigger_command_complete(), and trigger_command_start().
runqueue_task_add_first()
void runqueue_task_add_first (struct runqueue * q, struct runqueue_task * t, bool running)
Definition at line 186 of file runqueue.c.
{
    _runqueue_task_add(q, t, running, 1);
}
References _runqueue_task_add(), and q.
runqueue_task_cancel()
void runqueue_task_cancel (struct runqueue_task * t, int type)
Definition at line 120 of file runqueue.c.
{
    if (!t->queued)
        return;
    if (!t->running) {
        runqueue_task_complete(t);
        return;
    }
    t->cancelled = true;
    if (t->cancel_timeout)
        uloop_timeout_set(&t->timeout, t->cancel_timeout);
    if (t->type->cancel)
        t->type->cancel(t->q, t, type);
}
References runqueue_task_type::cancel, runqueue_task::cancel_timeout, runqueue_task::cancelled, runqueue_task::q, runqueue_task::queued, runqueue_task::running, runqueue_task_complete(), runqueue_task::timeout, runqueue_task::type, type, and uloop_timeout_set().
Referenced by __runqueue_cancel(), and __runqueue_task_timeout().
runqueue_task_complete()
void runqueue_task_complete (struct runqueue_task * t)
Definition at line 216 of file runqueue.c.
{
    struct runqueue *q = t->q;
    if (!t->queued)
        return;
    if (t->running)
        t->q->running_tasks--;
    uloop_timeout_cancel(&t->timeout);
    safe_list_del(&t->list);
    t->queued = false;
    t->running = false;
    t->cancelled = false;
    if (t->complete)
        t->complete(q, t);
    runqueue_start_next(q);
}
References runqueue_task::cancelled, runqueue_task::complete, runqueue_task::list, q, runqueue_task::q, runqueue_task::queued, runqueue_task::running, runqueue::running_tasks, runqueue_start_next(), safe_list_del(), runqueue_task::timeout, and uloop_timeout_cancel().
Referenced by __runqueue_proc_cb(), runqueue_task_cancel(), and runqueue_task_kill().
runqueue_task_kill()
void runqueue_task_kill (struct runqueue_task * t)
Definition at line 191 of file runqueue.c.
{
    struct runqueue *q = t->q;
    bool running = t->running;
    if (!t->queued)
        return;
    if (running && t->type->kill)
        t->type->kill(q, t);
    runqueue_task_complete(t);
}
References runqueue_task_type::kill, q, runqueue_task::q, runqueue_task::queued, runqueue_task::running, runqueue_task_complete(), and runqueue_task::type.
Referenced by __runqueue_task_timeout(), runqueue_kill(), and timer_cb().
Variable Documentation
runqueue_proc_type
const struct runqueue_task_type runqueue_proc_type static
Initial value:
= {
    .name = "process",
    .cancel = runqueue_process_cancel_cb,
    .kill = runqueue_process_kill_cb,
}
Definition at line 263 of file runqueue.c.
{
    .name = "process",
    .cancel = runqueue_process_cancel_cb,
    .kill = runqueue_process_kill_cb,
};
Referenced by runqueue_process_add().