zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/plug/coldplug.c File Reference
coldplug.c File Reference
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/mount.h>
#include <stdlib.h>
#include <unistd.h>
#include "../procd.h"
#include "../libc-compat.h"
#include "hotplug.h"
#include "../container.h"
Functions
static void coldplug_complete (struct uloop_timeout *t)
static void udevtrigger_complete (struct uloop_process *proc, int ret)
void procd_coldplug (void)
Variables
static struct uloop_process udevtrigger
Function Documentation
coldplug_complete()
static void coldplug_complete (struct uloop_timeout * t) static
Definition at line 30 of file coldplug.c.
{
    P_DEBUG(4, "Coldplug complete\n");
    hotplug_last_event(NULL);
    procd_state_next();
}
References hotplug_last_event(), P_DEBUG, and procd_state_next().
Referenced by udevtrigger_complete().
procd_coldplug()
void procd_coldplug (void)
Definition at line 43 of file coldplug.c.
{
    char *argv[] = { "udevtrigger", NULL };
    unsigned int oldumask = umask(0);
    if (!is_container()) {
        umount2("/dev/pts", MNT_DETACH);
        umount2("/dev/", MNT_DETACH);
        mount("tmpfs", "/dev", "tmpfs", MS_NOATIME | MS_NOEXEC | MS_NOSUID, "mode=0755,size=512K");
        mkdir("/dev/pts", 0755);
        mount("devpts", "/dev/pts", "devpts", MS_NOATIME | MS_NOEXEC | MS_NOSUID, 0);
    }
    ignore(symlink("/tmp/shm", "/dev/shm"));
    umask(oldumask);
    udevtrigger.cb = udevtrigger_complete;
    udevtrigger.pid = fork();
    if (!udevtrigger.pid) {
        execvp(argv[0], argv);
        ERROR("Failed to start coldplug: %m\n");
        exit(EXIT_FAILURE);
    }
    if (udevtrigger.pid <= 0) {
        ERROR("Failed to start new coldplug instance: %m\n");
        return;
    }
    uloop_process_add(&udevtrigger);
    P_DEBUG(4, "Launched coldplug instance, pid=%d\n", (int) udevtrigger.pid);
}
References uloop_process::cb, ERROR, ignore, is_container(), P_DEBUG, uloop_process::pid, udevtrigger, udevtrigger_complete(), and uloop_process_add().
Referenced by state_enter().
udevtrigger_complete()
static void udevtrigger_complete (struct uloop_process * proc, int ret) static
Definition at line 37 of file coldplug.c.
{
    P_DEBUG(4, "Finished udevtrigger\n");
    hotplug_last_event(coldplug_complete);
}
References coldplug_complete(), hotplug_last_event(), and P_DEBUG.
Referenced by procd_coldplug().
Variable Documentation
udevtrigger
struct uloop_process udevtrigger static
Definition at line 28 of file coldplug.c.
Referenced by procd_coldplug().