zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/jail/elf.c File Reference
elf.c File Reference
#include <string.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <glob.h>
#include <elf.h>
#include <linux/limits.h>
#include <libubox/utils.h>
#include "fs.h"
#include "log.h"
Macros
#define _GNU_SOURCE
Functions
static LIST_HEAD (library_paths)
static void alloc_library_path (const char *path)
void alloc_library (const char *path, const char *name)
int lib_open (char **fullpath, const char *file)
const char * find_lib (const char *file)
static int elf64_find_section (const char *map, unsigned int type, unsigned long *offset, unsigned long *size, unsigned long *vaddr)
static int elf32_find_section (const char *map, unsigned int type, unsigned long *offset, unsigned long *size, unsigned long *vaddr)
static int elf_find_section (const char *map, unsigned int type, unsigned long *offset, unsigned long *size, unsigned long *vaddr)
static int elf32_scan_dynamic (const char *map, unsigned long dyn_offset, unsigned long dyn_size, long load_offset)
static int elf64_scan_dynamic (const char *map, unsigned long dyn_offset, unsigned long dyn_size, long load_offset)
int elf_load_deps (const char *path, const char *map)
static void load_ldso_conf (const char *conf)
void init_library_search (void)
void free_library_search (void)
Variables
struct avl_tree libraries
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 14 of file elf.c.
Function Documentation
alloc_library()
void alloc_library (const char * path, const char * name)
Definition at line 56 of file elf.c.
{
    struct library *l;
    char *_name, *_path;
    l = calloc_a(sizeof(*l),
        &_path, strlen(path) + 1,
        &_name, strlen(name) + 1);
    if (!l)
        return;
    l->avl.key = l->name = strcpy(_name, name);
    l->path = strcpy(_path, path);
    avl_insert(&libraries, &l->avl);
    DEBUG("adding library %s (%s)\n", path, name);
}
References library::avl, avl_insert(), calloc_a, DEBUG, avl_node::key, libraries, library::name, library::path, and path.
Referenced by add_2paths_and_deps().
alloc_library_path()
static void alloc_library_path (const char * path) static
Definition at line 32 of file elf.c.
{
    struct stat s;
    if (stat(path, &s))
        return;
    struct library_path *p;
    char *_path;
    p = calloc_a(sizeof(*p),
        &_path, strlen(path) + 1);
    if (!p)
        return;
    p->path = strcpy(_path, path);
    list_add_tail(&p->list, &library_paths);
    DEBUG("adding ld.so path %s\n", path);
}
References calloc_a, DEBUG, library_path::list, list_add_tail(), library_path::path, and path.
Referenced by init_library_search(), and load_ldso_conf().
elf32_find_section()
static int elf32_find_section (const char * map, unsigned int type, unsigned long * offset, unsigned long * size, unsigned long * vaddr) static
Definition at line 128 of file elf.c.
{
    Elf32_Ehdr *e;
    Elf32_Phdr *ph;
    int i;
    e = (Elf32_Ehdr *) map;
    ph = (Elf32_Phdr *) (map + e->e_phoff);
    for (i = 0; i < e->e_phnum; i++) {
        if (ph[i].p_type == type) {
            *offset = ph[i].p_offset;
            if (size)
                *size = ph[i].p_filesz;
            if (vaddr)
                *vaddr = ph[i].p_vaddr;
            return 0;
        }
    }
    return -1;
}
References type.
Referenced by elf_find_section().
elf32_scan_dynamic()
static int elf32_scan_dynamic (const char * map, unsigned long dyn_offset, unsigned long dyn_size, long load_offset) static
Definition at line 165 of file elf.c.
{
    Elf32_Dyn *dynamic = (Elf32_Dyn *) (map + dyn_offset);
    const char *strtab = NULL;
    while ((void *) dynamic < (void *) (map + dyn_offset + dyn_size)) {
        Elf32_Dyn *curr = dynamic;
        dynamic++;
        if (curr->d_tag != DT_STRTAB)
            continue;
        strtab = map + (curr->d_un.d_ptr - load_offset);
        break;
    }
    if (!strtab)
        return -1;
    dynamic = (Elf32_Dyn *) (map + dyn_offset);
    while ((void *) dynamic < (void *) (map + dyn_offset + dyn_size)) {
        Elf32_Dyn *curr = dynamic;
        dynamic++;
        if (curr->d_tag != DT_NEEDED)
            continue;
        if (add_path_and_deps(&strtab[curr->d_un.d_val], 1, -1, 1))
            return -1;
    }
    return 0;
}
References add_path_and_deps().
Referenced by elf_load_deps().
elf64_find_section()
static int elf64_find_section (const char * map, unsigned int type, unsigned long * offset, unsigned long * size, unsigned long * vaddr) static
Definition at line 105 of file elf.c.
{
    Elf64_Ehdr *e;
    Elf64_Phdr *ph;
    int i;
    e = (Elf64_Ehdr *) map;
    ph = (Elf64_Phdr *) (map + e->e_phoff);
    for (i = 0; i < e->e_phnum; i++) {
        if (ph[i].p_type == type) {
            *offset = ph[i].p_offset;
            if (size)
                *size = ph[i].p_filesz;
            if (vaddr)
                *vaddr = ph[i].p_vaddr;
            return 0;
        }
    }
    return -1;
}
References type.
Referenced by elf_find_section().
elf64_scan_dynamic()
static int elf64_scan_dynamic (const char * map, unsigned long dyn_offset, unsigned long dyn_size, long load_offset) static
Definition at line 199 of file elf.c.
{
    Elf64_Dyn *dynamic = (Elf64_Dyn *) (map + dyn_offset);
    const char *strtab = NULL;
    while ((void *) dynamic < (void *) (map + dyn_offset + dyn_size)) {
        Elf64_Dyn *curr = dynamic;
        dynamic++;
        if (curr->d_tag != DT_STRTAB)
            continue;
        strtab = map + (curr->d_un.d_ptr - load_offset);
        break;
    }
    if (!strtab)
        return -1;
    dynamic = (Elf64_Dyn *) (map + dyn_offset);
    while ((void *) dynamic < (void *) (map + dyn_offset + dyn_size)) {
        Elf64_Dyn *curr = dynamic;
        dynamic++;
        if (curr->d_tag != DT_NEEDED)
            continue;
        if (add_path_and_deps(&strtab[curr->d_un.d_val], 1, -1, 1))
            return -1;
    }
    return 0;
}
References add_path_and_deps().
Referenced by elf_load_deps().
elf_find_section()
static int elf_find_section (const char * map, unsigned int type, unsigned long * offset, unsigned long * size, unsigned long * vaddr) static
Definition at line 151 of file elf.c.
{
    int clazz = map[EI_CLASS];
    if (clazz == ELFCLASS32)
        return elf32_find_section(map, type, offset, size, vaddr);
    else if (clazz == ELFCLASS64)
        return elf64_find_section(map, type, offset, size, vaddr);
    ERROR("unknown elf format %d\n", clazz);
    return -1;
}
References elf32_find_section(), elf64_find_section(), ERROR, and type.
Referenced by elf_load_deps().
elf_load_deps()
int elf_load_deps (const char * path, const char * map)
Definition at line 233 of file elf.c.
{
    unsigned long dyn_offset, dyn_size;
    unsigned long load_offset, load_vaddr;
    unsigned long interp_offset;
    if (elf_find_section(map, PT_INTERP, &interp_offset, NULL, NULL) == 0) {
        add_path_and_deps(map+interp_offset, 1, -1, 0);
    }
    if (elf_find_section(map, PT_LOAD, &load_offset, NULL, &load_vaddr)) {
        DEBUG("failed to load the .load section from %s\n", path);
        return 0;
    }
    if (elf_find_section(map, PT_DYNAMIC, &dyn_offset, &dyn_size, NULL)) {
        DEBUG("failed to load the .dynamic section from %s\n", path);
        return 0;
    }
    int clazz = map[EI_CLASS];
    if (clazz == ELFCLASS32)
        return elf32_scan_dynamic(map, dyn_offset, dyn_size, load_vaddr - load_offset);
    else if (clazz == ELFCLASS64)
        return elf64_scan_dynamic(map, dyn_offset, dyn_size, load_vaddr - load_offset);
    ERROR("unknown elf format %d\n", clazz);
    return -1;
}
References add_path_and_deps(), DEBUG, elf32_scan_dynamic(), elf64_scan_dynamic(), elf_find_section(), ERROR, and path.
Referenced by add_2paths_and_deps().
find_lib()
const char * find_lib (const char * file)
Definition at line 94 of file elf.c.
{
    struct library *l;
    l = avl_find_element(&libraries, file, l, avl);
    if (!l)
        return NULL;
    return l->path;
}
References library::avl, avl_find_element, libraries, and library::path.
Referenced by build_envp().
free_library_search()
void free_library_search (void)
Definition at line 319 of file elf.c.
{
    struct library_path *p, *ptmp;
    struct library *l, *tmp;
    list_for_each_entry_safe(p, ptmp, &library_paths, list)
        free(p);
    avl_remove_all_elements(&libraries, l, avl, tmp)
        free(l);
}
References library::avl, avl_remove_all_elements, libraries, and list_for_each_entry_safe.
Referenced by free_opts().
init_library_search()
void init_library_search (void)
Definition at line 310 of file elf.c.
{
    avl_init(&libraries, avl_strcmp, false, NULL);
    alloc_library_path("/lib");
    alloc_library_path("/lib64");
    alloc_library_path("/usr/lib");
    load_ldso_conf("/etc/ld.so.conf");
}
References alloc_library_path(), avl_init(), avl_strcmp(), libraries, and load_ldso_conf().
Referenced by main().
lib_open()
int lib_open (char ** fullpath, const char * file)
Definition at line 74 of file elf.c.
{
    struct library_path *p;
    char path[PATH_MAX];
    int fd = -1;
    *fullpath = NULL;
    list_for_each_entry(p, &library_paths, list) {
        snprintf(path, sizeof(path), "%s/%s", p->path, file);
        fd = open(path, O_RDONLY|O_CLOEXEC);
        if (fd >= 0) {
            *fullpath = strdup(path);
            break;
        }
    }
    return fd;
}
References library_path::list, list_for_each_entry, library_path::path, and path.
Referenced by add_2paths_and_deps().
LIST_HEAD()
static LIST_HEAD (library_paths) static
load_ldso_conf()
static void load_ldso_conf (const char * conf) static
Definition at line 264 of file elf.c.
{
    FILE* fp = fopen(conf, "r");
    char line[PATH_MAX];
    if (!fp) {
        DEBUG("failed to open %s\n", conf);
        return;
    }
    while (!feof(fp)) {
        int len;
        if (!fgets(line, sizeof(line), fp))
            break;
        len = strlen(line);
        if (len < 2)
            continue;
        if (*line == '#')
            continue;
        if (line[len - 1] == '\n')
            line[len - 1] = '\0';
        if (!strncmp(line, "include ", 8)) {
            char *sep = strstr(line, " ");
            glob_t gl;
            int i;
            if (!sep)
                continue;;
            while (*sep == ' ')
                sep++;
            if (glob(sep, GLOB_NOESCAPE | GLOB_MARK, NULL, &gl)) {
                ERROR("glob failed on %s\n", sep);
                continue;
            }
            for (i = 0; i < gl.gl_pathc; i++)
                load_ldso_conf(gl.gl_pathv[i]);
            globfree(&gl);
        } else {
            alloc_library_path(line);
        }
    }
    fclose(fp);
}
References alloc_library_path(), conf, DEBUG, ERROR, and load_ldso_conf().
Referenced by init_library_search(), and load_ldso_conf().
Variable Documentation
libraries
struct avl_tree libraries
Definition at line 29 of file elf.c.
Referenced by add_2paths_and_deps(), alloc_library(), find_lib(), free_library_search(), init_library_search(), and mount_all().