zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/libubox/ustream.h File Reference
ustream.h File Reference
#include <stdarg.h>
#include "uloop.h"
Classes
struct ustream_buf_list
struct ustream
struct ustream_fd
struct ustream_buf
Enumerations
enum read_blocked_reason { READ_BLOCKED_USER = (1 << 0) , READ_BLOCKED_FULL = (1 << 1) }
Functions
void ustream_fd_init (struct ustream_fd *s, int fd)
void ustream_free (struct ustream *s)
void ustream_consume (struct ustream *s, int len)
int ustream_read (struct ustream *s, char *buf, int buflen)
int ustream_write (struct ustream *s, const char *buf, int len, bool more)
int ustream_printf (struct ustream *s, const char *format,...) __attribute__((format(printf
int int ustream_vprintf (struct ustream *s, const char *format, va_list arg) __attribute__((format(printf
int int char * ustream_get_read_buf (struct ustream *s, int *buflen)
void ustream_set_read_blocked (struct ustream *s, bool set)
static bool ustream_read_blocked (struct ustream *s)
static int ustream_pending_data (struct ustream *s, bool write)
static bool ustream_read_buf_full (struct ustream *s)
void ustream_init_defaults (struct ustream *s)
char * ustream_reserve (struct ustream *s, int len, int *maxlen)
void ustream_fill_read (struct ustream *s, int len)
bool ustream_write_pending (struct ustream *s)
static void ustream_state_change (struct ustream *s)
static bool ustream_poll (struct ustream *s)
Class Documentation
ustream_buf_list
struct ustream_buf_list
Definition at line 33 of file ustream.h.
Class Members
int(*)(struct ustream *s, struct ustream_buf_list *l) alloc
int buffer_len
int buffers
int data_bytes
struct ustream_buf * data_tail
struct ustream_buf * head
int max_buffers
int min_buffers
struct ustream_buf * tail
ustream
struct ustream
Definition at line 49 of file ustream.h.
Class Members
bool eof
void(*)(struct ustream *s) free
struct ustream * next
void(*)(struct ustream *s, int bytes_new) notify_read
void(*)(struct ustream *s) notify_state
void(*)(struct ustream *s, int bytes) notify_write
uint8_t pending_cb
bool(*)(struct ustream *s) poll
enum read_blocked_reason read_blocked
void(*)(struct ustream *s) set_read_blocked
struct uloop_timeout state_change
bool string_data
struct ustream_buf_list r w
int(*)(struct ustream *s, const char *buf, int len, bool more) write
bool write_error
ustream_fd
struct ustream_fd
Definition at line 123 of file ustream.h.
Class Members
struct uloop_fd fd
struct ustream stream
ustream_buf
struct ustream_buf
Definition at line 128 of file ustream.h.
Class Members
char * data
char * end
char head[]
struct ustream_buf * next
char * tail
Enumeration Type Documentation
read_blocked_reason
enum read_blocked_reason
Enumerator
READ_BLOCKED_USER (1 << 0)
READ_BLOCKED_FULL (1 << 1)
Definition at line 28 of file ustream.h.
{
    READ_BLOCKED_USER = (1 << 0),
    READ_BLOCKED_FULL = (1 << 1),
};
Function Documentation
ustream_consume()
void ustream_consume (struct ustream * s, int len)
Definition at line 215 of file ustream.c.
{
    struct ustream_buf *buf = s->r.head;
    if (!len)
        return;
    s->r.data_bytes -= len;
    if (s->r.data_bytes < 0)
        abort();
    do {
        struct ustream_buf *next = buf->next;
        int buf_len = buf->tail - buf->data;
        if (len < buf_len) {
            buf->data += len;
            break;
        }
        len -= buf_len;
        ustream_free_buf(&s->r, buf);
        buf = next;
    } while(len);
    __ustream_set_read_blocked(s, s->read_blocked & ~READ_BLOCKED_FULL);
}
References __ustream_set_read_blocked(), buf, ustream_buf::next, ustream::read_blocked, READ_BLOCKED_FULL, and ustream_free_buf().
Referenced by client_cb(), client_read_cb(), instance_console(), instance_console_client(), instance_stdio(), local_cb(), netifd_process_log_read_cb(), pipe_cb(), rpc_exec_epipe_read_cb(), rpc_exec_opipe_read_cb(), test_client_fd_data_cb(), and ustream_read().
ustream_fd_init()
void ustream_fd_init (struct ustream_fd * s, int fd)
Definition at line 160 of file ustream-fd.c.
{
    struct ustream *s = &sf->stream;
    ustream_init_defaults(s);
    sf->fd.fd = fd;
    sf->fd.cb = ustream_uloop_cb;
    s->set_read_blocked = ustream_fd_set_read_blocked;
    s->write = ustream_fd_write;
    s->free = ustream_fd_free;
    s->poll = ustream_fd_poll;
    ustream_fd_set_uloop(s, false);
}
References uloop_fd::cb, uloop_fd::fd, ustream_fd::fd, ustream::free, ustream::poll, ustream::set_read_blocked, ustream_fd::stream, ustream_fd_free(), ustream_fd_poll(), ustream_fd_set_read_blocked(), ustream_fd_set_uloop(), ustream_fd_write(), ustream_init_defaults(), ustream_uloop_cb(), and ustream::write.
Referenced by container_handle_console(), instance_start(), netifd_start_process(), q_initd_run(), server_cb(), test_client_fd_cb(), and uxc_attach().
ustream_fill_read()
void ustream_fill_read (struct ustream * s, int len)
Definition at line 302 of file ustream.c.
{
    struct ustream_buf *buf = s->r.data_tail;
    int maxlen;
    s->r.data_bytes += len;
    do {
        if (!buf)
            abort();
        maxlen = buf->end - buf->tail;
        if (len < maxlen)
            maxlen = len;
        len -= maxlen;
        buf->tail += maxlen;
        ustream_fixup_string(s, buf);
        s->r.data_tail = buf;
        buf = buf->next;
    } while (len);
    if (s->notify_read) {
        if (s->pending_cb & CB_PENDING_READ)
            return;
        s->pending_cb |= CB_PENDING_READ;
        s->notify_read(s, s->r.data_bytes);
        s->pending_cb &= ~CB_PENDING_READ;
    }
}
References buf, CB_PENDING_READ, ustream::notify_read, ustream::pending_cb, and ustream_fixup_string().
Referenced by ustream_fd_read_pending().
ustream_free()
void ustream_free (struct ustream * s)
Definition at line 94 of file ustream.c.
{
    if (s->free)
        s->free(s);
    uloop_timeout_cancel(&s->state_change);
    ustream_free_buffers(&s->r);
    ustream_free_buffers(&s->w);
}
References ustream::free, ustream::state_change, uloop_timeout_cancel(), ustream_free_buffers(), and ustream::w.
Referenced by client_close(), instance_free_stdio(), netifd_delete_process(), q_initd_complete(), rpc_exec_ipipe_write_cb(), rpc_exec_reply(), rpc_file_exec_reply(), and uxc_attach().
ustream_get_read_buf()
int int char * ustream_get_read_buf (struct ustream * s, int * buflen)
Definition at line 334 of file ustream.c.
{
    char *data = NULL;
    int len = 0;
    if (s->r.head) {
        len = s->r.head->tail - s->r.head->data;
        if (len > 0)
            data = s->r.head->data;
    }
    if (buflen)
        *buflen = len;
    return data;
}
References ustream_buf::data.
Referenced by client_cb(), client_read_cb(), instance_console(), instance_console_client(), instance_stdio(), local_cb(), netifd_process_log_read_cb(), pipe_cb(), rpc_exec_epipe_read_cb(), rpc_exec_opipe_read_cb(), test_client_fd_data_cb(), and ustream_read().
ustream_init_defaults()
void ustream_init_defaults (struct ustream * s)
Definition at line 114 of file ustream.c.
{
#define DEFAULT_SET(_f, _default)   \
    do {                \
        if (!_f)        \
            _f = _default;  \
    } while(0)
    DEFAULT_SET(s->r.alloc, ustream_alloc_default);
    DEFAULT_SET(s->w.alloc, ustream_alloc_default);
    DEFAULT_SET(s->r.min_buffers, 1);
    DEFAULT_SET(s->r.max_buffers, 1);
    DEFAULT_SET(s->r.buffer_len, 4096);
    DEFAULT_SET(s->w.min_buffers, 2);
    DEFAULT_SET(s->w.max_buffers, -1);
    DEFAULT_SET(s->w.buffer_len, 256);
#undef DEFAULT_SET
    s->state_change.cb = ustream_state_change_cb;
    s->write_error = false;
    s->eof = false;
    s->read_blocked = 0;
    s->r.buffers = 0;
    s->r.data_bytes = 0;
    s->w.buffers = 0;
    s->w.data_bytes = 0;
}
References ustream_buf_list::alloc, ustream_buf_list::buffer_len, ustream_buf_list::buffers, uloop_timeout::cb, ustream_buf_list::data_bytes, DEFAULT_SET, ustream::eof, ustream_buf_list::max_buffers, ustream_buf_list::min_buffers, ustream::read_blocked, ustream::state_change, ustream_alloc_default(), ustream_state_change_cb(), ustream::w, and ustream::write_error.
Referenced by ustream_fd_init().
ustream_pending_data()
static int ustream_pending_data (struct ustream * s, bool write) inline static
Definition at line 174 of file ustream.h.
{
    struct ustream_buf_list *b = write ? &s->w : &s->r;
    return b->data_bytes;
}
References b, and ustream::w.
Referenced by rpc_ustream_to_blobmsg(), and rpc_ustream_to_blobmsg().
ustream_poll()
static bool ustream_poll (struct ustream * s) inline static
Definition at line 214 of file ustream.h.
{
    if (!s->poll)
        return false;
    return s->poll(s);
}
References ustream::poll.
Referenced by netifd_delete_process(), rpc_exec_process_cb(), and rpc_file_exec_process_cb().
ustream_printf()
int ustream_printf (struct ustream * s, const char * format, ...)
ustream_read()
int ustream_read (struct ustream * s, char * buf, int buflen)
Definition at line 351 of file ustream.c.
{
    char *chunk;
    int chunk_len;
    int len = 0;
    do {
        chunk = ustream_get_read_buf(s, &chunk_len);
        if (!chunk)
            break;
        if (chunk_len > buflen - len)
            chunk_len = buflen - len;
        memcpy(buf + len, chunk, chunk_len);
        ustream_consume(s, chunk_len);
        len += chunk_len;
    } while (len < buflen);
    return len;
}
References buf, ustream_consume(), and ustream_get_read_buf().
ustream_read_blocked()
static bool ustream_read_blocked (struct ustream * s) inline static
Definition at line 169 of file ustream.h.
{
    return !!(s->read_blocked & READ_BLOCKED_USER);
}
References ustream::read_blocked, and READ_BLOCKED_USER.
Referenced by client_notify_write(), and client_read_cb().
ustream_read_buf_full()
static bool ustream_read_buf_full (struct ustream * s) inline static
Definition at line 180 of file ustream.h.
{
    struct ustream_buf *buf = s->r.data_tail;
    return buf && buf->data == buf->head && buf->tail == buf->end &&
           s->r.buffers == s->r.max_buffers;
}
References buf.
Referenced by rpc_exec_epipe_read_cb(), rpc_exec_opipe_read_cb(), rpc_file_exec_epipe_read_cb(), and rpc_file_exec_opipe_read_cb().
ustream_reserve()
char * ustream_reserve (struct ustream * s, int len, int * maxlen)
Definition at line 287 of file ustream.c.
{
    struct ustream_buf *buf;
    if (!ustream_prepare_buf(s, &s->r, len)) {
        __ustream_set_read_blocked(s, s->read_blocked | READ_BLOCKED_FULL);
        *maxlen = 0;
        return NULL;
    }
    buf = s->r.data_tail;
    *maxlen = buf->end - buf->tail;
    return buf->tail;
}
References __ustream_set_read_blocked(), buf, ustream::read_blocked, READ_BLOCKED_FULL, and ustream_prepare_buf().
Referenced by ustream_fd_read_pending().
ustream_set_read_blocked()
void ustream_set_read_blocked (struct ustream * s, bool set)
Definition at line 205 of file ustream.c.
{
    unsigned char val = s->read_blocked & ~READ_BLOCKED_USER;
    if (set)
        val |= READ_BLOCKED_USER;
    __ustream_set_read_blocked(s, val);
}
References __ustream_set_read_blocked(), ustream::read_blocked, and READ_BLOCKED_USER.
Referenced by client_notify_write(), and client_read_cb().
ustream_state_change()
static void ustream_state_change (struct ustream * s) inline static
Definition at line 209 of file ustream.h.
{
    uloop_timeout_set(&s->state_change, 0);
}
References ustream::state_change, and uloop_timeout_set().
Referenced by __ustream_fd_poll(), ustream_fd_read_pending(), ustream_write_error(), and ustream_write_pending().
ustream_vprintf()
int int ustream_vprintf (struct ustream * s, const char * format, va_list arg)
ustream_write()
int ustream_write (struct ustream * s, const char * buf, int len, bool more)
Definition at line 446 of file ustream.c.
{
    struct ustream_buf_list *l = &s->w;
    int wr = 0;
    if (s->write_error)
        return 0;
    if (!l->data_bytes) {
        wr = s->write(s, data, len, more);
        if (wr == len)
            return wr;
        if (wr < 0) {
            ustream_write_error(s);
            return wr;
        }
        data += wr;
        len -= wr;
    }
    return ustream_write_buffered(s, data, len, wr);
}
References ustream_buf_list::data_bytes, ustream_write_buffered(), ustream_write_error(), ustream::w, ustream::write, and ustream::write_error.
Referenced by client_cb(), instance_console(), instance_console_client(), local_cb(), rpc_plugin_call_stdin_cb(), and ustream_vprintf().
ustream_write_pending()
bool ustream_write_pending (struct ustream * s)
Definition at line 378 of file ustream.c.
{
    struct ustream_buf *buf = s->w.head;
    int wr = 0, len;
    if (s->write_error)
        return false;
    while (buf && s->w.data_bytes) {
        struct ustream_buf *next = buf->next;
        int maxlen = buf->tail - buf->data;
        len = s->write(s, buf->data, maxlen, !!buf->next);
        if (len < 0) {
            ustream_write_error(s);
            break;
        }
        if (len == 0)
            break;
        wr += len;
        s->w.data_bytes -= len;
        if (len < maxlen) {
            buf->data += len;
            break;
        }
        ustream_free_buf(&s->w, buf);
        buf = next;
    }
    if (s->notify_write)
        s->notify_write(s, wr);
    if (s->eof && wr && !s->w.data_bytes)
        ustream_state_change(s);
    return !s->w.data_bytes;
}
References buf, ustream_buf_list::data_bytes, ustream::eof, ustream_buf_list::head, ustream_buf::next, ustream::notify_write, ustream_free_buf(), ustream_state_change(), ustream_write_error(), ustream::w, ustream::write, and ustream::write_error.
Referenced by __ustream_fd_poll().