zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/ubus/libubus.h File Reference
libubus.h File Reference
#include <libubox/avl.h>
#include <libubox/list.h>
#include <libubox/blobmsg.h>
#include <libubox/uloop.h>
#include <stdint.h>
#include "ubusmsg.h"
#include "ubus_common.h"
Classes
struct ubus_msghdr_buf
struct ubus_method
struct ubus_object_type
struct ubus_object
struct ubus_subscriber
struct ubus_event_handler
struct ubus_context
struct ubus_object_data
struct ubus_acl_key
struct ubus_request_data
struct ubus_request
struct ubus_notify_request
struct ubus_auto_conn
struct acl_object
Macros
#define UBUS_MAX_NOTIFY_PEERS 16
#define UBUS_OBJECT_TYPE(_name, _methods)
#define __UBUS_METHOD_NOARG(_name, _handler, _tags)
#define __UBUS_METHOD(_name, _handler, _policy, _tags)
#define UBUS_METHOD(_name, _handler, _policy)
#define UBUS_METHOD_TAG(_name, _handler, _policy, _tags)
#define UBUS_METHOD_MASK(_name, _handler, _policy, _mask)
#define UBUS_METHOD_NOARG(_name, _handler)
#define UBUS_METHOD_TAG_NOARG(_name, _handler, _tags)
#define UBUS_TAG_STATUS BIT(0)
#define UBUS_TAG_ADMIN BIT(1)
#define UBUS_TAG_PRIVATE BIT(2)
#define acl_for_each(o, m)
Typedefs
typedef void(* ubus_lookup_handler_t) (struct ubus_context *ctx, struct ubus_object_data *obj, void *priv)
typedef int(* ubus_handler_t) (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
typedef void(* ubus_state_handler_t) (struct ubus_context *ctx, struct ubus_object *obj)
typedef void(* ubus_remove_handler_t) (struct ubus_context *ctx, struct ubus_subscriber *obj, uint32_t id)
typedef void(* ubus_event_handler_t) (struct ubus_context *ctx, struct ubus_event_handler *ev, const char *type, struct blob_attr *msg)
typedef void(* ubus_data_handler_t) (struct ubus_request *req, int type, struct blob_attr *msg)
typedef void(* ubus_fd_handler_t) (struct ubus_request *req, int fd)
typedef void(* ubus_complete_handler_t) (struct ubus_request *req, int ret)
typedef void(* ubus_notify_complete_handler_t) (struct ubus_notify_request *req, int idx, int ret)
typedef void(* ubus_notify_data_handler_t) (struct ubus_notify_request *req, int type, struct blob_attr *msg)
typedef void(* ubus_connect_handler_t) (struct ubus_context *ctx)
typedef bool(* ubus_new_object_handler_t) (struct ubus_context *ctx, struct ubus_subscriber *sub, const char *path)
Functions
struct ubus_context * ubus_connect (const char *path)
int ubus_connect_ctx (struct ubus_context *ctx, const char *path)
void ubus_auto_connect (struct ubus_auto_conn *conn)
int ubus_reconnect (struct ubus_context *ctx, const char *path)
void ubus_free (struct ubus_context *ctx)
void ubus_shutdown (struct ubus_context *ctx)
static void ubus_auto_shutdown (struct ubus_auto_conn *conn)
const char * ubus_strerror (int error)
static void ubus_add_uloop (struct ubus_context *ctx)
static void ubus_handle_event (struct ubus_context *ctx)
int ubus_complete_request (struct ubus_context *ctx, struct ubus_request *req, int timeout)
void ubus_complete_request_async (struct ubus_context *ctx, struct ubus_request *req)
void ubus_abort_request (struct ubus_context *ctx, struct ubus_request *req)
int ubus_lookup (struct ubus_context *ctx, const char *path, ubus_lookup_handler_t cb, void *priv)
int ubus_lookup_id (struct ubus_context *ctx, const char *path, uint32_t *id)
int ubus_add_object (struct ubus_context *ctx, struct ubus_object *obj)
int ubus_remove_object (struct ubus_context *ctx, struct ubus_object *obj)
int ubus_register_subscriber (struct ubus_context *ctx, struct ubus_subscriber *obj)
static int ubus_unregister_subscriber (struct ubus_context *ctx, struct ubus_subscriber *obj)
int ubus_subscribe (struct ubus_context *ctx, struct ubus_subscriber *obj, uint32_t id)
int ubus_unsubscribe (struct ubus_context *ctx, struct ubus_subscriber *obj, uint32_t id)
int __ubus_monitor (struct ubus_context *ctx, const char *type)
static int ubus_monitor_start (struct ubus_context *ctx)
static int ubus_monitor_stop (struct ubus_context *ctx)
int ubus_register_acl (struct ubus_context *ctx)
int ubus_invoke_fd (struct ubus_context *ctx, uint32_t obj, const char *method, struct blob_attr *msg, ubus_data_handler_t cb, void *priv, int timeout, int fd)
static int ubus_invoke (struct ubus_context *ctx, uint32_t obj, const char *method, struct blob_attr *msg, ubus_data_handler_t cb, void *priv, int timeout)
int ubus_invoke_async_fd (struct ubus_context *ctx, uint32_t obj, const char *method, struct blob_attr *msg, struct ubus_request *req, int fd)
static int ubus_invoke_async (struct ubus_context *ctx, uint32_t obj, const char *method, struct blob_attr *msg, struct ubus_request *req)
int ubus_send_reply (struct ubus_context *ctx, struct ubus_request_data *req, struct blob_attr *msg)
static void ubus_defer_request (struct ubus_context *ctx, struct ubus_request_data *req, struct ubus_request_data *new_req)
static void ubus_request_set_fd (struct ubus_context *ctx, struct ubus_request_data *req, int fd)
static int ubus_request_get_caller_fd (struct ubus_request_data *req)
void ubus_complete_deferred_request (struct ubus_context *ctx, struct ubus_request_data *req, int ret)
int ubus_notify (struct ubus_context *ctx, struct ubus_object *obj, const char *type, struct blob_attr *msg, int timeout)
int ubus_notify_async (struct ubus_context *ctx, struct ubus_object *obj, const char *type, struct blob_attr *msg, struct ubus_notify_request *req)
int ubus_send_event (struct ubus_context *ctx, const char *id, struct blob_attr *data)
int ubus_register_event_handler (struct ubus_context *ctx, struct ubus_event_handler *ev, const char *pattern)
static int ubus_unregister_event_handler (struct ubus_context *ctx, struct ubus_event_handler *ev)
Variables
struct avl_tree acl_objects
Class Documentation
ubus_msghdr_buf
struct ubus_msghdr_buf
Definition at line 41 of file libubus.h.
Class Members
struct blob_attr * data
struct ubus_msghdr hdr
ubus_method
struct ubus_method
Definition at line 108 of file libubus.h.
Class Members
struct blob_attr data[]
ubus_handler_t handler
struct list_head list
unsigned long mask
int n_policy
const char * name
const struct blobmsg_policy * policy
unsigned long tags
ubus_object_type
struct ubus_object_type
Definition at line 118 of file libubus.h.
Class Members
uint32_t id
struct ubus_id id
const struct ubus_method * methods
struct list_head methods
int n_methods
const char * name
int refcount
ubus_object
struct ubus_object
Definition at line 126 of file libubus.h.
Class Members
struct avl_node avl
struct ubus_client * client
int event_seen
struct list_head events
bool has_subscribers
uint32_t id
struct ubus_id id
unsigned int invoke_seq
struct list_head list
const struct ubus_method * methods
int n_methods
const char * name
const char * path
struct avl_node path
int(*)(struct ubus_client *client, struct ubus_msg_buf *ub, const char *method, struct blob_attr *msg) recv_msg
ubus_state_handler_t subscribe_cb
struct list_head subscribers target_list
struct ubus_object_type * type
ubus_subscriber
struct ubus_subscriber
Definition at line 142 of file libubus.h.
Class Members
ubus_handler_t cb
struct list_head list
ubus_new_object_handler_t new_obj_cb
struct ubus_object obj
ubus_remove_handler_t remove_cb
ubus_event_handler
struct ubus_event_handler
Definition at line 151 of file libubus.h.
Class Members
ubus_event_handler_t cb
struct ubus_object obj
ubus_context
struct ubus_context
Definition at line 157 of file libubus.h.
Class Members
struct ubus_event_handler auto_subscribe_event_handler
struct list_head auto_subscribers
bool cancel_poll
void(*)(struct ubus_context *ctx) connection_lost
uint32_t local_id
void(*)(struct ubus_context *ctx, uint32_t seq, struct blob_attr *data) monitor_cb
struct ubus_msghdr_buf msgbuf
uint32_t msgbuf_data_len
int msgbuf_reduction_counter
struct avl_tree objects
struct list_head pending
struct uloop_timeout pending_timer
uint16_t request_seq
struct list_head requests
struct uloop_fd sock
int stack_depth
ubus_object_data
struct ubus_object_data
Definition at line 181 of file libubus.h.
Class Members
uint32_t id
const char * path
struct blob_attr * signature
uint32_t type_id
ubus_acl_key
struct ubus_acl_key
Definition at line 188 of file libubus.h.
Class Members
const char * group
const char * object
const char * user
ubus_request_data
struct ubus_request_data
Definition at line 194 of file libubus.h.
Class Members
struct ubus_acl_key acl
bool deferred
int fd
uint32_t object
uint32_t peer
int req_fd
uint16_t seq
ubus_request
struct ubus_request
Definition at line 207 of file libubus.h.
Class Members
bool blocked
bool cancelled
ubus_complete_handler_t complete_cb
struct ubus_context * ctx
ubus_data_handler_t data_cb
int fd
ubus_fd_handler_t fd_cb
struct list_head list
bool notify
uint32_t peer
struct list_head pending
void * priv
ubus_data_handler_t raw_data_cb
uint16_t seq
int status_code
bool status_msg
ubus_notify_request
struct ubus_notify_request
Definition at line 231 of file libubus.h.
Class Members
ubus_notify_complete_handler_t complete_cb
ubus_notify_data_handler_t data_cb
uint32_t id[UBUS_MAX_NOTIFY_PEERS+1]
uint32_t pending
struct ubus_request req
ubus_notify_complete_handler_t status_cb
ubus_auto_conn
struct ubus_auto_conn
Definition at line 242 of file libubus.h.
Class Members
ubus_connect_handler_t cb
struct ubus_context ctx
const char * path
struct uloop_timeout timer
acl_object
struct acl_object
Definition at line 334 of file libubus.h.
Class Members
struct blob_attr * acl
struct avl_node avl
struct ubus_acl_key key
Macro Definition Documentation
__UBUS_METHOD
#define __UBUS_METHOD (_name, _handler, _policy, _tags)
Value:
    __UBUS_METHOD_NOARG(_name, _handler, _tags),    \
    .policy = _policy,              \
    .n_policy = ARRAY_SIZE(_policy)
Definition at line 81 of file libubus.h.
#define __UBUS_METHOD(_name, _handler, _policy, _tags)  \
    __UBUS_METHOD_NOARG(_name, _handler, _tags),    \
    .policy = _policy,              \
    .n_policy = ARRAY_SIZE(_policy)
__UBUS_METHOD_NOARG
#define __UBUS_METHOD_NOARG (_name, _handler, _tags)
Value:
    .name = _name,                  \
    .handler = _handler,                \
    .tags = _tags
Definition at line 76 of file libubus.h.
#define __UBUS_METHOD_NOARG(_name, _handler, _tags) \
    .name = _name,                  \
    .handler = _handler,                \
    .tags = _tags
acl_for_each
#define acl_for_each (o, m)
Value:
    if ((m)->object && (m)->user && (m)->group) \
        avl_for_element_range(avl_find_ge_element(&acl_objects, m, o, avl), avl_find_le_element(&acl_objects, m, o, avl), o, avl)
Definition at line 343 of file libubus.h.
#define acl_for_each(o, m) \
    if ((m)->object && (m)->user && (m)->group) \
        avl_for_element_range(avl_find_ge_element(&acl_objects, m, o, avl), avl_find_le_element(&acl_objects, m, o, avl), o, avl)
UBUS_MAX_NOTIFY_PEERS
#define UBUS_MAX_NOTIFY_PEERS 16
Definition at line 29 of file libubus.h.
Referenced by ubus_process_notify_status().
UBUS_METHOD
#define UBUS_METHOD (_name, _handler, _policy)
Value:
    { __UBUS_METHOD(_name, _handler, _policy, 0) }
Definition at line 86 of file libubus.h.
#define UBUS_METHOD(_name, _handler, _policy)       \
    { __UBUS_METHOD(_name, _handler, _policy, 0) }
Referenced by rpc_file_api_init(), rpc_iwinfo_api_init(), rpc_rc_api_init(), rpc_session_api_init(), rpc_sys_api_init(), and rpc_uci_api_init().
UBUS_METHOD_MASK
#define UBUS_METHOD_MASK (_name, _handler, _policy, _mask)
Value:
    {                       \
        __UBUS_METHOD(_name, _handler, _policy, 0),\
        .mask = _mask               \
    }
Definition at line 92 of file libubus.h.
#define UBUS_METHOD_MASK(_name, _handler, _policy, _mask) \
    {                       \
        __UBUS_METHOD(_name, _handler, _policy, 0),\
        .mask = _mask               \
    }
UBUS_METHOD_NOARG
#define UBUS_METHOD_NOARG (_name, _handler)
Value:
    { __UBUS_METHOD_NOARG(_name, _handler, 0) }
Definition at line 98 of file libubus.h.
#define UBUS_METHOD_NOARG(_name, _handler)      \
    { __UBUS_METHOD_NOARG(_name, _handler, 0) }
Referenced by rpc_iwinfo_api_init(), rpc_sys_api_init(), and rpc_uci_api_init().
UBUS_METHOD_TAG
#define UBUS_METHOD_TAG (_name, _handler, _policy, _tags)
Value:
    { __UBUS_METHOD(_name, _handler, _policy, _tags) }
Definition at line 89 of file libubus.h.
#define UBUS_METHOD_TAG(_name, _handler, _policy, _tags)\
    { __UBUS_METHOD(_name, _handler, _policy, _tags) }
UBUS_METHOD_TAG_NOARG
#define UBUS_METHOD_TAG_NOARG (_name, _handler, _tags)
Value:
    { __UBUS_METHOD_NOARG(_name, _handler, _tags) }
Definition at line 101 of file libubus.h.
#define UBUS_METHOD_TAG_NOARG(_name, _handler, _tags)   \
    { __UBUS_METHOD_NOARG(_name, _handler, _tags) }
UBUS_OBJECT_TYPE
#define UBUS_OBJECT_TYPE (_name, _methods)
Value:
    {                       \
        .name = _name,              \
        .id = 0,                \
        .n_methods = ARRAY_SIZE(_methods),  \
        .methods = _methods         \
    }
Definition at line 68 of file libubus.h.
#define UBUS_OBJECT_TYPE(_name, _methods)       \
    {                       \
        .name = _name,              \
        .id = 0,                \
        .n_methods = ARRAY_SIZE(_methods),  \
        .methods = _methods         \
    }
Referenced by rpc_file_api_init(), rpc_iwinfo_api_init(), rpc_rc_api_init(), rpc_session_api_init(), rpc_sys_api_init(), and rpc_uci_api_init().
UBUS_TAG_ADMIN
#define UBUS_TAG_ADMIN BIT(1)
Definition at line 105 of file libubus.h.
UBUS_TAG_PRIVATE
#define UBUS_TAG_PRIVATE BIT(2)
Definition at line 106 of file libubus.h.
UBUS_TAG_STATUS
#define UBUS_TAG_STATUS BIT(0)
Definition at line 104 of file libubus.h.
Typedef Documentation
ubus_complete_handler_t
typedef void(* ubus_complete_handler_t) (struct ubus_request *req, int ret)
Definition at line 60 of file libubus.h.
ubus_connect_handler_t
typedef void(* ubus_connect_handler_t) (struct ubus_context *ctx)
Definition at line 65 of file libubus.h.
ubus_data_handler_t
typedef void(* ubus_data_handler_t) (struct ubus_request *req, int type, struct blob_attr *msg)
Definition at line 57 of file libubus.h.
ubus_event_handler_t
typedef void(* ubus_event_handler_t) (struct ubus_context *ctx, struct ubus_event_handler *ev, const char *type, struct blob_attr *msg)
Definition at line 55 of file libubus.h.
ubus_fd_handler_t
typedef void(* ubus_fd_handler_t) (struct ubus_request *req, int fd)
Definition at line 59 of file libubus.h.
ubus_handler_t
typedef int(* ubus_handler_t) (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
Definition at line 49 of file libubus.h.
ubus_lookup_handler_t
typedef void(* ubus_lookup_handler_t) (struct ubus_context *ctx, struct ubus_object_data *obj, void *priv)
Definition at line 46 of file libubus.h.
ubus_new_object_handler_t
typedef bool(* ubus_new_object_handler_t) (struct ubus_context *ctx, struct ubus_subscriber *sub, const char *path)
Definition at line 66 of file libubus.h.
ubus_notify_complete_handler_t
typedef void(* ubus_notify_complete_handler_t) (struct ubus_notify_request *req, int idx, int ret)
Definition at line 61 of file libubus.h.
ubus_notify_data_handler_t
typedef void(* ubus_notify_data_handler_t) (struct ubus_notify_request *req, int type, struct blob_attr *msg)
Definition at line 63 of file libubus.h.
ubus_remove_handler_t
typedef void(* ubus_remove_handler_t) (struct ubus_context *ctx, struct ubus_subscriber *obj, uint32_t id)
Definition at line 53 of file libubus.h.
ubus_state_handler_t
typedef void(* ubus_state_handler_t) (struct ubus_context *ctx, struct ubus_object *obj)
Definition at line 52 of file libubus.h.
Function Documentation
__ubus_monitor()
int __ubus_monitor (struct ubus_context * ctx, const char * type)
Definition at line 495 of file libubus-req.c.
{
    blob_buf_init(&b, 0);
    return ubus_invoke(ctx, UBUS_SYSTEM_OBJECT_MONITOR, type, b.head, NULL, NULL, 1000);
}
References b, blob_buf_init(), ctx, blob_buf::head, type, ubus_invoke(), and UBUS_SYSTEM_OBJECT_MONITOR.
Referenced by ubus_monitor_start(), and ubus_monitor_stop().
ubus_abort_request()
void ubus_abort_request (struct ubus_context * ctx, struct ubus_request * req)
Definition at line 80 of file libubus-req.c.
{
    if (list_empty(&req->list))
        return;
    req->cancelled = true;
    __ubus_process_req_data(req);
    list_del_init(&req->list);
}
References __ubus_process_req_data(), ubus_request::cancelled, ubus_request::list, list_del_init(), and list_empty().
Referenced by ubus_notify().
ubus_add_object()
int ubus_add_object (struct ubus_context * ctx, struct ubus_object * obj)
Definition at line 209 of file libubus-obj.c.
{
    struct ubus_request req;
    int ret;
    blob_buf_init(&b, 0);
    if (obj->name && obj->type) {
        blob_put_string(&b, UBUS_ATTR_OBJPATH, obj->name);
        if (obj->type->id)
            blob_put_int32(&b, UBUS_ATTR_OBJTYPE, obj->type->id);
        else if (!ubus_push_object_type(obj->type))
            return UBUS_STATUS_INVALID_ARGUMENT;
    }
    if (ubus_start_request(ctx, &req, b.head, UBUS_MSG_ADD_OBJECT, 0) < 0)
        return UBUS_STATUS_INVALID_ARGUMENT;
    req.raw_data_cb = ubus_add_object_cb;
    req.priv = obj;
    ret = ubus_complete_request(ctx, &req, 0);
    if (ret)
        return ret;
    if (!obj->id)
        return UBUS_STATUS_NO_DATA;
    return 0;
}
References b, blob_buf_init(), blob_put_int32, blob_put_string(), ctx, blob_buf::head, ubus_object::id, ubus_object_type::id, ubus_object::name, ubus_request::priv, ubus_request::raw_data_cb, ubus_object::type, ubus_add_object_cb(), UBUS_ATTR_OBJPATH, UBUS_ATTR_OBJTYPE, ubus_complete_request(), UBUS_MSG_ADD_OBJECT, ubus_push_object_type(), ubus_start_request(), UBUS_STATUS_INVALID_ARGUMENT, and UBUS_STATUS_NO_DATA.
Referenced by add_subsystem(), client_main(), main(), netifd_add_object(), netifd_ubus_add_interface(), rpc_file_api_init(), rpc_iwinfo_api_init(), rpc_plugin_register_exec(), rpc_rc_api_init(), rpc_session_api_init(), rpc_sys_api_init(), rpc_uci_api_init(), rpc_ucode_script_register(), server_main(), ubus_connect_handler(), ubus_init_service(), ubus_init_system(), ubus_lua_add(), ubus_refresh_state(), ubus_register_event_handler(), and ubus_register_subscriber().
ubus_add_uloop()
static void ubus_add_uloop (struct ubus_context * ctx) inline static
Definition at line 268 of file libubus.h.
{
    uloop_fd_add(&ctx->sock, ULOOP_BLOCKING | ULOOP_READ);
}
References ctx, ubus_context::sock, ULOOP_BLOCKING, uloop_fd_add(), and ULOOP_READ.
Referenced by do_listen(), main(), netifd_ubus_add_fd(), ubus_auto_connect_cb(), ubus_auto_reconnect_cb(), ubus_cli_monitor(), ubus_cli_wait_for(), ubus_connect_cb(), ubus_lua_connect(), and ubus_reconnect_cb().
ubus_auto_connect()
void ubus_auto_connect (struct ubus_auto_conn * conn)
Definition at line 345 of file libubus.c.
{
    conn->timer.cb = ubus_auto_connect_cb;
    ubus_auto_connect_cb(&conn->timer);
}
References uloop_timeout::cb, conn, ubus_auto_conn::timer, and ubus_auto_connect_cb().
Referenced by ustp_ubus_init().
ubus_auto_shutdown()
static void ubus_auto_shutdown (struct ubus_auto_conn * conn) inline static
Definition at line 260 of file libubus.h.
{
    uloop_timeout_cancel(&conn->timer);
    ubus_shutdown(&conn->ctx);
}
References conn, ubus_auto_conn::ctx, ubus_auto_conn::timer, ubus_shutdown(), and uloop_timeout_cancel().
Referenced by ustp_ubus_exit().
ubus_complete_deferred_request()
void ubus_complete_deferred_request (struct ubus_context * ctx, struct ubus_request_data * req, int ret)
Definition at line 189 of file libubus-req.c.
{
    blob_buf_init(&b, 0);
    blob_put_int32(&b, UBUS_ATTR_STATUS, ret);
    blob_put_int32(&b, UBUS_ATTR_OBJID, req->object);
    ubus_send_msg(ctx, req->seq, b.head, UBUS_MSG_STATUS, req->peer, req->fd);
}
References b, blob_buf_init(), blob_put_int32, ctx, ubus_request_data::fd, blob_buf::head, ubus_request_data::object, ubus_request_data::peer, ubus_request_data::seq, UBUS_ATTR_OBJID, UBUS_ATTR_STATUS, UBUS_MSG_STATUS, and ubus_send_msg().
Referenced by rc_init_cb(), rc_list_readdir(), rpc_exec_reply(), rpc_file_exec_reply(), rpc_ucode_request_finish(), rpc_ucode_script_call(), test_hello_reply(), ubus_lua_complete_deferred_request(), ubus_process_invoke(), and wireless_complete_kill_request().
ubus_complete_request()
int ubus_complete_request (struct ubus_context * ctx, struct ubus_request * req, int timeout)
Definition at line 140 of file libubus-req.c.
{
    ubus_complete_handler_t complete_cb = req->complete_cb;
    int status = UBUS_STATUS_NO_DATA;
    int64_t timeout = 0, time_end = 0;
    if (req_timeout)
        time_end = get_time_msec() + req_timeout;
    ubus_complete_request_async(ctx, req);
    req->complete_cb = ubus_sync_req_cb;
    ctx->stack_depth++;
    while (!req->status_msg) {
        if (req_timeout) {
            timeout = time_end - get_time_msec();
            if (timeout <= 0) {
                ubus_set_req_status(req, UBUS_STATUS_TIMEOUT);
                break;
            }
        }
        ubus_poll_data(ctx, (unsigned int) timeout);
        if (ctx->sock.eof) {
            ubus_set_req_status(req, UBUS_STATUS_CONNECTION_FAILED);
            ctx->cancel_poll = true;
            break;
        }
    }
    ctx->stack_depth--;
    if (ctx->stack_depth)
        ctx->cancel_poll = true;
    if (req->status_msg)
        status = req->status_code;
    req->complete_cb = complete_cb;
    if (req->complete_cb)
        req->complete_cb(req, status);
    if (!ctx->stack_depth && !ctx->sock.registered)
        ctx->pending_timer.cb(&ctx->pending_timer);
    return status;
}
References ubus_context::cancel_poll, uloop_timeout::cb, ubus_request::complete_cb, ctx, uloop_fd::eof, get_time_msec(), ubus_context::pending_timer, uloop_fd::registered, ubus_context::sock, ubus_context::stack_depth, ubus_request::status_code, ubus_request::status_msg, timeout, ubus_complete_request_async(), ubus_poll_data(), ubus_set_req_status(), UBUS_STATUS_CONNECTION_FAILED, UBUS_STATUS_NO_DATA, UBUS_STATUS_TIMEOUT, and ubus_sync_req_cb().
Referenced by __ubus_subscribe_request(), ubus_add_object(), ubus_invoke_fd(), ubus_lookup(), ubus_lookup_id(), ubus_notify(), ubus_remove_object(), and ubus_send_event().
ubus_complete_request_async()
void ubus_complete_request_async (struct ubus_context * ctx, struct ubus_request * req)
Definition at line 90 of file libubus-req.c.
{
    if (!list_empty(&req->list))
        return;
    list_add(&req->list, &ctx->requests);
}
References ctx, ubus_request::list, list_add(), list_empty(), and ubus_context::requests.
Referenced by acl_query(), client_main(), and ubus_complete_request().
ubus_connect()
struct ubus_context * ubus_connect (const char * path)
Definition at line 351 of file libubus.c.
{
    struct ubus_context *ctx;
    ctx = calloc(1, sizeof(*ctx));
    if (!ctx)
        return NULL;
    if (ubus_connect_ctx(ctx, path)) {
        free(ctx);
        ctx = NULL;
    }
    return ctx;
}
References ctx, path, and ubus_connect_ctx().
Referenced by main(), netifd_ubus_init(), pass_console(), run_netifd(), ubus_connect_cb(), ubus_lua_connect(), and uxc_attach().
ubus_connect_ctx()
int ubus_connect_ctx (struct ubus_context * ctx, const char * path)
Definition at line 284 of file libubus.c.
{
    uloop_init();
    memset(ctx, 0, sizeof(*ctx));
    ctx->sock.fd = -1;
    ctx->sock.cb = ubus_handle_data;
    ctx->connection_lost = ubus_default_connection_lost;
    ctx->pending_timer.cb = ubus_process_pending_msg;
    ctx->msgbuf.data = calloc(1, UBUS_MSG_CHUNK_SIZE);
    if (!ctx->msgbuf.data)
        return -1;
    ctx->msgbuf_data_len = UBUS_MSG_CHUNK_SIZE;
    INIT_LIST_HEAD(&ctx->requests);
    INIT_LIST_HEAD(&ctx->pending);
    INIT_LIST_HEAD(&ctx->auto_subscribers);
    avl_init(&ctx->objects, ubus_cmp_id, false, NULL);
    if (ubus_reconnect(ctx, path)) {
        free(ctx->msgbuf.data);
        ctx->msgbuf.data = NULL;
        return -1;
    }
    return 0;
}
References ubus_context::auto_subscribers, avl_init(), uloop_fd::cb, uloop_timeout::cb, ubus_context::connection_lost, ctx, ubus_msghdr_buf::data, uloop_fd::fd, INIT_LIST_HEAD(), ubus_context::msgbuf, ubus_context::msgbuf_data_len, ubus_context::objects, path, ubus_context::pending, ubus_context::pending_timer, ubus_context::requests, ubus_context::sock, ubus_cmp_id(), ubus_default_connection_lost(), ubus_handle_data(), UBUS_MSG_CHUNK_SIZE, ubus_process_pending_msg(), ubus_reconnect(), and uloop_init().
Referenced by ubus_auto_connect_cb(), and ubus_connect().
ubus_defer_request()
static void ubus_defer_request (struct ubus_context * ctx, struct ubus_request_data * req, struct ubus_request_data * new_req) inline static
Definition at line 375 of file libubus.h.
{
    (void) ctx;
    memcpy(new_req, req, sizeof(*req));
    req->deferred = true;
}
References ctx, and ubus_request_data::deferred.
Referenced by rc_init(), rc_list(), rpc_exec(), rpc_file_exec_run(), rpc_ucode_script_call(), test_hello(), ubus_lua_defer_request(), and wireless_device_process_kill_all().
ubus_free()
void ubus_free (struct ubus_context * ctx)
Definition at line 378 of file libubus.c.
{
    ubus_shutdown(ctx);
    free(ctx);
}
References ctx, and ubus_shutdown().
Referenced by free_and_exit(), jail_network_stop(), main(), netifd_ubus_done(), pass_console(), post_poststop(), ubus_lua__gc(), and uxc_attach().
ubus_handle_event()
static void ubus_handle_event (struct ubus_context * ctx) inline static
Definition at line 274 of file libubus.h.
{
    ctx->sock.cb(&ctx->sock, ULOOP_READ);
}
References uloop_fd::cb, ctx, ubus_context::sock, and ULOOP_READ.
ubus_invoke()
static int ubus_invoke (struct ubus_context * ctx, uint32_t obj, const char * method, struct blob_attr * msg, ubus_data_handler_t cb, void * priv, int timeout) inline static
Definition at line 354 of file libubus.h.
{
    return ubus_invoke_fd(ctx, obj, method, msg, cb, priv, timeout, -1);
}
References ctx, timeout, and ubus_invoke_fd().
Referenced by __ubus_monitor(), client_main(), get_ocistate(), jail_delete_instance(), jail_network_reload(), netifd_extdev_invoke(), netifd_sub_cb(), netifd_ubus_get_procd_data(), rpc_uci_trigger_event(), run_netifd(), run_ubusd(), runtime_load(), test_count(), ubus_cli_call(), ubus_lua_call(), ubus_register_event_handler(), ustp_ubus_exit(), uxc_boot(), uxc_create(), uxc_delete(), uxc_kill(), and uxc_start().
ubus_invoke_async()
static int ubus_invoke_async (struct ubus_context * ctx, uint32_t obj, const char * method, struct blob_attr * msg, struct ubus_request * req) inline static
Definition at line 365 of file libubus.h.
{
    return ubus_invoke_async_fd(ctx, obj, method, msg, req, -1);
}
References ctx, and ubus_invoke_async_fd().
Referenced by acl_query(), and client_main().
ubus_invoke_async_fd()
int ubus_invoke_async_fd (struct ubus_context * ctx, uint32_t obj, const char * method, struct blob_attr * msg, struct ubus_request * req, int fd)
Definition at line 220 of file libubus-req.c.
{
    blob_buf_init(&b, 0);
    blob_put_int32(&b, UBUS_ATTR_OBJID, obj);
    blob_put_string(&b, UBUS_ATTR_METHOD, method);
    ubus_put_data(&b, msg);
    memset(req, 0, sizeof(*req));
    req->fd = fd;
    if (__ubus_start_request(ctx, req, b.head, UBUS_MSG_INVOKE, obj) < 0)
        return UBUS_STATUS_INVALID_ARGUMENT;
    return 0;
}
References __ubus_start_request(), b, blob_buf_init(), blob_put_int32, blob_put_string(), ctx, ubus_request::fd, blob_buf::head, UBUS_ATTR_METHOD, UBUS_ATTR_OBJID, UBUS_MSG_INVOKE, ubus_put_data(), and UBUS_STATUS_INVALID_ARGUMENT.
Referenced by ubus_invoke_async(), and ubus_invoke_fd().
ubus_invoke_fd()
int ubus_invoke_fd (struct ubus_context * ctx, uint32_t obj, const char * method, struct blob_attr * msg, ubus_data_handler_t cb, void * priv, int timeout, int fd)
Definition at line 236 of file libubus-req.c.
{
    struct ubus_request req;
    int rc;
    rc = ubus_invoke_async_fd(ctx, obj, method, msg, &req, fd);
    if (rc)
        return rc;
    req.data_cb = cb;
    req.priv = priv;
    return ubus_complete_request(ctx, &req, timeout);
}
References ctx, ubus_request::data_cb, ubus_request::fd, ubus_request::priv, rc(), timeout, ubus_complete_request(), and ubus_invoke_async_fd().
Referenced by netns_updown(), pass_console(), ubus_invoke(), and uxc_attach().
ubus_lookup()
int ubus_lookup (struct ubus_context * ctx, const char * path, ubus_lookup_handler_t cb, void * priv)
Definition at line 161 of file libubus.c.
{
    struct ubus_lookup_request lookup;
    blob_buf_init(&b, 0);
    if (path)
        blob_put_string(&b, UBUS_ATTR_OBJPATH, path);
    if (ubus_start_request(ctx, &lookup.req, b.head, UBUS_MSG_LOOKUP, 0) < 0)
        return UBUS_STATUS_INVALID_ARGUMENT;
    lookup.req.raw_data_cb = ubus_lookup_cb;
    lookup.req.priv = priv;
    lookup.cb = cb;
    return ubus_complete_request(ctx, &lookup.req, 0);
}
References b, blob_buf_init(), blob_put_string(), ubus_lookup_request::cb, ctx, blob_buf::head, path, ubus_request::priv, ubus_request::raw_data_cb, ubus_lookup_request::req, UBUS_ATTR_OBJPATH, ubus_complete_request(), ubus_lookup_cb(), UBUS_MSG_LOOKUP, ubus_start_request(), and UBUS_STATUS_INVALID_ARGUMENT.
Referenced by rpc_plugin_lookup_plugin(), ubus_cli_list(), ubus_cli_wait_for(), ubus_lua_objects(), ubus_lua_signatures(), ubus_refresh_auto_subscribe(), and ubus_register_subscriber().
ubus_lookup_id()
int ubus_lookup_id (struct ubus_context * ctx, const char * path, uint32_t * id)
Definition at line 192 of file libubus.c.
{
    struct ubus_request req;
    blob_buf_init(&b, 0);
    if (path)
        blob_put_string(&b, UBUS_ATTR_OBJPATH, path);
    if (ubus_start_request(ctx, &req, b.head, UBUS_MSG_LOOKUP, 0) < 0)
        return UBUS_STATUS_INVALID_ARGUMENT;
    req.raw_data_cb = ubus_lookup_id_cb;
    req.priv = id;
    return ubus_complete_request(ctx, &req, 0);
}
References b, blob_buf_init(), blob_put_string(), ctx, blob_buf::head, id, path, ubus_request::priv, ubus_request::raw_data_cb, UBUS_ATTR_OBJPATH, ubus_complete_request(), ubus_lookup_id_cb(), UBUS_MSG_LOOKUP, ubus_start_request(), and UBUS_STATUS_INVALID_ARGUMENT.
Referenced by client_main(), extdev_lookup_id(), get_ocistate(), jail_delete_instance(), jail_network_reload(), netifd_sub_cb(), netifd_ubus_get_procd_data(), netns_updown(), pass_console(), rpc_uci_trigger_event(), run_netifd(), run_ubusd(), runtime_load(), test_count(), ubus_cli_call(), ubus_cli_subscribe(), ubus_lua_call(), ubus_lua_do_subscribe(), ustp_ubus_exit(), uxc_attach(), uxc_boot(), uxc_create(), uxc_delete(), uxc_kill(), uxc_start(), watch_subscribe_cb(), and watch_ubus_service().
ubus_monitor_start()
static int ubus_monitor_start (struct ubus_context * ctx) inline static
Definition at line 321 of file libubus.h.
{
    return __ubus_monitor(ctx, "add");
}
References __ubus_monitor(), and ctx.
Referenced by ubus_cli_monitor().
ubus_monitor_stop()
static int ubus_monitor_stop (struct ubus_context * ctx) inline static
Definition at line 326 of file libubus.h.
{
    return __ubus_monitor(ctx, "remove");
}
References __ubus_monitor(), and ctx.
Referenced by ubus_cli_monitor().
ubus_notify()
int ubus_notify (struct ubus_context * ctx, struct ubus_object * obj, const char * type, struct blob_attr * msg, int timeout)
Definition at line 311 of file libubus-req.c.
{
    struct ubus_notify_request req;
    int ret;
    ret = __ubus_notify_async(ctx, obj, type, msg, &req, timeout >= 0);
    if (ret < 0)
        return ret;
    if (timeout < 0) {
        ubus_abort_request(ctx, &req.req);
        return 0;
    }
    return ubus_complete_request(ctx, &req.req, timeout);
}
References __ubus_notify_async(), ctx, ubus_notify_request::req, timeout, type, ubus_abort_request(), and ubus_complete_request().
Referenced by netifd_ubus_device_notify(), netifd_ubus_interface_notify(), procd_bcast_event(), test_client_notify_cb(), ubus_event_bcast(), and ubus_lua_notify().
ubus_notify_async()
int ubus_notify_async (struct ubus_context * ctx, struct ubus_object * obj, const char * type, struct blob_attr * msg, struct ubus_notify_request * req)
Definition at line 304 of file libubus-req.c.
{
    return __ubus_notify_async(ctx, obj, type, msg, req, true);
}
References __ubus_notify_async(), ctx, ubus_notify_request::req, and type.
ubus_reconnect()
int ubus_reconnect (struct ubus_context * ctx, const char * path)
Definition at line 395 of file libubus-io.c.
{
    struct {
        struct ubus_msghdr hdr;
        struct blob_attr data;
    } hdr;
    struct blob_attr *buf;
    int ret = UBUS_STATUS_UNKNOWN_ERROR;
    if (!path)
        path = UBUS_UNIX_SOCKET;
    if (ctx->sock.fd >= 0) {
        if (ctx->sock.registered)
            uloop_fd_delete(&ctx->sock);
        close(ctx->sock.fd);
    }
    ctx->sock.eof = false;
    ctx->sock.error = false;
    ctx->sock.fd = usock(USOCK_UNIX, path, NULL);
    if (ctx->sock.fd < 0)
        return UBUS_STATUS_CONNECTION_FAILED;
    if (read(ctx->sock.fd, &hdr, sizeof(hdr)) != sizeof(hdr))
        goto out_close;
    if (!ubus_validate_hdr(&hdr.hdr))
        goto out_close;
    if (hdr.hdr.type != UBUS_MSG_HELLO)
        goto out_close;
    buf = calloc(1, blob_raw_len(&hdr.data));
    if (!buf)
        goto out_close;
    memcpy(buf, &hdr.data, sizeof(hdr.data));
    if (read(ctx->sock.fd, blob_data(buf), blob_len(buf)) != (ssize_t) blob_len(buf))
        goto out_free;
    ctx->local_id = hdr.hdr.peer;
    if (!ctx->local_id)
        goto out_free;
    ret = UBUS_STATUS_OK;
    fcntl(ctx->sock.fd, F_SETFL, fcntl(ctx->sock.fd, F_GETFL) | O_NONBLOCK | O_CLOEXEC);
    ubus_refresh_state(ctx);
out_free:
    free(buf);
out_close:
    if (ret)
        close(ctx->sock.fd);
    return ret;
}
References blob_data(), blob_len(), blob_raw_len(), buf, ctx, uloop_fd::eof, uloop_fd::error, uloop_fd::fd, ubus_context::local_id, path, uloop_fd::registered, ubus_context::sock, UBUS_MSG_HELLO, ubus_refresh_state(), UBUS_STATUS_CONNECTION_FAILED, UBUS_STATUS_OK, UBUS_STATUS_UNKNOWN_ERROR, ubus_validate_hdr(), uloop_fd_delete(), usock(), and USOCK_UNIX.
Referenced by netifd_ubus_reconnect_timer(), ubus_auto_reconnect_cb(), ubus_connect_ctx(), and ubus_reconnect_cb().
ubus_register_acl()
int ubus_register_acl (struct ubus_context * ctx)
Definition at line 142 of file libubus-acl.c.
{
    int ret;
    acl_event.cb = acl_subscribe_cb;
    ret = ubus_register_event_handler(ctx, &acl_event, "ubus.acl.sequence");
    if (!ret)
        acl_query(ctx);
    return ret;
}
References acl_event, acl_query(), acl_subscribe_cb(), ubus_event_handler::cb, ctx, and ubus_register_event_handler().
ubus_register_event_handler()
int ubus_register_event_handler (struct ubus_context * ctx, struct ubus_event_handler * ev, const char * pattern)
Definition at line 225 of file libubus.c.
{
    struct ubus_object *obj = &ev->obj;
    struct blob_buf b2 = {};
    int ret;
    if (!obj->id) {
        obj->methods = &event_method;
        obj->n_methods = 1;
        if (!!obj->name ^ !!obj->type)
            return UBUS_STATUS_INVALID_ARGUMENT;
        ret = ubus_add_object(ctx, obj);
        if (ret)
            return ret;
    }
    /* use a second buffer, ubus_invoke() overwrites the primary one */
    blob_buf_init(&b2, 0);
    blobmsg_add_u32(&b2, "object", obj->id);
    if (pattern)
        blobmsg_add_string(&b2, "pattern", pattern);
    ret = ubus_invoke(ctx, UBUS_SYSTEM_OBJECT_EVENT, "register", b2.head,
              NULL, NULL, 0);
    blob_buf_free(&b2);
    return ret;
}
References blob_buf_free(), blob_buf_init(), blobmsg_add_string(), blobmsg_add_u32(), ctx, event_method, blob_buf::head, ubus_object::id, ubus_object::methods, ubus_object::n_methods, ubus_object::name, ubus_event_handler::obj, ubus_object::type, ubus_add_object(), ubus_invoke(), UBUS_STATUS_INVALID_ARGUMENT, and UBUS_SYSTEM_OBJECT_EVENT.
Referenced by extdev_ext_ubus_obj_wait(), ubus_cli_listen(), ubus_cli_wait_for(), ubus_lua_listen(), ubus_refresh_auto_subscribe(), ubus_register_acl(), ubus_register_subscriber(), and watch_ubus().
ubus_register_subscriber()
int ubus_register_subscriber (struct ubus_context * ctx, struct ubus_subscriber * obj)
Definition at line 77 of file libubus-sub.c.
{
    struct ubus_object *obj = &s->obj;
    int ret;
    INIT_LIST_HEAD(&s->list);
    obj->methods = &watch_method;
    obj->n_methods = 1;
    ret = ubus_add_object(ctx, obj);
    if (ret)
        return ret;
    if (s->new_obj_cb) {
        struct ubus_event_handler *ev = &ctx->auto_subscribe_event_handler;
        list_add(&s->list, &ctx->auto_subscribers);
        ev->cb = ubus_auto_sub_event_handler_cb;
        if (!ev->obj.id)
            ubus_register_event_handler(ctx, ev, "ubus.object.add");
        ubus_lookup(ctx, NULL, ubus_auto_sub_lookup, s);
    }
    return 0;
}
References ubus_context::auto_subscribe_event_handler, ubus_context::auto_subscribers, ubus_event_handler::cb, ctx, ubus_object::id, INIT_LIST_HEAD(), ubus_subscriber::list, list_add(), ubus_object::methods, ubus_object::n_methods, ubus_subscriber::new_obj_cb, ubus_event_handler::obj, ubus_subscriber::obj, ubus_add_object(), ubus_auto_sub_event_handler_cb(), ubus_auto_sub_lookup(), ubus_lookup(), ubus_register_event_handler(), and watch_method.
Referenced by extdev_add_devtype(), server_main(), ubus_cli_subscribe(), ubus_connect_handler(), ubus_lua_do_subscribe(), watch_ubus(), and watch_ubus_service().
ubus_remove_object()
int ubus_remove_object (struct ubus_context * ctx, struct ubus_object * obj)
Definition at line 256 of file libubus-obj.c.
{
    struct ubus_request req;
    int ret;
    blob_buf_init(&b, 0);
    blob_put_int32(&b, UBUS_ATTR_OBJID, obj->id);
    if (ubus_start_request(ctx, &req, b.head, UBUS_MSG_REMOVE_OBJECT, 0) < 0)
        return UBUS_STATUS_INVALID_ARGUMENT;
    req.raw_data_cb = ubus_remove_object_cb;
    req.priv = obj;
    ret = ubus_complete_request(ctx, &req, 0);
    if (ret)
        return ret;
    if (obj->id)
        return UBUS_STATUS_NO_DATA;
    return 0;
}
References b, blob_buf_init(), blob_put_int32, ctx, blob_buf::head, ubus_object::id, ubus_request::priv, ubus_request::raw_data_cb, UBUS_ATTR_OBJID, ubus_complete_request(), UBUS_MSG_REMOVE_OBJECT, ubus_remove_object_cb(), ubus_start_request(), UBUS_STATUS_INVALID_ARGUMENT, and UBUS_STATUS_NO_DATA.
Referenced by netifd_ubus_remove_interface(), remove_subsystem(), ubus_unregister_event_handler(), ubus_unregister_subscriber(), and ustp_ubus_exit().
ubus_request_get_caller_fd()
static int ubus_request_get_caller_fd (struct ubus_request_data * req) inline static
Definition at line 391 of file libubus.h.
{
    int fd = req->req_fd;
    req->req_fd = -1;
    return fd;
}
References ubus_request_data::req_fd.
Referenced by container_handle_console(), and netifd_netns_updown().
ubus_request_set_fd()
static void ubus_request_set_fd (struct ubus_context * ctx, struct ubus_request_data * req, int fd) inline static
Definition at line 384 of file libubus.h.
{
    (void) ctx;
    req->fd = fd;
}
References ctx, and ubus_request_data::fd.
Referenced by test_hello_reply().
ubus_send_event()
int ubus_send_event (struct ubus_context * ctx, const char * id, struct blob_attr * data)
Definition at line 258 of file libubus.c.
{
    struct ubus_request req;
    void *s;
    blob_buf_init(&b, 0);
    blob_put_int32(&b, UBUS_ATTR_OBJID, UBUS_SYSTEM_OBJECT_EVENT);
    blob_put_string(&b, UBUS_ATTR_METHOD, "send");
    s = blob_nest_start(&b, UBUS_ATTR_DATA);
    blobmsg_add_string(&b, "id", id);
    blobmsg_add_field(&b, BLOBMSG_TYPE_TABLE, "data", blob_data(data), blob_len(data));
    blob_nest_end(&b, s);
    if (ubus_start_request(ctx, &req, b.head, UBUS_MSG_INVOKE, UBUS_SYSTEM_OBJECT_EVENT) < 0)
        return UBUS_STATUS_INVALID_ARGUMENT;
    return ubus_complete_request(ctx, &req, 0);
}
References b, blob_buf_init(), blob_data(), blob_len(), blob_nest_end(), blob_nest_start(), blob_put_int32, blob_put_string(), blobmsg_add_field(), blobmsg_add_string(), BLOBMSG_TYPE_TABLE, ctx, blob_buf::head, UBUS_ATTR_DATA, UBUS_ATTR_METHOD, UBUS_ATTR_OBJID, ubus_complete_request(), UBUS_MSG_INVOKE, ubus_start_request(), UBUS_STATUS_INVALID_ARGUMENT, and UBUS_SYSTEM_OBJECT_EVENT.
Referenced by netifd_ubus_interface_event(), ubus_cli_send(), and ubus_lua_send().
ubus_send_reply()
int ubus_send_reply (struct ubus_context * ctx, struct ubus_request_data * req, struct blob_attr * msg)
Definition at line 205 of file libubus-req.c.
{
    int ret;
    blob_buf_init(&b, 0);
    blob_put_int32(&b, UBUS_ATTR_OBJID, req->object);
    ubus_put_data(&b, msg);
    ret = ubus_send_msg(ctx, req->seq, b.head, UBUS_MSG_DATA, req->peer, -1);
    if (ret < 0)
        return UBUS_STATUS_NO_DATA;
    return 0;
}
References b, blob_buf_init(), blob_put_int32, ctx, blob_buf::head, ubus_request_data::object, ubus_request_data::peer, ubus_request_data::seq, UBUS_ATTR_OBJID, UBUS_MSG_DATA, ubus_put_data(), ubus_send_msg(), and UBUS_STATUS_NO_DATA.
Referenced by container_handle_features(), handle_state(), netifd_add_host_route(), netifd_dev_status(), netifd_get_proto_handlers(), netifd_handle_dump(), netifd_handle_iface_prepare(), netifd_handle_status(), netifd_handle_wdev_get_validate(), netifd_handle_wdev_status(), rc_list_readdir(), rpc_exec_reply(), rpc_file_exec_reply(), rpc_file_list(), rpc_file_md5(), rpc_file_read(), rpc_file_stat(), rpc_handle_access(), rpc_handle_get(), rpc_iwinfo_assoclist(), rpc_iwinfo_countrylist(), rpc_iwinfo_devices(), rpc_iwinfo_freqlist(), rpc_iwinfo_info(), rpc_iwinfo_phyname(), rpc_iwinfo_scan(), rpc_iwinfo_survey(), rpc_iwinfo_txpowerlist(), rpc_session_dump(), rpc_sys_packagelist(), rpc_uci_add(), rpc_uci_changes(), rpc_uci_configs(), rpc_uci_getcommon(), rpc_ucode_request_finish(), rpc_ucode_script_call(), service_get_data(), service_handle_list(), service_handle_validate(), service_handle_watchdog(), system_board(), system_info(), sysupgrade_error(), test_count(), test_hello_reply(), ubus_lua_reply(), validate_firmware_image(), and watchdog_set().
ubus_shutdown()
void ubus_shutdown (struct ubus_context * ctx)
Definition at line 367 of file libubus.c.
{
    blob_buf_free(&b);
    if (!ctx)
        return;
    uloop_fd_delete(&ctx->sock);
    close(ctx->sock.fd);
    uloop_timeout_cancel(&ctx->pending_timer);
    free(ctx->msgbuf.data);
}
References b, blob_buf_free(), ctx, ubus_msghdr_buf::data, uloop_fd::fd, ubus_context::msgbuf, ubus_context::pending_timer, ubus_context::sock, uloop_fd_delete(), and uloop_timeout_cancel().
Referenced by ubus_auto_shutdown(), and ubus_free().
ubus_strerror()
const char * ubus_strerror (int error)
Definition at line 59 of file libubus.c.
{
    static char err[32];
    if (error < 0 || error >= __UBUS_STATUS_LAST)
        goto out;
    if (!__ubus_strerror[error])
        goto out;
    return __ubus_strerror[error];
out:
    sprintf(err, "Unknown error: %d", error);
    return err;
}
References __UBUS_STATUS_LAST, __ubus_strerror, and err.
Referenced by __bridge_config_init(), __do_bridge_reload(), client_main(), extdev_bridge_member_cb(), extdev_invocation_error(), extdev_lookup_id(), main(), netifd_add_object(), procd_bcast_event(), rpc_ucode_script_register(), server_main(), test_client_notify_cb(), test_watch(), ubus_cli_error(), ubus_cli_listen(), ubus_cli_subscribe(), and ubus_init_system().
ubus_subscribe()
int ubus_subscribe (struct ubus_context * ctx, struct ubus_subscriber * obj, uint32_t id)
Definition at line 118 of file libubus-sub.c.
{
    return __ubus_subscribe_request(ctx, &obj->obj, id, UBUS_MSG_SUBSCRIBE);
}
References __ubus_subscribe_request(), ctx, ubus_subscriber::obj, and UBUS_MSG_SUBSCRIBE.
Referenced by extdev_subscribe(), netifd_sub_cb(), test_watch(), ubus_auto_sub_event_handler_cb(), ubus_auto_sub_lookup(), ubus_auto_sub_lookup(), ubus_cli_subscribe(), ubus_lua_do_subscribe(), ubusd_handle_add_watch(), watch_subscribe_cb(), and watch_ubus_service().
ubus_unregister_event_handler()
static int ubus_unregister_event_handler (struct ubus_context * ctx, struct ubus_event_handler * ev) inline static
Definition at line 423 of file libubus.h.
{
    return ubus_remove_object(ctx, &ev->obj);
}
References ctx, ubus_event_handler::obj, and ubus_remove_object().
ubus_unregister_subscriber()
static int ubus_unregister_subscriber (struct ubus_context * ctx, struct ubus_subscriber * obj) inline static
Definition at line 309 of file libubus.h.
{
    if (!list_empty(&obj->list))
        list_del_init(&obj->list);
    return ubus_remove_object(ctx, &obj->obj);
}
References ctx, ubus_subscriber::list, list_del_init(), list_empty(), ubus_subscriber::obj, and ubus_remove_object().
Referenced by ustp_ubus_exit().
ubus_unsubscribe()
int ubus_unsubscribe (struct ubus_context * ctx, struct ubus_subscriber * obj, uint32_t id)
Definition at line 123 of file libubus-sub.c.
{
    return __ubus_subscribe_request(ctx, &obj->obj, id, UBUS_MSG_UNSUBSCRIBE);
}
References __ubus_subscribe_request(), ctx, ubus_subscriber::obj, and UBUS_MSG_UNSUBSCRIBE.
Referenced by ubus_notify_unsubscribe(), and ubusd_handle_remove_watch().
Variable Documentation
acl_objects
struct avl_tree acl_objects extern
Referenced by acl_add(), and acl_recv_cb().