zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/plug/hotplug.h File Reference
hotplug.h File Reference
#include <libubox/uloop.h>
Functions
void hotplug (char *rules)
int hotplug_run (char *rules)
void hotplug_shutdown (void)
void hotplug_last_event (uloop_timeout_handler handler)
void procd_coldplug (void)
Function Documentation
hotplug()
void hotplug (char * rules)
Definition at line 608 of file hotplug.c.
{
    struct sockaddr_nl nls = {};
    int nlbufsize = 512 * 1024;
    rule_file = strdup(rules);
    nls.nl_family = AF_NETLINK;
    nls.nl_pid = 0;
    nls.nl_groups = -1;
    if ((hotplug_fd.fd = socket(PF_NETLINK, SOCK_DGRAM | SOCK_CLOEXEC, NETLINK_KOBJECT_UEVENT)) == -1) {
        ERROR("Failed to open hotplug socket: %m\n");
        exit(1);
    }
    if (bind(hotplug_fd.fd, (void *)&nls, sizeof(struct sockaddr_nl))) {
        ERROR("Failed to bind hotplug socket: %m\n");
        exit(1);
    }
    if (setsockopt(hotplug_fd.fd, SOL_SOCKET, SO_RCVBUFFORCE, &nlbufsize, sizeof(nlbufsize)))
        ERROR("Failed to resize receive buffer: %m\n");
    json_script_init(&jctx);
    queue_proc.cb = queue_proc_cb;
    uloop_fd_add(&hotplug_fd, ULOOP_READ);
}
References uloop_process::cb, ERROR, uloop_fd::fd, hotplug_fd, jctx, json_script_init(), queue_proc, queue_proc_cb(), rule_file, uloop_fd_add(), and ULOOP_READ.
Referenced by bonding_create_port(), bridge_alloc_member(), bridge_create_member(), bridge_insert_member(), hotplug_run(), and state_enter().
hotplug_last_event()
void hotplug_last_event (uloop_timeout_handler handler)
Definition at line 599 of file hotplug.c.
{
    last_event.cb = handler;
    if (handler)
        uloop_timeout_set(&last_event, HOTPLUG_WAIT);
    else
        uloop_timeout_cancel(&last_event);
}
References uloop_timeout::cb, HOTPLUG_WAIT, last_event, uloop_timeout_cancel(), and uloop_timeout_set().
Referenced by coldplug_complete(), and udevtrigger_complete().
hotplug_run()
int hotplug_run (char * rules)
Definition at line 635 of file hotplug.c.
{
    uloop_init();
    hotplug(rules);
    uloop_run();
    return 0;
}
References hotplug(), uloop_init(), and uloop_run().
Referenced by main().
hotplug_shutdown()
void hotplug_shutdown (void)
Definition at line 644 of file hotplug.c.
{
    uloop_fd_delete(&hotplug_fd);
    close(hotplug_fd.fd);
}
References uloop_fd::fd, hotplug_fd, and uloop_fd_delete().
procd_coldplug()
void procd_coldplug (void)
Definition at line 43 of file coldplug.c.
{
    char *argv[] = { "udevtrigger", NULL };
    unsigned int oldumask = umask(0);
    if (!is_container()) {
        umount2("/dev/pts", MNT_DETACH);
        umount2("/dev/", MNT_DETACH);
        mount("tmpfs", "/dev", "tmpfs", MS_NOATIME | MS_NOEXEC | MS_NOSUID, "mode=0755,size=512K");
        mkdir("/dev/pts", 0755);
        mount("devpts", "/dev/pts", "devpts", MS_NOATIME | MS_NOEXEC | MS_NOSUID, 0);
    }
    ignore(symlink("/tmp/shm", "/dev/shm"));
    umask(oldumask);
    udevtrigger.cb = udevtrigger_complete;
    udevtrigger.pid = fork();
    if (!udevtrigger.pid) {
        execvp(argv[0], argv);
        ERROR("Failed to start coldplug: %m\n");
        exit(EXIT_FAILURE);
    }
    if (udevtrigger.pid <= 0) {
        ERROR("Failed to start new coldplug instance: %m\n");
        return;
    }
    uloop_process_add(&udevtrigger);
    P_DEBUG(4, "Launched coldplug instance, pid=%d\n", (int) udevtrigger.pid);
}
References uloop_process::cb, ERROR, ignore, is_container(), P_DEBUG, uloop_process::pid, udevtrigger, udevtrigger_complete(), and uloop_process_add().
Referenced by state_enter().