zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/ustp/libnetlink.h File Reference
libnetlink.h File Reference
#include <stdio.h>
#include <asm/types.h>
#include <linux/netlink.h>
#include <linux/rtnetlink.h>
#include <sys/types.h>
Classes
struct rtnl_handle
Macros
#define RTA_TAIL(rta)
#define parse_rtattr_nested(tb, max, rta)
#define NLMSG_TAIL(nmsg)
Typedefs
typedef int(* rtnl_filter_t) (const struct sockaddr_nl *, struct nlmsghdr *n, void *)
Functions
int rtnl_open (struct rtnl_handle *rth, unsigned subscriptions)
int rtnl_open_byproto (struct rtnl_handle *rth, unsigned subscriptions, int protocol)
void rtnl_close (struct rtnl_handle *rth)
int rtnl_wilddump_request (struct rtnl_handle *rth, int fam, int type)
int rtnl_dump_request (struct rtnl_handle *rth, int type, void *req, int len)
int rtnl_dump_filter (struct rtnl_handle *rth, rtnl_filter_t filter, void *arg1, rtnl_filter_t junk, void *arg2)
int rtnl_talk (struct rtnl_handle *rtnl, struct nlmsghdr *n, pid_t peer, unsigned groups, struct nlmsghdr *answer, rtnl_filter_t junk, void *jarg)
int rtnl_send (struct rtnl_handle *rth, const char *buf, int)
int addattr8 (struct nlmsghdr *n, int maxlen, int type, __u8 data)
int addattr32 (struct nlmsghdr *n, int maxlen, int type, __u32 data)
int addattr_l (struct nlmsghdr *n, int maxlen, int type, const void *data, int alen)
int addraw_l (struct nlmsghdr *n, int maxlen, const void *data, int len)
int rta_addattr8 (struct rtattr *rta, int maxlen, int type, __u8 data)
int rta_addattr16 (struct rtattr *rta, int maxlen, int type, __u16 data)
int rta_addattr32 (struct rtattr *rta, int maxlen, int type, __u32 data)
int rta_addattr64 (struct rtattr *rta, int maxlen, int type, __u64 data)
int rta_addattr_l (struct rtattr *rta, int maxlen, int type, const void *data, int alen)
int parse_rtattr (struct rtattr *tb[], int max, struct rtattr *rta, int len)
int parse_rtattr_byindex (struct rtattr *tb[], int max, struct rtattr *rta, int len)
struct rtattr * rta_nest (struct rtattr *rta, int maxlen, int type)
int rta_nest_end (struct rtattr *rta, struct rtattr *nest)
int rtnl_listen (struct rtnl_handle *, rtnl_filter_t handler, void *jarg)
int rtnl_from_file (FILE *, rtnl_filter_t handler, void *jarg)
Class Documentation
rtnl_handle
struct rtnl_handle
Definition at line 10 of file libnetlink.h.
Class Members
__u32 dump
int fd
struct sockaddr_nl local
struct sockaddr_nl peer
__u32 seq
Macro Definition Documentation
NLMSG_TAIL
#define NLMSG_TAIL (nmsg)
Value:
    ((struct rtattr *) (((void *) (nmsg)) + NLMSG_ALIGN((nmsg)->nlmsg_len)))
Definition at line 64 of file libnetlink.h.
#define NLMSG_TAIL(nmsg) \
    ((struct rtattr *) (((void *) (nmsg)) + NLMSG_ALIGN((nmsg)->nlmsg_len)))
Referenced by addattr32(), addattr8(), addattr_l(), and addraw_l().
parse_rtattr_nested
#define parse_rtattr_nested (tb, max, rta)
Value:
    (parse_rtattr((tb), (max), RTA_DATA(rta), RTA_PAYLOAD(rta)))
Definition at line 58 of file libnetlink.h.
#define parse_rtattr_nested(tb, max, rta) \
    (parse_rtattr((tb), (max), RTA_DATA(rta), RTA_PAYLOAD(rta)))
RTA_TAIL
#define RTA_TAIL (rta)
Value:
        ((struct rtattr *) (((void *) (rta)) + \
                    RTA_ALIGN((rta)->rta_len)))
Definition at line 54 of file libnetlink.h.
#define RTA_TAIL(rta) \
        ((struct rtattr *) (((void *) (rta)) + \
                    RTA_ALIGN((rta)->rta_len)))
Referenced by rta_nest(), and rta_nest_end().
Typedef Documentation
rtnl_filter_t
typedef int(* rtnl_filter_t) (const struct sockaddr_nl *, struct nlmsghdr *n, void *)
Definition at line 26 of file libnetlink.h.
Function Documentation
addattr32()
int addattr32 (struct nlmsghdr * n, int maxlen, int type, __u32 data)
Definition at line 508 of file libnetlink.c.
{
    int len = RTA_LENGTH(4);
    struct rtattr *rta;
    if (NLMSG_ALIGN(n->nlmsg_len) + len > maxlen) {
        ERROR(
            "addattr32: Error! max allowed bound %d exceeded\n",
            maxlen);
        return -1;
    }
    rta = NLMSG_TAIL(n);
    rta->rta_type = type;
    rta->rta_len = len;
    memcpy(RTA_DATA(rta), &data, 4);
    n->nlmsg_len = NLMSG_ALIGN(n->nlmsg_len) + len;
    return 0;
}
References ERROR, NLMSG_TAIL, and type.
addattr8()
int addattr8 (struct nlmsghdr * n, int maxlen, int type, __u8 data)
Definition at line 526 of file libnetlink.c.
{
    int len = RTA_LENGTH(1);
    struct rtattr *rta;
    if (NLMSG_ALIGN(n->nlmsg_len) + len > maxlen) {
        ERROR(
            "addattr8: Error! max allowed bound %d exceeded\n",
            maxlen);
        return -1;
    }
    rta = NLMSG_TAIL(n);
    rta->rta_type = type;
    rta->rta_len = len;
    memcpy(RTA_DATA(rta), &data, 1);
    n->nlmsg_len = NLMSG_ALIGN(n->nlmsg_len) + len;
    return 0;
}
References ERROR, NLMSG_TAIL, and type.
Referenced by br_set_state().
addattr_l()
int addattr_l (struct nlmsghdr * n, int maxlen, int type, const void * data, int alen)
Definition at line 544 of file libnetlink.c.
{
    int len = RTA_LENGTH(alen);
    struct rtattr *rta;
    if (NLMSG_ALIGN(n->nlmsg_len) + RTA_ALIGN(len) > maxlen) {
        ERROR(
            "addattr_l ERROR: message exceeded bound of %d\n",
            maxlen);
        return -1;
    }
    rta = NLMSG_TAIL(n);
    rta->rta_type = type;
    rta->rta_len = len;
    memcpy(RTA_DATA(rta), data, alen);
    n->nlmsg_len = NLMSG_ALIGN(n->nlmsg_len) + RTA_ALIGN(len);
    return 0;
}
References ERROR, NLMSG_TAIL, and type.
addraw_l()
int addraw_l (struct nlmsghdr * n, int maxlen, const void * data, int len)
Definition at line 564 of file libnetlink.c.
{
    if (NLMSG_ALIGN(n->nlmsg_len) + NLMSG_ALIGN(len) > maxlen) {
        ERROR(
            "addraw_l ERROR: message exceeded bound of %d\n",
            maxlen);
        return -1;
    }
    memcpy(NLMSG_TAIL(n), data, len);
    memset((void *)NLMSG_TAIL(n) + len, 0, NLMSG_ALIGN(len) - len);
    n->nlmsg_len = NLMSG_ALIGN(n->nlmsg_len) + NLMSG_ALIGN(len);
    return 0;
}
References ERROR, and NLMSG_TAIL.
parse_rtattr()
int parse_rtattr (struct rtattr * tb[], int max, struct rtattr * rta, int len)
Definition at line 650 of file libnetlink.c.
{
    memset(tb, 0, sizeof(struct rtattr *) * (max + 1));
    while (RTA_OK(rta, len)) {
        if (rta->rta_type <= max)
            tb[rta->rta_type] = rta;
        rta = RTA_NEXT(rta, len);
    }
    if (len)
        ERROR("!!!Deficit %d, rta_len=%d\n", len,
            rta->rta_len);
    return 0;
}
References ERROR.
Referenced by dump_msg().
parse_rtattr_byindex()
int parse_rtattr_byindex (struct rtattr * tb[], int max, struct rtattr * rta, int len)
Definition at line 664 of file libnetlink.c.
{
    int i = 0;
    memset(tb, 0, sizeof(struct rtattr *) * max);
    while (RTA_OK(rta, len)) {
        if (rta->rta_type <= max && i < max)
            tb[i++] = rta;
        rta = RTA_NEXT(rta, len);
    }
    if (len)
        ERROR("!!!Deficit %d, rta_len=%d\n", len,
            rta->rta_len);
    return i;
}
References ERROR.
rta_addattr16()
int rta_addattr16 (struct rtattr * rta, int maxlen, int type, __u16 data)
Definition at line 623 of file libnetlink.c.
{
    return rta_addattr_l(rta, maxlen, type, &data, sizeof(__u16));
}
References rta_addattr_l(), and type.
rta_addattr32()
int rta_addattr32 (struct rtattr * rta, int maxlen, int type, __u32 data)
Definition at line 579 of file libnetlink.c.
{
    int len = RTA_LENGTH(4);
    struct rtattr *subrta;
    if (RTA_ALIGN(rta->rta_len) + len > maxlen) {
        ERROR(
            "rta_addattr32: Error! max allowed bound %d exceeded\n",
            maxlen);
        return -1;
    }
    subrta = (struct rtattr *)(((char *)rta) + RTA_ALIGN(rta->rta_len));
    subrta->rta_type = type;
    subrta->rta_len = len;
    memcpy(RTA_DATA(subrta), &data, 4);
    rta->rta_len = NLMSG_ALIGN(rta->rta_len) + len;
    return 0;
}
References ERROR, and type.
rta_addattr64()
int rta_addattr64 (struct rtattr * rta, int maxlen, int type, __u64 data)
Definition at line 628 of file libnetlink.c.
{
    return rta_addattr_l(rta, maxlen, type, &data, sizeof(__u64));
}
References rta_addattr_l(), and type.
rta_addattr8()
int rta_addattr8 (struct rtattr * rta, int maxlen, int type, __u8 data)
Definition at line 618 of file libnetlink.c.
{
    return rta_addattr_l(rta, maxlen, type, &data, sizeof(__u8));
}
References rta_addattr_l(), and type.
rta_addattr_l()
int rta_addattr_l (struct rtattr * rta, int maxlen, int type, const void * data, int alen)
Definition at line 598 of file libnetlink.c.
{
    struct rtattr *subrta;
    int len = RTA_LENGTH(alen);
    if (RTA_ALIGN(rta->rta_len) + RTA_ALIGN(len) > maxlen) {
        ERROR(
            "rta_addattr_l: Error! max allowed bound %d exceeded\n",
            maxlen);
        return -1;
    }
    subrta = (struct rtattr *)(((char *)rta) + RTA_ALIGN(rta->rta_len));
    subrta->rta_type = type;
    subrta->rta_len = len;
    memcpy(RTA_DATA(subrta), data, alen);
    rta->rta_len = NLMSG_ALIGN(rta->rta_len) + RTA_ALIGN(len);
    return 0;
}
References ERROR, and type.
Referenced by rta_addattr16(), rta_addattr64(), rta_addattr8(), and rta_nest().
rta_nest()
struct rtattr * rta_nest (struct rtattr * rta, int maxlen, int type)
Definition at line 633 of file libnetlink.c.
{
    struct rtattr *nest = RTA_TAIL(rta);
    rta_addattr_l(rta, maxlen, type, NULL, 0);
    nest->rta_type |= NLA_F_NESTED;
    return nest;
}
References rta_addattr_l(), RTA_TAIL, and type.
rta_nest_end()
int rta_nest_end (struct rtattr * rta, struct rtattr * nest)
Definition at line 643 of file libnetlink.c.
{
    nest->rta_len = (void *)RTA_TAIL(rta) - (void *)nest;
    return rta->rta_len;
}
References RTA_TAIL.
rtnl_close()
void rtnl_close (struct rtnl_handle * rth)
Definition at line 40 of file libnetlink.c.
{
    close(rth->fd);
}
References rtnl_handle::fd, and rth.
rtnl_dump_filter()
int rtnl_dump_filter (struct rtnl_handle * rth, rtnl_filter_t filter, void * arg1, rtnl_filter_t junk, void * arg2)
Definition at line 170 of file libnetlink.c.
{
    struct sockaddr_nl nladdr;
    struct iovec iov;
    struct msghdr msg = {
        .msg_name = &nladdr,
        .msg_namelen = sizeof(nladdr),
        .msg_iov = &iov,
        .msg_iovlen = 1,
    };
    char buf[16384];
    iov.iov_base = buf;
    while (1) {
        int status;
        struct nlmsghdr *h;
        iov.iov_len = sizeof(buf);
        status = recvmsg(rth->fd, &msg, 0);
        if (status < 0) {
            if (errno == EINTR)
                continue;
            ERROR("OVERRUN");
            continue;
        }
        if (status == 0) {
            ERROR("EOF on netlink\n");
            return -1;
        }
        h = (struct nlmsghdr *)buf;
        while (NLMSG_OK(h, status)) {
            int err;
            if (nladdr.nl_pid != 0 ||
                h->nlmsg_pid != rth->local.nl_pid ||
                h->nlmsg_seq != rth->dump) {
                if (junk) {
                    err = junk(&nladdr, h, arg2);
                    if (err < 0)
                        return err;
                }
                goto skip_it;
            }
            if (h->nlmsg_type == NLMSG_DONE)
                return 0;
            if (h->nlmsg_type == NLMSG_ERROR) {
                struct nlmsgerr *err =
                    (struct nlmsgerr *)NLMSG_DATA(h);
                if (h->nlmsg_len <
                    NLMSG_LENGTH(sizeof(struct nlmsgerr))) {
                    ERROR("ERROR truncated\n");
                } else {
                    errno = -err->error;
                    LOG("RTNETLINK answers");
                }
                return -1;
            }
            err = filter(&nladdr, h, arg1);
            if (err < 0)
                return err;
              skip_it:
            h = NLMSG_NEXT(h, status);
        }
        if (msg.msg_flags & MSG_TRUNC) {
            ERROR("Message truncated\n");
            continue;
        }
        if (status) {
            ERROR("!!!Remnant of size %d\n", status);
            return -1;
        }
    }
}
References buf, rtnl_handle::dump, err, ERROR, rtnl_handle::fd, rtnl_handle::local, LOG, and rth.
Referenced by init_bridge_ops().
rtnl_dump_request()
int rtnl_dump_request (struct rtnl_handle * rth, int type, void * req, int len)
Definition at line 142 of file libnetlink.c.
{
    struct nlmsghdr nlh;
    struct sockaddr_nl nladdr;
    struct iovec iov[2] = {
        {.iov_base = &nlh,.iov_len = sizeof(nlh)}
        ,
        {.iov_base = req,.iov_len = len}
    };
    struct msghdr msg = {
        .msg_name = &nladdr,
        .msg_namelen = sizeof(nladdr),
        .msg_iov = iov,
        .msg_iovlen = 2,
    };
    memset(&nladdr, 0, sizeof(nladdr));
    nladdr.nl_family = AF_NETLINK;
    nlh.nlmsg_len = NLMSG_LENGTH(len);
    nlh.nlmsg_type = type;
    nlh.nlmsg_flags = NLM_F_ROOT | NLM_F_MATCH | NLM_F_REQUEST;
    nlh.nlmsg_pid = 0;
    nlh.nlmsg_seq = rth->dump = ++rth->seq;
    return sendmsg(rth->fd, &msg, 0);
}
References rtnl_handle::dump, rtnl_handle::fd, rth, rtnl_handle::seq, and type.
rtnl_from_file()
int rtnl_from_file (FILE * rtnl, rtnl_filter_t handler, void * jarg)
Definition at line 455 of file libnetlink.c.
{
    int status;
    struct sockaddr_nl nladdr;
    char buf[8192];
    struct nlmsghdr *h = (void *)buf;
    memset(&nladdr, 0, sizeof(nladdr));
    nladdr.nl_family = AF_NETLINK;
    nladdr.nl_pid = 0;
    nladdr.nl_groups = 0;
    while (1) {
        int err, len;
        int l;
        status = fread(&buf, 1, sizeof(*h), rtnl);
        if (status < 0) {
            if (errno == EINTR)
                continue;
            ERROR("rtnl_from_file: fread");
            return -1;
        }
        if (status == 0)
            return 0;
        len = h->nlmsg_len;
        l = len - sizeof(*h);
        if (l < 0 || len > sizeof(buf)) {
            ERROR("!!!malformed message: len=%d @%lu\n",
                len, ftell(rtnl));
            return -1;
        }
        status = fread(NLMSG_DATA(h), 1, NLMSG_ALIGN(l), rtnl);
        if (status < 0) {
            ERROR("rtnl_from_file: fread");
            return -1;
        }
        if (status < l) {
            ERROR("rtnl-from_file: truncated message\n");
            return -1;
        }
        err = handler(&nladdr, h, jarg);
        if (err < 0)
            return err;
    }
}
References buf, err, and ERROR.
rtnl_listen()
int rtnl_listen (struct rtnl_handle * rtnl, rtnl_filter_t handler, void * jarg)
Definition at line 379 of file libnetlink.c.
{
    int status;
    struct nlmsghdr *h;
    struct sockaddr_nl nladdr;
    struct iovec iov;
    struct msghdr msg = {
        .msg_name = &nladdr,
        .msg_namelen = sizeof(nladdr),
        .msg_iov = &iov,
        .msg_iovlen = 1,
    };
    char buf[8192];
    memset(&nladdr, 0, sizeof(nladdr));
    nladdr.nl_family = AF_NETLINK;
    nladdr.nl_pid = 0;
    nladdr.nl_groups = 0;
    iov.iov_base = buf;
    while (1) {
        iov.iov_len = sizeof(buf);
        status = recvmsg(rtnl->fd, &msg, 0);
        if (status < 0) {
            if (errno == EINTR)
                continue;
            if (errno == EAGAIN)
                return 0;
            ERROR("OVERRUN: recvmsg(): error %d : %s\n", errno, strerror(errno));
            return -1;
        }
        if (status == 0) {
            ERROR("EOF on netlink\n");
            return -1;
        }
        if (msg.msg_namelen != sizeof(nladdr)) {
            ERROR("Sender address length == %d\n",
                msg.msg_namelen);
            continue;
        }
        for (h = (struct nlmsghdr *)buf; status >= sizeof(*h);) {
            int err;
            int len = h->nlmsg_len;
            int l = len - sizeof(*h);
            if (l < 0 || len > status) {
                if (msg.msg_flags & MSG_TRUNC) {
                    ERROR("Truncated message\n");
                    continue;
                }
                ERROR(
                    "!!!malformed message: len=%d\n", len);
                continue;
            }
            err = handler(&nladdr, h, jarg);
            if (err < 0) {
                ERROR("Handler returned %d\n", err);
                continue;
            }
            status -= NLMSG_ALIGN(len);
            h = (struct nlmsghdr *)((char *)h + NLMSG_ALIGN(len));
        }
        if (msg.msg_flags & MSG_TRUNC) {
            ERROR("Message truncated\n");
            continue;
        }
        if (status) {
            ERROR("!!!Remnant of size %d\n", status);
            continue;
        }
    }
}
References buf, err, ERROR, and rtnl_handle::fd.
Referenced by bridge_event_handler().
rtnl_open()
int rtnl_open (struct rtnl_handle * rth, unsigned subscriptions)
Definition at line 103 of file libnetlink.c.
{
    return rtnl_open_byproto(rth, subscriptions, NETLINK_ROUTE);
}
References rth, and rtnl_open_byproto().
Referenced by init_bridge_ops().
rtnl_open_byproto()
int rtnl_open_byproto (struct rtnl_handle * rth, unsigned subscriptions, int protocol)
Definition at line 45 of file libnetlink.c.
{
    socklen_t addr_len;
    int sndbuf = RTNL_SND_BUFSIZE;
    int rcvbuf = RTNL_RCV_BUFSIZE;
    int yes = 1;
    memset(rth, 0, sizeof(*rth));
    rth->fd = socket(AF_NETLINK, SOCK_RAW, protocol);
    if (rth->fd < 0) {
        ERROR("Cannot open netlink socket");
        return -1;
    }
    if (setsockopt(rth->fd, SOL_SOCKET, SO_SNDBUF, &sndbuf, sizeof(sndbuf))
        < 0) {
        ERROR("SO_SNDBUF");
        return -1;
    }
    if (setsockopt(rth->fd, SOL_SOCKET, SO_RCVBUF, &rcvbuf, sizeof(rcvbuf))
        < 0) {
        ERROR("SO_RCVBUF");
        return -1;
    }
    if (setsockopt(rth->fd, SOL_NETLINK, NETLINK_NO_ENOBUFS, &yes, sizeof(yes)) < 0)
        ERROR("NETLINK_NO_EBUFS");
    memset(&rth->local, 0, sizeof(rth->local));
    rth->local.nl_family = AF_NETLINK;
    rth->local.nl_groups = subscriptions;
    if (bind(rth->fd, (struct sockaddr *)&rth->local, sizeof(rth->local)) <
        0) {
        ERROR("Cannot bind netlink socket");
        return -1;
    }
    addr_len = sizeof(rth->local);
    if (getsockname(rth->fd, (struct sockaddr *)&rth->local, &addr_len) < 0) {
        ERROR("Cannot getsockname");
        return -1;
    }
    if (addr_len != sizeof(rth->local)) {
        ERROR("Wrong address length %d\n", addr_len);
        return -1;
    }
    if (rth->local.nl_family != AF_NETLINK) {
        ERROR("Wrong address family %d\n",
            rth->local.nl_family);
        return -1;
    }
    rth->seq = time(NULL);
    return 0;
}
References ERROR, rtnl_handle::fd, rtnl_handle::local, rth, RTNL_RCV_BUFSIZE, RTNL_SND_BUFSIZE, and rtnl_handle::seq.
Referenced by rtnl_open().
rtnl_send()
int rtnl_send (struct rtnl_handle * rth, const char * buf, int len)
Definition at line 131 of file libnetlink.c.
{
    struct sockaddr_nl nladdr;
    memset(&nladdr, 0, sizeof(nladdr));
    nladdr.nl_family = AF_NETLINK;
    return sendto(rth->fd, buf, len, 0, (struct sockaddr *)&nladdr,
              sizeof(nladdr));
}
References buf, rtnl_handle::fd, and rth.
rtnl_talk()
int rtnl_talk (struct rtnl_handle * rtnl, struct nlmsghdr * n, pid_t peer, unsigned groups, struct nlmsghdr * answer, rtnl_filter_t junk, void * jarg)
Definition at line 251 of file libnetlink.c.
{
    int status;
    unsigned seq;
    struct nlmsghdr *h;
    struct sockaddr_nl nladdr;
    struct iovec iov = {
        .iov_base = (void *)n,
        .iov_len = n->nlmsg_len
    };
    struct msghdr msg = {
        .msg_name = &nladdr,
        .msg_namelen = sizeof(nladdr),
        .msg_iov = &iov,
        .msg_iovlen = 1,
    };
    char buf[16384];
    memset(&nladdr, 0, sizeof(nladdr));
    nladdr.nl_family = AF_NETLINK;
    nladdr.nl_pid = peer;
    nladdr.nl_groups = groups;
    n->nlmsg_seq = seq = ++rtnl->seq;
    if (answer == NULL)
        n->nlmsg_flags |= NLM_F_ACK;
    status = sendmsg(rtnl->fd, &msg, 0);
    if (status < 0) {
        ERROR("Cannot talk to rtnetlink");
        return -1;
    }
    memset(buf, 0, sizeof(buf));
    iov.iov_base = buf;
    while (1) {
        iov.iov_len = sizeof(buf);
        status = recvmsg(rtnl->fd, &msg, 0);
        if (status < 0) {
            if (errno == EINTR)
                continue;
            ERROR("OVERRUN");
            continue;
        }
        if (status == 0) {
            ERROR("EOF on netlink\n");
            return -1;
        }
        if (msg.msg_namelen != sizeof(nladdr)) {
            ERROR("sender address length == %d\n",
                msg.msg_namelen);
            return -1;
        }
        for (h = (struct nlmsghdr *)buf; status >= sizeof(*h);) {
            int err;
            int len = h->nlmsg_len;
            int l = len - sizeof(*h);
            if (l < 0 || len > status) {
                if (msg.msg_flags & MSG_TRUNC) {
                    ERROR("Truncated message\n");
                    return -1;
                }
                ERROR(
                    "!!!malformed message: len=%d\n", len);
                return -1;
            }
            if (nladdr.nl_pid != peer ||
                h->nlmsg_pid != rtnl->local.nl_pid ||
                h->nlmsg_seq != seq) {
                if (junk) {
                    err = junk(&nladdr, h, jarg);
                    if (err < 0)
                        return err;
                }
                /* Don't forget to skip that message. */
                status -= NLMSG_ALIGN(len);
                h = (struct nlmsghdr *)((char *)h +
                            NLMSG_ALIGN(len));
                continue;
            }
            if (h->nlmsg_type == NLMSG_ERROR) {
                struct nlmsgerr *err =
                    (struct nlmsgerr *)NLMSG_DATA(h);
                if (l < sizeof(struct nlmsgerr)) {
                    ERROR("ERROR truncated\n");
                } else {
                    errno = -err->error;
                    if (errno == 0) {
                        if (answer)
                            memcpy(answer, h,
                                   h->nlmsg_len);
                        return 0;
                    }
                    LOG("RTNETLINK answers");
                }
                return -1;
            }
            if (answer) {
                memcpy(answer, h, h->nlmsg_len);
                return 0;
            }
            ERROR("Unexpected reply!!!\n");
            status -= NLMSG_ALIGN(len);
            h = (struct nlmsghdr *)((char *)h + NLMSG_ALIGN(len));
        }
        if (msg.msg_flags & MSG_TRUNC) {
            ERROR("Message truncated\n");
            continue;
        }
        if (status) {
            ERROR("!!!Remnant of size %d\n", status);
            return -1;
        }
    }
}
References buf, err, ERROR, rtnl_handle::fd, rtnl_handle::local, LOG, and rtnl_handle::seq.
Referenced by br_set_state().
rtnl_wilddump_request()
int rtnl_wilddump_request (struct rtnl_handle * rth, int fam, int type)
Definition at line 108 of file libnetlink.c.
{
    struct {
        struct nlmsghdr nlh;
        struct rtgenmsg g;
    } req;
    struct sockaddr_nl nladdr;
    memset(&nladdr, 0, sizeof(nladdr));
    nladdr.nl_family = AF_NETLINK;
    memset(&req, 0, sizeof(req));
    req.nlh.nlmsg_len = sizeof(req);
    req.nlh.nlmsg_type = type;
    req.nlh.nlmsg_flags = NLM_F_ROOT | NLM_F_MATCH | NLM_F_REQUEST;
    req.nlh.nlmsg_pid = 0;
    req.nlh.nlmsg_seq = rth->dump = ++rth->seq;
    req.g.rtgen_family = family;
    return sendto(rth->fd, (void *)&req, sizeof(req), 0,
              (struct sockaddr *)&nladdr, sizeof(nladdr));
}
References rtnl_handle::dump, rtnl_handle::fd, rth, rtnl_handle::seq, and type.
Referenced by init_bridge_ops().