zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/initd/init.c File Reference
init.c File Reference
#include <sys/wait.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/reboot.h>
#include <libubox/uloop.h>
#include <libubus.h>
#include <limits.h>
#include <stdlib.h>
#include <fcntl.h>
#include <getopt.h>
#include <libgen.h>
#include <regex.h>
#include <unistd.h>
#include <stdio.h>
#include "../utils/utils.h"
#include "init.h"
#include "../watchdog.h"
Functions
static void signal_shutdown (int signal, siginfo_t *siginfo, void *data)
static void cmdline (void)
static int selinux (char **argv)
int main (int argc, char **argv)
Variables
unsigned int debug = 0
static struct sigaction sa_shutdown
Function Documentation
cmdline()
static void cmdline (void) static
Definition at line 62 of file init.c.
{
    char line[20];
    char* res;
    long    r;
    res = get_cmdline_val("init_debug", line, sizeof(line));
    if (res != NULL) {
        r = strtol(line, NULL, 10);
        if ((r != LONG_MIN) && (r != LONG_MAX))
            debug = (int) r;
    }
}
References debug, get_cmdline_val, and r.
Referenced by main(), and service_start_early().
main()
int main (int argc, char ** argv)
Definition at line 121 of file init.c.
{
    pid_t pid;
    ulog_open(ULOG_KMSG, LOG_DAEMON, "init");
    sigaction(SIGTERM, &sa_shutdown, NULL);
    sigaction(SIGUSR1, &sa_shutdown, NULL);
    sigaction(SIGUSR2, &sa_shutdown, NULL);
    sigaction(SIGPWR, &sa_shutdown, NULL);
    if (selinux(argv))
        exit(-1);
    early();
    cmdline();
    watchdog_init(1);
    pid = fork();
    if (!pid) {
        char *kmod[] = { "/sbin/kmodloader", "/etc/modules-boot.d/", NULL };
        if (debug < 3)
            patch_stdio("/dev/null");
        execvp(kmod[0], kmod);
        ERROR("Failed to start kmodloader: %m\n");
        exit(EXIT_FAILURE);
    }
    if (pid <= 0) {
        ERROR("Failed to start kmodloader instance: %m\n");
    } else {
        const struct timespec req = {0, 10 * 1000 * 1000};
        int i;
        for (i = 0; i < 1200; i++) {
            if (waitpid(pid, NULL, WNOHANG) > 0)
                break;
            nanosleep(&req, NULL);
            watchdog_ping();
        }
    }
    uloop_init();
    preinit();
    uloop_run();
    return 0;
}
References cmdline(), debug, early(), ERROR, patch_stdio(), preinit(), sa_shutdown, selinux(), ULOG_KMSG, ulog_open(), uloop_init(), uloop_run(), watchdog_init(), and watchdog_ping().
selinux()
static int selinux (char ** argv) static
Definition at line 114 of file init.c.
{
    return 0;
}
Referenced by main().
signal_shutdown()
static void signal_shutdown (int signal, siginfo_t * siginfo, void * data) static
Definition at line 45 of file init.c.
{
    fprintf(stderr, "reboot\n");
    fflush(stderr);
    sync();
    sleep(2);
    reboot(RB_AUTOBOOT);
    while (1)
        ;
}
Variable Documentation
debug
unsigned int debug = 0
Definition at line 42 of file init.c.
Referenced by check_dbglvl(), cmdline(), handle_exec(), hotplug_handler_debug(), main(), parseOCIlinuxcgroups_devices(), parseOCIlinuxseccomp(), rule_handle_command(), spawn_procd(), trigger_command_run(), and watch_notify_cb().
sa_shutdown
struct sigaction sa_shutdown static
Initial value:
= {
    .sa_sigaction = signal_shutdown,
    .sa_flags = SA_SIGINFO
}
Definition at line 56 of file init.c.
{
    .sa_sigaction = signal_shutdown,
    .sa_flags = SA_SIGINFO
};
Referenced by main().