zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/netifd/interface-ip.h File Reference
interface-ip.h File Reference
#include "interface.h"
Classes
union if_addr
struct device_prefix_assignment
struct device_prefix
struct device_route
struct device_neighbor
struct device_addr
struct device_source_table
struct dns_server
struct dns_search_domain
Enumerations
enum device_addr_flags {
DEVADDR_INET4 = (0 << 0) , DEVADDR_INET6 = (1 << 0) , DEVADDR_FAMILY = DEVADDR_INET4 | DEVADDR_INET6 , DEVADDR_EXTERNAL = (1 << 2) ,
DEVROUTE_METRIC = (1 << 3) , DEVROUTE_MTU = (1 << 4) , DEVROUTE_PROTO = (1 << 5) , DEVADDR_OFFLINK = (1 << 6) ,
DEVROUTE_TABLE = (1 << 7) , DEVROUTE_SRCTABLE = (1 << 8) , DEVROUTE_ONLINK = (1 << 9) , DEVROUTE_TYPE = (1 << 10) ,
DEVNEIGH_MAC = (1 << 11) , DEVROUTE_NODEV = (1 << 12)
}
Functions
void interface_ip_init (struct interface *iface)
void interface_add_dns_server_list (struct interface_ip_settings *ip, struct blob_attr *list)
void interface_add_dns_search_list (struct interface_ip_settings *ip, struct blob_attr *list)
void interface_write_resolv_conf (const char *jail)
void interface_ip_add_route (struct interface *iface, struct blob_attr *attr, bool v6)
void interface_ip_add_neighbor (struct interface *iface, struct blob_attr *attr, bool v6)
void interface_ip_update_start (struct interface_ip_settings *ip)
void interface_ip_update_complete (struct interface_ip_settings *ip)
void interface_ip_flush (struct interface_ip_settings *ip)
void interface_ip_set_enabled (struct interface_ip_settings *ip, bool enabled)
void interface_ip_update_metric (struct interface_ip_settings *ip, int metric)
struct interface * interface_ip_add_target_route (union if_addr *addr, bool v6, struct interface *iface, bool exclude)
struct device_prefix * interface_ip_add_device_prefix (struct interface *iface, struct in6_addr *addr, uint8_t length, time_t valid_until, time_t preferred_until, struct in6_addr *excl_addr, uint8_t excl_length, const char *pclass)
void interface_ip_set_ula_prefix (const char *prefix)
void interface_refresh_assignments (bool hint)
void interface_update_prefix_delegation (struct interface_ip_settings *ip)
Variables
const struct uci_blob_param_list route_attr_list
const struct uci_blob_param_list neighbor_attr_list
struct list_head prefixes
Class Documentation
if_addr
union if_addr
Definition at line 59 of file interface-ip.h.
Class Members
struct in_addr in
struct in6_addr in6
device_prefix_assignment
struct device_prefix_assignment
Definition at line 64 of file interface-ip.h.
Class Members
struct in6_addr addr
int32_t assigned
bool enabled
struct list_head head
uint8_t length
char name[]
int weight
device_prefix
struct device_prefix
Definition at line 74 of file interface-ip.h.
Class Members
struct in6_addr addr
struct list_head assignments
struct in6_addr excl_addr
uint8_t excl_length
struct list_head head
struct interface * iface
uint8_t length
struct vlist_node node
char pclass[]
time_t preferred_until
time_t valid_until
device_route
struct device_route
Definition at line 91 of file interface-ip.h.
Class Members
union if_addr addr
bool enabled
bool failed
enum device_addr_flags flags
struct interface * iface
bool keep
unsigned int mask
int metric
int mtu
union if_addr nexthop
struct vlist_node node
unsigned int proto
union if_addr source
unsigned int sourcemask
unsigned int table
unsigned int type
time_t valid_until
device_neighbor
struct device_neighbor
Definition at line 115 of file interface-ip.h.
Class Members
union if_addr addr
bool enabled
bool failed
enum device_addr_flags flags
bool keep
uint8_t macaddr[6]
struct vlist_node node
bool proxy
bool router
device_addr
struct device_addr
Definition at line 129 of file interface-ip.h.
Class Members
union if_addr addr
uint32_t broadcast
bool enabled
bool failed
enum device_addr_flags flags
int index
unsigned int mask
struct vlist_node node
char * pclass
uint32_t point_to_point
unsigned int policy_table
time_t preferred_until
struct device_route subnet
time_t valid_until
device_source_table
struct device_source_table
Definition at line 153 of file interface-ip.h.
Class Members
union if_addr addr
struct list_head head
uint8_t mask
uint16_t refcount
uint32_t table
uint8_t v6
dns_server
struct dns_server
Definition at line 162 of file interface-ip.h.
Class Members
union if_addr addr
int af
struct vlist_simple_node node
dns_search_domain
struct dns_search_domain
Definition at line 168 of file interface-ip.h.
Class Members
char name[]
struct vlist_simple_node node
Enumeration Type Documentation
device_addr_flags
enum device_addr_flags
Enumerator
DEVADDR_INET4 (0 << 0)
DEVADDR_INET6 (1 << 0)
DEVADDR_FAMILY DEVADDR_INET4 | DEVADDR_INET6
DEVADDR_EXTERNAL (1 << 2)
DEVROUTE_METRIC (1 << 3)
DEVROUTE_MTU (1 << 4)
DEVROUTE_PROTO (1 << 5)
DEVADDR_OFFLINK (1 << 6)
DEVROUTE_TABLE (1 << 7)
DEVROUTE_SRCTABLE (1 << 8)
DEVROUTE_ONLINK (1 << 9)
DEVROUTE_TYPE (1 << 10)
DEVNEIGH_MAC (1 << 11)
DEVROUTE_NODEV (1 << 12)
Definition at line 19 of file interface-ip.h.
                       {
    /* address family for routes and addresses */
    DEVADDR_INET4       = (0 << 0),
    DEVADDR_INET6       = (1 << 0),
    DEVADDR_FAMILY      = DEVADDR_INET4 | DEVADDR_INET6,
    /* externally added address */
    DEVADDR_EXTERNAL    = (1 << 2),
    /* route overrides the default interface metric */
    DEVROUTE_METRIC     = (1 << 3),
    /* route overrides the default interface mtu */
    DEVROUTE_MTU        = (1 << 4),
    /* route overrides the default proto type */
    DEVROUTE_PROTO      = (1 << 5),
    /* address is off-link (no subnet-route) */
    DEVADDR_OFFLINK     = (1 << 6),
    /* route resides in different table */
    DEVROUTE_TABLE      = (1 << 7),
    /* route resides in default source-route table */
    DEVROUTE_SRCTABLE   = (1 << 8),
    /* route is on-link */
    DEVROUTE_ONLINK     = (1 << 9),
    /* route overrides the default route type */
    DEVROUTE_TYPE       = (1 << 10),
    /* neighbor mac address */
    DEVNEIGH_MAC        = (1 << 11),
    /* route specifies no device */
    DEVROUTE_NODEV      = (1 << 12),
};
Function Documentation
interface_add_dns_search_list()
void interface_add_dns_search_list (struct interface_ip_settings * ip, struct blob_attr * list)
Definition at line 1473 of file interface-ip.c.
{
    struct blob_attr *cur;
    size_t rem;
    blobmsg_for_each_attr(cur, list, rem) {
        if (blobmsg_type(cur) != BLOBMSG_TYPE_STRING)
            continue;
        if (!blobmsg_check_attr(cur, false))
            continue;
        interface_add_dns_search_domain(ip, blobmsg_data(cur));
    }
}
References blobmsg_check_attr(), blobmsg_data(), blobmsg_for_each_attr, BLOBMSG_TYPE_STRING, and interface_add_dns_search_domain().
Referenced by interface_alloc(), and proto_shell_update_link().
interface_add_dns_server_list()
void interface_add_dns_server_list (struct interface_ip_settings * ip, struct blob_attr * list)
Definition at line 1441 of file interface-ip.c.
{
    struct blob_attr *cur;
    size_t rem;
    blobmsg_for_each_attr(cur, list, rem) {
        if (blobmsg_type(cur) != BLOBMSG_TYPE_STRING)
            continue;
        if (!blobmsg_check_attr(cur, false))
            continue;
        interface_add_dns_server(ip, blobmsg_data(cur));
    }
}
References blobmsg_check_attr(), blobmsg_data(), blobmsg_for_each_attr, BLOBMSG_TYPE_STRING, and interface_add_dns_server().
Referenced by interface_alloc(), and proto_shell_update_link().
interface_ip_add_device_prefix()
struct device_prefix * interface_ip_add_device_prefix (struct interface * iface, struct in6_addr * addr, uint8_t length, time_t valid_until, time_t preferred_until, struct in6_addr * excl_addr, uint8_t excl_length, const char * pclass)
Definition at line 1345 of file interface-ip.c.
{
    union if_addr a = { .in6 = *addr };
    if (!pclass)
        pclass = (iface) ? iface->name : "local";
    struct device_prefix *prefix = calloc(1, sizeof(*prefix) + strlen(pclass) + 1);
    if (!prefix)
        return NULL;
    clear_if_addr(&a, length);
    prefix->length = length;
    prefix->addr = a.in6;
    prefix->preferred_until = preferred_until;
    prefix->valid_until = valid_until;
    prefix->iface = iface;
    INIT_LIST_HEAD(&prefix->assignments);
    if (excl_addr) {
        prefix->excl_addr = *excl_addr;
        prefix->excl_length = excl_length;
    }
    strcpy(prefix->pclass, pclass);
    if (iface)
        vlist_add(&iface->proto_ip.prefix, &prefix->node, &prefix->addr);
    else
        interface_update_prefix(NULL, &prefix->node, NULL);
    return prefix;
}
References device_prefix::addr, device_prefix::assignments, clear_if_addr(), device_prefix::excl_addr, device_prefix::excl_length, device_prefix::iface, if_addr::in6, INIT_LIST_HEAD(), interface_update_prefix(), device_prefix::length, interface::name, device_prefix::node, device_prefix::pclass, device_prefix::preferred_until, interface_ip_settings::prefix, interface::proto_ip, device_prefix::valid_until, and vlist_add().
Referenced by interface_ip_set_ula_prefix(), and parse_prefix_option().
interface_ip_add_neighbor()
void interface_ip_add_neighbor (struct interface * iface, struct blob_attr * attr, bool v6)
Definition at line 344 of file interface-ip.c.
{
    struct interface_ip_settings *ip;
    struct blob_attr *tb[__NEIGHBOR_MAX], *cur;
    struct device_neighbor *neighbor;
    int af = v6 ? AF_INET6: AF_INET;
    struct ether_addr *ea;
    blobmsg_parse(neighbor_attr, __NEIGHBOR_MAX, tb, blobmsg_data(attr), blobmsg_data_len(attr));
    if (!iface) {
        if ((cur = tb[NEIGHBOR_INTERFACE]) == NULL)
            return;
        iface = vlist_find(&interfaces, blobmsg_data(cur), iface, node);
        if (!iface)
            return;
        ip = &iface->config_ip;
    } else
        ip = &iface->proto_ip;
    neighbor = calloc(1,sizeof(*neighbor));
    if (!neighbor)
        return;
    neighbor->flags = v6 ? DEVADDR_INET6 : DEVADDR_INET4;
    if ((cur = tb[NEIGHBOR_ADDRESS]) != NULL){
        if (!inet_pton(af, blobmsg_data(cur), &neighbor->addr))
            goto error;
    } else
        goto error;
    if ((cur = tb[NEIGHBOR_MAC]) != NULL) {
        neighbor->flags |= DEVNEIGH_MAC;
        ea = ether_aton(blobmsg_data(cur));
        if (!ea)
            goto error;
        memcpy(neighbor->macaddr, ea, 6);
    }
    if ((cur = tb[NEIGHBOR_PROXY]) != NULL)
        neighbor->proxy = blobmsg_get_bool(cur);
    if ((cur = tb[NEIGHBOR_ROUTER]) != NULL)
        neighbor->router = blobmsg_get_bool(cur);
    vlist_add(&ip->neighbor, &neighbor->node, neighbor);
    return;
error:
    free(neighbor);
}
References __NEIGHBOR_MAX, device_neighbor::addr, blobmsg_data(), blobmsg_data_len(), blobmsg_get_bool(), blobmsg_parse(), interface::config_ip, DEVADDR_INET4, DEVADDR_INET6, DEVNEIGH_MAC, device_neighbor::flags, interfaces, device_neighbor::macaddr, interface_ip_settings::neighbor, NEIGHBOR_ADDRESS, neighbor_attr, NEIGHBOR_INTERFACE, NEIGHBOR_MAC, NEIGHBOR_PROXY, NEIGHBOR_ROUTER, device_neighbor::node, interface::proto_ip, device_neighbor::proxy, device_neighbor::router, vlist_add(), and vlist_find.
Referenced by config_parse_neighbor(), and proto_shell_parse_neighbor_list().
interface_ip_add_route()
void interface_ip_add_route (struct interface * iface, struct blob_attr * attr, bool v6)
Definition at line 402 of file interface-ip.c.
{
    struct interface_ip_settings *ip;
    struct blob_attr *tb[__ROUTE_MAX], *cur;
    struct device_route *route;
    int af = v6 ? AF_INET6 : AF_INET;
    bool no_device = false;
    blobmsg_parse(route_attr, __ROUTE_MAX, tb, blobmsg_data(attr), blobmsg_data_len(attr));
    if ((cur = tb[ROUTE_DISABLED]) != NULL && blobmsg_get_bool(cur))
        return;
    if (!iface) {
        if ((cur = tb[ROUTE_INTERFACE]) == NULL) {
            iface = vlist_find(&interfaces, "loopback", iface, node);
            no_device = true;
        } else {
            iface = vlist_find(&interfaces, blobmsg_data(cur), iface, node);
        }
        if (!iface)
            return;
        ip = &iface->config_ip;
    } else {
        ip = &iface->proto_ip;
    }
    route = calloc(1, sizeof(*route));
    if (!route)
        return;
    route->flags = v6 ? DEVADDR_INET6 : DEVADDR_INET4;
    route->mask = v6 ? 128 : 32;
    if ((cur = tb[ROUTE_MASK]) != NULL) {
        route->mask = parse_netmask_string(blobmsg_data(cur), v6);
        if (route->mask > (v6 ? 128 : 32))
            goto error;
    }
    if ((cur = tb[ROUTE_TARGET]) != NULL) {
        if (!parse_ip_and_netmask(af, blobmsg_data(cur), &route->addr, &route->mask)) {
            D(INTERFACE, "Failed to parse route target: %s", (char *) blobmsg_data(cur));
            goto error;
        }
        /* Mask out IPv4 host bits to avoid "Invalid prefix for given prefix length" */
        if (af == AF_INET && route->mask < 32)
            clear_if_addr(&route->addr, route->mask);
    }
    if ((cur = tb[ROUTE_GATEWAY]) != NULL) {
        if (!inet_pton(af, blobmsg_data(cur), &route->nexthop)) {
            D(INTERFACE, "Failed to parse route gateway: %s", (char *) blobmsg_data(cur));
            goto error;
        }
    }
    if ((cur = tb[ROUTE_METRIC]) != NULL) {
        route->metric = blobmsg_get_u32(cur);
        route->flags |= DEVROUTE_METRIC;
    }
    if ((cur = tb[ROUTE_MTU]) != NULL) {
        route->mtu = blobmsg_get_u32(cur);
        route->flags |= DEVROUTE_MTU;
    }
    /* Use source-based routing */
    if ((cur = tb[ROUTE_SOURCE]) != NULL) {
        char *saveptr, *source = alloca(blobmsg_data_len(cur));
        memcpy(source, blobmsg_data(cur), blobmsg_data_len(cur));
        const char *addr = strtok_r(source, "/", &saveptr);
        const char *mask = strtok_r(NULL, "/", &saveptr);
        if (!addr || inet_pton(af, addr, &route->source) < 1) {
            D(INTERFACE, "Failed to parse route source: %s", addr ? addr : "NULL");
            goto error;
        }
        route->sourcemask = (mask) ? atoi(mask) : ((af == AF_INET6) ? 128 : 32);
    }
    if ((cur = tb[ROUTE_ONLINK]) != NULL && blobmsg_get_bool(cur))
        route->flags |= DEVROUTE_ONLINK;
    if ((cur = tb[ROUTE_TABLE]) != NULL) {
        if (!system_resolve_rt_table(blobmsg_data(cur), &route->table)) {
            D(INTERFACE, "Failed to resolve routing table: %s", (char *) blobmsg_data(cur));
            goto error;
        }
        /* only set the table flag if not using the main (default) table */
        if (system_is_default_rt_table(route->table))
            route->table = 0;
        if (route->table)
            route->flags |= DEVROUTE_TABLE;
    }
    if ((cur = tb[ROUTE_VALID]) != NULL) {
        int64_t valid = blobmsg_get_u32(cur);
        int64_t valid_until = valid + (int64_t)system_get_rtime();
        if (valid_until <= LONG_MAX && valid != 0xffffffffLL) /* Catch overflow */
            route->valid_until = valid_until;
    }
    if ((cur = tb[ROUTE_TYPE]) != NULL) {
        if (!system_resolve_rt_type(blobmsg_data(cur), &route->type)) {
            D(INTERFACE, "Failed to resolve routing type: %s", (char *) blobmsg_data(cur));
            goto error;
        }
        route->flags |= DEVROUTE_TYPE;
    }
    if ((cur = tb[ROUTE_PROTO]) != NULL) {
        if (!system_resolve_rt_proto(blobmsg_data(cur), &route->proto)) {
            D(INTERFACE, "Failed to resolve proto type: %s", (char *) blobmsg_data(cur));
            goto error;
        }
        route->flags |= DEVROUTE_PROTO;
    }
    if (no_device)
        route->flags |= DEVROUTE_NODEV;
    else
        interface_set_route_info(iface, route);
    vlist_add(&ip->route, &route->node, route);
    return;
error:
    free(route);
}
References __ROUTE_MAX, device_route::addr, blobmsg_data(), blobmsg_data_len(), blobmsg_get_bool(), blobmsg_get_u32(), blobmsg_parse(), clear_if_addr(), interface::config_ip, D, DEVADDR_INET4, DEVADDR_INET6, DEVROUTE_METRIC, DEVROUTE_MTU, DEVROUTE_NODEV, DEVROUTE_ONLINK, DEVROUTE_PROTO, DEVROUTE_TABLE, DEVROUTE_TYPE, device_route::flags, device_route::iface, interface_set_route_info(), interfaces, device_route::mask, device_route::metric, device_route::mtu, device_route::nexthop, device_route::node, parse_ip_and_netmask(), parse_netmask_string(), device_route::proto, interface::proto_ip, interface_ip_settings::route, route_attr, ROUTE_DISABLED, ROUTE_GATEWAY, ROUTE_INTERFACE, ROUTE_MASK, ROUTE_METRIC, ROUTE_MTU, ROUTE_ONLINK, ROUTE_PROTO, ROUTE_SOURCE, ROUTE_TABLE, ROUTE_TARGET, ROUTE_TYPE, ROUTE_VALID, device_route::source, device_route::sourcemask, system_get_rtime(), system_is_default_rt_table(), system_resolve_rt_proto(), system_resolve_rt_table(), system_resolve_rt_type(), device_route::table, device_route::type, device_route::valid_until, vlist_add(), and vlist_find.
Referenced by config_parse_route(), and proto_shell_parse_route_list().
interface_ip_add_target_route()
struct interface * interface_ip_add_target_route (union if_addr * addr, bool v6, struct interface * iface, bool exclude)
Definition at line 260 of file interface-ip.c.
{
    struct device_route *route, *r_next = NULL;
    bool defaultroute_target = false;
    union if_addr addr_zero;
    int addrsize = v6 ? sizeof(addr->in6) : sizeof(addr->in);
    struct interface *exclude_iface = NULL;
    if (exclude) {
        exclude_iface = iface;
        iface = NULL;
    }
    memset(&addr_zero, 0, sizeof(addr_zero));
    if (memcmp(&addr_zero, addr, addrsize) == 0)
        defaultroute_target = true;
    if (iface) {
        /* look for locally addressable target first */
        if (interface_ip_find_addr_target(iface, addr, v6))
            return iface;
        /* do not stop at the first route, let the lookup compare
         * masks to find the best match */
        interface_ip_find_route_target(iface, addr, v6, &r_next);
    } else {
        vlist_for_each_element(&interfaces, iface, node) {
            if (iface == exclude_iface)
                continue;
            /* look for locally addressable target first */
            if (interface_ip_find_addr_target(iface, addr, v6))
                return iface;
            /* do not stop at the first route, let the lookup compare
             * masks to find the best match */
            interface_ip_find_route_target(iface, addr, v6, &r_next);
        }
    }
    if (!r_next)
        return NULL;
    iface = r_next->iface;
    if (defaultroute_target)
        return iface;
    route = calloc(1, sizeof(*route));
    if (!route)
        return NULL;
    route->flags = v6 ? DEVADDR_INET6 : DEVADDR_INET4;
    route->mask = v6 ? 128 : 32;
    memcpy(&route->addr, addr, addrsize);
    memcpy(&route->nexthop, &r_next->nexthop, sizeof(route->nexthop));
    route->mtu = r_next->mtu;
    route->metric = r_next->metric;
    route->table = r_next->table;
    route->iface = iface;
    vlist_add(&iface->host_routes, &route->node, route);
    return iface;
}
References device_route::addr, DEVADDR_INET4, DEVADDR_INET6, device_route::flags, interface::host_routes, device_route::iface, if_addr::in, if_addr::in6, interface_ip_find_addr_target(), interface_ip_find_route_target(), interfaces, device_route::mask, device_route::metric, device_route::mtu, device_route::nexthop, device_route::node, device_route::table, vlist_add(), and vlist_for_each_element.
Referenced by netifd_add_host_route(), and proto_shell_update_host_dep().
interface_ip_flush()
void interface_ip_flush (struct interface_ip_settings * ip)
Definition at line 1795 of file interface-ip.c.
{
    if (ip == &ip->iface->proto_ip)
        vlist_flush_all(&ip->iface->host_routes);
    vlist_simple_flush_all(&ip->dns_servers);
    vlist_simple_flush_all(&ip->dns_search);
    vlist_flush_all(&ip->route);
    vlist_flush_all(&ip->addr);
    vlist_flush_all(&ip->neighbor);
    vlist_flush_all(&ip->prefix);
}
References interface_ip_settings::addr, interface_ip_settings::dns_search, interface_ip_settings::dns_servers, interface::host_routes, interface_ip_settings::iface, interface_ip_settings::neighbor, interface_ip_settings::prefix, interface::proto_ip, interface_ip_settings::route, vlist_flush_all(), and vlist_simple_flush_all().
Referenced by interface_cleanup(), interface_set_l3_dev(), and mark_interface_down().
interface_ip_init()
void interface_ip_init (struct interface * iface)
Definition at line 1821 of file interface-ip.c.
{
    __interface_ip_init(&iface->proto_ip, iface);
    __interface_ip_init(&iface->config_ip, iface);
    vlist_init(&iface->host_routes, route_cmp, interface_update_host_route);
}
References __interface_ip_init(), interface::config_ip, interface::host_routes, interface_update_host_route(), interface::proto_ip, route_cmp(), and vlist_init().
Referenced by interface_alloc().
interface_ip_set_enabled()
void interface_ip_set_enabled (struct interface_ip_settings * ip, bool enabled)
Definition at line 1655 of file interface-ip.c.
{
    struct device_addr *addr;
    struct device_route *route;
    struct device_neighbor *neighbor;
    struct device *dev;
    struct interface *iface;
    ip->enabled = enabled;
    iface = ip->iface;
    dev = iface->l3_dev.dev;
    if (!dev)
        return;
    vlist_for_each_element(&ip->addr, addr, node) {
        bool v6 = ((addr->flags & DEVADDR_FAMILY) == DEVADDR_INET6) ? true : false;
        if (addr->flags & DEVADDR_EXTERNAL)
            continue;
        if (addr->enabled == enabled)
            continue;
        if (enabled) {
            system_add_address(dev, addr);
            addr->policy_table = (v6) ? iface->ip6table : iface->ip4table;
            if (iface->metric || addr->policy_table)
                interface_handle_subnet_route(iface, addr, true);
            if ((addr->flags & DEVADDR_OFFLINK) && (addr->mask < (v6 ? 128 : 32))) {
                struct device_route route;
                memset(&route, 0, sizeof(route));
                route.flags = v6 ? DEVADDR_INET6 : DEVADDR_INET4;
                route.metric = INT32_MAX;
                route.mask = addr->mask;
                route.addr = addr->addr;
                clear_if_addr(&route.addr, route.mask);
                /*
                 * In case off link is specifed as address property
                 * add null-route to avoid routing loops
                 */
                system_add_route(NULL, &route);
            }
            if (addr->policy_table)
                interface_add_addr_rules(addr, true);
        } else {
            interface_handle_subnet_route(iface, addr, false);
            system_del_address(dev, addr);
            if ((addr->flags & DEVADDR_OFFLINK) && (addr->mask < (v6 ? 128 : 32))) {
                struct device_route route;
                memset(&route, 0, sizeof(route));
                route.flags = v6 ? DEVADDR_INET6 : DEVADDR_INET4;
                route.metric = INT32_MAX;
                route.mask = addr->mask;
                route.addr = addr->addr;
                clear_if_addr(&route.addr, route.mask);
                /* Delete null-route */
                system_del_route(NULL, &route);
            }
            if (addr->policy_table)
                interface_add_addr_rules(addr, false);
        }
        addr->enabled = enabled;
    }
    vlist_for_each_element(&ip->route, route, node)
        interface_ip_set_route_enabled(ip, route, enabled);
    if (ip == &iface->proto_ip)
        vlist_for_each_element(&iface->host_routes, route, node)
            interface_ip_set_route_enabled(ip, route, enabled);
    vlist_for_each_element(&ip->neighbor, neighbor, node) {
        if (neighbor->enabled == enabled)
            continue;
        if (enabled) {
            if(system_add_neighbor(dev, neighbor))
                neighbor->failed = true;
        } else
            system_del_neighbor(dev, neighbor);
        neighbor->enabled = enabled;
    }
    struct device_prefix *c;
    struct device_prefix_assignment *a;
    list_for_each_entry(c, &prefixes, head)
        list_for_each_entry(a, &c->assignments, head)
            if (!strcmp(a->name, ip->iface->name))
                interface_set_prefix_address(a, c, ip->iface, enabled);
    if (ip->iface->policy_rules_set != enabled &&
        ip->iface->l3_dev.dev) {
        if (ip->iface->l3_dev.dev->settings.ipv6) {
            set_ip_lo_policy(enabled, true, ip->iface);
            set_ip_source_policy(enabled, true, IPRULE_PRIORITY_REJECT + ip->iface->l3_dev.dev->ifindex,
                         NULL, 0, 0, ip->iface, "failed_policy", true);
        }
        set_ip_lo_policy(enabled, false, ip->iface);
        ip->iface->policy_rules_set = enabled;
    }
}
References device_addr::addr, device_route::addr, interface_ip_settings::addr, device_prefix::assignments, clear_if_addr(), device_user::dev, DEVADDR_EXTERNAL, DEVADDR_FAMILY, DEVADDR_INET4, DEVADDR_INET6, DEVADDR_OFFLINK, device_addr::enabled, device_neighbor::enabled, device_prefix_assignment::enabled, device_route::enabled, interface::enabled, interface_ip_settings::enabled, device_neighbor::failed, device_addr::flags, device_route::flags, device_prefix_assignment::head, interface::host_routes, device_route::iface, interface_ip_settings::iface, device::ifindex, interface_add_addr_rules(), interface_handle_subnet_route(), interface_ip_set_route_enabled(), interface_set_prefix_address(), interface::ip4table, interface::ip6table, IPRULE_PRIORITY_REJECT, device_settings::ipv6, interface::l3_dev, list_for_each_entry, device_addr::mask, device_route::mask, device_route::metric, interface::metric, device_prefix_assignment::name, interface::name, interface_ip_settings::neighbor, interface::policy_rules_set, device_addr::policy_table, prefixes, interface::proto_ip, interface_ip_settings::route, set_ip_lo_policy(), set_ip_source_policy(), device::settings, system_add_address(), system_add_neighbor(), system_add_route(), system_del_address(), system_del_neighbor(), system_del_route(), and vlist_for_each_element.
Referenced by interface_change_config(), interface_proto_event_cb(), interface_set_l3_dev(), and mark_interface_down().
interface_ip_set_ula_prefix()
void interface_ip_set_ula_prefix (const char * prefix)
Definition at line 1383 of file interface-ip.c.
{
    char buf[INET6_ADDRSTRLEN + 4] = {0}, *saveptr;
    if (prefix)
        strncpy(buf, prefix, sizeof(buf) - 1);
    char *prefixaddr = strtok_r(buf, "/", &saveptr);
    struct in6_addr addr;
    if (!prefixaddr || inet_pton(AF_INET6, prefixaddr, &addr) < 1) {
        if (ula_prefix) {
            interface_update_prefix(NULL, NULL, &ula_prefix->node);
            ula_prefix = NULL;
        }
        return;
    }
    int length;
    char *prefixlen = strtok_r(NULL, ",", &saveptr);
    if (!prefixlen || (length = atoi(prefixlen)) < 1 || length > 64)
        return;
    if (!ula_prefix || !IN6_ARE_ADDR_EQUAL(&addr, &ula_prefix->addr) ||
            ula_prefix->length != length) {
        if (ula_prefix)
            interface_update_prefix(NULL, NULL, &ula_prefix->node);
        ula_prefix = interface_ip_add_device_prefix(NULL, &addr, length,
                0, 0, NULL, 0, NULL);
    }
}
References device_prefix::addr, buf, interface_ip_add_device_prefix(), interface_update_prefix(), device_prefix::length, device_prefix::node, and ula_prefix.
Referenced by config_init_globals().
interface_ip_update_complete()
void interface_ip_update_complete (struct interface_ip_settings * ip)
Definition at line 1783 of file interface-ip.c.
{
    vlist_simple_flush(&ip->dns_servers);
    vlist_simple_flush(&ip->dns_search);
    vlist_flush(&ip->route);
    vlist_flush(&ip->addr);
    vlist_flush(&ip->prefix);
    vlist_flush(&ip->neighbor);
    interface_write_resolv_conf(ip->iface->jail);
}
References interface_ip_settings::addr, interface_ip_settings::dns_search, interface_ip_settings::dns_servers, interface_ip_settings::iface, interface_write_resolv_conf(), interface::jail, interface_ip_settings::neighbor, interface_ip_settings::prefix, interface_ip_settings::route, vlist_flush(), and vlist_simple_flush().
Referenced by config_init_ip(), and interface_update_complete().
interface_ip_update_metric()
void interface_ip_update_metric (struct interface_ip_settings * ip, int metric)
interface_ip_update_start()
void interface_ip_update_start (struct interface_ip_settings * ip)
Definition at line 1770 of file interface-ip.c.
{
    if (ip != &ip->iface->config_ip) {
        vlist_simple_update(&ip->dns_servers);
        vlist_simple_update(&ip->dns_search);
    }
    vlist_update(&ip->route);
    vlist_update(&ip->addr);
    vlist_update(&ip->prefix);
    vlist_update(&ip->neighbor);
}
References interface_ip_settings::addr, interface::config_ip, interface_ip_settings::dns_search, interface_ip_settings::dns_servers, interface_ip_settings::iface, interface_ip_settings::neighbor, interface_ip_settings::prefix, interface_ip_settings::route, vlist_simple_update(), and vlist_update().
Referenced by config_init_ip(), and interface_update_start().
interface_refresh_assignments()
void interface_refresh_assignments (bool hint)
Definition at line 1252 of file interface-ip.c.
{
    static bool refresh = false;
    if (!hint && refresh) {
        struct device_prefix *p;
        time_t now = system_get_rtime();
        list_for_each_entry(p, &prefixes, head) {
            bool valid = !(p->valid_until && p->valid_until - 1 <= now);
            interface_update_prefix_assignments(p, valid);
        }
    }
    refresh = hint;
}
References device_prefix::head, interface_update_prefix_assignments(), list_for_each_entry, prefixes, system_get_rtime(), and device_prefix::valid_until.
Referenced by config_init_all(), and interface_merge_assignment_data().
interface_update_prefix_delegation()
void interface_update_prefix_delegation (struct interface_ip_settings * ip)
Definition at line 1268 of file interface-ip.c.
{
    struct device_prefix *prefix;
    time_t now = system_get_rtime();
    vlist_for_each_element(&ip->prefix, prefix, node) {
        bool valid = !(prefix->valid_until && prefix->valid_until - 1 <= now);
        interface_update_prefix_assignments(prefix, !ip->no_delegation && valid);
        if (ip->no_delegation) {
            if (prefix->head.next)
                list_del(&prefix->head);
        } else
            list_add(&prefix->head, &prefixes);
    }
}
References device_prefix::head, interface_update_prefix_assignments(), list_add(), list_del(), list_head::next, interface_ip_settings::no_delegation, interface_ip_settings::prefix, prefixes, system_get_rtime(), device_prefix::valid_until, and vlist_for_each_element.
Referenced by interface_change_config().
interface_write_resolv_conf()
void interface_write_resolv_conf (const char * jail)
Definition at line 1579 of file interface-ip.c.
{
    size_t plen = (jail ? strlen(jail) + 1 : 0 ) +
        (strlen(resolv_conf) >= strlen(DEFAULT_RESOLV_CONF) ?
        strlen(resolv_conf) : strlen(DEFAULT_RESOLV_CONF) ) + 1;
    char *path = alloca(plen);
    char *dpath = alloca(plen);
    char *tmppath = alloca(plen + 4);
    FILE *f;
    uint32_t crcold, crcnew;
    if (jail) {
        sprintf(path, "/tmp/resolv.conf-%s.d/resolv.conf.auto", jail);
        strcpy(dpath, path);
        dpath = dirname(dpath);
        mkdir(dpath, 0755);
    } else {
        strcpy(path, resolv_conf);
    }
    sprintf(tmppath, "%s.tmp", path);
    unlink(tmppath);
    f = fopen(tmppath, "w+");
    if (!f) {
        D(INTERFACE, "Failed to open %s for writing", path);
        return;
    }
    __interface_write_dns_entries(f, jail);
    fflush(f);
    rewind(f);
    crcnew = crc32_file(f);
    fclose(f);
    crcold = crcnew + 1;
    f = fopen(path, "r");
    if (f) {
        crcold = crc32_file(f);
        fclose(f);
    }
    if (crcold == crcnew) {
        unlink(tmppath);
    } else if (rename(tmppath, path) < 0) {
        D(INTERFACE, "Failed to replace %s", path);
        unlink(tmppath);
    }
}
References __interface_write_dns_entries(), crc32_file(), D, DEFAULT_RESOLV_CONF, path, and resolv_conf.
Referenced by interface_change_config(), interface_ip_update_complete(), and interface_proto_event_cb().
Variable Documentation
neighbor_attr_list
const struct uci_blob_param_list neighbor_attr_list extern
Definition at line 88 of file interface-ip.c.
{
    .n_params = __NEIGHBOR_MAX,
    .params = neighbor_attr,
};
Referenced by config_parse_neighbor().
prefixes
struct list_head prefixes extern
Definition at line 94 of file interface-ip.c.
Referenced by interface_ip_dump_prefix_assignment_list(), interface_ip_set_enabled(), interface_refresh_assignments(), interface_update_prefix(), and interface_update_prefix_delegation().
route_attr_list
const struct uci_blob_param_list route_attr_list extern
Definition at line 66 of file interface-ip.c.
{
    .n_params = __ROUTE_MAX,
    .params = route_attr,
};
Referenced by config_parse_route().