zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/netifd/wireless.h File Reference
wireless.h File Reference
#include <libubox/utils.h>
#include <libubox/list.h>
#include "interface.h"
Classes
struct wireless_driver
struct wireless_device
struct wireless_interface
struct wireless_vlan
struct wireless_station
struct wireless_process
struct wireless_driver.device
struct wireless_driver.interface
struct wireless_driver.vlan
struct wireless_driver.station
Functions
void wireless_device_create (struct wireless_driver *drv, const char *name, struct blob_attr *data)
void wireless_device_set_up (struct wireless_device *wdev)
void wireless_device_set_down (struct wireless_device *wdev)
void wireless_device_reconf (struct wireless_device *wdev)
void wireless_device_status (struct wireless_device *wdev, struct blob_buf *b)
void wireless_device_get_validate (struct wireless_device *wdev, struct blob_buf *b)
struct wireless_interface * wireless_interface_create (struct wireless_device *wdev, struct blob_attr *data, const char *section)
void wireless_vlan_create (struct wireless_interface *vif, struct blob_attr *data, const char *section)
void wireless_station_create (struct wireless_interface *vif, struct blob_attr *data, const char *section)
int wireless_device_notify (struct wireless_device *wdev, struct blob_attr *data, struct ubus_request_data *req)
void wireless_check_network_enabled (void)
void wireless_start_pending (int timeout)
void wireless_init (void)
void wireless_device_hotplug_event (const char *name, bool add)
Variables
struct vlist_tree wireless_devices
struct avl_tree wireless_drivers
Class Documentation
wireless_driver
struct wireless_driver
Definition at line 24 of file wireless.h.
Class Members
struct wireless_driver.device device
struct wireless_driver.interface interface
const char * name
struct avl_node node
const char * script
struct wireless_driver.station station
struct wireless_driver.vlan vlan
wireless_device
struct wireless_device
Definition at line 36 of file wireless.h.
Class Members
bool autostart
bool cancel
struct blob_attr * config
enum interface_config_state config_state
bool config_update
struct blob_attr * data
bool disabled
struct wireless_driver * drv
struct list_head handler
bool handler_action
bool handler_pending
struct vlist_tree interfaces
struct ubus_request_data * kill_request
char * name
struct vlist_node node
struct uloop_timeout poll
struct blob_attr * prev_config
bool reconf
int retry
bool retry_setup_failed
struct uloop_timeout script_check
struct list_head script_proc
struct uloop_fd script_proc_fd
struct netifd_process script_task
bool serialize
enum interface_state state
struct uloop_timeout timeout
int vif_idx
wireless_interface
struct wireless_interface
Definition at line 76 of file wireless.h.
Class Members
bool ap_mode
bool bridge_isolate
struct blob_attr * config
struct blob_attr * data
bool disabled
const char * ifname
bool isolate
int multicast_to_unicast
char * name
struct blob_attr * network
int network_ifindex
struct blob_attr * network_vlan
struct vlist_node node
bool proxyarp
const char * section
int sta_idx
struct vlist_tree stations
int vlan_idx
struct vlist_tree vlans
struct wireless_device * wdev
wireless_vlan
struct wireless_vlan
Definition at line 103 of file wireless.h.
Class Members
bool bridge_isolate
struct blob_attr * config
struct blob_attr * data
const char * ifname
bool isolate
int multicast_to_unicast
char * name
struct blob_attr * network
int network_ifindex
struct blob_attr * network_vlan
struct vlist_node node
const char * section
wireless_station
struct wireless_station
Definition at line 121 of file wireless.h.
Class Members
struct blob_attr * config
struct blob_attr * data
char * name
struct vlist_node node
const char * section
wireless_process
struct wireless_process
Definition at line 130 of file wireless.h.
Class Members
const char * exe
bool keep
struct list_head list
int pid
bool required
wireless_driver.device
struct wireless_driver.device
Definition at line 30 of file wireless.h.
Class Members
char * buf
struct uci_blob_param_list * config
wireless_driver.interface
struct wireless_driver.interface
Definition at line 30 of file wireless.h.
Class Members
char * buf
struct uci_blob_param_list * config
wireless_driver.vlan
struct wireless_driver.vlan
Definition at line 30 of file wireless.h.
Class Members
char * buf
struct uci_blob_param_list * config
wireless_driver.station
struct wireless_driver.station
Definition at line 30 of file wireless.h.
Class Members
char * buf
struct uci_blob_param_list * config
Function Documentation
wireless_check_network_enabled()
void wireless_check_network_enabled (void)
Definition at line 1661 of file wireless.c.
{
    struct wireless_device *wdev;
    vlist_for_each_element(&wireless_devices, wdev, node) {
        wdev_check_network_enabled(wdev);
        if (wdev->config_update)
            wireless_start_pending(1000);
    }
}
References wireless_device::config_update, vlist_for_each_element, wdev_check_network_enabled(), wireless_devices, and wireless_start_pending().
Referenced by interface_set_down(), and interface_set_up().
wireless_device_create()
void wireless_device_create (struct wireless_driver * drv, const char * name, struct blob_attr * data)
Definition at line 1105 of file wireless.c.
{
    struct wireless_device *wdev;
    char *name_buf;
    struct blob_attr *tb[__WDEV_ATTR_MAX];
    struct blob_attr *cur;
    blobmsg_parse_attr(wdev_policy, __WDEV_ATTR_MAX, tb, data);
    wdev = calloc_a(sizeof(*wdev), &name_buf, strlen(name) + 1);
    cur = tb[WDEV_ATTR_DISABLED];
    wdev->disabled = cur && blobmsg_get_bool(cur);
    wdev->drv = drv;
    wdev->state = IFS_DOWN;
    wdev->config_state = IFC_NORMAL;
    wdev->name = strcpy(name_buf, name);
    wdev->config = data;
    wdev->handler_pending = false;
    cur = tb[WDEV_ATTR_SERIALIZE];
    wdev->serialize = cur && blobmsg_get_bool(cur);
    cur = tb[WDEV_ATTR_RECONF];
    wdev->reconf = !cur || blobmsg_get_bool(cur);
    wdev->retry_setup_failed = false;
    wdev->autostart = true;
    INIT_LIST_HEAD(&wdev->script_proc);
    vlist_init(&wdev->interfaces, avl_strcmp, vif_update);
    wdev->interfaces.keep_old = true;
    wdev->timeout.cb = wireless_device_setup_timeout;
    wdev->script_task.cb = wireless_device_script_task_cb;
    wdev->script_task.dir_fd = drv_fd;
    wdev->script_task.log_prefix = wdev->name;
    wdev->script_proc_fd.fd = -1;
    wdev->script_proc_fd.cb = wireless_proc_poll_fd;
    wdev->script_check.cb = wireless_device_check_script_tasks;
    vlist_add(&wireless_devices, &wdev->node, wdev->name);
}
References __WDEV_ATTR_MAX, wireless_device::autostart, avl_strcmp(), blobmsg_get_bool(), blobmsg_parse_attr(), calloc_a, netifd_process::cb, uloop_fd::cb, uloop_timeout::cb, wireless_device::config, wireless_device::config_state, blob_attr::data, netifd_process::dir_fd, wireless_device::disabled, wireless_device::drv, drv_fd, uloop_fd::fd, wireless_device::handler_pending, IFC_NORMAL, IFS_DOWN, INIT_LIST_HEAD(), wireless_device::interfaces, vlist_tree::keep_old, netifd_process::log_prefix, wireless_device::name, wireless_device::node, wireless_device::reconf, wireless_device::retry_setup_failed, wireless_device::script_check, wireless_device::script_proc, wireless_device::script_proc_fd, wireless_device::script_task, wireless_device::serialize, wireless_device::state, wireless_device::timeout, vif_update(), vlist_add(), vlist_init(), WDEV_ATTR_DISABLED, WDEV_ATTR_RECONF, WDEV_ATTR_SERIALIZE, wdev_policy, wireless_device_check_script_tasks(), wireless_device_script_task_cb(), wireless_device_setup_timeout(), wireless_devices, and wireless_proc_poll_fd().
Referenced by config_parse_wireless_device().
wireless_device_get_validate()
void wireless_device_get_validate (struct wireless_device * wdev, struct blob_buf * b)
Definition at line 1325 of file wireless.c.
{
    struct uci_blob_param_list *p;
    void *c, *d;
    int i;
    c = blobmsg_open_table(b, wdev->name);
    d = blobmsg_open_table(b, "device");
    p = wdev->drv->device.config;
    for (i = 0; i < p->n_params; i++)
        blobmsg_add_string(b, p->params[i].name, uci_get_validate_string(p, i));
    blobmsg_close_table(b, d);
    d = blobmsg_open_table(b, "interface");
    p = wdev->drv->interface.config;
    for (i = 0; i < p->n_params; i++)
        blobmsg_add_string(b, p->params[i].name, uci_get_validate_string(p, i));
    blobmsg_close_table(b, d);
    blobmsg_close_table(b, c);
}
References b, blobmsg_add_string(), blobmsg_close_table(), blobmsg_open_table(), wireless_driver::device, wireless_device::drv, wireless_driver::interface, wireless_device::name, and uci_get_validate_string().
Referenced by netifd_handle_wdev_get_validate().
wireless_device_hotplug_event()
void wireless_device_hotplug_event (const char * name, bool add)
Definition at line 1673 of file wireless.c.
{
    struct wireless_interface *vif;
    struct wireless_device *wdev;
    const char *s;
    size_t len;
    s = strstr(name, ".sta");
    if (s) {
        if (strchr(s + 4, '.'))
            return;
        len = s - name;
    } else {
        len = strlen(name);
    }
    vlist_for_each_element(&wireless_devices, wdev, node) {
        vlist_for_each_element(&wdev->interfaces, vif, node) {
            if (!vif->ifname)
                continue;
            if (strlen(vif->ifname) != len ||
                strncmp(vif->ifname, name, len) != 0)
                continue;
            wireless_interface_handle_link(vif, name, add);
        }
    }
}
References wireless_interface::ifname, wireless_device::interfaces, wireless_device::name, vlist_for_each_element, wireless_devices, and wireless_interface_handle_link().
Referenced by device_hotplug_event().
wireless_device_notify()
int wireless_device_notify (struct wireless_device * wdev, struct blob_attr * data, struct ubus_request_data * req)
Definition at line 1510 of file wireless.c.
{
    enum {
        NOTIFY_ATTR_COMMAND,
        NOTIFY_ATTR_VIF,
        NOTIFY_ATTR_VLAN,
        NOTIFY_ATTR_DATA,
        __NOTIFY_MAX,
    };
    static const struct blobmsg_policy notify_policy[__NOTIFY_MAX] = {
        [NOTIFY_ATTR_COMMAND] = { .name = "command", .type = BLOBMSG_TYPE_INT32 },
        [NOTIFY_ATTR_VIF] = { .name = "interface", .type = BLOBMSG_TYPE_STRING },
        [NOTIFY_ATTR_VLAN] = { .name = "vlan", .type = BLOBMSG_TYPE_STRING },
        [NOTIFY_ATTR_DATA] = { .name = "data", .type = BLOBMSG_TYPE_TABLE },
    };
    struct wireless_interface *vif = NULL;
    struct wireless_vlan *vlan = NULL;
    struct blob_attr *tb[__NOTIFY_MAX];
    struct blob_attr *cur, **pdata;
    blobmsg_parse_attr(notify_policy, __NOTIFY_MAX, tb, data);
    if (!tb[NOTIFY_ATTR_COMMAND])
        return UBUS_STATUS_INVALID_ARGUMENT;
    if ((cur = tb[NOTIFY_ATTR_VIF]) != NULL) {
        vif = vlist_find(&wdev->interfaces, blobmsg_data(cur), vif, node);
        if (!vif)
            return UBUS_STATUS_NOT_FOUND;
    }
    if ((cur = tb[NOTIFY_ATTR_VLAN]) != NULL) {
        if (!vif)
            return UBUS_STATUS_NOT_FOUND;
        vlan = vlist_find(&vif->vlans, blobmsg_data(cur), vlan, node);
        if (!vlan)
            return UBUS_STATUS_NOT_FOUND;
    }
    cur = tb[NOTIFY_ATTR_DATA];
    if (!cur)
        return UBUS_STATUS_INVALID_ARGUMENT;
    switch (blobmsg_get_u32(tb[NOTIFY_ATTR_COMMAND])) {
    case NOTIFY_CMD_UP:
        if (vif || vlan)
            return UBUS_STATUS_INVALID_ARGUMENT;
        if (wdev->state != IFS_SETUP)
            return UBUS_STATUS_PERMISSION_DENIED;
        wireless_device_mark_up(wdev);
        break;
    case NOTIFY_CMD_SET_DATA:
        if (vlan)
            pdata = &vlan->data;
        else if (vif)
            pdata = &vif->data;
        else
            pdata = &wdev->data;
        free(*pdata);
        *pdata = blob_memdup(cur);
        if (vlan)
            wireless_vlan_set_data(vlan);
        else if (vif)
            wireless_interface_set_data(vif);
        wdev_prepare_prev_config(wdev);
        break;
    case NOTIFY_CMD_PROCESS_ADD:
        return wireless_device_add_process(wdev, cur);
    case NOTIFY_CMD_PROCESS_KILL_ALL:
        return wireless_device_process_kill_all(wdev, cur, req);
    case NOTIFY_CMD_SET_RETRY:
        return wireless_device_set_retry(wdev, cur);
    default:
        return UBUS_STATUS_INVALID_ARGUMENT;
    }
    return 0;
}
References blob_memdup(), blobmsg_data(), blobmsg_get_u32(), blobmsg_parse_attr(), BLOBMSG_TYPE_INT32, BLOBMSG_TYPE_STRING, BLOBMSG_TYPE_TABLE, blob_attr::data, wireless_device::data, wireless_interface::data, wireless_vlan::data, IFS_SETUP, wireless_device::interfaces, NOTIFY_CMD_PROCESS_ADD, NOTIFY_CMD_PROCESS_KILL_ALL, NOTIFY_CMD_SET_DATA, NOTIFY_CMD_SET_RETRY, NOTIFY_CMD_UP, wireless_device::state, UBUS_STATUS_INVALID_ARGUMENT, UBUS_STATUS_NOT_FOUND, UBUS_STATUS_PERMISSION_DENIED, wireless_interface::vlans, vlist_find, wdev_prepare_prev_config(), wireless_device_add_process(), wireless_device_mark_up(), wireless_device_process_kill_all(), wireless_device_set_retry(), wireless_interface_set_data(), and wireless_vlan_set_data().
Referenced by netifd_handle_wdev_notify().
wireless_device_reconf()
void wireless_device_reconf (struct wireless_device * wdev)
Definition at line 631 of file wireless.c.
{
    wdev->retry = WIRELESS_SETUP_RETRY;
    wdev->autostart = true;
    __wireless_device_set_up(wdev, wdev->reconf && (wdev->state == IFS_UP));
}
References __wireless_device_set_up(), wireless_device::autostart, IFS_UP, wireless_device::reconf, wireless_device::retry, wireless_device::state, and WIRELESS_SETUP_RETRY.
Referenced by netifd_handle_wdev_reconf(), and wdev_set_config_state().
wireless_device_set_down()
void wireless_device_set_down (struct wireless_device * wdev)
Definition at line 714 of file wireless.c.
{
    wdev->retry_setup_failed = false;
    wdev->autostart = false;
    __wireless_device_set_down(wdev);
}
References __wireless_device_set_down(), wireless_device::autostart, and wireless_device::retry_setup_failed.
Referenced by netifd_handle_wdev_down().
wireless_device_set_up()
void wireless_device_set_up (struct wireless_device * wdev)
Definition at line 623 of file wireless.c.
{
    wdev->retry = WIRELESS_SETUP_RETRY;
    wdev->autostart = true;
    __wireless_device_set_up(wdev, 0);
}
References __wireless_device_set_up(), wireless_device::autostart, wireless_device::retry, and WIRELESS_SETUP_RETRY.
Referenced by netifd_handle_wdev_up().
wireless_device_status()
void wireless_device_status (struct wireless_device * wdev, struct blob_buf * b)
Definition at line 1303 of file wireless.c.
{
    struct wireless_interface *iface;
    void *c, *i;
    c = blobmsg_open_table(b, wdev->name);
    blobmsg_add_u8(b, "up", wdev->state == IFS_UP);
    blobmsg_add_u8(b, "pending", wdev->state == IFS_SETUP || wdev->state == IFS_TEARDOWN);
    blobmsg_add_u8(b, "autostart", wdev->autostart);
    blobmsg_add_u8(b, "disabled", wdev->disabled);
    blobmsg_add_u8(b, "retry_setup_failed", wdev->retry_setup_failed);
    put_container(b, wdev->config, "config");
    i = blobmsg_open_array(b, "interfaces");
    vlist_for_each_element(&wdev->interfaces, iface, node)
        wireless_interface_status(iface, b);
    blobmsg_close_array(b, i);
    blobmsg_close_table(b, c);
}
References wireless_device::autostart, b, blobmsg_add_u8(), blobmsg_close_array(), blobmsg_close_table(), blobmsg_open_array(), blobmsg_open_table(), wireless_device::config, wireless_device::disabled, IFS_SETUP, IFS_TEARDOWN, IFS_UP, wireless_device::interfaces, wireless_device::name, put_container(), wireless_device::retry_setup_failed, wireless_device::state, vlist_for_each_element, wireless_interface::wdev, and wireless_interface_status().
Referenced by netifd_handle_wdev_status().
wireless_init()
void wireless_init (void)
Definition at line 849 of file wireless.c.
{
    vlist_init(&wireless_devices, avl_strcmp, wdev_update);
    wireless_devices.keep_old = true;
    wireless_devices.no_delete = true;
    avl_init(&wireless_drivers, avl_strcmp, false, NULL);
    drv_fd = netifd_open_subdir("wireless");
    if (drv_fd < 0)
        return;
    netifd_init_script_handlers(drv_fd, wireless_add_handler);
}
References avl_init(), avl_strcmp(), drv_fd, vlist_tree::keep_old, netifd_init_script_handlers(), netifd_open_subdir(), vlist_tree::no_delete, vlist_init(), wdev_update(), wireless_add_handler(), wireless_devices, and wireless_drivers.
Referenced by main().
wireless_interface_create()
struct wireless_interface * wireless_interface_create (struct wireless_device * wdev, struct blob_attr * data, const char * section)
Definition at line 1233 of file wireless.c.
{
    struct wireless_interface *vif;
    struct blob_attr *tb[__VIF_ATTR_MAX];
    struct blob_attr *cur;
    char *name_buf;
    char name[8];
    blobmsg_parse_attr(vif_policy, __VIF_ATTR_MAX, tb, data);
    cur = tb[VIF_ATTR_DISABLED];
    if (cur && blobmsg_get_bool(cur))
        return NULL;
    sprintf(name, "%d", wdev->vif_idx++);
    vif = calloc_a(sizeof(*vif),
               &name_buf, strlen(name) + 1);
    vif->name = strcpy(name_buf, name);
    vif->wdev = wdev;
    vif->config = data;
    vif->section = section;
    vif->isolate = false;
    vlist_init(&vif->vlans, avl_strcmp, vlan_update);
    vif->vlans.keep_old = true;
    vlist_init(&vif->stations, avl_strcmp, station_update);
    vif->stations.keep_old = true;
    vlist_add(&wdev->interfaces, &vif->node, vif->name);
    vif = vlist_find(&wdev->interfaces, name, vif, node);
    if (!vif)
        return NULL;
    vif->vlan_idx = vif->sta_idx = 0;
    vlist_update(&vif->vlans);
    vlist_update(&vif->stations);
    return vif;
}
References __VIF_ATTR_MAX, avl_strcmp(), blobmsg_get_bool(), blobmsg_parse_attr(), calloc_a, wireless_interface::config, blob_attr::data, wireless_device::interfaces, wireless_interface::isolate, vlist_tree::keep_old, wireless_interface::name, wireless_interface::node, wireless_interface::section, wireless_interface::sta_idx, station_update(), wireless_interface::stations, VIF_ATTR_DISABLED, wireless_device::vif_idx, vif_policy, wireless_interface::vlan_idx, vlan_update(), wireless_interface::vlans, vlist_add(), vlist_find, vlist_init(), vlist_update(), and wireless_interface::wdev.
Referenced by config_init_procd_wireless_interface(), and config_parse_wireless_interface().
wireless_start_pending()
void wireless_start_pending (int timeout)
Definition at line 1646 of file wireless.c.
{
    static struct uloop_timeout timer = {
        .cb = __wireless_start_pending
    };
    if (timeout) {
        uloop_timeout_set(&timer, timeout);
        return;
    }
    uloop_timeout_cancel(&timer);
    timer.cb(&timer);
}
References __wireless_start_pending(), uloop_timeout::cb, timeout, uloop_timeout_cancel(), and uloop_timeout_set().
Referenced by config_init_all(), and wireless_check_network_enabled().
wireless_station_create()
void wireless_station_create (struct wireless_interface * vif, struct blob_attr * data, const char * section)
Definition at line 1153 of file wireless.c.
{
    struct wireless_station *sta;
    struct blob_attr *tb[__STA_ATTR_MAX];
    struct blob_attr *cur;
    char *name_buf;
    char name[8];
    blobmsg_parse_attr(sta_policy, __STA_ATTR_MAX, tb, data);
    cur = tb[STA_ATTR_DISABLED];
    if (cur && blobmsg_get_bool(cur))
        return;
    sprintf(name, "%d", vif->sta_idx++);
    sta = calloc_a(sizeof(*sta),
               &name_buf, strlen(name) + 1);
    sta->name = strcpy(name_buf, name);
    sta->config = data;
    sta->section = section;
    vlist_add(&vif->stations, &sta->node, sta->name);
}
References __STA_ATTR_MAX, blobmsg_get_bool(), blobmsg_parse_attr(), calloc_a, wireless_station::config, blob_attr::data, wireless_station::name, wireless_station::node, wireless_station::section, STA_ATTR_DISABLED, wireless_interface::sta_idx, sta_policy, wireless_interface::stations, and vlist_add().
Referenced by config_init_procd_wireless_interface(), and config_parse_wireless_station().
wireless_vlan_create()
void wireless_vlan_create (struct wireless_interface * vif, struct blob_attr * data, const char * section)
Definition at line 1193 of file wireless.c.
{
    struct wireless_vlan *vlan;
    struct blob_attr *tb[__VLAN_ATTR_MAX];
    struct blob_attr *cur;
    char *name_buf;
    char name[8];
    blobmsg_parse_attr(vlan_policy, __VLAN_ATTR_MAX, tb, data);
    cur = tb[VLAN_ATTR_DISABLED];
    if (cur && blobmsg_get_bool(cur))
        return;
    sprintf(name, "%d", vif->vlan_idx++);
    vlan = calloc_a(sizeof(*vlan), &name_buf, strlen(name) + 1);
    vlan->name = strcpy(name_buf, name);
    vlan->config = data;
    vlan->section = section;
    vlist_add(&vif->vlans, &vlan->node, vlan->name);
}
References __VLAN_ATTR_MAX, blobmsg_get_bool(), blobmsg_parse_attr(), calloc_a, wireless_vlan::config, blob_attr::data, wireless_vlan::name, wireless_vlan::node, wireless_vlan::section, VLAN_ATTR_DISABLED, wireless_interface::vlan_idx, vlan_policy, wireless_interface::vlans, and vlist_add().
Referenced by config_init_procd_wireless_interface(), and config_parse_wireless_vlan().
Variable Documentation
wireless_devices
struct vlist_tree wireless_devices extern
Definition at line 37 of file wireless.c.
Referenced by __wireless_start_pending(), config_init_procd_wireless_interface(), config_init_wireless(), get_wdev(), netifd_handle_wdev_down(), netifd_handle_wdev_get_validate(), netifd_handle_wdev_reconf(), netifd_handle_wdev_status(), netifd_handle_wdev_up(), wireless_check_network_enabled(), wireless_device_create(), wireless_device_free(), wireless_device_hotplug_event(), and wireless_init().
wireless_drivers
struct avl_tree wireless_drivers extern
Definition at line 38 of file wireless.c.
Referenced by config_parse_wireless_device(), wireless_add_handler(), and wireless_init().