zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/jail/seccomp.h File Reference
seccomp.h File Reference
#include <stdio.h>
#include <syslog.h>
Functions
int install_syscall_filter (const char *argv, const char *file)
Function Documentation
install_syscall_filter()
int install_syscall_filter (const char * argv, const char * file)
Definition at line 25 of file seccomp.c.
{
    struct blob_buf b = { 0 };
    struct sock_fprog *prog = NULL;
    DEBUG("%s: setting up syscall filter\n", argv);
    blob_buf_init(&b, 0);
    if (!blobmsg_add_json_from_file(&b, file)) {
        ERROR("%s: failed to load %s\n", argv, file);
        return -1;
    }
    prog = parseOCIlinuxseccomp(b.head);
    if (!prog) {
        ERROR("%s: failed to parse seccomp filter rules %s\n", argv, file);
        return -1;
    }
    return applyOCIlinuxseccomp(prog);
}
References applyOCIlinuxseccomp(), b, blob_buf_init(), blobmsg_add_json_from_file(), DEBUG, ERROR, blob_buf::head, and parseOCIlinuxseccomp().
Referenced by __preload_main__().