zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/ustp/netif_utils.c File Reference
netif_utils.c File Reference
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <stdbool.h>
#include <fcntl.h>
#include <limits.h>
#include <sys/ioctl.h>
#include <sys/types.h>
#include <net/if.h>
#include <linux/if_ether.h>
#include <linux/ethtool.h>
#include <linux/sockios.h>
#include "netif_utils.h"
#include "log.h"
Macros
#define SYSFS_CLASS_NET "/sys/class/net"
Functions
int netsock_init (void)
int get_hwaddr (char *ifname, __u8 *hwaddr)
int get_flags (char *ifname)
int if_shutdown (char *ifname)
int ethtool_get_speed_duplex (char *ifname, int *speed, int *duplex)
bool is_bridge (char *if_name)
static int get_port_file (const char *if_name, const char *file)
int get_bpdu_filter (char *if_name)
int get_bridge_portno (char *if_name)
Variables
static int netsock = -1
Macro Definition Documentation
SYSFS_CLASS_NET
#define SYSFS_CLASS_NET "/sys/class/net"
Definition at line 44 of file netif_utils.c.
Referenced by get_port_file(), and is_bridge().
Function Documentation
ethtool_get_speed_duplex()
int ethtool_get_speed_duplex (char * ifname, int * speed, int * duplex)
Definition at line 107 of file netif_utils.c.
{
    struct ifreq ifr;
    memset(&ifr, 0, sizeof(ifr));
    strncpy(ifr.ifr_name, ifname, IFNAMSIZ - 1);
    struct ethtool_cmd ecmd;
    ecmd.cmd = ETHTOOL_GSET;
    ifr.ifr_data = (caddr_t)&ecmd;
    if(0 > ioctl(netsock, SIOCETHTOOL, &ifr))
    {
        INFO("Cannot get speed/duplex for %s: %m\n", ifname);
        return -1;
    }
    *speed = ecmd.speed;   /* Ethtool speed is in Mbps */
    *duplex = ecmd.duplex; /* We have same convention as ethtool.
                               0 = half, 1 = full */
    return 0;
}
References ifname, INFO, and netsock.
Referenced by set_if_up().
get_bpdu_filter()
int get_bpdu_filter (char * if_name)
Definition at line 175 of file netif_utils.c.
{
    return get_port_file(if_name, "bpdu_filter");
}
References get_port_file().
Referenced by set_if_up().
get_bridge_portno()
int get_bridge_portno (char * if_name)
Definition at line 180 of file netif_utils.c.
{
    return get_port_file(if_name, "port_no");
}
References get_port_file().
Referenced by create_if().
get_flags()
int get_flags (char * ifname)
Definition at line 74 of file netif_utils.c.
{
    struct ifreq ifr;
    memset(&ifr, 0, sizeof(ifr));
    strncpy(ifr.ifr_name, ifname, IFNAMSIZ - 1);
    if(0 > ioctl(netsock, SIOCGIFFLAGS, &ifr))
    {
        ERROR("%s: get interface flags failed: %m", ifname);
        return -1;
    }
    return ifr.ifr_flags;
}
References ERROR, ifname, and netsock.
Referenced by if_shutdown().
get_hwaddr()
int get_hwaddr (char * ifname, __u8 * hwaddr)
Definition at line 60 of file netif_utils.c.
{
    struct ifreq ifr;
    memset(&ifr, 0, sizeof(ifr));
    strncpy(ifr.ifr_name, ifname, IFNAMSIZ - 1);
    if(0 > ioctl(netsock, SIOCGIFHWADDR, &ifr))
    {
        ERROR("%s: get hw address failed: %m", ifname);
        return -1;
    }
    memcpy(hwaddr, ifr.ifr_hwaddr.sa_data, ETH_ALEN);
    return 0;
}
References ERROR, ifname, and netsock.
Referenced by check_mac_address(), create_br(), and create_if().
get_port_file()
static int get_port_file (const char * if_name, const char * file) static
Definition at line 137 of file netif_utils.c.
{
    char path[32 + IFNAMSIZ];
    sprintf(path, SYSFS_CLASS_NET "/%s/brport/%s", if_name, file);
    char buf[128];
    int fd;
    long res = -1;
    TSTM((fd = open(path, O_RDONLY)) >= 0, -1, "%m");
    int l;
    if((l = read(fd, buf, sizeof(buf) - 1)) < 0) {
        ERROR("Failed to read file %s: error %m", file);
        return -1;
    }
    if(0 == l)
    {
        ERROR("Empty %s file", file);
        goto out;
    }
    else if((sizeof(buf) - 1) == l)
    {
        ERROR("%s file too long", file);
        goto out;
    }
    buf[l] = 0;
    if('\n' == buf[l - 1])
        buf[l - 1] = 0;
    char *end;
    res = strtoul(buf, &end, 0);
    if(0 != *end || INT_MAX < res)
    {
        ERROR("Invalid %s %s", file, buf);
        res = -1;
    }
out:
    close(fd);
    return res;
}
References buf, ERROR, path, SYSFS_CLASS_NET, and TSTM.
Referenced by get_bpdu_filter(), and get_bridge_portno().
if_shutdown()
int if_shutdown (char * ifname)
Definition at line 87 of file netif_utils.c.
{
    struct ifreq ifr;
    memset(&ifr, 0, sizeof(ifr));
    /* TODO: Let's hope -1 is not a valid flag combination */
    if(-1 == (ifr.ifr_flags = get_flags(ifname)))
    {
        return -1;
    }
    ifr.ifr_flags &= ~IFF_UP;
    strncpy(ifr.ifr_name, ifname, IFNAMSIZ - 1);
    if(0 > ioctl(netsock, SIOCSIFFLAGS, &ifr))
    {
        ERROR("%s: set if_down flag failed: %m", ifname);
        return -1;
    }
    return 0;
}
References ERROR, get_flags(), ifname, and netsock.
Referenced by MSTP_OUT_shutdown_port().
is_bridge()
bool is_bridge (char * if_name)
Definition at line 130 of file netif_utils.c.
{
    char path[32 + IFNAMSIZ];
    sprintf(path, SYSFS_CLASS_NET "/%s/bridge", if_name);
    return (0 == access(path, R_OK));
}
References path, and SYSFS_CLASS_NET.
Referenced by dump_msg().
netsock_init()
int netsock_init (void)
Definition at line 49 of file netif_utils.c.
{
    netsock = socket(AF_INET, SOCK_DGRAM, 0);
    if(0 > netsock)
    {
        ERROR("Couldn't open inet socket for ioctls: %m\n");
        return -1;
    }
    return 0;
}
References ERROR, and netsock.
Referenced by main().
Variable Documentation
netsock
int netsock = -1 static
Definition at line 47 of file netif_utils.c.
Referenced by ethtool_get_speed_duplex(), get_flags(), get_hwaddr(), if_shutdown(), and netsock_init().