zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/upgraded/upgraded.c File Reference
upgraded.c File Reference
#include <sys/reboot.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <libubox/uloop.h>
#include "../watchdog.h"
Macros
#define _GNU_SOURCE
#define O_PATH 010000000
Functions
static void upgrade_proc_cb (struct uloop_process *proc, int ret)
static void sysupgrade (char *path, char *command)
int main (int argc, char **argv)
Variables
static struct uloop_process upgrade_proc
unsigned int debug = 2
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 15 of file upgraded.c.
O_PATH
#define O_PATH 010000000
Definition at line 31 of file upgraded.c.
Referenced by main().
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 66 of file upgraded.c.
{
    pid_t p = getpid();
    if (p != 1) {
        fprintf(stderr, "this tool needs to run as pid 1\n");
        return 1;
    }
    int fd = open("/", O_DIRECTORY|O_PATH);
    if (fd < 0) {
        fprintf(stderr, "unable to open prefix directory: %m\n");
        return 1;
    }
    if (chroot(".") < 0) {
        fprintf(stderr, "failed to chroot: %m\n");
        return 1;
    }
    if (fchdir(fd) == -1) {
        fprintf(stderr, "failed to chdir to prefix directory: %m\n");
        return 1;
    }
    close(fd);
    if (argc != 3) {
        fprintf(stderr, "sysupgrade stage 2 failed, invalid command line\n");
        return 1;
    }
    uloop_init();
    watchdog_init(0);
    sysupgrade(argv[1], argv[2]);
    reboot(RB_AUTOBOOT);
    return 0;
}
References O_PATH, sysupgrade(), uloop_init(), and watchdog_init().
sysupgrade()
static void sysupgrade (char * path, char * command) static
Definition at line 44 of file upgraded.c.
{
    char *args[] = { "/lib/upgrade/stage2", path, command, NULL };
    upgrade_proc.cb = upgrade_proc_cb;
    upgrade_proc.pid = fork();
    if (upgrade_proc.pid < 0) {
        fprintf(stderr, "Failed to fork sysupgrade\n");
        return;
    }
    if (!upgrade_proc.pid) {
        /* Child */
        execvp(args[0], args);
        fprintf(stderr, "Failed to exec sysupgrade\n");
        _exit(EXIT_FAILURE);
    }
    uloop_process_add(&upgrade_proc);
    uloop_run();
}
References uloop_process::cb, path, uloop_process::pid, uloop_process_add(), uloop_run(), upgrade_proc, and upgrade_proc_cb().
Referenced by main().
upgrade_proc_cb()
static void upgrade_proc_cb (struct uloop_process * proc, int ret) static
Definition at line 37 of file upgraded.c.
{
    if (ret)
        fprintf(stderr, "sysupgrade aborted with return code: %d\n", ret);
    uloop_end();
}
References uloop_end().
Referenced by sysupgrade().
Variable Documentation
debug
unsigned int debug = 2
Definition at line 35 of file upgraded.c.
upgrade_proc
struct uloop_process upgrade_proc static
Definition at line 34 of file upgraded.c.
Referenced by sysupgrade().