zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/netifd/vlandev.c File Reference
vlandev.c File Reference
#include <string.h>
#include <inttypes.h>
#include "netifd.h"
#include "device.h"
#include "interface.h"
#include "system.h"
#include "utils.h"
Classes
struct vlandev_device
Enumerations
enum {
VLANDEV_ATTR_IFNAME , VLANDEV_ATTR_VID , VLANDEV_ATTR_INGRESS_QOS_MAPPING , VLANDEV_ATTR_EGRESS_QOS_MAPPING ,
__VLANDEV_ATTR_MAX
}
Functions
static int __vlandev_hotplug_op (struct device *dev, struct device *member, struct blob_attr *vlan, bool add)
static int vlandev_hotplug_add (struct device *dev, struct device *member, struct blob_attr *vlan)
static int vlandev_hotplug_del (struct device *dev, struct device *member, struct blob_attr *vlan)
static int vlandev_hotplug_prepare (struct device *dev, struct device **bridge_dev)
static void vlandev_hotplug_check (struct vlandev_device *mvdev)
static void vlandev_base_cb (struct device_user *dev, enum device_event ev)
static int vlandev_set_down (struct vlandev_device *mvdev)
static int vlandev_set_up (struct vlandev_device *mvdev)
static int vlandev_set_state (struct device *dev, bool up)
static void vlandev_free (struct device *dev)
static void vlandev_qos_mapping_dump (struct blob_buf *b, const char *name, const struct vlist_simple_tree *qos_mapping_li)
static void vlandev_dump_info (struct device *dev, struct blob_buf *b)
static uint16_t vlandev_get_vid (struct device *dev, const char *id_str)
static void vlandev_config_init (struct device *dev)
static void vlandev_qos_mapping_list_apply (struct vlist_simple_tree *qos_mapping_li, struct blob_attr *list)
static void vlandev_apply_settings (struct vlandev_device *mvdev, struct blob_attr **tb)
static enum dev_change_type vlandev_reload (struct device *dev, struct blob_attr *attr)
static struct device * vlandev_create (const char *name, struct device_type *devtype, struct blob_attr *attr)
static void __init vlandev_device_type_init (void)
Variables
static const struct blobmsg_policy vlandev_attrs [__VLANDEV_ATTR_MAX]
static const struct uci_blob_param_list vlandev_attr_list
static struct device_type vlan8021q_device_type
static struct blob_buf b
static struct device_type vlan8021ad_device_type
Class Documentation
vlandev_device
struct vlandev_device
Definition at line 50 of file vlandev.c.
Class Members
struct vlandev_config config
struct blob_attr * config_data
struct device dev
struct blob_attr * ifname
struct device_user parent
device_state_cb set_state
struct blob_attr * vid
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
VLANDEV_ATTR_IFNAME
VLANDEV_ATTR_VID
VLANDEV_ATTR_INGRESS_QOS_MAPPING
VLANDEV_ATTR_EGRESS_QOS_MAPPING
__VLANDEV_ATTR_MAX
Definition at line 24 of file vlandev.c.
     {
    VLANDEV_ATTR_IFNAME,
    VLANDEV_ATTR_VID,
    VLANDEV_ATTR_INGRESS_QOS_MAPPING,
    VLANDEV_ATTR_EGRESS_QOS_MAPPING,
    __VLANDEV_ATTR_MAX
};
Function Documentation
__vlandev_hotplug_op()
static int __vlandev_hotplug_op (struct device * dev, struct device * member, struct blob_attr * vlan, bool add) static
Definition at line 64 of file vlandev.c.
{
    struct vlandev_device *mvdev = container_of(dev, struct vlandev_device, dev);
    void *a;
    dev = mvdev->parent.dev;
    if (!dev || !dev->hotplug_ops)
        return UBUS_STATUS_NOT_SUPPORTED;
    blob_buf_init(&b, 0);
    a = blobmsg_open_array(&b, "vlans");
    blobmsg_printf(&b, NULL, "%d:u", mvdev->config.vid);
    if (vlan && blobmsg_len(vlan))
        blob_put_raw(&b, blobmsg_data(vlan), blobmsg_len(vlan));
    blobmsg_close_array(&b, a);
    if (add)
        return dev->hotplug_ops->add(dev, member, blobmsg_data(b.head));
    else
        return dev->hotplug_ops->del(dev, member, blobmsg_data(b.head));
}
References device_hotplug_ops::add, b, blob_buf_init(), blob_put_raw(), blobmsg_close_array(), blobmsg_data(), blobmsg_len(), blobmsg_open_array(), blobmsg_printf(), vlandev_device::config, container_of, device_hotplug_ops::del, device_user::dev, vlandev_device::dev, blob_buf::head, device::hotplug_ops, vlandev_device::parent, UBUS_STATUS_NOT_SUPPORTED, and vlandev_config::vid.
Referenced by vlandev_hotplug_add(), and vlandev_hotplug_del().
vlandev_apply_settings()
static void vlandev_apply_settings (struct vlandev_device * mvdev, struct blob_attr ** tb) static
Definition at line 317 of file vlandev.c.
{
    struct vlandev_config *cfg = &mvdev->config;
    struct blob_attr *cur;
    cfg->proto = (mvdev->dev.type == &vlan8021q_device_type) ?
        VLAN_PROTO_8021Q : VLAN_PROTO_8021AD;
    vlist_simple_update(&cfg->ingress_qos_mapping_list);
    vlist_simple_update(&cfg->egress_qos_mapping_list);
    if ((cur = tb[VLANDEV_ATTR_INGRESS_QOS_MAPPING]))
        vlandev_qos_mapping_list_apply(&cfg->ingress_qos_mapping_list, cur);
    if ((cur = tb[VLANDEV_ATTR_EGRESS_QOS_MAPPING]))
        vlandev_qos_mapping_list_apply(&cfg->egress_qos_mapping_list, cur);
    vlist_simple_flush(&cfg->ingress_qos_mapping_list);
    vlist_simple_flush(&cfg->egress_qos_mapping_list);
}
References vlandev_device::config, vlandev_device::dev, vlandev_config::egress_qos_mapping_list, vlandev_config::ingress_qos_mapping_list, vlandev_config::proto, device::type, vlan8021q_device_type, VLAN_PROTO_8021AD, VLAN_PROTO_8021Q, VLANDEV_ATTR_EGRESS_QOS_MAPPING, VLANDEV_ATTR_INGRESS_QOS_MAPPING, vlandev_qos_mapping_list_apply(), vlist_simple_flush(), and vlist_simple_update().
Referenced by vlandev_reload().
vlandev_base_cb()
static void vlandev_base_cb (struct device_user * dev, enum device_event ev) static
Definition at line 130 of file vlandev.c.
{
    struct vlandev_device *mvdev = container_of(dev, struct vlandev_device, parent);
    switch (ev) {
    case DEV_EVENT_ADD:
        device_set_present(&mvdev->dev, true);
        break;
    case DEV_EVENT_REMOVE:
        device_set_present(&mvdev->dev, false);
        break;
    case DEV_EVENT_UPDATE_IFNAME:
        vlandev_hotplug_check(mvdev);
        break;
    case DEV_EVENT_TOPO_CHANGE:
        /* Propagate topo changes */
        device_broadcast_event(&mvdev->dev, DEV_EVENT_TOPO_CHANGE);
        break;
    default:
        return;
    }
}
References container_of, vlandev_device::dev, DEV_EVENT_ADD, DEV_EVENT_REMOVE, DEV_EVENT_TOPO_CHANGE, DEV_EVENT_UPDATE_IFNAME, device_broadcast_event, device_set_present, vlandev_device::parent, and vlandev_hotplug_check().
Referenced by vlandev_create().
vlandev_config_init()
static void vlandev_config_init (struct device * dev) static
Definition at line 271 of file vlandev.c.
{
    struct vlandev_device *mvdev;
    struct device *basedev = NULL;
    mvdev = container_of(dev, struct vlandev_device, dev);
    if (mvdev->ifname)
        basedev = device_get(blobmsg_data(mvdev->ifname), true);
    if (mvdev->vid)
        mvdev->config.vid = vlandev_get_vid(basedev, blobmsg_get_string(mvdev->vid));
    else
        mvdev->config.vid = 1;
    device_add_user(&mvdev->parent, basedev);
    vlandev_hotplug_check(mvdev);
}
References blobmsg_data(), blobmsg_get_string(), vlandev_device::config, container_of, device_add_user(), device_get(), vlandev_device::ifname, vlandev_device::parent, vlandev_config::vid, vlandev_device::vid, vlandev_get_vid(), and vlandev_hotplug_check().
Referenced by vlandev_reload().
vlandev_create()
static struct device * vlandev_create (const char * name, struct device_type * devtype, struct blob_attr * attr) static
Definition at line 384 of file vlandev.c.
{
    struct vlandev_device *mvdev;
    struct device *dev = NULL;
    mvdev = calloc(1, sizeof(*mvdev));
    if (!mvdev)
        return NULL;
    vlist_simple_init(&mvdev->config.ingress_qos_mapping_list,
              struct vlan_qos_mapping, node);
    vlist_simple_init(&mvdev->config.egress_qos_mapping_list,
              struct vlan_qos_mapping, node);
    dev = &mvdev->dev;
    if (device_init(dev, devtype, name) < 0) {
        device_cleanup(dev);
        free(mvdev);
        return NULL;
    }
    dev->config_pending = true;
    mvdev->set_state = dev->set_state;
    dev->set_state = vlandev_set_state;
    dev->hotplug_ops = NULL;
    mvdev->parent.cb = vlandev_base_cb;
    vlandev_reload(dev, attr);
    return dev;
}
References device_user::cb, vlandev_device::config, device::config_pending, vlandev_device::dev, device_cleanup(), device_init(), vlandev_config::egress_qos_mapping_list, device::hotplug_ops, vlandev_config::ingress_qos_mapping_list, vlandev_device::parent, device::set_state, vlandev_device::set_state, vlandev_base_cb(), vlandev_reload(), vlandev_set_state(), and vlist_simple_init.
vlandev_device_type_init()
static void __init vlandev_device_type_init (void) static
Definition at line 440 of file vlandev.c.
{
    device_type_add(&vlan8021ad_device_type);
    device_type_add(&vlan8021q_device_type);
}
References device_type_add(), vlan8021ad_device_type, and vlan8021q_device_type.
vlandev_dump_info()
static void vlandev_dump_info (struct device * dev, struct blob_buf * b) static
Definition at line 236 of file vlandev.c.
{
    struct vlandev_device *mvdev;
    mvdev = container_of(dev, struct vlandev_device, dev);
    blobmsg_add_string(b, "parent", mvdev->parent.dev->ifname);
    system_if_dump_info(dev, b);
    blobmsg_add_u32(b, "vid", mvdev->config.vid);
    vlandev_qos_mapping_dump(b, "ingress_qos_mapping", &mvdev->config.ingress_qos_mapping_list);
    vlandev_qos_mapping_dump(b, "egress_qos_mapping", &mvdev->config.egress_qos_mapping_list);
}
References b, blobmsg_add_string(), blobmsg_add_u32(), vlandev_device::config, container_of, device_user::dev, vlandev_device::dev, vlandev_config::egress_qos_mapping_list, device::ifname, vlandev_config::ingress_qos_mapping_list, vlandev_device::parent, system_if_dump_info(), vlandev_config::vid, and vlandev_qos_mapping_dump().
vlandev_free()
static void vlandev_free (struct device * dev) static
Definition at line 204 of file vlandev.c.
{
    struct vlandev_device *mvdev;
    mvdev = container_of(dev, struct vlandev_device, dev);
    device_remove_user(&mvdev->parent);
    free(mvdev->config_data);
    vlist_simple_flush_all(&mvdev->config.ingress_qos_mapping_list);
    vlist_simple_flush_all(&mvdev->config.egress_qos_mapping_list);
    free(mvdev);
}
References vlandev_device::config, vlandev_device::config_data, container_of, vlandev_device::dev, device_remove_user(), vlandev_config::egress_qos_mapping_list, vlandev_config::ingress_qos_mapping_list, vlandev_device::parent, and vlist_simple_flush_all().
vlandev_get_vid()
static uint16_t vlandev_get_vid (struct device * dev, const char * id_str) static
Definition at line 249 of file vlandev.c.
{
    unsigned long id;
    uint16_t *alias_id;
    char *err;
    id = strtoul(id_str, &err, 10);
    if (err && *err) {
        if (!dev)
            return 1;
        alias_id = kvlist_get(&dev->vlan_aliases, id_str);
        if (!alias_id)
            return 1;
        id = *alias_id;
    }
    return (uint16_t)id;
}
References vlandev_device::dev, err, id, kvlist_get(), and device::vlan_aliases.
Referenced by vlandev_config_init().
vlandev_hotplug_add()
static int vlandev_hotplug_add (struct device * dev, struct device * member, struct blob_attr * vlan) static
Definition at line 87 of file vlandev.c.
{
    return __vlandev_hotplug_op(dev, member, vlan, true);
}
References __vlandev_hotplug_op(), and vlandev_device::dev.
Referenced by vlandev_hotplug_check().
vlandev_hotplug_check()
static void vlandev_hotplug_check (struct vlandev_device * mvdev) static
Definition at line 110 of file vlandev.c.
{
    static const struct device_hotplug_ops hotplug_ops = {
        .prepare = vlandev_hotplug_prepare,
        .add = vlandev_hotplug_add,
        .del = vlandev_hotplug_del
    };
    struct device *dev = mvdev->parent.dev;
    if (!dev || !dev->hotplug_ops || avl_is_empty(&dev->vlans.avl) ||
        mvdev->dev.type != &vlan8021q_device_type) {
        mvdev->dev.hotplug_ops = NULL;
        return;
    }
    mvdev->dev.hotplug_ops = &hotplug_ops;
}
References vlist_tree::avl, avl_is_empty(), device_user::dev, vlandev_device::dev, device::hotplug_ops, vlandev_device::parent, device::type, vlan8021q_device_type, vlandev_hotplug_add(), vlandev_hotplug_del(), vlandev_hotplug_prepare(), and device::vlans.
Referenced by vlandev_base_cb(), and vlandev_config_init().
vlandev_hotplug_del()
static int vlandev_hotplug_del (struct device * dev, struct device * member, struct blob_attr * vlan) static
Definition at line 93 of file vlandev.c.
{
    return __vlandev_hotplug_op(dev, member, vlan, false);
}
References __vlandev_hotplug_op(), and vlandev_device::dev.
Referenced by vlandev_hotplug_check().
vlandev_hotplug_prepare()
static int vlandev_hotplug_prepare (struct device * dev, struct device ** bridge_dev) static
Definition at line 99 of file vlandev.c.
{
    struct vlandev_device *mvdev = container_of(dev, struct vlandev_device, dev);
    dev = mvdev->parent.dev;
    if (!dev || !dev->hotplug_ops)
        return UBUS_STATUS_NOT_SUPPORTED;
    return dev->hotplug_ops->prepare(dev, bridge_dev);
}
References container_of, device_user::dev, vlandev_device::dev, device::hotplug_ops, vlandev_device::parent, device_hotplug_ops::prepare, and UBUS_STATUS_NOT_SUPPORTED.
Referenced by vlandev_hotplug_check().
vlandev_qos_mapping_dump()
static void vlandev_qos_mapping_dump (struct blob_buf * b, const char * name, const struct vlist_simple_tree * qos_mapping_li) static
Definition at line 216 of file vlandev.c.
{
    const struct vlan_qos_mapping *elem;
    void *a, *t;
    a = blobmsg_open_array(b, name);
    vlist_simple_for_each_element(qos_mapping_li, elem, node) {
        t = blobmsg_open_table(b, NULL);
        blobmsg_add_u32(b, "from", elem->from);
        blobmsg_add_u32(b, "to", elem->to);
        blobmsg_close_table(b, t);
    }
    blobmsg_close_array(b, a);
}
References b, blobmsg_add_u32(), blobmsg_close_array(), blobmsg_close_table(), blobmsg_open_array(), blobmsg_open_table(), vlan_qos_mapping::from, vlan_qos_mapping::to, and vlist_simple_for_each_element.
Referenced by vlandev_dump_info().
vlandev_qos_mapping_list_apply()
static void vlandev_qos_mapping_list_apply (struct vlist_simple_tree * qos_mapping_li, struct blob_attr * list) static
Definition at line 289 of file vlandev.c.
{
    struct blob_attr *cur;
    struct vlan_qos_mapping *qos_mapping;
    size_t rem;
    int rc;
    blobmsg_for_each_attr(cur, list, rem) {
        if (blobmsg_type(cur) != BLOBMSG_TYPE_STRING)
            continue;
        if (!blobmsg_check_attr(cur, false))
            continue;
        qos_mapping = calloc(1, sizeof(*qos_mapping));
        if (!qos_mapping)
            continue;
        rc = sscanf(blobmsg_data(cur), "%" PRIu32 ":%" PRIu32, &qos_mapping->from, &qos_mapping->to);
        if (rc != 2) {
            free(qos_mapping);
            continue;
        }
        vlist_simple_add(qos_mapping_li, &qos_mapping->node);
    }
}
References blobmsg_check_attr(), blobmsg_data(), blobmsg_for_each_attr, BLOBMSG_TYPE_STRING, vlan_qos_mapping::from, vlan_qos_mapping::node, rc(), vlan_qos_mapping::to, and vlist_simple_add().
Referenced by vlandev_apply_settings().
vlandev_reload()
static enum dev_change_type vlandev_reload (struct device * dev, struct blob_attr * attr) static
Definition at line 339 of file vlandev.c.
{
    struct blob_attr *tb_dev[__DEV_ATTR_MAX];
    struct blob_attr *tb_mv[__VLANDEV_ATTR_MAX];
    enum dev_change_type ret = DEV_CONFIG_APPLIED;
    struct vlandev_device *mvdev;
    mvdev = container_of(dev, struct vlandev_device, dev);
    attr = blob_memdup(attr);
    blobmsg_parse(device_attr_list.params, __DEV_ATTR_MAX, tb_dev,
        blob_data(attr), blob_len(attr));
    blobmsg_parse(vlandev_attrs, __VLANDEV_ATTR_MAX, tb_mv,
        blob_data(attr), blob_len(attr));
    device_init_settings(dev, tb_dev);
    vlandev_apply_settings(mvdev, tb_mv);
    mvdev->ifname = tb_mv[VLANDEV_ATTR_IFNAME];
    mvdev->vid = tb_mv[VLANDEV_ATTR_VID];
    if (mvdev->config_data) {
        struct blob_attr *otb_dev[__DEV_ATTR_MAX];
        struct blob_attr *otb_mv[__VLANDEV_ATTR_MAX];
        blobmsg_parse(device_attr_list.params, __DEV_ATTR_MAX, otb_dev,
            blob_data(mvdev->config_data), blob_len(mvdev->config_data));
        if (uci_blob_diff(tb_dev, otb_dev, &device_attr_list, NULL))
            ret = DEV_CONFIG_RESTART;
        blobmsg_parse(vlandev_attrs, __VLANDEV_ATTR_MAX, otb_mv,
            blob_data(mvdev->config_data), blob_len(mvdev->config_data));
        if (uci_blob_diff(tb_mv, otb_mv, &vlandev_attr_list, NULL))
            ret = DEV_CONFIG_RESTART;
        vlandev_config_init(dev);
    }
    free(mvdev->config_data);
    mvdev->config_data = attr;
    return ret;
}
References __DEV_ATTR_MAX, __VLANDEV_ATTR_MAX, blob_data(), blob_len(), blob_memdup(), blobmsg_parse(), vlandev_device::config_data, container_of, vlandev_device::dev, DEV_CONFIG_APPLIED, DEV_CONFIG_RESTART, device_attr_list, device_init_settings(), vlandev_device::ifname, vlandev_device::vid, vlandev_apply_settings(), VLANDEV_ATTR_IFNAME, vlandev_attr_list, VLANDEV_ATTR_VID, vlandev_attrs, and vlandev_config_init().
Referenced by vlandev_create().
vlandev_set_down()
static int vlandev_set_down (struct vlandev_device * mvdev) static
Definition at line 154 of file vlandev.c.
{
    mvdev->set_state(&mvdev->dev, false);
    system_vlandev_del(&mvdev->dev);
    device_release(&mvdev->parent);
    return 0;
}
References vlandev_device::dev, device_release(), vlandev_device::parent, vlandev_device::set_state, and system_vlandev_del().
Referenced by vlandev_set_state().
vlandev_set_state()
static int vlandev_set_state (struct device * dev, bool up) static
Definition at line 190 of file vlandev.c.
{
    struct vlandev_device *mvdev;
    D(SYSTEM, "vlandev_set_state(%s, %u)", dev->ifname, up);
    mvdev = container_of(dev, struct vlandev_device, dev);
    if (up)
        return vlandev_set_up(mvdev);
    else
        return vlandev_set_down(mvdev);
}
References container_of, D, vlandev_device::dev, device::ifname, vlandev_set_down(), and vlandev_set_up().
Referenced by vlandev_create().
vlandev_set_up()
static int vlandev_set_up (struct vlandev_device * mvdev) static
Definition at line 164 of file vlandev.c.
{
    int ret;
    ret = device_claim(&mvdev->parent);
    if (ret < 0)
        return ret;
    ret = system_vlandev_add(&mvdev->dev, mvdev->parent.dev, &mvdev->config);
    if (ret < 0)
        goto release;
    ret = mvdev->set_state(&mvdev->dev, true);
    if (ret)
        goto delete;
    return 0;
delete:
    system_vlandev_del(&mvdev->dev);
release:
    device_release(&mvdev->parent);
    return ret;
}
References vlandev_device::config, device_user::dev, vlandev_device::dev, device_claim(), device_release(), vlandev_device::parent, vlandev_device::set_state, system_vlandev_add(), and system_vlandev_del().
Referenced by vlandev_set_state().
Variable Documentation
b
struct blob_buf b static
Definition at line 48 of file vlandev.c.
Referenced by __vlandev_hotplug_op(), vlandev_dump_info(), and vlandev_qos_mapping_dump().
vlan8021ad_device_type
struct device_type vlan8021ad_device_type static
Initial value:
= {
    .name = "8021ad",
    .config_params = &vlandev_attr_list,
    .create = vlandev_create,
    .config_init = vlandev_config_init,
    .reload = vlandev_reload,
    .free = vlandev_free,
    .dump_info = vlandev_dump_info,
}
Definition at line 420 of file vlandev.c.
{
    .name = "8021ad",
    .config_params = &vlandev_attr_list,
    .create = vlandev_create,
    .config_init = vlandev_config_init,
    .reload = vlandev_reload,
    .free = vlandev_free,
    .dump_info = vlandev_dump_info,
};
Referenced by vlandev_device_type_init().
vlan8021q_device_type
static struct device_type vlan8021q_device_type static
Initial value:
= {
    .name = "8021q",
    .config_params = &vlandev_attr_list,
    .create = vlandev_create,
    .config_init = vlandev_config_init,
    .reload = vlandev_reload,
    .free = vlandev_free,
    .dump_info = vlandev_dump_info,
}
Definition at line 47 of file vlandev.c.
Referenced by vlandev_apply_settings(), vlandev_device_type_init(), and vlandev_hotplug_check().
vlandev_attr_list
const struct uci_blob_param_list vlandev_attr_list static
Initial value:
= {
    .n_params = __VLANDEV_ATTR_MAX,
    .params = vlandev_attrs,
    .n_next = 1,
    .next = { &device_attr_list },
}
Definition at line 39 of file vlandev.c.
{
    .n_params = __VLANDEV_ATTR_MAX,
    .params = vlandev_attrs,
    .n_next = 1,
    .next = { &device_attr_list },
};
Referenced by vlandev_reload().
vlandev_attrs
const struct blobmsg_policy vlandev_attrs[__VLANDEV_ATTR_MAX] static
Initial value:
= {
    [VLANDEV_ATTR_IFNAME] = { "ifname", BLOBMSG_TYPE_STRING },
    [VLANDEV_ATTR_VID] = { "vid", BLOBMSG_TYPE_STRING },
    [VLANDEV_ATTR_INGRESS_QOS_MAPPING] = { "ingress_qos_mapping", BLOBMSG_TYPE_ARRAY },
    [VLANDEV_ATTR_EGRESS_QOS_MAPPING] = { "egress_qos_mapping", BLOBMSG_TYPE_ARRAY },
}
Definition at line 32 of file vlandev.c.
{
    [VLANDEV_ATTR_IFNAME] = { "ifname", BLOBMSG_TYPE_STRING },
    [VLANDEV_ATTR_VID] = { "vid", BLOBMSG_TYPE_STRING },
    [VLANDEV_ATTR_INGRESS_QOS_MAPPING] = { "ingress_qos_mapping", BLOBMSG_TYPE_ARRAY },
    [VLANDEV_ATTR_EGRESS_QOS_MAPPING] = { "egress_qos_mapping", BLOBMSG_TYPE_ARRAY },
};
Referenced by vlandev_reload().