zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/libubox/blob.c File Reference
blob.c File Reference
#include "blob.h"
Functions
static bool blob_buffer_grow (struct blob_buf *buf, int minlen)
static void blob_init (struct blob_attr *attr, int id, unsigned int len)
static struct blob_attr * offset_to_attr (struct blob_buf *buf, int offset)
static int attr_to_offset (struct blob_buf *buf, struct blob_attr *attr)
bool blob_buf_grow (struct blob_buf *buf, int required)
static struct blob_attr * blob_add (struct blob_buf *buf, struct blob_attr *pos, int id, int payload)
int blob_buf_init (struct blob_buf *buf, int id)
void blob_buf_free (struct blob_buf *buf)
void blob_fill_pad (struct blob_attr *attr)
void blob_set_raw_len (struct blob_attr *attr, unsigned int len)
struct blob_attr * blob_new (struct blob_buf *buf, int id, int payload)
struct blob_attr * blob_put_raw (struct blob_buf *buf, const void *ptr, unsigned int len)
struct blob_attr * blob_put (struct blob_buf *buf, int id, const void *ptr, unsigned int len)
void * blob_nest_start (struct blob_buf *buf, int id)
void blob_nest_end (struct blob_buf *buf, void *cookie)
bool blob_check_type (const void *ptr, unsigned int len, int type)
static int blob_parse_attr (struct blob_attr *attr, size_t attr_len, struct blob_attr **data, const struct blob_attr_info *info, int max)
int blob_parse_untrusted (struct blob_attr *attr, size_t attr_len, struct blob_attr **data, const struct blob_attr_info *info, int max)
int blob_parse (struct blob_attr *attr, struct blob_attr **data, const struct blob_attr_info *info, int max)
bool blob_attr_equal (const struct blob_attr *a1, const struct blob_attr *a2)
struct blob_attr * blob_memdup (struct blob_attr *attr)
Variables
static const size_t blob_type_minlen [BLOB_ATTR_LAST]
Function Documentation
attr_to_offset()
static int attr_to_offset (struct blob_buf * buf, struct blob_attr * attr) inline static
Definition at line 51 of file blob.c.
{
    return (char *)attr - (char *) buf->buf + BLOB_COOKIE;
}
References BLOB_COOKIE, and buf.
Referenced by blob_add(), blob_buf_grow(), and blob_nest_start().
blob_add()
static struct blob_attr * blob_add (struct blob_buf * buf, struct blob_attr * pos, int id, int payload) static
Definition at line 71 of file blob.c.
{
    int offset = attr_to_offset(buf, pos);
    int required = (offset - BLOB_COOKIE + sizeof(struct blob_attr) + payload) - buf->buflen;
    struct blob_attr *attr;
    if (required > 0) {
        if (!blob_buf_grow(buf, required))
            return NULL;
        attr = offset_to_attr(buf, offset);
    } else {
        attr = pos;
    }
    blob_init(attr, id, payload + sizeof(struct blob_attr));
    blob_fill_pad(attr);
    return attr;
}
References attr_to_offset(), blob_buf_grow(), BLOB_COOKIE, blob_fill_pad(), blob_init(), buf, and offset_to_attr().
Referenced by blob_buf_init(), blob_new(), and blob_put_raw().
blob_attr_equal()
bool blob_attr_equal (const struct blob_attr * a1, const struct blob_attr * a2)
Definition at line 311 of file blob.c.
{
    if (!a1 && !a2)
        return true;
    if (!a1 || !a2)
        return false;
    if (blob_pad_len(a1) != blob_pad_len(a2))
        return false;
    return !memcmp(a1, a2, blob_pad_len(a1));
}
References blob_pad_len().
Referenced by device_set_auth_status(), instance_config_changed(), station_update(), vif_update(), vlan_update(), and wdev_change_config().
blob_buf_free()
void blob_buf_free (struct blob_buf * buf)
Definition at line 104 of file blob.c.
{
    free(buf->buf);
    buf->buf = NULL;
    buf->head = NULL;
    buf->buflen = 0;
}
References buf.
Referenced by json_script_free(), main(), main(), netns_updown(), parseOCI(), parseOCIcapabilities_from_file(), pass_console(), proto_shell_create_tunnel(), reload_conf(), rpc_exec_reply(), rpc_file_exec_reply(), rpc_file_list(), rpc_file_md5(), rpc_file_read(), rpc_file_stat(), rpc_login_setup_acl_file(), rpc_sys_packagelist(), run_netifd(), run_ubusd(), ubus_lua__gc(), ubus_register_event_handler(), ubus_shutdown(), ubusd_proto_free_client(), uxc_attach(), uxc_create(), uxc_delete(), uxc_list(), uxc_set(), and uxc_state().
blob_buf_grow()
bool blob_buf_grow (struct blob_buf * buf, int required)
Definition at line 57 of file blob.c.
{
    int offset_head = attr_to_offset(buf, buf->head);
    if ((buf->buflen + required) > BLOB_ATTR_LEN_MASK)
        return false;
    if (!buf->grow || !buf->grow(buf, required))
        return false;
    buf->head = offset_to_attr(buf, offset_head);
    return true;
}
References attr_to_offset(), BLOB_ATTR_LEN_MASK, buf, and offset_to_attr().
Referenced by blob_add(), and blobmsg_realloc_string_buffer().
blob_buf_init()
int blob_buf_init (struct blob_buf * buf, int id)
Definition at line 91 of file blob.c.
{
    if (!buf->grow)
        buf->grow = blob_buffer_grow;
    buf->head = buf->buf;
    if (blob_add(buf, buf->buf, id, 0) == NULL)
        return -ENOMEM;
    return 0;
}
References blob_add(), blob_buffer_grow(), and buf.
Referenced by __device_broadcast_event(), __do_bridge_reload(), __ubus_monitor(), __ubus_notify_async(), __ubus_subscribe_request(), __udebug_buf_add(), __vlan_hotplug_op(), __vlandev_hotplug_op(), blobmsg_buf_init(), bridge_stp_notify(), client_main(), cmd_process_strings(), conf_load(), config_init_board(), config_init_devices(), config_parse_bridge_interface(), config_parse_interface(), config_parse_neighbor(), config_parse_route(), config_parse_rule(), config_parse_vlan(), config_parse_wireless_device(), config_parse_wireless_interface(), config_parse_wireless_station(), config_parse_wireless_vlan(), container_handle_features(), extdev_bridge_disable_interface(), extdev_bridge_disable_member(), extdev_bridge_enable_member(), extdev_dump(), extdev_free(), extdev_hotplug_prepare(), handle_button_timeout(), handle_expr_isdir(), handle_file(), handle_file(), handle_state(), hotplug_handler(), install_syscall_filter(), jail_delete_instance(), jshn_format(), netifd_add_host_route(), netifd_dev_status(), netifd_get_proto_handlers(), netifd_handle_dump(), netifd_handle_iface_prepare(), netifd_handle_status(), netifd_handle_wdev_get_validate(), netifd_handle_wdev_status(), netifd_sub_cb(), netifd_ubus_get_procd_data(), netifd_ubus_interface_event(), netifd_ubus_interface_notify(), netns_updown(), parseOCI(), parseOCIcapabilities_from_file(), pass_console(), prepare_config(), print_syscalls(), proto_shell_create_tunnel(), rc_list(), rpc_exec(), rpc_file_exec_reply(), rpc_file_list(), rpc_file_md5(), rpc_file_read(), rpc_file_stat(), rpc_handle_access(), rpc_handle_get(), rpc_iwinfo_assoclist(), rpc_iwinfo_countrylist(), rpc_iwinfo_devices(), rpc_iwinfo_freqlist(), rpc_iwinfo_info(), rpc_iwinfo_phyname(), rpc_iwinfo_scan(), rpc_iwinfo_survey(), rpc_iwinfo_txpowerlist(), rpc_login_setup_acl_file(), rpc_plugin_parse_exec(), rpc_session_to_blob(), rpc_sys_packagelist(), rpc_uci_add(), rpc_uci_changes(), rpc_uci_configs(), rpc_uci_getcommon(), rpc_uci_trigger_event(), rpc_ucode_request_finish(), rpc_ucode_script_call(), rule_handle_file(), run_netifd(), run_ubusd(), service_get_data(), service_handle_list(), service_handle_validate(), service_handle_watchdog(), service_instance_update(), service_start_early(), system_board(), system_info(), sysupgrade_error(), test_client_notify_cb(), test_count(), test_count(), test_hello_reply(), ubus_add_object(), ubus_cli_call(), ubus_cli_get_monitor_data(), ubus_cli_send(), ubus_complete_deferred_request(), ubus_event_bcast(), ubus_invoke_async_fd(), ubus_lookup(), ubus_lookup_id(), ubus_lua_call(), ubus_lua_notify(), ubus_lua_reply(), ubus_lua_send(), ubus_notify_subscription(), ubus_notify_unsubscribe(), ubus_register_event_handler(), ubus_remove_object(), ubus_send_event(), ubus_send_msg(), ubus_send_reply(), ubusd_acl_load_file(), ubusd_create_event_from_msg(), ubusd_create_object_event_msg(), ubusd_create_sequence_event_msg(), ubusd_handle_add_object(), ubusd_handle_invoke(), ubusd_handle_notify(), ubusd_handle_remove_object(), ubusd_monitor_message(), ubusd_proto_init_retmsg(), ubusd_reply_query(), ubusd_send_hello(), ubusd_send_obj(), udebug_entry_add(), udebug_send_msg(), ustp_ubus_exit(), uxc_attach(), uxc_boot(), uxc_create(), uxc_delete(), uxc_kill(), uxc_list(), uxc_set(), uxc_state(), validate_firmware_image_call(), and watchdog_set().
blob_buffer_grow()
static bool blob_buffer_grow (struct blob_buf * buf, int minlen) static
Definition at line 22 of file blob.c.
{
    struct blob_buf *new;
    int delta = ((minlen / 256) + 1) * 256;
    new = realloc(buf->buf, buf->buflen + delta);
    if (new) {
        buf->buf = new;
        memset(buf->buf + buf->buflen, 0, delta);
        buf->buflen += delta;
    }
    return !!new;
}
References buf.
Referenced by blob_buf_init().
blob_check_type()
bool blob_check_type (const void * ptr, unsigned int len, int type)
Definition at line 202 of file blob.c.
{
    const char *data = ptr;
    if (type >= BLOB_ATTR_LAST)
        return false;
    if (type >= BLOB_ATTR_INT8 && type <= BLOB_ATTR_INT64) {
        if (len != blob_type_minlen[type])
            return false;
    } else {
        if (len < blob_type_minlen[type])
            return false;
    }
    if (type == BLOB_ATTR_STRING && data[len - 1] != 0)
        return false;
    return true;
}
References BLOB_ATTR_INT64, BLOB_ATTR_INT8, BLOB_ATTR_LAST, BLOB_ATTR_STRING, blob_type_minlen, blob_attr::data, and type.
Referenced by blob_parse_attr(), blobmsg_check_attr_len(), and ubus_process_notify_status().
blob_fill_pad()
void blob_fill_pad (struct blob_attr * attr)
Definition at line 113 of file blob.c.
{
    char *buf = (char *) attr;
    int len = blob_pad_len(attr);
    int delta = len - blob_raw_len(attr);
    if (delta > 0)
        memset(buf + len - delta, 0, delta);
}
References blob_pad_len(), blob_raw_len(), and buf.
Referenced by blob_add(), and blobmsg_add_string_buffer().
blob_init()
static void blob_init (struct blob_attr * attr, int id, unsigned int len) static
Definition at line 36 of file blob.c.
{
    len &= BLOB_ATTR_LEN_MASK;
    len |= (id << BLOB_ATTR_ID_SHIFT) & BLOB_ATTR_ID_MASK;
    attr->id_len = cpu_to_be32(len);
}
References BLOB_ATTR_ID_MASK, BLOB_ATTR_ID_SHIFT, BLOB_ATTR_LEN_MASK, cpu_to_be32, and blob_attr::id_len.
Referenced by blob_add().
blob_memdup()
struct blob_attr * blob_memdup (struct blob_attr * attr)
Definition at line 326 of file blob.c.
{
    struct blob_attr *ret;
    int size = blob_pad_len(attr);
    ret = malloc(size);
    if (!ret)
        return NULL;
    memcpy(ret, attr, size);
    return ret;
}
References blob_pad_len().
Referenced by __bridge_reload(), acl_recv_cb(), block_cb(), bonding_reload(), bridge_reload(), cert_load(), config_init_board(), config_parse_interface(), device_apply_config(), device_create(), device_init_settings(), device_set_auth_status(), fstab_cb(), instance_init(), macvlan_reload(), netifd_add_dynamic(), ocistate_cb(), parseOCI(), service_update(), station_update(), veth_reload(), vif_update(), vlan_update(), vlandev_reload(), wdev_change_config(), wdev_create(), wdev_prepare_prev_config(), wireless_device_notify(), and wireless_device_run_handler().
blob_nest_end()
void blob_nest_end (struct blob_buf * buf, void * cookie)
Definition at line 185 of file blob.c.
{
    struct blob_attr *attr = offset_to_attr(buf, (unsigned long) cookie);
    blob_set_raw_len(attr, blob_pad_len(attr) + blob_len(buf->head));
    buf->head = attr;
}
References blob_len(), blob_pad_len(), blob_set_raw_len(), buf, and offset_to_attr().
Referenced by blobmsg_close_array(), blobmsg_close_table(), ubus_push_object_type(), ubus_send_event(), ubusd_create_object_event_msg(), ubusd_create_sequence_event_msg(), ubusd_handle_notify(), ubusd_reply_query(), and ubusd_send_obj().
blob_nest_start()
void * blob_nest_start (struct blob_buf * buf, int id)
Definition at line 175 of file blob.c.
{
    unsigned long offset = attr_to_offset(buf, buf->head);
    buf->head = blob_new(buf, id, 0);
    if (!buf->head)
        return NULL;
    return (void *) offset;
}
References attr_to_offset(), blob_new(), and buf.
Referenced by ubus_push_object_type(), ubus_send_event(), ubusd_create_object_event_msg(), ubusd_create_sequence_event_msg(), ubusd_handle_notify(), ubusd_reply_query(), and ubusd_send_obj().
blob_new()
struct blob_attr * blob_new (struct blob_buf * buf, int id, int payload)
Definition at line 132 of file blob.c.
{
    struct blob_attr *attr;
    attr = blob_add(buf, blob_next(buf->head), id, payload);
    if (!attr)
        return NULL;
    blob_set_raw_len(buf->head, blob_pad_len(buf->head) + blob_pad_len(attr));
    return attr;
}
References blob_add(), blob_next(), blob_pad_len(), blob_set_raw_len(), and buf.
Referenced by blob_nest_start(), blob_put(), blobmsg_new(), and main().
blob_parse()
int blob_parse (struct blob_attr * attr, struct blob_attr ** data, const struct blob_attr_info * info, int max)
Definition at line 296 of file blob.c.
{
    struct blob_attr *pos;
    int found = 0;
    size_t rem;
    memset(data, 0, sizeof(struct blob_attr *) * max);
    blob_for_each_attr(pos, attr, rem) {
        found += blob_parse_attr(pos, rem, data, info, max);
    }
    return found;
}
References blob_for_each_attr, blob_parse_attr(), blob_attr::data, and info.
Referenced by ubus_cli_get_monitor_data().
blob_parse_attr()
static int blob_parse_attr (struct blob_attr * attr, size_t attr_len, struct blob_attr ** data, const struct blob_attr_info * info, int max) static
Definition at line 224 of file blob.c.
{
    int id;
    size_t len;
    int found = 0;
    size_t data_len;
    if (!attr || attr_len < sizeof(struct blob_attr))
        return 0;
    id = blob_id(attr);
    if (id >= max)
        return 0;
    len = blob_raw_len(attr);
    if (len > attr_len || len < sizeof(struct blob_attr))
        return 0;
    data_len = blob_len(attr);
    if (data_len > len)
        return 0;
    if (info) {
        int type = info[id].type;
        if (type < BLOB_ATTR_LAST) {
            if (!blob_check_type(blob_data(attr), data_len, type))
                return 0;
        }
        if (info[id].minlen && len < info[id].minlen)
            return 0;
        if (info[id].maxlen && len > info[id].maxlen)
            return 0;
        if (info[id].validate && !info[id].validate(&info[id], attr))
            return 0;
    }
    if (!data[id])
        found++;
    data[id] = attr;
    return found;
}
References BLOB_ATTR_LAST, blob_check_type(), blob_data(), blob_id(), blob_len(), blob_raw_len(), blob_attr::data, id, info, and type.
Referenced by blob_parse(), and blob_parse_untrusted().
blob_parse_untrusted()
int blob_parse_untrusted (struct blob_attr * attr, size_t attr_len, struct blob_attr ** data, const struct blob_attr_info * info, int max)
Definition at line 272 of file blob.c.
{
    struct blob_attr *pos;
    size_t len = 0;
    int found = 0;
    size_t rem;
    if (!attr || attr_len < sizeof(struct blob_attr))
        return 0;
    len = blob_raw_len(attr);
    if (attr_len < len)
        return 0;
    memset(data, 0, sizeof(struct blob_attr *) * max);
    blob_for_each_attr_len(pos, attr, len, rem) {
        found += blob_parse_attr(pos, rem, data, info, max);
    }
    return found;
}
References blob_for_each_attr_len, blob_parse_attr(), blob_raw_len(), blob_attr::data, and info.
Referenced by cert_load(), fuzz_blob_parse(), ubus_cli_monitor_cb(), and ubus_parse_msg().
blob_put()
struct blob_attr * blob_put (struct blob_buf * buf, int id, const void * ptr, unsigned int len)
Definition at line 161 of file blob.c.
{
    struct blob_attr *attr;
    attr = blob_new(buf, id, len);
    if (!attr)
        return NULL;
    if (ptr)
        memcpy(blob_data(attr), ptr, len);
    return attr;
}
References blob_data(), blob_new(), and buf.
Referenced by blob_put_string(), blob_put_u16(), blob_put_u32(), blob_put_u64(), blob_put_u8(), proto_shell_create_tunnel(), ubus_put_data(), ubusd_create_event_from_msg(), ubusd_forward_invoke(), and ubusd_monitor_message().
blob_put_raw()
struct blob_attr * blob_put_raw (struct blob_buf * buf, const void * ptr, unsigned int len)
Definition at line 145 of file blob.c.
{
    struct blob_attr *attr;
    if (len < sizeof(struct blob_attr) || !ptr)
        return NULL;
    attr = blob_add(buf, blob_next(buf->head), 0, len - sizeof(struct blob_attr));
    if (!attr)
        return NULL;
    blob_set_raw_len(buf->head, blob_pad_len(buf->head) + len);
    memcpy(attr, ptr, len);
    return attr;
}
References blob_add(), blob_next(), blob_pad_len(), blob_set_raw_len(), and buf.
Referenced by __vlan_hotplug_op(), __vlandev_hotplug_op(), and put_container().
blob_set_raw_len()
void blob_set_raw_len (struct blob_attr * attr, unsigned int len)
Definition at line 124 of file blob.c.
{
    len &= BLOB_ATTR_LEN_MASK;
    attr->id_len &= ~cpu_to_be32(BLOB_ATTR_LEN_MASK);
    attr->id_len |= cpu_to_be32(len);
}
References BLOB_ATTR_LEN_MASK, cpu_to_be32, and blob_attr::id_len.
Referenced by blob_nest_end(), blob_new(), blob_put_raw(), blobmsg_add_string_buffer(), blobmsg_alloc_string_buffer(), and blobmsg_open_nested().
offset_to_attr()
static struct blob_attr * offset_to_attr (struct blob_buf * buf, int offset) inline static
Definition at line 44 of file blob.c.
{
    void *ptr = (char *)buf->buf + offset - BLOB_COOKIE;
    return ptr;
}
References BLOB_COOKIE, and buf.
Referenced by blob_add(), blob_buf_grow(), and blob_nest_end().
Variable Documentation
blob_type_minlen
const size_t blob_type_minlen[BLOB_ATTR_LAST] static
Initial value:
= {
    [BLOB_ATTR_STRING] = 1,
    [BLOB_ATTR_INT8] = sizeof(uint8_t),
    [BLOB_ATTR_INT16] = sizeof(uint16_t),
    [BLOB_ATTR_INT32] = sizeof(uint32_t),
    [BLOB_ATTR_INT64] = sizeof(uint64_t),
    [BLOB_ATTR_DOUBLE] = sizeof(double),
}
Definition at line 192 of file blob.c.
{
    [BLOB_ATTR_STRING] = 1,
    [BLOB_ATTR_INT8] = sizeof(uint8_t),
    [BLOB_ATTR_INT16] = sizeof(uint16_t),
    [BLOB_ATTR_INT32] = sizeof(uint32_t),
    [BLOB_ATTR_INT64] = sizeof(uint64_t),
    [BLOB_ATTR_DOUBLE] = sizeof(double),
};
Referenced by blob_check_type().