zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/ubus/ubusd_id.h File Reference
ubusd_id.h File Reference
#include <libubox/avl.h>
#include <stdint.h>
Classes
struct ubus_id
Functions
void ubus_init_id_tree (struct avl_tree *tree)
void ubus_init_string_tree (struct avl_tree *tree, bool dup)
bool ubus_alloc_id (struct avl_tree *tree, struct ubus_id *id, uint32_t val)
static void ubus_free_id (struct avl_tree *tree, struct ubus_id *id)
static struct ubus_id * ubus_find_id (struct avl_tree *tree, uint32_t id)
Class Documentation
ubus_id
struct ubus_id
Definition at line 20 of file ubusd_id.h.
Class Members
struct avl_node avl
uint32_t id
Function Documentation
ubus_alloc_id()
bool ubus_alloc_id (struct avl_tree * tree, struct ubus_id * id, uint32_t val)
Definition at line 53 of file ubusd_id.c.
{
    id->avl.key = &id->id;
    if (val) {
        id->id = val;
        return avl_insert(tree, &id->avl) == 0;
    }
    do {
        if (read(random_fd, &id->id, sizeof(id->id)) != sizeof(id->id))
            return false;
        if (id->id < UBUS_SYSTEM_OBJECT_MAX)
            continue;
    } while (avl_insert(tree, &id->avl) != 0);
    return true;
}
References avl_insert(), id, random_fd, and UBUS_SYSTEM_OBJECT_MAX.
Referenced by ubus_create_obj_type(), ubusd_create_object_internal(), and ubusd_proto_new_client().
ubus_find_id()
static struct ubus_id * ubus_find_id (struct avl_tree * tree, uint32_t id) inline static
Definition at line 34 of file ubusd_id.h.
{
    struct avl_node *avl;
    avl = avl_find(tree, &id);
    if (!avl)
        return NULL;
    return container_of(avl, struct ubus_id, avl);
}
References avl_find(), and container_of.
Referenced by ubus_get_obj_type(), ubusd_find_object(), ubusd_get_client_by_id(), ubusd_handle_invoke(), and ubusd_handle_notify().
ubus_free_id()
static void ubus_free_id (struct avl_tree * tree, struct ubus_id * id) inline static
Definition at line 29 of file ubusd_id.h.
{
    avl_delete(tree, &id->avl);
}
References avl_delete(), and id.
Referenced by ubus_unref_object_type(), ubusd_free_object(), ubusd_proto_free_client(), and ubusd_proto_new_client().
ubus_init_id_tree()
void ubus_init_id_tree (struct avl_tree * tree)
Definition at line 40 of file ubusd_id.c.
{
    if (random_fd < 0) {
        random_fd = open("/dev/urandom", O_RDONLY);
        if (random_fd < 0) {
            perror("open");
            exit(1);
        }
    }
    avl_init(tree, ubus_cmp_id, false, NULL);
}
References avl_init(), random_fd, and ubus_cmp_id().
Referenced by ubusd_obj_init(), and ubusd_proto_init().
ubus_init_string_tree()
void ubus_init_string_tree (struct avl_tree * tree, bool dup)
Definition at line 35 of file ubusd_id.c.
{
    avl_init(tree, avl_strcmp, dup, NULL);
}
References avl_init(), and avl_strcmp().
Referenced by ubusd_acl_init(), ubusd_event_init(), and ubusd_obj_init().