zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/netifd/config.h File Reference
config.h File Reference
#include <libubox/blobmsg.h>
#include <uci_blob.h>
Functions
int config_init_all (void)
struct ether_addr * config_get_default_macaddr (const char *ifname)
int config_get_default_gro (const char *ifname)
const char * config_get_default_conduit (const char *ifname)
Variables
bool config_init
Function Documentation
config_get_default_conduit()
const char * config_get_default_conduit (const char * ifname)
Definition at line 806 of file config.c.
{
    struct blob_attr *cur;
    if (!board_netdevs)
        return NULL;
    cur = config_find_blobmsg_attr(board_netdevs, ifname, BLOBMSG_TYPE_TABLE);
    if (!cur)
        return NULL;
    cur = config_find_blobmsg_attr(cur, "conduit", BLOBMSG_TYPE_STRING);
    if (!cur)
        return NULL;
    return blobmsg_get_string(cur);
}
References blobmsg_get_string(), BLOBMSG_TYPE_STRING, BLOBMSG_TYPE_TABLE, board_netdevs, config_find_blobmsg_attr(), and ifname.
Referenced by device_fill_default_settings().
config_get_default_gro()
int config_get_default_gro (const char * ifname)
Definition at line 788 of file config.c.
{
    struct blob_attr *cur;
    if (!board_netdevs)
        return -1;
    cur = config_find_blobmsg_attr(board_netdevs, ifname, BLOBMSG_TYPE_TABLE);
    if (!cur)
        return -1;
    cur = config_find_blobmsg_attr(cur, "gro", BLOBMSG_TYPE_BOOL);
    if (!cur)
        return -1;
    return blobmsg_get_bool(cur);
}
References blobmsg_get_bool(), BLOBMSG_TYPE_BOOL, BLOBMSG_TYPE_TABLE, board_netdevs, config_find_blobmsg_attr(), and ifname.
Referenced by device_fill_default_settings().
config_get_default_macaddr()
struct ether_addr * config_get_default_macaddr (const char * ifname)
Definition at line 770 of file config.c.
{
    struct blob_attr *cur;
    if (!board_netdevs)
        return NULL;
    cur = config_find_blobmsg_attr(board_netdevs, ifname, BLOBMSG_TYPE_TABLE);
    if (!cur)
        return NULL;
    cur = config_find_blobmsg_attr(cur, "macaddr", BLOBMSG_TYPE_STRING);
    if (!cur)
        return NULL;
    return ether_aton(blobmsg_get_string(cur));
}
References blobmsg_get_string(), BLOBMSG_TYPE_STRING, BLOBMSG_TYPE_TABLE, board_netdevs, config_find_blobmsg_attr(), and ifname.
Referenced by device_fill_default_settings().
config_init_all()
int config_init_all (void)
Definition at line 846 of file config.c.
{
    int ret = 0;
    char *err;
    uci_network = config_init_package("network");
    if (!uci_network) {
        uci_get_errorstr(uci_ctx, &err, NULL);
        netifd_log_message(L_CRIT, "Failed to load network config (%s)\n", err);
        free(err);
        return -1;
    }
    uci_wireless = config_init_package("wireless");
    if (!uci_wireless && uci_ctx->err != UCI_ERR_NOTFOUND) {
        uci_get_errorstr(uci_ctx, &err, NULL);
        netifd_log_message(L_CRIT, "Failed to load wireless config (%s)\n", err);
        free(err);
        ret = -1;
    }
    config_init_board();
    vlist_update(&interfaces);
    config_init = true;
    device_reset_config();
    config_init_devices(true);
    config_init_vlans();
    config_init_devices(false);
    config_init_interfaces();
    config_init_ip();
    config_init_rules();
    config_init_globals();
    config_init_wireless();
    config_init = false;
    device_reset_old();
    device_init_pending();
    vlist_flush(&interfaces);
    interface_refresh_assignments(false);
    interface_start_pending();
    wireless_start_pending(0);
    return ret;
}
References config_init, config_init_board(), config_init_devices(), config_init_globals(), config_init_interfaces(), config_init_ip(), config_init_package(), config_init_rules(), config_init_vlans(), config_init_wireless(), device_init_pending(), device_reset_config(), device_reset_old(), err, interface_refresh_assignments(), interface_start_pending(), interfaces, L_CRIT, netifd_log_message(), uci_ctx, uci_network, uci_wireless, vlist_flush(), vlist_update(), and wireless_start_pending().
Referenced by main(), and netifd_reload().
Variable Documentation
config_init
bool config_init extern
Definition at line 32 of file config.c.
Referenced by __wireless_device_set_up(), config_init_all(), device_create(), interface_check_state(), and interface_set_available().