zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/procd.h File Reference
procd.h File Reference
#include <libubox/uloop.h>
#include <libubox/utils.h>
#include <libubus.h>
#include <udebug.h>
#include <stdio.h>
#include <syslog.h>
#include "log.h"
Macros
#define __init __attribute__((constructor))
Functions
void procd_connect_ubus (void)
void procd_reconnect_ubus (int reconnect)
void ubus_init_hotplug (struct ubus_context *ctx)
void ubus_init_service (struct ubus_context *ctx)
void ubus_init_system (struct ubus_context *ctx)
void procd_state_next (void)
void procd_state_ubus_connect (void)
void procd_shutdown (int event)
void procd_early (void)
void procd_preinit (void)
void procd_signal (void)
void procd_signal_preinit (void)
void procd_inittab (void)
void procd_inittab_run (const char *action)
void procd_inittab_kill (void)
void procd_bcast_event (char *event, struct blob_attr *msg)
void trigger_event (const char *type, struct blob_attr *data)
void trigger_add (struct blob_attr *rule, void *id)
void trigger_del (void *id)
void watch_add (const char *_name, void *id)
void watch_del (void *id)
void watch_ubus (struct ubus_context *ctx)
void procd_udebug_printf (const char *format,...)
void procd_udebug_set_enabled (bool val)
Variables
char * ubus_socket
Macro Definition Documentation
__init
#define __init __attribute__((constructor))
Definition at line 28 of file procd.h.
Function Documentation
procd_bcast_event()
void procd_bcast_event (char * event, struct blob_attr * msg)
Definition at line 864 of file system.c.
{
    int ret;
    if (!notify)
        return;
    ret = ubus_notify(_ctx, &system_object, event, msg, -1);
    if (ret)
        fprintf(stderr, "Failed to notify log: %s\n", ubus_strerror(ret));
}
References _ctx, notify, system_object, ubus_notify(), and ubus_strerror().
procd_connect_ubus()
void procd_connect_ubus (void)
Definition at line 91 of file ubus.c.
{
    ubus_timer.cb = ubus_connect_cb;
    reset_timeout();
    timeout_retry();
}
References uloop_timeout::cb, reset_timeout(), timeout_retry(), ubus_connect_cb(), and ubus_timer.
Referenced by main(), and state_enter().
procd_early()
void procd_early (void)
procd_inittab()
void procd_inittab (void)
Definition at line 311 of file inittab.c.
{
#define LINE_LEN    128
    FILE *fp = fopen(tab, "r");
    struct init_action *a;
    regex_t pat_inittab;
    regmatch_t matches[5];
    char *line;
    if (!fp) {
        ERROR("Failed to open %s: %m\n", tab);
        return;
    }
    regcomp(&pat_inittab, "([a-zA-Z0-9]*):([a-zA-Z0-9]*):([a-zA-Z0-9]*):(.*)", REG_EXTENDED);
    line = malloc(LINE_LEN);
    a = calloc(1, sizeof(struct init_action));
    while (fgets(line, LINE_LEN, fp)) {
        char *tags[TAG_PROCESS + 1];
        char *tok;
        int i;
        int len = strlen(line);
        while (isspace(line[len - 1]))
            len--;
        line[len] = 0;
        if (*line == '#')
            continue;
        if (regexec(&pat_inittab, line, 5, matches, 0))
            continue;
        DEBUG(4, "Parsing inittab - %s\n", line);
        for (i = TAG_ID; i <= TAG_PROCESS; i++) {
            line[matches[i].rm_eo] = '\0';
            tags[i] = &line[matches[i + 1].rm_so];
        };
        tok = strtok(tags[TAG_PROCESS], " ");
        for (i = 0; i < (MAX_ARGS - 1) && tok; i++) {
            a->argv[i] = tok;
            tok = strtok(NULL, " ");
        }
        a->argv[i] = NULL;
        a->id = tags[TAG_ID];
        a->line = line;
        if (add_action(a, tags[TAG_ACTION]))
            continue;
        line = malloc(LINE_LEN);
        a = calloc(1, sizeof(struct init_action));
    }
    fclose(fp);
    free(line);
    free(a);
    regfree(&pat_inittab);
}
References add_action(), init_action::argv, DEBUG, ERROR, init_action::id, init_action::line, LINE_LEN, MAX_ARGS, tab, TAG_ACTION, TAG_ID, and TAG_PROCESS.
Referenced by state_enter().
procd_inittab_kill()
void procd_inittab_kill (void)
Definition at line 300 of file inittab.c.
{
    struct init_action *a;
    list_for_each_entry(a, &actions, list) {
        a->respawn = -1;
        if (a->proc.pid)
            kill(a->proc.pid, SIGKILL);
    }
}
References init_action::list, list_for_each_entry, uloop_process::pid, init_action::proc, and init_action::respawn.
Referenced by service_stop_all().
procd_inittab_run()
void procd_inittab_run (const char * action)
Definition at line 288 of file inittab.c.
{
    struct init_action *a;
    list_for_each_entry(a, &actions, list)
        if (!strcmp(a->handler->name, handler)) {
            a->handler->cb(a);
            if (!a->handler->multi)
                break;
        }
}
References init_handler::cb, init_action::handler, init_action::list, list_for_each_entry, init_handler::multi, and init_handler::name.
Referenced by handle_start_console(), and state_enter().
procd_preinit()
void procd_preinit (void)
procd_reconnect_ubus()
void procd_reconnect_ubus (int reconnect)
procd_shutdown()
void procd_shutdown (int event)
Definition at line 222 of file state.c.
{
    if (state >= STATE_SHUTDOWN)
        return;
    DEBUG(2, "Shutting down system with event %x\n", event);
    reboot_event = event;
    state = STATE_SHUTDOWN;
    state_enter();
}
References DEBUG, reboot_event, state, state_enter(), and STATE_SHUTDOWN.
Referenced by signal_shutdown(), and system_reboot().
procd_signal()
void procd_signal (void)
Definition at line 85 of file signal.c.
{
    signal(SIGPIPE, SIG_IGN);
    if (getpid() != 1)
        return;
    sigaction(SIGTERM, &sa_shutdown, NULL);
    sigaction(SIGINT, &sa_shutdown, NULL);
    sigaction(SIGUSR1, &sa_shutdown, NULL);
    sigaction(SIGUSR2, &sa_shutdown, NULL);
    sigaction(SIGPWR, &sa_shutdown, NULL);
    sigaction(SIGSEGV, &sa_crash, NULL);
    sigaction(SIGBUS, &sa_crash, NULL);
    sigaction(SIGHUP, &sa_dummy, NULL);
    sigaction(SIGKILL, &sa_dummy, NULL);
    sigaction(SIGSTOP, &sa_dummy, NULL);
#ifndef DISABLE_INIT
    reboot(RB_DISABLE_CAD);
#endif
}
References sa_crash, sa_dummy, and sa_shutdown.
Referenced by main().
procd_signal_preinit()
void procd_signal_preinit (void)
procd_state_next()
void procd_state_next (void)
Definition at line 209 of file state.c.
{
    DEBUG(4, "Change state %d -> %d\n", state, state + 1);
    state++;
    state_enter();
}
References DEBUG, state, and state_enter().
Referenced by coldplug_complete(), main(), procd_state_ubus_connect(), and rcdone().
procd_state_ubus_connect()
void procd_state_ubus_connect (void)
Definition at line 216 of file state.c.
{
    if (state == STATE_UBUS)
        procd_state_next();
}
References procd_state_next(), state, and STATE_UBUS.
Referenced by ubus_connect_cb().
procd_udebug_printf()
void procd_udebug_printf (const char * format, ...)
Definition at line 44 of file procd.c.
{
    va_list ap;
    va_start(ap, format);
    procd_udebug_vprintf(format, ap);
    va_end(ap);
}
References procd_udebug_vprintf().
procd_udebug_set_enabled()
void procd_udebug_set_enabled (bool val)
Definition at line 53 of file procd.c.
{
    static const struct udebug_buf_meta meta = {
        .name = "procd_log",
        .format = UDEBUG_FORMAT_STRING,
    };
    if (udebug_enabled == val)
        return;
    udebug_enabled = val;
    if (!val) {
        ulog_udebug(NULL);
        udebug_buf_free(&udb);
        udebug_free(&ud);
        return;
    }
    udebug_init(&ud);
    udebug_auto_connect(&ud, NULL);
    udebug_buf_init(&udb, 1024, 64 * 1024);
    udebug_buf_add(&ud, &udb, &meta);
    ulog_udebug(&udb);
}
References ud, udb, udebug_auto_connect(), udebug_buf_add(), udebug_buf_free(), udebug_buf_init(), udebug_enabled, UDEBUG_FORMAT_STRING, udebug_free(), udebug_init(), and ulog_udebug().
Referenced by main(), and procd_udebug_cb().
trigger_add()
void trigger_add (struct blob_attr * rule, void * id)
Definition at line 235 of file trigger.c.
{
    struct blob_attr *cur;
    int rem;
    blobmsg_for_each_attr(cur, rule, rem) {
        struct blob_attr *_cur, *type = NULL, *script = NULL, *timeout = NULL;
        int _rem;
        int i = 0;
        if (blobmsg_type(cur) != BLOBMSG_TYPE_ARRAY)
            continue;
        blobmsg_for_each_attr(_cur, cur, _rem) {
            switch (i++) {
            case 0:
                if (blobmsg_type(_cur) == BLOBMSG_TYPE_STRING)
                    type = _cur;
                break;
            case 1:
                if (blobmsg_type(_cur) == BLOBMSG_TYPE_ARRAY)
                    script = _cur;
                break;
            case 2:
                if (blobmsg_type(_cur) == BLOBMSG_TYPE_INT32)
                    timeout = _cur;
                break;
            }
        }
        if (type && script) {
            int t = 0;
            if (timeout)
                t = blobmsg_get_u32(timeout);
            _trigger_add(blobmsg_get_string(type), script, t, id);
        }
    }
}
References _trigger_add(), blobmsg_for_each_attr, blobmsg_get_string(), blobmsg_get_u32(), BLOBMSG_TYPE_ARRAY, BLOBMSG_TYPE_INT32, BLOBMSG_TYPE_STRING, script, timeout, and type.
Referenced by instance_config_parse(), and service_update().
trigger_del()
void trigger_del (void * id)
Definition at line 277 of file trigger.c.
{
    struct trigger *t, *n;
    list_for_each_entry_safe(t, n, &triggers, list) {
        if (t->id != id)
            continue;
        trigger_free(t);
    }
}
References trigger::id, trigger::list, list_for_each_entry_safe, and trigger_free().
Referenced by instance_free(), service_stopped(), and service_update().
trigger_event()
void trigger_event (const char * type, struct blob_attr * data)
Definition at line 297 of file trigger.c.
{
    struct trigger *t;
    list_for_each_entry(t, &triggers, list) {
        if (!trigger_match(type, t->type))
            continue;
        json_script_run(&t->jctx, t->type, data);
    }
}
References trigger::data, trigger::jctx, json_script_run(), trigger::list, list_for_each_entry, trigger_match(), trigger::type, and type.
Referenced by service_handle_event(), service_instance_update(), and watch_notify_cb().
ubus_init_hotplug()
void ubus_init_hotplug (struct ubus_context * ctx)
Definition at line 431 of file hotplug-dispatch.c.
{
    ctx = newctx;
    remove_subsystem(0, NULL);
    if (init_subsystems()) {
        printf("failed to initialize hotplug subsystems from %s\n", HOTPLUG_BASEDIR);
        return;
    }
    fd_inotify_read.fd = inotify_init1(IN_NONBLOCK | IN_CLOEXEC);
    fd_inotify_read.cb = inotify_read_handler;
    if (fd_inotify_read.fd == -1) {
        printf("failed to initialize inotify handler for %s\n", HOTPLUG_BASEDIR);
        return;
    }
    inotify_buffer = calloc(1, INOTIFY_SZ);
    if (!inotify_buffer)
        return;
    if (inotify_add_watch(fd_inotify_read.fd, HOTPLUG_BASEDIR,
        IN_CREATE | IN_MOVED_TO | IN_DELETE | IN_MOVED_FROM | IN_ONLYDIR) == -1)
        return;
    uloop_fd_add(&fd_inotify_read, ULOOP_READ);
}
References uloop_fd::cb, ctx, uloop_fd::fd, fd_inotify_read, HOTPLUG_BASEDIR, init_subsystems(), inotify_buffer, inotify_read_handler(), INOTIFY_SZ, remove_subsystem(), uloop_fd_add(), and ULOOP_READ.
Referenced by ubus_connect_cb().
ubus_init_service()
void ubus_init_service (struct ubus_context * ctx)
Definition at line 1081 of file service.c.
{
    struct stat statbuf;
    ctx = _ctx;
    ubus_add_object(ctx, &main_object);
    if (!stat("/sbin/ujail", &statbuf))
        ubus_add_object(ctx, &container_object);
}
References _ctx, container_object, ctx, main_object, and ubus_add_object().
Referenced by ubus_connect_cb().
ubus_init_system()
void ubus_init_system (struct ubus_context * ctx)
Definition at line 876 of file system.c.
{
    int ret;
    _ctx = ctx;
    initramfs = !!getenv("INITRAMFS");
    if (initramfs)
        unsetenv("INITRAMFS");
    ret = ubus_add_object(ctx, &system_object);
    if (ret)
        ERROR("Failed to add object: %s\n", ubus_strerror(ret));
}
References _ctx, ctx, ERROR, initramfs, system_object, ubus_add_object(), and ubus_strerror().
Referenced by ubus_connect_cb().
watch_add()
void watch_add (const char * _name, void * id)
Definition at line 68 of file watch.c.
{
    int len = strlen(_name);
    char *name;
    struct watch_object *o = calloc_a(sizeof(*o), &name, len + 1);
    o->name = name;
    strcpy(name, _name);
    o->id = id;
    list_add(&o->list, &watch_objects);
}
References calloc_a, id, watch_object::id, watch_object::list, list_add(), and watch_object::name.
Referenced by instance_config_parse().
watch_del()
void watch_del (void * id)
Definition at line 81 of file watch.c.
{
    struct watch_object *t, *n;
    list_for_each_entry_safe(t, n, &watch_objects, list) {
        if (t->id != id)
            continue;
        list_del(&t->list);
        free(t);
    }
}
References watch_object::id, watch_object::list, list_del(), and list_for_each_entry_safe.
Referenced by instance_free().
watch_ubus()
void watch_ubus (struct ubus_context * ctx)
Definition at line 111 of file watch.c.
{
    watch_event.cb = watch_subscribe_cb;
    watch_subscribe.cb = watch_notify_cb;
    if (ubus_register_subscriber(ctx, &watch_subscribe))
        ERROR("failed to register ubus subscriber\n");
    if (ubus_register_event_handler(ctx, &watch_event, "ubus.object.add"))
        ERROR("failed to add ubus event handler\n");
}
References ubus_event_handler::cb, ubus_subscriber::cb, ctx, ERROR, ubus_register_event_handler(), ubus_register_subscriber(), watch_event, watch_notify_cb(), watch_subscribe, and watch_subscribe_cb().
Referenced by ubus_connect_cb().
Variable Documentation
ubus_socket
char* ubus_socket extern
Definition at line 22 of file ubus.c.
Referenced by main(), ubus_connect_cb(), and ubus_reconnect_cb().