zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/libubox/md5.h File Reference
md5.h File Reference
#include <stdint.h>
#include <stddef.h>
Classes
struct md5_ctx
Typedefs
typedef struct md5_ctx md5_ctx_t
Functions
void md5_begin (md5_ctx_t *ctx)
void md5_hash (const void *data, size_t length, md5_ctx_t *ctx)
void md5_end (void *resbuf, md5_ctx_t *ctx)
int md5sum (const char *file, void *md5_buf)
Class Documentation
md5_ctx
struct md5_ctx
Definition at line 47 of file md5.h.
Class Members
uint32_t a
uint32_t b
unsigned char buffer[64]
uint32_t c
uint32_t d
uint32_t hi
uint32_t lo
Typedef Documentation
md5_ctx_t
typedef struct md5_ctx md5_ctx_t
Function Documentation
md5_begin()
void md5_begin (md5_ctx_t * ctx) extern
Definition at line 214 of file md5.c.
{
    ctx->a = 0x67452301;
    ctx->b = 0xefcdab89;
    ctx->c = 0x98badcfe;
    ctx->d = 0x10325476;
    ctx->lo = 0;
    ctx->hi = 0;
}
References ctx.
Referenced by hmac_md5(), instance_file_update(), and md5sum().
md5_end()
void md5_end (void * resbuf, md5_ctx_t * ctx) extern
Definition at line 259 of file md5.c.
{
    unsigned char *result = resbuf;
    unsigned long used, available;
    used = ctx->lo & 0x3f;
    ctx->buffer[used++] = 0x80;
    available = 64 - used;
    if (available < 8) {
        memset(&ctx->buffer[used], 0, available);
        body(ctx, ctx->buffer, 64);
        used = 0;
        available = 64;
    }
    memset(&ctx->buffer[used], 0, available - 8);
    ctx->lo <<= 3;
    ctx->buffer[56] = ctx->lo;
    ctx->buffer[57] = ctx->lo >> 8;
    ctx->buffer[58] = ctx->lo >> 16;
    ctx->buffer[59] = ctx->lo >> 24;
    ctx->buffer[60] = ctx->hi;
    ctx->buffer[61] = ctx->hi >> 8;
    ctx->buffer[62] = ctx->hi >> 16;
    ctx->buffer[63] = ctx->hi >> 24;
    body(ctx, ctx->buffer, 64);
    result[0] = ctx->a;
    result[1] = ctx->a >> 8;
    result[2] = ctx->a >> 16;
    result[3] = ctx->a >> 24;
    result[4] = ctx->b;
    result[5] = ctx->b >> 8;
    result[6] = ctx->b >> 16;
    result[7] = ctx->b >> 24;
    result[8] = ctx->c;
    result[9] = ctx->c >> 8;
    result[10] = ctx->c >> 16;
    result[11] = ctx->c >> 24;
    result[12] = ctx->d;
    result[13] = ctx->d >> 8;
    result[14] = ctx->d >> 16;
    result[15] = ctx->d >> 24;
    memset(ctx, 0, sizeof(*ctx));
}
References body(), and ctx.
Referenced by hmac_md5(), instance_file_update(), and md5sum().
md5_hash()
void md5_hash (const void * data, size_t length, md5_ctx_t * ctx) extern
Definition at line 225 of file md5.c.
{
    uint32_t saved_lo;
    unsigned long used, available;
    saved_lo = ctx->lo;
    if ((ctx->lo = (saved_lo + size) & 0x1fffffff) < saved_lo)
        ctx->hi++;
    ctx->hi += size >> 29;
    used = saved_lo & 0x3f;
    if (used) {
        available = 64 - used;
        if (size < available) {
            memcpy(&ctx->buffer[used], data, size);
            return;
        }
        memcpy(&ctx->buffer[used], data, available);
        data = (const unsigned char *)data + available;
        size -= available;
        body(ctx, ctx->buffer, 64);
    }
    if (size >= 64) {
        data = body(ctx, data, size & ~((size_t) 0x3f));
        size &= 0x3f;
    }
    memcpy(ctx->buffer, data, size);
}
References body(), and ctx.
Referenced by hmac_md5(), instance_file_update(), and md5sum().
md5sum()
int md5sum (const char * file, void * md5_buf)
Definition at line 311 of file md5.c.
{
    char buf[256];
    md5_ctx_t ctx;
    int ret = 0;
    FILE *f;
    f = fopen(file, "r");
    if (!f)
        return -1;
    md5_begin(&ctx);
    do {
        int len = fread(buf, 1, sizeof(buf), f);
        if (!len)
            break;
        md5_hash(buf, len, &ctx);
        ret += len;
    } while(1);
    md5_end(md5_buf, &ctx);
    fclose(f);
    return ret;
}
References buf, ctx, md5_begin(), md5_end(), and md5_hash().
Referenced by rpc_file_md5().