zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/ustp/mstp.c File Reference
mstp.c File Reference
#include <config.h>
#include <string.h>
#include <netinet/in.h>
#include <linux/if_bridge.h>
#include <asm/byteorder.h>
#include <time.h>
#include <sys/time.h>
#include "mstp.h"
#include "log.h"
#include "driver.h"
Macros
#define FOREACH_PORT_IN_BRIDGE(port, bridge)
#define FOREACH_TREE_IN_BRIDGE(tree, bridge)
#define FOREACH_PTP_IN_TREE(ptp, tree)
#define FOREACH_PTP_IN_PORT(ptp, port)
#define rstpVersion(br)
#define assurancePort(prt)
#define NEAREST_WHOLE_SECOND(msgTime)
#define PRSM_begin(prt)
#define PPMSM_begin(prt)
#define PTSM_begin(prt)
#define PISM_LOG(_fmt, _args...)
#define PISM_begin(ptp)
#define PRSSM_begin(tree)
#define PRTSM_LOG(_fmt, _args...)
#define PRTSM_run(ptp, dry_run)
#define PRTSM_begin(ptp)
#define PSTSM_begin(ptp)
#define TCSM_begin(ptp)
Functions
static void PTSM_tick (port_t *prt)
static bool TCSM_run (per_tree_port_t *ptp, bool dry_run)
static void BDSM_begin (port_t *prt)
static void br_state_machines_begin (bridge_t *br)
static void prt_state_machines_begin (port_t *prt)
static void tree_state_machines_begin (tree_t *tree)
static void br_state_machines_run (bridge_t *br)
static void updtbrAssuRcvdInfoWhile (port_t *prt)
static void RecalcConfigDigest (bridge_t *br)
static __u32 compute_pcost (int speed)
static void bridge_default_internal_vars (bridge_t *br)
static void tree_default_internal_vars (tree_t *tree)
static void port_default_internal_vars (port_t *prt)
static void ptp_default_internal_vars (per_tree_port_t *ptp)
static tree_t * create_tree (bridge_t *br, __u8 *macaddr, __be16 MSTID)
static per_tree_port_t * create_ptp (tree_t *tree, port_t *prt)
bool MSTP_IN_bridge_create (bridge_t *br, __u8 *macaddr)
bool MSTP_IN_port_create_and_add_tail (port_t *prt, __u16 portno)
void MSTP_IN_delete_port (port_t *prt)
void MSTP_IN_delete_bridge (bridge_t *br)
void MSTP_IN_set_bridge_address (bridge_t *br, __u8 *macaddr)
void MSTP_IN_set_bridge_enable (bridge_t *br, bool up)
void MSTP_IN_set_port_enable (port_t *prt, bool up, int speed, int duplex)
void MSTP_IN_one_second (bridge_t *br)
void MSTP_IN_all_fids_flushed (per_tree_port_t *ptp)
void MSTP_IN_rx_bpdu (port_t *prt, bpdu_t *bpdu, int size)
void MSTP_IN_get_cist_bridge_status (bridge_t *br, CIST_BridgeStatus *status)
void MSTP_IN_get_msti_bridge_status (tree_t *tree, MSTI_BridgeStatus *status)
int MSTP_IN_set_cist_bridge_config (bridge_t *br, CIST_BridgeConfig *cfg)
int MSTP_IN_set_msti_bridge_config (tree_t *tree, __u8 bridge_priority)
void MSTP_IN_get_cist_port_status (port_t *prt, CIST_PortStatus *status)
void MSTP_IN_get_msti_port_status (per_tree_port_t *ptp, MSTI_PortStatus *status)
int MSTP_IN_set_cist_port_config (port_t *prt, CIST_PortConfig *cfg)
int MSTP_IN_set_msti_port_config (per_tree_port_t *ptp, MSTI_PortConfig *cfg)
int MSTP_IN_port_mcheck (port_t *prt)
bool MSTP_IN_set_vid2fid (bridge_t *br, __u16 vid, __u16 fid)
bool MSTP_IN_set_all_vids2fids (bridge_t *br, __u16 *vids2fids)
bool MSTP_IN_set_fid2mstid (bridge_t *br, __u16 fid, __u16 mstid)
bool MSTP_IN_set_all_fids2mstids (bridge_t *br, __u16 *fids2mstids)
bool MSTP_IN_get_mstilist (bridge_t *br, int *num_mstis, __u16 *mstids)
bool MSTP_IN_create_msti (bridge_t *br, __u16 mstid)
bool MSTP_IN_delete_msti (bridge_t *br, __u16 mstid)
void MSTP_IN_set_mst_config_id (bridge_t *br, __u16 revision, __u8 *name)
static void set_TopologyChange (tree_t *tree, bool hint_SetToYes, port_t *port)
static bool samePriorityAndTimers (port_priority_vector_t *vec1, port_priority_vector_t *vec2, times_t *time1, times_t *time2, bool cist)
static bool betterorsamePriority (port_priority_vector_t *vec1, port_priority_vector_t *vec2, port_identifier_t pId1, port_identifier_t pId2, bool cist)
static bool betterorsameInfo (per_tree_port_t *ptp, port_info_origin_t newInfoIs)
static bool clearAllRcvdMsgs (port_t *prt, bool dry_run)
static void clearReselectTree (tree_t *tree)
static bool fromSameRegion (port_t *prt)
static void newTcWhile (per_tree_port_t *ptp)
static port_info_t rcvInfo (per_tree_port_t *ptp)
static void recordAgreement (per_tree_port_t *ptp)
static void recordDispute (per_tree_port_t *ptp)
static void recordMastered (per_tree_port_t *ptp)
static void recordPriority (per_tree_port_t *ptp)
static void recordProposal (per_tree_port_t *ptp)
static void recordTimes (per_tree_port_t *ptp)
static void set_fdbFlush (per_tree_port_t *ptp)
static void setRcvdMsgs (port_t *prt)
static void setReRootTree (tree_t *tree)
static void setSelectedTree (tree_t *tree)
static void setSyncTree (tree_t *tree)
static void setTcFlags (per_tree_port_t *ptp)
static void setTcPropTree (per_tree_port_t *ptp)
static void syncMaster (bridge_t *br)
static void txConfig (port_t *prt)
static __u8 message_role_from_port_role (per_tree_port_t *ptp)
static void txMstp (port_t *prt)
static void txTcn (port_t *prt)
static void updtBPDUVersion (port_t *prt)
static void updtRcvdInfoWhile (per_tree_port_t *ptp)
static void updtRolesDisabledTree (tree_t *tree)
static void reselectMSTIs (port_t *prt)
static void updtRolesTree (tree_t *tree)
static bool PRSM_to_DISCARD (port_t *prt, bool dry_run)
static void PRSM_to_RECEIVE (port_t *prt)
static bool PRSM_run (port_t *prt, bool dry_run)
static bool PPMSM_run (port_t *prt, bool dry_run)
static void PPMSM_to_CHECKING_RSTP (port_t *prt)
static void PPMSM_to_SELECTING_STP (port_t *prt)
static void PPMSM_to_SENSING (port_t *prt)
static void BDSM_to_EDGE (port_t *prt)
static void BDSM_to_NOT_EDGE (port_t *prt)
static bool BDSM_run (port_t *prt, bool dry_run)
static bool PTSM_run (port_t *prt, bool dry_run)
static bool PTSM_to_TRANSMIT_INIT (port_t *prt, bool begin, bool dry_run)
static void PTSM_to_TRANSMIT_CONFIG (port_t *prt)
static void PTSM_to_TRANSMIT_TCN (port_t *prt)
static void PTSM_to_TRANSMIT_RSTP (port_t *prt)
static void PTSM_to_TRANSMIT_PERIODIC (port_t *prt)
static void PTSM_to_IDLE (port_t *prt)
static bool PISM_run (per_tree_port_t *ptp, bool dry_run)
static void PISM_to_DISABLED (per_tree_port_t *ptp, bool begin)
static void PISM_to_AGED (per_tree_port_t *ptp)
static void PISM_to_UPDATE (per_tree_port_t *ptp)
static void PISM_to_SUPERIOR_DESIGNATED (per_tree_port_t *ptp)
static void PISM_to_REPEATED_DESIGNATED (per_tree_port_t *ptp)
static void PISM_to_INFERIOR_DESIGNATED (per_tree_port_t *ptp)
static void PISM_to_NOT_DESIGNATED (per_tree_port_t *ptp)
static void PISM_to_OTHER (per_tree_port_t *ptp)
static void PISM_to_CURRENT (per_tree_port_t *ptp)
static void PISM_to_RECEIVE (per_tree_port_t *ptp)
static bool PRSSM_run (tree_t *tree, bool dry_run)
static void PRSSM_to_INIT_TREE (tree_t *tree)
static void PRSSM_to_ROLE_SELECTION (tree_t *tree)
static bool PRTSM_runr (per_tree_port_t *ptp, bool recursive_call, bool dry_run)
static void PRTSM_to_INIT_PORT (per_tree_port_t *ptp)
static void PRTSM_to_DISABLE_PORT (per_tree_port_t *ptp)
static void PRTSM_to_DISABLED_PORT (per_tree_port_t *ptp, unsigned int MaxAge)
static void PRTSM_to_MASTER_PROPOSED (per_tree_port_t *ptp)
static void PRTSM_to_MASTER_AGREED (per_tree_port_t *ptp)
static void PRTSM_to_MASTER_SYNCED (per_tree_port_t *ptp)
static void PRTSM_to_MASTER_RETIRED (per_tree_port_t *ptp)
static void PRTSM_to_MASTER_FORWARD (per_tree_port_t *ptp)
static void PRTSM_to_MASTER_LEARN (per_tree_port_t *ptp, unsigned int forwardDelay)
static void PRTSM_to_MASTER_DISCARD (per_tree_port_t *ptp, unsigned int forwardDelay)
static void PRTSM_to_MASTER_PORT (per_tree_port_t *ptp)
static void PRTSM_to_ROOT_PROPOSED (per_tree_port_t *ptp)
static void PRTSM_to_ROOT_AGREED (per_tree_port_t *ptp)
static void PRTSM_to_ROOT_SYNCED (per_tree_port_t *ptp)
static void PRTSM_to_REROOT (per_tree_port_t *ptp)
static void PRTSM_to_ROOT_FORWARD (per_tree_port_t *ptp)
static void PRTSM_to_ROOT_LEARN (per_tree_port_t *ptp, unsigned int forwardDelay)
static void PRTSM_to_REROOTED (per_tree_port_t *ptp)
static void PRTSM_to_ROOT_PORT (per_tree_port_t *ptp, unsigned int FwdDelay)
static void PRTSM_to_DESIGNATED_PROPOSE (per_tree_port_t *ptp)
static void PRTSM_to_DESIGNATED_AGREED (per_tree_port_t *ptp)
static void PRTSM_to_DESIGNATED_SYNCED (per_tree_port_t *ptp)
static void PRTSM_to_DESIGNATED_RETIRED (per_tree_port_t *ptp)
static void PRTSM_to_DESIGNATED_FORWARD (per_tree_port_t *ptp)
static void PRTSM_to_DESIGNATED_LEARN (per_tree_port_t *ptp, unsigned int forwardDelay)
static void PRTSM_to_DESIGNATED_DISCARD (per_tree_port_t *ptp, unsigned int forwardDelay)
static void PRTSM_to_DESIGNATED_PORT (per_tree_port_t *ptp)
static void PRTSM_to_BLOCK_PORT (per_tree_port_t *ptp)
static void PRTSM_to_BACKUP_PORT (per_tree_port_t *ptp, unsigned int HelloTime)
static void PRTSM_to_ALTERNATE_PROPOSED (per_tree_port_t *ptp)
static void PRTSM_to_ALTERNATE_AGREED (per_tree_port_t *ptp)
static void PRTSM_to_ALTERNATE_PORT (per_tree_port_t *ptp, unsigned int forwardDelay)
static bool PSTSM_run (per_tree_port_t *ptp, bool dry_run)
static void PSTSM_to_DISCARDING (per_tree_port_t *ptp, bool begin)
static void PSTSM_to_LEARNING (per_tree_port_t *ptp)
static void PSTSM_to_FORWARDING (per_tree_port_t *ptp)
static void TCSM_to_INACTIVE (per_tree_port_t *ptp, bool begin)
static bool TCSM_to_LEARNING (per_tree_port_t *ptp, bool dry_run)
static void TCSM_to_DETECTED (per_tree_port_t *ptp)
static void TCSM_to_NOTIFIED_TCN (per_tree_port_t *ptp)
static void TCSM_to_NOTIFIED_TC (per_tree_port_t *ptp)
static void TCSM_to_PROPAGATING (per_tree_port_t *ptp)
static void TCSM_to_ACKNOWLEDGED (per_tree_port_t *ptp)
static void TCSM_to_ACTIVE (per_tree_port_t *ptp)
static bool __br_state_machines_run (bridge_t *br, bool dry_run)
Macro Definition Documentation
assurancePort
#define assurancePort (prt)
Value:
                            ((prt)->NetworkPort && (prt)->operPointToPointMAC \
                            && (prt)->sendRSTP)
Definition at line 74 of file mstp.c.
#define assurancePort(prt) ((prt)->NetworkPort && (prt)->operPointToPointMAC \
                            && (prt)->sendRSTP)
Referenced by __br_state_machines_run(), and PTSM_run().
FOREACH_PORT_IN_BRIDGE
#define FOREACH_PORT_IN_BRIDGE (port, bridge)
Value:
    list_for_each_entry((port), &(bridge)->ports, br_list)
Definition at line 60 of file mstp.c.
#define FOREACH_PORT_IN_BRIDGE(port, bridge) \
    list_for_each_entry((port), &(bridge)->ports, br_list)
Referenced by __br_state_machines_run(), br_state_machines_begin(), MSTP_IN_one_second(), MSTP_IN_set_bridge_enable(), and MSTP_IN_set_cist_bridge_config().
FOREACH_PTP_IN_PORT
#define FOREACH_PTP_IN_PORT (ptp, port)
Value:
    list_for_each_entry((ptp), &(port)->trees, port_list)
Definition at line 66 of file mstp.c.
#define FOREACH_PTP_IN_PORT(ptp, port) \
    list_for_each_entry((ptp), &(port)->trees, port_list)
Referenced by __br_state_machines_run(), br_state_machines_begin(), clearAllRcvdMsgs(), MSTP_IN_set_bridge_enable(), MSTP_IN_set_port_enable(), PRSM_run(), prt_state_machines_begin(), PTSM_tick(), and rcvInfo().
FOREACH_PTP_IN_TREE
#define FOREACH_PTP_IN_TREE (ptp, tree)
Value:
    list_for_each_entry((ptp), &(tree)->ports, tree_list)
Definition at line 64 of file mstp.c.
#define FOREACH_PTP_IN_TREE(ptp, tree) \
    list_for_each_entry((ptp), &(tree)->ports, tree_list)
Referenced by clearReselectTree(), MSTP_IN_create_msti(), MSTP_IN_set_cist_bridge_config(), MSTP_IN_set_msti_bridge_config(), PRSSM_run(), PRTSM_runr(), set_TopologyChange(), setReRootTree(), setSelectedTree(), setSyncTree(), setTcPropTree(), syncMaster(), tree_state_machines_begin(), updtRolesDisabledTree(), and updtRolesTree().
FOREACH_TREE_IN_BRIDGE
#define FOREACH_TREE_IN_BRIDGE (tree, bridge)
Value:
    list_for_each_entry((tree), &(bridge)->trees, bridge_list)
Definition at line 62 of file mstp.c.
#define FOREACH_TREE_IN_BRIDGE(tree, bridge) \
    list_for_each_entry((tree), &(bridge)->trees, bridge_list)
Referenced by __br_state_machines_run(), br_state_machines_begin(), MSTP_IN_create_msti(), MSTP_IN_delete_msti(), MSTP_IN_get_mstilist(), MSTP_IN_one_second(), MSTP_IN_port_create_and_add_tail(), MSTP_IN_set_all_fids2mstids(), MSTP_IN_set_bridge_address(), MSTP_IN_set_bridge_enable(), MSTP_IN_set_cist_bridge_config(), MSTP_IN_set_fid2mstid(), and prt_state_machines_begin().
NEAREST_WHOLE_SECOND
#define NEAREST_WHOLE_SECOND (msgTime)
Value:
    ((128 > msgTime[1]) ? msgTime[0] : msgTime[0] + 1)
Referenced by rcvInfo().
PISM_begin
#define PISM_begin (ptp)
Value:
PISM_to_DISABLED((ptp), true)
Definition at line 3327 of file mstp.c.
Referenced by br_state_machines_begin(), prt_state_machines_begin(), and tree_state_machines_begin().
PISM_LOG
#define PISM_LOG (_fmt, _args...)
Value:
{}
Definition at line 3323 of file mstp.c.
Referenced by PISM_to_AGED(), PISM_to_CURRENT(), PISM_to_DISABLED(), PISM_to_INFERIOR_DESIGNATED(), PISM_to_NOT_DESIGNATED(), PISM_to_OTHER(), PISM_to_RECEIVE(), PISM_to_REPEATED_DESIGNATED(), PISM_to_SUPERIOR_DESIGNATED(), and PISM_to_UPDATE().
PPMSM_begin
#define PPMSM_begin (prt)
Value:
PPMSM_to_CHECKING_RSTP(prt)
Definition at line 2967 of file mstp.c.
Referenced by br_state_machines_begin(), and prt_state_machines_begin().
PRSM_begin
#define PRSM_begin (prt)
Value:
PRSM_to_DISCARD((prt), false)
Definition at line 2882 of file mstp.c.
Referenced by br_state_machines_begin(), and prt_state_machines_begin().
PRSSM_begin
#define PRSSM_begin (tree)
Value:
PRSSM_to_INIT_TREE(tree)
Definition at line 3611 of file mstp.c.
Referenced by br_state_machines_begin(), and tree_state_machines_begin().
PRTSM_begin
#define PRTSM_begin (ptp)
Value:
PRTSM_to_INIT_PORT(ptp)
Definition at line 3674 of file mstp.c.
Referenced by br_state_machines_begin(), prt_state_machines_begin(), and tree_state_machines_begin().
PRTSM_LOG
#define PRTSM_LOG (_fmt, _args...)
Value:
{}
Definition at line 3669 of file mstp.c.
Referenced by PRTSM_runr(), PRTSM_to_ALTERNATE_AGREED(), PRTSM_to_ALTERNATE_PORT(), PRTSM_to_ALTERNATE_PROPOSED(), PRTSM_to_BACKUP_PORT(), PRTSM_to_BLOCK_PORT(), PRTSM_to_DESIGNATED_AGREED(), PRTSM_to_DESIGNATED_DISCARD(), PRTSM_to_DESIGNATED_FORWARD(), PRTSM_to_DESIGNATED_LEARN(), PRTSM_to_DESIGNATED_PORT(), PRTSM_to_DESIGNATED_PROPOSE(), PRTSM_to_DESIGNATED_RETIRED(), PRTSM_to_DESIGNATED_SYNCED(), PRTSM_to_DISABLE_PORT(), PRTSM_to_DISABLED_PORT(), PRTSM_to_INIT_PORT(), PRTSM_to_MASTER_AGREED(), PRTSM_to_MASTER_DISCARD(), PRTSM_to_MASTER_FORWARD(), PRTSM_to_MASTER_LEARN(), PRTSM_to_MASTER_PORT(), PRTSM_to_MASTER_PROPOSED(), PRTSM_to_MASTER_RETIRED(), PRTSM_to_MASTER_SYNCED(), PRTSM_to_REROOT(), PRTSM_to_REROOTED(), PRTSM_to_ROOT_AGREED(), PRTSM_to_ROOT_FORWARD(), PRTSM_to_ROOT_LEARN(), PRTSM_to_ROOT_PORT(), PRTSM_to_ROOT_PROPOSED(), and PRTSM_to_ROOT_SYNCED().
PRTSM_run
#define PRTSM_run (ptp, dry_run)
Value:
PRTSM_runr((ptp), false, (dry_run))
Definition at line 3673 of file mstp.c.
Referenced by __br_state_machines_run().
PSTSM_begin
#define PSTSM_begin (ptp)
Value:
PSTSM_to_DISCARDING((ptp), true)
Definition at line 4581 of file mstp.c.
Referenced by br_state_machines_begin(), prt_state_machines_begin(), and tree_state_machines_begin().
PTSM_begin
#define PTSM_begin (prt)
Value:
PTSM_to_TRANSMIT_INIT((prt), true, false)
Definition at line 3126 of file mstp.c.
Referenced by br_state_machines_begin(), and prt_state_machines_begin().
rstpVersion
#define rstpVersion (br)
Value:
((br)->ForceProtocolVersion >= protoRSTP)
Definition at line 70 of file mstp.c.
Referenced by MSTP_IN_port_mcheck(), PPMSM_run(), PPMSM_to_CHECKING_RSTP(), PRTSM_runr(), recordAgreement(), and set_fdbFlush().
TCSM_begin
#define TCSM_begin (ptp)
Value:
TCSM_to_INACTIVE((ptp), true)
Definition at line 4675 of file mstp.c.
Referenced by br_state_machines_begin(), prt_state_machines_begin(), and tree_state_machines_begin().
Function Documentation
__br_state_machines_run()
static bool __br_state_machines_run (bridge_t * br, bool dry_run) static
Definition at line 5030 of file mstp.c.
{
    port_t *prt;
    per_tree_port_t *ptp;
    tree_t *tree;
    /* Check if bridge assurance timer expires */
    FOREACH_PORT_IN_BRIDGE(prt, br)
    {
        if(prt->portEnabled && assurancePort(prt)
           && (0 == prt->brAssuRcvdInfoWhile) && !prt->BaInconsistent
          )
        {
            if(dry_run) /* state change */
                return true;
            prt->BaInconsistent = true;
            ERROR_PRTNAME(prt->bridge, prt, "Bridge assurance inconsistent");
        }
    }
    /* 13.28  Port Receive state machine */
    FOREACH_PORT_IN_BRIDGE(prt, br)
    {
        if(PRSM_run(prt, dry_run) && dry_run)
            return true;
    }
    /* 13.29  Port Protocol Migration state machine */
    FOREACH_PORT_IN_BRIDGE(prt, br)
    {
        if(PPMSM_run(prt, dry_run) && dry_run)
            return true;
    }
    /* 13.30  Bridge Detection state machine */
    FOREACH_PORT_IN_BRIDGE(prt, br)
    {
        if(BDSM_run(prt, dry_run) && dry_run)
            return true;
    }
    /* 13.31  Port Transmit state machine */
    FOREACH_PORT_IN_BRIDGE(prt, br)
    {
        if(PTSM_run(prt, dry_run) && dry_run)
            return true;
    }
    /* 13.32  Port Information state machine */
    FOREACH_PORT_IN_BRIDGE(prt, br)
    {
        FOREACH_PTP_IN_PORT(ptp, prt)
        {
            if(PISM_run(ptp, dry_run) && dry_run)
                return true;
        }
    }
    /* 13.33  Port Role Selection state machine */
    FOREACH_TREE_IN_BRIDGE(tree, br)
    {
        if(PRSSM_run(tree, dry_run) && dry_run)
            return true;
    }
    /* 13.34  Port Role Transitions state machine */
    FOREACH_PORT_IN_BRIDGE(prt, br)
    {
        FOREACH_PTP_IN_PORT(ptp, prt)
        {
            if(PRTSM_run(ptp, dry_run) && dry_run)
                return true;
        }
    }
    /* 13.35  Port State Transition state machine */
    FOREACH_PORT_IN_BRIDGE(prt, br)
    {
        FOREACH_PTP_IN_PORT(ptp, prt)
        {
            if(PSTSM_run(ptp, dry_run) && dry_run)
                return true;
        }
    }
    /* 13.36  Topology Change state machine */
    FOREACH_PORT_IN_BRIDGE(prt, br)
    {
        FOREACH_PTP_IN_PORT(ptp, prt)
        {
            if(TCSM_run(ptp, dry_run) && dry_run)
                return true;
        }
    }
    return false;
}
References assurancePort, port_t::BaInconsistent, BDSM_run(), port_t::brAssuRcvdInfoWhile, port_t::bridge, dry_run, ERROR_PRTNAME, FOREACH_PORT_IN_BRIDGE, FOREACH_PTP_IN_PORT, FOREACH_TREE_IN_BRIDGE, PISM_run(), port_t::portEnabled, PPMSM_run(), PRSM_run(), PRSSM_run(), PRTSM_run, PSTSM_run(), PTSM_run(), and TCSM_run().
Referenced by br_state_machines_run().
BDSM_begin()
static void BDSM_begin (port_t * prt) static
Definition at line 3077 of file mstp.c.
{
    if(prt->AdminEdgePort)
        BDSM_to_EDGE(prt/*, begin*/);
    else
        BDSM_to_NOT_EDGE(prt/*, begin*/);
}
References port_t::AdminEdgePort, BDSM_to_EDGE(), and BDSM_to_NOT_EDGE().
Referenced by br_state_machines_begin(), MSTP_IN_set_cist_port_config(), and prt_state_machines_begin().
BDSM_run()
static bool BDSM_run (port_t * prt, bool dry_run) static
Definition at line 3085 of file mstp.c.
{
    per_tree_port_t *cist;
    switch(prt->BDSM_state)
    {
        case BDSM_EDGE:
            if(((!prt->portEnabled || !prt->AutoEdge) && !prt->AdminEdgePort)
               || !prt->operEdge
              )
            {
                if(dry_run) /* state change */
                    return true;
                BDSM_to_NOT_EDGE(prt);
            }
            return false;
        case BDSM_NOT_EDGE:
             cist = GET_CIST_PTP_FROM_PORT(prt);
            /* NOTE: 802.1Q-2005(-2011) is not clear, which of the per-tree
             *  "proposing" flags to use here, or one should combine
             *  them all for all trees?
             * So, I decide that it will be the "proposing" flag
             *  from CIST tree - it seems like a good bet.
             */
            if((!prt->portEnabled && prt->AdminEdgePort)
               || ((0 == prt->edgeDelayWhile) && prt->AutoEdge && prt->sendRSTP
                   && cist->proposing)
              )
            {
                if(dry_run) /* state change */
                    return true;
                BDSM_to_EDGE(prt);
            }
        default:
            return false;
    }
}
References port_t::AdminEdgePort, port_t::AutoEdge, BDSM_EDGE, BDSM_NOT_EDGE, port_t::BDSM_state, BDSM_to_EDGE(), BDSM_to_NOT_EDGE(), dry_run, port_t::edgeDelayWhile, GET_CIST_PTP_FROM_PORT, port_t::operEdge, port_t::portEnabled, per_tree_port_t::proposing, and port_t::sendRSTP.
Referenced by __br_state_machines_run().
BDSM_to_EDGE()
static void BDSM_to_EDGE (port_t * prt) static
Definition at line 3055 of file mstp.c.
{
    prt->BDSM_state = BDSM_EDGE;
    prt->operEdge = true;
    /* No need to run, no one condition will be met
     * if(!begin)
     *     BDSM_run(prt, false); */
}
References BDSM_EDGE, port_t::BDSM_state, and port_t::operEdge.
Referenced by BDSM_begin(), and BDSM_run().
BDSM_to_NOT_EDGE()
static void BDSM_to_NOT_EDGE (port_t * prt) static
Definition at line 3066 of file mstp.c.
{
    prt->BDSM_state = BDSM_NOT_EDGE;
    prt->operEdge = false;
    /* No need to run, no one condition will be met
     * if(!begin)
     *     BDSM_run(prt, false); */
}
References BDSM_NOT_EDGE, port_t::BDSM_state, and port_t::operEdge.
Referenced by BDSM_begin(), and BDSM_run().
betterorsameInfo()
static bool betterorsameInfo (per_tree_port_t * ptp, port_info_origin_t newInfoIs) static
Definition at line 1753 of file mstp.c.
{
    if((ioReceived == newInfoIs) && (ioReceived == ptp->infoIs))
        return betterorsamePriority(&ptp->msgPriority,
                                    &ptp->portPriority,
                                    0, 0, (0 == ptp->MSTID));
    else if((ioMine == newInfoIs) && (ioMine == ptp->infoIs))
        return betterorsamePriority(&ptp->designatedPriority,
                                    &ptp->portPriority,
                                    0, 0, (0 == ptp->MSTID));
    return false;
}
References betterorsamePriority(), per_tree_port_t::designatedPriority, per_tree_port_t::infoIs, ioMine, ioReceived, per_tree_port_t::msgPriority, per_tree_port_t::MSTID, and per_tree_port_t::portPriority.
Referenced by PISM_to_SUPERIOR_DESIGNATED(), and PISM_to_UPDATE().
betterorsamePriority()
static bool betterorsamePriority (port_priority_vector_t * vec1, port_priority_vector_t * vec2, port_identifier_t pId1, port_identifier_t pId2, bool cist) static
Definition at line 1702 of file mstp.c.
{
    int result;
    if(cist)
    {
        if(0 < (result = _ncmp(vec1->RootID, vec2->RootID)))
            return false; /* worse */
        else if(0 > result)
            return true; /* better */
        /* The same. Check further. */
        if(0 < (result = _ncmp(vec1->ExtRootPathCost, vec2->ExtRootPathCost)))
            return false; /* worse */
        else if(0 > result)
            return true; /* better */
        /* The same. Check further. */
    }
    if(0 < (result = _ncmp(vec1->RRootID, vec2->RRootID)))
        return false; /* worse */
    else if(0 > result)
        return true; /* better */
    /* The same. Check further. */
    if(0 < (result = _ncmp(vec1->IntRootPathCost, vec2->IntRootPathCost)))
        return false; /* worse */
    else if(0 > result)
        return true; /* better */
    /* The same. Check further. */
    if(0 < (result = _ncmp(vec1->DesignatedBridgeID, vec2->DesignatedBridgeID)))
        return false; /* worse */
    else if(0 > result)
        return true; /* better */
    /* The same. Check further. */
    if(0 < (result = _ncmp(vec1->DesignatedPortID, vec2->DesignatedPortID)))
        return false; /* worse */
    else if(0 > result)
        return true; /* better */
    /* The same. Check further. */
    /* Port ID is a tie-breaker */
    return cmp(pId1, <=, pId2);
}
References _ncmp, cmp, port_priority_vector_t::DesignatedBridgeID, port_priority_vector_t::DesignatedPortID, port_priority_vector_t::ExtRootPathCost, port_priority_vector_t::IntRootPathCost, port_priority_vector_t::RootID, and port_priority_vector_t::RRootID.
Referenced by betterorsameInfo(), rcvInfo(), and updtRolesTree().
br_state_machines_begin()
static void br_state_machines_begin (bridge_t * br) static
Definition at line 4968 of file mstp.c.
{
    port_t *prt;
    per_tree_port_t *ptp;
    tree_t *tree;
    if(!br->bridgeEnabled)
        return;
    /* 13.28  Port Receive state machine */
    FOREACH_PORT_IN_BRIDGE(prt, br)
        PRSM_begin(prt);
    /* 13.29  Port Protocol Migration state machine */
    FOREACH_PORT_IN_BRIDGE(prt, br)
        PPMSM_begin(prt);
    /* 13.30  Bridge Detection state machine */
    FOREACH_PORT_IN_BRIDGE(prt, br)
        BDSM_begin(prt);
    /* 13.31  Port Transmit state machine */
    FOREACH_PORT_IN_BRIDGE(prt, br)
        PTSM_begin(prt);
    /* 13.32  Port Information state machine */
    FOREACH_PORT_IN_BRIDGE(prt, br)
    {
        FOREACH_PTP_IN_PORT(ptp, prt)
        {
            ptp->start_time = br->uptime; /* 12.8.2.2.3 b) */
            PISM_begin(ptp);
        }
    }
    /* 13.33  Port Role Selection state machine */
    FOREACH_TREE_IN_BRIDGE(tree, br)
        PRSSM_begin(tree);
    /* 13.34  Port Role Transitions state machine */
    FOREACH_PORT_IN_BRIDGE(prt, br)
    {
        FOREACH_PTP_IN_PORT(ptp, prt)
            PRTSM_begin(ptp);
    }
    /* 13.35  Port State Transition state machine */
    FOREACH_PORT_IN_BRIDGE(prt, br)
    {
        FOREACH_PTP_IN_PORT(ptp, prt)
            PSTSM_begin(ptp);
    }
    /* 13.36  Topology Change state machine */
    FOREACH_PORT_IN_BRIDGE(prt, br)
    {
        FOREACH_PTP_IN_PORT(ptp, prt)
            TCSM_begin(ptp);
    }
    br_state_machines_run(br);
}
References BDSM_begin(), br_state_machines_run(), bridge_t::bridgeEnabled, FOREACH_PORT_IN_BRIDGE, FOREACH_PTP_IN_PORT, FOREACH_TREE_IN_BRIDGE, PISM_begin, PPMSM_begin, PRSM_begin, PRSSM_begin, PRTSM_begin, PSTSM_begin, PTSM_begin, per_tree_port_t::start_time, TCSM_begin, and bridge_t::uptime.
Referenced by MSTP_IN_set_all_fids2mstids(), MSTP_IN_set_all_vids2fids(), MSTP_IN_set_bridge_address(), MSTP_IN_set_bridge_enable(), MSTP_IN_set_cist_bridge_config(), MSTP_IN_set_fid2mstid(), MSTP_IN_set_mst_config_id(), and MSTP_IN_set_vid2fid().
br_state_machines_run()
static void br_state_machines_run (bridge_t * br) static
Definition at line 5126 of file mstp.c.
{
    struct timespec tv, tv_end;
    signed long delta;
    if(!br->bridgeEnabled)
        return;
    clock_gettime(CLOCK_MONOTONIC, &tv_end);
    ++(tv_end.tv_sec);
    do {
        if(!__br_state_machines_run(br, true /* dry run */))
            return;
        __br_state_machines_run(br, false /* actual run */);
        /* Check for the timeout */
        clock_gettime(CLOCK_MONOTONIC, &tv);
        if(0 < (delta = tv.tv_sec - tv_end.tv_sec))
            return;
        if(0 == delta)
        {
            delta = tv.tv_nsec - tv_end.tv_nsec;
            if(0 < delta)
                return;
        }
    } while(true);
}
References __br_state_machines_run(), and bridge_t::bridgeEnabled.
Referenced by br_state_machines_begin(), MSTP_IN_all_fids_flushed(), MSTP_IN_delete_msti(), MSTP_IN_delete_port(), MSTP_IN_one_second(), MSTP_IN_port_mcheck(), MSTP_IN_rx_bpdu(), MSTP_IN_set_cist_bridge_config(), MSTP_IN_set_cist_port_config(), MSTP_IN_set_msti_port_config(), MSTP_IN_set_port_enable(), prt_state_machines_begin(), and tree_state_machines_begin().
bridge_default_internal_vars()
static void bridge_default_internal_vars (bridge_t * br) static
Definition at line 105 of file mstp.c.
{
    br->uptime = 0;
}
References bridge_t::uptime.
Referenced by MSTP_IN_bridge_create(), and MSTP_IN_set_bridge_enable().
clearAllRcvdMsgs()
static bool clearAllRcvdMsgs (port_t * prt, bool dry_run) static
Definition at line 1767 of file mstp.c.
{
    per_tree_port_t *ptp;
    if(dry_run)
    {
        FOREACH_PTP_IN_PORT(ptp, prt)
            if(ptp->rcvdMsg)
                return true;
        return false;
    }
    FOREACH_PTP_IN_PORT(ptp, prt)
        ptp->rcvdMsg = false;
    return false;
}
References dry_run, FOREACH_PTP_IN_PORT, and per_tree_port_t::rcvdMsg.
Referenced by PRSM_to_DISCARD().
clearReselectTree()
static void clearReselectTree (tree_t * tree) static
Definition at line 1786 of file mstp.c.
{
    per_tree_port_t *ptp;
    FOREACH_PTP_IN_TREE(ptp, tree)
        ptp->reselect = false;
}
References FOREACH_PTP_IN_TREE, and per_tree_port_t::reselect.
Referenced by PRSSM_to_ROLE_SELECTION().
compute_pcost()
static __u32 compute_pcost (int speed) static
Definition at line 96 of file mstp.c.
{
  /* speed is in MB/s*/
  if(speed > 0)
    return (speed < 20000000) ? 20000000 / speed : 1;
  else
    return MAX_PATH_COST;
}
References MAX_PATH_COST.
Referenced by create_ptp(), MSTP_IN_set_cist_port_config(), MSTP_IN_set_msti_port_config(), and MSTP_IN_set_port_enable().
create_ptp()
static per_tree_port_t * create_ptp (tree_t * tree, port_t * prt) static
Definition at line 205 of file mstp.c.
{
    /* Initialize all fields except anchors */
    per_tree_port_t *ptp = calloc(1, sizeof(*ptp));
    if(!ptp)
    {
        ERROR_PRTNAME(prt->bridge, prt, "Out of memory");
        return NULL;
    }
    ptp->port = prt;
    ptp->tree = tree;
    ptp->MSTID = tree->MSTID;
    ptp->state = BR_STATE_DISABLED;
    /* 0x80 = default port priority (17.14 of 802.1D) */
    ptp->portId = __constant_cpu_to_be16(0x8000) | prt->port_number;
    assign(ptp->AdminInternalPortPathCost, 0u);
    assign(ptp->InternalPortPathCost, compute_pcost(GET_PORT_SPEED(prt)));
    /* 802.1Q leaves portPriority and portTimes uninitialized */
    assign(ptp->portPriority, tree->BridgePriority);
    assign(ptp->portTimes, tree->BridgeTimes);
    ptp->calledFromFlushRoutine = false;
    ptp_default_internal_vars(ptp);
    return ptp;
}
References per_tree_port_t::AdminInternalPortPathCost, assign, port_t::bridge, tree_t::BridgePriority, tree_t::BridgeTimes, per_tree_port_t::calledFromFlushRoutine, compute_pcost(), ERROR_PRTNAME, GET_PORT_SPEED, per_tree_port_t::InternalPortPathCost, per_tree_port_t::MSTID, tree_t::MSTID, per_tree_port_t::port, port_t::port_number, per_tree_port_t::portId, per_tree_port_t::portPriority, per_tree_port_t::portTimes, ptp_default_internal_vars(), per_tree_port_t::state, and per_tree_port_t::tree.
Referenced by MSTP_IN_create_msti(), and MSTP_IN_port_create_and_add_tail().
create_tree()
static tree_t * create_tree (bridge_t * br, __u8 * macaddr, __be16 MSTID) static
Definition at line 174 of file mstp.c.
{
    /* Initialize all fields except anchor */
    tree_t *tree = calloc(1, sizeof(*tree));
    if(!tree)
    {
        ERROR_BRNAME(br, "Out of memory");
        return NULL;
    }
    tree->bridge = br;
    tree->MSTID = MSTID;
    INIT_LIST_HEAD(&tree->ports);
    memcpy(tree->BridgeIdentifier.s.mac_address, macaddr, ETH_ALEN);
    /* 0x8000 = default bridge priority (17.14 of 802.1D) */
    tree->BridgeIdentifier.s.priority = __constant_cpu_to_be16(0x8000) | MSTID;
    assign(tree->BridgePriority.RootID, tree->BridgeIdentifier);
    assign(tree->BridgePriority.RRootID, tree->BridgeIdentifier);
    assign(tree->BridgePriority.DesignatedBridgeID, tree->BridgeIdentifier);
    /* 13.23.4 */
    assign(tree->BridgeTimes.remainingHops, br->MaxHops);
    assign(tree->BridgeTimes.Forward_Delay, br->Forward_Delay);
    assign(tree->BridgeTimes.Max_Age, br->Max_Age);
    assign(tree->BridgeTimes.Message_Age, (__u8)0);
    assign(tree->BridgeTimes.Hello_Time, br->Hello_Time);
    tree_default_internal_vars(tree);
    return tree;
}
References assign, tree_t::bridge, tree_t::BridgeIdentifier, tree_t::BridgePriority, tree_t::BridgeTimes, port_priority_vector_t::DesignatedBridgeID, ERROR_BRNAME, bridge_t::Forward_Delay, times_t::Forward_Delay, bridge_t::Hello_Time, times_t::Hello_Time, INIT_LIST_HEAD(), bridge_t::Max_Age, times_t::Max_Age, bridge_t::MaxHops, times_t::Message_Age, tree_t::MSTID, tree_t::ports, times_t::remainingHops, port_priority_vector_t::RootID, port_priority_vector_t::RRootID, and tree_default_internal_vars().
Referenced by MSTP_IN_bridge_create(), and MSTP_IN_create_msti().
fromSameRegion()
static bool fromSameRegion (port_t * prt) static
Definition at line 1795 of file mstp.c.
{
    /* Check for rcvdRSTP is superfluous here */
    if((protoMSTP > prt->rcvdBpduData.protocolVersion)/* || (!prt->rcvdRSTP)*/)
        return false;
    return cmp(prt->bridge->MstConfigId,
               ==, prt->rcvdBpduData.mstConfigurationIdentifier);
}
References port_t::bridge, cmp, bridge_t::MstConfigId, protoMSTP, and port_t::rcvdBpduData.
Referenced by PRSM_to_RECEIVE().
message_role_from_port_role()
static __u8 message_role_from_port_role (per_tree_port_t * ptp) inline static
Definition at line 2380 of file mstp.c.
{
    switch(ptp->role)
    {
        case roleRoot:
            return encodedRoleRoot;
        case roleDesignated:
            return encodedRoleDesignated;
        case roleAlternate:
        case roleBackup:
            return encodedRoleAlternateBackup;
        case roleMaster:
            return encodedRoleMaster;
        default:
            ERROR_PRTNAME(ptp->port->bridge, ptp->port,
                          "Attempt to send from port with Disabled role");
            return encodedRoleAlternateBackup;
    }
}
References port_t::bridge, encodedRoleAlternateBackup, encodedRoleDesignated, encodedRoleMaster, encodedRoleRoot, ERROR_PRTNAME, per_tree_port_t::port, per_tree_port_t::role, roleAlternate, roleBackup, roleDesignated, roleMaster, and roleRoot.
Referenced by txMstp().
MSTP_IN_all_fids_flushed()
void MSTP_IN_all_fids_flushed (per_tree_port_t * ptp)
Definition at line 563 of file mstp.c.
{
    bridge_t *br = ptp->port->bridge;
    ptp->fdbFlush = false;
    if(!br->bridgeEnabled)
        return;
    if(!ptp->calledFromFlushRoutine)
    {
        TCSM_run(ptp, false /* actual run */);
        br_state_machines_run(br);
    }
}
References br_state_machines_run(), port_t::bridge, bridge_t::bridgeEnabled, per_tree_port_t::calledFromFlushRoutine, per_tree_port_t::fdbFlush, per_tree_port_t::port, and TCSM_run().
Referenced by driver_flush_all_fids().
MSTP_IN_bridge_create()
bool MSTP_IN_bridge_create (bridge_t * br, __u8 * macaddr)
Definition at line 236 of file mstp.c.
{
    tree_t *cist;
    if (!driver_create_bridge(br, macaddr))
        return false;
    /* Initialize all fields except sysdeps and anchor */
    INIT_LIST_HEAD(&br->ports);
    INIT_LIST_HEAD(&br->trees);
    br->bridgeEnabled = false;
    memset(br->vid2fid, 0, sizeof(br->vid2fid));
    memset(br->fid2mstid, 0, sizeof(br->fid2mstid));
    assign(br->MstConfigId.s.selector, (__u8)0);
    sprintf((char *)br->MstConfigId.s.configuration_name,
            "%02hhX%02hhX%02hhX%02hhX%02hhX%02hhX",
            macaddr[0], macaddr[1], macaddr[2],
            macaddr[3], macaddr[4], macaddr[5]);
    assign(br->MstConfigId.s.revision_level, __constant_cpu_to_be16(0));
    RecalcConfigDigest(br); /* set br->MstConfigId.s.configuration_digest */
    br->ForceProtocolVersion = protoRSTP;
    assign(br->MaxHops, (__u8)20);       /* 13.37.3 */
    assign(br->Forward_Delay, (__u8)15); /* 17.14 of 802.1D */
    assign(br->Max_Age, (__u8)20);       /* 17.14 of 802.1D */
    assign(br->Transmit_Hold_Count, 6u); /* 17.14 of 802.1D */
    assign(br->Migrate_Time, 3u); /* 17.14 of 802.1D */
    assign(br->Ageing_Time, 300u);/* 8.8.3 Table 8-3 */
    assign(br->Hello_Time, (__u8)2);     /* 17.14 of 802.1D */
    bridge_default_internal_vars(br);
    /* Create CIST */
    if(!(cist = create_tree(br, macaddr, 0)))
        return false;
    list_add_tail(&cist->bridge_list, &br->trees);
    return true;
}
References bridge_t::Ageing_Time, assign, bridge_default_internal_vars(), tree_t::bridge_list, bridge_t::bridgeEnabled, create_tree(), driver_create_bridge(), bridge_t::fid2mstid, bridge_t::ForceProtocolVersion, bridge_t::Forward_Delay, bridge_t::Hello_Time, INIT_LIST_HEAD(), list_add_tail(), bridge_t::Max_Age, bridge_t::MaxHops, bridge_t::Migrate_Time, bridge_t::MstConfigId, bridge_t::ports, protoRSTP, RecalcConfigDigest(), bridge_t::Transmit_Hold_Count, bridge_t::trees, and bridge_t::vid2fid.
Referenced by create_br().
MSTP_IN_create_msti()
bool MSTP_IN_create_msti (bridge_t * br, __u16 mstid)
Definition at line 1467 of file mstp.c.
{
    tree_t *tree, *tree_after, *new_tree;
    per_tree_port_t *ptp, *nxt, *ptp_after, *new_ptp;
    int num_of_mstis;
    __be16 MSTID;
    if((mstid < 1) || (mstid > MAX_MSTID))
    {
        ERROR_BRNAME(br, "Bad MSTID(%hu)", mstid);
        return false;
    }
    MSTID = __cpu_to_be16(mstid);
    /* Find place where to insert new MSTID.
     * Also check if such MSTID is already in the list.
     * Also count existing mstis.
     */
    tree_after = NULL;
    num_of_mstis = 0;
    FOREACH_TREE_IN_BRIDGE(tree, br)
    {
        if(tree->MSTID == MSTID)
        {
            INFO_BRNAME(br, "MSTID(%hu) is already in the list", mstid);
            return true; /* yes, it is success */
        }
        if(cmp(tree->MSTID, <, MSTID))
            tree_after = tree;
        ++num_of_mstis;
    }
    /* Sanity check */
    if(NULL == tree_after)
    {
        ERROR_BRNAME(br, "Can't add MSTID(%hu): no CIST in the list", mstid);
        return false;
    }
    /* End of Sanity check */
    /* Check for "<", not for "<=", as num_of_mstis include CIST */
    if(MAX_IMPLEMENTATION_MSTIS < num_of_mstis)
    {
        ERROR_BRNAME(br, "Can't add MSTID(%hu): maximum count(%u) reached",
                     mstid, MAX_IMPLEMENTATION_MSTIS);
        return false;
    }
    /* Create new tree and its list of PerTreePort structures */
    tree = GET_CIST_TREE(br);
    if(!(new_tree=create_tree(br,tree->BridgeIdentifier.s.mac_address,MSTID)))
        return false;
    FOREACH_PTP_IN_TREE(ptp_after, tree_after)
    {
        if(!(new_ptp = create_ptp(new_tree, ptp_after->port)))
        {
            /* Remove and free all previously created entries in tree's list */
            list_for_each_entry_safe(ptp, nxt, &new_tree->ports, tree_list)
            {
                list_del(&ptp->port_list);
                list_del(&ptp->tree_list);
                free(ptp);
            }
            return false;
        }
        list_add(&new_ptp->port_list, &ptp_after->port_list);
        list_add_tail(&new_ptp->tree_list, &new_tree->ports);
    }
    list_add(&new_tree->bridge_list, &tree_after->bridge_list);
    /* There are no FIDs allocated to this MSTID, so VID-to-MSTID mapping
     *  did not change. So, no need in RecalcConfigDigest.
     * Just initialize state machines for this tree.
     */
    tree_state_machines_begin(new_tree);
    return true;
}
References tree_t::bridge_list, tree_t::BridgeIdentifier, cmp, create_ptp(), create_tree(), ERROR_BRNAME, FOREACH_PTP_IN_TREE, FOREACH_TREE_IN_BRIDGE, GET_CIST_TREE, INFO_BRNAME, list_add(), list_add_tail(), list_del(), list_for_each_entry_safe, MAX_IMPLEMENTATION_MSTIS, MAX_MSTID, tree_t::MSTID, per_tree_port_t::port, per_tree_port_t::port_list, tree_t::ports, per_tree_port_t::tree_list, and tree_state_machines_begin().
MSTP_IN_delete_bridge()
void MSTP_IN_delete_bridge (bridge_t * br)
Definition at line 364 of file mstp.c.
{
    tree_t *tree, *nxt_tree;
    port_t *prt, *nxt_prt;
    driver_delete_bridge(br);
    br->bridgeEnabled = false;
    /* We SHOULD first delete all ports and only THEN delete all tree_t
     * structures as the tree_t structure contains the head for the per-port
     * list of tree data (tree_t.ports).
     * If this list_head will be deleted before all the per_tree_ports
     * bad things will happen ;)
     */
    list_for_each_entry_safe(prt, nxt_prt, &br->ports, br_list)
    {
        MSTP_IN_delete_port(prt);
        free(prt);
    }
    list_for_each_entry_safe(tree, nxt_tree, &br->trees, bridge_list)
    {
        list_del(&tree->bridge_list);
        free(tree);
    }
}
References tree_t::bridge_list, bridge_t::bridgeEnabled, driver_delete_bridge(), list_del(), list_for_each_entry_safe, MSTP_IN_delete_port(), bridge_t::ports, and bridge_t::trees.
Referenced by delete_br_byindex().
MSTP_IN_delete_msti()
bool MSTP_IN_delete_msti (bridge_t * br, __u16 mstid)
Definition at line 1546 of file mstp.c.
{
    tree_t *tree;
    per_tree_port_t *ptp, *nxt;
    int fid;
    bool found;
    __be16 MSTID = __cpu_to_be16(mstid);
    if((mstid < 1) || (mstid > MAX_MSTID))
    {
        ERROR_BRNAME(br, "Bad MSTID(%hu)", mstid);
        return false;
    }
    /* Check if there are FIDs associated with this MSTID */
    for(fid = 0; fid <= MAX_FID; ++fid)
    {
        if(br->fid2mstid[fid] == MSTID)
        {
            ERROR_BRNAME(br,
                "Can't delete MSTID(%hu): there are FIDs allocated to it",
                mstid);
            return false;
        }
    }
    found = false;
    FOREACH_TREE_IN_BRIDGE(tree, br)
    {
        if(tree->MSTID == MSTID)
        {
            found = true;
            break;
        }
    }
    if(!found)
    {
        INFO_BRNAME(br, "MSTID(%hu) is not in the list", mstid);
        return true; /* yes, it is success */
    }
    list_del(&tree->bridge_list);
    list_for_each_entry_safe(ptp, nxt, &tree->ports, tree_list)
    {
        list_del(&ptp->port_list);
        list_del(&ptp->tree_list);
        free(ptp);
    }
    free(tree);
    /* There are no FIDs allocated to this MSTID, so VID-to-MSTID mapping
     *  did not change. So, no need in RecalcConfigDigest.
     * Give state machine a spare run, just for the case...
     */
    br_state_machines_run(br);
    return true;
}
References br_state_machines_run(), tree_t::bridge_list, ERROR_BRNAME, bridge_t::fid2mstid, FOREACH_TREE_IN_BRIDGE, INFO_BRNAME, list_del(), list_for_each_entry_safe, MAX_FID, MAX_MSTID, tree_t::MSTID, per_tree_port_t::port_list, tree_t::ports, and per_tree_port_t::tree_list.
MSTP_IN_delete_port()
void MSTP_IN_delete_port (port_t * prt)
Definition at line 339 of file mstp.c.
{
    per_tree_port_t *ptp, *nxt;
    bridge_t *br = prt->bridge;
    driver_delete_port(prt);
    prt->deleted = true;
    if(prt->portEnabled)
    {
        prt->portEnabled = false;
        br_state_machines_run(br);
    }
    list_for_each_entry_safe(ptp, nxt, &prt->trees, port_list)
    {
        list_del(&ptp->port_list);
        list_del(&ptp->tree_list);
        free(ptp);
    }
    list_del(&prt->br_list);
    br_state_machines_run(br);
}
References port_t::br_list, br_state_machines_run(), port_t::bridge, port_t::deleted, driver_delete_port(), list_del(), list_for_each_entry_safe, per_tree_port_t::port_list, port_t::portEnabled, per_tree_port_t::tree_list, and port_t::trees.
Referenced by delete_if(), and MSTP_IN_delete_bridge().
MSTP_IN_get_cist_bridge_status()
void MSTP_IN_get_cist_bridge_status (bridge_t * br, CIST_BridgeStatus * status)
Definition at line 714 of file mstp.c.
{
    tree_t *cist = GET_CIST_TREE(br);
    assign(status->bridge_id, cist->BridgeIdentifier);
    assign(status->time_since_topology_change,
           cist->time_since_topology_change);
    assign(status->topology_change_count, cist->topology_change_count);
    status->topology_change = cist->topology_change;
    strncpy(status->topology_change_port, cist->topology_change_port,
            IFNAMSIZ);
    strncpy(status->last_topology_change_port, cist->last_topology_change_port,
            IFNAMSIZ);
    assign(status->designated_root, cist->rootPriority.RootID);
    assign(status->root_path_cost,
           __be32_to_cpu(cist->rootPriority.ExtRootPathCost));
    assign(status->regional_root, cist->rootPriority.RRootID);
    assign(status->internal_path_cost,
           __be32_to_cpu(cist->rootPriority.IntRootPathCost));
    assign(status->root_port_id, cist->rootPortId);
    assign(status->root_max_age, cist->rootTimes.Max_Age);
    assign(status->root_forward_delay, cist->rootTimes.Forward_Delay);
    assign(status->bridge_max_age, br->Max_Age);
    assign(status->bridge_forward_delay, br->Forward_Delay);
    assign(status->max_hops, br->MaxHops);
    assign(status->tx_hold_count, br->Transmit_Hold_Count);
    status->protocol_version = br->ForceProtocolVersion;
    status->enabled = br->bridgeEnabled;
    assign(status->bridge_hello_time, br->Hello_Time);
    assign(status->Ageing_Time, br->Ageing_Time);
}
References bridge_t::Ageing_Time, CIST_BridgeStatus::Ageing_Time, assign, CIST_BridgeStatus::bridge_forward_delay, CIST_BridgeStatus::bridge_hello_time, CIST_BridgeStatus::bridge_id, CIST_BridgeStatus::bridge_max_age, bridge_t::bridgeEnabled, tree_t::BridgeIdentifier, CIST_BridgeStatus::designated_root, CIST_BridgeStatus::enabled, port_priority_vector_t::ExtRootPathCost, bridge_t::ForceProtocolVersion, bridge_t::Forward_Delay, times_t::Forward_Delay, GET_CIST_TREE, bridge_t::Hello_Time, CIST_BridgeStatus::internal_path_cost, port_priority_vector_t::IntRootPathCost, CIST_BridgeStatus::last_topology_change_port, tree_t::last_topology_change_port, bridge_t::Max_Age, times_t::Max_Age, CIST_BridgeStatus::max_hops, bridge_t::MaxHops, CIST_BridgeStatus::protocol_version, CIST_BridgeStatus::regional_root, CIST_BridgeStatus::root_forward_delay, CIST_BridgeStatus::root_max_age, CIST_BridgeStatus::root_path_cost, CIST_BridgeStatus::root_port_id, port_priority_vector_t::RootID, tree_t::rootPortId, tree_t::rootPriority, tree_t::rootTimes, port_priority_vector_t::RRootID, CIST_BridgeStatus::time_since_topology_change, tree_t::time_since_topology_change, CIST_BridgeStatus::topology_change, tree_t::topology_change, CIST_BridgeStatus::topology_change_count, tree_t::topology_change_count, CIST_BridgeStatus::topology_change_port, tree_t::topology_change_port, bridge_t::Transmit_Hold_Count, and CIST_BridgeStatus::tx_hold_count.
MSTP_IN_get_cist_port_status()
void MSTP_IN_get_cist_port_status (port_t * prt, CIST_PortStatus * status)
Definition at line 1000 of file mstp.c.
{
    per_tree_port_t *cist = GET_CIST_PTP_FROM_PORT(prt);
    /* 12.8.2.2.3 b) */
    status->uptime = (signed int)((prt->bridge)->uptime)
                     - (signed int)(cist->start_time);
    status->state = cist->state;
    assign(status->port_id, cist->portId);
    assign(status->admin_external_port_path_cost,
           prt->AdminExternalPortPathCost);
    assign(status->external_port_path_cost, prt->ExternalPortPathCost);
    assign(status->designated_root, cist->portPriority.RootID);
    assign(status->designated_external_cost,
           __be32_to_cpu(cist->portPriority.ExtRootPathCost));
    assign(status->designated_bridge, cist->portPriority.DesignatedBridgeID);
    assign(status->designated_port, cist->portPriority.DesignatedPortID);
    assign(status->designated_regional_root, cist->portPriority.RRootID);
    assign(status->designated_internal_cost,
           __be32_to_cpu(cist->portPriority.IntRootPathCost));
    status->tc_ack = prt->tcAck;
    assign(status->port_hello_time, cist->portTimes.Hello_Time);
    status->admin_edge_port = prt->AdminEdgePort;
    status->auto_edge_port = prt->AutoEdge;
    status->oper_edge_port = prt->operEdge;
    status->enabled = prt->portEnabled;
    status->admin_p2p = prt->AdminP2P;
    status->oper_p2p = prt->operPointToPointMAC;
    status->restricted_role = prt->restrictedRole;
    status->restricted_tcn = prt->restrictedTcn;
    status->role = cist->role;
    status->disputed = cist->disputed;
    assign(status->admin_internal_port_path_cost,
           cist->AdminInternalPortPathCost);
    assign(status->internal_port_path_cost, cist->InternalPortPathCost);
    status->bpdu_guard_port = prt->BpduGuardPort;
    status->bpdu_guard_error = prt->BpduGuardError;
    status->network_port = prt->NetworkPort;
    status->ba_inconsistent = prt->BaInconsistent;
    status->bpdu_filter_port = prt->bpduFilterPort;
    status->num_rx_bpdu_filtered = prt->num_rx_bpdu_filtered;
    status->num_rx_bpdu = prt->num_rx_bpdu;
    status->num_rx_tcn = prt->num_rx_tcn;
    status->num_tx_bpdu = prt->num_tx_bpdu;
    status->num_tx_tcn = prt->num_tx_tcn;
    status->num_trans_fwd = prt->num_trans_fwd;
    status->num_trans_blk = prt->num_trans_blk;
    status->rcvdBpdu = prt->rcvdBpdu;
    status->rcvdRSTP = prt->rcvdRSTP;
    status->rcvdSTP = prt->rcvdSTP;
    status->rcvdTcAck = prt->rcvdTcAck;
    status->rcvdTcn = prt->rcvdTcn;
    status->sendRSTP = prt->sendRSTP;
}
References CIST_PortStatus::admin_edge_port, CIST_PortStatus::admin_external_port_path_cost, CIST_PortStatus::admin_internal_port_path_cost, CIST_PortStatus::admin_p2p, port_t::AdminEdgePort, port_t::AdminExternalPortPathCost, per_tree_port_t::AdminInternalPortPathCost, port_t::AdminP2P, assign, CIST_PortStatus::auto_edge_port, port_t::AutoEdge, CIST_PortStatus::ba_inconsistent, port_t::BaInconsistent, CIST_PortStatus::bpdu_filter_port, CIST_PortStatus::bpdu_guard_error, CIST_PortStatus::bpdu_guard_port, port_t::bpduFilterPort, port_t::BpduGuardError, port_t::BpduGuardPort, port_t::bridge, CIST_PortStatus::designated_bridge, CIST_PortStatus::designated_external_cost, CIST_PortStatus::designated_internal_cost, CIST_PortStatus::designated_port, CIST_PortStatus::designated_regional_root, CIST_PortStatus::designated_root, port_priority_vector_t::DesignatedBridgeID, port_priority_vector_t::DesignatedPortID, CIST_PortStatus::disputed, per_tree_port_t::disputed, CIST_PortStatus::enabled, CIST_PortStatus::external_port_path_cost, port_t::ExternalPortPathCost, port_priority_vector_t::ExtRootPathCost, GET_CIST_PTP_FROM_PORT, times_t::Hello_Time, CIST_PortStatus::internal_port_path_cost, per_tree_port_t::InternalPortPathCost, port_priority_vector_t::IntRootPathCost, CIST_PortStatus::network_port, port_t::NetworkPort, CIST_PortStatus::num_rx_bpdu, port_t::num_rx_bpdu, CIST_PortStatus::num_rx_bpdu_filtered, port_t::num_rx_bpdu_filtered, CIST_PortStatus::num_rx_tcn, port_t::num_rx_tcn, CIST_PortStatus::num_trans_blk, port_t::num_trans_blk, CIST_PortStatus::num_trans_fwd, port_t::num_trans_fwd, CIST_PortStatus::num_tx_bpdu, port_t::num_tx_bpdu, CIST_PortStatus::num_tx_tcn, port_t::num_tx_tcn, CIST_PortStatus::oper_edge_port, CIST_PortStatus::oper_p2p, port_t::operEdge, port_t::operPointToPointMAC, CIST_PortStatus::port_hello_time, CIST_PortStatus::port_id, port_t::portEnabled, per_tree_port_t::portId, per_tree_port_t::portPriority, per_tree_port_t::portTimes, CIST_PortStatus::rcvdBpdu, port_t::rcvdBpdu, CIST_PortStatus::rcvdRSTP, port_t::rcvdRSTP, CIST_PortStatus::rcvdSTP, port_t::rcvdSTP, CIST_PortStatus::rcvdTcAck, port_t::rcvdTcAck, CIST_PortStatus::rcvdTcn, port_t::rcvdTcn, CIST_PortStatus::restricted_role, CIST_PortStatus::restricted_tcn, port_t::restrictedRole, port_t::restrictedTcn, CIST_PortStatus::role, per_tree_port_t::role, port_priority_vector_t::RootID, port_priority_vector_t::RRootID, CIST_PortStatus::sendRSTP, port_t::sendRSTP, per_tree_port_t::start_time, CIST_PortStatus::state, per_tree_port_t::state, CIST_PortStatus::tc_ack, port_t::tcAck, and CIST_PortStatus::uptime.
MSTP_IN_get_msti_bridge_status()
void MSTP_IN_get_msti_bridge_status (tree_t * tree, MSTI_BridgeStatus * status)
Definition at line 746 of file mstp.c.
{
    assign(status->bridge_id, tree->BridgeIdentifier);
    assign(status->time_since_topology_change,
           tree->time_since_topology_change);
    assign(status->topology_change_count, tree->topology_change_count);
    status->topology_change = tree->topology_change;
    strncpy(status->topology_change_port, tree->topology_change_port,
            IFNAMSIZ);
    strncpy(status->last_topology_change_port, tree->last_topology_change_port,
            IFNAMSIZ);
    assign(status->regional_root, tree->rootPriority.RRootID);
    assign(status->internal_path_cost,
           __be32_to_cpu(tree->rootPriority.IntRootPathCost));
    assign(status->root_port_id, tree->rootPortId);
}
References assign, MSTI_BridgeStatus::bridge_id, tree_t::BridgeIdentifier, MSTI_BridgeStatus::internal_path_cost, port_priority_vector_t::IntRootPathCost, MSTI_BridgeStatus::last_topology_change_port, tree_t::last_topology_change_port, MSTI_BridgeStatus::regional_root, MSTI_BridgeStatus::root_port_id, tree_t::rootPortId, tree_t::rootPriority, port_priority_vector_t::RRootID, MSTI_BridgeStatus::time_since_topology_change, tree_t::time_since_topology_change, MSTI_BridgeStatus::topology_change, tree_t::topology_change, MSTI_BridgeStatus::topology_change_count, tree_t::topology_change_count, MSTI_BridgeStatus::topology_change_port, and tree_t::topology_change_port.
MSTP_IN_get_msti_port_status()
void MSTP_IN_get_msti_port_status (per_tree_port_t * ptp, MSTI_PortStatus * status)
Definition at line 1055 of file mstp.c.
{
    status->uptime = (signed int)((ptp->port->bridge)->uptime)
                     - (signed int)(ptp->start_time);
    status->state = ptp->state;
    assign(status->port_id, ptp->portId);
    assign(status->admin_internal_port_path_cost,
           ptp->AdminInternalPortPathCost);
    assign(status->internal_port_path_cost, ptp->InternalPortPathCost);
    assign(status->designated_regional_root, ptp->portPriority.RRootID);
    assign(status->designated_internal_cost,
           __be32_to_cpu(ptp->portPriority.IntRootPathCost));
    assign(status->designated_bridge, ptp->portPriority.DesignatedBridgeID);
    assign(status->designated_port, ptp->portPriority.DesignatedPortID);
    status->role = ptp->role;
    status->disputed = ptp->disputed;
}
References MSTI_PortStatus::admin_internal_port_path_cost, per_tree_port_t::AdminInternalPortPathCost, assign, port_t::bridge, MSTI_PortStatus::designated_bridge, MSTI_PortStatus::designated_internal_cost, MSTI_PortStatus::designated_port, MSTI_PortStatus::designated_regional_root, port_priority_vector_t::DesignatedBridgeID, port_priority_vector_t::DesignatedPortID, MSTI_PortStatus::disputed, per_tree_port_t::disputed, MSTI_PortStatus::internal_port_path_cost, per_tree_port_t::InternalPortPathCost, port_priority_vector_t::IntRootPathCost, per_tree_port_t::port, MSTI_PortStatus::port_id, per_tree_port_t::portId, per_tree_port_t::portPriority, MSTI_PortStatus::role, per_tree_port_t::role, port_priority_vector_t::RRootID, per_tree_port_t::start_time, MSTI_PortStatus::state, per_tree_port_t::state, and MSTI_PortStatus::uptime.
MSTP_IN_get_mstilist()
bool MSTP_IN_get_mstilist (bridge_t * br, int * num_mstis, __u16 * mstids)
Definition at line 1450 of file mstp.c.
{
    tree_t *tree;
    *num_mstis = 0;
    FOREACH_TREE_IN_BRIDGE(tree, br)
    {
        mstids[*num_mstis] = __be16_to_cpu(tree->MSTID);
        /* Check for "<", not for "<=", as num_mstis include CIST */
        if(MAX_IMPLEMENTATION_MSTIS < ++(*num_mstis))
            break;
    }
    return true;
}
References FOREACH_TREE_IN_BRIDGE, MAX_IMPLEMENTATION_MSTIS, and tree_t::MSTID.
MSTP_IN_one_second()
void MSTP_IN_one_second (bridge_t * br)
Definition at line 532 of file mstp.c.
{
    port_t *prt;
    tree_t *tree;
    ++(br->uptime);
    if(!br->bridgeEnabled)
        return;
    FOREACH_TREE_IN_BRIDGE(tree, br)
        if(!(tree->topology_change))
            ++(tree->time_since_topology_change);
    FOREACH_PORT_IN_BRIDGE(prt, br)
    {
        PTSM_tick(prt);
        /* support for rapid ageing */
        if(prt->rapidAgeingWhile)
        {
            if((--(prt->rapidAgeingWhile)) == 0)
            {
                if(!prt->deleted)
                    MSTP_OUT_set_ageing_time(prt, br->Ageing_Time);
            }
        }
    }
    br_state_machines_run(br);
}
References bridge_t::Ageing_Time, br_state_machines_run(), bridge_t::bridgeEnabled, port_t::deleted, FOREACH_PORT_IN_BRIDGE, FOREACH_TREE_IN_BRIDGE, MSTP_OUT_set_ageing_time(), PTSM_tick(), port_t::rapidAgeingWhile, tree_t::time_since_topology_change, tree_t::topology_change, and bridge_t::uptime.
Referenced by bridge_one_second().
MSTP_IN_port_create_and_add_tail()
bool MSTP_IN_port_create_and_add_tail (port_t * prt, __u16 portno)
Definition at line 275 of file mstp.c.
{
    tree_t *tree;
    per_tree_port_t *ptp, *nxt;
    bridge_t *br = prt->bridge;
    if (!driver_create_port(prt, portno))
        return false;
    /* Initialize all fields except sysdeps and bridge */
    INIT_LIST_HEAD(&prt->trees);
    prt->port_number = __cpu_to_be16(portno);
    assign(prt->AdminExternalPortPathCost, 0u);
    /* Default for operP2P is false because by default AdminP2P
     * says to auto-detect p2p state, and it is derived from duplex
     * and initially port is in down state and in this down state
     * duplex is set to false (half) */
    prt->AdminP2P = p2pAuto;
    prt->operPointToPointMAC = false;
    prt->portEnabled = false;
    prt->restrictedRole = false; /* 13.25.14 */
    prt->restrictedTcn = false; /* 13.25.15 */
    assign(prt->ExternalPortPathCost, MAX_PATH_COST); /* 13.37.1 */
    prt->AdminEdgePort = false; /* 13.25 */
    prt->AutoEdge = true;       /* 13.25 */
    prt->BpduGuardPort = false;
    prt->BpduGuardError = false;
    prt->NetworkPort = false;
    prt->dontTxmtBpdu = false;
    prt->bpduFilterPort = false;
    prt->deleted = false;
    port_default_internal_vars(prt);
    /* Create PerTreePort structures for all existing trees */
    FOREACH_TREE_IN_BRIDGE(tree, br)
    {
        if(!(ptp = create_ptp(tree, prt)))
        {
            /* Remove and free all previously created entries in port's list */
            list_for_each_entry_safe(ptp, nxt, &prt->trees, port_list)
            {
                list_del(&ptp->port_list);
                list_del(&ptp->tree_list);
                free(ptp);
            }
            return false;
        }
        list_add_tail(&ptp->port_list, &prt->trees);
        list_add_tail(&ptp->tree_list, &tree->ports);
    }
    /* Add new port to the tail of the list in the bridge */
    /* NOTE: if one wants add port NOT to the tail of the list of ports,
     * one should revise above loop (FOREACH_TREE_IN_BRIDGE)
     * because it heavily depends on the fact that port is added to the tail.
     */
    list_add_tail(&prt->br_list, &br->ports);
    prt_state_machines_begin(prt);
    return true;
}
References port_t::AdminEdgePort, port_t::AdminExternalPortPathCost, port_t::AdminP2P, assign, port_t::AutoEdge, port_t::bpduFilterPort, port_t::BpduGuardError, port_t::BpduGuardPort, port_t::br_list, port_t::bridge, create_ptp(), port_t::deleted, port_t::dontTxmtBpdu, driver_create_port(), port_t::ExternalPortPathCost, FOREACH_TREE_IN_BRIDGE, INIT_LIST_HEAD(), list_add_tail(), list_del(), list_for_each_entry_safe, MAX_PATH_COST, port_t::NetworkPort, port_t::operPointToPointMAC, p2pAuto, port_default_internal_vars(), per_tree_port_t::port_list, port_t::port_number, port_t::portEnabled, bridge_t::ports, tree_t::ports, prt_state_machines_begin(), port_t::restrictedRole, port_t::restrictedTcn, per_tree_port_t::tree_list, and port_t::trees.
Referenced by create_if().
MSTP_IN_port_mcheck()
int MSTP_IN_port_mcheck (port_t * prt)
Definition at line 1280 of file mstp.c.
{
    bridge_t *br = prt->bridge;
    per_tree_port_t *cist = GET_CIST_PTP_FROM_PORT(prt);
    if(rstpVersion(br) && prt->portEnabled && br->bridgeEnabled)
    {
        prt->mcheck = true;
        cist->proposing = true;
        br_state_machines_run(br);
    }
    return 0;
}
References br_state_machines_run(), port_t::bridge, bridge_t::bridgeEnabled, GET_CIST_PTP_FROM_PORT, port_t::mcheck, port_t::portEnabled, per_tree_port_t::proposing, and rstpVersion.
MSTP_IN_rx_bpdu()
void MSTP_IN_rx_bpdu (port_t * prt, bpdu_t * bpdu, int size)
Definition at line 579 of file mstp.c.
{
    int mstis_size;
    bridge_t *br = prt->bridge;
    ++(prt->num_rx_bpdu);
    if(prt->BpduGuardPort)
    {
        prt->BpduGuardError = true;
        ERROR_PRTNAME(br, prt,
                      "Received BPDU on BPDU Guarded Port - Port Down");
        MSTP_OUT_shutdown_port(prt);
        return;
    }
    if(prt->bpduFilterPort)
    {
        LOG_PRTNAME(br, prt,
                   "Received BPDU on BPDU Filtered Port - discarded");
        ++(prt->num_rx_bpdu_filtered);
        return;
    }
    if(!br->bridgeEnabled)
    {
        INFO_PRTNAME(br, prt, "Received BPDU while bridge is disabled");
        return;
    }
    if(prt->rcvdBpdu)
    {
        ERROR_PRTNAME(br, prt, "Port hasn't processed previous BPDU");
        return;
    }
    /* 14.4 Validation */
    if((TCN_BPDU_SIZE > size) || (0 != bpdu->protocolIdentifier))
    {
bpdu_validation_failed:
        INFO_PRTNAME(br, prt, "BPDU validation failed");
        return;
    }
    switch(bpdu->bpduType)
    {
        case bpduTypeTCN:
            /* 14.4.b) */
            /* Valid TCN BPDU */
            bpdu->protocolVersion = protoSTP;
            LOG_PRTNAME(br, prt, "received TCN BPDU");
            break;
        case bpduTypeConfig:
            /* 14.4.a) */
            if(CONFIG_BPDU_SIZE > size)
                goto bpdu_validation_failed;
            /* Valid Config BPDU */
            bpdu->protocolVersion = protoSTP;
            LOG_PRTNAME(br, prt, "received Config BPDU%s",
                        (bpdu->flags & (1 << offsetTc)) ? ", tcFlag" : ""
                       );
            break;
        case bpduTypeRST:
            if(protoRSTP == bpdu->protocolVersion)
            { /* 14.4.c) */
                if(RST_BPDU_SIZE > size)
                    goto bpdu_validation_failed;
                /* Valid RST BPDU */
                /* bpdu->protocolVersion = protoRSTP; */
                LOG_PRTNAME(br, prt, "received RST BPDU%s",
                            (bpdu->flags & (1 << offsetTc)) ? ", tcFlag" : ""
                           );
                break;
            }
            if(protoMSTP > bpdu->protocolVersion)
                goto bpdu_validation_failed;
            /* Yes, 802.1Q-2005 says here to check if it contains
             * "35 or more octets", not 36! (see 14.4.d).1) )
             * That's why I check size against CONFIG_BPDU_SIZE
             * and not RST_BPDU_SIZE.
             */
            if(CONFIG_BPDU_SIZE > size)
                goto bpdu_validation_failed;
            mstis_size = __be16_to_cpu(bpdu->version3_len)
                         - MST_BPDU_VER3LEN_WO_MSTI_MSGS;
            if((MST_BPDU_SIZE_WO_MSTI_MSGS > size) || (0 != bpdu->version1_len)
               || (0 > mstis_size)
               || ((MAX_STANDARD_MSTIS * sizeof(msti_configuration_message_t))
                   < mstis_size)
               || (0 != (mstis_size % sizeof(msti_configuration_message_t)))
              )
            { /* 14.4.d) */
                /* Valid RST BPDU */
                bpdu->protocolVersion = protoRSTP;
                LOG_PRTNAME(br, prt, "received RST BPDU");
                break;
            }
            /* 14.4.e) */
            /* Valid MST BPDU */
            bpdu->protocolVersion = protoMSTP;
            prt->rcvdBpduNumOfMstis = mstis_size
                                      / sizeof(msti_configuration_message_t);
            LOG_PRTNAME(br, prt, "received MST BPDU%s with %d MSTIs",
                        (bpdu->flags & (1 << offsetTc)) ? ", tcFlag" : "",
                        prt->rcvdBpduNumOfMstis
                       );
            break;
        default:
            goto bpdu_validation_failed;
    }
    if((protoSTP == bpdu->protocolVersion) && (bpduTypeTCN == bpdu->bpduType))
    {
        ++(prt->num_rx_tcn);
    }
    else
    {
        if(bpdu->flags & (1 << offsetTc))
            ++(prt->num_rx_tcn);
    }
    assign(prt->rcvdBpduData, *bpdu);
    prt->rcvdBpdu = true;
    /* Reset bridge assurance on receipt of valid BPDU */
    if(prt->BaInconsistent)
    {
        prt->BaInconsistent = false;
        INFO_PRTNAME(br, prt, "Clear Bridge assurance inconsistency");
    }
    updtbrAssuRcvdInfoWhile(prt);
    br_state_machines_run(br);
}
References assign, port_t::BaInconsistent, port_t::bpduFilterPort, port_t::BpduGuardError, port_t::BpduGuardPort, bpduTypeConfig, bpduTypeRST, bpduTypeTCN, br_state_machines_run(), port_t::bridge, bridge_t::bridgeEnabled, CONFIG_BPDU_SIZE, ERROR_PRTNAME, INFO_PRTNAME, LOG_PRTNAME, MAX_STANDARD_MSTIS, MST_BPDU_SIZE_WO_MSTI_MSGS, MST_BPDU_VER3LEN_WO_MSTI_MSGS, MSTP_OUT_shutdown_port(), port_t::num_rx_bpdu, port_t::num_rx_bpdu_filtered, port_t::num_rx_tcn, offsetTc, protoMSTP, protoRSTP, protoSTP, port_t::rcvdBpdu, port_t::rcvdBpduData, port_t::rcvdBpduNumOfMstis, RST_BPDU_SIZE, TCN_BPDU_SIZE, and updtbrAssuRcvdInfoWhile().
Referenced by bridge_bpdu_rcv().
MSTP_IN_set_all_fids2mstids()
bool MSTP_IN_set_all_fids2mstids (bridge_t * br, __u16 * fids2mstids)
Definition at line 1394 of file mstp.c.
{
    tree_t *tree;
    __be16 MSTID[MAX_FID + 1];
    bool found, vid2mstid_changed;
    int fid, vid;
    __be16 prev_vid2mstid[MAX_VID + 2];
    for(fid = 0; fid <= MAX_FID; ++fid)
    {
        if(fids2mstids[fid] > MAX_MSTID)
        { /* Incorrect value == keep prev value */
            fids2mstids[fid] = __be16_to_cpu(MSTID[fid] = br->fid2mstid[fid]);
        }
        else
            MSTID[fid] = __cpu_to_be16(fids2mstids[fid]);
        found = false;
        FOREACH_TREE_IN_BRIDGE(tree, br)
        {
            if(tree->MSTID == MSTID[fid])
            {
                found = true;
                break;
            }
        }
        if(!found)
        {
            ERROR_BRNAME(br,
                "Error allocating FID(%hu) to MSTID(%hu): MSTID not found",
                fid, fids2mstids[fid]);
            return false;
        }
    }
    for(vid = 1; vid <= MAX_VID; ++vid)
        prev_vid2mstid[vid] = br->fid2mstid[br->vid2fid[vid]];
    memcpy(br->fid2mstid, MSTID, sizeof(br->fid2mstid));
    vid2mstid_changed = false;
    for(vid = 1; vid <= MAX_VID; ++vid)
    {
        if(prev_vid2mstid[vid] != br->fid2mstid[br->vid2fid[vid]])
        {
            vid2mstid_changed = true;
            break;
        }
    }
    if(vid2mstid_changed)
    {
        RecalcConfigDigest(br);
        br_state_machines_begin(br);
    }
    return true;
}
References br_state_machines_begin(), ERROR_BRNAME, bridge_t::fid2mstid, FOREACH_TREE_IN_BRIDGE, MAX_FID, MAX_MSTID, MAX_VID, tree_t::MSTID, RecalcConfigDigest(), and bridge_t::vid2fid.
MSTP_IN_set_all_vids2fids()
bool MSTP_IN_set_all_vids2fids (bridge_t * br, __u16 * vids2fids)
Definition at line 1319 of file mstp.c.
{
    bool vid2mstid_changed;
    int vid;
    vid2mstid_changed = false;
    for(vid = 1; vid <= MAX_VID; ++vid)
    {
        if(vids2fids[vid] > MAX_FID)
        { /* Incorrect value == keep prev value */
            vids2fids[vid] = br->vid2fid[vid];
            continue;
        }
        if(br->fid2mstid[vids2fids[vid]] != br->fid2mstid[br->vid2fid[vid]])
            vid2mstid_changed = true;
    }
    memcpy(br->vid2fid, vids2fids, sizeof(br->vid2fid));
    if(vid2mstid_changed)
    {
        RecalcConfigDigest(br);
        br_state_machines_begin(br);
    }
    return true;
}
References br_state_machines_begin(), bridge_t::fid2mstid, MAX_FID, MAX_VID, RecalcConfigDigest(), and bridge_t::vid2fid.
MSTP_IN_set_bridge_address()
void MSTP_IN_set_bridge_address (bridge_t * br, __u8 * macaddr)
Definition at line 393 of file mstp.c.
{
    tree_t *tree;
    bool changed = false;
    FOREACH_TREE_IN_BRIDGE(tree, br)
    {
        if(0 == memcmp(tree->BridgeIdentifier.s.mac_address, macaddr, ETH_ALEN))
            continue;
        changed = true;
        memcpy(tree->BridgeIdentifier.s.mac_address, macaddr, ETH_ALEN);
        tree->BridgePriority.RootID = tree->BridgePriority.RRootID =
            tree->BridgePriority.DesignatedBridgeID = tree->BridgeIdentifier;
    }
    if(changed)
        br_state_machines_begin(br);
}
References br_state_machines_begin(), tree_t::BridgeIdentifier, tree_t::BridgePriority, port_priority_vector_t::DesignatedBridgeID, FOREACH_TREE_IN_BRIDGE, port_priority_vector_t::RootID, and port_priority_vector_t::RRootID.
Referenced by set_br_up(), and set_if_up().
MSTP_IN_set_bridge_enable()
void MSTP_IN_set_bridge_enable (bridge_t * br, bool up)
Definition at line 412 of file mstp.c.
{
    port_t *prt;
    per_tree_port_t *ptp;
    tree_t *tree;
    if(br->bridgeEnabled == up)
        return;
    br->bridgeEnabled = up;
    /* Reset all internal states and variables,
     * except those which are user-configurable */
    bridge_default_internal_vars(br);
    FOREACH_TREE_IN_BRIDGE(tree, br)
    {
        tree_default_internal_vars(tree);
    }
    FOREACH_PORT_IN_BRIDGE(prt, br)
    {
        /* NOTE: Don't check prt->deleted here, as it is imposible condition */
        /* NOTE: In the port_default_internal_vars() rapidAgeingWhile will be
         *  reset, so we should stop rapid ageing procedure here.
         */
        if(prt->rapidAgeingWhile)
        {
            MSTP_OUT_set_ageing_time(prt, br->Ageing_Time);
        }
        port_default_internal_vars(prt);
        FOREACH_PTP_IN_PORT(ptp, prt)
        {
            if(BR_STATE_DISABLED != ptp->state)
            {
                MSTP_OUT_set_state(ptp, BR_STATE_DISABLED);
            }
            ptp_default_internal_vars(ptp);
        }
    }
    br_state_machines_begin(br);
}
References bridge_t::Ageing_Time, br_state_machines_begin(), bridge_default_internal_vars(), bridge_t::bridgeEnabled, FOREACH_PORT_IN_BRIDGE, FOREACH_PTP_IN_PORT, FOREACH_TREE_IN_BRIDGE, MSTP_OUT_set_ageing_time(), MSTP_OUT_set_state(), port_default_internal_vars(), ptp_default_internal_vars(), port_t::rapidAgeingWhile, per_tree_port_t::state, and tree_default_internal_vars().
Referenced by set_br_up().
MSTP_IN_set_cist_bridge_config()
int MSTP_IN_set_cist_bridge_config (bridge_t * br, CIST_BridgeConfig * cfg)
Definition at line 764 of file mstp.c.
{
    bool changed, changedBridgeTimes, init;
    int r = 0;
    __u8 new_forward_delay, new_max_age;
    tree_t *tree;
    port_t *prt;
    per_tree_port_t *ptp;
    /* Firstly, validation */
    if(cfg->set_bridge_max_age)
    {
        new_max_age = cfg->bridge_max_age;
        if((6 > new_max_age) || (40 < new_max_age))
        {
            ERROR_BRNAME(br,
                "Bridge Max Age must be between 6 and 40 seconds");
            r = -1;
        }
    }
    else
        new_max_age = br->Max_Age;
    if(cfg->set_bridge_forward_delay)
    {
        new_forward_delay = cfg->bridge_forward_delay;
        if((4 > new_forward_delay) || (30 < new_forward_delay))
        {
            ERROR_BRNAME(br,
                "Bridge Forward Delay must be between 4 and 30 seconds");
            r = -1;
        }
    }
    else
        new_forward_delay = br->Forward_Delay;
    if(cfg->set_bridge_max_age || cfg->set_bridge_forward_delay)
    {
        if((2 * (new_forward_delay - 1)) < new_max_age)
        {
            ERROR_BRNAME(br, "Configured Bridge Times don't meet "
                "2 * (Bridge Foward Delay - 1 second) >= Bridge Max Age");
            r = -1;
        }
    }
    if(cfg->set_protocol_version)
    {
        switch(cfg->protocol_version)
        {
            case protoSTP:
            case protoRSTP:
            case protoMSTP:
                break;
            default:
                ERROR_BRNAME(br, "Bad protocol version (%d)",
                             cfg->protocol_version);
                r = -1;
        }
    }
    if(cfg->set_tx_hold_count)
    {
        if((1 > cfg->tx_hold_count) || (10 < cfg->tx_hold_count))
        {
            ERROR_BRNAME(br,
                "Transmit Hold Count must be between 1 and 10 seconds");
            r = -1;
        }
    }
    if(cfg->set_max_hops)
    {
        if((6 > cfg->max_hops) || (40 < cfg->max_hops))
        {
            ERROR_BRNAME(br, "Bridge Max Hops must be between 6 and 40");
            r = -1;
        }
    }
    if(cfg->set_bridge_hello_time)
    {
        if((1 > cfg->bridge_hello_time) || (10 < cfg->bridge_hello_time))
        {
            ERROR_BRNAME(br, "Bridge Hello Time must be between 1 and 10");
            r = -1;
        }
    }
    if(cfg->set_bridge_ageing_time)
    {
        if((10 > cfg->bridge_ageing_time)||(1000000 < cfg->bridge_ageing_time))
        {
            ERROR_BRNAME(br,
                "Bridge Ageing Time must be between 10 and 1000000 seconds");
            r = -1;
        }
    }
    if(r)
        return r;
    /* Secondly, do set */
    changed = changedBridgeTimes = init = false;
    if(cfg->set_bridge_max_age || cfg->set_bridge_forward_delay)
    {
        if(cmp(new_max_age, !=, br->Max_Age)
           || cmp(new_forward_delay, !=, br->Forward_Delay)
          )
        {
            assign(br->Max_Age, new_max_age);
            assign(br->Forward_Delay, new_forward_delay);
            changed = changedBridgeTimes = true;
        }
    }
    if((cfg->set_protocol_version)
       && (cfg->protocol_version != br->ForceProtocolVersion)
      )
    {
        br->ForceProtocolVersion = cfg->protocol_version;
        changed = init = true;
    }
    if(cfg->set_tx_hold_count)
    {
        if(cfg->tx_hold_count != br->Transmit_Hold_Count)
        {
            assign(br->Transmit_Hold_Count, cfg->tx_hold_count);
            FOREACH_PORT_IN_BRIDGE(prt, br)
                assign(prt->txCount, 0u);
            changed = true;
        }
    }
    if(cfg->set_max_hops)
    {
        if(cfg->max_hops != br->MaxHops)
        {
            assign(br->MaxHops, cfg->max_hops);
            changed = changedBridgeTimes = true;
        }
    }
    if(cfg->set_bridge_hello_time)
    {
        if(cfg->bridge_hello_time != br->Hello_Time)
        {
            INFO_BRNAME(br, "bridge hello_time new=%hhu, old=%hhu",
                        cfg->bridge_hello_time, br->Hello_Time);
            assign(br->Hello_Time, cfg->bridge_hello_time);
            changed = changedBridgeTimes = true;
        }
    }
    if(cfg->set_bridge_ageing_time)
    {
        if(cfg->bridge_ageing_time != br->Ageing_Time)
        {
            INFO_BRNAME(br, "bridge ageing_time new=%u, old=%u",
                        cfg->bridge_ageing_time, br->Ageing_Time);
            assign(br->Ageing_Time, cfg->bridge_ageing_time);
        }
    }
    /* Thirdly, finalize changes */
    if(changedBridgeTimes)
    {
        FOREACH_TREE_IN_BRIDGE(tree, br)
        {
            assign(tree->BridgeTimes.remainingHops, br->MaxHops);
            assign(tree->BridgeTimes.Forward_Delay, br->Forward_Delay);
            assign(tree->BridgeTimes.Max_Age, br->Max_Age);
            assign(tree->BridgeTimes.Hello_Time, br->Hello_Time);
        /* Comment found in rstpd by Srinivas Aji:
         * Do this for any change in BridgeTimes.
         * Otherwise we fail UNH rstp.op_D test 3.2 since when administratively
         * setting BridgeForwardDelay, etc, the values don't propagate from
         * rootTimes to designatedTimes immediately without this change.
         */
            FOREACH_PTP_IN_TREE(ptp, tree)
            {
                ptp->selected = false;
                ptp->reselect = true;
                /* TODO: change this when Hello_Time will be configurable
                 *   per-port. For now, copy Bridge's Hello_Time
                 *   to the port's Hello_Time.
                 */
                assign(ptp->portTimes.Hello_Time, br->Hello_Time);
            }
        }
    }
    if(changed && br->bridgeEnabled)
    {
        if(init)
            br_state_machines_begin(br);
        else
            br_state_machines_run(br);
    }
    return 0;
}
References bridge_t::Ageing_Time, assign, br_state_machines_begin(), br_state_machines_run(), CIST_BridgeConfig::bridge_ageing_time, CIST_BridgeConfig::bridge_forward_delay, CIST_BridgeConfig::bridge_hello_time, CIST_BridgeConfig::bridge_max_age, bridge_t::bridgeEnabled, tree_t::BridgeTimes, cmp, ERROR_BRNAME, bridge_t::ForceProtocolVersion, FOREACH_PORT_IN_BRIDGE, FOREACH_PTP_IN_TREE, FOREACH_TREE_IN_BRIDGE, bridge_t::Forward_Delay, times_t::Forward_Delay, bridge_t::Hello_Time, times_t::Hello_Time, INFO_BRNAME, bridge_t::Max_Age, times_t::Max_Age, CIST_BridgeConfig::max_hops, bridge_t::MaxHops, per_tree_port_t::portTimes, CIST_BridgeConfig::protocol_version, protoMSTP, protoRSTP, protoSTP, r, times_t::remainingHops, per_tree_port_t::reselect, per_tree_port_t::selected, CIST_BridgeConfig::set_bridge_ageing_time, CIST_BridgeConfig::set_bridge_forward_delay, CIST_BridgeConfig::set_bridge_hello_time, CIST_BridgeConfig::set_bridge_max_age, CIST_BridgeConfig::set_max_hops, CIST_BridgeConfig::set_protocol_version, CIST_BridgeConfig::set_tx_hold_count, bridge_t::Transmit_Hold_Count, CIST_BridgeConfig::tx_hold_count, and port_t::txCount.
Referenced by bridge_create().
MSTP_IN_set_cist_port_config()
int MSTP_IN_set_cist_port_config (port_t * prt, CIST_PortConfig * cfg)
Definition at line 1075 of file mstp.c.
{
    bool changed;
    __u32 new_ExternalPathCost;
    bool new_p2p;
    per_tree_port_t *cist;
    bridge_t *br = prt->bridge;
    /* Firstly, validation */
    if(cfg->set_admin_p2p)
    {
        switch(cfg->admin_p2p)
        {
            case p2pAuto:
            case p2pForceTrue:
            case p2pForceFalse:
                break;
            default:
                cfg->admin_p2p = p2pAuto;
        }
    }
    /* Secondly, do set */
    changed = false;
    if(cfg->set_admin_external_port_path_cost)
    {
        prt->AdminExternalPortPathCost = cfg->admin_external_port_path_cost;
        new_ExternalPathCost = (0 == prt->AdminExternalPortPathCost) ?
                                 compute_pcost(GET_PORT_SPEED(prt))
                               : prt->AdminExternalPortPathCost;
        if(prt->ExternalPortPathCost != new_ExternalPathCost)
        {
            assign(prt->ExternalPortPathCost, new_ExternalPathCost);
            changed = true;
            /* 12.8.2.3.4 */
            cist = GET_CIST_PTP_FROM_PORT(prt);
            cist->selected = false;
            cist->reselect = true;
        }
    }
    if(cfg->set_admin_p2p)
    {
        prt->AdminP2P = cfg->admin_p2p;
        switch(prt->AdminP2P)
        {
            case p2pForceTrue:
                new_p2p = true;
                break;
            case p2pForceFalse:
                new_p2p = false;
                break;
            case p2pAuto:
            default:
                new_p2p = !!GET_PORT_DUPLEX(prt);
                break;
        }
        if(prt->operPointToPointMAC != new_p2p)
        {
            prt->operPointToPointMAC = new_p2p;
            changed = true;
        }
    }
    if(cfg->set_admin_edge_port)
    {
        if(prt->AdminEdgePort != cfg->admin_edge_port)
        {
            prt->AdminEdgePort = cfg->admin_edge_port;
            BDSM_begin(prt);
            changed = true;
        }
    }
    if(cfg->set_auto_edge_port)
    {
        if(prt->AutoEdge != cfg->auto_edge_port)
        {
            prt->AutoEdge = cfg->auto_edge_port;
            changed = true;
        }
    }
    if(cfg->set_restricted_role)
    {
        if(prt->restrictedRole != cfg->restricted_role)
        {
            prt->restrictedRole = cfg->restricted_role;
            changed = true;
        }
    }
    if(cfg->set_restricted_tcn)
    {
        if(prt->restrictedTcn != cfg->restricted_tcn)
        {
            prt->restrictedTcn = cfg->restricted_tcn;
            changed = true;
        }
    }
    if(cfg->set_bpdu_guard_port)
    {
        if(prt->BpduGuardPort != cfg->bpdu_guard_port)
        {
            prt->BpduGuardPort = cfg->bpdu_guard_port;
            INFO_PRTNAME(br, prt,"BpduGuardPort new=%d", prt->BpduGuardPort);
        }
    }
    if(cfg->set_network_port)
    {
        if(prt->NetworkPort != cfg->network_port)
        {
            prt->NetworkPort = cfg->network_port;
            INFO_PRTNAME(br, prt, "NetworkPort new=%d", prt->NetworkPort);
            /* When Network port config is removed and bridge assurance
             * inconsistency is set, clear the inconsistency.
             */
            if(!prt->NetworkPort && prt->BaInconsistent)
            {
                prt->BaInconsistent = false;
                INFO_PRTNAME(br, prt, "Clear Bridge assurance inconsistency");
            }
            changed = true;
        }
    }
    if(cfg->set_dont_txmt)
    {
        if(prt->dontTxmtBpdu != cfg->dont_txmt)
        {
            prt->dontTxmtBpdu = cfg->dont_txmt;
            INFO_PRTNAME(br, prt, "donttxmt new=%d", prt->dontTxmtBpdu);
        }
    }
    if(cfg->set_bpdu_filter_port)
    {
        if (prt->bpduFilterPort != cfg->bpdu_filter_port)
        {
            prt->bpduFilterPort = cfg->bpdu_filter_port;
            prt->num_rx_bpdu_filtered = 0;
            INFO_PRTNAME(br, prt,"bpduFilterPort new=%d", prt->bpduFilterPort);
        }
    }
    if(changed && prt->portEnabled)
        br_state_machines_run(prt->bridge);
    return 0;
}
References CIST_PortConfig::admin_edge_port, CIST_PortConfig::admin_external_port_path_cost, CIST_PortConfig::admin_p2p, port_t::AdminEdgePort, port_t::AdminExternalPortPathCost, port_t::AdminP2P, assign, CIST_PortConfig::auto_edge_port, port_t::AutoEdge, port_t::BaInconsistent, BDSM_begin(), CIST_PortConfig::bpdu_filter_port, CIST_PortConfig::bpdu_guard_port, port_t::bpduFilterPort, port_t::BpduGuardPort, br_state_machines_run(), port_t::bridge, compute_pcost(), CIST_PortConfig::dont_txmt, port_t::dontTxmtBpdu, port_t::ExternalPortPathCost, GET_CIST_PTP_FROM_PORT, GET_PORT_DUPLEX, GET_PORT_SPEED, INFO_PRTNAME, CIST_PortConfig::network_port, port_t::NetworkPort, port_t::num_rx_bpdu_filtered, port_t::operPointToPointMAC, p2pAuto, p2pForceFalse, p2pForceTrue, port_t::portEnabled, per_tree_port_t::reselect, CIST_PortConfig::restricted_role, CIST_PortConfig::restricted_tcn, port_t::restrictedRole, port_t::restrictedTcn, per_tree_port_t::selected, CIST_PortConfig::set_admin_edge_port, CIST_PortConfig::set_admin_external_port_path_cost, CIST_PortConfig::set_admin_p2p, CIST_PortConfig::set_auto_edge_port, CIST_PortConfig::set_bpdu_filter_port, CIST_PortConfig::set_bpdu_guard_port, CIST_PortConfig::set_dont_txmt, CIST_PortConfig::set_network_port, CIST_PortConfig::set_restricted_role, and CIST_PortConfig::set_restricted_tcn.
Referenced by set_if_up().
MSTP_IN_set_fid2mstid()
bool MSTP_IN_set_fid2mstid (bridge_t * br, __u16 fid, __u16 mstid)
Definition at line 1346 of file mstp.c.
{
    tree_t *tree;
    __be16 MSTID;
    bool found;
    int vid;
    if(fid > MAX_FID)
    {
        ERROR_BRNAME(br, "Bad FID(%hu)", fid);
        return false;
    }
    MSTID = __cpu_to_be16(mstid);
    found = false;
    FOREACH_TREE_IN_BRIDGE(tree, br)
    {
        if(tree->MSTID == MSTID)
        {
            found = true;
            break;
        }
    }
    if(!found)
    {
        ERROR_BRNAME(br, "MSTID(%hu) not found", mstid);
        return false;
    }
    if(br->fid2mstid[fid] != MSTID)
    {
        br->fid2mstid[fid] = MSTID;
        /* check if there are VLANs using this FID */
        for(vid = 1; vid <= MAX_VID; ++vid)
        {
            if(br->vid2fid[vid] == fid)
            {
                RecalcConfigDigest(br);
                br_state_machines_begin(br);
                break;
            }
        }
    }
    return true;
}
References br_state_machines_begin(), ERROR_BRNAME, bridge_t::fid2mstid, FOREACH_TREE_IN_BRIDGE, MAX_FID, MAX_VID, tree_t::MSTID, RecalcConfigDigest(), and bridge_t::vid2fid.
MSTP_IN_set_mst_config_id()
void MSTP_IN_set_mst_config_id (bridge_t * br, __u16 revision, __u8 * name)
Definition at line 1605 of file mstp.c.
{
    __be16 valueRevision = __cpu_to_be16(revision);
    bool changed = (0 != strncmp((char *)name, (char *)br->MstConfigId.s.configuration_name,
                                 sizeof(br->MstConfigId.s.configuration_name))
                   )
                   || (valueRevision != br->MstConfigId.s.revision_level);
    if(changed)
    {
        assign(br->MstConfigId.s.revision_level, valueRevision);
        memset(br->MstConfigId.s.configuration_name, 0,
               sizeof(br->MstConfigId.s.configuration_name));
        strncpy((char *)br->MstConfigId.s.configuration_name, (char *)name,
                sizeof(br->MstConfigId.s.configuration_name) - 1);
        br_state_machines_begin(br);
    }
}
References assign, br_state_machines_begin(), and bridge_t::MstConfigId.
MSTP_IN_set_msti_bridge_config()
int MSTP_IN_set_msti_bridge_config (tree_t * tree, __u8 bridge_priority)
Definition at line 970 of file mstp.c.
{
    per_tree_port_t *ptp;
    __u8 valuePri;
    if(15 < bridge_priority)
    {
        ERROR_BRNAME(tree->bridge,
                     "MSTI %hu: Bridge Priority must be between 0 and 15",
                     __be16_to_cpu(tree->MSTID));
        return -1;
    }
    valuePri = bridge_priority << 4;
    if(GET_PRIORITY_FROM_IDENTIFIER(tree->BridgeIdentifier) == valuePri)
        return 0;
    SET_PRIORITY_IN_IDENTIFIER(valuePri, tree->BridgeIdentifier);
    tree->BridgePriority.RootID = tree->BridgePriority.RRootID =
        tree->BridgePriority.DesignatedBridgeID = tree->BridgeIdentifier;
    /* 12.8.1.4.4 do not require reselect, but I think it is needed,
     *  because 12.8.1.3.4.c) requires it */
    FOREACH_PTP_IN_TREE(ptp, tree)
    {
        ptp->selected = false;
        ptp->reselect = true;
    }
    return 0;
}
References tree_t::bridge, tree_t::BridgeIdentifier, tree_t::BridgePriority, port_priority_vector_t::DesignatedBridgeID, ERROR_BRNAME, FOREACH_PTP_IN_TREE, GET_PRIORITY_FROM_IDENTIFIER, tree_t::MSTID, per_tree_port_t::reselect, port_priority_vector_t::RootID, port_priority_vector_t::RRootID, per_tree_port_t::selected, and SET_PRIORITY_IN_IDENTIFIER.
MSTP_IN_set_msti_port_config()
int MSTP_IN_set_msti_port_config (per_tree_port_t * ptp, MSTI_PortConfig * cfg)
Definition at line 1230 of file mstp.c.
{
    __u8 valuePri;
    __u32 new_InternalPathCost;
    bool changed = false;
    port_t *prt = ptp->port;
    bridge_t *br = prt->bridge;
    if(cfg->set_port_priority)
    {
        if(15 < cfg->port_priority)
        {
            ERROR_MSTINAME(br, prt, ptp,
                           "Port Priority must be between 0 and 15");
            return -1;
        }
        valuePri = cfg->port_priority << 4;
        if(GET_PRIORITY_FROM_IDENTIFIER(ptp->portId) != valuePri)
        {
            SET_PRIORITY_IN_IDENTIFIER(valuePri, ptp->portId);
            changed = true;
        }
    }
    if(cfg->set_admin_internal_port_path_cost)
    {
        ptp->AdminInternalPortPathCost = cfg->admin_internal_port_path_cost;
        new_InternalPathCost = (0 == ptp->AdminInternalPortPathCost) ?
                                 compute_pcost(GET_PORT_SPEED(prt))
                               : ptp->AdminInternalPortPathCost;
        if(ptp->InternalPortPathCost != new_InternalPathCost)
        {
            assign(ptp->InternalPortPathCost, new_InternalPathCost);
            changed = true;
        }
    }
    if(changed && prt->portEnabled)
    {
        /* 12.8.2.4.4 */
        ptp->selected = false;
        ptp->reselect = true;
        br_state_machines_run(br);
    }
    return 0;
}
References MSTI_PortConfig::admin_internal_port_path_cost, per_tree_port_t::AdminInternalPortPathCost, assign, br_state_machines_run(), port_t::bridge, compute_pcost(), ERROR_MSTINAME, GET_PORT_SPEED, GET_PRIORITY_FROM_IDENTIFIER, per_tree_port_t::InternalPortPathCost, per_tree_port_t::port, MSTI_PortConfig::port_priority, port_t::portEnabled, per_tree_port_t::portId, per_tree_port_t::reselect, per_tree_port_t::selected, MSTI_PortConfig::set_admin_internal_port_path_cost, MSTI_PortConfig::set_port_priority, and SET_PRIORITY_IN_IDENTIFIER.
MSTP_IN_set_port_enable()
void MSTP_IN_set_port_enable (port_t * prt, bool up, int speed, int duplex)
Definition at line 452 of file mstp.c.
{
    __u32 computed_pcost, new_ExternalPathCost, new_InternalPathCost;
    per_tree_port_t *ptp;
    bool new_p2p;
    bool changed = false;
    if(up)
    {
        computed_pcost = compute_pcost(speed);
        new_ExternalPathCost = (0 == prt->AdminExternalPortPathCost) ?
                                 computed_pcost
                               : prt->AdminExternalPortPathCost;
        if(prt->ExternalPortPathCost != new_ExternalPathCost)
        {
            assign(prt->ExternalPortPathCost, new_ExternalPathCost);
            changed = true;
        }
        FOREACH_PTP_IN_PORT(ptp, prt)
        {
            new_InternalPathCost = (0 == ptp->AdminInternalPortPathCost) ?
                                    computed_pcost
                                   : ptp->AdminInternalPortPathCost;
            if(ptp->InternalPortPathCost != new_InternalPathCost)
            {
                assign(ptp->InternalPortPathCost, new_InternalPathCost);
                changed = true;
            }
        }
        switch(prt->AdminP2P)
        {
            case p2pForceTrue:
                new_p2p = true;
                break;
            case p2pForceFalse:
                new_p2p = false;
                break;
            case p2pAuto:
            default:
                new_p2p = !!duplex;
                break;
        }
        if(prt->operPointToPointMAC != new_p2p)
        {
            prt->operPointToPointMAC = new_p2p;
            changed = true;
        }
        if(!prt->portEnabled)
        {
            prt->portEnabled = true;
            prt->BpduGuardError = false;
            prt->BaInconsistent = false;
            prt->num_rx_bpdu_filtered = 0;
            prt->num_rx_bpdu = 0;
            prt->num_rx_tcn = 0;
            prt->num_tx_bpdu = 0;
            prt->num_tx_tcn = 0;
            changed = true;
            /* When port is enabled, initialize bridge assurance timer,
             * so that enough time is given before port is put in
             * inconsistent state.
             */
            updtbrAssuRcvdInfoWhile(prt);
        }
    }
    else
    {
        if(prt->portEnabled)
        {
            prt->portEnabled = false;
            changed = true;
        }
    }
    if(changed)
        br_state_machines_run(prt->bridge);
}
References port_t::AdminExternalPortPathCost, per_tree_port_t::AdminInternalPortPathCost, port_t::AdminP2P, assign, port_t::BaInconsistent, port_t::BpduGuardError, br_state_machines_run(), port_t::bridge, compute_pcost(), port_t::ExternalPortPathCost, FOREACH_PTP_IN_PORT, per_tree_port_t::InternalPortPathCost, port_t::num_rx_bpdu, port_t::num_rx_bpdu_filtered, port_t::num_rx_tcn, port_t::num_tx_bpdu, port_t::num_tx_tcn, port_t::operPointToPointMAC, p2pAuto, p2pForceFalse, p2pForceTrue, port_t::portEnabled, and updtbrAssuRcvdInfoWhile().
Referenced by set_if_up().
MSTP_IN_set_vid2fid()
bool MSTP_IN_set_vid2fid (bridge_t * br, __u16 vid, __u16 fid)
Definition at line 1296 of file mstp.c.
{
    bool vid2mstid_changed;
    if((vid < 1) || (vid > MAX_VID) || (fid > MAX_FID))
    {
        ERROR_BRNAME(br, "Error allocating VID(%hu) to FID(%hu)", vid, fid);
        return false;
    }
    vid2mstid_changed =
        (br->fid2mstid[fid] != br->fid2mstid[br->vid2fid[vid]]);
    br->vid2fid[vid] = fid;
    if(vid2mstid_changed)
    {
        RecalcConfigDigest(br);
        br_state_machines_begin(br);
    }
    return true;
}
References br_state_machines_begin(), ERROR_BRNAME, bridge_t::fid2mstid, MAX_FID, MAX_VID, RecalcConfigDigest(), and bridge_t::vid2fid.
newTcWhile()
static void newTcWhile (per_tree_port_t * ptp) static
Definition at line 1805 of file mstp.c.
{
    if(0 != ptp->tcWhile)
        return;
    tree_t *tree = ptp->tree;
    port_t *prt = ptp->port;
    if(prt->sendRSTP)
    {
        per_tree_port_t *cist = GET_CIST_PTP_FROM_PORT(prt);
        ptp->tcWhile = cist->portTimes.Hello_Time + 1;
        set_TopologyChange(tree, true, prt);
        if(0 == ptp->MSTID)
            prt->newInfo = true;
        else
            prt->newInfoMsti = true;
        return;
    }
    times_t *times = &tree->rootTimes;
    ptp->tcWhile = times->Max_Age + times->Forward_Delay;
    set_TopologyChange(tree, true, prt);
}
References times_t::Forward_Delay, GET_CIST_PTP_FROM_PORT, times_t::Hello_Time, times_t::Max_Age, per_tree_port_t::MSTID, port_t::newInfo, port_t::newInfoMsti, per_tree_port_t::port, per_tree_port_t::portTimes, tree_t::rootTimes, port_t::sendRSTP, set_TopologyChange(), per_tree_port_t::tcWhile, and per_tree_port_t::tree.
Referenced by TCSM_to_DETECTED(), TCSM_to_NOTIFIED_TCN(), and TCSM_to_PROPAGATING().
PISM_run()
static bool PISM_run (per_tree_port_t * ptp, bool dry_run) static
Definition at line 3478 of file mstp.c.
{
    bool rcvdXstMsg, updtXstInfo;
    port_t *prt = ptp->port;
    if((!prt->portEnabled) && (ioDisabled != ptp->infoIs))
    {
        if(dry_run) /* at least infoIs will change */
            return true;
        PISM_to_DISABLED(ptp, false);
        return false;
    }
    switch(ptp->PISM_state)
    {
        case PISM_DISABLED:
            if(prt->portEnabled)
            {
                if(dry_run) /* state change */
                    return true;
                PISM_to_AGED(ptp);
                return false;
            }
            if(ptp->rcvdMsg)
            {
                if(dry_run) /* at least rcvdMsg will change */
                    return true;
                PISM_to_DISABLED(ptp, false);
            }
            return false;
        case PISM_AGED:
            if(ptp->selected && ptp->updtInfo)
            {
                if(dry_run) /* state change */
                    return true;
                PISM_to_UPDATE(ptp);
            }
            return false;
        case PISM_UPDATE:
            /* return; */
        case PISM_SUPERIOR_DESIGNATED:
            /* return; */
        case PISM_REPEATED_DESIGNATED:
            /* return; */
        case PISM_INFERIOR_DESIGNATED:
            /* return; */
        case PISM_NOT_DESIGNATED:
            /* return; */
        case PISM_OTHER:
            if(dry_run) /* state change */
                return true;
            PISM_to_CURRENT(ptp);
            return false;
        case PISM_CURRENT:
            /*
             * Although 802.1Q-2005 does not define rcvdXstMsg and updtXstInfo
             *  from 802.1s we can conclude that they are:
             *  - rcvdXstMsg = rcvdCistMsg, if tree is CIST
             *                 rcvdMstiMsg, if tree is MSTI.
             *  - updtXstInfo = updtCistInfo, if tree is CIST
             *                  updtMstiInfo, if tree is MSTI.
             */
            if(0 == ptp->MSTID)
            { /* CIST */
                rcvdXstMsg = ptp->rcvdMsg; /* 13.25.12 */
                updtXstInfo = ptp->updtInfo; /* 13.25.16 */
            }
            else
            { /* MSTI */
                per_tree_port_t *cist = GET_CIST_PTP_FROM_PORT(prt);
                rcvdXstMsg = !cist->rcvdMsg && ptp->rcvdMsg; /* 13.25.13 */
                updtXstInfo = ptp->updtInfo || cist->updtInfo; /* 13.25.17 */
            }
            if(rcvdXstMsg && !updtXstInfo)
            {
                if(dry_run) /* state change */
                    return true;
                PISM_to_RECEIVE(ptp);
                return false;
            }
            if((ioReceived == ptp->infoIs) && (0 == ptp->rcvdInfoWhile)
               && !ptp->updtInfo && !rcvdXstMsg)
            {
                if(dry_run) /* state change */
                    return true;
                PISM_to_AGED(ptp);
                return false;
            }
            if(ptp->selected && ptp->updtInfo)
            {
                if(dry_run) /* state change */
                    return true;
                PISM_to_UPDATE(ptp);
            }
            return false;
        case PISM_RECEIVE:
            switch(ptp->rcvdInfo)
            {
                case SuperiorDesignatedInfo:
                    if(dry_run) /* state change */
                        return true;
                    PISM_to_SUPERIOR_DESIGNATED(ptp);
                    return false;
                case RepeatedDesignatedInfo:
                    if(dry_run) /* state change */
                        return true;
                    PISM_to_REPEATED_DESIGNATED(ptp);
                    return false;
                case InferiorDesignatedInfo:
                    if(dry_run) /* state change */
                        return true;
                    PISM_to_INFERIOR_DESIGNATED(ptp);
                    return false;
                case InferiorRootAlternateInfo:
                    if(dry_run) /* state change */
                        return true;
                    PISM_to_NOT_DESIGNATED(ptp);
                    return false;
                case OtherInfo:
                    if(dry_run) /* state change */
                        return true;
                    PISM_to_OTHER(ptp);
                    return false;
            }
            return false;
    }
    return false;
}
References dry_run, GET_CIST_PTP_FROM_PORT, InferiorDesignatedInfo, InferiorRootAlternateInfo, per_tree_port_t::infoIs, ioDisabled, ioReceived, per_tree_port_t::MSTID, OtherInfo, PISM_AGED, PISM_CURRENT, PISM_DISABLED, PISM_INFERIOR_DESIGNATED, PISM_NOT_DESIGNATED, PISM_OTHER, PISM_RECEIVE, PISM_REPEATED_DESIGNATED, per_tree_port_t::PISM_state, PISM_SUPERIOR_DESIGNATED, PISM_to_AGED(), PISM_to_CURRENT(), PISM_to_DISABLED(), PISM_to_INFERIOR_DESIGNATED(), PISM_to_NOT_DESIGNATED(), PISM_to_OTHER(), PISM_to_RECEIVE(), PISM_to_REPEATED_DESIGNATED(), PISM_to_SUPERIOR_DESIGNATED(), PISM_to_UPDATE(), PISM_UPDATE, per_tree_port_t::port, port_t::portEnabled, per_tree_port_t::rcvdInfo, per_tree_port_t::rcvdInfoWhile, per_tree_port_t::rcvdMsg, RepeatedDesignatedInfo, per_tree_port_t::selected, SuperiorDesignatedInfo, and per_tree_port_t::updtInfo.
Referenced by __br_state_machines_run(), PISM_to_AGED(), PISM_to_CURRENT(), PISM_to_DISABLED(), PISM_to_INFERIOR_DESIGNATED(), PISM_to_NOT_DESIGNATED(), PISM_to_OTHER(), PISM_to_RECEIVE(), PISM_to_REPEATED_DESIGNATED(), PISM_to_SUPERIOR_DESIGNATED(), and PISM_to_UPDATE().
PISM_to_AGED()
static void PISM_to_AGED (per_tree_port_t * ptp) static
Definition at line 3348 of file mstp.c.
{
    PISM_LOG("");
    ptp->PISM_state = PISM_AGED;
    ptp->infoIs = ioAged;
    ptp->reselect = true;
    ptp->selected = false;
    PISM_run(ptp, false /* actual run */);
}
References per_tree_port_t::infoIs, ioAged, PISM_AGED, PISM_LOG, PISM_run(), per_tree_port_t::PISM_state, per_tree_port_t::reselect, and per_tree_port_t::selected.
Referenced by PISM_run().
PISM_to_CURRENT()
static void PISM_to_CURRENT (per_tree_port_t * ptp) static
Definition at line 3459 of file mstp.c.
{
    PISM_LOG("");
    ptp->PISM_state = PISM_CURRENT;
    PISM_run(ptp, false /* actual run */);
}
References PISM_CURRENT, PISM_LOG, PISM_run(), and per_tree_port_t::PISM_state.
Referenced by PISM_run().
PISM_to_DISABLED()
static void PISM_to_DISABLED (per_tree_port_t * ptp, bool begin) static
Definition at line 3329 of file mstp.c.
{
    PISM_LOG("");
    ptp->PISM_state = PISM_DISABLED;
    ptp->rcvdMsg = false;
    ptp->proposing = false;
    ptp->proposed = false;
    ptp->agree = false;
    ptp->agreed = false;
    assign(ptp->rcvdInfoWhile, 0u);
    ptp->infoIs = ioDisabled;
    ptp->reselect = true;
    ptp->selected = false;
    if(!begin)
        PISM_run(ptp, false /* actual run */);
}
References per_tree_port_t::agree, per_tree_port_t::agreed, assign, per_tree_port_t::infoIs, ioDisabled, PISM_DISABLED, PISM_LOG, PISM_run(), per_tree_port_t::PISM_state, per_tree_port_t::proposed, per_tree_port_t::proposing, per_tree_port_t::rcvdInfoWhile, per_tree_port_t::rcvdMsg, per_tree_port_t::reselect, and per_tree_port_t::selected.
Referenced by PISM_run().
PISM_to_INFERIOR_DESIGNATED()
static void PISM_to_INFERIOR_DESIGNATED (per_tree_port_t * ptp) static
Definition at line 3426 of file mstp.c.
{
    PISM_LOG("");
    ptp->PISM_state = PISM_INFERIOR_DESIGNATED;
    recordDispute(ptp);
    ptp->rcvdMsg = false;
    PISM_run(ptp, false /* actual run */);
}
References PISM_INFERIOR_DESIGNATED, PISM_LOG, PISM_run(), per_tree_port_t::PISM_state, per_tree_port_t::rcvdMsg, and recordDispute().
Referenced by PISM_run().
PISM_to_NOT_DESIGNATED()
static void PISM_to_NOT_DESIGNATED (per_tree_port_t * ptp) static
Definition at line 3437 of file mstp.c.
{
    PISM_LOG("");
    ptp->PISM_state = PISM_NOT_DESIGNATED;
    recordAgreement(ptp);
    setTcFlags(ptp);
    ptp->rcvdMsg = false;
    PISM_run(ptp, false /* actual run */);
}
References PISM_LOG, PISM_NOT_DESIGNATED, PISM_run(), per_tree_port_t::PISM_state, per_tree_port_t::rcvdMsg, recordAgreement(), and setTcFlags().
Referenced by PISM_run().
PISM_to_OTHER()
static void PISM_to_OTHER (per_tree_port_t * ptp) static
Definition at line 3449 of file mstp.c.
{
    PISM_LOG("");
    ptp->PISM_state = PISM_OTHER;
    ptp->rcvdMsg = false;
    PISM_run(ptp, false /* actual run */);
}
References PISM_LOG, PISM_OTHER, PISM_run(), per_tree_port_t::PISM_state, and per_tree_port_t::rcvdMsg.
Referenced by PISM_run().
PISM_to_RECEIVE()
static void PISM_to_RECEIVE (per_tree_port_t * ptp) static
Definition at line 3467 of file mstp.c.
{
    PISM_LOG("");
    ptp->PISM_state = PISM_RECEIVE;
    ptp->rcvdInfo = rcvInfo(ptp);
    recordMastered(ptp);
    PISM_run(ptp, false /* actual run */);
}
References PISM_LOG, PISM_RECEIVE, PISM_run(), per_tree_port_t::PISM_state, per_tree_port_t::rcvdInfo, rcvInfo(), and recordMastered().
Referenced by PISM_run().
PISM_to_REPEATED_DESIGNATED()
static void PISM_to_REPEATED_DESIGNATED (per_tree_port_t * ptp) static
Definition at line 3409 of file mstp.c.
{
    PISM_LOG("");
    ptp->PISM_state = PISM_REPEATED_DESIGNATED;
    port_t *prt = ptp->port;
    prt->infoInternal = prt->rcvdInternal;
    recordProposal(ptp);
    setTcFlags(ptp);
    recordAgreement(ptp);
    updtRcvdInfoWhile(ptp);
    ptp->rcvdMsg = false;
    PISM_run(ptp, false /* actual run */);
}
References port_t::infoInternal, PISM_LOG, PISM_REPEATED_DESIGNATED, PISM_run(), per_tree_port_t::PISM_state, per_tree_port_t::port, port_t::rcvdInternal, per_tree_port_t::rcvdMsg, recordAgreement(), recordProposal(), setTcFlags(), and updtRcvdInfoWhile().
Referenced by PISM_run().
PISM_to_SUPERIOR_DESIGNATED()
static void PISM_to_SUPERIOR_DESIGNATED (per_tree_port_t * ptp) static
Definition at line 3383 of file mstp.c.
{
    PISM_LOG("");
    ptp->PISM_state = PISM_SUPERIOR_DESIGNATED;
    port_t *prt = ptp->port;
    prt->infoInternal = prt->rcvdInternal;
    ptp->agreed = false;
    ptp->proposing = false;
    recordProposal(ptp);
    setTcFlags(ptp);
    ptp->agree = ptp->agree && betterorsameInfo(ptp, ioReceived);
    recordAgreement(ptp);
    ptp->synced = ptp->synced && ptp->agreed;
    recordPriority(ptp);
    recordTimes(ptp);
    updtRcvdInfoWhile(ptp);
    ptp->infoIs = ioReceived;
    ptp->reselect = true;
    ptp->selected = false;
    ptp->rcvdMsg = false;
    PISM_run(ptp, false /* actual run */);
}
References per_tree_port_t::agree, per_tree_port_t::agreed, betterorsameInfo(), port_t::infoInternal, per_tree_port_t::infoIs, ioReceived, PISM_LOG, PISM_run(), per_tree_port_t::PISM_state, PISM_SUPERIOR_DESIGNATED, per_tree_port_t::port, per_tree_port_t::proposing, port_t::rcvdInternal, per_tree_port_t::rcvdMsg, recordAgreement(), recordPriority(), recordProposal(), recordTimes(), per_tree_port_t::reselect, per_tree_port_t::selected, setTcFlags(), per_tree_port_t::synced, and updtRcvdInfoWhile().
Referenced by PISM_run().
PISM_to_UPDATE()
static void PISM_to_UPDATE (per_tree_port_t * ptp) static
Definition at line 3360 of file mstp.c.
{
    PISM_LOG("");
    ptp->PISM_state = PISM_UPDATE;
    ptp->proposing = false;
    ptp->proposed = false;
    ptp->agreed = ptp->agreed && betterorsameInfo(ptp, ioMine);
    ptp->synced = ptp->synced && ptp->agreed;
    assign(ptp->portPriority, ptp->designatedPriority);
    assign(ptp->portTimes, ptp->designatedTimes);
    ptp->updtInfo = false;
    ptp->infoIs = ioMine;
    /* newInfoXst = TRUE; */
    port_t *prt = ptp->port;
    if(0 == ptp->MSTID)
        prt->newInfo = true;
    else
        prt->newInfoMsti = true;
    PISM_run(ptp, false /* actual run */);
}
References per_tree_port_t::agreed, assign, betterorsameInfo(), per_tree_port_t::designatedPriority, per_tree_port_t::designatedTimes, per_tree_port_t::infoIs, ioMine, per_tree_port_t::MSTID, port_t::newInfo, port_t::newInfoMsti, PISM_LOG, PISM_run(), per_tree_port_t::PISM_state, PISM_UPDATE, per_tree_port_t::port, per_tree_port_t::portPriority, per_tree_port_t::portTimes, per_tree_port_t::proposed, per_tree_port_t::proposing, per_tree_port_t::synced, and per_tree_port_t::updtInfo.
Referenced by PISM_run().
port_default_internal_vars()
static void port_default_internal_vars (port_t * prt) static
Definition at line 124 of file mstp.c.
{
    prt->infoInternal = false;
    prt->rcvdInternal = false;
    prt->rcvdTcAck = false;
    prt->rcvdTcn = false;
    assign(prt->rapidAgeingWhile, 0u);
    assign(prt->brAssuRcvdInfoWhile, 0u);
    prt->BaInconsistent = false;
    prt->num_rx_bpdu_filtered = 0;
    prt->num_rx_bpdu = 0;
    prt->num_rx_tcn = 0;
    prt->num_tx_bpdu = 0;
    prt->num_tx_tcn = 0;
    prt->num_trans_fwd = 0;
    prt->num_trans_blk = 0;
    /* The following are initialized in BEGIN state:
     * - mdelayWhile. mcheck, sendRSTP: in Port Protocol Migration SM
     * - helloWhen, newInfo, newInfoMsti, txCount: in Port Transmit SM
     * - edgeDelayWhile, rcvdBpdu, rcvdRSTP, rcvdSTP : in Port Receive SM
     * - operEdge: in Bridge Detection SM
     * - tcAck: in Topology Change SM
     */
}
References assign, port_t::BaInconsistent, port_t::brAssuRcvdInfoWhile, port_t::infoInternal, port_t::num_rx_bpdu, port_t::num_rx_bpdu_filtered, port_t::num_rx_tcn, port_t::num_trans_blk, port_t::num_trans_fwd, port_t::num_tx_bpdu, port_t::num_tx_tcn, port_t::rapidAgeingWhile, port_t::rcvdInternal, port_t::rcvdTcAck, and port_t::rcvdTcn.
Referenced by MSTP_IN_port_create_and_add_tail(), and MSTP_IN_set_bridge_enable().
PPMSM_run()
static bool PPMSM_run (port_t * prt, bool dry_run) static
Definition at line 3003 of file mstp.c.
{
    bridge_t *br = prt->bridge;
    switch(prt->PPMSM_state)
    {
        case PPMSM_CHECKING_RSTP:
            if((prt->mdelayWhile != br->Migrate_Time)
               && !prt->portEnabled)
            {
                if(dry_run) /* at least mdelayWhile will change */
                    return true;
                PPMSM_to_CHECKING_RSTP(prt);
                return false;
            }
            if(0 == prt->mdelayWhile)
            {
                if(dry_run) /* state change */
                    return true;
                PPMSM_to_SENSING(prt);
            }
            return false;
        case PPMSM_SELECTING_STP:
            if(0 == prt->mdelayWhile || !prt->portEnabled || prt->mcheck)
            {
                if(dry_run) /* state change */
                    return true;
                PPMSM_to_SENSING(prt);
            }
            return false;
        case PPMSM_SENSING:
            if(!prt->portEnabled || prt->mcheck
               || (rstpVersion(br) && !prt->sendRSTP && prt->rcvdRSTP))
            {
                if(dry_run) /* state change */
                    return true;
                PPMSM_to_CHECKING_RSTP(prt);
                return false;
            }
            if(prt->sendRSTP && prt->rcvdSTP)
            {
                if(dry_run) /* state change */
                    return true;
                PPMSM_to_SELECTING_STP(prt);
            }
            return false;
    }
    return false;
}
References port_t::bridge, dry_run, port_t::mcheck, port_t::mdelayWhile, bridge_t::Migrate_Time, port_t::portEnabled, PPMSM_CHECKING_RSTP, PPMSM_SELECTING_STP, PPMSM_SENSING, port_t::PPMSM_state, PPMSM_to_CHECKING_RSTP(), PPMSM_to_SELECTING_STP(), PPMSM_to_SENSING(), port_t::rcvdRSTP, port_t::rcvdSTP, rstpVersion, and port_t::sendRSTP.
Referenced by __br_state_machines_run(), PPMSM_to_SELECTING_STP(), and PPMSM_to_SENSING().
PPMSM_to_CHECKING_RSTP()
static void PPMSM_to_CHECKING_RSTP (port_t * prt) static
Definition at line 2969 of file mstp.c.
{
    prt->PPMSM_state = PPMSM_CHECKING_RSTP;
    bridge_t *br = prt->bridge;
    prt->mcheck = false;
    prt->sendRSTP = rstpVersion(br);
    assign(prt->mdelayWhile, br->Migrate_Time);
    /* No need to run, no one condition will be met
     * if(!begin)
     *     PPMSM_run(prt, false); */
}
References assign, port_t::bridge, port_t::mcheck, port_t::mdelayWhile, bridge_t::Migrate_Time, PPMSM_CHECKING_RSTP, port_t::PPMSM_state, rstpVersion, and port_t::sendRSTP.
Referenced by PPMSM_run().
PPMSM_to_SELECTING_STP()
static void PPMSM_to_SELECTING_STP (port_t * prt) static
Definition at line 2983 of file mstp.c.
{
    prt->PPMSM_state = PPMSM_SELECTING_STP;
    prt->sendRSTP = false;
    assign(prt->mdelayWhile, prt->bridge->Migrate_Time);
    PPMSM_run(prt, false /* actual run */);
}
References assign, port_t::bridge, port_t::mdelayWhile, bridge_t::Migrate_Time, PPMSM_run(), PPMSM_SELECTING_STP, port_t::PPMSM_state, and port_t::sendRSTP.
Referenced by PPMSM_run().
PPMSM_to_SENSING()
static void PPMSM_to_SENSING (port_t * prt) static
Definition at line 2993 of file mstp.c.
{
    prt->PPMSM_state = PPMSM_SENSING;
    prt->rcvdRSTP = false;
    prt->rcvdSTP = false;
    PPMSM_run(prt, false /* actual run */);
}
References PPMSM_run(), PPMSM_SENSING, port_t::PPMSM_state, port_t::rcvdRSTP, and port_t::rcvdSTP.
Referenced by PPMSM_run().
PRSM_run()
static bool PRSM_run (port_t * prt, bool dry_run) static
Definition at line 2922 of file mstp.c.
{
    per_tree_port_t *ptp;
    bool rcvdAnyMsg;
    if((prt->rcvdBpdu || (prt->edgeDelayWhile != prt->bridge->Migrate_Time))
       && !prt->portEnabled)
    {
        return PRSM_to_DISCARD(prt, dry_run);
    }
    switch(prt->PRSM_state)
    {
        case PRSM_DISCARD:
            if(prt->rcvdBpdu && prt->portEnabled)
            {
                if(dry_run) /* state change */
                    return true;
                PRSM_to_RECEIVE(prt);
            }
            return false;
        case PRSM_RECEIVE:
            rcvdAnyMsg = false;
            FOREACH_PTP_IN_PORT(ptp, prt)
            {
                if(ptp->rcvdMsg)
                {
                    rcvdAnyMsg = true;
                    break;
                }
            }
            if(prt->rcvdBpdu && prt->portEnabled && !rcvdAnyMsg)
            {
                if(dry_run) /* at least rcvdBpdu will change */
                    return true;
                PRSM_to_RECEIVE(prt);
            }
        default:
            return false;
    }
}
References port_t::bridge, dry_run, port_t::edgeDelayWhile, FOREACH_PTP_IN_PORT, bridge_t::Migrate_Time, port_t::portEnabled, PRSM_DISCARD, PRSM_RECEIVE, port_t::PRSM_state, PRSM_to_DISCARD(), PRSM_to_RECEIVE(), port_t::rcvdBpdu, and per_tree_port_t::rcvdMsg.
Referenced by __br_state_machines_run().
PRSM_to_DISCARD()
static bool PRSM_to_DISCARD (port_t * prt, bool dry_run) static
Definition at line 2883 of file mstp.c.
{
    if(dry_run)
    {
        return (prt->PRSM_state != PRSM_DISCARD)
               || prt->rcvdBpdu || prt->rcvdRSTP || prt->rcvdSTP
               || (prt->edgeDelayWhile != prt->bridge->Migrate_Time)
               || clearAllRcvdMsgs(prt, dry_run);
    }
    prt->PRSM_state = PRSM_DISCARD;
    prt->rcvdBpdu = false;
    prt->rcvdRSTP = false;
    prt->rcvdSTP = false;
    clearAllRcvdMsgs(prt, false /* actual run */);
    assign(prt->edgeDelayWhile, prt->bridge->Migrate_Time);
    /* No need to run, no one condition will be met
     * if(!begin)
     *     PRSM_run(prt, false); */
    return false;
}
References assign, port_t::bridge, clearAllRcvdMsgs(), dry_run, port_t::edgeDelayWhile, bridge_t::Migrate_Time, PRSM_DISCARD, port_t::PRSM_state, port_t::rcvdBpdu, port_t::rcvdRSTP, and port_t::rcvdSTP.
Referenced by PRSM_run().
PRSM_to_RECEIVE()
static void PRSM_to_RECEIVE (port_t * prt) static
Definition at line 2907 of file mstp.c.
{
    prt->PRSM_state = PRSM_RECEIVE;
    updtBPDUVersion(prt);
    prt->rcvdInternal = fromSameRegion(prt);
    setRcvdMsgs(prt);
    prt->operEdge = false;
    prt->rcvdBpdu = false;
    assign(prt->edgeDelayWhile, prt->bridge->Migrate_Time);
    /* No need to run, no one condition will be met
      PRSM_run(prt, false); */
}
References assign, port_t::bridge, port_t::edgeDelayWhile, fromSameRegion(), bridge_t::Migrate_Time, port_t::operEdge, PRSM_RECEIVE, port_t::PRSM_state, port_t::rcvdBpdu, port_t::rcvdInternal, setRcvdMsgs(), and updtBPDUVersion().
Referenced by PRSM_run().
PRSSM_run()
static bool PRSSM_run (tree_t * tree, bool dry_run) static
Definition at line 3638 of file mstp.c.
{
    per_tree_port_t *ptp;
    switch(tree->PRSSM_state)
    {
        case PRSSM_INIT_TREE:
            if(dry_run) /* state change */
                return true;
            PRSSM_to_ROLE_SELECTION(tree);
            return false;
        case PRSSM_ROLE_SELECTION:
            FOREACH_PTP_IN_TREE(ptp, tree)
                if(ptp->reselect)
                {
                    if(dry_run) /* at least reselect will change */
                        return true;
                    PRSSM_to_ROLE_SELECTION(tree);
                    return false;
                }
            return false;
    }
    return false;
}
References dry_run, FOREACH_PTP_IN_TREE, PRSSM_INIT_TREE, PRSSM_ROLE_SELECTION, tree_t::PRSSM_state, PRSSM_to_ROLE_SELECTION(), and per_tree_port_t::reselect.
Referenced by __br_state_machines_run(), and prt_state_machines_begin().
PRSSM_to_INIT_TREE()
static void PRSSM_to_INIT_TREE (tree_t * tree) static
Definition at line 3613 of file mstp.c.
{
    tree->PRSSM_state = PRSSM_INIT_TREE;
    updtRolesDisabledTree(tree);
    /* No need to check, as we assume begin = true here
     * because transition to this state can be initiated only by BEGIN var.
     * In other words, this function is called via xxx_begin macro only.
     * if(!begin)
     *     PRSSM_run(prt, false); */
}
References PRSSM_INIT_TREE, tree_t::PRSSM_state, and updtRolesDisabledTree().
PRSSM_to_ROLE_SELECTION()
static void PRSSM_to_ROLE_SELECTION (tree_t * tree) static
Definition at line 3626 of file mstp.c.
{
    tree->PRSSM_state = PRSSM_ROLE_SELECTION;
    clearReselectTree(tree);
    updtRolesTree(tree);
    setSelectedTree(tree);
    /* No need to run, no one condition will be met
      PRSSM_run(tree, false); */
}
References clearReselectTree(), PRSSM_ROLE_SELECTION, tree_t::PRSSM_state, setSelectedTree(), and updtRolesTree().
Referenced by PRSSM_run().
prt_state_machines_begin()
static void prt_state_machines_begin (port_t * prt) static
Definition at line 4926 of file mstp.c.
{
    bridge_t *br = prt->bridge;
    tree_t *tree;
    per_tree_port_t *ptp;
    if(!br->bridgeEnabled)
        return;
    /* 13.28  Port Receive state machine */
    PRSM_begin(prt);
    /* 13.29  Port Protocol Migration state machine */
    PPMSM_begin(prt);
    /* 13.30  Bridge Detection state machine */
    BDSM_begin(prt);
    /* 13.31  Port Transmit state machine */
    PTSM_begin(prt);
    /* 13.32  Port Information state machine */
    FOREACH_PTP_IN_PORT(ptp, prt)
    {
        ptp->start_time = br->uptime; /* 12.8.2.2.3 b) */
        PISM_begin(ptp);
    }
    /* 13.33  Port Role Selection state machine */
    FOREACH_TREE_IN_BRIDGE(tree, br)
        PRSSM_run(tree, false /* actual run */);
    /* 13.34  Port Role Transitions state machine */
    FOREACH_PTP_IN_PORT(ptp, prt)
        PRTSM_begin(ptp);
    /* 13.35  Port State Transition state machine */
    FOREACH_PTP_IN_PORT(ptp, prt)
        PSTSM_begin(ptp);
    /* 13.36  Topology Change state machine */
    FOREACH_PTP_IN_PORT(ptp, prt)
        TCSM_begin(ptp);
    br_state_machines_run(br);
}
References BDSM_begin(), br_state_machines_run(), port_t::bridge, bridge_t::bridgeEnabled, FOREACH_PTP_IN_PORT, FOREACH_TREE_IN_BRIDGE, PISM_begin, PPMSM_begin, PRSM_begin, PRSSM_run(), PRTSM_begin, PSTSM_begin, PTSM_begin, per_tree_port_t::start_time, TCSM_begin, and bridge_t::uptime.
Referenced by MSTP_IN_port_create_and_add_tail().
PRTSM_runr()
static bool PRTSM_runr (per_tree_port_t * ptp, bool recursive_call, bool dry_run) static
Definition at line 4120 of file mstp.c.
{
    /* Following vars do not need recalculating on recursive calls */
    static unsigned int MaxAge, FwdDelay, forwardDelay, HelloTime;
    static port_t *prt;
    static tree_t *tree;
    static per_tree_port_t *cist;
    /* Following vars are recalculated on each state transition */
    bool allSynced, reRooted;
    /* Following vars are auxiliary and don't depend on recursive_call */
    per_tree_port_t *ptp_1;
    if(!recursive_call)
    { /* calculate these intermediate vars only first time in chain of
       * recursive calls */
        prt = ptp->port;
        tree = ptp->tree;
        cist = GET_CIST_PTP_FROM_PORT(prt);
        /* 13.25.6 */
        FwdDelay = cist->designatedTimes.Forward_Delay;
        /* 13.25.7 */
        HelloTime = cist->portTimes.Hello_Time;
        /* 13.25.d) -> 17.20.5 of 802.1D */
        forwardDelay = prt->sendRSTP ? HelloTime : FwdDelay;
        /* 13.25.8 */
        MaxAge = cist->designatedTimes.Max_Age;
    }
    PRTSM_LOG("role = %d, selectedRole = %d, selected = %d, updtInfo = %d",
              ptp->role, ptp->selectedRole, ptp->selected, ptp->updtInfo);
    if((ptp->role != ptp->selectedRole) && ptp->selected && !ptp->updtInfo)
    {
        switch(ptp->selectedRole)
        {
            case roleDisabled:
                if(dry_run) /* at least role will change */
                    return true;
                PRTSM_to_DISABLE_PORT(ptp);
                return false;
            case roleMaster:
                if(dry_run) /* at least role will change */
                    return true;
                PRTSM_to_MASTER_PORT(ptp);
                return false;
            case roleRoot:
                if(dry_run) /* at least role will change */
                    return true;
                PRTSM_to_ROOT_PORT(ptp, FwdDelay);
                return false;
            case roleDesignated:
                if(dry_run) /* at least role will change */
                    return true;
                PRTSM_to_DESIGNATED_PORT(ptp);
                return false;
            case roleAlternate:
            case roleBackup:
                if(dry_run) /* at least role will change */
                    return true;
                PRTSM_to_BLOCK_PORT(ptp);
                return false;
        }
    }
    /* 13.25.1 */
    allSynced = true;
    FOREACH_PTP_IN_TREE(ptp_1, tree)
    {
        /* a) */
        if(!ptp_1->selected
           || (ptp_1->role != ptp_1->selectedRole)
           || ptp_1->updtInfo
          )
        {
            allSynced = false;
            break;
        }
        /* b) */
        switch(ptp->role)
        {
            case roleRoot:
            case roleAlternate:
                if((roleRoot != ptp_1->role) && !ptp_1->synced)
                    allSynced = false;
                break;
            case roleDesignated:
            case roleMaster:
                if((ptp != ptp_1) && !ptp_1->synced)
                    allSynced = false;
                break;
            default:
                allSynced = false;
        }
        if(!allSynced)
            break;
    }
    switch(ptp->PRTSM_state)
    {
     /* Disabled Port role transitions */
        case PRTSM_INIT_PORT:
            if(dry_run) /* state change */
                return true;
            PRTSM_to_DISABLE_PORT(ptp);
            return false;
        case PRTSM_DISABLE_PORT:
            if(ptp->selected && !ptp->updtInfo
               && !ptp->learning && !ptp->forwarding
              )
            {
                if(dry_run) /* state change */
                    return true;
                PRTSM_to_DISABLED_PORT(ptp, MaxAge);
            }
            return false;
        case PRTSM_DISABLED_PORT:
            if(ptp->selected && !ptp->updtInfo
               && (ptp->sync || ptp->reRoot || !ptp->synced
                   || (ptp->fdWhile != MaxAge))
              )
            {
                if(dry_run) /* one of (sync,reRoot,synced,fdWhile) will change */
                    return true;
                PRTSM_to_DISABLED_PORT(ptp, MaxAge);
            }
            return false;
     /* MasterPort role transitions */
        case PRTSM_MASTER_PROPOSED:
            /* return; */
        case PRTSM_MASTER_AGREED:
            /* return; */
        case PRTSM_MASTER_SYNCED:
            /* return; */
        case PRTSM_MASTER_RETIRED:
            /* return; */
        case PRTSM_MASTER_FORWARD:
            /* return; */
        case PRTSM_MASTER_LEARN:
            /* return; */
        case PRTSM_MASTER_DISCARD:
            if(dry_run) /* state change */
                return true;
            PRTSM_to_MASTER_PORT(ptp);
            return false;
        case PRTSM_MASTER_PORT:
            if(!(ptp->selected && !ptp->updtInfo))
                return false;
            if(ptp->reRoot && (0 == ptp->rrWhile))
            {
                if(dry_run) /* state change */
                    return true;
                PRTSM_to_MASTER_RETIRED(ptp);
                return false;
            }
            if((!ptp->learning && !ptp->forwarding && !ptp->synced)
               || (ptp->agreed && !ptp->synced)
               || (prt->operEdge && !ptp->synced)
               || (ptp->sync && ptp->synced)
              )
            {
                if(dry_run) /* state change */
                    return true;
                PRTSM_to_MASTER_SYNCED(ptp);
                return false;
            }
            if((allSynced && !ptp->agree)
               || (ptp->proposed && ptp->agree)
              )
            {
                if(dry_run) /* state change */
                    return true;
                PRTSM_to_MASTER_AGREED(ptp);
                return false;
            }
            if(ptp->proposed && !ptp->agree)
            {
                if(dry_run) /* state change */
                    return true;
                PRTSM_to_MASTER_PROPOSED(ptp);
                return false;
            }
            if(((0 == ptp->fdWhile) || allSynced)
               && ptp->learn && !ptp->forward
              )
            {
                if(dry_run) /* state change */
                    return true;
                PRTSM_to_MASTER_FORWARD(ptp);
                return false;
            }
            if(((0 == ptp->fdWhile) || allSynced)
               && !ptp->learn
              )
            {
                if(dry_run) /* state change */
                    return true;
                PRTSM_to_MASTER_LEARN(ptp, forwardDelay);
                return false;
            }
            if(((ptp->sync && !ptp->synced)
                || (ptp->reRoot && (0 != ptp->rrWhile))
                || ptp->disputed
               )
               && !prt->operEdge && (ptp->learn || ptp->forward)
              )
            {
                if(dry_run) /* state change */
                    return true;
                PRTSM_to_MASTER_DISCARD(ptp, forwardDelay);
                return false;
            }
            return false;
     /* RootPort role transitions */
        case PRTSM_ROOT_PROPOSED:
            /* return; */
        case PRTSM_ROOT_AGREED:
            /* return; */
        case PRTSM_ROOT_SYNCED:
            /* return; */
        case PRTSM_REROOT:
            /* return; */
        case PRTSM_ROOT_FORWARD:
            /* return; */
        case PRTSM_ROOT_LEARN:
            /* return; */
        case PRTSM_REROOTED:
            if(dry_run) /* state change */
                return true;
            PRTSM_to_ROOT_PORT(ptp, FwdDelay);
            return false;
        case PRTSM_ROOT_PORT:
            if(!(ptp->selected && !ptp->updtInfo))
                return false;
            if(!ptp->forward && !ptp->reRoot)
            {
                if(dry_run) /* state change */
                    return true;
                PRTSM_to_REROOT(ptp);
                return false;
            }
            if((ptp->agreed && !ptp->synced) || (ptp->sync && ptp->synced))
            {
                if(dry_run) /* state change */
                    return true;
                PRTSM_to_ROOT_SYNCED(ptp);
                return false;
            }
            if((allSynced && !ptp->agree) || (ptp->proposed && ptp->agree))
            {
                if(dry_run) /* state change */
                    return true;
                PRTSM_to_ROOT_AGREED(ptp);
                return false;
            }
            if(ptp->proposed && !ptp->agree)
            {
                if(dry_run) /* state change */
                    return true;
                PRTSM_to_ROOT_PROPOSED(ptp);
                return false;
            }
            /* 17.20.10 of 802.1D : reRooted */
            reRooted = true;
            FOREACH_PTP_IN_TREE(ptp_1, tree)
            {
                if((ptp != ptp_1) && (0 != ptp_1->rrWhile))
                {
                    reRooted = false;
                    break;
                }
            }
            if((0 == ptp->fdWhile)
               || (reRooted && (0 == ptp->rbWhile) && rstpVersion(prt->bridge))
              )
            {
                if(!ptp->learn)
                {
                    if(dry_run) /* state change */
                        return true;
                    PRTSM_to_ROOT_LEARN(ptp, forwardDelay);
                    return false;
                }
                else if(!ptp->forward)
                {
                    if(dry_run) /* state change */
                        return true;
                    PRTSM_to_ROOT_FORWARD(ptp);
                    return false;
                }
            }
            if(ptp->reRoot && ptp->forward)
            {
                if(dry_run) /* state change */
                    return true;
                PRTSM_to_REROOTED(ptp);
                return false;
            }
            if(ptp->rrWhile != FwdDelay)
            {
                if(dry_run) /* state change */
                    return true;
                PRTSM_to_ROOT_PORT(ptp, FwdDelay);
                return false;
            }
            return false;
     /* DesignatedPort role transitions */
        case PRTSM_DESIGNATED_PROPOSE:
            /* return; */
        case PRTSM_DESIGNATED_AGREED:
            /* return; */
        case PRTSM_DESIGNATED_SYNCED:
            /* return; */
        case PRTSM_DESIGNATED_RETIRED:
            /* return; */
        case PRTSM_DESIGNATED_FORWARD:
            /* return; */
        case PRTSM_DESIGNATED_LEARN:
            /* return; */
        case PRTSM_DESIGNATED_DISCARD:
            if(dry_run) /* state change */
                return true;
            PRTSM_to_DESIGNATED_PORT(ptp);
            return false;
        case PRTSM_DESIGNATED_PORT:
            if(!(ptp->selected && !ptp->updtInfo))
                return false;
            if(ptp->reRoot && (0 == ptp->rrWhile))
            {
                if(dry_run) /* state change */
                    return true;
                PRTSM_to_DESIGNATED_RETIRED(ptp);
                return false;
            }
            if((!ptp->learning && !ptp->forwarding && !ptp->synced)
               || (ptp->agreed && !ptp->synced)
               || (prt->operEdge && !ptp->synced)
               || (ptp->sync && ptp->synced)
              )
            {
                if(dry_run) /* state change */
                    return true;
                PRTSM_to_DESIGNATED_SYNCED(ptp);
                return false;
            }
            if(allSynced && (ptp->proposed || !ptp->agree))
            {
                if(dry_run) /* state change */
                    return true;
                PRTSM_to_DESIGNATED_AGREED(ptp);
                return false;
            }
            if(!ptp->forward && !ptp->agreed && !ptp->proposing
               && !prt->operEdge)
            {
                if(dry_run) /* state change */
                    return true;
                PRTSM_to_DESIGNATED_PROPOSE(ptp);
                return false;
            }
            /* Dont transition to learn/forward when BA inconsistent */
            if(((0 == ptp->fdWhile) || ptp->agreed || prt->operEdge)
               && ((0 == ptp->rrWhile) || !ptp->reRoot) && !ptp->sync
               && !ptp->port->BaInconsistent
              )
            {
                if(!ptp->learn)
                {
                    if(dry_run) /* state change */
                        return true;
                    PRTSM_to_DESIGNATED_LEARN(ptp, forwardDelay);
                    return false;
                }
                else if(!ptp->forward)
                {
                    if(dry_run) /* state change */
                        return true;
                    PRTSM_to_DESIGNATED_FORWARD(ptp);
                    return false;
                }
            }
            /* Transition to discarding when BA inconsistent */
            if(((ptp->sync && !ptp->synced)
                || (ptp->reRoot && (0 != ptp->rrWhile))
                || ptp->disputed
                || ptp->port->BaInconsistent
               )
               && !prt->operEdge && (ptp->learn || ptp->forward)
              )
            {
                if(dry_run) /* state change */
                    return true;
                PRTSM_to_DESIGNATED_DISCARD(ptp, forwardDelay);
                return false;
            }
            return false;
     /* AlternatePort and BackupPort role transitions */
        case PRTSM_BLOCK_PORT:
            if(ptp->selected && !ptp->updtInfo
               && !ptp->learning && !ptp->forwarding
              )
            {
                if(dry_run) /* state change */
                    return true;
                PRTSM_to_ALTERNATE_PORT(ptp, forwardDelay);
            }
            return false;
        case PRTSM_BACKUP_PORT:
            /* return; */
        case PRTSM_ALTERNATE_PROPOSED:
            /* return; */
        case PRTSM_ALTERNATE_AGREED:
            if(dry_run) /* state change */
                return true;
            PRTSM_to_ALTERNATE_PORT(ptp, forwardDelay);
            return false;
        case PRTSM_ALTERNATE_PORT:
            if(!(ptp->selected && !ptp->updtInfo))
                return false;
            if((allSynced && !ptp->agree) || (ptp->proposed && ptp->agree))
            {
                if(dry_run) /* state change */
                    return true;
                PRTSM_to_ALTERNATE_AGREED(ptp);
                return false;
            }
            if(ptp->proposed && !ptp->agree)
            {
                if(dry_run) /* state change */
                    return true;
                PRTSM_to_ALTERNATE_PROPOSED(ptp);
                return false;
            }
            if((ptp->rbWhile != 2 * HelloTime) && (roleBackup == ptp->role))
            {
                if(dry_run) /* state change */
                    return true;
                PRTSM_to_BACKUP_PORT(ptp, HelloTime);
                return false;
            }
            if((ptp->fdWhile != forwardDelay) || ptp->sync || ptp->reRoot
               || !ptp->synced)
            {
                if(dry_run) /* state change */
                    return true;
                PRTSM_to_ALTERNATE_PORT(ptp, forwardDelay);
                return false;
            }
            return false;
    }
    return false;
}
References per_tree_port_t::agree, per_tree_port_t::agreed, port_t::BaInconsistent, port_t::bridge, per_tree_port_t::designatedTimes, per_tree_port_t::disputed, dry_run, per_tree_port_t::fdWhile, FOREACH_PTP_IN_TREE, per_tree_port_t::forward, times_t::Forward_Delay, per_tree_port_t::forwarding, GET_CIST_PTP_FROM_PORT, times_t::Hello_Time, per_tree_port_t::learn, per_tree_port_t::learning, times_t::Max_Age, port_t::operEdge, per_tree_port_t::port, per_tree_port_t::portTimes, per_tree_port_t::proposed, per_tree_port_t::proposing, PRTSM_ALTERNATE_AGREED, PRTSM_ALTERNATE_PORT, PRTSM_ALTERNATE_PROPOSED, PRTSM_BACKUP_PORT, PRTSM_BLOCK_PORT, PRTSM_DESIGNATED_AGREED, PRTSM_DESIGNATED_DISCARD, PRTSM_DESIGNATED_FORWARD, PRTSM_DESIGNATED_LEARN, PRTSM_DESIGNATED_PORT, PRTSM_DESIGNATED_PROPOSE, PRTSM_DESIGNATED_RETIRED, PRTSM_DESIGNATED_SYNCED, PRTSM_DISABLE_PORT, PRTSM_DISABLED_PORT, PRTSM_INIT_PORT, PRTSM_LOG, PRTSM_MASTER_AGREED, PRTSM_MASTER_DISCARD, PRTSM_MASTER_FORWARD, PRTSM_MASTER_LEARN, PRTSM_MASTER_PORT, PRTSM_MASTER_PROPOSED, PRTSM_MASTER_RETIRED, PRTSM_MASTER_SYNCED, PRTSM_REROOT, PRTSM_REROOTED, PRTSM_ROOT_AGREED, PRTSM_ROOT_FORWARD, PRTSM_ROOT_LEARN, PRTSM_ROOT_PORT, PRTSM_ROOT_PROPOSED, PRTSM_ROOT_SYNCED, per_tree_port_t::PRTSM_state, PRTSM_to_ALTERNATE_AGREED(), PRTSM_to_ALTERNATE_PORT(), PRTSM_to_ALTERNATE_PROPOSED(), PRTSM_to_BACKUP_PORT(), PRTSM_to_BLOCK_PORT(), PRTSM_to_DESIGNATED_AGREED(), PRTSM_to_DESIGNATED_DISCARD(), PRTSM_to_DESIGNATED_FORWARD(), PRTSM_to_DESIGNATED_LEARN(), PRTSM_to_DESIGNATED_PORT(), PRTSM_to_DESIGNATED_PROPOSE(), PRTSM_to_DESIGNATED_RETIRED(), PRTSM_to_DESIGNATED_SYNCED(), PRTSM_to_DISABLE_PORT(), PRTSM_to_DISABLED_PORT(), PRTSM_to_MASTER_AGREED(), PRTSM_to_MASTER_DISCARD(), PRTSM_to_MASTER_FORWARD(), PRTSM_to_MASTER_LEARN(), PRTSM_to_MASTER_PORT(), PRTSM_to_MASTER_PROPOSED(), PRTSM_to_MASTER_RETIRED(), PRTSM_to_MASTER_SYNCED(), PRTSM_to_REROOT(), PRTSM_to_REROOTED(), PRTSM_to_ROOT_AGREED(), PRTSM_to_ROOT_FORWARD(), PRTSM_to_ROOT_LEARN(), PRTSM_to_ROOT_PORT(), PRTSM_to_ROOT_PROPOSED(), PRTSM_to_ROOT_SYNCED(), per_tree_port_t::rbWhile, per_tree_port_t::reRoot, per_tree_port_t::role, roleAlternate, roleBackup, roleDesignated, roleDisabled, roleMaster, roleRoot, per_tree_port_t::rrWhile, rstpVersion, per_tree_port_t::selected, per_tree_port_t::selectedRole, port_t::sendRSTP, per_tree_port_t::sync, per_tree_port_t::synced, per_tree_port_t::tree, and per_tree_port_t::updtInfo.
Referenced by PRTSM_to_ALTERNATE_AGREED(), PRTSM_to_ALTERNATE_PORT(), PRTSM_to_ALTERNATE_PROPOSED(), PRTSM_to_BACKUP_PORT(), PRTSM_to_BLOCK_PORT(), PRTSM_to_DESIGNATED_AGREED(), PRTSM_to_DESIGNATED_DISCARD(), PRTSM_to_DESIGNATED_FORWARD(), PRTSM_to_DESIGNATED_LEARN(), PRTSM_to_DESIGNATED_PORT(), PRTSM_to_DESIGNATED_PROPOSE(), PRTSM_to_DESIGNATED_RETIRED(), PRTSM_to_DESIGNATED_SYNCED(), PRTSM_to_DISABLE_PORT(), PRTSM_to_DISABLED_PORT(), PRTSM_to_MASTER_AGREED(), PRTSM_to_MASTER_DISCARD(), PRTSM_to_MASTER_FORWARD(), PRTSM_to_MASTER_LEARN(), PRTSM_to_MASTER_PORT(), PRTSM_to_MASTER_PROPOSED(), PRTSM_to_MASTER_RETIRED(), PRTSM_to_MASTER_SYNCED(), PRTSM_to_REROOT(), PRTSM_to_REROOTED(), PRTSM_to_ROOT_AGREED(), PRTSM_to_ROOT_FORWARD(), PRTSM_to_ROOT_LEARN(), PRTSM_to_ROOT_PORT(), PRTSM_to_ROOT_PROPOSED(), and PRTSM_to_ROOT_SYNCED().
PRTSM_to_ALTERNATE_AGREED()
static void PRTSM_to_ALTERNATE_AGREED (per_tree_port_t * ptp) static
Definition at line 4089 of file mstp.c.
{
    PRTSM_LOG("");
    ptp->PRTSM_state = PRTSM_ALTERNATE_AGREED;
    ptp->proposed = false;
    ptp->agree = true;
    /* newInfoXst = TRUE; */
    port_t *prt = ptp->port;
    if(0 == ptp->MSTID)
        prt->newInfo = true;
    else
        prt->newInfoMsti = true;
    PRTSM_runr(ptp, true, false /* actual run */);
}
References per_tree_port_t::agree, per_tree_port_t::MSTID, port_t::newInfo, port_t::newInfoMsti, per_tree_port_t::port, per_tree_port_t::proposed, PRTSM_ALTERNATE_AGREED, PRTSM_LOG, PRTSM_runr(), and per_tree_port_t::PRTSM_state.
Referenced by PRTSM_runr().
PRTSM_to_ALTERNATE_PORT()
static void PRTSM_to_ALTERNATE_PORT (per_tree_port_t * ptp, unsigned int forwardDelay) static
Definition at line 4106 of file mstp.c.
{
    PRTSM_LOG("");
    ptp->PRTSM_state = PRTSM_ALTERNATE_PORT;
    assign(ptp->fdWhile, forwardDelay);
    ptp->synced = true;
    assign(ptp->rrWhile, 0u);
    ptp->sync = false;
    ptp->reRoot = false;
    PRTSM_runr(ptp, true, false /* actual run */);
}
References assign, per_tree_port_t::fdWhile, PRTSM_ALTERNATE_PORT, PRTSM_LOG, PRTSM_runr(), per_tree_port_t::PRTSM_state, per_tree_port_t::reRoot, per_tree_port_t::rrWhile, per_tree_port_t::sync, and per_tree_port_t::synced.
Referenced by PRTSM_runr().
PRTSM_to_ALTERNATE_PROPOSED()
static void PRTSM_to_ALTERNATE_PROPOSED (per_tree_port_t * ptp) static
Definition at line 4078 of file mstp.c.
{
    PRTSM_LOG("");
    ptp->PRTSM_state = PRTSM_ALTERNATE_PROPOSED;
    setSyncTree(ptp->tree);
    ptp->proposed = false;
    PRTSM_runr(ptp, true, false /* actual run */);
}
References per_tree_port_t::proposed, PRTSM_ALTERNATE_PROPOSED, PRTSM_LOG, PRTSM_runr(), per_tree_port_t::PRTSM_state, setSyncTree(), and per_tree_port_t::tree.
Referenced by PRTSM_runr().
PRTSM_to_BACKUP_PORT()
static void PRTSM_to_BACKUP_PORT (per_tree_port_t * ptp, unsigned int HelloTime) static
Definition at line 4068 of file mstp.c.
{
    PRTSM_LOG("");
    ptp->PRTSM_state = PRTSM_BACKUP_PORT;
    assign(ptp->rbWhile, 2 * HelloTime);
    PRTSM_runr(ptp, true, false /* actual run */);
}
References assign, PRTSM_BACKUP_PORT, PRTSM_LOG, PRTSM_runr(), per_tree_port_t::PRTSM_state, and per_tree_port_t::rbWhile.
Referenced by PRTSM_runr().
PRTSM_to_BLOCK_PORT()
static void PRTSM_to_BLOCK_PORT (per_tree_port_t * ptp) static
Definition at line 4056 of file mstp.c.
{
    PRTSM_LOG("");
    ptp->PRTSM_state = PRTSM_BLOCK_PORT;
    ptp->role = ptp->selectedRole;
    ptp->learn = false;
    ptp->forward = false;
    PRTSM_runr(ptp, true, false /* actual run */);
}
References per_tree_port_t::forward, per_tree_port_t::learn, PRTSM_BLOCK_PORT, PRTSM_LOG, PRTSM_runr(), per_tree_port_t::PRTSM_state, per_tree_port_t::role, and per_tree_port_t::selectedRole.
Referenced by PRTSM_runr().
PRTSM_to_DESIGNATED_AGREED()
static void PRTSM_to_DESIGNATED_AGREED (per_tree_port_t * ptp) static
Definition at line 3968 of file mstp.c.
{
    PRTSM_LOG("");
    ptp->PRTSM_state = PRTSM_DESIGNATED_AGREED;
    ptp->proposed = false;
    ptp->sync = false;
    ptp->agree = true;
    /* newInfoXst = TRUE; */
    port_t *prt = ptp->port;
    if(0 == ptp->MSTID)
        prt->newInfo = true;
    else
        prt->newInfoMsti = true;
    PRTSM_runr(ptp, true, false /* actual run */);
}
References per_tree_port_t::agree, per_tree_port_t::MSTID, port_t::newInfo, port_t::newInfoMsti, per_tree_port_t::port, per_tree_port_t::proposed, PRTSM_DESIGNATED_AGREED, PRTSM_LOG, PRTSM_runr(), per_tree_port_t::PRTSM_state, and per_tree_port_t::sync.
Referenced by PRTSM_runr().
PRTSM_to_DESIGNATED_DISCARD()
static void PRTSM_to_DESIGNATED_DISCARD (per_tree_port_t * ptp, unsigned int forwardDelay) static
Definition at line 4031 of file mstp.c.
{
    PRTSM_LOG("");
    ptp->PRTSM_state = PRTSM_DESIGNATED_DISCARD;
    ptp->learn = false;
    ptp->forward = false;
    ptp->disputed = false;
    assign(ptp->fdWhile, forwardDelay);
    PRTSM_runr(ptp, true, false /* actual run */);
}
References assign, per_tree_port_t::disputed, per_tree_port_t::fdWhile, per_tree_port_t::forward, per_tree_port_t::learn, PRTSM_DESIGNATED_DISCARD, PRTSM_LOG, PRTSM_runr(), and per_tree_port_t::PRTSM_state.
Referenced by PRTSM_runr().
PRTSM_to_DESIGNATED_FORWARD()
static void PRTSM_to_DESIGNATED_FORWARD (per_tree_port_t * ptp) static
Definition at line 4008 of file mstp.c.
{
    PRTSM_LOG("");
    ptp->PRTSM_state = PRTSM_DESIGNATED_FORWARD;
    ptp->forward = true;
    assign(ptp->fdWhile, 0u);
    ptp->agreed = ptp->port->sendRSTP;
    PRTSM_runr(ptp, true, false /* actual run */);
}
References per_tree_port_t::agreed, assign, per_tree_port_t::fdWhile, per_tree_port_t::forward, per_tree_port_t::port, PRTSM_DESIGNATED_FORWARD, PRTSM_LOG, PRTSM_runr(), per_tree_port_t::PRTSM_state, and port_t::sendRSTP.
Referenced by PRTSM_runr().
PRTSM_to_DESIGNATED_LEARN()
static void PRTSM_to_DESIGNATED_LEARN (per_tree_port_t * ptp, unsigned int forwardDelay) static
Definition at line 4020 of file mstp.c.
{
    PRTSM_LOG("");
    ptp->PRTSM_state = PRTSM_DESIGNATED_LEARN;
    ptp->learn = true;
    assign(ptp->fdWhile, forwardDelay);
    PRTSM_runr(ptp, true, false /* actual run */);
}
References assign, per_tree_port_t::fdWhile, per_tree_port_t::learn, PRTSM_DESIGNATED_LEARN, PRTSM_LOG, PRTSM_runr(), and per_tree_port_t::PRTSM_state.
Referenced by PRTSM_runr().
PRTSM_to_DESIGNATED_PORT()
static void PRTSM_to_DESIGNATED_PORT (per_tree_port_t * ptp) static
Definition at line 4044 of file mstp.c.
{
    PRTSM_LOG("");
    ptp->PRTSM_state = PRTSM_DESIGNATED_PORT;
    ptp->role = roleDesignated;
    PRTSM_runr(ptp, true, false /* actual run */);
}
References PRTSM_DESIGNATED_PORT, PRTSM_LOG, PRTSM_runr(), per_tree_port_t::PRTSM_state, per_tree_port_t::role, and roleDesignated.
Referenced by PRTSM_runr().
PRTSM_to_DESIGNATED_PROPOSE()
static void PRTSM_to_DESIGNATED_PROPOSE (per_tree_port_t * ptp) static
Definition at line 3942 of file mstp.c.
{
    PRTSM_LOG("");
    ptp->PRTSM_state = PRTSM_DESIGNATED_PROPOSE;
    port_t *prt = ptp->port;
    ptp->proposing = true;
    /* newInfoXst = TRUE; */
    if(0 == ptp->MSTID)
    { /* CIST */
        /* 13.25.8. This tree is CIST. */
        unsigned int MaxAge = ptp->designatedTimes.Max_Age;
        /* 13.25.c) -> 17.20.4 of 802.1D : EdgeDelay */
        unsigned int EdgeDelay = prt->operPointToPointMAC ?
                                   prt->bridge->Migrate_Time
                                 : MaxAge;
        assign(prt->edgeDelayWhile, EdgeDelay);
        prt->newInfo = true;
    }
    else
        prt->newInfoMsti = true;
    PRTSM_runr(ptp, true, false /* actual run */);
}
References assign, port_t::bridge, per_tree_port_t::designatedTimes, port_t::edgeDelayWhile, times_t::Max_Age, bridge_t::Migrate_Time, per_tree_port_t::MSTID, port_t::newInfo, port_t::newInfoMsti, port_t::operPointToPointMAC, per_tree_port_t::port, per_tree_port_t::proposing, PRTSM_DESIGNATED_PROPOSE, PRTSM_LOG, PRTSM_runr(), and per_tree_port_t::PRTSM_state.
Referenced by PRTSM_runr().
PRTSM_to_DESIGNATED_RETIRED()
static void PRTSM_to_DESIGNATED_RETIRED (per_tree_port_t * ptp) static
Definition at line 3998 of file mstp.c.
{
    PRTSM_LOG("");
    ptp->PRTSM_state = PRTSM_DESIGNATED_RETIRED;
    ptp->reRoot = false;
    PRTSM_runr(ptp, true, false /* actual run */);
}
References PRTSM_DESIGNATED_RETIRED, PRTSM_LOG, PRTSM_runr(), per_tree_port_t::PRTSM_state, and per_tree_port_t::reRoot.
Referenced by PRTSM_runr().
PRTSM_to_DESIGNATED_SYNCED()
static void PRTSM_to_DESIGNATED_SYNCED (per_tree_port_t * ptp) static
Definition at line 3986 of file mstp.c.
{
    PRTSM_LOG("");
    ptp->PRTSM_state = PRTSM_DESIGNATED_SYNCED;
    assign(ptp->rrWhile, 0u);
    ptp->synced = true;
    ptp->sync = false;
    PRTSM_runr(ptp, true, false /* actual run */);
}
References assign, PRTSM_DESIGNATED_SYNCED, PRTSM_LOG, PRTSM_runr(), per_tree_port_t::PRTSM_state, per_tree_port_t::rrWhile, per_tree_port_t::sync, and per_tree_port_t::synced.
Referenced by PRTSM_runr().
PRTSM_to_DISABLE_PORT()
static void PRTSM_to_DISABLE_PORT (per_tree_port_t * ptp) static
Definition at line 3707 of file mstp.c.
{
    PRTSM_LOG("");
    ptp->PRTSM_state = PRTSM_DISABLE_PORT;
    /* Although 802.1Q-2005 says here to do role = selectedRole
     * I have difficulties with it in the next scenario:
     *  1) port was designated (role == selectedRole == roleDesignated)
     *  2) some config event occurs, e.g. MAC address changes and
     *     br_state_machines_begin is called
     *  3) role == selectedRole == roleDisabled, PRTSM_state = PRTSM_INIT_PORT
     * Because port was not actually down, on the next run
     *  Port Role Selection state machine sets selectedRole = roleDesignated
     *  and updtInfo = true:
     *  4) we have unconditional transition to DISABLE_PORT, and because
     *     updtInfo = true we can not follow transition to DESIGNATED_PORT
     *  5) if we follow standard, role = selectedRole = roleDesignated and
     *     on the next run we have transition to the DISABLED_PORT
     * And there we stuck. role == selectedRole, so we can not transit to
     *  DESIGNATED_PORT (it requires role != selectedRole ).
     *
     * Solution: do not follow the standard, and do role = roleDisabled
     *  instead of role = selectedRole.
     */
    ptp->role = roleDisabled;
    ptp->learn = false;
    ptp->forward = false;
    PRTSM_runr(ptp, true, false /* actual run */);
}
References per_tree_port_t::forward, per_tree_port_t::learn, PRTSM_DISABLE_PORT, PRTSM_LOG, PRTSM_runr(), per_tree_port_t::PRTSM_state, per_tree_port_t::role, and roleDisabled.
Referenced by PRTSM_runr().
PRTSM_to_DISABLED_PORT()
static void PRTSM_to_DISABLED_PORT (per_tree_port_t * ptp, unsigned int MaxAge) static
Definition at line 3738 of file mstp.c.
{
    PRTSM_LOG("");
    ptp->PRTSM_state = PRTSM_DISABLED_PORT;
    assign(ptp->fdWhile, MaxAge);
    ptp->synced = true;
    assign(ptp->rrWhile, 0u);
    ptp->sync = false;
    ptp->reRoot = false;
    PRTSM_runr(ptp, true, false /* actual run */);
}
References assign, per_tree_port_t::fdWhile, PRTSM_DISABLED_PORT, PRTSM_LOG, PRTSM_runr(), per_tree_port_t::PRTSM_state, per_tree_port_t::reRoot, per_tree_port_t::rrWhile, per_tree_port_t::sync, and per_tree_port_t::synced.
Referenced by PRTSM_runr().
PRTSM_to_INIT_PORT()
static void PRTSM_to_INIT_PORT (per_tree_port_t * ptp) static
Definition at line 3678 of file mstp.c.
{
    PRTSM_LOG("");
    ptp->PRTSM_state = PRTSM_INIT_PORT;
    unsigned int MaxAge, FwdDelay;
    per_tree_port_t *cist = GET_CIST_PTP_FROM_PORT(ptp->port);
    ptp->role = roleDisabled;
    ptp->learn = false;
    ptp->forward = false;
    ptp->synced = false;
    ptp->sync = true;
    ptp->reRoot = true;
    /* 13.25.6 */
    FwdDelay = cist->designatedTimes.Forward_Delay;
    assign(ptp->rrWhile, FwdDelay);
    /* 13.25.8 */
    MaxAge = cist->designatedTimes.Max_Age;
    assign(ptp->fdWhile, MaxAge);
    assign(ptp->rbWhile, 0u);
    /* No need to check, as we assume begin = true here
     * because transition to this state can be initiated only by BEGIN var.
     * In other words, this function is called via xxx_begin macro only.
     * if(!begin)
     *     PRTSM_runr(ptp, false, false); */
}
References assign, per_tree_port_t::designatedTimes, per_tree_port_t::fdWhile, per_tree_port_t::forward, times_t::Forward_Delay, GET_CIST_PTP_FROM_PORT, per_tree_port_t::learn, times_t::Max_Age, per_tree_port_t::port, PRTSM_INIT_PORT, PRTSM_LOG, per_tree_port_t::PRTSM_state, per_tree_port_t::rbWhile, per_tree_port_t::reRoot, per_tree_port_t::role, roleDisabled, per_tree_port_t::rrWhile, per_tree_port_t::sync, and per_tree_port_t::synced.
PRTSM_to_MASTER_AGREED()
static void PRTSM_to_MASTER_AGREED (per_tree_port_t * ptp) static
Definition at line 3765 of file mstp.c.
{
    PRTSM_LOG("");
    ptp->PRTSM_state = PRTSM_MASTER_AGREED;
    ptp->proposed = false;
    ptp->sync = false;
    ptp->agree = true;
    PRTSM_runr(ptp, true, false /* actual run */);
}
References per_tree_port_t::agree, per_tree_port_t::proposed, PRTSM_LOG, PRTSM_MASTER_AGREED, PRTSM_runr(), per_tree_port_t::PRTSM_state, and per_tree_port_t::sync.
Referenced by PRTSM_runr().
PRTSM_to_MASTER_DISCARD()
static void PRTSM_to_MASTER_DISCARD (per_tree_port_t * ptp, unsigned int forwardDelay) static
Definition at line 3822 of file mstp.c.
{
    PRTSM_LOG("");
    ptp->PRTSM_state = PRTSM_MASTER_DISCARD;
    ptp->learn = false;
    ptp->forward = false;
    ptp->disputed = false;
    assign(ptp->fdWhile, forwardDelay);
    PRTSM_runr(ptp, true, false /* actual run */);
}
References assign, per_tree_port_t::disputed, per_tree_port_t::fdWhile, per_tree_port_t::forward, per_tree_port_t::learn, PRTSM_LOG, PRTSM_MASTER_DISCARD, PRTSM_runr(), and per_tree_port_t::PRTSM_state.
Referenced by PRTSM_runr().
PRTSM_to_MASTER_FORWARD()
static void PRTSM_to_MASTER_FORWARD (per_tree_port_t * ptp) static
Definition at line 3799 of file mstp.c.
{
    PRTSM_LOG("");
    ptp->PRTSM_state = PRTSM_MASTER_FORWARD;
    ptp->forward = true;
    assign(ptp->fdWhile, 0u);
    ptp->agreed = ptp->port->sendRSTP;
    PRTSM_runr(ptp, true, false /* actual run */);
}
References per_tree_port_t::agreed, assign, per_tree_port_t::fdWhile, per_tree_port_t::forward, per_tree_port_t::port, PRTSM_LOG, PRTSM_MASTER_FORWARD, PRTSM_runr(), per_tree_port_t::PRTSM_state, and port_t::sendRSTP.
Referenced by PRTSM_runr().
PRTSM_to_MASTER_LEARN()
static void PRTSM_to_MASTER_LEARN (per_tree_port_t * ptp, unsigned int forwardDelay) static
Definition at line 3811 of file mstp.c.
{
    PRTSM_LOG("");
    ptp->PRTSM_state = PRTSM_MASTER_LEARN;
    ptp->learn = true;
    assign(ptp->fdWhile, forwardDelay);
    PRTSM_runr(ptp, true, false /* actual run */);
}
References assign, per_tree_port_t::fdWhile, per_tree_port_t::learn, PRTSM_LOG, PRTSM_MASTER_LEARN, PRTSM_runr(), and per_tree_port_t::PRTSM_state.
Referenced by PRTSM_runr().
PRTSM_to_MASTER_PORT()
static void PRTSM_to_MASTER_PORT (per_tree_port_t * ptp) static
Definition at line 3835 of file mstp.c.
{
    PRTSM_LOG("");
    ptp->PRTSM_state = PRTSM_MASTER_PORT;
    ptp->role = roleMaster;
    PRTSM_runr(ptp, true, false /* actual run */);
}
References PRTSM_LOG, PRTSM_MASTER_PORT, PRTSM_runr(), per_tree_port_t::PRTSM_state, per_tree_port_t::role, and roleMaster.
Referenced by PRTSM_runr().
PRTSM_to_MASTER_PROPOSED()
static void PRTSM_to_MASTER_PROPOSED (per_tree_port_t * ptp) static
Definition at line 3754 of file mstp.c.
{
    PRTSM_LOG("");
    ptp->PRTSM_state = PRTSM_MASTER_PROPOSED;
    setSyncTree(ptp->tree);
    ptp->proposed = false;
    PRTSM_runr(ptp, true, false /* actual run */);
}
References per_tree_port_t::proposed, PRTSM_LOG, PRTSM_MASTER_PROPOSED, PRTSM_runr(), per_tree_port_t::PRTSM_state, setSyncTree(), and per_tree_port_t::tree.
Referenced by PRTSM_runr().
PRTSM_to_MASTER_RETIRED()
static void PRTSM_to_MASTER_RETIRED (per_tree_port_t * ptp) static
Definition at line 3789 of file mstp.c.
{
    PRTSM_LOG("");
    ptp->PRTSM_state = PRTSM_MASTER_RETIRED;
    ptp->reRoot = false;
    PRTSM_runr(ptp, true, false /* actual run */);
}
References PRTSM_LOG, PRTSM_MASTER_RETIRED, PRTSM_runr(), per_tree_port_t::PRTSM_state, and per_tree_port_t::reRoot.
Referenced by PRTSM_runr().
PRTSM_to_MASTER_SYNCED()
static void PRTSM_to_MASTER_SYNCED (per_tree_port_t * ptp) static
Definition at line 3777 of file mstp.c.
{
    PRTSM_LOG("");
    ptp->PRTSM_state = PRTSM_MASTER_SYNCED;
    assign(ptp->rrWhile, 0u);
    ptp->synced = true;
    ptp->sync = false;
    PRTSM_runr(ptp, true, false /* actual run */);
}
References assign, PRTSM_LOG, PRTSM_MASTER_SYNCED, PRTSM_runr(), per_tree_port_t::PRTSM_state, per_tree_port_t::rrWhile, per_tree_port_t::sync, and per_tree_port_t::synced.
Referenced by PRTSM_runr().
PRTSM_to_REROOT()
static void PRTSM_to_REROOT (per_tree_port_t * ptp) static
Definition at line 3887 of file mstp.c.
{
    PRTSM_LOG("");
    ptp->PRTSM_state = PRTSM_REROOT;
    setReRootTree(ptp->tree);
    PRTSM_runr(ptp, true, false /* actual run */);
}
References PRTSM_LOG, PRTSM_REROOT, PRTSM_runr(), per_tree_port_t::PRTSM_state, setReRootTree(), and per_tree_port_t::tree.
Referenced by PRTSM_runr().
PRTSM_to_REROOTED()
static void PRTSM_to_REROOTED (per_tree_port_t * ptp) static
Definition at line 3919 of file mstp.c.
{
    PRTSM_LOG("");
    ptp->PRTSM_state = PRTSM_REROOTED;
    ptp->reRoot = false;
    PRTSM_runr(ptp, true, false /* actual run */);
}
References PRTSM_LOG, PRTSM_REROOTED, PRTSM_runr(), per_tree_port_t::PRTSM_state, and per_tree_port_t::reRoot.
Referenced by PRTSM_runr().
PRTSM_to_ROOT_AGREED()
static void PRTSM_to_ROOT_AGREED (per_tree_port_t * ptp) static
Definition at line 3858 of file mstp.c.
{
    PRTSM_LOG("");
    ptp->PRTSM_state = PRTSM_ROOT_AGREED;
    ptp->proposed = false;
    ptp->sync = false;
    ptp->agree = true;
    /* newInfoXst = TRUE; */
    port_t *prt = ptp->port;
    if(0 == ptp->MSTID)
        prt->newInfo = true;
    else
        prt->newInfoMsti = true;
    PRTSM_runr(ptp, true, false /* actual run */);
}
References per_tree_port_t::agree, per_tree_port_t::MSTID, port_t::newInfo, port_t::newInfoMsti, per_tree_port_t::port, per_tree_port_t::proposed, PRTSM_LOG, PRTSM_ROOT_AGREED, PRTSM_runr(), per_tree_port_t::PRTSM_state, and per_tree_port_t::sync.
Referenced by PRTSM_runr().
PRTSM_to_ROOT_FORWARD()
static void PRTSM_to_ROOT_FORWARD (per_tree_port_t * ptp) static
Definition at line 3897 of file mstp.c.
{
    PRTSM_LOG("");
    ptp->PRTSM_state = PRTSM_ROOT_FORWARD;
    assign(ptp->fdWhile, 0u);
    ptp->forward = true;
    PRTSM_runr(ptp, true, false /* actual run */);
}
References assign, per_tree_port_t::fdWhile, per_tree_port_t::forward, PRTSM_LOG, PRTSM_ROOT_FORWARD, PRTSM_runr(), and per_tree_port_t::PRTSM_state.
Referenced by PRTSM_runr().
PRTSM_to_ROOT_LEARN()
static void PRTSM_to_ROOT_LEARN (per_tree_port_t * ptp, unsigned int forwardDelay) static
Definition at line 3908 of file mstp.c.
{
    PRTSM_LOG("");
    ptp->PRTSM_state = PRTSM_ROOT_LEARN;
    assign(ptp->fdWhile, forwardDelay);
    ptp->learn = true;
    PRTSM_runr(ptp, true, false /* actual run */);
}
References assign, per_tree_port_t::fdWhile, per_tree_port_t::learn, PRTSM_LOG, PRTSM_ROOT_LEARN, PRTSM_runr(), and per_tree_port_t::PRTSM_state.
Referenced by PRTSM_runr().
PRTSM_to_ROOT_PORT()
static void PRTSM_to_ROOT_PORT (per_tree_port_t * ptp, unsigned int FwdDelay) static
Definition at line 3929 of file mstp.c.
{
    PRTSM_LOG("");
    ptp->PRTSM_state = PRTSM_ROOT_PORT;
    ptp->role = roleRoot;
    assign(ptp->rrWhile, FwdDelay);
    PRTSM_runr(ptp, true, false /* actual run */);
}
References assign, PRTSM_LOG, PRTSM_ROOT_PORT, PRTSM_runr(), per_tree_port_t::PRTSM_state, per_tree_port_t::role, roleRoot, and per_tree_port_t::rrWhile.
Referenced by PRTSM_runr().
PRTSM_to_ROOT_PROPOSED()
static void PRTSM_to_ROOT_PROPOSED (per_tree_port_t * ptp) static
Definition at line 3847 of file mstp.c.
{
    PRTSM_LOG("");
    ptp->PRTSM_state = PRTSM_ROOT_PROPOSED;
    setSyncTree(ptp->tree);
    ptp->proposed = false;
    PRTSM_runr(ptp, true, false /* actual run */);
}
References per_tree_port_t::proposed, PRTSM_LOG, PRTSM_ROOT_PROPOSED, PRTSM_runr(), per_tree_port_t::PRTSM_state, setSyncTree(), and per_tree_port_t::tree.
Referenced by PRTSM_runr().
PRTSM_to_ROOT_SYNCED()
static void PRTSM_to_ROOT_SYNCED (per_tree_port_t * ptp) static
Definition at line 3876 of file mstp.c.
{
    PRTSM_LOG("");
    ptp->PRTSM_state = PRTSM_ROOT_SYNCED;
    ptp->synced = true;
    ptp->sync = false;
    PRTSM_runr(ptp, true, false /* actual run */);
}
References PRTSM_LOG, PRTSM_ROOT_SYNCED, PRTSM_runr(), per_tree_port_t::PRTSM_state, per_tree_port_t::sync, and per_tree_port_t::synced.
Referenced by PRTSM_runr().
PSTSM_run()
static bool PSTSM_run (per_tree_port_t * ptp, bool dry_run) static
Definition at line 4634 of file mstp.c.
{
    switch(ptp->PSTSM_state)
    {
        case PSTSM_DISCARDING:
            if(ptp->learn)
            {
                if(dry_run) /* state change */
                    return true;
                PSTSM_to_LEARNING(ptp);
            }
            return false;
        case PSTSM_LEARNING:
            if(!ptp->learn)
            {
                if(dry_run) /* state change */
                    return true;
                PSTSM_to_DISCARDING(ptp, false);
            }
            else if(ptp->forward)
            {
                if(dry_run) /* state change */
                    return true;
                PSTSM_to_FORWARDING(ptp);
            }
            return false;
        case PSTSM_FORWARDING:
            if(!ptp->forward)
            {
                if(dry_run) /* state change */
                    return true;
                PSTSM_to_DISCARDING(ptp, false);
            }
            return false;
    }
    return false;
}
References dry_run, per_tree_port_t::forward, per_tree_port_t::learn, PSTSM_DISCARDING, PSTSM_FORWARDING, PSTSM_LEARNING, per_tree_port_t::PSTSM_state, PSTSM_to_DISCARDING(), PSTSM_to_FORWARDING(), and PSTSM_to_LEARNING().
Referenced by __br_state_machines_run(), PSTSM_to_DISCARDING(), and PSTSM_to_LEARNING().
PSTSM_to_DISCARDING()
static void PSTSM_to_DISCARDING (per_tree_port_t * ptp, bool begin) static
Definition at line 4583 of file mstp.c.
{
    ptp->PSTSM_state = PSTSM_DISCARDING;
    /* This effectively sets BLOCKING state:
    disableLearning();
    disableForwarding();
    */
    if(BR_STATE_BLOCKING != ptp->state)
    {
        if(!ptp->port->deleted)
            MSTP_OUT_set_state(ptp, BR_STATE_BLOCKING);
    }
    ptp->learning = false;
    ptp->forwarding = false;
    if(!begin)
        PSTSM_run(ptp, false /* actual run */);
}
References port_t::deleted, per_tree_port_t::forwarding, per_tree_port_t::learning, MSTP_OUT_set_state(), per_tree_port_t::port, PSTSM_DISCARDING, PSTSM_run(), per_tree_port_t::PSTSM_state, and per_tree_port_t::state.
Referenced by PSTSM_run().
PSTSM_to_FORWARDING()
static void PSTSM_to_FORWARDING (per_tree_port_t * ptp) static
Definition at line 4618 of file mstp.c.
{
    ptp->PSTSM_state = PSTSM_FORWARDING;
    /* enableForwarding(); */
    if(BR_STATE_FORWARDING != ptp->state)
    {
        if(!ptp->port->deleted)
            MSTP_OUT_set_state(ptp, BR_STATE_FORWARDING);
    }
    ptp->forwarding = true;
    /* No need to run, no one condition will be met
      PSTSM_run(ptp, false); */
}
References port_t::deleted, per_tree_port_t::forwarding, MSTP_OUT_set_state(), per_tree_port_t::port, PSTSM_FORWARDING, per_tree_port_t::PSTSM_state, and per_tree_port_t::state.
Referenced by PSTSM_run().
PSTSM_to_LEARNING()
static void PSTSM_to_LEARNING (per_tree_port_t * ptp) static
Definition at line 4603 of file mstp.c.
{
    ptp->PSTSM_state = PSTSM_LEARNING;
    /* enableLearning(); */
    if(BR_STATE_LEARNING != ptp->state)
    {
        if(!ptp->port->deleted)
            MSTP_OUT_set_state(ptp, BR_STATE_LEARNING);
    }
    ptp->learning = true;
    PSTSM_run(ptp, false /* actual run */);
}
References port_t::deleted, per_tree_port_t::learning, MSTP_OUT_set_state(), per_tree_port_t::port, PSTSM_LEARNING, PSTSM_run(), per_tree_port_t::PSTSM_state, and per_tree_port_t::state.
Referenced by PSTSM_run().
ptp_default_internal_vars()
static void ptp_default_internal_vars (per_tree_port_t * ptp) static
Definition at line 150 of file mstp.c.
{
    ptp->rcvdTc = false;
    ptp->tcProp = false;
    ptp->updtInfo = false;
    ptp->master = false; /* 13.24.5 */
    ptp->disputed = false;
    assign(ptp->rcvdInfo, (port_info_t)0);
    ptp->mastered = false;
    memset(&ptp->msgPriority, 0, sizeof(ptp->msgPriority));
    memset(&ptp->msgTimes, 0, sizeof(ptp->msgTimes));
    /* The following are initialized in BEGIN state:
     * - rcvdMsg: in Port Receive SM
     * - fdWhile, rrWhile, rbWhile, role, learn, forward,
     *   sync, synced, reRoot: in Port Role Transitions SM
     * - tcWhile, fdbFlush: Topology Change SM
     * - rcvdInfoWhile, proposed, proposing, agree, agreed,
     *   infoIs, reselect, selected: Port Information SM
     * - forwarding, learning: Port State Transition SM
     * - selectedRole, designatedPriority, designatedTimes: Port Role Selection SM
     */
}
References assign, per_tree_port_t::disputed, per_tree_port_t::master, per_tree_port_t::mastered, per_tree_port_t::msgPriority, per_tree_port_t::msgTimes, per_tree_port_t::rcvdInfo, per_tree_port_t::rcvdTc, per_tree_port_t::tcProp, and per_tree_port_t::updtInfo.
Referenced by create_ptp(), and MSTP_IN_set_bridge_enable().
PTSM_run()
static bool PTSM_run (port_t * prt, bool dry_run) static
Definition at line 3223 of file mstp.c.
{
   /* bool allTransmitReady; */
    per_tree_port_t *ptp;
    port_role_t cistRole;
    bool mstiMasterPort;
    if(!prt->portEnabled)
    {
        return PTSM_to_TRANSMIT_INIT(prt, false, dry_run);
    }
    switch(prt->PTSM_state)
    {
        case PTSM_TRANSMIT_INIT:
           /* return; */
        case PTSM_TRANSMIT_CONFIG:
           /* return; */
        case PTSM_TRANSMIT_TCN:
           /* return; */
        case PTSM_TRANSMIT_RSTP:
           /* return; */
        case PTSM_TRANSMIT_PERIODIC:
            if(dry_run) /* state change */
                return true;
            PTSM_to_IDLE(prt); /* UnConditional Transition */
            return false;
        case PTSM_IDLE:
            /* allTransmitReady = true; */
            ptp = GET_CIST_PTP_FROM_PORT(prt);
            if(!ptp->selected || ptp->updtInfo)
            {
                /* allTransmitReady = false; */
                return false;
            }
            cistRole = ptp->role;
            mstiMasterPort = false;
            list_for_each_entry_continue(ptp, &prt->trees, port_list)
            {
                if(!ptp->selected || ptp->updtInfo)
                {
                    /* allTransmitReady = false; */
                    return false;
                }
                if(roleMaster == ptp->role)
                    mstiMasterPort = true;
            }
            if(0 == prt->helloWhen)
            {
                if(dry_run) /* state change */
                    return true;
                PTSM_to_TRANSMIT_PERIODIC(prt);
                return false;
            }
            if(!(prt->txCount < prt->bridge->Transmit_Hold_Count))
                return false;
            if(prt->bpduFilterPort)
                return false;
            if(prt->sendRSTP)
            { /* implement MSTP */
                if(prt->newInfo || (prt->newInfoMsti && !mstiMasterPort)
                   || assurancePort(prt)
                  )
                {
                    if(dry_run) /* state change */
                        return true;
                    PTSM_to_TRANSMIT_RSTP(prt);
                    return false;
                }
            }
            else
            { /* fallback to STP */
                if(prt->newInfo && (roleDesignated == cistRole))
                {
                    if(dry_run) /* state change */
                        return true;
                    PTSM_to_TRANSMIT_CONFIG(prt);
                    return false;
                }
                if(prt->newInfo && (roleRoot == cistRole))
                {
                    if(dry_run) /* state change */
                        return true;
                    PTSM_to_TRANSMIT_TCN(prt);
                    return false;
                }
            }
            return false;
    }
    return false;
}
References assurancePort, port_t::bpduFilterPort, port_t::bridge, dry_run, GET_CIST_PTP_FROM_PORT, port_t::helloWhen, list_for_each_entry_continue, port_t::newInfo, port_t::newInfoMsti, port_t::portEnabled, PTSM_IDLE, port_t::PTSM_state, PTSM_to_IDLE(), PTSM_to_TRANSMIT_CONFIG(), PTSM_to_TRANSMIT_INIT(), PTSM_to_TRANSMIT_PERIODIC(), PTSM_to_TRANSMIT_RSTP(), PTSM_to_TRANSMIT_TCN(), PTSM_TRANSMIT_CONFIG, PTSM_TRANSMIT_INIT, PTSM_TRANSMIT_PERIODIC, PTSM_TRANSMIT_RSTP, PTSM_TRANSMIT_TCN, per_tree_port_t::role, roleDesignated, roleMaster, roleRoot, per_tree_port_t::selected, port_t::sendRSTP, bridge_t::Transmit_Hold_Count, port_t::trees, port_t::txCount, and per_tree_port_t::updtInfo.
Referenced by __br_state_machines_run(), PTSM_to_IDLE(), PTSM_to_TRANSMIT_CONFIG(), PTSM_to_TRANSMIT_INIT(), PTSM_to_TRANSMIT_PERIODIC(), PTSM_to_TRANSMIT_RSTP(), and PTSM_to_TRANSMIT_TCN().
PTSM_tick()
static void PTSM_tick (port_t * prt) static
Definition at line 2848 of file mstp.c.
{
    per_tree_port_t *ptp;
    if(prt->helloWhen)
        --(prt->helloWhen);
    if(prt->mdelayWhile)
        --(prt->mdelayWhile);
    if(prt->edgeDelayWhile)
        --(prt->edgeDelayWhile);
    if(prt->txCount)
        --(prt->txCount);
    if(prt->brAssuRcvdInfoWhile)
        --(prt->brAssuRcvdInfoWhile);
    FOREACH_PTP_IN_PORT(ptp, prt)
    {
        if(ptp->fdWhile)
            --(ptp->fdWhile);
        if(ptp->rrWhile)
            --(ptp->rrWhile);
        if(ptp->rbWhile)
            --(ptp->rbWhile);
        if(ptp->tcWhile)
        {
            if(0 == --(ptp->tcWhile))
                set_TopologyChange(ptp->tree, false, prt);
        }
        if(ptp->rcvdInfoWhile)
            --(ptp->rcvdInfoWhile);
    }
}
References port_t::brAssuRcvdInfoWhile, port_t::edgeDelayWhile, per_tree_port_t::fdWhile, FOREACH_PTP_IN_PORT, port_t::helloWhen, port_t::mdelayWhile, per_tree_port_t::rbWhile, per_tree_port_t::rcvdInfoWhile, per_tree_port_t::rrWhile, set_TopologyChange(), per_tree_port_t::tcWhile, per_tree_port_t::tree, and port_t::txCount.
Referenced by MSTP_IN_one_second().
PTSM_to_IDLE()
static void PTSM_to_IDLE (port_t * prt) static
Definition at line 3213 of file mstp.c.
{
    prt->PTSM_state = PTSM_IDLE;
    per_tree_port_t *cist = GET_CIST_PTP_FROM_PORT(prt);
    prt->helloWhen = cist->portTimes.Hello_Time;
    PTSM_run(prt, false /* actual run */);
}
References GET_CIST_PTP_FROM_PORT, times_t::Hello_Time, port_t::helloWhen, per_tree_port_t::portTimes, PTSM_IDLE, PTSM_run(), and port_t::PTSM_state.
Referenced by PTSM_run().
PTSM_to_TRANSMIT_CONFIG()
static void PTSM_to_TRANSMIT_CONFIG (port_t * prt) static
Definition at line 3148 of file mstp.c.
{
    prt->PTSM_state = PTSM_TRANSMIT_CONFIG;
    prt->newInfo = false;
    txConfig(prt);
    ++(prt->txCount);
    prt->tcAck = false;
    PTSM_run(prt, false /* actual run */);
}
References port_t::newInfo, PTSM_run(), port_t::PTSM_state, PTSM_TRANSMIT_CONFIG, port_t::tcAck, txConfig(), and port_t::txCount.
Referenced by PTSM_run().
PTSM_to_TRANSMIT_INIT()
static bool PTSM_to_TRANSMIT_INIT (port_t * prt, bool begin, bool dry_run) static
Definition at line 3128 of file mstp.c.
{
    if(dry_run)
    {
        return (prt->PTSM_state != PTSM_TRANSMIT_INIT)
               || (!prt->newInfo) || (!prt->newInfoMsti)
               || (0 != prt->txCount);
    }
    prt->PTSM_state = PTSM_TRANSMIT_INIT;
    prt->newInfo = true;
    prt->newInfoMsti = true;
    assign(prt->txCount, 0u);
    if(!begin && prt->portEnabled) /* prevent infinite loop */
        PTSM_run(prt, false /* actual run */);
    return false;
}
References assign, dry_run, port_t::newInfo, port_t::newInfoMsti, port_t::portEnabled, PTSM_run(), port_t::PTSM_state, PTSM_TRANSMIT_INIT, and port_t::txCount.
Referenced by PTSM_run().
PTSM_to_TRANSMIT_PERIODIC()
static void PTSM_to_TRANSMIT_PERIODIC (port_t * prt) static
Definition at line 3184 of file mstp.c.
{
    prt->PTSM_state = PTSM_TRANSMIT_PERIODIC;
    per_tree_port_t *ptp = GET_CIST_PTP_FROM_PORT(prt);
    bool cistDesignatedOrTCpropagatingRootPort =
        (roleDesignated == ptp->role)
        || ((roleRoot == ptp->role) && (0 != ptp->tcWhile));
    bool mstiDesignatedOrTCpropagatingRootPort;
    mstiDesignatedOrTCpropagatingRootPort = false;
    list_for_each_entry_continue(ptp, &prt->trees, port_list)
    {
        if((roleDesignated == ptp->role)
           || ((roleRoot == ptp->role) && (0 != ptp->tcWhile))
          )
        {
            mstiDesignatedOrTCpropagatingRootPort = true;
            break;
        }
    }
    prt->newInfo = prt->newInfo || cistDesignatedOrTCpropagatingRootPort;
    prt->newInfoMsti = prt->newInfoMsti
                       || mstiDesignatedOrTCpropagatingRootPort;
    PTSM_run(prt, false /* actual run */);
}
References GET_CIST_PTP_FROM_PORT, list_for_each_entry_continue, port_t::newInfo, port_t::newInfoMsti, PTSM_run(), port_t::PTSM_state, PTSM_TRANSMIT_PERIODIC, per_tree_port_t::role, roleDesignated, roleRoot, per_tree_port_t::tcWhile, and port_t::trees.
Referenced by PTSM_run().
PTSM_to_TRANSMIT_RSTP()
static void PTSM_to_TRANSMIT_RSTP (port_t * prt) static
Definition at line 3171 of file mstp.c.
{
    prt->PTSM_state = PTSM_TRANSMIT_RSTP;
    prt->newInfo = false;
    prt->newInfoMsti = false;
    txMstp(prt);
    ++(prt->txCount);
    prt->tcAck = false;
    PTSM_run(prt, false /* actual run */);
}
References port_t::newInfo, port_t::newInfoMsti, PTSM_run(), port_t::PTSM_state, PTSM_TRANSMIT_RSTP, port_t::tcAck, port_t::txCount, and txMstp().
Referenced by PTSM_run().
PTSM_to_TRANSMIT_TCN()
static void PTSM_to_TRANSMIT_TCN (port_t * prt) static
Definition at line 3160 of file mstp.c.
{
    prt->PTSM_state = PTSM_TRANSMIT_TCN;
    prt->newInfo = false;
    txTcn(prt);
    ++(prt->txCount);
    PTSM_run(prt, false /* actual run */);
}
References port_t::newInfo, PTSM_run(), port_t::PTSM_state, PTSM_TRANSMIT_TCN, port_t::txCount, and txTcn().
Referenced by PTSM_run().
rcvInfo()
static port_info_t rcvInfo (per_tree_port_t * ptp) static
Definition at line 1834 of file mstp.c.
{
    msti_configuration_message_t *msti_msg;
    per_tree_port_t *ptp_1;
    bool roleIsDesignated, cist;
    bool msg_Better_port, msg_SamePriorityAndTimers_port;
    port_priority_vector_t *mPri = &(ptp->msgPriority);
    times_t *mTimes = &(ptp->msgTimes);
    port_t *prt = ptp->port;
    bpdu_t *b = &(prt->rcvdBpduData);
    if(bpduTypeTCN == b->bpduType)
    {
        prt->rcvdTcn = true;
        FOREACH_PTP_IN_PORT(ptp_1, prt)
            ptp_1->rcvdTc = true;
        return OtherInfo;
    }
    if(0 == ptp->MSTID)
    { /* CIST */
        if(protoSTP != b->protocolVersion)
        {
            switch(BPDU_FLAGS_ROLE_GET(b->flags))
            {
                case encodedRoleAlternateBackup:
                case encodedRoleRoot:
                    roleIsDesignated = false;
                    break;
                case encodedRoleDesignated:
                    roleIsDesignated = true;
                    break;
                case encodedRoleMaster:
                    /* 802.1D-2004 S9.2.9 P61. The Unknown value of Port Role
                     * cannot be generated by a valid implementation; however,
                     * this value is accepted on receipt. roleMaster in MSTP is
                     * roleUnknown in RSTP.
                     * NOTE.If the Unknown value of the Port Role parameter is
                     * received, the state machines will effectively treat the RST
                     * BPDU as if it were a Configuration BPDU
                     */
                    if(protoRSTP == b->protocolVersion)
                    {
                        roleIsDesignated = true;
                        break;
                    }
                    else
                    {
                        return OtherInfo;
                    }
                    break;
                default:
                    return OtherInfo;
            }
        }
        else
        { /* 13.26.6.NOTE: A Configuration BPDU implicitly conveys a
           *   Designated Port Role */
            roleIsDesignated = true;
        }
        cist = true;
        assign(mPri->RRootID, b->cistRRootID);
        assign(mPri->DesignatedPortID, b->cistPortID);
        assign(mPri->RootID, b->cistRootID);
        assign(mPri->ExtRootPathCost, b->cistExtRootPathCost);
        /* messageTimes */
#define NEAREST_WHOLE_SECOND(msgTime)  \
    ((128 > msgTime[1]) ? msgTime[0] : msgTime[0] + 1)
        mTimes->Forward_Delay = NEAREST_WHOLE_SECOND(b->ForwardDelay);
        mTimes->Max_Age = NEAREST_WHOLE_SECOND(b->MaxAge);
        mTimes->Message_Age = NEAREST_WHOLE_SECOND(b->MessageAge);
        mTimes->Hello_Time = NEAREST_WHOLE_SECOND(b->HelloTime);
        if(protoMSTP > b->protocolVersion)
        { /* STP Configuration BPDU or RST BPDU */
            assign(mPri->IntRootPathCost, __constant_cpu_to_be32(0));
            assign(mPri->DesignatedBridgeID, b->cistRRootID);
            /* messageTimes.remainingHops */
            assign(mTimes->remainingHops, prt->bridge->MaxHops);
        }
        else
        { /* MST BPDU */
            assign(mPri->IntRootPathCost, b->cistIntRootPathCost);
            assign(mPri->DesignatedBridgeID, b->cistBridgeID);
            /* messageTimes.remainingHops */
            assign(mTimes->remainingHops, b->cistRemainingHops);
        }
    }
    else
    { /* MSTI */
        if(protoMSTP > b->protocolVersion)
            return OtherInfo;
        msti_msg = ptp->rcvdMstiConfig;
        switch(BPDU_FLAGS_ROLE_GET(msti_msg->flags))
        {
            case encodedRoleAlternateBackup:
            case encodedRoleRoot:
                roleIsDesignated = false;
                break;
            case encodedRoleDesignated:
                roleIsDesignated = true;
                break;
            default:
                return OtherInfo;
        }
        cist = false;
        assign(mPri->RRootID, msti_msg->mstiRRootID);
        assign(mPri->IntRootPathCost, msti_msg->mstiIntRootPathCost);
        /* Build MSTI DesignatedBridgeID */
        assign(mPri->DesignatedBridgeID, b->cistBridgeID);
        assign(mPri->DesignatedBridgeID.s.priority, ptp->MSTID);
        SET_PRIORITY_IN_IDENTIFIER(msti_msg->bridgeIdentifierPriority,
                                   mPri->DesignatedBridgeID);
        /* Build MSTI DesignatedPortID */
        assign(mPri->DesignatedPortID, b->cistPortID);
        SET_PRIORITY_IN_IDENTIFIER(msti_msg->portIdentifierPriority,
                                   mPri->DesignatedPortID);
        /* messageTimes */
        assign(mTimes->remainingHops, msti_msg->remainingHops);
    }
    msg_Better_port = !betterorsamePriority(&(ptp->portPriority), mPri,
                                            0, 0, cist);
    if(roleIsDesignated)
    {
        /* a).1) */
        if(msg_Better_port
           || ((0 == memcmp(mPri->DesignatedBridgeID.s.mac_address,
                            ptp->portPriority.DesignatedBridgeID.s.mac_address,
                            ETH_ALEN)
               )
               && (0 == ((mPri->DesignatedPortID
                          ^ ptp->portPriority.DesignatedPortID
                         ) & __constant_cpu_to_be16(0x0FFF)
                        )
                  )
              )
          )
            return SuperiorDesignatedInfo;
        /* a).2) */
        /* We already know that msgPriority _IS_NOT_BETTER_than portPriority.
         * So, if msgPriority _IS_SAME_OR_BETTER_than portPriority then
         *   msgPriority _IS_SAME_as portPriority.
        */
        msg_SamePriorityAndTimers_port =
            samePriorityAndTimers(mPri, &(ptp->portPriority),
                                  mTimes, &(ptp->portTimes),
                                  cist);
        if((!msg_SamePriorityAndTimers_port)
           && betterorsamePriority(mPri, &(ptp->portPriority), 0, 0, cist)
          )
            return SuperiorDesignatedInfo;
        /* b) */
        if(msg_SamePriorityAndTimers_port && (ioReceived == ptp->infoIs))
            return RepeatedDesignatedInfo;
        /* c) */
        return InferiorDesignatedInfo;
    }
    /* d) */
    if(!msg_Better_port)
        return InferiorRootAlternateInfo;
    return OtherInfo;
}
References assign, b, betterorsamePriority(), BPDU_FLAGS_ROLE_GET, bpduTypeTCN, port_t::bridge, port_priority_vector_t::DesignatedBridgeID, port_priority_vector_t::DesignatedPortID, encodedRoleAlternateBackup, encodedRoleDesignated, encodedRoleMaster, encodedRoleRoot, port_priority_vector_t::ExtRootPathCost, FOREACH_PTP_IN_PORT, times_t::Forward_Delay, times_t::Hello_Time, InferiorDesignatedInfo, InferiorRootAlternateInfo, per_tree_port_t::infoIs, port_priority_vector_t::IntRootPathCost, ioReceived, times_t::Max_Age, bridge_t::MaxHops, times_t::Message_Age, per_tree_port_t::msgPriority, per_tree_port_t::msgTimes, per_tree_port_t::MSTID, NEAREST_WHOLE_SECOND, OtherInfo, per_tree_port_t::port, per_tree_port_t::portPriority, per_tree_port_t::portTimes, protoMSTP, protoRSTP, protoSTP, port_t::rcvdBpduData, per_tree_port_t::rcvdMstiConfig, per_tree_port_t::rcvdTc, port_t::rcvdTcn, times_t::remainingHops, RepeatedDesignatedInfo, port_priority_vector_t::RootID, port_priority_vector_t::RRootID, samePriorityAndTimers(), SET_PRIORITY_IN_IDENTIFIER, and SuperiorDesignatedInfo.
Referenced by PISM_to_RECEIVE().
RecalcConfigDigest()
static void RecalcConfigDigest (bridge_t * br) static
Definition at line 79 of file mstp.c.
{
    __be16 vid2mstid[MAX_VID + 2];
    unsigned char mstp_key[] = HMAC_KEY;
    int vid;
    vid2mstid[0] = vid2mstid[MAX_VID + 1] = 0;
    for(vid = 1; vid <= MAX_VID; ++vid)
        vid2mstid[vid] = br->fid2mstid[br->vid2fid[vid]];
    hmac_md5((void *)vid2mstid, sizeof(vid2mstid), mstp_key, sizeof(mstp_key),
             (caddr_t)br->MstConfigId.s.configuration_digest);
}
References bridge_t::fid2mstid, HMAC_KEY, hmac_md5(), MAX_VID, bridge_t::MstConfigId, and bridge_t::vid2fid.
Referenced by MSTP_IN_bridge_create(), MSTP_IN_set_all_fids2mstids(), MSTP_IN_set_all_vids2fids(), MSTP_IN_set_fid2mstid(), and MSTP_IN_set_vid2fid().
recordAgreement()
static void recordAgreement (per_tree_port_t * ptp) static
Definition at line 2005 of file mstp.c.
{
    bool cist_agreed, cist_proposing;
    per_tree_port_t *cist;
    port_t *prt = ptp->port;
    bpdu_t *b = &(prt->rcvdBpduData);
    if(0 == ptp->MSTID)
    { /* CIST */
        if(rstpVersion(prt->bridge) && prt->operPointToPointMAC
           && (b->flags & (1 << offsetAgreement))
          )
        {
            ptp->agreed = true;
            ptp->proposing = false;
        }
        else
            ptp->agreed = false;
        cist_agreed = ptp->agreed;
        cist_proposing = ptp->proposing;
        if(!prt->rcvdInternal)
            list_for_each_entry_continue(ptp, &prt->trees, port_list)
            {
                ptp->agreed = cist_agreed;
                ptp->proposing = cist_proposing;
            }
        return;
    }
    /* MSTI */
    cist = GET_CIST_PTP_FROM_PORT(prt);
    if(prt->operPointToPointMAC
       && cmp(b->cistRootID, ==, cist->portPriority.RootID)
       && cmp(b->cistExtRootPathCost, ==, cist->portPriority.ExtRootPathCost)
       && cmp(b->cistRRootID, ==, cist->portPriority.RRootID)
       && (ptp->rcvdMstiConfig->flags & (1 << offsetAgreement))
      )
    {
        ptp->agreed = true;
        ptp->proposing = false;
    }
    else
        ptp->agreed = false;
}
References per_tree_port_t::agreed, b, port_t::bridge, cmp, port_priority_vector_t::ExtRootPathCost, GET_CIST_PTP_FROM_PORT, list_for_each_entry_continue, per_tree_port_t::MSTID, offsetAgreement, port_t::operPointToPointMAC, per_tree_port_t::port, per_tree_port_t::portPriority, per_tree_port_t::proposing, port_t::rcvdBpduData, port_t::rcvdInternal, per_tree_port_t::rcvdMstiConfig, port_priority_vector_t::RootID, port_priority_vector_t::RRootID, rstpVersion, and port_t::trees.
Referenced by PISM_to_NOT_DESIGNATED(), PISM_to_REPEATED_DESIGNATED(), and PISM_to_SUPERIOR_DESIGNATED().
recordDispute()
static void recordDispute (per_tree_port_t * ptp) static
Definition at line 2050 of file mstp.c.
{
    port_t *prt;
    if(0 == ptp->MSTID)
    { /* CIST */
        prt = ptp->port;
        /* 802.1Q-2005(-2011) is somewhat unclear for the case
         *  (!prt->rcvdInternal): if we should record dispute for all MSTIs
         *  unconditionally or only when CIST Learning flag is set in BPDU.
         * I guess that in this case MSTIs should be in sync with CIST
         * so record dispute for the MSTIs only when the same is done for CIST.
         * Additional supporting argument to this guess is that in
         *  setTcFlags() we do the same.
         * But that is only a guess and I could be wrong here ;)
         */
        if(prt->rcvdBpduData.flags & (1 << offsetLearnig))
        {
            ptp->disputed = true;
            ptp->agreed = false;
            if(!prt->rcvdInternal)
                list_for_each_entry_continue(ptp, &prt->trees, port_list)
                {
                    ptp->disputed = true;
                    ptp->agreed = false;
                }
        }
        return;
    }
    /* MSTI */
    if(ptp->rcvdMstiConfig->flags & (1 << offsetLearnig))
    {
        ptp->disputed = true;
        ptp->agreed = false;
    }
}
References per_tree_port_t::agreed, per_tree_port_t::disputed, list_for_each_entry_continue, per_tree_port_t::MSTID, offsetLearnig, per_tree_port_t::port, port_t::rcvdBpduData, port_t::rcvdInternal, per_tree_port_t::rcvdMstiConfig, and port_t::trees.
Referenced by PISM_to_INFERIOR_DESIGNATED().
recordMastered()
static void recordMastered (per_tree_port_t * ptp) static
Definition at line 2088 of file mstp.c.
{
    port_t *prt = ptp->port;
    if(0 == ptp->MSTID)
    { /* CIST */
        if(!prt->rcvdInternal)
            list_for_each_entry_continue(ptp, &prt->trees, port_list)
                ptp->mastered = false;
        return;
    }
    /* MSTI */
    ptp->mastered = prt->operPointToPointMAC
                    && (ptp->rcvdMstiConfig->flags & (1 << offsetMaster));
}
References list_for_each_entry_continue, per_tree_port_t::mastered, per_tree_port_t::MSTID, offsetMaster, port_t::operPointToPointMAC, per_tree_port_t::port, port_t::rcvdInternal, per_tree_port_t::rcvdMstiConfig, and port_t::trees.
Referenced by PISM_to_RECEIVE().
recordPriority()
static void recordPriority (per_tree_port_t * ptp) static
Definition at line 2105 of file mstp.c.
{
    assign(ptp->portPriority, ptp->msgPriority);
}
References assign, per_tree_port_t::msgPriority, and per_tree_port_t::portPriority.
Referenced by PISM_to_SUPERIOR_DESIGNATED().
recordProposal()
static void recordProposal (per_tree_port_t * ptp) static
Definition at line 2111 of file mstp.c.
{
    bool cist_proposed;
    port_t *prt;
    /* 802.1Q-2005 says to check if received message conveys
     *  a Designated Port Role. But there is no need in this check,
     *  as it is always true. This function is called only in two states:
     *  PISM_SUPERIOR_DESIGNATED and PISM_REPEATED_DESIGNATED, which
     *  can be entered only if rcvInfo returns
     *  SuperiorDesignatedInfo or RepeatedDesignatedInfo.
     *  Which in turn can only happen if message conveys designated role
     *   (see rcvInfo).
     */
    if(0 == ptp->MSTID)
    { /* CIST */
        prt = ptp->port;
        if(prt->rcvdBpduData.flags & (1 << offsetProposal))
            ptp->proposed = true;
        cist_proposed = ptp->proposed;
        if(!prt->rcvdInternal)
            list_for_each_entry_continue(ptp, &prt->trees, port_list)
                ptp->proposed = cist_proposed;
        return;
    }
    /* MSTI */
    if(ptp->rcvdMstiConfig->flags & (1 << offsetProposal))
        ptp->proposed = true;
}
References list_for_each_entry_continue, per_tree_port_t::MSTID, offsetProposal, per_tree_port_t::port, per_tree_port_t::proposed, port_t::rcvdBpduData, port_t::rcvdInternal, per_tree_port_t::rcvdMstiConfig, and port_t::trees.
Referenced by PISM_to_REPEATED_DESIGNATED(), and PISM_to_SUPERIOR_DESIGNATED().
recordTimes()
static void recordTimes (per_tree_port_t * ptp) static
Definition at line 2142 of file mstp.c.
{
    /* 802.1Q-2005 and 802.1D-2004 both say that we have to copy
     *   Hello_Time from msgTimes to portTimes.
     * 802.1Q-2011, on the other hand, says that Hello_Time should be set
     *   to the default here.
     * As we have configurable Hello_Time, I choose the third option:
     *   preserve the configured Hello_Time, It is in accordance with the
     *   spirit of 802.1Q-2011, if we allow Hello_Time to be configurable.
     */
    __u8 prev_Hello_Time = 0;
    assign(prev_Hello_Time, ptp->portTimes.Hello_Time);
    assign(ptp->portTimes, ptp->msgTimes);
    assign(ptp->portTimes.Hello_Time, prev_Hello_Time);
}
References assign, times_t::Hello_Time, per_tree_port_t::msgTimes, and per_tree_port_t::portTimes.
Referenced by PISM_to_SUPERIOR_DESIGNATED().
reselectMSTIs()
static void reselectMSTIs (port_t * prt) static
Definition at line 2589 of file mstp.c.
{
    per_tree_port_t *ptp = GET_CIST_PTP_FROM_PORT(prt);
    /* For each non-CIST ptp */
    list_for_each_entry_continue(ptp, &prt->trees, port_list)
        ptp->reselect = true;
}
References GET_CIST_PTP_FROM_PORT, list_for_each_entry_continue, per_tree_port_t::reselect, and port_t::trees.
Referenced by updtRolesTree().
samePriorityAndTimers()
static bool samePriorityAndTimers (port_priority_vector_t * vec1, port_priority_vector_t * vec2, times_t * time1, times_t * time2, bool cist) static
Definition at line 1664 of file mstp.c.
{
    if(cist)
    {
        if(cmp(time1->Forward_Delay, !=, time2->Forward_Delay))
            return false;
        if(cmp(time1->Max_Age, !=, time2->Max_Age))
            return false;
        if(cmp(time1->Message_Age, !=, time2->Message_Age))
            return false;
        if(cmp(time1->Hello_Time, !=, time2->Hello_Time))
            return false;
        if(cmp(vec1->RootID, !=, vec2->RootID))
            return false;
        if(cmp(vec1->ExtRootPathCost, !=, vec2->ExtRootPathCost))
            return false;
    }
    if(cmp(time1->remainingHops, !=, time2->remainingHops))
        return false;
    if(cmp(vec1->RRootID, !=, vec2->RRootID))
        return false;
    if(cmp(vec1->IntRootPathCost, !=, vec2->IntRootPathCost))
        return false;
    if(cmp(vec1->DesignatedBridgeID, !=, vec2->DesignatedBridgeID))
        return false;
    if(cmp(vec1->DesignatedPortID, !=, vec2->DesignatedPortID))
        return false;
    return true;
}
References cmp, port_priority_vector_t::DesignatedBridgeID, port_priority_vector_t::DesignatedPortID, port_priority_vector_t::ExtRootPathCost, times_t::Forward_Delay, times_t::Hello_Time, port_priority_vector_t::IntRootPathCost, times_t::Max_Age, times_t::Message_Age, times_t::remainingHops, port_priority_vector_t::RootID, and port_priority_vector_t::RRootID.
Referenced by rcvInfo(), and updtRolesTree().
set_fdbFlush()
static void set_fdbFlush (per_tree_port_t * ptp) static
Definition at line 2159 of file mstp.c.
{
    port_t *prt = ptp->port;
    if(prt->operEdge || prt->deleted)
    {
        ptp->fdbFlush = false;
        return;
    }
    bridge_t *br = prt->bridge;
    if(rstpVersion(br))
    {
        ptp->fdbFlush = true;
        ptp->calledFromFlushRoutine = true;
        MSTP_OUT_flush_all_fids(ptp);
        ptp->calledFromFlushRoutine = false;
    }
    else
    {
        per_tree_port_t *cist = GET_CIST_PTP_FROM_PORT(prt);
        unsigned int FwdDelay = cist->designatedTimes.Forward_Delay;
        /* Initiate rapid ageing */
        MSTP_OUT_set_ageing_time(prt, FwdDelay);
        assign(prt->rapidAgeingWhile, FwdDelay);
        ptp->fdbFlush = false;
    }
}
References assign, port_t::bridge, per_tree_port_t::calledFromFlushRoutine, port_t::deleted, per_tree_port_t::designatedTimes, per_tree_port_t::fdbFlush, times_t::Forward_Delay, GET_CIST_PTP_FROM_PORT, MSTP_OUT_flush_all_fids(), MSTP_OUT_set_ageing_time(), port_t::operEdge, per_tree_port_t::port, port_t::rapidAgeingWhile, and rstpVersion.
Referenced by TCSM_to_INACTIVE(), and TCSM_to_PROPAGATING().
set_TopologyChange()
static void set_TopologyChange (tree_t * tree, bool hint_SetToYes, port_t * port) static
Definition at line 1629 of file mstp.c.
{
    per_tree_port_t *ptp;
    bool prev_tc_not_set = !tree->topology_change;
    if(hint_SetToYes)
    {
        tree->topology_change = true;
        tree->time_since_topology_change = 0;
        if(prev_tc_not_set)
            ++(tree->topology_change_count);
        strncpy(tree->topology_change_port, tree->last_topology_change_port,
                IFNAMSIZ);
        strncpy(tree->last_topology_change_port, port->sysdeps.name, IFNAMSIZ);
        return;
    }
    /* Some tcWhile has just became zero. Check if we need reset
     * topology_change flag */
    if(prev_tc_not_set)
        return;
    tree->topology_change = false;
    FOREACH_PTP_IN_TREE(ptp, tree)
    {
        if(0 != ptp->tcWhile)
        {
            tree->topology_change = true;
            tree->time_since_topology_change = 0;
            return;
        }
    }
}
References FOREACH_PTP_IN_TREE, tree_t::last_topology_change_port, port, per_tree_port_t::tcWhile, tree_t::time_since_topology_change, tree_t::topology_change, tree_t::topology_change_count, and tree_t::topology_change_port.
Referenced by newTcWhile(), PTSM_tick(), TCSM_to_ACKNOWLEDGED(), and TCSM_to_INACTIVE().
setRcvdMsgs()
static void setRcvdMsgs (port_t * prt) static
Definition at line 2190 of file mstp.c.
{
    msti_configuration_message_t *msti_msg;
    int i;
    __be16 msg_MSTID;
    bool found;
    per_tree_port_t *ptp = GET_CIST_PTP_FROM_PORT(prt);
    ptp->rcvdMsg = true;
    /* 802.1Q-2005 says:
     *   "Make the received CST or CIST message available to the CIST Port
     *    Information state machines"
     * No need to do something special here, we already have rcvdBpduData.
     */
    if(prt->rcvdInternal)
    {
        list_for_each_entry_continue(ptp, &prt->trees, port_list)
        {
            found = false;
            /* Find if message for this MSTI is conveyed in the BPDU */
            for(i = 0, msti_msg = prt->rcvdBpduData.mstConfiguration;
                i < prt->rcvdBpduNumOfMstis;
                ++i, ++msti_msg)
            {
                msg_MSTID = msti_msg->mstiRRootID.s.priority
                            & __constant_cpu_to_be16(0x0FFF);
                if(msg_MSTID == ptp->MSTID)
                {
                    found = true;
                    break;
                }
            }
            if(found)
            {
                ptp->rcvdMsg = true;
                /* 802.1Q-2005 says:
                 *   "Make available each MSTI message and the common parts of
                 *    the CIST message priority (the CIST Root Identifier,
                 *    External Root Path Cost and Regional Root Identifier)
                 *    to the Port Information state machine for that MSTI"
                 * We set pointer to the MSTI configuration message for
                 * fast access, while do not anything special for common
                 * parts of the message, as the whole message is available
                 * in rcvdBpduData.
                 */
                ptp->rcvdMstiConfig = msti_msg;
            }
        }
    }
}
References GET_CIST_PTP_FROM_PORT, list_for_each_entry_continue, per_tree_port_t::MSTID, port_t::rcvdBpduData, port_t::rcvdInternal, per_tree_port_t::rcvdMsg, per_tree_port_t::rcvdMstiConfig, and port_t::trees.
Referenced by PRSM_to_RECEIVE().
setReRootTree()
static void setReRootTree (tree_t * tree) static
Definition at line 2243 of file mstp.c.
{
    per_tree_port_t *ptp;
    FOREACH_PTP_IN_TREE(ptp, tree)
        ptp->reRoot = true;
}
References FOREACH_PTP_IN_TREE, and per_tree_port_t::reRoot.
Referenced by PRTSM_to_REROOT().
setSelectedTree()
static void setSelectedTree (tree_t * tree) static
Definition at line 2252 of file mstp.c.
{
    per_tree_port_t *ptp;
    /*
     * 802.1Q-2005 says that I should check "reselect" var
     * and take no action if it is "true" for any of the ports.
     * But there is no need in this check as setSelectedTree is called
     * only from PRSSM_to_ROLE_SELECTION, which is atomic, and it is called
     * in this sequence (13.33):
     *   clearReselectTree(tree);
     *   updtRolesTree(tree);
     *   setSelectedTree(tree);
     * And we know that clearReselectTree resets "reselect" for all ports
     * and updtRolesTree() does not change value of "reselect".
     */
    FOREACH_PTP_IN_TREE(ptp, tree)
        ptp->selected = true;
}
References FOREACH_PTP_IN_TREE, and per_tree_port_t::selected.
Referenced by PRSSM_to_ROLE_SELECTION().
setSyncTree()
static void setSyncTree (tree_t * tree) static
Definition at line 2273 of file mstp.c.
{
    per_tree_port_t *ptp;
    FOREACH_PTP_IN_TREE(ptp, tree)
        ptp->sync = true;
}
References FOREACH_PTP_IN_TREE, and per_tree_port_t::sync.
Referenced by PRTSM_to_ALTERNATE_PROPOSED(), PRTSM_to_MASTER_PROPOSED(), and PRTSM_to_ROOT_PROPOSED().
setTcFlags()
static void setTcFlags (per_tree_port_t * ptp) static
Definition at line 2282 of file mstp.c.
{
    __u8 cistFlags;
    port_t *prt;
    if(0 == ptp->MSTID)
    { /* CIST */
        prt = ptp->port;
        cistFlags = prt->rcvdBpduData.flags;
        if(cistFlags & (1 << offsetTcAck))
            prt->rcvdTcAck = true;
        if(cistFlags & (1 << offsetTc))
        {
            ptp->rcvdTc = true;
            if(!prt->rcvdInternal)
                list_for_each_entry_continue(ptp, &prt->trees, port_list)
                    ptp->proposed = true;
        }
        return;
    }
    /* MSTI */
    if(ptp->rcvdMstiConfig->flags & (1 << offsetTc))
        ptp->rcvdTc = true;
}
References list_for_each_entry_continue, per_tree_port_t::MSTID, offsetTc, offsetTcAck, per_tree_port_t::port, per_tree_port_t::proposed, port_t::rcvdBpduData, port_t::rcvdInternal, per_tree_port_t::rcvdMstiConfig, per_tree_port_t::rcvdTc, port_t::rcvdTcAck, and port_t::trees.
Referenced by PISM_to_NOT_DESIGNATED(), PISM_to_REPEATED_DESIGNATED(), and PISM_to_SUPERIOR_DESIGNATED().
setTcPropTree()
static void setTcPropTree (per_tree_port_t * ptp) static
Definition at line 2308 of file mstp.c.
{
    per_tree_port_t *ptp_1;
    if(ptp->port->restrictedTcn)
        return;
    FOREACH_PTP_IN_TREE(ptp_1, ptp->tree)
    {
        if(ptp != ptp_1)
            ptp_1->tcProp = true;
    }
}
References FOREACH_PTP_IN_TREE, per_tree_port_t::port, port_t::restrictedTcn, per_tree_port_t::tcProp, and per_tree_port_t::tree.
Referenced by TCSM_to_DETECTED(), and TCSM_to_NOTIFIED_TC().
syncMaster()
static void syncMaster (bridge_t * br) static
Definition at line 2323 of file mstp.c.
{
    per_tree_port_t *ptp;
    tree_t *tree = GET_CIST_TREE(br);
    /* For each MSTI */
    list_for_each_entry_continue(tree, &br->trees, bridge_list)
    {
        FOREACH_PTP_IN_TREE(ptp, tree)
        {
            /* for each Port that has infoInternal set */
            if(ptp->port->infoInternal)
            {
                ptp->agree = false;
                ptp->agreed = false;
                ptp->synced = false;
                ptp->sync = true;
            }
        }
    }
}
References per_tree_port_t::agree, per_tree_port_t::agreed, FOREACH_PTP_IN_TREE, GET_CIST_TREE, port_t::infoInternal, list_for_each_entry_continue, per_tree_port_t::port, per_tree_port_t::sync, per_tree_port_t::synced, and bridge_t::trees.
Referenced by updtRolesTree().
TCSM_run()
static bool TCSM_run (per_tree_port_t * ptp, bool dry_run) static
Definition at line 4792 of file mstp.c.
{
    bool active_port;
    port_t *prt = ptp->port;
    switch(ptp->TCSM_state)
    {
        case TCSM_INACTIVE:
            if(ptp->learn && !ptp->fdbFlush)
            {
                if(dry_run) /* state change */
                    return true;
                TCSM_to_LEARNING(ptp, false /* actual run */);
            }
            return false;
        case TCSM_LEARNING:
            active_port = (roleRoot == ptp->role)
                          || (roleDesignated == ptp->role)
                          || (roleMaster == ptp->role);
            if(active_port && ptp->forward && !prt->operEdge)
            {
                if(dry_run) /* state change */
                    return true;
                TCSM_to_DETECTED(ptp);
                return false;
            }
            if(ptp->rcvdTc || prt->rcvdTcn || prt->rcvdTcAck || ptp->tcProp)
            {
                return TCSM_to_LEARNING(ptp, dry_run);
            }
            else if(!active_port && !(ptp->learn || ptp->learning))
            {
                if(dry_run) /* state change */
                    return true;
                TCSM_to_INACTIVE(ptp, false);
            }
            return false;
        case TCSM_NOTIFIED_TCN:
            if(dry_run) /* state change */
                return true;
            TCSM_to_NOTIFIED_TC(ptp);
            return false;
        case TCSM_DETECTED:
            /* return; */
        case TCSM_NOTIFIED_TC:
            /* return; */
        case TCSM_PROPAGATING:
            /* return; */
        case TCSM_ACKNOWLEDGED:
            if(dry_run) /* state change */
                return true;
            TCSM_to_ACTIVE(ptp);
            return false;
        case TCSM_ACTIVE:
            active_port = (roleRoot == ptp->role)
                          || (roleDesignated == ptp->role)
                          || (roleMaster == ptp->role);
            if(!active_port || prt->operEdge)
            {
                if(dry_run) /* state change */
                    return true;
                TCSM_to_LEARNING(ptp, false /* actual run */);
                return false;
            }
            if(prt->rcvdTcn)
            {
                if(dry_run) /* state change */
                    return true;
                TCSM_to_NOTIFIED_TCN(ptp);
                return false;
            }
            if(ptp->rcvdTc)
            {
                if(dry_run) /* state change */
                    return true;
                TCSM_to_NOTIFIED_TC(ptp);
                return false;
            }
            if(ptp->tcProp/* && !prt->operEdge */)
            {
                if(dry_run) /* state change */
                    return true;
                TCSM_to_PROPAGATING(ptp);
                return false;
            }
            if(prt->rcvdTcAck)
            {
                if(dry_run) /* state change */
                    return true;
                TCSM_to_ACKNOWLEDGED(ptp);
                return false;
            }
            return false;
    }
    return false;
}
References dry_run, per_tree_port_t::fdbFlush, per_tree_port_t::forward, per_tree_port_t::learn, per_tree_port_t::learning, port_t::operEdge, per_tree_port_t::port, per_tree_port_t::rcvdTc, port_t::rcvdTcAck, port_t::rcvdTcn, per_tree_port_t::role, roleDesignated, roleMaster, roleRoot, per_tree_port_t::tcProp, TCSM_ACKNOWLEDGED, TCSM_ACTIVE, TCSM_DETECTED, TCSM_INACTIVE, TCSM_LEARNING, TCSM_NOTIFIED_TC, TCSM_NOTIFIED_TCN, TCSM_PROPAGATING, per_tree_port_t::TCSM_state, TCSM_to_ACKNOWLEDGED(), TCSM_to_ACTIVE(), TCSM_to_DETECTED(), TCSM_to_INACTIVE(), TCSM_to_LEARNING(), TCSM_to_NOTIFIED_TC(), TCSM_to_NOTIFIED_TCN(), and TCSM_to_PROPAGATING().
Referenced by __br_state_machines_run(), MSTP_IN_all_fids_flushed(), TCSM_to_ACKNOWLEDGED(), TCSM_to_ACTIVE(), TCSM_to_DETECTED(), TCSM_to_INACTIVE(), TCSM_to_LEARNING(), TCSM_to_NOTIFIED_TC(), TCSM_to_NOTIFIED_TCN(), and TCSM_to_PROPAGATING().
TCSM_to_ACKNOWLEDGED()
static void TCSM_to_ACKNOWLEDGED (per_tree_port_t * ptp) static
Definition at line 4774 of file mstp.c.
{
    ptp->TCSM_state = TCSM_ACKNOWLEDGED;
    assign(ptp->tcWhile, 0u);
    set_TopologyChange(ptp->tree, false, ptp->port);
    ptp->port->rcvdTcAck = false;
    TCSM_run(ptp, false /* actual run */);
}
References assign, per_tree_port_t::port, port_t::rcvdTcAck, set_TopologyChange(), TCSM_ACKNOWLEDGED, TCSM_run(), per_tree_port_t::TCSM_state, per_tree_port_t::tcWhile, and per_tree_port_t::tree.
Referenced by TCSM_run().
TCSM_to_ACTIVE()
static void TCSM_to_ACTIVE (per_tree_port_t * ptp) static
Definition at line 4785 of file mstp.c.
{
    ptp->TCSM_state = TCSM_ACTIVE;
    TCSM_run(ptp, false /* actual run */);
}
References TCSM_ACTIVE, TCSM_run(), and per_tree_port_t::TCSM_state.
Referenced by TCSM_run().
TCSM_to_DETECTED()
static void TCSM_to_DETECTED (per_tree_port_t * ptp) static
Definition at line 4721 of file mstp.c.
{
    ptp->TCSM_state = TCSM_DETECTED;
    newTcWhile(ptp);
    setTcPropTree(ptp);
    /* newInfoXst = TRUE; */
    port_t *prt = ptp->port;
    if(0 == ptp->MSTID)
        prt->newInfo = true;
    else
        prt->newInfoMsti = true;
    TCSM_run(ptp, false /* actual run */);
}
References per_tree_port_t::MSTID, port_t::newInfo, port_t::newInfoMsti, newTcWhile(), per_tree_port_t::port, setTcPropTree(), TCSM_DETECTED, TCSM_run(), and per_tree_port_t::TCSM_state.
Referenced by TCSM_run().
TCSM_to_INACTIVE()
static void TCSM_to_INACTIVE (per_tree_port_t * ptp, bool begin) static
Definition at line 4677 of file mstp.c.
{
    ptp->TCSM_state = TCSM_INACTIVE;
    set_fdbFlush(ptp);
    assign(ptp->tcWhile, 0u);
    set_TopologyChange(ptp->tree, false, ptp->port);
    if(0 == ptp->MSTID) /* CIST */
        ptp->port->tcAck = false;
    if(!begin)
        TCSM_run(ptp, false /* actual run */);
}
References assign, per_tree_port_t::MSTID, per_tree_port_t::port, set_fdbFlush(), set_TopologyChange(), port_t::tcAck, TCSM_INACTIVE, TCSM_run(), per_tree_port_t::TCSM_state, per_tree_port_t::tcWhile, and per_tree_port_t::tree.
Referenced by TCSM_run().
TCSM_to_LEARNING()
static bool TCSM_to_LEARNING (per_tree_port_t * ptp, bool dry_run) static
Definition at line 4691 of file mstp.c.
{
    if(dry_run)
    {
        if((ptp->TCSM_state != TCSM_LEARNING) || ptp->rcvdTc || ptp->tcProp)
            return true;
        if(0 == ptp->MSTID) /* CIST */
        {
            port_t *prt = ptp->port;
            if(prt->rcvdTcn || prt->rcvdTcAck)
                return true;
        }
        return false;
    }
    ptp->TCSM_state = TCSM_LEARNING;
    if(0 == ptp->MSTID) /* CIST */
    {
        port_t *prt = ptp->port;
        prt->rcvdTcn = false;
        prt->rcvdTcAck = false;
    }
    ptp->rcvdTc = false;
    ptp->tcProp = false;
    TCSM_run(ptp, false /* actual run */);
    return false;
}
References dry_run, per_tree_port_t::MSTID, per_tree_port_t::port, per_tree_port_t::rcvdTc, port_t::rcvdTcAck, port_t::rcvdTcn, per_tree_port_t::tcProp, TCSM_LEARNING, TCSM_run(), and per_tree_port_t::TCSM_state.
Referenced by TCSM_run().
TCSM_to_NOTIFIED_TC()
static void TCSM_to_NOTIFIED_TC (per_tree_port_t * ptp) static
Definition at line 4746 of file mstp.c.
{
    ptp->TCSM_state = TCSM_NOTIFIED_TC;
    ptp->rcvdTc = false;
    if(0 == ptp->MSTID) /* CIST */
    {
        port_t *prt = ptp->port;
        prt->rcvdTcn = false;
        if(roleDesignated == ptp->role)
            prt->tcAck = true;
    }
    setTcPropTree(ptp);
    TCSM_run(ptp, false /* actual run */);
}
References per_tree_port_t::MSTID, per_tree_port_t::port, per_tree_port_t::rcvdTc, port_t::rcvdTcn, per_tree_port_t::role, roleDesignated, setTcPropTree(), port_t::tcAck, TCSM_NOTIFIED_TC, TCSM_run(), and per_tree_port_t::TCSM_state.
Referenced by TCSM_run().
TCSM_to_NOTIFIED_TCN()
static void TCSM_to_NOTIFIED_TCN (per_tree_port_t * ptp) static
Definition at line 4737 of file mstp.c.
{
    ptp->TCSM_state = TCSM_NOTIFIED_TCN;
    newTcWhile(ptp);
    TCSM_run(ptp, false /* actual run */);
}
References newTcWhile(), TCSM_NOTIFIED_TCN, TCSM_run(), and per_tree_port_t::TCSM_state.
Referenced by TCSM_run().
TCSM_to_PROPAGATING()
static void TCSM_to_PROPAGATING (per_tree_port_t * ptp) static
Definition at line 4763 of file mstp.c.
{
    ptp->TCSM_state = TCSM_PROPAGATING;
    newTcWhile(ptp);
    set_fdbFlush(ptp);
    ptp->tcProp = false;
    TCSM_run(ptp, false /* actual run */);
}
References newTcWhile(), set_fdbFlush(), per_tree_port_t::tcProp, TCSM_PROPAGATING, TCSM_run(), and per_tree_port_t::TCSM_state.
Referenced by TCSM_run().
tree_default_internal_vars()
static void tree_default_internal_vars (tree_t * tree) static
Definition at line 110 of file mstp.c.
{
    /* 12.8.1.1.3.(b,c,d) */
    tree->time_since_topology_change = 0;
    tree->topology_change_count = 0;
    tree->topology_change = false; /* since all tcWhile are initialized to 0 */
    strncpy(tree->topology_change_port, "None", IFNAMSIZ);
    strncpy(tree->last_topology_change_port, "None", IFNAMSIZ);
    /* The following are initialized in BEGIN state:
     *  - rootPortId, rootPriority, rootTimes: in Port Role Selection SM
     */
}
References tree_t::last_topology_change_port, tree_t::time_since_topology_change, tree_t::topology_change, tree_t::topology_change_count, and tree_t::topology_change_port.
Referenced by create_tree(), and MSTP_IN_set_bridge_enable().
tree_state_machines_begin()
static void tree_state_machines_begin (tree_t * tree) static
Definition at line 4895 of file mstp.c.
{
    bridge_t *br = tree->bridge;
    per_tree_port_t *ptp;
    if(!br->bridgeEnabled)
        return;
    /* 13.32  Port Information state machine */
    FOREACH_PTP_IN_TREE(ptp, tree)
    {
        ptp->start_time = br->uptime; /* 12.8.2.2.3 b) */
        PISM_begin(ptp);
    }
    /* 13.33  Port Role Selection state machine */
    PRSSM_begin(tree);
    /* 13.34  Port Role Transitions state machine */
    FOREACH_PTP_IN_TREE(ptp, tree)
        PRTSM_begin(ptp);
    /* 13.35  Port State Transition state machine */
    FOREACH_PTP_IN_TREE(ptp, tree)
        PSTSM_begin(ptp);
    /* 13.36  Topology Change state machine */
    FOREACH_PTP_IN_TREE(ptp, tree)
        TCSM_begin(ptp);
    br_state_machines_run(br);
}
References br_state_machines_run(), tree_t::bridge, bridge_t::bridgeEnabled, FOREACH_PTP_IN_TREE, PISM_begin, PRSSM_begin, PRTSM_begin, PSTSM_begin, per_tree_port_t::start_time, TCSM_begin, and bridge_t::uptime.
Referenced by MSTP_IN_create_msti().
txConfig()
static void txConfig (port_t * prt) static
Definition at line 2346 of file mstp.c.
{
    bpdu_t b;
    per_tree_port_t *cist = GET_CIST_PTP_FROM_PORT(prt);
    if(prt->deleted || (roleDisabled == cist->role) || prt->dontTxmtBpdu)
        return;
    b.protocolIdentifier = 0;
    b.protocolVersion = protoSTP;
    b.bpduType = bpduTypeConfig;
    /* Standard says "tcWhile ... for the Port". Which one tcWhile?
     * I guess that this means tcWhile for the CIST.
     * But that is only a guess and I could be wrong here ;)
     */
    b.flags = (0 != cist->tcWhile) ? (1 << offsetTc) : 0;
    if(prt->tcAck)
        b.flags |= (1 << offsetTcAck);
    assign(b.cistRootID, cist->designatedPriority.RootID);
    assign(b.cistExtRootPathCost, cist->designatedPriority.ExtRootPathCost);
    assign(b.cistRRootID, cist->designatedPriority.DesignatedBridgeID);
    assign(b.cistPortID, cist->designatedPriority.DesignatedPortID);
    b.MessageAge[0] = cist->designatedTimes.Message_Age;
    b.MessageAge[1] = 0;
    b.MaxAge[0] = cist->designatedTimes.Max_Age;
    b.MaxAge[1] = 0;
    b.HelloTime[0] = cist->portTimes.Hello_Time; /* ! use portTimes ! */
    b.HelloTime[1] = 0;
    b.ForwardDelay[0] = cist->designatedTimes.Forward_Delay;
    b.ForwardDelay[1] = 0;
    MSTP_OUT_tx_bpdu(prt, &b, CONFIG_BPDU_SIZE);
}
References assign, b, bpduTypeConfig, CONFIG_BPDU_SIZE, port_t::deleted, port_priority_vector_t::DesignatedBridgeID, port_priority_vector_t::DesignatedPortID, per_tree_port_t::designatedPriority, per_tree_port_t::designatedTimes, port_t::dontTxmtBpdu, port_priority_vector_t::ExtRootPathCost, times_t::Forward_Delay, GET_CIST_PTP_FROM_PORT, times_t::Hello_Time, times_t::Max_Age, times_t::Message_Age, MSTP_OUT_tx_bpdu(), offsetTc, offsetTcAck, per_tree_port_t::portTimes, protoSTP, per_tree_port_t::role, roleDisabled, port_priority_vector_t::RootID, port_t::tcAck, and per_tree_port_t::tcWhile.
Referenced by PTSM_to_TRANSMIT_CONFIG().
txMstp()
static void txMstp (port_t * prt) static
Definition at line 2403 of file mstp.c.
{
    bpdu_t b;
    bridge_t *br = prt->bridge;
    per_tree_port_t *cist = GET_CIST_PTP_FROM_PORT(prt);
    int msti_msgs_total_size;
    per_tree_port_t *ptp;
    msti_configuration_message_t *msti_msg;
    if(prt->deleted || (roleDisabled == cist->role) || prt->dontTxmtBpdu)
        return;
    b.protocolIdentifier = 0;
    b.bpduType = bpduTypeRST;
    /* Standard says "{tcWhile, agree, proposing} ... for the Port".
     * Which one {tcWhile, agree, proposing}?
     * I guess that this means {tcWhile, agree, proposing} for the CIST.
     * But that is only a guess and I could be wrong here ;)
     */
    b.flags = BPDU_FLAGS_ROLE_SET(message_role_from_port_role(cist));
    if(0 != cist->tcWhile)
        b.flags |= (1 << offsetTc);
    if(cist->proposing)
        b.flags |= (1 << offsetProposal);
    if(cist->learning)
        b.flags |= (1 << offsetLearnig);
    if(cist->forwarding)
        b.flags |= (1 << offsetForwarding);
    if(cist->agree)
        b.flags |= (1 << offsetAgreement);
    assign(b.cistRootID, cist->designatedPriority.RootID);
    assign(b.cistExtRootPathCost, cist->designatedPriority.ExtRootPathCost);
    assign(b.cistRRootID, cist->designatedPriority.RRootID);
    assign(b.cistPortID, cist->designatedPriority.DesignatedPortID);
    b.MessageAge[0] = cist->designatedTimes.Message_Age;
    b.MessageAge[1] = 0;
    b.MaxAge[0] = cist->designatedTimes.Max_Age;
    b.MaxAge[1] = 0;
    b.HelloTime[0] = cist->portTimes.Hello_Time; /* ! use portTimes ! */
    b.HelloTime[1] = 0;
    b.ForwardDelay[0] = cist->designatedTimes.Forward_Delay;
    b.ForwardDelay[1] = 0;
    b.version1_len = 0;
    if(br->ForceProtocolVersion < protoMSTP)
    {
        b.protocolVersion = protoRSTP;
        MSTP_OUT_tx_bpdu(prt, &b, RST_BPDU_SIZE);
        return;
    }
    b.protocolVersion = protoMSTP;
    /* MST specific fields */
    assign(b.mstConfigurationIdentifier, br->MstConfigId);
    assign(b.cistIntRootPathCost, cist->designatedPriority.IntRootPathCost);
    assign(b.cistBridgeID, cist->designatedPriority.DesignatedBridgeID);
    assign(b.cistRemainingHops, cist->designatedTimes.remainingHops);
    msti_msgs_total_size = 0;
    ptp = cist;
    msti_msg = b.mstConfiguration;
    /* 13.26.20.f) requires that msti configs should be inserted in
     * MSTID order. This is met by inserting trees in port's list of trees
     * in sorted (by MSTID) order (see MSTP_IN_create_msti) */
    list_for_each_entry_continue(ptp, &prt->trees, port_list)
    {
        msti_msg->flags =
            BPDU_FLAGS_ROLE_SET(message_role_from_port_role(ptp));
        if(0 != ptp->tcWhile)
            msti_msg->flags |= (1 << offsetTc);
        if(ptp->proposing)
            msti_msg->flags |= (1 << offsetProposal);
        if(ptp->learning)
            msti_msg->flags |= (1 << offsetLearnig);
        if(ptp->forwarding)
            msti_msg->flags |= (1 << offsetForwarding);
        if(ptp->agree)
            msti_msg->flags |= (1 << offsetAgreement);
        if(ptp->master)
            msti_msg->flags |= (1 << offsetMaster);
        assign(msti_msg->mstiRRootID, ptp->designatedPriority.RRootID);
        assign(msti_msg->mstiIntRootPathCost,
               ptp->designatedPriority.IntRootPathCost);
        msti_msg->bridgeIdentifierPriority =
            GET_PRIORITY_FROM_IDENTIFIER(ptp->designatedPriority.DesignatedBridgeID);
        msti_msg->portIdentifierPriority =
            GET_PRIORITY_FROM_IDENTIFIER(ptp->designatedPriority.DesignatedPortID);
        assign(msti_msg->remainingHops, ptp->designatedTimes.remainingHops);
        msti_msgs_total_size += sizeof(msti_configuration_message_t);
        ++msti_msg;
    }
    assign(b.version3_len, __cpu_to_be16(MST_BPDU_VER3LEN_WO_MSTI_MSGS
                                         + msti_msgs_total_size));
    MSTP_OUT_tx_bpdu(prt, &b, MST_BPDU_SIZE_WO_MSTI_MSGS
                              + msti_msgs_total_size);
}
References per_tree_port_t::agree, assign, b, BPDU_FLAGS_ROLE_SET, bpduTypeRST, port_t::bridge, port_t::deleted, port_priority_vector_t::DesignatedBridgeID, port_priority_vector_t::DesignatedPortID, per_tree_port_t::designatedPriority, per_tree_port_t::designatedTimes, port_t::dontTxmtBpdu, port_priority_vector_t::ExtRootPathCost, bridge_t::ForceProtocolVersion, times_t::Forward_Delay, per_tree_port_t::forwarding, GET_CIST_PTP_FROM_PORT, GET_PRIORITY_FROM_IDENTIFIER, times_t::Hello_Time, port_priority_vector_t::IntRootPathCost, per_tree_port_t::learning, list_for_each_entry_continue, per_tree_port_t::master, times_t::Max_Age, times_t::Message_Age, message_role_from_port_role(), MST_BPDU_SIZE_WO_MSTI_MSGS, MST_BPDU_VER3LEN_WO_MSTI_MSGS, bridge_t::MstConfigId, MSTP_OUT_tx_bpdu(), offsetAgreement, offsetForwarding, offsetLearnig, offsetMaster, offsetProposal, offsetTc, per_tree_port_t::portTimes, per_tree_port_t::proposing, protoMSTP, protoRSTP, times_t::remainingHops, per_tree_port_t::role, roleDisabled, port_priority_vector_t::RootID, port_priority_vector_t::RRootID, RST_BPDU_SIZE, per_tree_port_t::tcWhile, and port_t::trees.
Referenced by PTSM_to_TRANSMIT_RSTP().
txTcn()
static void txTcn (port_t * prt) static
Definition at line 2505 of file mstp.c.
{
    bpdu_t b;
    per_tree_port_t *cist = GET_CIST_PTP_FROM_PORT(prt);
    if(prt->deleted || (roleDisabled == cist->role) || prt->dontTxmtBpdu)
        return;
    b.protocolIdentifier = 0;
    b.protocolVersion = protoSTP;
    b.bpduType = bpduTypeTCN;
    MSTP_OUT_tx_bpdu(prt, &b, TCN_BPDU_SIZE);
}
References b, bpduTypeTCN, port_t::deleted, port_t::dontTxmtBpdu, GET_CIST_PTP_FROM_PORT, MSTP_OUT_tx_bpdu(), protoSTP, per_tree_port_t::role, roleDisabled, and TCN_BPDU_SIZE.
Referenced by PTSM_to_TRANSMIT_TCN().
updtBPDUVersion()
static void updtBPDUVersion (port_t * prt) static
Definition at line 2521 of file mstp.c.
{
    if(protoRSTP <= prt->rcvdBpduData.protocolVersion)
        prt->rcvdRSTP = true;
    else
        prt->rcvdSTP = true;
}
References protoRSTP, port_t::rcvdRSTP, and port_t::rcvdSTP.
Referenced by PRSM_to_RECEIVE().
updtbrAssuRcvdInfoWhile()
static void updtbrAssuRcvdInfoWhile (port_t * prt) static
Definition at line 2570 of file mstp.c.
{
    per_tree_port_t *cist = GET_CIST_PTP_FROM_PORT(prt);
    prt->brAssuRcvdInfoWhile = 3 * cist->portTimes.Hello_Time;
}
References port_t::brAssuRcvdInfoWhile, GET_CIST_PTP_FROM_PORT, times_t::Hello_Time, and per_tree_port_t::portTimes.
Referenced by MSTP_IN_rx_bpdu(), and MSTP_IN_set_port_enable().
updtRcvdInfoWhile()
static void updtRcvdInfoWhile (per_tree_port_t * ptp) static
Definition at line 2530 of file mstp.c.
{
    port_t *prt = ptp->port;
    per_tree_port_t *cist = GET_CIST_PTP_FROM_PORT(prt);
    unsigned int Message_Age = cist->portTimes.Message_Age;
    unsigned int Max_Age = cist->portTimes.Max_Age;
    unsigned int Hello_Time = cist->portTimes.Hello_Time;
    /* NOTE: 802.1Q-2005(-2011) says that we should use
     *  "remainingHops ... from the CIST's portTimes parameter"
     *  As for me this is clear oversight in the standard,
     *  the remainingHops should be taken form the port's own portTimes,
     *  not from CIST's. After all, if we don't use port's own
     *  remainingHops here, they aren't used anywhere at all.
     *  Besides, there is a scenario which breaks if we use CIST's
     *  remainingHops here:
     *   1) Connect two switches (SW1,SW2) with two ports, thus forming a loop
     *   2) Configure them to be in the same region, with two trees:
     *      0 (CIST) and 1.
     *   3) at SW1# mstpctl settreeprio br0 1 4
     *      SW1 becomes regional root in tree 1
     *   4) at SW2# mstpctl settreeprio br0 1 14
     *   5) at SW1# mstpctl settreeprio br0 1 9
     *
     *  And now we have the classic "count-to-infinity" problem when the old
     *  info ("Regional Root is SW1 with priority 4") circulates in the loop,
     *  because it is better than current info ("Regional Root is SW1 with
     *  priority 9"). The only way to get rid of that old info is
     *  to age it out by the means of remainingHops counter.
     *  In this situation we certainly must use counter from tree 1,
     *  not CIST's.
     */
    if((!prt->rcvdInternal && ((Message_Age + 1) <= Max_Age))
       || (prt->rcvdInternal && (ptp->portTimes.remainingHops > 1))
      )
        ptp->rcvdInfoWhile = 3 * Hello_Time;
    else
        ptp->rcvdInfoWhile = 0;
}
References GET_CIST_PTP_FROM_PORT, times_t::Hello_Time, times_t::Max_Age, times_t::Message_Age, per_tree_port_t::port, per_tree_port_t::portTimes, per_tree_port_t::rcvdInfoWhile, port_t::rcvdInternal, and times_t::remainingHops.
Referenced by PISM_to_REPEATED_DESIGNATED(), and PISM_to_SUPERIOR_DESIGNATED().
updtRolesDisabledTree()
static void updtRolesDisabledTree (tree_t * tree) static
Definition at line 2578 of file mstp.c.
{
    per_tree_port_t *ptp;
    FOREACH_PTP_IN_TREE(ptp, tree)
        ptp->selectedRole = roleDisabled;
}
References FOREACH_PTP_IN_TREE, roleDisabled, and per_tree_port_t::selectedRole.
Referenced by PRSSM_to_INIT_TREE().
updtRolesTree()
static void updtRolesTree (tree_t * tree) static
Definition at line 2599 of file mstp.c.
{
    per_tree_port_t *ptp, *root_ptp = NULL;
    port_priority_vector_t root_path_priority;
    bridge_identifier_t prevRRootID = tree->rootPriority.RRootID;
    __be32 prevExtRootPathCost = tree->rootPriority.ExtRootPathCost;
    bool cist = (0 == tree->MSTID);
    /* a), b) Select new root priority vector = {rootPriority, rootPortId} */
      /* Initial value = bridge priority vector = {BridgePriority, 0} */
    assign(tree->rootPriority, tree->BridgePriority);
    assign(tree->rootPortId, __constant_cpu_to_be16(0));
      /* Now check root path priority vectors of all ports in tree and see if
       * there is a better vector */
    FOREACH_PTP_IN_TREE(ptp, tree)
    {
        port_t *prt = ptp->port;
        /* 802.1Q says to calculate root priority vector only if port
         * is not Disabled, but check (infoIs == ioReceived) covers
         * the case (infoIs != ioDisabled).
         */
        if((ioReceived == ptp->infoIs) && !prt->restrictedRole
           && cmp(ptp->portPriority.DesignatedBridgeID, !=,
                  tree->BridgeIdentifier)
          )
        {
            root_path_priority = ptp->portPriority;
            if(prt->rcvdInternal)
            {
                assign(root_path_priority.IntRootPathCost,
                       __cpu_to_be32(__be32_to_cpu(root_path_priority.IntRootPathCost)
                                     + ptp->InternalPortPathCost)
                      );
            }
            else if(cist) /* Yes, this check might be superfluous,
                           * but I want to be on the safe side */
            {
                assign(root_path_priority.ExtRootPathCost,
                       __cpu_to_be32(__be32_to_cpu(root_path_priority.ExtRootPathCost)
                                     + prt->ExternalPortPathCost)
                      );
                assign(root_path_priority.RRootID, tree->BridgeIdentifier);
                assign(root_path_priority.IntRootPathCost,
                       __constant_cpu_to_be32(0));
            }
            if(betterorsamePriority(&root_path_priority, &tree->rootPriority,
                                    ptp->portId, tree->rootPortId, cist))
            {
                assign(tree->rootPriority, root_path_priority);
                assign(tree->rootPortId, ptp->portId);
                root_ptp = ptp;
            }
        }
    }
    /* 802.1q-2005 says, that at some point we need compare portTimes with
     * "... one for the Root Port ...". Bad IEEE! Why not mention explicit
     * var names??? (see 13.26.23.g) for instance)
     * These comparisons happen three times, twice in clause g)
     *   and once in clause i). Look for samePriorityAndTimers() calls.
     * So, now I should guess what will work for the "times for the Root Port".
     * Thanks to Rajani's experiments I know for sure that I should use
     *  designatedTimes here. Thank you, Rajani!
     * NOTE: Both Alex Rozin (author of rstplib) and Srinivas Aji (author
     *   of rstpd) also compare portTimes with designatedTimes.
     */
    /* c) Set new rootTimes */
    if(root_ptp)
    {
        assign(tree->rootTimes, root_ptp->portTimes);
        port_t *prt = root_ptp->port;
        if(prt->rcvdInternal)
        {
            if(tree->rootTimes.remainingHops)
                --(tree->rootTimes.remainingHops);
        }
        else
            ++(tree->rootTimes.Message_Age);
    }
    else
    {
        assign(tree->rootTimes, tree->BridgeTimes);
    }
    FOREACH_PTP_IN_TREE(ptp, tree)
    {
        port_t *prt = ptp->port;
        /* d) Set new designatedPriority */
        assign(ptp->designatedPriority, tree->rootPriority);
        assign(ptp->designatedPriority.DesignatedBridgeID,
               tree->BridgeIdentifier);
        assign(ptp->designatedPriority.DesignatedPortID, ptp->portId);
        /* I am not sure which condition to check here, as 802.1Q-2005 says:
         * "... If {Port} is attached to a LAN that has one or more STP Bridges
         *  attached (as determined by the Port Protocol Migration state
         * machine) ..." -- why not to mention explicit var name? Bad IEEE.
         * But I guess that sendSTP (i.e. !sendRSTP) var will do ;)
         */
        if(cist && !prt->sendRSTP)
            assign(ptp->designatedPriority.RRootID, tree->BridgeIdentifier);
        /* e) Set new designatedTimes */
        assign(ptp->designatedTimes, tree->rootTimes);
        /* Keep the configured Hello_Time for the port.
         * NOTE: this is in accordance with the spirit of 802.1D-2004.
         *    Also, this does not contradict 802.1Q-2005(-2011), as in these
         *    standards both designatedTimes and rootTimes structures
         *    don't have Hello_Time member.
         */
        assign(ptp->designatedTimes.Hello_Time, ptp->portTimes.Hello_Time);
    }
    /* syncMaster */
    if(cist && cmp(tree->rootPriority.RRootID, !=, prevRRootID)
       && ((0 != tree->rootPriority.ExtRootPathCost)
           || (0 != prevExtRootPathCost)
          )
      )
        syncMaster(tree->bridge);
    FOREACH_PTP_IN_TREE(ptp, tree)
    {
        port_t *prt = ptp->port;
        per_tree_port_t *cist_tree = GET_CIST_PTP_FROM_PORT(prt);
        /* f) Set Disabled role */
        if(ioDisabled == ptp->infoIs)
        {
            ptp->selectedRole = roleDisabled;
            continue;
        }
        if(!cist && (ioReceived == cist_tree->infoIs) && !prt->infoInternal)
        {
            /* g) Set role for the boundary port in MSTI */
            if(roleRoot == cist_tree->selectedRole)
            {
                ptp->selectedRole = roleMaster;
                if(!samePriorityAndTimers(&ptp->portPriority,
                                          &ptp->designatedPriority,
                                          &ptp->portTimes,
                                          &ptp->designatedTimes,
                                          /*cist*/ false))
                    ptp->updtInfo = true;
                continue;
            }
            /* Bad IEEE again! It says in 13.26.23 g) 2) that
             * MSTI state should follow CIST state only for the case of
             * Alternate port. This is obviously wrong!
             * In the descriptive clause 13.13 f) it says:
             *  "At a Boundary Port frames allocated to the CIST and
             *   all MSTIs are forwarded or not forwarded alike.
             *   This is because Port Role assignments are such that
             *   if the CIST Port Role is Root Port, the MSTI Port Role
             *   will be Master Port, and if the CIST Port Role is
             *   Designated Port, Alternate Port, Backup Port,
             *   or Disabled Port, each MSTIs Port Role will be the same."
             * So, ignore wrong 13.26.23 g) 2) and do as stated in 13.13 f) !
             */
            /* if(roleAlternate == cist_tree->selectedRole) */
            {
                ptp->selectedRole = cist_tree->selectedRole;
                if(!samePriorityAndTimers(&ptp->portPriority,
                                          &ptp->designatedPriority,
                                          &ptp->portTimes,
                                          &ptp->designatedTimes,
                                          /*cist*/ false))
                    ptp->updtInfo = true;
                continue;
            }
        }
        else
     /* if(cist || (ioReceived != cist_tree->infoIs) || prt->infoInternal) */
        {
            /* h) Set role for the aged info */
            if(ioAged == ptp->infoIs)
            {
                ptp->selectedRole = roleDesignated;
                ptp->updtInfo = true;
                continue;
            }
            /* i) Set role for the mine info */
            if(ioMine == ptp->infoIs)
            {
                ptp->selectedRole = roleDesignated;
                if(!samePriorityAndTimers(&ptp->portPriority,
                                          &ptp->designatedPriority,
                                          &ptp->portTimes,
                                          &ptp->designatedTimes,
                                          cist))
                    ptp->updtInfo = true;
                continue;
            }
            if(ioReceived == ptp->infoIs)
            {
                /* j) Set Root role */
                if(root_ptp == ptp)
                {
                    ptp->selectedRole = roleRoot;
                    ptp->updtInfo = false;
                }
                else
                {
                    if(betterorsamePriority(&ptp->portPriority,
                                             &ptp->designatedPriority,
                                             0, 0, cist))
                    {
                        if(cmp(ptp->portPriority.DesignatedBridgeID, !=,
                               tree->BridgeIdentifier))
{
                            /* k) Set Alternate role */
                            ptp->selectedRole = roleAlternate;
                        }
                        else
{
                            /* l) Set Backup role */
                            ptp->selectedRole = roleBackup;
                        }
                        /* reset updtInfo for both k) and l) */
                        ptp->updtInfo = false;
                    }
                    else /* designatedPriority is better than portPriority */
                    {
                        /* m) Set Designated role */
                        ptp->selectedRole = roleDesignated;
                        ptp->updtInfo = true;
                    }
                }
                /* This is not in standard. But we really should set here
                 * reselect for all MSTIs so that updtRolesTree is called
                 * for each MSTI and due to above clause g) MSTI role is
                 * changed to Master or reflects CIST port role.
                 * Because in 802.1Q-2005 this will not happen when BPDU arrives
                 * at boundary port - the rcvdMsg is not set for the MSTIs and
                 * updtRolesTree is not called.
                 * Bad IEEE !!!
                 */
                if(cist && (ptp->selectedRole != ptp->role))
                    reselectMSTIs(prt);
                continue;
            }
        }
    }
}
References assign, betterorsamePriority(), tree_t::bridge, tree_t::BridgeIdentifier, tree_t::BridgePriority, tree_t::BridgeTimes, cmp, port_priority_vector_t::DesignatedBridgeID, port_priority_vector_t::DesignatedPortID, per_tree_port_t::designatedPriority, per_tree_port_t::designatedTimes, port_t::ExternalPortPathCost, port_priority_vector_t::ExtRootPathCost, FOREACH_PTP_IN_TREE, GET_CIST_PTP_FROM_PORT, times_t::Hello_Time, port_t::infoInternal, per_tree_port_t::infoIs, per_tree_port_t::InternalPortPathCost, port_priority_vector_t::IntRootPathCost, ioAged, ioDisabled, ioMine, ioReceived, times_t::Message_Age, tree_t::MSTID, per_tree_port_t::port, per_tree_port_t::portId, per_tree_port_t::portPriority, per_tree_port_t::portTimes, port_t::rcvdInternal, times_t::remainingHops, reselectMSTIs(), port_t::restrictedRole, per_tree_port_t::role, roleAlternate, roleBackup, roleDesignated, roleDisabled, roleMaster, roleRoot, tree_t::rootPortId, tree_t::rootPriority, tree_t::rootTimes, port_priority_vector_t::RRootID, samePriorityAndTimers(), per_tree_port_t::selectedRole, port_t::sendRSTP, syncMaster(), and per_tree_port_t::updtInfo.
Referenced by PRSSM_to_ROLE_SELECTION().