zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/libubox/kvlist.c File Reference
kvlist.c File Reference
#include <stdlib.h>
#include <string.h>
#include "utils.h"
#include "avl-cmp.h"
#include "blob.h"
#include "kvlist.h"
Functions
int kvlist_strlen (struct kvlist *kv, const void *data)
int kvlist_blob_len (struct kvlist *kv, const void *data)
void kvlist_init (struct kvlist *kv, int(*get_len)(struct kvlist *kv, const void *data))
static struct kvlist_node * __kvlist_get (struct kvlist *kv, const char *name)
void * kvlist_get (struct kvlist *kv, const char *name)
bool kvlist_delete (struct kvlist *kv, const char *name)
bool kvlist_set (struct kvlist *kv, const char *name, const void *data)
void kvlist_free (struct kvlist *kv)
Function Documentation
__kvlist_get()
static struct kvlist_node * __kvlist_get (struct kvlist * kv, const char * name) static
Definition at line 43 of file kvlist.c.
{
    struct kvlist_node *node;
    return avl_find_element(&kv->avl, name, node, avl);
}
References kvlist::avl, kvlist_node::avl, and avl_find_element.
Referenced by kvlist_delete(), and kvlist_get().
kvlist_blob_len()
int kvlist_blob_len (struct kvlist * kv, const void * data)
Definition at line 32 of file kvlist.c.
{
    return blob_pad_len(data);
}
References blob_pad_len().
kvlist_delete()
bool kvlist_delete (struct kvlist * kv, const char * name)
Definition at line 61 of file kvlist.c.
{
    struct kvlist_node *node;
    node = __kvlist_get(kv, name);
    if (node) {
        avl_delete(&kv->avl, &node->avl);
        free(node);
    }
    return !!node;
}
References __kvlist_get(), kvlist::avl, node::avl, and avl_delete().
Referenced by kvlist_set().
kvlist_free()
void kvlist_free (struct kvlist * kv)
Definition at line 95 of file kvlist.c.
{
    struct kvlist_node *node, *tmp;
    avl_remove_all_elements(&kv->avl, node, avl, tmp)
        free(node);
}
References kvlist::avl, kvlist_node::avl, and avl_remove_all_elements.
Referenced by bridge_free(), and device_vlan_update().
kvlist_get()
void * kvlist_get (struct kvlist * kv, const char * name)
Definition at line 50 of file kvlist.c.
{
    struct kvlist_node *node;
    node = __kvlist_get(kv, name);
    if (!node)
        return NULL;
    return node->data;
}
References __kvlist_get().
Referenced by get_vlan_device(), and vlandev_get_vid().
kvlist_init()
void kvlist_init (struct kvlist * kv, int(* get_len)(struct kvlist *kv, const void *data))
Definition at line 37 of file kvlist.c.
{
    avl_init(&kv->avl, avl_strcmp, false, NULL);
    kv->get_len = get_len;
}
References kvlist::avl, avl_init(), avl_strcmp(), and kvlist::get_len.
Referenced by device_vlan_update().
kvlist_set()
bool kvlist_set (struct kvlist * kv, const char * name, const void * data)
Definition at line 74 of file kvlist.c.
{
    struct kvlist_node *node;
    char *name_buf;
    int len = kv->get_len(kv, data);
    node = calloc_a(sizeof(struct kvlist_node) + len,
        &name_buf, strlen(name) + 1);
    if (!node)
        return false;
    kvlist_delete(kv, name);
    memcpy(node->data, data, len);
    node->avl.key = strcpy(name_buf, name);
    avl_insert(&kv->avl, &node->avl);
    return true;
}
References kvlist::avl, node::avl, avl_insert(), calloc_a, kvlist::get_len, avl_node::key, and kvlist_delete().
Referenced by config_parse_vlan().
kvlist_strlen()
int kvlist_strlen (struct kvlist * kv, const void * data)
Definition at line 27 of file kvlist.c.
{
    return strlen(data) + 1;
}