zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/ustp/ubus.h File Reference
ubus.h File Reference
Functions
void ustp_ubus_init (void)
void ustp_ubus_exit (void)
Function Documentation
ustp_ubus_exit()
void ustp_ubus_exit (void)
Definition at line 228 of file ubus.c.
{
    uint32_t id;
    ubus_remove_object(&conn.ctx, &ustp_object);
    ubus_unregister_subscriber(&conn.ctx, &netifd_sub);
    blob_buf_init(&b, 0);
    if (ubus_lookup_id(&conn.ctx, "network.device", &id) == 0)
        ubus_invoke(&conn.ctx, id, "stp_init", b.head, NULL, NULL, 1000);
    ubus_auto_shutdown(&conn);
}
References b, blob_buf_init(), conn, ubus_auto_conn::ctx, blob_buf::head, id, netifd_sub, ubus_auto_shutdown(), ubus_invoke(), ubus_lookup_id(), ubus_remove_object(), ubus_unregister_subscriber(), and ustp_object.
Referenced by main().
ustp_ubus_init()
void ustp_ubus_init (void)
Definition at line 222 of file ubus.c.
{
    conn.cb = ubus_connect_handler;
    ubus_auto_connect(&conn);
}
References ubus_auto_conn::cb, conn, ubus_auto_connect(), and ubus_connect_handler().
Referenced by main().