zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/libubox/blob.h File Reference
blob.h File Reference
#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include <errno.h>
#include "utils.h"
Classes
struct blob_attr
struct blob_attr_info
struct blob_buf
Macros
#define BLOB_COOKIE 0x01234567
#define BLOB_ATTR_ID_MASK 0x7f000000
#define BLOB_ATTR_ID_SHIFT 24
#define BLOB_ATTR_LEN_MASK 0x00ffffff
#define BLOB_ATTR_ALIGN 4
#define BLOB_ATTR_EXTENDED 0x80000000
#define blob_put_int8 blob_put_u8
#define blob_put_int16 blob_put_u16
#define blob_put_int32 blob_put_u32
#define blob_put_int64 blob_put_u64
#define __blob_for_each_attr(pos, attr, rem)
#define blob_for_each_attr(pos, attr, rem)
#define blob_for_each_attr_len(pos, attr, attr_len, rem)
Enumerations
enum {
BLOB_ATTR_UNSPEC , BLOB_ATTR_NESTED , BLOB_ATTR_BINARY , BLOB_ATTR_STRING ,
BLOB_ATTR_INT8 , BLOB_ATTR_INT16 , BLOB_ATTR_INT32 , BLOB_ATTR_INT64 ,
BLOB_ATTR_DOUBLE , BLOB_ATTR_LAST
}
Functions
static void * blob_data (const struct blob_attr *attr)
static unsigned int blob_id (const struct blob_attr *attr)
static bool blob_is_extended (const struct blob_attr *attr)
static size_t blob_len (const struct blob_attr *attr)
static size_t blob_raw_len (const struct blob_attr *attr)
static size_t blob_pad_len (const struct blob_attr *attr)
static uint8_t blob_get_u8 (const struct blob_attr *attr)
static uint16_t blob_get_u16 (const struct blob_attr *attr)
static uint32_t blob_get_u32 (const struct blob_attr *attr)
static uint64_t blob_get_u64 (const struct blob_attr *attr)
static int8_t blob_get_int8 (const struct blob_attr *attr)
static int16_t blob_get_int16 (const struct blob_attr *attr)
static int32_t blob_get_int32 (const struct blob_attr *attr)
static int64_t blob_get_int64 (const struct blob_attr *attr)
static const char * blob_get_string (const struct blob_attr *attr)
static struct blob_attr * blob_next (const struct blob_attr *attr)
void blob_fill_pad (struct blob_attr *attr)
void blob_set_raw_len (struct blob_attr *attr, unsigned int len)
bool blob_attr_equal (const struct blob_attr *a1, const struct blob_attr *a2)
int blob_buf_init (struct blob_buf *buf, int id)
void blob_buf_free (struct blob_buf *buf)
bool blob_buf_grow (struct blob_buf *buf, int required)
struct blob_attr * blob_new (struct blob_buf *buf, int id, int payload)
void * blob_nest_start (struct blob_buf *buf, int id)
void blob_nest_end (struct blob_buf *buf, void *cookie)
struct blob_attr * blob_put (struct blob_buf *buf, int id, const void *ptr, unsigned int len)
bool blob_check_type (const void *ptr, unsigned int len, int type)
int blob_parse (struct blob_attr *attr, struct blob_attr **data, const struct blob_attr_info *info, int max)
int blob_parse_untrusted (struct blob_attr *attr, size_t attr_len, struct blob_attr **data, const struct blob_attr_info *info, int max)
struct blob_attr * blob_memdup (struct blob_attr *attr)
struct blob_attr * blob_put_raw (struct blob_buf *buf, const void *ptr, unsigned int len)
static struct blob_attr * blob_put_string (struct blob_buf *buf, int id, const char *str)
static struct blob_attr * blob_put_u8 (struct blob_buf *buf, int id, uint8_t val)
static struct blob_attr * blob_put_u16 (struct blob_buf *buf, int id, uint16_t val)
static struct blob_attr * blob_put_u32 (struct blob_buf *buf, int id, uint32_t val)
static struct blob_attr * blob_put_u64 (struct blob_buf *buf, int id, uint64_t val)
Variables
struct blob_attr __packed
Class Documentation
blob_attr
struct blob_attr
Definition at line 52 of file blob.h.
Class Members
char data[]
uint32_t id_len
blob_attr_info
struct blob_attr_info
Definition at line 57 of file blob.h.
Class Members
unsigned int maxlen
unsigned int minlen
unsigned int type
bool(*)(const struct blob_attr_info *, struct blob_attr *) validate
blob_buf
struct blob_buf
Definition at line 64 of file blob.h.
Class Members
void * buf
int buflen
bool(*)(struct blob_buf *buf, int minlen) grow
struct blob_attr * head
Macro Definition Documentation
__blob_for_each_attr
#define __blob_for_each_attr (pos, attr, rem)
Value:
    for (pos = (struct blob_attr *) attr; \
         rem >= sizeof(struct blob_attr) && (blob_pad_len(pos) <= rem) && \
         (blob_pad_len(pos) >= sizeof(struct blob_attr)); \
         rem -= blob_pad_len(pos), pos = blob_next(pos))
Definition at line 244 of file blob.h.
#define __blob_for_each_attr(pos, attr, rem) \
    for (pos = (struct blob_attr *) attr; \
         rem >= sizeof(struct blob_attr) && (blob_pad_len(pos) <= rem) && \
         (blob_pad_len(pos) >= sizeof(struct blob_attr)); \
         rem -= blob_pad_len(pos), pos = blob_next(pos))
Referenced by blobmsg_format_json_list(), blobmsg_list_fill(), blobmsg_parse(), blobmsg_parse_array(), dump_table(), rpc_ucode_blob_array_to_ucv(), rpc_ucode_validate_call_args(), and ubus_lua_parse_blob_array().
BLOB_ATTR_ALIGN
#define BLOB_ATTR_ALIGN 4
Definition at line 49 of file blob.h.
Referenced by blob_pad_len().
BLOB_ATTR_EXTENDED
#define BLOB_ATTR_EXTENDED 0x80000000
Definition at line 50 of file blob.h.
Referenced by blob_is_extended(), and blobmsg_new().
BLOB_ATTR_ID_MASK
#define BLOB_ATTR_ID_MASK 0x7f000000
Definition at line 46 of file blob.h.
Referenced by blob_id(), and blob_init().
BLOB_ATTR_ID_SHIFT
#define BLOB_ATTR_ID_SHIFT 24
Definition at line 47 of file blob.h.
Referenced by blob_id(), and blob_init().
BLOB_ATTR_LEN_MASK
#define BLOB_ATTR_LEN_MASK 0x00ffffff
Definition at line 48 of file blob.h.
Referenced by blob_buf_grow(), blob_init(), blob_len(), and blob_set_raw_len().
BLOB_COOKIE
#define BLOB_COOKIE 0x01234567
Definition at line 31 of file blob.h.
Referenced by attr_to_offset(), attr_to_offset(), blob_add(), blobmsg_realloc_string_buffer(), and offset_to_attr().
blob_for_each_attr
#define blob_for_each_attr (pos, attr, rem)
Value:
    for (rem = attr ? blob_len(attr) : 0, \
         pos = (struct blob_attr *) (attr ? blob_data(attr) : NULL); \
         rem >= sizeof(struct blob_attr) && (blob_pad_len(pos) <= rem) && \
         (blob_pad_len(pos) >= sizeof(struct blob_attr)); \
         rem -= blob_pad_len(pos), pos = blob_next(pos))
Definition at line 251 of file blob.h.
#define blob_for_each_attr(pos, attr, rem) \
    for (rem = attr ? blob_len(attr) : 0, \
         pos = (struct blob_attr *) (attr ? blob_data(attr) : NULL); \
         rem >= sizeof(struct blob_attr) && (blob_pad_len(pos) <= rem) && \
         (blob_pad_len(pos) >= sizeof(struct blob_attr)); \
         rem -= blob_pad_len(pos), pos = blob_next(pos))
Referenced by blob_parse(), interface_parse_data(), receive_list_result(), rpc_login_setup_acl_file(), rpc_plugin_parse_exec(), ubus_create_obj_type(), and ubus_process_notify_status().
blob_for_each_attr_len
#define blob_for_each_attr_len (pos, attr, attr_len, rem)
Value:
    for (rem = attr ? blob_len(attr) : 0, \
         pos = (struct blob_attr *) (attr ? blob_data(attr) : NULL); \
         rem >= sizeof(struct blob_attr) && rem < attr_len && (blob_pad_len(pos) <= rem) && \
         (blob_pad_len(pos) >= sizeof(struct blob_attr)); \
         rem -= blob_pad_len(pos), pos = blob_next(pos))
Definition at line 258 of file blob.h.
#define blob_for_each_attr_len(pos, attr, attr_len, rem) \
    for (rem = attr ? blob_len(attr) : 0, \
         pos = (struct blob_attr *) (attr ? blob_data(attr) : NULL); \
         rem >= sizeof(struct blob_attr) && rem < attr_len && (blob_pad_len(pos) <= rem) && \
         (blob_pad_len(pos) >= sizeof(struct blob_attr)); \
         rem -= blob_pad_len(pos), pos = blob_next(pos))
Referenced by blob_parse_untrusted().
blob_put_int16
#define blob_put_int16 blob_put_u16
Definition at line 240 of file blob.h.
blob_put_int32
#define blob_put_int32 blob_put_u32
Definition at line 241 of file blob.h.
Referenced by __ubus_notify_async(), __ubus_subscribe_request(), ubus_add_object(), ubus_complete_deferred_request(), ubus_invoke_async_fd(), ubus_notify_subscription(), ubus_notify_unsubscribe(), ubus_remove_object(), ubus_send_event(), ubus_send_reply(), ubusd_create_event_from_msg(), ubusd_create_object_event_msg(), ubusd_create_sequence_event_msg(), ubusd_forward_invoke(), ubusd_handle_add_object(), ubusd_handle_notify(), ubusd_handle_remove_object(), ubusd_monitor_message(), ubusd_proto_init_retmsg(), ubusd_reply_query(), and ubusd_send_obj().
blob_put_int64
#define blob_put_int64 blob_put_u64
Definition at line 242 of file blob.h.
blob_put_int8
#define blob_put_int8 blob_put_u8
Definition at line 239 of file blob.h.
Referenced by __ubus_notify_async(), ubus_notify_subscription(), ubusd_handle_notify(), and ubusd_monitor_message().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
BLOB_ATTR_UNSPEC
BLOB_ATTR_NESTED
BLOB_ATTR_BINARY
BLOB_ATTR_STRING
BLOB_ATTR_INT8
BLOB_ATTR_INT16
BLOB_ATTR_INT32
BLOB_ATTR_INT64
BLOB_ATTR_DOUBLE
BLOB_ATTR_LAST
Definition at line 33 of file blob.h.
     {
    BLOB_ATTR_UNSPEC,
    BLOB_ATTR_NESTED,
    BLOB_ATTR_BINARY,
    BLOB_ATTR_STRING,
    BLOB_ATTR_INT8,
    BLOB_ATTR_INT16,
    BLOB_ATTR_INT32,
    BLOB_ATTR_INT64,
    BLOB_ATTR_DOUBLE,
    BLOB_ATTR_LAST
};
Function Documentation
blob_attr_equal()
bool blob_attr_equal (const struct blob_attr * a1, const struct blob_attr * a2) extern
Definition at line 311 of file blob.c.
{
    if (!a1 && !a2)
        return true;
    if (!a1 || !a2)
        return false;
    if (blob_pad_len(a1) != blob_pad_len(a2))
        return false;
    return !memcmp(a1, a2, blob_pad_len(a1));
}
References blob_pad_len().
Referenced by device_set_auth_status(), instance_config_changed(), station_update(), vif_update(), vlan_update(), and wdev_change_config().
blob_buf_free()
void blob_buf_free (struct blob_buf * buf) extern
Definition at line 104 of file blob.c.
{
    free(buf->buf);
    buf->buf = NULL;
    buf->head = NULL;
    buf->buflen = 0;
}
References buf.
Referenced by json_script_free(), main(), main(), netns_updown(), parseOCI(), parseOCIcapabilities_from_file(), pass_console(), proto_shell_create_tunnel(), reload_conf(), rpc_exec_reply(), rpc_file_exec_reply(), rpc_file_list(), rpc_file_md5(), rpc_file_read(), rpc_file_stat(), rpc_login_setup_acl_file(), rpc_sys_packagelist(), run_netifd(), run_ubusd(), ubus_lua__gc(), ubus_register_event_handler(), ubus_shutdown(), ubusd_proto_free_client(), uxc_attach(), uxc_create(), uxc_delete(), uxc_list(), uxc_set(), and uxc_state().
blob_buf_grow()
bool blob_buf_grow (struct blob_buf * buf, int required) extern
Definition at line 57 of file blob.c.
{
    int offset_head = attr_to_offset(buf, buf->head);
    if ((buf->buflen + required) > BLOB_ATTR_LEN_MASK)
        return false;
    if (!buf->grow || !buf->grow(buf, required))
        return false;
    buf->head = offset_to_attr(buf, offset_head);
    return true;
}
References attr_to_offset(), BLOB_ATTR_LEN_MASK, buf, and offset_to_attr().
Referenced by blob_add(), and blobmsg_realloc_string_buffer().
blob_buf_init()
int blob_buf_init (struct blob_buf * buf, int id) extern
Definition at line 91 of file blob.c.
{
    if (!buf->grow)
        buf->grow = blob_buffer_grow;
    buf->head = buf->buf;
    if (blob_add(buf, buf->buf, id, 0) == NULL)
        return -ENOMEM;
    return 0;
}
References blob_add(), blob_buffer_grow(), and buf.
Referenced by __device_broadcast_event(), __do_bridge_reload(), __ubus_monitor(), __ubus_notify_async(), __ubus_subscribe_request(), __udebug_buf_add(), __vlan_hotplug_op(), __vlandev_hotplug_op(), blobmsg_buf_init(), bridge_stp_notify(), client_main(), cmd_process_strings(), conf_load(), config_init_board(), config_init_devices(), config_parse_bridge_interface(), config_parse_interface(), config_parse_neighbor(), config_parse_route(), config_parse_rule(), config_parse_vlan(), config_parse_wireless_device(), config_parse_wireless_interface(), config_parse_wireless_station(), config_parse_wireless_vlan(), container_handle_features(), extdev_bridge_disable_interface(), extdev_bridge_disable_member(), extdev_bridge_enable_member(), extdev_dump(), extdev_free(), extdev_hotplug_prepare(), handle_button_timeout(), handle_expr_isdir(), handle_file(), handle_file(), handle_state(), hotplug_handler(), install_syscall_filter(), jail_delete_instance(), jshn_format(), netifd_add_host_route(), netifd_dev_status(), netifd_get_proto_handlers(), netifd_handle_dump(), netifd_handle_iface_prepare(), netifd_handle_status(), netifd_handle_wdev_get_validate(), netifd_handle_wdev_status(), netifd_sub_cb(), netifd_ubus_get_procd_data(), netifd_ubus_interface_event(), netifd_ubus_interface_notify(), netns_updown(), parseOCI(), parseOCIcapabilities_from_file(), pass_console(), prepare_config(), print_syscalls(), proto_shell_create_tunnel(), rc_list(), rpc_exec(), rpc_file_exec_reply(), rpc_file_list(), rpc_file_md5(), rpc_file_read(), rpc_file_stat(), rpc_handle_access(), rpc_handle_get(), rpc_iwinfo_assoclist(), rpc_iwinfo_countrylist(), rpc_iwinfo_devices(), rpc_iwinfo_freqlist(), rpc_iwinfo_info(), rpc_iwinfo_phyname(), rpc_iwinfo_scan(), rpc_iwinfo_survey(), rpc_iwinfo_txpowerlist(), rpc_login_setup_acl_file(), rpc_plugin_parse_exec(), rpc_session_to_blob(), rpc_sys_packagelist(), rpc_uci_add(), rpc_uci_changes(), rpc_uci_configs(), rpc_uci_getcommon(), rpc_uci_trigger_event(), rpc_ucode_request_finish(), rpc_ucode_script_call(), rule_handle_file(), run_netifd(), run_ubusd(), service_get_data(), service_handle_list(), service_handle_validate(), service_handle_watchdog(), service_instance_update(), service_start_early(), system_board(), system_info(), sysupgrade_error(), test_client_notify_cb(), test_count(), test_count(), test_hello_reply(), ubus_add_object(), ubus_cli_call(), ubus_cli_get_monitor_data(), ubus_cli_send(), ubus_complete_deferred_request(), ubus_event_bcast(), ubus_invoke_async_fd(), ubus_lookup(), ubus_lookup_id(), ubus_lua_call(), ubus_lua_notify(), ubus_lua_reply(), ubus_lua_send(), ubus_notify_subscription(), ubus_notify_unsubscribe(), ubus_register_event_handler(), ubus_remove_object(), ubus_send_event(), ubus_send_msg(), ubus_send_reply(), ubusd_acl_load_file(), ubusd_create_event_from_msg(), ubusd_create_object_event_msg(), ubusd_create_sequence_event_msg(), ubusd_handle_add_object(), ubusd_handle_invoke(), ubusd_handle_notify(), ubusd_handle_remove_object(), ubusd_monitor_message(), ubusd_proto_init_retmsg(), ubusd_reply_query(), ubusd_send_hello(), ubusd_send_obj(), udebug_entry_add(), udebug_send_msg(), ustp_ubus_exit(), uxc_attach(), uxc_boot(), uxc_create(), uxc_delete(), uxc_kill(), uxc_list(), uxc_set(), uxc_state(), validate_firmware_image_call(), and watchdog_set().
blob_check_type()
bool blob_check_type (const void * ptr, unsigned int len, int type) extern
Definition at line 202 of file blob.c.
{
    const char *data = ptr;
    if (type >= BLOB_ATTR_LAST)
        return false;
    if (type >= BLOB_ATTR_INT8 && type <= BLOB_ATTR_INT64) {
        if (len != blob_type_minlen[type])
            return false;
    } else {
        if (len < blob_type_minlen[type])
            return false;
    }
    if (type == BLOB_ATTR_STRING && data[len - 1] != 0)
        return false;
    return true;
}
References BLOB_ATTR_INT64, BLOB_ATTR_INT8, BLOB_ATTR_LAST, BLOB_ATTR_STRING, blob_type_minlen, blob_attr::data, and type.
Referenced by blob_parse_attr(), blobmsg_check_attr_len(), and ubus_process_notify_status().
blob_data()
static void * blob_data (const struct blob_attr * attr) inline static
Definition at line 75 of file blob.h.
{
    return (void *) attr->data;
}
References blob_attr::data.
Referenced by __interface_add(), __json_process_cmd(), __rpc_check_path(), __ubusd_handle_lookup(), blob_get_u64(), blob_parse_attr(), blob_put(), blobmsg_check_name(), blobmsg_clear_name(), blobmsg_data(), blobmsg_data_len(), blobmsg_name(), blobmsg_new(), blobmsg_parse(), bonding_reload(), bridge_reload(), cert_dump_blob(), check_message(), config_parse_neighbor(), config_parse_route(), config_parse_rule(), config_parse_vlan(), config_watch_notify_cb(), device_set_config(), dump_message(), dump_message(), dump_message_cast_s64(), dump_message_cast_s64_json(), dump_message_cast_u64(), dump_message_cast_u64_json(), dump_message_json(), dump_table(), extdev_buf_add_list(), extdev_wait_ev_cb(), get_wdev(), handle_expr_isdir(), handle_file(), handle_file(), hotplug_handler(), interface_alloc(), interface_device_config_changed(), macvlan_reload(), netifd_add_dynamic(), netifd_add_host_route(), netifd_dev_status(), netifd_handle_alias(), netifd_handle_iface(), netifd_handle_set_state(), netifd_iface_handle_device(), netifd_netns_updown(), parseOCI(), proc_signal(), proto_apply_ip_settings(), proto_apply_static_ip_settings(), proto_shell_checkup_attach(), proto_shell_create_tunnel(), proto_shell_notify(), rpc_cgi_password_set(), rpc_file_exec(), rpc_handle_access(), rpc_handle_acl(), rpc_handle_create(), rpc_handle_destroy(), rpc_handle_get(), rpc_handle_list(), rpc_handle_login(), rpc_handle_set(), rpc_handle_unset(), rpc_iwinfo_assoclist(), rpc_iwinfo_open(), rpc_iwinfo_phyname(), rpc_session_from_blob(), rpc_sys_packagelist(), rpc_sys_upgrade_start(), rpc_uci_add(), rpc_uci_apply(), rpc_uci_changes(), rpc_uci_confirm(), rpc_uci_delete(), rpc_uci_getcommon(), rpc_uci_order(), rpc_uci_rename(), rpc_uci_revert_commit(), rpc_uci_rollback(), rpc_uci_set(), rpc_ucode_validate_call_args(), rule_handle_file(), settings_add(), simple_device_create(), system_add_ip_tunnel(), sysupgrade(), test_count(), test_count_data_cb(), test_hello(), test_watch(), tunnel_reload(), ubus_auto_sub_event_handler_cb(), ubus_cli_get_monitor_data(), ubus_event_handler(), ubus_lookup_cb(), ubus_lua_call_cb(), ubus_lua_signatures_cb(), ubus_method_handler(), ubus_process_invoke(), ubus_process_notify_status(), ubus_put_data(), ubus_reconnect(), ubus_send_event(), ubus_sub_notify_handler(), ubusd_acl_file_add(), ubusd_alloc_event_pattern(), ubusd_cmd_lookup(), ubusd_create_object(), ubusd_forward_event(), ubusd_forward_invoke(), ubusd_handle_invoke(), ubusd_handle_notify(), ubusd_monitor_message(), ubusd_proto_receive_message(), ubusd_send_event_msg(), uxc_boot(), uxc_create(), uxc_delete(), uxc_kill(), uxc_list(), uxc_set(), uxc_state(), validate_firmware_image(), veth_reload(), vlandev_reload(), wait_event_cb(), watch_subscribe_cb(), and watchdog_set().
blob_fill_pad()
void blob_fill_pad (struct blob_attr * attr) extern
Definition at line 113 of file blob.c.
{
    char *buf = (char *) attr;
    int len = blob_pad_len(attr);
    int delta = len - blob_raw_len(attr);
    if (delta > 0)
        memset(buf + len - delta, 0, delta);
}
References blob_pad_len(), blob_raw_len(), and buf.
Referenced by blob_add(), and blobmsg_add_string_buffer().
blob_get_int16()
static int16_t blob_get_int16 (const struct blob_attr * attr) inline static
Definition at line 161 of file blob.h.
{
    return blob_get_u16(attr);
}
References blob_get_u16().
blob_get_int32()
static int32_t blob_get_int32 (const struct blob_attr * attr) inline static
Definition at line 167 of file blob.h.
{
    return blob_get_u32(attr);
}
References blob_get_u32().
Referenced by ubus_cli_get_monitor_data(), ubus_cli_monitor_cb(), and ubus_process_notify_status().
blob_get_int64()
static int64_t blob_get_int64 (const struct blob_attr * attr) inline static
Definition at line 173 of file blob.h.
{
    return blob_get_u64(attr);
}
References blob_get_u64().
blob_get_int8()
static int8_t blob_get_int8 (const struct blob_attr * attr) inline static
Definition at line 155 of file blob.h.
{
    return blob_get_u8(attr);
}
References blob_get_u8().
Referenced by ubus_cli_get_monitor_data(), ubus_process_invoke(), and ubusd_handle_notify().
blob_get_string()
static const char * blob_get_string (const struct blob_attr * attr) inline static
Definition at line 179 of file blob.h.
{
    return attr->data;
}
References blob_attr::data.
blob_get_u16()
static uint16_t blob_get_u16 (const struct blob_attr * attr) inline static
Definition at line 132 of file blob.h.
{
    uint16_t *tmp = (uint16_t*)attr->data;
    return be16_to_cpu(*tmp);
}
References be16_to_cpu, and blob_attr::data.
Referenced by blob_get_int16().
blob_get_u32()
static uint32_t blob_get_u32 (const struct blob_attr * attr) inline static
Definition at line 139 of file blob.h.
{
    uint32_t *tmp = (uint32_t*)attr->data;
    return be32_to_cpu(*tmp);
}
References be32_to_cpu, and blob_attr::data.
Referenced by blob_get_int32(), ubus_add_object_cb(), ubus_get_status(), ubus_lookup_cb(), ubus_lookup_id_cb(), ubus_process_obj_msg(), ubus_process_unsubscribe(), ubusd_create_object(), ubusd_handle_add_watch(), ubusd_handle_invoke(), ubusd_handle_notify(), ubusd_handle_remove_object(), ubusd_handle_remove_watch(), ubusd_handle_response(), and ubusd_reply_query().
blob_get_u64()
static uint64_t blob_get_u64 (const struct blob_attr * attr) inline static
Definition at line 146 of file blob.h.
{
    uint32_t *ptr = (uint32_t *) blob_data(attr);
    uint64_t tmp = ((uint64_t) be32_to_cpu(ptr[0])) << 32;
    tmp |= be32_to_cpu(ptr[1]);
    return tmp;
}
References be32_to_cpu, and blob_data().
Referenced by blob_get_int64().
blob_get_u8()
static uint8_t blob_get_u8 (const struct blob_attr * attr) inline static
Definition at line 126 of file blob.h.
{
    return *((uint8_t *) attr->data);
}
References blob_attr::data.
Referenced by blob_get_int8(), and ubus_process_notify().
blob_id()
static unsigned int blob_id (const struct blob_attr * attr) inline static
Definition at line 84 of file blob.h.
{
    int id = (be32_to_cpu(attr->id_len) & BLOB_ATTR_ID_MASK) >> BLOB_ATTR_ID_SHIFT;
    return id;
}
References be32_to_cpu, BLOB_ATTR_ID_MASK, BLOB_ATTR_ID_SHIFT, id, and blob_attr::id_len.
Referenced by blob_parse_attr(), blobmsg_check_attr_len(), blobmsg_format_element(), blobmsg_parse(), blobmsg_parse_array(), blobmsg_type(), format_type(), rpc_ucode_blob_to_ucv(), rpc_ucode_validate_call_args(), and ubus_lua_parse_blob().
blob_is_extended()
static bool blob_is_extended (const struct blob_attr * attr) inline static
Definition at line 91 of file blob.h.
{
    return !!(attr->id_len & cpu_to_be32(BLOB_ATTR_EXTENDED));
}
References BLOB_ATTR_EXTENDED, cpu_to_be32, and blob_attr::id_len.
Referenced by blobmsg_check_name(), blobmsg_data(), blobmsg_format_json_with_cb(), blobmsg_parse(), and rpc_ucode_validate_call_args().
blob_len()
static size_t blob_len (const struct blob_attr * attr) inline static
Definition at line 100 of file blob.h.
{
    return (be32_to_cpu(attr->id_len) & BLOB_ATTR_LEN_MASK) - sizeof(struct blob_attr);
}
References be32_to_cpu, BLOB_ATTR_LEN_MASK, and blob_attr::id_len.
Referenced by __interface_add(), __rpc_check_path(), blob_nest_end(), blob_parse_attr(), blob_raw_len(), blobmsg_check_array_len(), blobmsg_check_name(), blobmsg_data_len(), blobmsg_list_equal(), bonding_reload(), bridge_reload(), config_parse_vlan(), config_watch_notify_cb(), device_set_config(), dump_message(), dump_message(), dump_message_cast_s64(), dump_message_cast_s64_json(), dump_message_cast_u64(), dump_message_cast_u64_json(), dump_message_json(), extdev_wait_ev_cb(), get_next_msg(), get_wdev(), handle_file(), handle_file(), interface_alloc(), interface_device_config_changed(), macvlan_reload(), netifd_add_dynamic(), netifd_add_host_route(), netifd_dev_status(), netifd_handle_alias(), netifd_handle_iface(), netifd_handle_set_state(), netifd_iface_handle_device(), netifd_netns_updown(), parseOCI(), proc_signal(), proto_apply_ip_settings(), proto_apply_static_ip_settings(), proto_shell_checkup_attach(), proto_shell_notify(), rpc_cgi_password_set(), rpc_file_exec(), rpc_handle_access(), rpc_handle_acl(), rpc_handle_create(), rpc_handle_destroy(), rpc_handle_get(), rpc_handle_list(), rpc_handle_login(), rpc_handle_set(), rpc_handle_unset(), rpc_iwinfo_assoclist(), rpc_iwinfo_open(), rpc_iwinfo_phyname(), rpc_session_from_blob(), rpc_sys_packagelist(), rpc_sys_upgrade_start(), rpc_uci_add(), rpc_uci_apply(), rpc_uci_changes(), rpc_uci_confirm(), rpc_uci_delete(), rpc_uci_getcommon(), rpc_uci_order(), rpc_uci_rename(), rpc_uci_revert_commit(), rpc_uci_rollback(), rpc_uci_set(), rpc_ucode_validate_call_args(), rule_handle_file(), setup_strbuf(), simple_device_create(), system_add_ip_tunnel(), sysupgrade(), test_count(), test_count_data_cb(), test_hello(), test_watch(), tunnel_reload(), ubus_auto_sub_event_handler_cb(), ubus_event_handler(), ubus_lua_call_cb(), ubus_lua_signatures_cb(), ubus_method_handler(), ubus_process_notify_status(), ubus_put_data(), ubus_reconnect(), ubus_send_event(), ubus_sub_notify_handler(), ubusd_acl_file_add(), ubusd_alloc_event_pattern(), ubusd_forward_event(), ubusd_forward_invoke(), ubusd_monitor_message(), validate_firmware_image(), veth_reload(), vlandev_reload(), wait_event_cb(), watch_subscribe_cb(), and watchdog_set().
blob_memdup()
struct blob_attr * blob_memdup (struct blob_attr * attr) extern
Definition at line 326 of file blob.c.
{
    struct blob_attr *ret;
    int size = blob_pad_len(attr);
    ret = malloc(size);
    if (!ret)
        return NULL;
    memcpy(ret, attr, size);
    return ret;
}
References blob_pad_len().
Referenced by __bridge_reload(), acl_recv_cb(), block_cb(), bonding_reload(), bridge_reload(), cert_load(), config_init_board(), config_parse_interface(), device_apply_config(), device_create(), device_init_settings(), device_set_auth_status(), fstab_cb(), instance_init(), macvlan_reload(), netifd_add_dynamic(), ocistate_cb(), parseOCI(), service_update(), station_update(), veth_reload(), vif_update(), vlan_update(), vlandev_reload(), wdev_change_config(), wdev_create(), wdev_prepare_prev_config(), wireless_device_notify(), and wireless_device_run_handler().
blob_nest_end()
void blob_nest_end (struct blob_buf * buf, void * cookie) extern
Definition at line 185 of file blob.c.
{
    struct blob_attr *attr = offset_to_attr(buf, (unsigned long) cookie);
    blob_set_raw_len(attr, blob_pad_len(attr) + blob_len(buf->head));
    buf->head = attr;
}
References blob_len(), blob_pad_len(), blob_set_raw_len(), buf, and offset_to_attr().
Referenced by blobmsg_close_array(), blobmsg_close_table(), ubus_push_object_type(), ubus_send_event(), ubusd_create_object_event_msg(), ubusd_create_sequence_event_msg(), ubusd_handle_notify(), ubusd_reply_query(), and ubusd_send_obj().
blob_nest_start()
void * blob_nest_start (struct blob_buf * buf, int id) extern
Definition at line 175 of file blob.c.
{
    unsigned long offset = attr_to_offset(buf, buf->head);
    buf->head = blob_new(buf, id, 0);
    if (!buf->head)
        return NULL;
    return (void *) offset;
}
References attr_to_offset(), blob_new(), and buf.
Referenced by ubus_push_object_type(), ubus_send_event(), ubusd_create_object_event_msg(), ubusd_create_sequence_event_msg(), ubusd_handle_notify(), ubusd_reply_query(), and ubusd_send_obj().
blob_new()
struct blob_attr * blob_new (struct blob_buf * buf, int id, int payload) extern
Definition at line 132 of file blob.c.
{
    struct blob_attr *attr;
    attr = blob_add(buf, blob_next(buf->head), id, payload);
    if (!attr)
        return NULL;
    blob_set_raw_len(buf->head, blob_pad_len(buf->head) + blob_pad_len(attr));
    return attr;
}
References blob_add(), blob_next(), blob_pad_len(), blob_set_raw_len(), and buf.
Referenced by blob_nest_start(), blob_put(), blobmsg_new(), and main().
blob_next()
static struct blob_attr * blob_next (const struct blob_attr * attr) inline static
Definition at line 185 of file blob.h.
{
    return (struct blob_attr *) ((char *) attr + blob_pad_len(attr));
}
References blob_pad_len().
Referenced by blob_new(), blob_put_raw(), blobmsg_add_string_buffer(), blobmsg_realloc_string_buffer(), and cert_load().
blob_pad_len()
static size_t blob_pad_len (const struct blob_attr * attr) inline static
Definition at line 118 of file blob.h.
{
    unsigned int len = blob_raw_len(attr);
    len = (len + BLOB_ATTR_ALIGN - 1) & ~(BLOB_ATTR_ALIGN - 1);
    return len;
}
References BLOB_ATTR_ALIGN, and blob_raw_len().
Referenced by __ubus_start_request(), _trigger_add(), _ubus_parse_msg(), blob_attr_equal(), blob_fill_pad(), blob_memdup(), blob_nest_end(), blob_new(), blob_next(), blob_put_raw(), blobmsg_add_string_buffer(), blobmsg_alloc_string_buffer(), blobmsg_open_nested(), blobmsg_realloc_string_buffer(), cert_load(), client_cb(), handle_button_complete(), interface_add_data(), kvlist_blob_len(), proto_shell_attach(), queue_add(), rpc_blob_from_file(), rpc_blob_to_file(), rpc_session_set(), rule_load_script(), static_attach(), trigger_command_add(), ubus_validate_hdr(), and udebug_send_msg().
blob_parse()
int blob_parse (struct blob_attr * attr, struct blob_attr ** data, const struct blob_attr_info * info, int max) extern
Definition at line 296 of file blob.c.
{
    struct blob_attr *pos;
    int found = 0;
    size_t rem;
    memset(data, 0, sizeof(struct blob_attr *) * max);
    blob_for_each_attr(pos, attr, rem) {
        found += blob_parse_attr(pos, rem, data, info, max);
    }
    return found;
}
References blob_for_each_attr, blob_parse_attr(), blob_attr::data, and info.
Referenced by ubus_cli_get_monitor_data().
blob_parse_untrusted()
int blob_parse_untrusted (struct blob_attr * attr, size_t attr_len, struct blob_attr ** data, const struct blob_attr_info * info, int max) extern
Definition at line 272 of file blob.c.
{
    struct blob_attr *pos;
    size_t len = 0;
    int found = 0;
    size_t rem;
    if (!attr || attr_len < sizeof(struct blob_attr))
        return 0;
    len = blob_raw_len(attr);
    if (attr_len < len)
        return 0;
    memset(data, 0, sizeof(struct blob_attr *) * max);
    blob_for_each_attr_len(pos, attr, len, rem) {
        found += blob_parse_attr(pos, rem, data, info, max);
    }
    return found;
}
References blob_for_each_attr_len, blob_parse_attr(), blob_raw_len(), blob_attr::data, and info.
Referenced by cert_load(), fuzz_blob_parse(), ubus_cli_monitor_cb(), and ubus_parse_msg().
blob_put()
struct blob_attr * blob_put (struct blob_buf * buf, int id, const void * ptr, unsigned int len) extern
Definition at line 161 of file blob.c.
{
    struct blob_attr *attr;
    attr = blob_new(buf, id, len);
    if (!attr)
        return NULL;
    if (ptr)
        memcpy(blob_data(attr), ptr, len);
    return attr;
}
References blob_data(), blob_new(), and buf.
Referenced by blob_put_string(), blob_put_u16(), blob_put_u32(), blob_put_u64(), blob_put_u8(), proto_shell_create_tunnel(), ubus_put_data(), ubusd_create_event_from_msg(), ubusd_forward_invoke(), and ubusd_monitor_message().
blob_put_raw()
struct blob_attr * blob_put_raw (struct blob_buf * buf, const void * ptr, unsigned int len) extern
Definition at line 145 of file blob.c.
{
    struct blob_attr *attr;
    if (len < sizeof(struct blob_attr) || !ptr)
        return NULL;
    attr = blob_add(buf, blob_next(buf->head), 0, len - sizeof(struct blob_attr));
    if (!attr)
        return NULL;
    blob_set_raw_len(buf->head, blob_pad_len(buf->head) + len);
    memcpy(attr, ptr, len);
    return attr;
}
References blob_add(), blob_next(), blob_pad_len(), blob_set_raw_len(), and buf.
Referenced by __vlan_hotplug_op(), __vlandev_hotplug_op(), and put_container().
blob_put_string()
static struct blob_attr * blob_put_string (struct blob_buf * buf, int id, const char * str) inline static
Definition at line 207 of file blob.h.
{
    return blob_put(buf, id, str, strlen(str) + 1);
}
References blob_put(), and buf.
Referenced by __ubus_notify_async(), ubus_add_object(), ubus_invoke_async_fd(), ubus_lookup(), ubus_lookup_id(), ubus_send_event(), ubusd_create_event_from_msg(), ubusd_create_object_event_msg(), ubusd_create_sequence_event_msg(), ubusd_forward_invoke(), and ubusd_send_obj().
blob_put_u16()
static struct blob_attr * blob_put_u16 (struct blob_buf * buf, int id, uint16_t val) inline static
Definition at line 219 of file blob.h.
{
    val = cpu_to_be16(val);
    return blob_put(buf, id, &val, sizeof(val));
}
References blob_put(), buf, and cpu_to_be16.
blob_put_u32()
static struct blob_attr * blob_put_u32 (struct blob_buf * buf, int id, uint32_t val) inline static
Definition at line 226 of file blob.h.
{
    val = cpu_to_be32(val);
    return blob_put(buf, id, &val, sizeof(val));
}
References blob_put(), buf, and cpu_to_be32.
blob_put_u64()
static struct blob_attr * blob_put_u64 (struct blob_buf * buf, int id, uint64_t val) inline static
Definition at line 233 of file blob.h.
{
    val = cpu_to_be64(val);
    return blob_put(buf, id, &val, sizeof(val));
}
References blob_put(), buf, and cpu_to_be64.
blob_put_u8()
static struct blob_attr * blob_put_u8 (struct blob_buf * buf, int id, uint8_t val) inline static
Definition at line 213 of file blob.h.
{
    return blob_put(buf, id, &val, sizeof(val));
}
References blob_put(), and buf.
blob_raw_len()
static size_t blob_raw_len (const struct blob_attr * attr) inline static
Definition at line 109 of file blob.h.
{
    return blob_len(attr) + sizeof(struct blob_attr);
}
References blob_len().
Referenced by avl_blobcmp(), blob_fill_pad(), blob_pad_len(), blob_parse_attr(), blob_parse_untrusted(), blobmsg_add_string_buffer(), blobmsg_alloc_string_buffer(), blobmsg_check_array(), blobmsg_check_attr(), blobmsg_check_attr_len(), client_cb(), get_next_msg(), req_data_cb(), ubus_add_object_cb(), ubus_cli_monitor_cb(), ubus_create_obj_method(), ubus_get_status(), ubus_lookup_cb(), ubus_lookup_id_cb(), ubus_msg_from_blob(), ubus_process_notify_status(), ubus_process_obj_msg(), ubus_process_req_data(), ubus_queue_msg(), ubus_reconnect(), ubus_remove_object_cb(), ubus_send_msg(), ubus_validate_hdr(), ubusd_acl_load_file(), ubusd_acl_recv(), ubusd_cmd_lookup(), ubusd_create_event_from_msg(), ubusd_create_object_event_msg(), ubusd_create_sequence_event_msg(), ubusd_monitor_message(), ubusd_proto_init_retmsg(), and ubusd_proto_receive_message().
blob_set_raw_len()
void blob_set_raw_len (struct blob_attr * attr, unsigned int len) extern
Definition at line 124 of file blob.c.
{
    len &= BLOB_ATTR_LEN_MASK;
    attr->id_len &= ~cpu_to_be32(BLOB_ATTR_LEN_MASK);
    attr->id_len |= cpu_to_be32(len);
}
References BLOB_ATTR_LEN_MASK, cpu_to_be32, and blob_attr::id_len.
Referenced by blob_nest_end(), blob_new(), blob_put_raw(), blobmsg_add_string_buffer(), blobmsg_alloc_string_buffer(), and blobmsg_open_nested().
Variable Documentation
__packed
struct blob_attr __packed