zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/ustp/config.h File Reference
config.h File Reference
#include <libubox/avl.h>
#include <stdint.h>
#include "mstp.h"
Classes
struct bridge_config
Functions
struct bridge_config * bridge_config_get (const char *name, bool create)
void bridge_config_expire (void)
Variables
struct avl_tree bridge_config
Class Documentation
bridge_config
struct bridge_config
Definition at line 119 of file system.h.
Class Members
int ageing_time
bool bridge_empty
CIST_BridgeConfig config
enum bridge_opt flags
int forward_delay
int hash_max
int hello_time
bool igmp_snoop
int last_member_interval
int max_age
bool multicast_querier
struct avl_node node
unsigned short priority
int query_interval
int query_response_interval
int robustness
bool stp
bool stp_kernel
const char * stp_proto
uint32_t timestamp
bool vlan_filtering
Function Documentation
bridge_config_expire()
void bridge_config_expire (void)
Definition at line 55 of file config.c.
{
    struct bridge_config *cfg, *tmp;
    uint32_t ts;
    ts = bridge_config_timestamp();
    avl_for_each_element_safe(&bridge_config, cfg, node, tmp) {
        if (ts - cfg->timestamp < 60)
            continue;
        avl_delete(&bridge_config, &cfg->node);
        free(cfg);
    }
}
References avl_delete(), avl_for_each_element_safe, bridge_config_timestamp(), bridge_config::node, and bridge_config::timestamp.
bridge_config_get()
struct bridge_config * bridge_config_get (const char * name, bool create)
Definition at line 33 of file config.c.
{
    struct bridge_config *cfg;
    char *name_buf;
    cfg = avl_find_element(&bridge_config, name, cfg, node);
    if (cfg)
        goto out;
    if (!create)
        return NULL;
    cfg = calloc_a(sizeof(*cfg), &name_buf, strlen(name) + 1);
    cfg->node.key = strcpy(name_buf, name);
    avl_insert(&bridge_config, &cfg->node);
out:
    cfg->timestamp = bridge_config_timestamp();
    return cfg;
}
References avl_find_element, avl_insert(), bridge_config_timestamp(), calloc_a, avl_node::key, bridge_config::node, and bridge_config::timestamp.
Referenced by ubus_bridge_state(), and ubus_set_bridge_config().
Variable Documentation
bridge_config
struct avl_tree bridge_config extern