zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/trace/preload.c File Reference
preload.c File Reference
#include <sys/ptrace.h>
#include <sys/types.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <dlfcn.h>
#include "../preload.h"
Macros
#define _GNU_SOURCE
#define ERROR(fmt, ...)
Functions
static int __preload_main__ (int argc, char **argv, char **envp)
int __libc_start_main (main_t main, int argc, char **argv, ElfW(auxv_t) *auxvec, __typeof(main) init, void(*fini)(void), void(*rtld_fini)(void), void *stack_end)
void __uClibc_main (main_t main, int argc, char **argv, void(*app_init)(void), void(*app_fini)(void), void(*rtld_fini)(void), void *stack_end attribute_unused)
Variables
static main_t __main__
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 14 of file preload.c.
ERROR
#define ERROR (fmt, ...)
Value:
    do { \
    fprintf(stderr,"perload-jail: "fmt, ## __VA_ARGS__); \
    } while (0)
Definition at line 26 of file preload.c.
#define ERROR(fmt, ...) do { \
    fprintf(stderr,"perload-jail: "fmt, ## __VA_ARGS__); \
    } while (0)
Function Documentation
__libc_start_main()
int __libc_start_main (main_t main, int argc, char ** argv, ElfW(auxv_t) * auxvec, __typeof(main) init, void(* fini)(void), void(* rtld_fini)(void), void * stack_end)
Definition at line 40 of file preload.c.
{
    start_main_t __start_main__;
    __start_main__ = dlsym(RTLD_NEXT, "__libc_start_main");
    if (!__start_main__) {
        ERROR("failed to find __libc_start_main %s\n", dlerror());
        return -1;
    }
    __main__ = main;
    return (*__start_main__)(__preload_main__, argc, argv, auxvec,
        init, fini, rtld_fini, stack_end);
}
References __main__, __preload_main__(), ERROR, and main().
__preload_main__()
static int __preload_main__ (int argc, char ** argv, char ** envp) static
Definition at line 32 of file preload.c.
{
    unsetenv("LD_PRELOAD");
    kill(getpid(), SIGSTOP);
    return (*__main__)(argc, argv, envp);
}
References __main__.
__uClibc_main()
void __uClibc_main (main_t main, int argc, char ** argv, void(* app_init)(void), void(* app_fini)(void), void(* rtld_fini)(void), void *stack_end attribute_unused)
Definition at line 62 of file preload.c.
{
    uClibc_main __start_main__;
    __start_main__ = dlsym(RTLD_NEXT, "__uClibc_main");
    if (!__start_main__) {
        ERROR("failed to find __uClibc_main %s\n", dlerror());
        return;
    }
    __main__ = main;
    return (*__start_main__)(__preload_main__, argc, argv,
        app_init, app_fini, rtld_fini, stack_end);
}
References __main__, __preload_main__(), ERROR, and main().
Variable Documentation
__main__
main_t __main__ static
Definition at line 30 of file preload.c.