zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/plug/hotplug.c File Reference
hotplug.c File Reference
#include <sys/stat.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <sys/sysmacros.h>
#include <linux/types.h>
#include <linux/netlink.h>
#include <libubox/blobmsg_json.h>
#include <libubox/json_script.h>
#include <libubox/uloop.h>
#include <libubox/utils.h>
#include <json-c/json.h>
#include <errno.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdlib.h>
#include <libgen.h>
#include <grp.h>
#include "../procd.h"
#include "hotplug.h"
Classes
struct cmd_queue
struct button_timeout
struct cmd_handler
Macros
#define HOTPLUG_WAIT 500
Enumerations
enum {
HANDLER_MKDEV = 0 , HANDLER_RM , HANDLER_EXEC , HANDLER_BUTTON ,
HANDLER_FW , HANDLER_START_CONSOLE
}
Functions
static LIST_HEAD (cmd_queue)
static LIST_HEAD (button_timer)
static void queue_add (struct cmd_handler *h, struct blob_attr *msg, struct blob_attr *data)
static void handle_button_complete (struct blob_attr *msg, struct blob_attr *data, int ret)
static void button_free (struct button_timeout *b)
static void button_timeout_remove (char *button)
static char * hotplug_msg_find_var (struct blob_attr *msg, const char *name)
static void chgrp_error (const char *group, const char *target, const char *failed)
static void chgrp_target (struct blob_attr *bgroup, struct blob_attr *btarget)
static void handle_makedev (struct blob_attr *msg, struct blob_attr *data)
static void handle_rm (struct blob_attr *msg, struct blob_attr *data)
static void handle_exec (struct blob_attr *msg, struct blob_attr *data)
static void handle_button_start (struct blob_attr *msg, struct blob_attr *data)
static void handle_firmware (struct blob_attr *msg, struct blob_attr *data)
static void handle_start_console (struct blob_attr *msg, struct blob_attr *data)
static void queue_next (void)
static void queue_proc_cb (struct uloop_process *c, int ret)
static void handle_button_timeout (struct uloop_timeout *t)
static const char * rule_handle_var (struct json_script_ctx *ctx, const char *name, struct blob_attr *vars)
static struct json_script_file * rule_handle_file (struct json_script_ctx *ctx, const char *name)
static void rule_handle_command (struct json_script_ctx *ctx, const char *name, struct blob_attr *data, struct blob_attr *vars)
static void rule_handle_error (struct json_script_ctx *ctx, const char *msg, struct blob_attr *context)
static void hotplug_handler_debug (struct blob_attr *data)
static void hotplug_handler (struct uloop_fd *u, unsigned int ev)
void hotplug_last_event (uloop_timeout_handler handler)
void hotplug (char *rules)
int hotplug_run (char *rules)
void hotplug_shutdown (void)
Variables
static struct uloop_process queue_proc
static struct uloop_timeout last_event
static struct blob_buf b button_buf
static char * rule_file
static struct blob_buf script
static struct cmd_queue * current
static struct cmd_handler handlers []
static struct json_script_ctx jctx
static struct uloop_fd hotplug_fd
Class Documentation
cmd_queue
struct cmd_queue
Definition at line 43 of file hotplug.c.
Class Members
void(*)(struct blob_attr *msg, struct blob_attr *data, int ret) complete
struct blob_attr * data
void(*)(struct blob_attr *msg, struct blob_attr *data) handler
struct list_head list
struct blob_attr * msg
void(*)(struct blob_attr *msg, struct blob_attr *data) start
int timeout
button_timeout
struct button_timeout
Definition at line 55 of file hotplug.c.
Class Members
struct blob_attr * data
struct list_head list
char * name
int seen
struct uloop_timeout timeout
cmd_handler
struct cmd_handler
Definition at line 327 of file hotplug.c.
Class Members
int atomic
void(*)(struct blob_attr *msg, struct blob_attr *data, int ret) complete
void(*)(struct blob_attr *msg, struct blob_attr *data) handler
char * name
void(*)(struct blob_attr *msg, struct blob_attr *data) start
Macro Definition Documentation
HOTPLUG_WAIT
#define HOTPLUG_WAIT 500
Definition at line 40 of file hotplug.c.
Referenced by hotplug_last_event(), and rule_handle_command().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
HANDLER_MKDEV 0
HANDLER_RM
HANDLER_EXEC
HANDLER_BUTTON
HANDLER_FW
HANDLER_START_CONSOLE
Definition at line 318 of file hotplug.c.
     {
    HANDLER_MKDEV = 0,
    HANDLER_RM,
    HANDLER_EXEC,
    HANDLER_BUTTON,
    HANDLER_FW,
    HANDLER_START_CONSOLE,
};
Function Documentation
button_free()
static void button_free (struct button_timeout * b) static
Definition at line 75 of file hotplug.c.
{
    uloop_timeout_cancel(&b->timeout);
    list_del(&b->list);
    free(b->data);
    free(b->name);
    free(b);
}
References b, list_del(), and uloop_timeout_cancel().
Referenced by button_timeout_remove(), and handle_button_timeout().
button_timeout_remove()
static void button_timeout_remove (char * button) static
Definition at line 84 of file hotplug.c.
{
    struct button_timeout *b, *c;
    if (!list_empty(&button_timer)) list_for_each_entry_safe(b, c, &button_timer, list) {
        if (!strcmp(b->name, button))
            button_free(b);
    }
}
References b, button_free(), button_timeout::list, list_empty(), and list_for_each_entry_safe.
Referenced by handle_button_start().
chgrp_error()
static void chgrp_error (const char * group, const char * target, const char * failed) static
Definition at line 112 of file hotplug.c.
{
    ERROR("cannot set group %s for %s (%s: %d)\n",
           group, target, failed, errno);
}
References ERROR.
Referenced by chgrp_target().
chgrp_target()
static void chgrp_target (struct blob_attr * bgroup, struct blob_attr * btarget) static
Definition at line 118 of file hotplug.c.
{
    int ret = 0;
    struct group *g = NULL;
    const char *group = blobmsg_get_string(bgroup);
    const char *target = blobmsg_get_string(btarget);
    errno = 0;
    g = getgrnam(group);
    if (!g)
        return chgrp_error(group, target, "getgrnam");
    ret = chown(target, 0, g->gr_gid);
    if (ret < 0)
        return chgrp_error(group, target, "chown");
}
References blobmsg_get_string(), and chgrp_error().
Referenced by handle_makedev().
handle_button_complete()
static void handle_button_complete (struct blob_attr * msg, struct blob_attr * data, int ret) static
Definition at line 448 of file hotplug.c.
{
    char *name = hotplug_msg_find_var(msg, "BUTTON");
    struct button_timeout *b;
    int timeout = ret >> 8;
    if (!timeout)
        return;
    if (!name)
        return;
    b = calloc(1, sizeof(*b));
    if (!b)
        return;
    b->data = malloc(blob_pad_len(data));
    b->name = strdup(name);
    b->seen = timeout;
    memcpy(b->data, data, blob_pad_len(data));
    b->timeout.cb = handle_button_timeout;
    uloop_timeout_set(&b->timeout, timeout * 1000);
    list_add(&b->list, &button_timer);
}
References b, blob_pad_len(), button_timeout::data, handle_button_timeout(), hotplug_msg_find_var(), list_add(), button_timeout::name, timeout, and uloop_timeout_set().
handle_button_start()
static void handle_button_start (struct blob_attr * msg, struct blob_attr * data) static
Definition at line 216 of file hotplug.c.
{
    char *button = hotplug_msg_find_var(msg, "BUTTON");
    if (button)
        button_timeout_remove(button);
}
References button_timeout_remove(), and hotplug_msg_find_var().
handle_button_timeout()
static void handle_button_timeout (struct uloop_timeout * t) static
Definition at line 433 of file hotplug.c.
{
    struct button_timeout *b;
    char seen[16];
    b = container_of(t, struct button_timeout, timeout);
    blob_buf_init(&button_buf, 0);
    blobmsg_add_string(&button_buf, "BUTTON", b->name);
    blobmsg_add_string(&button_buf, "ACTION", "timeout");
    snprintf(seen, sizeof(seen), "%d", b->seen);
    blobmsg_add_string(&button_buf, "SEEN", seen);
    queue_add(&handlers[HANDLER_EXEC], button_buf.head, b->data);
    button_free(b);
}
References b, blob_buf_init(), blobmsg_add_string(), button_buf, button_free(), container_of, HANDLER_EXEC, handlers, blob_buf::head, queue_add(), button_timeout::seen, and timeout.
Referenced by handle_button_complete().
handle_exec()
static void handle_exec (struct blob_attr * msg, struct blob_attr * data) static
Definition at line 181 of file hotplug.c.
{
    char *argv[8];
    struct blob_attr *cur;
    int rem, fd;
    int i = 0;
    blobmsg_for_each_attr(cur, msg, rem)
        setenv(blobmsg_name(cur), blobmsg_data(cur), 1);
    blobmsg_for_each_attr(cur, data, rem) {
        argv[i] = blobmsg_data(cur);
        i++;
        if (i == 7)
            break;
    }
    if (debug < 3) {
        fd = open("/dev/null", O_RDWR);
        if (fd > -1) {
            dup2(fd, STDIN_FILENO);
            dup2(fd, STDOUT_FILENO);
            dup2(fd, STDERR_FILENO);
            if (fd > STDERR_FILENO)
                close(fd);
        }
    }
    if (i > 0) {
        argv[i] = NULL;
        execvp(argv[0], &argv[0]);
    }
    exit(EXIT_FAILURE);
}
References blobmsg_data(), blobmsg_for_each_attr, blobmsg_name(), blob_attr::data, and debug.
handle_firmware()
static void handle_firmware (struct blob_attr * msg, struct blob_attr * data) static
Definition at line 224 of file hotplug.c.
{
    char *dir = blobmsg_get_string(blobmsg_data(data));
    char *file = hotplug_msg_find_var(msg, "FIRMWARE");
    char *dev = hotplug_msg_find_var(msg, "DEVPATH");
    struct stat s = { 0 };
    char *path, loadpath[256], syspath[256];
    int fw, src, load, len;
    static char buf[4096];
    P_DEBUG(2, "Firmware request for %s/%s\n", dir, file);
    if (!file || !dir || !dev) {
        ERROR("Request for unknown firmware %s/%s\n", dir, file);
        exit(EXIT_FAILURE);
    }
    path = alloca(strlen(dir) + strlen(file) + 2);
    sprintf(path, "%s/%s", dir, file);
    if (stat(path, &s)) {
        ERROR("Could not find firmware %s: %m\n", path);
        src = -1;
        s.st_size = 0;
        goto send_to_kernel;
    }
    src = open(path, O_RDONLY);
    if (src < 0) {
        ERROR("Failed to open %s: %m\n", path);
        s.st_size = 0;
        goto send_to_kernel;
    }
send_to_kernel:
    snprintf(loadpath, sizeof(loadpath), "/sys/%s/loading", dev);
    load = open(loadpath, O_WRONLY);
    if (!load) {
        ERROR("Failed to open %s: %m\n", loadpath);
        exit(EXIT_FAILURE);
    }
    if (write(load, "1", 1) == -1) {
        ERROR("Failed to write to %s: %m\n", loadpath);
        exit(EXIT_FAILURE);
    }
    close(load);
    snprintf(syspath, sizeof(syspath), "/sys/%s/data", dev);
    fw = open(syspath, O_WRONLY);
    if (fw < 0) {
        ERROR("Failed to open %s: %m\n", syspath);
        exit(EXIT_FAILURE);
    }
    len = s.st_size;
    while (len) {
        len = read(src, buf, sizeof(buf));
        if (len <= 0)
            break;
        if (write(fw, buf, len) == -1) {
            ERROR("failed to write firmware file %s/%s to %s: %m\n", dir, file, dev);
            break;
        }
    }
    if (src >= 0)
        close(src);
    close(fw);
    load = open(loadpath, O_WRONLY);
    if (write(load, "0", 1) == -1)
        ERROR("failed to write to %s: %m\n", loadpath);
    close(load);
    P_DEBUG(2, "Done loading %s\n", path);
    exit(EXIT_FAILURE);
}
References blobmsg_data(), blobmsg_get_string(), buf, blob_attr::data, ERROR, hotplug_msg_find_var(), P_DEBUG, and path.
handle_makedev()
static void handle_makedev (struct blob_attr * msg, struct blob_attr * data) static
Definition at line 136 of file hotplug.c.
{
    unsigned int oldumask = umask(0);
    static struct blobmsg_policy mkdev_policy[3] = {
        { .type = BLOBMSG_TYPE_STRING },
        { .type = BLOBMSG_TYPE_STRING },
        { .type = BLOBMSG_TYPE_STRING },
    };
    struct blob_attr *tb[3];
    char *minor = hotplug_msg_find_var(msg, "MINOR");
    char *major = hotplug_msg_find_var(msg, "MAJOR");
    char *subsystem = hotplug_msg_find_var(msg, "SUBSYSTEM");
    blobmsg_parse_array(mkdev_policy, 3, tb, blobmsg_data(data), blobmsg_data_len(data));
    if (tb[0] && tb[1] && minor && major && subsystem) {
        mode_t m = S_IFCHR;
        char *d = strdup(blobmsg_get_string(tb[0]));
        d = dirname(d);
        mkdir_p(d, 0755);
        free(d);
        if (!strcmp(subsystem, "block"))
            m = S_IFBLK;
        mknod(blobmsg_get_string(tb[0]),
                m | strtoul(blobmsg_data(tb[1]), NULL, 8),
                makedev(atoi(major), atoi(minor)));
        if (tb[2])
            chgrp_target(tb[2], tb[0]);
    }
    umask(oldumask);
}
References blobmsg_data(), blobmsg_data_len(), blobmsg_get_string(), blobmsg_parse_array(), BLOBMSG_TYPE_STRING, chgrp_target(), blob_attr::data, hotplug_msg_find_var(), makedev, and mkdir_p().
handle_rm()
static void handle_rm (struct blob_attr * msg, struct blob_attr * data) static
Definition at line 169 of file hotplug.c.
{
    static struct blobmsg_policy rm_policy = {
        .type = BLOBMSG_TYPE_STRING,
    };
    struct blob_attr *tb;
    blobmsg_parse_array(&rm_policy, 1, &tb, blobmsg_data(data), blobmsg_data_len(data));
    if (tb)
        unlink(blobmsg_data(tb));
}
References blobmsg_data(), blobmsg_data_len(), blobmsg_parse_array(), BLOBMSG_TYPE_STRING, and blob_attr::data.
handle_start_console()
static void handle_start_console (struct blob_attr * msg, struct blob_attr * data) static
Definition at line 304 of file hotplug.c.
{
    char *dev = blobmsg_get_string(blobmsg_data(data));
    P_DEBUG(2, "Start console request for %s\n", dev);
    procd_inittab_run("respawn");
    procd_inittab_run("askfirst");
    P_DEBUG(2, "Done starting console for %s\n", dev);
    exit(EXIT_FAILURE);
}
References blobmsg_data(), blobmsg_get_string(), P_DEBUG, and procd_inittab_run().
hotplug()
void hotplug (char * rules)
Definition at line 608 of file hotplug.c.
{
    struct sockaddr_nl nls = {};
    int nlbufsize = 512 * 1024;
    rule_file = strdup(rules);
    nls.nl_family = AF_NETLINK;
    nls.nl_pid = 0;
    nls.nl_groups = -1;
    if ((hotplug_fd.fd = socket(PF_NETLINK, SOCK_DGRAM | SOCK_CLOEXEC, NETLINK_KOBJECT_UEVENT)) == -1) {
        ERROR("Failed to open hotplug socket: %m\n");
        exit(1);
    }
    if (bind(hotplug_fd.fd, (void *)&nls, sizeof(struct sockaddr_nl))) {
        ERROR("Failed to bind hotplug socket: %m\n");
        exit(1);
    }
    if (setsockopt(hotplug_fd.fd, SOL_SOCKET, SO_RCVBUFFORCE, &nlbufsize, sizeof(nlbufsize)))
        ERROR("Failed to resize receive buffer: %m\n");
    json_script_init(&jctx);
    queue_proc.cb = queue_proc_cb;
    uloop_fd_add(&hotplug_fd, ULOOP_READ);
}
References uloop_process::cb, ERROR, uloop_fd::fd, hotplug_fd, jctx, json_script_init(), queue_proc, queue_proc_cb(), rule_file, uloop_fd_add(), and ULOOP_READ.
Referenced by bonding_create_port(), bridge_alloc_member(), bridge_create_member(), bridge_insert_member(), hotplug_run(), and state_enter().
hotplug_handler()
static void hotplug_handler (struct uloop_fd * u, unsigned int ev) static
Definition at line 567 of file hotplug.c.
{
    int i = 0;
    static char buf[4096];
    int len = recv(u->fd, buf, sizeof(buf) - 1, MSG_DONTWAIT);
    void *index;
    if (len < 1)
        return;
    buf[len] = '\0';
    blob_buf_init(&b, 0);
    index = blobmsg_open_table(&b, NULL);
    while (i < len) {
        int l = strlen(buf + i) + 1;
        char *e = strstr(&buf[i], "=");
        if (e) {
            *e = '\0';
            blobmsg_add_string(&b, &buf[i], &e[1]);
        }
        i += l;
    }
    blobmsg_close_table(&b, index);
    hotplug_handler_debug(b.head);
    json_script_run(&jctx, rule_file, blob_data(b.head));
}
References b, blob_buf_init(), blob_data(), blobmsg_add_string(), blobmsg_close_table(), blobmsg_open_table(), buf, uloop_fd::fd, blob_buf::head, hotplug_handler_debug(), jctx, json_script_run(), and rule_file.
hotplug_handler_debug()
static void hotplug_handler_debug (struct blob_attr * data) static
Definition at line 555 of file hotplug.c.
{
    char *str;
    if (debug < 3)
        return;
    str = blobmsg_format_json(data, true);
    P_DEBUG(3, "%s\n", str);
    free(str);
}
References blobmsg_format_json(), debug, and P_DEBUG.
Referenced by hotplug_handler().
hotplug_last_event()
void hotplug_last_event (uloop_timeout_handler handler)
Definition at line 599 of file hotplug.c.
{
    last_event.cb = handler;
    if (handler)
        uloop_timeout_set(&last_event, HOTPLUG_WAIT);
    else
        uloop_timeout_cancel(&last_event);
}
References uloop_timeout::cb, HOTPLUG_WAIT, last_event, uloop_timeout_cancel(), and uloop_timeout_set().
Referenced by coldplug_complete(), and udevtrigger_complete().
hotplug_msg_find_var()
static char * hotplug_msg_find_var (struct blob_attr * msg, const char * name) static
Definition at line 94 of file hotplug.c.
{
    struct blob_attr *cur;
    int rem;
    blobmsg_for_each_attr(cur, msg, rem) {
        if (blobmsg_type(cur) != BLOBMSG_TYPE_STRING)
            continue;
        if (strcmp(blobmsg_name(cur), name) != 0)
            continue;
        return blobmsg_data(cur);
    }
    return NULL;
}
References blobmsg_data(), blobmsg_for_each_attr, blobmsg_name(), and BLOBMSG_TYPE_STRING.
Referenced by handle_button_complete(), handle_button_start(), handle_firmware(), and handle_makedev().
hotplug_run()
int hotplug_run (char * rules)
Definition at line 635 of file hotplug.c.
{
    uloop_init();
    hotplug(rules);
    uloop_run();
    return 0;
}
References hotplug(), uloop_init(), and uloop_run().
Referenced by main().
hotplug_shutdown()
void hotplug_shutdown (void)
Definition at line 644 of file hotplug.c.
{
    uloop_fd_delete(&hotplug_fd);
    close(hotplug_fd.fd);
}
References uloop_fd::fd, hotplug_fd, and uloop_fd_delete().
LIST_HEAD() [1/2]
static LIST_HEAD (button_timer) static
LIST_HEAD() [2/2]
static LIST_HEAD (cmd_queue) static
queue_add()
static void queue_add (struct cmd_handler * h, struct blob_attr * msg, struct blob_attr * data) static
Definition at line 408 of file hotplug.c.
{
    struct cmd_queue *c = NULL;
    struct blob_attr *_msg, *_data;
    c = calloc_a(sizeof(struct cmd_queue),
        &_msg, blob_pad_len(msg),
        &_data, blob_pad_len(data),
        NULL);
    if (!c)
        return;
    c->msg = _msg;
    c->data = _data;
    memcpy(c->msg, msg, blob_pad_len(msg));
    memcpy(c->data, data, blob_pad_len(data));
    c->handler = h->handler;
    c->complete = h->complete;
    c->start = h->start;
    list_add_tail(&c->list, &cmd_queue);
    queue_next();
}
References blob_pad_len(), calloc_a, cmd_handler::complete, cmd_queue::complete, blob_attr::data, cmd_queue::data, cmd_handler::handler, cmd_queue::handler, cmd_queue::list, list_add_tail(), cmd_queue::msg, queue_next(), cmd_handler::start, and cmd_queue::start.
Referenced by handle_button_timeout(), and rule_handle_command().
queue_next()
static void queue_next (void) static
Definition at line 364 of file hotplug.c.
{
    struct cmd_queue *c;
    if (queue_proc.pending || list_empty(&cmd_queue))
        return;
    c = list_first_entry(&cmd_queue, struct cmd_queue, list);
    queue_proc.pid = fork();
    if (!queue_proc.pid) {
        uloop_done();
        c->handler(c->msg, c->data);
        exit(0);
    }
    if (c->start)
        c->start(c->msg, c->data);
    list_del(&c->list);
    if (c->complete)
        current = c;
    else
        free(c);
    if (queue_proc.pid <= 0) {
        queue_next();
        return;
    }
    uloop_process_add(&queue_proc);
    P_DEBUG(4, "Launched hotplug exec instance, pid=%d\n", (int) queue_proc.pid);
}
References cmd_queue::complete, current, cmd_queue::data, cmd_queue::handler, cmd_queue::list, list_del(), list_empty(), list_first_entry, cmd_queue::msg, P_DEBUG, uloop_process::pending, uloop_process::pid, queue_next(), queue_proc, cmd_queue::start, uloop_done(), and uloop_process_add().
Referenced by queue_add(), queue_next(), and queue_proc_cb().
queue_proc_cb()
static void queue_proc_cb (struct uloop_process * c, int ret) static
Definition at line 396 of file hotplug.c.
{
    P_DEBUG(4, "Finished hotplug exec instance, pid=%d\n", (int) c->pid);
    if (current) {
        current->complete(current->msg, current->data, ret);
        free(current);
        current = NULL;
    }
    queue_next();
}
References cmd_queue::complete, current, cmd_queue::data, cmd_queue::msg, P_DEBUG, uloop_process::pid, and queue_next().
Referenced by hotplug().
rule_handle_command()
static void rule_handle_command (struct json_script_ctx * ctx, const char * name, struct blob_attr * data, struct blob_attr * vars) static
Definition at line 509 of file hotplug.c.
{
    struct blob_attr *cur;
    int rem, i;
    if (debug > 3) {
        P_DEBUG(4, "Command: %s\n", name);
        blobmsg_for_each_attr(cur, data, rem)
            P_DEBUG(4, " %s\n", (char *) blobmsg_data(cur));
        P_DEBUG(4, "Message:\n");
        blobmsg_for_each_attr(cur, vars, rem)
            P_DEBUG(4, " %s=%s\n", blobmsg_name(cur), (char *) blobmsg_data(cur));
    }
    for (i = 0; i < ARRAY_SIZE(handlers); i++)
        if (!strcmp(handlers[i].name, name)) {
            if (handlers[i].atomic)
                handlers[i].handler(vars, data);
            else
                queue_add(&handlers[i], vars, data);
            break;
        }
    if (last_event.cb)
        uloop_timeout_set(&last_event, HOTPLUG_WAIT);
}
References ARRAY_SIZE, blobmsg_data(), blobmsg_for_each_attr, blobmsg_name(), uloop_timeout::cb, blob_attr::data, debug, cmd_handler::handler, handlers, HOTPLUG_WAIT, last_event, P_DEBUG, queue_add(), and uloop_timeout_set().
rule_handle_error()
static void rule_handle_error (struct json_script_ctx * ctx, const char * msg, struct blob_attr * context) static
Definition at line 538 of file hotplug.c.
{
    char *s;
    s = blobmsg_format_json(context, false);
    ERROR("ERROR: %s in block: %s\n", msg, s);
    free(s);
}
References blobmsg_format_json(), and ERROR.
rule_handle_file()
static struct json_script_file * rule_handle_file (struct json_script_ctx * ctx, const char * name) static
Definition at line 495 of file hotplug.c.
{
    json_object *obj;
    obj = json_object_from_file((char*)name);
    if (!obj)
        return NULL;
    blob_buf_init(&script, 0);
    blobmsg_add_json_element(&script, "", obj);
    return json_script_file_from_blobmsg(name, blob_data(script.head), blob_len(script.head));
}
References blob_buf_init(), blob_data(), blob_len(), blobmsg_add_json_element(), blob_buf::head, json_script_file_from_blobmsg(), and script.
rule_handle_var()
static const char * rule_handle_var (struct json_script_ctx * ctx, const char * name, struct blob_attr * vars) static
Definition at line 475 of file hotplug.c.
{
    const char *str, *sep;
    if (!strcmp(name, "DEVICENAME") || !strcmp(name, "DEVNAME")) {
        str = json_script_find_var(ctx, vars, "DEVPATH");
        if (!str)
            return NULL;
        sep = strrchr(str, '/');
        if (sep)
            return sep + 1;
        return str;
    }
    return NULL;
}
References ctx, json_script_find_var(), and button_timeout::name.
Variable Documentation
button_buf
struct blob_buf b button_buf static
Definition at line 67 of file hotplug.c.
Referenced by handle_button_timeout().
current
struct cmd_queue* current static
Definition at line 70 of file hotplug.c.
Referenced by queue_next(), and queue_proc_cb().
handlers
struct cmd_handler handlers[] static
Initial value:
= {
    [HANDLER_MKDEV] = {
        .name = "makedev",
        .atomic = 1,
        .handler = handle_makedev,
    },
    [HANDLER_RM] = {
        .name = "rm",
        .atomic = 1,
        .handler = handle_rm,
    },
    [HANDLER_EXEC] = {
        .name = "exec",
        .handler = handle_exec,
    },
    [HANDLER_BUTTON] = {
        .name = "button",
        .handler = handle_exec,
        .start = handle_button_start,
        .complete = handle_button_complete,
    },
    [HANDLER_FW] = {
        .name = "load-firmware",
        .handler = handle_firmware,
    },
    [HANDLER_START_CONSOLE] = {
        .name = "start-console",
        .handler = handle_start_console,
    },
}
Referenced by handle_button_timeout(), and rule_handle_command().
hotplug_fd
struct uloop_fd hotplug_fd static
Initial value:
= {
    .cb = hotplug_handler,
}
Definition at line 595 of file hotplug.c.
{
    .cb = hotplug_handler,
};
Referenced by hotplug(), and hotplug_shutdown().
jctx
struct json_script_ctx jctx static
Initial value:
= {
    .handle_var = rule_handle_var,
    .handle_error = rule_handle_error,
    .handle_command = rule_handle_command,
    .handle_file = rule_handle_file,
}
Definition at line 548 of file hotplug.c.
{
    .handle_var = rule_handle_var,
    .handle_error = rule_handle_error,
    .handle_command = rule_handle_command,
    .handle_file = rule_handle_file,
};
Referenced by hotplug(), and hotplug_handler().
last_event
struct uloop_timeout last_event static
Definition at line 66 of file hotplug.c.
Referenced by hotplug_last_event(), and rule_handle_command().
queue_proc
struct uloop_process queue_proc static
Definition at line 65 of file hotplug.c.
Referenced by hotplug(), and queue_next().
rule_file
char* rule_file static
Definition at line 68 of file hotplug.c.
Referenced by hotplug(), and hotplug_handler().
script
struct blob_buf script static
Definition at line 69 of file hotplug.c.
Referenced by hotplug_exec(), netifd_init_script_handler(), proto_shell_add_handler(), rpc_ucode_init_globals(), rpc_ucode_init_script(), rpc_ucode_request_finish(), rpc_ucode_script_call(), rpc_ucode_script_execute(), rpc_ucode_script_register(), rpc_ucode_script_validate(), rpc_ucode_validate_call_args(), rule_handle_file(), trigger_add(), and wireless_add_handler().