zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/netifd/netifd.h File Reference
netifd.h File Reference
#include <sys/socket.h>
#include <net/if.h>
#include <stdbool.h>
#include <stdio.h>
#include <libubox/uloop.h>
#include <libubox/ustream.h>
#include <libubox/utils.h>
#include <libubus.h>
#include <udebug.h>
#include <net/ethernet.h>
#include "utils.h"
Classes
struct netifd_process
Macros
#define DEFAULT_MAIN_PATH "/lib/netifd"
#define DEFAULT_CONFIG_PATH NULL /* use the default set in libuci */
#define DEFAULT_HOTPLUG_PATH "/sbin/hotplug-call"
#define DEFAULT_RESOLV_CONF "/tmp/resolv.conf.d/resolv.conf.auto"
#define DEFAULT_BOARD_JSON "/etc/board.json"
#define DPRINTF(format, ...)
#define D(level, format, ...)
#define LOG_BUF_SIZE 256
Enumerations
enum {
L_CRIT , L_WARNING , L_NOTICE , L_INFO ,
L_DEBUG
}
enum { DEBUG_SYSTEM = 0 , DEBUG_DEVICE = 1 , DEBUG_INTERFACE = 2 , DEBUG_WIRELESS = 3 }
Functions
static void no_debug (int level, const char *fmt,...)
void netifd_udebug_printf (const char *format,...)
void netifd_udebug_config (struct udebug_ubus *ctx, struct blob_attr *data, bool enabled)
void netifd_log_message (int priority, const char *format,...)
int netifd_start_process (const char **argv, char **env, struct netifd_process *proc)
void netifd_kill_process (struct netifd_process *proc)
void netifd_restart (void)
int netifd_reload (void)
Variables
const char * resolv_conf
char * hotplug_cmd_path
unsigned int debug_mask
struct udebug_buf udb_nl
const char * main_path
const char * config_path
Class Documentation
netifd_process
struct netifd_process
Definition at line 92 of file netifd.h.
Class Members
void(*)(struct netifd_process *, int ret) cb
int dir_fd
struct list_head list
struct ustream_fd log
bool log_overflow
const char * log_prefix
struct uloop_process uloop
Macro Definition Documentation
D
#define D (level, format, ...)
Value:
no_debug(DEBUG_ ## level, format, ## __VA_ARGS__)
Definition at line 83 of file netifd.h.
Referenced by __bridge_reload(), __device_add_user(), _device_set_present(), bonding_enable_port(), bridge_enable_member(), bridge_reload(), call_hotplug(), cb_clear_event(), config_init_procd_wireless_interface(), config_init_wireless(), config_parse_bridge_interface(), device_apply_config(), device_claim(), device_cleanup(), device_create(), device_create_default(), device_delete(), device_init_settings(), device_init_virtual(), device_refresh_present(), device_release(), device_remove_user(), extdev_bridge_add_member(), extdev_bridge_disable_member(), extdev_bridge_enable_member(), extdev_bridge_retry_enable_members(), extdev_bridge_set_down(), extdev_bridge_set_up(), extdev_hotplug_add(), get_vlan_device(), interface_add_dns_search_domain(), interface_add_dns_server(), interface_alloc(), interface_change_config(), interface_ip_add_route(), interface_queue_event(), interface_set_available(), interface_update(), interface_write_resolv_conf(), iprule_add(), macvlan_set_state(), netifd_extdev_add(), netifd_extdev_create(), netifd_extdev_free(), netifd_extdev_prepare(), netifd_extdev_reload(), netifd_extdev_remove(), netifd_ubus_add_interface(), netifd_ubus_init(), netifd_ubus_reconnect_timer(), proto_shell_add_handler(), proto_shell_checkup_timeout_cb(), proto_shell_handler(), proto_shell_parse_neighbor_list(), proto_shell_parse_route_list(), station_update(), system_add_vxlan(), system_address_msg(), system_bridge_addbr(), system_bridge_addif(), system_bridge_delbr(), system_bridge_delif(), system_bridge_vlan(), system_if_apply_settings(), system_if_clear_state(), system_if_down(), system_if_up(), system_link_netns_move(), system_macvlan_add(), system_neighbor_msg(), system_netns_open(), system_netns_set(), system_route_msg(), system_veth_add(), system_vlan_add(), system_vlan_del(), system_vlandev_add(), task_complete(), veth_set_state(), vif_update(), vlan_update(), vlandev_set_state(), wdev_change_config(), wdev_update(), wireless_add_handler(), wireless_device_add_process(), wireless_device_check_script_tasks(), wireless_device_run_handler(), wireless_device_setup_cancel(), wireless_process_free(), and wireless_process_kill_all().
DEFAULT_BOARD_JSON
#define DEFAULT_BOARD_JSON "/etc/board.json"
Definition at line 49 of file netifd.h.
Referenced by config_init_board().
DEFAULT_CONFIG_PATH
#define DEFAULT_CONFIG_PATH NULL /* use the default set in libuci */
Definition at line 46 of file netifd.h.
DEFAULT_HOTPLUG_PATH
#define DEFAULT_HOTPLUG_PATH "/sbin/hotplug-call"
Definition at line 47 of file netifd.h.
Referenced by usage().
DEFAULT_MAIN_PATH
#define DEFAULT_MAIN_PATH "/lib/netifd"
Definition at line 45 of file netifd.h.
DEFAULT_RESOLV_CONF
#define DEFAULT_RESOLV_CONF "/tmp/resolv.conf.d/resolv.conf.auto"
Definition at line 48 of file netifd.h.
Referenced by interface_write_resolv_conf().
DPRINTF
#define DPRINTF (format, ...)
Value:
no_debug(0, format, ## __VA_ARGS__)
Definition at line 82 of file netifd.h.
LOG_BUF_SIZE
#define LOG_BUF_SIZE 256
Definition at line 86 of file netifd.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
L_CRIT
L_WARNING
L_NOTICE
L_INFO
L_DEBUG
Definition at line 57 of file netifd.h.
     {
    L_CRIT,
    L_WARNING,
    L_NOTICE,
    L_INFO,
    L_DEBUG
};
anonymous enum
anonymous enum
Enumerator
DEBUG_SYSTEM 0
DEBUG_DEVICE 1
DEBUG_INTERFACE 2
DEBUG_WIRELESS 3
Definition at line 65 of file netifd.h.
     {
    DEBUG_SYSTEM    = 0,
    DEBUG_DEVICE    = 1,
    DEBUG_INTERFACE = 2,
    DEBUG_WIRELESS  = 3,
};
Function Documentation
netifd_kill_process()
void netifd_kill_process (struct netifd_process * proc)
Definition at line 255 of file main.c.
{
    if (!proc->uloop.pending)
        return;
    kill(proc->uloop.pid, SIGKILL);
    uloop_process_delete(&proc->uloop);
    netifd_delete_process(proc);
}
References netifd_delete_process(), uloop_process::pending, uloop_process::pid, netifd_process::uloop, and uloop_process_delete().
Referenced by netifd_kill_processes(), netifd_start_process(), proto_shell_free(), proto_shell_teardown_timeout_cb(), and wireless_device_setup_timeout().
netifd_log_message()
void netifd_log_message (int priority, const char * format, ...)
Referenced by __create(), __do_bridge_reload(), __interface_set_up(), config_init_all(), device_init_virtual(), device_set_ifname(), device_set_link(), device_type_add(), extdev_bridge_member_cb(), extdev_ext_handler_remove_cb(), extdev_invocation_error(), extdev_lookup_id(), extdev_subscribe(), interface_alloc(), interface_proto_event_cb(), interface_set_enabled(), interface_set_link_state(), interface_set_prefix_address(), interface_update_prefix_assignments(), netifd_init_extdev_handler(), netifd_process_log_read_cb(), system_if_apply_settings(), system_set_ethtool_eee_settings(), system_vlandev_add(), wireless_device_mark_down(), wireless_device_mark_up(), wireless_device_retry_setup(), and wireless_device_set_retry().
netifd_reload()
int netifd_reload (void)
Definition at line 270 of file main.c.
{
    return config_init_all();
}
References config_init_all().
Referenced by netifd_handle_reload().
netifd_restart()
void netifd_restart (void)
Definition at line 275 of file main.c.
{
    static struct uloop_timeout main_timer = {
        .cb = netifd_do_restart
    };
    interface_set_down(NULL);
    uloop_timeout_set(&main_timer, 1000);
}
References interface_set_down(), netifd_do_restart(), and uloop_timeout_set().
Referenced by netifd_handle_restart().
netifd_start_process()
int netifd_start_process (const char ** argv, char ** env, struct netifd_process * proc)
Definition at line 194 of file main.c.
{
    int pfds[2];
    int pid;
    netifd_kill_process(proc);
    if (pipe(pfds) < 0)
        return -1;
    if ((pid = fork()) < 0)
        goto error;
    if (!pid) {
        int i;
        if (env) {
            while (*env) {
                putenv(*env);
                env++;
            }
        }
        if (proc->dir_fd >= 0)
            if (fchdir(proc->dir_fd)) {}
        close(pfds[0]);
        for (i = 0; i <= 2; i++) {
            if (pfds[1] == i)
                continue;
            dup2(pfds[1], i);
        }
        if (pfds[1] > 2)
            close(pfds[1]);
        execvp(argv[0], (char **) argv);
        exit(127);
    }
    close(pfds[1]);
    proc->uloop.cb = netifd_process_cb;
    proc->uloop.pid = pid;
    uloop_process_add(&proc->uloop);
    list_add_tail(&proc->list, &process_list);
    system_fd_set_cloexec(pfds[0]);
    proc->log.stream.string_data = true;
    proc->log.stream.notify_read = netifd_process_log_read_cb;
    ustream_fd_init(&proc->log, pfds[0]);
    return 0;
error:
    close(pfds[0]);
    close(pfds[1]);
    return -1;
}
References uloop_process::cb, netifd_process::dir_fd, netifd_process::list, list_add_tail(), netifd_process::log, netifd_kill_process(), netifd_process_cb(), netifd_process_log_read_cb(), ustream::notify_read, uloop_process::pid, process_list, ustream_fd::stream, ustream::string_data, system_fd_set_cloexec(), netifd_process::uloop, uloop_process_add(), and ustream_fd_init().
Referenced by proto_shell_handler(), proto_shell_run_command(), and wireless_device_run_handler().
netifd_udebug_config()
void netifd_udebug_config (struct udebug_ubus * ctx, struct blob_attr * data, bool enabled)
Definition at line 112 of file main.c.
{
    udebug_ubus_apply_config(&ud, rings, ARRAY_SIZE(rings), data, enabled);
}
References ARRAY_SIZE, rings, and ud.
Referenced by netifd_ubus_init().
netifd_udebug_printf()
void netifd_udebug_printf (const char * format, ...)
Definition at line 103 of file main.c.
{
    va_list ap;
    va_start(ap, format);
    netifd_udebug_vprintf(format, ap);
    va_end(ap);
}
References netifd_udebug_vprintf().
no_debug()
static void no_debug (int level, const char * fmt, ...) inline static
Definition at line 88 of file netifd.h.
{
}
Variable Documentation
config_path
const char* config_path extern
Definition at line 33 of file main.c.
Referenced by config_init_package(), and main().
debug_mask
unsigned int debug_mask extern
Definition at line 31 of file main.c.
Referenced by main().
hotplug_cmd_path
char* hotplug_cmd_path extern
Definition at line 24 of file interface-event.c.
Referenced by main(), and run_cmd().
main_path
const char* main_path extern
Definition at line 32 of file main.c.
Referenced by main(), netifd_open_subdir(), and usage().
resolv_conf
const char* resolv_conf extern
Definition at line 34 of file main.c.
Referenced by interface_write_resolv_conf(), and main().
udb_nl
struct udebug_buf udb_nl extern
Definition at line 40 of file main.c.
Referenced by create_socket().