zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/rpcd/uci.c File Reference
uci.c File Reference
#include <libgen.h>
#include <glob.h>
#include <libubox/blobmsg.h>
#include <libubox/blobmsg_json.h>
#include <rpcd/uci.h>
#include <rpcd/exec.h>
#include <rpcd/session.h>
Enumerations
enum {
RPC_G_CONFIG , RPC_G_SECTION , RPC_G_OPTION , RPC_G_TYPE ,
RPC_G_MATCH , RPC_G_SESSION , __RPC_G_MAX
}
enum {
RPC_A_CONFIG , RPC_A_TYPE , RPC_A_NAME , RPC_A_VALUES ,
RPC_A_SESSION , __RPC_A_MAX
}
enum {
RPC_S_CONFIG , RPC_S_SECTION , RPC_S_TYPE , RPC_S_MATCH ,
RPC_S_VALUES , RPC_S_SESSION , __RPC_S_MAX
}
enum {
RPC_D_CONFIG , RPC_D_SECTION , RPC_D_TYPE , RPC_D_MATCH ,
RPC_D_OPTION , RPC_D_OPTIONS , RPC_D_SESSION , __RPC_D_MAX
}
enum {
RPC_R_CONFIG , RPC_R_SECTION , RPC_R_OPTION , RPC_R_NAME ,
RPC_R_SESSION , __RPC_R_MAX
}
enum { RPC_O_CONFIG , RPC_O_SECTIONS , RPC_O_SESSION , __RPC_O_MAX }
enum { RPC_C_CONFIG , RPC_C_SESSION , __RPC_C_MAX }
enum { RPC_T_ROLLBACK , RPC_T_TIMEOUT , RPC_T_SESSION , __RPC_T_MAX }
enum { RPC_B_SESSION , __RPC_B_MAX }
Functions
static bool rpc_uci_verify_str (const char *name, bool extended, bool type)
static bool rpc_uci_verify_name (const char *name)
static bool rpc_uci_verify_type (const char *type)
static bool rpc_uci_verify_section (const char *section)
static int rpc_uci_status (void)
static void rpc_uci_replace_savedir (const char *path)
static void rpc_uci_set_savedir (struct blob_attr *sid)
static bool rpc_uci_read_access (struct blob_attr *sid, struct blob_attr *config)
static bool rpc_uci_write_access (struct blob_attr *sid, struct blob_attr *config)
static bool rpc_uci_format_blob (struct blob_attr *v, const char **p)
static int rpc_uci_lookup (struct uci_ptr *ptr)
static bool rpc_uci_match_option (struct uci_option *o, const char *cmp)
static bool rpc_uci_match_section (struct uci_section *s, struct blob_attr *type, struct blob_attr *matches)
static void rpc_uci_dump_option (struct uci_option *o, const char *name)
static void rpc_uci_dump_section (struct uci_section *s, const char *name, int index)
static void rpc_uci_dump_package (struct uci_package *p, const char *name, struct blob_attr *type, struct blob_attr *matches)
static int rpc_uci_getcommon (struct ubus_context *ctx, struct ubus_request_data *req, struct blob_attr *msg, bool use_state)
static int rpc_uci_get (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int rpc_uci_state (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int rpc_uci_add (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int rpc_uci_merge_set (struct blob_attr *opt, struct uci_ptr *ptr)
static int rpc_uci_set (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int rpc_uci_merge_delete (struct blob_attr *opt, struct uci_ptr *ptr)
static int rpc_uci_delete (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int rpc_uci_rename (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int rpc_uci_order (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static void rpc_uci_dump_change (struct uci_delta *d)
static int rpc_uci_changes (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static void rpc_uci_trigger_event (struct ubus_context *ctx, const char *config)
static int rpc_uci_revert_commit (struct ubus_context *ctx, struct blob_attr *msg, bool commit)
static int rpc_uci_revert (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int rpc_uci_commit (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int rpc_uci_configs (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static void rpc_uci_purge_dir (const char *path)
static int rpc_uci_apply_config (struct ubus_context *ctx, char *config)
static void rpc_uci_copy_file (const char *src, const char *target, const char *file)
static int rpc_uci_apply_access (const char *sid, glob_t *gl)
static void rpc_uci_do_rollback (struct ubus_context *ctx, glob_t *gl)
static void rpc_uci_apply_timeout (struct uloop_timeout *t)
static int rpc_uci_apply (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int rpc_uci_confirm (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int rpc_uci_rollback (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int rpc_uci_reload (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static void rpc_uci_purge_savedir_cb (struct rpc_session *ses, void *priv)
void rpc_uci_purge_savedirs (void)
int rpc_uci_api_init (struct ubus_context *ctx)
Variables
static struct blob_buf buf
static struct uci_context * cursor
static struct uloop_timeout apply_timer
static struct ubus_context * apply_ctx
char apply_sid [RPC_SID_LEN+1]
static const struct blobmsg_policy rpc_uci_get_policy [__RPC_G_MAX]
static const struct blobmsg_policy rpc_uci_add_policy [__RPC_A_MAX]
static const struct blobmsg_policy rpc_uci_set_policy [__RPC_S_MAX]
static const struct blobmsg_policy rpc_uci_delete_policy [__RPC_D_MAX]
static const struct blobmsg_policy rpc_uci_rename_policy [__RPC_R_MAX]
static const struct blobmsg_policy rpc_uci_order_policy [__RPC_O_MAX]
static const struct blobmsg_policy rpc_uci_config_policy [__RPC_C_MAX]
static const struct blobmsg_policy rpc_uci_apply_policy [__RPC_T_MAX]
static const struct blobmsg_policy rpc_uci_rollback_policy [__RPC_B_MAX]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
RPC_G_CONFIG
RPC_G_SECTION
RPC_G_OPTION
RPC_G_TYPE
RPC_G_MATCH
RPC_G_SESSION
__RPC_G_MAX
Definition at line 36 of file uci.c.
     {
    RPC_G_CONFIG,
    RPC_G_SECTION,
    RPC_G_OPTION,
    RPC_G_TYPE,
    RPC_G_MATCH,
    RPC_G_SESSION,
    __RPC_G_MAX,
};
anonymous enum
anonymous enum
Enumerator
RPC_A_CONFIG
RPC_A_TYPE
RPC_A_NAME
RPC_A_VALUES
RPC_A_SESSION
__RPC_A_MAX
Definition at line 56 of file uci.c.
     {
    RPC_A_CONFIG,
    RPC_A_TYPE,
    RPC_A_NAME,
    RPC_A_VALUES,
    RPC_A_SESSION,
    __RPC_A_MAX,
};
anonymous enum
anonymous enum
Enumerator
RPC_S_CONFIG
RPC_S_SECTION
RPC_S_TYPE
RPC_S_MATCH
RPC_S_VALUES
RPC_S_SESSION
__RPC_S_MAX
Definition at line 74 of file uci.c.
     {
    RPC_S_CONFIG,
    RPC_S_SECTION,
    RPC_S_TYPE,
    RPC_S_MATCH,
    RPC_S_VALUES,
    RPC_S_SESSION,
    __RPC_S_MAX,
};
anonymous enum
anonymous enum
Enumerator
RPC_D_CONFIG
RPC_D_SECTION
RPC_D_TYPE
RPC_D_MATCH
RPC_D_OPTION
RPC_D_OPTIONS
RPC_D_SESSION
__RPC_D_MAX
Definition at line 94 of file uci.c.
     {
    RPC_D_CONFIG,
    RPC_D_SECTION,
    RPC_D_TYPE,
    RPC_D_MATCH,
    RPC_D_OPTION,
    RPC_D_OPTIONS,
    RPC_D_SESSION,
    __RPC_D_MAX,
};
anonymous enum
anonymous enum
Enumerator
RPC_R_CONFIG
RPC_R_SECTION
RPC_R_OPTION
RPC_R_NAME
RPC_R_SESSION
__RPC_R_MAX
Definition at line 116 of file uci.c.
     {
    RPC_R_CONFIG,
    RPC_R_SECTION,
    RPC_R_OPTION,
    RPC_R_NAME,
    RPC_R_SESSION,
    __RPC_R_MAX,
};
anonymous enum
anonymous enum
Enumerator
RPC_O_CONFIG
RPC_O_SECTIONS
RPC_O_SESSION
__RPC_O_MAX
Definition at line 134 of file uci.c.
     {
    RPC_O_CONFIG,
    RPC_O_SECTIONS,
    RPC_O_SESSION,
    __RPC_O_MAX,
};
anonymous enum
anonymous enum
Enumerator
RPC_C_CONFIG
RPC_C_SESSION
__RPC_C_MAX
Definition at line 148 of file uci.c.
     {
    RPC_C_CONFIG,
    RPC_C_SESSION,
    __RPC_C_MAX,
};
anonymous enum
anonymous enum
Enumerator
RPC_T_ROLLBACK
RPC_T_TIMEOUT
RPC_T_SESSION
__RPC_T_MAX
Definition at line 160 of file uci.c.
     {
    RPC_T_ROLLBACK,
    RPC_T_TIMEOUT,
    RPC_T_SESSION,
    __RPC_T_MAX,
};
anonymous enum
anonymous enum
Enumerator
RPC_B_SESSION
__RPC_B_MAX
Definition at line 174 of file uci.c.
     {
    RPC_B_SESSION,
    __RPC_B_MAX,
};
Function Documentation
rpc_uci_add()
static int rpc_uci_add (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 681 of file uci.c.
{
    struct blob_attr *tb[__RPC_A_MAX];
    struct blob_attr *cur, *elem;
    struct uci_package *p = NULL;
    struct uci_section *s;
    struct uci_ptr ptr = { 0 };
    int rem, rem2, err = 0;
    blobmsg_parse(rpc_uci_add_policy, __RPC_A_MAX, tb,
                  blob_data(msg), blob_len(msg));
    if (!tb[RPC_A_CONFIG] || !tb[RPC_A_TYPE])
        return UBUS_STATUS_INVALID_ARGUMENT;
    if (!rpc_uci_write_access(tb[RPC_A_SESSION], tb[RPC_A_CONFIG]))
        return UBUS_STATUS_PERMISSION_DENIED;
    if (!rpc_uci_verify_type(blobmsg_data(tb[RPC_A_TYPE])))
        return UBUS_STATUS_INVALID_ARGUMENT;
    if (tb[RPC_A_NAME] &&
        !rpc_uci_verify_name(blobmsg_data(tb[RPC_A_NAME])))
        return UBUS_STATUS_INVALID_ARGUMENT;
    ptr.package = blobmsg_data(tb[RPC_A_CONFIG]);
    if (uci_load(cursor, ptr.package, &p))
        return rpc_uci_status();
    /* add named section */
    if (tb[RPC_A_NAME])
    {
        ptr.section = blobmsg_data(tb[RPC_A_NAME]);
        ptr.value   = blobmsg_data(tb[RPC_A_TYPE]);
        ptr.option  = NULL;
        if (rpc_uci_lookup(&ptr) || uci_set(cursor, &ptr))
            goto out;
    }
    /* add anon section */
    else
    {
        if (uci_add_section(cursor, p, blobmsg_data(tb[RPC_A_TYPE]), &s) || !s)
            goto out;
        ptr.section = s->e.name;
    }
    if (tb[RPC_A_VALUES])
    {
        blobmsg_for_each_attr(cur, tb[RPC_A_VALUES], rem)
        {
            ptr.flags = 0;
            ptr.o = NULL;
            ptr.option = blobmsg_name(cur);
            if (!rpc_uci_verify_name(ptr.option))
            {
                if (!err)
                    err = UBUS_STATUS_INVALID_ARGUMENT;
                continue;
            }
            if (rpc_uci_lookup(&ptr) || !ptr.s)
            {
                if (!err)
                    err = UBUS_STATUS_NOT_FOUND;
                continue;
            }
            switch (blobmsg_type(cur))
            {
            case BLOBMSG_TYPE_ARRAY:
                blobmsg_for_each_attr(elem, cur, rem2)
                {
                    if (!rpc_uci_format_blob(elem, &ptr.value))
                    {
                        if (!err)
                            err = UBUS_STATUS_INVALID_ARGUMENT;
                        continue;
                    }
                    uci_add_list(cursor, &ptr);
                }
                break;
            default:
                if (!rpc_uci_format_blob(cur, &ptr.value))
                {
                    if (!err)
                        err = UBUS_STATUS_INVALID_ARGUMENT;
                }
                else
                {
                    uci_set(cursor, &ptr);
                }
                break;
            }
        }
    }
    if (!err)
    {
        uci_save(cursor, p);
        blob_buf_init(&buf, 0);
        blobmsg_add_string(&buf, "section", ptr.section);
        ubus_send_reply(ctx, req, buf.head);
    }
out:
    uci_unload(cursor, p);
    return err ? err : rpc_uci_status();
}
References __RPC_A_MAX, blob_buf_init(), blob_data(), blob_len(), blobmsg_add_string(), blobmsg_data(), blobmsg_for_each_attr, blobmsg_name(), blobmsg_parse(), BLOBMSG_TYPE_ARRAY, buf, ctx, cursor, err, blob_buf::head, RPC_A_CONFIG, RPC_A_NAME, RPC_A_SESSION, RPC_A_TYPE, RPC_A_VALUES, rpc_uci_add_policy, rpc_uci_format_blob(), rpc_uci_lookup(), rpc_uci_status(), rpc_uci_verify_name(), rpc_uci_verify_type(), rpc_uci_write_access(), ubus_send_reply(), UBUS_STATUS_INVALID_ARGUMENT, UBUS_STATUS_NOT_FOUND, and UBUS_STATUS_PERMISSION_DENIED.
Referenced by rpc_uci_api_init().
rpc_uci_api_init()
int rpc_uci_api_init (struct ubus_context * ctx)
Definition at line 1760 of file uci.c.
{
    static const struct ubus_method uci_methods[] = {
        { .name = "configs", .handler = rpc_uci_configs },
        UBUS_METHOD("get",      rpc_uci_get,      rpc_uci_get_policy),
        UBUS_METHOD("state",    rpc_uci_state,    rpc_uci_get_policy),
        UBUS_METHOD("add",      rpc_uci_add,      rpc_uci_add_policy),
        UBUS_METHOD("set",      rpc_uci_set,      rpc_uci_set_policy),
        UBUS_METHOD("delete",   rpc_uci_delete,   rpc_uci_delete_policy),
        UBUS_METHOD("rename",   rpc_uci_rename,   rpc_uci_rename_policy),
        UBUS_METHOD("order",    rpc_uci_order,    rpc_uci_order_policy),
        UBUS_METHOD("changes",  rpc_uci_changes,  rpc_uci_config_policy),
        UBUS_METHOD("revert",   rpc_uci_revert,   rpc_uci_config_policy),
        UBUS_METHOD("commit",   rpc_uci_commit,   rpc_uci_config_policy),
        UBUS_METHOD("apply",    rpc_uci_apply,    rpc_uci_apply_policy),
        UBUS_METHOD("confirm",  rpc_uci_confirm,  rpc_uci_rollback_policy),
        UBUS_METHOD("rollback", rpc_uci_rollback, rpc_uci_rollback_policy),
        UBUS_METHOD_NOARG("reload_config", rpc_uci_reload),
    };
    static struct ubus_object_type uci_type =
        UBUS_OBJECT_TYPE("rpcd-plugin-uci", uci_methods);
    static struct ubus_object obj = {
        .name = "uci",
        .type = &uci_type,
        .methods = uci_methods,
        .n_methods = ARRAY_SIZE(uci_methods),
    };
    static struct rpc_session_cb cb = {
        .cb = rpc_uci_purge_savedir_cb
    };
    cursor = uci_alloc_context();
    if (!cursor)
        return UBUS_STATUS_UNKNOWN_ERROR;
    rpc_session_destroy_cb(&cb);
    return ubus_add_object(ctx, &obj);
}
References ARRAY_SIZE, rpc_session_cb::cb, ctx, cursor, ubus_object_type::methods, rpc_session_destroy_cb(), rpc_uci_add(), rpc_uci_add_policy, rpc_uci_apply(), rpc_uci_apply_policy, rpc_uci_changes(), rpc_uci_commit(), rpc_uci_config_policy, rpc_uci_configs(), rpc_uci_confirm(), rpc_uci_delete(), rpc_uci_delete_policy, rpc_uci_get(), rpc_uci_get_policy, rpc_uci_order(), rpc_uci_order_policy, rpc_uci_purge_savedir_cb(), rpc_uci_reload(), rpc_uci_rename(), rpc_uci_rename_policy, rpc_uci_revert(), rpc_uci_rollback(), rpc_uci_rollback_policy, rpc_uci_set(), rpc_uci_set_policy, rpc_uci_state(), ubus_add_object(), UBUS_METHOD, UBUS_METHOD_NOARG, UBUS_OBJECT_TYPE, and UBUS_STATUS_UNKNOWN_ERROR.
Referenced by main().
rpc_uci_apply()
static int rpc_uci_apply (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 1566 of file uci.c.
{
    struct blob_attr *tb[__RPC_T_MAX];
    int timeout = RPC_APPLY_TIMEOUT;
    char tmp[PATH_MAX];
    bool rollback = false;
    int ret, i;
    char *sid;
    glob_t gl;
    blobmsg_parse(rpc_uci_apply_policy, __RPC_T_MAX, tb,
                  blob_data(msg), blob_len(msg));
    if (tb[RPC_T_ROLLBACK])
        rollback = blobmsg_get_bool(tb[RPC_T_ROLLBACK]);
    if (apply_sid[0] && rollback)
        return UBUS_STATUS_PERMISSION_DENIED;
    if (!tb[RPC_T_SESSION])
        return UBUS_STATUS_INVALID_ARGUMENT;
    sid = blobmsg_data(tb[RPC_T_SESSION]);
    if (tb[RPC_T_TIMEOUT])
        timeout = blobmsg_get_u32(tb[RPC_T_TIMEOUT]);
    rpc_uci_purge_dir(RPC_SNAPSHOT_FILES);
    rpc_uci_purge_dir(RPC_SNAPSHOT_DELTA);
    if (!apply_sid[0]) {
        rpc_uci_set_savedir(tb[RPC_T_SESSION]);
        mkdir(RPC_SNAPSHOT_FILES, 0700);
        mkdir(RPC_SNAPSHOT_DELTA, 0700);
        snprintf(tmp, sizeof(tmp), RPC_UCI_SAVEDIR_PREFIX "%s/*", sid);
        if (glob(tmp, GLOB_PERIOD, NULL, &gl) < 0)
            return UBUS_STATUS_NOT_FOUND;
        snprintf(tmp, sizeof(tmp), RPC_UCI_SAVEDIR_PREFIX "%s/", sid);
        ret = rpc_uci_apply_access(sid, &gl);
        if (ret) {
            globfree(&gl);
            return ret;
        }
        /* copy SID early because rpc_uci_apply_config() will clobber buf */
        if (rollback)
            strncpy(apply_sid, sid, RPC_SID_LEN);
        for (i = 0; i < gl.gl_pathc; i++) {
            char *config = basename(gl.gl_pathv[i]);
            struct stat s;
            if (*config == '.')
                continue;
            if (stat(gl.gl_pathv[i], &s) || !s.st_size)
                continue;
            rpc_uci_copy_file(RPC_UCI_DIR, RPC_SNAPSHOT_FILES, config);
            rpc_uci_copy_file(tmp, RPC_SNAPSHOT_DELTA, config);
            rpc_uci_apply_config(ctx, config);
        }
        globfree(&gl);
        if (rollback) {
            apply_timer.cb = rpc_uci_apply_timeout;
            uloop_timeout_set(&apply_timer, timeout * 1000);
            apply_ctx = ctx;
        }
    }
    return 0;
}
References __RPC_T_MAX, apply_ctx, apply_sid, apply_timer, blob_data(), blob_len(), blobmsg_data(), blobmsg_get_bool(), blobmsg_get_u32(), blobmsg_parse(), uloop_timeout::cb, config, ctx, RPC_APPLY_TIMEOUT, RPC_SID_LEN, RPC_SNAPSHOT_DELTA, RPC_SNAPSHOT_FILES, RPC_T_ROLLBACK, RPC_T_SESSION, RPC_T_TIMEOUT, rpc_uci_apply_access(), rpc_uci_apply_config(), rpc_uci_apply_policy, rpc_uci_apply_timeout(), rpc_uci_copy_file(), RPC_UCI_DIR, rpc_uci_purge_dir(), RPC_UCI_SAVEDIR_PREFIX, rpc_uci_set_savedir(), timeout, UBUS_STATUS_INVALID_ARGUMENT, UBUS_STATUS_NOT_FOUND, UBUS_STATUS_PERMISSION_DENIED, and uloop_timeout_set().
Referenced by rpc_uci_api_init().
rpc_uci_apply_access()
static int rpc_uci_apply_access (const char * sid, glob_t * gl) static
Definition at line 1481 of file uci.c.
{
    struct stat s;
    int i, c = 0;
    if (gl->gl_pathc < 3)
        return UBUS_STATUS_NO_DATA;
    for (i = 0; i < gl->gl_pathc; i++) {
        char *config = basename(gl->gl_pathv[i]);
        if (*config == '.')
            continue;
        if (stat(gl->gl_pathv[i], &s) || !s.st_size)
            continue;
        if (!rpc_session_access(sid, "uci", config, "write"))
            return UBUS_STATUS_PERMISSION_DENIED;
        c++;
    }
    if (!c)
        return UBUS_STATUS_NO_DATA;
    return 0;
}
References config, rpc_session_access(), UBUS_STATUS_NO_DATA, and UBUS_STATUS_PERMISSION_DENIED.
Referenced by rpc_uci_apply(), and rpc_uci_do_rollback().
rpc_uci_apply_config()
static int rpc_uci_apply_config (struct ubus_context * ctx, char * config) static
Definition at line 1444 of file uci.c.
{
    struct uci_package *p = NULL;
    if (!uci_load(cursor, config, &p)) {
        uci_commit(cursor, &p, false);
        uci_unload(cursor, p);
    }
    rpc_uci_trigger_event(ctx, config);
    return 0;
}
References config, ctx, cursor, and rpc_uci_trigger_event().
Referenced by rpc_uci_apply(), and rpc_uci_do_rollback().
rpc_uci_apply_timeout()
static void rpc_uci_apply_timeout (struct uloop_timeout * t) static
Definition at line 1551 of file uci.c.
{
    glob_t gl;
    char tmp[PATH_MAX];
    snprintf(tmp, sizeof(tmp), "%s/*", RPC_SNAPSHOT_FILES);
    if (glob(tmp, GLOB_PERIOD, NULL, &gl) < 0)
        return;
    rpc_uci_do_rollback(apply_ctx, &gl);
    globfree(&gl);
}
References apply_ctx, RPC_SNAPSHOT_FILES, and rpc_uci_do_rollback().
Referenced by rpc_uci_apply().
rpc_uci_changes()
static int rpc_uci_changes (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 1225 of file uci.c.
{
    struct blob_attr *tb[__RPC_C_MAX];
    struct uci_package *p = NULL;
    struct uci_element *e;
    char **configs;
    void *c, *d;
    int i;
    blobmsg_parse(rpc_uci_config_policy, __RPC_C_MAX, tb,
                  blob_data(msg), blob_len(msg));
    if (tb[RPC_C_CONFIG])
    {
        if (!rpc_uci_read_access(tb[RPC_C_SESSION], tb[RPC_C_CONFIG]))
            return UBUS_STATUS_PERMISSION_DENIED;
        if (uci_load(cursor, blobmsg_data(tb[RPC_C_CONFIG]), &p))
            return rpc_uci_status();
        blob_buf_init(&buf, 0);
        c = blobmsg_open_array(&buf, "changes");
        uci_foreach_element(&p->saved_delta, e)
            rpc_uci_dump_change(uci_to_delta(e));
        blobmsg_close_array(&buf, c);
        uci_unload(cursor, p);
        ubus_send_reply(ctx, req, buf.head);
        return rpc_uci_status();
    }
    rpc_uci_set_savedir(tb[RPC_C_SESSION]);
    if (uci_list_configs(cursor, &configs))
        return rpc_uci_status();
    blob_buf_init(&buf, 0);
    c = blobmsg_open_table(&buf, "changes");
    for (i = 0; configs[i]; i++)
    {
        if (tb[RPC_C_SESSION] &&
            !rpc_session_access(blobmsg_data(tb[RPC_C_SESSION]), "uci",
                                configs[i], "read"))
            continue;
        if (uci_load(cursor, configs[i], &p))
            continue;
        if (!uci_list_empty(&p->saved_delta))
        {
            d = blobmsg_open_array(&buf, configs[i]);
            uci_foreach_element(&p->saved_delta, e)
                rpc_uci_dump_change(uci_to_delta(e));
            blobmsg_close_array(&buf, d);
        }
        uci_unload(cursor, p);
    }
    free(configs);
    blobmsg_close_table(&buf, c);
    ubus_send_reply(ctx, req, buf.head);
    return 0;
}
References __RPC_C_MAX, blob_buf_init(), blob_data(), blob_len(), blobmsg_close_array(), blobmsg_close_table(), blobmsg_data(), blobmsg_open_array(), blobmsg_open_table(), blobmsg_parse(), buf, ctx, cursor, blob_buf::head, RPC_C_CONFIG, RPC_C_SESSION, rpc_session_access(), rpc_uci_config_policy, rpc_uci_dump_change(), rpc_uci_read_access(), rpc_uci_set_savedir(), rpc_uci_status(), ubus_send_reply(), and UBUS_STATUS_PERMISSION_DENIED.
Referenced by rpc_uci_api_init().
rpc_uci_commit()
static int rpc_uci_commit (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 1374 of file uci.c.
{
    return rpc_uci_revert_commit(ctx, msg, true);
}
References ctx, and rpc_uci_revert_commit().
Referenced by rpc_uci_api_init().
rpc_uci_configs()
static int rpc_uci_configs (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 1382 of file uci.c.
{
    char **configs;
    void *c;
    int i;
    if (uci_list_configs(cursor, &configs))
        goto out;
    blob_buf_init(&buf, 0);
    c = blobmsg_open_array(&buf, "configs");
    for (i = 0; configs[i]; i++)
        blobmsg_add_string(&buf, NULL, configs[i]);
    free(configs);
    blobmsg_close_array(&buf, c);
    ubus_send_reply(ctx, req, buf.head);
out:
    return rpc_uci_status();
}
References blob_buf_init(), blobmsg_add_string(), blobmsg_close_array(), blobmsg_open_array(), buf, ctx, cursor, blob_buf::head, rpc_uci_status(), and ubus_send_reply().
Referenced by rpc_uci_api_init().
rpc_uci_confirm()
static int rpc_uci_confirm (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 1648 of file uci.c.
{
    struct blob_attr *tb[__RPC_B_MAX];
    char *sid;
    blobmsg_parse(rpc_uci_rollback_policy, __RPC_B_MAX, tb,
                  blob_data(msg), blob_len(msg));
    if (!tb[RPC_B_SESSION])
        return UBUS_STATUS_INVALID_ARGUMENT;
    sid = blobmsg_data(tb[RPC_B_SESSION]);
    if (!apply_sid[0])
        return UBUS_STATUS_NO_DATA;
    if (strcmp(apply_sid, sid))
        return UBUS_STATUS_PERMISSION_DENIED;
    rpc_uci_purge_dir(RPC_SNAPSHOT_FILES);
    rpc_uci_purge_dir(RPC_SNAPSHOT_DELTA);
    uloop_timeout_cancel(&apply_timer);
    memset(apply_sid, 0, sizeof(apply_sid));
    apply_ctx = NULL;
    return 0;
}
References __RPC_B_MAX, apply_ctx, apply_sid, apply_timer, blob_data(), blob_len(), blobmsg_data(), blobmsg_parse(), RPC_B_SESSION, RPC_SNAPSHOT_DELTA, RPC_SNAPSHOT_FILES, rpc_uci_purge_dir(), rpc_uci_rollback_policy, UBUS_STATUS_INVALID_ARGUMENT, UBUS_STATUS_NO_DATA, UBUS_STATUS_PERMISSION_DENIED, and uloop_timeout_cancel().
Referenced by rpc_uci_api_init().
rpc_uci_copy_file()
static void rpc_uci_copy_file (const char * src, const char * target, const char * file) static
Definition at line 1458 of file uci.c.
{
    char tmp[256];
    FILE *in, *out;
    snprintf(tmp, sizeof(tmp), "%s%s", src, file);
    in = fopen(tmp, "rb");
    snprintf(tmp, sizeof(tmp), "%s%s", target, file);
    out = fopen(tmp, "wb+");
    if (in && out)
        while (!feof(in)) {
            int len = fread(tmp, 1, sizeof(tmp), in);
            if(len > 0)
                fwrite(tmp, 1, len, out);
        }
    if(in)
        fclose(in);
    if(out)
        fclose(out);
}
Referenced by rpc_uci_apply(), and rpc_uci_do_rollback().
rpc_uci_delete()
static int rpc_uci_delete (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 1009 of file uci.c.
{
    struct blob_attr *tb[__RPC_D_MAX];
    struct uci_package *p = NULL;
    struct uci_element *e, *tmp;
    struct uci_ptr ptr = { 0 };
    int err = 0;
    blobmsg_parse(rpc_uci_delete_policy, __RPC_D_MAX, tb,
                  blob_data(msg), blob_len(msg));
    if (!tb[RPC_D_CONFIG] ||
        (!tb[RPC_D_SECTION] && !tb[RPC_D_TYPE] && !tb[RPC_D_MATCH]))
        return UBUS_STATUS_INVALID_ARGUMENT;
    if (!rpc_uci_write_access(tb[RPC_D_SESSION], tb[RPC_D_CONFIG]))
        return UBUS_STATUS_PERMISSION_DENIED;
    if (tb[RPC_D_TYPE] &&
        !rpc_uci_verify_type(blobmsg_data(tb[RPC_D_TYPE])))
        return UBUS_STATUS_INVALID_ARGUMENT;
    if (tb[RPC_D_SECTION] &&
        !rpc_uci_verify_section(blobmsg_data(tb[RPC_D_SECTION])))
        return UBUS_STATUS_INVALID_ARGUMENT;
    ptr.package = blobmsg_data(tb[RPC_D_CONFIG]);
    if (uci_load(cursor, ptr.package, &p))
        return rpc_uci_status();
    if (tb[RPC_D_SECTION])
    {
        ptr.section = blobmsg_data(tb[RPC_D_SECTION]);
        if (tb[RPC_D_OPTIONS])
            err = rpc_uci_merge_delete(tb[RPC_D_OPTIONS], &ptr);
        else
            err = rpc_uci_merge_delete(tb[RPC_D_OPTION], &ptr);
    }
    else
    {
        uci_foreach_element_safe(&p->sections, tmp, e)
        {
            if (!rpc_uci_match_section(uci_to_section(e),
                                       tb[RPC_D_TYPE], tb[RPC_D_MATCH]))
                continue;
            ptr.s = NULL;
            ptr.section = e->name;
            if (tb[RPC_D_OPTIONS])
                err = rpc_uci_merge_delete(tb[RPC_D_OPTIONS], &ptr);
            else
                err = rpc_uci_merge_delete(tb[RPC_D_OPTION], &ptr);
        }
        if (!err && !ptr.section)
            err = UBUS_STATUS_NOT_FOUND;
    }
    if (!err)
        uci_save(cursor, p);
    uci_unload(cursor, p);
    return err ? err : rpc_uci_status();
}
References __RPC_D_MAX, blob_data(), blob_len(), blobmsg_data(), blobmsg_parse(), cursor, err, RPC_D_CONFIG, RPC_D_MATCH, RPC_D_OPTION, RPC_D_OPTIONS, RPC_D_SECTION, RPC_D_SESSION, RPC_D_TYPE, rpc_uci_delete_policy, rpc_uci_match_section(), rpc_uci_merge_delete(), rpc_uci_status(), rpc_uci_verify_section(), rpc_uci_verify_type(), rpc_uci_write_access(), UBUS_STATUS_INVALID_ARGUMENT, UBUS_STATUS_NOT_FOUND, and UBUS_STATUS_PERMISSION_DENIED.
Referenced by rpc_uci_api_init().
rpc_uci_do_rollback()
static void rpc_uci_do_rollback (struct ubus_context * ctx, glob_t * gl) static
Definition at line 1508 of file uci.c.
{
    int i, deny;
    char tmp[PATH_MAX];
    /* Test apply permission to see if the initiator session still exists.
     * If it does, restore the delta files as well, else just restore the
     * main configuration files. */
    deny = apply_sid[0]
        ? rpc_uci_apply_access(apply_sid, gl) : UBUS_STATUS_NOT_FOUND;
    if (!deny) {
        snprintf(tmp, sizeof(tmp), RPC_UCI_SAVEDIR_PREFIX "%s/", apply_sid);
        mkdir(tmp, 0700);
    }
    /* avoid merging unrelated uci changes when restoring old configs */
    rpc_uci_replace_savedir("/dev/null");
    for (i = 0; i < gl->gl_pathc; i++) {
        char *config = basename(gl->gl_pathv[i]);
        if (*config == '.')
            continue;
        rpc_uci_copy_file(RPC_SNAPSHOT_FILES, RPC_UCI_DIR, config);
        rpc_uci_apply_config(ctx, config);
        if (deny)
            continue;
        rpc_uci_copy_file(RPC_SNAPSHOT_DELTA, tmp, config);
    }
    rpc_uci_purge_dir(RPC_SNAPSHOT_FILES);
    rpc_uci_purge_dir(RPC_SNAPSHOT_DELTA);
    uloop_timeout_cancel(&apply_timer);
    memset(apply_sid, 0, sizeof(apply_sid));
    apply_ctx = NULL;
}
References apply_ctx, apply_sid, apply_timer, config, ctx, RPC_SNAPSHOT_DELTA, RPC_SNAPSHOT_FILES, rpc_uci_apply_access(), rpc_uci_apply_config(), rpc_uci_copy_file(), RPC_UCI_DIR, rpc_uci_purge_dir(), rpc_uci_replace_savedir(), RPC_UCI_SAVEDIR_PREFIX, UBUS_STATUS_NOT_FOUND, and uloop_timeout_cancel().
Referenced by rpc_uci_apply_timeout(), and rpc_uci_rollback().
rpc_uci_dump_change()
static void rpc_uci_dump_change (struct uci_delta * d) static
Definition at line 1189 of file uci.c.
{
    void *c;
    const char *types[] = {
        [UCI_CMD_REORDER]  = "order",
        [UCI_CMD_REMOVE]   = "remove",
        [UCI_CMD_RENAME]   = "rename",
        [UCI_CMD_ADD]      = "add",
        [UCI_CMD_LIST_ADD] = "list-add",
        [UCI_CMD_LIST_DEL] = "list-del",
        [UCI_CMD_CHANGE]   = "set",
    };
    if (!d->section)
        return;
    c = blobmsg_open_array(&buf, NULL);
    blobmsg_add_string(&buf, NULL, types[d->cmd]);
    blobmsg_add_string(&buf, NULL, d->section);
    if (d->e.name)
        blobmsg_add_string(&buf, NULL, d->e.name);
    if (d->value)
    {
        if (d->cmd == UCI_CMD_REORDER)
            blobmsg_add_u32(&buf, NULL, strtoul(d->value, NULL, 10));
        else
            blobmsg_add_string(&buf, NULL, d->value);
    }
    blobmsg_close_array(&buf, c);
}
References blobmsg_add_string(), blobmsg_add_u32(), blobmsg_close_array(), blobmsg_open_array(), and buf.
Referenced by rpc_uci_changes().
rpc_uci_dump_option()
static void rpc_uci_dump_option (struct uci_option * o, const char * name) static
Definition at line 510 of file uci.c.
{
    void *c;
    struct uci_element *e;
    switch (o->type)
    {
    case UCI_TYPE_STRING:
        blobmsg_add_string(&buf, name, o->v.string);
        break;
    case UCI_TYPE_LIST:
        c = blobmsg_open_array(&buf, name);
        uci_foreach_element(&o->v.list, e)
            blobmsg_add_string(&buf, NULL, e->name);
        blobmsg_close_array(&buf, c);
        break;
    default:
        break;
    }
}
References blobmsg_add_string(), blobmsg_close_array(), blobmsg_open_array(), and buf.
Referenced by rpc_uci_dump_section(), and rpc_uci_getcommon().
rpc_uci_dump_package()
static void rpc_uci_dump_package (struct uci_package * p, const char * name, struct blob_attr * type, struct blob_attr * matches) static
Definition at line 577 of file uci.c.
{
    void *c;
    struct uci_element *e;
    int i = -1;
    c = blobmsg_open_table(&buf, name);
    uci_foreach_element(&p->sections, e)
    {
        i++;
        if (!rpc_uci_match_section(uci_to_section(e), type, matches))
            continue;
        rpc_uci_dump_section(uci_to_section(e), e->name, i);
    }
    blobmsg_close_table(&buf, c);
}
References blobmsg_close_table(), blobmsg_open_table(), buf, rpc_uci_dump_section(), rpc_uci_match_section(), and type.
Referenced by rpc_uci_getcommon().
rpc_uci_dump_section()
static void rpc_uci_dump_section (struct uci_section * s, const char * name, int index) static
Definition at line 544 of file uci.c.
{
    void *c;
    struct uci_option *o;
    struct uci_element *e;
    c = blobmsg_open_table(&buf, name);
    blobmsg_add_u8(&buf, ".anonymous", s->anonymous);
    blobmsg_add_string(&buf, ".type", s->type);
    blobmsg_add_string(&buf, ".name", s->e.name);
    if (index >= 0)
        blobmsg_add_u32(&buf, ".index", index);
    uci_foreach_element(&s->options, e)
    {
        o = uci_to_option(e);
        rpc_uci_dump_option(o, o->e.name);
    }
    blobmsg_close_table(&buf, c);
}
References blobmsg_add_string(), blobmsg_add_u32(), blobmsg_add_u8(), blobmsg_close_table(), blobmsg_open_table(), buf, and rpc_uci_dump_option().
Referenced by rpc_uci_dump_package(), and rpc_uci_getcommon().
rpc_uci_format_blob()
static bool rpc_uci_format_blob (struct blob_attr * v, const char ** p) static
Definition at line 344 of file uci.c.
{
    static char buf[21];
    *p = NULL;
    switch (blobmsg_type(v))
    {
    case BLOBMSG_TYPE_STRING:
        *p = blobmsg_data(v);
        break;
    case BLOBMSG_TYPE_INT64:
        snprintf(buf, sizeof(buf), "%"PRIu64, blobmsg_get_u64(v));
        *p = buf;
        break;
    case BLOBMSG_TYPE_INT32:
        snprintf(buf, sizeof(buf), "%u", blobmsg_get_u32(v));
        *p = buf;
        break;
    case BLOBMSG_TYPE_INT16:
        snprintf(buf, sizeof(buf), "%u", blobmsg_get_u16(v));
        *p = buf;
        break;
    case BLOBMSG_TYPE_INT8:
        snprintf(buf, sizeof(buf), "%u", !!blobmsg_get_u8(v));
        *p = buf;
        break;
    default:
        break;
    }
    return !!*p;
}
References blobmsg_data(), blobmsg_get_u16(), blobmsg_get_u32(), blobmsg_get_u64(), blobmsg_get_u8(), BLOBMSG_TYPE_INT16, BLOBMSG_TYPE_INT32, BLOBMSG_TYPE_INT64, BLOBMSG_TYPE_INT8, BLOBMSG_TYPE_STRING, and buf.
Referenced by rpc_uci_add(), rpc_uci_match_section(), and rpc_uci_merge_set().
rpc_uci_get()
static int rpc_uci_get (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 665 of file uci.c.
{
    return rpc_uci_getcommon(ctx, req, msg, false);
}
References ctx, and rpc_uci_getcommon().
Referenced by rpc_uci_api_init().
rpc_uci_getcommon()
static int rpc_uci_getcommon (struct ubus_context * ctx, struct ubus_request_data * req, struct blob_attr * msg, bool use_state) static
Definition at line 601 of file uci.c.
{
    struct blob_attr *tb[__RPC_G_MAX];
    struct uci_package *p = NULL;
    struct uci_ptr ptr = { 0 };
    blobmsg_parse(rpc_uci_get_policy, __RPC_G_MAX, tb,
                  blob_data(msg), blob_len(msg));
    if (!tb[RPC_G_CONFIG])
        return UBUS_STATUS_INVALID_ARGUMENT;
    if (!rpc_uci_read_access(tb[RPC_G_SESSION], tb[RPC_G_CONFIG]))
        return UBUS_STATUS_PERMISSION_DENIED;
    ptr.package = blobmsg_data(tb[RPC_G_CONFIG]);
    if (use_state)
        uci_set_savedir(cursor, "/var/state");
    if (uci_load(cursor, ptr.package, &p))
        return rpc_uci_status();
    if (tb[RPC_G_SECTION])
    {
        ptr.section = blobmsg_data(tb[RPC_G_SECTION]);
        if (tb[RPC_G_OPTION])
            ptr.option = blobmsg_data(tb[RPC_G_OPTION]);
    }
    if (rpc_uci_lookup(&ptr) || !(ptr.flags & UCI_LOOKUP_COMPLETE))
        goto out;
    blob_buf_init(&buf, 0);
    switch (ptr.last->type)
    {
    case UCI_TYPE_PACKAGE:
        rpc_uci_dump_package(ptr.p, "values", tb[RPC_G_TYPE], tb[RPC_G_MATCH]);
        break;
    case UCI_TYPE_SECTION:
        rpc_uci_dump_section(ptr.s, "values", -1);
        break;
    case UCI_TYPE_OPTION:
        rpc_uci_dump_option(ptr.o, "value");
        break;
    default:
        break;
    }
    ubus_send_reply(ctx, req, buf.head);
out:
    uci_unload(cursor, p);
    return rpc_uci_status();
}
References __RPC_G_MAX, blob_buf_init(), blob_data(), blob_len(), blobmsg_data(), blobmsg_parse(), buf, ctx, cursor, blob_buf::head, RPC_G_CONFIG, RPC_G_MATCH, RPC_G_OPTION, RPC_G_SECTION, RPC_G_SESSION, RPC_G_TYPE, rpc_uci_dump_option(), rpc_uci_dump_package(), rpc_uci_dump_section(), rpc_uci_get_policy, rpc_uci_lookup(), rpc_uci_read_access(), rpc_uci_status(), ubus_send_reply(), UBUS_STATUS_INVALID_ARGUMENT, and UBUS_STATUS_PERMISSION_DENIED.
Referenced by rpc_uci_get(), and rpc_uci_state().
rpc_uci_lookup()
static int rpc_uci_lookup (struct uci_ptr * ptr) static
Definition at line 391 of file uci.c.
{
    int rv;
    struct uci_ptr lookup = *ptr;
    if (!lookup.s && lookup.section && *lookup.section == '@')
        lookup.flags |= UCI_LOOKUP_EXTENDED;
    rv = uci_lookup_ptr(cursor, &lookup, NULL, true);
    if (!rv)
        *ptr = lookup;
    return rv;
}
References cursor.
Referenced by rpc_uci_add(), rpc_uci_getcommon(), rpc_uci_merge_delete(), and rpc_uci_merge_set().
rpc_uci_match_option()
static bool rpc_uci_match_option (struct uci_option * o, const char * cmp) static
Definition at line 416 of file uci.c.
{
    struct uci_element *e;
    char *s, *p;
    if (o->type == UCI_TYPE_LIST)
    {
        uci_foreach_element(&o->v.list, e)
            if (e->name && !strcmp(e->name, cmp))
                return true;
        return false;
    }
    if (!o->v.string)
        return false;
    s = strdup(o->v.string);
    if (!s)
        return false;
    for (p = strtok(s, " \t"); p; p = strtok(NULL, " \t"))
    {
        if (!strcmp(p, cmp))
        {
            free(s);
            return true;
        }
    }
    free(s);
    return false;
}
References cmp.
Referenced by rpc_uci_match_section().
rpc_uci_match_section()
static bool rpc_uci_match_section (struct uci_section * s, struct blob_attr * type, struct blob_attr * matches) static
Definition at line 463 of file uci.c.
{
    struct uci_element *e;
    struct blob_attr *cur;
    const char *cmp;
    bool match = false;
    bool empty = true;
    int rem;
    if (type && strcmp(s->type, blobmsg_data(type)))
        return false;
    if (!matches)
        return true;
    blobmsg_for_each_attr(cur, matches, rem)
    {
        if (!rpc_uci_format_blob(cur, &cmp))
            continue;
        uci_foreach_element(&s->options, e)
        {
            if (strcmp(e->name, blobmsg_name(cur)))
                continue;
            if (!rpc_uci_match_option(uci_to_option(e), cmp))
                return false;
            match = true;
        }
        empty = false;
    }
    return (empty || match);
}
References blobmsg_data(), blobmsg_for_each_attr, blobmsg_name(), cmp, rpc_uci_format_blob(), rpc_uci_match_option(), and type.
Referenced by rpc_uci_delete(), rpc_uci_dump_package(), and rpc_uci_set().
rpc_uci_merge_delete()
static int rpc_uci_merge_delete (struct blob_attr * opt, struct uci_ptr * ptr) static
Definition at line 955 of file uci.c.
{
    struct blob_attr *cur;
    int rem, rv;
    if (rpc_uci_lookup(ptr) || !ptr->s)
        return UBUS_STATUS_NOT_FOUND;
    if (!opt)
    {
        ptr->o = NULL;
        ptr->option = NULL;
        uci_delete(cursor, ptr);
        return 0;
    }
    else if (blobmsg_type(opt) == BLOBMSG_TYPE_ARRAY)
    {
        rv = UBUS_STATUS_NOT_FOUND;
        blobmsg_for_each_attr(cur, opt, rem)
        {
            if (blobmsg_type(cur) != BLOBMSG_TYPE_STRING)
                continue;
            ptr->o = NULL;
            ptr->option = blobmsg_data(cur);
            if (rpc_uci_lookup(ptr) || !ptr->o)
                continue;
            uci_delete(cursor, ptr);
            ptr->flags = 0;
            rv = 0;
        }
        return rv;
    }
    else if (blobmsg_type(opt) == BLOBMSG_TYPE_STRING)
    {
        ptr->o = NULL;
        ptr->option = blobmsg_data(opt);
        if (rpc_uci_lookup(ptr) || !ptr->o)
            return UBUS_STATUS_NOT_FOUND;
        uci_delete(cursor, ptr);
        return 0;
    }
    return UBUS_STATUS_INVALID_ARGUMENT;
}
References blobmsg_data(), blobmsg_for_each_attr, BLOBMSG_TYPE_ARRAY, BLOBMSG_TYPE_STRING, cursor, rpc_uci_lookup(), UBUS_STATUS_INVALID_ARGUMENT, and UBUS_STATUS_NOT_FOUND.
Referenced by rpc_uci_delete().
rpc_uci_merge_set()
static int rpc_uci_merge_set (struct blob_attr * opt, struct uci_ptr * ptr) static
Definition at line 816 of file uci.c.
{
    struct blob_attr *cur;
    int rem, rv;
    ptr->flags = 0;
    ptr->o = NULL;
    ptr->option = blobmsg_name(opt);
    ptr->value = NULL;
    if (!rpc_uci_verify_name(ptr->option))
        return UBUS_STATUS_INVALID_ARGUMENT;
    if (rpc_uci_lookup(ptr) || !ptr->s)
        return UBUS_STATUS_NOT_FOUND;
    if (blobmsg_type(opt) == BLOBMSG_TYPE_ARRAY)
    {
        if (ptr->o) {
            uci_delete(cursor, ptr);
            ptr->flags = 0;
        }
        rv = UBUS_STATUS_INVALID_ARGUMENT;
        blobmsg_for_each_attr(cur, opt, rem)
        {
            if (!rpc_uci_format_blob(cur, &ptr->value))
                continue;
            uci_add_list(cursor, ptr);
            rv = 0;
        }
        return rv;
    }
    else if (ptr->o && ptr->o->type == UCI_TYPE_LIST)
    {
        uci_delete(cursor, ptr);
        ptr->flags = 0;
        if (!rpc_uci_format_blob(opt, &ptr->value))
            return UBUS_STATUS_INVALID_ARGUMENT;
        uci_set(cursor, ptr);
    }
    else
    {
        if (!rpc_uci_format_blob(opt, &ptr->value))
            return UBUS_STATUS_INVALID_ARGUMENT;
        if (!ptr->o || !ptr->o->v.string || strcmp(ptr->o->v.string, ptr->value))
            uci_set(cursor, ptr);
    }
    return 0;
}
References blobmsg_for_each_attr, blobmsg_name(), BLOBMSG_TYPE_ARRAY, cursor, rpc_uci_format_blob(), rpc_uci_lookup(), rpc_uci_verify_name(), UBUS_STATUS_INVALID_ARGUMENT, and UBUS_STATUS_NOT_FOUND.
Referenced by rpc_uci_set().
rpc_uci_order()
static int rpc_uci_order (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 1132 of file uci.c.
{
    struct blob_attr *tb[__RPC_O_MAX];
    struct blob_attr *cur;
    struct uci_package *p = NULL;
    struct uci_ptr ptr = { 0 };
    int rem, i = 0, err = 0;
    blobmsg_parse(rpc_uci_order_policy, __RPC_O_MAX, tb,
                  blob_data(msg), blob_len(msg));
    if (!tb[RPC_O_CONFIG] || !tb[RPC_O_SECTIONS])
        return UBUS_STATUS_INVALID_ARGUMENT;
    if (!rpc_uci_write_access(tb[RPC_O_SESSION], tb[RPC_O_CONFIG]))
        return UBUS_STATUS_PERMISSION_DENIED;
    ptr.package = blobmsg_data(tb[RPC_O_CONFIG]);
    if (uci_load(cursor, ptr.package, &p))
        return rpc_uci_status();
    blobmsg_for_each_attr(cur, tb[RPC_O_SECTIONS], rem)
    {
        if (blobmsg_type(cur) != BLOBMSG_TYPE_STRING)
        {
            if (!err)
                err = UBUS_STATUS_INVALID_ARGUMENT;
            continue;
        }
        ptr.s = NULL;
        ptr.section = blobmsg_data(cur);
        if (uci_lookup_ptr(cursor, &ptr, NULL, true) || !ptr.s)
        {
            if (!err)
                err = UBUS_STATUS_NOT_FOUND;
            continue;
        }
        uci_reorder_section(cursor, ptr.s, i++);
    }
    if (!err)
        uci_save(cursor, p);
    uci_unload(cursor, p);
    return err ? err : rpc_uci_status();
}
References __RPC_O_MAX, blob_data(), blob_len(), blobmsg_data(), blobmsg_for_each_attr, blobmsg_parse(), BLOBMSG_TYPE_STRING, cursor, err, RPC_O_CONFIG, RPC_O_SECTIONS, RPC_O_SESSION, rpc_uci_order_policy, rpc_uci_status(), rpc_uci_write_access(), UBUS_STATUS_INVALID_ARGUMENT, UBUS_STATUS_NOT_FOUND, and UBUS_STATUS_PERMISSION_DENIED.
Referenced by rpc_uci_api_init().
rpc_uci_purge_dir()
static void rpc_uci_purge_dir (const char * path) static
Definition at line 1415 of file uci.c.
{
    DIR *d;
    struct stat s;
    struct dirent *e;
    char file[PATH_MAX];
    if (stat(path, &s) || !S_ISDIR(s.st_mode))
        return;
    if ((d = opendir(path)) != NULL)
    {
        while ((e = readdir(d)) != NULL)
        {
            snprintf(file, sizeof(file) - 1, "%s/%s", path, e->d_name);
            if (stat(file, &s) || !S_ISREG(s.st_mode))
                continue;
            unlink(file);
        }
        closedir(d);
        rmdir(path);
    }
}
References path.
Referenced by rpc_uci_apply(), rpc_uci_confirm(), rpc_uci_do_rollback(), rpc_uci_purge_savedir_cb(), and rpc_uci_purge_savedirs().
rpc_uci_purge_savedir_cb()
static void rpc_uci_purge_savedir_cb (struct rpc_session * ses, void * priv) static
Definition at line 1734 of file uci.c.
{
    char path[PATH_MAX];
    snprintf(path, sizeof(path) - 1, RPC_UCI_SAVEDIR_PREFIX "%s", ses->id);
    rpc_uci_purge_dir(path);
}
References rpc_session::id, path, rpc_uci_purge_dir(), and RPC_UCI_SAVEDIR_PREFIX.
Referenced by rpc_uci_api_init().
rpc_uci_purge_savedirs()
void rpc_uci_purge_savedirs (void)
Definition at line 1746 of file uci.c.
{
    int i;
    glob_t gl;
    if (!glob(RPC_UCI_SAVEDIR_PREFIX "*", 0, NULL, &gl))
    {
        for (i = 0; i < gl.gl_pathc; i++)
            rpc_uci_purge_dir(gl.gl_pathv[i]);
        globfree(&gl);
    }
}
References rpc_uci_purge_dir(), and RPC_UCI_SAVEDIR_PREFIX.
Referenced by main().
rpc_uci_read_access()
static bool rpc_uci_read_access (struct blob_attr * sid, struct blob_attr * config) static
Definition at line 311 of file uci.c.
{
    rpc_uci_set_savedir(sid);
    if (!sid)
        return true;
    return rpc_session_access(blobmsg_data(sid), "uci",
                              blobmsg_data(config), "read");
}
References blobmsg_data(), config, rpc_session_access(), and rpc_uci_set_savedir().
Referenced by rpc_uci_changes(), and rpc_uci_getcommon().
rpc_uci_reload()
static int rpc_uci_reload (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 1715 of file uci.c.
{
    char * const cmd[2] = { "/sbin/reload_config", NULL };
    if (!fork()) {
        /* wait for the RPC call to complete */
        sleep(2);
        return execv(cmd[0], cmd);
    }
    return 0;
}
References cmd.
Referenced by rpc_uci_api_init().
rpc_uci_rename()
static int rpc_uci_rename (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 1081 of file uci.c.
{
    struct blob_attr *tb[__RPC_R_MAX];
    struct uci_package *p = NULL;
    struct uci_ptr ptr = { 0 };
    blobmsg_parse(rpc_uci_rename_policy, __RPC_R_MAX, tb,
                  blob_data(msg), blob_len(msg));
    if (!tb[RPC_R_CONFIG] || !tb[RPC_R_SECTION] || !tb[RPC_R_NAME])
        return UBUS_STATUS_INVALID_ARGUMENT;
    if (!rpc_uci_write_access(tb[RPC_R_SESSION], tb[RPC_R_CONFIG]))
        return UBUS_STATUS_PERMISSION_DENIED;
    ptr.package = blobmsg_data(tb[RPC_R_CONFIG]);
    ptr.section = blobmsg_data(tb[RPC_R_SECTION]);
    ptr.value   = blobmsg_data(tb[RPC_R_NAME]);
    if (!rpc_uci_verify_name(ptr.value))
        return UBUS_STATUS_INVALID_ARGUMENT;
    if (tb[RPC_R_OPTION])
        ptr.option = blobmsg_data(tb[RPC_R_OPTION]);
    if (uci_load(cursor, ptr.package, &p))
        return rpc_uci_status();
    if (uci_lookup_ptr(cursor, &ptr, NULL, true))
        goto out;
    if ((ptr.option && !ptr.o) || !ptr.s)
    {
        cursor->err = UCI_ERR_NOTFOUND;
        goto out;
    }
    if (uci_rename(cursor, &ptr))
        goto out;
    uci_save(cursor, p);
out:
    uci_unload(cursor, p);
    return rpc_uci_status();
}
References __RPC_R_MAX, blob_data(), blob_len(), blobmsg_data(), blobmsg_parse(), cursor, RPC_R_CONFIG, RPC_R_NAME, RPC_R_OPTION, RPC_R_SECTION, RPC_R_SESSION, rpc_uci_rename_policy, rpc_uci_status(), rpc_uci_verify_name(), rpc_uci_write_access(), UBUS_STATUS_INVALID_ARGUMENT, and UBUS_STATUS_PERMISSION_DENIED.
Referenced by rpc_uci_api_init().
rpc_uci_replace_savedir()
static void rpc_uci_replace_savedir (const char * path) static
Definition at line 265 of file uci.c.
{
    struct uci_element *e, *tmp;
    uci_foreach_element_safe(&cursor->delta_path, tmp, e) {
        if (e->name)
            free(e->name);
        free(e);
    }
    cursor->delta_path.prev = &cursor->delta_path;
    cursor->delta_path.next = &cursor->delta_path;
    if (path)
        uci_set_savedir(cursor, path);
}
References cursor, and path.
Referenced by rpc_uci_do_rollback(), and rpc_uci_set_savedir().
rpc_uci_revert()
static int rpc_uci_revert (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 1366 of file uci.c.
{
    return rpc_uci_revert_commit(ctx, msg, false);
}
References ctx, and rpc_uci_revert_commit().
Referenced by rpc_uci_api_init().
rpc_uci_revert_commit()
static int rpc_uci_revert_commit (struct ubus_context * ctx, struct blob_attr * msg, bool commit) static
Definition at line 1324 of file uci.c.
{
    struct blob_attr *tb[__RPC_C_MAX];
    struct uci_package *p = NULL;
    struct uci_ptr ptr = { 0 };
    if (apply_sid[0])
        return UBUS_STATUS_PERMISSION_DENIED;
    blobmsg_parse(rpc_uci_config_policy, __RPC_C_MAX, tb,
                  blob_data(msg), blob_len(msg));
    if (!tb[RPC_C_CONFIG])
        return UBUS_STATUS_INVALID_ARGUMENT;
    if (!rpc_uci_write_access(tb[RPC_C_SESSION], tb[RPC_C_CONFIG]))
        return UBUS_STATUS_PERMISSION_DENIED;
    ptr.package = blobmsg_data(tb[RPC_C_CONFIG]);
    if (commit)
    {
        if (!uci_load(cursor, ptr.package, &p))
        {
            uci_commit(cursor, &p, false);
            uci_unload(cursor, p);
            rpc_uci_trigger_event(ctx, blobmsg_get_string(tb[RPC_C_CONFIG]));
        }
    }
    else
    {
        if (!uci_lookup_ptr(cursor, &ptr, NULL, true) && ptr.p)
        {
            uci_revert(cursor, &ptr);
            uci_unload(cursor, ptr.p);
        }
    }
    return rpc_uci_status();
}
References __RPC_C_MAX, apply_sid, blob_data(), blob_len(), blobmsg_data(), blobmsg_get_string(), blobmsg_parse(), ctx, cursor, RPC_C_CONFIG, RPC_C_SESSION, rpc_uci_config_policy, rpc_uci_status(), rpc_uci_trigger_event(), rpc_uci_write_access(), UBUS_STATUS_INVALID_ARGUMENT, and UBUS_STATUS_PERMISSION_DENIED.
Referenced by rpc_uci_commit(), and rpc_uci_revert().
rpc_uci_rollback()
static int rpc_uci_rollback (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 1680 of file uci.c.
{
    struct blob_attr *tb[__RPC_B_MAX];
    char tmp[PATH_MAX];
    glob_t gl;
    char *sid;
    blobmsg_parse(rpc_uci_rollback_policy, __RPC_B_MAX, tb,
                  blob_data(msg), blob_len(msg));
    if (!apply_sid[0])
        return UBUS_STATUS_NO_DATA;
    if (!tb[RPC_B_SESSION])
        return UBUS_STATUS_INVALID_ARGUMENT;
    sid = blobmsg_data(tb[RPC_B_SESSION]);
    if (strcmp(apply_sid, sid))
        return UBUS_STATUS_PERMISSION_DENIED;
    snprintf(tmp, sizeof(tmp), "%s/*", RPC_SNAPSHOT_FILES);
    if (glob(tmp, GLOB_PERIOD, NULL, &gl) < 0)
        return UBUS_STATUS_NOT_FOUND;
    rpc_uci_do_rollback(ctx, &gl);
    globfree(&gl);
    return 0;
}
References __RPC_B_MAX, apply_sid, blob_data(), blob_len(), blobmsg_data(), blobmsg_parse(), ctx, RPC_B_SESSION, RPC_SNAPSHOT_FILES, rpc_uci_do_rollback(), rpc_uci_rollback_policy, UBUS_STATUS_INVALID_ARGUMENT, UBUS_STATUS_NO_DATA, UBUS_STATUS_NOT_FOUND, and UBUS_STATUS_PERMISSION_DENIED.
Referenced by rpc_uci_api_init().
rpc_uci_set()
static int rpc_uci_set (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 875 of file uci.c.
{
    struct blob_attr *tb[__RPC_S_MAX];
    struct blob_attr *cur;
    struct uci_package *p = NULL;
    struct uci_element *e;
    struct uci_ptr ptr = { 0 };
    int rem, rv, err = 0;
    blobmsg_parse(rpc_uci_set_policy, __RPC_S_MAX, tb,
                  blob_data(msg), blob_len(msg));
    if (!tb[RPC_S_CONFIG] || !tb[RPC_S_VALUES] ||
        (!tb[RPC_S_SECTION] && !tb[RPC_S_TYPE] && !tb[RPC_S_MATCH]))
        return UBUS_STATUS_INVALID_ARGUMENT;
    if (!rpc_uci_write_access(tb[RPC_S_SESSION], tb[RPC_S_CONFIG]))
        return UBUS_STATUS_PERMISSION_DENIED;
    if (tb[RPC_S_SECTION] &&
        !rpc_uci_verify_section(blobmsg_data(tb[RPC_S_SECTION])))
        return UBUS_STATUS_INVALID_ARGUMENT;
    ptr.package = blobmsg_data(tb[RPC_S_CONFIG]);
    if (uci_load(cursor, ptr.package, &p))
        return rpc_uci_status();
    if (tb[RPC_S_SECTION])
    {
        ptr.section = blobmsg_data(tb[RPC_S_SECTION]);
        blobmsg_for_each_attr(cur, tb[RPC_S_VALUES], rem)
        {
            rv = rpc_uci_merge_set(cur, &ptr);
            if (rv)
                err = rv;
        }
    }
    else
    {
        uci_foreach_element(&p->sections, e)
        {
            if (!rpc_uci_match_section(uci_to_section(e),
                                       tb[RPC_S_TYPE], tb[RPC_S_MATCH]))
                continue;
            ptr.s = NULL;
            ptr.section = e->name;
            blobmsg_for_each_attr(cur, tb[RPC_S_VALUES], rem)
            {
                rv = rpc_uci_merge_set(cur, &ptr);
                if (rv)
                    err = rv;
            }
        }
    }
    if (!err && !ptr.s)
        err = UBUS_STATUS_NOT_FOUND;
    if (!err)
        uci_save(cursor, p);
    uci_unload(cursor, p);
    return err ? err : rpc_uci_status();
}
References __RPC_S_MAX, blob_data(), blob_len(), blobmsg_data(), blobmsg_for_each_attr, blobmsg_parse(), cursor, err, RPC_S_CONFIG, RPC_S_MATCH, RPC_S_SECTION, RPC_S_SESSION, RPC_S_TYPE, RPC_S_VALUES, rpc_uci_match_section(), rpc_uci_merge_set(), rpc_uci_set_policy, rpc_uci_status(), rpc_uci_verify_section(), rpc_uci_write_access(), UBUS_STATUS_INVALID_ARGUMENT, UBUS_STATUS_NOT_FOUND, and UBUS_STATUS_PERMISSION_DENIED.
Referenced by rpc_uci_api_init().
rpc_uci_set_savedir()
static void rpc_uci_set_savedir (struct blob_attr * sid) static
Definition at line 289 of file uci.c.
{
    char path[PATH_MAX];
    if (!sid)
    {
        rpc_uci_replace_savedir("/tmp/.uci");
        return;
    }
    snprintf(path, sizeof(path) - 1,
             RPC_UCI_SAVEDIR_PREFIX "%s", blobmsg_get_string(sid));
    rpc_uci_replace_savedir(path);
}
References blobmsg_get_string(), path, rpc_uci_replace_savedir(), and RPC_UCI_SAVEDIR_PREFIX.
Referenced by rpc_uci_apply(), rpc_uci_changes(), rpc_uci_read_access(), and rpc_uci_write_access().
rpc_uci_state()
static int rpc_uci_state (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 673 of file uci.c.
{
    return rpc_uci_getcommon(ctx, req, msg, true);
}
References ctx, and rpc_uci_getcommon().
Referenced by rpc_uci_api_init().
rpc_uci_status()
static int rpc_uci_status (void) static
Definition at line 242 of file uci.c.
{
    switch (cursor->err)
    {
    case UCI_OK:
        return UBUS_STATUS_OK;
    case UCI_ERR_INVAL:
        return UBUS_STATUS_INVALID_ARGUMENT;
    case UCI_ERR_NOTFOUND:
        return UBUS_STATUS_NOT_FOUND;
    default:
        return UBUS_STATUS_UNKNOWN_ERROR;
    }
}
References cursor, UBUS_STATUS_INVALID_ARGUMENT, UBUS_STATUS_NOT_FOUND, UBUS_STATUS_OK, and UBUS_STATUS_UNKNOWN_ERROR.
Referenced by rpc_uci_add(), rpc_uci_changes(), rpc_uci_configs(), rpc_uci_delete(), rpc_uci_getcommon(), rpc_uci_order(), rpc_uci_rename(), rpc_uci_revert_commit(), and rpc_uci_set().
rpc_uci_trigger_event()
static void rpc_uci_trigger_event (struct ubus_context * ctx, const char * config) static
Definition at line 1304 of file uci.c.
{
    char *pkg = strdup(config);
    static struct blob_buf b;
    uint32_t id;
    if (!ubus_lookup_id(ctx, "service", &id)) {
        void *c;
        blob_buf_init(&b, 0);
        blobmsg_add_string(&b, "type", "config.change");
        c = blobmsg_open_table(&b, "data");
        blobmsg_add_string(&b, "package", pkg);
        blobmsg_close_table(&b, c);
        ubus_invoke(ctx, id, "event", b.head, NULL, 0, 1000);
    }
    free(pkg);
}
References b, blob_buf_init(), blobmsg_add_string(), blobmsg_close_table(), blobmsg_open_table(), config, ctx, blob_buf::head, id, ubus_invoke(), and ubus_lookup_id().
Referenced by rpc_uci_apply_config(), and rpc_uci_revert_commit().
rpc_uci_verify_name()
static bool rpc_uci_verify_name (const char * name) static
Definition at line 218 of file uci.c.
{
    return rpc_uci_verify_str(name, false, false);
}
References blobmsg_policy::name, and rpc_uci_verify_str().
Referenced by rpc_uci_add(), rpc_uci_merge_set(), and rpc_uci_rename().
rpc_uci_verify_section()
static bool rpc_uci_verify_section (const char * section) static
Definition at line 233 of file uci.c.
{
    return rpc_uci_verify_str(section, true, false);
}
References rpc_uci_verify_str().
Referenced by rpc_uci_delete(), and rpc_uci_set().
rpc_uci_verify_str()
static bool rpc_uci_verify_str (const char * name, bool extended, bool type) static
Definition at line 188 of file uci.c.
{
    const char *c;
    char *e;
    if (!name || !*name)
        return false;
    if (extended && *name != '@')
        extended = false;
    for (c = name + extended; *c; c++)
        if (!isalnum(*c) && *c != '_' && ((!type && !extended) || *c != '-'))
            break;
    if (extended) {
        if (*c != '[')
            return false;
        strtol(++c, &e, 10);
        return (e > c && *e == ']' && *(e+1) == 0);
    }
    return (*c == 0);
}
References blobmsg_policy::name, and type.
Referenced by rpc_uci_verify_name(), rpc_uci_verify_section(), and rpc_uci_verify_type().
rpc_uci_verify_type()
static bool rpc_uci_verify_type (const char * type) static
Definition at line 225 of file uci.c.
{
    return rpc_uci_verify_str(type, false, true);
}
References rpc_uci_verify_str(), and type.
Referenced by rpc_uci_add(), and rpc_uci_delete().
rpc_uci_write_access()
static bool rpc_uci_write_access (struct blob_attr * sid, struct blob_attr * config) static
Definition at line 328 of file uci.c.
{
    rpc_uci_set_savedir(sid);
    if (!sid)
        return true;
    return rpc_session_access(blobmsg_data(sid), "uci",
                              blobmsg_data(config), "write");
}
References blobmsg_data(), config, rpc_session_access(), and rpc_uci_set_savedir().
Referenced by rpc_uci_add(), rpc_uci_delete(), rpc_uci_order(), rpc_uci_rename(), rpc_uci_revert_commit(), and rpc_uci_set().
Variable Documentation
apply_ctx
struct ubus_context* apply_ctx static
Definition at line 32 of file uci.c.
Referenced by rpc_uci_apply(), rpc_uci_apply_timeout(), rpc_uci_confirm(), and rpc_uci_do_rollback().
apply_sid
char apply_sid[RPC_SID_LEN+1]
Definition at line 34 of file uci.c.
Referenced by rpc_reclaim_apply_session(), rpc_uci_apply(), rpc_uci_confirm(), rpc_uci_do_rollback(), rpc_uci_revert_commit(), and rpc_uci_rollback().
apply_timer
struct uloop_timeout apply_timer static
Definition at line 31 of file uci.c.
Referenced by rpc_uci_apply(), rpc_uci_confirm(), and rpc_uci_do_rollback().
buf
struct blob_buf buf static
Definition at line 29 of file uci.c.
Referenced by rpc_uci_add(), rpc_uci_changes(), rpc_uci_configs(), rpc_uci_dump_change(), rpc_uci_dump_option(), rpc_uci_dump_package(), rpc_uci_dump_section(), rpc_uci_format_blob(), and rpc_uci_getcommon().
cursor
struct uci_context* cursor static
Definition at line 30 of file uci.c.
Referenced by rpc_uci_add(), rpc_uci_api_init(), rpc_uci_apply_config(), rpc_uci_changes(), rpc_uci_configs(), rpc_uci_delete(), rpc_uci_getcommon(), rpc_uci_lookup(), rpc_uci_merge_delete(), rpc_uci_merge_set(), rpc_uci_order(), rpc_uci_rename(), rpc_uci_replace_savedir(), rpc_uci_revert_commit(), rpc_uci_set(), and rpc_uci_status().
rpc_uci_add_policy
const struct blobmsg_policy rpc_uci_add_policy[__RPC_A_MAX] static
Initial value:
= {
    [RPC_A_CONFIG]  = { .name = "config",  .type = BLOBMSG_TYPE_STRING },
    [RPC_A_TYPE]    = { .name = "type",    .type = BLOBMSG_TYPE_STRING },
    [RPC_A_NAME]    = { .name = "name",    .type = BLOBMSG_TYPE_STRING },
    [RPC_A_VALUES]  = { .name = "values",  .type = BLOBMSG_TYPE_TABLE  },
    [RPC_A_SESSION] = { .name = "ubus_rpc_session",
                                           .type = BLOBMSG_TYPE_STRING },
}
Definition at line 65 of file uci.c.
{
    [RPC_A_CONFIG]  = { .name = "config",  .type = BLOBMSG_TYPE_STRING },
    [RPC_A_TYPE]    = { .name = "type",    .type = BLOBMSG_TYPE_STRING },
    [RPC_A_NAME]    = { .name = "name",    .type = BLOBMSG_TYPE_STRING },
    [RPC_A_VALUES]  = { .name = "values",  .type = BLOBMSG_TYPE_TABLE  },
    [RPC_A_SESSION] = { .name = "ubus_rpc_session",
                                           .type = BLOBMSG_TYPE_STRING },
};
Referenced by rpc_uci_add(), and rpc_uci_api_init().
rpc_uci_apply_policy
const struct blobmsg_policy rpc_uci_apply_policy[__RPC_T_MAX] static
Initial value:
= {
    [RPC_T_ROLLBACK] = { .name = "rollback", .type = BLOBMSG_TYPE_BOOL },
    [RPC_T_TIMEOUT]  = { .name = "timeout", .type = BLOBMSG_TYPE_INT32 },
    [RPC_T_SESSION]  = { .name = "ubus_rpc_session",
                                            .type = BLOBMSG_TYPE_STRING },
}
Definition at line 167 of file uci.c.
{
    [RPC_T_ROLLBACK] = { .name = "rollback", .type = BLOBMSG_TYPE_BOOL },
    [RPC_T_TIMEOUT]  = { .name = "timeout", .type = BLOBMSG_TYPE_INT32 },
    [RPC_T_SESSION]  = { .name = "ubus_rpc_session",
                                            .type = BLOBMSG_TYPE_STRING },
};
Referenced by rpc_uci_api_init(), and rpc_uci_apply().
rpc_uci_config_policy
const struct blobmsg_policy rpc_uci_config_policy[__RPC_C_MAX] static
Initial value:
= {
    [RPC_C_CONFIG]   = { .name = "config",  .type = BLOBMSG_TYPE_STRING },
    [RPC_C_SESSION]  = { .name = "ubus_rpc_session",
                                            .type = BLOBMSG_TYPE_STRING },
}
Definition at line 154 of file uci.c.
{
    [RPC_C_CONFIG]   = { .name = "config",  .type = BLOBMSG_TYPE_STRING },
    [RPC_C_SESSION]  = { .name = "ubus_rpc_session",
                                            .type = BLOBMSG_TYPE_STRING },
};
Referenced by rpc_uci_api_init(), rpc_uci_changes(), and rpc_uci_revert_commit().
rpc_uci_delete_policy
const struct blobmsg_policy rpc_uci_delete_policy[__RPC_D_MAX] static
Initial value:
= {
    [RPC_D_CONFIG]  = { .name = "config",   .type = BLOBMSG_TYPE_STRING },
    [RPC_D_SECTION] = { .name = "section",  .type = BLOBMSG_TYPE_STRING },
    [RPC_D_TYPE]    = { .name = "type",     .type = BLOBMSG_TYPE_STRING },
    [RPC_D_MATCH]   = { .name = "match",    .type = BLOBMSG_TYPE_TABLE  },
    [RPC_D_OPTION]  = { .name = "option",   .type = BLOBMSG_TYPE_STRING },
    [RPC_D_OPTIONS] = { .name = "options",  .type = BLOBMSG_TYPE_ARRAY  },
    [RPC_D_SESSION] = { .name = "ubus_rpc_session",
                                            .type = BLOBMSG_TYPE_STRING },
}
Definition at line 105 of file uci.c.
{
    [RPC_D_CONFIG]  = { .name = "config",   .type = BLOBMSG_TYPE_STRING },
    [RPC_D_SECTION] = { .name = "section",  .type = BLOBMSG_TYPE_STRING },
    [RPC_D_TYPE]    = { .name = "type",     .type = BLOBMSG_TYPE_STRING },
    [RPC_D_MATCH]   = { .name = "match",    .type = BLOBMSG_TYPE_TABLE  },
    [RPC_D_OPTION]  = { .name = "option",   .type = BLOBMSG_TYPE_STRING },
    [RPC_D_OPTIONS] = { .name = "options",  .type = BLOBMSG_TYPE_ARRAY  },
    [RPC_D_SESSION] = { .name = "ubus_rpc_session",
                                            .type = BLOBMSG_TYPE_STRING },
};
Referenced by rpc_uci_api_init(), and rpc_uci_delete().
rpc_uci_get_policy
const struct blobmsg_policy rpc_uci_get_policy[__RPC_G_MAX] static
Initial value:
= {
    [RPC_G_CONFIG]  = { .name = "config",  .type = BLOBMSG_TYPE_STRING },
    [RPC_G_SECTION] = { .name = "section", .type = BLOBMSG_TYPE_STRING },
    [RPC_G_OPTION]  = { .name = "option",  .type = BLOBMSG_TYPE_STRING },
    [RPC_G_TYPE]    = { .name = "type",    .type = BLOBMSG_TYPE_STRING },
    [RPC_G_MATCH]   = { .name = "match",   .type = BLOBMSG_TYPE_TABLE  },
    [RPC_G_SESSION] = { .name = "ubus_rpc_session",
                                           .type = BLOBMSG_TYPE_STRING },
}
Definition at line 46 of file uci.c.
{
    [RPC_G_CONFIG]  = { .name = "config",  .type = BLOBMSG_TYPE_STRING },
    [RPC_G_SECTION] = { .name = "section", .type = BLOBMSG_TYPE_STRING },
    [RPC_G_OPTION]  = { .name = "option",  .type = BLOBMSG_TYPE_STRING },
    [RPC_G_TYPE]    = { .name = "type",    .type = BLOBMSG_TYPE_STRING },
    [RPC_G_MATCH]   = { .name = "match",   .type = BLOBMSG_TYPE_TABLE  },
    [RPC_G_SESSION] = { .name = "ubus_rpc_session",
                                           .type = BLOBMSG_TYPE_STRING },
};
Referenced by rpc_uci_api_init(), and rpc_uci_getcommon().
rpc_uci_order_policy
const struct blobmsg_policy rpc_uci_order_policy[__RPC_O_MAX] static
Initial value:
= {
    [RPC_O_CONFIG]   = { .name = "config",   .type = BLOBMSG_TYPE_STRING },
    [RPC_O_SECTIONS] = { .name = "sections", .type = BLOBMSG_TYPE_ARRAY  },
    [RPC_O_SESSION]  = { .name = "ubus_rpc_session",
                                             .type = BLOBMSG_TYPE_STRING },
}
Definition at line 141 of file uci.c.
{
    [RPC_O_CONFIG]   = { .name = "config",   .type = BLOBMSG_TYPE_STRING },
    [RPC_O_SECTIONS] = { .name = "sections", .type = BLOBMSG_TYPE_ARRAY  },
    [RPC_O_SESSION]  = { .name = "ubus_rpc_session",
                                             .type = BLOBMSG_TYPE_STRING },
};
Referenced by rpc_uci_api_init(), and rpc_uci_order().
rpc_uci_rename_policy
const struct blobmsg_policy rpc_uci_rename_policy[__RPC_R_MAX] static
Initial value:
= {
    [RPC_R_CONFIG]  = { .name = "config",   .type = BLOBMSG_TYPE_STRING },
    [RPC_R_SECTION] = { .name = "section",  .type = BLOBMSG_TYPE_STRING },
    [RPC_R_OPTION]  = { .name = "option",   .type = BLOBMSG_TYPE_STRING },
    [RPC_R_NAME]    = { .name = "name",     .type = BLOBMSG_TYPE_STRING },
    [RPC_R_SESSION] = { .name = "ubus_rpc_session",
                                            .type = BLOBMSG_TYPE_STRING },
}
Definition at line 125 of file uci.c.
{
    [RPC_R_CONFIG]  = { .name = "config",   .type = BLOBMSG_TYPE_STRING },
    [RPC_R_SECTION] = { .name = "section",  .type = BLOBMSG_TYPE_STRING },
    [RPC_R_OPTION]  = { .name = "option",   .type = BLOBMSG_TYPE_STRING },
    [RPC_R_NAME]    = { .name = "name",     .type = BLOBMSG_TYPE_STRING },
    [RPC_R_SESSION] = { .name = "ubus_rpc_session",
                                            .type = BLOBMSG_TYPE_STRING },
};
Referenced by rpc_uci_api_init(), and rpc_uci_rename().
rpc_uci_rollback_policy
const struct blobmsg_policy rpc_uci_rollback_policy[__RPC_B_MAX] static
Initial value:
= {
    [RPC_B_SESSION]  = { .name = "ubus_rpc_session",
                                            .type = BLOBMSG_TYPE_STRING },
}
Definition at line 179 of file uci.c.
{
    [RPC_B_SESSION]  = { .name = "ubus_rpc_session",
                                            .type = BLOBMSG_TYPE_STRING },
};
Referenced by rpc_uci_api_init(), rpc_uci_confirm(), and rpc_uci_rollback().
rpc_uci_set_policy
const struct blobmsg_policy rpc_uci_set_policy[__RPC_S_MAX] static
Initial value:
= {
    [RPC_S_CONFIG]  = { .name = "config",   .type = BLOBMSG_TYPE_STRING },
    [RPC_S_SECTION] = { .name = "section",  .type = BLOBMSG_TYPE_STRING },
    [RPC_S_TYPE]    = { .name = "type",     .type = BLOBMSG_TYPE_STRING },
    [RPC_S_MATCH]   = { .name = "match",    .type = BLOBMSG_TYPE_TABLE  },
    [RPC_S_VALUES]  = { .name = "values",   .type = BLOBMSG_TYPE_TABLE  },
    [RPC_S_SESSION] = { .name = "ubus_rpc_session",
                                            .type = BLOBMSG_TYPE_STRING },
}
Definition at line 84 of file uci.c.
{
    [RPC_S_CONFIG]  = { .name = "config",   .type = BLOBMSG_TYPE_STRING },
    [RPC_S_SECTION] = { .name = "section",  .type = BLOBMSG_TYPE_STRING },
    [RPC_S_TYPE]    = { .name = "type",     .type = BLOBMSG_TYPE_STRING },
    [RPC_S_MATCH]   = { .name = "match",    .type = BLOBMSG_TYPE_TABLE  },
    [RPC_S_VALUES]  = { .name = "values",   .type = BLOBMSG_TYPE_TABLE  },
    [RPC_S_SESSION] = { .name = "ubus_rpc_session",
                                            .type = BLOBMSG_TYPE_STRING },
};
Referenced by rpc_uci_api_init(), and rpc_uci_set().