zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/ubus/ubus_common.h File Reference
ubus_common.h File Reference
#include <stdbool.h>
Macros
#define UBUS_SIGNATURE_METHOD (BLOBMSG_TYPE_LAST + 1)
#define UBUS_SIGNATURE_END (BLOBMSG_TYPE_LAST + 2)
Functions
static bool ubus_strmatch_len (const char *s1, const char *s2, int *len)
Macro Definition Documentation
UBUS_SIGNATURE_END
#define UBUS_SIGNATURE_END (BLOBMSG_TYPE_LAST + 2)
Definition at line 20 of file ubus_common.h.
UBUS_SIGNATURE_METHOD
#define UBUS_SIGNATURE_METHOD (BLOBMSG_TYPE_LAST + 1)
Definition at line 19 of file ubus_common.h.
Function Documentation
ubus_strmatch_len()
static bool ubus_strmatch_len (const char * s1, const char * s2, int * len) inline static
Definition at line 22 of file ubus_common.h.
{
    for (*len = 0; s1[*len] == s2[*len]; (*len)++)
        if (!s1[*len])
            return true;
    return false;
}
Referenced by ubusd_acl_check(), ubusd_reply_add(), and ubusd_send_event().