zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/watchdog.h File Reference
watchdog.h File Reference
#include <stdbool.h>
Functions
void watchdog_init (int preinit)
char * watchdog_fd (void)
int watchdog_timeout (int timeout)
int watchdog_frequency (int frequency)
void watchdog_set_magicclose (bool val)
bool watchdog_get_magicclose (void)
void watchdog_set_stopped (bool val)
bool watchdog_get_stopped (void)
void watchdog_set_cloexec (bool val)
void watchdog_ping (void)
Function Documentation
watchdog_fd()
char * watchdog_fd (void)
Definition at line 179 of file watchdog.c.
{
    static char fd_buf[12];
    if (wdt_fd < 0)
        return NULL;
    snprintf(fd_buf, sizeof(fd_buf), "%d", wdt_fd);
    return fd_buf;
}
References wdt_fd.
Referenced by spawn_procd(), sysupgrade_exec_upgraded(), and watchdog_set().
watchdog_frequency()
int watchdog_frequency (int frequency)
Definition at line 169 of file watchdog.c.
{
    if (frequency) {
        DEBUG(4, "Set watchdog frequency: %ds\n", frequency);
        wdt_frequency = frequency;
    }
    return wdt_frequency;
}
References DEBUG, and wdt_frequency.
Referenced by watchdog_set().
watchdog_get_magicclose()
bool watchdog_get_magicclose (void)
Definition at line 132 of file watchdog.c.
{
    return wdt_magicclose;
}
References wdt_magicclose.
Referenced by watchdog_set().
watchdog_get_stopped()
bool watchdog_get_stopped (void)
Definition at line 151 of file watchdog.c.
{
    return !wdt_timeout.pending;
}
References uloop_timeout::pending, and wdt_timeout.
Referenced by watchdog_set().
watchdog_init()
void watchdog_init (int preinit)
Definition at line 191 of file watchdog.c.
{
    wdt_timeout.cb = watchdog_timeout_cb;
    if (watchdog_open(!preinit) < 0)
        return;
    LOG("- watchdog -\n");
    watchdog_set_drv_timeout();
    watchdog_timeout_cb(&wdt_timeout);
    DEBUG(4, "Opened watchdog with timeout %ds\n", watchdog_timeout(0));
    watchdog_print_status();
}
References uloop_timeout::cb, DEBUG, LOG, preinit(), watchdog_open(), watchdog_print_status(), watchdog_set_drv_timeout(), watchdog_timeout(), watchdog_timeout_cb(), and wdt_timeout.
Referenced by main(), and state_enter().
watchdog_ping()
void watchdog_ping (void)
Definition at line 37 of file watchdog.c.
{
    DEBUG(4, "Ping\n");
    if (wdt_fd >= 0 && write(wdt_fd, "X", 1) < 0)
        ERROR("WDT failed to write: %m\n");
}
References DEBUG, ERROR, and wdt_fd.
Referenced by main(), and watchdog_timeout_cb().
watchdog_set_cloexec()
void watchdog_set_cloexec (bool val)
Definition at line 208 of file watchdog.c.
{
    if (wdt_fd < 0)
        return;
    int flags = fcntl(wdt_fd, F_GETFD);
    if (val)
        flags |= FD_CLOEXEC;
    else
        flags &= ~FD_CLOEXEC;
    fcntl(wdt_fd, F_SETFD,  flags);
}
References wdt_fd.
Referenced by sysupgrade_exec_upgraded().
watchdog_set_magicclose()
void watchdog_set_magicclose (bool val)
Definition at line 127 of file watchdog.c.
{
    wdt_magicclose = val;
}
References wdt_magicclose.
Referenced by watchdog_set().
watchdog_set_stopped()
void watchdog_set_stopped (bool val)
Definition at line 137 of file watchdog.c.
{
    if (val) {
        uloop_timeout_cancel(&wdt_timeout);
        watchdog_close(wdt_magicclose);
    }
    else {
        watchdog_open(true);
        watchdog_set_drv_timeout();
        watchdog_timeout_cb(&wdt_timeout);
    }
}
References uloop_timeout_cancel(), watchdog_close(), watchdog_open(), watchdog_set_drv_timeout(), watchdog_timeout_cb(), wdt_magicclose, and wdt_timeout.
Referenced by watchdog_set().
watchdog_timeout()
int watchdog_timeout (int timeout)
Definition at line 156 of file watchdog.c.
{
    if (timeout) {
        DEBUG(4, "Set watchdog timeout: %ds\n", timeout);
        wdt_drv_timeout = timeout;
        if (wdt_fd >= 0)
            watchdog_set_drv_timeout();
    }
    return wdt_drv_timeout;
}
References DEBUG, timeout, watchdog_set_drv_timeout(), wdt_drv_timeout, and wdt_fd.
Referenced by watchdog_init(), and watchdog_set().