zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/service/validate.c File Reference
validate.c File Reference
#include <libubox/blobmsg_json.h>
#include <libubox/avl-cmp.h>
#include <json-c/json.h>
#include "../procd.h"
#include "service.h"
Enumerations
enum { SERVICE_VAL_PACKAGE , SERVICE_VAL_TYPE , SERVICE_VAL_DATA , __SERVICE_VAL_MAX }
Functions
static AVL_TREE (validators, avl_strcmp, true, NULL)
void service_validate_dump_all (struct blob_buf *b, char *p, char *s)
void service_validate_dump (struct blob_buf *b, struct service *s)
void service_validate_del (struct service *s)
void service_validate_add (struct service *s, struct blob_attr *msg)
Variables
static const struct blobmsg_policy service_validate_attrs [__SERVICE_VAL_MAX]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SERVICE_VAL_PACKAGE
SERVICE_VAL_TYPE
SERVICE_VAL_DATA
__SERVICE_VAL_MAX
Definition at line 22 of file validate.c.
     {
    SERVICE_VAL_PACKAGE,
    SERVICE_VAL_TYPE,
    SERVICE_VAL_DATA,
    __SERVICE_VAL_MAX
};
Function Documentation
AVL_TREE()
static AVL_TREE (validators , avl_strcmp , true , NULL) static
service_validate_add()
void service_validate_add (struct service * s, struct blob_attr * msg)
Definition at line 115 of file validate.c.
{
    struct blob_attr *tb[__SERVICE_VAL_MAX];
    struct validate *v;
    char *type, *package;
    struct blob_attr *cur;
    int rem;
    blobmsg_parse(service_validate_attrs, __SERVICE_VAL_MAX, tb, blobmsg_data(msg), blobmsg_data_len(msg));
    if (!tb[SERVICE_VAL_PACKAGE] || !tb[SERVICE_VAL_TYPE] || !tb[SERVICE_VAL_DATA])
        return;
    v = calloc_a(sizeof(*v), &package, blobmsg_data_len(tb[SERVICE_VAL_PACKAGE]) + 1,
             &type, blobmsg_data_len(tb[SERVICE_VAL_TYPE]) + 1);
    if (!v)
        return;
    v->type = type;
    v->avl.key = v->package = package;
    strcpy(v->package, blobmsg_get_string(tb[SERVICE_VAL_PACKAGE]));
    strcpy(v->type, blobmsg_get_string(tb[SERVICE_VAL_TYPE]));
    list_add(&v->list, &s->validators);
    if (avl_insert(&validators, &v->avl)) {
        free(v);
        return;
    }
    avl_init(&v->rules, avl_strcmp, false, NULL);
    blobmsg_for_each_attr(cur, tb[SERVICE_VAL_DATA], rem) {
        char *option;
        char *rule;
        struct vrule *vr = calloc_a(sizeof(*vr), &option, strlen(blobmsg_name(cur)) + 1,
            &rule, strlen(blobmsg_get_string(cur)) + 1);
        vr->avl.key = vr->option = option;
        vr->rule = rule;
        strcpy(vr->option, blobmsg_name(cur));
        strcpy(vr->rule, blobmsg_get_string(cur));
        if (avl_insert(&v->rules, &vr->avl))
            free(vr);
    }
}
References __SERVICE_VAL_MAX, validate::avl, vrule::avl, avl_init(), avl_insert(), avl_strcmp(), blobmsg_data(), blobmsg_data_len(), blobmsg_for_each_attr, blobmsg_get_string(), blobmsg_name(), blobmsg_parse(), calloc_a, avl_node::key, validate::list, list_add(), vrule::option, validate::package, vrule::rule, validate::rules, SERVICE_VAL_DATA, SERVICE_VAL_PACKAGE, SERVICE_VAL_TYPE, service_validate_attrs, type, validate::type, and service::validators.
Referenced by service_update().
service_validate_del()
void service_validate_del (struct service * s)
Definition at line 95 of file validate.c.
{
    struct validate *v, *n;
    if (list_empty(&s->validators))
        return;
        list_for_each_entry_safe(v, n, &s->validators, list) {
        struct vrule *vr, *a;
        avl_remove_all_elements(&v->rules, vr, avl, a)
            free(vr);
        avl_delete(&validators, &v->avl);
        list_del(&v->list);
        free(v);
    }
}
References validate::avl, vrule::avl, avl_delete(), avl_remove_all_elements, validate::list, list_del(), list_empty(), list_for_each_entry_safe, validate::rules, and service::validators.
Referenced by service_stopped(), and service_update().
service_validate_dump()
void service_validate_dump (struct blob_buf * b, struct service * s)
Definition at line 74 of file validate.c.
{
    struct validate *v;
    void *i = blobmsg_open_array(b, "validate");
        list_for_each_entry(v, &s->validators, list) {
        struct vrule *vr;
        void *k, *j = blobmsg_open_table(b, "validate");
        blobmsg_add_string(b, "package", v->package);
                blobmsg_add_string(b, "type", v->type);
        k = blobmsg_open_table(b, "rules");
        avl_for_each_element(&v->rules, vr, avl)
                    blobmsg_add_string(b, vr->option, vr->rule);
        blobmsg_close_table(b, k);
        blobmsg_close_table(b, j);
    }
    blobmsg_close_array(b, i);
}
References vrule::avl, avl_for_each_element, b, blobmsg_add_string(), blobmsg_close_array(), blobmsg_close_table(), blobmsg_open_array(), blobmsg_open_table(), validate::list, list_for_each_entry, vrule::option, validate::package, vrule::rule, validate::rules, validate::type, and service::validators.
Referenced by service_dump().
service_validate_dump_all()
void service_validate_dump_all (struct blob_buf * b, char * p, char * s)
Definition at line 38 of file validate.c.
{
    struct json_object *r = json_object_new_object();
    struct validate *v;
    if (!r)
        return;
    avl_for_each_element(&validators, v, avl) {
        struct json_object *o, *t;
        struct vrule *vr;
        if (p && strcmp(p, v->package))
            continue;
        if (s && strcmp(s, v->type))
            continue;
        json_object_object_get_ex(r, v->package, &o);
        if (!o) {
            o = json_object_new_object();
            json_object_object_add(r, v->package, o);
        }
        json_object_object_get_ex(o, v->type, &t);
        if (!t) {
            t = json_object_new_object();
            json_object_object_add(o, v->type, t);
        }
        avl_for_each_element(&v->rules, vr, avl)
            json_object_object_add(t, vr->option, json_object_new_string(vr->rule));
    }
    blobmsg_add_object(b, r);
    json_object_put(r);
}
References validate::avl, vrule::avl, avl_for_each_element, b, blobmsg_add_object(), vrule::option, validate::package, r, vrule::rule, validate::rules, and validate::type.
Referenced by service_handle_validate().
Variable Documentation
service_validate_attrs
const struct blobmsg_policy service_validate_attrs[__SERVICE_VAL_MAX] static
Initial value:
= {
    [SERVICE_VAL_PACKAGE] = { "package", BLOBMSG_TYPE_STRING },
    [SERVICE_VAL_TYPE] = { "type", BLOBMSG_TYPE_STRING },
    [SERVICE_VAL_DATA] = { "data", BLOBMSG_TYPE_TABLE },
}
Definition at line 29 of file validate.c.
{
    [SERVICE_VAL_PACKAGE] = { "package", BLOBMSG_TYPE_STRING },
    [SERVICE_VAL_TYPE] = { "type", BLOBMSG_TYPE_STRING },
    [SERVICE_VAL_DATA] = { "data", BLOBMSG_TYPE_TABLE },
};
Referenced by service_validate_add().