zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/ustp/mstp.h File Reference
mstp.h File Reference
#include <sys/types.h>
#include <stdlib.h>
#include <libubox/list.h>
#include "bridge_ctl.h"
Classes
union bridge_identifier_t
struct __attribute__
struct port_priority_vector_t
struct times_t
struct bridge_t
struct tree_t
struct port_t
struct per_tree_port_t
struct CIST_BridgeStatus
struct MSTI_BridgeStatus
struct CIST_BridgeConfig
struct CIST_PortStatus
struct MSTI_PortStatus
struct CIST_PortConfig
struct MSTI_PortConfig
Macros
#define COUNT_OF(x)
#define assign(x, y)
#define _ncmp(x, y)
#define cmp(x, _op, y)
#define HMAC_KEY
#define MAX_PORT_NUMBER 4095
#define MAX_VID 4094
#define MAX_FID 4095
#define MAX_MSTID 4094
#define MAX_STANDARD_MSTIS 64
#define MAX_IMPLEMENTATION_MSTIS 63
#define MAX_PATH_COST 200000000u
#define GET_PRIORITY_FROM_IDENTIFIER(id)
#define SET_PRIORITY_IN_IDENTIFIER(pri, id)
#define CONFIGURATION_NAME_LEN 32
#define CONFIGURATION_DIGEST_LEN 16
#define TCN_BPDU_SIZE offsetof(bpdu_t, flags)
#define CONFIG_BPDU_SIZE offsetof(bpdu_t, version1_len)
#define RST_BPDU_SIZE offsetof(bpdu_t, version3_len)
#define MST_BPDU_SIZE_WO_MSTI_MSGS offsetof(bpdu_t, mstConfiguration)
#define MST_BPDU_VER3LEN_WO_MSTI_MSGS
#define offsetMaster offsetTcAck
#define BPDU_FLAGS_ROLE_SET(role)
#define BPDU_FLAGS_ROLE_GET(flags)
#define GET_CIST_TREE(br)
#define GET_CIST_PTP_FROM_PORT(prt)
Typedefs
typedef __be16 port_identifier_t
Enumerations
enum port_info_t {
OtherInfo , SuperiorDesignatedInfo , RepeatedDesignatedInfo , InferiorDesignatedInfo ,
InferiorRootAlternateInfo
}
enum port_info_origin_t { ioDisabled , ioMine , ioAged , ioReceived }
enum port_role_t {
roleDisabled , roleRoot , roleDesignated , roleAlternate ,
roleBackup , roleMaster
}
enum port_encoded_role_t { encodedRoleMaster = 0 , encodedRoleAlternateBackup = 1 , encodedRoleRoot = 2 , encodedRoleDesignated = 3 }
enum protocol_version_t { protoSTP = 0 , protoRSTP = 2 , protoMSTP = 3 }
enum bpduType_t { bpduTypeConfig = 0 , bpduTypeRST = 2 , bpduTypeTCN = 128 }
enum bpduFlagOffset_t {
offsetTc = 0 , offsetProposal = 1 , offsetRole = 2 , offsetRole1 = 3 ,
offsetLearnig = 4 , offsetForwarding = 5 , offsetAgreement = 6 , offsetTcAck
}
enum admin_p2p_t { p2pAuto , p2pForceTrue , p2pForceFalse }
enum PRSM_states_t { PRSM_DISCARD , PRSM_RECEIVE }
enum PPMSM_states_t { PPMSM_CHECKING_RSTP , PPMSM_SELECTING_STP , PPMSM_SENSING }
enum BDSM_states_t { BDSM_EDGE , BDSM_NOT_EDGE }
enum PTSM_states_t {
PTSM_TRANSMIT_INIT , PTSM_TRANSMIT_CONFIG , PTSM_TRANSMIT_TCN , PTSM_TRANSMIT_RSTP ,
PTSM_TRANSMIT_PERIODIC , PTSM_IDLE
}
enum PISM_states_t {
PISM_DISABLED , PISM_AGED , PISM_UPDATE , PISM_SUPERIOR_DESIGNATED ,
PISM_REPEATED_DESIGNATED , PISM_INFERIOR_DESIGNATED , PISM_NOT_DESIGNATED , PISM_OTHER ,
PISM_CURRENT , PISM_RECEIVE
}
enum PRSSM_states_t { PRSSM_INIT_TREE , PRSSM_ROLE_SELECTION }
enum PRTSM_states_t {
PRTSM_INIT_PORT , PRTSM_DISABLE_PORT , PRTSM_DISABLED_PORT , PRTSM_MASTER_PROPOSED ,
PRTSM_MASTER_AGREED , PRTSM_MASTER_SYNCED , PRTSM_MASTER_RETIRED , PRTSM_MASTER_FORWARD ,
PRTSM_MASTER_LEARN , PRTSM_MASTER_DISCARD , PRTSM_MASTER_PORT , PRTSM_ROOT_PROPOSED ,
PRTSM_ROOT_AGREED , PRTSM_ROOT_SYNCED , PRTSM_REROOT , PRTSM_ROOT_FORWARD ,
PRTSM_ROOT_LEARN , PRTSM_REROOTED , PRTSM_ROOT_PORT , PRTSM_DESIGNATED_PROPOSE ,
PRTSM_DESIGNATED_AGREED , PRTSM_DESIGNATED_SYNCED , PRTSM_DESIGNATED_RETIRED , PRTSM_DESIGNATED_FORWARD ,
PRTSM_DESIGNATED_LEARN , PRTSM_DESIGNATED_DISCARD , PRTSM_DESIGNATED_PORT , PRTSM_BLOCK_PORT ,
PRTSM_BACKUP_PORT , PRTSM_ALTERNATE_PROPOSED , PRTSM_ALTERNATE_AGREED , PRTSM_ALTERNATE_PORT
}
enum PSTSM_states_t { PSTSM_DISCARDING , PSTSM_LEARNING , PSTSM_FORWARDING }
enum TCSM_states_t {
TCSM_INACTIVE , TCSM_LEARNING , TCSM_DETECTED , TCSM_NOTIFIED_TCN ,
TCSM_NOTIFIED_TC , TCSM_PROPAGATING , TCSM_ACKNOWLEDGED , TCSM_ACTIVE
}
Functions
void hmac_md5 (unsigned char *text, int text_len, unsigned char *key, int key_len, caddr_t digest)
bool MSTP_IN_bridge_create (bridge_t *br, __u8 *macaddr)
bool MSTP_IN_port_create_and_add_tail (port_t *prt, __u16 portno)
void MSTP_IN_delete_port (port_t *prt)
void MSTP_IN_delete_bridge (bridge_t *br)
void MSTP_IN_set_bridge_address (bridge_t *br, __u8 *macaddr)
void MSTP_IN_set_bridge_enable (bridge_t *br, bool up)
void MSTP_IN_set_port_enable (port_t *prt, bool up, int speed, int duplex)
void MSTP_IN_one_second (bridge_t *br)
void MSTP_IN_all_fids_flushed (per_tree_port_t *ptp)
void MSTP_IN_rx_bpdu (port_t *prt, bpdu_t *bpdu, int size)
bool MSTP_IN_set_vid2fid (bridge_t *br, __u16 vid, __u16 fid)
bool MSTP_IN_set_all_vids2fids (bridge_t *br, __u16 *vids2fids)
bool MSTP_IN_set_fid2mstid (bridge_t *br, __u16 fid, __u16 mstid)
bool MSTP_IN_set_all_fids2mstids (bridge_t *br, __u16 *fids2mstids)
bool MSTP_IN_get_mstilist (bridge_t *br, int *num_mstis, __u16 *mstids)
bool MSTP_IN_create_msti (bridge_t *br, __u16 mstid)
bool MSTP_IN_delete_msti (bridge_t *br, __u16 mstid)
void MSTP_IN_set_mst_config_id (bridge_t *br, __u16 revision, __u8 *name)
void MSTP_OUT_set_state (per_tree_port_t *ptp, int new_state)
void MSTP_OUT_flush_all_fids (per_tree_port_t *ptp)
void MSTP_OUT_set_ageing_time (port_t *prt, unsigned int ageingTime)
void MSTP_OUT_tx_bpdu (port_t *prt, bpdu_t *bpdu, int size)
void MSTP_OUT_shutdown_port (port_t *prt)
void MSTP_IN_get_cist_bridge_status (bridge_t *br, CIST_BridgeStatus *status)
void MSTP_IN_get_msti_bridge_status (tree_t *tree, MSTI_BridgeStatus *status)
int MSTP_IN_set_cist_bridge_config (bridge_t *br, CIST_BridgeConfig *cfg)
int MSTP_IN_set_msti_bridge_config (tree_t *tree, __u8 bridge_priority)
void MSTP_IN_get_cist_port_status (port_t *prt, CIST_PortStatus *status)
void MSTP_IN_get_msti_port_status (per_tree_port_t *ptp, MSTI_PortStatus *status)
int MSTP_IN_set_cist_port_config (port_t *prt, CIST_PortConfig *cfg)
int MSTP_IN_set_msti_port_config (per_tree_port_t *ptp, MSTI_PortConfig *cfg)
int MSTP_IN_port_mcheck (port_t *prt)
Variables
__be16 priority
__u8 mac_address [ETH_ALEN]
__u8 selector
__u8 configuration_name [CONFIGURATION_NAME_LEN]
__be16 revision_level
__u8 configuration_digest [CONFIGURATION_DIGEST_LEN]
Class Documentation
port_priority_vector_t
struct port_priority_vector_t
Definition at line 99 of file mstp.h.
Class Members
bridge_identifier_t DesignatedBridgeID
port_identifier_t DesignatedPortID
__be32 ExtRootPathCost
__be32 IntRootPathCost
bridge_identifier_t RootID
bridge_identifier_t RRootID
times_t
struct times_t
Definition at line 110 of file mstp.h.
Class Members
__u8 Forward_Delay
__u8 Hello_Time
__u8 Max_Age
__u8 Message_Age
__u8 remainingHops
bridge_t
struct bridge_t
Definition at line 373 of file mstp.h.
Class Members
unsigned int Ageing_Time
bool bridgeEnabled
__be16 fid2mstid[MAX_FID+1]
protocol_version_t ForceProtocolVersion
__u8 Forward_Delay
__u8 Hello_Time
struct list_head list
__u8 Max_Age
__u8 MaxHops
unsigned int Migrate_Time
mst_configuration_identifier_t MstConfigId
struct list_head ports
sysdep_br_data_t sysdeps
unsigned int Transmit_Hold_Count
struct list_head trees
unsigned int uptime
__u16 vid2fid[MAX_VID+1]
tree_t
struct tree_t
Definition at line 409 of file mstp.h.
Class Members
bridge_t * bridge
struct list_head bridge_list
bridge_identifier_t BridgeIdentifier
port_priority_vector_t BridgePriority
times_t BridgeTimes
char last_topology_change_port[IFNAMSIZ]
__be16 MSTID
struct list_head ports
PRSSM_states_t PRSSM_state
port_identifier_t rootPortId
port_priority_vector_t rootPriority
times_t rootTimes
unsigned int time_since_topology_change
bool topology_change
unsigned int topology_change_count
char topology_change_port[IFNAMSIZ]
port_t
struct port_t
Definition at line 443 of file mstp.h.
Class Members
bool AdminEdgePort
__u32 AdminExternalPortPathCost
admin_p2p_t AdminP2P
bool AutoEdge
bool BaInconsistent
BDSM_states_t BDSM_state
bool bpduFilterPort
bool BpduGuardError
bool BpduGuardPort
struct list_head br_list
unsigned int brAssuRcvdInfoWhile
bridge_t * bridge
bool deleted
bool dontTxmtBpdu
unsigned int edgeDelayWhile
__u32 ExternalPortPathCost
unsigned int helloWhen
bool infoInternal
bool mcheck
unsigned int mdelayWhile
bool NetworkPort
bool newInfo
bool newInfoMsti
unsigned int num_rx_bpdu
unsigned int num_rx_bpdu_filtered
unsigned int num_rx_tcn
unsigned int num_trans_blk
unsigned int num_trans_fwd
unsigned int num_tx_bpdu
unsigned int num_tx_tcn
bool operEdge
bool operPointToPointMAC
__be16 port_number
bool portEnabled
PPMSM_states_t PPMSM_state
PRSM_states_t PRSM_state
PTSM_states_t PTSM_state
unsigned int rapidAgeingWhile
bool rcvdBpdu
bpdu_t rcvdBpduData
int rcvdBpduNumOfMstis
bool rcvdInternal
bool rcvdRSTP
bool rcvdSTP
bool rcvdTcAck
bool rcvdTcn
bool restrictedRole
bool restrictedTcn
bool sendRSTP
sysdep_if_data_t sysdeps
bool tcAck
struct list_head trees
unsigned int txCount
per_tree_port_t
struct per_tree_port_t
Definition at line 507 of file mstp.h.
Class Members
__u32 AdminInternalPortPathCost
bool agree
bool agreed
bool calledFromFlushRoutine
port_priority_vector_t designatedPriority
times_t designatedTimes
bool disputed
bool fdbFlush
unsigned int fdWhile
bool forward
bool forwarding
port_info_origin_t infoIs
__u32 InternalPortPathCost
bool learn
bool learning
bool master
bool mastered
port_priority_vector_t msgPriority
times_t msgTimes
__be16 MSTID
PISM_states_t PISM_state
port_t * port
struct list_head port_list
port_identifier_t portId
port_priority_vector_t portPriority
times_t portTimes
bool proposed
bool proposing
PRTSM_states_t PRTSM_state
PSTSM_states_t PSTSM_state
unsigned int rbWhile
port_info_t rcvdInfo
unsigned int rcvdInfoWhile
bool rcvdMsg
msti_configuration_message_t * rcvdMstiConfig
bool rcvdTc
bool reRoot
bool reselect
port_role_t role
unsigned int rrWhile
bool selected
port_role_t selectedRole
unsigned int start_time
int state
bool sync
bool synced
bool tcProp
TCSM_states_t TCSM_state
unsigned int tcWhile
tree_t * tree
struct list_head tree_list
bool updtInfo
CIST_BridgeStatus
struct CIST_BridgeStatus
Definition at line 594 of file mstp.h.
Class Members
unsigned int Ageing_Time
__u8 bridge_forward_delay
__u8 bridge_hello_time
bridge_identifier_t bridge_id
__u8 bridge_max_age
bridge_identifier_t designated_root
bool enabled
unsigned int internal_path_cost
char last_topology_change_port[IFNAMSIZ]
__u8 max_hops
protocol_version_t protocol_version
bridge_identifier_t regional_root
__u8 root_forward_delay
__u8 root_max_age
unsigned int root_path_cost
port_identifier_t root_port_id
unsigned int time_since_topology_change
bool topology_change
unsigned int topology_change_count
char topology_change_port[IFNAMSIZ]
unsigned int tx_hold_count
MSTI_BridgeStatus
struct MSTI_BridgeStatus
Definition at line 622 of file mstp.h.
Class Members
bridge_identifier_t bridge_id
unsigned int internal_path_cost
char last_topology_change_port[IFNAMSIZ]
bridge_identifier_t regional_root
port_identifier_t root_port_id
unsigned int time_since_topology_change
bool topology_change
unsigned int topology_change_count
char topology_change_port[IFNAMSIZ]
CIST_BridgeConfig
struct CIST_BridgeConfig
Definition at line 638 of file mstp.h.
Class Members
unsigned int bridge_ageing_time
__u8 bridge_forward_delay
__u8 bridge_hello_time
__u8 bridge_max_age
__u8 max_hops
protocol_version_t protocol_version
bool set_bridge_ageing_time
bool set_bridge_forward_delay
bool set_bridge_hello_time
bool set_bridge_max_age
bool set_max_hops
bool set_protocol_version
bool set_tx_hold_count
unsigned int tx_hold_count
CIST_PortStatus
struct CIST_PortStatus
Definition at line 674 of file mstp.h.
Class Members
bool admin_edge_port
__u32 admin_external_port_path_cost
__u32 admin_internal_port_path_cost
admin_p2p_t admin_p2p
bool auto_edge_port
bool ba_inconsistent
bool bpdu_filter_port
bool bpdu_guard_error
bool bpdu_guard_port
bridge_identifier_t designated_bridge
__u32 designated_external_cost
__u32 designated_internal_cost
port_identifier_t designated_port
bridge_identifier_t designated_regional_root
bridge_identifier_t designated_root
bool disputed
bool enabled
__u32 external_port_path_cost
__u32 internal_port_path_cost
bool network_port
unsigned int num_rx_bpdu
unsigned int num_rx_bpdu_filtered
unsigned int num_rx_tcn
unsigned int num_trans_blk
unsigned int num_trans_fwd
unsigned int num_tx_bpdu
unsigned int num_tx_tcn
bool oper_edge_port
bool oper_p2p
__u8 port_hello_time
port_identifier_t port_id
bool rcvdBpdu
bool rcvdRSTP
bool rcvdSTP
bool rcvdTcAck
bool rcvdTcn
bool restricted_role
bool restricted_tcn
port_role_t role
bool sendRSTP
int state
bool tc_ack
unsigned int uptime
MSTI_PortStatus
struct MSTI_PortStatus
Definition at line 726 of file mstp.h.
Class Members
__u32 admin_internal_port_path_cost
bridge_identifier_t designated_bridge
__u32 designated_internal_cost
port_identifier_t designated_port
bridge_identifier_t designated_regional_root
bool disputed
__u32 internal_port_path_cost
port_identifier_t port_id
port_role_t role
int state
unsigned int uptime
CIST_PortConfig
struct CIST_PortConfig
Definition at line 745 of file mstp.h.
Class Members
bool admin_edge_port
__u32 admin_external_port_path_cost
admin_p2p_t admin_p2p
bool auto_edge_port
bool bpdu_filter_port
bool bpdu_guard_port
bool dont_txmt
bool network_port
bool restricted_role
bool restricted_tcn
bool set_admin_edge_port
bool set_admin_external_port_path_cost
bool set_admin_p2p
bool set_auto_edge_port
bool set_bpdu_filter_port
bool set_bpdu_guard_port
bool set_dont_txmt
bool set_network_port
bool set_restricted_role
bool set_restricted_tcn
MSTI_PortConfig
struct MSTI_PortConfig
Definition at line 789 of file mstp.h.
Class Members
__u32 admin_internal_port_path_cost
__u8 port_priority
bool set_admin_internal_port_path_cost
bool set_port_priority
Macro Definition Documentation
_ncmp
#define _ncmp (x, y)
Value:
    ({          \
    typeof(x) _cmp1 = (x);      \
    typeof(y) _cmp2 = (y);      \
    (void)(&_cmp1 == &_cmp2);   \
    memcmp(&_cmp1, &_cmp2, sizeof(_cmp1)); })
Definition at line 37 of file mstp.h.
#define _ncmp(x, y) ({          \
    typeof(x) _cmp1 = (x);      \
    typeof(y) _cmp2 = (y);      \
    (void)(&_cmp1 == &_cmp2);   \
    memcmp(&_cmp1, &_cmp2, sizeof(_cmp1)); })
Referenced by betterorsamePriority().
assign
#define assign (x, y)
Value:
    ({             \
    typeof(x) _assign1 = (x);       \
    typeof(y) _assign2 = (y);       \
    (void)(&_assign1 == &_assign2); \
    (x) = _assign2; })
Definition at line 32 of file mstp.h.
#define assign(x, y) ({             \
    typeof(x) _assign1 = (x);       \
    typeof(y) _assign2 = (y);       \
    (void)(&_assign1 == &_assign2); \
    (x) = _assign2; })
Referenced by create_ptp(), create_tree(), interface_ip_dump_prefix_assignment_list(), interface_ip_dump_prefix_list(), interface_prefix_assign(), MSTP_IN_bridge_create(), MSTP_IN_get_cist_bridge_status(), MSTP_IN_get_cist_port_status(), MSTP_IN_get_msti_bridge_status(), MSTP_IN_get_msti_port_status(), MSTP_IN_port_create_and_add_tail(), MSTP_IN_rx_bpdu(), MSTP_IN_set_cist_bridge_config(), MSTP_IN_set_cist_port_config(), MSTP_IN_set_mst_config_id(), MSTP_IN_set_msti_port_config(), MSTP_IN_set_port_enable(), PISM_to_DISABLED(), PISM_to_UPDATE(), port_default_internal_vars(), PPMSM_to_CHECKING_RSTP(), PPMSM_to_SELECTING_STP(), PRSM_to_DISCARD(), PRSM_to_RECEIVE(), PRTSM_to_ALTERNATE_PORT(), PRTSM_to_BACKUP_PORT(), PRTSM_to_DESIGNATED_DISCARD(), PRTSM_to_DESIGNATED_FORWARD(), PRTSM_to_DESIGNATED_LEARN(), PRTSM_to_DESIGNATED_PROPOSE(), PRTSM_to_DESIGNATED_SYNCED(), PRTSM_to_DISABLED_PORT(), PRTSM_to_INIT_PORT(), PRTSM_to_MASTER_DISCARD(), PRTSM_to_MASTER_FORWARD(), PRTSM_to_MASTER_LEARN(), PRTSM_to_MASTER_SYNCED(), PRTSM_to_ROOT_FORWARD(), PRTSM_to_ROOT_LEARN(), PRTSM_to_ROOT_PORT(), ptp_default_internal_vars(), PTSM_to_TRANSMIT_INIT(), rcvInfo(), recordPriority(), recordTimes(), set_fdbFlush(), TCSM_to_ACKNOWLEDGED(), TCSM_to_INACTIVE(), txConfig(), txMstp(), and updtRolesTree().
BPDU_FLAGS_ROLE_GET
#define BPDU_FLAGS_ROLE_GET (flags)
Value:
(((flags) >> offsetRole) & 3)
Definition at line 237 of file mstp.h.
Referenced by rcvInfo().
BPDU_FLAGS_ROLE_SET
#define BPDU_FLAGS_ROLE_SET (role)
Value:
(((role) & 3) << offsetRole)
Definition at line 236 of file mstp.h.
Referenced by txMstp().
cmp
#define cmp (x, _op, y)
Value:
(_ncmp((x), (y)) _op 0)
Definition at line 42 of file mstp.h.
Referenced by __blobmsg_list_init(), betterorsamePriority(), fromSameRegion(), MSTP_IN_create_msti(), MSTP_IN_set_cist_bridge_config(), recordAgreement(), rpc_uci_match_option(), rpc_uci_match_section(), samePriorityAndTimers(), updtRolesTree(), and vlist_init().
CONFIG_BPDU_SIZE
#define CONFIG_BPDU_SIZE offsetof(bpdu_t, version1_len)
Definition at line 167 of file mstp.h.
Referenced by MSTP_IN_rx_bpdu(), and txConfig().
CONFIGURATION_DIGEST_LEN
#define CONFIGURATION_DIGEST_LEN 16
Definition at line 86 of file mstp.h.
Referenced by __attribute__::__attribute__().
CONFIGURATION_NAME_LEN
#define CONFIGURATION_NAME_LEN 32
Definition at line 85 of file mstp.h.
Referenced by __attribute__::__attribute__().
COUNT_OF
#define COUNT_OF (x)
Value:
((sizeof(x)/sizeof(0[x])) / ((size_t)(!(sizeof(x) % sizeof(0[x])))))
Definition at line 24 of file mstp.h.
GET_CIST_PTP_FROM_PORT
#define GET_CIST_PTP_FROM_PORT (prt)
Value:
    list_entry((prt)->trees.next, per_tree_port_t, port_list)
Definition at line 453 of file mstp.h.
#define GET_CIST_PTP_FROM_PORT(prt) \
    list_entry((prt)->trees.next, per_tree_port_t, port_list)
Referenced by BDSM_run(), MSTP_IN_get_cist_port_status(), MSTP_IN_port_mcheck(), MSTP_IN_set_cist_port_config(), newTcWhile(), PISM_run(), PRTSM_runr(), PRTSM_to_INIT_PORT(), PTSM_run(), PTSM_to_IDLE(), PTSM_to_TRANSMIT_PERIODIC(), recordAgreement(), reselectMSTIs(), set_fdbFlush(), setRcvdMsgs(), txConfig(), txMstp(), txTcn(), updtbrAssuRcvdInfoWhile(), updtRcvdInfoWhile(), and updtRolesTree().
GET_CIST_TREE
#define GET_CIST_TREE (br)
Value:
list_entry((br)->trees.next, tree_t, bridge_list)
Definition at line 381 of file mstp.h.
Referenced by MSTP_IN_create_msti(), MSTP_IN_get_cist_bridge_status(), and syncMaster().
GET_PRIORITY_FROM_IDENTIFIER
#define GET_PRIORITY_FROM_IDENTIFIER (id)
Value:
(((__u8 *)(&(id)))[0] & 0xF0)
Definition at line 78 of file mstp.h.
Referenced by MSTP_IN_set_msti_bridge_config(), MSTP_IN_set_msti_port_config(), and txMstp().
HMAC_KEY
#define HMAC_KEY
Value:
                     {0x13, 0xAC, 0x06, 0xA6, 0x2E, 0x47, 0xFD, 0x51, \
                     0xF9, 0x5D, 0x2B, 0xA2, 0x43, 0xCD, 0x03, 0x46}
Definition at line 45 of file mstp.h.
#define HMAC_KEY    {0x13, 0xAC, 0x06, 0xA6, 0x2E, 0x47, 0xFD, 0x51, \
                     0xF9, 0x5D, 0x2B, 0xA2, 0x43, 0xCD, 0x03, 0x46}
Referenced by RecalcConfigDigest().
MAX_FID
#define MAX_FID 4095
Definition at line 55 of file mstp.h.
Referenced by MSTP_IN_delete_msti(), MSTP_IN_set_all_fids2mstids(), MSTP_IN_set_all_vids2fids(), MSTP_IN_set_fid2mstid(), and MSTP_IN_set_vid2fid().
MAX_IMPLEMENTATION_MSTIS
#define MAX_IMPLEMENTATION_MSTIS 63
Definition at line 60 of file mstp.h.
Referenced by MSTP_IN_create_msti(), and MSTP_IN_get_mstilist().
MAX_MSTID
#define MAX_MSTID 4094
Definition at line 56 of file mstp.h.
Referenced by MSTP_IN_create_msti(), MSTP_IN_delete_msti(), and MSTP_IN_set_all_fids2mstids().
MAX_PATH_COST
#define MAX_PATH_COST 200000000u
Definition at line 63 of file mstp.h.
Referenced by compute_pcost(), and MSTP_IN_port_create_and_add_tail().
MAX_PORT_NUMBER
#define MAX_PORT_NUMBER 4095
Definition at line 53 of file mstp.h.
Referenced by create_if().
MAX_STANDARD_MSTIS
#define MAX_STANDARD_MSTIS 64
Definition at line 59 of file mstp.h.
Referenced by MSTP_IN_rx_bpdu().
MAX_VID
#define MAX_VID 4094
Definition at line 54 of file mstp.h.
Referenced by MSTP_IN_set_all_fids2mstids(), MSTP_IN_set_all_vids2fids(), MSTP_IN_set_fid2mstid(), MSTP_IN_set_vid2fid(), and RecalcConfigDigest().
MST_BPDU_SIZE_WO_MSTI_MSGS
#define MST_BPDU_SIZE_WO_MSTI_MSGS offsetof(bpdu_t, mstConfiguration)
Definition at line 169 of file mstp.h.
Referenced by MSTP_IN_rx_bpdu(), and txMstp().
MST_BPDU_VER3LEN_WO_MSTI_MSGS
#define MST_BPDU_VER3LEN_WO_MSTI_MSGS
Value:
                    (MST_BPDU_SIZE_WO_MSTI_MSGS \
                    - offsetof(bpdu_t, mstConfigurationIdentifier))
Definition at line 170 of file mstp.h.
#define MST_BPDU_VER3LEN_WO_MSTI_MSGS (MST_BPDU_SIZE_WO_MSTI_MSGS \
                    - offsetof(bpdu_t, mstConfigurationIdentifier))
Referenced by MSTP_IN_rx_bpdu(), and txMstp().
offsetMaster
#define offsetMaster offsetTcAck
Referenced by recordMastered(), and txMstp().
RST_BPDU_SIZE
#define RST_BPDU_SIZE offsetof(bpdu_t, version3_len)
Definition at line 168 of file mstp.h.
Referenced by MSTP_IN_rx_bpdu(), and txMstp().
SET_PRIORITY_IN_IDENTIFIER
#define SET_PRIORITY_IN_IDENTIFIER (pri, id)
Value:
    do{ \
    __u8 *first_octet = (__u8 *)(&(id));        \
    *first_octet &= 0x0F;                       \
    *first_octet |= (pri) & 0xF0;               \
    }while(0)
Definition at line 79 of file mstp.h.
#define SET_PRIORITY_IN_IDENTIFIER(pri, id) do{ \
    __u8 *first_octet = (__u8 *)(&(id));        \
    *first_octet &= 0x0F;                       \
    *first_octet |= (pri) & 0xF0;               \
    }while(0)
Referenced by MSTP_IN_set_msti_bridge_config(), MSTP_IN_set_msti_port_config(), and rcvInfo().
TCN_BPDU_SIZE
#define TCN_BPDU_SIZE offsetof(bpdu_t, flags)
Definition at line 166 of file mstp.h.
Referenced by MSTP_IN_rx_bpdu(), and txTcn().
Typedef Documentation
port_identifier_t
typedef __be16 port_identifier_t
Definition at line 75 of file mstp.h.
Enumeration Type Documentation
admin_p2p_t
enum admin_p2p_t
Enumerator
p2pAuto
p2pForceTrue
p2pForceFalse
Definition at line 239 of file mstp.h.
{
    p2pAuto,
    p2pForceTrue,
    p2pForceFalse
}
BDSM_states_t
enum BDSM_states_t
Enumerator
BDSM_EDGE
BDSM_NOT_EDGE
Definition at line 263 of file mstp.h.
{
    BDSM_EDGE,
    BDSM_NOT_EDGE
} BDSM_states_t;
bpduFlagOffset_t
enum bpduFlagOffset_t
Enumerator
offsetTc 0
offsetProposal 1
offsetRole 2
offsetRole1 3
offsetLearnig 4
offsetForwarding 5
offsetAgreement 6
offsetTcAck 7 #define offsetMaster
Definition at line 222 of file mstp.h.
{
    offsetTc = 0,
    offsetProposal = 1,
    offsetRole = 2, /* actually, role is coded in two-bit field */
    offsetRole1 = 3, /* second bit of two-bit role field */
    offsetLearnig = 4,
    offsetForwarding = 5,
    offsetAgreement = 6,
    offsetTcAck = 7
/* in MSTI Configuration Message flags bit7 is used for Master flag */
#define offsetMaster    offsetTcAck
} bpduFlagOffset_t;
bpduType_t
enum bpduType_t
Enumerator
bpduTypeConfig 0
bpduTypeRST 2
bpduTypeTCN 128
Definition at line 215 of file mstp.h.
{
    bpduTypeConfig = 0,
    bpduTypeRST = 2,
    bpduTypeTCN = 128
} bpduType_t;
PISM_states_t
enum PISM_states_t
Enumerator
PISM_DISABLED
PISM_AGED
PISM_UPDATE
PISM_SUPERIOR_DESIGNATED
PISM_REPEATED_DESIGNATED
PISM_INFERIOR_DESIGNATED
PISM_NOT_DESIGNATED
PISM_OTHER
PISM_CURRENT
PISM_RECEIVE
Definition at line 282 of file mstp.h.
{
    PISM_DISABLED,
    PISM_AGED,
    PISM_UPDATE,
    PISM_SUPERIOR_DESIGNATED,
    PISM_REPEATED_DESIGNATED,
    PISM_INFERIOR_DESIGNATED,
    PISM_NOT_DESIGNATED,
    PISM_OTHER,
    PISM_CURRENT,
    PISM_RECEIVE
} PISM_states_t;
port_encoded_role_t
enum port_encoded_role_t
Enumerator
encodedRoleMaster 0
encodedRoleAlternateBackup 1
encodedRoleRoot 2
encodedRoleDesignated 3
Definition at line 200 of file mstp.h.
{
    encodedRoleMaster = 0,
    encodedRoleAlternateBackup = 1,
    encodedRoleRoot = 2,
    encodedRoleDesignated = 3
} port_encoded_role_t;
port_info_origin_t
enum port_info_origin_t
Enumerator
ioDisabled
ioMine
ioAged
ioReceived
Definition at line 182 of file mstp.h.
{
    ioDisabled,
    ioMine,
    ioAged,
    ioReceived
} port_info_origin_t;
port_info_t
enum port_info_t
Enumerator
OtherInfo
SuperiorDesignatedInfo
RepeatedDesignatedInfo
InferiorDesignatedInfo
InferiorRootAlternateInfo
Definition at line 173 of file mstp.h.
{
    OtherInfo,
    SuperiorDesignatedInfo,
    RepeatedDesignatedInfo,
    InferiorDesignatedInfo,
    InferiorRootAlternateInfo
} port_info_t;
port_role_t
enum port_role_t
Enumerator
roleDisabled
roleRoot
roleDesignated
roleAlternate
roleBackup
roleMaster
Definition at line 190 of file mstp.h.
{
    roleDisabled,
    roleRoot,
    roleDesignated,
    roleAlternate,
    roleBackup,
    roleMaster
} port_role_t;
PPMSM_states_t
enum PPMSM_states_t
Enumerator
PPMSM_CHECKING_RSTP
PPMSM_SELECTING_STP
PPMSM_SENSING
Definition at line 255 of file mstp.h.
{
    PPMSM_CHECKING_RSTP,
    PPMSM_SELECTING_STP,
    PPMSM_SENSING
} PPMSM_states_t;
protocol_version_t
enum protocol_version_t
Enumerator
protoSTP 0
protoRSTP 2
protoMSTP 3
Definition at line 208 of file mstp.h.
{
    protoSTP = 0,
    protoRSTP = 2,
    protoMSTP = 3
} protocol_version_t;
PRSM_states_t
enum PRSM_states_t
Enumerator
PRSM_DISCARD
PRSM_RECEIVE
Definition at line 248 of file mstp.h.
{
    PRSM_DISCARD,
    PRSM_RECEIVE
} PRSM_states_t;
PRSSM_states_t
enum PRSSM_states_t
Enumerator
PRSSM_INIT_TREE
PRSSM_ROLE_SELECTION
Definition at line 297 of file mstp.h.
{
    PRSSM_INIT_TREE,
    PRSSM_ROLE_SELECTION
} PRSSM_states_t;
PRTSM_states_t
enum PRTSM_states_t
Enumerator
PRTSM_INIT_PORT
PRTSM_DISABLE_PORT
PRTSM_DISABLED_PORT
PRTSM_MASTER_PROPOSED
PRTSM_MASTER_AGREED
PRTSM_MASTER_SYNCED
PRTSM_MASTER_RETIRED
PRTSM_MASTER_FORWARD
PRTSM_MASTER_LEARN
PRTSM_MASTER_DISCARD
PRTSM_MASTER_PORT
PRTSM_ROOT_PROPOSED
PRTSM_ROOT_AGREED
PRTSM_ROOT_SYNCED
PRTSM_REROOT
PRTSM_ROOT_FORWARD
PRTSM_ROOT_LEARN
PRTSM_REROOTED
PRTSM_ROOT_PORT
PRTSM_DESIGNATED_PROPOSE
PRTSM_DESIGNATED_AGREED
PRTSM_DESIGNATED_SYNCED
PRTSM_DESIGNATED_RETIRED
PRTSM_DESIGNATED_FORWARD
PRTSM_DESIGNATED_LEARN
PRTSM_DESIGNATED_DISCARD
PRTSM_DESIGNATED_PORT
PRTSM_BLOCK_PORT
PRTSM_BACKUP_PORT
PRTSM_ALTERNATE_PROPOSED
PRTSM_ALTERNATE_AGREED
PRTSM_ALTERNATE_PORT
Definition at line 305 of file mstp.h.
{
 /* Disabled Port role transitions */
    PRTSM_INIT_PORT,
    PRTSM_DISABLE_PORT,
    PRTSM_DISABLED_PORT,
 /* MasterPort role transitions */
    PRTSM_MASTER_PROPOSED,
    PRTSM_MASTER_AGREED,
    PRTSM_MASTER_SYNCED,
    PRTSM_MASTER_RETIRED,
    PRTSM_MASTER_FORWARD,
    PRTSM_MASTER_LEARN,
    PRTSM_MASTER_DISCARD,
    PRTSM_MASTER_PORT,
 /* RootPort role transitions */
    PRTSM_ROOT_PROPOSED,
    PRTSM_ROOT_AGREED,
    PRTSM_ROOT_SYNCED,
    PRTSM_REROOT,
    PRTSM_ROOT_FORWARD,
    PRTSM_ROOT_LEARN,
    PRTSM_REROOTED,
    PRTSM_ROOT_PORT,
 /* DesignatedPort role transitions */
    PRTSM_DESIGNATED_PROPOSE,
    PRTSM_DESIGNATED_AGREED,
    PRTSM_DESIGNATED_SYNCED,
    PRTSM_DESIGNATED_RETIRED,
    PRTSM_DESIGNATED_FORWARD,
    PRTSM_DESIGNATED_LEARN,
    PRTSM_DESIGNATED_DISCARD,
    PRTSM_DESIGNATED_PORT,
 /* AlternatePort and BackupPort role transitions */
    PRTSM_BLOCK_PORT,
    PRTSM_BACKUP_PORT,
    PRTSM_ALTERNATE_PROPOSED,
    PRTSM_ALTERNATE_AGREED,
    PRTSM_ALTERNATE_PORT
} PRTSM_states_t;
PSTSM_states_t
enum PSTSM_states_t
Enumerator
PSTSM_DISCARDING
PSTSM_LEARNING
PSTSM_FORWARDING
Definition at line 347 of file mstp.h.
{
    PSTSM_DISCARDING,
    PSTSM_LEARNING,
    PSTSM_FORWARDING
} PSTSM_states_t;
PTSM_states_t
enum PTSM_states_t
Enumerator
PTSM_TRANSMIT_INIT
PTSM_TRANSMIT_CONFIG
PTSM_TRANSMIT_TCN
PTSM_TRANSMIT_RSTP
PTSM_TRANSMIT_PERIODIC
PTSM_IDLE
Definition at line 270 of file mstp.h.
{
    PTSM_TRANSMIT_INIT,
    PTSM_TRANSMIT_CONFIG,
    PTSM_TRANSMIT_TCN,
    PTSM_TRANSMIT_RSTP,
    PTSM_TRANSMIT_PERIODIC,
    PTSM_IDLE
} PTSM_states_t;
TCSM_states_t
enum TCSM_states_t
Enumerator
TCSM_INACTIVE
TCSM_LEARNING
TCSM_DETECTED
TCSM_NOTIFIED_TCN
TCSM_NOTIFIED_TC
TCSM_PROPAGATING
TCSM_ACKNOWLEDGED
TCSM_ACTIVE
Definition at line 355 of file mstp.h.
{
    TCSM_INACTIVE,
    TCSM_LEARNING,
    TCSM_DETECTED,
    TCSM_NOTIFIED_TCN,
    TCSM_NOTIFIED_TC,
    TCSM_PROPAGATING,
    TCSM_ACKNOWLEDGED,
    TCSM_ACTIVE
} TCSM_states_t;
Function Documentation
hmac_md5()
void hmac_md5 (unsigned char * text, int text_len, unsigned char * key, int key_len, caddr_t digest) extern
Definition at line 32 of file hmac_md5.c.
{
    md5_ctx_t context;
    unsigned char k_ipad[65];    /* inner padding -
                                  * key XORd with ipad
                                  */
    unsigned char k_opad[65];    /* outer padding -
                                  * key XORd with opad
                                  */
    unsigned char tk[16];
    int i;
    /* if key is longer than 64 bytes reset it to key=MD5(key) */
    if(key_len > 64)
    {
        md5_ctx_t tctx;
        md5_begin(&tctx);
        md5_hash(key, key_len, &tctx);
        md5_end(tk, &tctx);
        key = tk;
        key_len = 16;
    }
    /*
     * the HMAC_MD5 transform looks like:
     *
     * MD5(K XOR opad, MD5(K XOR ipad, text))
     *
     * where K is an n byte key
     * ipad is the byte 0x36 repeated 64 times
     * opad is the byte 0x5c repeated 64 times
     * and text is the data being protected
     */
    /* start out by storing key in pads */
    bzero(k_ipad, sizeof k_ipad);
    bzero(k_opad, sizeof k_opad);
    bcopy(key, k_ipad, key_len);
    bcopy( key, k_opad, key_len);
    /* XOR key with ipad and opad values */
    for(i = 0; i < 64; ++i)
    {
        k_ipad[i] ^= 0x36;
        k_opad[i] ^= 0x5c;
    }
    /*
     * perform inner MD5
     */
    md5_begin(&context);                 /* init context for 1st
                                          * pass */
    md5_hash(k_ipad, 64, &context);      /* start with inner pad */
    md5_hash(text, text_len, &context);  /* then text of datagram */
    md5_end(digest, &context);           /* finish up 1st pass */
    /*
     * perform outer MD5
     */
    md5_begin(&context);                 /* init context for 2nd
                                          * pass */
    md5_hash(k_opad, 64, &context);      /* start with outer pad */
    md5_hash(digest, 16, &context);      /* then results of 1st
                                          * hash */
    md5_end(digest, &context);           /* finish up 2nd pass */
}
References md5_begin(), md5_end(), and md5_hash().
Referenced by RecalcConfigDigest().
MSTP_IN_all_fids_flushed()
void MSTP_IN_all_fids_flushed (per_tree_port_t * ptp)
Definition at line 563 of file mstp.c.
{
    bridge_t *br = ptp->port->bridge;
    ptp->fdbFlush = false;
    if(!br->bridgeEnabled)
        return;
    if(!ptp->calledFromFlushRoutine)
    {
        TCSM_run(ptp, false /* actual run */);
        br_state_machines_run(br);
    }
}
References br_state_machines_run(), port_t::bridge, bridge_t::bridgeEnabled, per_tree_port_t::calledFromFlushRoutine, per_tree_port_t::fdbFlush, per_tree_port_t::port, and TCSM_run().
Referenced by driver_flush_all_fids().
MSTP_IN_bridge_create()
bool MSTP_IN_bridge_create (bridge_t * br, __u8 * macaddr)
Definition at line 236 of file mstp.c.
{
    tree_t *cist;
    if (!driver_create_bridge(br, macaddr))
        return false;
    /* Initialize all fields except sysdeps and anchor */
    INIT_LIST_HEAD(&br->ports);
    INIT_LIST_HEAD(&br->trees);
    br->bridgeEnabled = false;
    memset(br->vid2fid, 0, sizeof(br->vid2fid));
    memset(br->fid2mstid, 0, sizeof(br->fid2mstid));
    assign(br->MstConfigId.s.selector, (__u8)0);
    sprintf((char *)br->MstConfigId.s.configuration_name,
            "%02hhX%02hhX%02hhX%02hhX%02hhX%02hhX",
            macaddr[0], macaddr[1], macaddr[2],
            macaddr[3], macaddr[4], macaddr[5]);
    assign(br->MstConfigId.s.revision_level, __constant_cpu_to_be16(0));
    RecalcConfigDigest(br); /* set br->MstConfigId.s.configuration_digest */
    br->ForceProtocolVersion = protoRSTP;
    assign(br->MaxHops, (__u8)20);       /* 13.37.3 */
    assign(br->Forward_Delay, (__u8)15); /* 17.14 of 802.1D */
    assign(br->Max_Age, (__u8)20);       /* 17.14 of 802.1D */
    assign(br->Transmit_Hold_Count, 6u); /* 17.14 of 802.1D */
    assign(br->Migrate_Time, 3u); /* 17.14 of 802.1D */
    assign(br->Ageing_Time, 300u);/* 8.8.3 Table 8-3 */
    assign(br->Hello_Time, (__u8)2);     /* 17.14 of 802.1D */
    bridge_default_internal_vars(br);
    /* Create CIST */
    if(!(cist = create_tree(br, macaddr, 0)))
        return false;
    list_add_tail(&cist->bridge_list, &br->trees);
    return true;
}
References bridge_t::Ageing_Time, assign, bridge_default_internal_vars(), tree_t::bridge_list, bridge_t::bridgeEnabled, create_tree(), driver_create_bridge(), bridge_t::fid2mstid, bridge_t::ForceProtocolVersion, bridge_t::Forward_Delay, bridge_t::Hello_Time, INIT_LIST_HEAD(), list_add_tail(), bridge_t::Max_Age, bridge_t::MaxHops, bridge_t::Migrate_Time, bridge_t::MstConfigId, bridge_t::ports, protoRSTP, RecalcConfigDigest(), bridge_t::Transmit_Hold_Count, bridge_t::trees, and bridge_t::vid2fid.
Referenced by create_br().
MSTP_IN_create_msti()
bool MSTP_IN_create_msti (bridge_t * br, __u16 mstid)
Definition at line 1467 of file mstp.c.
{
    tree_t *tree, *tree_after, *new_tree;
    per_tree_port_t *ptp, *nxt, *ptp_after, *new_ptp;
    int num_of_mstis;
    __be16 MSTID;
    if((mstid < 1) || (mstid > MAX_MSTID))
    {
        ERROR_BRNAME(br, "Bad MSTID(%hu)", mstid);
        return false;
    }
    MSTID = __cpu_to_be16(mstid);
    /* Find place where to insert new MSTID.
     * Also check if such MSTID is already in the list.
     * Also count existing mstis.
     */
    tree_after = NULL;
    num_of_mstis = 0;
    FOREACH_TREE_IN_BRIDGE(tree, br)
    {
        if(tree->MSTID == MSTID)
        {
            INFO_BRNAME(br, "MSTID(%hu) is already in the list", mstid);
            return true; /* yes, it is success */
        }
        if(cmp(tree->MSTID, <, MSTID))
            tree_after = tree;
        ++num_of_mstis;
    }
    /* Sanity check */
    if(NULL == tree_after)
    {
        ERROR_BRNAME(br, "Can't add MSTID(%hu): no CIST in the list", mstid);
        return false;
    }
    /* End of Sanity check */
    /* Check for "<", not for "<=", as num_of_mstis include CIST */
    if(MAX_IMPLEMENTATION_MSTIS < num_of_mstis)
    {
        ERROR_BRNAME(br, "Can't add MSTID(%hu): maximum count(%u) reached",
                     mstid, MAX_IMPLEMENTATION_MSTIS);
        return false;
    }
    /* Create new tree and its list of PerTreePort structures */
    tree = GET_CIST_TREE(br);
    if(!(new_tree=create_tree(br,tree->BridgeIdentifier.s.mac_address,MSTID)))
        return false;
    FOREACH_PTP_IN_TREE(ptp_after, tree_after)
    {
        if(!(new_ptp = create_ptp(new_tree, ptp_after->port)))
        {
            /* Remove and free all previously created entries in tree's list */
            list_for_each_entry_safe(ptp, nxt, &new_tree->ports, tree_list)
            {
                list_del(&ptp->port_list);
                list_del(&ptp->tree_list);
                free(ptp);
            }
            return false;
        }
        list_add(&new_ptp->port_list, &ptp_after->port_list);
        list_add_tail(&new_ptp->tree_list, &new_tree->ports);
    }
    list_add(&new_tree->bridge_list, &tree_after->bridge_list);
    /* There are no FIDs allocated to this MSTID, so VID-to-MSTID mapping
     *  did not change. So, no need in RecalcConfigDigest.
     * Just initialize state machines for this tree.
     */
    tree_state_machines_begin(new_tree);
    return true;
}
References tree_t::bridge_list, tree_t::BridgeIdentifier, cmp, create_ptp(), create_tree(), ERROR_BRNAME, FOREACH_PTP_IN_TREE, FOREACH_TREE_IN_BRIDGE, GET_CIST_TREE, INFO_BRNAME, list_add(), list_add_tail(), list_del(), list_for_each_entry_safe, MAX_IMPLEMENTATION_MSTIS, MAX_MSTID, tree_t::MSTID, per_tree_port_t::port, per_tree_port_t::port_list, tree_t::ports, per_tree_port_t::tree_list, and tree_state_machines_begin().
MSTP_IN_delete_bridge()
void MSTP_IN_delete_bridge (bridge_t * br)
Definition at line 364 of file mstp.c.
{
    tree_t *tree, *nxt_tree;
    port_t *prt, *nxt_prt;
    driver_delete_bridge(br);
    br->bridgeEnabled = false;
    /* We SHOULD first delete all ports and only THEN delete all tree_t
     * structures as the tree_t structure contains the head for the per-port
     * list of tree data (tree_t.ports).
     * If this list_head will be deleted before all the per_tree_ports
     * bad things will happen ;)
     */
    list_for_each_entry_safe(prt, nxt_prt, &br->ports, br_list)
    {
        MSTP_IN_delete_port(prt);
        free(prt);
    }
    list_for_each_entry_safe(tree, nxt_tree, &br->trees, bridge_list)
    {
        list_del(&tree->bridge_list);
        free(tree);
    }
}
References tree_t::bridge_list, bridge_t::bridgeEnabled, driver_delete_bridge(), list_del(), list_for_each_entry_safe, MSTP_IN_delete_port(), bridge_t::ports, and bridge_t::trees.
Referenced by delete_br_byindex().
MSTP_IN_delete_msti()
bool MSTP_IN_delete_msti (bridge_t * br, __u16 mstid)
Definition at line 1546 of file mstp.c.
{
    tree_t *tree;
    per_tree_port_t *ptp, *nxt;
    int fid;
    bool found;
    __be16 MSTID = __cpu_to_be16(mstid);
    if((mstid < 1) || (mstid > MAX_MSTID))
    {
        ERROR_BRNAME(br, "Bad MSTID(%hu)", mstid);
        return false;
    }
    /* Check if there are FIDs associated with this MSTID */
    for(fid = 0; fid <= MAX_FID; ++fid)
    {
        if(br->fid2mstid[fid] == MSTID)
        {
            ERROR_BRNAME(br,
                "Can't delete MSTID(%hu): there are FIDs allocated to it",
                mstid);
            return false;
        }
    }
    found = false;
    FOREACH_TREE_IN_BRIDGE(tree, br)
    {
        if(tree->MSTID == MSTID)
        {
            found = true;
            break;
        }
    }
    if(!found)
    {
        INFO_BRNAME(br, "MSTID(%hu) is not in the list", mstid);
        return true; /* yes, it is success */
    }
    list_del(&tree->bridge_list);
    list_for_each_entry_safe(ptp, nxt, &tree->ports, tree_list)
    {
        list_del(&ptp->port_list);
        list_del(&ptp->tree_list);
        free(ptp);
    }
    free(tree);
    /* There are no FIDs allocated to this MSTID, so VID-to-MSTID mapping
     *  did not change. So, no need in RecalcConfigDigest.
     * Give state machine a spare run, just for the case...
     */
    br_state_machines_run(br);
    return true;
}
References br_state_machines_run(), tree_t::bridge_list, ERROR_BRNAME, bridge_t::fid2mstid, FOREACH_TREE_IN_BRIDGE, INFO_BRNAME, list_del(), list_for_each_entry_safe, MAX_FID, MAX_MSTID, tree_t::MSTID, per_tree_port_t::port_list, tree_t::ports, and per_tree_port_t::tree_list.
MSTP_IN_delete_port()
void MSTP_IN_delete_port (port_t * prt)
Definition at line 339 of file mstp.c.
{
    per_tree_port_t *ptp, *nxt;
    bridge_t *br = prt->bridge;
    driver_delete_port(prt);
    prt->deleted = true;
    if(prt->portEnabled)
    {
        prt->portEnabled = false;
        br_state_machines_run(br);
    }
    list_for_each_entry_safe(ptp, nxt, &prt->trees, port_list)
    {
        list_del(&ptp->port_list);
        list_del(&ptp->tree_list);
        free(ptp);
    }
    list_del(&prt->br_list);
    br_state_machines_run(br);
}
References port_t::br_list, br_state_machines_run(), port_t::bridge, port_t::deleted, driver_delete_port(), list_del(), list_for_each_entry_safe, per_tree_port_t::port_list, port_t::portEnabled, per_tree_port_t::tree_list, and port_t::trees.
Referenced by delete_if(), and MSTP_IN_delete_bridge().
MSTP_IN_get_cist_bridge_status()
void MSTP_IN_get_cist_bridge_status (bridge_t * br, CIST_BridgeStatus * status)
Definition at line 714 of file mstp.c.
{
    tree_t *cist = GET_CIST_TREE(br);
    assign(status->bridge_id, cist->BridgeIdentifier);
    assign(status->time_since_topology_change,
           cist->time_since_topology_change);
    assign(status->topology_change_count, cist->topology_change_count);
    status->topology_change = cist->topology_change;
    strncpy(status->topology_change_port, cist->topology_change_port,
            IFNAMSIZ);
    strncpy(status->last_topology_change_port, cist->last_topology_change_port,
            IFNAMSIZ);
    assign(status->designated_root, cist->rootPriority.RootID);
    assign(status->root_path_cost,
           __be32_to_cpu(cist->rootPriority.ExtRootPathCost));
    assign(status->regional_root, cist->rootPriority.RRootID);
    assign(status->internal_path_cost,
           __be32_to_cpu(cist->rootPriority.IntRootPathCost));
    assign(status->root_port_id, cist->rootPortId);
    assign(status->root_max_age, cist->rootTimes.Max_Age);
    assign(status->root_forward_delay, cist->rootTimes.Forward_Delay);
    assign(status->bridge_max_age, br->Max_Age);
    assign(status->bridge_forward_delay, br->Forward_Delay);
    assign(status->max_hops, br->MaxHops);
    assign(status->tx_hold_count, br->Transmit_Hold_Count);
    status->protocol_version = br->ForceProtocolVersion;
    status->enabled = br->bridgeEnabled;
    assign(status->bridge_hello_time, br->Hello_Time);
    assign(status->Ageing_Time, br->Ageing_Time);
}
References bridge_t::Ageing_Time, CIST_BridgeStatus::Ageing_Time, assign, CIST_BridgeStatus::bridge_forward_delay, CIST_BridgeStatus::bridge_hello_time, CIST_BridgeStatus::bridge_id, CIST_BridgeStatus::bridge_max_age, bridge_t::bridgeEnabled, tree_t::BridgeIdentifier, CIST_BridgeStatus::designated_root, CIST_BridgeStatus::enabled, port_priority_vector_t::ExtRootPathCost, bridge_t::ForceProtocolVersion, bridge_t::Forward_Delay, times_t::Forward_Delay, GET_CIST_TREE, bridge_t::Hello_Time, CIST_BridgeStatus::internal_path_cost, port_priority_vector_t::IntRootPathCost, CIST_BridgeStatus::last_topology_change_port, tree_t::last_topology_change_port, bridge_t::Max_Age, times_t::Max_Age, CIST_BridgeStatus::max_hops, bridge_t::MaxHops, CIST_BridgeStatus::protocol_version, CIST_BridgeStatus::regional_root, CIST_BridgeStatus::root_forward_delay, CIST_BridgeStatus::root_max_age, CIST_BridgeStatus::root_path_cost, CIST_BridgeStatus::root_port_id, port_priority_vector_t::RootID, tree_t::rootPortId, tree_t::rootPriority, tree_t::rootTimes, port_priority_vector_t::RRootID, CIST_BridgeStatus::time_since_topology_change, tree_t::time_since_topology_change, CIST_BridgeStatus::topology_change, tree_t::topology_change, CIST_BridgeStatus::topology_change_count, tree_t::topology_change_count, CIST_BridgeStatus::topology_change_port, tree_t::topology_change_port, bridge_t::Transmit_Hold_Count, and CIST_BridgeStatus::tx_hold_count.
MSTP_IN_get_cist_port_status()
void MSTP_IN_get_cist_port_status (port_t * prt, CIST_PortStatus * status)
Definition at line 1000 of file mstp.c.
{
    per_tree_port_t *cist = GET_CIST_PTP_FROM_PORT(prt);
    /* 12.8.2.2.3 b) */
    status->uptime = (signed int)((prt->bridge)->uptime)
                     - (signed int)(cist->start_time);
    status->state = cist->state;
    assign(status->port_id, cist->portId);
    assign(status->admin_external_port_path_cost,
           prt->AdminExternalPortPathCost);
    assign(status->external_port_path_cost, prt->ExternalPortPathCost);
    assign(status->designated_root, cist->portPriority.RootID);
    assign(status->designated_external_cost,
           __be32_to_cpu(cist->portPriority.ExtRootPathCost));
    assign(status->designated_bridge, cist->portPriority.DesignatedBridgeID);
    assign(status->designated_port, cist->portPriority.DesignatedPortID);
    assign(status->designated_regional_root, cist->portPriority.RRootID);
    assign(status->designated_internal_cost,
           __be32_to_cpu(cist->portPriority.IntRootPathCost));
    status->tc_ack = prt->tcAck;
    assign(status->port_hello_time, cist->portTimes.Hello_Time);
    status->admin_edge_port = prt->AdminEdgePort;
    status->auto_edge_port = prt->AutoEdge;
    status->oper_edge_port = prt->operEdge;
    status->enabled = prt->portEnabled;
    status->admin_p2p = prt->AdminP2P;
    status->oper_p2p = prt->operPointToPointMAC;
    status->restricted_role = prt->restrictedRole;
    status->restricted_tcn = prt->restrictedTcn;
    status->role = cist->role;
    status->disputed = cist->disputed;
    assign(status->admin_internal_port_path_cost,
           cist->AdminInternalPortPathCost);
    assign(status->internal_port_path_cost, cist->InternalPortPathCost);
    status->bpdu_guard_port = prt->BpduGuardPort;
    status->bpdu_guard_error = prt->BpduGuardError;
    status->network_port = prt->NetworkPort;
    status->ba_inconsistent = prt->BaInconsistent;
    status->bpdu_filter_port = prt->bpduFilterPort;
    status->num_rx_bpdu_filtered = prt->num_rx_bpdu_filtered;
    status->num_rx_bpdu = prt->num_rx_bpdu;
    status->num_rx_tcn = prt->num_rx_tcn;
    status->num_tx_bpdu = prt->num_tx_bpdu;
    status->num_tx_tcn = prt->num_tx_tcn;
    status->num_trans_fwd = prt->num_trans_fwd;
    status->num_trans_blk = prt->num_trans_blk;
    status->rcvdBpdu = prt->rcvdBpdu;
    status->rcvdRSTP = prt->rcvdRSTP;
    status->rcvdSTP = prt->rcvdSTP;
    status->rcvdTcAck = prt->rcvdTcAck;
    status->rcvdTcn = prt->rcvdTcn;
    status->sendRSTP = prt->sendRSTP;
}
References CIST_PortStatus::admin_edge_port, CIST_PortStatus::admin_external_port_path_cost, CIST_PortStatus::admin_internal_port_path_cost, CIST_PortStatus::admin_p2p, port_t::AdminEdgePort, port_t::AdminExternalPortPathCost, per_tree_port_t::AdminInternalPortPathCost, port_t::AdminP2P, assign, CIST_PortStatus::auto_edge_port, port_t::AutoEdge, CIST_PortStatus::ba_inconsistent, port_t::BaInconsistent, CIST_PortStatus::bpdu_filter_port, CIST_PortStatus::bpdu_guard_error, CIST_PortStatus::bpdu_guard_port, port_t::bpduFilterPort, port_t::BpduGuardError, port_t::BpduGuardPort, port_t::bridge, CIST_PortStatus::designated_bridge, CIST_PortStatus::designated_external_cost, CIST_PortStatus::designated_internal_cost, CIST_PortStatus::designated_port, CIST_PortStatus::designated_regional_root, CIST_PortStatus::designated_root, port_priority_vector_t::DesignatedBridgeID, port_priority_vector_t::DesignatedPortID, CIST_PortStatus::disputed, per_tree_port_t::disputed, CIST_PortStatus::enabled, CIST_PortStatus::external_port_path_cost, port_t::ExternalPortPathCost, port_priority_vector_t::ExtRootPathCost, GET_CIST_PTP_FROM_PORT, times_t::Hello_Time, CIST_PortStatus::internal_port_path_cost, per_tree_port_t::InternalPortPathCost, port_priority_vector_t::IntRootPathCost, CIST_PortStatus::network_port, port_t::NetworkPort, CIST_PortStatus::num_rx_bpdu, port_t::num_rx_bpdu, CIST_PortStatus::num_rx_bpdu_filtered, port_t::num_rx_bpdu_filtered, CIST_PortStatus::num_rx_tcn, port_t::num_rx_tcn, CIST_PortStatus::num_trans_blk, port_t::num_trans_blk, CIST_PortStatus::num_trans_fwd, port_t::num_trans_fwd, CIST_PortStatus::num_tx_bpdu, port_t::num_tx_bpdu, CIST_PortStatus::num_tx_tcn, port_t::num_tx_tcn, CIST_PortStatus::oper_edge_port, CIST_PortStatus::oper_p2p, port_t::operEdge, port_t::operPointToPointMAC, CIST_PortStatus::port_hello_time, CIST_PortStatus::port_id, port_t::portEnabled, per_tree_port_t::portId, per_tree_port_t::portPriority, per_tree_port_t::portTimes, CIST_PortStatus::rcvdBpdu, port_t::rcvdBpdu, CIST_PortStatus::rcvdRSTP, port_t::rcvdRSTP, CIST_PortStatus::rcvdSTP, port_t::rcvdSTP, CIST_PortStatus::rcvdTcAck, port_t::rcvdTcAck, CIST_PortStatus::rcvdTcn, port_t::rcvdTcn, CIST_PortStatus::restricted_role, CIST_PortStatus::restricted_tcn, port_t::restrictedRole, port_t::restrictedTcn, CIST_PortStatus::role, per_tree_port_t::role, port_priority_vector_t::RootID, port_priority_vector_t::RRootID, CIST_PortStatus::sendRSTP, port_t::sendRSTP, per_tree_port_t::start_time, CIST_PortStatus::state, per_tree_port_t::state, CIST_PortStatus::tc_ack, port_t::tcAck, and CIST_PortStatus::uptime.
MSTP_IN_get_msti_bridge_status()
void MSTP_IN_get_msti_bridge_status (tree_t * tree, MSTI_BridgeStatus * status)
Definition at line 746 of file mstp.c.
{
    assign(status->bridge_id, tree->BridgeIdentifier);
    assign(status->time_since_topology_change,
           tree->time_since_topology_change);
    assign(status->topology_change_count, tree->topology_change_count);
    status->topology_change = tree->topology_change;
    strncpy(status->topology_change_port, tree->topology_change_port,
            IFNAMSIZ);
    strncpy(status->last_topology_change_port, tree->last_topology_change_port,
            IFNAMSIZ);
    assign(status->regional_root, tree->rootPriority.RRootID);
    assign(status->internal_path_cost,
           __be32_to_cpu(tree->rootPriority.IntRootPathCost));
    assign(status->root_port_id, tree->rootPortId);
}
References assign, MSTI_BridgeStatus::bridge_id, tree_t::BridgeIdentifier, MSTI_BridgeStatus::internal_path_cost, port_priority_vector_t::IntRootPathCost, MSTI_BridgeStatus::last_topology_change_port, tree_t::last_topology_change_port, MSTI_BridgeStatus::regional_root, MSTI_BridgeStatus::root_port_id, tree_t::rootPortId, tree_t::rootPriority, port_priority_vector_t::RRootID, MSTI_BridgeStatus::time_since_topology_change, tree_t::time_since_topology_change, MSTI_BridgeStatus::topology_change, tree_t::topology_change, MSTI_BridgeStatus::topology_change_count, tree_t::topology_change_count, MSTI_BridgeStatus::topology_change_port, and tree_t::topology_change_port.
MSTP_IN_get_msti_port_status()
void MSTP_IN_get_msti_port_status (per_tree_port_t * ptp, MSTI_PortStatus * status)
Definition at line 1055 of file mstp.c.
{
    status->uptime = (signed int)((ptp->port->bridge)->uptime)
                     - (signed int)(ptp->start_time);
    status->state = ptp->state;
    assign(status->port_id, ptp->portId);
    assign(status->admin_internal_port_path_cost,
           ptp->AdminInternalPortPathCost);
    assign(status->internal_port_path_cost, ptp->InternalPortPathCost);
    assign(status->designated_regional_root, ptp->portPriority.RRootID);
    assign(status->designated_internal_cost,
           __be32_to_cpu(ptp->portPriority.IntRootPathCost));
    assign(status->designated_bridge, ptp->portPriority.DesignatedBridgeID);
    assign(status->designated_port, ptp->portPriority.DesignatedPortID);
    status->role = ptp->role;
    status->disputed = ptp->disputed;
}
References MSTI_PortStatus::admin_internal_port_path_cost, per_tree_port_t::AdminInternalPortPathCost, assign, port_t::bridge, MSTI_PortStatus::designated_bridge, MSTI_PortStatus::designated_internal_cost, MSTI_PortStatus::designated_port, MSTI_PortStatus::designated_regional_root, port_priority_vector_t::DesignatedBridgeID, port_priority_vector_t::DesignatedPortID, MSTI_PortStatus::disputed, per_tree_port_t::disputed, MSTI_PortStatus::internal_port_path_cost, per_tree_port_t::InternalPortPathCost, port_priority_vector_t::IntRootPathCost, per_tree_port_t::port, MSTI_PortStatus::port_id, per_tree_port_t::portId, per_tree_port_t::portPriority, MSTI_PortStatus::role, per_tree_port_t::role, port_priority_vector_t::RRootID, per_tree_port_t::start_time, MSTI_PortStatus::state, per_tree_port_t::state, and MSTI_PortStatus::uptime.
MSTP_IN_get_mstilist()
bool MSTP_IN_get_mstilist (bridge_t * br, int * num_mstis, __u16 * mstids)
Definition at line 1450 of file mstp.c.
{
    tree_t *tree;
    *num_mstis = 0;
    FOREACH_TREE_IN_BRIDGE(tree, br)
    {
        mstids[*num_mstis] = __be16_to_cpu(tree->MSTID);
        /* Check for "<", not for "<=", as num_mstis include CIST */
        if(MAX_IMPLEMENTATION_MSTIS < ++(*num_mstis))
            break;
    }
    return true;
}
References FOREACH_TREE_IN_BRIDGE, MAX_IMPLEMENTATION_MSTIS, and tree_t::MSTID.
MSTP_IN_one_second()
void MSTP_IN_one_second (bridge_t * br)
Definition at line 532 of file mstp.c.
{
    port_t *prt;
    tree_t *tree;
    ++(br->uptime);
    if(!br->bridgeEnabled)
        return;
    FOREACH_TREE_IN_BRIDGE(tree, br)
        if(!(tree->topology_change))
            ++(tree->time_since_topology_change);
    FOREACH_PORT_IN_BRIDGE(prt, br)
    {
        PTSM_tick(prt);
        /* support for rapid ageing */
        if(prt->rapidAgeingWhile)
        {
            if((--(prt->rapidAgeingWhile)) == 0)
            {
                if(!prt->deleted)
                    MSTP_OUT_set_ageing_time(prt, br->Ageing_Time);
            }
        }
    }
    br_state_machines_run(br);
}
References bridge_t::Ageing_Time, br_state_machines_run(), bridge_t::bridgeEnabled, port_t::deleted, FOREACH_PORT_IN_BRIDGE, FOREACH_TREE_IN_BRIDGE, MSTP_OUT_set_ageing_time(), PTSM_tick(), port_t::rapidAgeingWhile, tree_t::time_since_topology_change, tree_t::topology_change, and bridge_t::uptime.
Referenced by bridge_one_second().
MSTP_IN_port_create_and_add_tail()
bool MSTP_IN_port_create_and_add_tail (port_t * prt, __u16 portno)
Definition at line 275 of file mstp.c.
{
    tree_t *tree;
    per_tree_port_t *ptp, *nxt;
    bridge_t *br = prt->bridge;
    if (!driver_create_port(prt, portno))
        return false;
    /* Initialize all fields except sysdeps and bridge */
    INIT_LIST_HEAD(&prt->trees);
    prt->port_number = __cpu_to_be16(portno);
    assign(prt->AdminExternalPortPathCost, 0u);
    /* Default for operP2P is false because by default AdminP2P
     * says to auto-detect p2p state, and it is derived from duplex
     * and initially port is in down state and in this down state
     * duplex is set to false (half) */
    prt->AdminP2P = p2pAuto;
    prt->operPointToPointMAC = false;
    prt->portEnabled = false;
    prt->restrictedRole = false; /* 13.25.14 */
    prt->restrictedTcn = false; /* 13.25.15 */
    assign(prt->ExternalPortPathCost, MAX_PATH_COST); /* 13.37.1 */
    prt->AdminEdgePort = false; /* 13.25 */
    prt->AutoEdge = true;       /* 13.25 */
    prt->BpduGuardPort = false;
    prt->BpduGuardError = false;
    prt->NetworkPort = false;
    prt->dontTxmtBpdu = false;
    prt->bpduFilterPort = false;
    prt->deleted = false;
    port_default_internal_vars(prt);
    /* Create PerTreePort structures for all existing trees */
    FOREACH_TREE_IN_BRIDGE(tree, br)
    {
        if(!(ptp = create_ptp(tree, prt)))
        {
            /* Remove and free all previously created entries in port's list */
            list_for_each_entry_safe(ptp, nxt, &prt->trees, port_list)
            {
                list_del(&ptp->port_list);
                list_del(&ptp->tree_list);
                free(ptp);
            }
            return false;
        }
        list_add_tail(&ptp->port_list, &prt->trees);
        list_add_tail(&ptp->tree_list, &tree->ports);
    }
    /* Add new port to the tail of the list in the bridge */
    /* NOTE: if one wants add port NOT to the tail of the list of ports,
     * one should revise above loop (FOREACH_TREE_IN_BRIDGE)
     * because it heavily depends on the fact that port is added to the tail.
     */
    list_add_tail(&prt->br_list, &br->ports);
    prt_state_machines_begin(prt);
    return true;
}
References port_t::AdminEdgePort, port_t::AdminExternalPortPathCost, port_t::AdminP2P, assign, port_t::AutoEdge, port_t::bpduFilterPort, port_t::BpduGuardError, port_t::BpduGuardPort, port_t::br_list, port_t::bridge, create_ptp(), port_t::deleted, port_t::dontTxmtBpdu, driver_create_port(), port_t::ExternalPortPathCost, FOREACH_TREE_IN_BRIDGE, INIT_LIST_HEAD(), list_add_tail(), list_del(), list_for_each_entry_safe, MAX_PATH_COST, port_t::NetworkPort, port_t::operPointToPointMAC, p2pAuto, port_default_internal_vars(), per_tree_port_t::port_list, port_t::port_number, port_t::portEnabled, bridge_t::ports, tree_t::ports, prt_state_machines_begin(), port_t::restrictedRole, port_t::restrictedTcn, per_tree_port_t::tree_list, and port_t::trees.
Referenced by create_if().
MSTP_IN_port_mcheck()
int MSTP_IN_port_mcheck (port_t * prt)
Definition at line 1280 of file mstp.c.
{
    bridge_t *br = prt->bridge;
    per_tree_port_t *cist = GET_CIST_PTP_FROM_PORT(prt);
    if(rstpVersion(br) && prt->portEnabled && br->bridgeEnabled)
    {
        prt->mcheck = true;
        cist->proposing = true;
        br_state_machines_run(br);
    }
    return 0;
}
References br_state_machines_run(), port_t::bridge, bridge_t::bridgeEnabled, GET_CIST_PTP_FROM_PORT, port_t::mcheck, port_t::portEnabled, per_tree_port_t::proposing, and rstpVersion.
MSTP_IN_rx_bpdu()
void MSTP_IN_rx_bpdu (port_t * prt, bpdu_t * bpdu, int size)
Definition at line 579 of file mstp.c.
{
    int mstis_size;
    bridge_t *br = prt->bridge;
    ++(prt->num_rx_bpdu);
    if(prt->BpduGuardPort)
    {
        prt->BpduGuardError = true;
        ERROR_PRTNAME(br, prt,
                      "Received BPDU on BPDU Guarded Port - Port Down");
        MSTP_OUT_shutdown_port(prt);
        return;
    }
    if(prt->bpduFilterPort)
    {
        LOG_PRTNAME(br, prt,
                   "Received BPDU on BPDU Filtered Port - discarded");
        ++(prt->num_rx_bpdu_filtered);
        return;
    }
    if(!br->bridgeEnabled)
    {
        INFO_PRTNAME(br, prt, "Received BPDU while bridge is disabled");
        return;
    }
    if(prt->rcvdBpdu)
    {
        ERROR_PRTNAME(br, prt, "Port hasn't processed previous BPDU");
        return;
    }
    /* 14.4 Validation */
    if((TCN_BPDU_SIZE > size) || (0 != bpdu->protocolIdentifier))
    {
bpdu_validation_failed:
        INFO_PRTNAME(br, prt, "BPDU validation failed");
        return;
    }
    switch(bpdu->bpduType)
    {
        case bpduTypeTCN:
            /* 14.4.b) */
            /* Valid TCN BPDU */
            bpdu->protocolVersion = protoSTP;
            LOG_PRTNAME(br, prt, "received TCN BPDU");
            break;
        case bpduTypeConfig:
            /* 14.4.a) */
            if(CONFIG_BPDU_SIZE > size)
                goto bpdu_validation_failed;
            /* Valid Config BPDU */
            bpdu->protocolVersion = protoSTP;
            LOG_PRTNAME(br, prt, "received Config BPDU%s",
                        (bpdu->flags & (1 << offsetTc)) ? ", tcFlag" : ""
                       );
            break;
        case bpduTypeRST:
            if(protoRSTP == bpdu->protocolVersion)
            { /* 14.4.c) */
                if(RST_BPDU_SIZE > size)
                    goto bpdu_validation_failed;
                /* Valid RST BPDU */
                /* bpdu->protocolVersion = protoRSTP; */
                LOG_PRTNAME(br, prt, "received RST BPDU%s",
                            (bpdu->flags & (1 << offsetTc)) ? ", tcFlag" : ""
                           );
                break;
            }
            if(protoMSTP > bpdu->protocolVersion)
                goto bpdu_validation_failed;
            /* Yes, 802.1Q-2005 says here to check if it contains
             * "35 or more octets", not 36! (see 14.4.d).1) )
             * That's why I check size against CONFIG_BPDU_SIZE
             * and not RST_BPDU_SIZE.
             */
            if(CONFIG_BPDU_SIZE > size)
                goto bpdu_validation_failed;
            mstis_size = __be16_to_cpu(bpdu->version3_len)
                         - MST_BPDU_VER3LEN_WO_MSTI_MSGS;
            if((MST_BPDU_SIZE_WO_MSTI_MSGS > size) || (0 != bpdu->version1_len)
               || (0 > mstis_size)
               || ((MAX_STANDARD_MSTIS * sizeof(msti_configuration_message_t))
                   < mstis_size)
               || (0 != (mstis_size % sizeof(msti_configuration_message_t)))
              )
            { /* 14.4.d) */
                /* Valid RST BPDU */
                bpdu->protocolVersion = protoRSTP;
                LOG_PRTNAME(br, prt, "received RST BPDU");
                break;
            }
            /* 14.4.e) */
            /* Valid MST BPDU */
            bpdu->protocolVersion = protoMSTP;
            prt->rcvdBpduNumOfMstis = mstis_size
                                      / sizeof(msti_configuration_message_t);
            LOG_PRTNAME(br, prt, "received MST BPDU%s with %d MSTIs",
                        (bpdu->flags & (1 << offsetTc)) ? ", tcFlag" : "",
                        prt->rcvdBpduNumOfMstis
                       );
            break;
        default:
            goto bpdu_validation_failed;
    }
    if((protoSTP == bpdu->protocolVersion) && (bpduTypeTCN == bpdu->bpduType))
    {
        ++(prt->num_rx_tcn);
    }
    else
    {
        if(bpdu->flags & (1 << offsetTc))
            ++(prt->num_rx_tcn);
    }
    assign(prt->rcvdBpduData, *bpdu);
    prt->rcvdBpdu = true;
    /* Reset bridge assurance on receipt of valid BPDU */
    if(prt->BaInconsistent)
    {
        prt->BaInconsistent = false;
        INFO_PRTNAME(br, prt, "Clear Bridge assurance inconsistency");
    }
    updtbrAssuRcvdInfoWhile(prt);
    br_state_machines_run(br);
}
References assign, port_t::BaInconsistent, port_t::bpduFilterPort, port_t::BpduGuardError, port_t::BpduGuardPort, bpduTypeConfig, bpduTypeRST, bpduTypeTCN, br_state_machines_run(), port_t::bridge, bridge_t::bridgeEnabled, CONFIG_BPDU_SIZE, ERROR_PRTNAME, INFO_PRTNAME, LOG_PRTNAME, MAX_STANDARD_MSTIS, MST_BPDU_SIZE_WO_MSTI_MSGS, MST_BPDU_VER3LEN_WO_MSTI_MSGS, MSTP_OUT_shutdown_port(), port_t::num_rx_bpdu, port_t::num_rx_bpdu_filtered, port_t::num_rx_tcn, offsetTc, protoMSTP, protoRSTP, protoSTP, port_t::rcvdBpdu, port_t::rcvdBpduData, port_t::rcvdBpduNumOfMstis, RST_BPDU_SIZE, TCN_BPDU_SIZE, and updtbrAssuRcvdInfoWhile().
Referenced by bridge_bpdu_rcv().
MSTP_IN_set_all_fids2mstids()
bool MSTP_IN_set_all_fids2mstids (bridge_t * br, __u16 * fids2mstids)
Definition at line 1394 of file mstp.c.
{
    tree_t *tree;
    __be16 MSTID[MAX_FID + 1];
    bool found, vid2mstid_changed;
    int fid, vid;
    __be16 prev_vid2mstid[MAX_VID + 2];
    for(fid = 0; fid <= MAX_FID; ++fid)
    {
        if(fids2mstids[fid] > MAX_MSTID)
        { /* Incorrect value == keep prev value */
            fids2mstids[fid] = __be16_to_cpu(MSTID[fid] = br->fid2mstid[fid]);
        }
        else
            MSTID[fid] = __cpu_to_be16(fids2mstids[fid]);
        found = false;
        FOREACH_TREE_IN_BRIDGE(tree, br)
        {
            if(tree->MSTID == MSTID[fid])
            {
                found = true;
                break;
            }
        }
        if(!found)
        {
            ERROR_BRNAME(br,
                "Error allocating FID(%hu) to MSTID(%hu): MSTID not found",
                fid, fids2mstids[fid]);
            return false;
        }
    }
    for(vid = 1; vid <= MAX_VID; ++vid)
        prev_vid2mstid[vid] = br->fid2mstid[br->vid2fid[vid]];
    memcpy(br->fid2mstid, MSTID, sizeof(br->fid2mstid));
    vid2mstid_changed = false;
    for(vid = 1; vid <= MAX_VID; ++vid)
    {
        if(prev_vid2mstid[vid] != br->fid2mstid[br->vid2fid[vid]])
        {
            vid2mstid_changed = true;
            break;
        }
    }
    if(vid2mstid_changed)
    {
        RecalcConfigDigest(br);
        br_state_machines_begin(br);
    }
    return true;
}
References br_state_machines_begin(), ERROR_BRNAME, bridge_t::fid2mstid, FOREACH_TREE_IN_BRIDGE, MAX_FID, MAX_MSTID, MAX_VID, tree_t::MSTID, RecalcConfigDigest(), and bridge_t::vid2fid.
MSTP_IN_set_all_vids2fids()
bool MSTP_IN_set_all_vids2fids (bridge_t * br, __u16 * vids2fids)
Definition at line 1319 of file mstp.c.
{
    bool vid2mstid_changed;
    int vid;
    vid2mstid_changed = false;
    for(vid = 1; vid <= MAX_VID; ++vid)
    {
        if(vids2fids[vid] > MAX_FID)
        { /* Incorrect value == keep prev value */
            vids2fids[vid] = br->vid2fid[vid];
            continue;
        }
        if(br->fid2mstid[vids2fids[vid]] != br->fid2mstid[br->vid2fid[vid]])
            vid2mstid_changed = true;
    }
    memcpy(br->vid2fid, vids2fids, sizeof(br->vid2fid));
    if(vid2mstid_changed)
    {
        RecalcConfigDigest(br);
        br_state_machines_begin(br);
    }
    return true;
}
References br_state_machines_begin(), bridge_t::fid2mstid, MAX_FID, MAX_VID, RecalcConfigDigest(), and bridge_t::vid2fid.
MSTP_IN_set_bridge_address()
void MSTP_IN_set_bridge_address (bridge_t * br, __u8 * macaddr)
Definition at line 393 of file mstp.c.
{
    tree_t *tree;
    bool changed = false;
    FOREACH_TREE_IN_BRIDGE(tree, br)
    {
        if(0 == memcmp(tree->BridgeIdentifier.s.mac_address, macaddr, ETH_ALEN))
            continue;
        changed = true;
        memcpy(tree->BridgeIdentifier.s.mac_address, macaddr, ETH_ALEN);
        tree->BridgePriority.RootID = tree->BridgePriority.RRootID =
            tree->BridgePriority.DesignatedBridgeID = tree->BridgeIdentifier;
    }
    if(changed)
        br_state_machines_begin(br);
}
References br_state_machines_begin(), tree_t::BridgeIdentifier, tree_t::BridgePriority, port_priority_vector_t::DesignatedBridgeID, FOREACH_TREE_IN_BRIDGE, port_priority_vector_t::RootID, and port_priority_vector_t::RRootID.
Referenced by set_br_up(), and set_if_up().
MSTP_IN_set_bridge_enable()
void MSTP_IN_set_bridge_enable (bridge_t * br, bool up)
Definition at line 412 of file mstp.c.
{
    port_t *prt;
    per_tree_port_t *ptp;
    tree_t *tree;
    if(br->bridgeEnabled == up)
        return;
    br->bridgeEnabled = up;
    /* Reset all internal states and variables,
     * except those which are user-configurable */
    bridge_default_internal_vars(br);
    FOREACH_TREE_IN_BRIDGE(tree, br)
    {
        tree_default_internal_vars(tree);
    }
    FOREACH_PORT_IN_BRIDGE(prt, br)
    {
        /* NOTE: Don't check prt->deleted here, as it is imposible condition */
        /* NOTE: In the port_default_internal_vars() rapidAgeingWhile will be
         *  reset, so we should stop rapid ageing procedure here.
         */
        if(prt->rapidAgeingWhile)
        {
            MSTP_OUT_set_ageing_time(prt, br->Ageing_Time);
        }
        port_default_internal_vars(prt);
        FOREACH_PTP_IN_PORT(ptp, prt)
        {
            if(BR_STATE_DISABLED != ptp->state)
            {
                MSTP_OUT_set_state(ptp, BR_STATE_DISABLED);
            }
            ptp_default_internal_vars(ptp);
        }
    }
    br_state_machines_begin(br);
}
References bridge_t::Ageing_Time, br_state_machines_begin(), bridge_default_internal_vars(), bridge_t::bridgeEnabled, FOREACH_PORT_IN_BRIDGE, FOREACH_PTP_IN_PORT, FOREACH_TREE_IN_BRIDGE, MSTP_OUT_set_ageing_time(), MSTP_OUT_set_state(), port_default_internal_vars(), ptp_default_internal_vars(), port_t::rapidAgeingWhile, per_tree_port_t::state, and tree_default_internal_vars().
Referenced by set_br_up().
MSTP_IN_set_cist_bridge_config()
int MSTP_IN_set_cist_bridge_config (bridge_t * br, CIST_BridgeConfig * cfg)
Definition at line 764 of file mstp.c.
{
    bool changed, changedBridgeTimes, init;
    int r = 0;
    __u8 new_forward_delay, new_max_age;
    tree_t *tree;
    port_t *prt;
    per_tree_port_t *ptp;
    /* Firstly, validation */
    if(cfg->set_bridge_max_age)
    {
        new_max_age = cfg->bridge_max_age;
        if((6 > new_max_age) || (40 < new_max_age))
        {
            ERROR_BRNAME(br,
                "Bridge Max Age must be between 6 and 40 seconds");
            r = -1;
        }
    }
    else
        new_max_age = br->Max_Age;
    if(cfg->set_bridge_forward_delay)
    {
        new_forward_delay = cfg->bridge_forward_delay;
        if((4 > new_forward_delay) || (30 < new_forward_delay))
        {
            ERROR_BRNAME(br,
                "Bridge Forward Delay must be between 4 and 30 seconds");
            r = -1;
        }
    }
    else
        new_forward_delay = br->Forward_Delay;
    if(cfg->set_bridge_max_age || cfg->set_bridge_forward_delay)
    {
        if((2 * (new_forward_delay - 1)) < new_max_age)
        {
            ERROR_BRNAME(br, "Configured Bridge Times don't meet "
                "2 * (Bridge Foward Delay - 1 second) >= Bridge Max Age");
            r = -1;
        }
    }
    if(cfg->set_protocol_version)
    {
        switch(cfg->protocol_version)
        {
            case protoSTP:
            case protoRSTP:
            case protoMSTP:
                break;
            default:
                ERROR_BRNAME(br, "Bad protocol version (%d)",
                             cfg->protocol_version);
                r = -1;
        }
    }
    if(cfg->set_tx_hold_count)
    {
        if((1 > cfg->tx_hold_count) || (10 < cfg->tx_hold_count))
        {
            ERROR_BRNAME(br,
                "Transmit Hold Count must be between 1 and 10 seconds");
            r = -1;
        }
    }
    if(cfg->set_max_hops)
    {
        if((6 > cfg->max_hops) || (40 < cfg->max_hops))
        {
            ERROR_BRNAME(br, "Bridge Max Hops must be between 6 and 40");
            r = -1;
        }
    }
    if(cfg->set_bridge_hello_time)
    {
        if((1 > cfg->bridge_hello_time) || (10 < cfg->bridge_hello_time))
        {
            ERROR_BRNAME(br, "Bridge Hello Time must be between 1 and 10");
            r = -1;
        }
    }
    if(cfg->set_bridge_ageing_time)
    {
        if((10 > cfg->bridge_ageing_time)||(1000000 < cfg->bridge_ageing_time))
        {
            ERROR_BRNAME(br,
                "Bridge Ageing Time must be between 10 and 1000000 seconds");
            r = -1;
        }
    }
    if(r)
        return r;
    /* Secondly, do set */
    changed = changedBridgeTimes = init = false;
    if(cfg->set_bridge_max_age || cfg->set_bridge_forward_delay)
    {
        if(cmp(new_max_age, !=, br->Max_Age)
           || cmp(new_forward_delay, !=, br->Forward_Delay)
          )
        {
            assign(br->Max_Age, new_max_age);
            assign(br->Forward_Delay, new_forward_delay);
            changed = changedBridgeTimes = true;
        }
    }
    if((cfg->set_protocol_version)
       && (cfg->protocol_version != br->ForceProtocolVersion)
      )
    {
        br->ForceProtocolVersion = cfg->protocol_version;
        changed = init = true;
    }
    if(cfg->set_tx_hold_count)
    {
        if(cfg->tx_hold_count != br->Transmit_Hold_Count)
        {
            assign(br->Transmit_Hold_Count, cfg->tx_hold_count);
            FOREACH_PORT_IN_BRIDGE(prt, br)
                assign(prt->txCount, 0u);
            changed = true;
        }
    }
    if(cfg->set_max_hops)
    {
        if(cfg->max_hops != br->MaxHops)
        {
            assign(br->MaxHops, cfg->max_hops);
            changed = changedBridgeTimes = true;
        }
    }
    if(cfg->set_bridge_hello_time)
    {
        if(cfg->bridge_hello_time != br->Hello_Time)
        {
            INFO_BRNAME(br, "bridge hello_time new=%hhu, old=%hhu",
                        cfg->bridge_hello_time, br->Hello_Time);
            assign(br->Hello_Time, cfg->bridge_hello_time);
            changed = changedBridgeTimes = true;
        }
    }
    if(cfg->set_bridge_ageing_time)
    {
        if(cfg->bridge_ageing_time != br->Ageing_Time)
        {
            INFO_BRNAME(br, "bridge ageing_time new=%u, old=%u",
                        cfg->bridge_ageing_time, br->Ageing_Time);
            assign(br->Ageing_Time, cfg->bridge_ageing_time);
        }
    }
    /* Thirdly, finalize changes */
    if(changedBridgeTimes)
    {
        FOREACH_TREE_IN_BRIDGE(tree, br)
        {
            assign(tree->BridgeTimes.remainingHops, br->MaxHops);
            assign(tree->BridgeTimes.Forward_Delay, br->Forward_Delay);
            assign(tree->BridgeTimes.Max_Age, br->Max_Age);
            assign(tree->BridgeTimes.Hello_Time, br->Hello_Time);
        /* Comment found in rstpd by Srinivas Aji:
         * Do this for any change in BridgeTimes.
         * Otherwise we fail UNH rstp.op_D test 3.2 since when administratively
         * setting BridgeForwardDelay, etc, the values don't propagate from
         * rootTimes to designatedTimes immediately without this change.
         */
            FOREACH_PTP_IN_TREE(ptp, tree)
            {
                ptp->selected = false;
                ptp->reselect = true;
                /* TODO: change this when Hello_Time will be configurable
                 *   per-port. For now, copy Bridge's Hello_Time
                 *   to the port's Hello_Time.
                 */
                assign(ptp->portTimes.Hello_Time, br->Hello_Time);
            }
        }
    }
    if(changed && br->bridgeEnabled)
    {
        if(init)
            br_state_machines_begin(br);
        else
            br_state_machines_run(br);
    }
    return 0;
}
References bridge_t::Ageing_Time, assign, br_state_machines_begin(), br_state_machines_run(), CIST_BridgeConfig::bridge_ageing_time, CIST_BridgeConfig::bridge_forward_delay, CIST_BridgeConfig::bridge_hello_time, CIST_BridgeConfig::bridge_max_age, bridge_t::bridgeEnabled, tree_t::BridgeTimes, cmp, ERROR_BRNAME, bridge_t::ForceProtocolVersion, FOREACH_PORT_IN_BRIDGE, FOREACH_PTP_IN_TREE, FOREACH_TREE_IN_BRIDGE, bridge_t::Forward_Delay, times_t::Forward_Delay, bridge_t::Hello_Time, times_t::Hello_Time, INFO_BRNAME, bridge_t::Max_Age, times_t::Max_Age, CIST_BridgeConfig::max_hops, bridge_t::MaxHops, per_tree_port_t::portTimes, CIST_BridgeConfig::protocol_version, protoMSTP, protoRSTP, protoSTP, r, times_t::remainingHops, per_tree_port_t::reselect, per_tree_port_t::selected, CIST_BridgeConfig::set_bridge_ageing_time, CIST_BridgeConfig::set_bridge_forward_delay, CIST_BridgeConfig::set_bridge_hello_time, CIST_BridgeConfig::set_bridge_max_age, CIST_BridgeConfig::set_max_hops, CIST_BridgeConfig::set_protocol_version, CIST_BridgeConfig::set_tx_hold_count, bridge_t::Transmit_Hold_Count, CIST_BridgeConfig::tx_hold_count, and port_t::txCount.
Referenced by bridge_create().
MSTP_IN_set_cist_port_config()
int MSTP_IN_set_cist_port_config (port_t * prt, CIST_PortConfig * cfg)
Definition at line 1075 of file mstp.c.
{
    bool changed;
    __u32 new_ExternalPathCost;
    bool new_p2p;
    per_tree_port_t *cist;
    bridge_t *br = prt->bridge;
    /* Firstly, validation */
    if(cfg->set_admin_p2p)
    {
        switch(cfg->admin_p2p)
        {
            case p2pAuto:
            case p2pForceTrue:
            case p2pForceFalse:
                break;
            default:
                cfg->admin_p2p = p2pAuto;
        }
    }
    /* Secondly, do set */
    changed = false;
    if(cfg->set_admin_external_port_path_cost)
    {
        prt->AdminExternalPortPathCost = cfg->admin_external_port_path_cost;
        new_ExternalPathCost = (0 == prt->AdminExternalPortPathCost) ?
                                 compute_pcost(GET_PORT_SPEED(prt))
                               : prt->AdminExternalPortPathCost;
        if(prt->ExternalPortPathCost != new_ExternalPathCost)
        {
            assign(prt->ExternalPortPathCost, new_ExternalPathCost);
            changed = true;
            /* 12.8.2.3.4 */
            cist = GET_CIST_PTP_FROM_PORT(prt);
            cist->selected = false;
            cist->reselect = true;
        }
    }
    if(cfg->set_admin_p2p)
    {
        prt->AdminP2P = cfg->admin_p2p;
        switch(prt->AdminP2P)
        {
            case p2pForceTrue:
                new_p2p = true;
                break;
            case p2pForceFalse:
                new_p2p = false;
                break;
            case p2pAuto:
            default:
                new_p2p = !!GET_PORT_DUPLEX(prt);
                break;
        }
        if(prt->operPointToPointMAC != new_p2p)
        {
            prt->operPointToPointMAC = new_p2p;
            changed = true;
        }
    }
    if(cfg->set_admin_edge_port)
    {
        if(prt->AdminEdgePort != cfg->admin_edge_port)
        {
            prt->AdminEdgePort = cfg->admin_edge_port;
            BDSM_begin(prt);
            changed = true;
        }
    }
    if(cfg->set_auto_edge_port)
    {
        if(prt->AutoEdge != cfg->auto_edge_port)
        {
            prt->AutoEdge = cfg->auto_edge_port;
            changed = true;
        }
    }
    if(cfg->set_restricted_role)
    {
        if(prt->restrictedRole != cfg->restricted_role)
        {
            prt->restrictedRole = cfg->restricted_role;
            changed = true;
        }
    }
    if(cfg->set_restricted_tcn)
    {
        if(prt->restrictedTcn != cfg->restricted_tcn)
        {
            prt->restrictedTcn = cfg->restricted_tcn;
            changed = true;
        }
    }
    if(cfg->set_bpdu_guard_port)
    {
        if(prt->BpduGuardPort != cfg->bpdu_guard_port)
        {
            prt->BpduGuardPort = cfg->bpdu_guard_port;
            INFO_PRTNAME(br, prt,"BpduGuardPort new=%d", prt->BpduGuardPort);
        }
    }
    if(cfg->set_network_port)
    {
        if(prt->NetworkPort != cfg->network_port)
        {
            prt->NetworkPort = cfg->network_port;
            INFO_PRTNAME(br, prt, "NetworkPort new=%d", prt->NetworkPort);
            /* When Network port config is removed and bridge assurance
             * inconsistency is set, clear the inconsistency.
             */
            if(!prt->NetworkPort && prt->BaInconsistent)
            {
                prt->BaInconsistent = false;
                INFO_PRTNAME(br, prt, "Clear Bridge assurance inconsistency");
            }
            changed = true;
        }
    }
    if(cfg->set_dont_txmt)
    {
        if(prt->dontTxmtBpdu != cfg->dont_txmt)
        {
            prt->dontTxmtBpdu = cfg->dont_txmt;
            INFO_PRTNAME(br, prt, "donttxmt new=%d", prt->dontTxmtBpdu);
        }
    }
    if(cfg->set_bpdu_filter_port)
    {
        if (prt->bpduFilterPort != cfg->bpdu_filter_port)
        {
            prt->bpduFilterPort = cfg->bpdu_filter_port;
            prt->num_rx_bpdu_filtered = 0;
            INFO_PRTNAME(br, prt,"bpduFilterPort new=%d", prt->bpduFilterPort);
        }
    }
    if(changed && prt->portEnabled)
        br_state_machines_run(prt->bridge);
    return 0;
}
References CIST_PortConfig::admin_edge_port, CIST_PortConfig::admin_external_port_path_cost, CIST_PortConfig::admin_p2p, port_t::AdminEdgePort, port_t::AdminExternalPortPathCost, port_t::AdminP2P, assign, CIST_PortConfig::auto_edge_port, port_t::AutoEdge, port_t::BaInconsistent, BDSM_begin(), CIST_PortConfig::bpdu_filter_port, CIST_PortConfig::bpdu_guard_port, port_t::bpduFilterPort, port_t::BpduGuardPort, br_state_machines_run(), port_t::bridge, compute_pcost(), CIST_PortConfig::dont_txmt, port_t::dontTxmtBpdu, port_t::ExternalPortPathCost, GET_CIST_PTP_FROM_PORT, GET_PORT_DUPLEX, GET_PORT_SPEED, INFO_PRTNAME, CIST_PortConfig::network_port, port_t::NetworkPort, port_t::num_rx_bpdu_filtered, port_t::operPointToPointMAC, p2pAuto, p2pForceFalse, p2pForceTrue, port_t::portEnabled, per_tree_port_t::reselect, CIST_PortConfig::restricted_role, CIST_PortConfig::restricted_tcn, port_t::restrictedRole, port_t::restrictedTcn, per_tree_port_t::selected, CIST_PortConfig::set_admin_edge_port, CIST_PortConfig::set_admin_external_port_path_cost, CIST_PortConfig::set_admin_p2p, CIST_PortConfig::set_auto_edge_port, CIST_PortConfig::set_bpdu_filter_port, CIST_PortConfig::set_bpdu_guard_port, CIST_PortConfig::set_dont_txmt, CIST_PortConfig::set_network_port, CIST_PortConfig::set_restricted_role, and CIST_PortConfig::set_restricted_tcn.
Referenced by set_if_up().
MSTP_IN_set_fid2mstid()
bool MSTP_IN_set_fid2mstid (bridge_t * br, __u16 fid, __u16 mstid)
Definition at line 1346 of file mstp.c.
{
    tree_t *tree;
    __be16 MSTID;
    bool found;
    int vid;
    if(fid > MAX_FID)
    {
        ERROR_BRNAME(br, "Bad FID(%hu)", fid);
        return false;
    }
    MSTID = __cpu_to_be16(mstid);
    found = false;
    FOREACH_TREE_IN_BRIDGE(tree, br)
    {
        if(tree->MSTID == MSTID)
        {
            found = true;
            break;
        }
    }
    if(!found)
    {
        ERROR_BRNAME(br, "MSTID(%hu) not found", mstid);
        return false;
    }
    if(br->fid2mstid[fid] != MSTID)
    {
        br->fid2mstid[fid] = MSTID;
        /* check if there are VLANs using this FID */
        for(vid = 1; vid <= MAX_VID; ++vid)
        {
            if(br->vid2fid[vid] == fid)
            {
                RecalcConfigDigest(br);
                br_state_machines_begin(br);
                break;
            }
        }
    }
    return true;
}
References br_state_machines_begin(), ERROR_BRNAME, bridge_t::fid2mstid, FOREACH_TREE_IN_BRIDGE, MAX_FID, MAX_VID, tree_t::MSTID, RecalcConfigDigest(), and bridge_t::vid2fid.
MSTP_IN_set_mst_config_id()
void MSTP_IN_set_mst_config_id (bridge_t * br, __u16 revision, __u8 * name)
Definition at line 1605 of file mstp.c.
{
    __be16 valueRevision = __cpu_to_be16(revision);
    bool changed = (0 != strncmp((char *)name, (char *)br->MstConfigId.s.configuration_name,
                                 sizeof(br->MstConfigId.s.configuration_name))
                   )
                   || (valueRevision != br->MstConfigId.s.revision_level);
    if(changed)
    {
        assign(br->MstConfigId.s.revision_level, valueRevision);
        memset(br->MstConfigId.s.configuration_name, 0,
               sizeof(br->MstConfigId.s.configuration_name));
        strncpy((char *)br->MstConfigId.s.configuration_name, (char *)name,
                sizeof(br->MstConfigId.s.configuration_name) - 1);
        br_state_machines_begin(br);
    }
}
References assign, br_state_machines_begin(), and bridge_t::MstConfigId.
MSTP_IN_set_msti_bridge_config()
int MSTP_IN_set_msti_bridge_config (tree_t * tree, __u8 bridge_priority)
Definition at line 970 of file mstp.c.
{
    per_tree_port_t *ptp;
    __u8 valuePri;
    if(15 < bridge_priority)
    {
        ERROR_BRNAME(tree->bridge,
                     "MSTI %hu: Bridge Priority must be between 0 and 15",
                     __be16_to_cpu(tree->MSTID));
        return -1;
    }
    valuePri = bridge_priority << 4;
    if(GET_PRIORITY_FROM_IDENTIFIER(tree->BridgeIdentifier) == valuePri)
        return 0;
    SET_PRIORITY_IN_IDENTIFIER(valuePri, tree->BridgeIdentifier);
    tree->BridgePriority.RootID = tree->BridgePriority.RRootID =
        tree->BridgePriority.DesignatedBridgeID = tree->BridgeIdentifier;
    /* 12.8.1.4.4 do not require reselect, but I think it is needed,
     *  because 12.8.1.3.4.c) requires it */
    FOREACH_PTP_IN_TREE(ptp, tree)
    {
        ptp->selected = false;
        ptp->reselect = true;
    }
    return 0;
}
References tree_t::bridge, tree_t::BridgeIdentifier, tree_t::BridgePriority, port_priority_vector_t::DesignatedBridgeID, ERROR_BRNAME, FOREACH_PTP_IN_TREE, GET_PRIORITY_FROM_IDENTIFIER, tree_t::MSTID, per_tree_port_t::reselect, port_priority_vector_t::RootID, port_priority_vector_t::RRootID, per_tree_port_t::selected, and SET_PRIORITY_IN_IDENTIFIER.
MSTP_IN_set_msti_port_config()
int MSTP_IN_set_msti_port_config (per_tree_port_t * ptp, MSTI_PortConfig * cfg)
Definition at line 1230 of file mstp.c.
{
    __u8 valuePri;
    __u32 new_InternalPathCost;
    bool changed = false;
    port_t *prt = ptp->port;
    bridge_t *br = prt->bridge;
    if(cfg->set_port_priority)
    {
        if(15 < cfg->port_priority)
        {
            ERROR_MSTINAME(br, prt, ptp,
                           "Port Priority must be between 0 and 15");
            return -1;
        }
        valuePri = cfg->port_priority << 4;
        if(GET_PRIORITY_FROM_IDENTIFIER(ptp->portId) != valuePri)
        {
            SET_PRIORITY_IN_IDENTIFIER(valuePri, ptp->portId);
            changed = true;
        }
    }
    if(cfg->set_admin_internal_port_path_cost)
    {
        ptp->AdminInternalPortPathCost = cfg->admin_internal_port_path_cost;
        new_InternalPathCost = (0 == ptp->AdminInternalPortPathCost) ?
                                 compute_pcost(GET_PORT_SPEED(prt))
                               : ptp->AdminInternalPortPathCost;
        if(ptp->InternalPortPathCost != new_InternalPathCost)
        {
            assign(ptp->InternalPortPathCost, new_InternalPathCost);
            changed = true;
        }
    }
    if(changed && prt->portEnabled)
    {
        /* 12.8.2.4.4 */
        ptp->selected = false;
        ptp->reselect = true;
        br_state_machines_run(br);
    }
    return 0;
}
References MSTI_PortConfig::admin_internal_port_path_cost, per_tree_port_t::AdminInternalPortPathCost, assign, br_state_machines_run(), port_t::bridge, compute_pcost(), ERROR_MSTINAME, GET_PORT_SPEED, GET_PRIORITY_FROM_IDENTIFIER, per_tree_port_t::InternalPortPathCost, per_tree_port_t::port, MSTI_PortConfig::port_priority, port_t::portEnabled, per_tree_port_t::portId, per_tree_port_t::reselect, per_tree_port_t::selected, MSTI_PortConfig::set_admin_internal_port_path_cost, MSTI_PortConfig::set_port_priority, and SET_PRIORITY_IN_IDENTIFIER.
MSTP_IN_set_port_enable()
void MSTP_IN_set_port_enable (port_t * prt, bool up, int speed, int duplex)
Definition at line 452 of file mstp.c.
{
    __u32 computed_pcost, new_ExternalPathCost, new_InternalPathCost;
    per_tree_port_t *ptp;
    bool new_p2p;
    bool changed = false;
    if(up)
    {
        computed_pcost = compute_pcost(speed);
        new_ExternalPathCost = (0 == prt->AdminExternalPortPathCost) ?
                                 computed_pcost
                               : prt->AdminExternalPortPathCost;
        if(prt->ExternalPortPathCost != new_ExternalPathCost)
        {
            assign(prt->ExternalPortPathCost, new_ExternalPathCost);
            changed = true;
        }
        FOREACH_PTP_IN_PORT(ptp, prt)
        {
            new_InternalPathCost = (0 == ptp->AdminInternalPortPathCost) ?
                                    computed_pcost
                                   : ptp->AdminInternalPortPathCost;
            if(ptp->InternalPortPathCost != new_InternalPathCost)
            {
                assign(ptp->InternalPortPathCost, new_InternalPathCost);
                changed = true;
            }
        }
        switch(prt->AdminP2P)
        {
            case p2pForceTrue:
                new_p2p = true;
                break;
            case p2pForceFalse:
                new_p2p = false;
                break;
            case p2pAuto:
            default:
                new_p2p = !!duplex;
                break;
        }
        if(prt->operPointToPointMAC != new_p2p)
        {
            prt->operPointToPointMAC = new_p2p;
            changed = true;
        }
        if(!prt->portEnabled)
        {
            prt->portEnabled = true;
            prt->BpduGuardError = false;
            prt->BaInconsistent = false;
            prt->num_rx_bpdu_filtered = 0;
            prt->num_rx_bpdu = 0;
            prt->num_rx_tcn = 0;
            prt->num_tx_bpdu = 0;
            prt->num_tx_tcn = 0;
            changed = true;
            /* When port is enabled, initialize bridge assurance timer,
             * so that enough time is given before port is put in
             * inconsistent state.
             */
            updtbrAssuRcvdInfoWhile(prt);
        }
    }
    else
    {
        if(prt->portEnabled)
        {
            prt->portEnabled = false;
            changed = true;
        }
    }
    if(changed)
        br_state_machines_run(prt->bridge);
}
References port_t::AdminExternalPortPathCost, per_tree_port_t::AdminInternalPortPathCost, port_t::AdminP2P, assign, port_t::BaInconsistent, port_t::BpduGuardError, br_state_machines_run(), port_t::bridge, compute_pcost(), port_t::ExternalPortPathCost, FOREACH_PTP_IN_PORT, per_tree_port_t::InternalPortPathCost, port_t::num_rx_bpdu, port_t::num_rx_bpdu_filtered, port_t::num_rx_tcn, port_t::num_tx_bpdu, port_t::num_tx_tcn, port_t::operPointToPointMAC, p2pAuto, p2pForceFalse, p2pForceTrue, port_t::portEnabled, and updtbrAssuRcvdInfoWhile().
Referenced by set_if_up().
MSTP_IN_set_vid2fid()
bool MSTP_IN_set_vid2fid (bridge_t * br, __u16 vid, __u16 fid)
Definition at line 1296 of file mstp.c.
{
    bool vid2mstid_changed;
    if((vid < 1) || (vid > MAX_VID) || (fid > MAX_FID))
    {
        ERROR_BRNAME(br, "Error allocating VID(%hu) to FID(%hu)", vid, fid);
        return false;
    }
    vid2mstid_changed =
        (br->fid2mstid[fid] != br->fid2mstid[br->vid2fid[vid]]);
    br->vid2fid[vid] = fid;
    if(vid2mstid_changed)
    {
        RecalcConfigDigest(br);
        br_state_machines_begin(br);
    }
    return true;
}
References br_state_machines_begin(), ERROR_BRNAME, bridge_t::fid2mstid, MAX_FID, MAX_VID, RecalcConfigDigest(), and bridge_t::vid2fid.
MSTP_OUT_flush_all_fids()
void MSTP_OUT_flush_all_fids (per_tree_port_t * ptp)
Definition at line 526 of file bridge_track.c.
{
    port_t *prt = ptp->port;
    bridge_t *br = prt->bridge;
    /* Translate CIST flushing to the kernel bridge code */
    if(0 == ptp->MSTID)
    { /* CIST */
        if(0 > br_flush_port(prt->sysdeps.name))
            ERROR_PRTNAME(br, prt,
                          "Couldn't flush kernel bridge forwarding database");
    }
    /* Completion signal MSTP_IN_all_fids_flushed will be called by driver */
    INFO_MSTINAME(br, prt, ptp, "Flushing forwarding database");
    driver_flush_all_fids(ptp);
}
References br_flush_port(), port_t::bridge, driver_flush_all_fids(), ERROR_PRTNAME, INFO_MSTINAME, per_tree_port_t::MSTID, sysdep_if_data_t::name, per_tree_port_t::port, and port_t::sysdeps.
Referenced by set_fdbFlush().
MSTP_OUT_set_ageing_time()
void MSTP_OUT_set_ageing_time (port_t * prt, unsigned int ageingTime)
Definition at line 543 of file bridge_track.c.
{
    unsigned int actual_ageing_time;
    bridge_t *br = prt->bridge;
    actual_ageing_time = driver_set_ageing_time(prt, ageingTime);
    INFO_PRTNAME(br, prt, "Setting new ageing time to %u", actual_ageing_time);
    /*
     * Translate new ageing time to the kernel bridge code.
     * Kernel bridging code does not support per-port ageing time,
     * so set ageing time for the whole bridge.
     */
    if(0 > br_set_ageing_time(br->sysdeps.name, actual_ageing_time))
        ERROR_BRNAME(br, "Couldn't set new ageing time in kernel bridge");
}
References br_set_ageing_time(), port_t::bridge, driver_set_ageing_time(), ERROR_BRNAME, INFO_PRTNAME, sysdep_br_data_t::name, and bridge_t::sysdeps.
Referenced by MSTP_IN_one_second(), MSTP_IN_set_bridge_enable(), and set_fdbFlush().
MSTP_OUT_set_state()
void MSTP_OUT_set_state (per_tree_port_t * ptp, int new_state)
Definition at line 478 of file bridge_track.c.
{
    char * state_name;
    port_t *prt = ptp->port;
    bridge_t *br = prt->bridge;
    if(ptp->state == new_state)
        return;
    ptp->state = driver_set_new_state(ptp, new_state);
    switch(ptp->state)
    {
        case BR_STATE_LISTENING:
            state_name = "listening";
            break;
        case BR_STATE_LEARNING:
            state_name = "learning";
            break;
        case BR_STATE_FORWARDING:
            state_name = "forwarding";
            ++(prt->num_trans_fwd);
            break;
        case BR_STATE_BLOCKING:
            state_name = "blocking";
            ++(prt->num_trans_blk);
            break;
        default:
        case BR_STATE_DISABLED:
            state_name = "disabled";
            break;
    }
    INFO_MSTINAME(br, prt, ptp, "entering %s state", state_name);
    /* Translate new CIST state to the kernel bridge code */
    if(0 == ptp->MSTID)
    { /* CIST */
        if(0 > br_set_state(&rth_state, prt->sysdeps.if_index, ptp->state))
            INFO_PRTNAME(br, prt, "Couldn't set kernel bridge state %s",
                          state_name);
    }
}
References br_set_state(), port_t::bridge, driver_set_new_state(), sysdep_if_data_t::if_index, INFO_MSTINAME, INFO_PRTNAME, per_tree_port_t::MSTID, port_t::num_trans_blk, port_t::num_trans_fwd, per_tree_port_t::port, rth_state, per_tree_port_t::state, and port_t::sysdeps.
Referenced by MSTP_IN_set_bridge_enable(), PSTSM_to_DISCARDING(), PSTSM_to_FORWARDING(), and PSTSM_to_LEARNING().
MSTP_OUT_shutdown_port()
void MSTP_OUT_shutdown_port (port_t * prt)
Definition at line 623 of file bridge_track.c.
{
    if(0 > if_shutdown(prt->sysdeps.name))
        ERROR_PRTNAME(prt->bridge, prt, "Couldn't shutdown port");
}
References port_t::bridge, ERROR_PRTNAME, if_shutdown(), sysdep_if_data_t::name, and port_t::sysdeps.
Referenced by MSTP_IN_rx_bpdu().
MSTP_OUT_tx_bpdu()
void MSTP_OUT_tx_bpdu (port_t * prt, bpdu_t * bpdu, int size)
Definition at line 560 of file bridge_track.c.
{
    char *bpdu_type, *tcflag;
    bridge_t *br = prt->bridge;
    switch(bpdu->protocolVersion)
    {
        case protoSTP:
            switch(bpdu->bpduType)
            {
                case bpduTypeConfig:
                    bpdu_type = "STP-Config";
                    break;
                case bpduTypeTCN:
                    bpdu_type = "STP-TCN";
                    break;
                default:
                    bpdu_type = "STP-UnknownType";
            }
            break;
        case protoRSTP:
            bpdu_type = "RST";
            break;
        case protoMSTP:
            bpdu_type = "MST";
            break;
        default:
            bpdu_type = "UnknownProto";
    }
    ++(prt->num_tx_bpdu);
    if((protoSTP == bpdu->protocolVersion) && (bpduTypeTCN == bpdu->bpduType))
    {
        ++(prt->num_tx_tcn);
        LOG_PRTNAME(br, prt, "sending %s BPDU", bpdu_type);
    }
    else
    {
        tcflag = "";
        if(bpdu->flags & (1 << offsetTc))
        {
            ++(prt->num_tx_tcn);
            tcflag = ", tcFlag";
        }
        LOG_PRTNAME(br, prt, "sending %s BPDU%s", bpdu_type, tcflag);
    }
    struct llc_header h;
    memcpy(h.dest_addr, bridge_group_address, ETH_ALEN);
    memcpy(h.src_addr, prt->sysdeps.macaddr, ETH_ALEN);
    h.len8023 = __cpu_to_be16(size + LLC_PDU_LEN_U);
    h.d_sap = h.s_sap = LLC_SAP_BSPAN;
    h.llc_ctrl = LLC_PDU_TYPE_U;
    struct iovec iov[2] =
    {
        { .iov_base = &h, .iov_len = sizeof(h) },
        { .iov_base = bpdu, .iov_len = size }
    };
    packet_send(prt->sysdeps.if_index, iov, 2, sizeof(h) + size);
}
References bpduTypeConfig, bpduTypeTCN, port_t::bridge, bridge_group_address, llc_header::d_sap, llc_header::dest_addr, sysdep_if_data_t::if_index, llc_header::len8023, llc_header::llc_ctrl, LLC_PDU_LEN_U, LLC_PDU_TYPE_U, LLC_SAP_BSPAN, LOG_PRTNAME, sysdep_if_data_t::macaddr, port_t::num_tx_bpdu, port_t::num_tx_tcn, offsetTc, packet_send(), protoMSTP, protoRSTP, protoSTP, llc_header::s_sap, llc_header::src_addr, and port_t::sysdeps.
Referenced by txConfig(), txMstp(), and txTcn().
Variable Documentation
configuration_digest
__u8 configuration_digest[CONFIGURATION_DIGEST_LEN]
Definition at line 3 of file mstp.h.
Referenced by __attribute__::__attribute__().
configuration_name
__u8 configuration_name[CONFIGURATION_NAME_LEN]
Definition at line 1 of file mstp.h.
Referenced by __attribute__::__attribute__().
mac_address
__u8 mac_address[ETH_ALEN]
Definition at line 1 of file mstp.h.
Referenced by bridge_identifier_t::__attribute__().
priority
__be16 priority
Definition at line 0 of file mstp.h.
Referenced by __attribute__(), bridge_identifier_t::__attribute__(), log_message(), set_ip_source_policy(), and ulog().
revision_level
__be16 revision_level
Definition at line 2 of file mstp.h.
Referenced by __attribute__::__attribute__().
selector
__u8 selector
Definition at line 0 of file mstp.h.
Referenced by __attribute__::__attribute__().