zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/netifd/proto.c File Reference
proto.c File Reference
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <limits.h>
#include <arpa/inet.h>
#include <netinet/in.h>
#include "netifd.h"
#include "system.h"
#include "interface.h"
#include "interface-ip.h"
#include "proto.h"
Enumerations
enum {
OPT_IPADDR , OPT_IP6ADDR , OPT_NETMASK , OPT_BROADCAST ,
OPT_PTPADDR , OPT_GATEWAY , OPT_IP6GW , OPT_IP6PREFIX ,
OPT_IP6DEPRECATED , __OPT_MAX
}
enum {
ADDR_IPADDR , ADDR_MASK , ADDR_BROADCAST , ADDR_PTP ,
ADDR_PREFERRED , ADDR_VALID , ADDR_OFFLINK , ADDR_CLASS ,
__ADDR_MAX
}
Functions
static struct device_addr * alloc_device_addr (bool v6, bool ext)
static struct device_addr * parse_addr (const char *str, bool v6, int mask, bool ext, uint32_t broadcast, uint32_t ptp, bool deprecated)
static int parse_static_address_option (struct interface *iface, struct blob_attr *attr, bool v6, int netmask, bool ext, uint32_t broadcast, uint32_t ptp, bool deprecated)
static struct device_addr * parse_address_item (struct blob_attr *attr, bool v6, bool ext)
static int parse_address_list (struct interface *iface, struct blob_attr *attr, bool v6, bool ext)
static bool parse_gateway_option (struct interface *iface, struct blob_attr *attr, bool v6)
static bool parse_prefix_option (struct interface *iface, const char *str, size_t len)
static int parse_prefix_list (struct interface *iface, struct blob_attr *attr)
int proto_apply_static_ip_settings (struct interface *iface, struct blob_attr *attr)
int proto_apply_ip_settings (struct interface *iface, struct blob_attr *attr, bool ext)
void add_proto_handler (struct proto_handler *p)
static void default_proto_free (struct interface_proto_state *proto)
static int invalid_proto_handler (struct interface_proto_state *proto, enum interface_proto_cmd cmd, bool force)
static int no_proto_handler (struct interface_proto_state *proto, enum interface_proto_cmd cmd, bool force)
static struct interface_proto_state * default_proto_attach (const struct proto_handler *h, struct interface *iface, struct blob_attr *attr)
static const struct proto_handler * get_proto_handler (const char *name)
void proto_dump_handlers (struct blob_buf *b)
void proto_init_interface (struct interface *iface, struct blob_attr *attr)
void proto_attach_interface (struct interface *iface, const char *proto_name)
int interface_proto_event (struct interface_proto_state *proto, enum interface_proto_cmd cmd, bool force)
Variables
static struct avl_tree handlers
static const struct blobmsg_policy proto_ip_attributes [__OPT_MAX]
static const struct uci_blob_param_info proto_ip_attr_info [__OPT_MAX]
static const char *const proto_ip_validate [__OPT_MAX]
const struct uci_blob_param_list proto_ip_attr
static const struct blobmsg_policy proto_ip_addr [__ADDR_MAX]
static const struct proto_handler no_proto
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPT_IPADDR
OPT_IP6ADDR
OPT_NETMASK
OPT_BROADCAST
OPT_PTPADDR
OPT_GATEWAY
OPT_IP6GW
OPT_IP6PREFIX
OPT_IP6DEPRECATED
__OPT_MAX
Definition at line 31 of file proto.c.
     {
    OPT_IPADDR,
    OPT_IP6ADDR,
    OPT_NETMASK,
    OPT_BROADCAST,
    OPT_PTPADDR,
    OPT_GATEWAY,
    OPT_IP6GW,
    OPT_IP6PREFIX,
    OPT_IP6DEPRECATED,
    __OPT_MAX,
};
anonymous enum
anonymous enum
Enumerator
ADDR_IPADDR
ADDR_MASK
ADDR_BROADCAST
ADDR_PTP
ADDR_PREFERRED
ADDR_VALID
ADDR_OFFLINK
ADDR_CLASS
__ADDR_MAX
Definition at line 80 of file proto.c.
     {
    ADDR_IPADDR,
    ADDR_MASK,
    ADDR_BROADCAST,
    ADDR_PTP,
    ADDR_PREFERRED,
    ADDR_VALID,
    ADDR_OFFLINK,
    ADDR_CLASS,
    __ADDR_MAX
};
Function Documentation
add_proto_handler()
void add_proto_handler (struct proto_handler * p)
Definition at line 518 of file proto.c.
{
    if (!handlers.comp)
        avl_init(&handlers, avl_strcmp, false, NULL);
    if (p->avl.key)
        return;
    p->avl.key = p->name;
    avl_insert(&handlers, &p->avl);
}
References proto_handler::avl, avl_init(), avl_insert(), avl_strcmp(), avl_tree::comp, handlers, avl_node::key, and proto_handler::name.
Referenced by proto_shell_add_handler(), and static_proto_init().
alloc_device_addr()
static struct device_addr * alloc_device_addr (bool v6, bool ext) static
Definition at line 104 of file proto.c.
{
    struct device_addr *addr;
    addr = calloc(1, sizeof(*addr));
    if (!addr)
        return NULL;
    addr->flags = v6 ? DEVADDR_INET6 : DEVADDR_INET4;
    if (ext)
        addr->flags |= DEVADDR_EXTERNAL;
    return addr;
}
References device_addr::addr, DEVADDR_EXTERNAL, DEVADDR_INET4, and DEVADDR_INET6.
Referenced by parse_addr(), and parse_address_item().
default_proto_attach()
static struct interface_proto_state * default_proto_attach (const struct proto_handler * h, struct interface * iface, struct blob_attr * attr) static
Definition at line 551 of file proto.c.
{
    struct interface_proto_state *proto;
    proto = calloc(1, sizeof(*proto));
    if (!proto)
        return NULL;
    proto->free = default_proto_free;
    proto->cb = no_proto_handler;
    return proto;
}
References interface_proto_state::cb, default_proto_free(), interface_proto_state::free, and no_proto_handler().
default_proto_free()
static void default_proto_free (struct interface_proto_state * proto) static
Definition at line 531 of file proto.c.
{
    free(proto);
}
Referenced by default_proto_attach().
get_proto_handler()
static const struct proto_handler * get_proto_handler (const char * name) static
Definition at line 573 of file proto.c.
{
    struct proto_handler *proto;
    if (!strcmp(name, "none"))
        return &no_proto;
    if (!handlers.comp)
        return NULL;
    return avl_find_element(&handlers, name, proto, avl);
}
References proto_handler::avl, avl_find_element, avl_tree::comp, handlers, proto_handler::name, and no_proto.
Referenced by proto_attach_interface().
interface_proto_event()
int interface_proto_event (struct interface_proto_state * proto, enum interface_proto_cmd cmd, bool force)
Definition at line 656 of file proto.c.
{
    enum interface_proto_event ev;
    int ret;
    ret = proto->cb(proto, cmd, force);
    if (ret || !(proto->handler->flags & PROTO_FLAG_IMMEDIATE))
        goto out;
    switch(cmd) {
    case PROTO_CMD_SETUP:
        ev = IFPEV_UP;
        break;
    case PROTO_CMD_TEARDOWN:
        ev = IFPEV_DOWN;
        break;
    case PROTO_CMD_RENEW:
        ev = IFPEV_RENEW;
        break;
    default:
        return -EINVAL;
    }
    proto->proto_event(proto, ev);
out:
    return ret;
}
References interface_proto_state::cb, cmd, proto_handler::flags, interface_proto_state::handler, IFPEV_DOWN, IFPEV_RENEW, IFPEV_UP, PROTO_CMD_RENEW, PROTO_CMD_SETUP, PROTO_CMD_TEARDOWN, interface_proto_state::proto_event, and PROTO_FLAG_IMMEDIATE.
invalid_proto_handler()
static int invalid_proto_handler (struct interface_proto_state * proto, enum interface_proto_cmd cmd, bool force) static
Definition at line 537 of file proto.c.
{
    return -1;
}
Referenced by proto_init_interface().
no_proto_handler()
static int no_proto_handler (struct interface_proto_state * proto, enum interface_proto_cmd cmd, bool force) static
Definition at line 544 of file proto.c.
{
    return 0;
}
Referenced by default_proto_attach().
parse_addr()
static struct device_addr * parse_addr (const char * str, bool v6, int mask, bool ext, uint32_t broadcast, uint32_t ptp, bool deprecated) static
Definition at line 120 of file proto.c.
{
    struct device_addr *addr;
    int af = v6 ? AF_INET6 : AF_INET;
    addr = alloc_device_addr(v6, ext);
    if (!addr)
        return NULL;
    addr->mask = mask;
    if (!parse_ip_and_netmask(af, str, &addr->addr, &addr->mask))
        goto error;
    if (v6 && IN6_IS_ADDR_MULTICAST(&addr->addr.in6))
        goto error;
    if (broadcast)
        addr->broadcast = broadcast;
    if (ptp)
        addr->point_to_point = ptp;
    if (deprecated)
        addr->preferred_until = system_get_rtime();
    return addr;
error:
    free(addr);
    return NULL;
}
References device_addr::addr, alloc_device_addr(), device_addr::broadcast, if_addr::in6, device_addr::mask, parse_ip_and_netmask(), and system_get_rtime().
Referenced by parse_static_address_option().
parse_address_item()
static struct device_addr * parse_address_item (struct blob_attr * attr, bool v6, bool ext) static
Definition at line 184 of file proto.c.
{
    struct device_addr *addr;
    struct blob_attr *tb[__ADDR_MAX];
    struct blob_attr *cur;
    if (blobmsg_type(attr) != BLOBMSG_TYPE_TABLE)
        return NULL;
    addr = alloc_device_addr(v6, ext);
    if (!addr)
        return NULL;
    blobmsg_parse(proto_ip_addr, __ADDR_MAX, tb, blobmsg_data(attr), blobmsg_data_len(attr));
    addr->mask = v6 ? 128 : 32;
    if ((cur = tb[ADDR_MASK])) {
        unsigned int new_mask;
        new_mask = parse_netmask_string(blobmsg_data(cur), v6);
        if (new_mask > addr->mask)
            goto error;
        addr->mask = new_mask;
    }
    cur = tb[ADDR_IPADDR];
    if (!cur)
        goto error;
    if (!inet_pton(v6 ? AF_INET6 : AF_INET, blobmsg_data(cur), &addr->addr))
        goto error;
    if ((cur = tb[ADDR_OFFLINK]) && blobmsg_get_bool(cur))
        addr->flags |= DEVADDR_OFFLINK;
    if (!v6) {
        if ((cur = tb[ADDR_BROADCAST]) &&
            !inet_pton(AF_INET, blobmsg_data(cur), &addr->broadcast))
            goto error;
        if ((cur = tb[ADDR_PTP]) &&
            !inet_pton(AF_INET, blobmsg_data(cur), &addr->point_to_point))
            goto error;
    } else {
        time_t now = system_get_rtime();
        if ((cur = tb[ADDR_PREFERRED])) {
            int64_t preferred = blobmsg_get_u32(cur);
            int64_t preferred_until = preferred + (int64_t)now;
            if (preferred_until <= LONG_MAX && preferred != 0xffffffffLL)
                addr->preferred_until = preferred_until;
        }
        if ((cur = tb[ADDR_VALID])) {
            int64_t valid = blobmsg_get_u32(cur);
            int64_t valid_until = valid + (int64_t)now;
            if (valid_until <= LONG_MAX && valid != 0xffffffffLL)
                addr->valid_until = valid_until;
        }
        if (addr->valid_until) {
            if (!addr->preferred_until)
                addr->preferred_until = addr->valid_until;
            else if (addr->preferred_until > addr->valid_until)
                goto error;
        }
        if ((cur = tb[ADDR_CLASS]))
            addr->pclass = strdup(blobmsg_get_string(cur));
    }
    return addr;
error:
    free(addr);
    return NULL;
}
References __ADDR_MAX, device_addr::addr, ADDR_BROADCAST, ADDR_CLASS, ADDR_IPADDR, ADDR_MASK, ADDR_OFFLINK, ADDR_PREFERRED, ADDR_PTP, ADDR_VALID, alloc_device_addr(), blobmsg_data(), blobmsg_data_len(), blobmsg_get_bool(), blobmsg_get_string(), blobmsg_get_u32(), blobmsg_parse(), BLOBMSG_TYPE_TABLE, device_addr::broadcast, DEVADDR_OFFLINK, device_addr::flags, device_addr::mask, parse_netmask_string(), device_addr::pclass, device_addr::point_to_point, device_addr::preferred_until, proto_ip_addr, system_get_rtime(), and device_addr::valid_until.
Referenced by parse_address_list().
parse_address_list()
static int parse_address_list (struct interface * iface, struct blob_attr * attr, bool v6, bool ext) static
Definition at line 263 of file proto.c.
{
    struct device_addr *addr;
    struct blob_attr *cur;
    int n_addr = 0;
    size_t rem;
    blobmsg_for_each_attr(cur, attr, rem) {
        addr = parse_address_item(cur, v6, ext);
        if (!addr)
            return -1;
        addr->index = n_addr;
        n_addr++;
        vlist_add(&iface->proto_ip.addr, &addr->node, addr);
    }
    return n_addr;
}
References device_addr::addr, interface_ip_settings::addr, blobmsg_for_each_attr, device_addr::index, device_addr::node, parse_address_item(), interface::proto_ip, and vlist_add().
Referenced by proto_apply_ip_settings().
parse_gateway_option()
static bool parse_gateway_option (struct interface * iface, struct blob_attr * attr, bool v6) static
Definition at line 285 of file proto.c.
{
    struct device_route *route;
    const char *str = blobmsg_data(attr);
    int af = v6 ? AF_INET6 : AF_INET;
    route = calloc(1, sizeof(*route));
    if (!route)
        return NULL;
    if (!inet_pton(af, str, &route->nexthop)) {
        interface_add_error(iface, "proto", "INVALID_GATEWAY", &str, 1);
        free(route);
        return false;
    }
    route->mask = 0;
    route->flags = (v6 ? DEVADDR_INET6 : DEVADDR_INET4);
    route->metric = iface->metric;
    unsigned int table = (v6) ? iface->ip6table : iface->ip4table;
    if (table) {
        route->table = table;
        route->flags |= DEVROUTE_SRCTABLE;
    }
    vlist_add(&iface->proto_ip.route, &route->node, route);
    return true;
}
References blobmsg_data(), DEVADDR_INET4, DEVADDR_INET6, DEVROUTE_SRCTABLE, device_route::flags, device_route::iface, interface_add_error(), interface::ip4table, interface::ip6table, device_route::mask, device_route::metric, interface::metric, device_route::nexthop, device_route::node, interface::proto_ip, interface_ip_settings::route, device_route::table, and vlist_add().
Referenced by proto_apply_ip_settings(), and proto_apply_static_ip_settings().
parse_prefix_list()
static int parse_prefix_list (struct interface * iface, struct blob_attr * attr) static
Definition at line 391 of file proto.c.
{
    struct blob_attr *cur;
    int n_addr = 0;
    size_t rem;
    blobmsg_for_each_attr(cur, attr, rem) {
        if (blobmsg_type(cur) != BLOBMSG_TYPE_STRING)
            return -1;
        n_addr++;
        if (!parse_prefix_option(iface, blobmsg_data(cur),
                blobmsg_data_len(cur)))
            return -1;
    }
    return n_addr;
}
References blobmsg_data(), blobmsg_data_len(), blobmsg_for_each_attr, BLOBMSG_TYPE_STRING, and parse_prefix_option().
Referenced by proto_apply_ip_settings(), and proto_apply_static_ip_settings().
parse_prefix_option()
static bool parse_prefix_option (struct interface * iface, const char * str, size_t len) static
Definition at line 317 of file proto.c.
{
    char buf[128] = {0}, *saveptr;
    if (len >= sizeof(buf))
        return false;
    memcpy(buf, str, len);
    char *addrstr = strtok_r(buf, "/", &saveptr);
    if (!addrstr)
        return false;
    char *lengthstr = strtok_r(NULL, ",", &saveptr);
    if (!lengthstr)
        return false;
    char *prefstr = strtok_r(NULL, ",", &saveptr);
    char *validstr = (!prefstr) ? NULL : strtok_r(NULL, ",", &saveptr);
    char *addstr = (!validstr) ? NULL : strtok_r(NULL, ",", &saveptr);
    const char *pclass = NULL;
    int64_t pref = (!prefstr) ? 0 : strtoul(prefstr, NULL, 10);
    int64_t valid = (!validstr) ? 0 : strtoul(validstr, NULL, 10);
    uint8_t length = strtoul(lengthstr, NULL, 10), excl_length = 0;
    if (length < 1 || length > 64)
        return false;
    struct in6_addr addr, excluded, *excludedp = NULL;
    if (inet_pton(AF_INET6, addrstr, &addr) < 1)
        return false;
    for (; addstr; addstr = strtok_r(NULL, ",", &saveptr)) {
        char *key = NULL, *val = NULL, *addsaveptr;
        if (!(key = strtok_r(addstr, "=", &addsaveptr)) ||
                !(val = strtok_r(NULL, ",", &addsaveptr)))
            continue;
        if (!strcmp(key, "excluded")) {
            char *sep = strchr(val, '/');
            if (!sep)
                return false;
            *sep = 0;
            excl_length = atoi(sep + 1);
            if (inet_pton(AF_INET6, val, &excluded) < 1)
                return false;
            excludedp = &excluded;
        } else if (!strcmp(key, "class")) {
            pclass = val;
        }
    }
    int64_t now = system_get_rtime();
    time_t preferred_until = 0;
    if (prefstr && pref != 0xffffffffLL && pref + now <= LONG_MAX)
        preferred_until = pref + now;
    time_t valid_until = 0;
    if (validstr && valid != 0xffffffffLL && valid + now <= LONG_MAX)
        valid_until = valid + now;
    interface_ip_add_device_prefix(iface, &addr, length,
            valid_until, preferred_until,
            excludedp, excl_length, pclass);
    return true;
}
References buf, interface_ip_add_device_prefix(), and system_get_rtime().
Referenced by parse_prefix_list().
parse_static_address_option()
static int parse_static_address_option (struct interface * iface, struct blob_attr * attr, bool v6, int netmask, bool ext, uint32_t broadcast, uint32_t ptp, bool deprecated) static
Definition at line 155 of file proto.c.
{
    struct blob_attr *cur;
    struct device_addr *addr;
    const char *str;
    int n_addr = 0;
    size_t rem;
    blobmsg_for_each_attr(cur, attr, rem) {
        if (blobmsg_type(cur) != BLOBMSG_TYPE_STRING)
            return -1;
        str = blobmsg_data(cur);
        addr = parse_addr(str, v6, netmask, ext, broadcast, ptp, deprecated);
        if (addr == NULL) {
            interface_add_error(iface, "proto", "INVALID_ADDRESS", &str, 1);
            return -1;
        }
        addr->index = n_addr;
        n_addr++;
        vlist_add(&iface->proto_ip.addr, &addr->node, addr);
    }
    return n_addr;
}
References device_addr::addr, interface_ip_settings::addr, blobmsg_data(), blobmsg_for_each_attr, BLOBMSG_TYPE_STRING, device_addr::broadcast, interface_add_error(), parse_addr(), interface::proto_ip, and vlist_add().
Referenced by proto_apply_static_ip_settings().
proto_apply_ip_settings()
int proto_apply_ip_settings (struct interface * iface, struct blob_attr * attr, bool ext)
Definition at line 481 of file proto.c.
{
    struct blob_attr *tb[__OPT_MAX];
    struct blob_attr *cur;
    int n_v4 = 0, n_v6 = 0;
    blobmsg_parse(proto_ip_attributes, __OPT_MAX, tb, blob_data(attr), blob_len(attr));
    if ((cur = tb[OPT_IPADDR]))
        n_v4 = parse_address_list(iface, cur, false, ext);
    if ((cur = tb[OPT_IP6ADDR]))
        n_v6 = parse_address_list(iface, cur, true, ext);
    if ((cur = tb[OPT_IP6PREFIX]))
        if (parse_prefix_list(iface, cur) < 0)
            goto out;
    if (n_v4 < 0 || n_v6 < 0)
        goto out;
    if ((cur = tb[OPT_GATEWAY])) {
        if (n_v4 && !parse_gateway_option(iface, cur, false))
            goto out;
    }
    if ((cur = tb[OPT_IP6GW])) {
        if (n_v6 && !parse_gateway_option(iface, cur, true))
            goto out;
    }
    return 0;
out:
    return -1;
}
References __OPT_MAX, blob_data(), blob_len(), blobmsg_parse(), OPT_GATEWAY, OPT_IP6ADDR, OPT_IP6GW, OPT_IP6PREFIX, OPT_IPADDR, parse_address_list(), parse_gateway_option(), parse_prefix_list(), and proto_ip_attributes.
Referenced by proto_shell_update_link().
proto_apply_static_ip_settings()
int proto_apply_static_ip_settings (struct interface * iface, struct blob_attr * attr)
Definition at line 411 of file proto.c.
{
    struct blob_attr *tb[__OPT_MAX];
    struct blob_attr *cur;
    const char *error;
    unsigned int netmask = 32;
    bool ip6deprecated;
    int n_v4 = 0, n_v6 = 0;
    struct in_addr bcast = {0,}, ptp = {0,};
    blobmsg_parse(proto_ip_attributes, __OPT_MAX, tb, blob_data(attr), blob_len(attr));
    if ((cur = tb[OPT_NETMASK])) {
        netmask = parse_netmask_string(blobmsg_data(cur), false);
        if (netmask > 32) {
            error = "INVALID_NETMASK";
            goto error;
        }
    }
    if ((cur = tb[OPT_BROADCAST])) {
        if (!inet_pton(AF_INET, blobmsg_data(cur), &bcast)) {
            error = "INVALID_BROADCAST";
            goto error;
        }
    }
    if ((cur = tb[OPT_PTPADDR])) {
        if (!inet_pton(AF_INET, blobmsg_data(cur), &ptp)) {
            error = "INVALID_PTPADDR";
            goto error;
        }
    }
    ip6deprecated = blobmsg_get_bool_default(tb[OPT_IP6DEPRECATED], false);
    if ((cur = tb[OPT_IPADDR]))
        n_v4 = parse_static_address_option(iface, cur, false,
            netmask, false, bcast.s_addr, ptp.s_addr, false);
    if ((cur = tb[OPT_IP6ADDR]))
        n_v6 = parse_static_address_option(iface, cur, true,
            128, false, 0, 0, ip6deprecated);
    if ((cur = tb[OPT_IP6PREFIX]))
        if (parse_prefix_list(iface, cur) < 0)
            goto out;
    if (n_v4 < 0 || n_v6 < 0)
        goto out;
    if ((cur = tb[OPT_GATEWAY])) {
        if (n_v4 && !parse_gateway_option(iface, cur, false))
            goto out;
    }
    if ((cur = tb[OPT_IP6GW])) {
        if (n_v6 && !parse_gateway_option(iface, cur, true))
            goto out;
    }
    return 0;
error:
    interface_add_error(iface, "proto", error, NULL, 0);
out:
    return -1;
}
References __OPT_MAX, blob_data(), blob_len(), blobmsg_data(), blobmsg_get_bool_default(), blobmsg_parse(), interface_add_error(), OPT_BROADCAST, OPT_GATEWAY, OPT_IP6ADDR, OPT_IP6DEPRECATED, OPT_IP6GW, OPT_IP6PREFIX, OPT_IPADDR, OPT_NETMASK, OPT_PTPADDR, parse_gateway_option(), parse_netmask_string(), parse_prefix_list(), parse_static_address_option(), and proto_ip_attributes.
Referenced by static_proto_setup().
proto_attach_interface()
void proto_attach_interface (struct interface * iface, const char * proto_name)
Definition at line 636 of file proto.c.
{
    const struct proto_handler *proto = &no_proto;
    const char *error = NULL;
    if (proto_name) {
        proto = get_proto_handler(proto_name);
        if (!proto) {
            error = "INVALID_PROTO";
            proto = &no_proto;
        }
    }
    iface->proto_handler = proto;
    if (error)
        interface_add_error(iface, "proto", error, NULL, 0);
}
References get_proto_handler(), interface_add_error(), no_proto, and interface::proto_handler.
Referenced by interface_alloc().
proto_dump_handlers()
void proto_dump_handlers (struct blob_buf * b)
Definition at line 587 of file proto.c.
{
    struct proto_handler *p;
    void *c;
    avl_for_each_element(&handlers, p, avl) {
        void *v;
        c = blobmsg_open_table(b, p->name);
        if (p->config_params && p->config_params->validate) {
            int i;
            v = blobmsg_open_table(b, "validate");
            for (i = 0; i < p->config_params->n_params; i++)
                blobmsg_add_string(b, p->config_params->params[i].name, uci_get_validate_string(p->config_params, i));
            blobmsg_close_table(b, v);
        }
        blobmsg_add_u8(b, "immediate", !!(p->flags & PROTO_FLAG_IMMEDIATE));
        blobmsg_add_u8(b, "no_device", !!(p->flags & PROTO_FLAG_NODEV));
        blobmsg_add_u8(b, "init_available", !!(p->flags & PROTO_FLAG_INIT_AVAILABLE));
        blobmsg_add_u8(b, "renew_available", !!(p->flags & PROTO_FLAG_RENEW_AVAILABLE));
        blobmsg_add_u8(b, "force_link_default", !!(p->flags & PROTO_FLAG_FORCE_LINK_DEFAULT));
        blobmsg_add_u8(b, "last_error", !!(p->flags & PROTO_FLAG_LASTERROR));
        blobmsg_add_u8(b, "teardown_on_l3_link_down", !!(p->flags & PROTO_FLAG_TEARDOWN_ON_L3_LINK_DOWN));
        blobmsg_add_u8(b, "no_task", !!(p->flags & PROTO_FLAG_NO_TASK));
        blobmsg_close_table(b, c);
    }
}
References proto_handler::avl, avl_for_each_element, b, blobmsg_add_string(), blobmsg_add_u8(), blobmsg_close_table(), blobmsg_open_table(), proto_handler::config_params, proto_handler::flags, handlers, proto_handler::name, PROTO_FLAG_FORCE_LINK_DEFAULT, PROTO_FLAG_IMMEDIATE, PROTO_FLAG_INIT_AVAILABLE, PROTO_FLAG_LASTERROR, PROTO_FLAG_NO_TASK, PROTO_FLAG_NODEV, PROTO_FLAG_RENEW_AVAILABLE, PROTO_FLAG_TEARDOWN_ON_L3_LINK_DOWN, and uci_get_validate_string().
Referenced by netifd_get_proto_handlers().
proto_init_interface()
void proto_init_interface (struct interface * iface, struct blob_attr * attr)
Definition at line 617 of file proto.c.
{
    const struct proto_handler *proto = iface->proto_handler;
    struct interface_proto_state *state = NULL;
    if (!proto)
        proto = &no_proto;
    state = proto->attach(proto, iface, attr);
    if (!state) {
        state = no_proto.attach(&no_proto, iface, attr);
        state->cb = invalid_proto_handler;
    }
    state->handler = proto;
    interface_set_proto_state(iface, state);
}
References proto_handler::attach, interface_proto_state::cb, interface_proto_state::handler, interface_proto_state::iface, interface_set_proto_state(), invalid_proto_handler(), no_proto, interface::proto_handler, and state.
Referenced by interface_do_reload(), and interface_update().
Variable Documentation
handlers
struct avl_tree handlers static
Definition at line 29 of file proto.c.
Referenced by add_proto_handler(), get_proto_handler(), proto_dump_handlers(), wireless_device_run_handler(), and wireless_handler_next().
no_proto
const struct proto_handler no_proto static
Initial value:
= {
    .name = "none",
    .flags = PROTO_FLAG_IMMEDIATE,
    .attach = default_proto_attach,
}
Definition at line 566 of file proto.c.
{
    .name = "none",
    .flags = PROTO_FLAG_IMMEDIATE,
    .attach = default_proto_attach,
};
Referenced by get_proto_handler(), proto_attach_interface(), and proto_init_interface().
proto_ip_addr
const struct blobmsg_policy proto_ip_addr[__ADDR_MAX] static
Initial value:
= {
    [ADDR_IPADDR] = { .name = "ipaddr", .type = BLOBMSG_TYPE_STRING },
    [ADDR_MASK] = { .name = "mask", .type = BLOBMSG_TYPE_STRING },
    [ADDR_BROADCAST] = { .name = "broadcast", .type = BLOBMSG_TYPE_STRING },
    [ADDR_PTP] = { .name = "ptp", .type = BLOBMSG_TYPE_STRING },
    [ADDR_PREFERRED] = { .name = "preferred", .type = BLOBMSG_TYPE_INT32 },
    [ADDR_VALID] = { .name = "valid", .type = BLOBMSG_TYPE_INT32 },
    [ADDR_OFFLINK] = { .name = "offlink", .type = BLOBMSG_TYPE_BOOL },
    [ADDR_CLASS] = { .name = "class", .type = BLOBMSG_TYPE_STRING },
}
Definition at line 92 of file proto.c.
{
    [ADDR_IPADDR] = { .name = "ipaddr", .type = BLOBMSG_TYPE_STRING },
    [ADDR_MASK] = { .name = "mask", .type = BLOBMSG_TYPE_STRING },
    [ADDR_BROADCAST] = { .name = "broadcast", .type = BLOBMSG_TYPE_STRING },
    [ADDR_PTP] = { .name = "ptp", .type = BLOBMSG_TYPE_STRING },
    [ADDR_PREFERRED] = { .name = "preferred", .type = BLOBMSG_TYPE_INT32 },
    [ADDR_VALID] = { .name = "valid", .type = BLOBMSG_TYPE_INT32 },
    [ADDR_OFFLINK] = { .name = "offlink", .type = BLOBMSG_TYPE_BOOL },
    [ADDR_CLASS] = { .name = "class", .type = BLOBMSG_TYPE_STRING },
};
Referenced by parse_address_item().
proto_ip_attr
const struct uci_blob_param_list proto_ip_attr
Initial value:
= {
    .n_params = __OPT_MAX,
    .params = proto_ip_attributes,
    .validate = proto_ip_validate,
    .info = proto_ip_attr_info,
}
Definition at line 73 of file proto.c.
{
    .n_params = __OPT_MAX,
    .params = proto_ip_attributes,
    .validate = proto_ip_validate,
    .info = proto_ip_attr_info,
};
proto_ip_attr_info
const struct uci_blob_param_info proto_ip_attr_info[__OPT_MAX] static
Initial value:
= {
    [OPT_IPADDR] = { .type = BLOBMSG_TYPE_STRING },
    [OPT_IP6ADDR] = { .type = BLOBMSG_TYPE_STRING },
    [OPT_IP6PREFIX] = { .type = BLOBMSG_TYPE_STRING },
}
Definition at line 56 of file proto.c.
{
    [OPT_IPADDR] = { .type = BLOBMSG_TYPE_STRING },
    [OPT_IP6ADDR] = { .type = BLOBMSG_TYPE_STRING },
    [OPT_IP6PREFIX] = { .type = BLOBMSG_TYPE_STRING },
};
proto_ip_attributes
const struct blobmsg_policy proto_ip_attributes[__OPT_MAX] static
Initial value:
= {
    [OPT_IPADDR] = { .name = "ipaddr", .type = BLOBMSG_TYPE_ARRAY },
    [OPT_IP6ADDR] = { .name = "ip6addr", .type = BLOBMSG_TYPE_ARRAY },
    [OPT_NETMASK] = { .name = "netmask", .type = BLOBMSG_TYPE_STRING },
    [OPT_BROADCAST] = { .name = "broadcast", .type = BLOBMSG_TYPE_STRING },
    [OPT_PTPADDR] = { .name = "ptpaddr", .type = BLOBMSG_TYPE_STRING },
    [OPT_GATEWAY] = { .name = "gateway", .type = BLOBMSG_TYPE_STRING },
    [OPT_IP6GW] = { .name = "ip6gw", .type = BLOBMSG_TYPE_STRING },
    [OPT_IP6PREFIX] = { .name = "ip6prefix", .type = BLOBMSG_TYPE_ARRAY },
    [OPT_IP6DEPRECATED] = { .name = "ip6deprecated", .type = BLOBMSG_TYPE_BOOL },
}
Definition at line 44 of file proto.c.
{
    [OPT_IPADDR] = { .name = "ipaddr", .type = BLOBMSG_TYPE_ARRAY },
    [OPT_IP6ADDR] = { .name = "ip6addr", .type = BLOBMSG_TYPE_ARRAY },
    [OPT_NETMASK] = { .name = "netmask", .type = BLOBMSG_TYPE_STRING },
    [OPT_BROADCAST] = { .name = "broadcast", .type = BLOBMSG_TYPE_STRING },
    [OPT_PTPADDR] = { .name = "ptpaddr", .type = BLOBMSG_TYPE_STRING },
    [OPT_GATEWAY] = { .name = "gateway", .type = BLOBMSG_TYPE_STRING },
    [OPT_IP6GW] = { .name = "ip6gw", .type = BLOBMSG_TYPE_STRING },
    [OPT_IP6PREFIX] = { .name = "ip6prefix", .type = BLOBMSG_TYPE_ARRAY },
    [OPT_IP6DEPRECATED] = { .name = "ip6deprecated", .type = BLOBMSG_TYPE_BOOL },
};
Referenced by proto_apply_ip_settings(), and proto_apply_static_ip_settings().
proto_ip_validate
const char* const proto_ip_validate[__OPT_MAX] static
Initial value:
= {
    [OPT_IPADDR] = "ip4addr",
    [OPT_IP6ADDR] = "ip6addr",
    [OPT_NETMASK] = "netmask",
    [OPT_BROADCAST] = "ipaddr",
    [OPT_PTPADDR] = "ip4addr",
    [OPT_GATEWAY] = "ip4addr",
    [OPT_IP6GW] = "ip6addr",
    [OPT_IP6PREFIX] = "ip6addr",
}
Definition at line 62 of file proto.c.
{
    [OPT_IPADDR] = "ip4addr",
    [OPT_IP6ADDR] = "ip6addr",
    [OPT_NETMASK] = "netmask",
    [OPT_BROADCAST] = "ipaddr",
    [OPT_PTPADDR] = "ip4addr",
    [OPT_GATEWAY] = "ip4addr",
    [OPT_IP6GW] = "ip6addr",
    [OPT_IP6PREFIX] = "ip6addr",
};