zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/rcS.c File Reference
rcS.c File Reference
#include <libubox/uloop.h>
#include <libubox/runqueue.h>
#include <inttypes.h>
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <glob.h>
#include <libubox/ustream.h>
#include "procd.h"
#include "rcS.h"
Classes
struct initd
Functions
static void pipe_cb (struct ustream *s, int bytes)
static void q_initd_run (struct runqueue *q, struct runqueue_task *t)
static void q_initd_complete (struct runqueue *q, struct runqueue_task *p)
static void add_initd (struct runqueue *q, char *file, char *param)
static int _rc (struct runqueue *q, char *path, const char *file, char *pattern, char *param)
int rcS (char *pattern, char *param, void(*q_empty)(struct runqueue *))
int rc (const char *file, char *param)
static void r_empty (struct runqueue *q)
static void __attribute__ ((constructor))
Variables
static struct runqueue q r
Class Documentation
initd
struct initd
Definition at line 38 of file rcS.c.
Class Members
struct ustream_fd fd
char * file
char * param
struct runqueue_process proc
struct timespec ts_start
Function Documentation
__attribute__()
static void __attribute__ ((constructor)) static
Definition at line 201 of file rcS.c.
{
    runqueue_init(&r);
    r.empty_cb = r_empty;
    r.max_running_tasks = 8;
}
References runqueue::empty_cb, runqueue::max_running_tasks, r, r_empty(), and runqueue_init().
_rc()
static int _rc (struct runqueue * q, char * path, const char * file, char * pattern, char * param) static
Definition at line 156 of file rcS.c.
{
    char *dir = alloca(2 + strlen(path) + strlen(file) + strlen(pattern));
    glob_t gl;
    int j;
    if (!dir) {
        ERROR("Out of memory in %s.\n", file);
        return -1;
    }
    DEBUG(2, "running %s/%s%s %s\n", path, file, pattern, param);
    sprintf(dir, "%s/%s%s", path, file, pattern);
    if (glob(dir, GLOB_NOESCAPE | GLOB_MARK, NULL, &gl)) {
        DEBUG(2, "glob failed on %s\n", dir);
        return -1;
    }
    for (j = 0; j < gl.gl_pathc; j++)
        add_initd(q, gl.gl_pathv[j], param);
    globfree(&gl);
    return 0;
}
References add_initd(), DEBUG, ERROR, initd::file, initd::param, path, and q.
Referenced by rc(), and rcS().
add_initd()
static void add_initd (struct runqueue * q, char * file, char * param) static
Definition at line 128 of file rcS.c.
{
    static const struct runqueue_task_type initd_type = {
        .run = q_initd_run,
        .cancel = runqueue_process_cancel_cb,
        .kill = runqueue_process_kill_cb,
    };
    struct initd *s;
    char *p, *f;
    s = calloc_a(sizeof(*s), &f, strlen(file) + 1, &p, strlen(param) + 1);
    if (!s) {
        ERROR("Out of memory in %s.\n", file);
        return;
    }
    s->proc.task.type = &initd_type;
    s->proc.task.complete = q_initd_complete;
    if (!strcmp(param, "stop") || !strcmp(param, "shutdown")) {
        s->proc.task.run_timeout = 15000;
        s->proc.task.cancel_timeout = 10000;
    }
    s->param = p;
    s->file = f;
    strcpy(s->param, param);
    strcpy(s->file, file);
    runqueue_task_add(q, &s->proc.task, false);
}
References calloc_a, runqueue_task::cancel_timeout, runqueue_task::complete, ERROR, initd::file, initd::param, initd::proc, q, q_initd_complete(), q_initd_run(), runqueue_task::run_timeout, runqueue_process_cancel_cb(), runqueue_process_kill_cb(), runqueue_task_add(), runqueue_process::task, and runqueue_task::type.
Referenced by _rc().
pipe_cb()
static void pipe_cb (struct ustream * s, int bytes) static
Definition at line 46 of file rcS.c.
{
    struct initd *initd = container_of(s, struct initd, fd.stream);
    char *newline, *str;
    int len;
    do {
        str = ustream_get_read_buf(s, NULL);
        if (!str)
            break;
        newline = strchr(str, '\n');
        if (!newline)
            break;
        *newline = 0;
        len = newline + 1 - str;
        ULOG_NOTE("%s: %s", initd->file, str);
#ifdef SHOW_BOOT_ON_CONSOLE
        fprintf(stderr, "%s: %s\n", initd->file, str);
#endif
        ustream_consume(s, len);
    } while (1);
}
References container_of, initd::fd, initd::file, ustream_fd::stream, ULOG_NOTE, ustream_consume(), and ustream_get_read_buf().
Referenced by q_initd_run().
q_initd_complete()
static void q_initd_complete (struct runqueue * q, struct runqueue_task * p) static
Definition at line 109 of file rcS.c.
{
    struct initd *s = container_of(p, struct initd, proc.task);
    struct timespec ts_stop, ts_res;
    clock_gettime(CLOCK_MONOTONIC_RAW, &ts_stop);
    ts_res.tv_sec = ts_stop.tv_sec - s->ts_start.tv_sec;
    ts_res.tv_nsec = ts_stop.tv_nsec - s->ts_start.tv_nsec;
    if (ts_res.tv_nsec < 0) {
        --ts_res.tv_sec;
        ts_res.tv_nsec += 1000000000;
    }
    DEBUG(2, "stop %s %s - took %" PRId64 ".%09" PRId64 "s\n", s->file, s->param, (int64_t)ts_res.tv_sec, (int64_t)ts_res.tv_nsec);
    ustream_free(&s->fd.stream);
    close(s->fd.fd.fd);
    free(s);
}
References container_of, DEBUG, initd::fd, uloop_fd::fd, ustream_fd::fd, initd::file, initd::param, initd::proc, ustream_fd::stream, runqueue_process::task, initd::ts_start, and ustream_free().
Referenced by add_initd().
q_initd_run()
static void q_initd_run (struct runqueue * q, struct runqueue_task * t) static
Definition at line 69 of file rcS.c.
{
    struct initd *s = container_of(t, struct initd, proc.task);
    int pipefd[2];
    pid_t pid;
    clock_gettime(CLOCK_MONOTONIC_RAW, &s->ts_start);
    DEBUG(2, "start %s %s \n", s->file, s->param);
    if (pipe(pipefd) == -1) {
        ERROR("Failed to create pipe: %m\n");
        return;
    }
    pid = fork();
    if (pid < 0)
        return;
    if (pid) {
        close(pipefd[1]);
        fcntl(pipefd[0], F_SETFD, FD_CLOEXEC);
        s->fd.stream.string_data = true,
        s->fd.stream.notify_read = pipe_cb,
        runqueue_process_add(q, &s->proc, pid);
        ustream_fd_init(&s->fd, pipefd[0]);
        return;
    }
    close(pipefd[0]);
    int devnull = open("/dev/null", O_RDONLY);
    dup2(devnull, STDIN_FILENO);
    dup2(pipefd[1], STDOUT_FILENO);
    dup2(pipefd[1], STDERR_FILENO);
    if (devnull > STDERR_FILENO)
        close(devnull);
    execlp(s->file, s->file, s->param, NULL);
    exit(1);
}
References container_of, DEBUG, ERROR, initd::fd, initd::file, ustream::notify_read, initd::param, pipe_cb(), initd::proc, q, runqueue_process_add(), ustream_fd::stream, ustream::string_data, runqueue_process::task, initd::ts_start, and ustream_fd_init().
Referenced by add_initd().
r_empty()
static void r_empty (struct runqueue * q) static
Definition at line 196 of file rcS.c.
{
}
Referenced by __attribute__().
rc()
int rc (const char * file, char * param)
Definition at line 191 of file rcS.c.
{
    return _rc(&r, "/etc/init.d", file, "", param);
}
References _rc(), initd::file, initd::param, and r.
Referenced by inotify_read_handler(), inotify_read_handler(), service_update(), test_count_data_cb(), ubus_invoke_fd(), ubusd_handle_lookup(), and vlandev_qos_mapping_list_apply().
rcS()
int rcS (char * pattern, char * param, void(* q_empty)(struct runqueue *))
Definition at line 182 of file rcS.c.
{
    runqueue_init(&q);
    q.empty_cb = q_empty;
    q.max_running_tasks = 1;
    return _rc(&q, "/etc/rc.d", pattern, "*", param);
}
References _rc(), runqueue::empty_cb, runqueue::max_running_tasks, initd::param, q, q_empty(), and runqueue_init().
Referenced by runrc().
Variable Documentation
r
struct runqueue q r static
Definition at line 36 of file rcS.c.
Referenced by __attribute__(), __attribute__(), __randname(), bridge_hotplug_set_member_vlans(), check_route(), cmdline(), device_fill_vlan_range(), dump_result(), get_active_console(), get_cmdline_val_offset(), get_next_msg(), instance_config_parse(), instance_dump(), interface_handle_subnet_route(), interface_ip_dump_neighbor_list(), interface_ip_dump_route_list(), is_container(), MSTP_IN_set_cist_bridge_config(), rc(), report_seccomp_vialation(), rpc_iwinfo_add_rateinfo(), rpc_ucode_request_finish(), service_validate_dump_all(), set_if_up(), test_b64_decode(), test_b64_encode(), test_basics(), test_blobmsg(), test_blobmsg_procd_instance(), and vjson_parse().