zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/netifd/veth.c File Reference
veth.c File Reference
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <assert.h>
#include <errno.h>
#include "netifd.h"
#include "device.h"
#include "interface.h"
#include "system.h"
Classes
struct veth
Enumerations
enum { VETH_ATTR_MACADDR , VETH_ATTR_PEER_NAME , VETH_ATTR_PEER_MACADDR , __VETH_ATTR_MAX }
Functions
static int veth_set_down (struct veth *veth)
static int veth_set_up (struct veth *veth)
static int veth_set_state (struct device *dev, bool up)
static void veth_free (struct device *dev)
static void veth_dump_info (struct device *dev, struct blob_buf *b)
static void veth_config_init (struct device *dev)
static void veth_apply_settings (struct veth *veth, struct blob_attr **tb)
static enum dev_change_type veth_reload (struct device *dev, struct blob_attr *attr)
static struct device * veth_create (const char *name, struct device_type *devtype, struct blob_attr *attr)
static void __init veth_device_type_init (void)
Variables
static const struct blobmsg_policy veth_attrs [__VETH_ATTR_MAX]
static const struct uci_blob_param_list veth_attr_list
static struct device_type veth_device_type
Class Documentation
veth
struct veth
Definition at line 48 of file veth.c.
Class Members
struct veth_config config
struct blob_attr * config_data
struct device dev
device_state_cb set_state
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
VETH_ATTR_MACADDR
VETH_ATTR_PEER_NAME
VETH_ATTR_PEER_MACADDR
__VETH_ATTR_MAX
Definition at line 27 of file veth.c.
     {
    VETH_ATTR_MACADDR,
    VETH_ATTR_PEER_NAME,
    VETH_ATTR_PEER_MACADDR,
    __VETH_ATTR_MAX
};
Function Documentation
veth_apply_settings()
static void veth_apply_settings (struct veth * veth, struct blob_attr ** tb) static
Definition at line 128 of file veth.c.
{
    struct veth_config *cfg = &veth->config;
    struct blob_attr *cur;
    struct ether_addr *ea;
    cfg->flags = 0;
    if ((cur = tb[VETH_ATTR_MACADDR]))
    {
        ea = ether_aton(blobmsg_data(cur));
        if (ea) {
            memcpy(cfg->macaddr, ea, 6);
            cfg->flags |= VETH_OPT_MACADDR;
        }
    }
    if ((cur = tb[VETH_ATTR_PEER_NAME]))
    {
        strncpy(cfg->peer_name, blobmsg_get_string(cur), sizeof(cfg->peer_name)-1);
        cfg->flags |= VETH_OPT_PEER_NAME;
    }
    if ((cur = tb[VETH_ATTR_PEER_MACADDR]))
    {
        ea = ether_aton(blobmsg_data(cur));
        if (ea) {
            memcpy(cfg->peer_macaddr, ea, 6);
            cfg->flags |= VETH_OPT_PEER_MACADDR;
        }
    }
}
References blobmsg_data(), blobmsg_get_string(), veth::config, veth_config::flags, veth_config::macaddr, veth_config::peer_macaddr, veth_config::peer_name, VETH_ATTR_MACADDR, VETH_ATTR_PEER_MACADDR, VETH_ATTR_PEER_NAME, VETH_OPT_MACADDR, VETH_OPT_PEER_MACADDR, and VETH_OPT_PEER_NAME.
Referenced by veth_reload().
veth_config_init()
static void veth_config_init (struct device * dev) static
Definition at line 122 of file veth.c.
{
    device_set_present(dev, true);
}
References veth::dev, and device_set_present.
Referenced by veth_reload().
veth_create()
static struct device * veth_create (const char * name, struct device_type * devtype, struct blob_attr * attr) static
Definition at line 205 of file veth.c.
{
    struct veth *veth;
    struct device *dev = NULL;
    veth = calloc(1, sizeof(*veth));
    if (!veth)
        return NULL;
    dev = &veth->dev;
    if (device_init(dev, devtype, name) < 0) {
        device_cleanup(dev);
        free(veth);
        return NULL;
    }
    dev->config_pending = true;
    veth->set_state = dev->set_state;
    dev->set_state = veth_set_state;
    dev->hotplug_ops = NULL;
    veth_reload(dev, attr);
    return dev;
}
References device::config_pending, veth::dev, device_cleanup(), device_init(), device::hotplug_ops, device::set_state, veth::set_state, veth_reload(), and veth_set_state().
veth_device_type_init()
static void __init veth_device_type_init (void) static
Definition at line 244 of file veth.c.
{
    device_type_add(&veth_device_type);
}
References device_type_add(), and veth_device_type.
veth_dump_info()
static void veth_dump_info (struct device * dev, struct blob_buf * b) static
Definition at line 111 of file veth.c.
{
    struct veth *veth;
    veth = container_of(dev, struct veth, dev);
    if (veth->config.flags & VETH_OPT_PEER_NAME)
        blobmsg_add_string(b, "peer", veth->config.peer_name);
    system_if_dump_info(dev, b);
}
References b, blobmsg_add_string(), veth::config, container_of, veth::dev, veth_config::flags, veth_config::peer_name, system_if_dump_info(), and VETH_OPT_PEER_NAME.
veth_free()
static void veth_free (struct device * dev) static
Definition at line 101 of file veth.c.
{
    struct veth *veth;
    veth = container_of(dev, struct veth, dev);
    free(veth->config_data);
    free(veth);
}
References veth::config_data, container_of, and veth::dev.
veth_reload()
static enum dev_change_type veth_reload (struct device * dev, struct blob_attr * attr) static
Definition at line 162 of file veth.c.
{
    struct blob_attr *tb_dev[__DEV_ATTR_MAX];
    struct blob_attr *tb_mv[__VETH_ATTR_MAX];
    enum dev_change_type ret = DEV_CONFIG_APPLIED;
    struct veth *veth;
    veth = container_of(dev, struct veth, dev);
    attr = blob_memdup(attr);
    blobmsg_parse(device_attr_list.params, __DEV_ATTR_MAX, tb_dev,
        blob_data(attr), blob_len(attr));
    blobmsg_parse(veth_attrs, __VETH_ATTR_MAX, tb_mv,
        blob_data(attr), blob_len(attr));
    device_init_settings(dev, tb_dev);
    veth_apply_settings(veth, tb_mv);
    if (veth->config_data) {
        struct blob_attr *otb_dev[__DEV_ATTR_MAX];
        struct blob_attr *otb_mv[__VETH_ATTR_MAX];
        blobmsg_parse(device_attr_list.params, __DEV_ATTR_MAX, otb_dev,
            blob_data(veth->config_data), blob_len(veth->config_data));
        if (uci_blob_diff(tb_dev, otb_dev, &device_attr_list, NULL))
            ret = DEV_CONFIG_RESTART;
        blobmsg_parse(veth_attrs, __VETH_ATTR_MAX, otb_mv,
            blob_data(veth->config_data), blob_len(veth->config_data));
        if (uci_blob_diff(tb_mv, otb_mv, &veth_attr_list, NULL))
            ret = DEV_CONFIG_RESTART;
        veth_config_init(dev);
    }
    free(veth->config_data);
    veth->config_data = attr;
    return ret;
}
References __DEV_ATTR_MAX, __VETH_ATTR_MAX, blob_data(), blob_len(), blob_memdup(), blobmsg_parse(), veth::config_data, container_of, veth::dev, DEV_CONFIG_APPLIED, DEV_CONFIG_RESTART, device_attr_list, device_init_settings(), veth_apply_settings(), veth_attr_list, veth_attrs, and veth_config_init().
Referenced by veth_create().
veth_set_down()
static int veth_set_down (struct veth * veth) static
Definition at line 58 of file veth.c.
{
    veth->set_state(&veth->dev, false);
    system_veth_del(&veth->dev);
    return 0;
}
References veth::dev, veth::set_state, and system_veth_del().
Referenced by veth_set_state().
veth_set_state()
static int veth_set_state (struct device * dev, bool up) static
Definition at line 87 of file veth.c.
{
    struct veth *veth;
    D(SYSTEM, "veth_set_state(%s, %u)", dev->ifname, up);
    veth = container_of(dev, struct veth, dev);
    if (up)
        return veth_set_up(veth);
    else
        return veth_set_down(veth);
}
References container_of, D, veth::dev, device::ifname, veth_set_down(), and veth_set_up().
Referenced by veth_create().
veth_set_up()
static int veth_set_up (struct veth * veth) static
Definition at line 67 of file veth.c.
{
    int ret;
    ret = system_veth_add(&veth->dev, &veth->config);
    if (ret < 0)
        return ret;
    ret = veth->set_state(&veth->dev, true);
    if (ret)
        goto delete;
    return 0;
delete:
    system_veth_del(&veth->dev);
    return ret;
}
References veth::config, veth::dev, veth::set_state, system_veth_add(), and system_veth_del().
Referenced by veth_set_state().
Variable Documentation
veth_attr_list
const struct uci_blob_param_list veth_attr_list static
Initial value:
= {
    .n_params = __VETH_ATTR_MAX,
    .params = veth_attrs,
    .n_next = 1,
    .next = { &device_attr_list },
}
Definition at line 40 of file veth.c.
{
    .n_params = __VETH_ATTR_MAX,
    .params = veth_attrs,
    .n_next = 1,
    .next = { &device_attr_list },
};
Referenced by veth_reload().
veth_attrs
const struct blobmsg_policy veth_attrs[__VETH_ATTR_MAX] static
Initial value:
= {
    [VETH_ATTR_MACADDR] = { "macaddr", BLOBMSG_TYPE_STRING },
    [VETH_ATTR_PEER_NAME]  = { "peer_name", BLOBMSG_TYPE_STRING },
    [VETH_ATTR_PEER_MACADDR] = { "peer_macaddr", BLOBMSG_TYPE_STRING },
}
Definition at line 34 of file veth.c.
{
    [VETH_ATTR_MACADDR] = { "macaddr", BLOBMSG_TYPE_STRING },
    [VETH_ATTR_PEER_NAME]  = { "peer_name", BLOBMSG_TYPE_STRING },
    [VETH_ATTR_PEER_MACADDR] = { "peer_macaddr", BLOBMSG_TYPE_STRING },
};
Referenced by veth_reload().
veth_device_type
struct device_type veth_device_type static
Initial value:
= {
    .name = "veth",
    .config_params = &veth_attr_list,
    .create = veth_create,
    .config_init = veth_config_init,
    .reload = veth_reload,
    .free = veth_free,
    .dump_info = veth_dump_info,
}
Definition at line 234 of file veth.c.
{
    .name = "veth",
    .config_params = &veth_attr_list,
    .create = veth_create,
    .config_init = veth_config_init,
    .reload = veth_reload,
    .free = veth_free,
    .dump_info = veth_dump_info,
};
Referenced by veth_device_type_init().