zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/netifd/system.c File Reference
system.c File Reference
#include "netifd.h"
#include "system.h"
#include <fcntl.h>
Functions
void system_fd_set_cloexec (int fd)
Variables
static const struct blobmsg_policy tunnel_attrs [__TUNNEL_ATTR_MAX]
const struct uci_blob_param_list tunnel_attr_list
static const struct blobmsg_policy vxlan_data_attrs [__VXLAN_DATA_ATTR_MAX]
const struct uci_blob_param_list vxlan_data_attr_list
static const struct blobmsg_policy gre_data_attrs [__GRE_DATA_ATTR_MAX]
const struct uci_blob_param_list gre_data_attr_list
static const struct blobmsg_policy vti_data_attrs [__VTI_DATA_ATTR_MAX]
const struct uci_blob_param_list vti_data_attr_list
static const struct blobmsg_policy xfrm_data_attrs [__XFRM_DATA_ATTR_MAX]
const struct uci_blob_param_list xfrm_data_attr_list
static const struct blobmsg_policy sixrd_data_attrs [__SIXRD_DATA_ATTR_MAX]
const struct uci_blob_param_list sixrd_data_attr_list
static const struct blobmsg_policy ipip6_data_attrs [__SIXRD_DATA_ATTR_MAX]
const struct uci_blob_param_list ipip6_data_attr_list
static const struct blobmsg_policy fmr_data_attrs [__FMR_DATA_ATTR_MAX]
const struct uci_blob_param_list fmr_data_attr_list
const char *const bonding_policy_str [__BONDING_MODE_MAX]
Function Documentation
system_fd_set_cloexec()
void system_fd_set_cloexec (int fd)
Definition at line 134 of file system.c.
{
#ifdef FD_CLOEXEC
    fcntl(fd, F_SETFD, fcntl(fd, F_GETFD) | FD_CLOEXEC);
#endif
}
Referenced by netifd_dir_push(), netifd_open_subdir(), netifd_start_process(), netifd_ubus_add_fd(), and system_init().
Variable Documentation
bonding_policy_str
const char* const bonding_policy_str[__BONDING_MODE_MAX]
Initial value:
= {
    [BONDING_MODE_BALANCE_RR] = "balance-rr",
    [BONDING_MODE_ACTIVE_BACKUP] = "active-backup",
    [BONDING_MODE_BALANCE_XOR] = "balance-xor",
    [BONDING_MODE_BROADCAST] = "broadcast",
    [BONDING_MODE_8023AD] = "802.3ad",
    [BONDING_MODE_BALANCE_TLB] = "balance-tlb",
    [BONDING_MODE_BALANCE_ALB] = "balance-alb",
}
Definition at line 124 of file system.c.
{
    [BONDING_MODE_BALANCE_RR] = "balance-rr",
    [BONDING_MODE_ACTIVE_BACKUP] = "active-backup",
    [BONDING_MODE_BALANCE_XOR] = "balance-xor",
    [BONDING_MODE_BROADCAST] = "broadcast",
    [BONDING_MODE_8023AD] = "802.3ad",
    [BONDING_MODE_BALANCE_TLB] = "balance-tlb",
    [BONDING_MODE_BALANCE_ALB] = "balance-alb",
};
Referenced by bonding_apply_settings(), and system_bonding_set_device().
fmr_data_attr_list
const struct uci_blob_param_list fmr_data_attr_list
Initial value:
= {
    .n_params = __FMR_DATA_ATTR_MAX,
    .params = fmr_data_attrs,
}
Definition at line 119 of file system.c.
{
    .n_params = __FMR_DATA_ATTR_MAX,
    .params = fmr_data_attrs,
};
Referenced by system_add_ip6_tunnel().
fmr_data_attrs
const struct blobmsg_policy fmr_data_attrs[__FMR_DATA_ATTR_MAX] static
Initial value:
= {
    [FMR_DATA_PREFIX6] = { .name = "prefix6", .type = BLOBMSG_TYPE_STRING },
    [FMR_DATA_PREFIX4] = { .name = "prefix4", .type = BLOBMSG_TYPE_STRING },
    [FMR_DATA_EALEN] = { .name = "ealen", .type = BLOBMSG_TYPE_INT32 },
    [FMR_DATA_OFFSET] = { .name = "offset", .type = BLOBMSG_TYPE_INT32 },
}
Definition at line 112 of file system.c.
{
    [FMR_DATA_PREFIX6] = { .name = "prefix6", .type = BLOBMSG_TYPE_STRING },
    [FMR_DATA_PREFIX4] = { .name = "prefix4", .type = BLOBMSG_TYPE_STRING },
    [FMR_DATA_EALEN] = { .name = "ealen", .type = BLOBMSG_TYPE_INT32 },
    [FMR_DATA_OFFSET] = { .name = "offset", .type = BLOBMSG_TYPE_INT32 },
};
gre_data_attr_list
const struct uci_blob_param_list gre_data_attr_list
Initial value:
= {
    .n_params = __GRE_DATA_ATTR_MAX,
    .params = gre_data_attrs,
}
Definition at line 68 of file system.c.
{
    .n_params = __GRE_DATA_ATTR_MAX,
    .params = gre_data_attrs,
};
Referenced by system_add_gre_tunnel().
gre_data_attrs
const struct blobmsg_policy gre_data_attrs[__GRE_DATA_ATTR_MAX] static
Initial value:
= {
    [GRE_DATA_IKEY] = { .name = "ikey", .type = BLOBMSG_TYPE_INT32 },
    [GRE_DATA_OKEY] = { .name = "okey", .type = BLOBMSG_TYPE_INT32 },
    [GRE_DATA_ICSUM] = { .name = "icsum", .type = BLOBMSG_TYPE_BOOL },
    [GRE_DATA_OCSUM] = { .name = "ocsum", .type = BLOBMSG_TYPE_BOOL },
    [GRE_DATA_ISEQNO] = { .name = "iseqno", .type = BLOBMSG_TYPE_BOOL },
    [GRE_DATA_OSEQNO] = { .name = "oseqno", .type = BLOBMSG_TYPE_BOOL },
    [GRE_DATA_ENCAPLIMIT] = { .name = "encaplimit", .type = BLOBMSG_TYPE_STRING },
}
Definition at line 58 of file system.c.
{
    [GRE_DATA_IKEY] = { .name = "ikey", .type = BLOBMSG_TYPE_INT32 },
    [GRE_DATA_OKEY] = { .name = "okey", .type = BLOBMSG_TYPE_INT32 },
    [GRE_DATA_ICSUM] = { .name = "icsum", .type = BLOBMSG_TYPE_BOOL },
    [GRE_DATA_OCSUM] = { .name = "ocsum", .type = BLOBMSG_TYPE_BOOL },
    [GRE_DATA_ISEQNO] = { .name = "iseqno", .type = BLOBMSG_TYPE_BOOL },
    [GRE_DATA_OSEQNO] = { .name = "oseqno", .type = BLOBMSG_TYPE_BOOL },
    [GRE_DATA_ENCAPLIMIT] = { .name = "encaplimit", .type = BLOBMSG_TYPE_STRING },
};
ipip6_data_attr_list
const struct uci_blob_param_list ipip6_data_attr_list
Initial value:
= {
    .n_params = __IPIP6_DATA_ATTR_MAX,
    .params = ipip6_data_attrs,
}
Definition at line 107 of file system.c.
{
    .n_params = __IPIP6_DATA_ATTR_MAX,
    .params = ipip6_data_attrs,
};
Referenced by system_add_ip6_tunnel().
ipip6_data_attrs
const struct blobmsg_policy ipip6_data_attrs[__SIXRD_DATA_ATTR_MAX] static
Initial value:
= {
    [IPIP6_DATA_ENCAPLIMIT] = { .name = "encaplimit", .type = BLOBMSG_TYPE_STRING },
    [IPIP6_DATA_FMRS] = { .name = "fmrs", .type = BLOBMSG_TYPE_ARRAY },
}
Definition at line 102 of file system.c.
{
    [IPIP6_DATA_ENCAPLIMIT] = { .name = "encaplimit", .type = BLOBMSG_TYPE_STRING },
    [IPIP6_DATA_FMRS] = { .name = "fmrs", .type = BLOBMSG_TYPE_ARRAY },
};
sixrd_data_attr_list
const struct uci_blob_param_list sixrd_data_attr_list
Initial value:
= {
    .n_params = __SIXRD_DATA_ATTR_MAX,
    .params = sixrd_data_attrs,
}
Definition at line 97 of file system.c.
{
    .n_params = __SIXRD_DATA_ATTR_MAX,
    .params = sixrd_data_attrs,
};
Referenced by system_add_sit_tunnel().
sixrd_data_attrs
const struct blobmsg_policy sixrd_data_attrs[__SIXRD_DATA_ATTR_MAX] static
Initial value:
= {
    [SIXRD_DATA_PREFIX] = { .name = "prefix", .type = BLOBMSG_TYPE_STRING },
    [SIXRD_DATA_RELAY_PREFIX] = { .name = "relay-prefix", .type = BLOBMSG_TYPE_STRING },
}
Definition at line 92 of file system.c.
{
    [SIXRD_DATA_PREFIX] = { .name = "prefix", .type = BLOBMSG_TYPE_STRING },
    [SIXRD_DATA_RELAY_PREFIX] = { .name = "relay-prefix", .type = BLOBMSG_TYPE_STRING },
};
tunnel_attr_list
const struct uci_blob_param_list tunnel_attr_list
Initial value:
= {
    .n_params = __TUNNEL_ATTR_MAX,
    .params = tunnel_attrs,
}
Definition at line 30 of file system.c.
{
    .n_params = __TUNNEL_ATTR_MAX,
    .params = tunnel_attrs,
};
Referenced by system_add_ip_tunnel().
tunnel_attrs
const struct blobmsg_policy tunnel_attrs[__TUNNEL_ATTR_MAX] static
Initial value:
= {
    [TUNNEL_ATTR_TYPE] = { .name = "mode", .type = BLOBMSG_TYPE_STRING },
    [TUNNEL_ATTR_LOCAL] = { .name = "local", .type = BLOBMSG_TYPE_STRING },
    [TUNNEL_ATTR_REMOTE] = { .name = "remote", .type = BLOBMSG_TYPE_STRING },
    [TUNNEL_ATTR_MTU] = { .name = "mtu", .type = BLOBMSG_TYPE_INT32 },
    [TUNNEL_ATTR_DF] = { .name = "df", .type = BLOBMSG_TYPE_BOOL },
    [TUNNEL_ATTR_TTL] = { .name = "ttl", .type = BLOBMSG_TYPE_INT32 },
    [TUNNEL_ATTR_TOS] = { .name = "tos", .type = BLOBMSG_TYPE_STRING },
    [TUNNEL_ATTR_LINK] = { .name = "link", .type = BLOBMSG_TYPE_STRING },
    [TUNNEL_ATTR_DATA] = { .name = "data", .type = BLOBMSG_TYPE_TABLE },
}
Definition at line 18 of file system.c.
{
    [TUNNEL_ATTR_TYPE] = { .name = "mode", .type = BLOBMSG_TYPE_STRING },
    [TUNNEL_ATTR_LOCAL] = { .name = "local", .type = BLOBMSG_TYPE_STRING },
    [TUNNEL_ATTR_REMOTE] = { .name = "remote", .type = BLOBMSG_TYPE_STRING },
    [TUNNEL_ATTR_MTU] = { .name = "mtu", .type = BLOBMSG_TYPE_INT32 },
    [TUNNEL_ATTR_DF] = { .name = "df", .type = BLOBMSG_TYPE_BOOL },
    [TUNNEL_ATTR_TTL] = { .name = "ttl", .type = BLOBMSG_TYPE_INT32 },
    [TUNNEL_ATTR_TOS] = { .name = "tos", .type = BLOBMSG_TYPE_STRING },
    [TUNNEL_ATTR_LINK] = { .name = "link", .type = BLOBMSG_TYPE_STRING },
    [TUNNEL_ATTR_DATA] = { .name = "data", .type = BLOBMSG_TYPE_TABLE },
};
vti_data_attr_list
const struct uci_blob_param_list vti_data_attr_list
Initial value:
= {
    .n_params = __VTI_DATA_ATTR_MAX,
    .params = vti_data_attrs,
}
Definition at line 78 of file system.c.
{
    .n_params = __VTI_DATA_ATTR_MAX,
    .params = vti_data_attrs,
};
Referenced by system_add_vti_tunnel().
vti_data_attrs
const struct blobmsg_policy vti_data_attrs[__VTI_DATA_ATTR_MAX] static
Initial value:
= {
    [VTI_DATA_IKEY] = { .name = "ikey", .type = BLOBMSG_TYPE_INT32 },
    [VTI_DATA_OKEY] = { .name = "okey", .type = BLOBMSG_TYPE_INT32 },
}
Definition at line 73 of file system.c.
{
    [VTI_DATA_IKEY] = { .name = "ikey", .type = BLOBMSG_TYPE_INT32 },
    [VTI_DATA_OKEY] = { .name = "okey", .type = BLOBMSG_TYPE_INT32 },
};
vxlan_data_attr_list
const struct uci_blob_param_list vxlan_data_attr_list
Initial value:
= {
    .n_params = __VXLAN_DATA_ATTR_MAX,
    .params = vxlan_data_attrs,
}
Definition at line 53 of file system.c.
{
    .n_params = __VXLAN_DATA_ATTR_MAX,
    .params = vxlan_data_attrs,
};
Referenced by system_add_vxlan().
vxlan_data_attrs
const struct blobmsg_policy vxlan_data_attrs[__VXLAN_DATA_ATTR_MAX] static
Initial value:
= {
    [VXLAN_DATA_ATTR_ID] = { .name = "id", .type = BLOBMSG_TYPE_INT32 },
    [VXLAN_DATA_ATTR_PORT] = { .name = "port", .type = BLOBMSG_TYPE_INT32 },
    [VXLAN_DATA_ATTR_MACADDR] = { .name = "macaddr", .type = BLOBMSG_TYPE_STRING },
    [VXLAN_DATA_ATTR_RXCSUM] = { .name = "rxcsum", .type = BLOBMSG_TYPE_BOOL },
    [VXLAN_DATA_ATTR_TXCSUM] = { .name = "txcsum", .type = BLOBMSG_TYPE_BOOL },
    [VXLAN_DATA_ATTR_SRCPORTMIN] = { .name = "srcportmin", .type = BLOBMSG_TYPE_INT32 },
    [VXLAN_DATA_ATTR_SRCPORTMAX] = { .name = "srcportmax", .type = BLOBMSG_TYPE_INT32 },
    [VXLAN_DATA_ATTR_LEARNING] = { .name = "learning", .type = BLOBMSG_TYPE_BOOL },
    [VXLAN_DATA_ATTR_RSC] = { .name = "rsc", .type = BLOBMSG_TYPE_BOOL },
    [VXLAN_DATA_ATTR_PROXY] = { .name = "proxy", .type = BLOBMSG_TYPE_BOOL },
    [VXLAN_DATA_ATTR_L2MISS] = { .name = "l2miss", .type = BLOBMSG_TYPE_BOOL },
    [VXLAN_DATA_ATTR_L3MISS] = { .name = "l3miss", .type = BLOBMSG_TYPE_BOOL },
    [VXLAN_DATA_ATTR_GBP] = { .name = "gbp", .type = BLOBMSG_TYPE_BOOL },
    [VXLAN_DATA_ATTR_AGEING] = { .name = "ageing", .type = BLOBMSG_TYPE_INT32 },
    [VXLAN_DATA_ATTR_LIMIT] = { .name = "maxaddress", .type = BLOBMSG_TYPE_INT32 },
}
Definition at line 35 of file system.c.
{
    [VXLAN_DATA_ATTR_ID] = { .name = "id", .type = BLOBMSG_TYPE_INT32 },
    [VXLAN_DATA_ATTR_PORT] = { .name = "port", .type = BLOBMSG_TYPE_INT32 },
    [VXLAN_DATA_ATTR_MACADDR] = { .name = "macaddr", .type = BLOBMSG_TYPE_STRING },
    [VXLAN_DATA_ATTR_RXCSUM] = { .name = "rxcsum", .type = BLOBMSG_TYPE_BOOL },
    [VXLAN_DATA_ATTR_TXCSUM] = { .name = "txcsum", .type = BLOBMSG_TYPE_BOOL },
    [VXLAN_DATA_ATTR_SRCPORTMIN] = { .name = "srcportmin", .type = BLOBMSG_TYPE_INT32 },
    [VXLAN_DATA_ATTR_SRCPORTMAX] = { .name = "srcportmax", .type = BLOBMSG_TYPE_INT32 },
    [VXLAN_DATA_ATTR_LEARNING] = { .name = "learning", .type = BLOBMSG_TYPE_BOOL },
    [VXLAN_DATA_ATTR_RSC] = { .name = "rsc", .type = BLOBMSG_TYPE_BOOL },
    [VXLAN_DATA_ATTR_PROXY] = { .name = "proxy", .type = BLOBMSG_TYPE_BOOL },
    [VXLAN_DATA_ATTR_L2MISS] = { .name = "l2miss", .type = BLOBMSG_TYPE_BOOL },
    [VXLAN_DATA_ATTR_L3MISS] = { .name = "l3miss", .type = BLOBMSG_TYPE_BOOL },
    [VXLAN_DATA_ATTR_GBP] = { .name = "gbp", .type = BLOBMSG_TYPE_BOOL },
    [VXLAN_DATA_ATTR_AGEING] = { .name = "ageing", .type = BLOBMSG_TYPE_INT32 },
    [VXLAN_DATA_ATTR_LIMIT] = { .name = "maxaddress", .type = BLOBMSG_TYPE_INT32 },
};
xfrm_data_attr_list
const struct uci_blob_param_list xfrm_data_attr_list
Initial value:
= {
    .n_params = __XFRM_DATA_ATTR_MAX,
    .params = xfrm_data_attrs,
}
Definition at line 87 of file system.c.
{
    .n_params = __XFRM_DATA_ATTR_MAX,
    .params = xfrm_data_attrs,
};
Referenced by system_add_xfrm_tunnel().
xfrm_data_attrs
const struct blobmsg_policy xfrm_data_attrs[__XFRM_DATA_ATTR_MAX] static
Initial value:
= {
    [XFRM_DATA_IF_ID] = { .name = "ifid", .type = BLOBMSG_TYPE_INT32 },
}
Definition at line 83 of file system.c.
{
    [XFRM_DATA_IF_ID] = { .name = "ifid", .type = BLOBMSG_TYPE_INT32 },
};