zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/rpcd/include/rpcd/plugin.h File Reference
plugin.h File Reference
#include <dlfcn.h>
#include <stdio.h>
#include <fcntl.h>
#include <unistd.h>
#include <limits.h>
#include <dirent.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <sys/types.h>
#include <libubox/blobmsg_json.h>
#include <libubus.h>
#include <json-c/json.h>
#include <rpcd/exec.h>
#include <rpcd/session.h>
Classes
struct rpc_daemon_ops
struct rpc_plugin
Macros
#define _GNU_SOURCE /* asprintf() */
#define RPC_PLUGIN_DIRECTORY INSTALL_PREFIX "/libexec/rpcd"
#define RPC_LIBRARY_DIRECTORY INSTALL_PREFIX "/lib/rpcd"
Functions
int rpc_plugin_api_init (struct ubus_context *ctx)
Class Documentation
rpc_daemon_ops
struct rpc_daemon_ops
Definition at line 47 of file plugin.h.
Class Members
int(*)(const char **args, rpc_exec_write_cb_t in, rpc_exec_read_cb_t out, rpc_exec_read_cb_t err, rpc_exec_done_cb_t end, void *priv, struct ubus_context *ctx, struct ubus_request_data *req) exec
int * exec_timeout
bool(*)(const char *sid, const char *scope, const char *object, const char *function) session_access
void(*)(struct rpc_session_cb *cb) session_create_cb
void(*)(struct rpc_session_cb *cb) session_destroy_cb
rpc_plugin
struct rpc_plugin
Definition at line 60 of file plugin.h.
Class Members
int(*)(const struct rpc_daemon_ops *ops, struct ubus_context *ctx) init
struct list_head list
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE /* asprintf() */
Definition at line 22 of file plugin.h.
RPC_LIBRARY_DIRECTORY
#define RPC_LIBRARY_DIRECTORY INSTALL_PREFIX "/lib/rpcd"
Definition at line 45 of file plugin.h.
Referenced by rpc_plugin_api_init(), and rpc_ucode_api_init().
RPC_PLUGIN_DIRECTORY
#define RPC_PLUGIN_DIRECTORY INSTALL_PREFIX "/libexec/rpcd"
Definition at line 42 of file plugin.h.
Referenced by rpc_plugin_api_init(), and rpc_plugin_call().
Function Documentation
rpc_plugin_api_init()
int rpc_plugin_api_init (struct ubus_context * ctx)
Definition at line 509 of file plugin.c.
{
    DIR *d;
    int rv = 0;
    struct stat s;
    struct dirent *e;
    char path[PATH_MAX];
    if ((d = opendir(RPC_PLUGIN_DIRECTORY)) != NULL)
    {
        while ((e = readdir(d)) != NULL)
        {
            snprintf(path, sizeof(path) - 1,
                     RPC_PLUGIN_DIRECTORY "/%s", e->d_name);
            if (stat(path, &s) || !S_ISREG(s.st_mode) || !(s.st_mode & S_IXUSR))
                continue;
            rv |= rpc_plugin_register_exec(ctx, path);
        }
        closedir(d);
    }
    if ((d = opendir(RPC_LIBRARY_DIRECTORY)) != NULL)
    {
        while ((e = readdir(d)) != NULL)
        {
            snprintf(path, sizeof(path) - 1,
                     RPC_LIBRARY_DIRECTORY "/%s", e->d_name);
            if (stat(path, &s) || !S_ISREG(s.st_mode))
                continue;
            rv |= rpc_plugin_register_library(ctx, path);
        }
        closedir(d);
    }
    return rv;
}
References ctx, path, RPC_LIBRARY_DIRECTORY, RPC_PLUGIN_DIRECTORY, rpc_plugin_register_exec(), and rpc_plugin_register_library().
Referenced by main().