zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/netifd/alias.c File Reference
alias.c File Reference
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "netifd.h"
#include "device.h"
#include "interface.h"
Classes
struct alias_device
Functions
static void alias_set_device (struct alias_device *alias, struct device *dev)
static int alias_device_set_state (struct device *dev, bool state)
static void alias_device_cb (struct device_user *dep, enum device_event ev)
static struct device * alias_device_create (const char *name, struct device_type *devtype, struct blob_attr *attr)
static void alias_device_free (struct device *dev)
static int alias_check_state (struct device *dev)
void alias_notify_device (const char *name, struct device *dev)
struct device * device_alias_get (const char *name)
static void __init alias_init (void)
Variables
static struct avl_tree aliases
static struct device_type alias_device_type
Class Documentation
alias_device
struct alias_device
Definition at line 24 of file alias.c.
Class Members
struct avl_node avl
struct device_user dep
struct device dev
char name[]
struct device_user new_dep
bool update
Function Documentation
alias_check_state()
static int alias_check_state (struct device * dev) static
Definition at line 152 of file alias.c.
{
    struct alias_device *alias;
    struct interface *iface;
    struct device *ndev = NULL;
    alias = container_of(dev, struct alias_device, dev);
    iface = vlist_find(&interfaces, alias->name, iface, node);
    if (iface && iface->state == IFS_UP)
        ndev = iface->l3_dev.dev;
    alias_set_device(alias, ndev);
    return 0;
}
References alias_set_device(), container_of, device_user::dev, IFS_UP, interfaces, interface::l3_dev, alias_device::name, interface::state, and vlist_find.
alias_device_cb()
static void alias_device_cb (struct device_user * dep, enum device_event ev) static
Definition at line 87 of file alias.c.
{
    struct alias_device *alias;
    alias = container_of(dep, struct alias_device, dep);
    switch (ev) {
    case DEV_EVENT_ADD:
        device_set_present(&alias->dev, true);
        break;
    case DEV_EVENT_REMOVE:
        device_set_present(&alias->dev, false);
        break;
    case DEV_EVENT_LINK_UP:
        device_set_link(&alias->dev, true);
        break;
    case DEV_EVENT_LINK_DOWN:
        device_set_link(&alias->dev, false);
        break;
    case DEV_EVENT_UPDATE_IFINDEX:
        device_set_ifindex(&alias->dev, dep->dev->ifindex);
        break;
    default:
        device_broadcast_event(&alias->dev, ev);
        break;
    }
}
References container_of, alias_device::dep, alias_device::dev, device_user::dev, DEV_EVENT_ADD, DEV_EVENT_LINK_DOWN, DEV_EVENT_LINK_UP, DEV_EVENT_REMOVE, DEV_EVENT_UPDATE_IFINDEX, device_broadcast_event, device_set_ifindex(), device_set_link(), device_set_present, and device::ifindex.
Referenced by alias_device_create().
alias_device_create()
static struct device * alias_device_create (const char * name, struct device_type * devtype, struct blob_attr * attr) static
Definition at line 115 of file alias.c.
{
    struct alias_device *alias;
    alias = calloc(1, sizeof(*alias) + strlen(name) + 1);
    if (!alias)
        return NULL;
    strcpy(alias->name, name);
    alias->dev.set_state = alias_device_set_state;
    alias->dev.hidden = true;
    if (device_init_virtual(&alias->dev, devtype, NULL) < 0) {
        free(alias);
        return NULL;
    }
    alias->avl.key = alias->name;
    avl_insert(&aliases, &alias->avl);
    alias->dep.alias = true;
    alias->dep.cb = alias_device_cb;
    device_check_state(&alias->dev);
    return &alias->dev;
}
References device_user::alias, alias_device_cb(), alias_device_set_state(), aliases, alias_device::avl, avl_insert(), device_user::cb, alias_device::dep, alias_device::dev, device_check_state(), device_init_virtual(), device::hidden, avl_node::key, alias_device::name, and device::set_state.
Referenced by device_alias_get().
alias_device_free()
static void alias_device_free (struct device * dev) static
Definition at line 141 of file alias.c.
{
    struct alias_device *alias;
    alias = container_of(dev, struct alias_device, dev);
    device_remove_user(&alias->new_dep);
    device_remove_user(&alias->dep);
    avl_delete(&aliases, &alias->avl);
    free(alias);
}
References aliases, alias_device::avl, avl_delete(), container_of, alias_device::dep, alias_device::dev, device_remove_user(), and alias_device::new_dep.
alias_device_set_state()
static int alias_device_set_state (struct device * dev, bool state) static
Definition at line 69 of file alias.c.
{
    struct alias_device *alias;
    alias = container_of(dev, struct alias_device, dev);
    if (!alias->dep.dev)
        return -1;
    if (state)
        return device_claim(&alias->dep);
    device_release(&alias->dep);
    if (alias->update)
        alias_set_device(alias, alias->new_dep.dev);
    return 0;
}
References alias_set_device(), container_of, alias_device::dep, alias_device::dev, device_user::dev, device_claim(), device_release(), alias_device::new_dep, state, and alias_device::update.
Referenced by alias_device_create().
alias_init()
static void __init alias_init (void) static
Definition at line 198 of file alias.c.
{
    avl_init(&aliases, avl_strcmp, false, NULL);
}
References aliases, avl_init(), and avl_strcmp().
alias_notify_device()
void alias_notify_device (const char * name, struct device * dev)
Definition at line 177 of file alias.c.
{
    struct alias_device *alias;
    alias = avl_find_element(&aliases, name, alias, avl);
    if (alias)
        alias_set_device(alias, dev);
}
References alias_set_device(), aliases, alias_device::avl, avl_find_element, alias_device::dev, and alias_device::name.
Referenced by interface_event(), and netifd_handle_alias().
alias_set_device()
static void alias_set_device (struct alias_device * alias, struct device * dev) static
Definition at line 33 of file alias.c.
{
    if (dev == alias->dep.dev) {
        if (alias->update) {
            device_remove_user(&alias->new_dep);
            alias->update = false;
            if (dev)
                device_set_present(&alias->dev, true);
        }
        return;
    }
    device_set_present(&alias->dev, false);
    device_remove_user(&alias->new_dep);
    if (alias->dev.active) {
        if (dev)
            device_add_user(&alias->new_dep, dev);
        alias->update = true;
        return;
    }
    alias->update = false;
    device_remove_user(&alias->dep);
    alias->dev.hidden = !dev;
    if (dev) {
        device_set_ifindex(&alias->dev, dev->ifindex);
        device_set_ifname(&alias->dev, dev->ifname);
        device_add_user(&alias->dep, dev);
    } else {
        device_set_ifname(&alias->dev, "");
        device_set_link(&alias->dev, false);
    }
}
References device_user::alias, device_user::dev, device_add_user(), device_remove_user(), device_set_ifindex(), device_set_ifname(), device_set_link(), device_set_present, device::ifindex, and device::ifname.
Referenced by alias_check_state(), alias_device_set_state(), and alias_notify_device().
device_alias_get()
struct device * device_alias_get (const char * name)
Definition at line 187 of file alias.c.
{
    struct alias_device *alias;
    alias = avl_find_element(&aliases, name, alias, avl);
    if (alias)
        return &alias->dev;
    return alias_device_create(name, &alias_device_type, NULL);
}
References alias_device_create(), alias_device_type, aliases, alias_device::avl, avl_find_element, alias_device::dev, and alias_device::name.
Referenced by __device_get().
Variable Documentation
alias_device_type
struct device_type alias_device_type static
Initial value:
= {
    .name = "Network alias",
    .create = alias_device_create,
    .free = alias_device_free,
    .check_state = alias_check_state,
}
Definition at line 169 of file alias.c.
{
    .name = "Network alias",
    .create = alias_device_create,
    .free = alias_device_free,
    .check_state = alias_check_state,
};
Referenced by device_alias_get().
aliases
struct avl_tree aliases static
Definition at line 22 of file alias.c.
Referenced by alias_device_create(), alias_device_free(), alias_init(), alias_notify_device(), and device_alias_get().