zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/libubox/usock.h File Reference
usock.h File Reference
Macros
#define USOCK_TCP 0
#define USOCK_UDP 1
#define USOCK_SERVER 0x0100
#define USOCK_NOCLOEXEC 0x0200
#define USOCK_NONBLOCK 0x0400
#define USOCK_NUMERIC 0x0800
#define USOCK_IPV6ONLY 0x2000
#define USOCK_IPV4ONLY 0x4000
#define USOCK_UNIX 0x8000
Functions
const char * usock_port (int port)
int usock (int type, const char *host, const char *service)
int usock_inet_timeout (int type, const char *host, const char *service, void *addr, int timeout)
static int usock_inet (int type, const char *host, const char *service, void *addr)
int usock_wait_ready (int fd, int msecs)
Macro Definition Documentation
USOCK_IPV4ONLY
#define USOCK_IPV4ONLY 0x4000
Definition at line 30 of file usock.h.
Referenced by run_server(), and usock_inet_timeout().
USOCK_IPV6ONLY
#define USOCK_IPV6ONLY 0x2000
Definition at line 29 of file usock.h.
Referenced by usock_inet_timeout().
USOCK_NOCLOEXEC
#define USOCK_NOCLOEXEC 0x0200
Definition at line 26 of file usock.h.
Referenced by usock_set_flags().
USOCK_NONBLOCK
#define USOCK_NONBLOCK 0x0400
Definition at line 27 of file usock.h.
Referenced by main(), usock_inet_timeout(), and usock_set_flags().
USOCK_NUMERIC
#define USOCK_NUMERIC 0x0800
Definition at line 28 of file usock.h.
Referenced by run_server(), and usock_inet_timeout().
USOCK_SERVER
#define USOCK_SERVER 0x0100
Definition at line 25 of file usock.h.
Referenced by main(), run_server(), usock_inet_notimeout(), usock_inet_timeout(), and usock_unix().
USOCK_TCP
#define USOCK_TCP 0
Definition at line 22 of file usock.h.
Referenced by run_server(), usock_inet_notimeout(), usock_inet_timeout(), and usock_unix().
USOCK_UDP
#define USOCK_UDP 1
Definition at line 23 of file usock.h.
USOCK_UNIX
#define USOCK_UNIX 0x8000
Definition at line 31 of file usock.h.
Referenced by main(), ubus_reconnect(), udebug_connect(), and usock().
Function Documentation
usock()
int usock (int type, const char * host, const char * service)
Definition at line 252 of file usock.c.
{
    int sock;
    if (type & USOCK_UNIX)
        sock = usock_unix(type, host);
    else
        sock = usock_inet(type, host, service, NULL);
    if (sock < 0)
        return -1;
    return sock;
}
References type, usock_inet(), USOCK_UNIX, and usock_unix().
Referenced by main(), run_server(), ubus_reconnect(), and udebug_connect().
usock_inet()
static int usock_inet (int type, const char * host, const char * service, void * addr) inline static
Definition at line 38 of file usock.h.
{
    return usock_inet_timeout(type, host, service, addr, -1);
}
References type, and usock_inet_timeout().
Referenced by usock().
usock_inet_timeout()
int usock_inet_timeout (int type, const char * host, const char * service, void * addr, int timeout)
Definition at line 134 of file usock.c.
{
    int socktype = ((type & 0xff) == USOCK_TCP) ? SOCK_STREAM : SOCK_DGRAM;
    bool server = !!(type & USOCK_SERVER);
    struct addrinfo *result, *rp;
    struct addrinfo hints = {
        .ai_family = (type & USOCK_IPV6ONLY) ? AF_INET6 :
            (type & USOCK_IPV4ONLY) ? AF_INET : AF_UNSPEC,
        .ai_socktype = socktype,
        .ai_flags = AI_ADDRCONFIG
            | ((type & USOCK_SERVER) ? AI_PASSIVE : 0)
            | ((type & USOCK_NUMERIC) ? AI_NUMERICHOST : 0),
    };
    struct addrinfo *rp_v6 = NULL;
    struct addrinfo *rp_v4 = NULL;
    struct pollfd pfds[2] = {
        { .fd = -1, .events = POLLOUT },
        { .fd = -1, .events = POLLOUT },
    };
    int sock = -1;
    int i;
    if (getaddrinfo(host, service, &hints, &result))
        return -1;
    if (timeout <= 0 || server) {
        sock = usock_inet_notimeout(type, result, addr);
        goto free_addrinfo;
    }
    for (rp = result; rp != NULL; rp = rp->ai_next) {
        if (rp->ai_family == AF_INET6 && !rp_v6)
            rp_v6 = rp;
        if (rp->ai_family == AF_INET && !rp_v4)
            rp_v4 = rp;
    }
    if (!rp_v6 && !rp_v4)
        goto out;
    if (rp_v6) {
        rp = rp_v6;
        pfds[0].fd = usock_connect(type | USOCK_NONBLOCK, rp->ai_addr,
                       rp->ai_addrlen, rp->ai_family,
                       socktype, server);
        if (pfds[0].fd < 0) {
            rp_v6 = NULL;
            goto try_v4;
        }
        if (timeout > 300) {
            if (poll_restart(pfds, 1, 300) == 1) {
                rp = rp_v6;
                sock = pfds[0].fd;
                goto out;
            }
        }
        timeout -= 300;
    }
try_v4:
    if (rp_v4) {
        rp = rp_v4;
        pfds[1].fd = usock_connect(type | USOCK_NONBLOCK, rp->ai_addr,
                         rp->ai_addrlen, rp->ai_family,
                         socktype, server);
        if (pfds[1].fd < 0) {
            rp_v4 = NULL;
            if (!rp_v6)
                goto out;
            goto wait;
        }
    }
wait:
    poll_restart(pfds + !rp_v6, !!rp_v6 + !!rp_v4, timeout);
    if (pfds[0].revents & POLLOUT) {
        rp = rp_v6;
        sock = pfds[0].fd;
        goto out;
    }
    if (pfds[1].revents & POLLOUT) {
        rp = rp_v4;
        sock = pfds[1].fd;
        goto out;
    }
out:
    for (i = 0; i < 2; i++) {
        int fd = pfds[i].fd;
        if (fd >= 0 && fd != sock)
            close(fd);
    }
    if (!(type & USOCK_NONBLOCK))
        fcntl(sock, F_SETFL, fcntl(sock, F_GETFL) & ~O_NONBLOCK);
    if (addr && sock >= 0)
        memcpy(addr, rp->ai_addr, rp->ai_addrlen);
free_addrinfo:
    freeaddrinfo(result);
    return sock;
}
References poll_restart(), server, timeout, type, usock_connect(), usock_inet_notimeout(), USOCK_IPV4ONLY, USOCK_IPV6ONLY, USOCK_NONBLOCK, USOCK_NUMERIC, USOCK_SERVER, and USOCK_TCP.
Referenced by usock_inet().
usock_port()
const char * usock_port (int port)
Definition at line 240 of file usock.c.
{
    static char buffer[sizeof("65535\0")];
    if (port < 0 || port > 65535)
        return NULL;
    snprintf(buffer, sizeof(buffer), "%u", port);
    return buffer;
}
References port.
usock_wait_ready()
int usock_wait_ready (int fd, int msecs)
Wait for a socket to become ready.
This may be useful for users of USOCK_NONBLOCK to wait (with a timeout) for a socket.
Parameters
fd file descriptor of socket
msecs timeout in microseconds
Definition at line 266 of file usock.c.
{
    struct pollfd fds[1];
    int res;
    fds[0].fd = fd;
    fds[0].events = POLLOUT;
    res = poll(fds, 1, msecs);
    if (res < 0) {
        return errno;
    } else if (res == 0) {
        return -ETIMEDOUT;
    } else {
        int err = 0;
        socklen_t optlen = sizeof(err);
        res = getsockopt(fd, SOL_SOCKET, SO_ERROR, &err, &optlen);
        if (res)
            return errno;
        if (err)
            return err;
    }
    return 0;
}
References err.