zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/jail/capabilities.c File Reference
capabilities.c File Reference
#include <syslog.h>
#include <sys/prctl.h>
#include <libubox/blobmsg.h>
#include <libubox/blobmsg_json.h>
#include "log.h"
#include "../capabilities-names.h"
#include "capabilities.h"
Macros
#define _GNU_SOURCE 1
#define JAIL_CAP_ERROR (1LLU << (CAP_LAST_CAP+1))
#define JAIL_CAP_ALL (0xffffffffffffffffLLU)
Enumerations
enum {
OCI_CAPABILITIES_BOUNDING , OCI_CAPABILITIES_EFFECTIVE , OCI_CAPABILITIES_INHERITABLE , OCI_CAPABILITIES_PERMITTED ,
OCI_CAPABILITIES_AMBIENT , __OCI_CAPABILITIES_MAX
}
Functions
static int find_capabilities (const char *name)
static uint64_t parseOCIcap (struct blob_attr *msg)
int parseOCIcapabilities (struct jail_capset *capset, struct blob_attr *msg)
int applyOCIcapabilities (struct jail_capset ocicapset, uint64_t retain)
int parseOCIcapabilities_from_file (struct jail_capset *capset, const char *file)
Variables
static const struct blobmsg_policy oci_capabilities_policy []
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE 1
Definition at line 15 of file capabilities.c.
JAIL_CAP_ALL
#define JAIL_CAP_ALL (0xffffffffffffffffLLU)
Definition at line 26 of file capabilities.c.
Referenced by applyOCIcapabilities(), and parseOCIcap().
JAIL_CAP_ERROR
#define JAIL_CAP_ERROR (1LLU << (CAP_LAST_CAP+1))
Definition at line 25 of file capabilities.c.
Referenced by parseOCIcap(), and parseOCIcapabilities().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OCI_CAPABILITIES_BOUNDING
OCI_CAPABILITIES_EFFECTIVE
OCI_CAPABILITIES_INHERITABLE
OCI_CAPABILITIES_PERMITTED
OCI_CAPABILITIES_AMBIENT
__OCI_CAPABILITIES_MAX
Definition at line 39 of file capabilities.c.
     {
    OCI_CAPABILITIES_BOUNDING,
    OCI_CAPABILITIES_EFFECTIVE,
    OCI_CAPABILITIES_INHERITABLE,
    OCI_CAPABILITIES_PERMITTED,
    OCI_CAPABILITIES_AMBIENT,
    __OCI_CAPABILITIES_MAX
};
Function Documentation
applyOCIcapabilities()
int applyOCIcapabilities (struct jail_capset ocicapset, uint64_t retain)
Definition at line 120 of file capabilities.c.
{
    struct __user_cap_header_struct uh = {};
    struct __user_cap_data_struct ud[2];
    int cap;
    int is_set;
    if (!ocicapset.apply)
        return 0;
    /* drop from bounding set */
    if (ocicapset.bounding != JAIL_CAP_ALL) {
        for (cap = 0; cap <= CAP_LAST_CAP; cap++) {
            if (!prctl(PR_CAPBSET_READ, cap, 0, 0, 0)) {
                /* can't raise */
                if (ocicapset.bounding & (1LLU << cap))
                    ERROR("capability %s (%d) is not in bounding set\n", capabilities_names[cap], cap);
                continue;
            }
            if ( ((ocicapset.bounding | retain) & (1LLU << cap)) == 0) {
                DEBUG("dropping capability %s (%d) from bounding set\n", capabilities_names[cap], cap);
                if (prctl(PR_CAPBSET_DROP, cap, 0, 0, 0)) {
                    ERROR("prctl(PR_CAPBSET_DROP, %d) failed: %m\n", cap);
                    return errno;
                }
            } else {
                DEBUG("keeping capability %s (%d)\n", capabilities_names[cap], cap);
            }
        }
    }
    /* set effective, permitted and inheritable */
    uh.version = _LINUX_CAPABILITY_VERSION_3;
    uh.pid = getpid();
    if (capget(&uh, ud)) {
        ERROR("capget() failed\n");
        return -1;
    }
    DEBUG("old capabilities: Pe=%016llx Pp=%016llx Pi=%016llx\n",
        0LLU | ud[0].effective | (0LLU | ud[1].effective) << 32,
        0LLU | ud[0].permitted | (0LLU | ud[1].permitted) << 32,
        0LLU | ud[0].inheritable | (0LLU | ud[1].inheritable) << 32);
    if (ocicapset.effective != JAIL_CAP_ALL) {
        ud[0].effective = (ocicapset.effective | retain) & 0xFFFFFFFFU;
        ud[1].effective = ((ocicapset.effective | retain) >> 32) & 0xFFFFFFFFU;
    }
    if (ocicapset.permitted != JAIL_CAP_ALL) {
        ud[0].permitted = (ocicapset.permitted | retain) & 0xFFFFFFFFU;
        ud[1].permitted = ((ocicapset.permitted | retain) >> 32) & 0xFFFFFFFFU;
    }
    if (ocicapset.inheritable != JAIL_CAP_ALL) {
        ud[0].inheritable = (ocicapset.inheritable | retain) & 0xFFFFFFFFU;
        ud[1].inheritable = ((ocicapset.inheritable | retain) >> 32) & 0xFFFFFFFFU;
    }
    DEBUG("new capabilities: Pe=%016llx Pp=%016llx Pi=%016llx\n",
        0LLU | ud[0].effective | (0LLU | ud[1].effective) << 32,
        0LLU | ud[0].permitted | (0LLU | ud[1].permitted) << 32,
        0LLU | ud[0].inheritable | (0LLU | ud[1].inheritable) << 32);
    if (capset(&uh, ud)) {
        ERROR("capset() failed\n");
        return -1;
    }
    /* edit ambient set */
    if (ocicapset.ambient != JAIL_CAP_ALL) {
        for (cap = 0; cap <= CAP_LAST_CAP; cap++) {
            is_set = prctl(PR_CAP_AMBIENT, PR_CAP_AMBIENT_IS_SET, cap, 0, 0);
            if ( (ocicapset.ambient & (1LLU << cap)) == 0) {
                if (is_set) {
                    DEBUG("dropping capability %s (%d) from ambient set\n", capabilities_names[cap], cap);
                    if (prctl(PR_CAP_AMBIENT, PR_CAP_AMBIENT_LOWER, cap, 0, 0)) {
                        ERROR("prctl(PR_CAP_AMBIENT, PR_CAP_AMBIENT_LOWER, %d, 0, 0) failed: %m\n", cap);
                        return errno;
                    }
                }
            } else {
                if (!is_set) {
                    DEBUG("raising capability %s (%d) to ambient set\n", capabilities_names[cap], cap);
                    if (prctl(PR_CAP_AMBIENT, PR_CAP_AMBIENT_RAISE, cap, 0, 0)) {\
                        ERROR("prctl(PR_CAP_AMBIENT, PR_CAP_AMBIENT_RAISE, %d, 0, 0) failed: %m\n", cap);
                        return errno;
                    }
                }
            }
        }
    }
    return 0;
}
References jail_capset::ambient, jail_capset::apply, jail_capset::bounding, capget(), capset(), DEBUG, jail_capset::effective, ERROR, jail_capset::inheritable, JAIL_CAP_ALL, jail_capset::permitted, and ud.
Referenced by post_start_hook().
find_capabilities()
static int find_capabilities (const char * name) static
Definition at line 28 of file capabilities.c.
{
    int i;
    for (i = 0; i <= CAP_LAST_CAP; i++)
        if (capabilities_names[i] && !strcasecmp(capabilities_names[i], name))
            return i;
    return -1;
}
Referenced by parseOCIcap().
parseOCIcap()
static uint64_t parseOCIcap (struct blob_attr * msg) static
Definition at line 56 of file capabilities.c.
{
    struct blob_attr *cur;
    int rem;
    uint64_t caps = 0;
    int capnum;
    /* each capset is optional, set all-1 mask if absent */
    if (!msg)
        return JAIL_CAP_ALL;
    blobmsg_for_each_attr(cur, msg, rem) {
        capnum = find_capabilities(blobmsg_get_string(cur));
        if (capnum < 0)
            return JAIL_CAP_ERROR;
        caps |= (1LLU << capnum);
    }
    return caps;
}
References blobmsg_for_each_attr, blobmsg_get_string(), find_capabilities(), JAIL_CAP_ALL, and JAIL_CAP_ERROR.
Referenced by parseOCIcapabilities().
parseOCIcapabilities()
int parseOCIcapabilities (struct jail_capset * capset, struct blob_attr * msg)
Definition at line 78 of file capabilities.c.
{
    struct blob_attr *tb[__OCI_CAPABILITIES_MAX];
    uint64_t caps;
    blobmsg_parse(oci_capabilities_policy, __OCI_CAPABILITIES_MAX, tb, blobmsg_data(msg), blobmsg_len(msg));
    caps = parseOCIcap(tb[OCI_CAPABILITIES_BOUNDING]);
    if (caps == JAIL_CAP_ERROR)
        return EINVAL;
    else
        capset->bounding = caps;
    caps = parseOCIcap(tb[OCI_CAPABILITIES_EFFECTIVE]);
    if (caps == JAIL_CAP_ERROR)
        return EINVAL;
    else
        capset->effective = caps;
    caps = parseOCIcap(tb[OCI_CAPABILITIES_INHERITABLE]);
    if (caps == JAIL_CAP_ERROR)
        return EINVAL;
    else
        capset->inheritable = caps;
    caps = parseOCIcap(tb[OCI_CAPABILITIES_PERMITTED]);
    if (caps == JAIL_CAP_ERROR)
        return EINVAL;
    else
        capset->permitted = caps;
    caps = parseOCIcap(tb[OCI_CAPABILITIES_AMBIENT]);
    if (caps == JAIL_CAP_ERROR)
        return EINVAL;
    else
        capset->ambient = caps;
    capset->apply = 1;
    return 0;
}
References __OCI_CAPABILITIES_MAX, blobmsg_data(), blobmsg_len(), blobmsg_parse(), capset(), JAIL_CAP_ERROR, OCI_CAPABILITIES_AMBIENT, OCI_CAPABILITIES_BOUNDING, OCI_CAPABILITIES_EFFECTIVE, OCI_CAPABILITIES_INHERITABLE, OCI_CAPABILITIES_PERMITTED, oci_capabilities_policy, and parseOCIcap().
Referenced by parseOCIcapabilities_from_file(), and parseOCIprocess().
parseOCIcapabilities_from_file()
int parseOCIcapabilities_from_file (struct jail_capset * capset, const char * file)
Definition at line 218 of file capabilities.c.
{
    struct blob_buf b = { 0 };
    int ret;
    blob_buf_init(&b, 0);
    ret = !blobmsg_add_json_from_file(&b, file);
    if (ret) {
        ERROR("failed to load %s\n", file);
        goto err;
    }
    ret = parseOCIcapabilities(capset, b.head);
err:
    blob_buf_free(&b);
    return ret;
}
References b, blob_buf_free(), blob_buf_init(), blobmsg_add_json_from_file(), capset(), err, ERROR, blob_buf::head, and parseOCIcapabilities().
Referenced by main().
Variable Documentation
oci_capabilities_policy
const struct blobmsg_policy oci_capabilities_policy[] static
Initial value:
= {
    [OCI_CAPABILITIES_BOUNDING] = { "bounding", BLOBMSG_TYPE_ARRAY },
    [OCI_CAPABILITIES_EFFECTIVE] = { "effective", BLOBMSG_TYPE_ARRAY },
    [OCI_CAPABILITIES_INHERITABLE] = { "inheritable", BLOBMSG_TYPE_ARRAY },
    [OCI_CAPABILITIES_PERMITTED] = { "permitted", BLOBMSG_TYPE_ARRAY },
    [OCI_CAPABILITIES_AMBIENT] = { "ambient", BLOBMSG_TYPE_ARRAY },
}
Definition at line 48 of file capabilities.c.
{
    [OCI_CAPABILITIES_BOUNDING] = { "bounding", BLOBMSG_TYPE_ARRAY },
    [OCI_CAPABILITIES_EFFECTIVE] = { "effective", BLOBMSG_TYPE_ARRAY },
    [OCI_CAPABILITIES_INHERITABLE] = { "inheritable", BLOBMSG_TYPE_ARRAY },
    [OCI_CAPABILITIES_PERMITTED] = { "permitted", BLOBMSG_TYPE_ARRAY },
    [OCI_CAPABILITIES_AMBIENT] = { "ambient", BLOBMSG_TYPE_ARRAY },
};
Referenced by parseOCIcapabilities().