zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/libubox/tests/test-blobmsg-parse.c File Reference
test-blobmsg-parse.c File Reference
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include <libgen.h>
#include "blobmsg.h"
Macros
#define BUF_LEN 256
Enumerations
enum { FOO_MESSAGE , FOO_LIST , FOO_TESTDATA , __FOO_MAX }
Functions
static void dump_result (const char *fn, int r, const char *filename, struct blob_attr **tb)
static void test_blobmsg (const char *filename)
int main (int argc, char *argv[])
Variables
static const struct blobmsg_policy foo_policy []
Macro Definition Documentation
BUF_LEN
#define BUF_LEN 256
Referenced by test_blobmsg().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
FOO_MESSAGE
FOO_LIST
FOO_TESTDATA
__FOO_MAX
Definition at line 8 of file test-blobmsg-parse.c.
     {
    FOO_MESSAGE,
    FOO_LIST,
    FOO_TESTDATA,
    __FOO_MAX
};
Function Documentation
dump_result()
static void dump_result (const char * fn, int r, const char * filename, struct blob_attr ** tb) static
Definition at line 30 of file test-blobmsg-parse.c.
{
    fprintf(stdout, "%s: %s: %c%c%c (%d)\n", basename((char *) filename), fn,
        tb[FOO_MESSAGE] ? 'M' : '.',
        tb[FOO_LIST] ? 'L' : '.',
        tb[FOO_TESTDATA] ? 'T' : '.',
        r);
}
References FOO_LIST, FOO_MESSAGE, FOO_TESTDATA, and r.
Referenced by test_blobmsg().
main()
int main (int argc, char * argv[])
Definition at line 70 of file test-blobmsg-parse.c.
{
    if (argc != 2) {
        fprintf(stderr, "Usage: %s <blobmsg.bin>\n", argv[0]);
        return 3;
    }
    test_blobmsg(argv[1]);
    return 0;
}
References test_blobmsg().
test_blobmsg()
static void test_blobmsg (const char * filename) static
Definition at line 39 of file test-blobmsg-parse.c.
{
#define BUF_LEN 256
    int r = 0;
    size_t len = 0;
    FILE *fd = NULL;
    char *buf = NULL;
    struct blob_attr *tb[__FOO_MAX];
    fd = fopen(filename, "r");
    if (!fd) {
        fprintf(stderr, "unable to open %s\n", filename);
        return;
    }
    buf = malloc(BUF_LEN+1);
    if (!buf)
        return;
    len = fread(buf, 1, BUF_LEN, fd);
    fclose(fd);
    r = blobmsg_parse(foo_policy, ARRAY_SIZE(foo_policy), tb, buf, len);
    dump_result("blobmsg_parse", r, filename, tb);
    r = blobmsg_parse_array(foo_policy, ARRAY_SIZE(foo_policy), tb, buf, len);
    dump_result("blobmsg_parse_array", r, filename, tb);
    free(buf);
}
References __FOO_MAX, ARRAY_SIZE, blobmsg_parse(), blobmsg_parse_array(), buf, BUF_LEN, dump_result(), foo_policy, and r.
Referenced by main().
Variable Documentation
foo_policy
const struct blobmsg_policy foo_policy[] static
Initial value:
= {
    [FOO_MESSAGE] = {
        .name = "message",
        .type = BLOBMSG_TYPE_STRING,
    },
    [FOO_LIST] = {
        .name = "list",
        .type = BLOBMSG_TYPE_ARRAY,
    },
    [FOO_TESTDATA] = {
        .name = "testdata",
        .type = BLOBMSG_TYPE_TABLE,
    },
}
Definition at line 15 of file test-blobmsg-parse.c.
{
    [FOO_MESSAGE] = {
        .name = "message",
        .type = BLOBMSG_TYPE_STRING,
    },
    [FOO_LIST] = {
        .name = "list",
        .type = BLOBMSG_TYPE_ARRAY,
    },
    [FOO_TESTDATA] = {
        .name = "testdata",
        .type = BLOBMSG_TYPE_TABLE,
    },
};
Referenced by fuzz_blob_parse(), fuzz_blobmsg_parse(), and test_blobmsg().