zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/initd/preinit.c File Reference
preinit.c File Reference
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/mount.h>
#include <fcntl.h>
#include <libubox/uloop.h>
#include <libubox/utils.h>
#include <libubus.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include "init.h"
#include "../watchdog.h"
#include "../sysupgrade.h"
Macros
#define _GNU_SOURCE
Functions
static void check_dbglvl (void)
static void check_sysupgrade (void)
static void spawn_procd (struct uloop_process *proc, int ret)
static void plugd_proc_cb (struct uloop_process *proc, int ret)
void preinit (void)
Variables
static struct uloop_process preinit_proc
static struct uloop_process plugd_proc
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 14 of file preinit.c.
Function Documentation
check_dbglvl()
static void check_dbglvl (void) static
Definition at line 37 of file preinit.c.
{
    FILE *fp = fopen("/tmp/debug_level", "r");
    int lvl = 0;
    if (!fp)
        return;
    if (fscanf(fp, "%d", &lvl) == EOF)
        ERROR("failed to read debug level: %m\n");
    fclose(fp);
    unlink("/tmp/debug_level");
    if (lvl > 0 && lvl < 5)
        debug = lvl;
}
References debug, and ERROR.
Referenced by spawn_procd().
check_sysupgrade()
static void check_sysupgrade (void) static
Definition at line 54 of file preinit.c.
{
    char *prefix = NULL, *path = NULL, *command = NULL;
    size_t n;
    if (chdir("/"))
        return;
    FILE *sysupgrade = fopen("/tmp/sysupgrade", "r");
    if (!sysupgrade)
        return;
    n = 0;
    if (getdelim(&prefix, &n, 0, sysupgrade) < 0)
        goto fail;
    n = 0;
    if (getdelim(&path, &n, 0, sysupgrade) < 0)
        goto fail;
    n = 0;
    if (getdelim(&command, &n, 0, sysupgrade) < 0)
        goto fail;
    fclose(sysupgrade);
    sysupgrade_exec_upgraded(prefix, path, NULL, command, NULL);
    while (true)
        sleep(1);
fail:
    fclose(sysupgrade);
    free(prefix);
    free(path);
    free(command);
}
References path, sysupgrade(), and sysupgrade_exec_upgraded().
Referenced by spawn_procd().
plugd_proc_cb()
static void plugd_proc_cb (struct uloop_process * proc, int ret) static
Definition at line 118 of file preinit.c.
{
    proc->pid = 0;
}
References uloop_process::pid.
Referenced by preinit().
preinit()
void preinit (void)
Definition at line 124 of file preinit.c.
{
    char *init[] = { "/bin/sh", "/etc/preinit", NULL };
    char *plug[] = { "/sbin/procd", "-h", "/etc/hotplug-preinit.json", NULL };
    int fd;
    LOG("- preinit -\n");
    plugd_proc.cb = plugd_proc_cb;
    plugd_proc.pid = fork();
    if (!plugd_proc.pid) {
        execvp(plug[0], plug);
        ERROR("Failed to start plugd: %m\n");
        exit(EXIT_FAILURE);
    }
    if (plugd_proc.pid <= 0) {
        ERROR("Failed to start new plugd instance: %m\n");
        return;
    }
    uloop_process_add(&plugd_proc);
    setenv("PREINIT", "1", 1);
    fd = creat("/tmp/.preinit", 0600);
    if (fd < 0)
        ERROR("Failed to create sentinel file: %m\n");
    else
        close(fd);
    preinit_proc.cb = spawn_procd;
    preinit_proc.pid = fork();
    if (!preinit_proc.pid) {
        execvp(init[0], init);
        ERROR("Failed to start preinit: %m\n");
        exit(EXIT_FAILURE);
    }
    if (preinit_proc.pid <= 0) {
        ERROR("Failed to start new preinit instance: %m\n");
        return;
    }
    uloop_process_add(&preinit_proc);
    DEBUG(4, "Launched preinit instance, pid=%d\n", (int) preinit_proc.pid);
}
References uloop_process::cb, DEBUG, ERROR, LOG, uloop_process::pid, plugd_proc, plugd_proc_cb(), preinit_proc, spawn_procd(), and uloop_process_add().
Referenced by main(), and watchdog_init().
spawn_procd()
static void spawn_procd (struct uloop_process * proc, int ret) static
Definition at line 91 of file preinit.c.
{
    char *wdt_fd = watchdog_fd();
    char *argv[] = { "/sbin/procd", NULL};
    char dbg[2];
    if (plugd_proc.pid > 0)
        kill(plugd_proc.pid, SIGKILL);
    unsetenv("PREINIT");
    unlink("/tmp/.preinit");
    check_sysupgrade();
    DEBUG(2, "Exec to real procd now\n");
    if (wdt_fd)
        setenv("WDTFD", wdt_fd, 1);
    check_dbglvl();
    if (debug > 0) {
        snprintf(dbg, 2, "%d", debug);
        setenv("DBGLVL", dbg, 1);
    }
    execvp(argv[0], argv);
}
References check_dbglvl(), check_sysupgrade(), dbg, DEBUG, debug, uloop_process::pid, plugd_proc, watchdog_fd(), and wdt_fd.
Referenced by preinit().
Variable Documentation
plugd_proc
struct uloop_process plugd_proc static
Definition at line 34 of file preinit.c.
Referenced by preinit(), and spawn_procd().
preinit_proc
struct uloop_process preinit_proc static
Definition at line 33 of file preinit.c.
Referenced by preinit().