zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/ustp/bridge_track.h File Reference
bridge_track.h File Reference
#include "mstp.h"
Functions
int bridge_create (int bridge_idx, CIST_BridgeConfig *cfg)
void bridge_delete (int bridge_idx)
int bridge_track_fini (void)
Function Documentation
bridge_create()
int bridge_create (int bridge_idx, CIST_BridgeConfig * cfg)
Definition at line 645 of file bridge_track.c.
{
    struct dirent **namelist;
    int *port_list, n_ports;
    bridge_t *br, *other_br;
    port_t *port, *tmp;
    int flags;
    bool found;
    int i;
    br = find_br(bridge_idx);
    if (!br)
        br = create_br(bridge_idx);
    if (!br)
        return -1;
    MSTP_IN_set_cist_bridge_config(br, cfg);
    flags = get_flags(br->sysdeps.name);
    if (flags >= 0)
        set_br_up(br, !!(flags & IFF_UP));
    n_ports = get_port_list(br->sysdeps.name, &namelist);
    port_list = alloca(n_ports * sizeof(*port_list));
    for (i = 0; i < n_ports; i++) {
        port_list[i] = if_nametoindex(namelist[i]->d_name);
        free(namelist[i]);
    }
    free(namelist);
    list_for_each_entry_safe(port, tmp, &br->ports, br_list) {
        found = false;
        for (i = 0; i < n_ports; i++) {
            if (port->sysdeps.if_index != port_list[i])
                continue;
            found = true;
            break;
        }
        if (found)
            continue;
        delete_if(port);
    }
    for (i = 0; i < n_ports; i++) {
        port = find_if(br, port_list[i]);
        if (port)
            continue;
        list_for_each_entry(other_br, &bridges, list) {
            if (br == other_br)
                continue;
            delete_if_byindex(other_br, port_list[i]);
        }
        port = find_if(br, port_list[i]);
        if (!port)
            port = create_if(br, port_list[i]);
        if (!port)
            continue;
        flags = get_flags(port->sysdeps.name);
        if (flags < 0)
            continue;
        set_if_up(port, !(~flags & (IFF_UP | IFF_RUNNING)));
    }
    return 0;
}
References create_br(), create_if(), delete_if(), delete_if_byindex(), find_br(), find_if(), get_flags(), get_port_list(), list_for_each_entry, list_for_each_entry_safe, MSTP_IN_set_cist_bridge_config(), sysdep_br_data_t::name, port, bridge_t::ports, set_br_up(), set_if_up(), and bridge_t::sysdeps.
bridge_delete()
void bridge_delete (int bridge_idx)
Definition at line 719 of file bridge_track.c.
{
    delete_br_byindex(index);
}
References delete_br_byindex().
Referenced by handle_worker_event().
bridge_track_fini()
int bridge_track_fini (void)
Definition at line 724 of file bridge_track.c.
{
    INFO("Stopping all bridges");
    bridge_t *br;
    list_for_each_entry(br, &bridges, list)
    {
        set_br_up(br, false);
    }
    return 0;
}
References INFO, list_for_each_entry, and set_br_up().
Referenced by main().