zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/libubox/ulog.h File Reference
ulog.h File Reference
#include <syslog.h>
#include "udebug.h"
Macros
#define ULOG_INFO(fmt, ...)
#define ULOG_NOTE(fmt, ...)
#define ULOG_WARN(fmt, ...)
#define ULOG_ERR(fmt, ...)
Enumerations
enum { ULOG_KMSG = (1 << 0) , ULOG_SYSLOG = (1 << 1) , ULOG_STDIO = (1 << 2) }
Functions
void ulog_open (int channels, int facility, const char *ident)
void ulog_udebug (struct udebug_buf *udb)
void ulog_close (void)
void ulog_threshold (int threshold)
void ulog (int priority, const char *fmt,...) __attribute__((format(printf
Macro Definition Documentation
ULOG_ERR
#define ULOG_ERR (fmt, ...)
Value:
ulog(LOG_ERR, fmt, ## __VA_ARGS__)
Definition at line 44 of file ulog.h.
Referenced by main(), print_syscalls(), report_seccomp_vialation(), and ubusd_acl_init_client().
ULOG_INFO
#define ULOG_INFO (fmt, ...)
Value:
ulog(LOG_INFO, fmt, ## __VA_ARGS__)
Definition at line 41 of file ulog.h.
Referenced by print_syscalls().
ULOG_NOTE
#define ULOG_NOTE (fmt, ...)
Value:
ulog(LOG_NOTICE, fmt, ## __VA_ARGS__)
Definition at line 42 of file ulog.h.
Referenced by pipe_cb().
ULOG_WARN
#define ULOG_WARN (fmt, ...)
Value:
ulog(LOG_WARNING, fmt, ## __VA_ARGS__)
Definition at line 43 of file ulog.h.
Referenced by instance_run(), instance_start(), and rpc_list_exec_timeout_cb().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ULOG_KMSG (1 << 0)
ULOG_SYSLOG (1 << 1)
ULOG_STDIO (1 << 2)
Definition at line 26 of file ulog.h.
     {
    ULOG_KMSG   = (1 << 0),
    ULOG_SYSLOG = (1 << 1),
    ULOG_STDIO  = (1 << 2)
};
Function Documentation
ulog()
void ulog (int priority, const char * fmt, ...)
ulog_close()
void ulog_close (void)
Definition at line 138 of file ulog.c.
{
    if (!_ulog_initialized)
        return;
    if (_ulog_channels & ULOG_SYSLOG)
        closelog();
    _ulog_initialized = 0;
}
References _ulog_channels, _ulog_initialized, and ULOG_SYSLOG.
Referenced by ulog_open().
ulog_open()
void ulog_open (int channels, int facility, const char * ident)
Definition at line 129 of file ulog.c.
{
    ulog_close();
    _ulog_channels = channels;
    _ulog_facility = facility;
    _ulog_ident = ident;
}
References _ulog_channels, _ulog_facility, _ulog_ident, and ulog_close().
Referenced by instance_stdio(), main(), and state_enter().
ulog_threshold()
void ulog_threshold (int threshold)
Definition at line 149 of file ulog.c.
{
    _ulog_threshold = threshold;
}
References _ulog_threshold.
Referenced by main().
ulog_udebug()
void ulog_udebug (struct udebug_buf * udb)
Definition at line 124 of file ulog.c.
{
    udb = _udb;
}
References udb.
Referenced by procd_udebug_set_enabled().