zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/ubus/ubusd_proto.c File Reference
ubusd_proto.c File Reference
#include <arpa/inet.h>
#include <unistd.h>
#include "ubusd.h"
Typedefs
typedef int(* ubus_cmd_cb) (struct ubus_client *cl, struct ubus_msg_buf *ub, struct blob_attr **attr)
Functions
struct blob_attr ** ubus_parse_msg (struct blob_attr *msg, size_t len)
static void ubus_msg_close_fd (struct ubus_msg_buf *ub)
static void ubus_msg_init (struct ubus_msg_buf *ub, uint8_t type, uint16_t seq, uint32_t peer)
static struct ubus_msg_buf * ubus_msg_from_blob (bool shared)
static struct ubus_msg_buf * ubus_reply_from_blob (struct ubus_msg_buf *ub, bool shared)
void ubus_proto_send_msg_from_blob (struct ubus_client *cl, struct ubus_msg_buf *ub, uint8_t type)
static bool ubusd_send_hello (struct ubus_client *cl)
static int ubusd_send_pong (struct ubus_client *cl, struct ubus_msg_buf *ub, struct blob_attr **attr)
static int ubusd_handle_remove_object (struct ubus_client *cl, struct ubus_msg_buf *ub, struct blob_attr **attr)
static int ubusd_handle_add_object (struct ubus_client *cl, struct ubus_msg_buf *ub, struct blob_attr **attr)
static void ubusd_send_obj (struct ubus_client *cl, struct ubus_msg_buf *ub, struct ubus_object *obj)
static int ubus_client_cmd_queue_add (struct ubus_client *cl, struct ubus_msg_buf *msg, struct ubus_object *obj)
static int __ubusd_handle_lookup (struct ubus_client *cl, struct ubus_msg_buf *ub, struct blob_attr **attr, struct ubus_client_cmd *cmd)
static int ubusd_handle_lookup (struct ubus_client *cl, struct ubus_msg_buf *ub, struct blob_attr **attr)
int ubusd_cmd_lookup (struct ubus_client *cl, struct ubus_client_cmd *cmd)
static void ubusd_forward_invoke (struct ubus_client *cl, struct ubus_object *obj, const char *method, struct ubus_msg_buf *ub, struct blob_attr *data)
static int ubusd_handle_invoke (struct ubus_client *cl, struct ubus_msg_buf *ub, struct blob_attr **attr)
static int ubusd_handle_notify (struct ubus_client *cl, struct ubus_msg_buf *ub, struct blob_attr **attr)
static struct ubus_client * ubusd_get_client_by_id (uint32_t id)
static int ubusd_handle_response (struct ubus_client *cl, struct ubus_msg_buf *ub, struct blob_attr **attr)
static int ubusd_handle_add_watch (struct ubus_client *cl, struct ubus_msg_buf *ub, struct blob_attr **attr)
static int ubusd_handle_remove_watch (struct ubus_client *cl, struct ubus_msg_buf *ub, struct blob_attr **attr)
void ubusd_proto_receive_message (struct ubus_client *cl, struct ubus_msg_buf *ub)
static int ubusd_proto_init_retmsg (struct ubus_client *cl)
struct ubus_client * ubusd_proto_new_client (int fd, uloop_fd_handler cb)
void ubusd_proto_free_client (struct ubus_client *cl)
void ubus_notify_subscription (struct ubus_object *obj)
void ubus_notify_unsubscribe (struct ubus_subscription *s)
static void __constructor ubusd_proto_init (void)
Variables
struct blob_buf b
static struct avl_tree clients
static struct blob_attr * attrbuf [UBUS_ATTR_MAX]
static const struct blob_attr_info ubus_policy [UBUS_ATTR_MAX]
static const ubus_cmd_cb handlers [__UBUS_MSG_LAST]
Typedef Documentation
ubus_cmd_cb
typedef int(* ubus_cmd_cb) (struct ubus_client *cl, struct ubus_msg_buf *ub, struct blob_attr **attr)
Definition at line 24 of file ubusd_proto.c.
Function Documentation
__ubusd_handle_lookup()
static int __ubusd_handle_lookup (struct ubus_client * cl, struct ubus_msg_buf * ub, struct blob_attr ** attr, struct ubus_client_cmd * cmd) static
Definition at line 204 of file ubusd_proto.c.
{
    struct ubus_object *obj = NULL;
    char *objpath;
    bool found = false;
    int len;
    if (!attr[UBUS_ATTR_OBJPATH]) {
        if (cmd)
            obj = cmd->obj;
        /* Start from beginning or continue from the last object */
        if (obj == NULL)
            obj = avl_first_element(&path, obj, path);
        avl_for_element_range(obj, avl_last_element(&path, obj, path), obj, path) {
            /* Keep sending objects until buffering starts */
            if (list_empty(&cl->tx_queue)) {
                ubusd_send_obj(cl, ub, obj);
            } else {
                /* Queue command and continue on the next call */
                int ret;
                if (cmd == NULL) {
                    ret = ubus_client_cmd_queue_add(cl, ub, obj);
                } else {
                    cmd->obj = obj;
                    ret = -2;
                }
                return ret;
            }
        }
        return 0;
    }
    objpath = blob_data(attr[UBUS_ATTR_OBJPATH]);
    len = strlen(objpath);
    if (objpath[len - 1] != '*') {
        obj = avl_find_element(&path, objpath, obj, path);
        if (!obj)
            return UBUS_STATUS_NOT_FOUND;
        ubusd_send_obj(cl, ub, obj);
        return 0;
    }
    objpath[--len] = 0;
    obj = avl_find_ge_element(&path, objpath, obj, path);
    if (!obj)
        return UBUS_STATUS_NOT_FOUND;
    while (!strncmp(objpath, obj->path.key, len)) {
        found = true;
        ubusd_send_obj(cl, ub, obj);
        if (obj == avl_last_element(&path, obj, path))
            break;
        obj = avl_next_element(obj, path);
    }
    if (!found)
        return UBUS_STATUS_NOT_FOUND;
    return 0;
}
References avl_find_element, avl_find_ge_element, avl_first_element, avl_for_element_range, avl_last_element, avl_next_element, blob_data(), cmd, list_empty(), path, ubus_object::path, ubus_client::tx_queue, UBUS_ATTR_OBJPATH, ubus_client_cmd_queue_add(), UBUS_STATUS_NOT_FOUND, and ubusd_send_obj().
Referenced by ubusd_cmd_lookup(), and ubusd_handle_lookup().
ubus_client_cmd_queue_add()
static int ubus_client_cmd_queue_add (struct ubus_client * cl, struct ubus_msg_buf * msg, struct ubus_object * obj) static
Definition at line 189 of file ubusd_proto.c.
{
    struct ubus_client_cmd *cmd = malloc(sizeof(*cmd));
    if (cmd) {
        cmd->msg = msg;
        cmd->obj = obj;
        list_add_tail(&cmd->list, &cl->cmd_queue);
        return -2;
    }
    return UBUS_STATUS_UNKNOWN_ERROR;
}
References cmd, ubus_client::cmd_queue, list_add_tail(), ubus_client_cmd::msg, ubus_client_cmd::obj, and UBUS_STATUS_UNKNOWN_ERROR.
Referenced by __ubusd_handle_lookup(), and ubusd_handle_lookup().
ubus_msg_close_fd()
static void ubus_msg_close_fd (struct ubus_msg_buf * ub) static
Definition at line 43 of file ubusd_proto.c.
{
    if (ub->fd < 0)
        return;
    close(ub->fd);
    ub->fd = -1;
}
References ubus_msg_buf::fd.
Referenced by ubusd_proto_receive_message().
ubus_msg_from_blob()
static struct ubus_msg_buf * ubus_msg_from_blob (bool shared) static
Definition at line 60 of file ubusd_proto.c.
{
    return ubus_msg_new(b.head, blob_raw_len(b.head), shared);
}
References b, blob_raw_len(), blob_buf::head, and ubus_msg_new().
Referenced by ubus_notify_subscription(), ubus_notify_unsubscribe(), ubus_reply_from_blob(), and ubusd_send_hello().
ubus_msg_init()
static void ubus_msg_init (struct ubus_msg_buf * ub, uint8_t type, uint16_t seq, uint32_t peer) static
Definition at line 52 of file ubusd_proto.c.
{
    ub->hdr.version = 0;
    ub->hdr.type = type;
    ub->hdr.seq = seq;
    ub->hdr.peer = peer;
}
References ubus_msg_buf::hdr, ubus_msghdr::peer, ubus_msghdr::seq, type, ubus_msghdr::type, and ubus_msghdr::version.
Referenced by ubus_notify_subscription(), ubus_notify_unsubscribe(), ubus_reply_from_blob(), and ubusd_send_hello().
ubus_notify_subscription()
void ubus_notify_subscription (struct ubus_object * obj)
Definition at line 615 of file ubusd_proto.c.
{
    bool active = !list_empty(&obj->subscribers);
    struct ubus_msg_buf *ub;
    blob_buf_init(&b, 0);
    blob_put_int32(&b, UBUS_ATTR_OBJID, obj->id.id);
    blob_put_int8(&b, UBUS_ATTR_ACTIVE, active);
    ub = ubus_msg_from_blob(false);
    if (!ub)
        return;
    ubus_msg_init(ub, UBUS_MSG_NOTIFY, ++obj->invoke_seq, 0);
    ubus_msg_send(obj->client, ub);
    ubus_msg_free(ub);
}
References b, blob_buf_init(), blob_put_int32, blob_put_int8, ubus_object::client, ubus_object::id, ubus_object::invoke_seq, list_empty(), UBUS_ATTR_ACTIVE, UBUS_ATTR_OBJID, ubus_msg_free(), ubus_msg_from_blob(), ubus_msg_init(), UBUS_MSG_NOTIFY, and ubus_msg_send().
Referenced by ubus_subscribe(), and ubus_unsubscribe().
ubus_notify_unsubscribe()
void ubus_notify_unsubscribe (struct ubus_subscription * s)
Definition at line 633 of file ubusd_proto.c.
{
    struct ubus_msg_buf *ub;
    blob_buf_init(&b, 0);
    blob_put_int32(&b, UBUS_ATTR_OBJID, s->subscriber->id.id);
    blob_put_int32(&b, UBUS_ATTR_TARGET, s->target->id.id);
    ub = ubus_msg_from_blob(false);
    if (ub != NULL) {
        ubus_msg_init(ub, UBUS_MSG_UNSUBSCRIBE, ++s->subscriber->invoke_seq, 0);
        ubus_msg_send(s->subscriber->client, ub);
        ubus_msg_free(ub);
    }
    ubus_unsubscribe(s);
}
References b, blob_buf_init(), blob_put_int32, ubus_object::client, ubus_object::id, ubus_object::invoke_seq, ubus_subscription::subscriber, ubus_subscription::target, UBUS_ATTR_OBJID, UBUS_ATTR_TARGET, ubus_msg_free(), ubus_msg_from_blob(), ubus_msg_init(), ubus_msg_send(), UBUS_MSG_UNSUBSCRIBE, and ubus_unsubscribe().
Referenced by ubusd_free_object().
ubus_parse_msg()
struct blob_attr ** ubus_parse_msg (struct blob_attr * msg, size_t len)
Definition at line 37 of file ubusd_proto.c.
{
    blob_parse_untrusted(msg, len, attrbuf, ubus_policy, UBUS_ATTR_MAX);
    return attrbuf;
}
References attrbuf, attrbuf, blob_parse_untrusted(), UBUS_ATTR_MAX, ubus_policy, and ubus_policy.
Referenced by _ubus_parse_msg(), req_data_cb(), ubus_add_object_cb(), ubus_get_status(), ubus_lookup_cb(), ubus_lookup_id_cb(), ubus_process_notify_status(), ubus_process_obj_msg(), ubus_remove_object_cb(), ubusd_acl_recv(), ubusd_cmd_lookup(), and ubusd_proto_receive_message().
ubus_proto_send_msg_from_blob()
void ubus_proto_send_msg_from_blob (struct ubus_client * cl, struct ubus_msg_buf * ub, uint8_t type)
Definition at line 78 of file ubusd_proto.c.
{
    /* keep the fd to be passed if it is UBUS_MSG_INVOKE */
    int fd = ub->fd;
    ub = ubus_reply_from_blob(ub, true);
    if (!ub)
        return;
    ub->hdr.type = type;
    ub->fd = fd;
    ubus_msg_send(cl, ub);
    ubus_msg_free(ub);
}
References ubus_msg_buf::fd, ubus_msg_buf::hdr, type, ubus_msghdr::type, ubus_msg_free(), ubus_msg_send(), and ubus_reply_from_blob().
Referenced by ubusd_forward_invoke(), ubusd_handle_add_object(), ubusd_handle_notify(), ubusd_handle_remove_object(), ubusd_reply_query(), and ubusd_send_obj().
ubus_reply_from_blob()
static struct ubus_msg_buf * ubus_reply_from_blob (struct ubus_msg_buf * ub, bool shared) static
Definition at line 65 of file ubusd_proto.c.
{
    struct ubus_msg_buf *new;
    new = ubus_msg_from_blob(shared);
    if (!new)
        return NULL;
    ubus_msg_init(new, UBUS_MSG_DATA, ub->hdr.seq, ub->hdr.peer);
    return new;
}
References ubus_msg_buf::hdr, ubus_msghdr::peer, ubus_msghdr::seq, UBUS_MSG_DATA, ubus_msg_from_blob(), and ubus_msg_init().
Referenced by ubus_proto_send_msg_from_blob().
ubusd_cmd_lookup()
int ubusd_cmd_lookup (struct ubus_client * cl, struct ubus_client_cmd * cmd)
Definition at line 285 of file ubusd_proto.c.
{
    struct ubus_msg_buf *ub = cmd->msg;
    struct blob_attr **attr;
    int ret;
    attr = ubus_parse_msg(ub->data, blob_raw_len(ub->data));
    ret = __ubusd_handle_lookup(cl, ub, attr, cmd);
    if (ret != -2) {
        struct ubus_msg_buf *retmsg = cl->retmsg;
        int *retmsg_data = blob_data(blob_data(retmsg->data));
        retmsg->hdr.seq = ub->hdr.seq;
        retmsg->hdr.peer = ub->hdr.peer;
        *retmsg_data = htonl(ret);
        ubus_msg_send(cl, retmsg);
    }
    return ret;
}
References __ubusd_handle_lookup(), blob_data(), blob_raw_len(), cmd, ubus_msg_buf::data, ubus_msg_buf::hdr, ubus_msghdr::peer, ubus_client::retmsg, ubus_msghdr::seq, ubus_msg_send(), and ubus_parse_msg().
Referenced by ubus_client_cmd_queue_process().
ubusd_forward_invoke()
static void ubusd_forward_invoke (struct ubus_client * cl, struct ubus_object * obj, const char * method, struct ubus_msg_buf * ub, struct blob_attr * data) static
Definition at line 308 of file ubusd_proto.c.
{
    blob_put_int32(&b, UBUS_ATTR_OBJID, obj->id.id);
    blob_put_string(&b, UBUS_ATTR_METHOD, method);
    if (cl->user)
        blob_put_string(&b, UBUS_ATTR_USER, cl->user);
    if (cl->group)
        blob_put_string(&b, UBUS_ATTR_GROUP, cl->group);
    if (data)
        blob_put(&b, UBUS_ATTR_DATA, blob_data(data), blob_len(data));
    ubus_proto_send_msg_from_blob(obj->client, ub, UBUS_MSG_INVOKE);
}
References b, blob_data(), blob_len(), blob_put(), blob_put_int32, blob_put_string(), ubus_object::client, ubus_msg_buf::data, ubus_client::group, ubus_object::id, UBUS_ATTR_DATA, UBUS_ATTR_GROUP, UBUS_ATTR_METHOD, UBUS_ATTR_OBJID, UBUS_ATTR_USER, UBUS_MSG_INVOKE, ubus_proto_send_msg_from_blob(), and ubus_client::user.
Referenced by ubusd_handle_invoke(), and ubusd_handle_notify().
ubusd_get_client_by_id()
static struct ubus_client * ubusd_get_client_by_id (uint32_t id) static
Definition at line 402 of file ubusd_proto.c.
{
    struct ubus_id *clid;
    clid = ubus_find_id(&clients, id);
    if (!clid)
        return NULL;
    return container_of(clid, struct ubus_client, id);
}
References clients, container_of, and ubus_find_id().
Referenced by ubusd_handle_response().
ubusd_handle_add_object()
static int ubusd_handle_add_object (struct ubus_client * cl, struct ubus_msg_buf * ub, struct blob_attr ** attr) static
Definition at line 143 of file ubusd_proto.c.
{
    struct ubus_object *obj;
    obj = ubusd_create_object(cl, attr);
    if (!obj)
        return UBUS_STATUS_INVALID_ARGUMENT;
    blob_buf_init(&b, 0);
    blob_put_int32(&b, UBUS_ATTR_OBJID, obj->id.id);
    if (attr[UBUS_ATTR_SIGNATURE] && obj->type)
        blob_put_int32(&b, UBUS_ATTR_OBJTYPE, obj->type->id.id);
    ubus_proto_send_msg_from_blob(cl, ub, UBUS_MSG_DATA);
    return 0;
}
References b, blob_buf_init(), blob_put_int32, ubus_object::id, ubus_object_type::id, ubus_object::type, UBUS_ATTR_OBJID, UBUS_ATTR_OBJTYPE, UBUS_ATTR_SIGNATURE, UBUS_MSG_DATA, ubus_proto_send_msg_from_blob(), UBUS_STATUS_INVALID_ARGUMENT, and ubusd_create_object().
ubusd_handle_add_watch()
static int ubusd_handle_add_watch (struct ubus_client * cl, struct ubus_msg_buf * ub, struct blob_attr ** attr) static
Definition at line 439 of file ubusd_proto.c.
{
    struct ubus_object *obj, *target;
    if (!attr[UBUS_ATTR_OBJID] || !attr[UBUS_ATTR_TARGET])
        return UBUS_STATUS_INVALID_ARGUMENT;
    obj = ubusd_find_object(blob_get_u32(attr[UBUS_ATTR_OBJID]));
    if (!obj)
        return UBUS_STATUS_NOT_FOUND;
    if (cl != obj->client)
        return UBUS_STATUS_INVALID_ARGUMENT;
    target = ubusd_find_object(blob_get_u32(attr[UBUS_ATTR_TARGET]));
    if (!target || !target->client)
        return UBUS_STATUS_NOT_FOUND;
    if (cl == target->client)
        return UBUS_STATUS_INVALID_ARGUMENT;
    if (!target->path.key) {
        if (strcmp(target->client->user, cl->user) && strcmp(target->client->group, cl->group))
            return UBUS_STATUS_NOT_FOUND;
    } else if (ubusd_acl_check(cl, target->path.key, NULL, UBUS_ACL_SUBSCRIBE)) {
        return UBUS_STATUS_NOT_FOUND;
    }
    ubus_subscribe(obj, target);
    return 0;
}
References blob_get_u32(), ubus_object::client, ubus_client::group, ubus_object::path, UBUS_ACL_SUBSCRIBE, UBUS_ATTR_OBJID, UBUS_ATTR_TARGET, UBUS_STATUS_INVALID_ARGUMENT, UBUS_STATUS_NOT_FOUND, ubus_subscribe(), ubusd_acl_check(), ubusd_find_object(), and ubus_client::user.
ubusd_handle_invoke()
static int ubusd_handle_invoke (struct ubus_client * cl, struct ubus_msg_buf * ub, struct blob_attr ** attr) static
Definition at line 324 of file ubusd_proto.c.
{
    struct ubus_object *obj = NULL;
    struct ubus_id *id;
    const char *method;
    if (!attr[UBUS_ATTR_METHOD] || !attr[UBUS_ATTR_OBJID])
        return UBUS_STATUS_INVALID_ARGUMENT;
    id = ubus_find_id(&objects, blob_get_u32(attr[UBUS_ATTR_OBJID]));
    if (!id)
        return UBUS_STATUS_NOT_FOUND;
    obj = container_of(id, struct ubus_object, id);
    method = blob_data(attr[UBUS_ATTR_METHOD]);
    if (ubusd_acl_check(cl, obj->path.key, method, UBUS_ACL_ACCESS))
        return UBUS_STATUS_PERMISSION_DENIED;
    if (!obj->client)
        return obj->recv_msg(cl, ub, method, attr[UBUS_ATTR_DATA]);
    ub->hdr.peer = cl->id.id;
    blob_buf_init(&b, 0);
    ubusd_forward_invoke(cl, obj, method, ub, attr[UBUS_ATTR_DATA]);
    return -1;
}
References b, blob_buf_init(), blob_data(), blob_get_u32(), ubus_object::client, container_of, ubus_msg_buf::hdr, id, ubus_client::id, ubus_id::id, objects, ubus_object::path, ubus_msghdr::peer, ubus_object::recv_msg, UBUS_ACL_ACCESS, UBUS_ATTR_DATA, UBUS_ATTR_METHOD, UBUS_ATTR_OBJID, ubus_find_id(), UBUS_STATUS_INVALID_ARGUMENT, UBUS_STATUS_NOT_FOUND, UBUS_STATUS_PERMISSION_DENIED, ubusd_acl_check(), and ubusd_forward_invoke().
ubusd_handle_lookup()
static int ubusd_handle_lookup (struct ubus_client * cl, struct ubus_msg_buf * ub, struct blob_attr ** attr) static
Definition at line 273 of file ubusd_proto.c.
{
    int rc;
    if (list_empty(&cl->tx_queue))
        rc = __ubusd_handle_lookup(cl, ub, attr, NULL);
    else
        rc = ubus_client_cmd_queue_add(cl, ub, NULL);
    return rc;
}
References __ubusd_handle_lookup(), list_empty(), rc(), ubus_client::tx_queue, and ubus_client_cmd_queue_add().
ubusd_handle_notify()
static int ubusd_handle_notify (struct ubus_client * cl, struct ubus_msg_buf * ub, struct blob_attr ** attr) static
Definition at line 355 of file ubusd_proto.c.
{
    struct ubus_object *obj = NULL;
    struct ubus_subscription *s;
    struct ubus_id *id;
    const char *method;
    bool no_reply = false;
    void *c;
    if (!attr[UBUS_ATTR_METHOD] || !attr[UBUS_ATTR_OBJID])
        return UBUS_STATUS_INVALID_ARGUMENT;
    if (attr[UBUS_ATTR_NO_REPLY])
        no_reply = blob_get_int8(attr[UBUS_ATTR_NO_REPLY]);
    id = ubus_find_id(&objects, blob_get_u32(attr[UBUS_ATTR_OBJID]));
    if (!id)
        return UBUS_STATUS_NOT_FOUND;
    obj = container_of(id, struct ubus_object, id);
    if (obj->client != cl)
        return UBUS_STATUS_PERMISSION_DENIED;
    if (!no_reply) {
        blob_buf_init(&b, 0);
        blob_put_int32(&b, UBUS_ATTR_OBJID, id->id);
        c = blob_nest_start(&b, UBUS_ATTR_SUBSCRIBERS);
        list_for_each_entry(s, &obj->subscribers, list) {
            blob_put_int32(&b, 0, s->subscriber->id.id);
        }
        blob_nest_end(&b, c);
        blob_put_int32(&b, UBUS_ATTR_STATUS, 0);
        ubus_proto_send_msg_from_blob(cl, ub, UBUS_MSG_STATUS);
    }
    ub->hdr.peer = cl->id.id;
    method = blob_data(attr[UBUS_ATTR_METHOD]);
    list_for_each_entry(s, &obj->subscribers, list) {
        blob_buf_init(&b, 0);
        if (no_reply)
            blob_put_int8(&b, UBUS_ATTR_NO_REPLY, 1);
        ubusd_forward_invoke(cl, s->subscriber, method, ub, attr[UBUS_ATTR_DATA]);
    }
    return -1;
}
References b, blob_buf_init(), blob_data(), blob_get_int8(), blob_get_u32(), blob_nest_end(), blob_nest_start(), blob_put_int32, blob_put_int8, ubus_object::client, container_of, ubus_msg_buf::hdr, id, ubus_client::id, ubus_id::id, ubus_object::id, list_for_each_entry, objects, ubus_msghdr::peer, ubus_subscription::subscriber, UBUS_ATTR_DATA, UBUS_ATTR_METHOD, UBUS_ATTR_NO_REPLY, UBUS_ATTR_OBJID, UBUS_ATTR_STATUS, UBUS_ATTR_SUBSCRIBERS, ubus_find_id(), UBUS_MSG_STATUS, ubus_proto_send_msg_from_blob(), UBUS_STATUS_INVALID_ARGUMENT, UBUS_STATUS_NOT_FOUND, UBUS_STATUS_PERMISSION_DENIED, and ubusd_forward_invoke().
ubusd_handle_remove_object()
static int ubusd_handle_remove_object (struct ubus_client * cl, struct ubus_msg_buf * ub, struct blob_attr ** attr) static
Definition at line 116 of file ubusd_proto.c.
{
    struct ubus_object *obj;
    if (!attr[UBUS_ATTR_OBJID])
        return UBUS_STATUS_INVALID_ARGUMENT;
    obj = ubusd_find_object(blob_get_u32(attr[UBUS_ATTR_OBJID]));
    if (!obj)
        return UBUS_STATUS_NOT_FOUND;
    if (obj->client != cl)
        return UBUS_STATUS_PERMISSION_DENIED;
    blob_buf_init(&b, 0);
    blob_put_int32(&b, UBUS_ATTR_OBJID, obj->id.id);
    /* check if we're removing the object type as well */
    if (obj->type && obj->type->refcount == 1)
        blob_put_int32(&b, UBUS_ATTR_OBJTYPE, obj->type->id.id);
    ubus_proto_send_msg_from_blob(cl, ub, UBUS_MSG_DATA);
    ubusd_free_object(obj);
    return 0;
}
References b, blob_buf_init(), blob_get_u32(), blob_put_int32, ubus_object::client, ubus_object::id, ubus_object_type::id, ubus_object_type::refcount, ubus_object::type, UBUS_ATTR_OBJID, UBUS_ATTR_OBJTYPE, UBUS_MSG_DATA, ubus_proto_send_msg_from_blob(), UBUS_STATUS_INVALID_ARGUMENT, UBUS_STATUS_NOT_FOUND, UBUS_STATUS_PERMISSION_DENIED, ubusd_find_object(), and ubusd_free_object().
ubusd_handle_remove_watch()
static int ubusd_handle_remove_watch (struct ubus_client * cl, struct ubus_msg_buf * ub, struct blob_attr ** attr) static
Definition at line 471 of file ubusd_proto.c.
{
    struct ubus_object *obj;
    struct ubus_subscription *s;
    uint32_t id;
    if (!attr[UBUS_ATTR_OBJID] || !attr[UBUS_ATTR_TARGET])
        return UBUS_STATUS_INVALID_ARGUMENT;
    obj = ubusd_find_object(blob_get_u32(attr[UBUS_ATTR_OBJID]));
    if (!obj)
        return UBUS_STATUS_NOT_FOUND;
    if (cl != obj->client)
        return UBUS_STATUS_INVALID_ARGUMENT;
    id = blob_get_u32(attr[UBUS_ATTR_TARGET]);
    list_for_each_entry(s, &obj->target_list, target_list) {
        if (s->target->id.id != id)
            continue;
        ubus_unsubscribe(s);
        return 0;
    }
    return UBUS_STATUS_NOT_FOUND;
}
References blob_get_u32(), ubus_object::client, id, ubus_object::id, list_for_each_entry, ubus_subscription::target, ubus_object::target_list, ubus_subscription::target_list, UBUS_ATTR_OBJID, UBUS_ATTR_TARGET, UBUS_STATUS_INVALID_ARGUMENT, UBUS_STATUS_NOT_FOUND, ubus_unsubscribe(), and ubusd_find_object().
ubusd_handle_response()
static int ubusd_handle_response (struct ubus_client * cl, struct ubus_msg_buf * ub, struct blob_attr ** attr) static
Definition at line 413 of file ubusd_proto.c.
{
    struct ubus_object *obj;
    if (!attr[UBUS_ATTR_OBJID] ||
        (ub->hdr.type == UBUS_MSG_STATUS && !attr[UBUS_ATTR_STATUS]) ||
        (ub->hdr.type == UBUS_MSG_DATA && !attr[UBUS_ATTR_DATA]))
        goto out;
    obj = ubusd_find_object(blob_get_u32(attr[UBUS_ATTR_OBJID]));
    if (!obj)
        goto out;
    if (cl != obj->client)
        goto out;
    cl = ubusd_get_client_by_id(ub->hdr.peer);
    if (!cl)
        goto out;
    ub->hdr.peer = blob_get_u32(attr[UBUS_ATTR_OBJID]);
    ubus_msg_send(cl, ub);
out:
    return -1;
}
References blob_get_u32(), ubus_object::client, ubus_msg_buf::hdr, ubus_msghdr::peer, ubus_msghdr::type, UBUS_ATTR_DATA, UBUS_ATTR_OBJID, UBUS_ATTR_STATUS, UBUS_MSG_DATA, ubus_msg_send(), UBUS_MSG_STATUS, ubusd_find_object(), and ubusd_get_client_by_id().
ubusd_proto_free_client()
void ubusd_proto_free_client (struct ubus_client * cl)
Definition at line 600 of file ubusd_proto.c.
{
    struct ubus_object *obj, *tmp;
    list_for_each_entry_safe(obj, tmp, &cl->objects, list) {
        ubusd_free_object(obj);
    }
    ubus_msg_free(cl->retmsg);
    blob_buf_free(&cl->b);
    ubusd_acl_free_client(cl);
    ubus_free_id(&clients, &cl->id);
}
References ubus_client::b, blob_buf_free(), clients, ubus_client::id, ubus_object::list, list_for_each_entry_safe, ubus_client::objects, ubus_client::retmsg, ubus_free_id(), ubus_msg_free(), ubusd_acl_free_client(), and ubusd_free_object().
Referenced by handle_client_disconnect().
ubusd_proto_init()
static void __constructor ubusd_proto_init (void) static
Definition at line 651 of file ubusd_proto.c.
{
    ubus_init_id_tree(&clients);
}
References clients, and ubus_init_id_tree().
ubusd_proto_init_retmsg()
static int ubusd_proto_init_retmsg (struct ubus_client * cl) static
Definition at line 548 of file ubusd_proto.c.
{
    struct blob_buf *b = &cl->b;
    blob_buf_init(&cl->b, 0);
    blob_put_int32(&cl->b, UBUS_ATTR_STATUS, 0);
    /* we make the 'retmsg' buffer shared with the blob_buf b, to reduce mem duplication */
    cl->retmsg = ubus_msg_new(b->head, blob_raw_len(b->head), true);
    if (!cl->retmsg)
        return -1;
    cl->retmsg->hdr.type = UBUS_MSG_STATUS;
    return 0;
}
References b, ubus_client::b, blob_buf_init(), blob_put_int32, blob_raw_len(), ubus_msg_buf::hdr, blob_buf::head, ubus_client::retmsg, ubus_msghdr::type, UBUS_ATTR_STATUS, ubus_msg_new(), and UBUS_MSG_STATUS.
Referenced by ubusd_proto_new_client().
ubusd_proto_new_client()
struct ubus_client * ubusd_proto_new_client (int fd, uloop_fd_handler cb)
Definition at line 564 of file ubusd_proto.c.
{
    struct ubus_client *cl;
    cl = calloc(1, sizeof(*cl));
    if (!cl)
        return NULL;
    if (ubusd_acl_init_client(cl, fd))
        goto free;
    INIT_LIST_HEAD(&cl->objects);
    INIT_LIST_HEAD(&cl->cmd_queue);
    INIT_LIST_HEAD(&cl->tx_queue);
    cl->sock.fd = fd;
    cl->sock.cb = cb;
    cl->pending_msg_fd = -1;
    if (!ubus_alloc_id(&clients, &cl->id, 0))
        goto free;
    if (ubusd_proto_init_retmsg(cl))
        goto free;
    if (!ubusd_send_hello(cl))
        goto delete;
    return cl;
delete:
    ubus_free_id(&clients, &cl->id);
free:
    free(cl);
    return NULL;
}
References uloop_fd::cb, clients, ubus_client::cmd_queue, uloop_fd::fd, ubus_client::id, INIT_LIST_HEAD(), ubus_client::objects, ubus_client::pending_msg_fd, ubus_client::sock, ubus_client::tx_queue, ubus_alloc_id(), ubus_free_id(), ubusd_acl_init_client(), ubusd_proto_init_retmsg(), and ubusd_send_hello().
Referenced by get_next_connection().
ubusd_proto_receive_message()
void ubusd_proto_receive_message (struct ubus_client * cl, struct ubus_msg_buf * ub)
Definition at line 512 of file ubusd_proto.c.
{
    ubus_cmd_cb cb = NULL;
    int ret;
    struct ubus_msg_buf *retmsg = cl->retmsg;
    int *retmsg_data = blob_data(blob_data(retmsg->data));
    retmsg->hdr.seq = ub->hdr.seq;
    retmsg->hdr.peer = ub->hdr.peer;
    if (ub->hdr.type < __UBUS_MSG_LAST)
        cb = handlers[ub->hdr.type];
    if (ub->hdr.type != UBUS_MSG_STATUS && ub->hdr.type != UBUS_MSG_INVOKE)
        ubus_msg_close_fd(ub);
    /* Note: no callback should free the `ub` buffer
             that's always done right after the callback finishes */
    if (cb)
        ret = cb(cl, ub, ubus_parse_msg(ub->data, blob_raw_len(ub->data)));
    else
        ret = UBUS_STATUS_INVALID_COMMAND;
    /* Command has not been completed yet and got queued */
    if (ret == -2)
        return;
    ubus_msg_free(ub);
    if (ret == -1)
        return;
    *retmsg_data = htonl(ret);
    ubus_msg_send(cl, retmsg);
}
References __UBUS_MSG_LAST, blob_data(), blob_raw_len(), ubus_msg_buf::data, handlers, ubus_msg_buf::hdr, ubus_msghdr::peer, ubus_client::retmsg, ubus_msghdr::seq, ubus_msghdr::type, ubus_msg_close_fd(), ubus_msg_free(), UBUS_MSG_INVOKE, ubus_msg_send(), UBUS_MSG_STATUS, ubus_parse_msg(), and UBUS_STATUS_INVALID_COMMAND.
Referenced by client_cb().
ubusd_send_hello()
static bool ubusd_send_hello (struct ubus_client * cl) static
Definition at line 94 of file ubusd_proto.c.
{
    struct ubus_msg_buf *ub;
    blob_buf_init(&b, 0);
    ub = ubus_msg_from_blob(true);
    if (!ub)
        return false;
    ubus_msg_init(ub, UBUS_MSG_HELLO, 0, cl->id.id);
    ubus_msg_send(cl, ub);
    ubus_msg_free(ub);
    return true;
}
References b, blob_buf_init(), ubus_client::id, ubus_id::id, ubus_msg_free(), ubus_msg_from_blob(), UBUS_MSG_HELLO, ubus_msg_init(), and ubus_msg_send().
Referenced by ubusd_proto_new_client().
ubusd_send_obj()
static void ubusd_send_obj (struct ubus_client * cl, struct ubus_msg_buf * ub, struct ubus_object * obj) static
Definition at line 160 of file ubusd_proto.c.
{
    struct ubus_method *m;
    int all_cnt = 0, cnt = 0;
    void *s;
    if (!obj->type)
        return;
    blob_buf_init(&b, 0);
    blob_put_string(&b, UBUS_ATTR_OBJPATH, obj->path.key);
    blob_put_int32(&b, UBUS_ATTR_OBJID, obj->id.id);
    blob_put_int32(&b, UBUS_ATTR_OBJTYPE, obj->type->id.id);
    s = blob_nest_start(&b, UBUS_ATTR_SIGNATURE);
    list_for_each_entry(m, &obj->type->methods, list) {
        all_cnt++;
        if (!ubusd_acl_check(cl, obj->path.key, blobmsg_name(m->data), UBUS_ACL_ACCESS)) {
            blobmsg_add_blob(&b, m->data);
            cnt++;
        }
    }
    blob_nest_end(&b, s);
    if (cnt || !all_cnt)
        ubus_proto_send_msg_from_blob(cl, ub, UBUS_MSG_DATA);
}
References b, blob_buf_init(), blob_nest_end(), blob_nest_start(), blob_put_int32, blob_put_string(), blobmsg_add_blob(), blobmsg_name(), ubus_method::data, ubus_object::id, ubus_object_type::id, ubus_method::list, list_for_each_entry, ubus_object_type::methods, ubus_object::path, ubus_object::type, UBUS_ACL_ACCESS, UBUS_ATTR_OBJID, UBUS_ATTR_OBJPATH, UBUS_ATTR_OBJTYPE, UBUS_ATTR_SIGNATURE, UBUS_MSG_DATA, ubus_proto_send_msg_from_blob(), and ubusd_acl_check().
Referenced by __ubusd_handle_lookup().
ubusd_send_pong()
static int ubusd_send_pong (struct ubus_client * cl, struct ubus_msg_buf * ub, struct blob_attr ** attr) static
Definition at line 109 of file ubusd_proto.c.
{
    ub->hdr.type = UBUS_MSG_DATA;
    ubus_msg_send(cl, ub);
    return 0;
}
References ubus_msg_buf::hdr, ubus_msghdr::type, UBUS_MSG_DATA, and ubus_msg_send().
Variable Documentation
attrbuf
struct blob_attr* attrbuf[UBUS_ATTR_MAX] static
Definition at line 22 of file ubusd_proto.c.
Referenced by ubus_parse_msg().
b
struct blob_buf b
Definition at line 19 of file ubusd_proto.c.
Referenced by ubus_msg_from_blob(), ubus_notify_subscription(), ubus_notify_unsubscribe(), ubusd_forward_invoke(), ubusd_handle_add_object(), ubusd_handle_invoke(), ubusd_handle_notify(), ubusd_handle_remove_object(), ubusd_proto_init_retmsg(), ubusd_send_hello(), and ubusd_send_obj().
clients
struct avl_tree clients static
Definition at line 20 of file ubusd_proto.c.
Referenced by ubusd_get_client_by_id(), ubusd_proto_free_client(), ubusd_proto_init(), and ubusd_proto_new_client().
handlers
const ubus_cmd_cb handlers[__UBUS_MSG_LAST] static
Initial value:
= {
    [UBUS_MSG_PING] = ubusd_send_pong,
    [UBUS_MSG_ADD_OBJECT] = ubusd_handle_add_object,
    [UBUS_MSG_REMOVE_OBJECT] = ubusd_handle_remove_object,
    [UBUS_MSG_LOOKUP] = ubusd_handle_lookup,
    [UBUS_MSG_INVOKE] = ubusd_handle_invoke,
    [UBUS_MSG_STATUS] = ubusd_handle_response,
    [UBUS_MSG_DATA] = ubusd_handle_response,
    [UBUS_MSG_SUBSCRIBE] = ubusd_handle_add_watch,
    [UBUS_MSG_UNSUBSCRIBE] = ubusd_handle_remove_watch,
    [UBUS_MSG_NOTIFY] = ubusd_handle_notify,
}
Definition at line 499 of file ubusd_proto.c.
{
    [UBUS_MSG_PING] = ubusd_send_pong,
    [UBUS_MSG_ADD_OBJECT] = ubusd_handle_add_object,
    [UBUS_MSG_REMOVE_OBJECT] = ubusd_handle_remove_object,
    [UBUS_MSG_LOOKUP] = ubusd_handle_lookup,
    [UBUS_MSG_INVOKE] = ubusd_handle_invoke,
    [UBUS_MSG_STATUS] = ubusd_handle_response,
    [UBUS_MSG_DATA] = ubusd_handle_response,
    [UBUS_MSG_SUBSCRIBE] = ubusd_handle_add_watch,
    [UBUS_MSG_UNSUBSCRIBE] = ubusd_handle_remove_watch,
    [UBUS_MSG_NOTIFY] = ubusd_handle_notify,
};
Referenced by ubusd_proto_receive_message().
ubus_policy
const struct blob_attr_info ubus_policy[UBUS_ATTR_MAX] static
Initial value:
= {
    [UBUS_ATTR_SIGNATURE] = { .type = BLOB_ATTR_NESTED },
    [UBUS_ATTR_OBJTYPE] = { .type = BLOB_ATTR_INT32 },
    [UBUS_ATTR_OBJPATH] = { .type = BLOB_ATTR_STRING },
    [UBUS_ATTR_OBJID] = { .type = BLOB_ATTR_INT32 },
    [UBUS_ATTR_STATUS] = { .type = BLOB_ATTR_INT32 },
    [UBUS_ATTR_METHOD] = { .type = BLOB_ATTR_STRING },
    [UBUS_ATTR_USER] = { .type = BLOB_ATTR_STRING },
    [UBUS_ATTR_GROUP] = { .type = BLOB_ATTR_STRING },
}
Definition at line 26 of file ubusd_proto.c.
{
    [UBUS_ATTR_SIGNATURE] = { .type = BLOB_ATTR_NESTED },
    [UBUS_ATTR_OBJTYPE] = { .type = BLOB_ATTR_INT32 },
    [UBUS_ATTR_OBJPATH] = { .type = BLOB_ATTR_STRING },
    [UBUS_ATTR_OBJID] = { .type = BLOB_ATTR_INT32 },
    [UBUS_ATTR_STATUS] = { .type = BLOB_ATTR_INT32 },
    [UBUS_ATTR_METHOD] = { .type = BLOB_ATTR_STRING },
    [UBUS_ATTR_USER] = { .type = BLOB_ATTR_STRING },
    [UBUS_ATTR_GROUP] = { .type = BLOB_ATTR_STRING },
};
Referenced by ubus_parse_msg().