zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/ustp/bridge_track.c File Reference
bridge_track.c File Reference
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <linux/param.h>
#include <netinet/in.h>
#include <linux/if_bridge.h>
#include <asm/byteorder.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <net/if.h>
#include <dirent.h>
#include "bridge_ctl.h"
#include "bridge_track.h"
#include "netif_utils.h"
#include "packet.h"
#include "log.h"
#include "mstp.h"
#include "driver.h"
#include "libnetlink.h"
Classes
struct llc_header
Macros
#define _GNU_SOURCE
#define SYSFS_CLASS_NET "/sys/class/net"
#define LLC_PDU_LEN_U 3 /* header and 1 control byte */
#define LLC_PDU_TYPE_U 3 /* first two bits */
#define LLC_SAP_BSPAN 0x42
Functions
static LIST_HEAD (bridges)
static bridge_t * create_br (int if_index)
static bridge_t * find_br (int if_index)
static port_t * create_if (bridge_t *br, int if_index)
static port_t * find_if (bridge_t *br, int if_index)
static void delete_if (port_t *prt)
static bool delete_if_byindex (bridge_t *br, int if_index)
static bool delete_br_byindex (int if_index)
void bridge_one_second (void)
static bool check_mac_address (char *name, __u8 *addr)
static void set_br_up (bridge_t *br, bool up)
static void set_if_up (port_t *prt, bool up)
int bridge_notify (int br_index, int if_index, bool newlink, unsigned flags)
struct llc_header __attribute__ ((packed))
void bridge_bpdu_rcv (int if_index, const unsigned char *data, int len)
static int br_set_state (struct rtnl_handle *rth, unsigned ifindex, __u8 state)
static int br_flush_port (char *ifname)
static int br_set_ageing_time (char *brname, unsigned int ageing_time)
void MSTP_OUT_set_state (per_tree_port_t *ptp, int new_state)
void MSTP_OUT_flush_all_fids (per_tree_port_t *ptp)
void MSTP_OUT_set_ageing_time (port_t *prt, unsigned int ageingTime)
void MSTP_OUT_tx_bpdu (port_t *prt, bpdu_t *bpdu, int size)
void MSTP_OUT_shutdown_port (port_t *prt)
static int not_dot_dotdot (const struct dirent *entry)
static int get_port_list (const char *br_ifname, struct dirent ***namelist)
int bridge_create (int bridge_idx, CIST_BridgeConfig *cfg)
void bridge_delete (int index)
int bridge_track_fini (void)
Variables
__u8 dest_addr [ETH_ALEN]
__u8 src_addr [ETH_ALEN]
__be16 len8023
__u8 d_sap
__u8 s_sap
__u8 llc_ctrl
static const __u8 bridge_group_address [ETH_ALEN]
Class Documentation
llc_header
struct llc_header
Definition at line 365 of file bridge_track.c.
Class Members
__u8 d_sap
__u8 dest_addr[ETH_ALEN]
__be16 len8023
__u8 llc_ctrl
__u8 s_sap
__u8 src_addr[ETH_ALEN]
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 26 of file bridge_track.c.
LLC_PDU_LEN_U
#define LLC_PDU_LEN_U 3 /* header and 1 control byte */
Definition at line 376 of file bridge_track.c.
Referenced by bridge_bpdu_rcv(), and MSTP_OUT_tx_bpdu().
LLC_PDU_TYPE_U
#define LLC_PDU_TYPE_U 3 /* first two bits */
Definition at line 377 of file bridge_track.c.
Referenced by bridge_bpdu_rcv(), and MSTP_OUT_tx_bpdu().
LLC_SAP_BSPAN
#define LLC_SAP_BSPAN 0x42
Definition at line 380 of file bridge_track.c.
Referenced by bridge_bpdu_rcv(), and MSTP_OUT_tx_bpdu().
SYSFS_CLASS_NET
#define SYSFS_CLASS_NET "/sys/class/net"
Definition at line 49 of file bridge_track.c.
Referenced by br_flush_port(), br_set_ageing_time(), and get_port_list().
Function Documentation
__attribute__()
struct llc_header __attribute__ ((packed))
References create_if(), delete_br_byindex(), delete_if(), delete_if_byindex(), ERROR, find_br(), find_if(), get_flags(), INFO, list_for_each_entry, LOG, sysdep_br_data_t::name, set_br_up(), set_if_up(), and bridge_t::sysdeps.
br_flush_port()
static int br_flush_port (char * ifname) static
Definition at line 450 of file bridge_track.c.
{
    char fname[128];
    snprintf(fname, sizeof(fname), SYSFS_CLASS_NET "/%s/brport/flush", ifname);
    int fd = open(fname, O_WRONLY);
    TSTM(0 <= fd, -1, "Couldn't open flush file %s for write: %m", fname);
    int write_result = write(fd, "1", 1);
    close(fd);
    TST(1 == write_result, -1);
    return 0;
}
References ifname, SYSFS_CLASS_NET, TST, and TSTM.
Referenced by MSTP_OUT_flush_all_fids().
br_set_ageing_time()
static int br_set_ageing_time (char * brname, unsigned int ageing_time) static
Definition at line 462 of file bridge_track.c.
{
    char fname[128], str_time[32];
    snprintf(fname, sizeof(fname), SYSFS_CLASS_NET "/%s/bridge/ageing_time",
             brname);
    int fd = open(fname, O_WRONLY);
    TSTM(0 <= fd, -1, "Couldn't open file %s for write: %m", fname);
    int len = sprintf(str_time, "%u", ageing_time * HZ);
    int write_result = write(fd, str_time, len);
    close(fd);
    TST(len == write_result, -1);
    return 0;
}
References SYSFS_CLASS_NET, TST, and TSTM.
Referenced by MSTP_OUT_set_ageing_time().
br_set_state()
static int br_set_state (struct rtnl_handle * rth, unsigned ifindex, __u8 state) static
Definition at line 428 of file bridge_track.c.
{
    struct
    {
        struct nlmsghdr n;
        struct ifinfomsg ifi;
        char buf[256];
    } req;
    memset(&req, 0, sizeof(req));
    req.n.nlmsg_len = NLMSG_LENGTH(sizeof(struct ifinfomsg));
    req.n.nlmsg_flags = NLM_F_REQUEST | NLM_F_REPLACE;
    req.n.nlmsg_type = RTM_SETLINK;
    req.ifi.ifi_family = AF_BRIDGE;
    req.ifi.ifi_index = ifindex;
    addattr8(&req.n, sizeof(req.buf), IFLA_PROTINFO, state);
    return rtnl_talk(rth, &req.n, 0, 0, NULL, NULL, NULL);
}
References addattr8(), buf, rth, rtnl_talk(), and state.
Referenced by MSTP_OUT_set_state().
bridge_bpdu_rcv()
void bridge_bpdu_rcv (int if_index, const unsigned char * data, int len)
Definition at line 386 of file bridge_track.c.
{
    port_t *prt = NULL;
    bridge_t *br;
    LOG("ifindex %d, len %d", if_index, len);
    list_for_each_entry(br, &bridges, list)
    {
        if((prt = find_if(br, if_index)))
            break;
    }
    if(!prt)
        return;
    /* sanity checks */
    TSTM(br == prt->bridge,, "Bridge mismatch. This bridge is '%s' but port "
        "'%s' belongs to bridge '%s'", br->sysdeps.name, prt->bridge->sysdeps.name);
    TSTM(prt->sysdeps.up,, "Port '%s' should be up", prt->sysdeps.name);
    /* Validate Ethernet and LLC header,
     * maybe we can skip this check thanks to Berkeley filter in packet socket?
     */
    struct llc_header *h;
    unsigned int l;
    TST(len > sizeof(struct llc_header),);
    h = (struct llc_header *)data;
    TST(0 == memcmp(h->dest_addr, bridge_group_address, ETH_ALEN),
             INFO("ifindex %d, len %d, %02hhX%02hhX%02hhX%02hhX%02hhX%02hhX",
                  if_index, len,
                  h->dest_addr[0], h->dest_addr[1], h->dest_addr[2],
                  h->dest_addr[3], h->dest_addr[4], h->dest_addr[5])
       );
    l = __be16_to_cpu(h->len8023);
    TST(l <= ETH_DATA_LEN && l <= len - ETH_HLEN && l >= LLC_PDU_LEN_U, );
    TST(h->d_sap == LLC_SAP_BSPAN && h->s_sap == LLC_SAP_BSPAN && (h->llc_ctrl & 0x3) == LLC_PDU_TYPE_U,);
    MSTP_IN_rx_bpdu(prt,
                    /* Don't include LLC header */
                    (bpdu_t *)(data + sizeof(*h)), l - LLC_PDU_LEN_U);
}
References port_t::bridge, bridge_group_address, llc_header::d_sap, llc_header::dest_addr, find_if(), INFO, llc_header::len8023, list_for_each_entry, llc_header::llc_ctrl, LLC_PDU_LEN_U, LLC_PDU_TYPE_U, LLC_SAP_BSPAN, LOG, MSTP_IN_rx_bpdu(), sysdep_br_data_t::name, sysdep_if_data_t::name, llc_header::s_sap, bridge_t::sysdeps, port_t::sysdeps, TST, TSTM, and sysdep_if_data_t::up.
Referenced by packet_rcv().
bridge_create()
int bridge_create (int bridge_idx, CIST_BridgeConfig * cfg)
Definition at line 645 of file bridge_track.c.
{
    struct dirent **namelist;
    int *port_list, n_ports;
    bridge_t *br, *other_br;
    port_t *port, *tmp;
    int flags;
    bool found;
    int i;
    br = find_br(bridge_idx);
    if (!br)
        br = create_br(bridge_idx);
    if (!br)
        return -1;
    MSTP_IN_set_cist_bridge_config(br, cfg);
    flags = get_flags(br->sysdeps.name);
    if (flags >= 0)
        set_br_up(br, !!(flags & IFF_UP));
    n_ports = get_port_list(br->sysdeps.name, &namelist);
    port_list = alloca(n_ports * sizeof(*port_list));
    for (i = 0; i < n_ports; i++) {
        port_list[i] = if_nametoindex(namelist[i]->d_name);
        free(namelist[i]);
    }
    free(namelist);
    list_for_each_entry_safe(port, tmp, &br->ports, br_list) {
        found = false;
        for (i = 0; i < n_ports; i++) {
            if (port->sysdeps.if_index != port_list[i])
                continue;
            found = true;
            break;
        }
        if (found)
            continue;
        delete_if(port);
    }
    for (i = 0; i < n_ports; i++) {
        port = find_if(br, port_list[i]);
        if (port)
            continue;
        list_for_each_entry(other_br, &bridges, list) {
            if (br == other_br)
                continue;
            delete_if_byindex(other_br, port_list[i]);
        }
        port = find_if(br, port_list[i]);
        if (!port)
            port = create_if(br, port_list[i]);
        if (!port)
            continue;
        flags = get_flags(port->sysdeps.name);
        if (flags < 0)
            continue;
        set_if_up(port, !(~flags & (IFF_UP | IFF_RUNNING)));
    }
    return 0;
}
References create_br(), create_if(), delete_if(), delete_if_byindex(), find_br(), find_if(), get_flags(), get_port_list(), list_for_each_entry, list_for_each_entry_safe, MSTP_IN_set_cist_bridge_config(), sysdep_br_data_t::name, port, bridge_t::ports, set_br_up(), set_if_up(), and bridge_t::sysdeps.
bridge_delete()
void bridge_delete (int index)
Definition at line 719 of file bridge_track.c.
{
    delete_br_byindex(index);
}
References delete_br_byindex().
Referenced by handle_worker_event().
bridge_notify()
int bridge_notify (int br_index, int if_index, bool newlink, unsigned flags)
Definition at line 282 of file bridge_track.c.
{
    port_t *prt;
    bridge_t *br = NULL, *other_br;
    bool up = !!(flags & IFF_UP);
    bool running = up && (flags & IFF_RUNNING);
    LOG("br_index %d, if_index %d, newlink %d, up %d, running %d",
        br_index, if_index, newlink, up, running);
    if((br_index >= 0) && (br_index != if_index))
    {
        if(!(br = find_br(br_index)))
            return -2; /* bridge not in list */
        int br_flags = get_flags(br->sysdeps.name);
        if(br_flags >= 0)
            set_br_up(br, !!(br_flags & IFF_UP));
    }
    if(br)
    {
        if(!(prt = find_if(br, if_index)))
        {
            if(!newlink)
            {
                INFO("Got DELLINK for unknown port %d on "
                     "bridge %d", if_index, br_index);
                return -1;
            }
            /* Check if this interface is slave of another bridge */
            list_for_each_entry(other_br, &bridges, list)
            {
                if(other_br != br)
                    if(delete_if_byindex(other_br, if_index))
                    {
                        INFO("Device %d has come to bridge %d. "
                             "Missed notify for deletion from bridge %d",
                             if_index, br_index, other_br->sysdeps.if_index);
                        break;
                    }
            }
            prt = create_if(br, if_index);
        }
        if(!prt)
        {
            ERROR("Couldn't create data for interface %d (master %d)",
                  if_index, br_index);
            return -1;
        }
        if(!newlink)
        {
            delete_if(prt);
            return 0;
        }
        set_if_up(prt, running); /* And speed and duplex */
    }
    else
    { /* Interface is not a bridge slave */
        if(!newlink)
        {
            /* DELLINK not from bridge means interface unregistered. */
            /* Cleanup removed bridge or removed bridge slave */
            if(!delete_br_byindex(if_index))
                list_for_each_entry(br, &bridges, list)
                {
                    if(delete_if_byindex(br, if_index))
                        break;
                }
            return 0;
        }
        else
        { /* This may be a new link */
            if(br_index == if_index)
            {
                if(!(br = find_br(br_index)))
                    return -2; /* bridge not in list */
                set_br_up(br, up);
            }
        }
    }
    return 0;
}
Referenced by dump_msg().
bridge_one_second()
void bridge_one_second (void)
Definition at line 164 of file bridge_track.c.
{
    bridge_t *br;
    list_for_each_entry(br, &bridges, list)
        MSTP_IN_one_second(br);
}
References list_for_each_entry, and MSTP_IN_one_second().
Referenced by handle_worker_event().
bridge_track_fini()
int bridge_track_fini (void)
Definition at line 724 of file bridge_track.c.
{
    INFO("Stopping all bridges");
    bridge_t *br;
    list_for_each_entry(br, &bridges, list)
    {
        set_br_up(br, false);
    }
    return 0;
}
References INFO, list_for_each_entry, and set_br_up().
Referenced by main().
check_mac_address()
static bool check_mac_address (char * name, __u8 * addr) static
Definition at line 173 of file bridge_track.c.
{
    __u8 temp_addr[ETH_ALEN];
    if(get_hwaddr(name, temp_addr))
    {
        LOG("Error getting hw address: %s", name);
        /* Error. Ignore the new value */
        return false;
    }
    if(memcmp(addr, temp_addr, sizeof(temp_addr)) == 0)
        return false;
    else
    {
        memcpy(addr, temp_addr, sizeof(temp_addr));
        return true;
    }
}
References get_hwaddr(), and LOG.
Referenced by set_br_up(), and set_if_up().
create_br()
static bridge_t * create_br (int if_index) static
Definition at line 54 of file bridge_track.c.
{
    bridge_t *br;
    TST((br = calloc(1, sizeof(*br))) != NULL, NULL);
    /* Init system dependent info */
    br->sysdeps.if_index = if_index;
    if (!if_indextoname(if_index, br->sysdeps.name))
        goto err;
    if (get_hwaddr(br->sysdeps.name, br->sysdeps.macaddr))
        goto err;
    INFO("Add bridge %s", br->sysdeps.name);
    if(!MSTP_IN_bridge_create(br, br->sysdeps.macaddr))
        goto err;
    list_add_tail(&br->list, &bridges);
    return br;
err:
    free(br);
    return NULL;
}
References err, get_hwaddr(), sysdep_br_data_t::if_index, INFO, bridge_t::list, list_add_tail(), sysdep_br_data_t::macaddr, MSTP_IN_bridge_create(), sysdep_br_data_t::name, bridge_t::sysdeps, and TST.
Referenced by bridge_create().
create_if()
static port_t * create_if (bridge_t * br, int if_index) static
Definition at line 88 of file bridge_track.c.
{
    port_t *prt;
    TST((prt = calloc(1, sizeof(*prt))) != NULL, NULL);
    /* Init system dependent info */
    prt->sysdeps.if_index = if_index;
    if (!if_indextoname(if_index, prt->sysdeps.name))
        goto err;
    if (get_hwaddr(prt->sysdeps.name, prt->sysdeps.macaddr))
        goto err;
    int portno;
    if(0 > (portno = get_bridge_portno(prt->sysdeps.name)))
    {
        ERROR("Couldn't get port number for %s", prt->sysdeps.name);
        goto err;
    }
    if((0 == portno) || (portno > MAX_PORT_NUMBER))
    {
        ERROR("Port number for %s is invalid (%d)", prt->sysdeps.name, portno);
        goto err;
    }
    INFO("Add iface %s as port#%d to bridge %s", prt->sysdeps.name,
         portno, br->sysdeps.name);
    prt->bridge = br;
    if(!MSTP_IN_port_create_and_add_tail(prt, portno))
        goto err;
    return prt;
err:
    free(prt);
    return NULL;
}
References port_t::bridge, err, ERROR, get_bridge_portno(), get_hwaddr(), sysdep_if_data_t::if_index, INFO, sysdep_if_data_t::macaddr, MAX_PORT_NUMBER, MSTP_IN_port_create_and_add_tail(), sysdep_br_data_t::name, sysdep_if_data_t::name, bridge_t::sysdeps, port_t::sysdeps, and TST.
Referenced by __attribute__(), and bridge_create().
delete_br_byindex()
static bool delete_br_byindex (int if_index) static
Definition at line 150 of file bridge_track.c.
{
    bridge_t *br;
    if(!(br = find_br(if_index)))
        return false;
    INFO("Delete bridge %s (%d)", br->sysdeps.name, if_index);
    list_del(&br->list);
    MSTP_IN_delete_bridge(br);
    free(br);
    return true;
}
References find_br(), INFO, bridge_t::list, list_del(), MSTP_IN_delete_bridge(), sysdep_br_data_t::name, and bridge_t::sysdeps.
Referenced by __attribute__(), and bridge_delete().
delete_if()
static void delete_if (port_t * prt) inline static
Definition at line 135 of file bridge_track.c.
{
    MSTP_IN_delete_port(prt);
    free(prt);
}
References MSTP_IN_delete_port().
Referenced by __attribute__(), bridge_create(), and delete_if_byindex().
delete_if_byindex()
static bool delete_if_byindex (bridge_t * br, int if_index) inline static
Definition at line 141 of file bridge_track.c.
{
    port_t *prt;
    if(!(prt = find_if(br, if_index)))
        return false;
    delete_if(prt);
    return true;
}
References delete_if(), and find_if().
Referenced by __attribute__(), and bridge_create().
find_br()
static bridge_t * find_br (int if_index) static
Definition at line 77 of file bridge_track.c.
{
    bridge_t *br;
    list_for_each_entry(br, &bridges, list)
    {
        if(br->sysdeps.if_index == if_index)
            return br;
    }
    return NULL;
}
References sysdep_br_data_t::if_index, list_for_each_entry, and bridge_t::sysdeps.
Referenced by __attribute__(), bridge_create(), and delete_br_byindex().
find_if()
static port_t * find_if (bridge_t * br, int if_index) static
Definition at line 124 of file bridge_track.c.
{
    port_t *prt;
    list_for_each_entry(prt, &br->ports, br_list)
    {
        if(prt->sysdeps.if_index == if_index)
            return prt;
    }
    return NULL;
}
References sysdep_if_data_t::if_index, list_for_each_entry, bridge_t::ports, and port_t::sysdeps.
Referenced by __attribute__(), bridge_bpdu_rcv(), bridge_create(), and delete_if_byindex().
get_port_list()
static int get_port_list (const char * br_ifname, struct dirent *** namelist) static
Definition at line 636 of file bridge_track.c.
{
    char buf[256];
    snprintf(buf, sizeof(buf), SYSFS_CLASS_NET "/%.230s/brif", br_ifname);
    return scandir(buf, namelist, not_dot_dotdot, versionsort);
}
References buf, not_dot_dotdot(), and SYSFS_CLASS_NET.
Referenced by bridge_create().
LIST_HEAD()
static LIST_HEAD (bridges) static
MSTP_OUT_flush_all_fids()
void MSTP_OUT_flush_all_fids (per_tree_port_t * ptp)
Definition at line 526 of file bridge_track.c.
{
    port_t *prt = ptp->port;
    bridge_t *br = prt->bridge;
    /* Translate CIST flushing to the kernel bridge code */
    if(0 == ptp->MSTID)
    { /* CIST */
        if(0 > br_flush_port(prt->sysdeps.name))
            ERROR_PRTNAME(br, prt,
                          "Couldn't flush kernel bridge forwarding database");
    }
    /* Completion signal MSTP_IN_all_fids_flushed will be called by driver */
    INFO_MSTINAME(br, prt, ptp, "Flushing forwarding database");
    driver_flush_all_fids(ptp);
}
References br_flush_port(), port_t::bridge, driver_flush_all_fids(), ERROR_PRTNAME, INFO_MSTINAME, per_tree_port_t::MSTID, sysdep_if_data_t::name, per_tree_port_t::port, and port_t::sysdeps.
Referenced by set_fdbFlush().
MSTP_OUT_set_ageing_time()
void MSTP_OUT_set_ageing_time (port_t * prt, unsigned int ageingTime)
Definition at line 543 of file bridge_track.c.
{
    unsigned int actual_ageing_time;
    bridge_t *br = prt->bridge;
    actual_ageing_time = driver_set_ageing_time(prt, ageingTime);
    INFO_PRTNAME(br, prt, "Setting new ageing time to %u", actual_ageing_time);
    /*
     * Translate new ageing time to the kernel bridge code.
     * Kernel bridging code does not support per-port ageing time,
     * so set ageing time for the whole bridge.
     */
    if(0 > br_set_ageing_time(br->sysdeps.name, actual_ageing_time))
        ERROR_BRNAME(br, "Couldn't set new ageing time in kernel bridge");
}
References br_set_ageing_time(), port_t::bridge, driver_set_ageing_time(), ERROR_BRNAME, INFO_PRTNAME, sysdep_br_data_t::name, and bridge_t::sysdeps.
Referenced by MSTP_IN_one_second(), MSTP_IN_set_bridge_enable(), and set_fdbFlush().
MSTP_OUT_set_state()
void MSTP_OUT_set_state (per_tree_port_t * ptp, int new_state)
Definition at line 478 of file bridge_track.c.
{
    char * state_name;
    port_t *prt = ptp->port;
    bridge_t *br = prt->bridge;
    if(ptp->state == new_state)
        return;
    ptp->state = driver_set_new_state(ptp, new_state);
    switch(ptp->state)
    {
        case BR_STATE_LISTENING:
            state_name = "listening";
            break;
        case BR_STATE_LEARNING:
            state_name = "learning";
            break;
        case BR_STATE_FORWARDING:
            state_name = "forwarding";
            ++(prt->num_trans_fwd);
            break;
        case BR_STATE_BLOCKING:
            state_name = "blocking";
            ++(prt->num_trans_blk);
            break;
        default:
        case BR_STATE_DISABLED:
            state_name = "disabled";
            break;
    }
    INFO_MSTINAME(br, prt, ptp, "entering %s state", state_name);
    /* Translate new CIST state to the kernel bridge code */
    if(0 == ptp->MSTID)
    { /* CIST */
        if(0 > br_set_state(&rth_state, prt->sysdeps.if_index, ptp->state))
            INFO_PRTNAME(br, prt, "Couldn't set kernel bridge state %s",
                          state_name);
    }
}
References br_set_state(), port_t::bridge, driver_set_new_state(), sysdep_if_data_t::if_index, INFO_MSTINAME, INFO_PRTNAME, per_tree_port_t::MSTID, port_t::num_trans_blk, port_t::num_trans_fwd, per_tree_port_t::port, rth_state, per_tree_port_t::state, and port_t::sysdeps.
Referenced by MSTP_IN_set_bridge_enable(), PSTSM_to_DISCARDING(), PSTSM_to_FORWARDING(), and PSTSM_to_LEARNING().
MSTP_OUT_shutdown_port()
void MSTP_OUT_shutdown_port (port_t * prt)
Definition at line 623 of file bridge_track.c.
{
    if(0 > if_shutdown(prt->sysdeps.name))
        ERROR_PRTNAME(prt->bridge, prt, "Couldn't shutdown port");
}
References port_t::bridge, ERROR_PRTNAME, if_shutdown(), sysdep_if_data_t::name, and port_t::sysdeps.
Referenced by MSTP_IN_rx_bpdu().
MSTP_OUT_tx_bpdu()
void MSTP_OUT_tx_bpdu (port_t * prt, bpdu_t * bpdu, int size)
Definition at line 560 of file bridge_track.c.
{
    char *bpdu_type, *tcflag;
    bridge_t *br = prt->bridge;
    switch(bpdu->protocolVersion)
    {
        case protoSTP:
            switch(bpdu->bpduType)
            {
                case bpduTypeConfig:
                    bpdu_type = "STP-Config";
                    break;
                case bpduTypeTCN:
                    bpdu_type = "STP-TCN";
                    break;
                default:
                    bpdu_type = "STP-UnknownType";
            }
            break;
        case protoRSTP:
            bpdu_type = "RST";
            break;
        case protoMSTP:
            bpdu_type = "MST";
            break;
        default:
            bpdu_type = "UnknownProto";
    }
    ++(prt->num_tx_bpdu);
    if((protoSTP == bpdu->protocolVersion) && (bpduTypeTCN == bpdu->bpduType))
    {
        ++(prt->num_tx_tcn);
        LOG_PRTNAME(br, prt, "sending %s BPDU", bpdu_type);
    }
    else
    {
        tcflag = "";
        if(bpdu->flags & (1 << offsetTc))
        {
            ++(prt->num_tx_tcn);
            tcflag = ", tcFlag";
        }
        LOG_PRTNAME(br, prt, "sending %s BPDU%s", bpdu_type, tcflag);
    }
    struct llc_header h;
    memcpy(h.dest_addr, bridge_group_address, ETH_ALEN);
    memcpy(h.src_addr, prt->sysdeps.macaddr, ETH_ALEN);
    h.len8023 = __cpu_to_be16(size + LLC_PDU_LEN_U);
    h.d_sap = h.s_sap = LLC_SAP_BSPAN;
    h.llc_ctrl = LLC_PDU_TYPE_U;
    struct iovec iov[2] =
    {
        { .iov_base = &h, .iov_len = sizeof(h) },
        { .iov_base = bpdu, .iov_len = size }
    };
    packet_send(prt->sysdeps.if_index, iov, 2, sizeof(h) + size);
}
References bpduTypeConfig, bpduTypeTCN, port_t::bridge, bridge_group_address, llc_header::d_sap, llc_header::dest_addr, sysdep_if_data_t::if_index, llc_header::len8023, llc_header::llc_ctrl, LLC_PDU_LEN_U, LLC_PDU_TYPE_U, LLC_SAP_BSPAN, LOG_PRTNAME, sysdep_if_data_t::macaddr, port_t::num_tx_bpdu, port_t::num_tx_tcn, offsetTc, packet_send(), protoMSTP, protoRSTP, protoSTP, llc_header::s_sap, llc_header::src_addr, and port_t::sysdeps.
Referenced by txConfig(), txMstp(), and txTcn().
not_dot_dotdot()
static int not_dot_dotdot (const struct dirent * entry) static
Definition at line 629 of file bridge_track.c.
{
    const char *n = entry->d_name;
    return strcmp(n, ".") || strcmp(n, "..");
}
Referenced by get_port_list().
set_br_up()
static void set_br_up (bridge_t * br, bool up) static
Definition at line 191 of file bridge_track.c.
{
    bool changed = false;
    if(up != br->sysdeps.up)
    {
        INFO("%s was %s. Set %s", br->sysdeps.name,
             br->sysdeps.up ? "up" : "down", up ? "up" : "down");
        br->sysdeps.up = up;
        changed = true;
    }
    if(check_mac_address(br->sysdeps.name, br->sysdeps.macaddr))
    {
        /* MAC address changed */
        /* Notify bridge address change */
        MSTP_IN_set_bridge_address(br, br->sysdeps.macaddr);
    }
    if(changed)
        MSTP_IN_set_bridge_enable(br, br->sysdeps.up);
}
References check_mac_address(), INFO, sysdep_br_data_t::macaddr, MSTP_IN_set_bridge_address(), MSTP_IN_set_bridge_enable(), sysdep_br_data_t::name, bridge_t::sysdeps, and sysdep_br_data_t::up.
Referenced by __attribute__(), bridge_create(), and bridge_track_fini().
set_if_up()
static void set_if_up (port_t * prt, bool up) static
Definition at line 214 of file bridge_track.c.
{
    INFO("Port %s : %s", prt->sysdeps.name, (up ? "up" : "down"));
    int speed = -1;
    int duplex = -1;
    bool changed = false;
    bool bpdu_filter;
    if(check_mac_address(prt->sysdeps.name, prt->sysdeps.macaddr))
    {
        /* MAC address changed */
        if(check_mac_address(prt->bridge->sysdeps.name,
           prt->bridge->sysdeps.macaddr))
        {
            /* Notify bridge address change */
            MSTP_IN_set_bridge_address(prt->bridge,
                                       prt->bridge->sysdeps.macaddr);
        }
    }
    if(!up)
    { /* Down */
        if(prt->sysdeps.up)
        {
            prt->sysdeps.up = false;
            changed = true;
        }
    }
    else
    { /* Up */
        int r = ethtool_get_speed_duplex(prt->sysdeps.name, &speed, &duplex);
        if((r < 0) || (speed < 0))
            speed = 10;
        if((r < 0) || (duplex < 0))
            duplex = 1; /* Assume full duplex */
        if(speed != prt->sysdeps.speed)
        {
            prt->sysdeps.speed = speed;
            changed = true;
        }
        if(duplex != prt->sysdeps.duplex)
        {
            prt->sysdeps.duplex = duplex;
            changed = true;
        }
        if(!prt->sysdeps.up)
        {
            prt->sysdeps.up = true;
            changed = true;
        }
    bpdu_filter = get_bpdu_filter(prt->sysdeps.name);
    if (bpdu_filter != prt->bpduFilterPort) {
        CIST_PortConfig cfg = {
            .bpdu_filter_port = bpdu_filter,
            .set_bpdu_filter_port = true
        };
        MSTP_IN_set_cist_port_config(prt, &cfg);
    }
    }
    if(changed)
        MSTP_IN_set_port_enable(prt, prt->sysdeps.up, prt->sysdeps.speed,
                                prt->sysdeps.duplex);
}
References port_t::bpduFilterPort, port_t::bridge, check_mac_address(), sysdep_if_data_t::duplex, ethtool_get_speed_duplex(), get_bpdu_filter(), INFO, sysdep_br_data_t::macaddr, sysdep_if_data_t::macaddr, MSTP_IN_set_bridge_address(), MSTP_IN_set_cist_port_config(), MSTP_IN_set_port_enable(), sysdep_br_data_t::name, sysdep_if_data_t::name, r, sysdep_if_data_t::speed, bridge_t::sysdeps, port_t::sysdeps, and sysdep_if_data_t::up.
Referenced by __attribute__(), and bridge_create().
Variable Documentation
bridge_group_address
const __u8 bridge_group_address[ETH_ALEN] static
Initial value:
=
{
    0x01, 0x80, 0xc2, 0x00, 0x00, 0x00
}
Definition at line 381 of file bridge_track.c.
{
    0x01, 0x80, 0xc2, 0x00, 0x00, 0x00
};
Referenced by bridge_bpdu_rcv(), and MSTP_OUT_tx_bpdu().
d_sap
__u8 d_sap
Definition at line 3 of file bridge_track.c.
dest_addr
__u8 dest_addr[ETH_ALEN]
Definition at line 0 of file bridge_track.c.
len8023
__be16 len8023
Definition at line 2 of file bridge_track.c.
llc_ctrl
__u8 llc_ctrl
Definition at line 5 of file bridge_track.c.
s_sap
__u8 s_sap
Definition at line 4 of file bridge_track.c.
src_addr
__u8 src_addr[ETH_ALEN]
Definition at line 1 of file bridge_track.c.