zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/rpcd/main.c File Reference
main.c File Reference
#include <unistd.h>
#include <stdlib.h>
#include <libubox/blobmsg_json.h>
#include <libubus.h>
#include <signal.h>
#include <sys/stat.h>
#include <rpcd/exec.h>
#include <rpcd/plugin.h>
#include <rpcd/rc.h>
#include <rpcd/session.h>
#include <rpcd/uci.h>
Functions
static void handle_signal (int sig)
static void exec_self (int argc, char **argv)
int main (int argc, char **argv)
Variables
static struct ubus_context * ctx
static bool respawn = false
int rpc_exec_timeout = RPC_EXEC_DEFAULT_TIMEOUT
Function Documentation
exec_self()
static void exec_self (int argc, char ** argv) static
Definition at line 48 of file main.c.
{
    int i;
    const char *cmd;
    char **args;
    cmd = rpc_exec_lookup(argv[0]);
    if (!cmd)
        return;
    args = calloc(argc + 1, sizeof(char *));
    if (!args)
        return;
    for (i = 0; i < argc; i++)
        args[i] = argv[i];
    setenv("RPC_HANGUP", "1", 1);
    execv(cmd, (char * const *)args);
}
References cmd, and rpc_exec_lookup().
Referenced by main().
handle_signal()
static void handle_signal (int sig) static
Definition at line 40 of file main.c.
{
    rpc_session_freeze();
    uloop_cancelled = true;
    respawn = (sig == SIGHUP);
}
References respawn, rpc_session_freeze(), and uloop_cancelled.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 69 of file main.c.
{
    struct stat s;
    const char *hangup;
    const char *ubus_socket = NULL;
    int ch;
    while ((ch = getopt(argc, argv, "s:t:")) != -1) {
        switch (ch) {
        case 's':
            ubus_socket = optarg;
            break;
        case 't':
            rpc_exec_timeout = 1000 * strtol(optarg, NULL, 0);
            break;
        default:
            break;
        }
    }
    if (rpc_exec_timeout < 1000 || rpc_exec_timeout > 600000) {
        fprintf(stderr, "Invalid execution timeout specified\n");
        return -1;
    }
    if (stat(RPC_UCI_DIR_PREFIX, &s))
        mkdir(RPC_UCI_DIR_PREFIX, 0700);
    umask(0077);
    signal(SIGPIPE, SIG_IGN);
    signal(SIGHUP,  handle_signal);
    signal(SIGUSR1, handle_signal);
    uloop_init();
    ctx = ubus_connect(ubus_socket);
    if (!ctx) {
        fprintf(stderr, "Failed to connect to ubus\n");
        return -1;
    }
    ubus_add_uloop(ctx);
    rpc_session_api_init(ctx);
    rpc_uci_api_init(ctx);
    rpc_rc_api_init(ctx);
    rpc_plugin_api_init(ctx);
    hangup = getenv("RPC_HANGUP");
    if (!hangup || strcmp(hangup, "1"))
        rpc_uci_purge_savedirs();
    else
        rpc_session_thaw();
    uloop_run();
    ubus_free(ctx);
    uloop_done();
    if (respawn)
        exec_self(argc, argv);
    return 0;
}
References ctx, exec_self(), handle_signal(), respawn, rpc_exec_timeout, rpc_plugin_api_init(), rpc_rc_api_init(), rpc_session_api_init(), rpc_session_thaw(), rpc_uci_api_init(), RPC_UCI_DIR_PREFIX, rpc_uci_purge_savedirs(), ubus_add_uloop(), ubus_connect(), ubus_free(), ubus_socket, uloop_done(), uloop_init(), and uloop_run().
Variable Documentation
ctx
struct ubus_context* ctx static
Definition at line 34 of file main.c.
Referenced by main().
respawn
bool respawn = false static
Definition at line 35 of file main.c.
Referenced by askconsole(), askfirst(), handle_signal(), main(), rcrespawn(), and service_start_early().
rpc_exec_timeout
int rpc_exec_timeout = RPC_EXEC_DEFAULT_TIMEOUT
Definition at line 37 of file main.c.
Referenced by main(), and rpc_exec().