zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/libubox/vlist.h File Reference
vlist.h File Reference
#include "avl.h"
Classes
struct vlist_tree
struct vlist_node
Macros
#define VLIST_TREE_INIT(_name, _comp, _update, _keep_old, _no_delete)
#define VLIST_TREE(_name, ...)
#define vlist_find(tree, name, element, node_member)
#define vlist_for_each_element(tree, element, node_member)
#define vlist_for_each_element_safe(tree, element, node_member, ptr)
#define vlist_for_each_element_reverse(tree, element, node_member)
#define vlist_for_first_to_element(tree, last, element, node_member)
#define vlist_for_first_to_element_reverse(tree, last, element, node_member)
#define vlist_for_element_to_last(tree, first, element, node_member)
#define vlist_for_element_to_last_reverse(tree, first, element, node_member)
Typedefs
typedef void(* vlist_update_cb) (struct vlist_tree *tree, struct vlist_node *node_new, struct vlist_node *node_old)
Functions
void vlist_init (struct vlist_tree *tree, avl_tree_comp cmp, vlist_update_cb update)
static void vlist_update (struct vlist_tree *tree)
void vlist_add (struct vlist_tree *tree, struct vlist_node *node, const void *key)
void vlist_delete (struct vlist_tree *tree, struct vlist_node *node)
void vlist_flush (struct vlist_tree *tree)
void vlist_flush_all (struct vlist_tree *tree)
Class Documentation
vlist_tree
struct vlist_tree
Definition at line 29 of file vlist.h.
Class Members
struct avl_tree avl
bool keep_old
bool no_delete
vlist_update_cb update
int version
vlist_node
struct vlist_node
Definition at line 39 of file vlist.h.
Class Members
struct avl_node avl
int version
Macro Definition Documentation
vlist_find
#define vlist_find (tree, name, element, node_member)
Value:
    avl_find_element(&(tree)->avl, name, element, node_member.avl)
Definition at line 59 of file vlist.h.
#define vlist_find(tree, name, element, node_member) \
    avl_find_element(&(tree)->avl, name, element, node_member.avl)
Referenced by __interface_add(), alias_check_state(), bonding_create_port(), bonding_hotplug_add(), bonding_hotplug_del(), bridge_hotplug_add(), bridge_hotplug_del(), bridge_hotplug_get_vlan(), bridge_insert_member(), bridge_vlan_check_attr(), config_init_procd_wireless_interface(), config_init_wireless(), container_handle_console(), extdev_bridge_create_member(), extdev_hotplug_remove(), get_wdev(), interface_claim_device(), interface_ip_add_neighbor(), interface_ip_add_route(), interface_update_prefix(), interface_update_prefix_assignments(), netifd_add_host_route(), netifd_handle_iface(), proto_shell_update_host_dep(), register_interfaces(), service_handle_delete(), service_handle_signal(), service_handle_watchdog(), system_add_ip_tunnel(), vif_config_add_bridge(), wireless_check_interface(), wireless_device_notify(), wireless_interface_create(), wireless_interface_handle_link(), and wireless_vlan_handle_link().
vlist_for_each_element
#define vlist_for_each_element (tree, element, node_member)
Value:
    avl_for_each_element(&(tree)->avl, element, node_member.avl)
Definition at line 72 of file vlist.h.
#define vlist_for_each_element(tree, element, node_member) \
    avl_for_each_element(&(tree)->avl, element, node_member.avl)
Referenced by __bridge_enable_members(), __find_ip_addr_target(), __find_ip_route_target(), __interface_write_dns_entries(), __wireless_start_pending(), bonding_reset_primary(), bonding_retry_ports(), bonding_set_down(), bonding_set_up(), bridge_config_init(), bridge_dev_vlan_update(), bridge_disable_member(), bridge_dump_info(), bridge_free_member(), bridge_member_enable_vlans(), bridge_recalc_member_pvid(), bridge_reset_primary(), bridge_retry_members(), bridge_set_down(), bridge_set_local_vlans(), bridge_set_up(), bridge_set_vlan_state(), config_init_ip(), config_init_wireless(), container_handle_console(), extdev_bridge_set_down(), extdev_bridge_set_up(), generic_interface_cb(), interface_ip_add_target_route(), interface_ip_dump_address_list(), interface_ip_dump_neighbor_list(), interface_ip_dump_prefix_list(), interface_ip_dump_route_list(), interface_ip_set_enabled(), interface_ip_valid_until_handler(), interface_set_down(), interface_start_jail(), interface_start_pending(), interface_stop_jail(), interface_update_prefix_assignments(), interface_update_prefix_delegation(), netifd_handle_dump(), netifd_handle_wdev_down(), netifd_handle_wdev_get_validate(), netifd_handle_wdev_reconf(), netifd_handle_wdev_status(), netifd_handle_wdev_up(), prepare_config(), service_dump(), service_get_data(), service_handle_signal(), service_handle_state(), system_bridge_vlan_check(), wdev_check_network_enabled(), wdev_vlan_check_network_enabled(), wireless_check_network_enabled(), wireless_device_free_state(), wireless_device_hotplug_event(), wireless_device_mark_down(), wireless_device_mark_up(), wireless_device_status(), and wireless_interface_status().
vlist_for_each_element_reverse
#define vlist_for_each_element_reverse (tree, element, node_member)
Value:
    avl_for_each_element_reverse(&(tree)->avl, element, node_member.avl)
Definition at line 78 of file vlist.h.
#define vlist_for_each_element_reverse(tree, element, node_member) \
    avl_for_each_element_reverse(&(tree)->avl, element, node_member.avl)
vlist_for_each_element_safe
#define vlist_for_each_element_safe (tree, element, node_member, ptr)
Value:
    avl_for_each_element_safe(&(tree)->avl, element, node_member.avl, ptr)
Definition at line 75 of file vlist.h.
#define vlist_for_each_element_safe(tree, element, node_member, ptr) \
    avl_for_each_element_safe(&(tree)->avl, element, node_member.avl, ptr)
Referenced by interface_ip_valid_until_handler(), and service_avl_stop_all().
vlist_for_element_to_last
#define vlist_for_element_to_last (tree, first, element, node_member)
Value:
    avl_for_element_range(first, avl_last_element(&(tree)->avl, element, node_member.avl), element, node_member.avl)
Definition at line 87 of file vlist.h.
#define vlist_for_element_to_last(tree, first, element, node_member) \
    avl_for_element_range(first, avl_last_element(&(tree)->avl, element, node_member.avl), element, node_member.avl)
vlist_for_element_to_last_reverse
#define vlist_for_element_to_last_reverse (tree, first, element, node_member)
Value:
    avl_for_element_range_reverse(first, avl_last_element(&(tree)->avl, element, node_member.avl), element, node_member.avl)
Definition at line 90 of file vlist.h.
#define vlist_for_element_to_last_reverse(tree, first, element, node_member) \
    avl_for_element_range_reverse(first, avl_last_element(&(tree)->avl, element, node_member.avl), element, node_member.avl)
vlist_for_first_to_element
#define vlist_for_first_to_element (tree, last, element, node_member)
Value:
    avl_for_element_range(avl_first_element(&(tree)->avl, element, node_member.avl), last, element, node_member.avl)
Definition at line 81 of file vlist.h.
#define vlist_for_first_to_element(tree, last, element, node_member) \
    avl_for_element_range(avl_first_element(&(tree)->avl, element, node_member.avl), last, element, node_member.avl)
vlist_for_first_to_element_reverse
#define vlist_for_first_to_element_reverse (tree, last, element, node_member)
Value:
    avl_for_element_range_reverse(avl_first_element(&(tree)->avl, element, node_member.avl), last, element, node_member.avl)
Definition at line 84 of file vlist.h.
#define vlist_for_first_to_element_reverse(tree, last, element, node_member) \
    avl_for_element_range_reverse(avl_first_element(&(tree)->avl, element, node_member.avl), last, element, node_member.avl)
VLIST_TREE
#define VLIST_TREE (_name, ...)
Value:
    struct vlist_tree _name =                   \
        VLIST_TREE_INIT(_name, __VA_ARGS__)
Definition at line 53 of file vlist.h.
#define VLIST_TREE(_name, ...)                      \
    struct vlist_tree _name =                   \
        VLIST_TREE_INIT(_name, __VA_ARGS__)
VLIST_TREE_INIT
#define VLIST_TREE_INIT (_name, _comp, _update, _keep_old, _no_delete)
Value:
    {                               \
        .avl = AVL_TREE_INIT(_name.avl, _comp, false, NULL),    \
        .update = _update,                  \
        .version = 1,                       \
        .keep_old = _keep_old,                  \
        .no_delete = _no_delete,                \
    }
Definition at line 44 of file vlist.h.
#define VLIST_TREE_INIT(_name, _comp, _update, _keep_old, _no_delete)   \
    {                               \
        .avl = AVL_TREE_INIT(_name.avl, _comp, false, NULL),    \
        .update = _update,                  \
        .version = 1,                       \
        .keep_old = _keep_old,                  \
        .no_delete = _no_delete,                \
    }
Typedef Documentation
vlist_update_cb
typedef void(* vlist_update_cb) (struct vlist_tree *tree, struct vlist_node *node_new, struct vlist_node *node_old)
Definition at line 25 of file vlist.h.
Function Documentation
vlist_add()
void vlist_add (struct vlist_tree * tree, struct vlist_node * node, const void * key)
Definition at line 36 of file vlist.c.
{
    struct vlist_node *old_node = NULL;
    struct avl_node *anode;
    node->avl.key = key;
    node->version = tree->version;
    anode = avl_find(&tree->avl, key);
    if (anode) {
        old_node = container_of(anode, struct vlist_node, avl);
        if (tree->keep_old || tree->no_delete) {
            old_node->version = tree->version;
            goto update_only;
        }
        avl_delete(&tree->avl, anode);
    }
    avl_insert(&tree->avl, &node->avl);
update_only:
    tree->update(tree, node, old_node);
}
References node::avl, vlist_tree::avl, avl_delete(), avl_find(), avl_insert(), container_of, vlist_tree::keep_old, avl_node::key, vlist_tree::no_delete, vlist_tree::update, vlist_node::version, and vlist_tree::version.
Referenced by __interface_add(), bonding_create_port(), bridge_hotplug_get_vlan(), bridge_insert_member(), config_parse_vlan(), extdev_bridge_create_member(), interface_ip_add_device_prefix(), interface_ip_add_neighbor(), interface_ip_add_route(), interface_ip_add_target_route(), iprule_add(), parse_address_list(), parse_gateway_option(), parse_static_address_option(), service_instance_add(), ubusd_acl_load_file(), wireless_device_create(), wireless_interface_create(), wireless_station_create(), and wireless_vlan_create().
vlist_delete()
void vlist_delete (struct vlist_tree * tree, struct vlist_node * node)
Definition at line 28 of file vlist.c.
{
    if (!tree->no_delete)
        avl_delete(&tree->avl, &node->avl);
    tree->update(tree, NULL, node);
}
References node::avl, vlist_tree::avl, avl_delete(), vlist_tree::no_delete, and vlist_tree::update.
Referenced by bonding_hotplug_del(), bonding_port_cb(), bridge_free_member(), bridge_hotplug_del(), bridge_member_cb(), extdev_bridge_member_cb(), extdev_hotplug_remove(), interface_ip_valid_until_handler(), netifd_iface_do_remove(), service_handle_delete(), and vlist_flush().
vlist_flush()
void vlist_flush (struct vlist_tree * tree)
Definition at line 62 of file vlist.c.
{
    struct vlist_node *node, *tmp;
    avl_for_each_element_safe(&tree->avl, node, avl, tmp) {
        if ((node->version == tree->version || node->version == -1) &&
            tree->version != -1)
            continue;
        vlist_delete(tree, node);
    }
}
References vlist_node::avl, vlist_tree::avl, avl_for_each_element_safe, vlist_tree::version, and vlist_delete().
Referenced by __bridge_config_init(), bonding_config_init(), bridge_config_init(), config_init_all(), config_init_procd_wireless_interface(), config_init_wireless(), config_parse_wireless_interface(), device_vlan_update(), interface_ip_update_complete(), iprule_update_complete(), service_handle_update(), service_update(), ubusd_acl_load(), and vlist_flush_all().
vlist_flush_all()
void vlist_flush_all (struct vlist_tree * tree)
Definition at line 76 of file vlist.c.
{
    tree->version = -1;
    vlist_flush(tree);
}
References vlist_tree::version, and vlist_flush().
Referenced by bonding_free(), bridge_free(), extdev_free(), interface_ip_flush(), service_delete(), vif_free(), and wireless_device_free().
vlist_init()
void vlist_init (struct vlist_tree * tree, avl_tree_comp cmp, vlist_update_cb update)
Definition at line 19 of file vlist.c.
{
    tree->update = update;
    tree->version = 1;
    avl_init(&tree->avl, cmp, 0, tree);
}
References vlist_tree::avl, avl_init(), cmp, vlist_tree::update, and vlist_tree::version.
Referenced by __bridge_create(), __interface_ip_init(), bonding_create(), bridge_create(), interface_init_list(), interface_ip_init(), iprule_init_list(), service_alloc(), wireless_device_create(), wireless_init(), and wireless_interface_create().
vlist_update()
static void vlist_update (struct vlist_tree * tree) inline static
Definition at line 62 of file vlist.h.
{
    tree->version++;
}
References vlist_tree::version.
Referenced by __bridge_config_init(), bonding_config_init(), bridge_config_init(), config_init_all(), config_init_wireless(), device_vlan_update(), interface_ip_update_start(), iprule_update_start(), service_handle_update(), service_update(), ubusd_acl_load(), and wireless_interface_create().