zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/ubus/tests/fuzz/test-fuzz.c File Reference
test-fuzz.c File Reference
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include <limits.h>
#include <libubox/blob.h>
#include <libubox/blobmsg.h>
#include "ubusmsg.h"
#include "libubus.h"
#include "libubus-internal.h"
Functions
static void _ubus_validate_hdr (const uint8_t *data, size_t size)
static void _ubus_parse_msg (const uint8_t *data, size_t size)
int LLVMFuzzerTestOneInput (const uint8_t *data, size_t size)
Function Documentation
_ubus_parse_msg()
static void _ubus_parse_msg (const uint8_t * data, size_t size) static
Definition at line 21 of file test-fuzz.c.
{
    struct blob_attr *attr = (struct blob_attr *) data;
    if (size < sizeof(struct blob_attr *))
        return;
    if (blob_pad_len(attr) > UBUS_MAX_MSGLEN)
        return;
    ubus_parse_msg(attr, size);
}
References blob_pad_len(), blob_attr::data, and ubus_parse_msg().
Referenced by LLVMFuzzerTestOneInput().
_ubus_validate_hdr()
static void _ubus_validate_hdr (const uint8_t * data, size_t size) static
Definition at line 13 of file test-fuzz.c.
{
    if (size > sizeof(struct ubus_msghdr))
        return;
    ubus_validate_hdr((struct ubus_msghdr *) data);
}
References ubus_validate_hdr().
Referenced by LLVMFuzzerTestOneInput().
LLVMFuzzerTestOneInput()
int LLVMFuzzerTestOneInput (const uint8_t * data, size_t size)
Definition at line 34 of file test-fuzz.c.
{
    _ubus_validate_hdr(data, size);
    _ubus_parse_msg(data, size);
    return 0;
}
References _ubus_parse_msg(), _ubus_validate_hdr(), and blob_attr::data.