zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/libubox/tests/test-blobmsg_check_array.c File Reference
test-blobmsg_check_array.c File Reference
#include <stdio.h>
#include "blobmsg.h"
Macros
#define ARRAY_SIZE(x)
Enumerations
enum { ARRAY_A = 0 , ARRAY_B = 0 }
Functions
static int check_table_a_entries (struct blob_attr *attr)
static int check_message (struct blob_buf *buf)
static void fill_message (struct blob_buf *const buf)
int main (int argc, char **argv)
Variables
static char const array_a [] = "array_a"
static char const array_b [] = "array_b"
static const struct blobmsg_policy pol_a []
static const struct blobmsg_policy pol_b []
Macro Definition Documentation
ARRAY_SIZE
#define ARRAY_SIZE (x)
Value:
(sizeof(x) / sizeof((x)[0]))
Definition at line 44 of file test-blobmsg_check_array.c.
Referenced by check_message(), and check_table_a_entries().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ARRAY_A 0
ARRAY_B 0
Definition at line 21 of file test-blobmsg_check_array.c.
     {
    ARRAY_A = 0,
    ARRAY_B = 0,
};
Function Documentation
check_message()
static int check_message (struct blob_buf * buf) static
Definition at line 110 of file test-blobmsg_check_array.c.
{
    struct blob_attr *tb[ARRAY_SIZE(pol_a)];
    if (blobmsg_parse(pol_a, ARRAY_SIZE(pol_a), tb,
                      blob_data(buf->head), blobmsg_data_len(buf->head)) != 0) {
        fprintf(stderr, "Policy %s parse failed\n", array_a);
        return -1;
    }
    if (tb[ARRAY_A] == NULL) {
        fprintf(stderr, "%s not found\n", array_a);
        return -1;
    }
    int const result = blobmsg_check_array(tb[ARRAY_A], BLOBMSG_TYPE_TABLE);
    if (result < 0) {
        fprintf(stderr, "Failed blobmsg_check_array() (TABLE) on %s (%d)\n",
                array_a, result);
        return -1;
    }
    return check_table_a_entries(tb[ARRAY_A]);
}
References ARRAY_A, array_a, ARRAY_SIZE, blob_data(), blobmsg_check_array(), blobmsg_data_len(), blobmsg_parse(), BLOBMSG_TYPE_TABLE, buf, check_table_a_entries(), and pol_a.
Referenced by main().
check_table_a_entries()
static int check_table_a_entries (struct blob_attr * attr) static
Definition at line 48 of file test-blobmsg_check_array.c.
{
    struct blob_attr *cur;
    size_t rem;
    int entry_number = 0;
    blobmsg_for_each_attr(cur, attr, rem) {
        int failed = 0;
        fprintf(stderr, "Process %s: entry %d\n", array_a, entry_number);
        struct blob_attr *tb[ARRAY_SIZE(pol_b)];
        if (blobmsg_parse(pol_b, ARRAY_SIZE(pol_b), tb,
                          blobmsg_data(cur), blobmsg_data_len(cur)) != 0) {
            fprintf(stderr, "Policy %s parse failed\n", array_b);
            return -1;
        }
        if (tb[ARRAY_B] == NULL) {
            fprintf(stderr, "%s not found\n", array_b);
            return -1;
        }
        /*
         * This is the test that fails when blobmsg_check_array() passes the
         * length obtained by blob_len(attr).
         * It succeeds when blobmsg_check_array() uses blob_len(attr), which is
         * equivalent to the origianl code, pre the length check changes.
         */
        if (blobmsg_check_array(tb[ARRAY_B], BLOBMSG_TYPE_STRING) < 0) {
            fprintf(stderr, "Failed blobmsg_check_array() (STRING) on %s\n",
                        array_b);
            failed = 1;
        }
        /*
         * Continue outputting the strings even though the test above might
         * have failed.
         * This will show that the array does actually contain the expected
         * string.
         */
        struct blob_attr *cur2;
        size_t rem2;
        blobmsg_for_each_attr(cur2, tb[ARRAY_B], rem2) {
            fprintf(stderr, "%s contains string: %s\n",
                            array_b, blobmsg_get_string(cur2));
        }
        entry_number++;
        if (failed)
            return -1;
    }
    return 0;
}
References array_a, ARRAY_B, array_b, ARRAY_SIZE, blobmsg_check_array(), blobmsg_data(), blobmsg_data_len(), blobmsg_for_each_attr, blobmsg_get_string(), blobmsg_parse(), BLOBMSG_TYPE_STRING, and pol_b.
Referenced by check_message().
fill_message()
static void fill_message (struct blob_buf *const buf) static
Definition at line 137 of file test-blobmsg_check_array.c.
{
    void * const tbl_a = blobmsg_open_array(buf, "array_a");
    void * const obj = blobmsg_open_table(buf, NULL);
    void * const tbl_b = blobmsg_open_array(buf, "array_b");
    blobmsg_add_string(buf, NULL, "1");
    blobmsg_close_array(buf, tbl_b);
    blobmsg_close_table(buf, obj);
    blobmsg_close_array(buf, tbl_a);
}
References blobmsg_add_string(), blobmsg_close_array(), blobmsg_close_table(), blobmsg_open_array(), blobmsg_open_table(), and buf.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 153 of file test-blobmsg_check_array.c.
{
    int result;
    static struct blob_buf buf;
    blobmsg_buf_init(&buf);
    fill_message(&buf);
    result = check_message(&buf);
    if (result == 0)
        fprintf(stderr, "blobmsg_check_array() test passed\n");
    if (buf.buf != NULL)
        free(buf.buf);
    return result ? EXIT_FAILURE : EXIT_SUCCESS;
}
References blobmsg_buf_init(), buf, check_message(), and fill_message().
Variable Documentation
array_a
char const array_a[] = "array_a" static
Definition at line 26 of file test-blobmsg_check_array.c.
Referenced by check_message(), and check_table_a_entries().
array_b
char const array_b[] = "array_b" static
Definition at line 27 of file test-blobmsg_check_array.c.
Referenced by check_table_a_entries().
pol_a
const struct blobmsg_policy pol_a[] static
Initial value:
= {
    [ARRAY_A] = {
        .name = array_a,
        .type = BLOBMSG_TYPE_ARRAY
    }
}
Definition at line 29 of file test-blobmsg_check_array.c.
{
    [ARRAY_A] = {
        .name = array_a,
        .type = BLOBMSG_TYPE_ARRAY
    }
};
Referenced by check_message().
pol_b
const struct blobmsg_policy pol_b[] static
Initial value:
= {
    [ARRAY_B] = {
        .name = array_b,
        .type = BLOBMSG_TYPE_ARRAY
    }
}
Definition at line 36 of file test-blobmsg_check_array.c.
{
    [ARRAY_B] = {
        .name = array_b,
        .type = BLOBMSG_TYPE_ARRAY
    }
};
Referenced by check_table_a_entries().