zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/ubus/ubusd_id.c File Reference
ubusd_id.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <fcntl.h>
#include <libubox/avl-cmp.h>
#include "ubusmsg.h"
#include "ubusd_id.h"
Functions
static int ubus_cmp_id (const void *k1, const void *k2, void *ptr)
void ubus_init_string_tree (struct avl_tree *tree, bool dup)
void ubus_init_id_tree (struct avl_tree *tree)
bool ubus_alloc_id (struct avl_tree *tree, struct ubus_id *id, uint32_t val)
Variables
static int random_fd = -1
Function Documentation
ubus_alloc_id()
bool ubus_alloc_id (struct avl_tree * tree, struct ubus_id * id, uint32_t val)
Definition at line 53 of file ubusd_id.c.
{
    id->avl.key = &id->id;
    if (val) {
        id->id = val;
        return avl_insert(tree, &id->avl) == 0;
    }
    do {
        if (read(random_fd, &id->id, sizeof(id->id)) != sizeof(id->id))
            return false;
        if (id->id < UBUS_SYSTEM_OBJECT_MAX)
            continue;
    } while (avl_insert(tree, &id->avl) != 0);
    return true;
}
References avl_insert(), id, random_fd, and UBUS_SYSTEM_OBJECT_MAX.
Referenced by ubus_create_obj_type(), ubusd_create_object_internal(), and ubusd_proto_new_client().
ubus_cmp_id()
static int ubus_cmp_id (const void * k1, const void * k2, void * ptr) static
Definition at line 25 of file ubusd_id.c.
{
    const uint32_t *id1 = k1, *id2 = k2;
    if (*id1 < *id2)
        return -1;
    else
        return *id1 > *id2;
}
Referenced by ubus_init_id_tree().
ubus_init_id_tree()
void ubus_init_id_tree (struct avl_tree * tree)
Definition at line 40 of file ubusd_id.c.
{
    if (random_fd < 0) {
        random_fd = open("/dev/urandom", O_RDONLY);
        if (random_fd < 0) {
            perror("open");
            exit(1);
        }
    }
    avl_init(tree, ubus_cmp_id, false, NULL);
}
References avl_init(), random_fd, and ubus_cmp_id().
Referenced by ubusd_obj_init(), and ubusd_proto_init().
ubus_init_string_tree()
void ubus_init_string_tree (struct avl_tree * tree, bool dup)
Definition at line 35 of file ubusd_id.c.
{
    avl_init(tree, avl_strcmp, dup, NULL);
}
References avl_init(), and avl_strcmp().
Referenced by ubusd_acl_init(), ubusd_event_init(), and ubusd_obj_init().
Variable Documentation
random_fd
int random_fd = -1 static
Definition at line 23 of file ubusd_id.c.
Referenced by ubus_alloc_id(), and ubus_init_id_tree().