zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/libubox/kvlist.h File Reference
kvlist.h File Reference
#include "avl-cmp.h"
#include "avl.h"
Classes
struct kvlist
struct kvlist_node
Macros
#define KVLIST_INIT(_name, _get_len)
#define KVLIST(_name, _get_len)
#define __ptr_to_kv(_ptr)
#define __avl_list_to_kv(_l)
#define kvlist_for_each(kv, name, value)
Functions
void kvlist_init (struct kvlist *kv, int(*get_len)(struct kvlist *kv, const void *data))
void kvlist_free (struct kvlist *kv)
void * kvlist_get (struct kvlist *kv, const char *name)
bool kvlist_set (struct kvlist *kv, const char *name, const void *data)
bool kvlist_delete (struct kvlist *kv, const char *name)
int kvlist_strlen (struct kvlist *kv, const void *data)
int kvlist_blob_len (struct kvlist *kv, const void *data)
Class Documentation
kvlist
struct kvlist
Definition at line 24 of file kvlist.h.
Class Members
struct avl_tree avl
int(*)(struct kvlist *kv, const void *data) get_len
Macro Definition Documentation
__avl_list_to_kv
#define __avl_list_to_kv (_l)
Value:
container_of(_l, struct kvlist_node, avl.list)
Definition at line 46 of file kvlist.h.
__ptr_to_kv
#define __ptr_to_kv (_ptr)
Value:
container_of(((char *) (_ptr)), struct kvlist_node, data[0])
Definition at line 45 of file kvlist.h.
KVLIST
#define KVLIST (_name, _get_len)
Value:
    struct kvlist _name = KVLIST_INIT(_name, _get_len)
Definition at line 42 of file kvlist.h.
#define KVLIST(_name, _get_len)                         \
    struct kvlist _name = KVLIST_INIT(_name, _get_len)
kvlist_for_each
#define kvlist_for_each (kv, name, value)
Value:
    for (value = (void *) __avl_list_to_kv((kv)->avl.list_head.next)->data,         \
         name = (const char *) __ptr_to_kv(value)->avl.key, (void) name;            \
         &__ptr_to_kv(value)->avl.list != &(kv)->avl.list_head;             \
         value = (void *) (__avl_list_to_kv(__ptr_to_kv(value)->avl.list.next))->data,  \
         name = (const char *) __ptr_to_kv(value)->avl.key)
Definition at line 48 of file kvlist.h.
#define kvlist_for_each(kv, name, value) \
    for (value = (void *) __avl_list_to_kv((kv)->avl.list_head.next)->data,         \
         name = (const char *) __ptr_to_kv(value)->avl.key, (void) name;            \
         &__ptr_to_kv(value)->avl.list != &(kv)->avl.list_head;             \
         value = (void *) (__avl_list_to_kv(__ptr_to_kv(value)->avl.list.next))->data,  \
         name = (const char *) __ptr_to_kv(value)->avl.key)
KVLIST_INIT
#define KVLIST_INIT (_name, _get_len)
Value:
    {                                   \
        .avl = AVL_TREE_INIT(_name.avl, avl_strcmp, false, NULL),   \
        .get_len = _get_len                     \
    }
Definition at line 36 of file kvlist.h.
#define KVLIST_INIT(_name, _get_len)                        \
    {                                   \
        .avl = AVL_TREE_INIT(_name.avl, avl_strcmp, false, NULL),   \
        .get_len = _get_len                     \
    }
Function Documentation
kvlist_blob_len()
int kvlist_blob_len (struct kvlist * kv, const void * data)
Definition at line 32 of file kvlist.c.
{
    return blob_pad_len(data);
}
References blob_pad_len().
kvlist_delete()
bool kvlist_delete (struct kvlist * kv, const char * name)
Definition at line 61 of file kvlist.c.
{
    struct kvlist_node *node;
    node = __kvlist_get(kv, name);
    if (node) {
        avl_delete(&kv->avl, &node->avl);
        free(node);
    }
    return !!node;
}
References __kvlist_get(), kvlist::avl, node::avl, and avl_delete().
Referenced by kvlist_set().
kvlist_free()
void kvlist_free (struct kvlist * kv)
Definition at line 95 of file kvlist.c.
{
    struct kvlist_node *node, *tmp;
    avl_remove_all_elements(&kv->avl, node, avl, tmp)
        free(node);
}
References kvlist::avl, kvlist_node::avl, and avl_remove_all_elements.
Referenced by bridge_free(), and device_vlan_update().
kvlist_get()
void * kvlist_get (struct kvlist * kv, const char * name)
Definition at line 50 of file kvlist.c.
{
    struct kvlist_node *node;
    node = __kvlist_get(kv, name);
    if (!node)
        return NULL;
    return node->data;
}
References __kvlist_get().
Referenced by get_vlan_device(), and vlandev_get_vid().
kvlist_init()
void kvlist_init (struct kvlist * kv, int(* get_len)(struct kvlist *kv, const void *data))
Definition at line 37 of file kvlist.c.
{
    avl_init(&kv->avl, avl_strcmp, false, NULL);
    kv->get_len = get_len;
}
References kvlist::avl, avl_init(), avl_strcmp(), and kvlist::get_len.
Referenced by device_vlan_update().
kvlist_set()
bool kvlist_set (struct kvlist * kv, const char * name, const void * data)
Definition at line 74 of file kvlist.c.
{
    struct kvlist_node *node;
    char *name_buf;
    int len = kv->get_len(kv, data);
    node = calloc_a(sizeof(struct kvlist_node) + len,
        &name_buf, strlen(name) + 1);
    if (!node)
        return false;
    kvlist_delete(kv, name);
    memcpy(node->data, data, len);
    node->avl.key = strcpy(name_buf, name);
    avl_insert(&kv->avl, &node->avl);
    return true;
}
References kvlist::avl, node::avl, avl_insert(), calloc_a, kvlist::get_len, avl_node::key, and kvlist_delete().
Referenced by config_parse_vlan().
kvlist_strlen()
int kvlist_strlen (struct kvlist * kv, const void * data)
Definition at line 27 of file kvlist.c.
{
    return strlen(data) + 1;
}