zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/ustp/worker.c File Reference
worker.c File Reference
#include <pthread.h>
#include <string.h>
#include <stdlib.h>
#include <libubox/uloop.h>
#include <libubox/utils.h>
#include "worker.h"
#include "bridge_ctl.h"
#include "bridge_track.h"
#include "packet.h"
Classes
struct worker_queued_event
Functions
static LIST_HEAD (w_queue)
static struct worker_event * worker_next_event (void)
static void handle_worker_event (struct worker_event *ev)
static void * worker_thread_fn (void *arg)
static void worker_timer_cb (struct uloop_timeout *t)
int worker_init (void)
void worker_cleanup (void)
void worker_queue_event (struct worker_event *ev)
Variables
static pthread_t w_thread
static pthread_mutex_t w_lock = PTHREAD_MUTEX_INITIALIZER
static pthread_cond_t w_cond = PTHREAD_COND_INITIALIZER
static struct uloop_timeout w_timer
Class Documentation
worker_queued_event
struct worker_queued_event
Definition at line 32 of file worker.c.
Class Members
struct worker_event ev
struct list_head list
Function Documentation
handle_worker_event()
static void handle_worker_event (struct worker_event * ev) static
Definition at line 57 of file worker.c.
{
    switch (ev->type) {
    case WORKER_EV_ONE_SECOND:
        bridge_one_second();
        break;
    case WORKER_EV_BRIDGE_EVENT:
        bridge_event_handler();
        break;
    case WORKER_EV_RECV_PACKET:
        packet_rcv();
        break;
    case WORKER_EV_BRIDGE_ADD:
        bridge_create(ev->bridge_idx, &ev->bridge_config);
        break;
    case WORKER_EV_BRIDGE_REMOVE:
        bridge_delete(ev->bridge_idx);
        break;
    default:
        return;
    }
}
References worker_event::bridge_config, bridge_create(), bridge_delete(), bridge_event_handler(), worker_event::bridge_idx, bridge_one_second(), packet_rcv(), worker_event::type, WORKER_EV_BRIDGE_ADD, WORKER_EV_BRIDGE_EVENT, WORKER_EV_BRIDGE_REMOVE, WORKER_EV_ONE_SECOND, and WORKER_EV_RECV_PACKET.
Referenced by worker_thread_fn().
LIST_HEAD()
static LIST_HEAD (w_queue) static
worker_cleanup()
void worker_cleanup (void)
Definition at line 113 of file worker.c.
{
    struct worker_event ev = {
        .type = WORKER_EV_SHUTDOWN,
    };
    worker_queue_event(&ev);
    pthread_join(w_thread, NULL);
}
References w_thread, WORKER_EV_SHUTDOWN, and worker_queue_event().
Referenced by main().
worker_init()
int worker_init (void)
Definition at line 105 of file worker.c.
{
    w_timer.cb = worker_timer_cb;
    uloop_timeout_set(&w_timer, 1000);
    return pthread_create(&w_thread, NULL, worker_thread_fn, NULL);
}
References uloop_timeout::cb, uloop_timeout_set(), w_thread, w_timer, worker_thread_fn(), and worker_timer_cb().
Referenced by main().
worker_next_event()
static struct worker_event * worker_next_event (void) static
Definition at line 37 of file worker.c.
{
    struct worker_queued_event *ev;
    static struct worker_event ev_data;
    pthread_mutex_lock(&w_lock);
    while (list_empty(&w_queue))
        pthread_cond_wait(&w_cond, &w_lock);
    ev = list_first_entry(&w_queue, struct worker_queued_event, list);
    list_del(&ev->list);
    pthread_mutex_unlock(&w_lock);
    memcpy(&ev_data, &ev->ev, sizeof(ev_data));
    free(ev);
    return &ev_data;
}
References worker_queued_event::ev, worker_queued_event::list, list_del(), list_empty(), list_first_entry, w_cond, and w_lock.
Referenced by worker_thread_fn().
worker_queue_event()
void worker_queue_event (struct worker_event * ev)
Definition at line 123 of file worker.c.
{
    struct worker_queued_event *evc;
    evc = malloc(sizeof(*evc));
    memcpy(&evc->ev, ev, sizeof(*ev));
    pthread_mutex_lock(&w_lock);
    list_add_tail(&evc->list, &w_queue);
    pthread_mutex_unlock(&w_lock);
    pthread_cond_signal(&w_cond);
}
References worker_queued_event::ev, worker_queued_event::list, list_add_tail(), w_cond, and w_lock.
Referenced by bridge_event_cb(), packet_event(), ubus_bridge_state(), worker_cleanup(), and worker_timer_cb().
worker_thread_fn()
static void * worker_thread_fn (void * arg) static
Definition at line 80 of file worker.c.
{
    struct worker_event *ev;
    while (1) {
        ev = worker_next_event();
        if (ev->type == WORKER_EV_SHUTDOWN)
            break;
        handle_worker_event(ev);
    }
    return NULL;
}
References handle_worker_event(), worker_event::type, WORKER_EV_SHUTDOWN, and worker_next_event().
Referenced by worker_init().
worker_timer_cb()
static void worker_timer_cb (struct uloop_timeout * t) static
Definition at line 95 of file worker.c.
{
    struct worker_event ev = {
        .type = WORKER_EV_ONE_SECOND,
    };
    uloop_timeout_set(t, 1000);
    worker_queue_event(&ev);
}
References uloop_timeout_set(), WORKER_EV_ONE_SECOND, and worker_queue_event().
Referenced by worker_init().
Variable Documentation
w_cond
pthread_cond_t w_cond = PTHREAD_COND_INITIALIZER static
Definition at line 28 of file worker.c.
Referenced by worker_next_event(), and worker_queue_event().
w_lock
pthread_mutex_t w_lock = PTHREAD_MUTEX_INITIALIZER static
Definition at line 27 of file worker.c.
Referenced by worker_next_event(), and worker_queue_event().
w_thread
pthread_t w_thread static
Definition at line 26 of file worker.c.
Referenced by worker_cleanup(), and worker_init().
w_timer
struct uloop_timeout w_timer static
Definition at line 30 of file worker.c.
Referenced by worker_init().