zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/procd.c File Reference
procd.c File Reference
#include <sys/wait.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/reboot.h>
#include <unistd.h>
#include <getopt.h>
#include <libgen.h>
#include "procd.h"
#include "watchdog.h"
#include "plug/hotplug.h"
Functions
static void procd_udebug_vprintf (const char *format, va_list ap)
void procd_udebug_printf (const char *format,...)
void procd_udebug_set_enabled (bool val)
static int usage (const char *prog)
int main (int argc, char **argv)
Variables
unsigned int debug
static struct udebug ud
static struct udebug_buf udb
static bool udebug_enabled
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 91 of file procd.c.
{
    int ch;
    char *dbglvl = getenv("DBGLVL");
    int ulog_channels = ULOG_KMSG;
    if (dbglvl) {
        debug = atoi(dbglvl);
        unsetenv("DBGLVL");
    }
    while ((ch = getopt(argc, argv, "d:s:h:S")) != -1) {
        switch (ch) {
        case 'h':
            return hotplug_run(optarg);
        case 's':
            ubus_socket = optarg;
            break;
        case 'd':
            debug = atoi(optarg);
            break;
        case 'S':
            ulog_channels = ULOG_STDIO;
            break;
        default:
            return usage(argv[0]);
        }
    }
    ulog_open(ulog_channels, LOG_DAEMON, "procd");
    ulog_threshold(LOG_DEBUG + 1);
    setsid();
    uloop_init();
    procd_signal();
    procd_udebug_set_enabled(true);
    if (getpid() != 1)
        procd_connect_ubus();
    else
        procd_state_next();
    uloop_run();
    uloop_done();
    return 0;
}
References debug, hotplug_run(), procd_connect_ubus(), procd_signal(), procd_state_next(), procd_udebug_set_enabled(), ubus_socket, ULOG_KMSG, ulog_open(), ULOG_STDIO, ulog_threshold(), uloop_done(), uloop_init(), uloop_run(), and usage().
procd_udebug_printf()
void procd_udebug_printf (const char * format, ...)
Definition at line 44 of file procd.c.
{
    va_list ap;
    va_start(ap, format);
    procd_udebug_vprintf(format, ap);
    va_end(ap);
}
References procd_udebug_vprintf().
procd_udebug_set_enabled()
void procd_udebug_set_enabled (bool val)
Definition at line 53 of file procd.c.
{
    static const struct udebug_buf_meta meta = {
        .name = "procd_log",
        .format = UDEBUG_FORMAT_STRING,
    };
    if (udebug_enabled == val)
        return;
    udebug_enabled = val;
    if (!val) {
        ulog_udebug(NULL);
        udebug_buf_free(&udb);
        udebug_free(&ud);
        return;
    }
    udebug_init(&ud);
    udebug_auto_connect(&ud, NULL);
    udebug_buf_init(&udb, 1024, 64 * 1024);
    udebug_buf_add(&ud, &udb, &meta);
    ulog_udebug(&udb);
}
References ud, udb, udebug_auto_connect(), udebug_buf_add(), udebug_buf_free(), udebug_buf_init(), udebug_enabled, UDEBUG_FORMAT_STRING, udebug_free(), udebug_init(), and ulog_udebug().
Referenced by main(), and procd_udebug_cb().
procd_udebug_vprintf()
static void procd_udebug_vprintf (const char * format, va_list ap) static
Definition at line 34 of file procd.c.
{
    if (!udebug_enabled)
        return;
    udebug_entry_init(&udb);
    udebug_entry_vprintf(&udb, format, ap);
    udebug_entry_add(&udb);
}
References udb, udebug_enabled, udebug_entry_add(), udebug_entry_init(), and udebug_entry_vprintf().
Referenced by procd_udebug_printf().
usage()
static int usage (const char * prog) static
Definition at line 79 of file procd.c.
{
    fprintf(stderr, "Usage: %s [options]\n"
        "Options:\n"
        "   -s <path>   Path to ubus socket\n"
        "   -h <path>   run as hotplug daemon\n"
        "   -d <level>  Enable debug messages\n"
        "   -S      Print messages to stdout\n"
        "\n", prog);
    return 1;
}
Variable Documentation
debug
unsigned int debug
Definition at line 28 of file procd.c.
Referenced by main().
ud
struct udebug ud static
Definition at line 30 of file procd.c.
Referenced by procd_udebug_set_enabled().
udb
struct udebug_buf udb static
Definition at line 31 of file procd.c.
Referenced by procd_udebug_set_enabled(), and procd_udebug_vprintf().
udebug_enabled
bool udebug_enabled static
Definition at line 32 of file procd.c.
Referenced by procd_udebug_set_enabled(), and procd_udebug_vprintf().