zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/libubox/examples/json_script-example.c File Reference
json_script-example.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <json.h>
#include "blobmsg.h"
#include "blobmsg_json.h"
#include "json_script.h"
Functions
static void handle_command (struct json_script_ctx *ctx, const char *name, struct blob_attr *data, struct blob_attr *vars)
static struct json_script_file * handle_file (struct json_script_ctx *ctx, const char *filename)
static void usage (const char *prog, int exit_code)
int main (int argc, char *argv[])
Variables
struct json_script_ctx jctx
struct blob_buf b_vars
struct blob_buf b_script
Function Documentation
handle_command()
static void handle_command (struct json_script_ctx * ctx, const char * name, struct blob_attr * data, struct blob_attr * vars) static
Definition at line 13 of file json_script-example.c.
{
    struct blob_attr *cur;
    size_t rem;
    fprintf(stdout, "%s", name);
    blobmsg_for_each_attr(cur, data, rem)
        fprintf(stdout, " %s", (char *) blobmsg_data(cur));
    fprintf(stdout, "\n");
}
References blobmsg_data(), blobmsg_for_each_attr, and blob_attr::data.
Referenced by main().
handle_file()
static struct json_script_file * handle_file (struct json_script_ctx * ctx, const char * filename) static
Definition at line 26 of file json_script-example.c.
{
    json_object *obj;
    obj = json_object_from_file(filename);
    if (!obj) {
        fprintf(stderr, "load JSON data from %s failed.\n", filename);
        return NULL;
    }
    blob_buf_init(&b_script, 0);
    blobmsg_add_json_element(&b_script, "", obj);
    json_object_put(obj);
    return json_script_file_from_blobmsg(filename,
        blob_data(b_script.head), blob_len(b_script.head));
}
References b_script, blob_buf_init(), blob_data(), blob_len(), blobmsg_add_json_element(), blob_buf::head, and json_script_file_from_blobmsg().
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 50 of file json_script-example.c.
{
    int i;
    char *file = NULL;
    const char *prog = argv[0];
    blobmsg_buf_init(&b_vars);
    blobmsg_buf_init(&b_script);
    json_script_init(&jctx);
    jctx.handle_command = handle_command;
    jctx.handle_file = handle_file;
    for (i = 1; i < argc; i++) {
        char *sep = strchr(argv[i], '=');
        if (sep) {
            *sep = '\0';
            blobmsg_add_string(&b_vars, argv[i], sep + 1);
        } else if (!file) {
            file = argv[i];
        } else {
            usage(prog, -1);
        }
    }
    if (i < argc || !file)
        usage(prog, -2);
    json_script_run(&jctx, file, b_vars.head);
    json_script_free(&jctx);
    blob_buf_free(&b_script);
    blob_buf_free(&b_vars);
    return 0;
}
References b_script, b_vars, blob_buf_free(), blobmsg_add_string(), blobmsg_buf_init(), handle_command(), json_script_ctx::handle_command, handle_file(), json_script_ctx::handle_file, blob_buf::head, jctx, json_script_free(), json_script_init(), json_script_run(), and usage().
usage()
static void usage (const char * prog, int exit_code) static
Definition at line 44 of file json_script-example.c.
{
    fprintf(stderr, "Usage: %s [VARNAME=value] <filename_json_script>\n", prog);
    exit(exit_code);
}
Variable Documentation
b_script
struct blob_buf b_script
Definition at line 11 of file json_script-example.c.
Referenced by handle_file(), and main().
b_vars
struct blob_buf b_vars
Definition at line 10 of file json_script-example.c.
Referenced by main().
jctx
struct json_script_ctx jctx
Definition at line 9 of file json_script-example.c.
Referenced by main(), rule_handle_command(), and rule_load_script().