zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/netifd/device.h File Reference
device.h File Reference
#include <libubox/avl.h>
#include <libubox/safe_list.h>
#include <libubox/kvlist.h>
#include <netinet/in.h>
Classes
struct device_type
struct device_user
struct device_settings
struct device_vlan_range
struct device
struct device_hotplug_ops
struct bridge_vlan_port
struct bridge_vlan_hotplug_port
struct bridge_vlan
Macros
#define device_broadcast_event(dev, ev)
#define device_set_present(dev, state)
Typedefs
typedef int(* device_state_cb) (struct device *, bool up)
Enumerations
enum {
DEV_ATTR_TYPE , DEV_ATTR_MTU , DEV_ATTR_MTU6 , DEV_ATTR_MACADDR ,
DEV_ATTR_TXQUEUELEN , DEV_ATTR_ENABLED , DEV_ATTR_IPV6 , DEV_ATTR_PROMISC ,
DEV_ATTR_RPFILTER , DEV_ATTR_ACCEPTLOCAL , DEV_ATTR_IGMPVERSION , DEV_ATTR_MLDVERSION ,
DEV_ATTR_NEIGHREACHABLETIME , DEV_ATTR_DADTRANSMITS , DEV_ATTR_MULTICAST_TO_UNICAST , DEV_ATTR_MULTICAST_ROUTER ,
DEV_ATTR_MULTICAST_FAST_LEAVE , DEV_ATTR_MULTICAST , DEV_ATTR_LEARNING , DEV_ATTR_UNICAST_FLOOD ,
DEV_ATTR_NEIGHGCSTALETIME , DEV_ATTR_SENDREDIRECTS , DEV_ATTR_NEIGHLOCKTIME , DEV_ATTR_ISOLATE ,
DEV_ATTR_IP6SEGMENTROUTING , DEV_ATTR_DROP_V4_UNICAST_IN_L2_MULTICAST , DEV_ATTR_DROP_V6_UNICAST_IN_L2_MULTICAST , DEV_ATTR_DROP_GRATUITOUS_ARP ,
DEV_ATTR_DROP_UNSOLICITED_NA , DEV_ATTR_ARP_ACCEPT , DEV_ATTR_AUTH , DEV_ATTR_AUTH_VLAN ,
DEV_ATTR_SPEED , DEV_ATTR_DUPLEX , DEV_ATTR_VLAN , DEV_ATTR_PAUSE ,
DEV_ATTR_ASYM_PAUSE , DEV_ATTR_RXPAUSE , DEV_ATTR_TXPAUSE , DEV_ATTR_AUTONEG ,
DEV_ATTR_GRO , DEV_ATTR_MASTER , DEV_ATTR_EEE , __DEV_ATTR_MAX
}
enum dev_change_type { DEV_CONFIG_NO_CHANGE , DEV_CONFIG_APPLIED , DEV_CONFIG_RESTART , DEV_CONFIG_RECREATE }
enum {
DEV_OPT_MTU = (1ULL << 0) , DEV_OPT_MACADDR = (1ULL << 1) , DEV_OPT_TXQUEUELEN = (1ULL << 2) , DEV_OPT_IPV6 = (1ULL << 3) ,
DEV_OPT_PROMISC = (1ULL << 4) , DEV_OPT_RPFILTER = (1ULL << 5) , DEV_OPT_ACCEPTLOCAL = (1ULL << 6) , DEV_OPT_IGMPVERSION = (1ULL << 7) ,
DEV_OPT_MLDVERSION = (1ULL << 8) , DEV_OPT_NEIGHREACHABLETIME = (1ULL << 9) , DEV_OPT_DEFAULT_MACADDR = (1ULL << 10) , DEV_OPT_AUTH = (1ULL << 11) ,
DEV_OPT_MTU6 = (1ULL << 12) , DEV_OPT_DADTRANSMITS = (1ULL << 13) , DEV_OPT_MULTICAST_TO_UNICAST = (1ULL << 14) , DEV_OPT_MULTICAST_ROUTER = (1ULL << 15) ,
DEV_OPT_MULTICAST = (1ULL << 16) , DEV_OPT_LEARNING = (1ULL << 17) , DEV_OPT_UNICAST_FLOOD = (1ULL << 18) , DEV_OPT_NEIGHGCSTALETIME = (1ULL << 19) ,
DEV_OPT_MULTICAST_FAST_LEAVE = (1ULL << 20) , DEV_OPT_SENDREDIRECTS = (1ULL << 21) , DEV_OPT_NEIGHLOCKTIME = (1ULL << 22) , DEV_OPT_ISOLATE = (1ULL << 23) ,
DEV_OPT_IP6SEGMENTROUTING = (1ULL << 24) , DEV_OPT_DROP_V4_UNICAST_IN_L2_MULTICAST = (1ULL << 25) , DEV_OPT_DROP_V6_UNICAST_IN_L2_MULTICAST = (1ULL << 26) , DEV_OPT_DROP_GRATUITOUS_ARP = (1ULL << 27) ,
DEV_OPT_DROP_UNSOLICITED_NA = (1ULL << 28) , DEV_OPT_ARP_ACCEPT = (1ULL << 29) , DEV_OPT_SPEED = (1ULL << 30) , DEV_OPT_DUPLEX = (1ULL << 31) ,
DEV_OPT_PAUSE = (1ULL << 32) , DEV_OPT_ASYM_PAUSE = (1ULL << 33) , DEV_OPT_RXPAUSE = (1ULL << 34) , DEV_OPT_TXPAUSE = (1ULL << 35) ,
DEV_OPT_AUTONEG = (1ULL << 36) , DEV_OPT_GRO = (1ULL << 37) , DEV_OPT_MASTER = (1ULL << 38) , DEV_OPT_EEE = (1ULL << 39)
}
enum device_event {
DEV_EVENT_ADD , DEV_EVENT_REMOVE , DEV_EVENT_UPDATE_IFNAME , DEV_EVENT_UPDATE_IFINDEX ,
DEV_EVENT_SETUP , DEV_EVENT_TEARDOWN , DEV_EVENT_UP , DEV_EVENT_DOWN ,
DEV_EVENT_AUTH_UP , DEV_EVENT_LINK_UP , DEV_EVENT_LINK_DOWN , DEV_EVENT_TOPO_CHANGE ,
__DEV_EVENT_MAX
}
enum bridge_vlan_flags { BRVLAN_F_SELF = (1 << 0) , BRVLAN_F_PVID = (1 << 1) , BRVLAN_F_UNTAGGED = (1 << 2) }
Functions
void device_vlan_update (bool done)
void device_stp_init (void)
int device_type_add (struct device_type *devtype)
struct device_type * device_type_get (const char *tname)
struct device * device_create (const char *name, struct device_type *type, struct blob_attr *config)
void device_merge_settings (struct device *dev, struct device_settings *n)
void device_init_settings (struct device *dev, struct blob_attr **tb)
void device_init_pending (void)
enum dev_change_type device_apply_config (struct device *dev, struct device_type *type, struct blob_attr *config)
void device_reset_config (void)
void device_reset_old (void)
int device_init_virtual (struct device *dev, struct device_type *type, const char *name)
int device_init (struct device *dev, struct device_type *type, const char *ifname)
void device_cleanup (struct device *dev)
struct device * device_find (const char *name)
struct device * __device_get (const char *name, int create, bool check_vlan)
static struct device * device_get (const char *name, int create)
void device_add_user (struct device_user *dep, struct device *dev)
void device_remove_user (struct device_user *dep)
const char * device_event_name (enum device_event ev)
void __device_broadcast_event (struct device *dev, enum device_event ev)
void _device_set_present (struct device *dev, bool state)
void device_set_link (struct device *dev, bool state)
void device_set_ifindex (struct device *dev, int ifindex)
int device_set_ifname (struct device *dev, const char *name)
void device_refresh_present (struct device *dev)
int device_claim (struct device_user *dep)
void device_release (struct device_user *dep)
int device_check_state (struct device *dev)
void device_dump_status (struct blob_buf *b, struct device *dev)
void device_free_unused (void)
struct device * get_vlan_device_chain (const char *ifname, int create)
void alias_notify_device (const char *name, struct device *dev)
struct device * device_alias_get (const char *name)
void device_set_auth_status (struct device *dev, bool value, struct blob_attr *vlans)
static void device_set_deferred (struct device *dev, bool value)
static void device_set_disabled (struct device *dev, bool value)
static bool device_link_active (struct device *dev)
bool device_check_ip6segmentrouting (void)
void device_hotplug_event (const char *name, bool add)
Variables
const struct uci_blob_param_list device_attr_list
struct device_type simple_device_type
struct device_type tunnel_device_type
Class Documentation
device_type
struct device_type
Definition at line 85 of file device.h.
Class Members
bool bridge_capability
int(*)(struct device *) check_state
void(*)(struct device *) config_init
const struct uci_blob_param_list * config_params
struct device *(*)(const char *name, struct device_type *devtype, struct blob_attr *attr) create
void(*)(struct device *, struct blob_buf *buf) dump_info
void(*)(struct device *, struct blob_buf *buf) dump_stats
void(*)(struct device *) free
struct list_head list
const char * name
const char * name_prefix
enum dev_change_type(*)(struct device *, struct blob_attr *) reload
void(*)(struct device *) stp_init
void(*)(struct device *) vlan_update
device_user
struct device_user
Definition at line 175 of file device.h.
Class Members
bool alias
void(*)(struct device_user *, enum device_event) cb
bool claimed
struct device * dev
uint8_t ev_idx[__DEV_EVENT_MAX]
bool hotplug
struct safe_list list
device_settings
struct device_settings
Definition at line 188 of file device.h.
Class Members
bool acceptlocal
bool arp_accept
bool asym_pause
bool auth
bool autoneg
unsigned int dadtransmits
bool drop_gratuitous_arp
bool drop_unsolicited_na
bool drop_v4_unicast_in_l2_multicast
bool drop_v6_unicast_in_l2_multicast
bool duplex
bool eee
uint64_t flags
bool gro
unsigned int igmpversion
bool ip6segmentrouting
bool ipv6
bool isolate
bool learning
uint8_t macaddr[6]
int master_ifindex
unsigned int mldversion
unsigned int mtu
unsigned int mtu6
bool multicast
bool multicast_fast_leave
unsigned int multicast_router
bool multicast_to_unicast
unsigned int neigh4gcstaletime
int neigh4locktime
unsigned int neigh4reachabletime
unsigned int neigh6gcstaletime
unsigned int neigh6reachabletime
bool pause
bool promisc
unsigned int rpfilter
bool rxpause
bool sendredirects
unsigned int speed
bool txpause
unsigned int txqueuelen
bool unicast_flood
uint64_t valid_flags
device_vlan_range
struct device_vlan_range
Definition at line 234 of file device.h.
Class Members
uint16_t end
uint16_t start
device
struct device
Definition at line 242 of file device.h.
Class Members
int active
struct safe_list aliases
bool auth_status
struct blob_attr * auth_vlans
struct avl_node avl
bool bpdu_filter
struct blob_attr * config
struct blob_attr * config_auth_vlans
struct interface * config_iface
bool config_pending
bool current_config
bool default_config
bool deferred
bool disabled
bool external
struct device_vlan_range * extra_vlan
bool hidden
const struct device_hotplug_ops * hotplug_ops
bool iface_config
int ifindex
char ifname[IFNAMSIZ]
bool link_active
int n_extra_vlan
struct device_settings orig_settings
struct device_user parent
bool present
device_state_cb set_state
struct device_settings settings
bool sys_present
struct device_type * type
struct safe_list users
struct kvlist vlan_aliases
struct vlist_tree vlans
bool wireless
bool wireless_ap
bool wireless_isolate
bool wireless_proxyarp
device_hotplug_ops
struct device_hotplug_ops
Definition at line 297 of file device.h.
Class Members
int(*)(struct device *main, struct device *member, struct blob_attr *vlan) add
int(*)(struct device *main, struct device *member, struct blob_attr *vlan) del
int(*)(struct device *dev, struct device **bridge_dev) prepare
bridge_vlan_port
struct bridge_vlan_port
Definition at line 309 of file device.h.
Class Members
int8_t check
uint16_t flags
const char * ifname
bridge_vlan_hotplug_port
struct bridge_vlan_hotplug_port
Definition at line 315 of file device.h.
Class Members
struct list_head list
struct bridge_vlan_port port
bridge_vlan
struct bridge_vlan
Definition at line 320 of file device.h.
Class Members
struct list_head hotplug_ports
bool local
int n_ports
struct vlist_node node
bool pending
struct bridge_vlan_port * ports
uint16_t vid
Macro Definition Documentation
device_broadcast_event
#define device_broadcast_event (dev, ev)
Value:
    do {                    \
    struct device *__ev_dev = (dev);                    \
    D(DEVICE, "%s: event (%s)",                     \
      (__ev_dev && __ev_dev->ifname[0] ? __ev_dev->ifname : "(none)"),  \
      device_event_name(ev));                       \
    __device_broadcast_event(__ev_dev, ev);                 \
} while (0)
Definition at line 370 of file device.h.
#define device_broadcast_event(dev, ev) do {                    \
    struct device *__ev_dev = (dev);                    \
    D(DEVICE, "%s: event (%s)",                     \
      (__ev_dev && __ev_dev->ifname[0] ? __ev_dev->ifname : "(none)"),  \
      device_event_name(ev));                       \
    __device_broadcast_event(__ev_dev, ev);                 \
} while (0)
Referenced by __device_set_present(), alias_device_cb(), bridge_disable_member(), bridge_enable_member(), device_claim(), device_release(), device_set_auth_status(), device_set_ifindex(), device_set_ifname(), device_set_link(), extdev_bridge_disable_member(), extdev_bridge_enable_member(), extdev_hotplug_add(), vlan_dev_cb(), and vlandev_base_cb().
device_set_present
#define device_set_present (dev, state)
Value:
    do {                    \
    struct device *__ev_dev = (dev);                    \
    bool __ev_state = state;                        \
    D(DEVICE, "%s: set present=%d",                     \
      (__ev_dev && __ev_dev->ifname[0] ? __ev_dev->ifname : "(none)"),  \
      __ev_state);                              \
    _device_set_present(__ev_dev, __ev_state);              \
} while (0)
Definition at line 379 of file device.h.
#define device_set_present(dev, state) do {                 \
    struct device *__ev_dev = (dev);                    \
    bool __ev_state = state;                        \
    D(DEVICE, "%s: set present=%d",                     \
      (__ev_dev && __ev_dev->ifname[0] ? __ev_dev->ifname : "(none)"),  \
      __ev_state);                              \
    _device_set_present(__ev_dev, __ev_state);              \
} while (0)
Referenced by __bridge_config_init(), __device_get(), __reload(), alias_device_cb(), alias_set_device(), bonding_enable_port(), bonding_free_port(), bonding_hotplug_prepare(), bonding_port_cb(), bonding_remove_port(), bonding_set_up(), bridge_config_init(), bridge_enable_member(), bridge_free_member(), bridge_hotplug_prepare(), bridge_member_cb(), bridge_remove_member(), bridge_set_up(), cb_if_check_error(), device_apply_config(), device_hotplug_event(), device_replace(), extdev_bridge_enable_member(), extdev_bridge_free_member(), extdev_bridge_member_cb(), extdev_bridge_remove_member(), extdev_bridge_set_up(), extdev_hotplug_prepare(), interface_handle_link(), macvlan_base_cb(), proto_shell_update_link(), system_device_update_state(), system_if_check(), tunnel_create(), veth_config_init(), vlan_dev_cb(), and vlandev_base_cb().
Typedef Documentation
device_state_cb
typedef int(* device_state_cb) (struct device *, bool up)
Definition at line 29 of file device.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
DEV_ATTR_TYPE
DEV_ATTR_MTU
DEV_ATTR_MTU6
DEV_ATTR_MACADDR
DEV_ATTR_TXQUEUELEN
DEV_ATTR_ENABLED
DEV_ATTR_IPV6
DEV_ATTR_PROMISC
DEV_ATTR_RPFILTER
DEV_ATTR_ACCEPTLOCAL
DEV_ATTR_IGMPVERSION
DEV_ATTR_MLDVERSION
DEV_ATTR_NEIGHREACHABLETIME
DEV_ATTR_DADTRANSMITS
DEV_ATTR_MULTICAST_TO_UNICAST
DEV_ATTR_MULTICAST_ROUTER
DEV_ATTR_MULTICAST_FAST_LEAVE
DEV_ATTR_MULTICAST
DEV_ATTR_LEARNING
DEV_ATTR_UNICAST_FLOOD
DEV_ATTR_NEIGHGCSTALETIME
DEV_ATTR_SENDREDIRECTS
DEV_ATTR_NEIGHLOCKTIME
DEV_ATTR_ISOLATE
DEV_ATTR_IP6SEGMENTROUTING
DEV_ATTR_DROP_V4_UNICAST_IN_L2_MULTICAST
DEV_ATTR_DROP_V6_UNICAST_IN_L2_MULTICAST
DEV_ATTR_DROP_GRATUITOUS_ARP
DEV_ATTR_DROP_UNSOLICITED_NA
DEV_ATTR_ARP_ACCEPT
DEV_ATTR_AUTH
DEV_ATTR_AUTH_VLAN
DEV_ATTR_SPEED
DEV_ATTR_DUPLEX
DEV_ATTR_VLAN
DEV_ATTR_PAUSE
DEV_ATTR_ASYM_PAUSE
DEV_ATTR_RXPAUSE
DEV_ATTR_TXPAUSE
DEV_ATTR_AUTONEG
DEV_ATTR_GRO
DEV_ATTR_MASTER
DEV_ATTR_EEE
__DEV_ATTR_MAX
Definition at line 31 of file device.h.
     {
    DEV_ATTR_TYPE,
    DEV_ATTR_MTU,
    DEV_ATTR_MTU6,
    DEV_ATTR_MACADDR,
    DEV_ATTR_TXQUEUELEN,
    DEV_ATTR_ENABLED,
    DEV_ATTR_IPV6,
    DEV_ATTR_PROMISC,
    DEV_ATTR_RPFILTER,
    DEV_ATTR_ACCEPTLOCAL,
    DEV_ATTR_IGMPVERSION,
    DEV_ATTR_MLDVERSION,
    DEV_ATTR_NEIGHREACHABLETIME,
    DEV_ATTR_DADTRANSMITS,
    DEV_ATTR_MULTICAST_TO_UNICAST,
    DEV_ATTR_MULTICAST_ROUTER,
    DEV_ATTR_MULTICAST_FAST_LEAVE,
    DEV_ATTR_MULTICAST,
    DEV_ATTR_LEARNING,
    DEV_ATTR_UNICAST_FLOOD,
    DEV_ATTR_NEIGHGCSTALETIME,
    DEV_ATTR_SENDREDIRECTS,
    DEV_ATTR_NEIGHLOCKTIME,
    DEV_ATTR_ISOLATE,
    DEV_ATTR_IP6SEGMENTROUTING,
    DEV_ATTR_DROP_V4_UNICAST_IN_L2_MULTICAST,
    DEV_ATTR_DROP_V6_UNICAST_IN_L2_MULTICAST,
    DEV_ATTR_DROP_GRATUITOUS_ARP,
    DEV_ATTR_DROP_UNSOLICITED_NA,
    DEV_ATTR_ARP_ACCEPT,
    DEV_ATTR_AUTH,
    DEV_ATTR_AUTH_VLAN,
    DEV_ATTR_SPEED,
    DEV_ATTR_DUPLEX,
    DEV_ATTR_VLAN,
    DEV_ATTR_PAUSE,
    DEV_ATTR_ASYM_PAUSE,
    DEV_ATTR_RXPAUSE,
    DEV_ATTR_TXPAUSE,
    DEV_ATTR_AUTONEG,
    DEV_ATTR_GRO,
    DEV_ATTR_MASTER,
    DEV_ATTR_EEE,
    __DEV_ATTR_MAX,
};
anonymous enum
anonymous enum
Enumerator
DEV_OPT_MTU (1ULL << 0)
DEV_OPT_MACADDR (1ULL << 1)
DEV_OPT_TXQUEUELEN (1ULL << 2)
DEV_OPT_IPV6 (1ULL << 3)
DEV_OPT_PROMISC (1ULL << 4)
DEV_OPT_RPFILTER (1ULL << 5)
DEV_OPT_ACCEPTLOCAL (1ULL << 6)
DEV_OPT_IGMPVERSION (1ULL << 7)
DEV_OPT_MLDVERSION (1ULL << 8)
DEV_OPT_NEIGHREACHABLETIME (1ULL << 9)
DEV_OPT_DEFAULT_MACADDR (1ULL << 10)
DEV_OPT_AUTH (1ULL << 11)
DEV_OPT_MTU6 (1ULL << 12)
DEV_OPT_DADTRANSMITS (1ULL << 13)
DEV_OPT_MULTICAST_TO_UNICAST (1ULL << 14)
DEV_OPT_MULTICAST_ROUTER (1ULL << 15)
DEV_OPT_MULTICAST (1ULL << 16)
DEV_OPT_LEARNING (1ULL << 17)
DEV_OPT_UNICAST_FLOOD (1ULL << 18)
DEV_OPT_NEIGHGCSTALETIME (1ULL << 19)
DEV_OPT_MULTICAST_FAST_LEAVE (1ULL << 20)
DEV_OPT_SENDREDIRECTS (1ULL << 21)
DEV_OPT_NEIGHLOCKTIME (1ULL << 22)
DEV_OPT_ISOLATE (1ULL << 23)
DEV_OPT_IP6SEGMENTROUTING (1ULL << 24)
DEV_OPT_DROP_V4_UNICAST_IN_L2_MULTICAST (1ULL << 25)
DEV_OPT_DROP_V6_UNICAST_IN_L2_MULTICAST (1ULL << 26)
DEV_OPT_DROP_GRATUITOUS_ARP (1ULL << 27)
DEV_OPT_DROP_UNSOLICITED_NA (1ULL << 28)
DEV_OPT_ARP_ACCEPT (1ULL << 29)
DEV_OPT_SPEED (1ULL << 30)
DEV_OPT_DUPLEX (1ULL << 31)
DEV_OPT_PAUSE (1ULL << 32)
DEV_OPT_ASYM_PAUSE (1ULL << 33)
DEV_OPT_RXPAUSE (1ULL << 34)
DEV_OPT_TXPAUSE (1ULL << 35)
DEV_OPT_AUTONEG (1ULL << 36)
DEV_OPT_GRO (1ULL << 37)
DEV_OPT_MASTER (1ULL << 38)
DEV_OPT_EEE (1ULL << 39)
Definition at line 106 of file device.h.
     {
    DEV_OPT_MTU         = (1ULL << 0),
    DEV_OPT_MACADDR         = (1ULL << 1),
    DEV_OPT_TXQUEUELEN      = (1ULL << 2),
    DEV_OPT_IPV6            = (1ULL << 3),
    DEV_OPT_PROMISC         = (1ULL << 4),
    DEV_OPT_RPFILTER        = (1ULL << 5),
    DEV_OPT_ACCEPTLOCAL     = (1ULL << 6),
    DEV_OPT_IGMPVERSION     = (1ULL << 7),
    DEV_OPT_MLDVERSION      = (1ULL << 8),
    DEV_OPT_NEIGHREACHABLETIME  = (1ULL << 9),
    DEV_OPT_DEFAULT_MACADDR     = (1ULL << 10),
    DEV_OPT_AUTH            = (1ULL << 11),
    DEV_OPT_MTU6            = (1ULL << 12),
    DEV_OPT_DADTRANSMITS        = (1ULL << 13),
    DEV_OPT_MULTICAST_TO_UNICAST    = (1ULL << 14),
    DEV_OPT_MULTICAST_ROUTER    = (1ULL << 15),
    DEV_OPT_MULTICAST       = (1ULL << 16),
    DEV_OPT_LEARNING        = (1ULL << 17),
    DEV_OPT_UNICAST_FLOOD       = (1ULL << 18),
    DEV_OPT_NEIGHGCSTALETIME    = (1ULL << 19),
    DEV_OPT_MULTICAST_FAST_LEAVE    = (1ULL << 20),
    DEV_OPT_SENDREDIRECTS       = (1ULL << 21),
    DEV_OPT_NEIGHLOCKTIME       = (1ULL << 22),
    DEV_OPT_ISOLATE         = (1ULL << 23),
    DEV_OPT_IP6SEGMENTROUTING   = (1ULL << 24),
    DEV_OPT_DROP_V4_UNICAST_IN_L2_MULTICAST = (1ULL << 25),
    DEV_OPT_DROP_V6_UNICAST_IN_L2_MULTICAST = (1ULL << 26),
    DEV_OPT_DROP_GRATUITOUS_ARP = (1ULL << 27),
    DEV_OPT_DROP_UNSOLICITED_NA = (1ULL << 28),
    DEV_OPT_ARP_ACCEPT      = (1ULL << 29),
    DEV_OPT_SPEED           = (1ULL << 30),
    DEV_OPT_DUPLEX          = (1ULL << 31),
    DEV_OPT_PAUSE           = (1ULL << 32),
    DEV_OPT_ASYM_PAUSE      = (1ULL << 33),
    DEV_OPT_RXPAUSE         = (1ULL << 34),
    DEV_OPT_TXPAUSE         = (1ULL << 35),
    DEV_OPT_AUTONEG         = (1ULL << 36),
    DEV_OPT_GRO         = (1ULL << 37),
    DEV_OPT_MASTER          = (1ULL << 38),
    DEV_OPT_EEE         = (1ULL << 39),
};
bridge_vlan_flags
enum bridge_vlan_flags
Enumerator
BRVLAN_F_SELF (1 << 0)
BRVLAN_F_PVID (1 << 1)
BRVLAN_F_UNTAGGED (1 << 2)
Definition at line 303 of file device.h.
                       {
    BRVLAN_F_SELF =     (1 << 0),
    BRVLAN_F_PVID =     (1 << 1),
    BRVLAN_F_UNTAGGED = (1 << 2),
};
dev_change_type
enum dev_change_type
Enumerator
DEV_CONFIG_NO_CHANGE
DEV_CONFIG_APPLIED
DEV_CONFIG_RESTART
DEV_CONFIG_RECREATE
Definition at line 78 of file device.h.
                     {
    DEV_CONFIG_NO_CHANGE,
    DEV_CONFIG_APPLIED,
    DEV_CONFIG_RESTART,
    DEV_CONFIG_RECREATE,
};
device_event
enum device_event
Enumerator
DEV_EVENT_ADD
DEV_EVENT_REMOVE
DEV_EVENT_UPDATE_IFNAME
DEV_EVENT_UPDATE_IFINDEX
DEV_EVENT_SETUP
DEV_EVENT_TEARDOWN
DEV_EVENT_UP
DEV_EVENT_DOWN
DEV_EVENT_AUTH_UP
DEV_EVENT_LINK_UP
DEV_EVENT_LINK_DOWN
DEV_EVENT_TOPO_CHANGE
__DEV_EVENT_MAX
Definition at line 150 of file device.h.
                  {
    DEV_EVENT_ADD,
    DEV_EVENT_REMOVE,
    DEV_EVENT_UPDATE_IFNAME,
    DEV_EVENT_UPDATE_IFINDEX,
    DEV_EVENT_SETUP,
    DEV_EVENT_TEARDOWN,
    DEV_EVENT_UP,
    DEV_EVENT_DOWN,
    DEV_EVENT_AUTH_UP,
    DEV_EVENT_LINK_UP,
    DEV_EVENT_LINK_DOWN,
    /* Topology changed (i.e. bridge member added) */
    DEV_EVENT_TOPO_CHANGE,
    __DEV_EVENT_MAX
};
Function Documentation
__device_broadcast_event()
void __device_broadcast_event (struct device * dev, enum device_event ev)
Definition at line 645 of file device.c.
{
    const char *ev_name;
    int dev_ev = ev;
    safe_list_for_each(&dev->aliases, device_broadcast_cb, &dev_ev);
    safe_list_for_each(&dev->users, device_broadcast_cb, &dev_ev);
    switch (ev) {
    case DEV_EVENT_ADD:
    case DEV_EVENT_REMOVE:
    case DEV_EVENT_UP:
    case DEV_EVENT_DOWN:
    case DEV_EVENT_AUTH_UP:
    case DEV_EVENT_LINK_UP:
    case DEV_EVENT_LINK_DOWN:
    case DEV_EVENT_TOPO_CHANGE:
        break;
    default:
        return;
    }
    ev_name = device_event_name(ev);
    if (!dev->ifname[0])
        return;
    blob_buf_init(&b, 0);
    blobmsg_add_string(&b, "name", dev->ifname);
    blobmsg_add_u8(&b, "auth_status", dev->auth_status);
    blobmsg_add_u8(&b, "present", dev->present);
    blobmsg_add_u8(&b, "active", dev->active);
    blobmsg_add_u8(&b, "link_active", dev->link_active);
    netifd_ubus_device_notify(ev_name, b.head, -1);
}
References device::active, device::aliases, device::auth_status, b, blob_buf_init(), blobmsg_add_string(), blobmsg_add_u8(), device_user::dev, DEV_EVENT_ADD, DEV_EVENT_AUTH_UP, DEV_EVENT_DOWN, DEV_EVENT_LINK_DOWN, DEV_EVENT_LINK_UP, DEV_EVENT_REMOVE, DEV_EVENT_TOPO_CHANGE, DEV_EVENT_UP, device_broadcast_cb(), device_event_name(), blob_buf::head, device::ifname, device::link_active, netifd_ubus_device_notify(), device::present, safe_list_for_each(), and device::users.
__device_get()
struct device * __device_get (const char * name, int create, bool check_vlan)
Definition at line 857 of file device.c.
{
    struct device *dev;
    dev = avl_find_element(&devices, name, dev, avl);
    if (!dev && check_vlan && strchr(name, '.'))
        return get_vlan_device_chain(name, create);
    if (name[0] == '@')
        return device_alias_get(name + 1);
    if (dev) {
        if (create > 1 && !dev->external) {
            dev->external = true;
            device_set_present(dev, true);
        }
        return dev;
    }
    if (!create)
        return NULL;
    return device_create_default(name, create > 1);
}
References device::avl, avl_find_element, device_alias_get(), device_create_default(), device_set_present, devices, device::external, and get_vlan_device_chain().
Referenced by device_get(), get_vlan_device_chain(), and wireless_interface_handle_link().
_device_set_present()
void _device_set_present (struct device * dev, bool state)
Definition at line 964 of file device.c.
{
    if (dev->sys_present == state)
        return;
    D(DEVICE, "%s '%s' %s present", dev->type->name, dev->ifname, state ? "is now" : "is no longer" );
    dev->sys_present = state;
    if (!state)
        __device_set_present(dev, state, true);
    else
        device_refresh_present(dev);
    if (!state)
        safe_list_for_each(&dev->users, device_release_cb, NULL);
}
References __device_set_present(), D, device_user::dev, device_refresh_present(), device_release_cb(), device::ifname, device_type::name, safe_list_for_each(), state, device::sys_present, device::type, and device::users.
alias_notify_device()
void alias_notify_device (const char * name, struct device * dev)
Definition at line 177 of file alias.c.
{
    struct alias_device *alias;
    alias = avl_find_element(&aliases, name, alias, avl);
    if (alias)
        alias_set_device(alias, dev);
}
References alias_set_device(), aliases, alias_device::avl, avl_find_element, alias_device::dev, and alias_device::name.
Referenced by interface_event(), and netifd_handle_alias().
device_add_user()
void device_add_user (struct device_user * dep, struct device * dev)
Definition at line 1067 of file device.c.
{
    if (dep->dev == dev)
        return;
    if (dep->dev)
        device_remove_user(dep);
    if (!dev)
        return;
    __device_add_user(dep, dev);
}
References __device_add_user(), device_user::dev, and device_remove_user().
Referenced by alias_set_device(), bonding_port_update(), bridge_member_update(), extdev_bridge_member_update(), get_vlan_device(), interface_add_link(), interface_set_l3_dev(), interface_set_main_dev(), macvlan_config_init(), simple_device_set_state(), and vlandev_config_init().
device_alias_get()
struct device * device_alias_get (const char * name)
Definition at line 187 of file alias.c.
{
    struct alias_device *alias;
    alias = avl_find_element(&aliases, name, alias, avl);
    if (alias)
        return &alias->dev;
    return alias_device_create(name, &alias_device_type, NULL);
}
References alias_device_create(), alias_device_type, aliases, alias_device::avl, avl_find_element, alias_device::dev, and alias_device::name.
Referenced by __device_get().
device_apply_config()
enum dev_change_type device_apply_config (struct device * dev, struct device_type * type, struct blob_attr * config)
Definition at line 1192 of file device.c.
{
    enum dev_change_type change;
    change = device_set_config(dev, type, config);
    switch (change) {
        case DEV_CONFIG_RESTART:
        case DEV_CONFIG_APPLIED:
            D(DEVICE, "Device '%s': config applied", dev->ifname);
            config = blob_memdup(config);
            free(dev->config);
            dev->config = config;
            if (change == DEV_CONFIG_RESTART && dev->present) {
                int ret = 0;
                device_set_present(dev, false);
                if (dev->active) {
                    ret = dev->set_state(dev, false);
                    if (!ret)
                        ret = dev->set_state(dev, true);
                }
                if (!ret)
                    device_set_present(dev, true);
            }
            break;
        case DEV_CONFIG_NO_CHANGE:
            D(DEVICE, "Device '%s': no configuration change", dev->ifname);
            break;
        case DEV_CONFIG_RECREATE:
            break;
    }
    return change;
}
References device::active, blob_memdup(), config, device::config, D, DEV_CONFIG_APPLIED, DEV_CONFIG_NO_CHANGE, DEV_CONFIG_RECREATE, DEV_CONFIG_RESTART, device_set_config(), device_set_present, device::ifname, device::present, device::set_state, and type.
Referenced by config_init_devices(), device_create(), interface_set_device_config(), and tunnel_create().
device_check_ip6segmentrouting()
bool device_check_ip6segmentrouting (void)
Definition at line 1151 of file device.c.
{
    struct device *dev;
    bool ip6segmentrouting = false;
    avl_for_each_element(&devices, dev, avl)
        ip6segmentrouting |= dev->settings.ip6segmentrouting;
    return ip6segmentrouting;
}
References device::avl, avl_for_each_element, devices, device_settings::ip6segmentrouting, and device::settings.
Referenced by system_if_apply_settings().
device_check_state()
int device_check_state (struct device * dev)
Definition at line 767 of file device.c.
{
    if (!dev->type->check_state)
        return simple_device_type.check_state(dev);
    return dev->type->check_state(dev);
}
References device_type::check_state, simple_device_type, and device::type.
Referenced by alias_device_create(), device_create(), device_create_default(), and device_init_pending().
device_claim()
int device_claim (struct device_user * dep)
Definition at line 713 of file device.c.
{
    struct device *dev = dep->dev;
    int ret = 0;
    if (dep->claimed)
        return 0;
    if (!dev)
        return -1;
    dep->claimed = true;
    D(DEVICE, "Claim %s %s, new active count: %d", dev->type->name, dev->ifname, dev->active + 1);
    if (++dev->active != 1)
        return 0;
    device_broadcast_event(dev, DEV_EVENT_SETUP);
    device_fill_default_settings(dev);
    ret = dev->set_state(dev, true);
    if (ret == 0)
        device_broadcast_event(dev, DEV_EVENT_UP);
    else {
        D(DEVICE, "claim %s %s failed: %d", dev->type->name, dev->ifname, ret);
        dev->active = 0;
        dep->claimed = false;
    }
    return ret;
}
References device::active, device_user::claimed, D, device_user::dev, DEV_EVENT_SETUP, DEV_EVENT_UP, device_broadcast_event, device_fill_default_settings(), device::ifname, device_type::name, device::set_state, and device::type.
Referenced by alias_device_set_state(), bonding_enable_port(), bridge_enable_member(), extdev_bridge_enable_member(), interface_set_l3_dev(), interface_set_main_dev(), interface_set_up(), macvlan_set_up(), proto_shell_update_link(), simple_device_set_state(), vlan_set_device_state(), and vlandev_set_up().
device_cleanup()
void device_cleanup (struct device * dev)
Definition at line 904 of file device.c.
{
    D(DEVICE, "Clean up device '%s'", dev->ifname);
    safe_list_for_each(&dev->users, device_cleanup_cb, NULL);
    safe_list_for_each(&dev->aliases, device_cleanup_cb, NULL);
    device_delete(dev);
}
References device::aliases, D, device_user::dev, device_cleanup_cb(), device_delete(), device::ifname, safe_list_for_each(), and device::users.
Referenced by __create(), bonding_create(), bridge_create(), device_create_default(), device_free(), free_vlan_if(), get_vlan_device(), macvlan_create(), tunnel_create(), veth_create(), and vlandev_create().
device_create()
struct device * device_create (const char * name, struct device_type * type, struct blob_attr * config)
Definition at line 1281 of file device.c.
{
    struct device *odev = NULL, *dev;
    enum dev_change_type change;
    odev = device_find(name);
    if (odev) {
        odev->current_config = true;
        change = device_apply_config(odev, type, config);
        switch (change) {
        case DEV_CONFIG_RECREATE:
            D(DEVICE, "Device '%s': recreate device", odev->ifname);
            device_delete(odev);
            break;
        default:
            return odev;
        }
    } else
        D(DEVICE, "Create new device '%s' (%s)", name, type->name);
    config = blob_memdup(config);
    if (!config)
        return NULL;
    dev = type->create(name, type, config);
    if (!dev)
        return NULL;
    dev->current_config = true;
    dev->config = config;
    if (odev)
        device_replace(dev, odev);
    if (!config_init && dev->config_pending) {
        type->config_init(dev);
        dev->config_pending = false;
    }
    device_check_state(dev);
    return dev;
}
References blob_memdup(), config, config_init, device::current_config, D, DEV_CONFIG_RECREATE, device_apply_config(), device_check_state(), device_delete(), device_find(), device_replace(), device::ifname, and type.
Referenced by config_init_devices(), config_parse_bridge_interface(), and proto_shell_create_tunnel().
device_dump_status()
void device_dump_status (struct blob_buf * b, struct device * dev)
Definition at line 1326 of file device.c.
{
    struct device_settings st;
    void *c, *s;
    if (!dev) {
        avl_for_each_element(&devices, dev, avl) {
            if (!dev->present)
                continue;
            c = blobmsg_open_table(b, dev->ifname);
            device_dump_status(b, dev);
            blobmsg_close_table(b, c);
        }
        return;
    }
    blobmsg_add_u8(b, "external", dev->external);
    blobmsg_add_u8(b, "present", dev->present);
    blobmsg_add_string(b, "type", dev->type->name);
    if (!dev->present)
        return;
    blobmsg_add_u8(b, "up", !!dev->active);
    blobmsg_add_u8(b, "carrier", !!dev->link_active);
    blobmsg_add_u8(b, "auth_status", !!dev->auth_status);
    if (dev->type->dump_info)
        dev->type->dump_info(dev, b);
    else
        system_if_dump_info(dev, b);
    if (dev->active) {
        device_merge_settings(dev, &st);
        if (st.flags & DEV_OPT_MASTER) {
            char buf[64], *devname;
            devname = if_indextoname(st.master_ifindex, buf);
            if (devname)
                blobmsg_add_string(b, "conduit", devname);
        }
        if (st.flags & DEV_OPT_MTU)
            blobmsg_add_u32(b, "mtu", st.mtu);
        if (st.flags & DEV_OPT_MTU6)
            blobmsg_add_u32(b, "mtu6", st.mtu6);
        if (st.flags & DEV_OPT_MACADDR)
            blobmsg_add_string(b, "macaddr", format_macaddr(st.macaddr));
        if (st.flags & DEV_OPT_TXQUEUELEN)
            blobmsg_add_u32(b, "txqueuelen", st.txqueuelen);
        if (st.flags & DEV_OPT_IPV6)
            blobmsg_add_u8(b, "ipv6", st.ipv6);
        if (st.flags & DEV_OPT_IP6SEGMENTROUTING)
            blobmsg_add_u8(b, "ip6segmentrouting", st.ip6segmentrouting);
        if (st.flags & DEV_OPT_PROMISC)
            blobmsg_add_u8(b, "promisc", st.promisc);
        if (st.flags & DEV_OPT_RPFILTER)
            blobmsg_add_u32(b, "rpfilter", st.rpfilter);
        if (st.flags & DEV_OPT_ACCEPTLOCAL)
            blobmsg_add_u8(b, "acceptlocal", st.acceptlocal);
        if (st.flags & DEV_OPT_IGMPVERSION)
            blobmsg_add_u32(b, "igmpversion", st.igmpversion);
        if (st.flags & DEV_OPT_MLDVERSION)
            blobmsg_add_u32(b, "mldversion", st.mldversion);
        if (st.flags & DEV_OPT_NEIGHREACHABLETIME) {
            blobmsg_add_u32(b, "neigh4reachabletime", st.neigh4reachabletime);
            blobmsg_add_u32(b, "neigh6reachabletime", st.neigh6reachabletime);
        }
        if (st.flags & DEV_OPT_NEIGHGCSTALETIME) {
            blobmsg_add_u32(b, "neigh4gcstaletime", st.neigh4gcstaletime);
            blobmsg_add_u32(b, "neigh6gcstaletime", st.neigh6gcstaletime);
        }
        if (st.flags & DEV_OPT_NEIGHLOCKTIME)
            blobmsg_add_u32(b, "neigh4locktime", st.neigh4locktime);
        if (st.flags & DEV_OPT_DADTRANSMITS)
            blobmsg_add_u32(b, "dadtransmits", st.dadtransmits);
        if (st.flags & DEV_OPT_MULTICAST_TO_UNICAST)
            blobmsg_add_u8(b, "multicast_to_unicast", st.multicast_to_unicast);
        if (st.flags & DEV_OPT_MULTICAST_ROUTER)
            blobmsg_add_u32(b, "multicast_router", st.multicast_router);
        if (st.flags & DEV_OPT_MULTICAST_FAST_LEAVE)
            blobmsg_add_u8(b, "multicast_fast_leave", st.multicast_fast_leave);
        if (st.flags & DEV_OPT_MULTICAST)
            blobmsg_add_u8(b, "multicast", st.multicast);
        if (st.flags & DEV_OPT_LEARNING)
            blobmsg_add_u8(b, "learning", st.learning);
        if (st.flags & DEV_OPT_UNICAST_FLOOD)
            blobmsg_add_u8(b, "unicast_flood", st.unicast_flood);
        if (st.flags & DEV_OPT_SENDREDIRECTS)
            blobmsg_add_u8(b, "sendredirects", st.sendredirects);
        if (st.flags & DEV_OPT_DROP_V4_UNICAST_IN_L2_MULTICAST)
            blobmsg_add_u8(b, "drop_v4_unicast_in_l2_multicast", st.drop_v4_unicast_in_l2_multicast);
        if (st.flags & DEV_OPT_DROP_V6_UNICAST_IN_L2_MULTICAST)
            blobmsg_add_u8(b, "drop_v6_unicast_in_l2_multicast", st.drop_v6_unicast_in_l2_multicast);
        if (st.flags & DEV_OPT_DROP_GRATUITOUS_ARP)
            blobmsg_add_u8(b, "drop_gratuitous_arp", st.drop_gratuitous_arp);
        if (st.flags & DEV_OPT_DROP_UNSOLICITED_NA)
            blobmsg_add_u8(b, "drop_unsolicited_na", st.drop_unsolicited_na);
        if (st.flags & DEV_OPT_ARP_ACCEPT)
            blobmsg_add_u8(b, "arp_accept", st.arp_accept);
        if (st.flags & DEV_OPT_AUTH)
            blobmsg_add_u8(b, "auth", st.auth);
        if (st.flags & DEV_OPT_GRO)
            blobmsg_add_u8(b, "gro", st.gro);
        if (st.flags & DEV_OPT_EEE)
            blobmsg_add_u8(b, "eee", st.eee);
    }
    s = blobmsg_open_table(b, "statistics");
    if (dev->type->dump_stats)
        dev->type->dump_stats(dev, b);
    else
        system_if_dump_stats(dev, b);
    blobmsg_close_table(b, s);
}
References device_settings::acceptlocal, device::active, device_settings::arp_accept, device_settings::auth, device::auth_status, avl_for_each_element, b, blobmsg_add_string(), blobmsg_add_u32(), blobmsg_add_u8(), blobmsg_close_table(), blobmsg_open_table(), buf, device_settings::dadtransmits, DEV_OPT_ACCEPTLOCAL, DEV_OPT_ARP_ACCEPT, DEV_OPT_AUTH, DEV_OPT_DADTRANSMITS, DEV_OPT_DROP_GRATUITOUS_ARP, DEV_OPT_DROP_UNSOLICITED_NA, DEV_OPT_DROP_V4_UNICAST_IN_L2_MULTICAST, DEV_OPT_DROP_V6_UNICAST_IN_L2_MULTICAST, DEV_OPT_EEE, DEV_OPT_GRO, DEV_OPT_IGMPVERSION, DEV_OPT_IP6SEGMENTROUTING, DEV_OPT_IPV6, DEV_OPT_LEARNING, DEV_OPT_MACADDR, DEV_OPT_MASTER, DEV_OPT_MLDVERSION, DEV_OPT_MTU, DEV_OPT_MTU6, DEV_OPT_MULTICAST, DEV_OPT_MULTICAST_FAST_LEAVE, DEV_OPT_MULTICAST_ROUTER, DEV_OPT_MULTICAST_TO_UNICAST, DEV_OPT_NEIGHGCSTALETIME, DEV_OPT_NEIGHLOCKTIME, DEV_OPT_NEIGHREACHABLETIME, DEV_OPT_PROMISC, DEV_OPT_RPFILTER, DEV_OPT_SENDREDIRECTS, DEV_OPT_TXQUEUELEN, DEV_OPT_UNICAST_FLOOD, device_dump_status(), device_merge_settings(), devices, device_settings::drop_gratuitous_arp, device_settings::drop_unsolicited_na, device_settings::drop_v4_unicast_in_l2_multicast, device_settings::drop_v6_unicast_in_l2_multicast, device_type::dump_info, device_type::dump_stats, device_settings::eee, device::external, device_settings::flags, format_macaddr(), device_settings::gro, device::ifname, device_settings::igmpversion, device_settings::ip6segmentrouting, device_settings::ipv6, device_settings::learning, device::link_active, device_settings::macaddr, device_settings::master_ifindex, device_settings::mldversion, device_settings::mtu, device_settings::mtu6, device_settings::multicast, device_settings::multicast_fast_leave, device_settings::multicast_router, device_settings::multicast_to_unicast, device_type::name, device_settings::neigh4gcstaletime, device_settings::neigh4locktime, device_settings::neigh4reachabletime, device_settings::neigh6gcstaletime, device_settings::neigh6reachabletime, device::present, device_settings::promisc, device_settings::rpfilter, device_settings::sendredirects, system_if_dump_info(), system_if_dump_stats(), device_settings::txqueuelen, device::type, and device_settings::unicast_flood.
Referenced by device_dump_status(), and netifd_dev_status().
device_event_name()
const char * device_event_name (enum device_event ev)
Definition at line 622 of file device.c.
{
    static const char * const event_names[] = {
        [DEV_EVENT_ADD] = "add",
        [DEV_EVENT_REMOVE] = "remove",
        [DEV_EVENT_UPDATE_IFNAME] = "update_ifname",
        [DEV_EVENT_UPDATE_IFINDEX] = "update_ifindex",
        [DEV_EVENT_SETUP] = "setup",
        [DEV_EVENT_TEARDOWN] = "teardown",
        [DEV_EVENT_UP] = "up",
        [DEV_EVENT_DOWN] = "down",
        [DEV_EVENT_AUTH_UP] = "auth_up",
        [DEV_EVENT_LINK_UP] = "link_up",
        [DEV_EVENT_LINK_DOWN] = "link_down",
        [DEV_EVENT_TOPO_CHANGE] = "topo_change",
    };
    if (ev >= ARRAY_SIZE(event_names) || !event_names[ev])
        return "unknown";
    return event_names[ev];
}
References ARRAY_SIZE, DEV_EVENT_ADD, DEV_EVENT_AUTH_UP, DEV_EVENT_DOWN, DEV_EVENT_LINK_DOWN, DEV_EVENT_LINK_UP, DEV_EVENT_REMOVE, DEV_EVENT_SETUP, DEV_EVENT_TEARDOWN, DEV_EVENT_TOPO_CHANGE, DEV_EVENT_UP, DEV_EVENT_UPDATE_IFINDEX, and DEV_EVENT_UPDATE_IFNAME.
Referenced by __device_broadcast_event().
device_find()
struct device * device_find (const char * name)
Definition at line 849 of file device.c.
{
    struct device *dev;
    return avl_find_element(&devices, name, dev, avl);
}
References device::avl, avl_find_element, and devices.
Referenced by cb_rtnl_event(), device_create(), device_hotplug_event(), netifd_dev_status(), and netifd_handle_set_state().
device_free_unused()
void device_free_unused (void)
Definition at line 1109 of file device.c.
{
    static struct uloop_timeout free_timer = {
        .cb = __device_free_unused,
    };
    uloop_timeout_set(&free_timer, 1);
}
References __device_free_unused(), and uloop_timeout_set().
Referenced by device_remove_user(), and netifd_handle_alias().
device_get()
static struct device * device_get (const char * name, int create) inline static
Definition at line 361 of file device.h.
{
    return __device_get(name, create, true);
}
References __device_get().
Referenced by __bridge_reload(), bonding_config_init(), bridge_add_member(), config_init_devices(), config_init_vlans(), extdev_bridge_add_member(), interface_claim_device(), interface_handle_link(), macvlan_config_init(), netifd_handle_alias(), proto_shell_update_link(), simple_device_create(), system_if_get_parent(), vlandev_config_init(), and wireless_vlan_handle_link().
device_hotplug_event()
void device_hotplug_event (const char * name, bool add)
Definition at line 1447 of file device.c.
{
    struct device *dev;
    wireless_device_hotplug_event(name, add);
    dev = device_find(name);
    if (!dev || dev->type != &simple_device_type)
        return;
    device_set_present(dev, add);
}
References device_find(), device_set_present, simple_device_type, device::type, and wireless_device_hotplug_event().
Referenced by handle_hotplug_msg().
device_init()
int device_init (struct device * dev, struct device_type * type, const char * ifname)
Definition at line 801 of file device.c.
{
    int ret;
    ret = device_init_virtual(dev, type, ifname);
    if (ret < 0)
        return ret;
    dev->avl.key = dev->ifname;
    ret = avl_insert(&devices, &dev->avl);
    if (ret < 0)
        return ret;
    system_if_clear_state(dev);
    return 0;
}
References device::avl, avl_insert(), device_init_virtual(), devices, device::ifname, ifname, avl_node::key, system_if_clear_state(), and type.
Referenced by __bridge_create(), __create(), bonding_create(), bridge_create(), device_create_default(), get_vlan_device(), macvlan_create(), tunnel_create(), veth_create(), and vlandev_create().
device_init_pending()
void device_init_pending (void)
Definition at line 1136 of file device.c.
{
    struct device *dev, *tmp;
    avl_for_each_element_safe(&devices, dev, avl, tmp) {
        if (!dev->config_pending)
            continue;
        dev->type->config_init(dev);
        dev->config_pending = false;
        device_check_state(dev);
    }
}
References device::avl, avl_for_each_element_safe, device_type::config_init, device::config_pending, device_check_state(), devices, and device::type.
Referenced by config_init_all().
device_init_settings()
void device_init_settings (struct device * dev, struct blob_attr ** tb)
Definition at line 357 of file device.c.
{
    struct device_settings *s = &dev->settings;
    struct blob_attr *cur;
    struct ether_addr *ea;
    bool disabled = false;
    if (dev->wireless)
        s->flags &= DEV_OPT_ISOLATE;
    else
        s->flags = 0;
    if ((cur = tb[DEV_ATTR_ENABLED]))
        disabled = !blobmsg_get_bool(cur);
    if ((cur = tb[DEV_ATTR_MTU]) && blobmsg_get_u32(cur) >= 68) {
        s->mtu = blobmsg_get_u32(cur);
        s->flags |= DEV_OPT_MTU;
    }
    if ((cur = tb[DEV_ATTR_MTU6]) && blobmsg_get_u32(cur) >= 1280) {
        s->mtu6 = blobmsg_get_u32(cur);
        s->flags |= DEV_OPT_MTU6;
    }
    if ((cur = tb[DEV_ATTR_TXQUEUELEN])) {
        s->txqueuelen = blobmsg_get_u32(cur);
        s->flags |= DEV_OPT_TXQUEUELEN;
    }
    if ((cur = tb[DEV_ATTR_MACADDR])) {
        ea = ether_aton(blobmsg_data(cur));
        if (ea) {
            memcpy(s->macaddr, ea, 6);
            s->flags |= DEV_OPT_MACADDR;
        }
    }
    if ((cur = tb[DEV_ATTR_IPV6])) {
        s->ipv6 = blobmsg_get_bool(cur);
        s->flags |= DEV_OPT_IPV6;
    }
    if ((cur = tb[DEV_ATTR_IP6SEGMENTROUTING])) {
        s->ip6segmentrouting = blobmsg_get_bool(cur);
        s->flags |= DEV_OPT_IP6SEGMENTROUTING;
    }
    if ((cur = tb[DEV_ATTR_PROMISC])) {
        s->promisc = blobmsg_get_bool(cur);
        s->flags |= DEV_OPT_PROMISC;
    }
    if ((cur = tb[DEV_ATTR_RPFILTER])) {
        if (system_resolve_rpfilter(blobmsg_data(cur), &s->rpfilter))
            s->flags |= DEV_OPT_RPFILTER;
        else
            D(DEVICE, "Failed to resolve rpfilter: %s", (char *) blobmsg_data(cur));
    }
    if ((cur = tb[DEV_ATTR_ACCEPTLOCAL])) {
        s->acceptlocal = blobmsg_get_bool(cur);
        s->flags |= DEV_OPT_ACCEPTLOCAL;
    }
    if ((cur = tb[DEV_ATTR_IGMPVERSION])) {
        s->igmpversion = blobmsg_get_u32(cur);
        if (s->igmpversion >= 1 && s->igmpversion <= 3)
            s->flags |= DEV_OPT_IGMPVERSION;
        else
            D(DEVICE, "Failed to resolve igmpversion: %d", blobmsg_get_u32(cur));
    }
    if ((cur = tb[DEV_ATTR_MLDVERSION])) {
        s->mldversion = blobmsg_get_u32(cur);
        if (s->mldversion >= 1 && s->mldversion <= 2)
            s->flags |= DEV_OPT_MLDVERSION;
        else
            D(DEVICE, "Failed to resolve mldversion: %d", blobmsg_get_u32(cur));
    }
    if ((cur = tb[DEV_ATTR_NEIGHREACHABLETIME])) {
        s->neigh6reachabletime = s->neigh4reachabletime = blobmsg_get_u32(cur);
        s->flags |= DEV_OPT_NEIGHREACHABLETIME;
    }
    if ((cur = tb[DEV_ATTR_NEIGHGCSTALETIME])) {
        s->neigh6gcstaletime = s->neigh4gcstaletime = blobmsg_get_u32(cur);
        s->flags |= DEV_OPT_NEIGHGCSTALETIME;
    }
    if ((cur = tb[DEV_ATTR_NEIGHLOCKTIME])) {
        s->neigh4locktime = blobmsg_get_u32(cur);
        s->flags |= DEV_OPT_NEIGHLOCKTIME;
    }
    if ((cur = tb[DEV_ATTR_DADTRANSMITS])) {
        s->dadtransmits = blobmsg_get_u32(cur);
        s->flags |= DEV_OPT_DADTRANSMITS;
    }
    if ((cur = tb[DEV_ATTR_MULTICAST_TO_UNICAST])) {
        s->multicast_to_unicast = blobmsg_get_bool(cur);
        s->flags |= DEV_OPT_MULTICAST_TO_UNICAST;
    }
    if ((cur = tb[DEV_ATTR_MULTICAST_ROUTER])) {
        s->multicast_router = blobmsg_get_u32(cur);
        if (s->multicast_router <= 2)
            s->flags |= DEV_OPT_MULTICAST_ROUTER;
        else
            D(DEVICE, "Invalid value: %d - (Use 0: never, 1: learn, 2: always)", blobmsg_get_u32(cur));
    }
    if ((cur = tb[DEV_ATTR_MULTICAST_FAST_LEAVE])) {
        s->multicast_fast_leave = blobmsg_get_bool(cur);
        s->flags |= DEV_OPT_MULTICAST_FAST_LEAVE;
    }
    if ((cur = tb[DEV_ATTR_MULTICAST])) {
        s->multicast = blobmsg_get_bool(cur);
        s->flags |= DEV_OPT_MULTICAST;
    }
    if ((cur = tb[DEV_ATTR_LEARNING])) {
        s->learning = blobmsg_get_bool(cur);
        s->flags |= DEV_OPT_LEARNING;
    }
    if ((cur = tb[DEV_ATTR_UNICAST_FLOOD])) {
        s->unicast_flood = blobmsg_get_bool(cur);
        s->flags |= DEV_OPT_UNICAST_FLOOD;
    }
    if ((cur = tb[DEV_ATTR_SENDREDIRECTS])) {
        s->sendredirects = blobmsg_get_bool(cur);
        s->flags |= DEV_OPT_SENDREDIRECTS;
    }
    if ((cur = tb[DEV_ATTR_ISOLATE])) {
        s->isolate = blobmsg_get_bool(cur);
        s->flags |= DEV_OPT_ISOLATE;
    }
    if ((cur = tb[DEV_ATTR_DROP_V4_UNICAST_IN_L2_MULTICAST])) {
        s->drop_v4_unicast_in_l2_multicast = blobmsg_get_bool(cur);
        s->flags |= DEV_OPT_DROP_V4_UNICAST_IN_L2_MULTICAST;
    }
    if ((cur = tb[DEV_ATTR_DROP_V6_UNICAST_IN_L2_MULTICAST])) {
        s->drop_v6_unicast_in_l2_multicast = blobmsg_get_bool(cur);
        s->flags |= DEV_OPT_DROP_V6_UNICAST_IN_L2_MULTICAST;
    }
    if ((cur = tb[DEV_ATTR_DROP_GRATUITOUS_ARP])) {
        s->drop_gratuitous_arp = blobmsg_get_bool(cur);
        s->flags |= DEV_OPT_DROP_GRATUITOUS_ARP;
    }
    if ((cur = tb[DEV_ATTR_DROP_UNSOLICITED_NA])) {
        s->drop_unsolicited_na = blobmsg_get_bool(cur);
        s->flags |= DEV_OPT_DROP_UNSOLICITED_NA;
    }
    if ((cur = tb[DEV_ATTR_ARP_ACCEPT])) {
        s->arp_accept = blobmsg_get_bool(cur);
        s->flags |= DEV_OPT_ARP_ACCEPT;
    }
    if ((cur = tb[DEV_ATTR_AUTH])) {
        s->auth = blobmsg_get_bool(cur);
        s->flags |= DEV_OPT_AUTH;
    }
    if ((cur = tb[DEV_ATTR_SPEED])) {
        s->speed = blobmsg_get_u32(cur);
        s->flags |= DEV_OPT_SPEED;
    }
    if ((cur = tb[DEV_ATTR_DUPLEX])) {
        s->duplex = blobmsg_get_bool(cur);
        s->flags |= DEV_OPT_DUPLEX;
    }
    if ((cur = tb[DEV_ATTR_PAUSE])) {
        s->pause = blobmsg_get_bool(cur);
        s->flags |= DEV_OPT_PAUSE;
    }
    if ((cur = tb[DEV_ATTR_ASYM_PAUSE])) {
        s->asym_pause = blobmsg_get_bool(cur);
        s->flags |= DEV_OPT_ASYM_PAUSE;
    }
    if ((cur = tb[DEV_ATTR_RXPAUSE])) {
        s->rxpause = blobmsg_get_bool(cur);
        s->flags |= DEV_OPT_RXPAUSE;
    }
    if ((cur = tb[DEV_ATTR_TXPAUSE])) {
        s->txpause = blobmsg_get_bool(cur);
        s->flags |= DEV_OPT_TXPAUSE;
    }
    if ((cur = tb[DEV_ATTR_AUTONEG])) {
        s->autoneg = blobmsg_get_bool(cur);
        s->flags |= DEV_OPT_AUTONEG;
    }
    if ((cur = tb[DEV_ATTR_GRO])) {
        s->gro = blobmsg_get_bool(cur);
        s->flags |= DEV_OPT_GRO;
    }
    if ((cur = tb[DEV_ATTR_MASTER])) {
        char *ifname = blobmsg_get_string(cur);
        s->master_ifindex = if_nametoindex(ifname);
        s->flags |= DEV_OPT_MASTER;
    }
    if ((cur = tb[DEV_ATTR_EEE])) {
        s->eee = blobmsg_get_bool(cur);
        s->flags |= DEV_OPT_EEE;
    }
    /* Remember the settings present in UCI */
    s->valid_flags = s->flags;
    cur = tb[DEV_ATTR_AUTH_VLAN];
    free(dev->config_auth_vlans);
    dev->config_auth_vlans = cur ? blob_memdup(cur) : NULL;
    device_set_extra_vlans(dev, tb[DEV_ATTR_VLAN]);
    device_set_disabled(dev, disabled);
}
References device_settings::acceptlocal, device_settings::arp_accept, device_settings::asym_pause, device_settings::auth, device_settings::autoneg, blob_memdup(), blobmsg_data(), blobmsg_get_bool(), blobmsg_get_string(), blobmsg_get_u32(), device::config_auth_vlans, D, device_settings::dadtransmits, DEV_ATTR_ACCEPTLOCAL, DEV_ATTR_ARP_ACCEPT, DEV_ATTR_ASYM_PAUSE, DEV_ATTR_AUTH, DEV_ATTR_AUTH_VLAN, DEV_ATTR_AUTONEG, DEV_ATTR_DADTRANSMITS, DEV_ATTR_DROP_GRATUITOUS_ARP, DEV_ATTR_DROP_UNSOLICITED_NA, DEV_ATTR_DROP_V4_UNICAST_IN_L2_MULTICAST, DEV_ATTR_DROP_V6_UNICAST_IN_L2_MULTICAST, DEV_ATTR_DUPLEX, DEV_ATTR_EEE, DEV_ATTR_ENABLED, DEV_ATTR_GRO, DEV_ATTR_IGMPVERSION, DEV_ATTR_IP6SEGMENTROUTING, DEV_ATTR_IPV6, DEV_ATTR_ISOLATE, DEV_ATTR_LEARNING, DEV_ATTR_MACADDR, DEV_ATTR_MASTER, DEV_ATTR_MLDVERSION, DEV_ATTR_MTU, DEV_ATTR_MTU6, DEV_ATTR_MULTICAST, DEV_ATTR_MULTICAST_FAST_LEAVE, DEV_ATTR_MULTICAST_ROUTER, DEV_ATTR_MULTICAST_TO_UNICAST, DEV_ATTR_NEIGHGCSTALETIME, DEV_ATTR_NEIGHLOCKTIME, DEV_ATTR_NEIGHREACHABLETIME, DEV_ATTR_PAUSE, DEV_ATTR_PROMISC, DEV_ATTR_RPFILTER, DEV_ATTR_RXPAUSE, DEV_ATTR_SENDREDIRECTS, DEV_ATTR_SPEED, DEV_ATTR_TXPAUSE, DEV_ATTR_TXQUEUELEN, DEV_ATTR_UNICAST_FLOOD, DEV_ATTR_VLAN, DEV_OPT_ACCEPTLOCAL, DEV_OPT_ARP_ACCEPT, DEV_OPT_ASYM_PAUSE, DEV_OPT_AUTH, DEV_OPT_AUTONEG, DEV_OPT_DADTRANSMITS, DEV_OPT_DROP_GRATUITOUS_ARP, DEV_OPT_DROP_UNSOLICITED_NA, DEV_OPT_DROP_V4_UNICAST_IN_L2_MULTICAST, DEV_OPT_DROP_V6_UNICAST_IN_L2_MULTICAST, DEV_OPT_DUPLEX, DEV_OPT_EEE, DEV_OPT_GRO, DEV_OPT_IGMPVERSION, DEV_OPT_IP6SEGMENTROUTING, DEV_OPT_IPV6, DEV_OPT_ISOLATE, DEV_OPT_LEARNING, DEV_OPT_MACADDR, DEV_OPT_MASTER, DEV_OPT_MLDVERSION, DEV_OPT_MTU, DEV_OPT_MTU6, DEV_OPT_MULTICAST, DEV_OPT_MULTICAST_FAST_LEAVE, DEV_OPT_MULTICAST_ROUTER, DEV_OPT_MULTICAST_TO_UNICAST, DEV_OPT_NEIGHGCSTALETIME, DEV_OPT_NEIGHLOCKTIME, DEV_OPT_NEIGHREACHABLETIME, DEV_OPT_PAUSE, DEV_OPT_PROMISC, DEV_OPT_RPFILTER, DEV_OPT_RXPAUSE, DEV_OPT_SENDREDIRECTS, DEV_OPT_SPEED, DEV_OPT_TXPAUSE, DEV_OPT_TXQUEUELEN, DEV_OPT_UNICAST_FLOOD, device_set_disabled(), device_set_extra_vlans(), device_settings::drop_gratuitous_arp, device_settings::drop_unsolicited_na, device_settings::drop_v4_unicast_in_l2_multicast, device_settings::drop_v6_unicast_in_l2_multicast, device_settings::duplex, device_settings::eee, device_settings::flags, device_settings::gro, ifname, device_settings::igmpversion, device_settings::ip6segmentrouting, device_settings::ipv6, device_settings::isolate, device_settings::learning, device_settings::macaddr, device_settings::master_ifindex, device_settings::mldversion, device_settings::mtu, device_settings::mtu6, device_settings::multicast, device_settings::multicast_fast_leave, device_settings::multicast_router, device_settings::multicast_to_unicast, device_settings::neigh4gcstaletime, device_settings::neigh4locktime, device_settings::neigh4reachabletime, device_settings::neigh6gcstaletime, device_settings::neigh6reachabletime, device_settings::pause, device_settings::promisc, device_settings::rpfilter, device_settings::rxpause, device_settings::sendredirects, device::settings, device_settings::speed, system_resolve_rpfilter(), device_settings::txpause, device_settings::txqueuelen, device_settings::unicast_flood, device_settings::valid_flags, and device::wireless.
Referenced by bonding_reload(), bridge_reload(), device_set_config(), macvlan_reload(), simple_device_create(), tunnel_reload(), veth_reload(), and vlandev_reload().
device_init_virtual()
int device_init_virtual (struct device * dev, struct device_type * type, const char * name)
Definition at line 775 of file device.c.
{
    assert(dev);
    assert(type);
    D(DEVICE, "Initialize device '%s'", name ? name : "");
    INIT_SAFE_LIST(&dev->users);
    INIT_SAFE_LIST(&dev->aliases);
    dev->type = type;
    if (name) {
        int ret;
        ret = device_set_ifname(dev, name);
        if (ret < 0) {
            netifd_log_message(L_WARNING, "Failed to initalize device '%s'\n", name);
            return ret;
        }
    }
    if (!dev->set_state)
        dev->set_state = set_device_state;
    return 0;
}
References device::aliases, D, device_set_ifname(), INIT_SAFE_LIST, L_WARNING, netifd_log_message(), set_device_state(), device::set_state, device::type, type, and device::users.
Referenced by alias_device_create(), and device_init().
device_link_active()
static bool device_link_active (struct device * dev) inline static
Definition at line 420 of file device.h.
{
    if (dev->settings.auth && !dev->auth_status)
        return false;
    return dev->link_active;
}
References device_settings::auth, device::auth_status, device::link_active, and device::settings.
Referenced by interface_main_dev_cb().
device_merge_settings()
void device_merge_settings (struct device * dev, struct device_settings * n)
Definition at line 250 of file device.c.
{
    struct device_settings *os = &dev->orig_settings;
    struct device_settings *s = &dev->settings;
    memset(n, 0, sizeof(*n));
    n->mtu = s->flags & DEV_OPT_MTU ? s->mtu : os->mtu;
    n->mtu6 = s->flags & DEV_OPT_MTU6 ? s->mtu6 : os->mtu6;
    n->txqueuelen = s->flags & DEV_OPT_TXQUEUELEN ?
        s->txqueuelen : os->txqueuelen;
    memcpy(n->macaddr,
        (s->flags & (DEV_OPT_MACADDR|DEV_OPT_DEFAULT_MACADDR) ? s->macaddr : os->macaddr),
        sizeof(n->macaddr));
    n->ipv6 = s->flags & DEV_OPT_IPV6 ? s->ipv6 : os->ipv6;
    n->ip6segmentrouting = s->flags & DEV_OPT_IP6SEGMENTROUTING ? s->ip6segmentrouting : os->ip6segmentrouting;
    n->promisc = s->flags & DEV_OPT_PROMISC ? s->promisc : os->promisc;
    n->rpfilter = s->flags & DEV_OPT_RPFILTER ? s->rpfilter : os->rpfilter;
    n->acceptlocal = s->flags & DEV_OPT_ACCEPTLOCAL ? s->acceptlocal : os->acceptlocal;
    n->igmpversion = s->flags & DEV_OPT_IGMPVERSION ? s->igmpversion : os->igmpversion;
    n->mldversion = s->flags & DEV_OPT_MLDVERSION ? s->mldversion : os->mldversion;
    n->neigh4reachabletime = s->flags & DEV_OPT_NEIGHREACHABLETIME ?
        s->neigh4reachabletime : os->neigh4reachabletime;
    n->neigh6reachabletime = s->flags & DEV_OPT_NEIGHREACHABLETIME ?
        s->neigh6reachabletime : os->neigh6reachabletime;
    n->neigh4gcstaletime = s->flags & DEV_OPT_NEIGHGCSTALETIME ?
        s->neigh4gcstaletime : os->neigh4gcstaletime;
    n->neigh6gcstaletime = s->flags & DEV_OPT_NEIGHGCSTALETIME ?
        s->neigh6gcstaletime : os->neigh6gcstaletime;
    n->neigh4locktime = s->flags & DEV_OPT_NEIGHLOCKTIME ?
        s->neigh4locktime : os->neigh4locktime;
    n->dadtransmits = s->flags & DEV_OPT_DADTRANSMITS ?
        s->dadtransmits : os->dadtransmits;
    n->multicast = s->flags & DEV_OPT_MULTICAST ?
        s->multicast : os->multicast;
    n->multicast_to_unicast = s->multicast_to_unicast;
    n->multicast_router = s->multicast_router;
    n->multicast_fast_leave = s->multicast_fast_leave;
    n->learning = s->learning;
    n->unicast_flood = s->unicast_flood;
    n->sendredirects = s->flags & DEV_OPT_SENDREDIRECTS ?
        s->sendredirects : os->sendredirects;
    n->drop_v4_unicast_in_l2_multicast = s->flags & DEV_OPT_DROP_V4_UNICAST_IN_L2_MULTICAST ?
        s->drop_v4_unicast_in_l2_multicast : os->drop_v4_unicast_in_l2_multicast;
    n->drop_v6_unicast_in_l2_multicast = s->flags & DEV_OPT_DROP_V6_UNICAST_IN_L2_MULTICAST ?
        s->drop_v6_unicast_in_l2_multicast : os->drop_v6_unicast_in_l2_multicast;
    n->drop_gratuitous_arp = s->flags & DEV_OPT_DROP_GRATUITOUS_ARP ?
        s->drop_gratuitous_arp : os->drop_gratuitous_arp;
    n->drop_unsolicited_na = s->flags & DEV_OPT_DROP_UNSOLICITED_NA ?
        s->drop_unsolicited_na : os->drop_unsolicited_na;
    n->arp_accept = s->flags & DEV_OPT_ARP_ACCEPT ?
        s->arp_accept : os->arp_accept;
    n->auth = s->flags & DEV_OPT_AUTH ? s->auth : os->auth;
    n->speed = s->flags & DEV_OPT_SPEED ? s->speed : os->speed;
    n->duplex = s->flags & DEV_OPT_DUPLEX ? s->duplex : os->duplex;
    n->pause = s->flags & DEV_OPT_PAUSE ? s->pause : os->pause;
    n->asym_pause = s->flags & DEV_OPT_ASYM_PAUSE ? s->asym_pause : os->asym_pause;
    n->rxpause = s->flags & DEV_OPT_RXPAUSE ? s->rxpause : os->rxpause;
    n->txpause = s->flags & DEV_OPT_TXPAUSE ? s->txpause : os->txpause;
    n->autoneg = s->flags & DEV_OPT_AUTONEG ? s->autoneg : os->autoneg;
    n->gro = s->flags & DEV_OPT_GRO ? s->gro : os->gro;
    n->eee = s->flags & DEV_OPT_EEE ? s->eee : os->eee;
    n->master_ifindex = s->flags & DEV_OPT_MASTER ? s->master_ifindex : os->master_ifindex;
    n->flags = s->flags | os->flags | os->valid_flags;
}
References device_settings::acceptlocal, device_settings::arp_accept, device_settings::asym_pause, device_settings::auth, device_settings::autoneg, device_settings::dadtransmits, DEV_OPT_ACCEPTLOCAL, DEV_OPT_ARP_ACCEPT, DEV_OPT_ASYM_PAUSE, DEV_OPT_AUTH, DEV_OPT_AUTONEG, DEV_OPT_DADTRANSMITS, DEV_OPT_DEFAULT_MACADDR, DEV_OPT_DROP_GRATUITOUS_ARP, DEV_OPT_DROP_UNSOLICITED_NA, DEV_OPT_DROP_V4_UNICAST_IN_L2_MULTICAST, DEV_OPT_DROP_V6_UNICAST_IN_L2_MULTICAST, DEV_OPT_DUPLEX, DEV_OPT_EEE, DEV_OPT_GRO, DEV_OPT_IGMPVERSION, DEV_OPT_IP6SEGMENTROUTING, DEV_OPT_IPV6, DEV_OPT_MACADDR, DEV_OPT_MASTER, DEV_OPT_MLDVERSION, DEV_OPT_MTU, DEV_OPT_MTU6, DEV_OPT_MULTICAST, DEV_OPT_NEIGHGCSTALETIME, DEV_OPT_NEIGHLOCKTIME, DEV_OPT_NEIGHREACHABLETIME, DEV_OPT_PAUSE, DEV_OPT_PROMISC, DEV_OPT_RPFILTER, DEV_OPT_RXPAUSE, DEV_OPT_SENDREDIRECTS, DEV_OPT_SPEED, DEV_OPT_TXPAUSE, DEV_OPT_TXQUEUELEN, device_settings::drop_gratuitous_arp, device_settings::drop_unsolicited_na, device_settings::drop_v4_unicast_in_l2_multicast, device_settings::drop_v6_unicast_in_l2_multicast, device_settings::duplex, device_settings::eee, device_settings::flags, device_settings::gro, device_settings::igmpversion, device_settings::ip6segmentrouting, device_settings::ipv6, device_settings::learning, device_settings::macaddr, device_settings::master_ifindex, device_settings::mldversion, device_settings::mtu, device_settings::mtu6, device_settings::multicast, device_settings::multicast_fast_leave, device_settings::multicast_router, device_settings::multicast_to_unicast, device_settings::neigh4gcstaletime, device_settings::neigh4locktime, device_settings::neigh4reachabletime, device_settings::neigh6gcstaletime, device_settings::neigh6reachabletime, device::orig_settings, device_settings::pause, device_settings::promisc, device_settings::rpfilter, device_settings::rxpause, device_settings::sendredirects, device::settings, device_settings::speed, device_settings::txpause, device_settings::txqueuelen, device_settings::unicast_flood, and device_settings::valid_flags.
Referenced by device_dump_status(), and eui64_ifaceid().
device_refresh_present()
void device_refresh_present (struct device * dev)
Definition at line 922 of file device.c.
{
    bool state = dev->sys_present;
    if (dev->disabled || dev->deferred)
        state = false;
    D(DEVICE, "refresh device %s present: sys=%d disabled=%d deferred=%d",
      dev->ifname, dev->sys_present, dev->disabled, dev->deferred);
    __device_set_present(dev, state, false);
}
References __device_set_present(), D, device::deferred, device_user::dev, device::disabled, device::ifname, state, and device::sys_present.
Referenced by _device_set_present(), device_set_deferred(), and device_set_disabled().
device_release()
void device_release (struct device_user * dep)
Definition at line 743 of file device.c.
{
    struct device *dev = dep->dev;
    if (!dep->claimed)
        return;
    dep->claimed = false;
    dev->active--;
    D(DEVICE, "Release %s %s, new active count: %d", dev->type->name, dev->ifname, dev->active);
    assert(dev->active >= 0);
    if (dev->active)
        return;
    device_broadcast_event(dev, DEV_EVENT_TEARDOWN);
    dev->set_state(dev, false);
    if (dev->active)
        return;
    device_broadcast_event(dev, DEV_EVENT_DOWN);
}
References device::active, device_user::claimed, D, device_user::dev, DEV_EVENT_DOWN, DEV_EVENT_TEARDOWN, device_broadcast_event, device::ifname, device_type::name, device::set_state, and device::type.
Referenced by __interface_set_down(), alias_device_set_state(), bonding_disable_port(), bonding_enable_port(), bridge_disable_member(), bridge_enable_member(), device_cleanup_cb(), device_release_cb(), device_remove_user(), device_replace(), extdev_bridge_disable_member(), interface_flush_state(), interface_proto_event_cb(), macvlan_set_down(), macvlan_set_up(), simple_device_set_state(), vlan_set_device_state(), vlandev_set_down(), and vlandev_set_up().
device_remove_user()
void device_remove_user (struct device_user * dep)
Definition at line 1118 of file device.c.
{
    struct device *dev = dep->dev;
    if (!dep->dev)
        return;
    dep->hotplug = false;
    if (dep->claimed)
        device_release(dep);
    safe_list_del(&dep->list);
    dep->dev = NULL;
    D(DEVICE, "Remove user for device '%s', refcount=%d", dev->ifname, device_refcount(dev));
    device_free_unused();
}
References device_user::claimed, D, device_user::dev, device_free_unused(), device_refcount(), device_release(), device_user::hotplug, device::ifname, device_user::list, and safe_list_del().
Referenced by alias_device_free(), alias_set_device(), bonding_free_port(), bridge_free_member(), device_add_user(), extdev_bridge_free_member(), free_vlan_if(), interface_cleanup(), interface_ext_dev_cb(), interface_proto_event_cb(), interface_remove_link(), macvlan_free(), simple_device_free(), and vlandev_free().
device_reset_config()
void device_reset_config (void)
Definition at line 1252 of file device.c.
{
    struct device *dev;
    avl_for_each_element(&devices, dev, avl)
        dev->current_config = false;
}
References device::avl, avl_for_each_element, device::current_config, and devices.
Referenced by config_init_all().
device_reset_old()
void device_reset_old (void)
Definition at line 1261 of file device.c.
{
    struct device *dev, *tmp, *ndev;
    avl_for_each_element_safe(&devices, dev, avl, tmp) {
        if (dev->current_config || dev->default_config)
            continue;
        if (dev->type != &simple_device_type)
            continue;
        ndev = device_create_default(dev->ifname, dev->external);
        if (!ndev)
            continue;
        device_replace(ndev, dev);
    }
}
References device::avl, avl_for_each_element_safe, device::current_config, device::default_config, device_create_default(), device_replace(), devices, device::external, device::ifname, simple_device_type, and device::type.
Referenced by config_init_all().
device_set_auth_status()
void device_set_auth_status (struct device * dev, bool value, struct blob_attr * vlans)
Definition at line 935 of file device.c.
{
    if (!value)
        vlans = NULL;
    else if (!blob_attr_equal(vlans, dev->auth_vlans))
        device_set_auth_status(dev, false, NULL);
    free(dev->auth_vlans);
    dev->auth_vlans = vlans ? blob_memdup(vlans) : NULL;
    if (dev->auth_status == value)
        return;
    dev->auth_status = value;
    if (!dev->present)
        return;
    if (dev->auth_status) {
        device_broadcast_event(dev, DEV_EVENT_AUTH_UP);
        return;
    }
    device_broadcast_event(dev, DEV_EVENT_LINK_DOWN);
    if (!dev->link_active)
        return;
    device_broadcast_event(dev, DEV_EVENT_LINK_UP);
}
References device::auth_status, device::auth_vlans, blob_attr_equal(), blob_memdup(), device_user::dev, DEV_EVENT_AUTH_UP, DEV_EVENT_LINK_DOWN, DEV_EVENT_LINK_UP, device_broadcast_event, device_set_auth_status(), device::link_active, and device::present.
Referenced by device_set_auth_status(), and netifd_handle_set_state().
device_set_deferred()
static void device_set_deferred (struct device * dev, bool value) inline static
Definition at line 406 of file device.h.
{
    dev->deferred = value;
    device_refresh_present(dev);
}
References device::deferred, and device_refresh_present().
Referenced by netifd_handle_set_state().
device_set_disabled()
static void device_set_disabled (struct device * dev, bool value) inline static
Definition at line 413 of file device.h.
{
    dev->disabled = value;
    device_refresh_present(dev);
}
References device_refresh_present(), and device::disabled.
Referenced by device_init_settings(), and system_device_update_state().
device_set_ifindex()
void device_set_ifindex (struct device * dev, int ifindex)
Definition at line 992 of file device.c.
{
    if (dev->ifindex == ifindex)
        return;
    dev->ifindex = ifindex;
    device_broadcast_event(dev, DEV_EVENT_UPDATE_IFINDEX);
}
References device_user::dev, DEV_EVENT_UPDATE_IFINDEX, device_broadcast_event, and device::ifindex.
Referenced by alias_device_cb(), alias_set_device(), set_device_state(), and system_if_clear_state().
device_set_ifname()
int device_set_ifname (struct device * dev, const char * name)
Definition at line 1001 of file device.c.
{
    int ret = 0;
    if (!strcmp(dev->ifname, name))
        return 0;
    if (strlen(name) > sizeof(dev->ifname) - 1) {
        netifd_log_message(L_WARNING, "Cannot set device name: '%s' is longer than max size %zd\n",
            name, sizeof(dev->ifname) - 1);
        return -1;
    }
    if (dev->avl.key)
        avl_delete(&devices, &dev->avl);
    strcpy(dev->ifname, name);
    if (dev->avl.key)
        ret = avl_insert(&devices, &dev->avl);
    if (ret == 0)
        device_broadcast_event(dev, DEV_EVENT_UPDATE_IFNAME);
    return ret;
}
References device::avl, avl_delete(), avl_insert(), device_user::dev, DEV_EVENT_UPDATE_IFNAME, device_broadcast_event, devices, device::ifname, avl_node::key, L_WARNING, and netifd_log_message().
Referenced by alias_set_device(), device_init_virtual(), and vlan_dev_cb().
device_set_link()
void device_set_link (struct device * dev, bool state)
Definition at line 979 of file device.c.
{
    if (dev->link_active == state)
        return;
    netifd_log_message(L_NOTICE, "%s '%s' link is %s\n", dev->type->name, dev->ifname, state ? "up" : "down" );
    dev->link_active = state;
    if (!state)
        dev->auth_status = false;
    device_broadcast_event(dev, state ? DEV_EVENT_LINK_UP : DEV_EVENT_LINK_DOWN);
}
References device::auth_status, device_user::dev, DEV_EVENT_LINK_DOWN, DEV_EVENT_LINK_UP, device_broadcast_event, device::ifname, L_NOTICE, device::link_active, device_type::name, netifd_log_message(), state, and device::type.
Referenced by alias_device_cb(), alias_set_device(), cb_if_check_error(), system_device_update_state(), and system_if_check().
device_stp_init()
void device_stp_init (void)
Definition at line 142 of file device.c.
{
    struct device *dev;
    avl_for_each_element(&devices, dev, avl) {
        if (!dev->type->stp_init)
            continue;
        dev->type->stp_init(dev);
    }
}
References device::avl, avl_for_each_element, devices, device_type::stp_init, and device::type.
Referenced by netifd_handle_stp_init().
device_type_add()
int device_type_add (struct device_type * devtype)
Definition at line 87 of file device.c.
{
    if (device_type_get(devtype->name)) {
        netifd_log_message(L_WARNING, "Device handler '%s' already exists\n",
                   devtype->name);
        return 1;
    }
    netifd_log_message(L_NOTICE, "Added device handler type: %s\n",
        devtype->name);
    list_add(&devtype->list, &devtypes);
    return 0;
}
References device_type_get(), devtypes, L_NOTICE, L_WARNING, device_type::list, list_add(), device_type::name, and netifd_log_message().
Referenced by bonding_device_type_init(), bridge_device_type_init(), extdev_add_devtype(), macvlan_device_type_init(), simple_device_type_init(), tunnel_device_type_init(), veth_device_type_init(), and vlandev_device_type_init().
device_type_get()
struct device_type * device_type_get (const char * tname)
Definition at line 103 of file device.c.
{
    struct device_type *cur;
    list_for_each_entry(cur, &devtypes, list)
        if (!strcmp(cur->name, tname))
            return cur;
    return NULL;
}
References devtypes, device_type::list, list_for_each_entry, and device_type::name.
Referenced by config_init_devices(), config_parse_interface(), and device_type_add().
device_vlan_update()
void device_vlan_update (bool done)
Definition at line 119 of file device.c.
{
    struct device *dev;
    avl_for_each_element(&devices, dev, avl) {
        if (!dev->vlans.update)
            continue;
        if (!done) {
            if (dev->vlan_aliases.get_len)
                kvlist_free(&dev->vlan_aliases);
            else
                kvlist_init(&dev->vlan_aliases, device_vlan_len);
            vlist_update(&dev->vlans);
        } else {
            vlist_flush(&dev->vlans);
            if (dev->type->vlan_update)
                dev->type->vlan_update(dev);
        }
    }
}
References device::avl, avl_for_each_element, device_vlan_len(), devices, kvlist::get_len, kvlist_free(), kvlist_init(), device::type, vlist_tree::update, device::vlan_aliases, device_type::vlan_update, device::vlans, vlist_flush(), and vlist_update().
Referenced by config_init_vlans().
get_vlan_device_chain()
struct device * get_vlan_device_chain (const char * ifname, int create)
Definition at line 254 of file vlan.c.
{
    struct device *dev = NULL, *vldev;
    char *buf, *s, *next;
    buf = strdup(ifname);
    if (!buf)
        return NULL;
    s = split_vlan(buf);
    dev = __device_get(buf, create, false);
    if (!dev || !s)
        goto out;
    /* for the first split, we need to check if we're using an alias or
     * if the . separator isn't being used as a vlan separator (e.g. for
     * AP WDS VLANs */
    if (!isdigit(s[0])) {
        next = split_vlan(s);
        vldev = get_vlan_device(dev, s, create);
        if (!vldev) {
            s[-1] = '.';
            dev = __device_get(buf, create, false);
            if (!dev)
                goto out;
            if (next)
                next[-1] = '.';
        } else {
            dev = vldev;
            s = next;
        }
    }
    while (s) {
        next = split_vlan(s);
        dev = get_vlan_device(dev, s, create);
        if (!dev)
            break;
        s = next;
    }
out:
    free(buf);
    return dev;
}
References __device_get(), buf, get_vlan_device(), ifname, and split_vlan().
Referenced by __device_get().
Variable Documentation
device_attr_list
const struct uci_blob_param_list device_attr_list extern
Definition at line 80 of file device.c.
{
    .n_params = __DEV_ATTR_MAX,
    .params = dev_attrs,
};
Referenced by bonding_reload(), bridge_reload(), device_set_config(), get_vlan_device(), interface_device_config_changed(), macvlan_reload(), tunnel_reload(), veth_reload(), and vlandev_reload().
simple_device_type
struct device_type simple_device_type extern
Definition at line 240 of file device.c.
{
    .name = "Network device",
    .config_params = &device_attr_list,
    .create = simple_device_create,
    .check_state = system_if_check,
    .free = simple_device_free,
};
Referenced by cb_if_check_error(), config_init_devices(), config_parse_interface(), device_check_state(), device_create_default(), device_hotplug_event(), device_reset_old(), simple_device_type_init(), system_device_update_state(), and system_if_check().
tunnel_device_type
struct device_type tunnel_device_type extern
Definition at line 98 of file tunnel.c.
{
    .name = "tunnel",
    .config_params = &tunnel_attr_list,
    .reload = tunnel_reload,
    .create = tunnel_create,
    .free = tunnel_free,
};
Referenced by proto_shell_create_tunnel(), and tunnel_device_type_init().