zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/ubus/lua/ubus.c File Reference
ubus.c File Reference
#include <unistd.h>
#include <libubus.h>
#include <libubox/blobmsg.h>
#include <libubox/blobmsg_json.h>
#include <lauxlib.h>
#include <lua.h>
Classes
struct ubus_lua_connection
struct ubus_lua_object
struct ubus_lua_event
struct ubus_lua_subscriber
Macros
#define MODNAME "ubus"
#define METANAME MODNAME ".meta"
Functions
static int ubus_lua_parse_blob (lua_State *L, struct blob_attr *attr, bool table)
static int ubus_lua_parse_blob_array (lua_State *L, struct blob_attr *attr, size_t len, bool table)
static bool ubus_lua_format_blob_is_array (lua_State *L)
static int ubus_lua_format_blob_array (lua_State *L, struct blob_buf *b, bool table)
static int ubus_lua_format_blob (lua_State *L, struct blob_buf *b, bool table)
static int ubus_lua_connect (lua_State *L)
static void ubus_lua_objects_cb (struct ubus_context *c, struct ubus_object_data *o, void *p)
static int ubus_lua_objects (lua_State *L)
static int ubus_method_handler (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int lua_gettablelen (lua_State *L, int index)
static int ubus_lua_reply (lua_State *L)
static int ubus_lua_defer_request (lua_State *L)
static int ubus_lua_complete_deferred_request (lua_State *L)
static int ubus_lua_load_methods (lua_State *L, struct ubus_method *m)
static void ubus_new_sub_cb (struct ubus_context *ctx, struct ubus_object *obj)
static void ubus_lua_load_newsub_cb (lua_State *L, struct ubus_lua_object *obj)
static struct ubus_object * ubus_lua_load_object (lua_State *L)
static int ubus_lua_add (lua_State *L)
static int ubus_lua_notify (lua_State *L)
static void ubus_lua_signatures_cb (struct ubus_context *c, struct ubus_object_data *o, void *p)
static int ubus_lua_signatures (lua_State *L)
static void ubus_lua_call_cb (struct ubus_request *req, int type, struct blob_attr *msg)
static int ubus_lua_call (lua_State *L)
static void ubus_event_handler (struct ubus_context *ctx, struct ubus_event_handler *ev, const char *type, struct blob_attr *msg)
static struct ubus_event_handler * ubus_lua_load_event (lua_State *L)
static int ubus_lua_listen (lua_State *L)
static void ubus_sub_remove_handler (struct ubus_context *ctx, struct ubus_subscriber *s, uint32_t id)
static int ubus_sub_notify_handler (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int ubus_lua_do_subscribe (struct ubus_context *ctx, lua_State *L, const char *target, int idxnotify, int idxremove)
static int ubus_lua_subscribe (lua_State *L)
static int ubus_lua_send (lua_State *L)
static int ubus_lua__gc (lua_State *L)
int luaopen_ubus (lua_State *L)
Variables
static lua_State * state
static const luaL_Reg ubus []
Class Documentation
ubus_lua_connection
struct ubus_lua_connection
Definition at line 28 of file ubus.c.
Class Members
struct blob_buf buf
struct ubus_context * ctx
int timeout
ubus_lua_object
struct ubus_lua_object
Definition at line 34 of file ubus.c.
Class Members
struct ubus_object o
int r
int rsubscriber
ubus_lua_event
struct ubus_lua_event
Definition at line 40 of file ubus.c.
Class Members
struct ubus_event_handler e
int r
ubus_lua_subscriber
struct ubus_lua_subscriber
Definition at line 45 of file ubus.c.
Class Members
int rnotify
int rremove
struct ubus_subscriber s
Macro Definition Documentation
METANAME
#define METANAME MODNAME ".meta"
Definition at line 24 of file ubus.c.
Referenced by luaopen_ubus(), ubus_lua__gc(), ubus_lua_add(), ubus_lua_call(), ubus_lua_complete_deferred_request(), ubus_lua_connect(), ubus_lua_defer_request(), ubus_lua_listen(), ubus_lua_notify(), ubus_lua_objects(), ubus_lua_reply(), ubus_lua_send(), ubus_lua_signatures(), and ubus_lua_subscribe().
MODNAME
#define MODNAME "ubus"
Definition at line 23 of file ubus.c.
Referenced by luaopen_ubus().
Function Documentation
lua_gettablelen()
static int lua_gettablelen (lua_State * L, int index) static
Definition at line 335 of file ubus.c.
{
    int cnt = 0;
    lua_pushnil(L);
    index -= 1;
    while (lua_next(L, index) != 0) {
        cnt++;
        lua_pop(L, 1);
    }
    return cnt;
}
Referenced by ubus_lua_load_methods(), and ubus_lua_load_object().
luaopen_ubus()
int luaopen_ubus (lua_State * L)
Definition at line 970 of file ubus.c.
{
    /* create metatable */
    luaL_newmetatable(L, METANAME);
    /* metatable.__index = metatable */
    lua_pushvalue(L, -1);
    lua_setfield(L, -2, "__index");
    /* fill metatable */
    luaL_register(L, NULL, ubus);
    lua_pop(L, 1);
    /* create module */
    luaL_register(L, MODNAME, ubus);
    /* set some enum defines */
    lua_pushinteger(L, BLOBMSG_TYPE_ARRAY);
    lua_setfield(L, -2, "ARRAY");
    lua_pushinteger(L, BLOBMSG_TYPE_TABLE);
    lua_setfield(L, -2, "TABLE");
    lua_pushinteger(L, BLOBMSG_TYPE_STRING);
    lua_setfield(L, -2, "STRING");
    lua_pushinteger(L, BLOBMSG_TYPE_INT64);
    lua_setfield(L, -2, "INT64");
    lua_pushinteger(L, BLOBMSG_TYPE_INT32);
    lua_setfield(L, -2, "INT32");
    lua_pushinteger(L, BLOBMSG_TYPE_INT16);
    lua_setfield(L, -2, "INT16");
    lua_pushinteger(L, BLOBMSG_TYPE_INT8);
    lua_setfield(L, -2, "INT8");
    lua_pushinteger(L, BLOBMSG_TYPE_DOUBLE);
    lua_setfield(L, -2, "DOUBLE");
    lua_pushinteger(L, BLOBMSG_TYPE_BOOL);
    lua_setfield(L, -2, "BOOLEAN");
    /* used in our callbacks */
    state = L;
    /* create the callback table */
    lua_createtable(L, 1, 0);
    lua_setglobal(L, "__ubus_cb");
    /* create the event table */
    lua_createtable(L, 1, 0);
    lua_setglobal(L, "__ubus_cb_event");
    /* create the subscriber table */
    lua_createtable(L, 1, 0);
    lua_setglobal(L, "__ubus_cb_subscribe");
    /* create the publisher table - notifications of new subs */
    lua_createtable(L, 1, 0);
    lua_setglobal(L, "__ubus_cb_publisher");
    return 0;
}
References BLOBMSG_TYPE_ARRAY, BLOBMSG_TYPE_BOOL, BLOBMSG_TYPE_DOUBLE, BLOBMSG_TYPE_INT16, BLOBMSG_TYPE_INT32, BLOBMSG_TYPE_INT64, BLOBMSG_TYPE_INT8, BLOBMSG_TYPE_STRING, BLOBMSG_TYPE_TABLE, METANAME, MODNAME, state, and ubus.
ubus_event_handler()
static void ubus_event_handler (struct ubus_context * ctx, struct ubus_event_handler * ev, const char * type, struct blob_attr * msg) static
Definition at line 706 of file ubus.c.
{
    struct ubus_lua_event *listener = container_of(ev, struct ubus_lua_event, e);
    lua_getglobal(state, "__ubus_cb_event");
    lua_rawgeti(state, -1, listener->r);
    lua_remove(state, -2);
    if (lua_isfunction(state, -1)) {
        ubus_lua_parse_blob_array(state, blob_data(msg), blob_len(msg), true);
        lua_call(state, 1, 0);
    } else {
        lua_pop(state, 1);
    }
}
References blob_data(), blob_len(), container_of, ubus_lua_event::e, ubus_lua_event::r, state, and ubus_lua_parse_blob_array().
Referenced by ubus_lua_load_event().
ubus_lua__gc()
static int ubus_lua__gc (lua_State * L) static
Definition at line 934 of file ubus.c.
{
    struct ubus_lua_connection *c = luaL_checkudata(L, 1, METANAME);
    blob_buf_free(&c->buf);
    if (c->ctx != NULL)
    {
        ubus_free(c->ctx);
        memset(c, 0, sizeof(*c));
    }
    return 0;
}
References blob_buf_free(), ubus_lua_connection::buf, ubus_lua_connection::ctx, METANAME, and ubus_free().
ubus_lua_add()
static int ubus_lua_add (lua_State * L) static
Definition at line 557 of file ubus.c.
{
    struct ubus_lua_connection *c = luaL_checkudata(L, 1, METANAME);
    /* verify top level object */
    if (lua_istable(L, 1)) {
        lua_pushstring(L, "you need to pass a table");
        return lua_error(L);
    }
    /* scan each object */
    lua_pushnil(L);
    while (lua_next(L, -2) != 0) {
        struct ubus_object *obj = NULL;
        /* check if the object has a table of methods */
        if ((lua_type(L, -2) == LUA_TSTRING) && (lua_type(L, -1) == LUA_TTABLE)) {
            obj = ubus_lua_load_object(L);
            if (obj){
                ubus_add_object(c->ctx, obj);
                                /* allow future reference of ubus obj */
                lua_pushstring(state,"__ubusobj");
                lua_pushlightuserdata(state, obj);
                lua_settable(state,-3);
                        }
        }
        lua_pop(L, 1);
    }
    return 0;
}
References ubus_lua_connection::ctx, METANAME, state, ubus_add_object(), and ubus_lua_load_object().
ubus_lua_call()
static int ubus_lua_call (lua_State * L) static
Definition at line 664 of file ubus.c.
{
    int rv, top;
    uint32_t id;
    struct ubus_lua_connection *c = luaL_checkudata(L, 1, METANAME);
    const char *path = luaL_checkstring(L, 2);
    const char *func = luaL_checkstring(L, 3);
    luaL_checktype(L, 4, LUA_TTABLE);
    blob_buf_init(&c->buf, 0);
    if (!ubus_lua_format_blob_array(L, &c->buf, true))
    {
        lua_pushnil(L);
        lua_pushinteger(L, UBUS_STATUS_INVALID_ARGUMENT);
        return 2;
    }
    rv = ubus_lookup_id(c->ctx, path, &id);
    if (rv)
    {
        lua_pushnil(L);
        lua_pushinteger(L, rv);
        return 2;
    }
    top = lua_gettop(L);
    rv = ubus_invoke(c->ctx, id, func, c->buf.head, ubus_lua_call_cb, L, c->timeout * 1000);
    if (rv != UBUS_STATUS_OK)
    {
        lua_pop(L, 1);
        lua_pushnil(L);
        lua_pushinteger(L, rv);
        return 2;
    }
    return lua_gettop(L) - top;
}
References blob_buf_init(), ubus_lua_connection::buf, ubus_lua_connection::ctx, blob_buf::head, id, METANAME, path, ubus_lua_connection::timeout, ubus_invoke(), ubus_lookup_id(), ubus_lua_call_cb(), ubus_lua_format_blob_array(), UBUS_STATUS_INVALID_ARGUMENT, and UBUS_STATUS_OK.
ubus_lua_call_cb()
static void ubus_lua_call_cb (struct ubus_request * req, int type, struct blob_attr * msg) static
Definition at line 652 of file ubus.c.
{
    lua_State *L = (lua_State *)req->priv;
    if (!msg && L)
        lua_pushnil(L);
    if (msg && L)
        ubus_lua_parse_blob_array(L, blob_data(msg), blob_len(msg), true);
}
References blob_data(), blob_len(), ubus_request::priv, and ubus_lua_parse_blob_array().
Referenced by ubus_lua_call().
ubus_lua_complete_deferred_request()
static int ubus_lua_complete_deferred_request (lua_State * L) static
Definition at line 380 of file ubus.c.
{
    struct ubus_lua_connection *c = luaL_checkudata(L, 1, METANAME);
    struct ubus_request_data *req = lua_touserdata(L, 2);
    int ret = luaL_checkinteger(L, 3);
    ubus_complete_deferred_request(c->ctx, req, ret);
    return 0;
}
References ubus_lua_connection::ctx, METANAME, and ubus_complete_deferred_request().
ubus_lua_connect()
static int ubus_lua_connect (lua_State * L) static
Definition at line 251 of file ubus.c.
{
    struct ubus_lua_connection *c;
    const char *sockpath = luaL_optstring(L, 1, NULL);
    int timeout = luaL_optint(L, 2, 30);
    if ((c = lua_newuserdata(L, sizeof(*c))) != NULL &&
        (c->ctx = ubus_connect(sockpath)) != NULL)
    {
        ubus_add_uloop(c->ctx);
        c->timeout = timeout;
        memset(&c->buf, 0, sizeof(c->buf));
        luaL_getmetatable(L, METANAME);
        lua_setmetatable(L, -2);
        return 1;
    }
    /* NB: no errors from ubus_connect() yet */
    lua_pushnil(L);
    lua_pushinteger(L, UBUS_STATUS_UNKNOWN_ERROR);
    return 2;
}
References ubus_lua_connection::buf, ubus_lua_connection::ctx, METANAME, timeout, ubus_lua_connection::timeout, ubus_add_uloop(), ubus_connect(), and UBUS_STATUS_UNKNOWN_ERROR.
ubus_lua_defer_request()
static int ubus_lua_defer_request (lua_State * L) static
Definition at line 370 of file ubus.c.
{
    struct ubus_lua_connection *c = luaL_checkudata(L, 1, METANAME);
    struct ubus_request_data *req = lua_touserdata(L, 2);
    struct ubus_request_data *new_req = lua_newuserdata(L, sizeof(struct ubus_request_data));
    ubus_defer_request(c->ctx, req, new_req);
    return 1;
}
References ubus_lua_connection::ctx, METANAME, and ubus_defer_request().
ubus_lua_do_subscribe()
static int ubus_lua_do_subscribe (struct ubus_context * ctx, lua_State * L, const char * target, int idxnotify, int idxremove) static
Definition at line 819 of file ubus.c.
{
    uint32_t id;
    int status;
    struct ubus_lua_subscriber *sub;
    if( ( status = ubus_lookup_id( ctx, target, &id ) ) ){
        lua_pushfstring( L, "Unable find target, status=%d", status );
        return lua_error( L );
    }
    sub = calloc( 1, sizeof( struct ubus_lua_subscriber ) );
    if( !sub ){
        lua_pushstring( L, "Out of memory" );
        return lua_error( L );
    }
    if( idxnotify ){
        lua_getglobal(L, "__ubus_cb_subscribe");
        lua_pushvalue(L, idxnotify);
        sub->rnotify = luaL_ref(L, -2);
        lua_pop(L, 1);
        sub->s.cb = ubus_sub_notify_handler;
    }
    if( idxremove ){
        lua_getglobal(L, "__ubus_cb_subscribe");
        lua_pushvalue(L, idxremove);
        sub->rremove = luaL_ref(L, -2);
        lua_pop(L, 1);
        sub->s.remove_cb = ubus_sub_remove_handler;
    }
    if( ( status = ubus_register_subscriber( ctx, &sub->s ) ) ){
        lua_pushfstring( L, "Failed to register subscriber, status=%d", status );
        return lua_error( L );
    }
    if( ( status = ubus_subscribe( ctx, &sub->s, id) ) ){
        lua_pushfstring( L, "Failed to register subscriber, status=%d", status );
        return lua_error( L );
    }
    return 0;
}
References ubus_subscriber::cb, ctx, id, ubus_subscriber::remove_cb, ubus_lua_subscriber::rnotify, ubus_lua_subscriber::rremove, ubus_lua_subscriber::s, ubus_lookup_id(), ubus_register_subscriber(), ubus_sub_notify_handler(), ubus_sub_remove_handler(), and ubus_subscribe().
Referenced by ubus_lua_subscribe().
ubus_lua_format_blob()
static int ubus_lua_format_blob (lua_State * L, struct blob_buf * b, bool table) static
Definition at line 183 of file ubus.c.
{
    void *c;
    bool rv = true;
    const char *key = table ? lua_tostring(L, -2) : NULL;
    switch (lua_type(L, -1))
    {
    case LUA_TBOOLEAN:
        blobmsg_add_u8(b, key, (uint8_t)lua_toboolean(L, -1));
        break;
#ifdef LUA_TINT
    case LUA_TINT:
#endif
    case LUA_TNUMBER:
        if ((uint64_t)lua_tonumber(L, -1) > INT_MAX)
            blobmsg_add_u64(b, key, (uint64_t)lua_tonumber(L, -1));
        else
            blobmsg_add_u32(b, key, (uint32_t)lua_tointeger(L, -1));
        break;
    case LUA_TSTRING:
    case LUA_TUSERDATA:
    case LUA_TLIGHTUSERDATA:
        blobmsg_add_string(b, key, lua_tostring(L, -1));
        break;
    case LUA_TTABLE:
        if (ubus_lua_format_blob_is_array(L))
        {
            c = blobmsg_open_array(b, key);
            rv = ubus_lua_format_blob_array(L, b, false);
            blobmsg_close_array(b, c);
        }
        else
        {
            c = blobmsg_open_table(b, key);
            rv = ubus_lua_format_blob_array(L, b, true);
            blobmsg_close_table(b, c);
        }
        break;
    default:
        rv = false;
        break;
    }
    return rv;
}
References b, blobmsg_add_string(), blobmsg_add_u32(), blobmsg_add_u64(), blobmsg_add_u8(), blobmsg_close_array(), blobmsg_close_table(), blobmsg_open_array(), blobmsg_open_table(), ubus_lua_format_blob_array(), and ubus_lua_format_blob_is_array().
Referenced by ubus_lua_format_blob_array().
ubus_lua_format_blob_array()
static int ubus_lua_format_blob_array (lua_State * L, struct blob_buf * b, bool table) static
Definition at line 235 of file ubus.c.
{
    for (lua_pushnil(L); lua_next(L, -2); lua_pop(L, 1))
    {
        if (!ubus_lua_format_blob(L, b, table))
        {
            lua_pop(L, 1);
            return false;
        }
    }
    return true;
}
References b, and ubus_lua_format_blob().
Referenced by ubus_lua_call(), ubus_lua_format_blob(), ubus_lua_notify(), ubus_lua_reply(), and ubus_lua_send().
ubus_lua_format_blob_is_array()
static bool ubus_lua_format_blob_is_array (lua_State * L) static
Definition at line 147 of file ubus.c.
{
    lua_Integer prv = 0;
    lua_Integer cur = 0;
    /* Find out whether table is array-like */
    for (lua_pushnil(L); lua_next(L, -2); lua_pop(L, 1))
    {
#ifdef LUA_TINT
        if (lua_type(L, -2) != LUA_TNUMBER && lua_type(L, -2) != LUA_TINT)
#else
        if (lua_type(L, -2) != LUA_TNUMBER)
#endif
        {
            lua_pop(L, 2);
            return false;
        }
        cur = lua_tointeger(L, -2);
        if ((cur - 1) != prv)
        {
            lua_pop(L, 2);
            return false;
        }
        prv = cur;
    }
    return true;
}
Referenced by ubus_lua_format_blob().
ubus_lua_listen()
static int ubus_lua_listen (lua_State * L) static
Definition at line 744 of file ubus.c.
{
    struct ubus_lua_connection *c = luaL_checkudata(L, 1, METANAME);
    /* verify top level object */
    luaL_checktype(L, 2, LUA_TTABLE);
    /* scan each object */
    lua_pushnil(L);
    while (lua_next(L, -2) != 0) {
        struct ubus_event_handler *listener;
        /* check if the key is a string and the value is a method */
        if ((lua_type(L, -2) == LUA_TSTRING) && (lua_type(L, -1) == LUA_TFUNCTION)) {
            listener = ubus_lua_load_event(L);
            if(listener != NULL) {
                ubus_register_event_handler(c->ctx, listener, lua_tostring(L, -2));
            }
        }
        lua_pop(L, 1);
    }
    return 0;
}
References ubus_lua_connection::ctx, METANAME, ubus_lua_load_event(), and ubus_register_event_handler().
ubus_lua_load_event()
static struct ubus_event_handler * ubus_lua_load_event (lua_State * L) static
Definition at line 724 of file ubus.c.
{
    struct ubus_lua_event* event = NULL;
    event = calloc(1, sizeof(struct ubus_lua_event));
    if (!event)
        return NULL;
    event->e.cb = ubus_event_handler;
    /* update the he callback lookup table */
    lua_getglobal(L, "__ubus_cb_event");
    lua_pushvalue(L, -2);
    event->r = luaL_ref(L, -2);
    lua_setfield(L, -1, lua_tostring(L, -3));
    return &event->e;
}
References ubus_event_handler().
Referenced by ubus_lua_listen().
ubus_lua_load_methods()
static int ubus_lua_load_methods (lua_State * L, struct ubus_method * m) static
Definition at line 390 of file ubus.c.
{
    struct blobmsg_policy *p;
    int plen;
    int pidx = 0;
    /* get the function pointer */
    lua_pushinteger(L, 1);
    lua_gettable(L, -2);
    /* get the policy table */
    lua_pushinteger(L, 2);
    lua_gettable(L, -3);
    /* check if the method table is valid */
    if ((lua_type(L, -2) != LUA_TFUNCTION) ||
            (lua_type(L, -1) != LUA_TTABLE) ||
            lua_objlen(L, -1)) {
        lua_pop(L, 2);
        return 1;
    }
    /* store function pointer */
    lua_pushvalue(L, -2);
    lua_setfield(L, -6, lua_tostring(L, -5));
    m->name = lua_tostring(L, -4);
    m->handler = ubus_method_handler;
    plen = lua_gettablelen(L, -1);
    /* exit if policy table is empty */
    if (!plen) {
        lua_pop(L, 2);
        return 0;
    }
    /* setup the policy pointers */
    p = calloc(plen, sizeof(struct blobmsg_policy));
    if (!p)
        return 1;
    m->policy = p;
    lua_pushnil(L);
    while (lua_next(L, -2) != 0) {
        int val = lua_tointeger(L, -1);
        /* check if the policy is valid */
        if ((lua_type(L, -2) != LUA_TSTRING) ||
                (lua_type(L, -1) != LUA_TNUMBER) ||
                (val < 0) ||
                (val > BLOBMSG_TYPE_LAST)) {
            lua_pop(L, 1);
            continue;
        }
        p[pidx].name = lua_tostring(L, -2);
        p[pidx].type = val;
        lua_pop(L, 1);
        pidx++;
    }
    m->n_policy = pidx;
    lua_pop(L, 2);
    return 0;
}
References BLOBMSG_TYPE_LAST, ubus_method::handler, lua_gettablelen(), ubus_method::n_policy, blobmsg_policy::name, ubus_method::name, ubus_method::policy, blobmsg_policy::type, and ubus_method_handler().
Referenced by ubus_lua_load_object().
ubus_lua_load_newsub_cb()
static void ubus_lua_load_newsub_cb (lua_State * L, struct ubus_lua_object * obj) static
Definition at line 477 of file ubus.c.
{
    /* keep ref to func */
    lua_getglobal(L, "__ubus_cb_publisher");
    lua_pushvalue(L, -2);
    obj->rsubscriber = luaL_ref(L, -2);
    lua_pop(L, 1);
    /* real callback */
    obj->o.subscribe_cb = ubus_new_sub_cb;
    return;
}
References ubus_lua_object::o, ubus_lua_object::rsubscriber, ubus_object::subscribe_cb, and ubus_new_sub_cb().
Referenced by ubus_lua_load_object().
ubus_lua_load_object()
static struct ubus_object * ubus_lua_load_object (lua_State * L) static
Definition at line 490 of file ubus.c.
{
    struct ubus_lua_object *obj = NULL;
    int mlen = lua_gettablelen(L, -1);
    struct ubus_method *m;
    int midx = 0;
    /* setup object pointers */
    obj = calloc(1, sizeof(struct ubus_lua_object));
    if (!obj)
        return NULL;
    obj->o.name = lua_tostring(L, -2);
    /* setup method pointers */
    m = calloc(mlen, sizeof(struct ubus_method));
    obj->o.methods = m;
    /* setup type pointers */
    obj->o.type = calloc(1, sizeof(struct ubus_object_type));
    if (!obj->o.type) {
        free(obj);
        return NULL;
    }
    obj->o.type->name = lua_tostring(L, -2);
    obj->o.type->id = 0;
    obj->o.type->methods = obj->o.methods;
    /* create the callback lookup table */
    lua_createtable(L, 1, 0);
    lua_getglobal(L, "__ubus_cb");
    lua_pushvalue(L, -2);
    obj->r = luaL_ref(L, -2);
    lua_pop(L, 1);
    /* scan each method */
    lua_pushnil(L);
    while (lua_next(L, -3) != 0) {
                /* check if its the subscriber notification callback */
                if( lua_type( L, -2 ) == LUA_TSTRING &&
                                lua_type( L, -1 ) == LUA_TFUNCTION ){
                  if( !strcmp( lua_tostring( L, -2 ), "__subscriber_cb" ) )
                          ubus_lua_load_newsub_cb( L, obj );
                }
        /* check if it looks like a method */
        if ((lua_type(L, -2) != LUA_TSTRING) ||
                (lua_type(L, -1) != LUA_TTABLE) ||
                !lua_objlen(L, -1)) {
            lua_pop(L, 1);
            continue;
        }
        if (!ubus_lua_load_methods(L, &m[midx]))
            midx++;
        lua_pop(L, 1);
    }
    obj->o.type->n_methods = obj->o.n_methods = midx;
    /* pop the callback table */
    lua_pop(L, 1);
    return &obj->o;
}
References ubus_object_type::id, lua_gettablelen(), ubus_object::methods, ubus_object_type::methods, ubus_object::n_methods, ubus_object_type::n_methods, ubus_object::name, ubus_object_type::name, ubus_lua_object::o, ubus_lua_object::r, ubus_object::type, ubus_lua_load_methods(), and ubus_lua_load_newsub_cb().
Referenced by ubus_lua_add().
ubus_lua_notify()
static int ubus_lua_notify (lua_State * L) static
Definition at line 592 of file ubus.c.
{
    struct ubus_lua_connection *c;
    struct ubus_object *obj;
    const char* method;
    c = luaL_checkudata(L, 1, METANAME);
    method = luaL_checkstring(L, 3);
    luaL_checktype(L, 4, LUA_TTABLE);
    if( !lua_islightuserdata( L, 2 ) ){
        lua_pushfstring( L, "Invald 2nd parameter, expected ubus obj ref" );
        return lua_error( L );
    }
    obj = lua_touserdata( L, 2 );
    /* create parameters from table */
    blob_buf_init(&c->buf, 0);
    if( !ubus_lua_format_blob_array( L, &c->buf, true ) ){
        lua_pushfstring( L, "Invalid 4th parameter, expected table of arguments" );
        return lua_error( L );
    }
    ubus_notify( c->ctx, obj, method, c->buf.head, -1 );
    return 0;
}
References blob_buf_init(), ubus_lua_connection::buf, ubus_lua_connection::ctx, blob_buf::head, METANAME, ubus_lua_format_blob_array(), and ubus_notify().
ubus_lua_objects()
static int ubus_lua_objects (lua_State * L) static
Definition at line 285 of file ubus.c.
{
    int rv;
    struct ubus_lua_connection *c = luaL_checkudata(L, 1, METANAME);
    const char *path = (lua_gettop(L) >= 2) ? luaL_checkstring(L, 2) : NULL;
    lua_newtable(L);
    rv = ubus_lookup(c->ctx, path, ubus_lua_objects_cb, L);
    if (rv != UBUS_STATUS_OK)
    {
        lua_pop(L, 1);
        lua_pushnil(L);
        lua_pushinteger(L, rv);
        return 2;
    }
    return 1;
}
References ubus_lua_connection::ctx, METANAME, path, ubus_lookup(), ubus_lua_objects_cb(), and UBUS_STATUS_OK.
ubus_lua_objects_cb()
static void ubus_lua_objects_cb (struct ubus_context * c, struct ubus_object_data * o, void * p) static
Definition at line 276 of file ubus.c.
{
    lua_State *L = (lua_State *)p;
    lua_pushstring(L, o->path);
    lua_rawseti(L, -2, lua_objlen(L, -2) + 1);
}
References ubus_object_data::path.
Referenced by ubus_lua_objects().
ubus_lua_parse_blob()
static int ubus_lua_parse_blob (lua_State * L, struct blob_attr * attr, bool table) static
Definition at line 78 of file ubus.c.
{
    int len;
    int off = 0;
    void *data;
    if (!blobmsg_check_attr(attr, false))
        return 0;
    if (table && blobmsg_name(attr)[0])
    {
        lua_pushstring(L, blobmsg_name(attr));
        off++;
    }
    data = blobmsg_data(attr);
    len = blobmsg_data_len(attr);
    switch (blob_id(attr))
    {
    case BLOBMSG_TYPE_BOOL:
        lua_pushboolean(L, *(uint8_t *)data);
        break;
    case BLOBMSG_TYPE_INT16:
        lua_pushinteger(L, be16_to_cpu(*(uint16_t *)data));
        break;
    case BLOBMSG_TYPE_INT32:
        lua_pushinteger(L, be32_to_cpu(*(uint32_t *)data));
        break;
    case BLOBMSG_TYPE_INT64:
        lua_pushnumber(L, (double) be64_to_cpu(*(uint64_t *)data));
        break;
    case BLOBMSG_TYPE_DOUBLE:
        {
            union {
                double d;
                uint64_t u64;
            } v;
            v.u64 = be64_to_cpu(*(uint64_t *)data);
            lua_pushnumber(L, v.d);
        }
        break;
    case BLOBMSG_TYPE_STRING:
        lua_pushstring(L, data);
        break;
    case BLOBMSG_TYPE_ARRAY:
        ubus_lua_parse_blob_array(L, data, len, false);
        break;
    case BLOBMSG_TYPE_TABLE:
        ubus_lua_parse_blob_array(L, data, len, true);
        break;
    default:
        lua_pushnil(L);
        break;
    }
    return off + 1;
}
References be16_to_cpu, be32_to_cpu, be64_to_cpu, blob_id(), blobmsg_check_attr(), blobmsg_data(), blobmsg_data_len(), blobmsg_name(), BLOBMSG_TYPE_ARRAY, BLOBMSG_TYPE_BOOL, BLOBMSG_TYPE_DOUBLE, BLOBMSG_TYPE_INT16, BLOBMSG_TYPE_INT32, BLOBMSG_TYPE_INT64, BLOBMSG_TYPE_STRING, BLOBMSG_TYPE_TABLE, blob_attr::data, and ubus_lua_parse_blob_array().
Referenced by ubus_lua_parse_blob_array().
ubus_lua_parse_blob_array()
static int ubus_lua_parse_blob_array (lua_State * L, struct blob_attr * attr, size_t len, bool table) static
Definition at line 55 of file ubus.c.
{
    int rv;
    int idx = 1;
    size_t rem = len;
    struct blob_attr *pos;
    lua_newtable(L);
    __blob_for_each_attr(pos, attr, rem)
    {
        rv = ubus_lua_parse_blob(L, pos, table);
        if (rv > 1)
            lua_rawset(L, -3);
        else if (rv > 0)
            lua_rawseti(L, -2, idx++);
    }
    return 1;
}
References __blob_for_each_attr, and ubus_lua_parse_blob().
Referenced by ubus_event_handler(), ubus_lua_call_cb(), ubus_lua_parse_blob(), ubus_lua_signatures_cb(), ubus_method_handler(), and ubus_sub_notify_handler().
ubus_lua_reply()
static int ubus_lua_reply (lua_State * L) static
Definition at line 349 of file ubus.c.
{
    struct ubus_lua_connection *c = luaL_checkudata(L, 1, METANAME);
    struct ubus_request_data *req;
    luaL_checktype(L, 3, LUA_TTABLE);
    blob_buf_init(&c->buf, 0);
    if (!ubus_lua_format_blob_array(L, &c->buf, true))
    {
        lua_pushnil(L);
        lua_pushinteger(L, UBUS_STATUS_INVALID_ARGUMENT);
        return 2;
    }
    req = lua_touserdata(L, 2);
    ubus_send_reply(c->ctx, req, c->buf.head);
    return 0;
}
References blob_buf_init(), ubus_lua_connection::buf, ubus_lua_connection::ctx, blob_buf::head, METANAME, ubus_lua_format_blob_array(), ubus_send_reply(), and UBUS_STATUS_INVALID_ARGUMENT.
ubus_lua_send()
static int ubus_lua_send (lua_State * L) static
Definition at line 907 of file ubus.c.
{
    struct ubus_lua_connection *c = luaL_checkudata(L, 1, METANAME);
    const char *event = luaL_checkstring(L, 2);
    if (*event == 0)
        return luaL_argerror(L, 2, "no event name");
    // Event content convert to ubus form
    luaL_checktype(L, 3, LUA_TTABLE);
    blob_buf_init(&c->buf, 0);
    if (!ubus_lua_format_blob_array(L, &c->buf, true)) {
        lua_pushnil(L);
        lua_pushinteger(L, UBUS_STATUS_INVALID_ARGUMENT);
        return 2;
    }
    // Send the event
    ubus_send_event(c->ctx, event, c->buf.head);
    return 0;
}
References blob_buf_init(), ubus_lua_connection::buf, ubus_lua_connection::ctx, blob_buf::head, METANAME, ubus_lua_format_blob_array(), ubus_send_event(), and UBUS_STATUS_INVALID_ARGUMENT.
ubus_lua_signatures()
static int ubus_lua_signatures (lua_State * L) static
Definition at line 631 of file ubus.c.
{
    int rv;
    struct ubus_lua_connection *c = luaL_checkudata(L, 1, METANAME);
    const char *path = luaL_checkstring(L, 2);
    rv = ubus_lookup(c->ctx, path, ubus_lua_signatures_cb, L);
    if (rv != UBUS_STATUS_OK)
    {
        lua_pop(L, 1);
        lua_pushnil(L);
        lua_pushinteger(L, rv);
        return 2;
    }
    return 1;
}
References ubus_lua_connection::ctx, METANAME, path, ubus_lookup(), ubus_lua_signatures_cb(), and UBUS_STATUS_OK.
ubus_lua_signatures_cb()
static void ubus_lua_signatures_cb (struct ubus_context * c, struct ubus_object_data * o, void * p) static
Definition at line 620 of file ubus.c.
{
    lua_State *L = (lua_State *)p;
    if (!o->signature)
        return;
    ubus_lua_parse_blob_array(L, blob_data(o->signature), blob_len(o->signature), true);
}
References blob_data(), blob_len(), ubus_object_data::signature, and ubus_lua_parse_blob_array().
Referenced by ubus_lua_signatures().
ubus_lua_subscribe()
static int ubus_lua_subscribe (lua_State * L) static
Definition at line 867 of file ubus.c.
{
    int idxnotify, idxremove, stackstart;
    struct ubus_lua_connection *c;
    const char* target;
    idxnotify = idxremove = 0;
    stackstart = lua_gettop( L );
    c = luaL_checkudata(L, 1, METANAME);
    target = luaL_checkstring(L, 2);
    luaL_checktype(L, 3, LUA_TTABLE);
    lua_pushstring( L, "notify");
    lua_gettable( L, 3 );
    if( lua_type( L, -1 ) == LUA_TFUNCTION ){
        idxnotify = lua_gettop( L );
    } else {
        lua_pop( L, 1 );
    }
    lua_pushstring( L, "remove");
    lua_gettable( L, 3 );
    if( lua_type( L, -1 ) == LUA_TFUNCTION ){
        idxremove = lua_gettop( L );
    } else {
        lua_pop( L, 1 );
    }
    if( idxnotify )
        ubus_lua_do_subscribe( c->ctx, L, target, idxnotify, idxremove );
    if( lua_gettop( L ) > stackstart )
        lua_pop( L, lua_gettop( L ) - stackstart );
    return 0;
}
References ubus_lua_connection::ctx, METANAME, and ubus_lua_do_subscribe().
ubus_method_handler()
static int ubus_method_handler (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 306 of file ubus.c.
{
    struct ubus_lua_object *o = container_of(obj, struct ubus_lua_object, o);
    int rv = 0;
    lua_getglobal(state, "__ubus_cb");
    lua_rawgeti(state, -1, o->r);
    lua_getfield(state, -1, method);
    lua_remove(state, -2);
    lua_remove(state, -2);
    if (lua_isfunction(state, -1)) {
        lua_pushlightuserdata(state, req);
        if (!msg)
            lua_pushnil(state);
        else
            ubus_lua_parse_blob_array(state, blob_data(msg), blob_len(msg), true);
        lua_call(state, 2, 1);
        if (lua_isnumber(state, -1))
            rv = lua_tonumber(state, -1);
    }
    lua_pop(state, 1);
    return rv;
}
References blob_data(), blob_len(), container_of, ubus_lua_object::o, state, and ubus_lua_parse_blob_array().
Referenced by ubus_lua_load_methods().
ubus_new_sub_cb()
static void ubus_new_sub_cb (struct ubus_context * ctx, struct ubus_object * obj) static
Definition at line 458 of file ubus.c.
{
    struct ubus_lua_object *luobj;
    luobj = container_of(obj, struct ubus_lua_object, o);
    lua_getglobal(state, "__ubus_cb_publisher");
    lua_rawgeti(state, -1, luobj->rsubscriber);
    lua_remove(state, -2);
    if (lua_isfunction(state, -1)) {
        lua_pushnumber(state, luobj->o.has_subscribers );
        lua_call(state, 1, 0);
    } else {
        lua_pop(state, 1);
    }
}
References container_of, ubus_object::has_subscribers, ubus_lua_object::o, ubus_lua_object::rsubscriber, and state.
Referenced by ubus_lua_load_newsub_cb().
ubus_sub_notify_handler()
static int ubus_sub_notify_handler (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 787 of file ubus.c.
{
    struct ubus_subscriber *s;
    struct ubus_lua_subscriber *sub;
    s = container_of(obj, struct ubus_subscriber, obj);
    sub = container_of(s, struct ubus_lua_subscriber, s);
    lua_getglobal(state, "__ubus_cb_subscribe");
    lua_rawgeti(state, -1, sub->rnotify);
    lua_remove(state, -2);
    if (lua_isfunction(state, -1)) {
        if( msg ){
            ubus_lua_parse_blob_array(state, blob_data(msg), blob_len(msg), true);
        } else {
            lua_pushnil(state);
        }
        lua_pushstring(state, method);
        lua_call(state, 2, 0);
    } else {
        lua_pop(state, 1);
    }
    return 0;
}
References blob_data(), blob_len(), container_of, ubus_lua_subscriber::rnotify, ubus_lua_subscriber::s, state, and ubus_lua_parse_blob_array().
Referenced by ubus_lua_do_subscribe().
ubus_sub_remove_handler()
static void ubus_sub_remove_handler (struct ubus_context * ctx, struct ubus_subscriber * s, uint32_t id) static
Definition at line 768 of file ubus.c.
{
    struct ubus_lua_subscriber *sub;
    sub = container_of(s, struct ubus_lua_subscriber, s);
    lua_getglobal(state, "__ubus_cb_subscribe");
    lua_rawgeti(state, -1, sub->rremove);
    lua_remove(state, -2);
    if (lua_isfunction(state, -1)) {
        lua_call(state, 0, 0);
    } else {
        lua_pop(state, 1);
    }
}
References container_of, ubus_lua_subscriber::rremove, ubus_lua_subscriber::s, and state.
Referenced by ubus_lua_do_subscribe().
Variable Documentation
state
lua_State* state static
Definition at line 26 of file ubus.c.
Referenced by luaopen_ubus(), ubus_event_handler(), ubus_lua_add(), ubus_method_handler(), ubus_new_sub_cb(), ubus_sub_notify_handler(), and ubus_sub_remove_handler().
ubus
const luaL_Reg ubus[] static
Initial value:
= {
    { "connect", ubus_lua_connect },
    { "objects", ubus_lua_objects },
    { "add", ubus_lua_add },
    { "notify", ubus_lua_notify },
    { "reply", ubus_lua_reply },
    { "defer_request", ubus_lua_defer_request },
    { "complete_deferred_request", ubus_lua_complete_deferred_request },
    { "signatures", ubus_lua_signatures },
    { "call", ubus_lua_call },
    { "close", ubus_lua__gc },
    { "listen", ubus_lua_listen },
    { "send", ubus_lua_send },
    { "subscribe", ubus_lua_subscribe },
    { "__gc", ubus_lua__gc },
    { NULL, NULL },
}
Definition at line 948 of file ubus.c.
{
    { "connect", ubus_lua_connect },
    { "objects", ubus_lua_objects },
    { "add", ubus_lua_add },
    { "notify", ubus_lua_notify },
    { "reply", ubus_lua_reply },
    { "defer_request", ubus_lua_defer_request },
    { "complete_deferred_request", ubus_lua_complete_deferred_request },
    { "signatures", ubus_lua_signatures },
    { "call", ubus_lua_call },
    { "close", ubus_lua__gc },
    { "listen", ubus_lua_listen },
    { "send", ubus_lua_send },
    { "subscribe", ubus_lua_subscribe },
    { "__gc", ubus_lua__gc },
    { NULL, NULL },
};
Referenced by luaopen_ubus(), main(), netifd_handle_down(), netifd_handle_iface_prepare(), netifd_handle_renew(), netifd_handle_set_data(), netifd_handle_status(), netifd_handle_up(), netifd_iface_handle_device(), netifd_iface_notify_proto(), netifd_iface_remove(), and netns_updown().