zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/netifd/iprule.h File Reference
iprule.h File Reference
#include "interface-ip.h"
Classes
struct iprule
Macros
#define IPRULE_PRIORITY_ADDR 10000
#define IPRULE_PRIORITY_ADDR_MASK 20000
#define IPRULE_PRIORITY_NW 90000
#define IPRULE_PRIORITY_REJECT 4200000000
Enumerations
enum iprule_flags {
IPRULE_INET4 = (0 << 0) , IPRULE_INET6 = (1 << 0) , IPRULE_FAMILY = IPRULE_INET4 | IPRULE_INET6 , IPRULE_IN = (1 << 2) ,
IPRULE_OUT = (1 << 3) , IPRULE_SRC = (1 << 4) , IPRULE_DEST = (1 << 5) , IPRULE_PRIORITY = (1 << 6) ,
IPRULE_TOS = (1 << 7) , IPRULE_FWMARK = (1 << 8) , IPRULE_FWMASK = (1 << 9) , IPRULE_LOOKUP = (1 << 10) ,
IPRULE_ACTION = (1 << 11) , IPRULE_GOTO = (1 << 12) , IPRULE_SUP_PREFIXLEN = (1 << 13) , IPRULE_UIDRANGE = (1 << 14)
}
Functions
void iprule_add (struct blob_attr *attr, bool v6)
void iprule_update_start (void)
void iprule_update_complete (void)
Variables
struct vlist_tree iprules
const struct uci_blob_param_list rule_attr_list
Class Documentation
iprule
struct iprule
Definition at line 71 of file iprule.h.
Class Members
unsigned int action
union if_addr dest_addr
unsigned int dest_mask
enum iprule_flags flags
unsigned int fwmark
unsigned int fwmask
unsigned int gotoid
char in_dev[IFNAMSIZ]
char * in_iface
struct interface_user in_iface_user
bool invert
unsigned int lookup
struct vlist_node node
unsigned int order
char out_dev[IFNAMSIZ]
char * out_iface
struct interface_user out_iface_user
unsigned int priority
union if_addr src_addr
unsigned int src_mask
unsigned int sup_prefixlen
unsigned int tos
unsigned int uidrange_end
unsigned int uidrange_start
Macro Definition Documentation
IPRULE_PRIORITY_ADDR
#define IPRULE_PRIORITY_ADDR 10000
Definition at line 20 of file iprule.h.
Referenced by interface_add_addr_rules().
IPRULE_PRIORITY_ADDR_MASK
#define IPRULE_PRIORITY_ADDR_MASK 20000
Definition at line 21 of file iprule.h.
Referenced by interface_add_addr_rules(), and interface_set_prefix_address().
IPRULE_PRIORITY_NW
#define IPRULE_PRIORITY_NW 90000
Definition at line 22 of file iprule.h.
Referenced by interface_set_prefix_address(), and set_ip_lo_policy().
IPRULE_PRIORITY_REJECT
#define IPRULE_PRIORITY_REJECT 4200000000
Definition at line 23 of file iprule.h.
Referenced by interface_ip_set_enabled(), and interface_set_prefix_address().
Enumeration Type Documentation
iprule_flags
enum iprule_flags
Enumerator
IPRULE_INET4 (0 << 0)
IPRULE_INET6 (1 << 0)
IPRULE_FAMILY IPRULE_INET4 | IPRULE_INET6
IPRULE_IN (1 << 2)
IPRULE_OUT (1 << 3)
IPRULE_SRC (1 << 4)
IPRULE_DEST (1 << 5)
IPRULE_PRIORITY (1 << 6)
IPRULE_TOS (1 << 7)
IPRULE_FWMARK (1 << 8)
IPRULE_FWMASK (1 << 9)
IPRULE_LOOKUP (1 << 10)
IPRULE_ACTION (1 << 11)
IPRULE_GOTO (1 << 12)
IPRULE_SUP_PREFIXLEN (1 << 13)
IPRULE_UIDRANGE (1 << 14)
Definition at line 25 of file iprule.h.
                  {
    /* address family for rule */
    IPRULE_INET4        = (0 << 0),
    IPRULE_INET6        = (1 << 0),
    IPRULE_FAMILY       = IPRULE_INET4 | IPRULE_INET6,
    /* rule specifies input device */
    IPRULE_IN       = (1 << 2),
    /* rule specifies output device */
    IPRULE_OUT      = (1 << 3),
    /* rule specifies src */
    IPRULE_SRC      = (1 << 4),
    /* rule specifies dest */
    IPRULE_DEST     = (1 << 5),
    /* rule specifies priority */
    IPRULE_PRIORITY     = (1 << 6),
    /* rule specifies diffserv/tos */
    IPRULE_TOS      = (1 << 7),
    /* rule specifies fwmark */
    IPRULE_FWMARK       = (1 << 8),
    /* rule specifies fwmask */
    IPRULE_FWMASK       = (1 << 9),
    /* rule performs table lookup */
    IPRULE_LOOKUP       = (1 << 10),
    /* rule performs routing action */
    IPRULE_ACTION       = (1 << 11),
    /* rule is a goto */
    IPRULE_GOTO     = (1 << 12),
    /* rule suppresses results by prefix length */
    IPRULE_SUP_PREFIXLEN    = (1 << 13),
    /* rule specifies uidrange */
    IPRULE_UIDRANGE     = (1 << 14),
};
Function Documentation
iprule_add()
void iprule_add (struct blob_attr * attr, bool v6)
Definition at line 201 of file iprule.c.
{
    struct blob_attr *tb[__RULE_MAX], *cur;
    struct iprule *rule;
    char *iface_name;
    int af = v6 ? AF_INET6 : AF_INET;
    blobmsg_parse(rule_attr, __RULE_MAX, tb, blobmsg_data(attr), blobmsg_data_len(attr));
    if ((cur = tb[RULE_DISABLED]) != NULL && blobmsg_get_bool(cur))
        return;
    rule = calloc(1, sizeof(*rule));
    if (!rule)
        return;
    rule->flags = v6 ? IPRULE_INET6 : IPRULE_INET4;
    rule->order = iprules_counter[rule->flags]++;
    if ((cur = tb[RULE_INVERT]) != NULL)
        rule->invert = blobmsg_get_bool(cur);
    if ((cur = tb[RULE_INTERFACE_IN]) != NULL) {
        iface_name = calloc(1, strlen(blobmsg_data(cur)) + 1);
        rule->in_iface = strcpy(iface_name, blobmsg_data(cur));
        rule->in_iface_user.cb = &rule_in_cb;
        rule->flags |= IPRULE_IN;
    }
    if ((cur = tb[RULE_INTERFACE_OUT]) != NULL) {
        iface_name = calloc(1, strlen(blobmsg_data(cur)) + 1);
        rule->out_iface = strcpy(iface_name, blobmsg_data(cur));
        rule->out_iface_user.cb = &rule_out_cb;
        rule->flags |= IPRULE_OUT;
    }
    if ((cur = tb[RULE_SRC]) != NULL) {
        if (!parse_ip_and_netmask(af, blobmsg_data(cur), &rule->src_addr, &rule->src_mask)) {
            D(INTERFACE, "Failed to parse rule source: %s", (char *) blobmsg_data(cur));
            goto error;
        }
        rule->flags |= IPRULE_SRC;
    }
    if ((cur = tb[RULE_DEST]) != NULL) {
        if (!parse_ip_and_netmask(af, blobmsg_data(cur), &rule->dest_addr, &rule->dest_mask)) {
            D(INTERFACE, "Failed to parse rule destination: %s", (char *) blobmsg_data(cur));
            goto error;
        }
        rule->flags |= IPRULE_DEST;
    }
    if ((cur = tb[RULE_PRIORITY]) != NULL) {
        rule->priority = blobmsg_get_u32(cur);
        rule->flags |= IPRULE_PRIORITY;
    }
    if ((cur = tb[RULE_TOS]) != NULL) {
        if ((rule->tos = blobmsg_get_u32(cur)) > 255) {
            D(INTERFACE, "Invalid TOS value: %u", blobmsg_get_u32(cur));
            goto error;
        }
        rule->flags |= IPRULE_TOS;
    }
    if ((cur = tb[RULE_FWMARK]) != NULL) {
        if (!iprule_parse_mark(blobmsg_data(cur), rule)) {
            D(INTERFACE, "Failed to parse rule fwmark: %s", (char *) blobmsg_data(cur));
            goto error;
        }
        /* flags set by iprule_parse_mark() */
    }
    if ((cur = tb[RULE_LOOKUP]) != NULL) {
        if (!system_resolve_rt_table(blobmsg_data(cur), &rule->lookup)) {
            D(INTERFACE, "Failed to parse rule lookup table: %s", (char *) blobmsg_data(cur));
            goto error;
        }
        rule->flags |= IPRULE_LOOKUP;
    }
    if ((cur = tb[RULE_SUP_PREFIXLEN]) != NULL) {
        rule->sup_prefixlen = blobmsg_get_u32(cur);
        rule->flags |= IPRULE_SUP_PREFIXLEN;
    }
    if ((cur = tb[RULE_UIDRANGE]) != NULL) {
        int ret = sscanf(blobmsg_get_string(cur), "%u-%u", &rule->uidrange_start, &rule->uidrange_end);
        if (ret == 1)
            rule->uidrange_end = rule->uidrange_start;
        else if (ret != 2) {
            D(INTERFACE, "Failed to parse UID range: %s", (char *) blobmsg_data(cur));
            goto error;
        }
        rule->flags |= IPRULE_UIDRANGE;
    }
    if ((cur = tb[RULE_ACTION]) != NULL) {
        if (!system_resolve_iprule_action(blobmsg_data(cur), &rule->action)) {
            D(INTERFACE, "Failed to parse rule action: %s", (char *) blobmsg_data(cur));
            goto error;
        }
        rule->flags |= IPRULE_ACTION;
    }
    if ((cur = tb[RULE_GOTO]) != NULL) {
        rule->gotoid = blobmsg_get_u32(cur);
        rule->flags |= IPRULE_GOTO;
    }
    vlist_add(&iprules, &rule->node, rule);
    return;
error:
    free(rule);
}
References __RULE_MAX, iprule::action, blobmsg_data(), blobmsg_data_len(), blobmsg_get_bool(), blobmsg_get_string(), blobmsg_get_u32(), blobmsg_parse(), interface_user::cb, D, iprule::dest_addr, iprule::dest_mask, iprule::flags, iprule::gotoid, iprule::in_iface, iprule::in_iface_user, iprule::invert, IPRULE_ACTION, IPRULE_DEST, IPRULE_GOTO, IPRULE_IN, IPRULE_INET4, IPRULE_INET6, IPRULE_LOOKUP, IPRULE_OUT, iprule_parse_mark(), IPRULE_PRIORITY, IPRULE_SRC, IPRULE_SUP_PREFIXLEN, IPRULE_TOS, IPRULE_UIDRANGE, iprules, iprules_counter, iprule::lookup, iprule::node, iprule::order, iprule::out_iface, iprule::out_iface_user, parse_ip_and_netmask(), iprule::priority, RULE_ACTION, rule_attr, RULE_DEST, RULE_DISABLED, RULE_FWMARK, RULE_GOTO, rule_in_cb(), RULE_INTERFACE_IN, RULE_INTERFACE_OUT, RULE_INVERT, RULE_LOOKUP, rule_out_cb(), RULE_PRIORITY, RULE_SRC, RULE_SUP_PREFIXLEN, RULE_TOS, RULE_UIDRANGE, iprule::src_addr, iprule::src_mask, iprule::sup_prefixlen, system_resolve_iprule_action(), system_resolve_rt_table(), iprule::tos, iprule::uidrange_end, iprule::uidrange_start, and vlist_add().
Referenced by config_parse_rule().
iprule_update_complete()
void iprule_update_complete (void)
Definition at line 333 of file iprule.c.
{
    vlist_flush(&iprules);
}
References iprules, and vlist_flush().
Referenced by config_init_rules().
iprule_update_start()
void iprule_update_start (void)
Definition at line 320 of file iprule.c.
{
    if (!iprules_flushed) {
        system_flush_iprules();
        iprules_flushed = true;
    }
    iprules_counter[0] = 1;
    iprules_counter[1] = 1;
    vlist_update(&iprules);
}
References iprules, iprules_counter, iprules_flushed, system_flush_iprules(), and vlist_update().
Referenced by config_init_rules().
Variable Documentation
iprules
struct vlist_tree iprules extern
Definition at line 30 of file iprule.c.
Referenced by generic_interface_cb(), iprule_add(), iprule_init_list(), iprule_update_complete(), and iprule_update_start().
rule_attr_list
const struct uci_blob_param_list rule_attr_list extern
Definition at line 69 of file iprule.c.
{
    .n_params = __RULE_MAX,
    .params = rule_attr,
};
Referenced by config_parse_rule().