zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/initd/init.h File Reference
init.h File Reference
#include <errno.h>
#include "../log.h"
Macros
#define EARLY_PATH "/usr/sbin:/sbin:/usr/bin:/bin"
Functions
void preinit (void)
void early (void)
int mkdev (const char *progname, int progmode)
Macro Definition Documentation
EARLY_PATH
#define EARLY_PATH "/usr/sbin:/sbin:/usr/bin:/bin"
Definition at line 22 of file init.h.
Referenced by early_env().
Function Documentation
early()
void early (void)
Definition at line 91 of file early.c.
{
    if (getpid() != 1)
        return;
    early_mounts();
    early_env();
    LOG("Console is alive\n");
}
References early_env(), early_mounts(), and LOG.
Referenced by main().
mkdev()
int mkdev (const char * progname, int progmode)
Definition at line 112 of file mkdev.c.
{
    char *pattern;
    if (chdir("/dev"))
        return 1;
    pattern = add_pattern(name);
    patterns = &pattern;
    mode = _mode;
    n_patterns = 1;
    find_devs(true);
    find_devs(false);
    free(pattern);
    return chdir("/");
}
References add_pattern(), find_devs(), n_patterns, and patterns.
Referenced by early_dev().
preinit()
void preinit (void)
Definition at line 124 of file preinit.c.
{
    char *init[] = { "/bin/sh", "/etc/preinit", NULL };
    char *plug[] = { "/sbin/procd", "-h", "/etc/hotplug-preinit.json", NULL };
    int fd;
    LOG("- preinit -\n");
    plugd_proc.cb = plugd_proc_cb;
    plugd_proc.pid = fork();
    if (!plugd_proc.pid) {
        execvp(plug[0], plug);
        ERROR("Failed to start plugd: %m\n");
        exit(EXIT_FAILURE);
    }
    if (plugd_proc.pid <= 0) {
        ERROR("Failed to start new plugd instance: %m\n");
        return;
    }
    uloop_process_add(&plugd_proc);
    setenv("PREINIT", "1", 1);
    fd = creat("/tmp/.preinit", 0600);
    if (fd < 0)
        ERROR("Failed to create sentinel file: %m\n");
    else
        close(fd);
    preinit_proc.cb = spawn_procd;
    preinit_proc.pid = fork();
    if (!preinit_proc.pid) {
        execvp(init[0], init);
        ERROR("Failed to start preinit: %m\n");
        exit(EXIT_FAILURE);
    }
    if (preinit_proc.pid <= 0) {
        ERROR("Failed to start new preinit instance: %m\n");
        return;
    }
    uloop_process_add(&preinit_proc);
    DEBUG(4, "Launched preinit instance, pid=%d\n", (int) preinit_proc.pid);
}
References uloop_process::cb, DEBUG, ERROR, LOG, uloop_process::pid, plugd_proc, plugd_proc_cb(), preinit_proc, spawn_procd(), and uloop_process_add().
Referenced by main(), and watchdog_init().