zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/service/instance.h File Reference
instance.h File Reference
#include <libubox/vlist.h>
#include <libubox/uloop.h>
#include <libubox/ustream.h>
#include "../utils/utils.h"
Classes
struct jail
struct watchdog
struct service_instance
Macros
#define RESPAWN_ERROR (5 * 60)
#define SIGNALLED_OFFSET 128
Typedefs
typedef enum instance_watchdog instance_watchdog_mode_t
Enumerations
enum instance_watchdog { INSTANCE_WATCHDOG_MODE_DISABLED , INSTANCE_WATCHDOG_MODE_PASSIVE , INSTANCE_WATCHDOG_MODE_ACTIVE , __INSTANCE_WATCHDOG_MODE_MAX }
Functions
void instance_start (struct service_instance *in)
void instance_stop (struct service_instance *in, bool halt)
void instance_update (struct service_instance *in, struct service_instance *in_new)
void instance_init (struct service_instance *in, struct service *s, struct blob_attr *config)
void instance_free (struct service_instance *in)
void instance_dump (struct blob_buf *b, struct service_instance *in, int debug)
Class Documentation
jail
struct jail
Definition at line 26 of file instance.h.
Class Members
int argc
bool cgroupsns
bool console
char * hostname
bool log
struct blobmsg_list mount
char * name
bool netns
char * pidfile
bool procfs
bool ronly
struct blobmsg_list setns
bool sysfs
bool ubus
bool userns
watchdog
struct watchdog
Definition at line 51 of file instance.h.
Class Members
uint32_t freq
instance_watchdog_mode_t mode
struct uloop_timeout timeout
service_instance
struct service_instance
Definition at line 57 of file instance.h.
Class Members
struct ustream_fd _stderr
struct ustream_fd _stdout
char * bundle
char * capabilities
struct blob_attr * command
struct blob_attr * config
struct ustream_fd console
struct ustream_fd console_client
struct blobmsg_list data
struct blobmsg_list env
struct blobmsg_list errors
int exit_code
char * extroot
struct blobmsg_list file
gid_t gr_gid
char * group
bool halt
bool has_jail
bool immediately
struct jail jail
struct blobmsg_list limits
const char * name
struct blobmsg_list netdev
int8_t nice
bool no_new_privs
struct vlist_node node
char * overlaydir
char * pidfile
struct uloop_process proc
gid_t pw_gid
int reload_signal
bool require_jail
bool respawn
int respawn_count
uint32_t respawn_retry
uint32_t respawn_threshold
uint32_t respawn_timeout
bool restart
char * seccomp
struct service * srv
struct timespec start
int syslog_facility
uint32_t term_timeout
struct uloop_timeout timeout
char * tmpoverlaysize
bool trace
struct blob_attr * trigger
uid_t uid
char * user
bool valid
struct watchdog watchdog
Macro Definition Documentation
RESPAWN_ERROR
#define RESPAWN_ERROR (5 * 60)
Definition at line 23 of file instance.h.
SIGNALLED_OFFSET
#define SIGNALLED_OFFSET 128
Definition at line 24 of file instance.h.
Referenced by instance_exit_code().
Typedef Documentation
instance_watchdog_mode_t
typedef enum instance_watchdog instance_watchdog_mode_t
Enumeration Type Documentation
instance_watchdog
enum instance_watchdog
Enumerator
INSTANCE_WATCHDOG_MODE_DISABLED
INSTANCE_WATCHDOG_MODE_PASSIVE
INSTANCE_WATCHDOG_MODE_ACTIVE
__INSTANCE_WATCHDOG_MODE_MAX
Definition at line 44 of file instance.h.
{
    INSTANCE_WATCHDOG_MODE_DISABLED,
    INSTANCE_WATCHDOG_MODE_PASSIVE,
    INSTANCE_WATCHDOG_MODE_ACTIVE,
    __INSTANCE_WATCHDOG_MODE_MAX,
} instance_watchdog_mode_t;
Function Documentation
instance_dump()
void instance_dump (struct blob_buf * b, struct service_instance * in, int debug)
Definition at line 1659 of file instance.c.
{
    void *i;
    if (!in->valid)
        return;
    i = blobmsg_open_table(b, in->name);
    blobmsg_add_u8(b, "running", in->proc.pending);
    if (in->proc.pending)
        blobmsg_add_u32(b, "pid", in->proc.pid);
    if (in->command)
        blobmsg_add_blob(b, in->command);
    if (in->bundle)
        blobmsg_add_string(b, "bundle", in->bundle);
    blobmsg_add_u32(b, "term_timeout", in->term_timeout);
    if (!in->proc.pending)
        blobmsg_add_u32(b, "exit_code", in->exit_code);
    if (!avl_is_empty(&in->errors.avl)) {
        struct blobmsg_list_node *var;
        void *e = blobmsg_open_array(b, "errors");
        blobmsg_list_for_each(&in->errors, var)
            blobmsg_add_string(b, NULL, blobmsg_data(var->data));
        blobmsg_close_table(b, e);
    }
    if (!avl_is_empty(&in->env.avl)) {
        struct blobmsg_list_node *var;
        void *e = blobmsg_open_table(b, "env");
        blobmsg_list_for_each(&in->env, var)
            blobmsg_add_string(b, blobmsg_name(var->data), blobmsg_data(var->data));
        blobmsg_close_table(b, e);
    }
    if (!avl_is_empty(&in->data.avl)) {
        struct blobmsg_list_node *var;
        void *e = blobmsg_open_table(b, "data");
        blobmsg_list_for_each(&in->data, var)
            blobmsg_add_blob(b, var->data);
        blobmsg_close_table(b, e);
    }
    if (!avl_is_empty(&in->limits.avl)) {
        struct blobmsg_list_node *var;
        void *e = blobmsg_open_table(b, "limits");
        blobmsg_list_for_each(&in->limits, var)
            blobmsg_add_string(b, blobmsg_name(var->data), blobmsg_data(var->data));
        blobmsg_close_table(b, e);
    }
    if (!avl_is_empty(&in->netdev.avl)) {
        struct blobmsg_list_node *var;
        void *n = blobmsg_open_array(b, "netdev");
        blobmsg_list_for_each(&in->netdev, var)
            blobmsg_add_string(b, NULL, blobmsg_data(var->data));
        blobmsg_close_array(b, n);
    }
    if (in->reload_signal)
        blobmsg_add_u32(b, "reload_signal", in->reload_signal);
    if (in->respawn) {
        void *r = blobmsg_open_table(b, "respawn");
        blobmsg_add_u32(b, "threshold", in->respawn_threshold);
        blobmsg_add_u32(b, "timeout", in->respawn_timeout);
        blobmsg_add_u32(b, "retry", in->respawn_retry);
        blobmsg_close_table(b, r);
    }
    if (in->trace)
        blobmsg_add_u8(b, "trace", true);
    if (in->no_new_privs)
        blobmsg_add_u8(b, "no_new_privs", true);
    if (in->seccomp)
        blobmsg_add_string(b, "seccomp", in->seccomp);
    if (in->capabilities)
        blobmsg_add_string(b, "capabilities", in->capabilities);
    if (in->pidfile)
        blobmsg_add_string(b, "pidfile", in->pidfile);
    if (in->user)
        blobmsg_add_string(b, "user", in->user);
    if (in->group)
        blobmsg_add_string(b, "group", in->group);
    if (in->has_jail) {
        void *r = blobmsg_open_table(b, "jail");
        if (in->jail.name)
            blobmsg_add_string(b, "name", in->jail.name);
        if (!in->bundle) {
            if (in->jail.hostname)
                blobmsg_add_string(b, "hostname", in->jail.hostname);
            blobmsg_add_u8(b, "procfs", in->jail.procfs);
            blobmsg_add_u8(b, "sysfs", in->jail.sysfs);
            blobmsg_add_u8(b, "ubus", in->jail.ubus);
            blobmsg_add_u8(b, "log", in->jail.log);
            blobmsg_add_u8(b, "ronly", in->jail.ronly);
            blobmsg_add_u8(b, "netns", in->jail.netns);
            blobmsg_add_u8(b, "userns", in->jail.userns);
            blobmsg_add_u8(b, "cgroupsns", in->jail.cgroupsns);
        } else {
            if (in->jail.pidfile)
                blobmsg_add_string(b, "pidfile", in->jail.pidfile);
            blobmsg_add_u8(b, "immediately", in->immediately);
        }
        blobmsg_add_u8(b, "console", (in->console.fd.fd > -1));
        blobmsg_close_table(b, r);
        if (!avl_is_empty(&in->jail.mount.avl)) {
            struct blobmsg_list_node *var;
            void *e = blobmsg_open_table(b, "mount");
            blobmsg_list_for_each(&in->jail.mount, var)
                blobmsg_add_string(b, blobmsg_name(var->data), blobmsg_data(var->data));
            blobmsg_close_table(b, e);
        }
        if (!avl_is_empty(&in->jail.setns.avl)) {
            struct blobmsg_list_node *var;
            void *s = blobmsg_open_array(b, "setns");
            blobmsg_list_for_each(&in->jail.setns, var)
                blobmsg_add_blob(b, var->data);
            blobmsg_close_array(b, s);
        }
    }
    if (in->extroot)
        blobmsg_add_string(b, "extroot", in->extroot);
    if (in->overlaydir)
        blobmsg_add_string(b, "overlaydir", in->overlaydir);
    if (in->tmpoverlaysize)
        blobmsg_add_string(b, "tmpoverlaysize", in->tmpoverlaysize);
    if (verbose && in->trigger)
        blobmsg_add_blob(b, in->trigger);
    if (in->watchdog.mode != INSTANCE_WATCHDOG_MODE_DISABLED) {
        void *r = blobmsg_open_table(b, "watchdog");
        blobmsg_add_u32(b, "mode", in->watchdog.mode);
        blobmsg_add_u32(b, "timeout", in->watchdog.freq);
        blobmsg_close_table(b, r);
    }
    blobmsg_close_table(b, i);
}
References blobmsg_list::avl, avl_is_empty(), b, blobmsg_add_blob(), blobmsg_add_string(), blobmsg_add_u32(), blobmsg_add_u8(), blobmsg_close_array(), blobmsg_close_table(), blobmsg_data(), blobmsg_list_for_each, blobmsg_name(), blobmsg_open_array(), blobmsg_open_table(), service_instance::bundle, service_instance::capabilities, jail::cgroupsns, service_instance::command, service_instance::console, blobmsg_list_node::data, service_instance::data, service_instance::env, service_instance::errors, service_instance::exit_code, service_instance::extroot, uloop_fd::fd, ustream_fd::fd, watchdog::freq, service_instance::group, service_instance::has_jail, jail::hostname, service_instance::immediately, INSTANCE_WATCHDOG_MODE_DISABLED, service_instance::jail, service_instance::limits, jail::log, watchdog::mode, jail::mount, jail::name, service_instance::name, service_instance::netdev, jail::netns, service_instance::no_new_privs, service_instance::overlaydir, uloop_process::pending, uloop_process::pid, jail::pidfile, service_instance::pidfile, service_instance::proc, jail::procfs, r, service_instance::reload_signal, service_instance::respawn, service_instance::respawn_retry, service_instance::respawn_threshold, service_instance::respawn_timeout, jail::ronly, service_instance::seccomp, jail::setns, jail::sysfs, service_instance::term_timeout, service_instance::tmpoverlaysize, service_instance::trace, service_instance::trigger, jail::ubus, service_instance::user, jail::userns, service_instance::valid, verbose, and service_instance::watchdog.
Referenced by service_dump().
instance_free()
void instance_free (struct service_instance * in)
Definition at line 1589 of file instance.c.
{
    instance_free_stdio(in);
    uloop_process_delete(&in->proc);
    uloop_timeout_cancel(&in->timeout);
    uloop_timeout_cancel(&in->watchdog.timeout);
    trigger_del(in);
    watch_del(in);
    instance_config_cleanup(in);
    free(in->config);
    free(in->user);
    free(in->group);
    free(in->extroot);
    free(in->overlaydir);
    free(in->tmpoverlaysize);
    free(in->bundle);
    free(in->jail.name);
    free(in->jail.hostname);
    free(in->jail.pidfile);
    free(in->seccomp);
    free(in->capabilities);
    free(in->pidfile);
    free(in);
}
References service_instance::bundle, service_instance::capabilities, service_instance::config, service_instance::extroot, service_instance::group, jail::hostname, instance_config_cleanup(), instance_free_stdio(), service_instance::jail, jail::name, service_instance::overlaydir, jail::pidfile, service_instance::pidfile, service_instance::proc, service_instance::seccomp, service_instance::timeout, watchdog::timeout, service_instance::tmpoverlaysize, trigger_del(), uloop_process_delete(), uloop_timeout_cancel(), service_instance::user, watch_del(), and service_instance::watchdog.
Referenced by instance_delete(), and service_instance_update().
instance_init()
void instance_init (struct service_instance * in, struct service * s, struct blob_attr * config)
Definition at line 1615 of file instance.c.
{
    config = blob_memdup(config);
    in->srv = s;
    in->name = blobmsg_name(config);
    in->config = config;
    in->timeout.cb = instance_timeout;
    in->proc.cb = instance_exit;
    in->term_timeout = 5;
    in->syslog_facility = LOG_DAEMON;
    in->exit_code = 0;
    in->require_jail = false;
    in->immediately = false;
    in->_stdout.fd.fd = -2;
    in->_stdout.stream.string_data = true;
    in->_stdout.stream.notify_read = instance_stdout;
    in->_stderr.fd.fd = -2;
    in->_stderr.stream.string_data = true;
    in->_stderr.stream.notify_read = instance_stderr;
    in->console.fd.fd = -2;
    in->console.stream.string_data = true;
    in->console.stream.notify_read = instance_console;
    in->console_client.fd.fd = -2;
    in->console_client.stream.string_data = true;
    in->console_client.stream.notify_read = instance_console_client;
    blobmsg_list_init(&in->netdev, struct instance_netdev, node, instance_netdev_cmp);
    blobmsg_list_init(&in->file, struct instance_file, node, instance_file_cmp);
    blobmsg_list_simple_init(&in->env);
    blobmsg_list_simple_init(&in->data);
    blobmsg_list_simple_init(&in->limits);
    blobmsg_list_simple_init(&in->errors);
    blobmsg_list_simple_init(&in->jail.mount);
    blobmsg_list_simple_init(&in->jail.setns);
    in->watchdog.timeout.cb = instance_watchdog;
    in->valid = instance_config_parse(in);
}
References service_instance::_stderr, service_instance::_stdout, blob_memdup(), blobmsg_list_init, blobmsg_list_simple_init, blobmsg_name(), uloop_process::cb, uloop_timeout::cb, config, service_instance::config, service_instance::console, service_instance::console_client, service_instance::data, service_instance::env, service_instance::errors, service_instance::exit_code, uloop_fd::fd, ustream_fd::fd, service_instance::file, service_instance::immediately, instance_config_parse(), instance_console(), instance_console_client(), instance_exit(), instance_file_cmp(), instance_netdev_cmp(), instance_stderr(), instance_stdout(), instance_timeout(), service_instance::jail, service_instance::limits, jail::mount, service_instance::name, service_instance::netdev, ustream::notify_read, service_instance::proc, service_instance::require_jail, jail::setns, service_instance::srv, ustream_fd::stream, ustream::string_data, service_instance::syslog_facility, service_instance::term_timeout, service_instance::timeout, watchdog::timeout, service_instance::valid, and service_instance::watchdog.
Referenced by service_instance_add().
instance_start()
void instance_start (struct service_instance * in)
Definition at line 611 of file instance.c.
{
    int pid;
    int opipe[2] = { -1, -1 };
    int epipe[2] = { -1, -1 };
    if (!avl_is_empty(&in->errors.avl)) {
        LOG("Not starting instance %s::%s, an error was indicated\n", in->srv->name, in->name);
        return;
    }
    if (!in->bundle && !in->command) {
        LOG("Not starting instance %s::%s, command not set\n", in->srv->name, in->name);
        return;
    }
    if (in->proc.pending) {
        if (in->halt)
            in->restart = true;
        return;
    }
    instance_free_stdio(in);
    if (in->_stdout.fd.fd > -2) {
        if (pipe(opipe)) {
            ULOG_WARN("pipe() failed: %m\n");
            opipe[0] = opipe[1] = -1;
        }
    }
    if (in->_stderr.fd.fd > -2) {
        if (pipe(epipe)) {
            ULOG_WARN("pipe() failed: %m\n");
            epipe[0] = epipe[1] = -1;
        }
    }
    in->restart = false;
    in->halt = false;
    if (!in->valid)
        return;
    pid = fork();
    if (pid < 0)
        return;
    if (!pid) {
        uloop_done();
        closefd(opipe[0]);
        closefd(epipe[0]);
        instance_add_cgroup(in->srv->name, in->name);
        instance_run(in, opipe[1], epipe[1]);
        return;
    }
    P_DEBUG(2, "Started instance %s::%s[%d]\n", in->srv->name, in->name, pid);
    in->proc.pid = pid;
    instance_writepid(in);
    clock_gettime(CLOCK_MONOTONIC, &in->start);
    uloop_process_add(&in->proc);
    if (opipe[0] > -1) {
        ustream_fd_init(&in->_stdout, opipe[0]);
        closefd(opipe[1]);
        fcntl(opipe[0], F_SETFD, FD_CLOEXEC);
    }
    if (epipe[0] > -1) {
        ustream_fd_init(&in->_stderr, epipe[0]);
        closefd(epipe[1]);
        fcntl(epipe[0], F_SETFD, FD_CLOEXEC);
    }
    if (in->watchdog.mode != INSTANCE_WATCHDOG_MODE_DISABLED) {
        uloop_timeout_set(&in->watchdog.timeout, in->watchdog.freq * 1000);
        P_DEBUG(2, "Started instance %s::%s watchdog timer : timeout = %d\n", in->srv->name, in->name, in->watchdog.freq);
    }
    service_event("instance.start", in->srv->name, in->name);
}
References service_instance::_stderr, service_instance::_stdout, blobmsg_list::avl, avl_is_empty(), service_instance::bundle, closefd(), service_instance::command, service_instance::errors, uloop_fd::fd, ustream_fd::fd, watchdog::freq, service_instance::halt, instance_add_cgroup(), instance_free_stdio(), instance_run(), INSTANCE_WATCHDOG_MODE_DISABLED, instance_writepid(), LOG, watchdog::mode, service::name, service_instance::name, P_DEBUG, uloop_process::pending, uloop_process::pid, service_instance::proc, service_instance::restart, service_event(), service_instance::srv, service_instance::start, watchdog::timeout, ULOG_WARN, uloop_done(), uloop_process_add(), uloop_timeout_set(), ustream_fd_init(), service_instance::valid, and service_instance::watchdog.
Referenced by instance_exit(), instance_timeout(), instance_update(), service_handle_state(), and service_instance_update().
instance_stop()
void instance_stop (struct service_instance * in, bool halt)
Definition at line 867 of file instance.c.
{
    if (!in->proc.pending) {
        if (halt)
            instance_delete(in);
        return;
    }
    in->halt = halt;
    in->restart = in->respawn = false;
    kill(in->proc.pid, SIGTERM);
    if (!in->has_jail)
        uloop_timeout_set(&in->timeout, in->term_timeout * 1000);
}
References service_instance::halt, service_instance::has_jail, instance_delete(), uloop_process::pending, uloop_process::pid, service_instance::proc, service_instance::respawn, service_instance::restart, service_instance::term_timeout, service_instance::timeout, and uloop_timeout_set().
Referenced by instance_watchdog(), service_avl_stop_all(), service_handle_state(), and service_instance_update().
instance_update()
void instance_update (struct service_instance * in, struct service_instance * in_new)
Definition at line 1571 of file instance.c.
{
    bool changed = instance_config_changed(in, in_new);
    bool running = in->proc.pending;
    bool stopping = in->halt;
    if (!running || stopping) {
        instance_config_move(in, in_new);
        instance_start(in);
    } else {
        if (changed)
            instance_restart(in);
        instance_config_move(in, in_new);
        /* restart happens in the child callback handler */
    }
}
References service_instance::halt, instance_config_changed(), instance_config_move(), instance_restart(), instance_start(), uloop_process::pending, and service_instance::proc.
Referenced by service_instance_update().