zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/libubox/uloop-kqueue.c File Reference
uloop-kqueue.c File Reference
Functions
static int uloop_init_pollfd (void)
static uint16_t get_flags (unsigned int flags, unsigned int mask)
static int register_kevent (struct uloop_fd *fd, unsigned int flags)
static int register_poll (struct uloop_fd *fd, unsigned int flags)
static int __uloop_fd_delete (struct uloop_fd *fd)
static int64_t get_timestamp_us (void)
static int uloop_fetch_events (int timeout)
static int timer_register (struct uloop_interval *tm, unsigned int msecs)
static int timer_remove (struct uloop_interval *tm)
static int64_t timer_next (struct uloop_interval *tm)
Variables
static struct kevent events [ULOOP_MAX_EVENTS]
Function Documentation
__uloop_fd_delete()
static int __uloop_fd_delete (struct uloop_fd * fd) static
Definition at line 101 of file uloop-kqueue.c.
{
    return register_poll(fd, 0);
}
References register_poll().
get_flags()
static uint16_t get_flags (unsigned int flags, unsigned int mask) static
Definition at line 37 of file uloop-kqueue.c.
{
    uint16_t kflags = 0;
    if (!(flags & mask))
        return EV_DELETE;
    kflags = EV_ADD;
    if (flags & ULOOP_EDGE_TRIGGER)
        kflags |= EV_CLEAR;
    return kflags;
}
References ULOOP_EDGE_TRIGGER.
Referenced by __attribute__(), bridge_create(), and register_kevent().
get_timestamp_us()
static int64_t get_timestamp_us (void) static
Definition at line 106 of file uloop-kqueue.c.
{
#ifdef CLOCK_MONOTONIC
    struct timespec ts = { 0, 0 };
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return ts.tv_sec * 1000000 + ts.tv_nsec / 1000;
#else
    struct timeval tv = { 0, 0 };
    gettimeofday(&tv, NULL);
    return tv.tv_sec * 1000000 + tv.tv_usec;
#endif
}
Referenced by timer_next(), timer_register(), and uloop_fetch_events().
register_kevent()
static int register_kevent (struct uloop_fd * fd, unsigned int flags) static
Definition at line 53 of file uloop-kqueue.c.
{
    struct timespec timeout = { 0, 0 };
    struct kevent ev[2];
    int nev = 0;
    unsigned int fl = 0;
    unsigned int changed;
    uint16_t kflags;
    if (flags & ULOOP_EDGE_DEFER)
        flags &= ~ULOOP_EDGE_TRIGGER;
    changed = flags ^ fd->flags;
    if (changed & ULOOP_EDGE_TRIGGER)
        changed |= flags;
    if (!changed)
        return 0;
    if (changed & ULOOP_READ) {
        kflags = get_flags(flags, ULOOP_READ);
        EV_SET(&ev[nev++], fd->fd, EVFILT_READ, kflags, 0, 0, fd);
    }
    if (changed & ULOOP_WRITE) {
        kflags = get_flags(flags, ULOOP_WRITE);
        EV_SET(&ev[nev++], fd->fd, EVFILT_WRITE, kflags, 0, 0, fd);
    }
    if (!flags)
        fl |= EV_DELETE;
    if (kevent(poll_fd, ev, nev, NULL, fl, &timeout) == -1)
        return -1;
    return 0;
}
References uloop_fd::fd, uloop_fd::flags, get_flags(), poll_fd, timeout, ULOOP_EDGE_TRIGGER, ULOOP_READ, and ULOOP_WRITE.
Referenced by register_poll(), and uloop_fetch_events().
register_poll()
static int register_poll (struct uloop_fd * fd, unsigned int flags) static
Definition at line 91 of file uloop-kqueue.c.
{
    if (flags & ULOOP_EDGE_TRIGGER)
        flags |= ULOOP_EDGE_DEFER;
    else
        flags &= ~ULOOP_EDGE_DEFER;
    return register_kevent(fd, flags);
}
References register_kevent(), and ULOOP_EDGE_TRIGGER.
Referenced by __uloop_fd_delete().
timer_next()
static int64_t timer_next (struct uloop_interval * tm) static
Definition at line 200 of file uloop-kqueue.c.
{
    int64_t t1 = tm->priv.time.fired;
    int64_t t2 = get_timestamp_us();
    while (t1 < t2)
        t1 += tm->priv.time.msecs * 1000;
    return (t1 - t2) / 1000;
}
References get_timestamp_us(), and uloop_interval::priv.
timer_register()
static int timer_register (struct uloop_interval * tm, unsigned int msecs) static
Definition at line 179 of file uloop-kqueue.c.
{
    struct kevent ev;
    tm->priv.time.msecs = msecs;
    tm->priv.time.fired = get_timestamp_us();
    EV_SET(&ev, (uintptr_t)tm, EVFILT_TIMER, EV_ADD, NOTE_USECONDS, msecs * 1000, tm);
    return kevent(poll_fd, &ev, 1, NULL, 0, NULL);
}
References get_timestamp_us(), poll_fd, and uloop_interval::priv.
timer_remove()
static int timer_remove (struct uloop_interval * tm) static
Definition at line 191 of file uloop-kqueue.c.
{
    struct kevent ev;
    EV_SET(&ev, (uintptr_t)tm, EVFILT_TIMER, EV_DELETE, 0, 0, NULL);
    return kevent(poll_fd, &ev, 1, NULL, 0, NULL);
}
References poll_fd.
uloop_fetch_events()
static int uloop_fetch_events (int timeout) static
Definition at line 123 of file uloop-kqueue.c.
{
    struct timespec ts;
    int nfds, n;
    if (timeout >= 0) {
        ts.tv_sec = timeout / 1000;
        ts.tv_nsec = (timeout % 1000) * 1000000;
    }
    nfds = kevent(poll_fd, NULL, 0, events, ARRAY_SIZE(events), timeout >= 0 ? &ts : NULL);
    for (n = 0; n < nfds; n++) {
        if (events[n].filter == EVFILT_TIMER) {
            struct uloop_interval *tm = events[n].udata;
            tm->priv.time.fired = get_timestamp_us();
            tm->expirations += events[n].data;
            tm->cb(tm);
            continue;
        }
        struct uloop_fd_event *cur = &cur_fds[n];
        struct uloop_fd *u = events[n].udata;
        unsigned int ev = 0;
        cur->fd = u;
        if (!u)
            continue;
        if (events[n].flags & EV_ERROR) {
            u->error = true;
            if (!(u->flags & ULOOP_ERROR_CB))
                uloop_fd_delete(u);
        }
        if(events[n].filter == EVFILT_READ)
            ev |= ULOOP_READ;
        else if (events[n].filter == EVFILT_WRITE)
            ev |= ULOOP_WRITE;
        if (events[n].flags & EV_EOF)
            u->eof = true;
        else if (!ev)
            cur->fd = NULL;
        cur->events = ev;
        if (u->flags & ULOOP_EDGE_DEFER) {
            u->flags &= ~ULOOP_EDGE_DEFER;
            u->flags |= ULOOP_EDGE_TRIGGER;
            register_kevent(u, u->flags);
        }
    }
    return nfds;
}
References ARRAY_SIZE, uloop_interval::cb, cur_fds, uloop_fd::eof, uloop_fd::error, events, uloop_fd_event::events, uloop_interval::expirations, uloop_fd_event::fd, uloop_fd::flags, get_timestamp_us(), poll_fd, uloop_interval::priv, register_kevent(), timeout, ULOOP_EDGE_TRIGGER, ULOOP_ERROR_CB, uloop_fd_delete(), ULOOP_READ, and ULOOP_WRITE.
uloop_init_pollfd()
static int uloop_init_pollfd (void) static
Definition at line 18 of file uloop-kqueue.c.
{
    struct timespec timeout = { 0, 0 };
    struct kevent ev = {};
    if (poll_fd >= 0)
        return 0;
    poll_fd = kqueue();
    if (poll_fd < 0)
        return -1;
    EV_SET(&ev, SIGCHLD, EVFILT_SIGNAL, EV_ADD, 0, 0, 0);
    kevent(poll_fd, &ev, 1, NULL, 0, &timeout);
    return 0;
}
References poll_fd, and timeout.
Variable Documentation
events
struct kevent events[ULOOP_MAX_EVENTS] static
Definition at line 51 of file uloop-kqueue.c.
Referenced by uloop_fetch_events().