zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/service/watch.c File Reference
watch.c File Reference
#include <stdlib.h>
#include <unistd.h>
#include <libubox/blobmsg_json.h>
#include "../procd.h"
Classes
struct watch_object
Functions
static LIST_HEAD (watch_objects)
static void watch_subscribe_cb (struct ubus_context *ctx, struct ubus_event_handler *ev, const char *type, struct blob_attr *msg)
void watch_add (const char *_name, void *id)
void watch_del (void *id)
static int watch_notify_cb (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
void watch_ubus (struct ubus_context *ctx)
Variables
static struct ubus_event_handler watch_event
static struct ubus_subscriber watch_subscribe
Class Documentation
watch_object
struct watch_object
Definition at line 22 of file watch.c.
Class Members
void * id
struct list_head list
char * name
Function Documentation
LIST_HEAD()
static LIST_HEAD (watch_objects) static
watch_add()
void watch_add (const char * _name, void * id)
Definition at line 68 of file watch.c.
{
    int len = strlen(_name);
    char *name;
    struct watch_object *o = calloc_a(sizeof(*o), &name, len + 1);
    o->name = name;
    strcpy(name, _name);
    o->id = id;
    list_add(&o->list, &watch_objects);
}
References calloc_a, id, watch_object::id, watch_object::list, list_add(), and watch_object::name.
Referenced by instance_config_parse().
watch_del()
void watch_del (void * id)
Definition at line 81 of file watch.c.
{
    struct watch_object *t, *n;
    list_for_each_entry_safe(t, n, &watch_objects, list) {
        if (t->id != id)
            continue;
        list_del(&t->list);
        free(t);
    }
}
References watch_object::id, watch_object::list, list_del(), and list_for_each_entry_safe.
Referenced by instance_free().
watch_notify_cb()
static int watch_notify_cb (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 94 of file watch.c.
{
    if (debug >= 3) {
        char *str;
        str = blobmsg_format_json(msg, true);
        P_DEBUG(3, "Received ubus notify '%s': %s\n", method, str);
        free(str);
    }
    trigger_event(method, msg);
    return 0;
}
References blobmsg_format_json(), debug, P_DEBUG, and trigger_event().
Referenced by watch_ubus().
watch_subscribe_cb()
static void watch_subscribe_cb (struct ubus_context * ctx, struct ubus_event_handler * ev, const char * type, struct blob_attr * msg) static
Definition at line 33 of file watch.c.
{
    static const struct blobmsg_policy policy = {
        "path", BLOBMSG_TYPE_STRING
    };
    struct watch_object *o;
    struct blob_attr *attr;
    const char *path;
    P_DEBUG(3, "ubus event %s\n", type);
    if (strcmp(type, "ubus.object.add") != 0)
        return;
    blobmsg_parse(&policy, 1, &attr, blob_data(msg), blob_len(msg));
    if (!attr)
        return;
    path = blobmsg_data(attr);
    P_DEBUG(3, "ubus path %s\n", path);
    list_for_each_entry(o, &watch_objects, list) {
        unsigned int id;
        if (strcmp(o->name, path))
            continue;
        if (ubus_lookup_id(ctx, path, &id))
            continue;
        if (!ubus_subscribe(ctx, &watch_subscribe, id))
            return;
        ERROR("failed to subscribe %d\n", id);
    }
}
References blob_data(), blob_len(), blobmsg_data(), blobmsg_parse(), BLOBMSG_TYPE_STRING, ctx, ERROR, id, list_for_each_entry, watch_object::name, P_DEBUG, path, type, ubus_lookup_id(), ubus_subscribe(), and watch_subscribe.
Referenced by watch_ubus().
watch_ubus()
void watch_ubus (struct ubus_context * ctx)
Definition at line 111 of file watch.c.
{
    watch_event.cb = watch_subscribe_cb;
    watch_subscribe.cb = watch_notify_cb;
    if (ubus_register_subscriber(ctx, &watch_subscribe))
        ERROR("failed to register ubus subscriber\n");
    if (ubus_register_event_handler(ctx, &watch_event, "ubus.object.add"))
        ERROR("failed to add ubus event handler\n");
}
References ubus_event_handler::cb, ubus_subscriber::cb, ctx, ERROR, ubus_register_event_handler(), ubus_register_subscriber(), watch_event, watch_notify_cb(), watch_subscribe, and watch_subscribe_cb().
Referenced by ubus_connect_cb().
Variable Documentation
watch_event
struct ubus_event_handler watch_event static
Definition at line 29 of file watch.c.
Referenced by watch_ubus().
watch_subscribe
struct ubus_subscriber watch_subscribe static
Definition at line 30 of file watch.c.
Referenced by watch_subscribe_cb(), and watch_ubus().