zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/ubus/ubusd_obj.c File Reference
ubusd_obj.c File Reference
#include "ubusd.h"
#include "ubusd_obj.h"
Functions
static void ubus_unref_object_type (struct ubus_object_type *type)
static bool ubus_create_obj_method (struct ubus_object_type *type, struct blob_attr *attr)
static struct ubus_object_type * ubus_create_obj_type (struct blob_attr *sig)
static struct ubus_object_type * ubus_get_obj_type (uint32_t obj_id)
struct ubus_object * ubusd_create_object_internal (struct ubus_object_type *type, uint32_t id)
struct ubus_object * ubusd_create_object (struct ubus_client *cl, struct blob_attr **attr)
void ubus_subscribe (struct ubus_object *obj, struct ubus_object *target)
void ubus_unsubscribe (struct ubus_subscription *s)
void ubusd_free_object (struct ubus_object *obj)
static void __constructor ubusd_obj_init (void)
Variables
struct avl_tree obj_types
struct avl_tree objects
struct avl_tree path
Function Documentation
ubus_create_obj_method()
static bool ubus_create_obj_method (struct ubus_object_type * type, struct blob_attr * attr) static
Definition at line 37 of file ubusd_obj.c.
{
    struct ubus_method *m;
    int bloblen = blob_raw_len(attr);
    m = calloc(1, sizeof(*m) + bloblen);
    if (!m)
        return false;
    list_add_tail(&m->list, &type->methods);
    memcpy(m->data, attr, bloblen);
    m->name = blobmsg_name(m->data);
    return true;
}
References blob_raw_len(), blobmsg_name(), ubus_method::data, ubus_method::list, list_add_tail(), ubus_method::name, and type.
Referenced by ubus_create_obj_type().
ubus_create_obj_type()
static struct ubus_object_type * ubus_create_obj_type (struct blob_attr * sig) static
Definition at line 53 of file ubusd_obj.c.
{
    struct ubus_object_type *type;
    struct blob_attr *pos;
    size_t rem;
    type = calloc(1, sizeof(*type));
    if (!type)
        return NULL;
    type->refcount = 1;
    if (!ubus_alloc_id(&obj_types, &type->id, 0))
        goto error_free;
    INIT_LIST_HEAD(&type->methods);
    blob_for_each_attr(pos, sig, rem) {
        if (!blobmsg_check_attr(pos, true))
            goto error_unref;
        if (!ubus_create_obj_method(type, pos))
            goto error_unref;
    }
    return type;
error_unref:
    ubus_unref_object_type(type);
    return NULL;
error_free:
    free(type);
    return NULL;
}
References blob_for_each_attr, blobmsg_check_attr(), INIT_LIST_HEAD(), obj_types, type, ubus_alloc_id(), ubus_create_obj_method(), and ubus_unref_object_type().
Referenced by ubusd_create_object().
ubus_get_obj_type()
static struct ubus_object_type * ubus_get_obj_type (uint32_t obj_id) static
Definition at line 89 of file ubusd_obj.c.
{
    struct ubus_object_type *type;
    struct ubus_id *id;
    id = ubus_find_id(&obj_types, obj_id);
    if (!id)
        return NULL;
    type = container_of(id, struct ubus_object_type, id);
    type->refcount++;
    return type;
}
References container_of, id, obj_types, type, and ubus_find_id().
Referenced by ubusd_create_object().
ubus_subscribe()
void ubus_subscribe (struct ubus_object * obj, struct ubus_object * target)
Definition at line 172 of file ubusd_obj.c.
{
    struct ubus_subscription *s;
    bool first = list_empty(&target->subscribers);
    s = calloc(1, sizeof(*s));
    if (!s)
        return;
    s->subscriber = obj;
    s->target = target;
    list_add(&s->list, &target->subscribers);
    list_add(&s->target_list, &obj->target_list);
    if (first)
        ubus_notify_subscription(target);
}
References list_add(), list_empty(), ubus_subscription::subscriber, ubus_subscription::target, ubus_object::target_list, ubus_subscription::target_list, and ubus_notify_subscription().
ubus_unref_object_type()
static void ubus_unref_object_type (struct ubus_object_type * type) static
Definition at line 21 of file ubusd_obj.c.
{
    struct ubus_method *m, *tmp;
    if (--type->refcount > 0)
        return;
    list_for_each_entry_safe(m, tmp, &type->methods, list) {
        list_del(&m->list);
        free(m);
    }
    ubus_free_id(&obj_types, &type->id);
    free(type);
}
References ubus_method::list, list_del(), list_for_each_entry_safe, obj_types, type, and ubus_free_id().
Referenced by ubus_create_obj_type(), ubusd_create_object(), and ubusd_free_object().
ubus_unsubscribe()
void ubus_unsubscribe (struct ubus_subscription * s)
Definition at line 190 of file ubusd_obj.c.
{
    struct ubus_object *obj = s->target;
    list_del(&s->list);
    list_del(&s->target_list);
    free(s);
    if (list_empty(&obj->subscribers))
        ubus_notify_subscription(obj);
}
References list_del(), list_empty(), ubus_subscription::target, ubus_subscription::target_list, and ubus_notify_subscription().
Referenced by ubusd_free_object().
ubusd_create_object()
struct ubus_object * ubusd_create_object (struct ubus_client * cl, struct blob_attr ** attr)
Definition at line 129 of file ubusd_obj.c.
{
    struct ubus_object *obj;
    struct ubus_object_type *type = NULL;
    if (attr[UBUS_ATTR_OBJTYPE])
        type = ubus_get_obj_type(blob_get_u32(attr[UBUS_ATTR_OBJTYPE]));
    else if (attr[UBUS_ATTR_SIGNATURE])
        type = ubus_create_obj_type(attr[UBUS_ATTR_SIGNATURE]);
    obj = ubusd_create_object_internal(type, 0);
    if (type)
        ubus_unref_object_type(type);
    if (!obj)
        return NULL;
    if (attr[UBUS_ATTR_OBJPATH]) {
        if (ubusd_acl_check(cl, blob_data(attr[UBUS_ATTR_OBJPATH]), NULL, UBUS_ACL_PUBLISH))
            goto free;
        obj->path.key = strdup(blob_data(attr[UBUS_ATTR_OBJPATH]));
        if (!obj->path.key)
            goto free;
        if (avl_insert(&path, &obj->path) != 0) {
            free((void *) obj->path.key);
            obj->path.key = NULL;
            goto free;
        }
        ubusd_send_obj_event(obj, true);
    }
    obj->client = cl;
    list_add(&obj->list, &cl->objects);
    return obj;
free:
    ubusd_free_object(obj);
    return NULL;
}
References avl_insert(), blob_data(), blob_get_u32(), ubus_object::client, ubus_object::list, list_add(), ubus_client::objects, path, ubus_object::path, type, UBUS_ACL_PUBLISH, UBUS_ATTR_OBJPATH, UBUS_ATTR_OBJTYPE, UBUS_ATTR_SIGNATURE, ubus_create_obj_type(), ubus_get_obj_type(), ubus_unref_object_type(), ubusd_acl_check(), ubusd_create_object_internal(), ubusd_free_object(), and ubusd_send_obj_event().
Referenced by ubusd_handle_add_object().
ubusd_create_object_internal()
struct ubus_object * ubusd_create_object_internal (struct ubus_object_type * type, uint32_t id)
Definition at line 103 of file ubusd_obj.c.
{
    struct ubus_object *obj;
    obj = calloc(1, sizeof(*obj));
    if (!obj)
        return NULL;
    if (!ubus_alloc_id(&objects, &obj->id, id))
        goto error_free;
    obj->type = type;
    INIT_LIST_HEAD(&obj->list);
    INIT_LIST_HEAD(&obj->events);
    INIT_LIST_HEAD(&obj->subscribers);
    INIT_LIST_HEAD(&obj->target_list);
    if (type)
        type->refcount++;
    return obj;
error_free:
    free(obj);
    return NULL;
}
References ubus_object::events, ubus_object::id, INIT_LIST_HEAD(), ubus_object::list, objects, ubus_object::target_list, type, ubus_object::type, and ubus_alloc_id().
Referenced by ubusd_acl_init(), ubusd_create_object(), ubusd_event_init(), and ubusd_monitor_init().
ubusd_free_object()
void ubusd_free_object (struct ubus_object * obj)
Definition at line 202 of file ubusd_obj.c.
{
    struct ubus_subscription *s, *tmp;
    list_for_each_entry_safe(s, tmp, &obj->target_list, target_list) {
        ubus_unsubscribe(s);
    }
    list_for_each_entry_safe(s, tmp, &obj->subscribers, list) {
        ubus_notify_unsubscribe(s);
    }
    ubusd_event_cleanup_object(obj);
    if (obj->path.key) {
        ubusd_send_obj_event(obj, false);
        avl_delete(&path, &obj->path);
        free((void *) obj->path.key);
    }
    if (!list_empty(&obj->list))
        list_del(&obj->list);
    ubus_free_id(&objects, &obj->id);
    if (obj->type)
        ubus_unref_object_type(obj->type);
    free(obj);
}
References avl_delete(), ubus_object::id, ubus_object::list, list_del(), list_empty(), list_for_each_entry_safe, objects, path, ubus_object::path, ubus_object::target_list, ubus_subscription::target_list, ubus_object::type, ubus_free_id(), ubus_notify_unsubscribe(), ubus_unref_object_type(), ubus_unsubscribe(), ubusd_event_cleanup_object(), and ubusd_send_obj_event().
Referenced by ubusd_create_object(), ubusd_handle_remove_object(), and ubusd_proto_free_client().
ubusd_obj_init()
static void __constructor ubusd_obj_init (void) static
Definition at line 227 of file ubusd_obj.c.
{
    ubus_init_id_tree(&objects);
    ubus_init_id_tree(&obj_types);
    ubus_init_string_tree(&path, false);
    ubusd_event_init();
    ubusd_acl_init();
    ubusd_monitor_init();
}
References obj_types, objects, path, ubus_init_id_tree(), ubus_init_string_tree(), ubusd_acl_init(), ubusd_event_init(), and ubusd_monitor_init().
Variable Documentation
obj_types
struct avl_tree obj_types
Definition at line 17 of file ubusd_obj.c.
Referenced by ubus_create_obj_type(), ubus_get_obj_type(), ubus_unref_object_type(), and ubusd_obj_init().
objects
struct avl_tree objects
Definition at line 18 of file ubusd_obj.c.
Referenced by ubusd_create_object_internal(), ubusd_find_object(), ubusd_free_object(), ubusd_handle_invoke(), ubusd_handle_notify(), and ubusd_obj_init().
path
struct avl_tree path
Definition at line 19 of file ubusd_obj.c.
Referenced by __rpc_check_path(), __ubusd_handle_lookup(), _add_mount_bind(), _rc(), add_2paths_and_deps(), add_mount_bind(), add_path_and_deps(), add_script_interp(), alloc_library(), alloc_library_path(), cbuf_alloc(), check_sysupgrade(), checkpath(), create_devices(), device_has_attribute(), device_list_insert(), elf_load_deps(), extdev_wait_ev_cb(), find_devs(), get_port_file(), handle_expr_isdir(), handle_firmware(), interface_write_resolv_conf(), is_bridge(), jshn_format_file(), jshn_parse_file(), lib_open(), make_dev(), netifd_ubus_init(), rc_check_script(), rc_init(), rc_list_readdir(), read_file(), rpc_blob_from_file(), rpc_blob_to_file(), rpc_canonicalize_path(), rpc_exec_lookup(), rpc_file_access(), rpc_file_exec_lookup(), rpc_file_list(), rpc_file_md5(), rpc_file_read(), rpc_file_remove(), rpc_file_remove_recursive(), rpc_file_stat(), rpc_file_write(), rpc_login_setup_acl_file(), rpc_plugin_api_init(), rpc_plugin_register_exec(), rpc_plugin_register_library(), rpc_session_freeze(), rpc_session_thaw(), rpc_uci_purge_dir(), rpc_uci_purge_savedir_cb(), rpc_uci_replace_savedir(), rpc_uci_set_savedir(), rpc_ucode_api_init(), rpc_ucode_init_script(), rpc_ucode_script_compile(), rpc_ucode_script_execute(), system_get_bridge(), sysupgrade(), sysupgrade_exec_upgraded(), ubus_auto_sub_event_handler_cb(), ubus_cli_list(), ubus_connect(), ubus_connect_ctx(), ubus_lookup(), ubus_lookup_id(), ubus_lua_call(), ubus_lua_objects(), ubus_lua_signatures(), ubus_reconnect(), ubusd_acl_load(), ubusd_create_object(), ubusd_free_object(), ubusd_obj_init(), udebug_auto_connect(), udebug_connect(), uxc_create(), uxc_set(), validate_firmware_image_call(), wait_check_object(), wait_event_cb(), watch_subscribe_cb(), and write_file().