zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/ubus/libubus-internal.h File Reference
libubus-internal.h File Reference
Functions
struct blob_attr ** ubus_parse_msg (struct blob_attr *msg, size_t len)
bool ubus_validate_hdr (struct ubus_msghdr *hdr)
void ubus_handle_data (struct uloop_fd *u, unsigned int events)
int ubus_send_msg (struct ubus_context *ctx, uint32_t seq, struct blob_attr *msg, int cmd, uint32_t peer, int fd)
void ubus_process_msg (struct ubus_context *ctx, struct ubus_msghdr_buf *buf, int fd)
int __hidden ubus_start_request (struct ubus_context *ctx, struct ubus_request *req, struct blob_attr *msg, int cmd, uint32_t peer)
int __hidden __ubus_start_request (struct ubus_context *ctx, struct ubus_request *req, struct blob_attr *msg, int cmd, uint32_t peer)
void ubus_process_obj_msg (struct ubus_context *ctx, struct ubus_msghdr_buf *buf, int fd)
void ubus_process_req_msg (struct ubus_context *ctx, struct ubus_msghdr_buf *buf, int fd)
void __hidden ubus_poll_data (struct ubus_context *ctx, int timeout)
Variables
struct blob_buf b
const struct ubus_method watch_method
Function Documentation
__ubus_start_request()
int __hidden __ubus_start_request (struct ubus_context * ctx, struct ubus_request * req, struct blob_attr * msg, int cmd, uint32_t peer)
Definition at line 53 of file libubus-req.c.
{
    if (msg && blob_pad_len(msg) > UBUS_MAX_MSGLEN)
        return -1;
    INIT_LIST_HEAD(&req->list);
    INIT_LIST_HEAD(&req->pending);
    req->ctx = ctx;
    req->peer = peer;
    req->seq = ++ctx->request_seq;
    return ubus_send_msg(ctx, req->seq, msg, cmd, peer, req->fd);
}
References blob_pad_len(), cmd, ctx, ubus_request::ctx, ubus_request::fd, INIT_LIST_HEAD(), ubus_request::list, ubus_request::peer, ubus_request::pending, ubus_context::request_seq, ubus_request::seq, and ubus_send_msg().
Referenced by ubus_invoke_async_fd(), and ubus_start_request().
ubus_handle_data()
void ubus_handle_data (struct uloop_fd * u, unsigned int events)
Definition at line 312 of file libubus-io.c.
{
    struct ubus_context *ctx = container_of(u, struct ubus_context, sock);
    int recv_fd = -1;
    while (1) {
        if (!ctx->stack_depth)
            ctx->pending_timer.cb(&ctx->pending_timer);
        if (!get_next_msg(ctx, &recv_fd))
            break;
        ubus_process_msg(ctx, &ctx->msgbuf, recv_fd);
        if (uloop_cancelling() || ctx->cancel_poll)
            break;
    }
    if (!ctx->stack_depth)
        ctx->pending_timer.cb(&ctx->pending_timer);
    if (u->eof)
        ctx->connection_lost(ctx);
}
References ubus_context::cancel_poll, uloop_timeout::cb, ubus_context::connection_lost, container_of, ctx, uloop_fd::eof, get_next_msg(), ubus_context::msgbuf, ubus_context::pending_timer, ubus_context::sock, ubus_context::stack_depth, ubus_process_msg(), and uloop_cancelling().
Referenced by ubus_connect_ctx(), and ubus_poll_data().
ubus_parse_msg()
struct blob_attr ** ubus_parse_msg (struct blob_attr * msg, size_t len)
Definition at line 46 of file libubus-io.c.
{
    blob_parse_untrusted(msg, len, attrbuf, ubus_policy, UBUS_ATTR_MAX);
    return attrbuf;
}
References attrbuf, blob_parse_untrusted(), UBUS_ATTR_MAX, and ubus_policy.
Referenced by _ubus_parse_msg(), req_data_cb(), ubus_add_object_cb(), ubus_get_status(), ubus_lookup_cb(), ubus_lookup_id_cb(), ubus_process_notify_status(), ubus_process_obj_msg(), ubus_remove_object_cb(), and ubusd_acl_recv().
ubus_poll_data()
void __hidden ubus_poll_data (struct ubus_context * ctx, int timeout)
Definition at line 335 of file libubus-io.c.
{
    struct pollfd pfd = {
        .fd = ctx->sock.fd,
        .events = POLLIN | POLLERR,
    };
    ctx->cancel_poll = false;
    poll(&pfd, 1, timeout ? timeout : -1);
    ubus_handle_data(&ctx->sock, ULOOP_READ);
}
References ubus_context::cancel_poll, ctx, uloop_fd::fd, ubus_context::sock, timeout, ubus_handle_data(), and ULOOP_READ.
Referenced by ubus_complete_request().
ubus_process_msg()
void ubus_process_msg (struct ubus_context * ctx, struct ubus_msghdr_buf * buf, int fd)
Definition at line 93 of file libubus.c.
{
    switch(buf->hdr.type) {
    case UBUS_MSG_STATUS:
    case UBUS_MSG_DATA:
        ubus_process_req_msg(ctx, buf, fd);
        break;
    case UBUS_MSG_INVOKE:
    case UBUS_MSG_UNSUBSCRIBE:
    case UBUS_MSG_NOTIFY:
        if (ctx->stack_depth) {
            ubus_queue_msg(ctx, buf);
            break;
        }
        ctx->stack_depth++;
        ubus_process_obj_msg(ctx, buf, fd);
        ctx->stack_depth--;
        break;
    case UBUS_MSG_MONITOR:
        if (ctx->monitor_cb)
            ctx->monitor_cb(ctx, buf->hdr.seq, buf->data);
        break;
    }
}
References buf, ctx, ubus_context::monitor_cb, ubus_context::stack_depth, UBUS_MSG_DATA, UBUS_MSG_INVOKE, UBUS_MSG_MONITOR, UBUS_MSG_NOTIFY, UBUS_MSG_STATUS, UBUS_MSG_UNSUBSCRIBE, ubus_process_obj_msg(), ubus_process_req_msg(), and ubus_queue_msg().
Referenced by ubus_handle_data(), and ubus_process_pending_msg().
ubus_process_obj_msg()
void ubus_process_obj_msg (struct ubus_context * ctx, struct ubus_msghdr_buf * buf, int fd)
Definition at line 115 of file libubus-obj.c.
{
    void (*cb)(struct ubus_context *, struct ubus_msghdr *,
           struct ubus_object *, struct blob_attr **, int fd);
    struct ubus_msghdr *hdr = &buf->hdr;
    struct blob_attr **attrbuf;
    struct ubus_object *obj;
    uint32_t objid;
    void *prev_data = NULL;
    attrbuf = ubus_parse_msg(buf->data, blob_raw_len(buf->data));
    if (!attrbuf[UBUS_ATTR_OBJID])
        return;
    objid = blob_get_u32(attrbuf[UBUS_ATTR_OBJID]);
    obj = avl_find_element(&ctx->objects, &objid, obj, avl);
    switch (hdr->type) {
    case UBUS_MSG_INVOKE:
        cb = ubus_process_invoke;
        break;
    case UBUS_MSG_UNSUBSCRIBE:
        cb = ubus_process_unsubscribe;
        break;
    case UBUS_MSG_NOTIFY:
        cb = ubus_process_notify;
        break;
    default:
        return;
    }
    if (buf == &ctx->msgbuf) {
        prev_data = buf->data;
        buf->data = NULL;
    }
    cb(ctx, hdr, obj, attrbuf, fd);
    if (prev_data) {
        if (buf->data)
            free(prev_data);
        else
            buf->data = prev_data;
    }
}
References attrbuf, ubus_object::avl, avl_find_element, blob_get_u32(), blob_raw_len(), buf, ctx, ubus_context::msgbuf, ubus_context::objects, ubus_msghdr::type, UBUS_ATTR_OBJID, UBUS_MSG_INVOKE, UBUS_MSG_NOTIFY, UBUS_MSG_UNSUBSCRIBE, ubus_parse_msg(), ubus_process_invoke(), ubus_process_notify(), and ubus_process_unsubscribe().
Referenced by ubus_process_msg().
ubus_process_req_msg()
void ubus_process_req_msg (struct ubus_context * ctx, struct ubus_msghdr_buf * buf, int fd)
Definition at line 462 of file libubus-req.c.
{
    struct ubus_msghdr *hdr = &buf->hdr;
    struct ubus_request *req;
    int id = -1;
    switch(hdr->type) {
    case UBUS_MSG_STATUS:
        req = ubus_find_request(ctx, hdr->seq, hdr->peer, &id);
        if (!req)
            break;
        if (fd >= 0) {
            if (req->fd_cb)
                req->fd_cb(req, fd);
            else
                close(fd);
        }
        if (id >= 0)
            ubus_process_notify_status(req, id, buf);
        else
            ubus_process_req_status(req, buf);
        break;
    case UBUS_MSG_DATA:
        req = ubus_find_request(ctx, hdr->seq, hdr->peer, &id);
        if (req && (req->data_cb || req->raw_data_cb))
            ubus_process_req_data(req, buf);
        break;
    }
}
References buf, ctx, ubus_request::data_cb, ubus_request::fd, ubus_request::fd_cb, ubus_msghdr::peer, ubus_request::raw_data_cb, ubus_msghdr::seq, ubus_msghdr::type, ubus_find_request(), UBUS_MSG_DATA, UBUS_MSG_STATUS, ubus_process_notify_status(), ubus_process_req_data(), and ubus_process_req_status().
Referenced by ubus_process_msg().
ubus_send_msg()
int ubus_send_msg (struct ubus_context * ctx, uint32_t seq, struct blob_attr * msg, int cmd, uint32_t peer, int fd)
Definition at line 126 of file libubus-io.c.
{
    struct ubus_msghdr hdr;
    struct iovec iov[2] = {
        STATIC_IOV(hdr)
    };
    int ret;
    hdr.version = 0;
    hdr.type = cmd;
    hdr.seq = cpu_to_be16(seq);
    hdr.peer = cpu_to_be32(peer);
    if (!msg) {
        blob_buf_init(&b, 0);
        msg = b.head;
    }
    iov[1].iov_base = (char *) msg;
    iov[1].iov_len = blob_raw_len(msg);
    ret = writev_retry(ctx->sock.fd, iov, ARRAY_SIZE(iov), fd);
    if (ret < 0)
        ctx->sock.eof = true;
    if (fd >= 0)
        close(fd);
    return ret;
}
References ARRAY_SIZE, b, blob_buf_init(), blob_raw_len(), cmd, cpu_to_be16, cpu_to_be32, ctx, uloop_fd::eof, uloop_fd::fd, blob_buf::head, ubus_msghdr::peer, ubus_msghdr::seq, ubus_context::sock, STATIC_IOV, ubus_msghdr::type, ubus_msghdr::version, and writev_retry().
Referenced by __ubus_start_request(), ubus_complete_deferred_request(), and ubus_send_reply().
ubus_start_request()
int __hidden ubus_start_request (struct ubus_context * ctx, struct ubus_request * req, struct blob_attr * msg, int cmd, uint32_t peer)
Definition at line 69 of file libubus-req.c.
{
    memset(req, 0, sizeof(*req));
    req->fd = -1;
    return __ubus_start_request(ctx, req, msg, cmd, peer);
}
References __ubus_start_request(), cmd, ctx, and ubus_request::fd.
Referenced by __ubus_notify_async(), __ubus_subscribe_request(), ubus_add_object(), ubus_lookup(), ubus_lookup_id(), ubus_remove_object(), and ubus_send_event().
ubus_validate_hdr()
bool ubus_validate_hdr (struct ubus_msghdr * hdr)
Definition at line 224 of file libubus-io.c.
{
    struct blob_attr *data = (struct blob_attr *) (hdr + 1);
    if (hdr->version != 0)
        return false;
    if (blob_raw_len(data) < sizeof(*data))
        return false;
    if (blob_pad_len(data) > UBUS_MAX_MSGLEN)
        return false;
    return true;
}
References blob_pad_len(), blob_raw_len(), blob_attr::data, and ubus_msghdr::version.
Referenced by _ubus_validate_hdr(), get_next_msg(), and ubus_reconnect().
Variable Documentation
b
struct blob_buf b extern
Definition at line 19 of file ubusd_proto.c.
watch_method
const struct ubus_method watch_method extern
Referenced by ubus_process_unsubscribe(), and ubus_register_subscriber().