zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/netifd/extdev.h File Reference
extdev.h File Reference
Functions
void extdev_init (void)
Function Documentation
extdev_init()
void extdev_init (void)
Definition at line 1369 of file extdev.c.
{
    confdir_fd = netifd_open_subdir("extdev-config");
    if (confdir_fd < 0)
        return;
    netifd_init_extdev_handlers(confdir_fd, extdev_add_devtype);
}
References confdir_fd, extdev_add_devtype(), netifd_init_extdev_handlers(), and netifd_open_subdir().
Referenced by main().