zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/trace/trace.c File Reference
trace.c File Reference
#include <fcntl.h>
#include <stddef.h>
#include <sys/ptrace.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/user.h>
#include <sys/wait.h>
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <errno.h>
#include <libgen.h>
#include <syslog.h>
#include <limits.h>
#include <libubox/ulog.h>
#include <libubox/uloop.h>
#include <libubox/blobmsg.h>
#include <libubox/blobmsg_json.h>
#include "../syscall-names.h"
Classes
struct tracee
struct syscall
Macros
#define _GNU_SOURCE
#define PTRACE_EVENT_STOP 128
#define PTRACE_EVENT_SECCOMP 7
#define _offsetof(a, b)
#define ARRAY_SIZE(arr)
Enumerations
enum mode { UTRACE , SECCOMP_TRACE }
Functions
static void set_syscall (const char *name, int val)
static int cmp_count (const void *a, const void *b)
static void print_syscalls (int policy, const char *json)
static void report_seccomp_vialation (pid_t pid, unsigned syscall)
static void tracer_cb (struct uloop_process *c, int ret)
static void sigterm_handler (int signum)
int main (int argc, char **argv, char **envp)
Variables
enum mode mode = UTRACE
static struct tracee tracer
static int syscall_count [SYSCALL_COUNT]
static int violation_count
static struct blob_buf b
static int debug
char * json = NULL
int ptrace_restart
Class Documentation
tracee
struct tracee
Definition at line 80 of file trace.c.
Class Members
int in_syscall
struct uloop_process proc
syscall
struct syscall
Definition at line 106 of file trace.c.
Class Members
int count
int syscall
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 14 of file trace.c.
_offsetof
#define _offsetof (a, b)
Value:
__builtin_offsetof(a,b)
Definition at line 48 of file trace.c.
ARRAY_SIZE
#define ARRAY_SIZE (arr)
Value:
(sizeof(arr) / sizeof((arr)[0]))
Definition at line 49 of file trace.c.
PTRACE_EVENT_SECCOMP
#define PTRACE_EVENT_SECCOMP 7
Definition at line 38 of file trace.c.
Referenced by tracer_cb().
PTRACE_EVENT_STOP
#define PTRACE_EVENT_STOP 128
Definition at line 33 of file trace.c.
Referenced by tracer_cb().
Enumeration Type Documentation
mode
enum mode
Enumerator
UTRACE
SECCOMP_TRACE
Definition at line 75 of file trace.c.
          {
    UTRACE,
    SECCOMP_TRACE,
} mode = UTRACE;
Function Documentation
cmp_count()
static int cmp_count (const void * a, const void * b) static
Definition at line 111 of file trace.c.
{
    return ((struct syscall*)b)->count - ((struct syscall*)a)->count;
}
References b, and syscall::count.
Referenced by print_syscalls().
main()
int main (int argc, char ** argv, char ** envp)
Definition at line 308 of file trace.c.
{
    int status, ch, policy = EPERM;
    pid_t child;
    /* When invoked via seccomp-trace symlink, work as seccomp
     * violation logger rather than as syscall tracer */
    if (strstr(argv[0], "seccomp-trace"))
        mode = SECCOMP_TRACE;
    while ((ch = getopt(argc, argv, "f:p:")) != -1) {
        switch (ch) {
        case 'f':
            json = optarg;
            break;
        case 'p':
            policy = atoi(optarg);
            break;
        }
    }
    if (!json)
        json = getenv("SECCOMP_FILE");
    argc -= optind;
    argv += optind;
    if (!argc)
        return -1;
    if (getenv("TRACE_DEBUG"))
        debug = 1;
    unsetenv("TRACE_DEBUG");
    child = fork();
    if (child == 0) {
        char **_argv = calloc(argc + 1, sizeof(char *));
        char **_envp;
        char *preload = NULL;
        const char *old_preload = getenv("LD_PRELOAD");
        int newenv = 0;
        int envc = 0;
        int ret;
        memcpy(_argv, argv, argc * sizeof(char *));
        while (envp[envc++])
            ;
        _envp = calloc(envc + 2, sizeof(char *));
        switch (mode) {
        case UTRACE:
            preload = "/lib/libpreload-trace.so";
            newenv = 1;
            break;
        case SECCOMP_TRACE:
            preload = "/lib/libpreload-seccomp.so";
            newenv = 2;
            if (asprintf(&_envp[1], "SECCOMP_FILE=%s", json ? json : "") < 0)
                ULOG_ERR("failed to allocate SECCOMP_FILE env: %m\n");
            kill(getpid(), SIGSTOP);
            break;
        }
        if (asprintf(&_envp[0], "LD_PRELOAD=%s%s%s", preload,
                 old_preload ? ":" : "",
                  old_preload ? old_preload : "") < 0)
            ULOG_ERR("failed to allocate LD_PRELOAD env: %m\n");
        memcpy(&_envp[newenv], envp, envc * sizeof(char *));
        ret = execve(_argv[0], _argv, _envp);
        ULOG_ERR("failed to exec %s: %m\n", _argv[0]);
        free(_argv);
        if (_envp[0])
            free(_envp[0]);
        if (newenv == 2 && _envp[1])
            free(_envp[1]);
        free(_envp);
        return ret;
    }
    if (child < 0)
        return -1;
    waitpid(child, &status, WUNTRACED);
    if (!WIFSTOPPED(status)) {
        ULOG_ERR("failed to start %s\n", *argv);
        return -1;
    }
    /* Initialize uloop to catch all ptrace stops from now on. */
    uloop_init();
    int ptrace_options = PTRACE_O_TRACEFORK | PTRACE_O_TRACEVFORK | PTRACE_O_TRACECLONE;
    switch (mode) {
    case UTRACE:
        ptrace_options |= PTRACE_O_TRACESYSGOOD;
        ptrace_restart = PTRACE_SYSCALL;
        break;
    case SECCOMP_TRACE:
        ptrace_options |= PTRACE_O_TRACESECCOMP;
        ptrace_restart = PTRACE_CONT;
        break;
    }
    if (ptrace(PTRACE_SEIZE, child, 0, ptrace_options) == -1) {
        ULOG_ERR("PTRACE_SEIZE: %m\n");
        return -1;
    }
    if (ptrace(ptrace_restart, child, 0, SIGCONT) == -1) {
        ULOG_ERR("ptrace_restart: %m\n");
        return -1;
    }
    tracer.proc.pid = child;
    tracer.proc.cb = tracer_cb;
    uloop_process_add(&tracer.proc);
    signal(SIGTERM, sigterm_handler); /* Override uloop's SIGTERM handler */
    uloop_run();
    uloop_done();
    switch (mode) {
    case UTRACE:
        if (!json)
            if (asprintf(&json, "/tmp/%s.%u.json", basename(*argv), child) < 0)
                ULOG_ERR("failed to allocate output path: %m\n");
        break;
    case SECCOMP_TRACE:
        if (!violation_count)
            return 0;
        if (asprintf(&json, "/tmp/%s.%u.violations.json", basename(*argv), child) < 0)
            ULOG_ERR("failed to allocate violations output path: %m\n");
        break;
    }
    print_syscalls(policy, json);
    return 0;
}
References uloop_process::cb, debug, json, uloop_process::pid, print_syscalls(), tracee::proc, ptrace_restart, SECCOMP_TRACE, sigterm_handler(), tracer, tracer_cb(), ULOG_ERR, uloop_done(), uloop_init(), uloop_process_add(), uloop_run(), UTRACE, and violation_count.
print_syscalls()
static void print_syscalls (int policy, const char * json) static
Definition at line 116 of file trace.c.
{
    void *c, *d, *e;
    int i;
    char *tmp;
    if (mode == UTRACE) {
        set_syscall("rt_sigaction", 1);
        set_syscall("sigreturn", 1);
        set_syscall("rt_sigreturn", 1);
        set_syscall("exit_group", 1);
        set_syscall("exit", 1);
    }
    struct syscall sorted[SYSCALL_COUNT];
    for (i = 0; i < SYSCALL_COUNT; i++) {
        sorted[i].syscall = syscall_index_to_number(i);
        sorted[i].count = syscall_count[i];
    }
    qsort(sorted, SYSCALL_COUNT, sizeof(sorted[0]), cmp_count);
    blob_buf_init(&b, 0);
    blobmsg_add_string(&b, "defaultAction", "SCMP_ACT_KILL_PROCESS");
    c = blobmsg_open_array(&b, "syscalls");
    d = blobmsg_open_table(&b, "");
    e = blobmsg_open_array(&b, "names");
    for (i = 0; i < SYSCALL_COUNT; i++) {
        int sc = sorted[i].syscall;
        if (!sorted[i].count)
            break;
        if (syscall_name(sc)) {
            if (debug)
                printf("syscall %d (%s) was called %d times\n",
                       sc, syscall_name(sc), sorted[i].count);
            blobmsg_add_string(&b, NULL, syscall_name(sc));
        } else {
            ULOG_ERR("no name found for syscall(%d)\n", sc);
        }
    }
    blobmsg_close_array(&b, e);
    blobmsg_add_string(&b, "action", "SCMP_ACT_ALLOW");
    blobmsg_close_table(&b, d);
    blobmsg_close_array(&b, c);
    if (json) {
        FILE *fp = fopen(json, "w");
        if (fp) {
            tmp = blobmsg_format_json_indent(b.head, true, 0);
            if (!tmp) {
                fclose(fp);
                return;
            }
            fprintf(fp, "%s\n", tmp);
            free(tmp);
            fclose(fp);
            ULOG_INFO("saving syscall trace to %s\n", json);
        } else {
            ULOG_ERR("failed to open %s\n", json);
        }
    } else {
        tmp = blobmsg_format_json_indent(b.head, true, 0);
        if (!tmp)
            return;
        printf("%s\n", tmp);
        free(tmp);
    }
}
References b, blob_buf_init(), blobmsg_add_string(), blobmsg_close_array(), blobmsg_close_table(), blobmsg_format_json_indent(), blobmsg_open_array(), blobmsg_open_table(), cmp_count(), syscall::count, debug, blob_buf::head, json, set_syscall(), syscall::syscall, syscall_count, ULOG_ERR, ULOG_INFO, and UTRACE.
Referenced by main().
report_seccomp_vialation()
static void report_seccomp_vialation (pid_t pid, unsigned syscall) static
Definition at line 188 of file trace.c.
{
    char buf[200];
    snprintf(buf, sizeof(buf), "/proc/%d/cmdline", pid);
    int f = open(buf, O_RDONLY);
    if (f < 0)
        return;
    int r = read(f, buf, sizeof(buf) - 1);
    buf[sizeof(buf) - 1] = '\0';
    if (r >= 0)
        buf[r] = 0;
    else
        strcpy(buf, "unknown?");
    close(f);
    if (violation_count < INT_MAX)
        violation_count++;
    int i = syscall_index(syscall);
    if (i >= 0) {
        syscall_count[i]++;
        ULOG_ERR("%s[%u] tried to call non-whitelisted syscall: %s (see %s)\n",
             buf, pid,  syscall_name(syscall), json);
    } else {
        ULOG_ERR("%s[%u] tried to call non-whitelisted syscall: %d (see %s)\n",
             buf, pid,  syscall, json);
    }
}
References buf, json, r, syscall_count, ULOG_ERR, and violation_count.
Referenced by tracer_cb().
set_syscall()
static void set_syscall (const char * name, int val) static
Definition at line 93 of file trace.c.
{
    int i;
    for (i = 0; i < SYSCALL_COUNT; i++) {
        int sc = syscall_index_to_number(i);
        if (syscall_name(sc) && !strcmp(syscall_name(sc), name)) {
            syscall_count[i] = val;
            return;
        }
    }
}
References syscall_count.
Referenced by print_syscalls().
sigterm_handler()
static void sigterm_handler (int signum) static
Definition at line 299 of file trace.c.
{
    /* When we receive SIGTERM, we forward it to the tracee. After
     * the tracee exits, trace_cb() will be called and make us
     * exit too. */
    kill(tracer.proc.pid, SIGTERM);
}
References uloop_process::pid, tracee::proc, and tracer.
Referenced by main().
tracer_cb()
static void tracer_cb (struct uloop_process * c, int ret) static
Definition at line 218 of file trace.c.
{
    struct tracee *tracee = container_of(c, struct tracee, proc);
    int inject_signal = 0;
    /* We explicitely check for events in upper 16 bits, because
     * musl (as opposed to glibc) does not report
     * PTRACE_EVENT_STOP as WIFSTOPPED */
    if (WIFSTOPPED(ret) || (ret >> 16)) {
        if (WSTOPSIG(ret) & 0x80) {
            if (!tracee->in_syscall) {
#ifdef __aarch64__
                int syscall = -1;
                struct ptrace_syscall_info ptsi = {.op=PTRACE_SYSCALL_INFO_ENTRY};
                if (ptrace(PTRACE_GET_SYSCALL_INFO, c->pid, sizeof(ptsi), &ptsi) != -1)
                    syscall = ptsi.entry.nr;
#else
                int syscall = ptrace(PTRACE_PEEKUSER, c->pid, reg_syscall_nr);
#endif
                int i = syscall_index(syscall);
                if (i >= 0) {
                    syscall_count[i]++;
                    if (debug)
                        fprintf(stderr, "%s()\n", syscall_name(syscall));
                } else if (debug) {
                    fprintf(stderr, "syscal(%d)\n", syscall);
                }
            }
            tracee->in_syscall = !tracee->in_syscall;
        } else if ((ret >> 8) == (SIGTRAP | (PTRACE_EVENT_FORK << 8)) ||
               (ret >> 8) == (SIGTRAP | (PTRACE_EVENT_VFORK << 8)) ||
               (ret >> 8) == (SIGTRAP | (PTRACE_EVENT_CLONE << 8))) {
            struct tracee *child = calloc(1, sizeof(struct tracee));
            unsigned long msg;
            ptrace(PTRACE_GETEVENTMSG, c->pid, 0, &msg);
            child->proc.pid = msg;
            child->proc.cb = tracer_cb;
            ptrace(ptrace_restart, child->proc.pid, 0, 0);
            uloop_process_add(&child->proc);
            if (debug)
                fprintf(stderr, "Tracing new child %d\n", child->proc.pid);
        } else if ((ret >> 16) == PTRACE_EVENT_STOP) {
            /* Nothing special to do here */
        } else if ((ret >> 8) == (SIGTRAP | (PTRACE_EVENT_SECCOMP << 8))) {
#ifdef __aarch64__
            int syscall = -1;
            struct ptrace_syscall_info ptsi = {.op=PTRACE_SYSCALL_INFO_SECCOMP};
            if (ptrace(PTRACE_GET_SYSCALL_INFO, c->pid, sizeof(ptsi), &ptsi) != -1)
                syscall = ptsi.entry.nr;
#else
            int syscall = ptrace(PTRACE_PEEKUSER, c->pid, reg_syscall_nr);
#if defined(__arm__)
            ptrace(PTRACE_SET_SYSCALL, c->pid, 0, -1);
            ptrace(PTRACE_POKEUSER, c->pid, reg_retval_nr, -ENOSYS);
#else
            ptrace(PTRACE_POKEUSER, c->pid, reg_syscall_nr, -1);
#endif
#endif
            report_seccomp_vialation(c->pid, syscall);
        } else {
            inject_signal = WSTOPSIG(ret);
            if (debug)
                fprintf(stderr, "Injecting signal %d into pid %d\n",
                    inject_signal, tracee->proc.pid);
        }
    } else if (WIFEXITED(ret) || (WIFSIGNALED(ret) && WTERMSIG(ret))) {
        if (tracee == &tracer) {
            uloop_end(); /* Main process exit */
        } else {
            if (debug)
                fprintf(stderr, "Child %d exited\n", tracee->proc.pid);
            free(tracee);
        }
        return;
    }
    ptrace(ptrace_restart, c->pid, 0, inject_signal);
    uloop_process_add(c);
}
References uloop_process::cb, container_of, debug, tracee::in_syscall, uloop_process::pid, tracee::proc, PTRACE_EVENT_SECCOMP, PTRACE_EVENT_STOP, ptrace_restart, report_seccomp_vialation(), syscall_count, tracer, tracer_cb(), uloop_end(), and uloop_process_add().
Referenced by main(), and tracer_cb().
Variable Documentation
b
struct blob_buf b static
Definition at line 88 of file trace.c.
Referenced by cmp_count(), and print_syscalls().
debug
int debug static
Definition at line 89 of file trace.c.
Referenced by main(), print_syscalls(), and tracer_cb().
json
char* json = NULL
Definition at line 90 of file trace.c.
Referenced by cert_dump_blob(), main(), main(), print_syscalls(), and report_seccomp_vialation().
mode
enum mode mode = UTRACE
ptrace_restart
int ptrace_restart
Definition at line 91 of file trace.c.
Referenced by main(), and tracer_cb().
syscall_count
int syscall_count[SYSCALL_COUNT] static
Definition at line 86 of file trace.c.
Referenced by print_syscalls(), report_seccomp_vialation(), set_syscall(), and tracer_cb().
tracer
struct tracee tracer static
Definition at line 85 of file trace.c.
Referenced by main(), sigterm_handler(), and tracer_cb().
violation_count
int violation_count static
Definition at line 87 of file trace.c.
Referenced by main(), and report_seccomp_vialation().