zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/ubus/examples/server.c File Reference
server.c File Reference
#include <unistd.h>
#include <signal.h>
#include <libubox/blobmsg_json.h>
#include "libubus.h"
#include "count.h"
Classes
struct hello_request
Enumerations
enum { HELLO_ID , HELLO_MSG , __HELLO_MAX }
enum { WATCH_ID , WATCH_COUNTER , __WATCH_MAX }
enum { COUNT_TO , COUNT_STRING , __COUNT_MAX }
Functions
static void test_hello_fd_reply (struct uloop_timeout *t)
static void test_hello_reply (struct uloop_timeout *t)
static int test_hello (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static void test_handle_remove (struct ubus_context *ctx, struct ubus_subscriber *s, uint32_t id)
static int test_notify (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int test_watch (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int test_count (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static void server_main (void)
int main (int argc, char **argv)
Variables
static struct ubus_context * ctx
static struct ubus_subscriber test_event
static struct blob_buf b
static const struct blobmsg_policy hello_policy []
static const struct blobmsg_policy watch_policy [__WATCH_MAX]
static const struct blobmsg_policy count_policy [__COUNT_MAX]
static const struct ubus_method test_methods []
static struct ubus_object_type test_object_type
static struct ubus_object test_object
Class Documentation
hello_request
struct hello_request
Definition at line 36 of file server.c.
Class Members
char data[]
int fd
int idx
struct ubus_request_data req
struct uloop_timeout timeout
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
HELLO_ID
HELLO_MSG
__HELLO_MAX
Definition at line 25 of file server.c.
     {
    HELLO_ID,
    HELLO_MSG,
    __HELLO_MAX
};
anonymous enum
anonymous enum
Enumerator
WATCH_ID
WATCH_COUNTER
__WATCH_MAX
Definition at line 108 of file server.c.
     {
    WATCH_ID,
    WATCH_COUNTER,
    __WATCH_MAX
};
anonymous enum
anonymous enum
Enumerator
COUNT_TO
COUNT_STRING
__COUNT_MAX
Definition at line 160 of file server.c.
     {
    COUNT_TO,
    COUNT_STRING,
    __COUNT_MAX
};
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 229 of file server.c.
{
    const char *ubus_socket = NULL;
    int ch;
    while ((ch = getopt(argc, argv, "cs:")) != -1) {
        switch (ch) {
        case 's':
            ubus_socket = optarg;
            break;
        default:
            break;
        }
    }
    uloop_init();
    signal(SIGPIPE, SIG_IGN);
    ctx = ubus_connect(ubus_socket);
    if (!ctx) {
        fprintf(stderr, "Failed to connect to ubus\n");
        return -1;
    }
    ubus_add_uloop(ctx);
    server_main();
    ubus_free(ctx);
    uloop_done();
    return 0;
}
References ctx, server_main(), ubus_add_uloop(), ubus_connect(), ubus_free(), ubus_socket, uloop_done(), and uloop_init().
server_main()
static void server_main (void) static
Definition at line 214 of file server.c.
{
    int ret;
    ret = ubus_add_object(ctx, &test_object);
    if (ret)
        fprintf(stderr, "Failed to add object: %s\n", ubus_strerror(ret));
    ret = ubus_register_subscriber(ctx, &test_event);
    if (ret)
        fprintf(stderr, "Failed to add watch handler: %s\n", ubus_strerror(ret));
    uloop_run();
}
References ctx, test_event, test_object, ubus_add_object(), ubus_register_subscriber(), ubus_strerror(), and uloop_run().
Referenced by main().
test_count()
static int test_count (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 171 of file server.c.
{
    struct blob_attr *tb[__COUNT_MAX];
    char *s1, *s2;
    uint32_t num;
    blobmsg_parse(count_policy, __COUNT_MAX, tb, blob_data(msg), blob_len(msg));
    if (!tb[COUNT_TO] || !tb[COUNT_STRING])
        return UBUS_STATUS_INVALID_ARGUMENT;
    num = blobmsg_get_u32(tb[COUNT_TO]);
    s1 = blobmsg_get_string(tb[COUNT_STRING]);
    s2 = count_to_number(num);
    if (!s1 || !s2) {
        free(s2);
        return UBUS_STATUS_UNKNOWN_ERROR;
    }
    blob_buf_init(&b, 0);
    blobmsg_add_u32(&b, "rc", strcmp(s1, s2));
    ubus_send_reply(ctx, req, b.head);
    free(s2);
    return 0;
}
References __COUNT_MAX, b, blob_buf_init(), blob_data(), blob_len(), blobmsg_add_u32(), blobmsg_get_string(), blobmsg_get_u32(), blobmsg_parse(), count_policy, COUNT_STRING, COUNT_TO, count_to_number(), ctx, blob_buf::head, ubus_send_reply(), UBUS_STATUS_INVALID_ARGUMENT, and UBUS_STATUS_UNKNOWN_ERROR.
test_handle_remove()
static void test_handle_remove (struct ubus_context * ctx, struct ubus_subscriber * s, uint32_t id) static
Definition at line 120 of file server.c.
{
    fprintf(stderr, "Object %08x went away\n", id);
}
Referenced by test_watch().
test_hello()
static int test_hello (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 81 of file server.c.
{
    struct hello_request *hreq;
    struct blob_attr *tb[__HELLO_MAX];
    const char format[] = "%s received a message: %s";
    const char *msgstr = "(unknown)";
    blobmsg_parse(hello_policy, ARRAY_SIZE(hello_policy), tb, blob_data(msg), blob_len(msg));
    if (tb[HELLO_MSG])
        msgstr = blobmsg_data(tb[HELLO_MSG]);
    size_t len = sizeof(*hreq) + sizeof(format) + strlen(obj->name) + strlen(msgstr) + 1;
    hreq = calloc(1, len);
    if (!hreq)
        return UBUS_STATUS_UNKNOWN_ERROR;
    snprintf(hreq->data, len, format, obj->name, msgstr);
    ubus_defer_request(ctx, req, &hreq->req);
    hreq->timeout.cb = test_hello_reply;
    uloop_timeout_set(&hreq->timeout, 1000);
    return 0;
}
References __HELLO_MAX, ARRAY_SIZE, blob_data(), blob_len(), blobmsg_data(), blobmsg_parse(), uloop_timeout::cb, ctx, hello_request::data, HELLO_MSG, hello_policy, ubus_object::name, hello_request::req, test_hello_reply(), hello_request::timeout, ubus_defer_request(), UBUS_STATUS_UNKNOWN_ERROR, and uloop_timeout_set().
test_hello_fd_reply()
static void test_hello_fd_reply (struct uloop_timeout * t) static
Definition at line 44 of file server.c.
{
    struct hello_request *req = container_of(t, struct hello_request, timeout);
    char *data;
    data = alloca(strlen(req->data) + 32);
    sprintf(data, "msg%d: %s\n", ++req->idx, req->data);
    if (write(req->fd, data, strlen(data)) < 0) {
        close(req->fd);
        free(req);
        return;
    }
    uloop_timeout_set(&req->timeout, 1000);
}
References container_of, hello_request::data, ubus_request_data::fd, hello_request::req, timeout, and uloop_timeout_set().
Referenced by test_hello_reply().
test_hello_reply()
static void test_hello_reply (struct uloop_timeout * t) static
Definition at line 60 of file server.c.
{
    struct hello_request *req = container_of(t, struct hello_request, timeout);
    int fds[2];
    blob_buf_init(&b, 0);
    blobmsg_add_string(&b, "message", req->data);
    ubus_send_reply(ctx, &req->req, b.head);
    if (pipe(fds) == -1) {
        fprintf(stderr, "Failed to create pipe\n");
        return;
    }
    ubus_request_set_fd(ctx, &req->req, fds[0]);
    ubus_complete_deferred_request(ctx, &req->req, 0);
    req->fd = fds[1];
    req->timeout.cb = test_hello_fd_reply;
    test_hello_fd_reply(t);
}
References b, blob_buf_init(), blobmsg_add_string(), container_of, ctx, ubus_request_data::fd, blob_buf::head, hello_request::req, test_hello_fd_reply(), timeout, ubus_complete_deferred_request(), ubus_request_set_fd(), and ubus_send_reply().
Referenced by test_hello().
test_notify()
static int test_notify (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 127 of file server.c.
{
#if 0
    char *str;
    str = blobmsg_format_json(msg, true);
    fprintf(stderr, "Received notification '%s': %s\n", method, str);
    free(str);
#endif
    return 0;
}
References blobmsg_format_json().
Referenced by test_watch().
test_watch()
static int test_watch (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 142 of file server.c.
{
    struct blob_attr *tb[__WATCH_MAX];
    int ret;
    blobmsg_parse(watch_policy, __WATCH_MAX, tb, blob_data(msg), blob_len(msg));
    if (!tb[WATCH_ID])
        return UBUS_STATUS_INVALID_ARGUMENT;
    test_event.remove_cb = test_handle_remove;
    test_event.cb = test_notify;
    ret = ubus_subscribe(ctx, &test_event, blobmsg_get_u32(tb[WATCH_ID]));
    fprintf(stderr, "Watching object %08x: %s\n", blobmsg_get_u32(tb[WATCH_ID]), ubus_strerror(ret));
    return ret;
}
References __WATCH_MAX, blob_data(), blob_len(), blobmsg_get_u32(), blobmsg_parse(), ubus_subscriber::cb, ctx, ubus_subscriber::remove_cb, test_event, test_handle_remove(), test_notify(), UBUS_STATUS_INVALID_ARGUMENT, ubus_strerror(), ubus_subscribe(), WATCH_ID, and watch_policy.
Variable Documentation
b
struct blob_buf b static
Definition at line 23 of file server.c.
Referenced by test_count(), and test_hello_reply().
count_policy
const struct blobmsg_policy count_policy[__COUNT_MAX] static
Initial value:
= {
    [COUNT_TO] = { .name = "to", .type = BLOBMSG_TYPE_INT32 },
    [COUNT_STRING] = { .name = "string", .type = BLOBMSG_TYPE_STRING },
}
Definition at line 166 of file server.c.
{
    [COUNT_TO] = { .name = "to", .type = BLOBMSG_TYPE_INT32 },
    [COUNT_STRING] = { .name = "string", .type = BLOBMSG_TYPE_STRING },
};
Referenced by test_count().
ctx
struct ubus_context* ctx static
Definition at line 21 of file server.c.
Referenced by main(), server_main(), test_count(), test_hello(), test_hello_reply(), and test_watch().
hello_policy
const struct blobmsg_policy hello_policy[] static
Initial value:
= {
    [HELLO_ID] = { .name = "id", .type = BLOBMSG_TYPE_INT32 },
    [HELLO_MSG] = { .name = "msg", .type = BLOBMSG_TYPE_STRING },
}
Definition at line 31 of file server.c.
{
    [HELLO_ID] = { .name = "id", .type = BLOBMSG_TYPE_INT32 },
    [HELLO_MSG] = { .name = "msg", .type = BLOBMSG_TYPE_STRING },
};
Referenced by test_hello().
test_event
struct ubus_subscriber test_event static
Definition at line 22 of file server.c.
Referenced by server_main(), and test_watch().
test_methods
const struct ubus_method test_methods[] static
Initial value:
= {
    UBUS_METHOD("hello", test_hello, hello_policy),
    UBUS_METHOD("watch", test_watch, watch_policy),
    UBUS_METHOD("count", test_count, count_policy),
}
Definition at line 198 of file server.c.
{
    UBUS_METHOD("hello", test_hello, hello_policy),
    UBUS_METHOD("watch", test_watch, watch_policy),
    UBUS_METHOD("count", test_count, count_policy),
};
test_object
struct ubus_object test_object static
Initial value:
= {
    .name = "test",
    .type = &test_object_type,
    .methods = test_methods,
    .n_methods = ARRAY_SIZE(test_methods),
}
Definition at line 207 of file server.c.
{
    .name = "test",
    .type = &test_object_type,
    .methods = test_methods,
    .n_methods = ARRAY_SIZE(test_methods),
};
Referenced by server_main().
test_object_type
struct ubus_object_type test_object_type static
Initial value:
=
    UBUS_OBJECT_TYPE("test", test_methods)
Definition at line 204 of file server.c.
watch_policy
const struct blobmsg_policy watch_policy[__WATCH_MAX] static
Initial value:
= {
    [WATCH_ID] = { .name = "id", .type = BLOBMSG_TYPE_INT32 },
    [WATCH_COUNTER] = { .name = "counter", .type = BLOBMSG_TYPE_INT32 },
}
Definition at line 114 of file server.c.
{
    [WATCH_ID] = { .name = "id", .type = BLOBMSG_TYPE_INT32 },
    [WATCH_COUNTER] = { .name = "counter", .type = BLOBMSG_TYPE_INT32 },
};
Referenced by test_watch().