zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/libubox/examples/ustream-example.c File Reference
ustream-example.c File Reference
#include <sys/socket.h>
#include <netinet/in.h>
#include <stdio.h>
#include <getopt.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "ustream.h"
#include "uloop.h"
#include "usock.h"
Classes
struct client
Functions
static void client_read_cb (struct ustream *s, int bytes)
static void client_close (struct ustream *s)
static void client_notify_write (struct ustream *s, int bytes)
static void client_notify_state (struct ustream *s)
static void server_cb (struct uloop_fd *fd, unsigned int events)
static int run_server (void)
static int usage (const char *name)
int main (int argc, char **argv)
Variables
static struct uloop_fd server
static const char * port = "10000"
struct client * next_client = NULL
Class Documentation
client
struct client
Definition at line 18 of file ustream-example.c.
Class Members
int ctr
struct ustream_fd s
struct sockaddr_in sin
Function Documentation
client_close()
static void client_close (struct ustream * s) static
Definition at line 52 of file ustream-example.c.
{
    struct client *cl = container_of(s, struct client, s.stream);
    fprintf(stderr, "Connection closed\n");
    ustream_free(s);
    close(cl->s.fd.fd);
    free(cl);
}
References container_of, uloop_fd::fd, ustream_fd::fd, client::s, ustream_fd::stream, and ustream_free().
Referenced by client_notify_state().
client_notify_state()
static void client_notify_state (struct ustream * s) static
Definition at line 72 of file ustream-example.c.
{
    struct client *cl = container_of(s, struct client, s.stream);
    if (!s->eof)
        return;
    fprintf(stderr, "eof!, pending: %d, total: %d\n", s->w.data_bytes, cl->ctr);
    if (!s->w.data_bytes)
        return client_close(s);
}
References client_close(), container_of, client::ctr, client::s, and ustream_fd::stream.
Referenced by server_cb().
client_notify_write()
static void client_notify_write (struct ustream * s, int bytes) static
Definition at line 62 of file ustream-example.c.
{
    fprintf(stderr, "Wrote %d bytes, pending: %d\n", bytes, s->w.data_bytes);
    if (s->w.data_bytes < 128 && ustream_read_blocked(s)) {
        fprintf(stderr, "Unblock read\n");
        ustream_set_read_blocked(s, false);
    }
}
References client::s, ustream_read_blocked(), and ustream_set_read_blocked().
Referenced by server_cb().
client_read_cb()
static void client_read_cb (struct ustream * s, int bytes) static
Definition at line 25 of file ustream-example.c.
{
    struct client *cl = container_of(s, struct client, s.stream);
    struct ustream_buf *buf = s->r.head;
    char *newline, *str;
    do {
        str = ustream_get_read_buf(s, NULL);
        if (!str)
            break;
        newline = strchr(buf->data, '\n');
        if (!newline)
            break;
        *newline = 0;
        ustream_printf(s, "%s\n", str);
        ustream_consume(s, newline + 1 - str);
        cl->ctr += newline + 1 - str;
    } while(1);
    if (s->w.data_bytes > 256 && !ustream_read_blocked(s)) {
        fprintf(stderr, "Block read, bytes: %d\n", s->w.data_bytes);
        ustream_set_read_blocked(s, true);
    }
}
References buf, container_of, client::ctr, ustream_buf_list::data_bytes, client::s, ustream_fd::stream, ustream_consume(), ustream_get_read_buf(), ustream_printf(), ustream_read_blocked(), ustream_set_read_blocked(), and ustream::w.
Referenced by server_cb().
main()
int main (int argc, char ** argv)
Definition at line 133 of file ustream-example.c.
{
    int ch;
    while ((ch = getopt(argc, argv, "p:")) != -1) {
        switch(ch) {
        case 'p':
            port = optarg;
            break;
        default:
            return usage(argv[0]);
        }
    }
    return run_server();
}
References port, run_server(), and usage().
run_server()
static int run_server (void) static
Definition at line 110 of file ustream-example.c.
{
    server.cb = server_cb;
    server.fd = usock(USOCK_TCP | USOCK_SERVER | USOCK_IPV4ONLY | USOCK_NUMERIC, "127.0.0.1", port);
    if (server.fd < 0) {
        perror("usock");
        return 1;
    }
    uloop_init();
    uloop_fd_add(&server, ULOOP_READ);
    uloop_run();
    return 0;
}
References uloop_fd::cb, uloop_fd::fd, port, server, server_cb(), uloop_fd_add(), uloop_init(), ULOOP_READ, uloop_run(), usock(), USOCK_IPV4ONLY, USOCK_NUMERIC, USOCK_SERVER, and USOCK_TCP.
Referenced by main().
server_cb()
static void server_cb (struct uloop_fd * fd, unsigned int events) static
Definition at line 85 of file ustream-example.c.
{
    struct client *cl;
    unsigned int sl = sizeof(struct sockaddr_in);
    int sfd;
    if (!next_client)
        next_client = calloc(1, sizeof(*next_client));
    cl = next_client;
    sfd = accept(server.fd, (struct sockaddr *) &cl->sin, &sl);
    if (sfd < 0) {
        fprintf(stderr, "Accept failed\n");
        return;
    }
    cl->s.stream.string_data = true;
    cl->s.stream.notify_read = client_read_cb;
    cl->s.stream.notify_state = client_notify_state;
    cl->s.stream.notify_write = client_notify_write;
    ustream_fd_init(&cl->s, sfd);
    next_client = NULL;
    fprintf(stderr, "New connection\n");
}
References client_notify_state(), client_notify_write(), client_read_cb(), uloop_fd::fd, next_client, ustream::notify_read, ustream::notify_state, ustream::notify_write, client::s, server, client::sin, ustream_fd::stream, ustream::string_data, and ustream_fd_init().
Referenced by run_server().
usage()
static int usage (const char * name) static
Definition at line 127 of file ustream-example.c.
{
    fprintf(stderr, "Usage: %s -p <port>\n", name);
    return 1;
}
Variable Documentation
next_client
struct client* next_client = NULL
Definition at line 16 of file ustream-example.c.
Referenced by server_cb().
port
const char* port = "10000" static
Definition at line 15 of file ustream-example.c.
Referenced by __bridge_set_member_vlan(), bonding_hotplug_add(), bonding_hotplug_del(), bridge_create(), bridge_dump_port(), bridge_dump_vlan(), bridge_find_vlan_member_port(), bridge_free_member(), bridge_hotplug_get_vlan_port(), bridge_hotplug_set_member_vlans(), bridge_member_vlan_is_pvid(), bridge_recalc_member_pvid(), bridge_set_member_vlan(), bridge_set_vlan_state(), bridge_vlan_check_attr(), bridge_vlan_check_port(), bridge_vlan_free(), config_parse_vlan(), main(), run_server(), set_TopologyChange(), system_add_vxlan(), system_bonding_set_port(), system_bridge_vlan_check(), and usock_port().
server
struct uloop_fd server static
Definition at line 14 of file ustream-example.c.
Referenced by run_server(), server_cb(), usock_connect(), usock_inet_notimeout(), usock_inet_timeout(), and usock_unix().