zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/netifd/utils.h File Reference
utils.h File Reference
#include <unistd.h>
#include <stdio.h>
#include <uci_blob.h>
#include <libubox/list.h>
#include <libubox/avl.h>
#include <libubox/avl-cmp.h>
#include <libubox/blobmsg.h>
#include <libubox/vlist.h>
#include <libubox/utils.h>
Classes
struct vlist_simple_tree
struct vlist_simple_node
Macros
#define __init __attribute__((constructor))
#define vlist_for_each_element_safe(tree, element, node_member, ptr)
#define vlist_simple_init(tree, node, member)
#define vlist_simple_for_each_element(tree, element, node_member)
#define vlist_simple_empty(tree)
Functions
static bool blobmsg_get_bool_default (struct blob_attr *attr, bool val)
void __vlist_simple_init (struct vlist_simple_tree *tree, int offset)
void vlist_simple_delete (struct vlist_simple_tree *tree, struct vlist_simple_node *node)
void vlist_simple_flush (struct vlist_simple_tree *tree)
void vlist_simple_flush_all (struct vlist_simple_tree *tree)
void vlist_simple_replace (struct vlist_simple_tree *dest, struct vlist_simple_tree *old)
static void vlist_simple_update (struct vlist_simple_tree *tree)
static void vlist_simple_add (struct vlist_simple_tree *tree, struct vlist_simple_node *node)
unsigned int parse_netmask_string (const char *str, bool v6)
bool split_netmask (char *str, unsigned int *netmask, bool v6)
int parse_ip_and_netmask (int af, const char *str, void *addr, unsigned int *netmask)
bool check_pid_path (int pid, const char *exe)
char * format_macaddr (uint8_t *mac)
uint32_t crc32_file (FILE *fp)
const char * uci_get_validate_string (const struct uci_blob_param_list *p, int i)
Class Documentation
vlist_simple_tree
struct vlist_simple_tree
Definition at line 37 of file utils.h.
Class Members
int head_offset
struct list_head list
int version
vlist_simple_node
struct vlist_simple_node
Definition at line 43 of file utils.h.
Class Members
struct list_head list
int version
Macro Definition Documentation
__init
#define __init __attribute__((constructor))
Definition at line 35 of file utils.h.
vlist_for_each_element_safe
#define vlist_for_each_element_safe (tree, element, node_member, ptr)
Value:
        avl_for_each_element_safe(&(tree)->avl, element, node_member.avl, ptr)
Definition at line 48 of file utils.h.
#define vlist_for_each_element_safe(tree, element, node_member, ptr) \
        avl_for_each_element_safe(&(tree)->avl, element, node_member.avl, ptr)
vlist_simple_empty
#define vlist_simple_empty (tree)
Value:
    list_empty(&(tree)->list)
Definition at line 74 of file utils.h.
#define vlist_simple_empty(tree) \
    list_empty(&(tree)->list)
Referenced by __interface_write_dns_entries().
vlist_simple_for_each_element
#define vlist_simple_for_each_element (tree, element, node_member)
Value:
    list_for_each_entry(element, &(tree)->list, node_member.list)
Definition at line 71 of file utils.h.
#define vlist_simple_for_each_element(tree, element, node_member) \
    list_for_each_entry(element, &(tree)->list, node_member.list)
Referenced by interface_ip_dump_dns_search_list(), interface_ip_dump_dns_server_list(), system_vlandev_add(), vlandev_qos_mapping_dump(), and write_resolv_conf_entries().
vlist_simple_init
#define vlist_simple_init (tree, node, member)
Value:
    __vlist_simple_init(tree, offsetof(node, member))
Definition at line 51 of file utils.h.
#define vlist_simple_init(tree, node, member) \
    __vlist_simple_init(tree, offsetof(node, member))
Referenced by __interface_ip_init(), and vlandev_create().
Function Documentation
__vlist_simple_init()
void __vlist_simple_init (struct vlist_simple_tree * tree, int offset)
Definition at line 28 of file utils.c.
{
    INIT_LIST_HEAD(&tree->list);
    tree->version = 1;
    tree->head_offset = offset;
}
References vlist_simple_tree::head_offset, INIT_LIST_HEAD(), vlist_simple_tree::list, and vlist_simple_tree::version.
blobmsg_get_bool_default()
static bool blobmsg_get_bool_default (struct blob_attr * attr, bool val) inline static
Definition at line 27 of file utils.h.
{
    if (!attr)
        return val;
    return blobmsg_get_bool(attr);
}
References blobmsg_get_bool().
Referenced by interface_alloc(), and proto_apply_static_ip_settings().
check_pid_path()
bool check_pid_path (int pid, const char * exe)
Definition at line 178 of file utils.c.
{
    const char deleted[] = " (deleted)";
    const int deleted_len = strlen(deleted);
    int proc_exe_len;
    int exe_len = strlen(exe);
#ifdef __APPLE__
    char proc_exe_buf[PROC_PIDPATHINFO_SIZE];
    proc_exe_len = proc_pidpath(pid, proc_exe_buf, sizeof(proc_exe_buf));
#else
    char proc_exe[32];
    char *proc_exe_buf = alloca(exe_len);
    sprintf(proc_exe, "/proc/%d/exe", pid);
    proc_exe_len = readlink(proc_exe, proc_exe_buf, exe_len);
#endif
    if (proc_exe_len == exe_len)
        return !memcmp(exe, proc_exe_buf, exe_len);
    else if (proc_exe_len == exe_len + deleted_len)
        return !memcmp(exe, proc_exe_buf, exe_len) &&
            !memcmp(exe + exe_len, deleted, deleted_len);
    else
        return false;
}
Referenced by wireless_process_check().
crc32_file()
uint32_t crc32_file (FILE * fp)
Definition at line 151 of file utils.c.
{
    static uint32_t *crcvals = NULL;
    if (!crcvals) {
        crcvals = malloc(sizeof(*crcvals) * 256);
        for (size_t i = 0; i < 256; ++i) {
            uint32_t c = i;
            for (size_t j = 0; j < 8; ++j)
                c = (c & 1) ? (0xEDB88320 ^ (c >> 1)) : (c >> 1);
            crcvals[i] = c;
        }
    }
    uint8_t buf[1024];
    size_t len;
    uint32_t c = 0xFFFFFFFF;
    do {
        len = fread(buf, 1, sizeof(buf), fp);
        for (size_t i = 0; i < len; ++i)
            c = crcvals[(c ^ buf[i]) & 0xFF] ^ (c >> 8);
    } while (len == sizeof(buf));
    return c ^ 0xFFFFFFFF;
}
References buf.
Referenced by interface_write_resolv_conf().
format_macaddr()
char * format_macaddr (uint8_t * mac)
Definition at line 140 of file utils.c.
{
    static char str[sizeof("ff:ff:ff:ff:ff:ff ")];
    snprintf(str, sizeof(str), "%02x:%02x:%02x:%02x:%02x:%02x",
         mac[0], mac[1], mac[2], mac[3], mac[4], mac[5]);
    return str;
}
Referenced by device_dump_status(), interface_ip_dump_neighbor_list(), system_if_apply_settings(), and system_neighbor_msg().
parse_ip_and_netmask()
int parse_ip_and_netmask (int af, const char * str, void * addr, unsigned int * netmask)
Definition at line 120 of file utils.c.
{
    char *astr = alloca(strlen(str) + 1);
    strcpy(astr, str);
    if (!split_netmask(astr, netmask, af == AF_INET6))
        return 0;
    if (af == AF_INET6) {
        if (*netmask > 128)
            return 0;
    } else {
        if (*netmask > 32)
            return 0;
    }
    return inet_pton(af, astr, addr);
}
References split_netmask().
Referenced by interface_ip_add_route(), iprule_add(), parse_addr(), system_add_ip6_tunnel(), and system_add_sit_tunnel().
parse_netmask_string()
unsigned int parse_netmask_string (const char * str, bool v6)
Definition at line 80 of file utils.c.
{
    struct in_addr addr;
    unsigned int ret;
    char *err = NULL;
    if (!strchr(str, '.')) {
        ret = strtoul(str, &err, 0);
        if (err && *err)
            goto error;
        return ret;
    }
    if (v6)
        goto error;
    if (inet_aton(str, &addr) != 1)
        goto error;
    return 32 - fls(~(ntohl(addr.s_addr)));
error:
    return ~0;
}
Referenced by split_netmask().
split_netmask()
bool split_netmask (char * str, unsigned int * netmask, bool v6)
Definition at line 107 of file utils.c.
{
    char *delim = strchr(str, '/');
    if (delim) {
        *(delim++) = 0;
        *netmask = parse_netmask_string(delim, v6);
    }
    return true;
}
References parse_netmask_string().
Referenced by parse_ip_and_netmask().
uci_get_validate_string()
const char * uci_get_validate_string (const struct uci_blob_param_list * p, int i)
Definition at line 214 of file utils.c.
{
    if (p->validate[i])
        return p->validate[i];
    else if (uci_validate_name[p->params[i].type])
        return uci_validate_name[p->params[i].type];
    return p->validate[BLOBMSG_TYPE_STRING];
}
References BLOBMSG_TYPE_STRING, and uci_validate_name.
Referenced by proto_dump_handlers(), and wireless_device_get_validate().
vlist_simple_add()
static void vlist_simple_add (struct vlist_simple_tree * tree, struct vlist_simple_node * node) inline static
Definition at line 65 of file utils.h.
{
    node->version = tree->version;
    list_add_tail(&node->list, &tree->list);
}
References vlist_simple_tree::list, list_add_tail(), and vlist_simple_tree::version.
Referenced by interface_add_dns_search_domain(), interface_add_dns_server(), vlandev_qos_mapping_list_apply(), and vlist_simple_replace().
vlist_simple_delete()
void vlist_simple_delete (struct vlist_simple_tree * tree, struct vlist_simple_node * node)
Definition at line 36 of file utils.c.
{
    char *ptr;
    list_del(&node->list);
    ptr = (char *) node - tree->head_offset;
    free(ptr);
}
References vlist_simple_tree::head_offset, and list_del().
Referenced by vlist_simple_flush().
vlist_simple_flush()
void vlist_simple_flush (struct vlist_simple_tree * tree)
Definition at line 46 of file utils.c.
{
    struct vlist_simple_node *n, *tmp;
    list_for_each_entry_safe(n, tmp, &tree->list, list) {
        if ((n->version == tree->version || n->version == -1) &&
            tree->version != -1)
            continue;
        vlist_simple_delete(tree, n);
    }
}
References vlist_simple_node::list, vlist_simple_tree::list, list_for_each_entry_safe, vlist_simple_node::version, vlist_simple_tree::version, and vlist_simple_delete().
Referenced by interface_ip_update_complete(), vlandev_apply_settings(), vlist_simple_flush_all(), and vlist_simple_replace().
vlist_simple_flush_all()
void vlist_simple_flush_all (struct vlist_simple_tree * tree)
Definition at line 73 of file utils.c.
{
    tree->version = -1;
    vlist_simple_flush(tree);
}
References vlist_simple_tree::version, and vlist_simple_flush().
Referenced by interface_ip_flush(), and vlandev_free().
vlist_simple_replace()
void vlist_simple_replace (struct vlist_simple_tree * dest, struct vlist_simple_tree * old)
Definition at line 60 of file utils.c.
{
    struct vlist_simple_node *n, *tmp;
    vlist_simple_update(dest);
    list_for_each_entry_safe(n, tmp, &old->list, list) {
        list_del(&n->list);
        vlist_simple_add(dest, n);
    }
    vlist_simple_flush(dest);
}
References vlist_simple_node::list, vlist_simple_tree::list, list_del(), list_for_each_entry_safe, vlist_simple_add(), vlist_simple_flush(), and vlist_simple_update().
Referenced by interface_replace_dns().
vlist_simple_update()
static void vlist_simple_update (struct vlist_simple_tree * tree) inline static
Definition at line 60 of file utils.h.
{
    tree->version++;
}
References vlist_simple_tree::version.
Referenced by interface_ip_update_start(), vlandev_apply_settings(), and vlist_simple_replace().