zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/libubox/tests/test-blobmsg.c File Reference
test-blobmsg.c File Reference
#include <stdio.h>
#include <float.h>
#include <limits.h>
#include <stdint.h>
#include <inttypes.h>
#include "blobmsg.h"
#include "blobmsg_json.h"
Macros
#define indent_printf(indent, ...)
#define ARRAY_SIZE(x)
Enumerations
enum { FOO_MESSAGE , FOO_LIST , FOO_TESTDATA }
Functions
static void dump_attr_data (struct blob_attr *data, int indent, int next_indent)
static void dump_table (struct blob_attr *head, size_t len, int indent, bool array)
static void dump_message (struct blob_buf *buf)
static void fill_message (struct blob_buf *buf)
int main (int argc, char **argv)
Variables
static const char * indent_str = "\t\t\t\t\t\t\t\t\t\t\t\t\t"
static const struct blobmsg_policy pol []
Macro Definition Documentation
ARRAY_SIZE
#define ARRAY_SIZE (x)
Value:
(sizeof(x) / sizeof((x)[0]))
Definition at line 90 of file test-blobmsg.c.
Referenced by dump_message().
indent_printf
#define indent_printf (indent, ...)
Value:
    do { \
    if (indent > 0) \
        fwrite(indent_str, indent, 1, stderr); \
    fprintf(stderr, __VA_ARGS__); \
} while(0)
Definition at line 12 of file test-blobmsg.c.
#define indent_printf(indent, ...) do { \
    if (indent > 0) \
        fwrite(indent_str, indent, 1, stderr); \
    fprintf(stderr, __VA_ARGS__); \
} while(0)
Referenced by dump_attr_data(), and dump_table().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
FOO_MESSAGE
FOO_LIST
FOO_TESTDATA
Definition at line 68 of file test-blobmsg.c.
     {
    FOO_MESSAGE,
    FOO_LIST,
    FOO_TESTDATA
};
Function Documentation
dump_attr_data()
static void dump_attr_data (struct blob_attr * data, int indent, int next_indent) static
Definition at line 36 of file test-blobmsg.c.
{
    int type = blobmsg_type(data);
    switch(type) {
    case BLOBMSG_TYPE_STRING:
        indent_printf(indent, "%s (str)\n", blobmsg_get_string(data));
        break;
    case BLOBMSG_TYPE_INT8:
        indent_printf(indent, "%d (i8)\n", (int8_t) blobmsg_get_u8(data));
        break;
    case BLOBMSG_TYPE_INT16:
        indent_printf(indent, "%d (i16)\n", (int16_t) blobmsg_get_u16(data));
        break;
    case BLOBMSG_TYPE_INT32:
        indent_printf(indent, "%d (i32)\n", (int32_t) blobmsg_get_u32(data));
        break;
    case BLOBMSG_TYPE_INT64:
        indent_printf(indent, "%"PRId64" (i64)\n", (int64_t) blobmsg_get_u64(data));
        break;
    case BLOBMSG_TYPE_DOUBLE:
        indent_printf(indent, "%lf (dbl)\n", blobmsg_get_double(data));
        break;
    case BLOBMSG_TYPE_TABLE:
    case BLOBMSG_TYPE_ARRAY:
        if (!indent)
            indent_printf(indent, "\n");
        dump_table(blobmsg_data(data), blobmsg_data_len(data),
               next_indent, type == BLOBMSG_TYPE_ARRAY);
        break;
    }
}
References blobmsg_data(), blobmsg_data_len(), blobmsg_get_double(), blobmsg_get_string(), blobmsg_get_u16(), blobmsg_get_u32(), blobmsg_get_u64(), blobmsg_get_u8(), BLOBMSG_TYPE_ARRAY, BLOBMSG_TYPE_DOUBLE, BLOBMSG_TYPE_INT16, BLOBMSG_TYPE_INT32, BLOBMSG_TYPE_INT64, BLOBMSG_TYPE_INT8, BLOBMSG_TYPE_STRING, BLOBMSG_TYPE_TABLE, dump_table(), indent_printf, and type.
Referenced by dump_table().
dump_message()
static void dump_message (struct blob_buf * buf) static
Definition at line 93 of file test-blobmsg.c.
{
    struct blob_attr *tb[ARRAY_SIZE(pol)];
    if (blobmsg_parse(pol, ARRAY_SIZE(pol), tb, blob_data(buf->head), blob_len(buf->head)) != 0) {
        fprintf(stderr, "Parse failed\n");
        return;
    }
    if (tb[FOO_MESSAGE])
        fprintf(stderr, "Message: %s\n", (char *) blobmsg_data(tb[FOO_MESSAGE]));
    if (tb[FOO_LIST]) {
        fprintf(stderr, "List: ");
        dump_table(blobmsg_data(tb[FOO_LIST]), blobmsg_data_len(tb[FOO_LIST]), 0, true);
    }
    if (tb[FOO_TESTDATA]) {
        fprintf(stderr, "Testdata: ");
        dump_table(blobmsg_data(tb[FOO_TESTDATA]), blobmsg_data_len(tb[FOO_TESTDATA]), 0, false);
    }
}
References ARRAY_SIZE, blob_data(), blob_len(), blobmsg_data(), blobmsg_data_len(), blobmsg_parse(), buf, dump_table(), FOO_LIST, FOO_MESSAGE, FOO_TESTDATA, and pol.
Referenced by main().
dump_table()
static void dump_table (struct blob_attr * head, size_t len, int indent, bool array) static
Definition at line 21 of file test-blobmsg.c.
{
    struct blob_attr *attr;
    struct blobmsg_hdr *hdr;
    indent_printf(indent, "{\n");
    __blob_for_each_attr(attr, head, len) {
        hdr = blob_data(attr);
        if (!array)
            indent_printf(indent + 1, "%s : ", hdr->name);
        dump_attr_data(attr, 0, indent + 1);
    }
    indent_printf(indent, "}\n");
}
References __blob_for_each_attr, blob_data(), dump_attr_data(), indent_printf, and blobmsg_hdr::name.
Referenced by dump_attr_data(), and dump_message().
fill_message()
static void fill_message (struct blob_buf * buf) static
Definition at line 115 of file test-blobmsg.c.
{
    void *tbl;
    blobmsg_add_string(buf, "message", "Hello, world!");
    tbl = blobmsg_open_table(buf, "testdata");
    blobmsg_add_double(buf, "dbl-min", DBL_MIN);
    blobmsg_add_double(buf, "dbl-max", DBL_MAX);
    blobmsg_add_u8(buf, "foo", 0);
    blobmsg_add_u8(buf, "poo", 100);
    blobmsg_add_u8(buf, "moo-min", INT8_MIN);
    blobmsg_add_u8(buf, "moo-max", INT8_MAX);
    blobmsg_add_u16(buf, "bar-min", INT16_MIN);
    blobmsg_add_u16(buf, "bar-max", INT16_MAX);
    blobmsg_add_u32(buf, "baz-min", INT32_MIN);
    blobmsg_add_u32(buf, "baz-max", INT32_MAX);
    blobmsg_add_u64(buf, "taz-min", INT64_MIN);
    blobmsg_add_u64(buf, "taz-max", INT64_MAX);
    blobmsg_add_string(buf, "world", "2");
    blobmsg_close_table(buf, tbl);
    tbl = blobmsg_open_array(buf, "list");
    blobmsg_add_u8(buf, NULL, 0);
    blobmsg_add_u8(buf, NULL, 100);
    blobmsg_add_u8(buf, NULL, INT8_MIN);
    blobmsg_add_u8(buf, NULL, INT8_MAX);
    blobmsg_add_u16(buf, NULL, INT16_MIN);
    blobmsg_add_u16(buf, NULL, INT16_MAX);
    blobmsg_add_u32(buf, NULL, INT32_MIN);
    blobmsg_add_u32(buf, NULL, INT32_MAX);
    blobmsg_add_u64(buf, NULL, INT64_MIN);
    blobmsg_add_u64(buf, NULL, INT64_MAX);
    blobmsg_add_double(buf, NULL, DBL_MIN);
    blobmsg_add_double(buf, NULL, DBL_MAX);
    blobmsg_close_table(buf, tbl);
}
References blobmsg_add_double(), blobmsg_add_string(), blobmsg_add_u16(), blobmsg_add_u32(), blobmsg_add_u64(), blobmsg_add_u8(), blobmsg_close_table(), blobmsg_open_array(), blobmsg_open_table(), and buf.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 153 of file test-blobmsg.c.
{
    char *json = NULL;
    static struct blob_buf buf;
    blobmsg_buf_init(&buf);
    fill_message(&buf);
    fprintf(stderr, "[*] blobmsg dump:\n");
    dump_message(&buf);
    json = blobmsg_format_json(buf.head, true);
    if (!json)
        exit(EXIT_FAILURE);
    fprintf(stderr, "\n[*] blobmsg to json: %s\n", json);
    blobmsg_buf_init(&buf);
    if (!blobmsg_add_json_from_string(&buf, json))
        exit(EXIT_FAILURE);
    fprintf(stderr, "\n[*] blobmsg from json:\n");
    dump_message(&buf);
    if (buf.buf)
        free(buf.buf);
    free(json);
    return 0;
}
References blobmsg_add_json_from_string(), blobmsg_buf_init(), blobmsg_format_json(), buf, dump_message(), fill_message(), and json.
Variable Documentation
indent_str
const char* indent_str = "\t\t\t\t\t\t\t\t\t\t\t\t\t" static
Definition at line 10 of file test-blobmsg.c.
pol
const struct blobmsg_policy pol[] static
Initial value:
= {
    [FOO_MESSAGE] = {
        .name = "message",
        .type = BLOBMSG_TYPE_STRING,
    },
    [FOO_LIST] = {
        .name = "list",
        .type = BLOBMSG_TYPE_ARRAY,
    },
    [FOO_TESTDATA] = {
        .name = "testdata",
        .type = BLOBMSG_TYPE_TABLE,
    },
}
Definition at line 74 of file test-blobmsg.c.
{
    [FOO_MESSAGE] = {
        .name = "message",
        .type = BLOBMSG_TYPE_STRING,
    },
    [FOO_LIST] = {
        .name = "list",
        .type = BLOBMSG_TYPE_ARRAY,
    },
    [FOO_TESTDATA] = {
        .name = "testdata",
        .type = BLOBMSG_TYPE_TABLE,
    },
};
Referenced by dump_message().