zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/libubox/runqueue.h File Reference
runqueue.h File Reference
#include "list.h"
#include "safe_list.h"
#include "uloop.h"
Classes
struct runqueue
struct runqueue_task_type
struct runqueue_task
struct runqueue_process
Macros
#define RUNQUEUE_INIT(_name, _max_running)
#define RUNQUEUE(_name, _max_running)
Functions
void runqueue_init (struct runqueue *q)
void runqueue_cancel (struct runqueue *q)
void runqueue_cancel_active (struct runqueue *q)
void runqueue_cancel_pending (struct runqueue *q)
void runqueue_kill (struct runqueue *q)
void runqueue_stop (struct runqueue *q)
void runqueue_resume (struct runqueue *q)
void runqueue_task_add (struct runqueue *q, struct runqueue_task *t, bool running)
void runqueue_task_add_first (struct runqueue *q, struct runqueue_task *t, bool running)
void runqueue_task_complete (struct runqueue_task *t)
void runqueue_task_cancel (struct runqueue_task *t, int type)
void runqueue_task_kill (struct runqueue_task *t)
void runqueue_process_add (struct runqueue *q, struct runqueue_process *p, pid_t pid)
void runqueue_process_cancel_cb (struct runqueue *q, struct runqueue_task *t, int type)
void runqueue_process_kill_cb (struct runqueue *q, struct runqueue_task *t)
Class Documentation
runqueue
struct runqueue
Definition at line 30 of file runqueue.h.
Class Members
bool empty
void(*)(struct runqueue *q) empty_cb
int max_running_tasks
int running_tasks
bool stopped
struct safe_list tasks_active
struct safe_list tasks_inactive
struct uloop_timeout timeout
runqueue_task_type
struct runqueue_task_type
Definition at line 44 of file runqueue.h.
Class Members
void(*)(struct runqueue *q, struct runqueue_task *t, int type) cancel
void(*)(struct runqueue *q, struct runqueue_task *t) kill
const char * name
void(*)(struct runqueue *q, struct runqueue_task *t) run
runqueue_task
struct runqueue_task
Definition at line 71 of file runqueue.h.
Class Members
int cancel_timeout
int cancel_type
bool cancelled
void(*)(struct runqueue *q, struct runqueue_task *t) complete
struct safe_list list
struct runqueue * q
bool queued
int run_timeout
bool running
struct uloop_timeout timeout
const struct runqueue_task_type * type
runqueue_process
struct runqueue_process
Definition at line 88 of file runqueue.h.
Class Members
struct uloop_process proc
struct runqueue_task task
Macro Definition Documentation
RUNQUEUE
#define RUNQUEUE (_name, _max_running)
Value:
    struct runqueue _name = RUNQUEUE_INIT(_name, _max_running)
Definition at line 99 of file runqueue.h.
#define RUNQUEUE(_name, _max_running) \
    struct runqueue _name = RUNQUEUE_INIT(_name, _max_running)
RUNQUEUE_INIT
#define RUNQUEUE_INIT (_name, _max_running)
Value:
        { \
        .tasks_active = SAFE_LIST_INIT(_name.tasks_active), \
        .tasks_inactive = SAFE_LIST_INIT(_name.tasks_inactive), \
        .max_running_tasks = _max_running \
    }
Definition at line 93 of file runqueue.h.
#define RUNQUEUE_INIT(_name, _max_running) { \
        .tasks_active = SAFE_LIST_INIT(_name.tasks_active), \
        .tasks_inactive = SAFE_LIST_INIT(_name.tasks_inactive), \
        .max_running_tasks = _max_running \
    }
Function Documentation
runqueue_cancel()
void runqueue_cancel (struct runqueue * q)
Definition at line 102 of file runqueue.c.
{
    runqueue_cancel_pending(q);
    runqueue_cancel_active(q);
}
References q, runqueue_cancel_active(), and runqueue_cancel_pending().
runqueue_cancel_active()
void runqueue_cancel_active (struct runqueue * q)
Definition at line 92 of file runqueue.c.
{
    safe_list_for_each(&q->tasks_active, __runqueue_cancel, NULL);
}
References __runqueue_cancel(), q, safe_list_for_each(), and runqueue::tasks_active.
Referenced by runqueue_cancel().
runqueue_cancel_pending()
void runqueue_cancel_pending (struct runqueue * q)
Definition at line 97 of file runqueue.c.
{
    safe_list_for_each(&q->tasks_inactive, __runqueue_cancel, NULL);
}
References __runqueue_cancel(), q, safe_list_for_each(), and runqueue::tasks_inactive.
Referenced by runqueue_cancel(), and runqueue_kill().
runqueue_init()
void runqueue_init (struct runqueue * q)
Definition at line 31 of file runqueue.c.
{
    INIT_SAFE_LIST(&q->tasks_active);
    INIT_SAFE_LIST(&q->tasks_inactive);
}
References INIT_SAFE_LIST, q, runqueue::tasks_active, and runqueue::tasks_inactive.
Referenced by __attribute__(), main(), and rcS().
runqueue_kill()
void runqueue_kill (struct runqueue * q)
Definition at line 108 of file runqueue.c.
{
    struct runqueue_task *t;
    while (!list_empty(&q->tasks_active.list)) {
        t = list_first_entry(&q->tasks_active.list, struct runqueue_task, list.list);
        runqueue_task_kill(t);
    }
    runqueue_cancel_pending(q);
    uloop_timeout_cancel(&q->timeout);
}
References runqueue_task::list, safe_list::list, list_empty(), list_first_entry, q, runqueue_cancel_pending(), runqueue_task_kill(), runqueue::tasks_active, runqueue::timeout, and uloop_timeout_cancel().
runqueue_process_add()
void runqueue_process_add (struct runqueue * q, struct runqueue_process * p, pid_t pid)
Definition at line 269 of file runqueue.c.
{
    if (p->proc.pending)
        return;
    p->proc.pid = pid;
    p->proc.cb = __runqueue_proc_cb;
    if (!p->task.type)
        p->task.type = &runqueue_proc_type;
    uloop_process_add(&p->proc);
    if (!p->task.running)
        runqueue_task_add(q, &p->task, true);
}
References __runqueue_proc_cb(), uloop_process::cb, uloop_process::pending, uloop_process::pid, runqueue_process::proc, q, runqueue_task::running, runqueue_proc_type, runqueue_task_add(), runqueue_process::task, runqueue_task::type, and uloop_process_add().
Referenced by q_initd_run(), q_sleep_run(), and trigger_command_run().
runqueue_process_cancel_cb()
void runqueue_process_cancel_cb (struct runqueue * q, struct runqueue_task * t, int type)
Definition at line 245 of file runqueue.c.
{
    struct runqueue_process *p = container_of(t, struct runqueue_process, task);
    if (!type)
        type = SIGTERM;
    kill(p->proc.pid, type);
}
References container_of, uloop_process::pid, runqueue_process::proc, task, and type.
Referenced by add_initd(), q_sleep_cancel(), and trigger_command_start().
runqueue_process_kill_cb()
void runqueue_process_kill_cb (struct runqueue * q, struct runqueue_task * t)
Definition at line 255 of file runqueue.c.
{
    struct runqueue_process *p = container_of(t, struct runqueue_process, task);
    uloop_process_delete(&p->proc);
    kill(p->proc.pid, SIGKILL);
}
References container_of, uloop_process::pid, runqueue_process::proc, task, and uloop_process_delete().
Referenced by add_initd(), add_sleeper(), my_runqueue_process_kill_cb(), and trigger_command_start().
runqueue_resume()
void runqueue_resume (struct runqueue * q)
Definition at line 210 of file runqueue.c.
{
    q->stopped = false;
    runqueue_start_next(q);
}
References q, runqueue_start_next(), and runqueue::stopped.
runqueue_stop()
void runqueue_stop (struct runqueue * q)
Definition at line 205 of file runqueue.c.
{
    q->stopped = true;
}
References q, and runqueue::stopped.
runqueue_task_add()
void runqueue_task_add (struct runqueue * q, struct runqueue_task * t, bool running)
Definition at line 181 of file runqueue.c.
{
    _runqueue_task_add(q, t, running, 0);
}
References _runqueue_task_add(), and q.
Referenced by add_initd(), add_sleeper(), runqueue_process_add(), trigger_command_complete(), and trigger_command_start().
runqueue_task_add_first()
void runqueue_task_add_first (struct runqueue * q, struct runqueue_task * t, bool running)
Definition at line 186 of file runqueue.c.
{
    _runqueue_task_add(q, t, running, 1);
}
References _runqueue_task_add(), and q.
runqueue_task_cancel()
void runqueue_task_cancel (struct runqueue_task * t, int type)
Definition at line 120 of file runqueue.c.
{
    if (!t->queued)
        return;
    if (!t->running) {
        runqueue_task_complete(t);
        return;
    }
    t->cancelled = true;
    if (t->cancel_timeout)
        uloop_timeout_set(&t->timeout, t->cancel_timeout);
    if (t->type->cancel)
        t->type->cancel(t->q, t, type);
}
References runqueue_task_type::cancel, runqueue_task::cancel_timeout, runqueue_task::cancelled, runqueue_task::q, runqueue_task::queued, runqueue_task::running, runqueue_task_complete(), runqueue_task::timeout, runqueue_task::type, type, and uloop_timeout_set().
Referenced by __runqueue_cancel(), and __runqueue_task_timeout().
runqueue_task_complete()
void runqueue_task_complete (struct runqueue_task * t)
Definition at line 216 of file runqueue.c.
{
    struct runqueue *q = t->q;
    if (!t->queued)
        return;
    if (t->running)
        t->q->running_tasks--;
    uloop_timeout_cancel(&t->timeout);
    safe_list_del(&t->list);
    t->queued = false;
    t->running = false;
    t->cancelled = false;
    if (t->complete)
        t->complete(q, t);
    runqueue_start_next(q);
}
References runqueue_task::cancelled, runqueue_task::complete, runqueue_task::list, q, runqueue_task::q, runqueue_task::queued, runqueue_task::running, runqueue::running_tasks, runqueue_start_next(), safe_list_del(), runqueue_task::timeout, and uloop_timeout_cancel().
Referenced by __runqueue_proc_cb(), runqueue_task_cancel(), and runqueue_task_kill().
runqueue_task_kill()
void runqueue_task_kill (struct runqueue_task * t)
Definition at line 191 of file runqueue.c.
{
    struct runqueue *q = t->q;
    bool running = t->running;
    if (!t->queued)
        return;
    if (running && t->type->kill)
        t->type->kill(q, t);
    runqueue_task_complete(t);
}
References runqueue_task_type::kill, q, runqueue_task::q, runqueue_task::queued, runqueue_task::running, runqueue_task_complete(), and runqueue_task::type.
Referenced by __runqueue_task_timeout(), runqueue_kill(), and timer_cb().