zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/ubus/libubus-acl.c File Reference
libubus-acl.c File Reference
#include <unistd.h>
#include <libubox/blob.h>
#include <libubox/blobmsg.h>
#include "libubus.h"
#include <libubox/avl-cmp.h>
Enumerations
enum {
ACL_OBJ_OBJECT , ACL_OBJ_USER , ACL_OBJ_GROUP , ACL_OBJ_ACL ,
__ACL_OBJ_MAX
}
enum { ACL_POLICY_SEQ , ACL_POLICY_ACL , __ACL_POLICY_MAX }
Functions
static int acl_cmp (const void *k1, const void *k2, void *ptr)
AVL_TREE (acl_objects, acl_cmp, true, NULL)
static void acl_add (struct blob_attr *obj)
static void acl_recv_cb (struct ubus_request *req, int type, struct blob_attr *msg)
static void acl_query (struct ubus_context *ctx)
static void acl_subscribe_cb (struct ubus_context *ctx, struct ubus_event_handler *ev, const char *type, struct blob_attr *msg)
int ubus_register_acl (struct ubus_context *ctx)
Variables
static struct ubus_event_handler acl_event
static struct ubus_request acl_req
static struct blob_attr * acl_blob
static const struct blobmsg_policy acl_obj_policy [__ACL_OBJ_MAX]
static const struct blobmsg_policy acl_policy [__ACL_POLICY_MAX]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ACL_OBJ_OBJECT
ACL_OBJ_USER
ACL_OBJ_GROUP
ACL_OBJ_ACL
__ACL_OBJ_MAX
Definition at line 47 of file libubus-acl.c.
     {
    ACL_OBJ_OBJECT,
    ACL_OBJ_USER,
    ACL_OBJ_GROUP,
    ACL_OBJ_ACL,
    __ACL_OBJ_MAX
};
anonymous enum
anonymous enum
Enumerator
ACL_POLICY_SEQ
ACL_POLICY_ACL
__ACL_POLICY_MAX
Definition at line 89 of file libubus-acl.c.
     {
    ACL_POLICY_SEQ,
    ACL_POLICY_ACL,
    __ACL_POLICY_MAX
};
Function Documentation
acl_add()
static void acl_add (struct blob_attr * obj) static
Definition at line 63 of file libubus-acl.c.
{
    struct blob_attr *tb[__ACL_OBJ_MAX];
    struct acl_object *acl;
    blobmsg_parse(acl_obj_policy, __ACL_OBJ_MAX, tb, blobmsg_data(obj),
              blobmsg_data_len(obj));
    if (!tb[ACL_OBJ_OBJECT] || !tb[ACL_OBJ_ACL])
        return;
    if (!tb[ACL_OBJ_USER] && !tb[ACL_OBJ_GROUP])
        return;
    acl = calloc(1, sizeof(*acl));
    if (!acl)
        return;
    acl->avl.key = &acl->key;
    acl->key.object = blobmsg_get_string(tb[ACL_OBJ_OBJECT]);
    acl->key.user = blobmsg_get_string(tb[ACL_OBJ_USER]);
    acl->key.group = blobmsg_get_string(tb[ACL_OBJ_GROUP]);
    acl->acl = tb[ACL_OBJ_ACL];
    avl_insert(&acl_objects, &acl->avl);
}
References __ACL_OBJ_MAX, acl_object::acl, ACL_OBJ_ACL, ACL_OBJ_GROUP, ACL_OBJ_OBJECT, acl_obj_policy, ACL_OBJ_USER, acl_objects, avl_insert(), blobmsg_data(), blobmsg_data_len(), blobmsg_get_string(), and blobmsg_parse().
Referenced by acl_recv_cb().
acl_cmp()
static int acl_cmp (const void * k1, const void * k2, void * ptr) static
Definition at line 26 of file libubus-acl.c.
{
    const struct ubus_acl_key *key1 = k1;
    const struct ubus_acl_key *key2 = k2;
    int ret = 0;
    if (key1->user && key2->user)
        ret = strcmp(key1->user, key2->user);
    if (ret)
        return ret;
    if (key1->group && key2->group)
        ret = strcmp(key1->group, key2->group);
    if (ret)
        return ret;
    return strcmp(key1->object, key2->object);
}
References ubus_acl_key::group, ubus_acl_key::object, and ubus_acl_key::user.
acl_query()
static void acl_query (struct ubus_context * ctx) static
Definition at line 127 of file libubus-acl.c.
{
    ubus_invoke_async(ctx, UBUS_SYSTEM_OBJECT_ACL, "query", NULL, &acl_req);
    acl_req.data_cb = acl_recv_cb;
    ubus_complete_request_async(ctx, &acl_req);
}
References acl_recv_cb(), acl_req, ctx, ubus_request::data_cb, ubus_complete_request_async(), ubus_invoke_async(), and UBUS_SYSTEM_OBJECT_ACL.
Referenced by acl_subscribe_cb(), and ubus_register_acl().
acl_recv_cb()
static void acl_recv_cb (struct ubus_request * req, int type, struct blob_attr * msg) static
Definition at line 100 of file libubus-acl.c.
{
    struct blob_attr *tb[__ACL_POLICY_MAX];
    struct blob_attr *cur;
    size_t rem;
    if (acl_blob) {
        struct acl_object *p, *q;
        avl_for_each_element_safe(&acl_objects, p, avl, q) {
            avl_delete(&acl_objects, &p->avl);
            free(p);
        }
        free(acl_blob);
    }
    acl_blob = blob_memdup(msg);
    blobmsg_parse(acl_policy, __ACL_POLICY_MAX, tb, blobmsg_data(msg),
              blobmsg_data_len(msg));
    if (!tb[ACL_POLICY_SEQ] && !tb[ACL_POLICY_ACL])
        return;
    blobmsg_for_each_attr(cur, tb[ACL_POLICY_ACL], rem)
        acl_add(cur);
}
References __ACL_POLICY_MAX, acl_add(), acl_blob, acl_objects, acl_policy, ACL_POLICY_ACL, ACL_POLICY_SEQ, acl_object::avl, avl_delete(), avl_for_each_element_safe, blob_memdup(), blobmsg_data(), blobmsg_data_len(), blobmsg_for_each_attr, blobmsg_parse(), and q.
Referenced by acl_query().
acl_subscribe_cb()
static void acl_subscribe_cb (struct ubus_context * ctx, struct ubus_event_handler * ev, const char * type, struct blob_attr * msg) static
Definition at line 134 of file libubus-acl.c.
{
    if (strcmp(type, "ubus.acl.sequence"))
        return;
    acl_query(ctx);
}
References acl_query(), ctx, and type.
Referenced by ubus_register_acl().
AVL_TREE()
AVL_TREE (acl_objects , acl_cmp , true , NULL)
ubus_register_acl()
int ubus_register_acl (struct ubus_context * ctx)
Definition at line 142 of file libubus-acl.c.
{
    int ret;
    acl_event.cb = acl_subscribe_cb;
    ret = ubus_register_event_handler(ctx, &acl_event, "ubus.acl.sequence");
    if (!ret)
        acl_query(ctx);
    return ret;
}
References acl_event, acl_query(), acl_subscribe_cb(), ubus_event_handler::cb, ctx, and ubus_register_event_handler().
Variable Documentation
acl_blob
struct blob_attr* acl_blob static
Definition at line 24 of file libubus-acl.c.
Referenced by acl_recv_cb().
acl_event
struct ubus_event_handler acl_event static
Definition at line 22 of file libubus-acl.c.
Referenced by ubus_register_acl().
acl_obj_policy
const struct blobmsg_policy acl_obj_policy[__ACL_OBJ_MAX] static
Initial value:
= {
    [ACL_OBJ_OBJECT] = { .name = "obj", .type = BLOBMSG_TYPE_STRING },
    [ACL_OBJ_USER] = { .name = "user", .type = BLOBMSG_TYPE_STRING },
    [ACL_OBJ_GROUP] = { .name = "group", .type = BLOBMSG_TYPE_STRING },
    [ACL_OBJ_ACL] = { .name = "acl", .type = BLOBMSG_TYPE_TABLE },
}
Definition at line 55 of file libubus-acl.c.
{
    [ACL_OBJ_OBJECT] = { .name = "obj", .type = BLOBMSG_TYPE_STRING },
    [ACL_OBJ_USER] = { .name = "user", .type = BLOBMSG_TYPE_STRING },
    [ACL_OBJ_GROUP] = { .name = "group", .type = BLOBMSG_TYPE_STRING },
    [ACL_OBJ_ACL] = { .name = "acl", .type = BLOBMSG_TYPE_TABLE },
};
Referenced by acl_add().
acl_policy
const struct blobmsg_policy acl_policy[__ACL_POLICY_MAX] static
Initial value:
= {
    [ACL_POLICY_SEQ] = { .name = "seq", .type = BLOBMSG_TYPE_INT32 },
    [ACL_POLICY_ACL] = { .name = "acl", .type = BLOBMSG_TYPE_ARRAY },
}
Definition at line 95 of file libubus-acl.c.
{
    [ACL_POLICY_SEQ] = { .name = "seq", .type = BLOBMSG_TYPE_INT32 },
    [ACL_POLICY_ACL] = { .name = "acl", .type = BLOBMSG_TYPE_ARRAY },
};
Referenced by acl_recv_cb().
acl_req
struct ubus_request acl_req static
Definition at line 23 of file libubus-acl.c.
Referenced by acl_query().