zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/libubox/json_script.h File Reference
json_script.h File Reference
#include "avl.h"
#include "blob.h"
#include "blobmsg.h"
#include "utils.h"
Classes
struct json_script_ctx
struct json_script_file
Functions
void json_script_init (struct json_script_ctx *ctx)
void json_script_free (struct json_script_ctx *ctx)
void json_script_run (struct json_script_ctx *ctx, const char *filename, struct blob_attr *vars)
void json_script_run_file (struct json_script_ctx *ctx, struct json_script_file *file, struct blob_attr *vars)
static void json_script_abort (struct json_script_ctx *ctx)
int json_script_eval_string (struct json_script_ctx *ctx, struct blob_attr *vars, struct blob_buf *buf, const char *name, const char *pattern)
struct json_script_file * json_script_file_from_blobmsg (const char *name, void *data, int len)
const char * json_script_find_var (struct json_script_ctx *ctx, struct blob_attr *vars, const char *name)
Class Documentation
json_script_ctx
struct json_script_ctx
Definition at line 26 of file json_script.h.
Class Members
bool abort
struct blob_buf buf
struct avl_tree files
void(*)(struct json_script_ctx *ctx, const char *name, struct blob_attr *cmd, struct blob_attr *vars) handle_command
void(*)(struct json_script_ctx *ctx, const char *msg, struct blob_attr *context) handle_error
int(*)(struct json_script_ctx *ctx, const char *name, struct blob_attr *expr, struct blob_attr *vars) handle_expr
struct json_script_file *(*)(struct json_script_ctx *ctx, const char *name) handle_file
const char *(*)(struct json_script_ctx *ctx, const char *name, struct blob_attr *vars) handle_var
uint32_t run_seq
json_script_file
struct json_script_file
Definition at line 81 of file json_script.h.
Class Members
struct avl_node avl
struct blob_attr data[]
struct json_script_file * next
unsigned int seq
Function Documentation
json_script_abort()
static void json_script_abort (struct json_script_ctx * ctx) inline static
Definition at line 110 of file json_script.h.
{
    ctx->abort = true;
}
References ctx.
json_script_eval_string()
int json_script_eval_string (struct json_script_ctx * ctx, struct blob_attr * vars, struct blob_buf * buf, const char * name, const char * pattern)
Definition at line 502 of file json_script.c.
{
    struct json_call call = {
        .ctx = ctx,
        .vars = vars,
    };
    return eval_string(&call, buf, name, pattern);
}
References buf, ctx, eval_string(), and json_call::vars.
json_script_file_from_blobmsg()
struct json_script_file * json_script_file_from_blobmsg (const char * name, void * data, int len)
Definition at line 38 of file json_script.c.
{
    struct json_script_file *f;
    char *new_name;
    int name_len = 0;
    if (name)
        name_len = strlen(name) + 1;
    f = calloc_a(sizeof(*f) + len, &new_name, name_len);
    if (!f)
        return NULL;
    memcpy(f->data, data, len);
    if (name)
        f->avl.key = strcpy(new_name, name);
    return f;
}
References json_script_file::avl, calloc_a, json_script_file::data, and avl_node::key.
Referenced by handle_file(), handle_file(), rule_handle_file(), and rule_load_script().
json_script_find_var()
const char * json_script_find_var (struct json_script_ctx * ctx, struct blob_attr * vars, const char * name)
Definition at line 94 of file json_script.c.
{
    struct blob_attr *cur;
    size_t rem;
    blobmsg_for_each_attr(cur, vars, rem) {
        if (blobmsg_type(cur) != BLOBMSG_TYPE_STRING)
            continue;
        if (strcmp(blobmsg_name(cur), name) != 0)
            continue;
        return blobmsg_data(cur);
    }
    return ctx->handle_var(ctx, name, vars);
}
References blobmsg_data(), blobmsg_for_each_attr, blobmsg_name(), BLOBMSG_TYPE_STRING, and ctx.
Referenced by msg_find_var(), and rule_handle_var().
json_script_free()
void json_script_free (struct json_script_ctx * ctx)
Definition at line 652 of file json_script.c.
{
    struct json_script_file *f, *next;
    avl_remove_all_elements(&ctx->files, f, avl, next)
        __json_script_file_free(f);
    blob_buf_free(&ctx->buf);
}
References __json_script_file_free(), json_script_file::avl, avl_remove_all_elements, blob_buf_free(), ctx, and json_script_file::next.
Referenced by main(), and trigger_free().
json_script_init()
void json_script_init (struct json_script_ctx * ctx)
Definition at line 689 of file json_script.c.
{
    avl_init(&ctx->files, avl_strcmp, false, NULL);
    if (!ctx->handle_error)
        ctx->handle_error = __default_handle_error;
    if (!ctx->handle_var)
        ctx->handle_var = __default_handle_var;
    if (!ctx->handle_expr)
        ctx->handle_expr = __default_handle_expr;
    if (!ctx->handle_file)
        ctx->handle_file = __default_handle_file;
}
References __default_handle_error(), __default_handle_expr(), __default_handle_file(), __default_handle_var(), avl_init(), avl_strcmp(), and ctx.
Referenced by _trigger_add(), hotplug(), and main().
json_script_run()
void json_script_run (struct json_script_ctx * ctx, const char * filename, struct blob_attr * vars)
Definition at line 626 of file json_script.c.
{
    struct json_script_file *file;
    file = json_script_get_file(ctx, name);
    if (!file)
        return;
    json_script_run_file(ctx, file, vars);
}
References ctx, json_script_get_file(), and json_script_run_file().
Referenced by hotplug_handler(), main(), and trigger_event().
json_script_run_file()
void json_script_run_file (struct json_script_ctx * ctx, struct json_script_file * file, struct blob_attr * vars)
Definition at line 607 of file json_script.c.
{
    static unsigned int _seq = 0;
    struct json_call call = {
        .ctx = ctx,
        .vars = vars,
        .seq = ++_seq,
    };
    /* overflow */
    if (!call.seq)
        call.seq = ++_seq;
    ctx->abort = false;
    __json_script_run(&call, file, NULL);
}
References __json_script_run(), ctx, json_call::seq, and json_call::vars.
Referenced by json_script_run().