zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/state.c File Reference
state.c File Reference
#include <fcntl.h>
#include <pwd.h>
#include <sys/reboot.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <signal.h>
#include "container.h"
#include "procd.h"
#include "syslog.h"
#include "plug/hotplug.h"
#include "watchdog.h"
#include "service/service.h"
#include "utils/utils.h"
Enumerations
enum {
STATE_NONE = 0 , STATE_EARLY , STATE_UBUS , STATE_INIT ,
STATE_RUNNING , STATE_SHUTDOWN , STATE_HALT , __STATE_MAX
}
Functions
static void set_stdio (const char *tty)
static void set_console (void)
static void perform_halt ()
static void state_enter (void)
void procd_state_next (void)
void procd_state_ubus_connect (void)
void procd_shutdown (int event)
Variables
static int state = STATE_NONE
static int reboot_event
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
STATE_NONE 0
STATE_EARLY
STATE_UBUS
STATE_INIT
STATE_RUNNING
STATE_SHUTDOWN
STATE_HALT
__STATE_MAX
Definition at line 32 of file state.c.
     {
    STATE_NONE = 0,
    STATE_EARLY,
    STATE_UBUS,
    STATE_INIT,
    STATE_RUNNING,
    STATE_SHUTDOWN,
    STATE_HALT,
    __STATE_MAX,
};
Function Documentation
perform_halt()
static void perform_halt () static
Definition at line 98 of file state.c.
{
    if (reboot_event == RB_POWER_OFF)
        LOG("- power down -\n");
    else
        LOG("- reboot -\n");
    /* Allow time for last message to reach serial console, etc */
    sleep(1);
    if (is_container()) {
        reboot(reboot_event);
        exit(EXIT_SUCCESS);
        return;
    }
    /* We have to fork here, since the kernel calls do_exit(EXIT_SUCCESS)
     * in linux/kernel/sys.c, which can cause the machine to panic when
     * the init process exits... */
    if (!vfork()) { /* child */
        reboot(reboot_event);
        _exit(EXIT_SUCCESS);
    }
    while (1)
        sleep(1);
}
References is_container(), LOG, and reboot_event.
Referenced by state_enter().
procd_shutdown()
void procd_shutdown (int event)
Definition at line 222 of file state.c.
{
    if (state >= STATE_SHUTDOWN)
        return;
    DEBUG(2, "Shutting down system with event %x\n", event);
    reboot_event = event;
    state = STATE_SHUTDOWN;
    state_enter();
}
References DEBUG, reboot_event, state, state_enter(), and STATE_SHUTDOWN.
Referenced by signal_shutdown(), and system_reboot().
procd_state_next()
void procd_state_next (void)
Definition at line 209 of file state.c.
{
    DEBUG(4, "Change state %d -> %d\n", state, state + 1);
    state++;
    state_enter();
}
References DEBUG, state, and state_enter().
Referenced by coldplug_complete(), main(), procd_state_ubus_connect(), and rcdone().
procd_state_ubus_connect()
void procd_state_ubus_connect (void)
Definition at line 216 of file state.c.
{
    if (state == STATE_UBUS)
        procd_state_next();
}
References procd_state_next(), state, and STATE_UBUS.
Referenced by ubus_connect_cb().
set_console()
static void set_console (void) static
Definition at line 58 of file state.c.
{
    const char* tty;
    char* split;
    char line[ 20 ];
    const char* try[] = { "tty0", "console", NULL }; /* Try the most common outputs */
    int f, i = 0;
    tty = get_cmdline_val("console",line,sizeof(line));
    if (tty != NULL) {
        split = strchr(tty, ',');
        if ( split != NULL )
            *split = '\0';
    } else {
        // Try a default
        tty=try[i];
        i++;
    }
    if (chdir("/dev")) {
        ERROR("failed to change dir to /dev: %m\n");
        return;
    }
    while (tty!=NULL) {
        f = open(tty, O_RDONLY);
        if (f >= 0) {
            close(f);
            break;
        }
        tty=try[i];
        i++;
    }
    if (chdir("/"))
        ERROR("failed to change dir to /: %m\n");
    if (tty != NULL)
        set_stdio(tty);
}
References ERROR, get_cmdline_val, and set_stdio().
Referenced by state_enter().
set_stdio()
static void set_stdio (const char * tty) static
Definition at line 46 of file state.c.
{
    if (chdir("/dev") ||
        !freopen(tty, "r", stdin) ||
        !freopen(tty, "w", stdout) ||
        !freopen(tty, "w", stderr) ||
        chdir("/"))
        ERROR("failed to set stdio: %m\n");
    else
        fcntl(STDERR_FILENO, F_SETFL, fcntl(STDERR_FILENO, F_GETFL) | O_NONBLOCK);
}
References ERROR.
Referenced by set_console(), and state_enter().
state_enter()
static void state_enter (void) static
Definition at line 126 of file state.c.
{
    char ubus_cmd[] = "/sbin/ubusd";
    struct passwd *p;
    switch (state) {
    case STATE_EARLY:
        LOG("- early -\n");
        watchdog_init(0);
        hotplug("/etc/hotplug.json");
        procd_coldplug();
        break;
    case STATE_UBUS:
        // try to reopen incase the wdt was not available before coldplug
        watchdog_init(0);
        set_stdio("console");
        p = getpwnam("ubus");
        if (p) {
            int ret;
            LOG("- ubus -\n");
            mkdir(p->pw_dir, 0755);
            ret = chown(p->pw_dir, p->pw_uid, p->pw_gid);
            if (ret)
                LOG("- ubus - failed to chown(%s)\n", p->pw_dir);
        } else {
            LOG("- ubus (running as root!) -\n");
        }
        procd_connect_ubus();
        service_start_early("ubus", ubus_cmd, p?"ubus":NULL, p?"ubus":NULL);
        break;
    case STATE_INIT:
        LOG("- init -\n");
        procd_inittab();
        procd_inittab_run("respawn");
        procd_inittab_run("askconsole");
        procd_inittab_run("askfirst");
        procd_inittab_run("sysinit");
        // switch to syslog log channel
        ulog_open(ULOG_SYSLOG, LOG_DAEMON, "procd");
        break;
    case STATE_RUNNING:
        LOG("- init complete -\n");
        procd_inittab_run("respawnlate");
        procd_inittab_run("askconsolelate");
        break;
    case STATE_SHUTDOWN:
        /* Redirect output to the console for the users' benefit */
        set_console();
        LOG("- shutdown -\n");
        procd_inittab_run("shutdown");
        sync();
        break;
    case STATE_HALT:
        // To prevent killed processes from interrupting the sleep
        signal(SIGCHLD, SIG_IGN);
        LOG("- SIGTERM processes -\n");
        kill(-1, SIGTERM);
        sync();
        sleep(1);
        LOG("- SIGKILL processes -\n");
        kill(-1, SIGKILL);
        sync();
        sleep(1);
#ifndef DISABLE_INIT
        perform_halt();
#else
        exit(EXIT_SUCCESS);
#endif
        break;
    default:
        ERROR("Unhandled state %d\n", state);
        return;
    };
}
References ERROR, hotplug(), LOG, perform_halt(), procd_coldplug(), procd_connect_ubus(), procd_inittab(), procd_inittab_run(), service_start_early(), set_console(), set_stdio(), state, STATE_EARLY, STATE_HALT, STATE_INIT, STATE_RUNNING, STATE_SHUTDOWN, STATE_UBUS, ulog_open(), ULOG_SYSLOG, and watchdog_init().
Referenced by procd_shutdown(), and procd_state_next().
Variable Documentation
reboot_event
int reboot_event static
Definition at line 44 of file state.c.
Referenced by perform_halt(), and procd_shutdown().
state
int state = STATE_NONE static
Definition at line 43 of file state.c.
Referenced by procd_shutdown(), procd_state_next(), procd_state_ubus_connect(), and state_enter().