zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/libubox/vlist.c File Reference
vlist.c File Reference
#include "vlist.h"
Functions
void vlist_init (struct vlist_tree *tree, avl_tree_comp cmp, vlist_update_cb update)
void vlist_delete (struct vlist_tree *tree, struct vlist_node *node)
void vlist_add (struct vlist_tree *tree, struct vlist_node *node, const void *key)
void vlist_flush (struct vlist_tree *tree)
void vlist_flush_all (struct vlist_tree *tree)
Function Documentation
vlist_add()
void vlist_add (struct vlist_tree * tree, struct vlist_node * node, const void * key)
Definition at line 36 of file vlist.c.
{
    struct vlist_node *old_node = NULL;
    struct avl_node *anode;
    node->avl.key = key;
    node->version = tree->version;
    anode = avl_find(&tree->avl, key);
    if (anode) {
        old_node = container_of(anode, struct vlist_node, avl);
        if (tree->keep_old || tree->no_delete) {
            old_node->version = tree->version;
            goto update_only;
        }
        avl_delete(&tree->avl, anode);
    }
    avl_insert(&tree->avl, &node->avl);
update_only:
    tree->update(tree, node, old_node);
}
References node::avl, vlist_tree::avl, avl_delete(), avl_find(), avl_insert(), container_of, vlist_tree::keep_old, avl_node::key, vlist_tree::no_delete, vlist_tree::update, vlist_node::version, and vlist_tree::version.
Referenced by __interface_add(), bonding_create_port(), bridge_hotplug_get_vlan(), bridge_insert_member(), config_parse_vlan(), extdev_bridge_create_member(), interface_ip_add_device_prefix(), interface_ip_add_neighbor(), interface_ip_add_route(), interface_ip_add_target_route(), iprule_add(), parse_address_list(), parse_gateway_option(), parse_static_address_option(), service_instance_add(), ubusd_acl_load_file(), wireless_device_create(), wireless_interface_create(), wireless_station_create(), and wireless_vlan_create().
vlist_delete()
void vlist_delete (struct vlist_tree * tree, struct vlist_node * node)
Definition at line 28 of file vlist.c.
{
    if (!tree->no_delete)
        avl_delete(&tree->avl, &node->avl);
    tree->update(tree, NULL, node);
}
References node::avl, vlist_tree::avl, avl_delete(), vlist_tree::no_delete, and vlist_tree::update.
Referenced by bonding_hotplug_del(), bonding_port_cb(), bridge_free_member(), bridge_hotplug_del(), bridge_member_cb(), extdev_bridge_member_cb(), extdev_hotplug_remove(), interface_ip_valid_until_handler(), netifd_iface_do_remove(), service_handle_delete(), and vlist_flush().
vlist_flush()
void vlist_flush (struct vlist_tree * tree)
Definition at line 62 of file vlist.c.
{
    struct vlist_node *node, *tmp;
    avl_for_each_element_safe(&tree->avl, node, avl, tmp) {
        if ((node->version == tree->version || node->version == -1) &&
            tree->version != -1)
            continue;
        vlist_delete(tree, node);
    }
}
References vlist_node::avl, vlist_tree::avl, avl_for_each_element_safe, vlist_tree::version, and vlist_delete().
Referenced by __bridge_config_init(), bonding_config_init(), bridge_config_init(), config_init_all(), config_init_procd_wireless_interface(), config_init_wireless(), config_parse_wireless_interface(), device_vlan_update(), interface_ip_update_complete(), iprule_update_complete(), service_handle_update(), service_update(), ubusd_acl_load(), and vlist_flush_all().
vlist_flush_all()
void vlist_flush_all (struct vlist_tree * tree)
Definition at line 76 of file vlist.c.
{
    tree->version = -1;
    vlist_flush(tree);
}
References vlist_tree::version, and vlist_flush().
Referenced by bonding_free(), bridge_free(), extdev_free(), interface_ip_flush(), service_delete(), vif_free(), and wireless_device_free().
vlist_init()
void vlist_init (struct vlist_tree * tree, avl_tree_comp cmp, vlist_update_cb update)
Definition at line 19 of file vlist.c.
{
    tree->update = update;
    tree->version = 1;
    avl_init(&tree->avl, cmp, 0, tree);
}
References vlist_tree::avl, avl_init(), cmp, vlist_tree::update, and vlist_tree::version.
Referenced by __bridge_create(), __interface_ip_init(), bonding_create(), bridge_create(), interface_init_list(), interface_ip_init(), iprule_init_list(), service_alloc(), wireless_device_create(), wireless_init(), and wireless_interface_create().