zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/rpcd/include/rpcd/rc.h File Reference
rc.h File Reference
Functions
int rpc_rc_api_init (struct ubus_context *ctx)
Function Documentation
rpc_rc_api_init()
int rpc_rc_api_init (struct ubus_context * ctx)
Definition at line 391 of file rc.c.
{
    static const struct ubus_method rc_methods[] = {
        UBUS_METHOD("list", rc_list, rc_list_policy),
        UBUS_METHOD("init", rc_init, rc_init_policy),
    };
    static struct ubus_object_type rc_type =
        UBUS_OBJECT_TYPE("rc", rc_methods);
    static struct ubus_object obj = {
        .name = "rc",
        .type = &rc_type,
        .methods = rc_methods,
        .n_methods = ARRAY_SIZE(rc_methods),
    };
    return ubus_add_object(ctx, &obj);
}
References ARRAY_SIZE, ctx, ubus_object_type::methods, rc_init(), rc_init_policy, rc_list(), rc_list_policy, ubus_add_object(), UBUS_METHOD, and UBUS_OBJECT_TYPE.
Referenced by main().