zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/jail/fs.h File Reference
fs.h File Reference
#include <sys/mount.h>
#include <libubox/blobmsg.h>
Functions
int add_mount (const char *source, const char *target, const char *filesystemtype, unsigned long mountflags, unsigned long propflags, const char *optstr, int error)
int add_mount_inner (const char *source, const char *target, const char *filesystemtype, unsigned long mountflags, unsigned long propflags, const char *optstr, int error)
int add_mount_bind (const char *path, int readonly, int error)
int parseOCImount (struct blob_attr *msg)
int add_2paths_and_deps (const char *path, const char *path2, int readonly, int error, int lib)
static int add_path_and_deps (const char *path, int readonly, int error, int lib)
int mount_all (const char *jailroot)
void mount_list_init (void)
void mount_free (void)
Function Documentation
add_2paths_and_deps()
int add_2paths_and_deps (const char * path, const char * path2, int readonly, int error, int lib)
Definition at line 486 of file fs.c.
{
    assert(path != NULL);
    assert(path2 != NULL);
    if (lib == 0 && path[0] != '/') {
        ERROR("%s is not an absolute path\n", path);
        return error;
    }
    char *map = NULL;
    int fd, ret = -1;
    if (path[0] == '/') {
        if (avl_find(&mounts, path2))
            return 0;
        fd = open(path, O_RDONLY|O_CLOEXEC);
        if (fd < 0)
            return error;
        _add_mount_bind(path, path2, readonly, error);
    } else {
        if (avl_find(&libraries, path))
            return 0;
        char *fullpath;
        fd = lib_open(&fullpath, path);
        if (fd < 0)
            return error;
        if (fullpath) {
            alloc_library(fullpath, path);
            free(fullpath);
        }
    }
    struct stat s;
    if (fstat(fd, &s) == -1) {
        ERROR("fstat(%s) failed: %m\n", path);
        ret = error;
        goto out;
    }
    if (!S_ISREG(s.st_mode)) {
        ret = 0;
        goto out;
    }
    /* too small to be an ELF or a script -> "normal" file */
    if (s.st_size < 4) {
        ret = 0;
        goto out;
    }
    map = mmap(NULL, s.st_size, PROT_READ, MAP_PRIVATE, fd, 0);
    if (map == MAP_FAILED) {
        ERROR("failed to mmap %s: %m\n", path);
        ret = -1;
        goto out;
    }
    if (map[0] == '#' && map[1] == '!') {
        ret = add_script_interp(path, map, s.st_size);
        goto out;
    }
    if (map[0] == ELFMAG0 && map[1] == ELFMAG1 && map[2] == ELFMAG2 && map[3] == ELFMAG3) {
        ret = elf_load_deps(path, map);
        goto out;
    }
    ret = 0;
out:
    if (fd >= 0)
        close(fd);
    if (map)
        munmap(map, s.st_size);
    return ret;
}
References _add_mount_bind(), add_script_interp(), alloc_library(), avl_find(), elf_load_deps(), ERROR, mount::error, lib_open(), libraries, mounts, and path.
Referenced by add_path_and_deps(), and main().
add_mount()
int add_mount (const char * source, const char * target, const char * filesystemtype, unsigned long mountflags, unsigned long propflags, const char * optstr, int error)
Definition at line 197 of file fs.c.
{
    return _add_mount(source, target, filesystemtype, mountflags, propflags, optstr, error, false);
}
References _add_mount(), mount::error, mount::filesystemtype, mount::mountflags, mount::optstr, mount::propflags, mount::source, and mount::target.
Referenced by _add_mount_bind(), parseOCIlinux(), parseOCImount(), and post_main().
add_mount_bind()
int add_mount_bind (const char * path, int readonly, int error)
Definition at line 219 of file fs.c.
{
    return _add_mount_bind(path, path, readonly, error);
}
References _add_mount_bind(), mount::error, and path.
Referenced by main(), mount_all(), and post_main().
add_mount_inner()
int add_mount_inner (const char * source, const char * target, const char * filesystemtype, unsigned long mountflags, unsigned long propflags, const char * optstr, int error)
Definition at line 203 of file fs.c.
{
    return _add_mount(source, target, filesystemtype, mountflags, propflags, optstr, error, true);
}
References _add_mount(), mount::error, mount::filesystemtype, mount::mountflags, mount::optstr, mount::propflags, mount::source, and mount::target.
Referenced by post_main().
add_path_and_deps()
static int add_path_and_deps (const char * path, int readonly, int error, int lib) inline static
Definition at line 27 of file fs.h.
{
    return add_2paths_and_deps(path, path, readonly, error, lib);
}
References add_2paths_and_deps(), and path.
Referenced by add_script_interp(), elf32_scan_dynamic(), elf64_scan_dynamic(), elf_load_deps(), and main().
mount_all()
int mount_all (const char * jailroot)
Definition at line 429 of file fs.c.
{
    struct library *l;
    struct mount *m;
    build_noafile();
    avl_for_each_element(&libraries, l, avl)
        add_mount_bind(l->path, 1, -1);
    avl_for_each_element(&mounts, m, avl)
        if (do_mount(jailroot, m->source, m->target, m->filesystemtype, m->mountflags,
                 m->propflags, m->optstr, m->error, m->inner))
            return -1;
    return 0;
}
References add_mount_bind(), mount::avl, avl_for_each_element, build_noafile(), do_mount(), mount::error, mount::filesystemtype, mount::inner, libraries, mount::mountflags, mounts, mount::optstr, library::path, mount::propflags, mount::source, and mount::target.
Referenced by build_jail_fs().
mount_free()
void mount_free (void)
Definition at line 446 of file fs.c.
                      {
    struct mount *m, *tmp;
    avl_remove_all_elements(&mounts, m, avl, tmp) {
        if (m->source != (void*)(-1))
            free((void*)m->source);
        free((void*)m->target);
        free((void*)m->filesystemtype);
        free((void*)m->optstr);
        free(m);
    }
}
References mount::avl, avl_remove_all_elements, mount::filesystemtype, mounts, mount::optstr, mount::source, and mount::target.
Referenced by free_opts().
mount_list_init()
void mount_list_init (void)
Definition at line 459 of file fs.c.
{
    avl_init(&mounts, avl_strcmp, false, NULL);
}
References avl_init(), avl_strcmp(), and mounts.
Referenced by main().
parseOCImount()
int parseOCImount (struct blob_attr * msg)
Definition at line 388 of file fs.c.
{
    struct blob_attr *tb[__OCI_MOUNT_MAX];
    unsigned long mount_flags = 0;
    unsigned long propagation_flags = 0;
    char *mount_data = NULL;
    int ret, err = -1;
    blobmsg_parse(oci_mount_policy, __OCI_MOUNT_MAX, tb, blobmsg_data(msg), blobmsg_len(msg));
    if (!tb[OCI_MOUNT_DESTINATION])
        return EINVAL;
    if (tb[OCI_MOUNT_OPTIONS]) {
        ret = parseOCImountopts(tb[OCI_MOUNT_OPTIONS], &mount_flags, &propagation_flags, &mount_data, &err);
        if (ret)
            return ret;
    }
    ret = add_mount(tb[OCI_MOUNT_SOURCE] ? blobmsg_get_string(tb[OCI_MOUNT_SOURCE]) : NULL,
          blobmsg_get_string(tb[OCI_MOUNT_DESTINATION]),
          tb[OCI_MOUNT_TYPE] ? blobmsg_get_string(tb[OCI_MOUNT_TYPE]) : NULL,
          mount_flags, propagation_flags, mount_data, err);
    if (mount_data)
        free(mount_data);
    return ret;
}
References __OCI_MOUNT_MAX, add_mount(), blobmsg_data(), blobmsg_get_string(), blobmsg_len(), blobmsg_parse(), err, OCI_MOUNT_DESTINATION, OCI_MOUNT_OPTIONS, oci_mount_policy, OCI_MOUNT_SOURCE, OCI_MOUNT_TYPE, and parseOCImountopts().
Referenced by parseOCI().