zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/jail/netifd.h File Reference
netifd.h File Reference
#include <libubus.h>
Functions
int jail_network_start (struct ubus_context *new_ctx, char *new_jail_name, pid_t new_ns_pid)
int jail_network_stop (void)
Function Documentation
jail_network_start()
int jail_network_start (struct ubus_context * new_ctx, char * new_jail_name, pid_t new_ns_pid)
Definition at line 434 of file netifd.c.
{
    ubus_pw = getpwnam("ubus");
    int ret = 0;
    int netns_fd;
    host_ubus_ctx = new_ctx;
    ns_pid = new_ns_pid;
    jail_name = new_jail_name;
    if (asprintf(&ubus_sock_dir, "/var/containers/ubus-%s", jail_name) == -1) {
        ret = ENOMEM;
        goto errout_dir;
    }
    if (asprintf(&ubus_sock_path, "%s/%s", ubus_sock_dir, ubus_sock_name) == -1) {
        ret = ENOMEM;
        goto errout_path;
    }
    mkdir_p(ubus_sock_dir, 0755);
    if (ubus_pw) {
        ret = chown(ubus_sock_dir, ubus_pw->pw_uid, ubus_pw->pw_gid);
        if (ret) {
            ret = errno;
            goto errout;
        }
    }
    fd_inotify_read.fd = inotify_init1(IN_NONBLOCK | IN_CLOEXEC);
    fd_inotify_read.cb = inotify_read_handler;
    if (fd_inotify_read.fd == -1) {
        ERROR("failed to initialize inotify handler\n");
        ret = EIO;
        goto errout;
    }
    uloop_fd_add(&fd_inotify_read, ULOOP_READ);
    inotify_buffer = calloc(1, INOTIFY_SZ);
    if (!inotify_buffer) {
        ret = ENOMEM;
        goto errout_inotify;
    }
    if (inotify_add_watch(fd_inotify_read.fd, ubus_sock_dir, IN_CREATE) == -1) {
        ERROR("failed to add inotify watch on %s\n", ubus_sock_dir);
        free(inotify_buffer);
        ret = EIO;
        goto errout_inotify;
    }
    watch_ubus_service();
    netns_fd = ns_open_pid("net", ns_pid);
    if (netns_fd < 0) {
        ret = ESRCH;
        goto errout_inotify;
    }
    netns_updown(host_ubus_ctx, jail_name, true, netns_fd);
    close(netns_fd);
    uloop_timeout_add(&ubus_start_timeout);
    uloop_run();
    return 0;
errout_inotify:
    close(fd_inotify_read.fd);
errout:
    free(ubus_sock_path);
errout_path:
    free(ubus_sock_dir);
errout_dir:
    return ret;
}
References uloop_fd::cb, ERROR, uloop_fd::fd, fd_inotify_read, host_ubus_ctx, inotify_buffer, inotify_read_handler(), INOTIFY_SZ, jail_name, mkdir_p(), netns_fd, netns_updown(), ns_open_pid(), ns_pid, ubus_pw, ubus_sock_dir, ubus_sock_name, ubus_sock_path, ubus_start_timeout, uloop_fd_add(), ULOOP_READ, uloop_run(), uloop_timeout_add(), and watch_ubus_service().
Referenced by post_main().
jail_network_stop()
int jail_network_stop (void)
Definition at line 526 of file netifd.c.
{
    int host_netns = open("/proc/self/ns/net", O_RDONLY);
    if (host_netns < 0)
        return errno;
    netns_updown(jail_ubus_ctx, NULL, false, host_netns);
    close(host_netns);
    ubus_free(jail_ubus_ctx);
    jail_delete_instance("netifd");
    jail_delete_instance("ubus");
    if (uci_config_network) {
        unlink(uci_config_network);
        rmdir(dirname(uci_config_network));
        free(uci_config_network);
    }
    free(ubus_sock_path);
    rmdir(ubus_sock_dir);
    free(ubus_sock_dir);
    return 0;
}
References jail_delete_instance(), jail_ubus_ctx, netns_updown(), ubus_free(), ubus_sock_dir, ubus_sock_path, and uci_config_network.
Referenced by poststop().