zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/netifd/interface.h File Reference
interface.h File Reference
#include "device.h"
#include "config.h"
Classes
struct interface_error
struct interface_user
struct interface_ip_settings
struct interface_data
struct interface_assignment_class
struct interface
Enumerations
enum interface_event {
IFEV_DOWN , IFEV_UP , IFEV_UP_FAILED , IFEV_UPDATE ,
IFEV_FREE , IFEV_RELOAD , IFEV_LINK_UP , IFEV_CREATE
}
enum interface_state { IFS_SETUP , IFS_UP , IFS_TEARDOWN , IFS_DOWN }
enum interface_config_state { IFC_NORMAL , IFC_RELOAD , IFC_REMOVE }
enum interface_id_selection_type { IFID_FIXED , IFID_RANDOM , IFID_EUI64 }
enum interface_update_flags { IUF_ADDRESS = (1 << 0) , IUF_ROUTE = (1 << 1) , IUF_PREFIX = (1 << 2) , IUF_DATA = (1 << 3) }
Functions
struct interface * interface_alloc (const char *name, struct blob_attr *config, bool dynamic)
bool interface_add (struct interface *iface, struct blob_attr *config)
bool interface_add_alias (struct interface *iface, struct blob_attr *config)
void interface_set_proto_state (struct interface *iface, struct interface_proto_state *state)
void interface_set_available (struct interface *iface, bool new_state)
void interface_set_up (struct interface *iface)
void interface_set_down (struct interface *iface)
int interface_renew (struct interface *iface)
void interface_set_l3_dev (struct interface *iface, struct device *dev)
void interface_add_user (struct interface_user *dep, struct interface *iface)
void interface_remove_user (struct interface_user *dep)
int interface_handle_link (struct interface *iface, const char *name, struct blob_attr *vlan, bool add, bool link_ext)
void interface_add_error (struct interface *iface, const char *subsystem, const char *code, const char **data, int n_data)
int interface_add_data (struct interface *iface, const struct blob_attr *data)
int interface_parse_data (struct interface *iface, const struct blob_attr *attr)
void interface_update_start (struct interface *iface, const bool keep_old)
void interface_update_complete (struct interface *iface)
void interface_start_pending (void)
void interface_start_jail (int netns_fd, const char *jail)
void interface_stop_jail (int netns_fd)
Variables
struct vlist_tree interfaces
const struct uci_blob_param_list interface_attr_list
Class Documentation
interface_error
struct interface_error
Definition at line 61 of file interface.h.
Class Members
const char * code
const char * data[]
struct list_head list
const char * subsystem
interface_user
struct interface_user
Definition at line 69 of file interface.h.
Class Members
void(*)(struct interface_user *dep, struct interface *iface, enum interface_event ev) cb
struct interface * iface
struct list_head list
interface_ip_settings
struct interface_ip_settings
Definition at line 75 of file interface.h.
Class Members
struct vlist_tree addr
struct vlist_simple_tree dns_search
struct vlist_simple_tree dns_servers
bool enabled
struct interface * iface
struct vlist_tree neighbor
bool no_defaultroute
bool no_delegation
bool no_dns
struct vlist_tree prefix
struct vlist_tree route
interface_data
struct interface_data
Definition at line 91 of file interface.h.
Class Members
struct blob_attr data[]
struct avl_node node
interface_assignment_class
struct interface_assignment_class
Definition at line 96 of file interface.h.
Class Members
struct list_head head
char name[]
interface
struct interface
Definition at line 104 of file interface.h.
Class Members
struct list_head assignment_classes
struct in6_addr assignment_fixed_iface_id
int32_t assignment_hint
enum interface_id_selection_type assignment_iface_id_selection
uint8_t assignment_length
int assignment_weight
bool autostart
bool available
struct blob_attr * config
bool config_autostart
struct interface_ip_settings config_ip
enum interface_config_state config_state
struct avl_tree data
const char * device
bool device_config
int dns_metric
bool dynamic
bool enabled
struct list_head errors
struct device_user ext_dev
bool force_link
char * host_device
struct vlist_tree host_neighbors
struct vlist_tree host_routes
enum interface_event hotplug_ev
struct list_head hotplug_list
unsigned int ip4table
unsigned int ip6table
char * jail
char * jail_device
struct device_user l3_dev
bool link_state
bool link_up_event
struct device_user main_dev
int metric
const char * name
int netns_fd
struct vlist_node node
struct interface_user parent_iface
const char * parent_ifname
bool policy_rules_set
struct interface_proto_state * proto
const struct proto_handler * proto_handler
struct interface_ip_settings proto_ip
struct uloop_timeout remove_timer
bool renew
time_t start_time
enum interface_state state
struct ubus_object ubus
enum interface_update_flags updated
struct list_head users
const char * zone
Enumeration Type Documentation
interface_config_state
enum interface_config_state
Enumerator
IFC_NORMAL
IFC_RELOAD
IFC_REMOVE
Definition at line 42 of file interface.h.
{
    IFC_NORMAL,
    IFC_RELOAD,
    IFC_REMOVE
};
interface_event
enum interface_event
Enumerator
IFEV_DOWN
IFEV_UP
IFEV_UP_FAILED
IFEV_UPDATE
IFEV_FREE
IFEV_RELOAD
IFEV_LINK_UP
IFEV_CREATE
Definition at line 23 of file interface.h.
                     {
    IFEV_DOWN,
    IFEV_UP,
    IFEV_UP_FAILED,
    IFEV_UPDATE,
    IFEV_FREE,
    IFEV_RELOAD,
    IFEV_LINK_UP,
    /* send when a new interface created. This is before proto handlers has been attached. */
    IFEV_CREATE,
};
interface_id_selection_type
enum interface_id_selection_type
Enumerator
IFID_FIXED
IFID_RANDOM
IFID_EUI64
Definition at line 48 of file interface.h.
{
    IFID_FIXED,
    IFID_RANDOM,
    IFID_EUI64
};
interface_state
enum interface_state
Enumerator
IFS_SETUP
IFS_UP
IFS_TEARDOWN
IFS_DOWN
Definition at line 35 of file interface.h.
                     {
    IFS_SETUP,
    IFS_UP,
    IFS_TEARDOWN,
    IFS_DOWN,
};
interface_update_flags
enum interface_update_flags
Enumerator
IUF_ADDRESS (1 << 0)
IUF_ROUTE (1 << 1)
IUF_PREFIX (1 << 2)
IUF_DATA (1 << 3)
Definition at line 54 of file interface.h.
{
    IUF_ADDRESS = (1 << 0),
    IUF_ROUTE   = (1 << 1),
    IUF_PREFIX  = (1 << 2),
    IUF_DATA    = (1 << 3),
};
Function Documentation
interface_add()
bool interface_add (struct interface * iface, struct blob_attr * config)
Definition at line 996 of file interface.c.
{
    return __interface_add(iface, config, false);
}
References __interface_add(), and config.
Referenced by config_parse_interface(), and netifd_add_dynamic().
interface_add_alias()
bool interface_add_alias (struct interface * iface, struct blob_attr * config)
Definition at line 1002 of file interface.c.
{
    if (iface->proto_handler->flags & PROTO_FLAG_NODEV)
        return false;
    return __interface_add(iface, config, true);
}
References __interface_add(), config, proto_handler::flags, PROTO_FLAG_NODEV, and interface::proto_handler.
Referenced by config_parse_interface().
interface_add_data()
int interface_add_data (struct interface * iface, const struct blob_attr * data)
Definition at line 205 of file interface.c.
{
    struct interface_data *n, *o;
    if (!blobmsg_check_attr(data, true))
        return UBUS_STATUS_INVALID_ARGUMENT;
    const char *name = blobmsg_name(data);
    unsigned len = blob_pad_len(data);
    o = avl_find_element(&iface->data, name, o, node);
    if (o) {
        if (blob_pad_len(o->data) == len && !memcmp(o->data, data, len))
            return 0;
        interface_data_del(iface, o);
    }
    n = calloc(1, sizeof(*n) + len);
    if (!n)
        return UBUS_STATUS_UNKNOWN_ERROR;
    memcpy(n->data, data, len);
    n->node.key = blobmsg_name(n->data);
    avl_insert(&iface->data, &n->node);
    iface->updated |= IUF_DATA;
    return 0;
}
References avl_find_element, avl_insert(), blob_pad_len(), blobmsg_check_attr(), blobmsg_name(), interface::data, interface_data::data, interface_data_del(), IUF_DATA, avl_node::key, interface_data::node, UBUS_STATUS_INVALID_ARGUMENT, UBUS_STATUS_UNKNOWN_ERROR, and interface::updated.
Referenced by interface_parse_data(), and proto_shell_parse_data().
interface_add_error()
void interface_add_error (struct interface * iface, const char * subsystem, const char * code, const char ** data, int n_data)
Definition at line 135 of file interface.c.
{
    struct interface_error *error;
    int i, len = 0;
    int *datalen = NULL;
    char *dest, *d_subsys, *d_code;
    /* if the configured protocol handler has the last error support capability,
           errors should only be added if the running protocol handler matches the
           configured one */
    if (iface->proto &&
        (iface->proto->handler->flags & PROTO_FLAG_LASTERROR) &&
        (iface->proto->handler->name != iface->proto_handler->name))
        return;
    if (n_data) {
        len = n_data * sizeof(char *);
        datalen = alloca(len);
        for (i = 0; i < n_data; i++) {
            datalen[i] = strlen(data[i]) + 1;
            len += datalen[i];
        }
    }
    error = calloc_a(sizeof(*error) + sizeof(char *) + len,
        &d_subsys, subsystem ? strlen(subsystem) + 1 : 0,
        &d_code, code ? strlen(code) + 1 : 0);
    if (!error)
        return;
    /* Only keep the last flagged error, prevent this list grows unlimitted in case the
       protocol can't be established (e.g auth failure) */
    if (iface->proto_handler->flags & PROTO_FLAG_LASTERROR)
        interface_error_flush(iface);
    list_add_tail(&error->list, &iface->errors);
    dest = (char *) &error->data[n_data + 1];
    for (i = 0; i < n_data; i++) {
        error->data[i] = dest;
        memcpy(dest, data[i], datalen[i]);
        dest += datalen[i];
    }
    error->data[n_data] = NULL;
    if (subsystem)
        error->subsystem = strcpy(d_subsys, subsystem);
    if (code)
        error->code = strcpy(d_code, code);
}
References calloc_a, interface_error::code, interface_error::data, interface::errors, proto_handler::flags, interface_proto_state::handler, interface_error_flush(), interface_error::list, list_add_tail(), proto_handler::name, interface::proto, PROTO_FLAG_LASTERROR, interface::proto_handler, and interface_error::subsystem.
Referenced by interface_set_up(), parse_gateway_option(), parse_static_address_option(), proto_apply_static_ip_settings(), proto_attach_interface(), and proto_shell_notify_error().
interface_add_user()
void interface_add_user (struct interface_user * dep, struct interface * iface)
Definition at line 501 of file interface.c.
{
    if (!iface) {
        list_add(&dep->list, &iface_all_users);
        return;
    }
    dep->iface = iface;
    list_add(&dep->list, &iface->users);
    if (iface->state == IFS_UP)
        dep->cb(dep, iface, IFEV_UP);
}
References interface_user::cb, interface_user::iface, IFEV_UP, IFS_UP, interface_user::list, list_add(), interface::state, and interface::users.
Referenced by generic_interface_cb(), interface_claim_device(), interface_event_init(), iprule_init_list(), proto_shell_add_host_dependency(), proto_shell_if_down_cb(), proto_shell_update_host_dep(), and register_interfaces().
interface_alloc()
struct interface * interface_alloc (const char * name, struct blob_attr * config, bool dynamic)
Definition at line 818 of file interface.c.
{
    struct interface *iface;
    struct blob_attr *tb[IFACE_ATTR_MAX];
    struct blob_attr *cur;
    const char *proto_name = NULL;
    char *iface_name;
    bool force_link = false;
    iface = calloc_a(sizeof(*iface), &iface_name, strlen(name) + 1);
    iface->name = strcpy(iface_name, name);
    INIT_LIST_HEAD(&iface->errors);
    INIT_LIST_HEAD(&iface->users);
    INIT_LIST_HEAD(&iface->hotplug_list);
    INIT_LIST_HEAD(&iface->assignment_classes);
    interface_ip_init(iface);
    avl_init(&iface->data, avl_strcmp, false, NULL);
    iface->config_ip.enabled = false;
    iface->main_dev.cb = interface_main_dev_cb;
    iface->l3_dev.cb = interface_l3_dev_cb;
    iface->ext_dev.cb = interface_ext_dev_cb;
    blobmsg_parse(iface_attrs, IFACE_ATTR_MAX, tb,
              blob_data(config), blob_len(config));
    iface->zone = NULL;
    if ((cur = tb[IFACE_ATTR_ZONE]))
        iface->zone = strdup(blobmsg_get_string(cur));
    if ((cur = tb[IFACE_ATTR_PROTO]))
        proto_name = blobmsg_data(cur);
    proto_attach_interface(iface, proto_name);
    if (iface->proto_handler->flags & PROTO_FLAG_FORCE_LINK_DEFAULT)
        force_link = true;
    iface->autostart = blobmsg_get_bool_default(tb[IFACE_ATTR_AUTO], true);
    iface->renew = blobmsg_get_bool_default(tb[IFACE_ATTR_RENEW], true);
    iface->force_link = blobmsg_get_bool_default(tb[IFACE_ATTR_FORCE_LINK], force_link);
    iface->dynamic = dynamic;
    iface->proto_ip.no_defaultroute =
        !blobmsg_get_bool_default(tb[IFACE_ATTR_DEFAULTROUTE], true);
    iface->proto_ip.no_dns =
        !blobmsg_get_bool_default(tb[IFACE_ATTR_PEERDNS], true);
    if ((cur = tb[IFACE_ATTR_DNS]))
        interface_add_dns_server_list(&iface->config_ip, cur);
    if ((cur = tb[IFACE_ATTR_DNS_SEARCH]))
        interface_add_dns_search_list(&iface->config_ip, cur);
    if ((cur = tb[IFACE_ATTR_DNS_METRIC]))
        iface->dns_metric = blobmsg_get_u32(cur);
    if ((cur = tb[IFACE_ATTR_METRIC]))
        iface->metric = blobmsg_get_u32(cur);
    if ((cur = tb[IFACE_ATTR_IP6ASSIGN]))
        iface->assignment_length = blobmsg_get_u32(cur);
    /* defaults */
    iface->assignment_iface_id_selection = IFID_FIXED;
    iface->assignment_fixed_iface_id = in6addr_any;
    iface->assignment_fixed_iface_id.s6_addr[15] = 1;
    if ((cur = tb[IFACE_ATTR_IP6IFACEID])) {
        const char *ifaceid = blobmsg_data(cur);
        if (!strcmp(ifaceid, "random")) {
            iface->assignment_iface_id_selection = IFID_RANDOM;
        }
        else if (!strcmp(ifaceid, "eui64")) {
            iface->assignment_iface_id_selection = IFID_EUI64;
        }
        else {
            /* we expect an IPv6 address with network id zero here -> fixed iface id
               if we cannot parse -> revert to iface id 1 */
            if (inet_pton(AF_INET6,ifaceid,&iface->assignment_fixed_iface_id) != 1 ||
                    iface->assignment_fixed_iface_id.s6_addr32[0] != 0 ||
                    iface->assignment_fixed_iface_id.s6_addr32[1] != 0) {
                iface->assignment_fixed_iface_id = in6addr_any;
                iface->assignment_fixed_iface_id.s6_addr[15] = 1;
                netifd_log_message(L_WARNING, "Failed to parse ip6ifaceid for interface '%s', \
                            falling back to iface id 1.\n", iface->name);
            }
        }
    }
    iface->assignment_hint = -1;
    if ((cur = tb[IFACE_ATTR_IP6HINT]))
        iface->assignment_hint = strtol(blobmsg_get_string(cur), NULL, 16) &
                ~((1 << (64 - iface->assignment_length)) - 1);
    if ((cur = tb[IFACE_ATTR_IP6CLASS]))
        interface_add_assignment_classes(iface, cur);
    if ((cur = tb[IFACE_ATTR_IP6WEIGHT]))
        iface->assignment_weight = blobmsg_get_u32(cur);
    if ((cur = tb[IFACE_ATTR_IP4TABLE])) {
        if (!system_resolve_rt_table(blobmsg_data(cur), &iface->ip4table))
            D(INTERFACE, "Failed to resolve routing table: %s", (char *) blobmsg_data(cur));
    }
    if ((cur = tb[IFACE_ATTR_IP6TABLE])) {
        if (!system_resolve_rt_table(blobmsg_data(cur), &iface->ip6table))
            D(INTERFACE, "Failed to resolve routing table: %s", (char *) blobmsg_data(cur));
    }
    iface->proto_ip.no_delegation = !blobmsg_get_bool_default(tb[IFACE_ATTR_DELEGATE], true);
    iface->config_autostart = iface->autostart;
    iface->jail = NULL;
    if ((cur = tb[IFACE_ATTR_JAIL])) {
        iface->jail = strdup(blobmsg_get_string(cur));
        iface->autostart = false;
    }
    iface->jail_device = NULL;
    if ((cur = tb[IFACE_ATTR_JAIL_DEVICE]))
        iface->jail_device = strdup(blobmsg_get_string(cur));
    else if ((cur = tb[IFACE_ATTR_JAIL_IFNAME]))
        iface->jail_device = strdup(blobmsg_get_string(cur));
    iface->host_device = NULL;
    if ((cur = tb[IFACE_ATTR_HOST_DEVICE]))
        iface->host_device = strdup(blobmsg_get_string(cur));
    return iface;
}
References interface::assignment_classes, interface::assignment_fixed_iface_id, interface::assignment_hint, interface::assignment_iface_id_selection, interface::assignment_length, interface::assignment_weight, interface::autostart, avl_init(), avl_strcmp(), blob_data(), blob_len(), blobmsg_data(), blobmsg_get_bool_default(), blobmsg_get_string(), blobmsg_get_u32(), blobmsg_parse(), calloc_a, device_user::cb, config, interface::config_autostart, interface::config_ip, D, interface::data, interface::dns_metric, interface::dynamic, interface_ip_settings::enabled, interface::errors, interface::ext_dev, proto_handler::flags, interface::force_link, interface::host_device, interface::hotplug_list, IFACE_ATTR_AUTO, IFACE_ATTR_DEFAULTROUTE, IFACE_ATTR_DELEGATE, IFACE_ATTR_DNS, IFACE_ATTR_DNS_METRIC, IFACE_ATTR_DNS_SEARCH, IFACE_ATTR_FORCE_LINK, IFACE_ATTR_HOST_DEVICE, IFACE_ATTR_IP4TABLE, IFACE_ATTR_IP6ASSIGN, IFACE_ATTR_IP6CLASS, IFACE_ATTR_IP6HINT, IFACE_ATTR_IP6IFACEID, IFACE_ATTR_IP6TABLE, IFACE_ATTR_IP6WEIGHT, IFACE_ATTR_JAIL, IFACE_ATTR_JAIL_DEVICE, IFACE_ATTR_JAIL_IFNAME, IFACE_ATTR_MAX, IFACE_ATTR_METRIC, IFACE_ATTR_PEERDNS, IFACE_ATTR_PROTO, IFACE_ATTR_RENEW, IFACE_ATTR_ZONE, iface_attrs, IFID_EUI64, IFID_FIXED, IFID_RANDOM, INIT_LIST_HEAD(), interface_add_assignment_classes(), interface_add_dns_search_list(), interface_add_dns_server_list(), interface_ext_dev_cb(), interface_ip_init(), interface_l3_dev_cb(), interface_main_dev_cb(), interface::ip4table, interface::ip6table, interface::jail, interface::jail_device, interface::l3_dev, L_WARNING, interface::main_dev, interface::metric, interface::name, netifd_log_message(), interface_ip_settings::no_defaultroute, interface_ip_settings::no_delegation, interface_ip_settings::no_dns, proto_attach_interface(), PROTO_FLAG_FORCE_LINK_DEFAULT, interface::proto_handler, interface::proto_ip, interface::renew, system_resolve_rt_table(), interface::users, and interface::zone.
Referenced by config_parse_interface(), and netifd_add_dynamic().
interface_handle_link()
int interface_handle_link (struct interface * iface, const char * name, struct blob_attr * vlan, bool add, bool link_ext)
Definition at line 1114 of file interface.c.
{
    struct device *dev;
    dev = device_get(name, add ? (link_ext ? 2 : 1) : 0);
    if (!dev)
        return UBUS_STATUS_NOT_FOUND;
    if (!add)
        return interface_remove_link(iface, dev, vlan);
    interface_set_device_config(iface, dev);
    if (!link_ext)
        device_set_present(dev, true);
    return interface_add_link(iface, dev, vlan, link_ext);
}
References device_get(), device_set_present, interface_add_link(), interface_remove_link(), interface_set_device_config(), and UBUS_STATUS_NOT_FOUND.
Referenced by netifd_iface_handle_device(), wireless_interface_handle_link(), and wireless_vlan_handle_link().
interface_parse_data()
int interface_parse_data (struct interface * iface, const struct blob_attr * attr)
Definition at line 235 of file interface.c.
{
    struct blob_attr *cur;
    size_t rem;
    int ret;
    iface->updated = 0;
    blob_for_each_attr(cur, attr, rem) {
        ret = interface_add_data(iface, cur);
        if (ret)
            return ret;
    }
    if (iface->updated && iface->state == IFS_UP)
        interface_event(iface, IFEV_UPDATE);
    return 0;
}
References blob_for_each_attr, IFEV_UPDATE, IFS_UP, interface_add_data(), interface::state, and interface::updated.
Referenced by netifd_handle_set_data().
interface_remove_user()
void interface_remove_user (struct interface_user * dep)
Definition at line 515 of file interface.c.
{
    list_del_init(&dep->list);
    dep->iface = NULL;
}
References interface_user::iface, interface_user::list, and list_del_init().
Referenced by deregister_interfaces(), interface_alias_cb(), interface_change_config(), interface_claim_device(), interface_cleanup(), proto_shell_clear_host_dep(), proto_shell_if_down_cb(), and proto_shell_update_host_dep().
interface_renew()
int interface_renew (struct interface * iface)
Definition at line 1179 of file interface.c.
{
    if (iface->state == IFS_TEARDOWN || iface->state == IFS_DOWN)
        return -1;
    return interface_proto_event(iface->proto, PROTO_CMD_RENEW, false);
}
References IFS_DOWN, IFS_TEARDOWN, interface::proto, PROTO_CMD_RENEW, and interface::state.
Referenced by netifd_handle_renew().
interface_set_available()
void interface_set_available (struct interface * iface, bool new_state)
Definition at line 485 of file interface.c.
{
    if (iface->available == new_state)
        return;
    D(INTERFACE, "Interface '%s', available=%d", iface->name, new_state);
    iface->available = new_state;
    if (new_state) {
        if (iface->autostart && !config_init)
            interface_set_up(iface);
    } else
        __interface_set_down(iface, true);
}
References __interface_set_down(), interface::autostart, interface::available, config_init, D, interface_set_up(), and interface::name.
Referenced by interface_add_link(), interface_alias_cb(), interface_claim_device(), interface_cleanup_state(), interface_main_dev_cb(), interface_set_main_dev(), proto_shell_check_dependencies(), and proto_shell_set_available().
interface_set_down()
void interface_set_down (struct interface * iface)
Definition at line 1166 of file interface.c.
{
    if (!iface) {
        vlist_for_each_element(&interfaces, iface, node)
            __interface_set_down(iface, false);
    } else {
        iface->autostart = false;
        wireless_check_network_enabled();
        __interface_set_down(iface, false);
    }
}
References __interface_set_down(), interface::autostart, interfaces, vlist_for_each_element, and wireless_check_network_enabled().
Referenced by interface_stop_jail(), netifd_handle_down(), and netifd_restart().
interface_set_l3_dev()
void interface_set_l3_dev (struct interface * iface, struct device * dev)
Definition at line 1011 of file interface.c.
{
    bool enabled = iface->config_ip.enabled;
    bool claimed = iface->l3_dev.claimed;
    if (iface->l3_dev.dev == dev)
        return;
    interface_ip_set_enabled(&iface->config_ip, false);
    interface_ip_set_enabled(&iface->proto_ip, false);
    interface_ip_flush(&iface->proto_ip);
    device_add_user(&iface->l3_dev, dev);
    if (dev) {
        if (claimed) {
            if (device_claim(&iface->l3_dev) < 0)
                return;
        }
        interface_ip_set_enabled(&iface->config_ip, enabled);
        interface_ip_set_enabled(&iface->proto_ip, enabled);
    }
}
References device_user::claimed, interface::config_ip, device_user::dev, device_add_user(), device_claim(), interface_ip_settings::enabled, interface_ip_flush(), interface_ip_set_enabled(), interface::l3_dev, and interface::proto_ip.
Referenced by interface_cleanup_state(), interface_proto_event_cb(), interface_set_main_dev(), proto_shell_update_link(), and static_proto_setup().
interface_set_proto_state()
void interface_set_proto_state (struct interface * iface, struct interface_proto_state * state)
Definition at line 802 of file interface.c.
{
    if (iface->proto) {
        iface->proto->free(iface->proto);
        iface->proto = NULL;
    }
    iface->state = IFS_DOWN;
    iface->proto = state;
    if (!state)
        return;
    state->proto_event = interface_proto_event_cb;
    state->iface = iface;
}
References interface_proto_state::free, IFS_DOWN, interface_proto_event_cb(), interface::proto, interface_proto_state::proto_event, interface::state, and state.
Referenced by interface_cleanup_state(), and proto_init_interface().
interface_set_up()
void interface_set_up (struct interface * iface)
Definition at line 1134 of file interface.c.
{
    int ret;
    const char *error = NULL;
    iface->autostart = true;
    wireless_check_network_enabled();
    if (iface->state != IFS_DOWN)
        return;
    interface_clear_errors(iface);
    if (iface->available) {
        if (iface->main_dev.dev) {
            ret = device_claim(&iface->main_dev);
            if (!ret)
                interface_check_state(iface);
            else
                error = "DEVICE_CLAIM_FAILED";
        } else {
            ret = __interface_set_up(iface);
            if (ret)
                error = "SETUP_FAILED";
        }
    } else
        error = "NO_DEVICE";
    if (error)
        interface_add_error(iface, "interface", error, NULL, 0);
}
References __interface_set_up(), interface::autostart, interface::available, device_user::dev, device_claim(), IFS_DOWN, interface_add_error(), interface_check_state(), interface_clear_errors(), interface::main_dev, interface::state, and wireless_check_network_enabled().
Referenced by interface_handle_config_change(), interface_set_available(), interface_start_pending(), and netifd_handle_up().
interface_start_jail()
void interface_start_jail (int netns_fd, const char * jail)
Definition at line 1199 of file interface.c.
{
    struct interface *iface;
    vlist_for_each_element(&interfaces, iface, node) {
        if (!iface->jail || strcmp(iface->jail, jail))
            continue;
        system_link_netns_move(iface->main_dev.dev, netns_fd, iface->jail_device);
    }
}
References device_user::dev, interfaces, interface::jail, interface::jail_device, interface::main_dev, netns_fd, system_link_netns_move(), and vlist_for_each_element.
Referenced by netifd_netns_updown().
interface_start_pending()
void interface_start_pending (void)
Definition at line 1188 of file interface.c.
{
    struct interface *iface;
    vlist_for_each_element(&interfaces, iface, node) {
        if (iface->autostart)
            interface_set_up(iface);
    }
}
References interface::autostart, interface_set_up(), interfaces, and vlist_for_each_element.
Referenced by config_init_all().
interface_stop_jail()
void interface_stop_jail (int netns_fd)
Definition at line 1212 of file interface.c.
{
    struct interface *iface;
    char *orig_ifname;
    vlist_for_each_element(&interfaces, iface, node) {
        orig_ifname = iface->host_device;
        interface_set_down(iface);
        system_link_netns_move(iface->main_dev.dev, netns_fd, orig_ifname);
    }
}
References device_user::dev, interface::host_device, interface_set_down(), interfaces, interface::main_dev, netns_fd, system_link_netns_move(), and vlist_for_each_element.
Referenced by netifd_netns_updown().
interface_update_complete()
void interface_update_complete (struct interface * iface)
Definition at line 1244 of file interface.c.
{
    interface_ip_update_complete(&iface->proto_ip);
}
References interface_ip_update_complete(), and interface::proto_ip.
Referenced by proto_shell_update_link().
interface_update_start()
void interface_update_start (struct interface * iface, const bool keep_old)
Definition at line 1235 of file interface.c.
{
    iface->updated = 0;
    if (!keep_old)
        interface_ip_update_start(&iface->proto_ip);
}
References interface_ip_update_start(), interface::proto_ip, and interface::updated.
Referenced by proto_shell_update_link().
Variable Documentation
interface_attr_list
const struct uci_blob_param_list interface_attr_list extern
Definition at line 92 of file interface.c.
{
    .n_params = IFACE_ATTR_MAX,
    .params = iface_attrs,
};
Referenced by config_parse_interface().
interfaces
struct vlist_tree interfaces extern
Definition at line 30 of file interface.c.
Referenced by __interface_add(), __interface_write_dns_entries(), alias_check_state(), config_init_all(), config_init_ip(), interface_claim_device(), interface_do_free(), interface_init_list(), interface_ip_add_neighbor(), interface_ip_add_route(), interface_ip_add_target_route(), interface_ip_valid_until_handler(), interface_set_down(), interface_start_jail(), interface_start_pending(), interface_stop_jail(), interface_update_prefix(), interface_update_prefix_assignments(), netifd_add_host_route(), netifd_handle_dump(), netifd_handle_iface(), netifd_iface_do_remove(), proto_shell_update_host_dep(), register_interfaces(), system_add_ip_tunnel(), vif_config_add_bridge(), wireless_check_interface(), wireless_interface_handle_link(), and wireless_vlan_handle_link().