zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/jail/elf.h File Reference
elf.h File Reference
#include <libubox/avl.h>
#include <libubox/avl-cmp.h>
Classes
struct library
struct library_path
Functions
void alloc_library (const char *path, const char *name)
int elf_load_deps (const char *path, const char *map)
const char * find_lib (const char *file)
void init_library_search (void)
int lib_open (char **fullpath, const char *file)
void free_library_search (void)
Variables
struct avl_tree libraries
Class Documentation
library
struct library
Definition at line 19 of file elf.h.
Class Members
struct avl_node avl
char * name
char * path
library_path
struct library_path
Definition at line 25 of file elf.h.
Class Members
struct list_head list
char * path
Function Documentation
alloc_library()
void alloc_library (const char * path, const char * name)
Definition at line 56 of file elf.c.
{
    struct library *l;
    char *_name, *_path;
    l = calloc_a(sizeof(*l),
        &_path, strlen(path) + 1,
        &_name, strlen(name) + 1);
    if (!l)
        return;
    l->avl.key = l->name = strcpy(_name, name);
    l->path = strcpy(_path, path);
    avl_insert(&libraries, &l->avl);
    DEBUG("adding library %s (%s)\n", path, name);
}
References library::avl, avl_insert(), calloc_a, DEBUG, avl_node::key, libraries, library::name, library::path, and path.
Referenced by add_2paths_and_deps().
elf_load_deps()
int elf_load_deps (const char * path, const char * map)
Definition at line 233 of file elf.c.
{
    unsigned long dyn_offset, dyn_size;
    unsigned long load_offset, load_vaddr;
    unsigned long interp_offset;
    if (elf_find_section(map, PT_INTERP, &interp_offset, NULL, NULL) == 0) {
        add_path_and_deps(map+interp_offset, 1, -1, 0);
    }
    if (elf_find_section(map, PT_LOAD, &load_offset, NULL, &load_vaddr)) {
        DEBUG("failed to load the .load section from %s\n", path);
        return 0;
    }
    if (elf_find_section(map, PT_DYNAMIC, &dyn_offset, &dyn_size, NULL)) {
        DEBUG("failed to load the .dynamic section from %s\n", path);
        return 0;
    }
    int clazz = map[EI_CLASS];
    if (clazz == ELFCLASS32)
        return elf32_scan_dynamic(map, dyn_offset, dyn_size, load_vaddr - load_offset);
    else if (clazz == ELFCLASS64)
        return elf64_scan_dynamic(map, dyn_offset, dyn_size, load_vaddr - load_offset);
    ERROR("unknown elf format %d\n", clazz);
    return -1;
}
References add_path_and_deps(), DEBUG, elf32_scan_dynamic(), elf64_scan_dynamic(), elf_find_section(), ERROR, and path.
Referenced by add_2paths_and_deps().
find_lib()
const char * find_lib (const char * file)
Definition at line 94 of file elf.c.
{
    struct library *l;
    l = avl_find_element(&libraries, file, l, avl);
    if (!l)
        return NULL;
    return l->path;
}
References library::avl, avl_find_element, libraries, and library::path.
Referenced by build_envp().
free_library_search()
void free_library_search (void)
Definition at line 319 of file elf.c.
{
    struct library_path *p, *ptmp;
    struct library *l, *tmp;
    list_for_each_entry_safe(p, ptmp, &library_paths, list)
        free(p);
    avl_remove_all_elements(&libraries, l, avl, tmp)
        free(l);
}
References library::avl, avl_remove_all_elements, libraries, and list_for_each_entry_safe.
Referenced by free_opts().
init_library_search()
void init_library_search (void)
Definition at line 310 of file elf.c.
{
    avl_init(&libraries, avl_strcmp, false, NULL);
    alloc_library_path("/lib");
    alloc_library_path("/lib64");
    alloc_library_path("/usr/lib");
    load_ldso_conf("/etc/ld.so.conf");
}
References alloc_library_path(), avl_init(), avl_strcmp(), libraries, and load_ldso_conf().
Referenced by main().
lib_open()
int lib_open (char ** fullpath, const char * file)
Definition at line 74 of file elf.c.
{
    struct library_path *p;
    char path[PATH_MAX];
    int fd = -1;
    *fullpath = NULL;
    list_for_each_entry(p, &library_paths, list) {
        snprintf(path, sizeof(path), "%s/%s", p->path, file);
        fd = open(path, O_RDONLY|O_CLOEXEC);
        if (fd >= 0) {
            *fullpath = strdup(path);
            break;
        }
    }
    return fd;
}
References library_path::list, list_for_each_entry, library_path::path, and path.
Referenced by add_2paths_and_deps().
Variable Documentation
libraries
struct avl_tree libraries extern
Definition at line 29 of file elf.c.
Referenced by add_2paths_and_deps(), alloc_library(), find_lib(), free_library_search(), init_library_search(), and mount_all().