zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/ubus/libubus-req.c File Reference
libubus-req.c File Reference
#include <unistd.h>
#include "libubus.h"
#include "libubus-internal.h"
Classes
struct ubus_pending_data
Functions
static void req_data_cb (struct ubus_request *req, int type, struct blob_attr *data)
static void __ubus_process_req_data (struct ubus_request *req)
int __hidden __ubus_start_request (struct ubus_context *ctx, struct ubus_request *req, struct blob_attr *msg, int cmd, uint32_t peer)
int __hidden ubus_start_request (struct ubus_context *ctx, struct ubus_request *req, struct blob_attr *msg, int cmd, uint32_t peer)
void ubus_abort_request (struct ubus_context *ctx, struct ubus_request *req)
void ubus_complete_request_async (struct ubus_context *ctx, struct ubus_request *req)
static void ubus_req_complete_cb (struct ubus_request *req)
static void ubus_set_req_status (struct ubus_request *req, int ret)
static void ubus_sync_req_cb (struct ubus_request *req, int ret)
static int64_t get_time_msec (void)
int ubus_complete_request (struct ubus_context *ctx, struct ubus_request *req, int req_timeout)
void ubus_complete_deferred_request (struct ubus_context *ctx, struct ubus_request_data *req, int ret)
static void ubus_put_data (struct blob_buf *buf, struct blob_attr *msg)
int ubus_send_reply (struct ubus_context *ctx, struct ubus_request_data *req, struct blob_attr *msg)
int ubus_invoke_async_fd (struct ubus_context *ctx, uint32_t obj, const char *method, struct blob_attr *msg, struct ubus_request *req, int fd)
int ubus_invoke_fd (struct ubus_context *ctx, uint32_t obj, const char *method, struct blob_attr *msg, ubus_data_handler_t cb, void *priv, int timeout, int fd)
static void ubus_notify_complete_cb (struct ubus_request *req, int ret)
static void ubus_notify_data_cb (struct ubus_request *req, int type, struct blob_attr *msg)
static int __ubus_notify_async (struct ubus_context *ctx, struct ubus_object *obj, const char *type, struct blob_attr *msg, struct ubus_notify_request *req, bool reply)
int ubus_notify_async (struct ubus_context *ctx, struct ubus_object *obj, const char *type, struct blob_attr *msg, struct ubus_notify_request *req)
int ubus_notify (struct ubus_context *ctx, struct ubus_object *obj, const char *type, struct blob_attr *msg, int timeout)
static bool ubus_get_status (struct ubus_msghdr_buf *buf, int *ret)
static int ubus_process_req_status (struct ubus_request *req, struct ubus_msghdr_buf *buf)
static void ubus_process_req_data (struct ubus_request *req, struct ubus_msghdr_buf *buf)
static int ubus_find_notify_id (struct ubus_notify_request *n, uint32_t objid)
static struct ubus_request * ubus_find_request (struct ubus_context *ctx, uint32_t seq, uint32_t peer, int *id)
static void ubus_process_notify_status (struct ubus_request *req, int id, struct ubus_msghdr_buf *buf)
void __hidden ubus_process_req_msg (struct ubus_context *ctx, struct ubus_msghdr_buf *buf, int fd)
int __ubus_monitor (struct ubus_context *ctx, const char *type)
Class Documentation
ubus_pending_data
struct ubus_pending_data
Definition at line 18 of file libubus-req.c.
Class Members
struct blob_attr data[]
struct list_head list
int type
Function Documentation
__ubus_monitor()
int __ubus_monitor (struct ubus_context * ctx, const char * type)
Definition at line 495 of file libubus-req.c.
{
    blob_buf_init(&b, 0);
    return ubus_invoke(ctx, UBUS_SYSTEM_OBJECT_MONITOR, type, b.head, NULL, NULL, 1000);
}
References b, blob_buf_init(), ctx, blob_buf::head, type, ubus_invoke(), and UBUS_SYSTEM_OBJECT_MONITOR.
Referenced by ubus_monitor_start(), and ubus_monitor_stop().
__ubus_notify_async()
static int __ubus_notify_async (struct ubus_context * ctx, struct ubus_object * obj, const char * type, struct blob_attr * msg, struct ubus_notify_request * req, bool reply) static
Definition at line 277 of file libubus-req.c.
{
    memset(req, 0, sizeof(*req));
    blob_buf_init(&b, 0);
    blob_put_int32(&b, UBUS_ATTR_OBJID, obj->id);
    blob_put_string(&b, UBUS_ATTR_METHOD, type);
    ubus_put_data(&b, msg);
    if (!reply)
        blob_put_int8(&b, UBUS_ATTR_NO_REPLY, true);
    if (ubus_start_request(ctx, &req->req, b.head, UBUS_MSG_NOTIFY, obj->id) < 0)
        return UBUS_STATUS_INVALID_ARGUMENT;
    /* wait for status message from ubusd first */
    req->req.notify = true;
    req->pending = 1;
    req->id[0] = obj->id;
    req->req.complete_cb = ubus_notify_complete_cb;
    req->req.data_cb = ubus_notify_data_cb;
    return 0;
}
References b, blob_buf_init(), blob_put_int32, blob_put_int8, blob_put_string(), ubus_request::complete_cb, ctx, ubus_request::data_cb, blob_buf::head, ubus_object::id, ubus_request::notify, ubus_request::pending, ubus_notify_request::req, type, UBUS_ATTR_METHOD, UBUS_ATTR_NO_REPLY, UBUS_ATTR_OBJID, UBUS_MSG_NOTIFY, ubus_notify_complete_cb(), ubus_notify_data_cb(), ubus_put_data(), ubus_start_request(), and UBUS_STATUS_INVALID_ARGUMENT.
Referenced by ubus_notify(), and ubus_notify_async().
__ubus_process_req_data()
static void __ubus_process_req_data (struct ubus_request * req) static
Definition at line 41 of file libubus-req.c.
{
    struct ubus_pending_data *data, *tmp;
    list_for_each_entry_safe(data, tmp, &req->pending, list) {
        list_del(&data->list);
        if (!req->cancelled)
            req_data_cb(req, data->type, data->data);
        free(data);
    }
}
References ubus_request::cancelled, blob_attr::data, ubus_pending_data::data, ubus_pending_data::list, list_del(), list_for_each_entry_safe, ubus_request::pending, and req_data_cb().
Referenced by ubus_abort_request(), and ubus_process_req_data().
__ubus_start_request()
int __hidden __ubus_start_request (struct ubus_context * ctx, struct ubus_request * req, struct blob_attr * msg, int cmd, uint32_t peer)
Definition at line 53 of file libubus-req.c.
{
    if (msg && blob_pad_len(msg) > UBUS_MAX_MSGLEN)
        return -1;
    INIT_LIST_HEAD(&req->list);
    INIT_LIST_HEAD(&req->pending);
    req->ctx = ctx;
    req->peer = peer;
    req->seq = ++ctx->request_seq;
    return ubus_send_msg(ctx, req->seq, msg, cmd, peer, req->fd);
}
References blob_pad_len(), cmd, ctx, ubus_request::ctx, ubus_request::fd, INIT_LIST_HEAD(), ubus_request::list, ubus_request::peer, ubus_request::pending, ubus_context::request_seq, ubus_request::seq, and ubus_send_msg().
Referenced by ubus_invoke_async_fd(), and ubus_start_request().
get_time_msec()
static int64_t get_time_msec (void) static
Definition at line 129 of file libubus-req.c.
{
    struct timespec ts;
    int64_t val;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    val = (int64_t) ts.tv_sec * 1000LL;
    val += ts.tv_nsec / 1000000LL;
    return val;
}
Referenced by ubus_complete_request().
req_data_cb()
static void req_data_cb (struct ubus_request * req, int type, struct blob_attr * data) static
Definition at line 24 of file libubus-req.c.
{
    struct blob_attr **attr;
    if (req->raw_data_cb)
        req->raw_data_cb(req, type, data);
    if (!req->data_cb)
        return;
    attr = ubus_parse_msg(data, blob_raw_len(data));
    if (!attr[UBUS_ATTR_DATA])
        return;
    req->data_cb(req, type, attr[UBUS_ATTR_DATA]);
}
References blob_raw_len(), blob_attr::data, ubus_request::data_cb, ubus_request::raw_data_cb, type, UBUS_ATTR_DATA, and ubus_parse_msg().
Referenced by __ubus_process_req_data(), and ubus_process_req_data().
ubus_abort_request()
void ubus_abort_request (struct ubus_context * ctx, struct ubus_request * req)
Definition at line 80 of file libubus-req.c.
{
    if (list_empty(&req->list))
        return;
    req->cancelled = true;
    __ubus_process_req_data(req);
    list_del_init(&req->list);
}
References __ubus_process_req_data(), ubus_request::cancelled, ubus_request::list, list_del_init(), and list_empty().
Referenced by ubus_notify().
ubus_complete_deferred_request()
void ubus_complete_deferred_request (struct ubus_context * ctx, struct ubus_request_data * req, int ret)
Definition at line 189 of file libubus-req.c.
{
    blob_buf_init(&b, 0);
    blob_put_int32(&b, UBUS_ATTR_STATUS, ret);
    blob_put_int32(&b, UBUS_ATTR_OBJID, req->object);
    ubus_send_msg(ctx, req->seq, b.head, UBUS_MSG_STATUS, req->peer, req->fd);
}
References b, blob_buf_init(), blob_put_int32, ctx, ubus_request_data::fd, blob_buf::head, ubus_request_data::object, ubus_request_data::peer, ubus_request_data::seq, UBUS_ATTR_OBJID, UBUS_ATTR_STATUS, UBUS_MSG_STATUS, and ubus_send_msg().
Referenced by rc_init_cb(), rc_list_readdir(), rpc_exec_reply(), rpc_file_exec_reply(), rpc_ucode_request_finish(), rpc_ucode_script_call(), test_hello_reply(), ubus_lua_complete_deferred_request(), ubus_process_invoke(), and wireless_complete_kill_request().
ubus_complete_request()
int ubus_complete_request (struct ubus_context * ctx, struct ubus_request * req, int req_timeout)
Definition at line 140 of file libubus-req.c.
{
    ubus_complete_handler_t complete_cb = req->complete_cb;
    int status = UBUS_STATUS_NO_DATA;
    int64_t timeout = 0, time_end = 0;
    if (req_timeout)
        time_end = get_time_msec() + req_timeout;
    ubus_complete_request_async(ctx, req);
    req->complete_cb = ubus_sync_req_cb;
    ctx->stack_depth++;
    while (!req->status_msg) {
        if (req_timeout) {
            timeout = time_end - get_time_msec();
            if (timeout <= 0) {
                ubus_set_req_status(req, UBUS_STATUS_TIMEOUT);
                break;
            }
        }
        ubus_poll_data(ctx, (unsigned int) timeout);
        if (ctx->sock.eof) {
            ubus_set_req_status(req, UBUS_STATUS_CONNECTION_FAILED);
            ctx->cancel_poll = true;
            break;
        }
    }
    ctx->stack_depth--;
    if (ctx->stack_depth)
        ctx->cancel_poll = true;
    if (req->status_msg)
        status = req->status_code;
    req->complete_cb = complete_cb;
    if (req->complete_cb)
        req->complete_cb(req, status);
    if (!ctx->stack_depth && !ctx->sock.registered)
        ctx->pending_timer.cb(&ctx->pending_timer);
    return status;
}
References ubus_context::cancel_poll, uloop_timeout::cb, ubus_request::complete_cb, ctx, uloop_fd::eof, get_time_msec(), ubus_context::pending_timer, uloop_fd::registered, ubus_context::sock, ubus_context::stack_depth, ubus_request::status_code, ubus_request::status_msg, timeout, ubus_complete_request_async(), ubus_poll_data(), ubus_set_req_status(), UBUS_STATUS_CONNECTION_FAILED, UBUS_STATUS_NO_DATA, UBUS_STATUS_TIMEOUT, and ubus_sync_req_cb().
Referenced by __ubus_subscribe_request(), ubus_add_object(), ubus_invoke_fd(), ubus_lookup(), ubus_lookup_id(), ubus_notify(), ubus_remove_object(), and ubus_send_event().
ubus_complete_request_async()
void ubus_complete_request_async (struct ubus_context * ctx, struct ubus_request * req)
Definition at line 90 of file libubus-req.c.
{
    if (!list_empty(&req->list))
        return;
    list_add(&req->list, &ctx->requests);
}
References ctx, ubus_request::list, list_add(), list_empty(), and ubus_context::requests.
Referenced by acl_query(), client_main(), and ubus_complete_request().
ubus_find_notify_id()
static int ubus_find_notify_id (struct ubus_notify_request * n, uint32_t objid) static
Definition at line 381 of file libubus-req.c.
{
    uint32_t pending = n->pending;
    int i;
    for (i = 0; pending; i++, pending >>= 1) {
        if (!(pending & 1))
            continue;
        if (n->id[i] == objid)
            return i;
    }
    return -1;
}
References ubus_notify_request::id, pending, and ubus_notify_request::pending.
Referenced by ubus_find_request().
ubus_find_request()
static struct ubus_request * ubus_find_request (struct ubus_context * ctx, uint32_t seq, uint32_t peer, int * id) static
Definition at line 398 of file libubus-req.c.
{
    struct ubus_request *req;
    list_for_each_entry(req, &ctx->requests, list) {
        struct ubus_notify_request *nreq;
        nreq = container_of(req, struct ubus_notify_request, req);
        if (seq != req->seq)
            continue;
        if (req->notify) {
            if (!nreq->pending)
                continue;
            *id = ubus_find_notify_id(nreq, peer);
            if (*id < 0)
                continue;
        } else if (peer != req->peer)
            continue;
        return req;
    }
    return NULL;
}
References container_of, ctx, ubus_request::list, list_for_each_entry, ubus_request::notify, ubus_request::peer, ubus_notify_request::pending, ubus_notify_request::req, ubus_context::requests, ubus_request::seq, and ubus_find_notify_id().
Referenced by ubus_process_req_msg().
ubus_get_status()
static bool ubus_get_status (struct ubus_msghdr_buf * buf, int * ret) static
Definition at line 329 of file libubus-req.c.
{
    struct blob_attr **attrbuf = ubus_parse_msg(buf->data, blob_raw_len(buf->data));
    if (!attrbuf[UBUS_ATTR_STATUS])
        return false;
    *ret = blob_get_u32(attrbuf[UBUS_ATTR_STATUS]);
    return true;
}
References attrbuf, blob_get_u32(), blob_raw_len(), buf, UBUS_ATTR_STATUS, and ubus_parse_msg().
Referenced by ubus_process_notify_status(), and ubus_process_req_status().
ubus_invoke_async_fd()
int ubus_invoke_async_fd (struct ubus_context * ctx, uint32_t obj, const char * method, struct blob_attr * msg, struct ubus_request * req, int fd)
Definition at line 220 of file libubus-req.c.
{
    blob_buf_init(&b, 0);
    blob_put_int32(&b, UBUS_ATTR_OBJID, obj);
    blob_put_string(&b, UBUS_ATTR_METHOD, method);
    ubus_put_data(&b, msg);
    memset(req, 0, sizeof(*req));
    req->fd = fd;
    if (__ubus_start_request(ctx, req, b.head, UBUS_MSG_INVOKE, obj) < 0)
        return UBUS_STATUS_INVALID_ARGUMENT;
    return 0;
}
References __ubus_start_request(), b, blob_buf_init(), blob_put_int32, blob_put_string(), ctx, ubus_request::fd, blob_buf::head, UBUS_ATTR_METHOD, UBUS_ATTR_OBJID, UBUS_MSG_INVOKE, ubus_put_data(), and UBUS_STATUS_INVALID_ARGUMENT.
Referenced by ubus_invoke_async(), and ubus_invoke_fd().
ubus_invoke_fd()
int ubus_invoke_fd (struct ubus_context * ctx, uint32_t obj, const char * method, struct blob_attr * msg, ubus_data_handler_t cb, void * priv, int timeout, int fd)
Definition at line 236 of file libubus-req.c.
{
    struct ubus_request req;
    int rc;
    rc = ubus_invoke_async_fd(ctx, obj, method, msg, &req, fd);
    if (rc)
        return rc;
    req.data_cb = cb;
    req.priv = priv;
    return ubus_complete_request(ctx, &req, timeout);
}
References ctx, ubus_request::data_cb, ubus_request::fd, ubus_request::priv, rc(), timeout, ubus_complete_request(), and ubus_invoke_async_fd().
Referenced by netns_updown(), pass_console(), ubus_invoke(), and uxc_attach().
ubus_notify()
int ubus_notify (struct ubus_context * ctx, struct ubus_object * obj, const char * type, struct blob_attr * msg, int timeout)
Definition at line 311 of file libubus-req.c.
{
    struct ubus_notify_request req;
    int ret;
    ret = __ubus_notify_async(ctx, obj, type, msg, &req, timeout >= 0);
    if (ret < 0)
        return ret;
    if (timeout < 0) {
        ubus_abort_request(ctx, &req.req);
        return 0;
    }
    return ubus_complete_request(ctx, &req.req, timeout);
}
References __ubus_notify_async(), ctx, ubus_notify_request::req, timeout, type, ubus_abort_request(), and ubus_complete_request().
Referenced by netifd_ubus_device_notify(), netifd_ubus_interface_notify(), procd_bcast_event(), test_client_notify_cb(), ubus_event_bcast(), and ubus_lua_notify().
ubus_notify_async()
int ubus_notify_async (struct ubus_context * ctx, struct ubus_object * obj, const char * type, struct blob_attr * msg, struct ubus_notify_request * req)
Definition at line 304 of file libubus-req.c.
{
    return __ubus_notify_async(ctx, obj, type, msg, req, true);
}
References __ubus_notify_async(), ctx, ubus_notify_request::req, and type.
ubus_notify_complete_cb()
static void ubus_notify_complete_cb (struct ubus_request * req, int ret) static
Definition at line 253 of file libubus-req.c.
{
    struct ubus_notify_request *nreq;
    nreq = container_of(req, struct ubus_notify_request, req);
    if (!nreq->complete_cb)
        return;
    nreq->complete_cb(nreq, 0, 0);
}
References ubus_notify_request::complete_cb, container_of, and ubus_notify_request::req.
Referenced by __ubus_notify_async().
ubus_notify_data_cb()
static void ubus_notify_data_cb (struct ubus_request * req, int type, struct blob_attr * msg) static
Definition at line 265 of file libubus-req.c.
{
    struct ubus_notify_request *nreq;
    nreq = container_of(req, struct ubus_notify_request, req);
    if (!nreq->data_cb)
        return;
    nreq->data_cb(nreq, type, msg);
}
References container_of, ubus_notify_request::data_cb, ubus_notify_request::req, and type.
Referenced by __ubus_notify_async().
ubus_process_notify_status()
static void ubus_process_notify_status (struct ubus_request * req, int id, struct ubus_msghdr_buf * buf) static
Definition at line 424 of file libubus-req.c.
{
    struct ubus_notify_request *nreq;
    struct blob_attr **tb;
    struct blob_attr *cur;
    size_t rem;
    int idx = 1;
    int ret = 0;
    nreq = container_of(req, struct ubus_notify_request, req);
    nreq->pending &= ~(1 << id);
    if (!id) {
        /* first id: ubusd's status message with a list of ids */
        tb = ubus_parse_msg(buf->data, blob_raw_len(buf->data));
        if (tb[UBUS_ATTR_SUBSCRIBERS]) {
            blob_for_each_attr(cur, tb[UBUS_ATTR_SUBSCRIBERS], rem) {
                if (!blob_check_type(blob_data(cur), blob_len(cur), BLOB_ATTR_INT32))
                    continue;
                nreq->pending |= (1 << idx);
                nreq->id[idx] = blob_get_int32(cur);
                idx++;
                if (idx == UBUS_MAX_NOTIFY_PEERS + 1)
                    break;
            }
        }
    } else {
        ubus_get_status(buf, &ret);
        if (nreq->status_cb)
            nreq->status_cb(nreq, id, ret);
    }
    if (!nreq->pending)
        ubus_set_req_status(req, 0);
}
References BLOB_ATTR_INT32, blob_check_type(), blob_data(), blob_for_each_attr, blob_get_int32(), blob_len(), blob_raw_len(), buf, container_of, id, ubus_notify_request::id, ubus_notify_request::pending, ubus_notify_request::status_cb, UBUS_ATTR_SUBSCRIBERS, ubus_get_status(), UBUS_MAX_NOTIFY_PEERS, ubus_parse_msg(), and ubus_set_req_status().
Referenced by ubus_process_req_msg().
ubus_process_req_data()
static void ubus_process_req_data (struct ubus_request * req, struct ubus_msghdr_buf * buf) static
Definition at line 353 of file libubus-req.c.
{
    struct ubus_pending_data *data;
    int len;
    if (!req->blocked) {
        req->blocked = true;
        req_data_cb(req, buf->hdr.type, buf->data);
        __ubus_process_req_data(req);
        req->blocked = false;
        if (req->status_msg)
            ubus_req_complete_cb(req);
        return;
    }
    len = blob_raw_len(buf->data);
    data = calloc(1, sizeof(*data) + len);
    if (!data)
        return;
    data->type = buf->hdr.type;
    memcpy(data->data, buf->data, len);
    list_add(&data->list, &req->pending);
}
References __ubus_process_req_data(), blob_raw_len(), ubus_request::blocked, buf, blob_attr::data, ubus_pending_data::data, list_add(), ubus_request::pending, req_data_cb(), ubus_request::status_msg, and ubus_req_complete_cb().
Referenced by ubus_process_req_msg().
ubus_process_req_msg()
void __hidden ubus_process_req_msg (struct ubus_context * ctx, struct ubus_msghdr_buf * buf, int fd)
Definition at line 462 of file libubus-req.c.
{
    struct ubus_msghdr *hdr = &buf->hdr;
    struct ubus_request *req;
    int id = -1;
    switch(hdr->type) {
    case UBUS_MSG_STATUS:
        req = ubus_find_request(ctx, hdr->seq, hdr->peer, &id);
        if (!req)
            break;
        if (fd >= 0) {
            if (req->fd_cb)
                req->fd_cb(req, fd);
            else
                close(fd);
        }
        if (id >= 0)
            ubus_process_notify_status(req, id, buf);
        else
            ubus_process_req_status(req, buf);
        break;
    case UBUS_MSG_DATA:
        req = ubus_find_request(ctx, hdr->seq, hdr->peer, &id);
        if (req && (req->data_cb || req->raw_data_cb))
            ubus_process_req_data(req, buf);
        break;
    }
}
References buf, ctx, ubus_request::data_cb, ubus_request::fd, ubus_request::fd_cb, ubus_msghdr::peer, ubus_request::raw_data_cb, ubus_msghdr::seq, ubus_msghdr::type, ubus_find_request(), UBUS_MSG_DATA, UBUS_MSG_STATUS, ubus_process_notify_status(), ubus_process_req_data(), and ubus_process_req_status().
Referenced by ubus_process_msg().
ubus_process_req_status()
static int ubus_process_req_status (struct ubus_request * req, struct ubus_msghdr_buf * buf) static
Definition at line 341 of file libubus-req.c.
{
    int ret = UBUS_STATUS_INVALID_ARGUMENT;
    ubus_get_status(buf, &ret);
    req->peer = buf->hdr.peer;
    ubus_set_req_status(req, ret);
    return ret;
}
References buf, ubus_request::peer, ubus_get_status(), ubus_set_req_status(), and UBUS_STATUS_INVALID_ARGUMENT.
Referenced by ubus_process_req_msg().
ubus_put_data()
static void ubus_put_data (struct blob_buf * buf, struct blob_attr * msg) static
Definition at line 197 of file libubus-req.c.
{
    if (msg)
        blob_put(buf, UBUS_ATTR_DATA, blob_data(msg), blob_len(msg));
    else
        blob_put(buf, UBUS_ATTR_DATA, NULL, 0);
}
References blob_data(), blob_len(), blob_put(), buf, and UBUS_ATTR_DATA.
Referenced by __ubus_notify_async(), ubus_invoke_async_fd(), and ubus_send_reply().
ubus_req_complete_cb()
static void ubus_req_complete_cb (struct ubus_request * req) static
Definition at line 99 of file libubus-req.c.
{
    ubus_complete_handler_t cb = req->complete_cb;
    if (!cb)
        return;
    req->complete_cb = NULL;
    cb(req, req->status_code);
}
References ubus_request::complete_cb, and ubus_request::status_code.
Referenced by ubus_process_req_data(), and ubus_set_req_status().
ubus_send_reply()
int ubus_send_reply (struct ubus_context * ctx, struct ubus_request_data * req, struct blob_attr * msg)
Definition at line 205 of file libubus-req.c.
{
    int ret;
    blob_buf_init(&b, 0);
    blob_put_int32(&b, UBUS_ATTR_OBJID, req->object);
    ubus_put_data(&b, msg);
    ret = ubus_send_msg(ctx, req->seq, b.head, UBUS_MSG_DATA, req->peer, -1);
    if (ret < 0)
        return UBUS_STATUS_NO_DATA;
    return 0;
}
References b, blob_buf_init(), blob_put_int32, ctx, blob_buf::head, ubus_request_data::object, ubus_request_data::peer, ubus_request_data::seq, UBUS_ATTR_OBJID, UBUS_MSG_DATA, ubus_put_data(), ubus_send_msg(), and UBUS_STATUS_NO_DATA.
Referenced by container_handle_features(), handle_state(), netifd_add_host_route(), netifd_dev_status(), netifd_get_proto_handlers(), netifd_handle_dump(), netifd_handle_iface_prepare(), netifd_handle_status(), netifd_handle_wdev_get_validate(), netifd_handle_wdev_status(), rc_list_readdir(), rpc_exec_reply(), rpc_file_exec_reply(), rpc_file_list(), rpc_file_md5(), rpc_file_read(), rpc_file_stat(), rpc_handle_access(), rpc_handle_get(), rpc_iwinfo_assoclist(), rpc_iwinfo_countrylist(), rpc_iwinfo_devices(), rpc_iwinfo_freqlist(), rpc_iwinfo_info(), rpc_iwinfo_phyname(), rpc_iwinfo_scan(), rpc_iwinfo_survey(), rpc_iwinfo_txpowerlist(), rpc_session_dump(), rpc_sys_packagelist(), rpc_uci_add(), rpc_uci_changes(), rpc_uci_configs(), rpc_uci_getcommon(), rpc_ucode_request_finish(), rpc_ucode_script_call(), service_get_data(), service_handle_list(), service_handle_validate(), service_handle_watchdog(), system_board(), system_info(), sysupgrade_error(), test_count(), test_hello_reply(), ubus_lua_reply(), validate_firmware_image(), and watchdog_set().
ubus_set_req_status()
static void ubus_set_req_status (struct ubus_request * req, int ret) static
Definition at line 111 of file libubus-req.c.
{
    if (!list_empty(&req->list))
        list_del_init(&req->list);
    req->status_msg = true;
    req->status_code = ret;
    if (!req->blocked)
        ubus_req_complete_cb(req);
}
References ubus_request::blocked, ubus_request::list, list_del_init(), list_empty(), ubus_request::status_code, ubus_request::status_msg, and ubus_req_complete_cb().
Referenced by ubus_complete_request(), ubus_process_notify_status(), and ubus_process_req_status().
ubus_start_request()
int __hidden ubus_start_request (struct ubus_context * ctx, struct ubus_request * req, struct blob_attr * msg, int cmd, uint32_t peer)
Definition at line 69 of file libubus-req.c.
{
    memset(req, 0, sizeof(*req));
    req->fd = -1;
    return __ubus_start_request(ctx, req, msg, cmd, peer);
}
References __ubus_start_request(), cmd, ctx, and ubus_request::fd.
Referenced by __ubus_notify_async(), __ubus_subscribe_request(), ubus_add_object(), ubus_lookup(), ubus_lookup_id(), ubus_remove_object(), and ubus_send_event().
ubus_sync_req_cb()
static void ubus_sync_req_cb (struct ubus_request * req, int ret) static
Definition at line 122 of file libubus-req.c.
{
    req->status_msg = true;
    req->status_code = ret;
    req->ctx->cancel_poll = true;
}
References ubus_context::cancel_poll, ubus_request::ctx, ubus_request::status_code, and ubus_request::status_msg.
Referenced by ubus_complete_request().