zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/watchdog.c File Reference
watchdog.c File Reference
#include <linux/watchdog.h>
#include <sys/ioctl.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <libubox/uloop.h>
#include "procd.h"
#include "watchdog.h"
Macros
#define WDT_PATH "/dev/watchdog"
Functions
void watchdog_ping (void)
static void watchdog_timeout_cb (struct uloop_timeout *t)
static int watchdog_open (bool cloexec)
static void watchdog_close (bool with_release)
static int watchdog_set_drv_timeout (void)
static void watchdog_print_status (void)
void watchdog_set_magicclose (bool val)
bool watchdog_get_magicclose (void)
void watchdog_set_stopped (bool val)
bool watchdog_get_stopped (void)
int watchdog_timeout (int timeout)
int watchdog_frequency (int frequency)
char * watchdog_fd (void)
void watchdog_init (int preinit)
void watchdog_set_cloexec (bool val)
Variables
static struct uloop_timeout wdt_timeout
static int wdt_fd = -1
static int wdt_drv_timeout = 30
static int wdt_frequency = 5
static bool wdt_magicclose = false
Macro Definition Documentation
WDT_PATH
#define WDT_PATH "/dev/watchdog"
Definition at line 29 of file watchdog.c.
Referenced by watchdog_open().
Function Documentation
watchdog_close()
static void watchdog_close (bool with_release) static
Definition at line 74 of file watchdog.c.
{
    if (wdt_fd < 0)
        return;
    if (with_release) {
        if (write(wdt_fd, "V", 1) < 0)
            ERROR("WDT failed to write release: %m\n");
    }
    if (close(wdt_fd) == -1)
        ERROR("WDT failed to close watchdog: %m\n");
    wdt_fd = -1;
}
References ERROR, and wdt_fd.
Referenced by watchdog_set_stopped().
watchdog_fd()
char * watchdog_fd (void)
Definition at line 179 of file watchdog.c.
{
    static char fd_buf[12];
    if (wdt_fd < 0)
        return NULL;
    snprintf(fd_buf, sizeof(fd_buf), "%d", wdt_fd);
    return fd_buf;
}
References wdt_fd.
Referenced by spawn_procd(), sysupgrade_exec_upgraded(), and watchdog_set().
watchdog_frequency()
int watchdog_frequency (int frequency)
Definition at line 169 of file watchdog.c.
{
    if (frequency) {
        DEBUG(4, "Set watchdog frequency: %ds\n", frequency);
        wdt_frequency = frequency;
    }
    return wdt_frequency;
}
References DEBUG, and wdt_frequency.
Referenced by watchdog_set().
watchdog_get_magicclose()
bool watchdog_get_magicclose (void)
Definition at line 132 of file watchdog.c.
{
    return wdt_magicclose;
}
References wdt_magicclose.
Referenced by watchdog_set().
watchdog_get_stopped()
bool watchdog_get_stopped (void)
Definition at line 151 of file watchdog.c.
{
    return !wdt_timeout.pending;
}
References uloop_timeout::pending, and wdt_timeout.
Referenced by watchdog_set().
watchdog_init()
void watchdog_init (int preinit)
Definition at line 191 of file watchdog.c.
{
    wdt_timeout.cb = watchdog_timeout_cb;
    if (watchdog_open(!preinit) < 0)
        return;
    LOG("- watchdog -\n");
    watchdog_set_drv_timeout();
    watchdog_timeout_cb(&wdt_timeout);
    DEBUG(4, "Opened watchdog with timeout %ds\n", watchdog_timeout(0));
    watchdog_print_status();
}
References uloop_timeout::cb, DEBUG, LOG, preinit(), watchdog_open(), watchdog_print_status(), watchdog_set_drv_timeout(), watchdog_timeout(), watchdog_timeout_cb(), and wdt_timeout.
Referenced by main(), and state_enter().
watchdog_open()
static int watchdog_open (bool cloexec) static
Definition at line 50 of file watchdog.c.
{
    char *env = getenv("WDTFD");
    if (wdt_fd >= 0)
        return wdt_fd;
    if (env) {
        DEBUG(2, "Watchdog handover: fd=%s\n", env);
        wdt_fd = atoi(env);
        unsetenv("WDTFD");
    } else {
        wdt_fd = open(WDT_PATH, O_WRONLY);
    }
    if (wdt_fd < 0)
        return wdt_fd;
    if (cloexec)
        fcntl(wdt_fd, F_SETFD, fcntl(wdt_fd, F_GETFD) | FD_CLOEXEC);
    return wdt_fd;
}
References DEBUG, wdt_fd, and WDT_PATH.
Referenced by watchdog_init(), and watchdog_set_stopped().
watchdog_ping()
void watchdog_ping (void)
Definition at line 37 of file watchdog.c.
{
    DEBUG(4, "Ping\n");
    if (wdt_fd >= 0 && write(wdt_fd, "X", 1) < 0)
        ERROR("WDT failed to write: %m\n");
}
References DEBUG, ERROR, and wdt_fd.
Referenced by main(), and watchdog_timeout_cb().
watchdog_print_status()
static void watchdog_print_status (void) static
Definition at line 98 of file watchdog.c.
{
    struct watchdog_info wdt_info;
    int bootstatus;
    if (wdt_fd < 0)
        return;
    if (ioctl(wdt_fd, WDIOC_GETSUPPORT, &wdt_info)) {
        DEBUG(2, "Watchdog GETSUPPORT failed\n");
        return;
    }
    if (!(wdt_info.options & WDIOF_CARDRESET)) {
        DEBUG(2, "Watchdog does not have CARDRESET support\n");
        return;
    }
    if (ioctl(wdt_fd, WDIOC_GETBOOTSTATUS, &bootstatus)) {
        DEBUG(2, "Watchdog GETBOOTSTATUS failed\n");
        return;
    }
    if (bootstatus & WDIOF_CARDRESET)
        LOG("Watchdog has previously reset the system\n");
    else
        DEBUG(2, "Watchdog did not previously reset the system\n");
}
References DEBUG, LOG, and wdt_fd.
Referenced by watchdog_init().
watchdog_set_cloexec()
void watchdog_set_cloexec (bool val)
Definition at line 208 of file watchdog.c.
{
    if (wdt_fd < 0)
        return;
    int flags = fcntl(wdt_fd, F_GETFD);
    if (val)
        flags |= FD_CLOEXEC;
    else
        flags &= ~FD_CLOEXEC;
    fcntl(wdt_fd, F_SETFD,  flags);
}
References wdt_fd.
Referenced by sysupgrade_exec_upgraded().
watchdog_set_drv_timeout()
static int watchdog_set_drv_timeout (void) static
Definition at line 90 of file watchdog.c.
{
    if (wdt_fd < 0)
        return -1;
    return ioctl(wdt_fd, WDIOC_SETTIMEOUT, &wdt_drv_timeout);
}
References wdt_drv_timeout, and wdt_fd.
Referenced by watchdog_init(), watchdog_set_stopped(), and watchdog_timeout().
watchdog_set_magicclose()
void watchdog_set_magicclose (bool val)
Definition at line 127 of file watchdog.c.
{
    wdt_magicclose = val;
}
References wdt_magicclose.
Referenced by watchdog_set().
watchdog_set_stopped()
void watchdog_set_stopped (bool val)
Definition at line 137 of file watchdog.c.
{
    if (val) {
        uloop_timeout_cancel(&wdt_timeout);
        watchdog_close(wdt_magicclose);
    }
    else {
        watchdog_open(true);
        watchdog_set_drv_timeout();
        watchdog_timeout_cb(&wdt_timeout);
    }
}
References uloop_timeout_cancel(), watchdog_close(), watchdog_open(), watchdog_set_drv_timeout(), watchdog_timeout_cb(), wdt_magicclose, and wdt_timeout.
Referenced by watchdog_set().
watchdog_timeout()
int watchdog_timeout (int timeout)
Definition at line 156 of file watchdog.c.
{
    if (timeout) {
        DEBUG(4, "Set watchdog timeout: %ds\n", timeout);
        wdt_drv_timeout = timeout;
        if (wdt_fd >= 0)
            watchdog_set_drv_timeout();
    }
    return wdt_drv_timeout;
}
References DEBUG, timeout, watchdog_set_drv_timeout(), wdt_drv_timeout, and wdt_fd.
Referenced by watchdog_init(), and watchdog_set().
watchdog_timeout_cb()
static void watchdog_timeout_cb (struct uloop_timeout * t) static
Definition at line 44 of file watchdog.c.
{
    watchdog_ping();
    uloop_timeout_set(t, wdt_frequency * 1000);
}
References uloop_timeout_set(), watchdog_ping(), and wdt_frequency.
Referenced by watchdog_init(), and watchdog_set_stopped().
Variable Documentation
wdt_drv_timeout
int wdt_drv_timeout = 30 static
Definition at line 33 of file watchdog.c.
Referenced by watchdog_set_drv_timeout(), and watchdog_timeout().
wdt_fd
int wdt_fd = -1 static
Definition at line 32 of file watchdog.c.
Referenced by spawn_procd(), sysupgrade_exec_upgraded(), watchdog_close(), watchdog_fd(), watchdog_open(), watchdog_ping(), watchdog_print_status(), watchdog_set_cloexec(), watchdog_set_drv_timeout(), and watchdog_timeout().
wdt_frequency
int wdt_frequency = 5 static
Definition at line 34 of file watchdog.c.
Referenced by watchdog_frequency(), and watchdog_timeout_cb().
wdt_magicclose
bool wdt_magicclose = false static
Definition at line 35 of file watchdog.c.
Referenced by watchdog_get_magicclose(), watchdog_set_magicclose(), and watchdog_set_stopped().
wdt_timeout
struct uloop_timeout wdt_timeout static
Definition at line 31 of file watchdog.c.
Referenced by watchdog_get_stopped(), watchdog_init(), and watchdog_set_stopped().