zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/libubox/blobmsg.h File Reference
blobmsg.h File Reference
#include <stdarg.h>
#include "blob.h"
Classes
struct blobmsg_hdr
struct blobmsg_policy
Macros
#define BLOBMSG_ALIGN 2
#define BLOBMSG_PADDING(len)
#define blobmsg_for_each_attr(pos, attr, rem)
#define __blobmsg_for_each_attr(pos, attr, rem)
Enumerations
enum blobmsg_type {
BLOBMSG_TYPE_UNSPEC , BLOBMSG_TYPE_ARRAY , BLOBMSG_TYPE_TABLE , BLOBMSG_TYPE_STRING ,
BLOBMSG_TYPE_INT64 , BLOBMSG_TYPE_INT32 , BLOBMSG_TYPE_INT16 , BLOBMSG_TYPE_INT8 ,
BLOBMSG_TYPE_BOOL = BLOBMSG_TYPE_INT8 , BLOBMSG_TYPE_DOUBLE , __BLOBMSG_TYPE_LAST , BLOBMSG_TYPE_LAST = __BLOBMSG_TYPE_LAST - 1 ,
BLOBMSG_CAST_INT64 = __BLOBMSG_TYPE_LAST
}
Functions
static int blobmsg_hdrlen (unsigned int namelen)
static void blobmsg_clear_name (struct blob_attr *attr)
static const char * blobmsg_name (const struct blob_attr *attr)
static int blobmsg_type (const struct blob_attr *attr)
static uint16_t blobmsg_namelen (const struct blobmsg_hdr *hdr)
static void * blobmsg_data (const struct blob_attr *attr)
static size_t blobmsg_data_len (const struct blob_attr *attr)
static size_t blobmsg_len (const struct blob_attr *attr)
bool blobmsg_check_attr (const struct blob_attr *attr, bool name)
bool blobmsg_check_attr_len (const struct blob_attr *attr, bool name, size_t len)
bool blobmsg_check_attr_list (const struct blob_attr *attr, int type)
bool blobmsg_check_attr_list_len (const struct blob_attr *attr, int type, size_t len)
int blobmsg_check_array (const struct blob_attr *attr, int type)
int blobmsg_check_array_len (const struct blob_attr *attr, int type, size_t len)
int blobmsg_parse (const struct blobmsg_policy *policy, int policy_len, struct blob_attr **tb, void *data, unsigned int len)
int blobmsg_parse_array (const struct blobmsg_policy *policy, int policy_len, struct blob_attr **tb, void *data, unsigned int len)
int blobmsg_add_field (struct blob_buf *buf, int type, const char *name, const void *data, unsigned int len)
static int blobmsg_parse_attr (const struct blobmsg_policy *policy, int policy_len, struct blob_attr **tb, struct blob_attr *data)
static int blobmsg_parse_array_attr (const struct blobmsg_policy *policy, int policy_len, struct blob_attr **tb, struct blob_attr *data)
static int blobmsg_add_double (struct blob_buf *buf, const char *name, double val)
static int blobmsg_add_u8 (struct blob_buf *buf, const char *name, uint8_t val)
static int blobmsg_add_u16 (struct blob_buf *buf, const char *name, uint16_t val)
static int blobmsg_add_u32 (struct blob_buf *buf, const char *name, uint32_t val)
static int blobmsg_add_u64 (struct blob_buf *buf, const char *name, uint64_t val)
static int blobmsg_add_string (struct blob_buf *buf, const char *name, const char *string)
static int blobmsg_add_blob (struct blob_buf *buf, struct blob_attr *attr)
void * blobmsg_open_nested (struct blob_buf *buf, const char *name, bool array)
static void * blobmsg_open_array (struct blob_buf *buf, const char *name)
static void * blobmsg_open_table (struct blob_buf *buf, const char *name)
static void blobmsg_close_array (struct blob_buf *buf, void *cookie)
static void blobmsg_close_table (struct blob_buf *buf, void *cookie)
static int blobmsg_buf_init (struct blob_buf *buf)
static uint8_t blobmsg_get_u8 (struct blob_attr *attr)
static bool blobmsg_get_bool (struct blob_attr *attr)
static uint16_t blobmsg_get_u16 (struct blob_attr *attr)
static uint32_t blobmsg_get_u32 (struct blob_attr *attr)
static uint64_t blobmsg_get_u64 (struct blob_attr *attr)
static uint64_t blobmsg_cast_u64 (struct blob_attr *attr)
static int64_t blobmsg_cast_s64 (struct blob_attr *attr)
static double blobmsg_get_double (struct blob_attr *attr)
static char * blobmsg_get_string (struct blob_attr *attr)
void * blobmsg_alloc_string_buffer (struct blob_buf *buf, const char *name, unsigned int maxlen)
void * blobmsg_realloc_string_buffer (struct blob_buf *buf, unsigned int maxlen)
void blobmsg_add_string_buffer (struct blob_buf *buf)
int blobmsg_vprintf (struct blob_buf *buf, const char *name, const char *format, va_list arg)
int blobmsg_printf (struct blob_buf *buf, const char *name, const char *format,...) __attribute__((format(printf
Variables
struct blobmsg_hdr __packed
Class Documentation
blobmsg_hdr
struct blobmsg_hdr
Definition at line 41 of file blobmsg.h.
Class Members
uint8_t name[]
uint16_t namelen
blobmsg_policy
struct blobmsg_policy
Definition at line 46 of file blobmsg.h.
Class Members
const char * name
enum blobmsg_type type
Macro Definition Documentation
__blobmsg_for_each_attr
#define __blobmsg_for_each_attr (pos, attr, rem)
Value:
    for (pos = (struct blob_attr *) (attr ? blobmsg_data(attr) : NULL); \
         rem >= sizeof(struct blob_attr) && (blob_pad_len(pos) <= rem) && \
         (blob_pad_len(pos) >= sizeof(struct blob_attr)); \
         rem -= blob_pad_len(pos), pos = blob_next(pos))
Definition at line 371 of file blobmsg.h.
#define __blobmsg_for_each_attr(pos, attr, rem) \
    for (pos = (struct blob_attr *) (attr ? blobmsg_data(attr) : NULL); \
         rem >= sizeof(struct blob_attr) && (blob_pad_len(pos) <= rem) && \
         (blob_pad_len(pos) >= sizeof(struct blob_attr)); \
         rem -= blob_pad_len(pos), pos = blob_next(pos))
BLOBMSG_ALIGN
#define BLOBMSG_ALIGN 2
Definition at line 22 of file blobmsg.h.
blobmsg_for_each_attr
#define blobmsg_for_each_attr (pos, attr, rem)
Value:
    for (rem = attr ? blobmsg_data_len(attr) : 0, \
         pos = (struct blob_attr *) (attr ? blobmsg_data(attr) : NULL); \
         rem >= sizeof(struct blob_attr) && (blob_pad_len(pos) <= rem) && \
         (blob_pad_len(pos) >= sizeof(struct blob_attr)); \
         rem -= blob_pad_len(pos), pos = blob_next(pos))
Definition at line 364 of file blobmsg.h.
#define blobmsg_for_each_attr(pos, attr, rem) \
    for (rem = attr ? blobmsg_data_len(attr) : 0, \
         pos = (struct blob_attr *) (attr ? blobmsg_data(attr) : NULL); \
         rem >= sizeof(struct blob_attr) && (blob_pad_len(pos) <= rem) && \
         (blob_pad_len(pos) >= sizeof(struct blob_attr)); \
         rem -= blob_pad_len(pos), pos = blob_next(pos))
Referenced by __bridge_config_init(), __buf_add_all(), acl_recv_cb(), blobmsg_check_array_len(), bonding_config_init(), bridge_config_init(), bridge_hotplug_set_member_vlans(), check_table_a_entries(), checkblock(), checkvolumes(), cmd_process_strings(), config_init_procd_wireless_interface(), config_parse_vlan(), device_set_extra_vlans(), expr_and_or(), expr_eq_regex(), extdev_buf_add_list(), fill_string_list(), handle_case(), handle_command(), handle_command(), handle_exec(), handle_expr_has(), hotplug_call(), hotplug_msg_find_var(), instance_config_parse(), instance_config_parse_command(), instance_gen_setns_argstr(), instance_jail_parse(), instance_run(), interface_add_assignment_classes(), interface_add_dns_search_list(), interface_add_dns_server_list(), json_process_cmd(), json_script_find_var(), list_cb(), netifd_handle_alias(), netifd_ubus_data_cb(), parse_address_list(), parse_prefix_list(), parse_static_address_option(), parseOCI(), parseOCIcap(), parseOCIdevices(), parseOCIenvarray(), parseOCIhook(), parseOCIlinux(), parseOCIlinuxcgroups_devices(), parseOCIlinuxcgroups_legacy_blockio(), parseOCIlinuxcgroups_unified(), parseOCIlinuxseccomp(), parseOCImountopts(), parseOCIprocess(), parseOCIprocessuser(), parseOCIsysctl(), parseOCIuidgidmappings(), proto_shell_notify_error(), proto_shell_parse_data(), proto_shell_parse_neighbor_list(), proto_shell_parse_route_list(), resolveuuid(), rpc_file_exec_run(), rpc_handle_acl(), rpc_handle_get(), rpc_handle_set(), rpc_handle_unset(), rpc_login_setup_acl_file(), rpc_login_setup_acl_scope(), rpc_plugin_parse_signature(), rpc_session_from_blob(), rpc_uci_add(), rpc_uci_match_section(), rpc_uci_merge_delete(), rpc_uci_merge_set(), rpc_uci_order(), rpc_uci_set(), rule_handle_command(), service_update(), service_validate_add(), settings_add(), system_add_ip6_tunnel(), system_bonding_set_device(), sysupgrade_exec_upgraded(), trigger_add(), trigger_command_run(), ubusd_acl_check(), ubusd_acl_file_add(), uxc_boot(), uxc_create(), uxc_delete(), uxc_kill(), uxc_list(), uxc_set(), uxc_state(), vif_config_add_bridge(), vlandev_qos_mapping_list_apply(), wireless_check_interface(), wireless_interface_handle_link(), and wireless_vlan_handle_link().
BLOBMSG_PADDING
#define BLOBMSG_PADDING (len)
Value:
(((len) + (1 << BLOBMSG_ALIGN) - 1) & ~((1 << BLOBMSG_ALIGN) - 1))
Definition at line 23 of file blobmsg.h.
Referenced by blobmsg_hdrlen().
Enumeration Type Documentation
blobmsg_type
enum blobmsg_type
Enumerator
BLOBMSG_TYPE_UNSPEC
BLOBMSG_TYPE_ARRAY
BLOBMSG_TYPE_TABLE
BLOBMSG_TYPE_STRING
BLOBMSG_TYPE_INT64
BLOBMSG_TYPE_INT32
BLOBMSG_TYPE_INT16
BLOBMSG_TYPE_INT8
BLOBMSG_TYPE_BOOL BLOBMSG_TYPE_INT8
BLOBMSG_TYPE_DOUBLE
__BLOBMSG_TYPE_LAST
BLOBMSG_TYPE_LAST __BLOBMSG_TYPE_LAST - 1
BLOBMSG_CAST_INT64 __BLOBMSG_TYPE_LAST
Definition at line 25 of file blobmsg.h.
                  {
    BLOBMSG_TYPE_UNSPEC,
    BLOBMSG_TYPE_ARRAY,
    BLOBMSG_TYPE_TABLE,
    BLOBMSG_TYPE_STRING,
    BLOBMSG_TYPE_INT64,
    BLOBMSG_TYPE_INT32,
    BLOBMSG_TYPE_INT16,
    BLOBMSG_TYPE_INT8,
    BLOBMSG_TYPE_BOOL = BLOBMSG_TYPE_INT8,
    BLOBMSG_TYPE_DOUBLE,
    __BLOBMSG_TYPE_LAST,
    BLOBMSG_TYPE_LAST = __BLOBMSG_TYPE_LAST - 1,
    BLOBMSG_CAST_INT64 = __BLOBMSG_TYPE_LAST,
};
Function Documentation
blobmsg_add_blob()
static int blobmsg_add_blob (struct blob_buf * buf, struct blob_attr * attr) inline static
Definition at line 241 of file blobmsg.h.
{
    return blobmsg_add_field(buf, blobmsg_type(attr), blobmsg_name(attr),
                 blobmsg_data(attr), blobmsg_data_len(attr));
}
References blobmsg_add_field(), blobmsg_data(), blobmsg_data_len(), blobmsg_name(), and buf.
Referenced by cmd_process_strings(), handle_state(), instance_dump(), netifd_dump_status(), prepare_config(), service_dump(), service_get_data(), ubusd_send_obj(), and uxc_set().
blobmsg_add_double()
static int blobmsg_add_double (struct blob_buf * buf, const char * name, double val) inline static
Definition at line 196 of file blobmsg.h.
{
    union {
        double d;
        uint64_t u64;
    } v;
    v.d = val;
    v.u64 = cpu_to_be64(v.u64);
    return blobmsg_add_field(buf, BLOBMSG_TYPE_DOUBLE, name, &v.u64, 8);
}
References blobmsg_add_field(), BLOBMSG_TYPE_DOUBLE, buf, and cpu_to_be64.
Referenced by blobmsg_add_json_element(), fill_message(), fill_message(), rpc_plugin_json_element_to_blob(), and rpc_ucode_ucv_to_blob().
blobmsg_add_field()
int blobmsg_add_field (struct blob_buf * buf, int type, const char * name, const void * data, unsigned int len)
Definition at line 377 of file blobmsg.c.
{
    struct blob_attr *attr;
    void *data_dest;
    attr = blobmsg_new(buf, type, name, len, &data_dest);
    if (!attr)
        return -1;
    if (len > 0)
        memcpy(data_dest, data, len);
    return 0;
}
References blobmsg_new(), buf, blob_attr::data, and type.
Referenced by __buf_add_all(), blobmsg_add_blob(), blobmsg_add_double(), blobmsg_add_json_element(), blobmsg_add_string(), blobmsg_add_u16(), blobmsg_add_u32(), blobmsg_add_u64(), blobmsg_add_u8(), rpc_handle_get(), rpc_plugin_json_element_to_blob(), rpc_session_dump_data(), rpc_ucode_ucv_to_blob(), ubus_cli_get_monitor_data(), ubus_send_event(), and ubusd_reply_add().
blobmsg_add_string()
static int blobmsg_add_string (struct blob_buf * buf, const char * name, const char * string) inline static
Definition at line 235 of file blobmsg.h.
{
    return blobmsg_add_field(buf, BLOBMSG_TYPE_STRING, name, string, strlen(string) + 1);
}
References blobmsg_add_field(), BLOBMSG_TYPE_STRING, and buf.
Referenced by __device_broadcast_event(), __udebug_buf_add(), _rpc_file_add_stat(), add_parsed_data(), blobmsg_add_json_element(), bridge_dump_info(), bridge_stp_notify(), client_main(), config_parse_bridge_interface(), container_handle_features(), device_dump_status(), extdev_bridge_disable_interface(), extdev_bridge_disable_member(), extdev_bridge_enable_member(), extdev_buf_add_list(), extdev_dump(), extdev_free(), extdev_hotplug_prepare(), fill_message(), fill_message(), fill_message(), handle_button_timeout(), handle_state(), hotplug_handler(), instance_dump(), interface_ip_dump_address_list(), interface_ip_dump_dns_search_list(), interface_ip_dump_neighbor_list(), interface_ip_dump_prefix_list(), jail_delete_instance(), macvlan_dump_info(), main(), netifd_add_host_route(), netifd_add_interface_errors(), netifd_dump_status(), netifd_handle_dump(), netifd_handle_iface_prepare(), netifd_ubus_get_procd_data(), netifd_ubus_interface_event(), netifd_ubus_interface_notify(), netns_updown(), pass_console(), print_syscalls(), proto_dump_handlers(), put_cgroups(), put_namespace(), rpc_file_list(), rpc_file_stat(), rpc_iwinfo_add_bit_array(), rpc_iwinfo_assoclist(), rpc_iwinfo_call_hw_ht_mode(), rpc_iwinfo_call_int(), rpc_iwinfo_call_str(), rpc_iwinfo_countrylist(), rpc_iwinfo_devices(), rpc_iwinfo_phyname(), rpc_iwinfo_scan(), rpc_plugin_json_element_to_blob(), rpc_session_dump_acls(), rpc_session_to_blob(), rpc_sys_packagelist(), rpc_uci_add(), rpc_uci_configs(), rpc_uci_dump_change(), rpc_uci_dump_option(), rpc_uci_dump_section(), rpc_uci_trigger_event(), rpc_ucode_ucv_to_blob(), run_netifd(), run_ubusd(), service_handle_watchdog(), service_start_early(), service_validate_dump(), system_add_devtype(), system_add_ethtool_pause_an(), system_add_pause_modes(), system_board(), system_if_dump_info(), sysupgrade_error(), test_count(), test_hello_reply(), ubus_cli_get_monitor_data(), ubus_event_bcast(), ubus_lua_format_blob(), ubus_register_event_handler(), ubus_send_event(), ubusd_create_object_event_msg(), ubusd_reply_add(), uxc_attach(), uxc_boot(), uxc_create(), uxc_delete(), uxc_kill(), uxc_list(), uxc_set(), uxc_state(), veth_dump_info(), vif_config_add_bridge(), vlandev_dump_info(), watchdog_set(), wireless_device_get_validate(), wireless_interface_status(), wireless_station_status(), and wireless_vlan_status().
blobmsg_add_string_buffer()
void blobmsg_add_string_buffer (struct blob_buf * buf)
Definition at line 361 of file blobmsg.c.
{
    struct blob_attr *attr;
    int len, attrlen;
    attr = blob_next(buf->head);
    len = strlen(blobmsg_data(attr)) + 1;
    attrlen = blob_raw_len(attr) + len;
    blob_set_raw_len(attr, attrlen);
    blob_fill_pad(attr);
    blob_set_raw_len(buf->head, blob_raw_len(buf->head) + blob_pad_len(attr));
}
References blob_fill_pad(), blob_next(), blob_pad_len(), blob_raw_len(), blob_set_raw_len(), blobmsg_data(), and buf.
Referenced by __attribute__(), eval_string(), interface_ip_dump_address_list(), interface_ip_dump_dns_server_list(), interface_ip_dump_neighbor_list(), interface_ip_dump_prefix_assignment_list(), interface_ip_dump_prefix_list(), interface_ip_dump_route_list(), rpc_file_md5(), rpc_file_read(), rpc_ustream_to_blobmsg(), rpc_ustream_to_blobmsg(), system_add_link_mode_name(), system_board(), and system_if_dump_info().
blobmsg_add_u16()
static int blobmsg_add_u16 (struct blob_buf * buf, const char * name, uint16_t val) inline static
Definition at line 214 of file blobmsg.h.
{
    val = cpu_to_be16(val);
    return blobmsg_add_field(buf, BLOBMSG_TYPE_INT16, name, &val, 2);
}
References blobmsg_add_field(), BLOBMSG_TYPE_INT16, buf, and cpu_to_be16.
Referenced by add_parsed_data(), extdev_buf_add_list(), fill_message(), fill_message(), rc_list_add_table(), and rpc_iwinfo_assoclist().
blobmsg_add_u32()
static int blobmsg_add_u32 (struct blob_buf * buf, const char * name, uint32_t val) inline static
Definition at line 221 of file blobmsg.h.
{
    val = cpu_to_be32(val);
    return blobmsg_add_field(buf, BLOBMSG_TYPE_INT32, name, &val, 4);
}
References blobmsg_add_field(), BLOBMSG_TYPE_INT32, buf, and cpu_to_be32.
Referenced by _rpc_file_add_stat(), add_parsed_data(), blobmsg_add_json_element(), bridge_dump_info(), bridge_dump_vlan(), bridge_stp_notify(), client_main(), device_dump_status(), extdev_buf_add_list(), fill_message(), fill_message(), handle_state(), instance_dump(), interface_ip_dump_address_list(), interface_ip_dump_neighbor_list(), interface_ip_dump_prefix_assignment_list(), interface_ip_dump_prefix_list(), interface_ip_dump_route_list(), netifd_dump_status(), rpc_exec_reply(), rpc_file_exec_reply(), rpc_iwinfo_add_encryption(), rpc_iwinfo_add_rateinfo(), rpc_iwinfo_assoclist(), rpc_iwinfo_call_hardware_id(), rpc_iwinfo_call_int(), rpc_iwinfo_freqlist(), rpc_iwinfo_scan(), rpc_iwinfo_survey(), rpc_iwinfo_txpowerlist(), rpc_plugin_json_element_to_blob(), rpc_session_to_blob(), rpc_uci_dump_change(), rpc_uci_dump_section(), rpc_ucode_ucv_to_blob(), run_netifd(), service_handle_watchdog(), system_info(), test_client_notify_cb(), test_count(), test_count(), ubus_cli_get_monitor_data(), ubus_lua_format_blob(), ubus_push_method_data(), ubus_register_event_handler(), ubusd_create_object_event_msg(), ubusd_create_sequence_event_msg(), ubusd_reply_query(), uxc_kill(), uxc_list(), vlandev_dump_info(), vlandev_qos_mapping_dump(), and watchdog_set().
blobmsg_add_u64()
static int blobmsg_add_u64 (struct blob_buf * buf, const char * name, uint64_t val) inline static
Definition at line 228 of file blobmsg.h.
{
    val = cpu_to_be64(val);
    return blobmsg_add_field(buf, BLOBMSG_TYPE_INT64, name, &val, 8);
}
References blobmsg_add_field(), BLOBMSG_TYPE_INT64, buf, and cpu_to_be64.
Referenced by __udebug_buf_add(), add_parsed_data(), blobmsg_add_json_element(), extdev_buf_add_list(), fill_message(), fill_message(), rpc_iwinfo_assoclist(), rpc_iwinfo_survey(), rpc_plugin_json_element_to_blob(), rpc_session_to_blob(), rpc_ucode_ucv_to_blob(), system_if_dump_stats(), system_info(), and ubus_lua_format_blob().
blobmsg_add_u8()
static int blobmsg_add_u8 (struct blob_buf * buf, const char * name, uint8_t val) inline static
Definition at line 208 of file blobmsg.h.
{
    return blobmsg_add_field(buf, BLOBMSG_TYPE_INT8, name, &val, 1);
}
References blobmsg_add_field(), BLOBMSG_TYPE_INT8, and buf.
Referenced by __device_broadcast_event(), add_parsed_data(), blobmsg_add_json_element(), bridge_dump_info(), bridge_dump_vlan(), container_handle_features(), device_dump_status(), extdev_buf_add_list(), fill_message(), fill_message(), instance_dump(), netifd_dump_status(), netns_updown(), proto_dump_handlers(), rc_list_add_table(), rpc_handle_access(), rpc_iwinfo_add_encryption(), rpc_iwinfo_add_rateinfo(), rpc_iwinfo_assoclist(), rpc_iwinfo_countrylist(), rpc_iwinfo_freqlist(), rpc_iwinfo_txpowerlist(), rpc_plugin_json_element_to_blob(), rpc_uci_dump_section(), rpc_ucode_ucv_to_blob(), run_netifd(), service_dump(), system_if_dump_info(), ubus_cli_get_monitor_data(), ubus_lua_format_blob(), uxc_create(), uxc_list(), uxc_set(), vif_config_add_bridge(), watchdog_set(), and wireless_device_status().
blobmsg_alloc_string_buffer()
void * blobmsg_alloc_string_buffer (struct blob_buf * buf, const char * name, unsigned int maxlen)
Definition at line 326 of file blobmsg.c.
{
    struct blob_attr *attr;
    void *data_dest;
    maxlen++;
    attr = blobmsg_new(buf, BLOBMSG_TYPE_STRING, name, maxlen, &data_dest);
    if (!attr)
        return NULL;
    blob_set_raw_len(buf->head, blob_pad_len(buf->head) - blob_pad_len(attr));
    blob_set_raw_len(attr, blob_raw_len(attr) - maxlen);
    return data_dest;
}
References blob_pad_len(), blob_raw_len(), blob_set_raw_len(), blobmsg_new(), BLOBMSG_TYPE_STRING, and buf.
Referenced by __attribute__(), eval_string(), interface_ip_dump_address_list(), interface_ip_dump_dns_server_list(), interface_ip_dump_neighbor_list(), interface_ip_dump_prefix_assignment_list(), interface_ip_dump_prefix_list(), interface_ip_dump_route_list(), rpc_file_md5(), rpc_file_read(), rpc_ustream_to_blobmsg(), rpc_ustream_to_blobmsg(), system_add_link_mode_name(), system_board(), and system_if_dump_info().
blobmsg_buf_init()
static int blobmsg_buf_init (struct blob_buf * buf) inline static
Definition at line 273 of file blobmsg.h.
{
    return blob_buf_init(buf, BLOBMSG_TYPE_TABLE);
}
References blob_buf_init(), BLOBMSG_TYPE_TABLE, and buf.
Referenced by main(), and main().
blobmsg_cast_s64()
static int64_t blobmsg_cast_s64 (struct blob_attr * attr) inline static
Definition at line 322 of file blobmsg.h.
{
    int64_t tmp = 0;
    if (blobmsg_type(attr) == BLOBMSG_TYPE_INT64)
        tmp = blobmsg_get_u64(attr);
    else if (blobmsg_type(attr) == BLOBMSG_TYPE_INT32)
        tmp = (int32_t)blobmsg_get_u32(attr);
    else if (blobmsg_type(attr) == BLOBMSG_TYPE_INT16)
        tmp = (int16_t)blobmsg_get_u16(attr);
    else if (blobmsg_type(attr) == BLOBMSG_TYPE_INT8)
        tmp = (int8_t)blobmsg_get_u8(attr);
    return tmp;
}
References blobmsg_get_u16(), blobmsg_get_u32(), blobmsg_get_u64(), blobmsg_get_u8(), BLOBMSG_TYPE_INT16, BLOBMSG_TYPE_INT32, BLOBMSG_TYPE_INT64, and BLOBMSG_TYPE_INT8.
Referenced by dump_message_cast_s64(), dump_message_cast_s64_json(), parseOCIlinuxcgroups_legacy_cpu(), and parseOCIlinuxcgroups_legacy_memory().
blobmsg_cast_u64()
static uint64_t blobmsg_cast_u64 (struct blob_attr * attr) inline static
Definition at line 306 of file blobmsg.h.
{
    uint64_t tmp = 0;
    if (blobmsg_type(attr) == BLOBMSG_TYPE_INT64)
        tmp = blobmsg_get_u64(attr);
    else if (blobmsg_type(attr) == BLOBMSG_TYPE_INT32)
        tmp = blobmsg_get_u32(attr);
    else if (blobmsg_type(attr) == BLOBMSG_TYPE_INT16)
        tmp = blobmsg_get_u16(attr);
    else if (blobmsg_type(attr) == BLOBMSG_TYPE_INT8)
        tmp = blobmsg_get_u8(attr);
    return tmp;
}
References blobmsg_get_u16(), blobmsg_get_u32(), blobmsg_get_u64(), blobmsg_get_u8(), BLOBMSG_TYPE_INT16, BLOBMSG_TYPE_INT32, BLOBMSG_TYPE_INT64, and BLOBMSG_TYPE_INT8.
Referenced by dump_message_cast_u64(), dump_message_cast_u64_json(), parseOCIlinuxcgroups_devices(), parseOCIlinuxcgroups_legacy_blockio(), parseOCIlinuxcgroups_legacy_cpu(), parseOCIlinuxcgroups_legacy_pids(), parseOCIlinuxseccomp(), and parseOCIrlimit().
blobmsg_check_array()
int blobmsg_check_array (const struct blob_attr * attr, int type)
Definition at line 87 of file blobmsg.c.
{
    return blobmsg_check_array_len(attr, type, blob_raw_len(attr));
}
References blob_raw_len(), blobmsg_check_array_len(), and type.
Referenced by blobmsg_check_attr_list(), bridge_hotplug_set_member_vlans(), check_message(), check_table_a_entries(), and device_set_extra_vlans().
blobmsg_check_array_len()
int blobmsg_check_array_len (const struct blob_attr * attr, int type, size_t len)
Definition at line 92 of file blobmsg.c.
{
    struct blob_attr *cur;
    size_t rem;
    bool name;
    int size = 0;
    if (type > BLOBMSG_TYPE_LAST)
        return -1;
    if (!blobmsg_check_attr_len(attr, false, blob_len))
        return -1;
    switch (blobmsg_type(attr)) {
    case BLOBMSG_TYPE_TABLE:
        name = true;
        break;
    case BLOBMSG_TYPE_ARRAY:
        name = false;
        break;
    default:
        return -1;
    }
    blobmsg_for_each_attr(cur, attr, rem) {
        if (type != BLOBMSG_TYPE_UNSPEC && blobmsg_type(cur) != type)
            return -1;
        if (!blobmsg_check_attr_len(cur, name, rem))
            return -1;
        size++;
    }
    return size;
}
References blob_len(), blobmsg_check_attr_len(), blobmsg_for_each_attr, BLOBMSG_TYPE_ARRAY, BLOBMSG_TYPE_LAST, BLOBMSG_TYPE_TABLE, BLOBMSG_TYPE_UNSPEC, and type.
Referenced by blobmsg_check_array(), blobmsg_check_attr_list_len(), and fuzz_blobmsg_parse().
blobmsg_check_attr()
bool blobmsg_check_attr (const struct blob_attr * attr, bool name)
Definition at line 28 of file blobmsg.c.
{
    return blobmsg_check_attr_len(attr, name, blob_raw_len(attr));
}
References blob_raw_len(), and blobmsg_check_attr_len().
Referenced by blobmsg_format_element(), blobmsg_list_fill(), fill_string_list(), interface_add_assignment_classes(), interface_add_data(), interface_add_dns_search_list(), interface_add_dns_server_list(), netifd_handle_alias(), netifd_ubus_data_cb(), proto_shell_notify_error(), rpc_ucode_blob_to_ucv(), ubus_create_obj_type(), ubus_lua_parse_blob(), and vlandev_qos_mapping_list_apply().
blobmsg_check_attr_len()
bool blobmsg_check_attr_len (const struct blob_attr * attr, bool name, size_t len)
Definition at line 58 of file blobmsg.c.
{
    const char *data;
    size_t data_len;
    int id;
    if (len < sizeof(struct blob_attr))
        return false;
    data_len = blob_raw_len(attr);
    if (data_len < sizeof(struct blob_attr) || data_len > len)
        return false;
    if (!blobmsg_check_name(attr, name))
        return false;
    id = blob_id(attr);
    if (id > BLOBMSG_TYPE_LAST)
        return false;
    if (!blob_type[id])
        return true;
    data = blobmsg_data(attr);
    data_len = blobmsg_data_len(attr);
    return blob_check_type(data, data_len, blob_type[id]);
}
References blob_check_type(), blob_id(), blob_raw_len(), blob_type, blobmsg_check_name(), blobmsg_data(), blobmsg_data_len(), BLOBMSG_TYPE_LAST, id, and blobmsg_hdr::name.
Referenced by blobmsg_check_array_len(), blobmsg_check_attr(), blobmsg_parse(), blobmsg_parse_array(), fuzz_blobmsg_parse(), and rpc_ucode_validate_call_args().
blobmsg_check_attr_list()
bool blobmsg_check_attr_list (const struct blob_attr * attr, int type)
Definition at line 130 of file blobmsg.c.
{
    return blobmsg_check_array(attr, type) >= 0;
}
References blobmsg_check_array(), and type.
Referenced by instance_config_parse_command(), instance_fill_array(), and test_blobmsg_procd_instance().
blobmsg_check_attr_list_len()
bool blobmsg_check_attr_list_len (const struct blob_attr * attr, int type, size_t len)
Definition at line 135 of file blobmsg.c.
{
    return blobmsg_check_array_len(attr, type, len) >= 0;
}
References blobmsg_check_array_len(), and type.
Referenced by fuzz_blobmsg_parse().
blobmsg_clear_name()
static void blobmsg_clear_name (struct blob_attr * attr) inline static
Definition at line 56 of file blobmsg.h.
{
    struct blobmsg_hdr *hdr = (struct blobmsg_hdr *) blob_data(attr);
    hdr->name[0] = 0;
}
References blob_data(), and blobmsg_hdr::name.
blobmsg_close_array()
static void blobmsg_close_array (struct blob_buf * buf, void * cookie) inline static
Definition at line 262 of file blobmsg.h.
{
    blob_nest_end(buf, cookie);
}
References blob_nest_end(), and buf.
Referenced by __udebug_buf_add(), __vlan_hotplug_op(), __vlandev_hotplug_op(), blobmsg_add_json_element(), bridge_dump_info(), bridge_dump_vlan(), cmd_process_strings(), config_parse_neighbor(), config_parse_route(), config_parse_rule(), container_handle_features(), extdev_buf_add_list(), fill_message(), instance_dump(), netifd_add_interface_errors(), netifd_dump_status(), netifd_handle_dump(), print_syscalls(), rpc_file_list(), rpc_iwinfo_add_bit_array(), rpc_iwinfo_add_encryption(), rpc_iwinfo_assoclist(), rpc_iwinfo_call_hardware_id(), rpc_iwinfo_countrylist(), rpc_iwinfo_devices(), rpc_iwinfo_freqlist(), rpc_iwinfo_scan(), rpc_iwinfo_survey(), rpc_iwinfo_txpowerlist(), rpc_plugin_json_element_to_blob(), rpc_session_dump_acls(), rpc_uci_changes(), rpc_uci_configs(), rpc_uci_dump_change(), rpc_uci_dump_option(), rpc_ucode_ucv_to_blob(), run_netifd(), run_ubusd(), service_start_early(), service_validate_dump(), system_add_ethtool_pause_an(), system_board(), system_if_dump_info(), system_info(), ubus_lua_format_blob(), uxc_list(), uxc_set(), vlandev_qos_mapping_dump(), wireless_device_status(), and wireless_interface_status().
blobmsg_close_table()
static void blobmsg_close_table (struct blob_buf * buf, void * cookie) inline static
Definition at line 268 of file blobmsg.h.
{
    blob_nest_end(buf, cookie);
}
References blob_nest_end(), and buf.
Referenced by __do_bridge_reload(), blobmsg_add_json_element(), bridge_dump_info(), bridge_dump_vlan(), conf_load(), device_dump_status(), extdev_buf_add_list(), fill_message(), fill_message(), hotplug_handler(), instance_dump(), interface_ip_dump_address_list(), interface_ip_dump_neighbor_list(), interface_ip_dump_prefix_assignment_list(), interface_ip_dump_prefix_list(), interface_ip_dump_route_list(), netifd_add_interface_errors(), netifd_dump_status(), netifd_handle_dump(), prepare_config(), print_syscalls(), proto_dump_handlers(), put_container(), rc_list_add_table(), rpc_file_list(), rpc_handle_get(), rpc_iwinfo_add_encryption(), rpc_iwinfo_assoclist(), rpc_iwinfo_countrylist(), rpc_iwinfo_freqlist(), rpc_iwinfo_info(), rpc_iwinfo_scan(), rpc_iwinfo_survey(), rpc_iwinfo_txpowerlist(), rpc_plugin_json_element_to_blob(), rpc_session_dump_acls(), rpc_session_to_blob(), rpc_sys_packagelist(), rpc_uci_changes(), rpc_uci_dump_package(), rpc_uci_dump_section(), rpc_uci_trigger_event(), rpc_ucode_ucv_to_blob(), run_netifd(), run_ubusd(), service_dump(), service_get_data(), service_start_early(), service_validate_dump(), system_if_dump_info(), system_info(), sysupgrade_error(), ubus_lua_format_blob(), ubus_push_method_data(), ubusd_reply_add(), ubusd_reply_query(), uxc_create(), uxc_list(), vlandev_qos_mapping_dump(), wireless_device_get_validate(), wireless_device_status(), wireless_interface_status(), wireless_station_status(), and wireless_vlan_status().
blobmsg_data()
static void * blobmsg_data (const struct blob_attr * attr) inline static
Definition at line 78 of file blobmsg.h.
{
    struct blobmsg_hdr *hdr;
    char *data;
    if (!attr)
        return NULL;
    hdr = (struct blobmsg_hdr *) blob_data(attr);
    data = (char *) blob_data(attr);
    if (blob_is_extended(attr))
        data += blobmsg_hdrlen(blobmsg_namelen(hdr));
    return data;
}
References blob_data(), blob_is_extended(), blobmsg_hdrlen(), and blobmsg_namelen().
Referenced by __bridge_config_init(), __bridge_reload(), __buf_add_all(), __interface_add(), __json_process_cmd(), __json_process_type(), __reload(), __rpc_iwinfo_open(), __vlan_hotplug_op(), __vlandev_hotplug_op(), acl_add(), acl_recv_cb(), add_parsed_data(), blobmsg_add_blob(), blobmsg_add_string_buffer(), blobmsg_check_attr_len(), blobmsg_data_len(), blobmsg_format_element(), blobmsg_format_json_with_cb(), blobmsg_get_bool(), blobmsg_get_string(), blobmsg_get_u16(), blobmsg_get_u32(), blobmsg_get_u64(), blobmsg_get_u8(), blobmsg_list_fill(), blobmsg_new(), blobmsg_parse_array_attr(), blobmsg_parse_attr(), blobmsg_realloc_string_buffer(), block_cb(), bridge_config_init(), check_table_a_entries(), checkblock(), cmd_process_strings(), config_find_blobmsg_attr(), container_handle_console(), container_handle_kill(), device_init_settings(), dump_attr_data(), dump_cb(), dump_message(), expr_eq_regex(), extdev_buf_add_list(), extdev_wait_ev_cb(), fill_string_list(), fstab_cb(), get_wdev(), handle_case(), handle_command(), handle_command(), handle_exec(), handle_expr_has(), handle_expr_isdir(), handle_firmware(), handle_if(), handle_include(), handle_makedev(), handle_rm(), handle_start_console(), hotplug_call(), hotplug_msg_find_var(), instance_config_parse(), instance_dump(), instance_fill_any(), instance_fill_array(), instance_gen_setns_argstr(), instance_jail_parse(), instance_run(), instance_stdio(), interface_add_assignment_classes(), interface_add_dns_search_list(), interface_add_dns_server_list(), interface_alloc(), interface_ip_add_neighbor(), interface_ip_add_route(), iprule_add(), jail_run(), json_get_tuple(), json_process_expr(), json_script_find_var(), list_cb(), macvlan_apply_settings(), macvlan_config_init(), netifd_add_host_route(), netifd_dev_status(), netifd_handle_alias(), netifd_handle_iface(), netifd_handle_set_state(), netifd_iface_handle_device(), ocistate_cb(), parse_address_item(), parse_gateway_option(), parse_prefix_list(), parse_static_address_option(), parseOCIcapabilities(), parseOCIdevices(), parseOCIhook(), parseOCIhooks(), parseOCIlinux(), parseOCIlinuxcgroups(), parseOCIlinuxcgroups_devices(), parseOCIlinuxcgroups_legacy_blockio(), parseOCIlinuxcgroups_legacy_cpu(), parseOCIlinuxcgroups_legacy_memory(), parseOCIlinuxcgroups_legacy_pids(), parseOCIlinuxns(), parseOCIlinuxseccomp(), parseOCImount(), parseOCIprocess(), parseOCIprocessuser(), parseOCIrlimit(), parseOCIroot(), parseOCIuidgidmappings(), proto_apply_static_ip_settings(), proto_shell_add_host_dependency(), proto_shell_create_tunnel(), proto_shell_notify_error(), proto_shell_update_link(), put_container(), rc_init(), rc_list(), resolveuuid(), rpc_cgi_password_set(), rpc_file_access(), rpc_file_exec(), rpc_file_exec_run(), rpc_file_write(), rpc_handle_access(), rpc_handle_acl(), rpc_handle_destroy(), rpc_handle_get(), rpc_handle_list(), rpc_handle_set(), rpc_handle_unset(), rpc_iwinfo_assoclist(), rpc_login_setup_acl_scope(), rpc_session_dump_data(), rpc_session_from_blob(), rpc_uci_add(), rpc_uci_apply(), rpc_uci_changes(), rpc_uci_confirm(), rpc_uci_delete(), rpc_uci_format_blob(), rpc_uci_getcommon(), rpc_uci_match_section(), rpc_uci_merge_delete(), rpc_uci_order(), rpc_uci_read_access(), rpc_uci_rename(), rpc_uci_revert_commit(), rpc_uci_rollback(), rpc_uci_set(), rpc_uci_write_access(), rpc_ucode_blob_to_ucv(), rule_handle_command(), service_get_data(), service_handle_delete(), service_handle_event(), service_handle_list(), service_handle_set(), service_handle_signal(), service_handle_state(), service_handle_update(), service_handle_validate(), service_handle_watchdog(), service_update(), service_validate_add(), settings_add(), system_add_gre_tunnel(), system_add_ip6_tunnel(), system_add_ip_tunnel(), system_add_proto_tunnel(), system_add_sit_tunnel(), system_add_vti_tunnel(), system_add_vxlan(), system_add_xfrm_tunnel(), test_hello(), ubus_bridge_state(), ubus_cli_get_monitor_data(), ubus_lua_parse_blob(), ubus_set_bridge_config(), ubusd_acl_add_access(), ubusd_alloc_event_pattern(), ubusd_create_event_from_msg(), ubusd_forward_event(), ubusd_reply_add(), uxc_boot(), uxc_create(), uxc_delete(), uxc_kill(), uxc_list(), uxc_set(), uxc_state(), veth_apply_settings(), vif_config_add_bridge(), vlandev_config_init(), vlandev_qos_mapping_list_apply(), wait_event_cb(), watch_subscribe_cb(), wireless_device_add_process(), wireless_device_notify(), wireless_interface_handle_link(), wireless_interface_set_data(), wireless_vlan_handle_link(), and wireless_vlan_set_data().
blobmsg_data_len()
static size_t blobmsg_data_len (const struct blob_attr * attr) inline static
Definition at line 95 of file blobmsg.h.
{
    uint8_t *start, *end;
    if (!attr)
        return 0;
    start = (uint8_t *) blob_data(attr);
    end = (uint8_t *) blobmsg_data(attr);
    return blob_len(attr) - (end - start);
}
References blob_data(), blob_len(), and blobmsg_data().
Referenced by __buf_add_all(), acl_add(), acl_recv_cb(), add_parsed_data(), blobmsg_add_blob(), blobmsg_check_attr_len(), blobmsg_format_element(), blobmsg_format_json_with_cb(), blobmsg_len(), check_message(), check_table_a_entries(), container_handle_console(), container_handle_kill(), dump_attr_data(), dump_message(), extdev_buf_add_list(), handle_if(), handle_makedev(), handle_rm(), instance_config_parse(), instance_fill_any(), instance_fill_array(), instance_gen_setns_argstr(), instance_jail_parse(), interface_add_assignment_classes(), interface_ip_add_neighbor(), interface_ip_add_route(), iprule_add(), json_get_tuple(), parse_address_item(), parse_prefix_list(), proto_shell_create_tunnel(), rc_init(), rc_list(), rpc_cgi_password_set(), rpc_file_exec_run(), rpc_file_write(), rpc_handle_get(), rpc_session_dump_data(), rpc_ucode_blob_to_ucv(), service_get_data(), service_handle_delete(), service_handle_event(), service_handle_list(), service_handle_set(), service_handle_signal(), service_handle_state(), service_handle_update(), service_handle_validate(), service_handle_watchdog(), service_update(), service_validate_add(), ubus_cli_get_monitor_data(), ubus_lua_parse_blob(), ubusd_acl_add_access(), ubusd_create_event_from_msg(), and ubusd_reply_add().
blobmsg_get_bool()
static bool blobmsg_get_bool (struct blob_attr * attr) inline static
Definition at line 283 of file blobmsg.h.
{
    return *(uint8_t *) blobmsg_data(attr);
}
References blobmsg_data().
Referenced by __bridge_reload(), blobmsg_get_bool_default(), bridge_apply_settings(), config_get_default_gro(), config_parse_vlan(), device_init_settings(), instance_config_parse(), instance_jail_parse(), interface_ip_add_neighbor(), interface_ip_add_route(), iprule_add(), list_cb(), netifd_add_host_route(), netifd_handle_set_state(), netifd_iface_handle_device(), netifd_netns_updown(), parse_address_item(), parseOCIlinuxcgroups_devices(), parseOCIprocess(), parseOCIroot(), proto_shell_set_available(), proto_shell_update_link(), rc_list(), resolveuuid(), rpc_file_read(), rpc_file_write(), rpc_sys_packagelist(), rpc_sys_upgrade_start(), rpc_uci_apply(), service_handle_list(), service_update(), settings_add(), system_add_gre_tunnel(), system_add_proto_tunnel(), system_vxlan_map_bool_attr(), sysupgrade(), test_blobmsg_procd_instance(), ubus_bridge_state(), uxc_boot(), uxc_list(), watchdog_set(), wireless_device_add_process(), wireless_device_create(), wireless_device_process_kill_all(), wireless_interface_create(), wireless_interface_init_config(), wireless_station_create(), wireless_vlan_create(), and wireless_vlan_init_config().
blobmsg_get_double()
static double blobmsg_get_double (struct blob_attr * attr) inline static
Definition at line 338 of file blobmsg.h.
{
    union {
        double d;
        uint64_t u64;
    } v;
    v.u64 = blobmsg_get_u64(attr);
    return v.d;
}
References blobmsg_get_u64().
Referenced by blobmsg_format_element(), dump_attr_data(), dump_message(), dump_message_cast_s64(), dump_message_cast_s64_json(), dump_message_cast_u64(), dump_message_cast_u64_json(), and dump_message_json().
blobmsg_get_string()
static char * blobmsg_get_string (struct blob_attr * attr) inline static
Definition at line 348 of file blobmsg.h.
{
    if (!attr)
        return NULL;
    return (char *) blobmsg_data(attr);
}
References blobmsg_data().
Referenced by __bridge_reload(), __rpc_check_path(), acl_add(), add_parsed_data(), bonding_apply_settings(), bonding_config_init(), bridge_apply_settings(), bridge_hotplug_set_member_vlans(), check_table_a_entries(), checkblock(), checkvolumes(), chgrp_target(), config_get_default_conduit(), config_get_default_macaddr(), config_parse_vlan(), config_procd_wireless_interface_cb(), config_watch_notify_cb(), device_init_settings(), device_set_extra_vlans(), dump_attr_data(), dump_message(), dump_message_cast_s64(), dump_message_cast_s64_json(), dump_message_cast_u64(), dump_message_cast_u64_json(), dump_message_json(), extdev_buf_add_list(), handle_firmware(), handle_makedev(), handle_start_console(), hotplug_call(), instance_config_parse(), instance_gen_setns_argstr(), instance_jail_parse(), interface_alloc(), iprule_add(), list_cb(), netifd_add_dynamic(), netifd_netns_updown(), parse_address_item(), parseOCI(), parseOCIcap(), parseOCIdevices(), parseOCIenvarray(), parseOCIhook(), parseOCIlinux(), parseOCIlinuxcgroups_devices(), parseOCIlinuxcgroups_legacy_cpu(), parseOCIlinuxcgroups_unified(), parseOCIlinuxns(), parseOCIlinuxseccomp(), parseOCImount(), parseOCImountopts(), parseOCIprocess(), parseOCIrlimit(), parseOCIroot(), parseOCIsysctl(), rc_init(), rc_list(), resolveuuid(), rpc_file_exec_run(), rpc_handle_destroy(), rpc_handle_login(), rpc_iwinfo_phyname(), rpc_reclaim_apply_session(), rpc_session_from_blob(), rpc_uci_revert_commit(), rpc_uci_set_savedir(), service_handle_event(), service_handle_list(), service_handle_signal(), service_handle_validate(), service_handle_watchdog(), service_validate_add(), settings_add(), system_add_gre_tunnel(), system_add_ip6_tunnel(), system_add_proto_tunnel(), system_add_vxlan(), system_bonding_set_device(), sysupgrade(), test_count(), trigger_add(), trigger_command_run(), ubus_auto_sub_event_handler_cb(), ubus_bridge_state(), ubus_process_invoke(), ubus_set_bridge_config(), ubusd_acl_check(), ubusd_acl_file_add(), uxc_boot(), uxc_create(), uxc_delete(), uxc_kill(), uxc_list(), uxc_set(), uxc_state(), validate_firmware_image(), veth_apply_settings(), vlandev_config_init(), wireless_check_interface(), and wireless_interface_init_config().
blobmsg_get_u16()
static uint16_t blobmsg_get_u16 (struct blob_attr * attr) inline static
Definition at line 288 of file blobmsg.h.
{
    return be16_to_cpu(*(uint16_t *) blobmsg_data(attr));
}
References be16_to_cpu, and blobmsg_data().
Referenced by add_parsed_data(), blobmsg_cast_s64(), blobmsg_cast_u64(), dump_attr_data(), dump_message(), extdev_buf_add_list(), rpc_uci_format_blob(), and sysupgrade_exec_upgraded().
blobmsg_get_u32()
static uint32_t blobmsg_get_u32 (struct blob_attr * attr) inline static
Definition at line 293 of file blobmsg.h.
{
    return be32_to_cpu(*(uint32_t *) blobmsg_data(attr));
}
References be32_to_cpu, and blobmsg_data().
Referenced by add_parsed_data(), blobmsg_cast_s64(), blobmsg_cast_u64(), bridge_apply_settings(), config_parse_vlan(), container_handle_kill(), device_init_settings(), dump_attr_data(), dump_message(), dump_message_json(), extdev_buf_add_list(), format_type(), instance_config_parse(), instance_gen_setns_argstr(), interface_alloc(), interface_ip_add_route(), iprule_add(), list_cb(), parse_address_item(), parseOCIdevices(), parseOCIhook(), parseOCIlinuxcgroups_legacy_blockio(), parseOCIlinuxseccomp(), parseOCIprocess(), parseOCIprocessuser(), parseOCIuidgidmappings(), proc_signal(), proto_shell_checkup_attach(), proto_shell_kill_command(), proto_shell_notify(), rpc_file_write(), rpc_handle_create(), rpc_handle_login(), rpc_plugin_parse_signature(), rpc_session_from_blob(), rpc_uci_apply(), rpc_uci_format_blob(), service_handle_signal(), service_handle_watchdog(), system_add_gre_tunnel(), system_add_ip6_tunnel(), system_add_ip_tunnel(), system_add_proto_tunnel(), system_add_vti_tunnel(), system_add_vxlan(), system_add_xfrm_tunnel(), sysupgrade_exec_upgraded(), test_blobmsg_procd_instance(), test_count(), test_count_data_cb(), test_watch(), trigger_add(), ubus_auto_sub_event_handler_cb(), ubus_set_bridge_config(), ubusd_alloc_event_pattern(), uxc_list(), watchdog_set(), wireless_device_add_process(), wireless_device_notify(), wireless_device_process_kill_all(), and wireless_device_set_retry().
blobmsg_get_u64()
static uint64_t blobmsg_get_u64 (struct blob_attr * attr) inline static
Definition at line 298 of file blobmsg.h.
{
    uint32_t *ptr = (uint32_t *) blobmsg_data(attr);
    uint64_t tmp = ((uint64_t) be32_to_cpu(ptr[0])) << 32;
    tmp |= be32_to_cpu(ptr[1]);
    return tmp;
}
References be32_to_cpu, and blobmsg_data().
Referenced by add_parsed_data(), blobmsg_cast_s64(), blobmsg_cast_u64(), blobmsg_get_double(), dump_attr_data(), dump_message(), dump_message_json(), extdev_buf_add_list(), rpc_session_from_blob(), and rpc_uci_format_blob().
blobmsg_get_u8()
static uint8_t blobmsg_get_u8 (struct blob_attr * attr) inline static
Definition at line 278 of file blobmsg.h.
{
    return *(uint8_t *) blobmsg_data(attr);
}
References blobmsg_data().
Referenced by add_parsed_data(), blobmsg_cast_s64(), blobmsg_cast_u64(), dump_attr_data(), dump_message(), dump_message_json(), extdev_buf_add_list(), netifd_handle_set_state(), rpc_uci_format_blob(), service_handle_state(), and sysupgrade_exec_upgraded().
blobmsg_hdrlen()
static int blobmsg_hdrlen (unsigned int namelen) inline static
Definition at line 51 of file blobmsg.h.
{
    return BLOBMSG_PADDING(sizeof(struct blobmsg_hdr) + namelen + 1);
}
References BLOBMSG_PADDING.
Referenced by blobmsg_check_name(), blobmsg_data(), blobmsg_new(), and blobmsg_open_nested().
blobmsg_len()
static size_t blobmsg_len (const struct blob_attr * attr) inline static
Definition at line 108 of file blobmsg.h.
{
    return blobmsg_data_len(attr);
}
References blobmsg_data_len().
Referenced by __bridge_reload(), __reload(), __vlan_hotplug_op(), __vlandev_hotplug_op(), blobmsg_parse_array_attr(), blobmsg_parse_attr(), checkblock(), config_find_blobmsg_attr(), dump_cb(), hotplug_call(), list_cb(), ocistate_cb(), parseOCIcapabilities(), parseOCIdevices(), parseOCIhook(), parseOCIhooks(), parseOCIlinux(), parseOCIlinuxcgroups(), parseOCIlinuxcgroups_devices(), parseOCIlinuxcgroups_legacy_blockio(), parseOCIlinuxcgroups_legacy_cpu(), parseOCIlinuxcgroups_legacy_memory(), parseOCIlinuxcgroups_legacy_pids(), parseOCIlinuxns(), parseOCIlinuxseccomp(), parseOCImount(), parseOCIprocess(), parseOCIprocessuser(), parseOCIrlimit(), parseOCIroot(), parseOCIuidgidmappings(), put_container(), resolveuuid(), settings_add(), system_add_gre_tunnel(), system_add_ip6_tunnel(), system_add_sit_tunnel(), system_add_vti_tunnel(), system_add_vxlan(), system_add_xfrm_tunnel(), ubus_bridge_state(), ubus_set_bridge_config(), uxc_boot(), uxc_create(), uxc_delete(), uxc_kill(), uxc_list(), uxc_set(), and uxc_state().
blobmsg_name()
static const char * blobmsg_name (const struct blob_attr * attr) inline static
Definition at line 62 of file blobmsg.h.
{
    struct blobmsg_hdr *hdr = (struct blobmsg_hdr *) blob_data(attr);
    return (const char *)(hdr + 1);
}
References blob_data().
Referenced by __buf_add_all(), blobmsg_add_blob(), blobmsg_format_element(), blobmsg_list_fill(), config_procd_wireless_interface_cb(), handle_case(), handle_exec(), hotplug_msg_find_var(), instance_dump(), instance_init(), instance_run(), interface_add_data(), jail_run(), json_script_find_var(), list_cb(), parseOCIlinuxcgroups_unified(), parseOCIsysctl(), resolveuuid(), rpc_file_exec_run(), rpc_handle_get(), rpc_handle_set(), rpc_login_setup_acl_file(), rpc_login_setup_acl_scope(), rpc_plugin_parse_signature(), rpc_session_dump_data(), rpc_session_from_blob(), rpc_session_set(), rpc_uci_add(), rpc_uci_match_section(), rpc_uci_merge_set(), rpc_ucode_blob_to_ucv(), rule_handle_command(), service_get_data(), service_validate_add(), settings_add(), sysupgrade_exec_upgraded(), ubus_create_obj_method(), ubus_lua_parse_blob(), ubusd_acl_add_access(), ubusd_send_obj(), uxc_delete(), and uxc_set().
blobmsg_namelen()
static uint16_t blobmsg_namelen (const struct blobmsg_hdr * hdr) static
Definition at line 73 of file blobmsg.h.
{
    return be16_to_cpu(hdr->namelen);
}
References be16_to_cpu, and blobmsg_hdr::namelen.
Referenced by blobmsg_check_name(), blobmsg_data(), blobmsg_parse(), and rpc_ucode_validate_call_args().
blobmsg_open_array()
static void * blobmsg_open_array (struct blob_buf * buf, const char * name) inline static
Definition at line 250 of file blobmsg.h.
{
    return blobmsg_open_nested(buf, name, true);
}
References blobmsg_open_nested(), and buf.
Referenced by __udebug_buf_add(), __vlan_hotplug_op(), __vlandev_hotplug_op(), blobmsg_add_json_element(), bridge_dump_info(), bridge_dump_vlan(), cmd_process_strings(), config_parse_neighbor(), config_parse_route(), config_parse_rule(), container_handle_features(), extdev_buf_add_list(), fill_message(), fill_message(), instance_dump(), netifd_add_interface_errors(), netifd_dump_status(), netifd_handle_dump(), print_syscalls(), rpc_file_list(), rpc_iwinfo_add_bit_array(), rpc_iwinfo_add_encryption(), rpc_iwinfo_assoclist(), rpc_iwinfo_call_hardware_id(), rpc_iwinfo_countrylist(), rpc_iwinfo_devices(), rpc_iwinfo_freqlist(), rpc_iwinfo_scan(), rpc_iwinfo_survey(), rpc_iwinfo_txpowerlist(), rpc_plugin_json_element_to_blob(), rpc_session_dump_acls(), rpc_uci_changes(), rpc_uci_configs(), rpc_uci_dump_change(), rpc_uci_dump_option(), rpc_ucode_ucv_to_blob(), run_netifd(), run_ubusd(), service_start_early(), service_validate_dump(), system_add_ethtool_pause_an(), system_if_dump_info(), system_info(), ubus_lua_format_blob(), ubusd_reply_query(), uxc_list(), uxc_set(), vlandev_qos_mapping_dump(), wireless_device_status(), and wireless_interface_status().
blobmsg_open_nested()
void * blobmsg_open_nested (struct blob_buf * buf, const char * name, bool array)
Definition at line 266 of file blobmsg.c.
{
    struct blob_attr *head;
    int type = array ? BLOBMSG_TYPE_ARRAY : BLOBMSG_TYPE_TABLE;
    unsigned long offset = attr_to_offset(buf, buf->head);
    void *data;
    if (!name)
        name = "";
    head = blobmsg_new(buf, type, name, 0, &data);
    if (!head)
        return NULL;
    blob_set_raw_len(buf->head, blob_pad_len(buf->head) - blobmsg_hdrlen(strlen(name)));
    buf->head = head;
    return (void *)offset;
}
References attr_to_offset(), blob_pad_len(), blob_set_raw_len(), blobmsg_hdrlen(), blobmsg_new(), BLOBMSG_TYPE_ARRAY, BLOBMSG_TYPE_TABLE, buf, blob_attr::data, and type.
Referenced by blobmsg_open_array(), and blobmsg_open_table().
blobmsg_open_table()
static void * blobmsg_open_table (struct blob_buf * buf, const char * name) inline static
Definition at line 256 of file blobmsg.h.
{
    return blobmsg_open_nested(buf, name, false);
}
References blobmsg_open_nested(), and buf.
Referenced by __do_bridge_reload(), blobmsg_add_json_element(), bridge_dump_info(), bridge_dump_vlan(), conf_load(), device_dump_status(), extdev_buf_add_list(), fill_message(), fill_message(), hotplug_handler(), instance_dump(), interface_ip_dump_address_list(), interface_ip_dump_neighbor_list(), interface_ip_dump_prefix_assignment_list(), interface_ip_dump_prefix_list(), interface_ip_dump_route_list(), netifd_add_interface_errors(), netifd_dump_status(), netifd_handle_dump(), prepare_config(), print_syscalls(), proto_dump_handlers(), put_container(), rc_list_add_table(), rpc_file_list(), rpc_handle_get(), rpc_iwinfo_add_encryption(), rpc_iwinfo_assoclist(), rpc_iwinfo_countrylist(), rpc_iwinfo_freqlist(), rpc_iwinfo_info(), rpc_iwinfo_scan(), rpc_iwinfo_survey(), rpc_iwinfo_txpowerlist(), rpc_plugin_json_element_to_blob(), rpc_session_dump_acls(), rpc_session_to_blob(), rpc_sys_packagelist(), rpc_uci_changes(), rpc_uci_dump_package(), rpc_uci_dump_section(), rpc_uci_trigger_event(), rpc_ucode_ucv_to_blob(), run_netifd(), run_ubusd(), service_dump(), service_get_data(), service_start_early(), service_validate_dump(), system_board(), system_if_dump_info(), system_info(), sysupgrade_error(), ubus_lua_format_blob(), ubus_push_method_data(), ubusd_reply_add(), uxc_create(), uxc_list(), vlandev_qos_mapping_dump(), wireless_device_get_validate(), wireless_device_status(), wireless_interface_status(), wireless_station_status(), and wireless_vlan_status().
blobmsg_parse()
int blobmsg_parse (const struct blobmsg_policy * policy, int policy_len, struct blob_attr ** tb, void * data, unsigned int len)
Definition at line 166 of file blobmsg.c.
{
    const struct blobmsg_hdr *hdr;
    struct blob_attr *attr;
    uint8_t *pslen;
    int i;
    memset(tb, 0, policy_len * sizeof(*tb));
    if (!data || !len)
        return -EINVAL;
    pslen = alloca(policy_len);
    for (i = 0; i < policy_len; i++) {
        if (!policy[i].name)
            continue;
        pslen[i] = strlen(policy[i].name);
    }
    __blob_for_each_attr(attr, data, len) {
        if (!blobmsg_check_attr_len(attr, false, len))
            return -1;
        if (!blob_is_extended(attr))
            continue;
        hdr = blob_data(attr);
        for (i = 0; i < policy_len; i++) {
            if (!policy[i].name)
                continue;
            if (policy[i].type != BLOBMSG_TYPE_UNSPEC &&
                policy[i].type != BLOBMSG_CAST_INT64 &&
                blob_id(attr) != policy[i].type)
                continue;
            if (policy[i].type == BLOBMSG_CAST_INT64 &&
                (blob_id(attr) != BLOBMSG_TYPE_INT64 &&
                 blob_id(attr) != BLOBMSG_TYPE_INT32 &&
                 blob_id(attr) != BLOBMSG_TYPE_INT16 &&
                 blob_id(attr) != BLOBMSG_TYPE_INT8))
                continue;
            if (blobmsg_namelen(hdr) != pslen[i])
                continue;
            if (tb[i])
                continue;
            if (strcmp(policy[i].name, (char *) hdr->name) != 0)
                continue;
            tb[i] = attr;
        }
    }
    return 0;
}
References __blob_for_each_attr, blob_data(), blob_id(), blob_is_extended(), BLOBMSG_CAST_INT64, blobmsg_check_attr_len(), blobmsg_namelen(), BLOBMSG_TYPE_INT16, BLOBMSG_TYPE_INT32, BLOBMSG_TYPE_INT64, BLOBMSG_TYPE_INT8, BLOBMSG_TYPE_UNSPEC, blob_attr::data, blobmsg_hdr::name, and type.
Referenced by __bridge_reload(), __interface_add(), __reload(), __rpc_check_path(), acl_add(), acl_recv_cb(), blobmsg_parse_attr(), bonding_reload(), bridge_reload(), check_message(), check_table_a_entries(), checkblock(), config_find_blobmsg_attr(), config_parse_vlan(), config_watch_notify_cb(), container_handle_console(), container_handle_kill(), device_set_config(), dump_cb(), dump_message(), dump_message(), dump_message_cast_s64(), dump_message_cast_s64_json(), dump_message_cast_u64(), dump_message_cast_u64_json(), dump_message_json(), extdev_wait_ev_cb(), fuzz_blobmsg_parse(), get_wdev(), hotplug_call(), instance_config_parse(), instance_gen_setns_argstr(), instance_jail_parse(), interface_alloc(), interface_device_config_changed(), interface_ip_add_neighbor(), interface_ip_add_route(), iprule_add(), list_cb(), macvlan_reload(), netifd_add_dynamic(), netifd_add_host_route(), netifd_dev_status(), netifd_handle_alias(), netifd_handle_iface(), netifd_handle_set_state(), netifd_iface_handle_device(), netifd_netns_updown(), ocistate_cb(), parse_address_item(), parseOCI(), parseOCIcapabilities(), parseOCIdevices(), parseOCIhook(), parseOCIhooks(), parseOCIlinux(), parseOCIlinuxcgroups(), parseOCIlinuxcgroups_devices(), parseOCIlinuxcgroups_legacy_blockio(), parseOCIlinuxcgroups_legacy_cpu(), parseOCIlinuxcgroups_legacy_memory(), parseOCIlinuxcgroups_legacy_pids(), parseOCIlinuxns(), parseOCIlinuxseccomp(), parseOCImount(), parseOCIprocess(), parseOCIprocessuser(), parseOCIrlimit(), parseOCIroot(), parseOCIuidgidmappings(), proc_signal(), proto_apply_ip_settings(), proto_apply_static_ip_settings(), proto_shell_checkup_attach(), proto_shell_notify(), rc_init(), rc_list(), resolveuuid(), rpc_cgi_password_set(), rpc_file_exec(), rpc_handle_access(), rpc_handle_acl(), rpc_handle_create(), rpc_handle_destroy(), rpc_handle_get(), rpc_handle_list(), rpc_handle_login(), rpc_handle_set(), rpc_handle_unset(), rpc_iwinfo_assoclist(), rpc_iwinfo_open(), rpc_iwinfo_phyname(), rpc_session_from_blob(), rpc_sys_packagelist(), rpc_sys_upgrade_start(), rpc_uci_add(), rpc_uci_apply(), rpc_uci_changes(), rpc_uci_confirm(), rpc_uci_delete(), rpc_uci_getcommon(), rpc_uci_order(), rpc_uci_rename(), rpc_uci_revert_commit(), rpc_uci_rollback(), rpc_uci_set(), service_get_data(), service_handle_delete(), service_handle_event(), service_handle_list(), service_handle_set(), service_handle_signal(), service_handle_state(), service_handle_update(), service_handle_validate(), service_handle_watchdog(), service_validate_add(), settings_add(), simple_device_create(), system_add_gre_tunnel(), system_add_ip6_tunnel(), system_add_ip_tunnel(), system_add_sit_tunnel(), system_add_vti_tunnel(), system_add_vxlan(), system_add_xfrm_tunnel(), sysupgrade(), test_blobmsg(), test_blobmsg_procd_instance(), test_count(), test_count_data_cb(), test_hello(), test_watch(), tunnel_reload(), ubus_auto_sub_event_handler_cb(), ubus_bridge_state(), ubus_set_bridge_config(), ubusd_acl_add_access(), ubusd_acl_file_add(), ubusd_alloc_event_pattern(), ubusd_forward_event(), uxc_boot(), uxc_create(), uxc_delete(), uxc_kill(), uxc_list(), uxc_set(), uxc_state(), validate_firmware_image(), veth_reload(), vlandev_reload(), wait_event_cb(), watch_subscribe_cb(), and watchdog_set().
blobmsg_parse_array()
int blobmsg_parse_array (const struct blobmsg_policy * policy, int policy_len, struct blob_attr ** tb, void * data, unsigned int len)
Definition at line 140 of file blobmsg.c.
{
    struct blob_attr *attr;
    int i = 0;
    memset(tb, 0, policy_len * sizeof(*tb));
    __blob_for_each_attr(attr, data, len) {
        if (policy[i].type != BLOBMSG_TYPE_UNSPEC &&
            blob_id(attr) != policy[i].type)
            continue;
        if (!blobmsg_check_attr_len(attr, false, len))
            return -1;
        if (tb[i])
            continue;
        tb[i++] = attr;
        if (i == policy_len)
            break;
    }
    return 0;
}
References __blob_for_each_attr, blob_id(), blobmsg_check_attr_len(), BLOBMSG_TYPE_UNSPEC, blob_attr::data, and type.
Referenced by blobmsg_parse_array_attr(), fuzz_blobmsg_parse(), handle_if(), handle_makedev(), handle_rm(), json_get_tuple(), and test_blobmsg().
blobmsg_parse_array_attr()
static int blobmsg_parse_array_attr (const struct blobmsg_policy * policy, int policy_len, struct blob_attr ** tb, struct blob_attr * data) inline static
Definition at line 189 of file blobmsg.h.
{
    return blobmsg_parse_array(policy, policy_len, tb, blobmsg_data(data), blobmsg_len(data));
}
References blobmsg_data(), blobmsg_len(), and blobmsg_parse_array().
blobmsg_parse_attr()
static int blobmsg_parse_attr (const struct blobmsg_policy * policy, int policy_len, struct blob_attr ** tb, struct blob_attr * data) inline static
Definition at line 182 of file blobmsg.h.
{
    return blobmsg_parse(policy, policy_len, tb, blobmsg_data(data), blobmsg_len(data));
}
References blobmsg_data(), blobmsg_len(), and blobmsg_parse().
Referenced by config_procd_wireless_interface_cb(), wireless_device_add_process(), wireless_device_create(), wireless_device_notify(), wireless_device_process_kill_all(), wireless_device_set_retry(), wireless_interface_create(), wireless_interface_init_config(), wireless_interface_set_data(), wireless_station_create(), wireless_vlan_create(), wireless_vlan_init_config(), and wireless_vlan_set_data().
blobmsg_printf()
int blobmsg_printf (struct blob_buf * buf, const char * name, const char * format, ...)
Referenced by __vlan_hotplug_op(), __vlandev_hotplug_op(), and bridge_dump_port().
blobmsg_realloc_string_buffer()
void * blobmsg_realloc_string_buffer (struct blob_buf * buf, unsigned int maxlen)
Definition at line 343 of file blobmsg.c.
{
    struct blob_attr *attr = blob_next(buf->head);
    int offset = attr_to_offset(buf, blob_next(buf->head)) + blob_pad_len(attr) - BLOB_COOKIE;
    int required = maxlen + 1 - (buf->buflen - offset);
    if (required <= 0)
        goto out;
    if (!blob_buf_grow(buf, required))
        return NULL;
    attr = blob_next(buf->head);
out:
    return blobmsg_data(attr);
}
References attr_to_offset(), blob_buf_grow(), BLOB_COOKIE, blob_next(), blob_pad_len(), blobmsg_data(), and buf.
Referenced by eval_string().
blobmsg_type()
static int blobmsg_type (const struct blob_attr * attr) inline static
Definition at line 68 of file blobmsg.h.
{
    return blob_id(attr);
}
References blob_id().
blobmsg_vprintf()
int blobmsg_vprintf (struct blob_buf * buf, const char * name, const char * format, va_list arg)
Referenced by __attribute__().
Variable Documentation
__packed
struct blobmsg_hdr __packed