zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/libubox/avl-cmp.c File Reference
avl-cmp.c File Reference
#include <string.h>
#include "avl-cmp.h"
#include "blob.h"
Functions
static int _min (int v1, int v2)
int avl_strcmp (const void *k1, const void *k2, void *ptr)
int avl_blobcmp (const void *k1, const void *k2, void *ptr)
Function Documentation
_min()
static int _min (int v1, int v2) inline static
Definition at line 20 of file avl-cmp.c.
{
    return v1 < v2 ? v1 : v2;
}
Referenced by avl_blobcmp().
avl_blobcmp()
int avl_blobcmp (const void * k1, const void * k2, void * ptr)
Definition at line 32 of file avl-cmp.c.
{
    int len = _min(blob_raw_len(k1), blob_raw_len(k2));
    return memcmp(k1, k2, len);
}
References _min(), and blob_raw_len().
avl_strcmp()
int avl_strcmp (const void * k1, const void * k2, void * ptr)
Definition at line 26 of file avl-cmp.c.
{
    return strcmp(k1, k2);
}
Referenced by __blobmsg_list_init(), __bridge_create(), add_proto_handler(), alias_init(), bonding_create(), bridge_create(), cgroups_init(), dev_init(), init_library_search(), interface_alloc(), interface_init_list(), json_script_init(), kvlist_init(), mount_list_init(), rpc_session_api_init(), rpc_session_grant(), rpc_session_new(), runtime_load(), service_alloc(), service_validate_add(), settings_add(), test_basics(), ubus_init_string_tree(), wireless_device_create(), wireless_init(), and wireless_interface_create().