zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/ustp/config.c File Reference
config.c File Reference
#include <string.h>
#include <libubox/avl-cmp.h>
#include <libubox/utils.h>
#include "config.h"
Functions
AVL_TREE (bridge_config, avl_strcmp, false, NULL)
static uint32_t bridge_config_timestamp (void)
struct bridge_config * bridge_config_get (const char *name, bool create)
void bridge_config_expire (void)
Function Documentation
AVL_TREE()
AVL_TREE (bridge_config , avl_strcmp , false , NULL)
bridge_config_expire()
void bridge_config_expire (void)
Definition at line 55 of file config.c.
{
    struct bridge_config *cfg, *tmp;
    uint32_t ts;
    ts = bridge_config_timestamp();
    avl_for_each_element_safe(&bridge_config, cfg, node, tmp) {
        if (ts - cfg->timestamp < 60)
            continue;
        avl_delete(&bridge_config, &cfg->node);
        free(cfg);
    }
}
References avl_delete(), avl_for_each_element_safe, bridge_config_timestamp(), bridge_config::node, and bridge_config::timestamp.
bridge_config_get()
struct bridge_config * bridge_config_get (const char * name, bool create)
Definition at line 33 of file config.c.
{
    struct bridge_config *cfg;
    char *name_buf;
    cfg = avl_find_element(&bridge_config, name, cfg, node);
    if (cfg)
        goto out;
    if (!create)
        return NULL;
    cfg = calloc_a(sizeof(*cfg), &name_buf, strlen(name) + 1);
    cfg->node.key = strcpy(name_buf, name);
    avl_insert(&bridge_config, &cfg->node);
out:
    cfg->timestamp = bridge_config_timestamp();
    return cfg;
}
References avl_find_element, avl_insert(), bridge_config_timestamp(), calloc_a, avl_node::key, bridge_config::node, and bridge_config::timestamp.
Referenced by ubus_bridge_state(), and ubus_set_bridge_config().
bridge_config_timestamp()
static uint32_t bridge_config_timestamp (void) static
Definition at line 23 of file config.c.
{
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return ts.tv_sec;
}
Referenced by bridge_config_expire(), and bridge_config_get().