zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/rpcd/include/rpcd/session.h File Reference
session.h File Reference
#include <ctype.h>
#include <fcntl.h>
#include <dirent.h>
#include <unistd.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <libubox/avl.h>
#include <libubox/blobmsg_json.h>
Classes
struct rpc_session
struct rpc_session_data
struct rpc_session_acl_scope
struct rpc_session_acl
struct rpc_session_cb
Macros
#define RPC_SID_LEN 32
#define RPC_DEFAULT_SESSION_TIMEOUT 300
#define RPC_DEFAULT_SESSION_ID "00000000000000000000000000000000"
#define RPC_SESSION_DIRECTORY "/var/run/rpcd/sessions"
#define RPC_SESSION_ACL_DIR INSTALL_PREFIX "/share/rpcd/acl.d"
Functions
int rpc_session_api_init (struct ubus_context *ctx)
bool rpc_session_access (const char *sid, const char *scope, const char *object, const char *function)
void rpc_session_create_cb (struct rpc_session_cb *cb)
void rpc_session_destroy_cb (struct rpc_session_cb *cb)
void rpc_session_freeze (void)
void rpc_session_thaw (void)
Variables
char apply_sid [RPC_SID_LEN+1]
Class Documentation
rpc_session
struct rpc_session
Definition at line 41 of file session.h.
Class Members
struct avl_tree acls
struct avl_node avl
struct avl_tree data
char id[RPC_SID_LEN+1]
struct uloop_timeout t
int timeout
rpc_session_data
struct rpc_session_data
Definition at line 52 of file session.h.
Class Members
struct blob_attr attr[]
struct avl_node avl
rpc_session_acl_scope
struct rpc_session_acl_scope
Definition at line 57 of file session.h.
Class Members
struct avl_tree acls
struct avl_node avl
rpc_session_acl
struct rpc_session_acl
Definition at line 62 of file session.h.
Class Members
struct avl_node avl
const char * function
const char * object
int sort_len
rpc_session_cb
struct rpc_session_cb
Definition at line 74 of file session.h.
Class Members
void(*)(struct rpc_session *, void *) cb
struct list_head list
void * priv
Macro Definition Documentation
RPC_DEFAULT_SESSION_ID
#define RPC_DEFAULT_SESSION_ID "00000000000000000000000000000000"
Definition at line 35 of file session.h.
Referenced by rpc_handle_destroy(), rpc_session_api_init(), and rpc_session_freeze().
RPC_DEFAULT_SESSION_TIMEOUT
#define RPC_DEFAULT_SESSION_TIMEOUT 300
Definition at line 34 of file session.h.
Referenced by rpc_handle_create(), and rpc_handle_login().
RPC_SESSION_ACL_DIR
#define RPC_SESSION_ACL_DIR INSTALL_PREFIX "/share/rpcd/acl.d"
Definition at line 37 of file session.h.
Referenced by rpc_login_setup_acls().
RPC_SESSION_DIRECTORY
#define RPC_SESSION_DIRECTORY "/var/run/rpcd/sessions"
Definition at line 36 of file session.h.
Referenced by rpc_session_freeze(), and rpc_session_thaw().
RPC_SID_LEN
#define RPC_SID_LEN 32
Definition at line 33 of file session.h.
Referenced by rpc_session_from_blob(), rpc_uci_apply(), and rpc_validate_sid().
Function Documentation
rpc_session_access()
bool rpc_session_access (const char * sid, const char * scope, const char * object, const char * function)
Definition at line 1364 of file session.c.
{
    struct rpc_session *ses = rpc_session_get(sid);
    if (!ses)
        return false;
    return rpc_session_acl_allowed(ses, scope, object, function);
}
References rpc_session_acl_allowed(), and rpc_session_get().
Referenced by rpc_uci_apply_access(), rpc_uci_changes(), rpc_uci_read_access(), and rpc_uci_write_access().
rpc_session_api_init()
int rpc_session_api_init (struct ubus_context * ctx)
Definition at line 1323 of file session.c.
{
    struct rpc_session *ses;
    static const struct ubus_method session_methods[] = {
        UBUS_METHOD("create",  rpc_handle_create,  new_policy),
        UBUS_METHOD("list",    rpc_handle_list,    sid_policy),
        UBUS_METHOD("grant",   rpc_handle_acl,     acl_policy),
        UBUS_METHOD("revoke",  rpc_handle_acl,     acl_policy),
        UBUS_METHOD("access",  rpc_handle_access,  perm_policy),
        UBUS_METHOD("set",     rpc_handle_set,     set_policy),
        UBUS_METHOD("get",     rpc_handle_get,     get_policy),
        UBUS_METHOD("unset",   rpc_handle_unset,   get_policy),
        UBUS_METHOD("destroy", rpc_handle_destroy, sid_policy),
        UBUS_METHOD("login",   rpc_handle_login,   login_policy),
    };
    static struct ubus_object_type session_type =
        UBUS_OBJECT_TYPE("rpcd-plugin-session", session_methods);
    static struct ubus_object obj = {
        .name = "session",
        .type = &session_type,
        .methods = session_methods,
        .n_methods = ARRAY_SIZE(session_methods),
    };
    avl_init(&sessions, avl_strcmp, false, NULL);
    /* setup the default session */
    ses = rpc_session_new();
    if (ses) {
        strcpy(ses->id, RPC_DEFAULT_SESSION_ID);
        rpc_login_setup_acls(ses, NULL);
        avl_insert(&sessions, &ses->avl);
    }
    return ubus_add_object(ctx, &obj);
}
References acl_policy, ARRAY_SIZE, rpc_session::avl, avl_init(), avl_insert(), avl_strcmp(), ctx, get_policy, rpc_session::id, login_policy, ubus_object_type::methods, new_policy, perm_policy, RPC_DEFAULT_SESSION_ID, rpc_handle_access(), rpc_handle_acl(), rpc_handle_create(), rpc_handle_destroy(), rpc_handle_get(), rpc_handle_list(), rpc_handle_login(), rpc_handle_set(), rpc_handle_unset(), rpc_login_setup_acls(), rpc_session_new(), sessions, set_policy, sid_policy, ubus_add_object(), UBUS_METHOD, and UBUS_OBJECT_TYPE.
Referenced by main().
rpc_session_create_cb()
void rpc_session_create_cb (struct rpc_session_cb * cb)
Definition at line 1375 of file session.c.
{
    if (cb && cb->cb)
        list_add(&cb->list, &create_callbacks);
}
References rpc_session_cb::cb, rpc_session_cb::list, and list_add().
rpc_session_destroy_cb()
void rpc_session_destroy_cb (struct rpc_session_cb * cb)
Definition at line 1381 of file session.c.
{
    if (cb && cb->cb)
        list_add(&cb->list, &destroy_callbacks);
}
References rpc_session_cb::cb, rpc_session_cb::list, and list_add().
Referenced by rpc_uci_api_init().
rpc_session_freeze()
void rpc_session_freeze (void)
Definition at line 1387 of file session.c.
{
    struct stat s;
    struct rpc_session *ses;
    char path[PATH_MAX];
    if (stat(RPC_SESSION_DIRECTORY, &s))
        mkdir(RPC_SESSION_DIRECTORY, 0700);
    avl_for_each_element(&sessions, ses, avl) {
        /* skip default session */
        if (!strcmp(ses->id, RPC_DEFAULT_SESSION_ID))
            continue;
        snprintf(path, sizeof(path) - 1, RPC_SESSION_DIRECTORY "/%s", ses->id);
        rpc_session_to_blob(ses, false);
        rpc_blob_to_file(path, buf.head);
    }
}
References rpc_session::avl, avl_for_each_element, buf, blob_buf::head, rpc_session::id, path, rpc_blob_to_file(), RPC_DEFAULT_SESSION_ID, RPC_SESSION_DIRECTORY, rpc_session_to_blob(), and sessions.
Referenced by handle_signal().
rpc_session_thaw()
void rpc_session_thaw (void)
Definition at line 1407 of file session.c.
{
    DIR *d;
    char path[PATH_MAX];
    struct dirent *e;
    struct blob_attr *attr;
    struct uci_context *uci;
    d = opendir(RPC_SESSION_DIRECTORY);
    if (!d)
        return;
    uci = uci_alloc_context();
    if (!uci)
        return;
    while ((e = readdir(d)) != NULL) {
        if (!rpc_validate_sid(e->d_name))
            continue;
        snprintf(path, sizeof(path) - 1,
                 RPC_SESSION_DIRECTORY "/%s", e->d_name);
        attr = rpc_blob_from_file(path);
        if (attr) {
            rpc_session_from_blob(uci, attr);
            free(attr);
        }
        unlink(path);
    }
    closedir(d);
    uci_free_context(uci);
}
References path, rpc_blob_from_file(), RPC_SESSION_DIRECTORY, rpc_session_from_blob(), and rpc_validate_sid().
Referenced by main().
Variable Documentation
apply_sid
char apply_sid[RPC_SID_LEN+1] extern
Definition at line 34 of file uci.c.
Referenced by rpc_reclaim_apply_session(), rpc_uci_apply(), rpc_uci_confirm(), rpc_uci_do_rollback(), rpc_uci_revert_commit(), and rpc_uci_rollback().