zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/ubus/libubus-io.c File Reference
libubus-io.c File Reference
#include <sys/types.h>
#include <sys/uio.h>
#include <sys/socket.h>
#include <unistd.h>
#include <fcntl.h>
#include <poll.h>
#include <libubox/usock.h>
#include <libubox/blob.h>
#include <libubox/blobmsg.h>
#include "libubus.h"
#include "libubus-internal.h"
Macros
#define _GNU_SOURCE
#define STATIC_IOV(_var)
#define UBUS_MSGBUF_REDUCTION_INTERVAL 16
Functions
__hidden struct blob_attr ** ubus_parse_msg (struct blob_attr *msg, size_t len)
static void wait_data (int fd, bool write)
static int writev_retry (int fd, struct iovec *iov, int iov_len, int sock_fd)
int __hidden ubus_send_msg (struct ubus_context *ctx, uint32_t seq, struct blob_attr *msg, int cmd, uint32_t peer, int fd)
static int recv_retry (struct ubus_context *ctx, struct iovec *iov, bool wait, int *recv_fd)
bool ubus_validate_hdr (struct ubus_msghdr *hdr)
static bool alloc_msg_buf (struct ubus_context *ctx, int len)
static bool get_next_msg (struct ubus_context *ctx, int *recv_fd)
void __hidden ubus_handle_data (struct uloop_fd *u, unsigned int events)
void __hidden ubus_poll_data (struct ubus_context *ctx, int timeout)
static void ubus_auto_sub_lookup (struct ubus_context *ctx, struct ubus_object_data *obj, void *priv)
static void ubus_refresh_auto_subscribe (struct ubus_context *ctx)
static void ubus_refresh_state (struct ubus_context *ctx)
int ubus_reconnect (struct ubus_context *ctx, const char *path)
Variables
static const struct blob_attr_info ubus_policy [UBUS_ATTR_MAX]
static struct blob_attr * attrbuf [UBUS_ATTR_MAX]
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 14 of file libubus-io.c.
STATIC_IOV
#define STATIC_IOV (_var)
Value:
{ .iov_base = (char *) &(_var), .iov_len = sizeof(_var) }
Definition at line 30 of file libubus-io.c.
Referenced by get_next_msg(), and ubus_send_msg().
UBUS_MSGBUF_REDUCTION_INTERVAL
#define UBUS_MSGBUF_REDUCTION_INTERVAL 16
Definition at line 32 of file libubus-io.c.
Referenced by alloc_msg_buf().
Function Documentation
alloc_msg_buf()
static bool alloc_msg_buf (struct ubus_context * ctx, int len) static
Definition at line 240 of file libubus-io.c.
{
    void *ptr;
    int buf_len = ctx->msgbuf_data_len;
    int rem;
    if (!ctx->msgbuf.data)
        buf_len = 0;
    rem = (len % UBUS_MSG_CHUNK_SIZE);
    if (rem > 0)
        len += UBUS_MSG_CHUNK_SIZE - rem;
    if (len < buf_len &&
        ++ctx->msgbuf_reduction_counter > UBUS_MSGBUF_REDUCTION_INTERVAL) {
        ctx->msgbuf_reduction_counter = 0;
        buf_len = 0;
    }
    if (len <= buf_len)
        return true;
    ptr = realloc(ctx->msgbuf.data, len);
    if (!ptr)
        return false;
    ctx->msgbuf.data = ptr;
    ctx->msgbuf_data_len = len;
    return true;
}
References ctx, ubus_msghdr_buf::data, ubus_context::msgbuf, ubus_context::msgbuf_data_len, ubus_context::msgbuf_reduction_counter, UBUS_MSG_CHUNK_SIZE, and UBUS_MSGBUF_REDUCTION_INTERVAL.
Referenced by get_next_msg().
get_next_msg()
static bool get_next_msg (struct ubus_context * ctx, int * recv_fd) static
Definition at line 271 of file libubus-io.c.
{
    struct {
        struct ubus_msghdr hdr;
        struct blob_attr data;
    } hdrbuf;
    struct iovec iov = STATIC_IOV(hdrbuf);
    int len;
    int r;
    /* receive header + start attribute */
    r = recv_retry(ctx, &iov, false, recv_fd);
    if (r <= 0) {
        if (r < 0)
            ctx->sock.eof = true;
        return false;
    }
    hdrbuf.hdr.seq = be16_to_cpu(hdrbuf.hdr.seq);
    hdrbuf.hdr.peer = be32_to_cpu(hdrbuf.hdr.peer);
    if (!ubus_validate_hdr(&hdrbuf.hdr))
        return false;
    len = blob_raw_len(&hdrbuf.data);
    if (!alloc_msg_buf(ctx, len))
        return false;
    memcpy(&ctx->msgbuf.hdr, &hdrbuf.hdr, sizeof(hdrbuf.hdr));
    memcpy(ctx->msgbuf.data, &hdrbuf.data, sizeof(hdrbuf.data));
    iov.iov_base = (char *)ctx->msgbuf.data + sizeof(hdrbuf.data);
    iov.iov_len = blob_len(ctx->msgbuf.data);
    if (iov.iov_len > 0 &&
        recv_retry(ctx, &iov, true, NULL) <= 0)
        return false;
    return true;
}
References alloc_msg_buf(), be16_to_cpu, be32_to_cpu, blob_len(), blob_raw_len(), ctx, blob_attr::data, ubus_msghdr_buf::data, uloop_fd::eof, ubus_msghdr_buf::hdr, ubus_context::msgbuf, r, recv_retry(), ubus_context::sock, STATIC_IOV, and ubus_validate_hdr().
Referenced by ubus_handle_data().
recv_retry()
static int recv_retry (struct ubus_context * ctx, struct iovec * iov, bool wait, int * recv_fd) static
Definition at line 158 of file libubus-io.c.
{
    uint8_t fd_buf[CMSG_SPACE(sizeof(int))] = { 0 };
    struct msghdr msghdr = { 0 };
    struct cmsghdr *cmsg;
    int total = 0;
    int bytes;
    int *pfd;
    int fd;
    fd = ctx->sock.fd;
    msghdr.msg_iov = iov,
    msghdr.msg_iovlen = 1,
    msghdr.msg_control = fd_buf;
    msghdr.msg_controllen = sizeof(fd_buf);
    cmsg = CMSG_FIRSTHDR(&msghdr);
    cmsg->cmsg_type = SCM_RIGHTS;
    cmsg->cmsg_level = SOL_SOCKET;
    cmsg->cmsg_len = CMSG_LEN(sizeof(int));
    pfd = (int *) CMSG_DATA(cmsg);
    while (iov->iov_len > 0) {
        if (recv_fd) {
            msghdr.msg_control = fd_buf;
            msghdr.msg_controllen = cmsg->cmsg_len;
        } else {
            msghdr.msg_control = NULL;
            msghdr.msg_controllen = 0;
        }
        *pfd = -1;
        bytes = recvmsg(fd, &msghdr, 0);
        if (!bytes)
            return -1;
        if (bytes < 0) {
            bytes = 0;
            if (errno == EINTR)
                continue;
            if (errno != EAGAIN)
                return -1;
        }
        if (!wait && !bytes)
            return 0;
        if (recv_fd)
            *recv_fd = *pfd;
        recv_fd = NULL;
        wait = true;
        iov->iov_len -= bytes;
        iov->iov_base += bytes;
        total += bytes;
        if (iov->iov_len > 0)
            wait_data(fd, false);
    }
    return total;
}
References ctx, uloop_fd::fd, ubus_context::sock, and wait_data().
Referenced by get_next_msg().
ubus_auto_sub_lookup()
static void ubus_auto_sub_lookup (struct ubus_context * ctx, struct ubus_object_data * obj, void * priv) static
Definition at line 348 of file libubus-io.c.
{
    struct ubus_subscriber *s;
    list_for_each_entry(s, &ctx->auto_subscribers, list)
        if (s->new_obj_cb(ctx, s, obj->path))
            ubus_subscribe(ctx, s, obj->id);
}
References ubus_context::auto_subscribers, ctx, ubus_object::id, ubus_subscriber::list, list_for_each_entry, ubus_subscriber::new_obj_cb, ubus_subscriber::obj, ubus_object::path, and ubus_subscribe().
Referenced by ubus_refresh_auto_subscribe().
ubus_handle_data()
void __hidden ubus_handle_data (struct uloop_fd * u, unsigned int events)
Definition at line 312 of file libubus-io.c.
{
    struct ubus_context *ctx = container_of(u, struct ubus_context, sock);
    int recv_fd = -1;
    while (1) {
        if (!ctx->stack_depth)
            ctx->pending_timer.cb(&ctx->pending_timer);
        if (!get_next_msg(ctx, &recv_fd))
            break;
        ubus_process_msg(ctx, &ctx->msgbuf, recv_fd);
        if (uloop_cancelling() || ctx->cancel_poll)
            break;
    }
    if (!ctx->stack_depth)
        ctx->pending_timer.cb(&ctx->pending_timer);
    if (u->eof)
        ctx->connection_lost(ctx);
}
References ubus_context::cancel_poll, uloop_timeout::cb, ubus_context::connection_lost, container_of, ctx, uloop_fd::eof, get_next_msg(), ubus_context::msgbuf, ubus_context::pending_timer, ubus_context::sock, ubus_context::stack_depth, ubus_process_msg(), and uloop_cancelling().
Referenced by ubus_connect_ctx(), and ubus_poll_data().
ubus_parse_msg()
__hidden struct blob_attr ** ubus_parse_msg (struct blob_attr * msg, size_t len)
Definition at line 46 of file libubus-io.c.
{
    blob_parse_untrusted(msg, len, attrbuf, ubus_policy, UBUS_ATTR_MAX);
    return attrbuf;
}
ubus_poll_data()
void __hidden ubus_poll_data (struct ubus_context * ctx, int timeout)
Definition at line 335 of file libubus-io.c.
{
    struct pollfd pfd = {
        .fd = ctx->sock.fd,
        .events = POLLIN | POLLERR,
    };
    ctx->cancel_poll = false;
    poll(&pfd, 1, timeout ? timeout : -1);
    ubus_handle_data(&ctx->sock, ULOOP_READ);
}
References ubus_context::cancel_poll, ctx, uloop_fd::fd, ubus_context::sock, timeout, ubus_handle_data(), and ULOOP_READ.
Referenced by ubus_complete_request().
ubus_reconnect()
int ubus_reconnect (struct ubus_context * ctx, const char * path)
Definition at line 395 of file libubus-io.c.
{
    struct {
        struct ubus_msghdr hdr;
        struct blob_attr data;
    } hdr;
    struct blob_attr *buf;
    int ret = UBUS_STATUS_UNKNOWN_ERROR;
    if (!path)
        path = UBUS_UNIX_SOCKET;
    if (ctx->sock.fd >= 0) {
        if (ctx->sock.registered)
            uloop_fd_delete(&ctx->sock);
        close(ctx->sock.fd);
    }
    ctx->sock.eof = false;
    ctx->sock.error = false;
    ctx->sock.fd = usock(USOCK_UNIX, path, NULL);
    if (ctx->sock.fd < 0)
        return UBUS_STATUS_CONNECTION_FAILED;
    if (read(ctx->sock.fd, &hdr, sizeof(hdr)) != sizeof(hdr))
        goto out_close;
    if (!ubus_validate_hdr(&hdr.hdr))
        goto out_close;
    if (hdr.hdr.type != UBUS_MSG_HELLO)
        goto out_close;
    buf = calloc(1, blob_raw_len(&hdr.data));
    if (!buf)
        goto out_close;
    memcpy(buf, &hdr.data, sizeof(hdr.data));
    if (read(ctx->sock.fd, blob_data(buf), blob_len(buf)) != (ssize_t) blob_len(buf))
        goto out_free;
    ctx->local_id = hdr.hdr.peer;
    if (!ctx->local_id)
        goto out_free;
    ret = UBUS_STATUS_OK;
    fcntl(ctx->sock.fd, F_SETFL, fcntl(ctx->sock.fd, F_GETFL) | O_NONBLOCK | O_CLOEXEC);
    ubus_refresh_state(ctx);
out_free:
    free(buf);
out_close:
    if (ret)
        close(ctx->sock.fd);
    return ret;
}
References blob_data(), blob_len(), blob_raw_len(), buf, ctx, uloop_fd::eof, uloop_fd::error, uloop_fd::fd, ubus_context::local_id, path, uloop_fd::registered, ubus_context::sock, UBUS_MSG_HELLO, ubus_refresh_state(), UBUS_STATUS_CONNECTION_FAILED, UBUS_STATUS_OK, UBUS_STATUS_UNKNOWN_ERROR, ubus_validate_hdr(), uloop_fd_delete(), usock(), and USOCK_UNIX.
Referenced by netifd_ubus_reconnect_timer(), ubus_auto_reconnect_cb(), ubus_connect_ctx(), and ubus_reconnect_cb().
ubus_refresh_auto_subscribe()
static void ubus_refresh_auto_subscribe (struct ubus_context * ctx) static
Definition at line 359 of file libubus-io.c.
{
    struct ubus_event_handler *ev = &ctx->auto_subscribe_event_handler;
    if (list_empty(&ctx->auto_subscribers))
        return;
    ubus_register_event_handler(ctx, ev, "ubus.object.add");
    ubus_lookup(ctx, NULL, ubus_auto_sub_lookup, NULL);
}
References ubus_context::auto_subscribe_event_handler, ubus_context::auto_subscribers, ctx, list_empty(), ubus_auto_sub_lookup(), ubus_lookup(), and ubus_register_event_handler().
Referenced by ubus_refresh_state().
ubus_refresh_state()
static void ubus_refresh_state (struct ubus_context * ctx) static
Definition at line 371 of file libubus-io.c.
{
    struct ubus_object *obj, *tmp;
    struct ubus_object **objs;
    int n, i = 0;
    /* clear all type IDs, they need to be registered again */
    avl_for_each_element(&ctx->objects, obj, avl)
        if (obj->type)
            obj->type->id = 0;
    /* push out all objects again */
    objs = alloca(ctx->objects.count * sizeof(*objs));
    avl_remove_all_elements(&ctx->objects, obj, avl, tmp) {
        objs[i++] = obj;
        obj->id = 0;
    }
    for (n = i, i = 0; i < n; i++)
        ubus_add_object(ctx, objs[i]);
    ubus_refresh_auto_subscribe(ctx);
}
References ubus_object::avl, avl_for_each_element, avl_remove_all_elements, avl_tree::count, ctx, ubus_object::id, ubus_object_type::id, ubus_context::objects, ubus_object::type, ubus_add_object(), and ubus_refresh_auto_subscribe().
Referenced by ubus_reconnect().
ubus_send_msg()
int __hidden ubus_send_msg (struct ubus_context * ctx, uint32_t seq, struct blob_attr * msg, int cmd, uint32_t peer, int fd)
Definition at line 126 of file libubus-io.c.
{
    struct ubus_msghdr hdr;
    struct iovec iov[2] = {
        STATIC_IOV(hdr)
    };
    int ret;
    hdr.version = 0;
    hdr.type = cmd;
    hdr.seq = cpu_to_be16(seq);
    hdr.peer = cpu_to_be32(peer);
    if (!msg) {
        blob_buf_init(&b, 0);
        msg = b.head;
    }
    iov[1].iov_base = (char *) msg;
    iov[1].iov_len = blob_raw_len(msg);
    ret = writev_retry(ctx->sock.fd, iov, ARRAY_SIZE(iov), fd);
    if (ret < 0)
        ctx->sock.eof = true;
    if (fd >= 0)
        close(fd);
    return ret;
}
References ARRAY_SIZE, b, blob_buf_init(), blob_raw_len(), cmd, cpu_to_be16, cpu_to_be32, ctx, uloop_fd::eof, uloop_fd::fd, blob_buf::head, ubus_msghdr::peer, ubus_msghdr::seq, ubus_context::sock, STATIC_IOV, ubus_msghdr::type, ubus_msghdr::version, and writev_retry().
Referenced by __ubus_start_request(), ubus_complete_deferred_request(), and ubus_send_reply().
ubus_validate_hdr()
bool ubus_validate_hdr (struct ubus_msghdr * hdr)
Definition at line 224 of file libubus-io.c.
{
    struct blob_attr *data = (struct blob_attr *) (hdr + 1);
    if (hdr->version != 0)
        return false;
    if (blob_raw_len(data) < sizeof(*data))
        return false;
    if (blob_pad_len(data) > UBUS_MAX_MSGLEN)
        return false;
    return true;
}
References blob_pad_len(), blob_raw_len(), blob_attr::data, and ubus_msghdr::version.
Referenced by _ubus_validate_hdr(), get_next_msg(), and ubus_reconnect().
wait_data()
static void wait_data (int fd, bool write) static
Definition at line 52 of file libubus-io.c.
{
    struct pollfd pfd = { .fd = fd };
    pfd.events = write ? POLLOUT : POLLIN;
    poll(&pfd, 1, -1);
}
Referenced by recv_retry(), and writev_retry().
writev_retry()
static int writev_retry (int fd, struct iovec * iov, int iov_len, int sock_fd) static
Definition at line 60 of file libubus-io.c.
{
    uint8_t fd_buf[CMSG_SPACE(sizeof(int))] = { 0 };
    struct msghdr msghdr = { 0 };
    struct cmsghdr *cmsg;
    int len = 0;
    int *pfd;
    msghdr.msg_iov = iov,
    msghdr.msg_iovlen = iov_len,
    msghdr.msg_control = fd_buf;
    msghdr.msg_controllen = sizeof(fd_buf);
    cmsg = CMSG_FIRSTHDR(&msghdr);
    cmsg->cmsg_type = SCM_RIGHTS;
    cmsg->cmsg_level = SOL_SOCKET;
    cmsg->cmsg_len = CMSG_LEN(sizeof(int));
    pfd = (int *) CMSG_DATA(cmsg);
    msghdr.msg_controllen = cmsg->cmsg_len;
    do {
        ssize_t cur_len;
        if (sock_fd < 0) {
            msghdr.msg_control = NULL;
            msghdr.msg_controllen = 0;
        } else {
            *pfd = sock_fd;
        }
        cur_len = sendmsg(fd, &msghdr, 0);
        if (cur_len < 0) {
            switch(errno) {
            case EAGAIN:
                wait_data(fd, true);
                break;
            case EINTR:
                break;
            default:
                return -1;
            }
            continue;
        }
        if (len > 0)
            sock_fd = -1;
        len += cur_len;
        while (cur_len >= (ssize_t) iov->iov_len) {
            cur_len -= iov->iov_len;
            iov_len--;
            iov++;
            if (!iov_len)
                return len;
        }
        iov->iov_base += cur_len;
        iov->iov_len -= cur_len;
        msghdr.msg_iov = iov;
        msghdr.msg_iovlen = iov_len;
    } while (1);
    /* Should never reach here */
    return -1;
}
References wait_data().
Referenced by ubus_send_msg().
Variable Documentation
attrbuf
struct blob_attr* attrbuf[UBUS_ATTR_MAX] static
Definition at line 44 of file libubus-io.c.
Referenced by ubus_add_object_cb(), ubus_get_status(), ubus_parse_msg(), ubus_process_invoke(), ubus_process_notify(), ubus_process_obj_msg(), ubus_process_unsubscribe(), and ubus_remove_object_cb().
ubus_policy
const struct blob_attr_info ubus_policy[UBUS_ATTR_MAX] static
Initial value:
= {
    [UBUS_ATTR_STATUS] = { .type = BLOB_ATTR_INT32 },
    [UBUS_ATTR_OBJID] = { .type = BLOB_ATTR_INT32 },
    [UBUS_ATTR_OBJPATH] = { .type = BLOB_ATTR_STRING },
    [UBUS_ATTR_METHOD] = { .type = BLOB_ATTR_STRING },
    [UBUS_ATTR_ACTIVE] = { .type = BLOB_ATTR_INT8 },
    [UBUS_ATTR_NO_REPLY] = { .type = BLOB_ATTR_INT8 },
    [UBUS_ATTR_SUBSCRIBERS] = { .type = BLOB_ATTR_NESTED },
}
Definition at line 34 of file libubus-io.c.
{
    [UBUS_ATTR_STATUS] = { .type = BLOB_ATTR_INT32 },
    [UBUS_ATTR_OBJID] = { .type = BLOB_ATTR_INT32 },
    [UBUS_ATTR_OBJPATH] = { .type = BLOB_ATTR_STRING },
    [UBUS_ATTR_METHOD] = { .type = BLOB_ATTR_STRING },
    [UBUS_ATTR_ACTIVE] = { .type = BLOB_ATTR_INT8 },
    [UBUS_ATTR_NO_REPLY] = { .type = BLOB_ATTR_INT8 },
    [UBUS_ATTR_SUBSCRIBERS] = { .type = BLOB_ATTR_NESTED },
};
Referenced by ubus_parse_msg().