zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/ustp/main.c File Reference
main.c File Reference
#include <config.h>
#include <unistd.h>
#include <syslog.h>
#include <signal.h>
#include <stdbool.h>
#include <string.h>
#include <sys/types.h>
#include <libubox/uloop.h>
#include "bridge_ctl.h"
#include "netif_utils.h"
#include "packet.h"
#include "log.h"
#include "mstp.h"
#include "driver.h"
#include "bridge_track.h"
#include "worker.h"
#include "ubus.h"
#include <stdarg.h>
#include <time.h>
Macros
#define APP_NAME "ustpd"
Functions
int main (int argc, char *argv[])
static void vDprintf (int level, const char *fmt, va_list ap)
void Dprintf (int level, const char *fmt,...)
Variables
static int print_to_syslog = 1
int log_level = LOG_LEVEL_DEFAULT
Macro Definition Documentation
APP_NAME
#define APP_NAME "ustpd"
Definition at line 49 of file main.c.
Referenced by main().
Function Documentation
Dprintf()
void Dprintf (int level, const char * fmt, ...)
Definition at line 129 of file main.c.
{
    va_list ap;
    va_start(ap, fmt);
    vDprintf(level, fmt, ap);
    va_end(ap);
}
References vDprintf().
main()
int main (int argc, char * argv[])
Definition at line 55 of file main.c.
{
    int c;
    while((c = getopt(argc, argv, "sv:")) != -1) {
        switch (c) {
        case 's':
            print_to_syslog = 0;
            break;
        case 'v': {
            char *end;
            long l;
            l = strtoul(optarg, &end, 0);
            if(*optarg == 0 || *end != 0 || l > LOG_LEVEL_MAX) {
                ERROR("Invalid loglevel %s", optarg);
                exit(1);
            }
            log_level = l;
            break;
        }
        default:
            return -1;
        }
    }
    if (print_to_syslog)
        openlog(APP_NAME, LOG_PID, LOG_DAEMON);
    uloop_init();
    TST(worker_init() == 0, -1);
    TST(packet_sock_init() == 0, -1);
    TST(netsock_init() == 0, -1);
    TST(init_bridge_ops() == 0, -1);
    ustp_ubus_init();
    uloop_run();
    bridge_track_fini();
    worker_cleanup();
    ustp_ubus_exit();
    uloop_done();
    return 0;
}
References APP_NAME, bridge_track_fini(), ERROR, init_bridge_ops(), log_level, LOG_LEVEL_MAX, netsock_init(), packet_sock_init(), print_to_syslog, TST, uloop_done(), uloop_init(), uloop_run(), ustp_ubus_exit(), ustp_ubus_init(), worker_cleanup(), and worker_init().
vDprintf()
static void vDprintf (int level, const char * fmt, va_list ap) static
Definition at line 105 of file main.c.
{
    if(level > log_level)
        return;
    if(!print_to_syslog)
    {
        char logbuf[256];
        logbuf[255] = 0;
        time_t clock;
        struct tm *local_tm;
        time(&clock);
        local_tm = localtime(&clock);
        int l = strftime(logbuf, sizeof(logbuf) - 1, "%F %T ", local_tm);
        vsnprintf(logbuf + l, sizeof(logbuf) - l - 1, fmt, ap);
        printf("%s\n", logbuf);
        fflush(stdout);
    }
    else
    {
        vsyslog((level <= LOG_LEVEL_INFO) ? LOG_INFO : LOG_DEBUG, fmt, ap);
    }
}
References log_level, LOG_LEVEL_INFO, and print_to_syslog.
Referenced by Dprintf().
Variable Documentation
log_level
int log_level = LOG_LEVEL_DEFAULT
Definition at line 52 of file main.c.
print_to_syslog
int print_to_syslog = 1 static
Definition at line 51 of file main.c.
Referenced by main(), and vDprintf().