zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/initd/early.c File Reference
early.c File Reference
#include <sys/mount.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/sysmacros.h>
#include <stdio.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdlib.h>
#include "../utils/utils.h"
#include "init.h"
#include "../libc-compat.h"
#include "../container.h"
Functions
static void early_dev (void)
static void early_console (const char *dev)
static void early_mounts (void)
static void early_env (void)
void early (void)
Function Documentation
early()
void early (void)
Definition at line 91 of file early.c.
{
    if (getpid() != 1)
        return;
    early_mounts();
    early_env();
    LOG("Console is alive\n");
}
References early_env(), early_mounts(), and LOG.
Referenced by main().
early_console()
static void early_console (const char * dev) static
Definition at line 38 of file early.c.
{
    struct stat s;
    if (stat(dev, &s)) {
        ERROR("Failed to stat %s: %m\n", dev);
        return;
    }
    if (patch_stdio(dev)) {
        ERROR("Failed to setup i/o redirection\n");
        return;
    }
    fcntl(STDERR_FILENO, F_SETFL, fcntl(STDERR_FILENO, F_GETFL) | O_NONBLOCK);
}
References ERROR, and patch_stdio().
Referenced by early_mounts().
early_dev()
static void early_dev (void) static
Definition at line 31 of file early.c.
{
    mkdev("*", 0600);
    mknod("/dev/null", 0666, makedev(1, 3));
}
References makedev, and mkdev().
Referenced by early_mounts().
early_env()
static void early_env (void) static
Definition at line 85 of file early.c.
{
    setenv("PATH", EARLY_PATH, 1);
}
References EARLY_PATH.
Referenced by early().
early_mounts()
static void early_mounts (void) static
Definition at line 56 of file early.c.
{
    unsigned int oldumask = umask(0);
    if (!is_container()) {
        mount("proc", "/proc", "proc", MS_NOATIME | MS_NODEV | MS_NOEXEC | MS_NOSUID, NULL);
        mount("sysfs", "/sys", "sysfs", MS_NOATIME | MS_NODEV | MS_NOEXEC | MS_NOSUID, NULL);
        mount("efivars", "/sys/firmware/efi/efivars", "efivarfs", MS_NOATIME | MS_NODEV | MS_NOEXEC | MS_NOSUID, NULL);
        mount("cgroup2", "/sys/fs/cgroup", "cgroup2",  MS_NODEV | MS_NOEXEC | MS_NOSUID | MS_RELATIME, "nsdelegate");
        mount("tmpfs", "/dev", "tmpfs", MS_NOATIME | MS_NOEXEC | MS_NOSUID, "mode=0755,size=512K");
        ignore(symlink("/tmp/shm", "/dev/shm"));
        mkdir("/dev/pts", 0755);
        mount("devpts", "/dev/pts", "devpts", MS_NOATIME | MS_NOEXEC | MS_NOSUID, NULL);
        early_dev();
    }
    early_console("/dev/console");
    mount("tmpfs", "/tmp", "tmpfs", MS_NOSUID | MS_NODEV | MS_NOATIME, "mode=01777");
    mkdir("/tmp/shm", 01777);
    mkdir("/tmp/run", 0755);
    mkdir("/tmp/lock", 0755);
    mkdir("/tmp/state", 0755);
    umask(oldumask);
}
References early_console(), early_dev(), ignore, and is_container().
Referenced by early().