zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/rcS.h File Reference
rcS.h File Reference
#include <libubox/runqueue.h>
Functions
int rcS (char *pattern, char *param, void(*q_empty)(struct runqueue *))
int rc (const char *file, char *param)
Function Documentation
rc()
int rc (const char * file, char * param) extern
Definition at line 191 of file rcS.c.
{
    return _rc(&r, "/etc/init.d", file, "", param);
}
References _rc(), initd::file, initd::param, and r.
Referenced by inotify_read_handler(), inotify_read_handler(), service_update(), test_count_data_cb(), ubus_invoke_fd(), ubusd_handle_lookup(), and vlandev_qos_mapping_list_apply().
rcS()
int rcS (char * pattern, char * param, void(* q_empty)(struct runqueue *)) extern
Definition at line 182 of file rcS.c.
{
    runqueue_init(&q);
    q.empty_cb = q_empty;
    q.max_running_tasks = 1;
    return _rc(&q, "/etc/rc.d", pattern, "*", param);
}
References _rc(), runqueue::empty_cb, runqueue::max_running_tasks, initd::param, q, q_empty(), and runqueue_init().
Referenced by runrc().