zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/netifd/macvlan.c File Reference
macvlan.c File Reference
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <assert.h>
#include <errno.h>
#include "netifd.h"
#include "device.h"
#include "interface.h"
#include "system.h"
Classes
struct macvlan_device
Enumerations
enum { MACVLAN_ATTR_IFNAME , MACVLAN_ATTR_MACADDR , MACVLAN_ATTR_MODE , __MACVLAN_ATTR_MAX }
Functions
static void macvlan_base_cb (struct device_user *dev, enum device_event ev)
static int macvlan_set_down (struct macvlan_device *mvdev)
static int macvlan_set_up (struct macvlan_device *mvdev)
static int macvlan_set_state (struct device *dev, bool up)
static void macvlan_free (struct device *dev)
static void macvlan_dump_info (struct device *dev, struct blob_buf *b)
static void macvlan_config_init (struct device *dev)
static void macvlan_apply_settings (struct macvlan_device *mvdev, struct blob_attr **tb)
static enum dev_change_type macvlan_reload (struct device *dev, struct blob_attr *attr)
static struct device * macvlan_create (const char *name, struct device_type *devtype, struct blob_attr *attr)
static void __init macvlan_device_type_init (void)
Variables
static const struct blobmsg_policy macvlan_attrs [__MACVLAN_ATTR_MAX]
static const struct uci_blob_param_list macvlan_attr_list
static struct device_type macvlan_device_type
Class Documentation
macvlan_device
struct macvlan_device
Definition at line 47 of file macvlan.c.
Class Members
struct macvlan_config config
struct blob_attr * config_data
struct device dev
struct blob_attr * ifname
struct device_user parent
device_state_cb set_state
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
MACVLAN_ATTR_IFNAME
MACVLAN_ATTR_MACADDR
MACVLAN_ATTR_MODE
__MACVLAN_ATTR_MAX
Definition at line 26 of file macvlan.c.
     {
    MACVLAN_ATTR_IFNAME,
    MACVLAN_ATTR_MACADDR,
    MACVLAN_ATTR_MODE,
    __MACVLAN_ATTR_MAX
};
Function Documentation
macvlan_apply_settings()
static void macvlan_apply_settings (struct macvlan_device * mvdev, struct blob_attr ** tb) static
Definition at line 160 of file macvlan.c.
{
    struct macvlan_config *cfg = &mvdev->config;
    struct blob_attr *cur;
    struct ether_addr *ea;
    cfg->flags = 0;
    cfg->mode = NULL;
    if ((cur = tb[MACVLAN_ATTR_MACADDR])) {
        ea = ether_aton(blobmsg_data(cur));
        if (ea) {
            memcpy(cfg->macaddr, ea, 6);
            cfg->flags |= MACVLAN_OPT_MACADDR;
        }
    }
    if ((cur = tb[MACVLAN_ATTR_MODE]))
        cfg->mode = blobmsg_data(cur);
}
References blobmsg_data(), macvlan_device::config, macvlan_config::flags, macvlan_config::macaddr, MACVLAN_ATTR_MACADDR, MACVLAN_ATTR_MODE, MACVLAN_OPT_MACADDR, and macvlan_config::mode.
Referenced by macvlan_reload().
macvlan_base_cb()
static void macvlan_base_cb (struct device_user * dev, enum device_event ev) static
Definition at line 59 of file macvlan.c.
{
    struct macvlan_device *mvdev = container_of(dev, struct macvlan_device, parent);
    switch (ev) {
    case DEV_EVENT_ADD:
        device_set_present(&mvdev->dev, true);
        break;
    case DEV_EVENT_REMOVE:
        device_set_present(&mvdev->dev, false);
        break;
    default:
        return;
    }
}
References container_of, macvlan_device::dev, DEV_EVENT_ADD, DEV_EVENT_REMOVE, device_set_present, and macvlan_device::parent.
Referenced by macvlan_create().
macvlan_config_init()
static void macvlan_config_init (struct device * dev) static
Definition at line 147 of file macvlan.c.
{
    struct macvlan_device *mvdev;
    struct device *basedev = NULL;
    mvdev = container_of(dev, struct macvlan_device, dev);
    if (mvdev->ifname)
        basedev = device_get(blobmsg_data(mvdev->ifname), true);
    device_add_user(&mvdev->parent, basedev);
}
References blobmsg_data(), container_of, device_add_user(), device_get(), macvlan_device::ifname, and macvlan_device::parent.
Referenced by macvlan_reload().
macvlan_create()
static struct device * macvlan_create (const char * name, struct device_type * devtype, struct blob_attr * attr) static
Definition at line 226 of file macvlan.c.
{
    struct macvlan_device *mvdev;
    struct device *dev = NULL;
    mvdev = calloc(1, sizeof(*mvdev));
    if (!mvdev)
        return NULL;
    dev = &mvdev->dev;
    if (device_init(dev, devtype, name) < 0) {
        device_cleanup(dev);
        free(mvdev);
        return NULL;
    }
    dev->config_pending = true;
    mvdev->set_state = dev->set_state;
    dev->set_state = macvlan_set_state;
    dev->hotplug_ops = NULL;
    mvdev->parent.cb = macvlan_base_cb;
    macvlan_reload(dev, attr);
    return dev;
}
References device_user::cb, device::config_pending, macvlan_device::dev, device_cleanup(), device_init(), device::hotplug_ops, macvlan_base_cb(), macvlan_reload(), macvlan_set_state(), macvlan_device::parent, device::set_state, and macvlan_device::set_state.
macvlan_device_type_init()
static void __init macvlan_device_type_init (void) static
Definition at line 266 of file macvlan.c.
{
    device_type_add(&macvlan_device_type);
}
References device_type_add(), and macvlan_device_type.
macvlan_dump_info()
static void macvlan_dump_info (struct device * dev, struct blob_buf * b) static
Definition at line 137 of file macvlan.c.
{
    struct macvlan_device *mvdev;
    mvdev = container_of(dev, struct macvlan_device, dev);
    blobmsg_add_string(b, "parent", mvdev->parent.dev->ifname);
    system_if_dump_info(dev, b);
}
References b, blobmsg_add_string(), container_of, device_user::dev, macvlan_device::dev, device::ifname, macvlan_device::parent, and system_if_dump_info().
macvlan_free()
static void macvlan_free (struct device * dev) static
Definition at line 126 of file macvlan.c.
{
    struct macvlan_device *mvdev;
    mvdev = container_of(dev, struct macvlan_device, dev);
    device_remove_user(&mvdev->parent);
    free(mvdev->config_data);
    free(mvdev);
}
References macvlan_device::config_data, container_of, macvlan_device::dev, device_remove_user(), and macvlan_device::parent.
macvlan_reload()
static enum dev_change_type macvlan_reload (struct device * dev, struct blob_attr * attr) static
Definition at line 182 of file macvlan.c.
{
    struct blob_attr *tb_dev[__DEV_ATTR_MAX];
    struct blob_attr *tb_mv[__MACVLAN_ATTR_MAX];
    enum dev_change_type ret = DEV_CONFIG_APPLIED;
    struct macvlan_device *mvdev;
    mvdev = container_of(dev, struct macvlan_device, dev);
    attr = blob_memdup(attr);
    blobmsg_parse(device_attr_list.params, __DEV_ATTR_MAX, tb_dev,
        blob_data(attr), blob_len(attr));
    blobmsg_parse(macvlan_attrs, __MACVLAN_ATTR_MAX, tb_mv,
        blob_data(attr), blob_len(attr));
    device_init_settings(dev, tb_dev);
    macvlan_apply_settings(mvdev, tb_mv);
    mvdev->ifname = tb_mv[MACVLAN_ATTR_IFNAME];
    if (mvdev->config_data) {
        struct blob_attr *otb_dev[__DEV_ATTR_MAX];
        struct blob_attr *otb_mv[__MACVLAN_ATTR_MAX];
        blobmsg_parse(device_attr_list.params, __DEV_ATTR_MAX, otb_dev,
            blob_data(mvdev->config_data), blob_len(mvdev->config_data));
        if (uci_blob_diff(tb_dev, otb_dev, &device_attr_list, NULL))
            ret = DEV_CONFIG_RESTART;
        blobmsg_parse(macvlan_attrs, __MACVLAN_ATTR_MAX, otb_mv,
            blob_data(mvdev->config_data), blob_len(mvdev->config_data));
        if (uci_blob_diff(tb_mv, otb_mv, &macvlan_attr_list, NULL))
            ret = DEV_CONFIG_RESTART;
        macvlan_config_init(dev);
    }
    free(mvdev->config_data);
    mvdev->config_data = attr;
    return ret;
}
References __DEV_ATTR_MAX, __MACVLAN_ATTR_MAX, blob_data(), blob_len(), blob_memdup(), blobmsg_parse(), macvlan_device::config_data, container_of, macvlan_device::dev, DEV_CONFIG_APPLIED, DEV_CONFIG_RESTART, device_attr_list, device_init_settings(), macvlan_device::ifname, macvlan_apply_settings(), MACVLAN_ATTR_IFNAME, macvlan_attr_list, macvlan_attrs, and macvlan_config_init().
Referenced by macvlan_create().
macvlan_set_down()
static int macvlan_set_down (struct macvlan_device * mvdev) static
Definition at line 76 of file macvlan.c.
{
    mvdev->set_state(&mvdev->dev, false);
    system_macvlan_del(&mvdev->dev);
    device_release(&mvdev->parent);
    return 0;
}
References macvlan_device::dev, device_release(), macvlan_device::parent, macvlan_device::set_state, and system_macvlan_del().
Referenced by macvlan_set_state().
macvlan_set_state()
static int macvlan_set_state (struct device * dev, bool up) static
Definition at line 112 of file macvlan.c.
{
    struct macvlan_device *mvdev;
    D(SYSTEM, "macvlan_set_state(%s, %u)", dev->ifname, up);
    mvdev = container_of(dev, struct macvlan_device, dev);
    if (up)
        return macvlan_set_up(mvdev);
    else
        return macvlan_set_down(mvdev);
}
References container_of, D, macvlan_device::dev, device::ifname, macvlan_set_down(), and macvlan_set_up().
Referenced by macvlan_create().
macvlan_set_up()
static int macvlan_set_up (struct macvlan_device * mvdev) static
Definition at line 86 of file macvlan.c.
{
    int ret;
    ret = device_claim(&mvdev->parent);
    if (ret < 0)
        return ret;
    ret = system_macvlan_add(&mvdev->dev, mvdev->parent.dev, &mvdev->config);
    if (ret < 0)
        goto release;
    ret = mvdev->set_state(&mvdev->dev, true);
    if (ret)
        goto delete;
    return 0;
delete:
    system_macvlan_del(&mvdev->dev);
release:
    device_release(&mvdev->parent);
    return ret;
}
References macvlan_device::config, device_user::dev, macvlan_device::dev, device_claim(), device_release(), macvlan_device::parent, macvlan_device::set_state, system_macvlan_add(), and system_macvlan_del().
Referenced by macvlan_set_state().
Variable Documentation
macvlan_attr_list
const struct uci_blob_param_list macvlan_attr_list static
Initial value:
= {
    .n_params = __MACVLAN_ATTR_MAX,
    .params = macvlan_attrs,
    .n_next = 1,
    .next = { &device_attr_list },
}
Definition at line 39 of file macvlan.c.
{
    .n_params = __MACVLAN_ATTR_MAX,
    .params = macvlan_attrs,
    .n_next = 1,
    .next = { &device_attr_list },
};
Referenced by macvlan_reload().
macvlan_attrs
const struct blobmsg_policy macvlan_attrs[__MACVLAN_ATTR_MAX] static
Initial value:
= {
    [MACVLAN_ATTR_IFNAME]  = { "ifname", BLOBMSG_TYPE_STRING },
    [MACVLAN_ATTR_MACADDR] = { "macaddr", BLOBMSG_TYPE_STRING },
    [MACVLAN_ATTR_MODE] = { "mode", BLOBMSG_TYPE_STRING },
}
Definition at line 33 of file macvlan.c.
{
    [MACVLAN_ATTR_IFNAME]  = { "ifname", BLOBMSG_TYPE_STRING },
    [MACVLAN_ATTR_MACADDR] = { "macaddr", BLOBMSG_TYPE_STRING },
    [MACVLAN_ATTR_MODE] = { "mode", BLOBMSG_TYPE_STRING },
};
Referenced by macvlan_reload().
macvlan_device_type
struct device_type macvlan_device_type static
Initial value:
= {
    .name = "macvlan",
    .config_params = &macvlan_attr_list,
    .create = macvlan_create,
    .config_init = macvlan_config_init,
    .reload = macvlan_reload,
    .free = macvlan_free,
    .dump_info = macvlan_dump_info,
}
Definition at line 256 of file macvlan.c.
{
    .name = "macvlan",
    .config_params = &macvlan_attr_list,
    .create = macvlan_create,
    .config_init = macvlan_config_init,
    .reload = macvlan_reload,
    .free = macvlan_free,
    .dump_info = macvlan_dump_info,
};
Referenced by macvlan_device_type_init().