zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/netifd/wireless.c File Reference
wireless.c File Reference
#include <signal.h>
#include "netifd.h"
#include "wireless.h"
#include "handler.h"
#include "ubus.h"
Macros
#define WIRELESS_SETUP_RETRY 3
Enumerations
enum { WDEV_ATTR_DISABLED , WDEV_ATTR_RECONF , WDEV_ATTR_SERIALIZE , __WDEV_ATTR_MAX }
enum {
VIF_ATTR_DISABLED , VIF_ATTR_NETWORK , VIF_ATTR_NETWORK_VLAN , VIF_ATTR_BRIDGE_ISOLATE ,
VIF_ATTR_ISOLATE , VIF_ATTR_MODE , VIF_ATTR_PROXYARP , VIF_ATTR_MCAST_TO_UCAST ,
__VIF_ATTR_MAX
}
enum {
VLAN_ATTR_DISABLED , VLAN_ATTR_NETWORK , VLAN_ATTR_NETWORK_VLAN , VLAN_ATTR_BRIDGE_ISOLATE ,
VLAN_ATTR_ISOLATE , VLAN_ATTR_MCAST_TO_UCAST , __VLAN_ATTR_MAX
}
enum { STA_ATTR_DISABLED , __STA_ATTR_MAX }
enum {
NOTIFY_CMD_UP = 0 , NOTIFY_CMD_SET_DATA = 1 , NOTIFY_CMD_PROCESS_ADD = 2 , NOTIFY_CMD_PROCESS_KILL_ALL = 3 ,
NOTIFY_CMD_SET_RETRY = 4
}
Functions
static LIST_HEAD (handlers)
static void wireless_handler_stop (struct wireless_device *wdev)
static void put_container (struct blob_buf *buf, struct blob_attr *attr, const char *name)
static void vif_config_add_bridge (struct blob_buf *buf, struct blob_attr *networks, bool prepare)
static void prepare_config (struct wireless_device *wdev, struct blob_buf *buf, bool up)
static bool wireless_process_check (struct wireless_process *proc)
static void wireless_complete_kill_request (struct wireless_device *wdev)
static void wireless_process_free (struct wireless_device *wdev, struct wireless_process *proc)
static void wireless_close_script_proc_fd (struct wireless_device *wdev)
static void wireless_process_kill_all (struct wireless_device *wdev, int signal, bool free)
static void wireless_device_free_state (struct wireless_device *wdev)
static void wireless_device_set_mcast_to_unicast (struct device *dev, int val)
static void wireless_check_interface (struct blob_attr *list, int *enabled, int *ifindex)
static void wireless_interface_handle_link (struct wireless_interface *vif, const char *ifname, bool up)
static void wireless_vlan_handle_link (struct wireless_vlan *vlan, bool up)
static void wireless_device_setup_cancel (struct wireless_device *wdev)
static void wireless_device_run_handler (struct wireless_device *wdev, bool up)
static void wireless_handler_next (void)
static void __wireless_device_set_up (struct wireless_device *wdev, int force)
static void wireless_device_free (struct wireless_device *wdev)
static void wdev_handle_config_change (struct wireless_device *wdev)
static void wireless_device_mark_down (struct wireless_device *wdev)
static void wireless_device_setup_timeout (struct uloop_timeout *timeout)
void wireless_device_set_up (struct wireless_device *wdev)
void wireless_device_reconf (struct wireless_device *wdev)
static void __wireless_device_set_down (struct wireless_device *wdev)
static void wireless_device_mark_up (struct wireless_device *wdev)
static void wireless_device_retry_setup (struct wireless_device *wdev)
static void wireless_device_script_task_cb (struct netifd_process *proc, int ret)
void wireless_device_set_down (struct wireless_device *wdev)
static void wdev_set_config_state (struct wireless_device *wdev, enum interface_config_state s)
static void wdev_prepare_prev_config (struct wireless_device *wdev)
static void wdev_change_config (struct wireless_device *wdev, struct wireless_device *wd_new)
static void wdev_create (struct wireless_device *wdev)
static void wdev_update (struct vlist_tree *tree, struct vlist_node *node_new, struct vlist_node *node_old)
static void wireless_add_handler (const char *script, const char *name, json_object *obj)
void wireless_init (void)
static void wireless_interface_init_config (struct wireless_interface *vif)
static void vif_free (struct wireless_interface *vif)
static void vif_update (struct vlist_tree *tree, struct vlist_node *node_new, struct vlist_node *node_old)
static void wireless_vlan_init_config (struct wireless_vlan *vlan)
static void vlan_update (struct vlist_tree *tree, struct vlist_node *node_new, struct vlist_node *node_old)
static void station_update (struct vlist_tree *tree, struct vlist_node *node_new, struct vlist_node *node_old)
static void wireless_proc_poll_fd (struct uloop_fd *fd, unsigned int events)
static void wireless_device_check_script_tasks (struct uloop_timeout *timeout)
void wireless_device_create (struct wireless_driver *drv, const char *name, struct blob_attr *data)
void wireless_station_create (struct wireless_interface *vif, struct blob_attr *data, const char *section)
static void wireless_station_status (struct wireless_station *sta, struct blob_buf *b)
void wireless_vlan_create (struct wireless_interface *vif, struct blob_attr *data, const char *section)
static void wireless_vlan_status (struct wireless_vlan *vlan, struct blob_buf *b)
struct wireless_interface * wireless_interface_create (struct wireless_device *wdev, struct blob_attr *data, const char *section)
static void wireless_interface_status (struct wireless_interface *iface, struct blob_buf *b)
void wireless_device_status (struct wireless_device *wdev, struct blob_buf *b)
void wireless_device_get_validate (struct wireless_device *wdev, struct blob_buf *b)
static void wireless_interface_set_data (struct wireless_interface *vif)
static void wireless_vlan_set_data (struct wireless_vlan *vlan)
static int wireless_device_add_process (struct wireless_device *wdev, struct blob_attr *data)
static int wireless_device_process_kill_all (struct wireless_device *wdev, struct blob_attr *data, struct ubus_request_data *req)
static int wireless_device_set_retry (struct wireless_device *wdev, struct blob_attr *data)
int wireless_device_notify (struct wireless_device *wdev, struct blob_attr *data, struct ubus_request_data *req)
static void wdev_vlan_check_network_enabled (struct wireless_device *wdev, struct wireless_interface *vif)
static void wdev_check_network_enabled (struct wireless_device *wdev)
static void __wireless_start_pending (struct uloop_timeout *t)
void wireless_start_pending (int timeout)
void wireless_check_network_enabled (void)
void wireless_device_hotplug_event (const char *name, bool add)
Variables
struct vlist_tree wireless_devices
struct avl_tree wireless_drivers
static struct blob_buf b
static int drv_fd
static bool handler_pending
static const struct blobmsg_policy wdev_policy [__WDEV_ATTR_MAX]
static const struct uci_blob_param_list wdev_param
static const struct blobmsg_policy vif_policy [__VIF_ATTR_MAX]
static const struct uci_blob_param_list vif_param
static const struct blobmsg_policy vlan_policy [__VLAN_ATTR_MAX]
static const struct uci_blob_param_list vlan_param
static const struct blobmsg_policy sta_policy [__STA_ATTR_MAX]
static const struct uci_blob_param_list station_param
Macro Definition Documentation
WIRELESS_SETUP_RETRY
#define WIRELESS_SETUP_RETRY 3
Definition at line 35 of file wireless.c.
Referenced by wdev_create(), wdev_handle_config_change(), wireless_device_mark_up(), wireless_device_reconf(), wireless_device_set_retry(), and wireless_device_set_up().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
WDEV_ATTR_DISABLED
WDEV_ATTR_RECONF
WDEV_ATTR_SERIALIZE
__WDEV_ATTR_MAX
Definition at line 44 of file wireless.c.
     {
    WDEV_ATTR_DISABLED,
    WDEV_ATTR_RECONF,
    WDEV_ATTR_SERIALIZE,
    __WDEV_ATTR_MAX,
};
anonymous enum
anonymous enum
Enumerator
VIF_ATTR_DISABLED
VIF_ATTR_NETWORK
VIF_ATTR_NETWORK_VLAN
VIF_ATTR_BRIDGE_ISOLATE
VIF_ATTR_ISOLATE
VIF_ATTR_MODE
VIF_ATTR_PROXYARP
VIF_ATTR_MCAST_TO_UCAST
__VIF_ATTR_MAX
Definition at line 62 of file wireless.c.
     {
    VIF_ATTR_DISABLED,
    VIF_ATTR_NETWORK,
    VIF_ATTR_NETWORK_VLAN,
    VIF_ATTR_BRIDGE_ISOLATE,
    VIF_ATTR_ISOLATE,
    VIF_ATTR_MODE,
    VIF_ATTR_PROXYARP,
    VIF_ATTR_MCAST_TO_UCAST,
    __VIF_ATTR_MAX,
};
anonymous enum
anonymous enum
Enumerator
VLAN_ATTR_DISABLED
VLAN_ATTR_NETWORK
VLAN_ATTR_NETWORK_VLAN
VLAN_ATTR_BRIDGE_ISOLATE
VLAN_ATTR_ISOLATE
VLAN_ATTR_MCAST_TO_UCAST
__VLAN_ATTR_MAX
Definition at line 90 of file wireless.c.
     {
    VLAN_ATTR_DISABLED,
    VLAN_ATTR_NETWORK,
    VLAN_ATTR_NETWORK_VLAN,
    VLAN_ATTR_BRIDGE_ISOLATE,
    VLAN_ATTR_ISOLATE,
    VLAN_ATTR_MCAST_TO_UCAST,
    __VLAN_ATTR_MAX,
};
anonymous enum
anonymous enum
Enumerator
STA_ATTR_DISABLED
__STA_ATTR_MAX
Definition at line 114 of file wireless.c.
     {
    STA_ATTR_DISABLED,
    __STA_ATTR_MAX,
};
anonymous enum
anonymous enum
Enumerator
NOTIFY_CMD_UP 0
NOTIFY_CMD_SET_DATA 1
NOTIFY_CMD_PROCESS_ADD 2
NOTIFY_CMD_PROCESS_KILL_ALL 3
NOTIFY_CMD_SET_RETRY 4
Definition at line 1500 of file wireless.c.
     {
    NOTIFY_CMD_UP = 0,
    NOTIFY_CMD_SET_DATA = 1,
    NOTIFY_CMD_PROCESS_ADD = 2,
    NOTIFY_CMD_PROCESS_KILL_ALL = 3,
    NOTIFY_CMD_SET_RETRY = 4,
};
Function Documentation
__wireless_device_set_down()
static void __wireless_device_set_down (struct wireless_device * wdev) static
Definition at line 639 of file wireless.c.
{
    if (wdev->state == IFS_TEARDOWN || wdev->state == IFS_DOWN)
        return;
    if (wdev->script_task.uloop.pending) {
        wireless_device_setup_cancel(wdev);
        return;
    }
    wdev->state = IFS_TEARDOWN;
    wireless_device_run_handler(wdev, false);
}
References IFS_DOWN, IFS_TEARDOWN, uloop_process::pending, wireless_device::script_task, wireless_device::state, netifd_process::uloop, wireless_device_run_handler(), and wireless_device_setup_cancel().
Referenced by wdev_set_config_state(), wireless_device_mark_up(), wireless_device_retry_setup(), and wireless_device_set_down().
__wireless_device_set_up()
static void __wireless_device_set_up (struct wireless_device * wdev, int force) static
Definition at line 534 of file wireless.c.
{
    if (wdev->disabled)
        return;
    if (wdev->retry_setup_failed)
        return;
    if (!wdev->autostart)
        return;
    if ((!force && wdev->state != IFS_DOWN) || config_init)
        return;
    wdev->state = IFS_SETUP;
    wireless_device_run_handler(wdev, true);
}
References wireless_device::autostart, config_init, wireless_device::disabled, IFS_DOWN, IFS_SETUP, wireless_device::retry_setup_failed, wireless_device::state, and wireless_device_run_handler().
Referenced by __wireless_start_pending(), wdev_handle_config_change(), wireless_device_reconf(), wireless_device_set_retry(), and wireless_device_set_up().
__wireless_start_pending()
static void __wireless_start_pending (struct uloop_timeout * t) static
Definition at line 1634 of file wireless.c.
{
    struct wireless_device *wdev;
    vlist_for_each_element(&wireless_devices, wdev, node) {
        wdev_check_network_enabled(wdev);
        if (wdev->config_update)
            wdev_set_config_state(wdev, IFC_RELOAD);
        __wireless_device_set_up(wdev, 0);
    }
}
References __wireless_device_set_up(), wireless_device::config_update, IFC_RELOAD, vlist_for_each_element, wdev_check_network_enabled(), wdev_set_config_state(), and wireless_devices.
Referenced by wireless_start_pending().
LIST_HEAD()
static LIST_HEAD (handlers) static
prepare_config()
static void prepare_config (struct wireless_device * wdev, struct blob_buf * buf, bool up) static
Definition at line 191 of file wireless.c.
{
    struct wireless_interface *vif;
    struct wireless_vlan *vlan;
    struct wireless_station *sta;
    void *l, *i, *j, *k;
    blob_buf_init(&b, 0);
    put_container(&b, wdev->config, "config");
    if (wdev->data)
        blobmsg_add_blob(&b, wdev->data);
    l = blobmsg_open_table(&b, "interfaces");
    vlist_for_each_element(&wdev->interfaces, vif, node) {
        if (vif->disabled)
            continue;
        i = blobmsg_open_table(&b, vif->name);
        vif_config_add_bridge(&b, vif->network, up);
        put_container(&b, vif->config, "config");
        if (vif->data)
            blobmsg_add_blob(&b, vif->data);
        j = blobmsg_open_table(&b, "vlans");
        vlist_for_each_element(&vif->vlans, vlan, node) {
            k = blobmsg_open_table(&b, vlan->name);
            vif_config_add_bridge(&b, vlan->network, up);
            put_container(&b, vlan->config, "config");
            if (vlan->data)
                blobmsg_add_blob(&b, vlan->data);
            blobmsg_close_table(&b, k);
        }
        blobmsg_close_table(&b, j);
        j = blobmsg_open_table(&b, "stas");
        vlist_for_each_element(&vif->stations, sta, node) {
            k = blobmsg_open_table(&b, sta->name);
            put_container(&b, sta->config, "config");
            if (sta->data)
                blobmsg_add_blob(&b, sta->data);
            blobmsg_close_table(&b, k);
        }
        blobmsg_close_table(&b, j);
        blobmsg_close_table(&b, i);
    }
    blobmsg_close_table(&b, l);
}
References b, blob_buf_init(), blobmsg_add_blob(), blobmsg_close_table(), blobmsg_open_table(), wireless_device::config, wireless_interface::config, wireless_station::config, wireless_vlan::config, wireless_device::data, wireless_interface::data, wireless_station::data, wireless_vlan::data, wireless_interface::disabled, wireless_device::interfaces, wireless_interface::name, wireless_station::name, wireless_vlan::name, wireless_interface::network, wireless_vlan::network, put_container(), wireless_interface::stations, vif_config_add_bridge(), wireless_interface::vlans, and vlist_for_each_element.
Referenced by wdev_prepare_prev_config(), and wireless_device_run_handler().
put_container()
static void put_container (struct blob_buf * buf, struct blob_attr * attr, const char * name) static
Definition at line 138 of file wireless.c.
{
    void *c = blobmsg_open_table(buf, name);
    blob_put_raw(buf, blobmsg_data(attr), blobmsg_len(attr));
    blobmsg_close_table(buf, c);
}
References blob_put_raw(), blobmsg_close_table(), blobmsg_data(), blobmsg_len(), blobmsg_open_table(), and buf.
Referenced by prepare_config(), wireless_device_status(), wireless_interface_status(), wireless_station_status(), and wireless_vlan_status().
station_update()
static void station_update (struct vlist_tree * tree, struct vlist_node * node_new, struct vlist_node * node_old) static
Definition at line 1016 of file wireless.c.
{
    struct wireless_station *sta_old = container_of_safe(node_old, struct wireless_station, node);
    struct wireless_station *sta_new = container_of_safe(node_new, struct wireless_station, node);
    struct wireless_interface *vif = container_of(tree, struct wireless_interface, stations);
    struct wireless_device *wdev = vif->wdev;
    if (sta_old && sta_new) {
        free((void *) sta_old->section);
        sta_old->section = strdup(sta_new->section);
        if (blob_attr_equal(sta_old->config, sta_new->config)) {
            free(sta_new);
            return;
        }
        D(WIRELESS, "Update wireless station %s on device %s", sta_new->name, wdev->name);
        free(sta_old->config);
        sta_old->config = blob_memdup(sta_new->config);
        free(sta_new);
    } else if (sta_new) {
        D(WIRELESS, "Create new wireless station %s on device %s", sta_new->name, wdev->name);
        sta_new->section = strdup(sta_new->section);
        sta_new->config = blob_memdup(sta_new->config);
    } else if (sta_old) {
        D(WIRELESS, "Delete wireless station %s on device %s", sta_old->name, wdev->name);
        free((void *) sta_old->section);
        free(sta_old->config);
        free(sta_old);
    }
    wdev->config_update = true;
}
References blob_attr_equal(), blob_memdup(), wireless_station::config, wireless_device::config_update, container_of, container_of_safe, D, wireless_device::name, wireless_station::name, wireless_station::section, wireless_interface::stations, and wireless_interface::wdev.
Referenced by wireless_interface_create().
vif_config_add_bridge()
static void vif_config_add_bridge (struct blob_buf * buf, struct blob_attr * networks, bool prepare) static
Definition at line 146 of file wireless.c.
{
    struct interface *iface;
    struct device *dev = NULL, *orig_dev;
    struct blob_attr *cur;
    const char *network;
    size_t rem;
    if (!networks)
        return;
    blobmsg_for_each_attr(cur, networks, rem) {
        network = blobmsg_data(cur);
        iface = vlist_find(&interfaces, network, iface, node);
        if (!iface)
            continue;
        dev = iface->main_dev.dev;
        if (!dev)
            return;
        if (!dev->hotplug_ops)
            return;
    }
    if (!dev)
        return;
    orig_dev = dev;
    if (dev->hotplug_ops && dev->hotplug_ops->prepare)
        dev->hotplug_ops->prepare(dev, &dev);
    if (!dev || !dev->type->bridge_capability)
        return;
    blobmsg_add_string(buf, "bridge", dev->ifname);
    blobmsg_add_string(buf, "bridge-ifname", orig_dev->ifname);
    if (dev->settings.flags & DEV_OPT_MULTICAST_TO_UNICAST)
        blobmsg_add_u8(buf, "multicast_to_unicast",
                   dev->settings.multicast_to_unicast);
}
References blobmsg_add_string(), blobmsg_add_u8(), blobmsg_data(), blobmsg_for_each_attr, device_type::bridge_capability, buf, device_user::dev, DEV_OPT_MULTICAST_TO_UNICAST, device_settings::flags, device::hotplug_ops, device::ifname, interfaces, interface::main_dev, device_settings::multicast_to_unicast, device_hotplug_ops::prepare, device::settings, device::type, and vlist_find.
Referenced by prepare_config().
vif_free()
static void vif_free (struct wireless_interface * vif) static
Definition at line 896 of file wireless.c.
{
    vlist_flush_all(&vif->vlans);
    vlist_flush_all(&vif->stations);
    free((void *) vif->section);
    free(vif->config);
    free(vif);
}
References wireless_interface::config, wireless_interface::section, wireless_interface::stations, wireless_interface::vlans, and vlist_flush_all().
Referenced by vif_update().
vif_update()
static void vif_update (struct vlist_tree * tree, struct vlist_node * node_new, struct vlist_node * node_old) static
Definition at line 907 of file wireless.c.
{
    struct wireless_interface *vif_old = container_of(node_old, struct wireless_interface, node);
    struct wireless_interface *vif_new = container_of(node_new, struct wireless_interface, node);
    struct wireless_device *wdev;
    if (vif_old)
        wdev = vif_old->wdev;
    else
        wdev = vif_new->wdev;
    if (vif_old && vif_new) {
        free((void *) vif_old->section);
        vif_old->section = strdup(vif_new->section);
        if (blob_attr_equal(vif_old->config, vif_new->config)) {
            free(vif_new);
            return;
        }
        D(WIRELESS, "Update wireless interface %s on device %s", vif_new->name, wdev->name);
        wireless_interface_handle_link(vif_old, NULL, false);
        free(vif_old->config);
        vif_old->config = blob_memdup(vif_new->config);
        wireless_interface_init_config(vif_old);
        free(vif_new);
    } else if (vif_new) {
        D(WIRELESS, "Create new wireless interface %s on device %s", vif_new->name, wdev->name);
        vif_new->section = strdup(vif_new->section);
        vif_new->config = blob_memdup(vif_new->config);
        wireless_interface_init_config(vif_new);
    } else if (vif_old) {
        D(WIRELESS, "Delete wireless interface %s on device %s", vif_old->name, wdev->name);
        wireless_interface_handle_link(vif_old, NULL, false);
        vif_free(vif_old);
    }
    wdev->config_update = true;
}
References blob_attr_equal(), blob_memdup(), wireless_interface::config, wireless_device::config_update, container_of, D, wireless_device::name, wireless_interface::name, wireless_interface::section, vif_free(), wireless_interface::wdev, wireless_interface_handle_link(), and wireless_interface_init_config().
Referenced by wireless_device_create().
vlan_update()
static void vlan_update (struct vlist_tree * tree, struct vlist_node * node_new, struct vlist_node * node_old) static
Definition at line 975 of file wireless.c.
{
    struct wireless_vlan *vlan_old = container_of_safe(node_old, struct wireless_vlan, node);
    struct wireless_vlan *vlan_new = container_of_safe(node_new, struct wireless_vlan, node);
    struct wireless_interface *vif = container_of(tree, struct wireless_interface, vlans);
    struct wireless_device *wdev = vif->wdev;
    if (vlan_old && vlan_new) {
        free((void *) vlan_old->section);
        vlan_old->section = strdup(vlan_new->section);
        if (blob_attr_equal(vlan_old->config, vlan_new->config)) {
            free(vlan_new);
            return;
        }
        D(WIRELESS, "Update wireless vlan %s on device %s", vlan_new->name, wdev->name);
        wireless_vlan_handle_link(vlan_old, false);
        free(vlan_old->config);
        vlan_old->config = blob_memdup(vlan_new->config);
        vlan_old->isolate = vlan_new->isolate;
        wireless_vlan_init_config(vlan_old);
        free(vlan_new);
    } else if (vlan_new) {
        D(WIRELESS, "Create new wireless vlan %s on device %s", vlan_new->name, wdev->name);
        vlan_new->section = strdup(vlan_new->section);
        vlan_new->config = blob_memdup(vlan_new->config);
        wireless_vlan_init_config(vlan_new);
    } else if (vlan_old) {
        D(WIRELESS, "Delete wireless vlan %s on device %s", vlan_old->name, wdev->name);
        wireless_vlan_handle_link(vlan_old, false);
        free((void *) vlan_old->section);
        free(vlan_old->config);
        free(vlan_old);
    }
    wdev->config_update = true;
}
References blob_attr_equal(), blob_memdup(), wireless_vlan::config, wireless_device::config_update, container_of, container_of_safe, D, wireless_vlan::isolate, wireless_device::name, wireless_vlan::name, wireless_vlan::section, wireless_interface::vlans, wireless_interface::wdev, wireless_vlan_handle_link(), and wireless_vlan_init_config().
Referenced by wireless_interface_create().
wdev_change_config()
static void wdev_change_config (struct wireless_device * wdev, struct wireless_device * wd_new) static
Definition at line 749 of file wireless.c.
{
    struct blob_attr *new_config = wd_new->config;
    bool disabled = wd_new->disabled;
    wdev->reconf = wd_new->reconf;
    wdev->serialize = wd_new->serialize;
    free(wd_new);
    if (blob_attr_equal(wdev->config, new_config) && wdev->disabled == disabled)
        return;
    D(WIRELESS, "Update configuration of wireless device '%s'", wdev->name);
    free(wdev->config);
    wdev->config = blob_memdup(new_config);
    wdev->disabled = disabled;
    wdev->config_update = true;
}
References blob_attr_equal(), blob_memdup(), wireless_device::config, wireless_device::config_update, D, wireless_device::disabled, wireless_device::name, wireless_device::reconf, and wireless_device::serialize.
Referenced by wdev_update().
wdev_check_network_enabled()
static void wdev_check_network_enabled (struct wireless_device * wdev) static
Definition at line 1613 of file wireless.c.
{
    struct wireless_interface *vif;
    vlist_for_each_element(&wdev->interfaces, vif, node) {
        int enabled = -1, ifindex = -1;
        wireless_check_interface(vif->network, &enabled, &ifindex);
        wdev_vlan_check_network_enabled(wdev, vif);
        if (vif->disabled == !enabled &&
            (wdev->state != IFS_UP || vif->network_ifindex == ifindex))
            continue;
        vif->disabled = !enabled;
        vif->network_ifindex = ifindex;
        wdev->config_update = true;
    }
}
References wireless_device::config_update, wireless_interface::disabled, IFS_UP, wireless_device::interfaces, wireless_interface::network, wireless_interface::network_ifindex, wireless_device::state, vlist_for_each_element, wireless_interface::wdev, wdev_vlan_check_network_enabled(), and wireless_check_interface().
Referenced by __wireless_start_pending(), and wireless_check_network_enabled().
wdev_create()
static void wdev_create (struct wireless_device * wdev) static
Definition at line 769 of file wireless.c.
{
    wdev->retry = WIRELESS_SETUP_RETRY;
    wdev->config = blob_memdup(wdev->config);
}
References blob_memdup(), wireless_device::config, wireless_device::retry, and WIRELESS_SETUP_RETRY.
Referenced by wdev_update().
wdev_handle_config_change()
static void wdev_handle_config_change (struct wireless_device * wdev) static
Definition at line 564 of file wireless.c.
{
    enum interface_config_state state = wdev->config_state;
    switch(state) {
    case IFC_RELOAD:
        wdev->retry = WIRELESS_SETUP_RETRY;
        wdev->retry_setup_failed = false;
        fallthrough;
    case IFC_NORMAL:
        __wireless_device_set_up(wdev, 0);
        wdev->config_state = IFC_NORMAL;
        break;
    case IFC_REMOVE:
        wireless_device_free(wdev);
        break;
    }
}
References __wireless_device_set_up(), wireless_device::config_state, fallthrough, IFC_NORMAL, IFC_RELOAD, IFC_REMOVE, wireless_device::retry, wireless_device::retry_setup_failed, state, wireless_device_free(), and WIRELESS_SETUP_RETRY.
Referenced by wdev_set_config_state(), and wireless_device_mark_down().
wdev_prepare_prev_config()
static void wdev_prepare_prev_config (struct wireless_device * wdev) static
Definition at line 741 of file wireless.c.
{
    prepare_config(wdev, &b, false);
    free(wdev->prev_config);
    wdev->prev_config = blob_memdup(b.head);
}
References b, blob_memdup(), blob_buf::head, prepare_config(), and wireless_device::prev_config.
Referenced by wireless_device_notify().
wdev_set_config_state()
static void wdev_set_config_state (struct wireless_device * wdev, enum interface_config_state s) static
Definition at line 722 of file wireless.c.
{
    if (wdev->config_state != IFC_NORMAL)
        return;
    wdev->config_update = false;
    if (!wdev->disabled && s == IFC_RELOAD && wdev->reconf && wdev->state == IFS_UP) {
        wireless_device_reconf(wdev);
        return;
    }
    wdev->config_state = s;
    if (wdev->state == IFS_DOWN)
        wdev_handle_config_change(wdev);
    else
        __wireless_device_set_down(wdev);
}
References __wireless_device_set_down(), wireless_device::config_state, wireless_device::config_update, wireless_device::disabled, IFC_NORMAL, IFC_RELOAD, IFS_DOWN, IFS_UP, wireless_device::reconf, wireless_device::state, wdev_handle_config_change(), and wireless_device_reconf().
Referenced by __wireless_start_pending(), and wdev_update().
wdev_update()
static void wdev_update (struct vlist_tree * tree, struct vlist_node * node_new, struct vlist_node * node_old) static
Definition at line 777 of file wireless.c.
{
    struct wireless_device *wd_old = container_of(node_old, struct wireless_device, node);
    struct wireless_device *wd_new = container_of(node_new, struct wireless_device, node);
    if (wd_old && wd_new) {
        D(WIRELESS, "Update wireless device '%s'", wd_old->name);
        wdev_change_config(wd_old, wd_new);
    } else if (wd_old) {
        D(WIRELESS, "Delete wireless device '%s'", wd_old->name);
        wdev_set_config_state(wd_old, IFC_REMOVE);
    } else if (wd_new) {
        D(WIRELESS, "Create wireless device '%s'", wd_new->name);
        wdev_create(wd_new);
    }
}
References container_of, D, IFC_REMOVE, wireless_device::name, wdev_change_config(), wdev_create(), and wdev_set_config_state().
Referenced by wireless_init().
wdev_vlan_check_network_enabled()
static void wdev_vlan_check_network_enabled (struct wireless_device * wdev, struct wireless_interface * vif) static
Definition at line 1594 of file wireless.c.
{
    struct wireless_vlan *vlan;
    vlist_for_each_element(&vif->vlans, vlan, node) {
        int enabled = -1, ifindex = -1;
        wireless_check_interface(vlan->network, &enabled, &ifindex);
        if (wdev->state != IFS_UP || vlan->network_ifindex == ifindex)
            continue;
        vlan->network_ifindex = ifindex;
        wdev->config_update = true;
    }
}
References wireless_device::config_update, IFS_UP, wireless_vlan::network, wireless_vlan::network_ifindex, wireless_device::state, wireless_interface::vlans, vlist_for_each_element, and wireless_check_interface().
Referenced by wdev_check_network_enabled().
wireless_add_handler()
static void wireless_add_handler (const char * script, const char * name, json_object * obj) static
Definition at line 797 of file wireless.c.
{
    struct wireless_driver *drv;
    char *name_str, *script_str;
    json_object *dev_config_obj, *iface_config_obj, *vlan_config_obj, *station_config_obj;
    struct uci_blob_param_list *dev_config, *iface_config, *vlan_config, *station_config;
    dev_config_obj = json_get_field(obj, "device", json_type_array);
    iface_config_obj = json_get_field(obj, "iface", json_type_array);
    vlan_config_obj = json_get_field(obj, "vlan", json_type_array);
    station_config_obj = json_get_field(obj, "station", json_type_array);
    if (!dev_config_obj || !iface_config_obj || !vlan_config_obj || !station_config_obj)
        return;
    drv = calloc_a(sizeof(*drv),
        &dev_config, sizeof(*dev_config) + sizeof(void *),
        &iface_config, sizeof(*iface_config) + sizeof(void *),
        &vlan_config, sizeof(*vlan_config) + sizeof(void *),
        &station_config, sizeof(*station_config) + sizeof(void *),
        &name_str, strlen(name) + 1,
        &script_str, strlen(script) + 1);
    drv->name = strcpy(name_str, name);
    drv->script = strcpy(script_str, script);
    dev_config->n_next = 1;
    dev_config->next[0] = &wdev_param;
    drv->device.config = dev_config;
    iface_config->n_next = 1;
    iface_config->next[0] = &vif_param;
    drv->interface.config = iface_config;
    vlan_config->n_next = 1;
    vlan_config->next[0] = &vlan_param;
    drv->vlan.config = vlan_config;
    station_config->n_next = 1;
    station_config->next[0] = &station_param;
    drv->station.config = station_config;
    drv->device.buf = netifd_handler_parse_config(drv->device.config, dev_config_obj);
    drv->interface.buf = netifd_handler_parse_config(drv->interface.config, iface_config_obj);
    drv->vlan.buf = netifd_handler_parse_config(drv->vlan.config, vlan_config_obj);
    drv->station.buf = netifd_handler_parse_config(drv->station.config, station_config_obj);
    drv->node.key = drv->name;
    avl_insert(&wireless_drivers, &drv->node);
    D(WIRELESS, "Add handler for script %s: %s", script, name);
}
References avl_insert(), calloc_a, D, wireless_driver::device, wireless_driver::interface, json_get_field(), avl_node::key, wireless_driver::name, netifd_handler_parse_config(), wireless_driver::node, script, wireless_driver::script, wireless_driver::station, station_param, vif_param, wireless_driver::vlan, vlan_param, wdev_param, and wireless_drivers.
Referenced by wireless_init().
wireless_check_interface()
static void wireless_check_interface (struct blob_attr * list, int * enabled, int * ifindex) static
Definition at line 340 of file wireless.c.
{
    struct interface *iface;
    struct blob_attr *cur;
    size_t rem;
    blobmsg_for_each_attr(cur, list, rem) {
        struct device *mdev;
        iface = vlist_find(&interfaces, blobmsg_get_string(cur), iface, node);
        if (!iface)
            continue;
        if (iface->autostart)
            *enabled = 1;
        else if (*enabled != 1)
            *enabled = 0;
        mdev = iface->main_dev.dev;
        if (!mdev || !mdev->hotplug_ops)
            continue;
        *ifindex = mdev->ifindex;
    }
}
References interface::autostart, blobmsg_for_each_attr, blobmsg_get_string(), device_user::dev, device::hotplug_ops, device::ifindex, interfaces, interface::main_dev, and vlist_find.
Referenced by wdev_check_network_enabled(), wdev_vlan_check_network_enabled(), wireless_interface_handle_link(), and wireless_vlan_handle_link().
wireless_check_network_enabled()
void wireless_check_network_enabled (void)
Definition at line 1661 of file wireless.c.
{
    struct wireless_device *wdev;
    vlist_for_each_element(&wireless_devices, wdev, node) {
        wdev_check_network_enabled(wdev);
        if (wdev->config_update)
            wireless_start_pending(1000);
    }
}
References wireless_device::config_update, vlist_for_each_element, wdev_check_network_enabled(), wireless_devices, and wireless_start_pending().
Referenced by interface_set_down(), and interface_set_up().
wireless_close_script_proc_fd()
static void wireless_close_script_proc_fd (struct wireless_device * wdev) static
Definition at line 269 of file wireless.c.
{
    if (wdev->script_proc_fd.fd < 0)
        return;
    uloop_fd_delete(&wdev->script_proc_fd);
    close(wdev->script_proc_fd.fd);
    wdev->script_proc_fd.fd = -1;
}
References uloop_fd::fd, wireless_device::script_proc_fd, and uloop_fd_delete().
Referenced by wireless_device_run_handler(), wireless_proc_poll_fd(), and wireless_process_kill_all().
wireless_complete_kill_request()
static void wireless_complete_kill_request (struct wireless_device * wdev) static
Definition at line 247 of file wireless.c.
{
    if (!wdev->kill_request)
        return;
    ubus_complete_deferred_request(ubus_ctx, wdev->kill_request, 0);
    free(wdev->kill_request);
    wdev->kill_request = NULL;
}
References wireless_device::kill_request, ubus_complete_deferred_request(), and ubus_ctx.
Referenced by wireless_device_free_state(), and wireless_process_free().
wireless_device_add_process()
static int wireless_device_add_process (struct wireless_device * wdev, struct blob_attr * data) static
Definition at line 1390 of file wireless.c.
{
    enum {
        PROC_ATTR_PID,
        PROC_ATTR_EXE,
        PROC_ATTR_REQUIRED,
        PROC_ATTR_KEEP,
        __PROC_ATTR_MAX
    };
    static const struct blobmsg_policy proc_policy[__PROC_ATTR_MAX] = {
        [PROC_ATTR_PID] = { .name = "pid", .type = BLOBMSG_TYPE_INT32 },
        [PROC_ATTR_EXE] = { .name = "exe", .type = BLOBMSG_TYPE_STRING },
        [PROC_ATTR_REQUIRED] = { .name = "required", .type = BLOBMSG_TYPE_BOOL },
        [PROC_ATTR_KEEP] = { .name = "keep", .type = BLOBMSG_TYPE_BOOL },
    };
    struct blob_attr *tb[__PROC_ATTR_MAX];
    struct wireless_process *proc;
    char *name;
    int pid;
    if (!data)
        return UBUS_STATUS_INVALID_ARGUMENT;
    blobmsg_parse_attr(proc_policy, __PROC_ATTR_MAX, tb, data);
    if (!tb[PROC_ATTR_PID] || !tb[PROC_ATTR_EXE])
        return UBUS_STATUS_INVALID_ARGUMENT;
    pid = blobmsg_get_u32(tb[PROC_ATTR_PID]);
    if (pid < 2)
        return UBUS_STATUS_INVALID_ARGUMENT;
    proc = calloc_a(sizeof(*proc),
        &name, strlen(blobmsg_data(tb[PROC_ATTR_EXE])) + 1);
    proc->pid = pid;
    proc->exe = strcpy(name, blobmsg_data(tb[PROC_ATTR_EXE]));
    if (tb[PROC_ATTR_REQUIRED])
        proc->required = blobmsg_get_bool(tb[PROC_ATTR_REQUIRED]);
    if (tb[PROC_ATTR_KEEP])
        proc->keep = blobmsg_get_bool(tb[PROC_ATTR_KEEP]);
    D(WIRELESS, "Wireless device '%s' add pid %d", wdev->name, proc->pid);
    list_add(&proc->list, &wdev->script_proc);
    uloop_timeout_set(&wdev->script_check, 0);
    return 0;
}
References blobmsg_data(), blobmsg_get_bool(), blobmsg_get_u32(), blobmsg_parse_attr(), BLOBMSG_TYPE_BOOL, BLOBMSG_TYPE_INT32, BLOBMSG_TYPE_STRING, calloc_a, D, wireless_process::exe, wireless_process::keep, wireless_process::list, list_add(), wireless_device::name, wireless_process::pid, wireless_process::required, wireless_device::script_check, wireless_device::script_proc, UBUS_STATUS_INVALID_ARGUMENT, and uloop_timeout_set().
Referenced by wireless_device_notify().
wireless_device_check_script_tasks()
static void wireless_device_check_script_tasks (struct uloop_timeout * timeout) static
Definition at line 1080 of file wireless.c.
{
    struct wireless_device *wdev = container_of(timeout, struct wireless_device, script_check);
    struct wireless_process *proc, *tmp;
    bool restart = false;
    list_for_each_entry_safe(proc, tmp, &wdev->script_proc, list) {
        if (wireless_process_check(proc))
            continue;
        D(WIRELESS, "Wireless device '%s' pid %d has terminated", wdev->name, proc->pid);
        if (proc->required)
            restart = true;
        wireless_process_free(wdev, proc);
    }
    if (restart)
        wireless_device_retry_setup(wdev);
    else
        uloop_timeout_set(&wdev->script_check, 1000);
}
References container_of, D, wireless_process::list, list_for_each_entry_safe, wireless_device::name, wireless_process::pid, wireless_process::required, wireless_device::script_check, wireless_device::script_proc, timeout, uloop_timeout_set(), wireless_device_retry_setup(), wireless_process_check(), and wireless_process_free().
Referenced by wireless_device_create().
wireless_device_create()
void wireless_device_create (struct wireless_driver * drv, const char * name, struct blob_attr * data)
Definition at line 1105 of file wireless.c.
{
    struct wireless_device *wdev;
    char *name_buf;
    struct blob_attr *tb[__WDEV_ATTR_MAX];
    struct blob_attr *cur;
    blobmsg_parse_attr(wdev_policy, __WDEV_ATTR_MAX, tb, data);
    wdev = calloc_a(sizeof(*wdev), &name_buf, strlen(name) + 1);
    cur = tb[WDEV_ATTR_DISABLED];
    wdev->disabled = cur && blobmsg_get_bool(cur);
    wdev->drv = drv;
    wdev->state = IFS_DOWN;
    wdev->config_state = IFC_NORMAL;
    wdev->name = strcpy(name_buf, name);
    wdev->config = data;
    wdev->handler_pending = false;
    cur = tb[WDEV_ATTR_SERIALIZE];
    wdev->serialize = cur && blobmsg_get_bool(cur);
    cur = tb[WDEV_ATTR_RECONF];
    wdev->reconf = !cur || blobmsg_get_bool(cur);
    wdev->retry_setup_failed = false;
    wdev->autostart = true;
    INIT_LIST_HEAD(&wdev->script_proc);
    vlist_init(&wdev->interfaces, avl_strcmp, vif_update);
    wdev->interfaces.keep_old = true;
    wdev->timeout.cb = wireless_device_setup_timeout;
    wdev->script_task.cb = wireless_device_script_task_cb;
    wdev->script_task.dir_fd = drv_fd;
    wdev->script_task.log_prefix = wdev->name;
    wdev->script_proc_fd.fd = -1;
    wdev->script_proc_fd.cb = wireless_proc_poll_fd;
    wdev->script_check.cb = wireless_device_check_script_tasks;
    vlist_add(&wireless_devices, &wdev->node, wdev->name);
}
References __WDEV_ATTR_MAX, wireless_device::autostart, avl_strcmp(), blobmsg_get_bool(), blobmsg_parse_attr(), calloc_a, netifd_process::cb, uloop_fd::cb, uloop_timeout::cb, wireless_device::config, wireless_device::config_state, blob_attr::data, netifd_process::dir_fd, wireless_device::disabled, wireless_device::drv, drv_fd, uloop_fd::fd, wireless_device::handler_pending, IFC_NORMAL, IFS_DOWN, INIT_LIST_HEAD(), wireless_device::interfaces, vlist_tree::keep_old, netifd_process::log_prefix, wireless_device::name, wireless_device::node, wireless_device::reconf, wireless_device::retry_setup_failed, wireless_device::script_check, wireless_device::script_proc, wireless_device::script_proc_fd, wireless_device::script_task, wireless_device::serialize, wireless_device::state, wireless_device::timeout, vif_update(), vlist_add(), vlist_init(), WDEV_ATTR_DISABLED, WDEV_ATTR_RECONF, WDEV_ATTR_SERIALIZE, wdev_policy, wireless_device_check_script_tasks(), wireless_device_script_task_cb(), wireless_device_setup_timeout(), wireless_devices, and wireless_proc_poll_fd().
Referenced by config_parse_wireless_device().
wireless_device_free()
static void wireless_device_free (struct wireless_device * wdev) static
Definition at line 553 of file wireless.c.
{
    wireless_handler_stop(wdev);
    vlist_flush_all(&wdev->interfaces);
    avl_delete(&wireless_devices.avl, &wdev->node.avl);
    free(wdev->config);
    free(wdev->prev_config);
    free(wdev);
}
References vlist_node::avl, vlist_tree::avl, avl_delete(), wireless_device::config, wireless_device::interfaces, wireless_device::node, wireless_device::prev_config, vlist_flush_all(), wireless_devices, and wireless_handler_stop().
Referenced by wdev_handle_config_change().
wireless_device_free_state()
static void wireless_device_free_state (struct wireless_device * wdev) static
Definition at line 301 of file wireless.c.
{
    struct wireless_interface *vif;
    struct wireless_vlan *vlan;
    struct wireless_station *sta;
    wireless_handler_stop(wdev);
    uloop_timeout_cancel(&wdev->script_check);
    uloop_timeout_cancel(&wdev->timeout);
    wireless_complete_kill_request(wdev);
    free(wdev->data);
    wdev->data = NULL;
    vlist_for_each_element(&wdev->interfaces, vif, node) {
        free(vif->data);
        vif->data = NULL;
        vif->ifname = NULL;
        vlist_for_each_element(&vif->vlans, vlan, node) {
            free(vlan->data);
            vlan->data = NULL;
            vlan->ifname = NULL;
        }
        vlist_for_each_element(&vif->stations, sta, node) {
            free(sta->data);
            sta->data = NULL;
        }
    }
}
References wireless_device::data, wireless_interface::data, wireless_station::data, wireless_vlan::data, wireless_interface::ifname, wireless_vlan::ifname, wireless_device::interfaces, wireless_device::script_check, wireless_interface::stations, wireless_device::timeout, uloop_timeout_cancel(), wireless_interface::vlans, vlist_for_each_element, wireless_complete_kill_request(), and wireless_handler_stop().
Referenced by wireless_device_mark_down().
wireless_device_get_validate()
void wireless_device_get_validate (struct wireless_device * wdev, struct blob_buf * b)
Definition at line 1325 of file wireless.c.
{
    struct uci_blob_param_list *p;
    void *c, *d;
    int i;
    c = blobmsg_open_table(b, wdev->name);
    d = blobmsg_open_table(b, "device");
    p = wdev->drv->device.config;
    for (i = 0; i < p->n_params; i++)
        blobmsg_add_string(b, p->params[i].name, uci_get_validate_string(p, i));
    blobmsg_close_table(b, d);
    d = blobmsg_open_table(b, "interface");
    p = wdev->drv->interface.config;
    for (i = 0; i < p->n_params; i++)
        blobmsg_add_string(b, p->params[i].name, uci_get_validate_string(p, i));
    blobmsg_close_table(b, d);
    blobmsg_close_table(b, c);
}
References b, blobmsg_add_string(), blobmsg_close_table(), blobmsg_open_table(), wireless_driver::device, wireless_device::drv, wireless_driver::interface, wireless_device::name, and uci_get_validate_string().
Referenced by netifd_handle_wdev_get_validate().
wireless_device_hotplug_event()
void wireless_device_hotplug_event (const char * name, bool add)
Definition at line 1673 of file wireless.c.
{
    struct wireless_interface *vif;
    struct wireless_device *wdev;
    const char *s;
    size_t len;
    s = strstr(name, ".sta");
    if (s) {
        if (strchr(s + 4, '.'))
            return;
        len = s - name;
    } else {
        len = strlen(name);
    }
    vlist_for_each_element(&wireless_devices, wdev, node) {
        vlist_for_each_element(&wdev->interfaces, vif, node) {
            if (!vif->ifname)
                continue;
            if (strlen(vif->ifname) != len ||
                strncmp(vif->ifname, name, len) != 0)
                continue;
            wireless_interface_handle_link(vif, name, add);
        }
    }
}
References wireless_interface::ifname, wireless_device::interfaces, wireless_device::name, vlist_for_each_element, wireless_devices, and wireless_interface_handle_link().
Referenced by device_hotplug_event().
wireless_device_mark_down()
static void wireless_device_mark_down (struct wireless_device * wdev) static
Definition at line 585 of file wireless.c.
{
    struct wireless_interface *vif;
    struct wireless_vlan *vlan;
    netifd_log_message(L_NOTICE, "Wireless device '%s' is now down\n", wdev->name);
    vlist_for_each_element(&wdev->interfaces, vif, node) {
        wireless_interface_handle_link(vif, NULL, false);
        vlist_for_each_element(&vif->vlans, vlan, node)
            wireless_vlan_handle_link(vlan, false);
    }
    wireless_process_kill_all(wdev, SIGTERM, true);
    wdev->cancel = false;
    wdev->state = IFS_DOWN;
    wireless_device_free_state(wdev);
    wdev_handle_config_change(wdev);
}
References wireless_device::cancel, IFS_DOWN, wireless_device::interfaces, L_NOTICE, wireless_device::name, netifd_log_message(), wireless_device::state, wireless_interface::vlans, vlist_for_each_element, wdev_handle_config_change(), wireless_device_free_state(), wireless_interface_handle_link(), wireless_process_kill_all(), and wireless_vlan_handle_link().
Referenced by wireless_device_script_task_cb(), and wireless_device_setup_timeout().
wireless_device_mark_up()
static void wireless_device_mark_up (struct wireless_device * wdev) static
Definition at line 655 of file wireless.c.
{
    struct wireless_interface *vif;
    struct wireless_vlan *vlan;
    if (wdev->cancel) {
        wdev->cancel = false;
        __wireless_device_set_down(wdev);
        return;
    }
    netifd_log_message(L_NOTICE, "Wireless device '%s' is now up\n", wdev->name);
    wdev->retry = WIRELESS_SETUP_RETRY;
    wdev->state = IFS_UP;
    vlist_for_each_element(&wdev->interfaces, vif, node) {
        wireless_interface_handle_link(vif, NULL, true);
        vlist_for_each_element(&vif->vlans, vlan, node)
            wireless_vlan_handle_link(vlan, true);
    }
}
References __wireless_device_set_down(), wireless_device::cancel, IFS_UP, wireless_device::interfaces, L_NOTICE, wireless_device::name, netifd_log_message(), wireless_device::retry, wireless_device::state, wireless_interface::vlans, vlist_for_each_element, wireless_interface_handle_link(), WIRELESS_SETUP_RETRY, and wireless_vlan_handle_link().
Referenced by wireless_device_notify().
wireless_device_notify()
int wireless_device_notify (struct wireless_device * wdev, struct blob_attr * data, struct ubus_request_data * req)
Definition at line 1510 of file wireless.c.
{
    enum {
        NOTIFY_ATTR_COMMAND,
        NOTIFY_ATTR_VIF,
        NOTIFY_ATTR_VLAN,
        NOTIFY_ATTR_DATA,
        __NOTIFY_MAX,
    };
    static const struct blobmsg_policy notify_policy[__NOTIFY_MAX] = {
        [NOTIFY_ATTR_COMMAND] = { .name = "command", .type = BLOBMSG_TYPE_INT32 },
        [NOTIFY_ATTR_VIF] = { .name = "interface", .type = BLOBMSG_TYPE_STRING },
        [NOTIFY_ATTR_VLAN] = { .name = "vlan", .type = BLOBMSG_TYPE_STRING },
        [NOTIFY_ATTR_DATA] = { .name = "data", .type = BLOBMSG_TYPE_TABLE },
    };
    struct wireless_interface *vif = NULL;
    struct wireless_vlan *vlan = NULL;
    struct blob_attr *tb[__NOTIFY_MAX];
    struct blob_attr *cur, **pdata;
    blobmsg_parse_attr(notify_policy, __NOTIFY_MAX, tb, data);
    if (!tb[NOTIFY_ATTR_COMMAND])
        return UBUS_STATUS_INVALID_ARGUMENT;
    if ((cur = tb[NOTIFY_ATTR_VIF]) != NULL) {
        vif = vlist_find(&wdev->interfaces, blobmsg_data(cur), vif, node);
        if (!vif)
            return UBUS_STATUS_NOT_FOUND;
    }
    if ((cur = tb[NOTIFY_ATTR_VLAN]) != NULL) {
        if (!vif)
            return UBUS_STATUS_NOT_FOUND;
        vlan = vlist_find(&vif->vlans, blobmsg_data(cur), vlan, node);
        if (!vlan)
            return UBUS_STATUS_NOT_FOUND;
    }
    cur = tb[NOTIFY_ATTR_DATA];
    if (!cur)
        return UBUS_STATUS_INVALID_ARGUMENT;
    switch (blobmsg_get_u32(tb[NOTIFY_ATTR_COMMAND])) {
    case NOTIFY_CMD_UP:
        if (vif || vlan)
            return UBUS_STATUS_INVALID_ARGUMENT;
        if (wdev->state != IFS_SETUP)
            return UBUS_STATUS_PERMISSION_DENIED;
        wireless_device_mark_up(wdev);
        break;
    case NOTIFY_CMD_SET_DATA:
        if (vlan)
            pdata = &vlan->data;
        else if (vif)
            pdata = &vif->data;
        else
            pdata = &wdev->data;
        free(*pdata);
        *pdata = blob_memdup(cur);
        if (vlan)
            wireless_vlan_set_data(vlan);
        else if (vif)
            wireless_interface_set_data(vif);
        wdev_prepare_prev_config(wdev);
        break;
    case NOTIFY_CMD_PROCESS_ADD:
        return wireless_device_add_process(wdev, cur);
    case NOTIFY_CMD_PROCESS_KILL_ALL:
        return wireless_device_process_kill_all(wdev, cur, req);
    case NOTIFY_CMD_SET_RETRY:
        return wireless_device_set_retry(wdev, cur);
    default:
        return UBUS_STATUS_INVALID_ARGUMENT;
    }
    return 0;
}
References blob_memdup(), blobmsg_data(), blobmsg_get_u32(), blobmsg_parse_attr(), BLOBMSG_TYPE_INT32, BLOBMSG_TYPE_STRING, BLOBMSG_TYPE_TABLE, blob_attr::data, wireless_device::data, wireless_interface::data, wireless_vlan::data, IFS_SETUP, wireless_device::interfaces, NOTIFY_CMD_PROCESS_ADD, NOTIFY_CMD_PROCESS_KILL_ALL, NOTIFY_CMD_SET_DATA, NOTIFY_CMD_SET_RETRY, NOTIFY_CMD_UP, wireless_device::state, UBUS_STATUS_INVALID_ARGUMENT, UBUS_STATUS_NOT_FOUND, UBUS_STATUS_PERMISSION_DENIED, wireless_interface::vlans, vlist_find, wdev_prepare_prev_config(), wireless_device_add_process(), wireless_device_mark_up(), wireless_device_process_kill_all(), wireless_device_set_retry(), wireless_interface_set_data(), and wireless_vlan_set_data().
Referenced by netifd_handle_wdev_notify().
wireless_device_process_kill_all()
static int wireless_device_process_kill_all (struct wireless_device * wdev, struct blob_attr * data, struct ubus_request_data * req) static
Definition at line 1442 of file wireless.c.
{
    enum {
        KILL_ATTR_SIGNAL,
        KILL_ATTR_IMMEDIATE,
        __KILL_ATTR_MAX
    };
    static const struct blobmsg_policy kill_policy[__KILL_ATTR_MAX] = {
        [KILL_ATTR_SIGNAL] = { .name = "signal", .type = BLOBMSG_TYPE_INT32 },
        [KILL_ATTR_IMMEDIATE] = { .name = "immediate", .type = BLOBMSG_TYPE_BOOL },
    };
    struct blob_attr *tb[__KILL_ATTR_MAX];
    struct blob_attr *cur;
    bool immediate = false;
    int signal = SIGTERM;
    blobmsg_parse_attr(kill_policy, __KILL_ATTR_MAX, tb, data);
    if ((cur = tb[KILL_ATTR_SIGNAL]))
        signal = blobmsg_get_u32(cur);
    if ((cur = tb[KILL_ATTR_IMMEDIATE]))
        immediate = blobmsg_get_bool(cur);
    if (wdev->state != IFS_TEARDOWN || wdev->kill_request)
        return UBUS_STATUS_PERMISSION_DENIED;
    wireless_process_kill_all(wdev, signal, immediate);
    if (list_empty(&wdev->script_proc))
        return 0;
    wdev->kill_request = calloc(1, sizeof(*wdev->kill_request));
    ubus_defer_request(ubus_ctx, req, wdev->kill_request);
    return 0;
}
References blobmsg_get_bool(), blobmsg_get_u32(), blobmsg_parse_attr(), BLOBMSG_TYPE_BOOL, BLOBMSG_TYPE_INT32, blob_attr::data, IFS_TEARDOWN, wireless_device::kill_request, list_empty(), wireless_device::script_proc, wireless_device::state, ubus_ctx, ubus_defer_request(), UBUS_STATUS_PERMISSION_DENIED, and wireless_process_kill_all().
Referenced by wireless_device_notify().
wireless_device_reconf()
void wireless_device_reconf (struct wireless_device * wdev)
Definition at line 631 of file wireless.c.
{
    wdev->retry = WIRELESS_SETUP_RETRY;
    wdev->autostart = true;
    __wireless_device_set_up(wdev, wdev->reconf && (wdev->state == IFS_UP));
}
References __wireless_device_set_up(), wireless_device::autostart, IFS_UP, wireless_device::reconf, wireless_device::retry, wireless_device::state, and WIRELESS_SETUP_RETRY.
Referenced by netifd_handle_wdev_reconf(), and wdev_set_config_state().
wireless_device_retry_setup()
static void wireless_device_retry_setup (struct wireless_device * wdev) static
Definition at line 677 of file wireless.c.
{
    if (wdev->state == IFS_TEARDOWN || wdev->state == IFS_DOWN || wdev->cancel)
        return;
    netifd_log_message(wdev->retry ? L_WARNING : L_CRIT,
               "Wireless device '%s' setup failed, retry=%d\n",
               wdev->name, wdev->retry);
    if (--wdev->retry < 0)
        wdev->retry_setup_failed = true;
    __wireless_device_set_down(wdev);
}
References __wireless_device_set_down(), wireless_device::cancel, IFS_DOWN, IFS_TEARDOWN, L_CRIT, L_WARNING, wireless_device::name, netifd_log_message(), wireless_device::retry, wireless_device::retry_setup_failed, and wireless_device::state.
Referenced by wireless_device_check_script_tasks(), and wireless_device_script_task_cb().
wireless_device_run_handler()
static void wireless_device_run_handler (struct wireless_device * wdev, bool up) static
Definition at line 463 of file wireless.c.
{
    const char *action = up ? "setup" : "teardown";
    const char *argv[6];
    char *config;
    int i = 0;
    int fds[2] = { -1, -1 };
    wireless_handler_stop(wdev);
    if (handler_pending && wdev->serialize) {
        wdev->handler_action = up;
        wdev->handler_pending = true;
        list_add_tail(&wdev->handler, &handlers);
        return;
    }
    if (wdev->serialize)
        handler_pending = true;
    D(WIRELESS, "Wireless device '%s' run %s handler", wdev->name, action);
    if (!up && wdev->prev_config) {
        config = blobmsg_format_json(wdev->prev_config, true);
        free(wdev->prev_config);
        wdev->prev_config = NULL;
    } else {
        prepare_config(wdev, &b, up);
        free(wdev->prev_config);
        wdev->prev_config = up ? blob_memdup(b.head) : NULL;
        config = blobmsg_format_json(b.head, true);
    }
    argv[i++] = wdev->drv->script;
    argv[i++] = wdev->drv->name;
    argv[i++] = action;
    argv[i++] = wdev->name;
    argv[i++] = config;
    argv[i] = NULL;
    if (up && pipe(fds) == 0) {
        if (wdev->script_proc_fd.fd >= 0)
            wireless_close_script_proc_fd(wdev);
        wdev->script_proc_fd.fd = fds[0];
        uloop_fd_add(&wdev->script_proc_fd,
                 ULOOP_READ | ULOOP_EDGE_TRIGGER);
    }
    netifd_start_process(argv, NULL, &wdev->script_task);
    if (fds[1] >= 0)
        close(fds[1]);
    free(config);
}
References b, blob_memdup(), blobmsg_format_json(), config, D, wireless_device::drv, uloop_fd::fd, wireless_device::handler, wireless_device::handler_action, handler_pending, wireless_device::handler_pending, handlers, blob_buf::head, list_add_tail(), wireless_device::name, wireless_driver::name, netifd_start_process(), prepare_config(), wireless_device::prev_config, wireless_driver::script, wireless_device::script_proc_fd, wireless_device::script_task, wireless_device::serialize, ULOOP_EDGE_TRIGGER, uloop_fd_add(), ULOOP_READ, wireless_close_script_proc_fd(), and wireless_handler_stop().
Referenced by __wireless_device_set_down(), __wireless_device_set_up(), and wireless_handler_next().
wireless_device_script_task_cb()
static void wireless_device_script_task_cb (struct netifd_process * proc, int ret) static
Definition at line 692 of file wireless.c.
{
    struct wireless_device *wdev = container_of(proc, struct wireless_device, script_task);
    switch (wdev->state) {
    case IFS_SETUP:
        wireless_device_retry_setup(wdev);
        break;
    case IFS_TEARDOWN:
        wireless_device_mark_down(wdev);
        break;
    default:
        break;
    }
    if (wdev->serialize) {
        handler_pending = false;
        wireless_handler_next();
    }
}
References container_of, handler_pending, IFS_SETUP, IFS_TEARDOWN, wireless_device::script_task, wireless_device::serialize, wireless_device::state, wireless_device_mark_down(), wireless_device_retry_setup(), and wireless_handler_next().
Referenced by wireless_device_create().
wireless_device_set_down()
void wireless_device_set_down (struct wireless_device * wdev)
Definition at line 714 of file wireless.c.
{
    wdev->retry_setup_failed = false;
    wdev->autostart = false;
    __wireless_device_set_down(wdev);
}
References __wireless_device_set_down(), wireless_device::autostart, and wireless_device::retry_setup_failed.
Referenced by netifd_handle_wdev_down().
wireless_device_set_mcast_to_unicast()
static void wireless_device_set_mcast_to_unicast (struct device * dev, int val) static
Definition at line 329 of file wireless.c.
{
    if (val < 0) {
        dev->settings.flags &= ~DEV_OPT_MULTICAST_TO_UNICAST;
        return;
    }
    dev->settings.multicast_to_unicast = !!val;
    dev->settings.flags |= DEV_OPT_MULTICAST_TO_UNICAST;
}
References DEV_OPT_MULTICAST_TO_UNICAST, device_settings::flags, device_settings::multicast_to_unicast, and device::settings.
Referenced by wireless_interface_handle_link(), and wireless_vlan_handle_link().
wireless_device_set_retry()
static int wireless_device_set_retry (struct wireless_device * wdev, struct blob_attr * data) static
Definition at line 1483 of file wireless.c.
{
    static const struct blobmsg_policy retry_policy = {
        .name = "retry", .type = BLOBMSG_TYPE_INT32
    };
    struct blob_attr *val;
    blobmsg_parse_attr(&retry_policy, 1, &val, data);
    if (val)
        wdev->retry = blobmsg_get_u32(val);
    else
        wdev->retry = WIRELESS_SETUP_RETRY;
    __wireless_device_set_up(wdev, 0);
    netifd_log_message(L_NOTICE, "Wireless device '%s' set retry=%d\n", wdev->name, wdev->retry);
    return 0;
}
References __wireless_device_set_up(), blobmsg_get_u32(), blobmsg_parse_attr(), BLOBMSG_TYPE_INT32, blob_attr::data, L_NOTICE, wireless_device::name, netifd_log_message(), wireless_device::retry, and WIRELESS_SETUP_RETRY.
Referenced by wireless_device_notify().
wireless_device_set_up()
void wireless_device_set_up (struct wireless_device * wdev)
Definition at line 623 of file wireless.c.
{
    wdev->retry = WIRELESS_SETUP_RETRY;
    wdev->autostart = true;
    __wireless_device_set_up(wdev, 0);
}
References __wireless_device_set_up(), wireless_device::autostart, wireless_device::retry, and WIRELESS_SETUP_RETRY.
Referenced by netifd_handle_wdev_up().
wireless_device_setup_cancel()
static void wireless_device_setup_cancel (struct wireless_device * wdev) static
Definition at line 451 of file wireless.c.
{
    if (wdev->cancel)
        return;
    wireless_handler_stop(wdev);
    D(WIRELESS, "Cancel wireless device '%s' setup", wdev->name);
    wdev->cancel = true;
    uloop_timeout_set(&wdev->timeout, 10 * 1000);
}
References wireless_device::cancel, D, wireless_device::name, wireless_device::timeout, uloop_timeout_set(), and wireless_handler_stop().
Referenced by __wireless_device_set_down().
wireless_device_setup_timeout()
static void wireless_device_setup_timeout (struct uloop_timeout * timeout) static
Definition at line 609 of file wireless.c.
{
    struct wireless_device *wdev = container_of(timeout, struct wireless_device, timeout);
    if (wdev->handler_pending) {
        wdev->handler_pending = false;
        list_del(&wdev->handler);
    }
    netifd_kill_process(&wdev->script_task);
    wdev->script_task.cb(&wdev->script_task, -1);
    wireless_device_mark_down(wdev);
}
References netifd_process::cb, container_of, wireless_device::handler, wireless_device::handler_pending, list_del(), netifd_kill_process(), wireless_device::script_task, timeout, and wireless_device_mark_down().
Referenced by wireless_device_create().
wireless_device_status()
void wireless_device_status (struct wireless_device * wdev, struct blob_buf * b)
Definition at line 1303 of file wireless.c.
{
    struct wireless_interface *iface;
    void *c, *i;
    c = blobmsg_open_table(b, wdev->name);
    blobmsg_add_u8(b, "up", wdev->state == IFS_UP);
    blobmsg_add_u8(b, "pending", wdev->state == IFS_SETUP || wdev->state == IFS_TEARDOWN);
    blobmsg_add_u8(b, "autostart", wdev->autostart);
    blobmsg_add_u8(b, "disabled", wdev->disabled);
    blobmsg_add_u8(b, "retry_setup_failed", wdev->retry_setup_failed);
    put_container(b, wdev->config, "config");
    i = blobmsg_open_array(b, "interfaces");
    vlist_for_each_element(&wdev->interfaces, iface, node)
        wireless_interface_status(iface, b);
    blobmsg_close_array(b, i);
    blobmsg_close_table(b, c);
}
References wireless_device::autostart, b, blobmsg_add_u8(), blobmsg_close_array(), blobmsg_close_table(), blobmsg_open_array(), blobmsg_open_table(), wireless_device::config, wireless_device::disabled, IFS_SETUP, IFS_TEARDOWN, IFS_UP, wireless_device::interfaces, wireless_device::name, put_container(), wireless_device::retry_setup_failed, wireless_device::state, vlist_for_each_element, wireless_interface::wdev, and wireless_interface_status().
Referenced by netifd_handle_wdev_status().
wireless_handler_next()
static void wireless_handler_next (void) static
Definition at line 519 of file wireless.c.
{
    struct wireless_device *wdev;
    if (handler_pending)
        return;
    if (list_empty(&handlers))
        return;
    wdev = list_first_entry(&handlers, struct wireless_device, handler);
    list_del(&wdev->handler);
    wdev->handler_pending = false;
    wireless_device_run_handler(wdev, wdev->handler_action);
}
References wireless_device::handler, wireless_device::handler_action, handler_pending, wireless_device::handler_pending, handlers, list_del(), list_empty(), list_first_entry, and wireless_device_run_handler().
Referenced by wireless_device_script_task_cb().
wireless_handler_stop()
static void wireless_handler_stop (struct wireless_device * wdev) static
Definition at line 129 of file wireless.c.
{
    if (wdev->handler_pending) {
        wdev->handler_pending = false;
        list_del(&wdev->handler);
    }
}
References wireless_device::handler, wireless_device::handler_pending, and list_del().
Referenced by wireless_device_free(), wireless_device_free_state(), wireless_device_run_handler(), and wireless_device_setup_cancel().
wireless_init()
void wireless_init (void)
Definition at line 849 of file wireless.c.
{
    vlist_init(&wireless_devices, avl_strcmp, wdev_update);
    wireless_devices.keep_old = true;
    wireless_devices.no_delete = true;
    avl_init(&wireless_drivers, avl_strcmp, false, NULL);
    drv_fd = netifd_open_subdir("wireless");
    if (drv_fd < 0)
        return;
    netifd_init_script_handlers(drv_fd, wireless_add_handler);
}
References avl_init(), avl_strcmp(), drv_fd, vlist_tree::keep_old, netifd_init_script_handlers(), netifd_open_subdir(), vlist_tree::no_delete, vlist_init(), wdev_update(), wireless_add_handler(), wireless_devices, and wireless_drivers.
Referenced by main().
wireless_interface_create()
struct wireless_interface * wireless_interface_create (struct wireless_device * wdev, struct blob_attr * data, const char * section)
Definition at line 1233 of file wireless.c.
{
    struct wireless_interface *vif;
    struct blob_attr *tb[__VIF_ATTR_MAX];
    struct blob_attr *cur;
    char *name_buf;
    char name[8];
    blobmsg_parse_attr(vif_policy, __VIF_ATTR_MAX, tb, data);
    cur = tb[VIF_ATTR_DISABLED];
    if (cur && blobmsg_get_bool(cur))
        return NULL;
    sprintf(name, "%d", wdev->vif_idx++);
    vif = calloc_a(sizeof(*vif),
               &name_buf, strlen(name) + 1);
    vif->name = strcpy(name_buf, name);
    vif->wdev = wdev;
    vif->config = data;
    vif->section = section;
    vif->isolate = false;
    vlist_init(&vif->vlans, avl_strcmp, vlan_update);
    vif->vlans.keep_old = true;
    vlist_init(&vif->stations, avl_strcmp, station_update);
    vif->stations.keep_old = true;
    vlist_add(&wdev->interfaces, &vif->node, vif->name);
    vif = vlist_find(&wdev->interfaces, name, vif, node);
    if (!vif)
        return NULL;
    vif->vlan_idx = vif->sta_idx = 0;
    vlist_update(&vif->vlans);
    vlist_update(&vif->stations);
    return vif;
}
References __VIF_ATTR_MAX, avl_strcmp(), blobmsg_get_bool(), blobmsg_parse_attr(), calloc_a, wireless_interface::config, blob_attr::data, wireless_device::interfaces, wireless_interface::isolate, vlist_tree::keep_old, wireless_interface::name, wireless_interface::node, wireless_interface::section, wireless_interface::sta_idx, station_update(), wireless_interface::stations, VIF_ATTR_DISABLED, wireless_device::vif_idx, vif_policy, wireless_interface::vlan_idx, vlan_update(), wireless_interface::vlans, vlist_add(), vlist_find, vlist_init(), vlist_update(), and wireless_interface::wdev.
Referenced by config_init_procd_wireless_interface(), and config_parse_wireless_interface().
wireless_interface_handle_link()
static void wireless_interface_handle_link (struct wireless_interface * vif, const char * ifname, bool up) static
Definition at line 366 of file wireless.c.
{
    struct interface *iface;
    struct blob_attr *cur;
    const char *network;
    struct device *dev;
    int enabled = -1;
    size_t rem;
    if (!vif->network || !vif->ifname)
        return;
    if (!ifname)
        ifname = vif->ifname;
    if (!up)
        goto out;
    dev = __device_get(ifname, 2, false);
    if (!dev)
        goto out;
    dev->wireless = true;
    dev->settings.flags |= DEV_OPT_ISOLATE;
    dev->settings.isolate = vif->bridge_isolate;
    if (strcmp(ifname, vif->ifname) != 0)
        goto out;
    dev->wireless_isolate = vif->isolate;
    dev->wireless_proxyarp = vif->proxyarp;
    dev->wireless_ap = vif->ap_mode;
    wireless_device_set_mcast_to_unicast(dev, vif->multicast_to_unicast);
    dev->bpdu_filter = dev->wireless_ap;
out:
    wireless_check_interface(vif->network, &enabled, &vif->network_ifindex);
    blobmsg_for_each_attr(cur, vif->network, rem) {
        network = blobmsg_data(cur);
        iface = vlist_find(&interfaces, network, iface, node);
        if (!iface)
            continue;
        interface_handle_link(iface, ifname, vif->network_vlan, up, true);
    }
}
References __device_get(), wireless_interface::ap_mode, blobmsg_data(), blobmsg_for_each_attr, device::bpdu_filter, wireless_interface::bridge_isolate, DEV_OPT_ISOLATE, device_settings::flags, ifname, wireless_interface::ifname, interface_handle_link(), interfaces, device_settings::isolate, wireless_interface::isolate, wireless_interface::multicast_to_unicast, wireless_interface::network, wireless_interface::network_ifindex, wireless_interface::network_vlan, wireless_interface::proxyarp, device::settings, vlist_find, device::wireless, device::wireless_ap, wireless_check_interface(), wireless_device_set_mcast_to_unicast(), device::wireless_isolate, and device::wireless_proxyarp.
Referenced by vif_update(), wireless_device_hotplug_event(), wireless_device_mark_down(), and wireless_device_mark_up().
wireless_interface_init_config()
static void wireless_interface_init_config (struct wireless_interface * vif) static
Definition at line 865 of file wireless.c.
{
    struct blob_attr *tb[__VIF_ATTR_MAX];
    struct blob_attr *cur;
    vif->network = NULL;
    blobmsg_parse_attr(vif_policy, __VIF_ATTR_MAX, tb, vif->config);
    if ((cur = tb[VIF_ATTR_NETWORK]))
        vif->network = cur;
    if ((cur = tb[VIF_ATTR_NETWORK_VLAN]))
        vif->network_vlan = cur;
    cur = tb[VIF_ATTR_MODE];
    vif->ap_mode = cur && !strcmp(blobmsg_get_string(cur), "ap");
    cur = tb[VIF_ATTR_BRIDGE_ISOLATE];
    vif->bridge_isolate = cur && blobmsg_get_bool(cur);
    cur = tb[VIF_ATTR_ISOLATE];
    vif->isolate = cur && blobmsg_get_bool(cur);
    cur = tb[VIF_ATTR_PROXYARP];
    vif->proxyarp = vif->ap_mode && cur && blobmsg_get_bool(cur);
    cur = tb[VIF_ATTR_MCAST_TO_UCAST];
    vif->multicast_to_unicast = cur ? blobmsg_get_bool(cur) : -1;
}
References __VIF_ATTR_MAX, wireless_interface::ap_mode, blobmsg_get_bool(), blobmsg_get_string(), blobmsg_parse_attr(), wireless_interface::bridge_isolate, wireless_interface::config, wireless_interface::isolate, wireless_interface::multicast_to_unicast, wireless_interface::network, wireless_interface::network_vlan, wireless_interface::proxyarp, VIF_ATTR_BRIDGE_ISOLATE, VIF_ATTR_ISOLATE, VIF_ATTR_MCAST_TO_UCAST, VIF_ATTR_MODE, VIF_ATTR_NETWORK, VIF_ATTR_NETWORK_VLAN, VIF_ATTR_PROXYARP, and vif_policy.
Referenced by vif_update().
wireless_interface_set_data()
static void wireless_interface_set_data (struct wireless_interface * vif) static
Definition at line 1350 of file wireless.c.
{
    enum {
        VIF_DATA_IFNAME,
        __VIF_DATA_MAX,
    };
    static const struct blobmsg_policy data_policy[__VIF_DATA_MAX] = {
        [VIF_DATA_IFNAME] = { .name = "ifname", .type = BLOBMSG_TYPE_STRING },
    };
    struct blob_attr *tb[__VIF_DATA_MAX];
    struct blob_attr *cur;
    blobmsg_parse_attr(data_policy, __VIF_DATA_MAX, tb, vif->data);
    if ((cur = tb[VIF_DATA_IFNAME]))
        vif->ifname = blobmsg_data(cur);
}
References blobmsg_data(), blobmsg_parse_attr(), BLOBMSG_TYPE_STRING, wireless_interface::data, and wireless_interface::ifname.
Referenced by wireless_device_notify().
wireless_interface_status()
static void wireless_interface_status (struct wireless_interface * iface, struct blob_buf * b) static
Definition at line 1278 of file wireless.c.
{
    struct wireless_vlan *vlan;
    struct wireless_station *sta;
    void *i, *j;
    i = blobmsg_open_table(b, NULL);
    if (iface->section)
        blobmsg_add_string(b, "section", iface->section);
    if (iface->ifname)
        blobmsg_add_string(b, "ifname", iface->ifname);
    put_container(b, iface->config, "config");
    j = blobmsg_open_array(b, "vlans");
    vlist_for_each_element(&iface->vlans, vlan, node)
        wireless_vlan_status(vlan, b);
    blobmsg_close_array(b, j);
    j = blobmsg_open_array(b, "stations");
    vlist_for_each_element(&iface->stations, sta, node)
        wireless_station_status(sta, b);
    blobmsg_close_array(b, j);
    blobmsg_close_table(b, i);
}
References b, blobmsg_add_string(), blobmsg_close_array(), blobmsg_close_table(), blobmsg_open_array(), blobmsg_open_table(), wireless_interface::config, wireless_interface::ifname, put_container(), wireless_interface::section, wireless_interface::stations, wireless_interface::vlans, vlist_for_each_element, wireless_station_status(), and wireless_vlan_status().
Referenced by wireless_device_status().
wireless_proc_poll_fd()
static void wireless_proc_poll_fd (struct uloop_fd * fd, unsigned int events) static
Definition at line 1051 of file wireless.c.
{
    struct wireless_device *wdev = container_of(fd, struct wireless_device, script_proc_fd);
    char buf[128];
    while (1) {
        int b = read(fd->fd, buf, sizeof(buf));
        if (b < 0) {
            if (errno == EINTR)
                continue;
            if (errno == EAGAIN)
                return;
            goto done;
        }
        if (!b)
            goto done;
    }
done:
    uloop_timeout_set(&wdev->script_check, 0);
    wireless_close_script_proc_fd(wdev);
}
References b, buf, container_of, uloop_fd::fd, wireless_device::script_check, wireless_device::script_proc_fd, uloop_timeout_set(), and wireless_close_script_proc_fd().
Referenced by wireless_device_create().
wireless_process_check()
static bool wireless_process_check (struct wireless_process * proc) static
Definition at line 241 of file wireless.c.
{
    return check_pid_path(proc->pid, proc->exe);
}
References check_pid_path(), wireless_process::exe, and wireless_process::pid.
Referenced by wireless_device_check_script_tasks(), and wireless_process_kill_all().
wireless_process_free()
static void wireless_process_free (struct wireless_device * wdev, struct wireless_process * proc) static
Definition at line 258 of file wireless.c.
{
    D(WIRELESS, "Wireless device '%s' free pid %d", wdev->name, proc->pid);
    list_del(&proc->list);
    free(proc);
    if (list_empty(&wdev->script_proc))
        wireless_complete_kill_request(wdev);
}
References D, wireless_process::list, list_del(), list_empty(), wireless_device::name, wireless_process::pid, wireless_device::script_proc, and wireless_complete_kill_request().
Referenced by wireless_device_check_script_tasks(), and wireless_process_kill_all().
wireless_process_kill_all()
static void wireless_process_kill_all (struct wireless_device * wdev, int signal, bool free) static
Definition at line 280 of file wireless.c.
{
    struct wireless_process *proc, *tmp;
    list_for_each_entry_safe(proc, tmp, &wdev->script_proc, list) {
        bool check = wireless_process_check(proc);
        if (check && !proc->keep) {
            D(WIRELESS, "Wireless device '%s' kill pid %d", wdev->name, proc->pid);
            kill(proc->pid, signal);
        }
        if (free || !check)
            wireless_process_free(wdev, proc);
    }
    if (free)
        wireless_close_script_proc_fd(wdev);
}
References D, wireless_process::keep, wireless_process::list, list_for_each_entry_safe, wireless_device::name, wireless_process::pid, wireless_device::script_proc, wireless_close_script_proc_fd(), wireless_process_check(), and wireless_process_free().
Referenced by wireless_device_mark_down(), and wireless_device_process_kill_all().
wireless_start_pending()
void wireless_start_pending (int timeout)
Definition at line 1646 of file wireless.c.
{
    static struct uloop_timeout timer = {
        .cb = __wireless_start_pending
    };
    if (timeout) {
        uloop_timeout_set(&timer, timeout);
        return;
    }
    uloop_timeout_cancel(&timer);
    timer.cb(&timer);
}
References __wireless_start_pending(), uloop_timeout::cb, timeout, uloop_timeout_cancel(), and uloop_timeout_set().
Referenced by config_init_all(), and wireless_check_network_enabled().
wireless_station_create()
void wireless_station_create (struct wireless_interface * vif, struct blob_attr * data, const char * section)
Definition at line 1153 of file wireless.c.
{
    struct wireless_station *sta;
    struct blob_attr *tb[__STA_ATTR_MAX];
    struct blob_attr *cur;
    char *name_buf;
    char name[8];
    blobmsg_parse_attr(sta_policy, __STA_ATTR_MAX, tb, data);
    cur = tb[STA_ATTR_DISABLED];
    if (cur && blobmsg_get_bool(cur))
        return;
    sprintf(name, "%d", vif->sta_idx++);
    sta = calloc_a(sizeof(*sta),
               &name_buf, strlen(name) + 1);
    sta->name = strcpy(name_buf, name);
    sta->config = data;
    sta->section = section;
    vlist_add(&vif->stations, &sta->node, sta->name);
}
References __STA_ATTR_MAX, blobmsg_get_bool(), blobmsg_parse_attr(), calloc_a, wireless_station::config, blob_attr::data, wireless_station::name, wireless_station::node, wireless_station::section, STA_ATTR_DISABLED, wireless_interface::sta_idx, sta_policy, wireless_interface::stations, and vlist_add().
Referenced by config_init_procd_wireless_interface(), and config_parse_wireless_station().
wireless_station_status()
static void wireless_station_status (struct wireless_station * sta, struct blob_buf * b) static
Definition at line 1180 of file wireless.c.
{
    void *i;
    i = blobmsg_open_table(b, NULL);
    if (sta->section)
        blobmsg_add_string(b, "section", sta->section);
    put_container(b, sta->config, "config");
    blobmsg_close_table(b, i);
}
References b, blobmsg_add_string(), blobmsg_close_table(), blobmsg_open_table(), wireless_station::config, put_container(), and wireless_station::section.
Referenced by wireless_interface_status().
wireless_vlan_create()
void wireless_vlan_create (struct wireless_interface * vif, struct blob_attr * data, const char * section)
Definition at line 1193 of file wireless.c.
{
    struct wireless_vlan *vlan;
    struct blob_attr *tb[__VLAN_ATTR_MAX];
    struct blob_attr *cur;
    char *name_buf;
    char name[8];
    blobmsg_parse_attr(vlan_policy, __VLAN_ATTR_MAX, tb, data);
    cur = tb[VLAN_ATTR_DISABLED];
    if (cur && blobmsg_get_bool(cur))
        return;
    sprintf(name, "%d", vif->vlan_idx++);
    vlan = calloc_a(sizeof(*vlan), &name_buf, strlen(name) + 1);
    vlan->name = strcpy(name_buf, name);
    vlan->config = data;
    vlan->section = section;
    vlist_add(&vif->vlans, &vlan->node, vlan->name);
}
References __VLAN_ATTR_MAX, blobmsg_get_bool(), blobmsg_parse_attr(), calloc_a, wireless_vlan::config, blob_attr::data, wireless_vlan::name, wireless_vlan::node, wireless_vlan::section, VLAN_ATTR_DISABLED, wireless_interface::vlan_idx, vlan_policy, wireless_interface::vlans, and vlist_add().
Referenced by config_init_procd_wireless_interface(), and config_parse_wireless_vlan().
wireless_vlan_handle_link()
static void wireless_vlan_handle_link (struct wireless_vlan * vlan, bool up) static
Definition at line 414 of file wireless.c.
{
    struct interface *iface;
    struct blob_attr *cur;
    const char *network;
    int enabled = -1;
    size_t rem;
    if (!vlan->network || !vlan->ifname)
        return;
    if (up) {
        struct device *dev = device_get(vlan->ifname, 2);
        if (dev) {
            dev->wireless_isolate = vlan->isolate;
            dev->wireless = true;
            dev->wireless_ap = true;
            dev->bpdu_filter = true;
            dev->settings.flags |= DEV_OPT_ISOLATE;
            dev->settings.isolate = vlan->bridge_isolate;
            wireless_device_set_mcast_to_unicast(dev, vlan->multicast_to_unicast);
        }
    }
    wireless_check_interface(vlan->network, &enabled, &vlan->network_ifindex);
    blobmsg_for_each_attr(cur, vlan->network, rem) {
        network = blobmsg_data(cur);
        iface = vlist_find(&interfaces, network, iface, node);
        if (!iface)
            continue;
        interface_handle_link(iface, vlan->ifname, vlan->network_vlan, up, true);
    }
}
References blobmsg_data(), blobmsg_for_each_attr, device::bpdu_filter, wireless_vlan::bridge_isolate, DEV_OPT_ISOLATE, device_get(), device_settings::flags, wireless_vlan::ifname, interface_handle_link(), interfaces, device_settings::isolate, wireless_vlan::isolate, wireless_vlan::multicast_to_unicast, wireless_vlan::network, wireless_vlan::network_ifindex, wireless_vlan::network_vlan, device::settings, vlist_find, device::wireless, device::wireless_ap, wireless_check_interface(), wireless_device_set_mcast_to_unicast(), and device::wireless_isolate.
Referenced by vlan_update(), wireless_device_mark_down(), and wireless_device_mark_up().
wireless_vlan_init_config()
static void wireless_vlan_init_config (struct wireless_vlan * vlan) static
Definition at line 949 of file wireless.c.
{
    struct blob_attr *tb[__VLAN_ATTR_MAX];
    struct blob_attr *cur;
    vlan->network = NULL;
    blobmsg_parse_attr(vlan_policy, __VLAN_ATTR_MAX, tb, vlan->config);
    if ((cur = tb[VLAN_ATTR_NETWORK]))
        vlan->network = cur;
    if ((cur = tb[VLAN_ATTR_NETWORK_VLAN]))
        vlan->network_vlan = cur;
    cur = tb[VLAN_ATTR_BRIDGE_ISOLATE];
    vlan->bridge_isolate = cur && blobmsg_get_bool(cur);
    cur = tb[VLAN_ATTR_ISOLATE];
    vlan->isolate = cur && blobmsg_get_bool(cur);
    cur = tb[VLAN_ATTR_MCAST_TO_UCAST];
    vlan->multicast_to_unicast = cur ? blobmsg_get_bool(cur) : -1;
}
References __VLAN_ATTR_MAX, blobmsg_get_bool(), blobmsg_parse_attr(), wireless_vlan::bridge_isolate, wireless_vlan::config, wireless_vlan::isolate, wireless_vlan::multicast_to_unicast, wireless_vlan::network, wireless_vlan::network_vlan, VLAN_ATTR_BRIDGE_ISOLATE, VLAN_ATTR_ISOLATE, VLAN_ATTR_MCAST_TO_UCAST, VLAN_ATTR_NETWORK, VLAN_ATTR_NETWORK_VLAN, and vlan_policy.
Referenced by vlan_update().
wireless_vlan_set_data()
static void wireless_vlan_set_data (struct wireless_vlan * vlan) static
Definition at line 1370 of file wireless.c.
{
    enum {
        VLAN_DATA_IFNAME,
        __VLAN_DATA_MAX,
    };
    static const struct blobmsg_policy data_policy[__VLAN_DATA_MAX] = {
        [VLAN_DATA_IFNAME] = { .name = "ifname", .type = BLOBMSG_TYPE_STRING },
    };
    struct blob_attr *tb[__VLAN_DATA_MAX];
    struct blob_attr *cur;
    blobmsg_parse_attr(data_policy, __VLAN_DATA_MAX, tb, vlan->data);
    if ((cur = tb[VLAN_DATA_IFNAME]))
        vlan->ifname = blobmsg_data(cur);
}
References blobmsg_data(), blobmsg_parse_attr(), BLOBMSG_TYPE_STRING, wireless_vlan::data, and wireless_vlan::ifname.
Referenced by wireless_device_notify().
wireless_vlan_status()
static void wireless_vlan_status (struct wireless_vlan * vlan, struct blob_buf * b) static
Definition at line 1219 of file wireless.c.
{
    void *i;
    i = blobmsg_open_table(b, NULL);
    if (vlan->section)
        blobmsg_add_string(b, "section", vlan->section);
    if (vlan->ifname)
        blobmsg_add_string(b, "ifname", vlan->ifname);
    put_container(b, vlan->config, "config");
    blobmsg_close_table(b, i);
}
References b, blobmsg_add_string(), blobmsg_close_table(), blobmsg_open_table(), wireless_vlan::config, wireless_vlan::ifname, put_container(), and wireless_vlan::section.
Referenced by wireless_interface_status().
Variable Documentation
b
struct blob_buf b static
Definition at line 39 of file wireless.c.
Referenced by prepare_config(), wdev_prepare_prev_config(), wireless_device_get_validate(), wireless_device_run_handler(), wireless_device_status(), wireless_interface_status(), wireless_proc_poll_fd(), wireless_station_status(), and wireless_vlan_status().
drv_fd
int drv_fd static
Definition at line 40 of file wireless.c.
Referenced by wireless_device_create(), and wireless_init().
handler_pending
bool handler_pending static
Definition at line 42 of file wireless.c.
Referenced by wireless_device_run_handler(), wireless_device_script_task_cb(), and wireless_handler_next().
sta_policy
const struct blobmsg_policy sta_policy[__STA_ATTR_MAX] static
Initial value:
= {
    [STA_ATTR_DISABLED] = { .name = "disabled", .type = BLOBMSG_TYPE_BOOL },
}
Definition at line 119 of file wireless.c.
{
    [STA_ATTR_DISABLED] = { .name = "disabled", .type = BLOBMSG_TYPE_BOOL },
};
Referenced by wireless_station_create().
station_param
const struct uci_blob_param_list station_param static
Initial value:
= {
    .n_params = ARRAY_SIZE(sta_policy),
    .params = sta_policy,
}
Definition at line 123 of file wireless.c.
{
    .n_params = ARRAY_SIZE(sta_policy),
    .params = sta_policy,
};
Referenced by wireless_add_handler().
vif_param
const struct uci_blob_param_list vif_param static
Initial value:
= {
    .n_params = ARRAY_SIZE(vif_policy),
    .params = vif_policy,
}
Definition at line 85 of file wireless.c.
{
    .n_params = ARRAY_SIZE(vif_policy),
    .params = vif_policy,
};
Referenced by wireless_add_handler().
vif_policy
const struct blobmsg_policy vif_policy[__VIF_ATTR_MAX] static
Initial value:
= {
    [VIF_ATTR_DISABLED] = { .name = "disabled", .type = BLOBMSG_TYPE_BOOL },
    [VIF_ATTR_NETWORK] = { .name = "network", .type = BLOBMSG_TYPE_ARRAY },
    [VIF_ATTR_NETWORK_VLAN] = { .name = "network_vlan", .type = BLOBMSG_TYPE_ARRAY },
    [VIF_ATTR_BRIDGE_ISOLATE] = { .name = "bridge_isolate", .type = BLOBMSG_TYPE_BOOL },
    [VIF_ATTR_ISOLATE] = { .name = "isolate", .type = BLOBMSG_TYPE_BOOL },
    [VIF_ATTR_MODE] = { .name = "mode", .type = BLOBMSG_TYPE_STRING },
    [VIF_ATTR_PROXYARP] = { .name = "proxy_arp", .type = BLOBMSG_TYPE_BOOL },
    [VIF_ATTR_MCAST_TO_UCAST] = { .name = "multicast_to_unicast", .type = BLOBMSG_TYPE_BOOL },
}
Definition at line 74 of file wireless.c.
{
    [VIF_ATTR_DISABLED] = { .name = "disabled", .type = BLOBMSG_TYPE_BOOL },
    [VIF_ATTR_NETWORK] = { .name = "network", .type = BLOBMSG_TYPE_ARRAY },
    [VIF_ATTR_NETWORK_VLAN] = { .name = "network_vlan", .type = BLOBMSG_TYPE_ARRAY },
    [VIF_ATTR_BRIDGE_ISOLATE] = { .name = "bridge_isolate", .type = BLOBMSG_TYPE_BOOL },
    [VIF_ATTR_ISOLATE] = { .name = "isolate", .type = BLOBMSG_TYPE_BOOL },
    [VIF_ATTR_MODE] = { .name = "mode", .type = BLOBMSG_TYPE_STRING },
    [VIF_ATTR_PROXYARP] = { .name = "proxy_arp", .type = BLOBMSG_TYPE_BOOL },
    [VIF_ATTR_MCAST_TO_UCAST] = { .name = "multicast_to_unicast", .type = BLOBMSG_TYPE_BOOL },
};
Referenced by wireless_interface_create(), and wireless_interface_init_config().
vlan_param
const struct uci_blob_param_list vlan_param static
Initial value:
= {
    .n_params = ARRAY_SIZE(vlan_policy),
    .params = vlan_policy,
}
Definition at line 109 of file wireless.c.
{
    .n_params = ARRAY_SIZE(vlan_policy),
    .params = vlan_policy,
};
Referenced by wireless_add_handler().
vlan_policy
const struct blobmsg_policy vlan_policy[__VLAN_ATTR_MAX] static
Initial value:
= {
    [VLAN_ATTR_DISABLED] = { .name = "disabled", .type = BLOBMSG_TYPE_BOOL },
    [VLAN_ATTR_NETWORK] = { .name = "network", .type = BLOBMSG_TYPE_ARRAY },
    [VLAN_ATTR_NETWORK_VLAN] = { .name = "network_vlan", .type = BLOBMSG_TYPE_ARRAY },
    [VLAN_ATTR_BRIDGE_ISOLATE] = { .name = "bridge_isolate", .type = BLOBMSG_TYPE_BOOL },
    [VLAN_ATTR_ISOLATE] = { .name = "isolate", .type = BLOBMSG_TYPE_BOOL },
    [VLAN_ATTR_MCAST_TO_UCAST] = { .name = "multicast_to_unicast", .type = BLOBMSG_TYPE_BOOL },
}
Definition at line 100 of file wireless.c.
{
    [VLAN_ATTR_DISABLED] = { .name = "disabled", .type = BLOBMSG_TYPE_BOOL },
    [VLAN_ATTR_NETWORK] = { .name = "network", .type = BLOBMSG_TYPE_ARRAY },
    [VLAN_ATTR_NETWORK_VLAN] = { .name = "network_vlan", .type = BLOBMSG_TYPE_ARRAY },
    [VLAN_ATTR_BRIDGE_ISOLATE] = { .name = "bridge_isolate", .type = BLOBMSG_TYPE_BOOL },
    [VLAN_ATTR_ISOLATE] = { .name = "isolate", .type = BLOBMSG_TYPE_BOOL },
    [VLAN_ATTR_MCAST_TO_UCAST] = { .name = "multicast_to_unicast", .type = BLOBMSG_TYPE_BOOL },
};
Referenced by wireless_vlan_create(), and wireless_vlan_init_config().
wdev_param
const struct uci_blob_param_list wdev_param static
Initial value:
= {
    .n_params = ARRAY_SIZE(wdev_policy),
    .params = wdev_policy,
}
Definition at line 57 of file wireless.c.
{
    .n_params = ARRAY_SIZE(wdev_policy),
    .params = wdev_policy,
};
Referenced by wireless_add_handler().
wdev_policy
const struct blobmsg_policy wdev_policy[__WDEV_ATTR_MAX] static
Initial value:
= {
    [WDEV_ATTR_DISABLED] = { .name = "disabled", .type = BLOBMSG_TYPE_BOOL },
    [WDEV_ATTR_RECONF] = { .name = "reconf", .type = BLOBMSG_TYPE_BOOL },
    [WDEV_ATTR_SERIALIZE] = { .name = "serialize", .type = BLOBMSG_TYPE_BOOL },
}
Definition at line 51 of file wireless.c.
{
    [WDEV_ATTR_DISABLED] = { .name = "disabled", .type = BLOBMSG_TYPE_BOOL },
    [WDEV_ATTR_RECONF] = { .name = "reconf", .type = BLOBMSG_TYPE_BOOL },
    [WDEV_ATTR_SERIALIZE] = { .name = "serialize", .type = BLOBMSG_TYPE_BOOL },
};
Referenced by get_wdev(), and wireless_device_create().
wireless_devices
struct vlist_tree wireless_devices
Definition at line 37 of file wireless.c.
Referenced by __wireless_start_pending(), config_init_procd_wireless_interface(), config_init_wireless(), get_wdev(), netifd_handle_wdev_down(), netifd_handle_wdev_get_validate(), netifd_handle_wdev_reconf(), netifd_handle_wdev_status(), netifd_handle_wdev_up(), wireless_check_network_enabled(), wireless_device_create(), wireless_device_free(), wireless_device_hotplug_event(), and wireless_init().
wireless_drivers
struct avl_tree wireless_drivers
Definition at line 38 of file wireless.c.
Referenced by config_parse_wireless_device(), wireless_add_handler(), and wireless_init().