zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/rpcd/file.c File Reference
file.c File Reference
#include <fcntl.h>
#include <errno.h>
#include <unistd.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include <dirent.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <libubus.h>
#include <libubox/blobmsg.h>
#include <libubox/md5.h>
#include <libubox/ustream.h>
#include <libubox/utils.h>
#include <rpcd/plugin.h>
Classes
struct rpc_file_exec_context
Macros
#define _GNU_SOURCE
#define RPC_FILE_MIN_SIZE (4096)
#define RPC_FILE_MAX_SIZE (4096 * 64)
#define RPC_CMDLINE_MAX_SIZE (1024)
#define ustream_for_each_read_buffer(stream, ptr, len)
#define ustream_declare(us, fd, name)
#define rpc_check_path(msg, policy_selector, perm, path, s)
Enumerations
enum { RPC_F_R_PATH , RPC_F_R_SESSION , __RPC_F_R_MAX }
enum { RPC_F_RB_PATH , RPC_F_RB_BASE64 , RPC_F_RB_SESSION , __RPC_F_RB_MAX }
enum {
RPC_F_RW_PATH , RPC_F_RW_DATA , RPC_F_RW_APPEND , RPC_F_RW_MODE ,
RPC_F_RW_BASE64 , RPC_F_RW_SESSION , __RPC_F_RW_MAX
}
enum {
RPC_E_CMD , RPC_E_PARM , RPC_E_ENV , RPC_E_SESSION ,
__RPC_E_MAX
}
Functions
static int rpc_errno_status (void)
static bool rpc_file_access (const struct blob_attr *sid, const char *path, const char *perm)
static char * rpc_canonicalize_path (const char *path)
static struct blob_attr ** __rpc_check_path (const struct blobmsg_policy *policy, size_t policy_len, int policy_path_idx, int policy_sid_idx, const char *perm, struct blob_attr *msg, char **path, struct stat *s)
static int rpc_file_read (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int rpc_file_write (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int rpc_file_md5 (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static void _rpc_file_add_stat (struct stat *s)
static int rpc_file_list (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int rpc_file_stat (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int rpc_file_remove_recursive (const char *path)
static int rpc_file_remove (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static const char * rpc_file_exec_lookup (const char *cmd)
static void rpc_ustream_to_blobmsg (struct ustream *s, const char *name)
static void rpc_file_exec_reply (struct rpc_file_exec_context *c, int rv)
static void rpc_file_exec_timeout_cb (struct uloop_timeout *t)
static void rpc_file_exec_process_cb (struct uloop_process *p, int stat)
static void rpc_file_exec_opipe_read_cb (struct ustream *s, int bytes)
static void rpc_file_exec_epipe_read_cb (struct ustream *s, int bytes)
static void rpc_file_exec_opipe_state_cb (struct ustream *s)
static void rpc_file_exec_epipe_state_cb (struct ustream *s)
static void rpc_fdclose (int fd)
static int rpc_file_exec_run (const char *cmd, const struct blob_attr *sid, const struct blob_attr *arg, const struct blob_attr *env, struct ubus_context *ctx, struct ubus_request_data *req)
static int rpc_file_exec (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static int rpc_file_api_init (const struct rpc_daemon_ops *o, struct ubus_context *ctx)
Variables
static const struct rpc_daemon_ops * ops
static struct blob_buf buf
static char * canonpath
static char cmdstr [RPC_CMDLINE_MAX_SIZE]
static const struct blobmsg_policy rpc_file_R_policy [__RPC_F_R_MAX]
static const struct blobmsg_policy rpc_file_RB_policy [__RPC_F_RB_MAX]
static const struct blobmsg_policy rpc_file_RW_policy [__RPC_F_RW_MAX]
static const struct blobmsg_policy rpc_exec_policy [__RPC_E_MAX]
static const char * d_types []
struct rpc_plugin rpc_plugin
Class Documentation
rpc_file_exec_context
struct rpc_file_exec_context
Definition at line 64 of file file.c.
Class Members
struct ubus_context * context
struct ustream_fd epipe
struct ustream_fd opipe
struct uloop_process process
struct ubus_request_data request
int stat
struct uloop_timeout timeout
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 20 of file file.c.
rpc_check_path
#define rpc_check_path (msg, policy_selector, perm, path, s)
Value:
    __rpc_check_path(rpc_file_ ## policy_selector ## _policy, \
        ARRAY_SIZE(rpc_file_ ## policy_selector ## _policy), \
        RPC_F_ ## policy_selector ## _PATH, \
        RPC_F_ ## policy_selector ## _SESSION, \
        perm, msg, path, s)
Definition at line 281 of file file.c.
#define rpc_check_path(msg, policy_selector, perm, path, s) \
    __rpc_check_path(rpc_file_ ## policy_selector ## _policy, \
        ARRAY_SIZE(rpc_file_ ## policy_selector ## _policy), \
        RPC_F_ ## policy_selector ## _PATH, \
        RPC_F_ ## policy_selector ## _SESSION, \
        perm, msg, path, s)
Referenced by rpc_file_list(), rpc_file_md5(), rpc_file_read(), rpc_file_remove(), rpc_file_stat(), and rpc_file_write().
RPC_CMDLINE_MAX_SIZE
#define RPC_CMDLINE_MAX_SIZE (1024)
Definition at line 47 of file file.c.
RPC_FILE_MAX_SIZE
#define RPC_FILE_MAX_SIZE (4096 * 64)
Definition at line 44 of file file.c.
Referenced by rpc_file_read().
RPC_FILE_MIN_SIZE
#define RPC_FILE_MIN_SIZE (4096)
Definition at line 41 of file file.c.
Referenced by rpc_file_read().
ustream_declare
#define ustream_declare (us, fd, name)
Value:
    us.stream.string_data   = true;                       \
    us.stream.r.buffer_len  = 4096;                       \
    us.stream.r.max_buffers = RPC_FILE_MAX_SIZE / 4096;   \
    us.stream.notify_read   = rpc_file_##name##_read_cb;  \
    us.stream.notify_state  = rpc_file_##name##_state_cb; \
    ustream_fd_init(&us, fd);
Definition at line 54 of file file.c.
#define ustream_declare(us, fd, name)                     \
    us.stream.string_data   = true;                       \
    us.stream.r.buffer_len  = 4096;                       \
    us.stream.r.max_buffers = RPC_FILE_MAX_SIZE / 4096;   \
    us.stream.notify_read   = rpc_file_##name##_read_cb;  \
    us.stream.notify_state  = rpc_file_##name##_state_cb; \
    ustream_fd_init(&us, fd);
Referenced by rpc_file_exec_run().
ustream_for_each_read_buffer
#define ustream_for_each_read_buffer (stream, ptr, len)
Value:
    for (ptr = ustream_get_read_buf(stream, &len);     \
         ptr != NULL && len > 0;                       \
         ustream_consume(stream, len), ptr = ustream_get_read_buf(stream, &len))
Definition at line 49 of file file.c.
#define ustream_for_each_read_buffer(stream, ptr, len) \
    for (ptr = ustream_get_read_buf(stream, &len);     \
         ptr != NULL && len > 0;                       \
         ustream_consume(stream, len), ptr = ustream_get_read_buf(stream, &len))
Referenced by rpc_ustream_to_blobmsg(), and rpc_ustream_to_blobmsg().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
RPC_F_R_PATH
RPC_F_R_SESSION
__RPC_F_R_MAX
Definition at line 79 of file file.c.
     {
    RPC_F_R_PATH,
    RPC_F_R_SESSION,
    __RPC_F_R_MAX,
};
anonymous enum
anonymous enum
Enumerator
RPC_F_RB_PATH
RPC_F_RB_BASE64
RPC_F_RB_SESSION
__RPC_F_RB_MAX
Definition at line 91 of file file.c.
     {
    RPC_F_RB_PATH,
    RPC_F_RB_BASE64,
    RPC_F_RB_SESSION,
    __RPC_F_RB_MAX,
};
anonymous enum
anonymous enum
Enumerator
RPC_F_RW_PATH
RPC_F_RW_DATA
RPC_F_RW_APPEND
RPC_F_RW_MODE
RPC_F_RW_BASE64
RPC_F_RW_SESSION
__RPC_F_RW_MAX
Definition at line 105 of file file.c.
     {
    RPC_F_RW_PATH,
    RPC_F_RW_DATA,
    RPC_F_RW_APPEND,
    RPC_F_RW_MODE,
    RPC_F_RW_BASE64,
    RPC_F_RW_SESSION,
    __RPC_F_RW_MAX,
};
anonymous enum
anonymous enum
Enumerator
RPC_E_CMD
RPC_E_PARM
RPC_E_ENV
RPC_E_SESSION
__RPC_E_MAX
Definition at line 125 of file file.c.
     {
    RPC_E_CMD,
    RPC_E_PARM,
    RPC_E_ENV,
    RPC_E_SESSION,
    __RPC_E_MAX,
};
Function Documentation
__rpc_check_path()
static struct blob_attr ** __rpc_check_path (const struct blobmsg_policy * policy, size_t policy_len, int policy_path_idx, int policy_sid_idx, const char * perm, struct blob_attr * msg, char ** path, struct stat * s) static
Definition at line 247 of file file.c.
{
    static struct blob_attr *tb[__RPC_F_RW_MAX]; /* largest _MAX constant */
    blobmsg_parse(policy, policy_len, tb, blob_data(msg), blob_len(msg));
    if (!tb[policy_path_idx])
    {
        errno = EINVAL;
        return NULL;
    }
    *path = rpc_canonicalize_path(blobmsg_get_string(tb[policy_path_idx]));
    if (*path == NULL)
    {
        errno = ENOMEM;
        return NULL;
    }
    if (!rpc_file_access(tb[policy_sid_idx], *path, perm))
    {
        errno = EACCES;
        return NULL;
    }
    if (s != NULL && stat(*path, s) != 0)
        return NULL;
    return tb;
}
References __RPC_F_RW_MAX, blob_data(), blob_len(), blobmsg_get_string(), blobmsg_parse(), path, rpc_canonicalize_path(), and rpc_file_access().
_rpc_file_add_stat()
static void _rpc_file_add_stat (struct stat * s) static
Definition at line 465 of file file.c.
{
    int type;
    type = S_ISREG(s->st_mode) ? DT_REG :
            S_ISDIR(s->st_mode) ? DT_DIR :
             S_ISCHR(s->st_mode) ? DT_CHR :
              S_ISBLK(s->st_mode) ? DT_BLK :
               S_ISFIFO(s->st_mode) ? DT_FIFO :
                S_ISLNK(s->st_mode) ? DT_LNK :
                 S_ISSOCK(s->st_mode) ? DT_SOCK :
                  DT_UNKNOWN;
    blobmsg_add_string(&buf, "type", d_types[type]);
    blobmsg_add_u32(&buf, "size",  s->st_size);
    blobmsg_add_u32(&buf, "mode",  s->st_mode);
    blobmsg_add_u32(&buf, "atime", s->st_atime);
    blobmsg_add_u32(&buf, "mtime", s->st_mtime);
    blobmsg_add_u32(&buf, "ctime", s->st_ctime);
    blobmsg_add_u32(&buf, "inode", s->st_ino);
    blobmsg_add_u32(&buf, "uid",   s->st_uid);
    blobmsg_add_u32(&buf, "gid",   s->st_gid);
}
References blobmsg_add_string(), blobmsg_add_u32(), buf, d_types, and type.
Referenced by rpc_file_list(), and rpc_file_stat().
rpc_canonicalize_path()
static char * rpc_canonicalize_path (const char * path) static
Definition at line 186 of file file.c.
{
    char *cp;
    const char *p;
    if (path == NULL || *path == '\0')
        return NULL;
    if (canonpath != NULL)
        free(canonpath);
    canonpath = strdup(path);
    if (canonpath == NULL)
        return NULL;
    /* normalize */
    for (cp = canonpath, p = path; *p != '\0'; ) {
        if (*p != '/')
            goto next;
        /* skip repeating / */
        if (p[1] == '/') {
            p++;
            continue;
        }
        /* /./ or /../ */
        if (p[1] == '.') {
            /* skip /./ */
            if ((p[2] == '\0') || (p[2] == '/')) {
                p += 2;
                continue;
            }
            /* collapse /x/../ */
            if ((p[2] == '.') && ((p[3] == '\0') || (p[3] == '/'))) {
                while ((cp > canonpath) && (*--cp != '/'))
                    ;
                p += 3;
                continue;
            }
        }
next:
        *cp++ = *p++;
    }
    /* remove trailing slash if not root / */
    if ((cp > canonpath + 1) && (cp[-1] == '/'))
        cp--;
    else if (cp == canonpath)
        *cp++ = '/';
    *cp = '\0';
    return canonpath;
}
References canonpath, and path.
Referenced by __rpc_check_path(), and rpc_file_exec_run().
rpc_errno_status()
static int rpc_errno_status (void) static
Definition at line 154 of file file.c.
{
    switch (errno)
    {
    case EACCES:
        return UBUS_STATUS_PERMISSION_DENIED;
    case ENOTDIR:
        return UBUS_STATUS_INVALID_ARGUMENT;
    case ENOENT:
        return UBUS_STATUS_NOT_FOUND;
    case EINVAL:
        return UBUS_STATUS_INVALID_ARGUMENT;
    default:
        return UBUS_STATUS_UNKNOWN_ERROR;
    }
}
References UBUS_STATUS_INVALID_ARGUMENT, UBUS_STATUS_NOT_FOUND, UBUS_STATUS_PERMISSION_DENIED, and UBUS_STATUS_UNKNOWN_ERROR.
Referenced by rpc_file_exec_run(), rpc_file_list(), rpc_file_md5(), rpc_file_read(), rpc_file_remove(), rpc_file_remove_recursive(), rpc_file_stat(), and rpc_file_write().
rpc_fdclose()
static void rpc_fdclose (int fd) static
Definition at line 787 of file file.c.
{
    if (fd > 2)
        close(fd);
}
Referenced by rpc_file_exec_run().
rpc_file_access()
static bool rpc_file_access (const struct blob_attr * sid, const char * path, const char * perm) static
Definition at line 176 of file file.c.
{
    if (!sid)
        return true;
    return ops->session_access(blobmsg_data(sid), "file", path, perm);
}
References blobmsg_data(), ops, path, and rpc_daemon_ops::session_access.
Referenced by __rpc_check_path(), and rpc_file_exec_run().
rpc_file_api_init()
static int rpc_file_api_init (const struct rpc_daemon_ops * o, struct ubus_context * ctx) static
Definition at line 989 of file file.c.
{
    static const struct ubus_method file_methods[] = {
        UBUS_METHOD("read",    rpc_file_read,   rpc_file_RB_policy),
        UBUS_METHOD("write",   rpc_file_write,  rpc_file_RW_policy),
        UBUS_METHOD("list",    rpc_file_list,   rpc_file_R_policy),
        UBUS_METHOD("stat",    rpc_file_stat,   rpc_file_R_policy),
        UBUS_METHOD("md5",     rpc_file_md5,    rpc_file_R_policy),
        UBUS_METHOD("remove",  rpc_file_remove, rpc_file_R_policy),
        UBUS_METHOD("exec",    rpc_file_exec,   rpc_exec_policy),
    };
    static struct ubus_object_type file_type =
        UBUS_OBJECT_TYPE("rpcd-plugin-file", file_methods);
    static struct ubus_object obj = {
        .name = "file",
        .type = &file_type,
        .methods = file_methods,
        .n_methods = ARRAY_SIZE(file_methods),
    };
    ops = o;
    return ubus_add_object(ctx, &obj);
}
References ARRAY_SIZE, ctx, ubus_object_type::methods, ops, rpc_exec_policy, rpc_file_exec(), rpc_file_list(), rpc_file_md5(), rpc_file_R_policy, rpc_file_RB_policy, rpc_file_read(), rpc_file_remove(), rpc_file_RW_policy, rpc_file_stat(), rpc_file_write(), ubus_add_object(), UBUS_METHOD, and UBUS_OBJECT_TYPE.
rpc_file_exec()
static int rpc_file_exec (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 971 of file file.c.
{
    struct blob_attr *tb[__RPC_E_MAX];
    blobmsg_parse(rpc_exec_policy, __RPC_E_MAX, tb,
                  blob_data(msg), blob_len(msg));
    if (!tb[RPC_E_CMD])
        return UBUS_STATUS_INVALID_ARGUMENT;
    return rpc_file_exec_run(blobmsg_data(tb[RPC_E_CMD]), tb[RPC_E_SESSION],
                             tb[RPC_E_PARM], tb[RPC_E_ENV], ctx, req);
}
References __RPC_E_MAX, blob_data(), blob_len(), blobmsg_data(), blobmsg_parse(), ctx, RPC_E_CMD, RPC_E_ENV, RPC_E_PARM, RPC_E_SESSION, rpc_exec_policy, rpc_file_exec_run(), and UBUS_STATUS_INVALID_ARGUMENT.
Referenced by rpc_file_api_init().
rpc_file_exec_epipe_read_cb()
static void rpc_file_exec_epipe_read_cb (struct ustream * s, int bytes) static
Definition at line 757 of file file.c.
{
    struct rpc_file_exec_context *c =
        container_of(s, struct rpc_file_exec_context, epipe.stream);
    if (ustream_read_buf_full(s))
        rpc_file_exec_reply(c, UBUS_STATUS_NOT_SUPPORTED);
}
References container_of, rpc_file_exec_context::epipe, rpc_file_exec_reply(), ustream_fd::stream, UBUS_STATUS_NOT_SUPPORTED, and ustream_read_buf_full().
rpc_file_exec_epipe_state_cb()
static void rpc_file_exec_epipe_state_cb (struct ustream * s) static
Definition at line 777 of file file.c.
{
    struct rpc_file_exec_context *c =
        container_of(s, struct rpc_file_exec_context, epipe.stream);
    if (c->opipe.stream.eof && c->epipe.stream.eof)
        rpc_file_exec_reply(c, UBUS_STATUS_OK);
}
References container_of, ustream::eof, rpc_file_exec_context::epipe, rpc_file_exec_context::opipe, rpc_file_exec_reply(), ustream_fd::stream, and UBUS_STATUS_OK.
rpc_file_exec_lookup()
static const char * rpc_file_exec_lookup (const char * cmd) static
Definition at line 629 of file file.c.
{
    struct stat s;
    int plen = 0, clen = strlen(cmd) + 1;
    char *search, *p;
    static char path[PATH_MAX];
    if (!stat(cmd, &s) && S_ISREG(s.st_mode))
        return cmd;
    search = getenv("PATH");
    if (!search)
        search = "/bin:/usr/bin:/sbin:/usr/sbin";
    p = search;
    do
    {
        if (*p != ':' && *p != '\0')
            continue;
        plen = p - search;
        if ((plen + clen) >= sizeof(path))
            continue;
        strncpy(path, search, plen);
        sprintf(path + plen, "/%s", cmd);
        if (!stat(path, &s) && S_ISREG(s.st_mode))
            return path;
        search = p + 1;
    }
    while (*p++);
    return NULL;
}
References cmd, and path.
Referenced by rpc_file_exec_run().
rpc_file_exec_opipe_read_cb()
static void rpc_file_exec_opipe_read_cb (struct ustream * s, int bytes) static
Definition at line 747 of file file.c.
{
    struct rpc_file_exec_context *c =
        container_of(s, struct rpc_file_exec_context, opipe.stream);
    if (ustream_read_buf_full(s))
        rpc_file_exec_reply(c, UBUS_STATUS_NOT_SUPPORTED);
}
References container_of, rpc_file_exec_context::opipe, rpc_file_exec_reply(), ustream_fd::stream, UBUS_STATUS_NOT_SUPPORTED, and ustream_read_buf_full().
rpc_file_exec_opipe_state_cb()
static void rpc_file_exec_opipe_state_cb (struct ustream * s) static
Definition at line 767 of file file.c.
{
    struct rpc_file_exec_context *c =
        container_of(s, struct rpc_file_exec_context, opipe.stream);
    if (c->opipe.stream.eof && c->epipe.stream.eof)
        rpc_file_exec_reply(c, UBUS_STATUS_OK);
}
References container_of, ustream::eof, rpc_file_exec_context::epipe, rpc_file_exec_context::opipe, rpc_file_exec_reply(), ustream_fd::stream, and UBUS_STATUS_OK.
rpc_file_exec_process_cb()
static void rpc_file_exec_process_cb (struct uloop_process * p, int stat) static
Definition at line 735 of file file.c.
{
    struct rpc_file_exec_context *c =
        container_of(p, struct rpc_file_exec_context, process);
    c->stat = stat;
    ustream_poll(&c->opipe.stream);
    ustream_poll(&c->epipe.stream);
}
References container_of, rpc_file_exec_context::epipe, rpc_file_exec_context::opipe, rpc_file_exec_context::process, rpc_file_exec_context::stat, ustream_fd::stream, and ustream_poll().
Referenced by rpc_file_exec_run().
rpc_file_exec_reply()
static void rpc_file_exec_reply (struct rpc_file_exec_context * c, int rv) static
Definition at line 695 of file file.c.
{
    uloop_timeout_cancel(&c->timeout);
    uloop_process_delete(&c->process);
    if (rv == UBUS_STATUS_OK)
    {
        blob_buf_init(&buf, 0);
        blobmsg_add_u32(&buf, "code", WEXITSTATUS(c->stat));
        rpc_ustream_to_blobmsg(&c->opipe.stream, "stdout");
        rpc_ustream_to_blobmsg(&c->epipe.stream, "stderr");
        ubus_send_reply(c->context, &c->request, buf.head);
        blob_buf_free(&buf);
    }
    ubus_complete_deferred_request(c->context, &c->request, rv);
    ustream_free(&c->opipe.stream);
    ustream_free(&c->epipe.stream);
    close(c->opipe.fd.fd);
    close(c->epipe.fd.fd);
    free(c);
}
References blob_buf_free(), blob_buf_init(), blobmsg_add_u32(), buf, rpc_file_exec_context::context, rpc_file_exec_context::epipe, uloop_fd::fd, ustream_fd::fd, blob_buf::head, rpc_file_exec_context::opipe, rpc_file_exec_context::process, rpc_file_exec_context::request, rpc_ustream_to_blobmsg(), rpc_file_exec_context::stat, ustream_fd::stream, rpc_file_exec_context::timeout, ubus_complete_deferred_request(), ubus_send_reply(), UBUS_STATUS_OK, uloop_process_delete(), uloop_timeout_cancel(), and ustream_free().
Referenced by rpc_file_exec_epipe_read_cb(), rpc_file_exec_epipe_state_cb(), rpc_file_exec_opipe_read_cb(), rpc_file_exec_opipe_state_cb(), and rpc_file_exec_timeout_cb().
rpc_file_exec_run()
static int rpc_file_exec_run (const char * cmd, const struct blob_attr * sid, const struct blob_attr * arg, const struct blob_attr * env, struct ubus_context * ctx, struct ubus_request_data * req) static
Definition at line 794 of file file.c.
{
    pid_t pid;
    int devnull;
    int opipe[2];
    int epipe[2];
    int rem;
    struct blob_attr *cur;
    uint8_t arglen;
    char *executable, **args, **tmp, *p;
    struct rpc_file_exec_context *c;
    if (sid && env)
        return UBUS_STATUS_PERMISSION_DENIED;
    cmd = rpc_file_exec_lookup(cmd);
    if (!cmd)
        return UBUS_STATUS_NOT_FOUND;
    executable = rpc_canonicalize_path(cmd);
    if (executable == NULL)
        return UBUS_STATUS_UNKNOWN_ERROR;
    if (!rpc_file_access(sid, executable, "exec"))
    {
        if (arg == NULL || strlen(executable) >= sizeof(cmdstr))
            return UBUS_STATUS_PERMISSION_DENIED;
        arglen = 2;
        p = cmdstr + sprintf(cmdstr, "%s", executable);
        blobmsg_for_each_attr(cur, arg, rem)
        {
            if (blobmsg_type(cur) != BLOBMSG_TYPE_STRING)
                continue;
            if (arglen == 255 ||
                p + blobmsg_data_len(cur) >= cmdstr + sizeof(cmdstr))
                return UBUS_STATUS_PERMISSION_DENIED;
            p += sprintf(p, " %s", blobmsg_get_string(cur));
            arglen++;
        }
        if (!rpc_file_access(sid, cmdstr, "exec"))
            return UBUS_STATUS_PERMISSION_DENIED;
    }
    c = malloc(sizeof(*c));
    if (!c)
        return UBUS_STATUS_UNKNOWN_ERROR;
    if (pipe(opipe))
        goto fail_opipe;
    if (pipe(epipe))
        goto fail_epipe;
    switch ((pid = fork()))
    {
    case -1:
        goto fail_fork;
    case 0:
        uloop_done();
        devnull = open("/dev/null", O_RDWR);
        if (devnull == -1)
            return UBUS_STATUS_UNKNOWN_ERROR;
        dup2(devnull, 0);
        dup2(opipe[1], 1);
        dup2(epipe[1], 2);
        rpc_fdclose(devnull);
        rpc_fdclose(opipe[0]);
        rpc_fdclose(opipe[1]);
        rpc_fdclose(epipe[0]);
        rpc_fdclose(epipe[1]);
        arglen = 2;
        args = malloc(sizeof(char *) * arglen);
        if (!args)
            return UBUS_STATUS_UNKNOWN_ERROR;
        args[0] = (char *)executable;
        args[1] = NULL;
        if (arg)
        {
            blobmsg_for_each_attr(cur, arg, rem)
            {
                if (blobmsg_type(cur) != BLOBMSG_TYPE_STRING)
                    continue;
                if (arglen == 255)
                {
                    free(args);
                    return UBUS_STATUS_INVALID_ARGUMENT;
                }
                arglen++;
                tmp = realloc(args, sizeof(char *) * arglen);
                if (!tmp)
                {
                    free(args);
                    return UBUS_STATUS_UNKNOWN_ERROR;
                }
                args = tmp;
                args[arglen-2] = blobmsg_data(cur);
                args[arglen-1] = NULL;
            }
        }
        if (env)
        {
            blobmsg_for_each_attr(cur, env, rem)
            {
                if (blobmsg_type(cur) != BLOBMSG_TYPE_STRING)
                    continue;
                setenv(blobmsg_name(cur), blobmsg_data(cur), 1);
            }
        }
        if (execv(executable, args))
            return rpc_errno_status();
    default:
        memset(c, 0, sizeof(*c));
        ustream_declare(c->opipe, opipe[0], exec_opipe);
        ustream_declare(c->epipe, epipe[0], exec_epipe);
        c->process.pid = pid;
        c->process.cb = rpc_file_exec_process_cb;
        uloop_process_add(&c->process);
        c->timeout.cb = rpc_file_exec_timeout_cb;
        uloop_timeout_set(&c->timeout, *ops->exec_timeout);
        close(opipe[1]);
        close(epipe[1]);
        c->context = ctx;
        ubus_defer_request(ctx, req, &c->request);
    }
    return UBUS_STATUS_OK;
fail_fork:
    close(epipe[0]);
    close(epipe[1]);
fail_epipe:
    close(opipe[0]);
    close(opipe[1]);
fail_opipe:
    free(c);
    return rpc_errno_status();
}
References blobmsg_data(), blobmsg_data_len(), blobmsg_for_each_attr, blobmsg_get_string(), blobmsg_name(), BLOBMSG_TYPE_STRING, uloop_process::cb, uloop_timeout::cb, cmd, cmdstr, rpc_file_exec_context::context, ctx, rpc_file_exec_context::epipe, rpc_daemon_ops::exec_timeout, rpc_file_exec_context::opipe, ops, uloop_process::pid, rpc_file_exec_context::process, rpc_file_exec_context::request, rpc_canonicalize_path(), rpc_errno_status(), rpc_fdclose(), rpc_file_access(), rpc_file_exec_lookup(), rpc_file_exec_process_cb(), rpc_file_exec_timeout_cb(), rpc_file_exec_context::timeout, ubus_defer_request(), UBUS_STATUS_INVALID_ARGUMENT, UBUS_STATUS_NOT_FOUND, UBUS_STATUS_OK, UBUS_STATUS_PERMISSION_DENIED, UBUS_STATUS_UNKNOWN_ERROR, uloop_done(), uloop_process_add(), uloop_timeout_set(), and ustream_declare.
Referenced by rpc_file_exec().
rpc_file_exec_timeout_cb()
static void rpc_file_exec_timeout_cb (struct uloop_timeout * t) static
Definition at line 725 of file file.c.
{
    struct rpc_file_exec_context *c =
        container_of(t, struct rpc_file_exec_context, timeout);
    kill(c->process.pid, SIGKILL);
    rpc_file_exec_reply(c, UBUS_STATUS_TIMEOUT);
}
References container_of, uloop_process::pid, rpc_file_exec_context::process, rpc_file_exec_reply(), timeout, and UBUS_STATUS_TIMEOUT.
Referenced by rpc_file_exec_run().
rpc_file_list()
static int rpc_file_list (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 490 of file file.c.
{
    DIR *fd;
    void *c, *d;
    struct stat s;
    struct dirent *e;
    char *path, *entrypath;
    if (!rpc_check_path(msg, R, "list", &path, NULL))
        return rpc_errno_status();
    if ((fd = opendir(path)) == NULL)
        return rpc_errno_status();
    blob_buf_init(&buf, 0);
    c = blobmsg_open_array(&buf, "entries");
    while ((e = readdir(fd)) != NULL)
    {
        if (!strcmp(e->d_name, ".") || !strcmp(e->d_name, ".."))
            continue;
        if (asprintf(&entrypath, "%s/%s", path, e->d_name) < 0)
            continue;
        if (!stat(entrypath, &s))
        {
            d = blobmsg_open_table(&buf, NULL);
            blobmsg_add_string(&buf, "name", e->d_name);
            _rpc_file_add_stat(&s);
            blobmsg_close_table(&buf, d);
        }
        free(entrypath);
    }
    closedir(fd);
    blobmsg_close_array(&buf, c);
    ubus_send_reply(ctx, req, buf.head);
    blob_buf_free(&buf);
    return 0;
}
References _rpc_file_add_stat(), blob_buf_free(), blob_buf_init(), blobmsg_add_string(), blobmsg_close_array(), blobmsg_close_table(), blobmsg_open_array(), blobmsg_open_table(), buf, ctx, blob_buf::head, path, rpc_check_path, rpc_errno_status(), and ubus_send_reply().
Referenced by rpc_file_api_init().
rpc_file_md5()
static int rpc_file_md5 (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 432 of file file.c.
{
    int rv, i;
    char *path;
    struct stat s;
    uint8_t md5[16];
    char *wbuf;
    if (!rpc_check_path(msg, R, "read", &path, &s))
        return rpc_errno_status();
    if (!S_ISREG(s.st_mode))
        return UBUS_STATUS_NOT_SUPPORTED;
    if ((rv = md5sum(path, md5)) <= 0)
        return rpc_errno_status();
    blob_buf_init(&buf, 0);
    wbuf = blobmsg_alloc_string_buffer(&buf, "md5", 33);
    for (i = 0; i < 16; i++)
        sprintf(wbuf + (i * 2), "%02x", (uint8_t) md5[i]);
    blobmsg_add_string_buffer(&buf);
    ubus_send_reply(ctx, req, buf.head);
    blob_buf_free(&buf);
    return UBUS_STATUS_OK;
}
References blob_buf_free(), blob_buf_init(), blobmsg_add_string_buffer(), blobmsg_alloc_string_buffer(), buf, ctx, blob_buf::head, md5sum(), path, rpc_check_path, rpc_errno_status(), ubus_send_reply(), UBUS_STATUS_NOT_SUPPORTED, and UBUS_STATUS_OK.
Referenced by rpc_file_api_init().
rpc_file_read()
static int rpc_file_read (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 289 of file file.c.
{
    struct blob_attr **tb;
    bool base64 = false;
    int fd, rv;
    ssize_t len;
    char *path;
    struct stat s;
    char *wbuf;
    tb = rpc_check_path(msg, RB, "read", &path, &s);
    if (tb == NULL)
        return rpc_errno_status();
    if (s.st_size >= RPC_FILE_MAX_SIZE)
        return UBUS_STATUS_NOT_SUPPORTED;
    if ((fd = open(path, O_RDONLY)) < 0)
        return rpc_errno_status();
    /* some sysfs files do not report a length */
    if (s.st_size == 0)
        s.st_size = RPC_FILE_MIN_SIZE;
    blob_buf_init(&buf, 0);
    if (tb[RPC_F_RB_BASE64])
        base64 = blobmsg_get_bool(tb[RPC_F_RB_BASE64]);
    len = s.st_size + 1;
    if (base64)
        len = B64_ENCODE_LEN(s.st_size);
    wbuf = blobmsg_alloc_string_buffer(&buf, "data", len);
    if (!wbuf)
    {
        rv = UBUS_STATUS_UNKNOWN_ERROR;
        goto out;
    }
    if ((len = read(fd, wbuf, s.st_size)) <= 0)
    {
        rv = UBUS_STATUS_NO_DATA;
        goto out;
    }
    if (base64)
    {
        uint8_t *data = calloc(len, sizeof(uint8_t));
        if (!data)
        {
            rv = UBUS_STATUS_UNKNOWN_ERROR;
            goto out;
        }
        memcpy(data, wbuf, len);
        len = b64_encode(data, len, wbuf, B64_ENCODE_LEN(len));
        free(data);
        if (len < 0)
        {
            rv = UBUS_STATUS_UNKNOWN_ERROR;
            goto out;
        }
    }
    *(wbuf + len) = '\0';
    blobmsg_add_string_buffer(&buf);
    ubus_send_reply(ctx, req, buf.head);
    rv = UBUS_STATUS_OK;
out:
    blob_buf_free(&buf);
    close(fd);
    return rv;
}
References b64_encode(), B64_ENCODE_LEN, blob_buf_free(), blob_buf_init(), blobmsg_add_string_buffer(), blobmsg_alloc_string_buffer(), blobmsg_get_bool(), buf, ctx, blob_buf::head, path, rpc_check_path, rpc_errno_status(), RPC_F_RB_BASE64, RPC_FILE_MAX_SIZE, RPC_FILE_MIN_SIZE, ubus_send_reply(), UBUS_STATUS_NO_DATA, UBUS_STATUS_NOT_SUPPORTED, UBUS_STATUS_OK, and UBUS_STATUS_UNKNOWN_ERROR.
Referenced by rpc_file_api_init().
rpc_file_remove()
static int rpc_file_remove (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 606 of file file.c.
{
    struct stat s;
    char *path = NULL;
    if (!rpc_check_path(msg, R, "write", &path, NULL))
        return rpc_errno_status();
    if (lstat(path, &s))
        return rpc_errno_status();
    if (S_ISDIR(s.st_mode))
        return rpc_file_remove_recursive(path);
    if (unlink(path))
        return rpc_errno_status();
    return 0;
}
References path, rpc_check_path, rpc_errno_status(), and rpc_file_remove_recursive().
Referenced by rpc_file_api_init().
rpc_file_remove_recursive()
static int rpc_file_remove_recursive (const char * path) static
Definition at line 563 of file file.c.
{
    DIR *fd;
    int err = 0;
    struct stat s;
    struct dirent *e;
    char *entrypath;
    if ((fd = opendir(path)) == NULL)
        return rpc_errno_status();
    for (e = readdir(fd); e != NULL && err == 0; e = readdir(fd))
    {
        if (!strcmp(e->d_name, ".") || !strcmp(e->d_name, ".."))
            continue;
        if (asprintf(&entrypath, "%s/%s", path, e->d_name) >= 0)
        {
            if (!lstat(entrypath, &s))
            {
                if (S_ISDIR(s.st_mode))
                    err = rpc_file_remove_recursive(entrypath);
                else if (unlink(entrypath))
                    err = rpc_errno_status();
            }
            free(entrypath);
        }
        else
        {
            err = UBUS_STATUS_UNKNOWN_ERROR;
        }
    }
    closedir(fd);
    if (!err && rmdir(path))
        return rpc_errno_status();
    return err;
}
References err, path, rpc_errno_status(), rpc_file_remove_recursive(), and UBUS_STATUS_UNKNOWN_ERROR.
Referenced by rpc_file_remove(), and rpc_file_remove_recursive().
rpc_file_stat()
static int rpc_file_stat (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 538 of file file.c.
{
    char *path;
    struct stat s;
    if (!rpc_check_path(msg, R, "list", &path, &s))
        return rpc_errno_status();
    blob_buf_init(&buf, 0);
    blobmsg_add_string(&buf, "path", path);
    _rpc_file_add_stat(&s);
    ubus_send_reply(ctx, req, buf.head);
    blob_buf_free(&buf);
    return 0;
}
References _rpc_file_add_stat(), blob_buf_free(), blob_buf_init(), blobmsg_add_string(), buf, ctx, blob_buf::head, path, rpc_check_path, rpc_errno_status(), and ubus_send_reply().
Referenced by rpc_file_api_init().
rpc_file_write()
static int rpc_file_write (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 370 of file file.c.
{
    struct blob_attr **tb;
    int append = O_TRUNC;
    mode_t prev_mode, mode = 0666;
    int fd, rv = 0;
    char *path = NULL;
    void *data = NULL;
    ssize_t data_len = 0;
    tb = rpc_check_path(msg, RW, "write", &path, NULL);
    if (tb == NULL)
        return rpc_errno_status();
    if (!tb[RPC_F_RW_DATA])
        return UBUS_STATUS_INVALID_ARGUMENT;
    data = blobmsg_data(tb[RPC_F_RW_DATA]);
    data_len = blobmsg_data_len(tb[RPC_F_RW_DATA]) - 1;
    if (tb[RPC_F_RW_APPEND] && blobmsg_get_bool(tb[RPC_F_RW_APPEND]))
        append = O_APPEND;
    if (tb[RPC_F_RW_MODE])
        mode = blobmsg_get_u32(tb[RPC_F_RW_MODE]);
    prev_mode = umask(0);
    fd = open(path, O_CREAT | O_WRONLY | append, mode);
    umask(prev_mode);
    if (fd < 0)
        return rpc_errno_status();
    if (tb[RPC_F_RW_BASE64] && blobmsg_get_bool(tb[RPC_F_RW_BASE64]))
    {
        data_len = b64_decode(data, data, data_len);
        if (data_len < 0)
        {
            rv = UBUS_STATUS_UNKNOWN_ERROR;
            goto out;
        }
    }
    if (write(fd, data, data_len) < 0)
        rv = -1;
out:
    if (fsync(fd) < 0)
        rv = -1;
    close(fd);
    sync();
    if (rv)
        return rpc_errno_status();
    return 0;
}
References b64_decode(), blobmsg_data(), blobmsg_data_len(), blobmsg_get_bool(), blobmsg_get_u32(), blob_attr::data, path, rpc_check_path, rpc_errno_status(), RPC_F_RW_APPEND, RPC_F_RW_BASE64, RPC_F_RW_DATA, RPC_F_RW_MODE, UBUS_STATUS_INVALID_ARGUMENT, and UBUS_STATUS_UNKNOWN_ERROR.
Referenced by rpc_file_api_init().
rpc_ustream_to_blobmsg()
static void rpc_ustream_to_blobmsg (struct ustream * s, const char * name) static
Definition at line 671 of file file.c.
{
    int len;
    char *rbuf, *wbuf;
    if ((len = ustream_pending_data(s, false)) > 0)
    {
        wbuf = blobmsg_alloc_string_buffer(&buf, name, len + 1);
        if (!wbuf)
            return;
        ustream_for_each_read_buffer(s, rbuf, len)
        {
            memcpy(wbuf, rbuf, len);
            wbuf += len;
        }
        *wbuf = 0;
        blobmsg_add_string_buffer(&buf);
    }
}
References blobmsg_add_string_buffer(), blobmsg_alloc_string_buffer(), buf, ustream_for_each_read_buffer, and ustream_pending_data().
Referenced by rpc_file_exec_reply().
Variable Documentation
buf
struct blob_buf buf static
Definition at line 75 of file file.c.
Referenced by _rpc_file_add_stat(), rpc_file_exec_reply(), rpc_file_list(), rpc_file_md5(), rpc_file_read(), rpc_file_stat(), and rpc_ustream_to_blobmsg().
canonpath
char* canonpath static
Definition at line 76 of file file.c.
Referenced by rpc_canonicalize_path().
cmdstr
char cmdstr[RPC_CMDLINE_MAX_SIZE] static
Definition at line 77 of file file.c.
Referenced by rpc_file_exec_run().
d_types
const char* d_types[] static
Initial value:
= {
    [DT_BLK]     = "block",
    [DT_CHR]     = "char",
    [DT_DIR]     = "directory",
    [DT_FIFO]    = "fifo",
    [DT_LNK]     = "symlink",
    [DT_REG]     = "file",
    [DT_SOCK]    = "socket",
    [DT_UNKNOWN] = "unknown",
}
Definition at line 141 of file file.c.
{
    [DT_BLK]     = "block",
    [DT_CHR]     = "char",
    [DT_DIR]     = "directory",
    [DT_FIFO]    = "fifo",
    [DT_LNK]     = "symlink",
    [DT_REG]     = "file",
    [DT_SOCK]    = "socket",
    [DT_UNKNOWN] = "unknown",
};
Referenced by _rpc_file_add_stat().
ops
const struct rpc_daemon_ops* ops static
Definition at line 62 of file file.c.
Referenced by netifd_handle_iface_prepare(), rpc_file_access(), rpc_file_api_init(), rpc_file_exec_run(), rpc_iwinfo_phyname(), and rpc_ucode_api_init().
rpc_exec_policy
const struct blobmsg_policy rpc_exec_policy[__RPC_E_MAX] static
Initial value:
= {
    [RPC_E_CMD]     = { .name = "command", .type = BLOBMSG_TYPE_STRING },
    [RPC_E_PARM]    = { .name = "params",  .type = BLOBMSG_TYPE_ARRAY  },
    [RPC_E_ENV]     = { .name = "env",     .type = BLOBMSG_TYPE_TABLE  },
    [RPC_E_SESSION] = { .name = "ubus_rpc_session",
                        .type = BLOBMSG_TYPE_STRING },
}
Definition at line 133 of file file.c.
{
    [RPC_E_CMD]     = { .name = "command", .type = BLOBMSG_TYPE_STRING },
    [RPC_E_PARM]    = { .name = "params",  .type = BLOBMSG_TYPE_ARRAY  },
    [RPC_E_ENV]     = { .name = "env",     .type = BLOBMSG_TYPE_TABLE  },
    [RPC_E_SESSION] = { .name = "ubus_rpc_session",
                        .type = BLOBMSG_TYPE_STRING },
};
Referenced by rpc_file_api_init(), and rpc_file_exec().
rpc_file_R_policy
const struct blobmsg_policy rpc_file_R_policy[__RPC_F_R_MAX] static
Initial value:
= {
    [RPC_F_R_PATH]    = { .name = "path", .type = BLOBMSG_TYPE_STRING },
    [RPC_F_R_SESSION] = { .name = "ubus_rpc_session",
                          .type = BLOBMSG_TYPE_STRING },
}
Definition at line 85 of file file.c.
{
    [RPC_F_R_PATH]    = { .name = "path", .type = BLOBMSG_TYPE_STRING },
    [RPC_F_R_SESSION] = { .name = "ubus_rpc_session",
                          .type = BLOBMSG_TYPE_STRING },
};
Referenced by rpc_file_api_init().
rpc_file_RB_policy
const struct blobmsg_policy rpc_file_RB_policy[__RPC_F_RB_MAX] static
Initial value:
= {
    [RPC_F_RB_PATH]    = { .name = "path",   .type = BLOBMSG_TYPE_STRING },
    [RPC_F_RB_BASE64]  = { .name = "base64", .type = BLOBMSG_TYPE_BOOL   },
    [RPC_F_RB_SESSION] = { .name = "ubus_rpc_session",
                           .type = BLOBMSG_TYPE_STRING },
}
Definition at line 98 of file file.c.
{
    [RPC_F_RB_PATH]    = { .name = "path",   .type = BLOBMSG_TYPE_STRING },
    [RPC_F_RB_BASE64]  = { .name = "base64", .type = BLOBMSG_TYPE_BOOL   },
    [RPC_F_RB_SESSION] = { .name = "ubus_rpc_session",
                           .type = BLOBMSG_TYPE_STRING },
};
Referenced by rpc_file_api_init().
rpc_file_RW_policy
const struct blobmsg_policy rpc_file_RW_policy[__RPC_F_RW_MAX] static
Initial value:
= {
    [RPC_F_RW_PATH]    = { .name = "path",   .type = BLOBMSG_TYPE_STRING },
    [RPC_F_RW_DATA]    = { .name = "data",   .type = BLOBMSG_TYPE_STRING },
    [RPC_F_RW_APPEND]  = { .name = "append", .type = BLOBMSG_TYPE_BOOL  },
    [RPC_F_RW_MODE]    = { .name = "mode",   .type = BLOBMSG_TYPE_INT32  },
    [RPC_F_RW_BASE64]  = { .name = "base64", .type = BLOBMSG_TYPE_BOOL   },
    [RPC_F_RW_SESSION] = { .name = "ubus_rpc_session",
                           .type = BLOBMSG_TYPE_STRING },
}
Definition at line 115 of file file.c.
{
    [RPC_F_RW_PATH]    = { .name = "path",   .type = BLOBMSG_TYPE_STRING },
    [RPC_F_RW_DATA]    = { .name = "data",   .type = BLOBMSG_TYPE_STRING },
    [RPC_F_RW_APPEND]  = { .name = "append", .type = BLOBMSG_TYPE_BOOL  },
    [RPC_F_RW_MODE]    = { .name = "mode",   .type = BLOBMSG_TYPE_INT32  },
    [RPC_F_RW_BASE64]  = { .name = "base64", .type = BLOBMSG_TYPE_BOOL   },
    [RPC_F_RW_SESSION] = { .name = "ubus_rpc_session",
                           .type = BLOBMSG_TYPE_STRING },
};
Referenced by rpc_file_api_init().
rpc_plugin
struct rpc_plugin rpc_plugin
Initial value:
= {
    .init = rpc_file_api_init
}
Definition at line 1016 of file file.c.
{
    .init = rpc_file_api_init
};