zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/rpcd/plugin.c File Reference
plugin.c File Reference
#include <rpcd/plugin.h>
Classes
struct rpc_plugin_lookup_context
struct call_context
Functions
static void rpc_plugin_lookup_plugin_cb (struct ubus_context *ctx, struct ubus_object_data *obj, void *priv)
static bool rpc_plugin_lookup_plugin (struct ubus_context *ctx, struct ubus_object *obj, char *strptr)
static void rpc_plugin_json_array_to_blob (struct array_list *a, struct blob_buf *blob)
static void rpc_plugin_json_object_to_blob (json_object *o, struct blob_buf *blob)
static void rpc_plugin_json_element_to_blob (const char *name, json_object *val, struct blob_buf *blob)
static int rpc_plugin_call_stdin_cb (struct ustream *s, void *priv)
static int rpc_plugin_call_stdout_cb (struct blob_buf *blob, char *buf, int len, void *priv)
static int rpc_plugin_call_stderr_cb (struct blob_buf *blob, char *buf, int len, void *priv)
static int rpc_plugin_call_finish_cb (struct blob_buf *blob, int stat, void *priv)
static int rpc_plugin_call (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static bool rpc_plugin_parse_signature (struct blob_attr *sig, struct ubus_method *method)
static struct ubus_object * rpc_plugin_parse_exec (const char *name, int fd)
static int rpc_plugin_register_exec (struct ubus_context *ctx, const char *path)
static LIST_HEAD (plugins)
static int rpc_plugin_register_library (struct ubus_context *ctx, const char *path)
int rpc_plugin_api_init (struct ubus_context *ctx)
Variables
static struct blob_buf buf
static const struct rpc_daemon_ops ops
Class Documentation
rpc_plugin_lookup_context
struct rpc_plugin_lookup_context
Definition at line 23 of file plugin.c.
Class Members
bool found
uint32_t id
char * name
call_context
struct call_context
Definition at line 122 of file plugin.c.
Class Members
const char * argv[4]
char * input
bool input_done
char * method
json_object * obj
bool output_done
char path[PATH_MAX]
json_tokener * tok
Function Documentation
LIST_HEAD()
static LIST_HEAD (plugins) static
rpc_plugin_api_init()
int rpc_plugin_api_init (struct ubus_context * ctx)
Definition at line 509 of file plugin.c.
{
    DIR *d;
    int rv = 0;
    struct stat s;
    struct dirent *e;
    char path[PATH_MAX];
    if ((d = opendir(RPC_PLUGIN_DIRECTORY)) != NULL)
    {
        while ((e = readdir(d)) != NULL)
        {
            snprintf(path, sizeof(path) - 1,
                     RPC_PLUGIN_DIRECTORY "/%s", e->d_name);
            if (stat(path, &s) || !S_ISREG(s.st_mode) || !(s.st_mode & S_IXUSR))
                continue;
            rv |= rpc_plugin_register_exec(ctx, path);
        }
        closedir(d);
    }
    if ((d = opendir(RPC_LIBRARY_DIRECTORY)) != NULL)
    {
        while ((e = readdir(d)) != NULL)
        {
            snprintf(path, sizeof(path) - 1,
                     RPC_LIBRARY_DIRECTORY "/%s", e->d_name);
            if (stat(path, &s) || !S_ISREG(s.st_mode))
                continue;
            rv |= rpc_plugin_register_library(ctx, path);
        }
        closedir(d);
    }
    return rv;
}
References ctx, path, RPC_LIBRARY_DIRECTORY, RPC_PLUGIN_DIRECTORY, rpc_plugin_register_exec(), and rpc_plugin_register_library().
Referenced by main().
rpc_plugin_call()
static int rpc_plugin_call (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 201 of file plugin.c.
{
    int rv = UBUS_STATUS_UNKNOWN_ERROR;
    struct call_context *c;
    char *plugin, *mptr;
    c = calloc_a(sizeof(*c), &mptr, strlen(method) + 1);
    if (!c)
        goto fail;
    c->method = strcpy(mptr, method);
    c->input = blobmsg_format_json(msg, true);
    c->tok = json_tokener_new();
    if (!c->input || !c->tok)
        goto fail;
    plugin = c->path + sprintf(c->path, "%s/", RPC_PLUGIN_DIRECTORY);
    if (!rpc_plugin_lookup_plugin(ctx, obj, plugin))
    {
        rv = UBUS_STATUS_NOT_FOUND;
        goto fail;
    }
    c->argv[0] = c->path;
    c->argv[1] = "call";
    c->argv[2] = c->method;
    rv = rpc_exec(c->argv, rpc_plugin_call_stdin_cb,
                  rpc_plugin_call_stdout_cb, rpc_plugin_call_stderr_cb,
                  rpc_plugin_call_finish_cb, c, ctx, req);
    if (rv == UBUS_STATUS_OK)
        return rv;
fail:
    if (c)
    {
        if (c->input)
            free(c->input);
        if (c->tok)
            json_tokener_free(c->tok);
        free(c);
    }
    return rv;
}
References call_context::argv, blobmsg_format_json(), calloc_a, ctx, call_context::input, call_context::method, call_context::obj, call_context::path, rpc_exec(), rpc_plugin_call_finish_cb(), rpc_plugin_call_stderr_cb(), rpc_plugin_call_stdin_cb(), rpc_plugin_call_stdout_cb(), RPC_PLUGIN_DIRECTORY, rpc_plugin_lookup_plugin(), call_context::tok, UBUS_STATUS_NOT_FOUND, UBUS_STATUS_OK, and UBUS_STATUS_UNKNOWN_ERROR.
Referenced by rpc_plugin_parse_signature().
rpc_plugin_call_finish_cb()
static int rpc_plugin_call_finish_cb (struct blob_buf * blob, int stat, void * priv) static
Definition at line 170 of file plugin.c.
{
    struct call_context *c = priv;
    int rv = UBUS_STATUS_INVALID_ARGUMENT;
    if (json_tokener_get_error(c->tok) == json_tokener_success)
    {
        if (c->obj)
        {
            if (json_object_get_type(c->obj) == json_type_object)
            {
                rpc_plugin_json_object_to_blob(c->obj, blob);
                rv = UBUS_STATUS_OK;
            }
            json_object_put(c->obj);
        }
        else
        {
            rv = UBUS_STATUS_NO_DATA;
        }
    }
    json_tokener_free(c->tok);
    free(c->input);
    return rv;
}
References call_context::input, call_context::obj, rpc_plugin_json_object_to_blob(), call_context::tok, UBUS_STATUS_INVALID_ARGUMENT, UBUS_STATUS_NO_DATA, and UBUS_STATUS_OK.
Referenced by rpc_plugin_call().
rpc_plugin_call_stderr_cb()
static int rpc_plugin_call_stderr_cb (struct blob_buf * blob, char * buf, int len, void * priv) static
Definition at line 164 of file plugin.c.
{
    return len;
}
Referenced by rpc_plugin_call().
rpc_plugin_call_stdin_cb()
static int rpc_plugin_call_stdin_cb (struct ustream * s, void * priv) static
Definition at line 134 of file plugin.c.
{
    struct call_context *c = priv;
    if (!c->input_done)
    {
        ustream_write(s, c->input, strlen(c->input), false);
        c->input_done = true;
    }
    return 0;
}
References call_context::input, call_context::input_done, and ustream_write().
Referenced by rpc_plugin_call().
rpc_plugin_call_stdout_cb()
static int rpc_plugin_call_stdout_cb (struct blob_buf * blob, char * buf, int len, void * priv) static
Definition at line 148 of file plugin.c.
{
    struct call_context *c = priv;
    if (!c->output_done)
    {
        c->obj = json_tokener_parse_ex(c->tok, buf, len);
        if (json_tokener_get_error(c->tok) != json_tokener_continue)
            c->output_done = true;
    }
    return len;
}
References buf, call_context::obj, call_context::output_done, and call_context::tok.
Referenced by rpc_plugin_call().
rpc_plugin_json_array_to_blob()
static void rpc_plugin_json_array_to_blob (struct array_list * a, struct blob_buf * blob) static
Definition at line 107 of file plugin.c.
{
    int i, len;
    for (i = 0, len = array_list_length(a); i < len; i++)
        rpc_plugin_json_element_to_blob(NULL, array_list_get_idx(a, i), blob);
}
References rpc_plugin_json_element_to_blob().
Referenced by rpc_plugin_json_element_to_blob().
rpc_plugin_json_element_to_blob()
static void rpc_plugin_json_element_to_blob (const char * name, json_object * val, struct blob_buf * blob) static
Definition at line 61 of file plugin.c.
{
    void *c;
    int64_t n;
    switch (json_object_get_type(val)) {
    case json_type_object:
        c = blobmsg_open_table(blob, name);
        rpc_plugin_json_object_to_blob(val, blob);
        blobmsg_close_table(blob, c);
        break;
    case json_type_array:
        c = blobmsg_open_array(blob, name);
        rpc_plugin_json_array_to_blob(json_object_get_array(val), blob);
        blobmsg_close_array(blob, c);
        break;
    case json_type_string:
        blobmsg_add_string(blob, name, json_object_get_string(val));
        break;
    case json_type_boolean:
        blobmsg_add_u8(blob, name, json_object_get_boolean(val));
        break;
    case json_type_int:
        n = json_object_get_int64(val);
        if (n >= INT32_MIN && n <= INT32_MAX)
            blobmsg_add_u32(blob, name, n);
        else
            blobmsg_add_u64(blob, name, n);
        break;
    case json_type_double:
        blobmsg_add_double(blob, name, json_object_get_double(val));
        break;
    case json_type_null:
        blobmsg_add_field(blob, BLOBMSG_TYPE_UNSPEC, name, NULL, 0);
        break;
    }
}
References blobmsg_add_double(), blobmsg_add_field(), blobmsg_add_string(), blobmsg_add_u32(), blobmsg_add_u64(), blobmsg_add_u8(), blobmsg_close_array(), blobmsg_close_table(), blobmsg_open_array(), blobmsg_open_table(), BLOBMSG_TYPE_UNSPEC, rpc_plugin_lookup_context::name, rpc_plugin_json_array_to_blob(), and rpc_plugin_json_object_to_blob().
Referenced by rpc_plugin_json_array_to_blob(), and rpc_plugin_json_object_to_blob().
rpc_plugin_json_object_to_blob()
static void rpc_plugin_json_object_to_blob (json_object * o, struct blob_buf * blob) static
Definition at line 116 of file plugin.c.
{
    json_object_object_foreach(o, key, val)
        rpc_plugin_json_element_to_blob(key, val, blob);
}
References rpc_plugin_json_element_to_blob().
Referenced by rpc_plugin_call_finish_cb(), and rpc_plugin_json_element_to_blob().
rpc_plugin_lookup_plugin()
static bool rpc_plugin_lookup_plugin (struct ubus_context * ctx, struct ubus_object * obj, char * strptr) static
Definition at line 43 of file plugin.c.
{
    struct rpc_plugin_lookup_context c = { .id = obj->id, .name = strptr };
    if (ubus_lookup(ctx, NULL, rpc_plugin_lookup_plugin_cb, &c))
        return false;
    return c.found;
}
References ctx, rpc_plugin_lookup_context::found, ubus_object::id, rpc_plugin_lookup_plugin_cb(), and ubus_lookup().
Referenced by rpc_plugin_call().
rpc_plugin_lookup_plugin_cb()
static void rpc_plugin_lookup_plugin_cb (struct ubus_context * ctx, struct ubus_object_data * obj, void * priv) static
Definition at line 30 of file plugin.c.
{
    struct rpc_plugin_lookup_context *c = priv;
    if (c->id == obj->id)
    {
        c->found = true;
        sprintf(c->name, "%s", obj->path);
    }
}
References rpc_plugin_lookup_context::found, rpc_plugin_lookup_context::id, ubus_object_data::id, rpc_plugin_lookup_context::name, and ubus_object_data::path.
Referenced by rpc_plugin_lookup_plugin().
rpc_plugin_parse_exec()
static struct ubus_object * rpc_plugin_parse_exec (const char * name, int fd) static
Definition at line 322 of file plugin.c.
{
    int len, rem, n_method;
    struct blob_attr *cur;
    struct ubus_method *methods;
    struct ubus_object_type *obj_type;
    struct ubus_object *obj;
    char outbuf[1024];
    json_tokener *tok;
    json_object *jsobj;
    blob_buf_init(&buf, 0);
    tok = json_tokener_new();
    if (!tok)
        return NULL;
    while ((len = read(fd, outbuf, sizeof(outbuf))) > 0)
    {
        jsobj = json_tokener_parse_ex(tok, outbuf, len);
        if (json_tokener_get_error(tok) == json_tokener_continue)
            continue;
        if (json_tokener_get_error(tok) != json_tokener_success)
            break;
        if (jsobj)
        {
            if (json_object_get_type(jsobj) == json_type_object)
                blobmsg_add_object(&buf, jsobj);
            json_object_put(jsobj);
            break;
        }
    }
    json_tokener_free(tok);
    n_method = 0;
    blob_for_each_attr(cur, buf.head, rem)
        n_method++;
    if (!n_method)
        return NULL;
    methods = calloc(n_method, sizeof(*methods));
    if (!methods)
        return NULL;
    n_method = 0;
    blob_for_each_attr(cur, buf.head, rem)
    {
        if (!rpc_plugin_parse_signature(cur, &methods[n_method]))
            continue;
        n_method++;
    }
    obj = calloc(1, sizeof(*obj));
    if (!obj)
        return NULL;
    obj_type = calloc(1, sizeof(*obj_type));
    if (!obj_type) {
        free(obj);
        return NULL;
    }
    if (asprintf((char **)&obj_type->name, "rpcd-plugin-exec-%s", name) < 0) {
        free(obj);
        free(obj_type);
        return NULL;
    }
    obj_type->methods = methods;
    obj_type->n_methods = n_method;
    obj->name = strdup(name);
    obj->type = obj_type;
    obj->methods = methods;
    obj->n_methods = n_method;
    return obj;
}
References blob_buf_init(), blob_for_each_attr, blobmsg_add_object(), buf, blob_buf::head, ubus_object::methods, ubus_object_type::methods, ubus_object::n_methods, ubus_object_type::n_methods, ubus_object::name, ubus_object_type::name, rpc_plugin_parse_signature(), and ubus_object::type.
Referenced by rpc_plugin_register_exec().
rpc_plugin_parse_signature()
static bool rpc_plugin_parse_signature (struct blob_attr * sig, struct ubus_method * method) static
Definition at line 256 of file plugin.c.
{
    int rem, n_attr;
    enum blobmsg_type type;
    struct blob_attr *attr;
    struct blobmsg_policy *policy = NULL;
    if (!sig || blobmsg_type(sig) != BLOBMSG_TYPE_TABLE)
        return false;
    n_attr = 0;
    blobmsg_for_each_attr(attr, sig, rem)
        n_attr++;
    if (n_attr)
    {
        policy = calloc(n_attr, sizeof(*policy));
        if (!policy)
            return false;
        n_attr = 0;
        blobmsg_for_each_attr(attr, sig, rem)
        {
            type = blobmsg_type(attr);
            if (type == BLOBMSG_TYPE_INT32)
            {
                switch (blobmsg_get_u32(attr))
                {
                case 8:
                    type = BLOBMSG_TYPE_INT8;
                    break;
                case 16:
                    type = BLOBMSG_TYPE_INT16;
                    break;
                case 64:
                    type = BLOBMSG_TYPE_INT64;
                    break;
                default:
                    type = BLOBMSG_TYPE_INT32;
                    break;
                }
            }
            policy[n_attr].name = strdup(blobmsg_name(attr));
            policy[n_attr].type = type;
            n_attr++;
        }
    }
    method->name = strdup(blobmsg_name(sig));
    method->handler = rpc_plugin_call;
    method->policy = policy;
    method->n_policy = n_attr;
    return true;
}
References blobmsg_for_each_attr, blobmsg_get_u32(), blobmsg_name(), BLOBMSG_TYPE_INT16, BLOBMSG_TYPE_INT32, BLOBMSG_TYPE_INT64, BLOBMSG_TYPE_INT8, BLOBMSG_TYPE_TABLE, ubus_method::handler, ubus_method::n_policy, blobmsg_policy::name, ubus_method::name, ubus_method::policy, rpc_plugin_call(), blobmsg_policy::type, and type.
Referenced by rpc_plugin_parse_exec().
rpc_plugin_register_exec()
static int rpc_plugin_register_exec (struct ubus_context * ctx, const char * path) static
Definition at line 416 of file plugin.c.
{
    pid_t pid;
    int rv = UBUS_STATUS_NO_DATA, fd, fds[2];
    const char *name;
    struct ubus_object *plugin;
    name = strrchr(path, '/');
    if (!name)
        return UBUS_STATUS_INVALID_ARGUMENT;
    if (pipe(fds))
        return UBUS_STATUS_UNKNOWN_ERROR;
    switch ((pid = fork()))
    {
    case -1:
        return UBUS_STATUS_UNKNOWN_ERROR;
    case 0:
        fd = open("/dev/null", O_RDWR);
        if (fd > -1)
        {
            dup2(fd, 0);
            dup2(fd, 2);
            if (fd > 2)
                close(fd);
        }
        dup2(fds[1], 1);
        close(fds[0]);
        close(fds[1]);
        if (execl(path, path, "list", NULL))
            return UBUS_STATUS_UNKNOWN_ERROR;
    default:
        plugin = rpc_plugin_parse_exec(name + 1, fds[0]);
        if (!plugin)
            goto out;
        rv = ubus_add_object(ctx, plugin);
out:
        close(fds[0]);
        close(fds[1]);
        waitpid(pid, NULL, 0);
        return rv;
    }
}
References ctx, ubus_object::name, path, rpc_plugin_parse_exec(), ubus_add_object(), UBUS_STATUS_INVALID_ARGUMENT, UBUS_STATUS_NO_DATA, and UBUS_STATUS_UNKNOWN_ERROR.
Referenced by rpc_plugin_api_init().
rpc_plugin_register_library()
static int rpc_plugin_register_library (struct ubus_context * ctx, const char * path) static
Definition at line 485 of file plugin.c.
{
    struct rpc_plugin *p;
    void *dlh;
    dlh = dlopen(path, RTLD_LAZY | RTLD_LOCAL);
    if (!dlh) {
        fprintf(stderr, "Failed to load plugin %s: %s\n",
                path, dlerror());
        return UBUS_STATUS_UNKNOWN_ERROR;
    }
    p = dlsym(dlh, "rpc_plugin");
    if (!p)
        return UBUS_STATUS_NOT_FOUND;
    list_add(&p->list, &plugins);
    return p->init(&ops, ctx);
}
References ctx, rpc_plugin::init, rpc_plugin::list, list_add(), ops, path, UBUS_STATUS_NOT_FOUND, and UBUS_STATUS_UNKNOWN_ERROR.
Referenced by rpc_plugin_api_init().
Variable Documentation
buf
struct blob_buf buf static
Definition at line 21 of file plugin.c.
Referenced by rpc_plugin_call_stdout_cb(), and rpc_plugin_parse_exec().
ops
const struct rpc_daemon_ops ops static
Initial value:
= {
    .session_access     = rpc_session_access,
    .session_create_cb  = rpc_session_create_cb,
    .session_destroy_cb = rpc_session_destroy_cb,
    .exec               = rpc_exec,
    .exec_timeout       = &rpc_exec_timeout,
}
Definition at line 476 of file plugin.c.
{
    .session_access     = rpc_session_access,
    .session_create_cb  = rpc_session_create_cb,
    .session_destroy_cb = rpc_session_destroy_cb,
    .exec               = rpc_exec,
    .exec_timeout       = &rpc_exec_timeout,
};
Referenced by rpc_plugin_register_library().