zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/ubus/ubusd_event.c File Reference
ubusd_event.c File Reference
#include <arpa/inet.h>
#include "ubusd.h"
Classes
struct event_source
Enumerations
enum { EVREG_PATTERN , EVREG_OBJECT , EVREG_LAST }
enum { EVMSG_ID , EVMSG_DATA , EVMSG_LAST }
Functions
static void ubusd_delete_event_source (struct event_source *evs)
void ubusd_event_cleanup_object (struct ubus_object *obj)
static int ubusd_alloc_event_pattern (struct ubus_client *cl, struct blob_attr *msg)
static void ubusd_send_event_msg (struct ubus_msg_buf **ub, struct ubus_client *cl, struct ubus_object *obj, const char *id, event_fill_cb fill_cb, void *cb_priv)
int ubusd_send_event (struct ubus_client *cl, const char *id, event_fill_cb fill_cb, void *cb_priv)
static struct ubus_msg_buf * ubusd_create_event_from_msg (void *priv, const char *id)
static int ubusd_forward_event (struct ubus_client *cl, struct blob_attr *msg)
static int ubusd_event_recv (struct ubus_client *cl, struct ubus_msg_buf *ub, const char *method, struct blob_attr *msg)
static struct ubus_msg_buf * ubusd_create_object_event_msg (void *priv, const char *id)
void ubusd_send_obj_event (struct ubus_object *obj, bool add)
void ubusd_event_init (void)
Variables
static struct avl_tree patterns
static struct ubus_object * event_obj
static int event_seq = 0
static int obj_event_seq = 1
static struct blobmsg_policy evr_policy []
static struct blobmsg_policy ev_policy []
Class Documentation
event_source
struct event_source
Definition at line 22 of file ubusd_event.c.
Class Members
struct avl_node avl
struct list_head list
struct ubus_object * obj
bool partial
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
EVREG_PATTERN
EVREG_OBJECT
EVREG_LAST
Definition at line 45 of file ubusd_event.c.
     {
    EVREG_PATTERN,
    EVREG_OBJECT,
    EVREG_LAST,
};
anonymous enum
anonymous enum
Enumerator
EVMSG_ID
EVMSG_DATA
EVMSG_LAST
Definition at line 185 of file ubusd_event.c.
     {
    EVMSG_ID,
    EVMSG_DATA,
    EVMSG_LAST,
};
Function Documentation
ubusd_alloc_event_pattern()
static int ubusd_alloc_event_pattern (struct ubus_client * cl, struct blob_attr * msg) static
Definition at line 56 of file ubusd_event.c.
{
    struct event_source *ev;
    struct ubus_object *obj;
    struct blob_attr *attr[EVREG_LAST];
    char *pattern, *name;
    uint32_t id;
    bool partial = false;
    int len;
    if (!msg)
        return UBUS_STATUS_INVALID_ARGUMENT;
    blobmsg_parse(evr_policy, EVREG_LAST, attr, blob_data(msg), blob_len(msg));
    if (!attr[EVREG_OBJECT] || !attr[EVREG_PATTERN])
        return UBUS_STATUS_INVALID_ARGUMENT;
    id = blobmsg_get_u32(attr[EVREG_OBJECT]);
    if (id < UBUS_SYSTEM_OBJECT_MAX)
        return UBUS_STATUS_PERMISSION_DENIED;
    obj = ubusd_find_object(id);
    if (!obj)
        return UBUS_STATUS_NOT_FOUND;
    if (obj->client != cl)
        return UBUS_STATUS_PERMISSION_DENIED;
    pattern = blobmsg_data(attr[EVREG_PATTERN]);
    len = strlen(pattern);
    if (pattern[len - 1] == '*') {
        partial = true;
        pattern[len - 1] = 0;
        len--;
    }
    if (pattern[0] && ubusd_acl_check(cl, pattern, NULL, UBUS_ACL_LISTEN))
        return UBUS_STATUS_PERMISSION_DENIED;
    ev = calloc(1, sizeof(*ev) + len + 1);
    if (!ev)
        return UBUS_STATUS_NO_DATA;
    list_add(&ev->list, &obj->events);
    ev->obj = obj;
    ev->partial = partial;
    name = (char *) (ev + 1);
    strcpy(name, pattern);
    ev->avl.key = name;
    avl_insert(&patterns, &ev->avl);
    return 0;
}
References event_source::avl, avl_insert(), blob_data(), blob_len(), blobmsg_data(), blobmsg_get_u32(), blobmsg_parse(), ubus_object::client, ubus_object::events, evr_policy, EVREG_LAST, EVREG_OBJECT, EVREG_PATTERN, id, avl_node::key, event_source::list, list_add(), event_source::obj, event_source::partial, patterns, UBUS_ACL_LISTEN, UBUS_STATUS_INVALID_ARGUMENT, UBUS_STATUS_NO_DATA, UBUS_STATUS_NOT_FOUND, UBUS_STATUS_PERMISSION_DENIED, UBUS_SYSTEM_OBJECT_MAX, ubusd_acl_check(), and ubusd_find_object().
Referenced by ubusd_event_recv().
ubusd_create_event_from_msg()
static struct ubus_msg_buf * ubusd_create_event_from_msg (void * priv, const char * id) static
Definition at line 197 of file ubusd_event.c.
{
    struct blob_attr *msg = priv;
    blob_buf_init(&b, 0);
    blob_put_int32(&b, UBUS_ATTR_OBJID, 0);
    blob_put_string(&b, UBUS_ATTR_METHOD, id);
    blob_put(&b, UBUS_ATTR_DATA, blobmsg_data(msg), blobmsg_data_len(msg));
    return ubus_msg_new(b.head, blob_raw_len(b.head), true);
}
References b, blob_buf_init(), blob_put(), blob_put_int32, blob_put_string(), blob_raw_len(), blobmsg_data(), blobmsg_data_len(), blob_buf::head, UBUS_ATTR_DATA, UBUS_ATTR_METHOD, UBUS_ATTR_OBJID, and ubus_msg_new().
Referenced by ubusd_forward_event().
ubusd_create_object_event_msg()
static struct ubus_msg_buf * ubusd_create_object_event_msg (void * priv, const char * id) static
Definition at line 243 of file ubusd_event.c.
{
    struct ubus_object *obj = priv;
    void *s;
    blob_buf_init(&b, 0);
    blob_put_int32(&b, UBUS_ATTR_OBJID, 0);
    blob_put_string(&b, UBUS_ATTR_METHOD, id);
    s = blob_nest_start(&b, UBUS_ATTR_DATA);
    blobmsg_add_u32(&b, "id", obj->id.id);
    blobmsg_add_string(&b, "path", obj->path.key);
    blob_nest_end(&b, s);
    return ubus_msg_new(b.head, blob_raw_len(b.head), true);
}
References b, blob_buf_init(), blob_nest_end(), blob_nest_start(), blob_put_int32, blob_put_string(), blob_raw_len(), blobmsg_add_string(), blobmsg_add_u32(), blob_buf::head, ubus_object::id, ubus_object::path, UBUS_ATTR_DATA, UBUS_ATTR_METHOD, UBUS_ATTR_OBJID, and ubus_msg_new().
Referenced by ubusd_send_obj_event().
ubusd_delete_event_source()
static void ubusd_delete_event_source (struct event_source * evs) static
Definition at line 29 of file ubusd_event.c.
{
    list_del(&evs->list);
    avl_delete(&patterns, &evs->avl);
    free(evs);
}
References event_source::avl, avl_delete(), event_source::list, list_del(), and patterns.
Referenced by ubusd_event_cleanup_object().
ubusd_event_cleanup_object()
void ubusd_event_cleanup_object (struct ubus_object * obj)
Definition at line 36 of file ubusd_event.c.
{
    struct event_source *ev, *tmp;
    list_for_each_entry_safe(ev, tmp, &obj->events, list) {
        ubusd_delete_event_source(ev);
    }
}
References ubus_object::events, event_source::list, list_for_each_entry_safe, event_source::obj, and ubusd_delete_event_source().
Referenced by ubusd_free_object().
ubusd_event_init()
void ubusd_event_init (void)
Definition at line 266 of file ubusd_event.c.
{
    ubus_init_string_tree(&patterns, true);
    event_obj = ubusd_create_object_internal(NULL, UBUS_SYSTEM_OBJECT_EVENT);
    if (event_obj != NULL)
        event_obj->recv_msg = ubusd_event_recv;
}
References event_obj, patterns, ubus_object::recv_msg, ubus_init_string_tree(), UBUS_SYSTEM_OBJECT_EVENT, ubusd_create_object_internal(), and ubusd_event_recv().
Referenced by ubusd_obj_init().
ubusd_event_recv()
static int ubusd_event_recv (struct ubus_client * cl, struct ubus_msg_buf * ub, const char * method, struct blob_attr * msg) static
Definition at line 231 of file ubusd_event.c.
{
    if (!strcmp(method, "register"))
        return ubusd_alloc_event_pattern(cl, msg);
    if (!strcmp(method, "send"))
        return ubusd_forward_event(cl, msg);
    return UBUS_STATUS_INVALID_COMMAND;
}
References UBUS_STATUS_INVALID_COMMAND, ubusd_alloc_event_pattern(), and ubusd_forward_event().
Referenced by ubusd_event_init().
ubusd_forward_event()
static int ubusd_forward_event (struct ubus_client * cl, struct blob_attr * msg) static
Definition at line 209 of file ubusd_event.c.
{
    struct blob_attr *data;
    struct blob_attr *attr[EVMSG_LAST];
    const char *id;
    if (!msg)
        return UBUS_STATUS_INVALID_ARGUMENT;
    blobmsg_parse(ev_policy, EVMSG_LAST, attr, blob_data(msg), blob_len(msg));
    if (!attr[EVMSG_ID] || !attr[EVMSG_DATA])
        return UBUS_STATUS_INVALID_ARGUMENT;
    id = blobmsg_data(attr[EVMSG_ID]);
    data = attr[EVMSG_DATA];
    if (!strncmp(id, "ubus.", 5))
        return UBUS_STATUS_PERMISSION_DENIED;
    return ubusd_send_event(cl, id, ubusd_create_event_from_msg, data);
}
References blob_data(), blob_len(), blobmsg_data(), blobmsg_parse(), blob_attr::data, ev_policy, EVMSG_DATA, EVMSG_ID, EVMSG_LAST, id, UBUS_STATUS_INVALID_ARGUMENT, UBUS_STATUS_PERMISSION_DENIED, ubusd_create_event_from_msg(), and ubusd_send_event().
Referenced by ubusd_event_recv().
ubusd_send_event()
int ubusd_send_event (struct ubus_client * cl, const char * id, event_fill_cb fill_cb, void * cb_priv)
Definition at line 140 of file ubusd_event.c.
{
    struct ubus_msg_buf *ub = NULL;
    struct event_source *ev;
    int match_len = 0;
    if (ubusd_acl_check(cl, id, NULL, UBUS_ACL_SEND))
        return UBUS_STATUS_PERMISSION_DENIED;
    obj_event_seq++;
    /*
     * Since this tree is sorted alphabetically, we can only expect to find
     * matching entries as long as the number of matching characters
     * between the pattern string and our string is monotonically increasing.
     */
    avl_for_each_element(&patterns, ev, avl) {
        const char *key = ev->avl.key;
        int cur_match_len;
        bool full_match;
        full_match = ubus_strmatch_len(id, key, &cur_match_len);
        if (cur_match_len < match_len)
            break;
        match_len = cur_match_len;
        if (!full_match) {
            if (!ev->partial)
                continue;
            if (match_len != (int) strlen(key))
                continue;
        }
        ubusd_send_event_msg(&ub, cl, ev->obj, id, fill_cb, cb_priv);
    }
    if (ub)
        ubus_msg_free(ub);
    return 0;
}
References event_source::avl, avl_for_each_element, avl_node::key, event_source::obj, obj_event_seq, event_source::partial, patterns, UBUS_ACL_SEND, ubus_msg_free(), UBUS_STATUS_PERMISSION_DENIED, ubus_strmatch_len(), ubusd_acl_check(), and ubusd_send_event_msg().
Referenced by ubusd_acl_load(), ubusd_forward_event(), and ubusd_send_obj_event().
ubusd_send_event_msg()
static void ubusd_send_event_msg (struct ubus_msg_buf ** ub, struct ubus_client * cl, struct ubus_object * obj, const char * id, event_fill_cb fill_cb, void * cb_priv) static
Definition at line 111 of file ubusd_event.c.
{
    uint32_t *objid_ptr;
    /* do not loop back events */
    if (obj->client == cl)
        return;
    /* do not send duplicate events */
    if (obj->event_seen == obj_event_seq)
        return;
    obj->event_seen = obj_event_seq;
    if (!*ub) {
        *ub = fill_cb(cb_priv, id);
        (*ub)->hdr.type = UBUS_MSG_INVOKE;
        (*ub)->hdr.peer = 0;
    }
    objid_ptr = blob_data(blob_data((*ub)->data));
    *objid_ptr = htonl(obj->id.id);
    (*ub)->hdr.seq = ++event_seq;
    ubus_msg_send(obj->client, *ub);
}
References blob_data(), ubus_object::client, ubus_object::event_seen, event_seq, ubus_object::id, obj_event_seq, UBUS_MSG_INVOKE, and ubus_msg_send().
Referenced by ubusd_send_event().
ubusd_send_obj_event()
void ubusd_send_obj_event (struct ubus_object * obj, bool add)
Definition at line 259 of file ubusd_event.c.
{
    const char *id = add ? "ubus.object.add" : "ubus.object.remove";
    ubusd_send_event(NULL, id, ubusd_create_object_event_msg, obj);
}
References ubusd_create_object_event_msg(), and ubusd_send_event().
Referenced by ubusd_create_object(), and ubusd_free_object().
Variable Documentation
ev_policy
struct blobmsg_policy ev_policy[] static
Initial value:
= {
    [EVMSG_ID] = { .name = "id", .type = BLOBMSG_TYPE_STRING },
    [EVMSG_DATA] = { .name = "data", .type = BLOBMSG_TYPE_TABLE },
}
Definition at line 191 of file ubusd_event.c.
{
    [EVMSG_ID] = { .name = "id", .type = BLOBMSG_TYPE_STRING },
    [EVMSG_DATA] = { .name = "data", .type = BLOBMSG_TYPE_TABLE },
};
Referenced by ubusd_forward_event().
event_obj
struct ubus_object* event_obj static
Definition at line 18 of file ubusd_event.c.
Referenced by ubusd_event_init().
event_seq
int event_seq = 0 static
Definition at line 19 of file ubusd_event.c.
Referenced by ubusd_send_event_msg().
evr_policy
struct blobmsg_policy evr_policy[] static
Initial value:
= {
    [EVREG_PATTERN] = { .name = "pattern", .type = BLOBMSG_TYPE_STRING },
    [EVREG_OBJECT] = { .name = "object", .type = BLOBMSG_TYPE_INT32 },
}
Definition at line 51 of file ubusd_event.c.
{
    [EVREG_PATTERN] = { .name = "pattern", .type = BLOBMSG_TYPE_STRING },
    [EVREG_OBJECT] = { .name = "object", .type = BLOBMSG_TYPE_INT32 },
};
Referenced by ubusd_alloc_event_pattern().
obj_event_seq
int obj_event_seq = 1 static
Definition at line 20 of file ubusd_event.c.
Referenced by ubusd_send_event(), and ubusd_send_event_msg().
patterns
struct avl_tree patterns static
Definition at line 17 of file ubusd_event.c.
Referenced by ubusd_alloc_event_pattern(), ubusd_delete_event_source(), ubusd_event_init(), and ubusd_send_event().