zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/ustp/driver.h File Reference
driver.h File Reference
#include "mstp.h"
Functions
static int driver_set_new_state (per_tree_port_t *ptp, int new_state)
static void driver_flush_all_fids (per_tree_port_t *ptp)
static unsigned int driver_set_ageing_time (port_t *prt, unsigned int ageingTime)
static bool driver_create_msti (bridge_t *br, __u16 mstid)
static bool driver_delete_msti (bridge_t *br, __u16 mstid)
static bool driver_create_bridge (bridge_t *br, __u8 *macaddr)
static bool driver_create_port (port_t *prt, __u16 portno)
static void driver_delete_bridge (bridge_t *br)
static void driver_delete_port (port_t *prt)
Function Documentation
driver_create_bridge()
static bool driver_create_bridge (bridge_t * br, __u8 * macaddr) inline static
Definition at line 48 of file driver.h.
{
    return true;
}
Referenced by MSTP_IN_bridge_create().
driver_create_msti()
static bool driver_create_msti (bridge_t * br, __u16 mstid) inline static
Definition at line 36 of file driver.h.
{
    return true;
}
driver_create_port()
static bool driver_create_port (port_t * prt, __u16 portno) inline static
Definition at line 54 of file driver.h.
{
    return true;
}
Referenced by MSTP_IN_port_create_and_add_tail().
driver_delete_bridge()
static void driver_delete_bridge (bridge_t * br) inline static
Definition at line 59 of file driver.h.
{
}
Referenced by MSTP_IN_delete_bridge().
driver_delete_msti()
static bool driver_delete_msti (bridge_t * br, __u16 mstid) inline static
Definition at line 42 of file driver.h.
{
    return true;
}
driver_delete_port()
static void driver_delete_port (port_t * prt) inline static
Definition at line 63 of file driver.h.
{
}
Referenced by MSTP_IN_delete_port().
driver_flush_all_fids()
static void driver_flush_all_fids (per_tree_port_t * ptp) inline static
Definition at line 24 of file driver.h.
{
    MSTP_IN_all_fids_flushed(ptp);
}
References MSTP_IN_all_fids_flushed().
Referenced by MSTP_OUT_flush_all_fids().
driver_set_ageing_time()
static unsigned int driver_set_ageing_time (port_t * prt, unsigned int ageingTime) inline static
Definition at line 30 of file driver.h.
{
    return ageingTime;
}
Referenced by MSTP_OUT_set_ageing_time().
driver_set_new_state()
static int driver_set_new_state (per_tree_port_t * ptp, int new_state) inline static
Definition at line 18 of file driver.h.
{
    return new_state;
}
Referenced by MSTP_OUT_set_state().