zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/ubus/libubus.c File Reference
libubus.c File Reference
#include <sys/types.h>
#include <sys/socket.h>
#include <unistd.h>
#include <libubox/blob.h>
#include <libubox/blobmsg.h>
#include "libubus.h"
#include "libubus-internal.h"
#include "ubusmsg.h"
Classes
struct ubus_pending_msg
struct ubus_lookup_request
Functions
static int ubus_cmp_id (const void *k1, const void *k2, void *ptr)
const char * ubus_strerror (int error)
static void ubus_queue_msg (struct ubus_context *ctx, struct ubus_msghdr_buf *buf)
void __hidden ubus_process_msg (struct ubus_context *ctx, struct ubus_msghdr_buf *buf, int fd)
static void ubus_process_pending_msg (struct uloop_timeout *timeout)
static void ubus_lookup_cb (struct ubus_request *ureq, int type, struct blob_attr *msg)
int ubus_lookup (struct ubus_context *ctx, const char *path, ubus_lookup_handler_t cb, void *priv)
static void ubus_lookup_id_cb (struct ubus_request *req, int type, struct blob_attr *msg)
int ubus_lookup_id (struct ubus_context *ctx, const char *path, uint32_t *id)
static int ubus_event_cb (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
int ubus_register_event_handler (struct ubus_context *ctx, struct ubus_event_handler *ev, const char *pattern)
int ubus_send_event (struct ubus_context *ctx, const char *id, struct blob_attr *data)
static void ubus_default_connection_lost (struct ubus_context *ctx)
int ubus_connect_ctx (struct ubus_context *ctx, const char *path)
static void ubus_auto_reconnect_cb (struct uloop_timeout *timeout)
static void ubus_auto_disconnect_cb (struct ubus_context *ctx)
static void ubus_auto_connect_cb (struct uloop_timeout *timeout)
void ubus_auto_connect (struct ubus_auto_conn *conn)
struct ubus_context * ubus_connect (const char *path)
void ubus_shutdown (struct ubus_context *ctx)
void ubus_free (struct ubus_context *ctx)
Variables
const char * __ubus_strerror [__UBUS_STATUS_LAST]
struct blob_buf b __hidden = {}
static const struct ubus_method event_method
Class Documentation
ubus_pending_msg
struct ubus_pending_msg
Definition at line 44 of file libubus.c.
Class Members
struct ubus_msghdr_buf hdr
struct list_head list
ubus_lookup_request
struct ubus_lookup_request
Definition at line 136 of file libubus.c.
Class Members
ubus_lookup_handler_t cb
struct ubus_request req
Function Documentation
ubus_auto_connect()
void ubus_auto_connect (struct ubus_auto_conn * conn)
Definition at line 345 of file libubus.c.
{
    conn->timer.cb = ubus_auto_connect_cb;
    ubus_auto_connect_cb(&conn->timer);
}
References uloop_timeout::cb, conn, ubus_auto_conn::timer, and ubus_auto_connect_cb().
Referenced by ustp_ubus_init().
ubus_auto_connect_cb()
static void ubus_auto_connect_cb (struct uloop_timeout * timeout) static
Definition at line 330 of file libubus.c.
{
    struct ubus_auto_conn *conn = container_of(timeout, struct ubus_auto_conn, timer);
    if (ubus_connect_ctx(&conn->ctx, conn->path)) {
        uloop_timeout_set(timeout, 1000);
        fprintf(stderr, "failed to connect to ubus\n");
        return;
    }
    conn->ctx.connection_lost = ubus_auto_disconnect_cb;
    if (conn->cb)
        conn->cb(&conn->ctx);
    ubus_add_uloop(&conn->ctx);
}
References ubus_auto_conn::cb, conn, ubus_context::connection_lost, container_of, ubus_auto_conn::ctx, ubus_auto_conn::path, timeout, ubus_auto_conn::timer, ubus_add_uloop(), ubus_auto_disconnect_cb(), ubus_connect_ctx(), and uloop_timeout_set().
Referenced by ubus_auto_connect().
ubus_auto_disconnect_cb()
static void ubus_auto_disconnect_cb (struct ubus_context * ctx) static
Definition at line 322 of file libubus.c.
{
    struct ubus_auto_conn *conn = container_of(ctx, struct ubus_auto_conn, ctx);
    conn->timer.cb = ubus_auto_reconnect_cb;
    uloop_timeout_set(&conn->timer, 1000);
}
References uloop_timeout::cb, conn, container_of, ctx, ubus_auto_conn::timer, ubus_auto_reconnect_cb(), and uloop_timeout_set().
Referenced by ubus_auto_connect_cb().
ubus_auto_reconnect_cb()
static void ubus_auto_reconnect_cb (struct uloop_timeout * timeout) static
Definition at line 312 of file libubus.c.
{
    struct ubus_auto_conn *conn = container_of(timeout, struct ubus_auto_conn, timer);
    if (!ubus_reconnect(&conn->ctx, conn->path))
        ubus_add_uloop(&conn->ctx);
    else
        uloop_timeout_set(timeout, 1000);
}
References conn, container_of, ubus_auto_conn::ctx, ubus_auto_conn::path, timeout, ubus_auto_conn::timer, ubus_add_uloop(), ubus_reconnect(), and uloop_timeout_set().
Referenced by ubus_auto_disconnect_cb().
ubus_cmp_id()
static int ubus_cmp_id (const void * k1, const void * k2, void * ptr) static
Definition at line 49 of file libubus.c.
{
    const uint32_t *id1 = k1, *id2 = k2;
    if (*id1 < *id2)
        return -1;
    else
        return *id1 > *id2;
}
Referenced by ubus_connect_ctx().
ubus_connect()
struct ubus_context * ubus_connect (const char * path)
Definition at line 351 of file libubus.c.
{
    struct ubus_context *ctx;
    ctx = calloc(1, sizeof(*ctx));
    if (!ctx)
        return NULL;
    if (ubus_connect_ctx(ctx, path)) {
        free(ctx);
        ctx = NULL;
    }
    return ctx;
}
References ctx, path, and ubus_connect_ctx().
Referenced by main(), netifd_ubus_init(), pass_console(), run_netifd(), ubus_connect_cb(), ubus_lua_connect(), and uxc_attach().
ubus_connect_ctx()
int ubus_connect_ctx (struct ubus_context * ctx, const char * path)
Definition at line 284 of file libubus.c.
{
    uloop_init();
    memset(ctx, 0, sizeof(*ctx));
    ctx->sock.fd = -1;
    ctx->sock.cb = ubus_handle_data;
    ctx->connection_lost = ubus_default_connection_lost;
    ctx->pending_timer.cb = ubus_process_pending_msg;
    ctx->msgbuf.data = calloc(1, UBUS_MSG_CHUNK_SIZE);
    if (!ctx->msgbuf.data)
        return -1;
    ctx->msgbuf_data_len = UBUS_MSG_CHUNK_SIZE;
    INIT_LIST_HEAD(&ctx->requests);
    INIT_LIST_HEAD(&ctx->pending);
    INIT_LIST_HEAD(&ctx->auto_subscribers);
    avl_init(&ctx->objects, ubus_cmp_id, false, NULL);
    if (ubus_reconnect(ctx, path)) {
        free(ctx->msgbuf.data);
        ctx->msgbuf.data = NULL;
        return -1;
    }
    return 0;
}
References ubus_context::auto_subscribers, avl_init(), uloop_fd::cb, uloop_timeout::cb, ubus_context::connection_lost, ctx, ubus_msghdr_buf::data, uloop_fd::fd, INIT_LIST_HEAD(), ubus_context::msgbuf, ubus_context::msgbuf_data_len, ubus_context::objects, path, ubus_context::pending, ubus_context::pending_timer, ubus_context::requests, ubus_context::sock, ubus_cmp_id(), ubus_default_connection_lost(), ubus_handle_data(), UBUS_MSG_CHUNK_SIZE, ubus_process_pending_msg(), ubus_reconnect(), and uloop_init().
Referenced by ubus_auto_connect_cb(), and ubus_connect().
ubus_default_connection_lost()
static void ubus_default_connection_lost (struct ubus_context * ctx) static
Definition at line 278 of file libubus.c.
{
    if (ctx->sock.registered)
        uloop_end();
}
References ctx, uloop_fd::registered, ubus_context::sock, and uloop_end().
Referenced by ubus_connect_ctx().
ubus_event_cb()
static int ubus_event_cb (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 209 of file libubus.c.
{
    struct ubus_event_handler *ev;
    ev = container_of(obj, struct ubus_event_handler, obj);
    ev->cb(ctx, ev, method, msg);
    return 0;
}
References ubus_event_handler::cb, container_of, ctx, and ubus_event_handler::obj.
ubus_free()
void ubus_free (struct ubus_context * ctx)
Definition at line 378 of file libubus.c.
{
    ubus_shutdown(ctx);
    free(ctx);
}
References ctx, and ubus_shutdown().
Referenced by free_and_exit(), jail_network_stop(), main(), netifd_ubus_done(), pass_console(), post_poststop(), ubus_lua__gc(), and uxc_attach().
ubus_lookup()
int ubus_lookup (struct ubus_context * ctx, const char * path, ubus_lookup_handler_t cb, void * priv)
Definition at line 161 of file libubus.c.
{
    struct ubus_lookup_request lookup;
    blob_buf_init(&b, 0);
    if (path)
        blob_put_string(&b, UBUS_ATTR_OBJPATH, path);
    if (ubus_start_request(ctx, &lookup.req, b.head, UBUS_MSG_LOOKUP, 0) < 0)
        return UBUS_STATUS_INVALID_ARGUMENT;
    lookup.req.raw_data_cb = ubus_lookup_cb;
    lookup.req.priv = priv;
    lookup.cb = cb;
    return ubus_complete_request(ctx, &lookup.req, 0);
}
References b, blob_buf_init(), blob_put_string(), ubus_lookup_request::cb, ctx, blob_buf::head, path, ubus_request::priv, ubus_request::raw_data_cb, ubus_lookup_request::req, UBUS_ATTR_OBJPATH, ubus_complete_request(), ubus_lookup_cb(), UBUS_MSG_LOOKUP, ubus_start_request(), and UBUS_STATUS_INVALID_ARGUMENT.
Referenced by rpc_plugin_lookup_plugin(), ubus_cli_list(), ubus_cli_wait_for(), ubus_lua_objects(), ubus_lua_signatures(), ubus_refresh_auto_subscribe(), and ubus_register_subscriber().
ubus_lookup_cb()
static void ubus_lookup_cb (struct ubus_request * ureq, int type, struct blob_attr * msg) static
Definition at line 141 of file libubus.c.
{
    struct ubus_lookup_request *req;
    struct ubus_object_data obj = {};
    struct blob_attr **attr;
    req = container_of(ureq, struct ubus_lookup_request, req);
    attr = ubus_parse_msg(msg, blob_raw_len(msg));
    if (!attr[UBUS_ATTR_OBJID] || !attr[UBUS_ATTR_OBJPATH] ||
        !attr[UBUS_ATTR_OBJTYPE])
        return;
    obj.id = blob_get_u32(attr[UBUS_ATTR_OBJID]);
    obj.path = blob_data(attr[UBUS_ATTR_OBJPATH]);
    obj.type_id = blob_get_u32(attr[UBUS_ATTR_OBJTYPE]);
    obj.signature = attr[UBUS_ATTR_SIGNATURE];
    req->cb(ureq->ctx, &obj, ureq->priv);
}
References blob_data(), blob_get_u32(), blob_raw_len(), ubus_lookup_request::cb, container_of, ubus_request::ctx, ubus_object_data::id, ubus_object_data::path, ubus_request::priv, ubus_lookup_request::req, ubus_object_data::signature, ubus_object_data::type_id, UBUS_ATTR_OBJID, UBUS_ATTR_OBJPATH, UBUS_ATTR_OBJTYPE, UBUS_ATTR_SIGNATURE, and ubus_parse_msg().
Referenced by ubus_lookup().
ubus_lookup_id()
int ubus_lookup_id (struct ubus_context * ctx, const char * path, uint32_t * id)
Definition at line 192 of file libubus.c.
{
    struct ubus_request req;
    blob_buf_init(&b, 0);
    if (path)
        blob_put_string(&b, UBUS_ATTR_OBJPATH, path);
    if (ubus_start_request(ctx, &req, b.head, UBUS_MSG_LOOKUP, 0) < 0)
        return UBUS_STATUS_INVALID_ARGUMENT;
    req.raw_data_cb = ubus_lookup_id_cb;
    req.priv = id;
    return ubus_complete_request(ctx, &req, 0);
}
References b, blob_buf_init(), blob_put_string(), ctx, blob_buf::head, id, path, ubus_request::priv, ubus_request::raw_data_cb, UBUS_ATTR_OBJPATH, ubus_complete_request(), ubus_lookup_id_cb(), UBUS_MSG_LOOKUP, ubus_start_request(), and UBUS_STATUS_INVALID_ARGUMENT.
Referenced by client_main(), extdev_lookup_id(), get_ocistate(), jail_delete_instance(), jail_network_reload(), netifd_sub_cb(), netifd_ubus_get_procd_data(), netns_updown(), pass_console(), rpc_uci_trigger_event(), run_netifd(), run_ubusd(), runtime_load(), test_count(), ubus_cli_call(), ubus_cli_subscribe(), ubus_lua_call(), ubus_lua_do_subscribe(), ustp_ubus_exit(), uxc_attach(), uxc_boot(), uxc_create(), uxc_delete(), uxc_kill(), uxc_start(), watch_subscribe_cb(), and watch_ubus_service().
ubus_lookup_id_cb()
static void ubus_lookup_id_cb (struct ubus_request * req, int type, struct blob_attr * msg) static
Definition at line 179 of file libubus.c.
{
    struct blob_attr **attr;
    uint32_t *id = req->priv;
    attr = ubus_parse_msg(msg, blob_raw_len(msg));
    if (!attr[UBUS_ATTR_OBJID])
        return;
    *id = blob_get_u32(attr[UBUS_ATTR_OBJID]);
}
References blob_get_u32(), blob_raw_len(), ubus_request::priv, UBUS_ATTR_OBJID, and ubus_parse_msg().
Referenced by ubus_lookup_id().
ubus_process_msg()
void __hidden ubus_process_msg (struct ubus_context * ctx, struct ubus_msghdr_buf * buf, int fd)
Definition at line 93 of file libubus.c.
{
    switch(buf->hdr.type) {
    case UBUS_MSG_STATUS:
    case UBUS_MSG_DATA:
        ubus_process_req_msg(ctx, buf, fd);
        break;
    case UBUS_MSG_INVOKE:
    case UBUS_MSG_UNSUBSCRIBE:
    case UBUS_MSG_NOTIFY:
        if (ctx->stack_depth) {
            ubus_queue_msg(ctx, buf);
            break;
        }
        ctx->stack_depth++;
        ubus_process_obj_msg(ctx, buf, fd);
        ctx->stack_depth--;
        break;
    case UBUS_MSG_MONITOR:
        if (ctx->monitor_cb)
            ctx->monitor_cb(ctx, buf->hdr.seq, buf->data);
        break;
    }
}
References buf, ctx, ubus_context::monitor_cb, ubus_context::stack_depth, UBUS_MSG_DATA, UBUS_MSG_INVOKE, UBUS_MSG_MONITOR, UBUS_MSG_NOTIFY, UBUS_MSG_STATUS, UBUS_MSG_UNSUBSCRIBE, ubus_process_obj_msg(), ubus_process_req_msg(), and ubus_queue_msg().
Referenced by ubus_handle_data(), and ubus_process_pending_msg().
ubus_process_pending_msg()
static void ubus_process_pending_msg (struct uloop_timeout * timeout) static
Definition at line 120 of file libubus.c.
{
    struct ubus_context *ctx = container_of(timeout, struct ubus_context, pending_timer);
    struct ubus_pending_msg *pending;
    while (!list_empty(&ctx->pending)) {
        if (ctx->stack_depth)
            break;
        pending = list_first_entry(&ctx->pending, struct ubus_pending_msg, list);
        list_del(&pending->list);
        ubus_process_msg(ctx, &pending->hdr, -1);
        free(pending);
    }
}
References container_of, ctx, ubus_pending_msg::list, list_del(), list_empty(), list_first_entry, pending, ubus_context::pending, ubus_context::pending_timer, ubus_context::stack_depth, timeout, and ubus_process_msg().
Referenced by ubus_connect_ctx().
ubus_queue_msg()
static void ubus_queue_msg (struct ubus_context * ctx, struct ubus_msghdr_buf * buf) static
Definition at line 77 of file libubus.c.
{
    struct ubus_pending_msg *pending;
    void *data;
    pending = calloc_a(sizeof(*pending), &data, blob_raw_len(buf->data));
    pending->hdr.data = data;
    memcpy(&pending->hdr.hdr, &buf->hdr, sizeof(buf->hdr));
    memcpy(data, buf->data, blob_raw_len(buf->data));
    list_add_tail(&pending->list, &ctx->pending);
    if (ctx->sock.registered)
        uloop_timeout_set(&ctx->pending_timer, 1);
}
References blob_raw_len(), buf, calloc_a, ctx, list_add_tail(), pending, ubus_context::pending, ubus_context::pending_timer, uloop_fd::registered, ubus_context::sock, and uloop_timeout_set().
Referenced by ubus_process_msg().
ubus_register_event_handler()
int ubus_register_event_handler (struct ubus_context * ctx, struct ubus_event_handler * ev, const char * pattern)
Definition at line 225 of file libubus.c.
{
    struct ubus_object *obj = &ev->obj;
    struct blob_buf b2 = {};
    int ret;
    if (!obj->id) {
        obj->methods = &event_method;
        obj->n_methods = 1;
        if (!!obj->name ^ !!obj->type)
            return UBUS_STATUS_INVALID_ARGUMENT;
        ret = ubus_add_object(ctx, obj);
        if (ret)
            return ret;
    }
    /* use a second buffer, ubus_invoke() overwrites the primary one */
    blob_buf_init(&b2, 0);
    blobmsg_add_u32(&b2, "object", obj->id);
    if (pattern)
        blobmsg_add_string(&b2, "pattern", pattern);
    ret = ubus_invoke(ctx, UBUS_SYSTEM_OBJECT_EVENT, "register", b2.head,
              NULL, NULL, 0);
    blob_buf_free(&b2);
    return ret;
}
References blob_buf_free(), blob_buf_init(), blobmsg_add_string(), blobmsg_add_u32(), ctx, event_method, blob_buf::head, ubus_object::id, ubus_object::methods, ubus_object::n_methods, ubus_object::name, ubus_event_handler::obj, ubus_object::type, ubus_add_object(), ubus_invoke(), UBUS_STATUS_INVALID_ARGUMENT, and UBUS_SYSTEM_OBJECT_EVENT.
Referenced by extdev_ext_ubus_obj_wait(), ubus_cli_listen(), ubus_cli_wait_for(), ubus_lua_listen(), ubus_refresh_auto_subscribe(), ubus_register_acl(), ubus_register_subscriber(), and watch_ubus().
ubus_send_event()
int ubus_send_event (struct ubus_context * ctx, const char * id, struct blob_attr * data)
Definition at line 258 of file libubus.c.
{
    struct ubus_request req;
    void *s;
    blob_buf_init(&b, 0);
    blob_put_int32(&b, UBUS_ATTR_OBJID, UBUS_SYSTEM_OBJECT_EVENT);
    blob_put_string(&b, UBUS_ATTR_METHOD, "send");
    s = blob_nest_start(&b, UBUS_ATTR_DATA);
    blobmsg_add_string(&b, "id", id);
    blobmsg_add_field(&b, BLOBMSG_TYPE_TABLE, "data", blob_data(data), blob_len(data));
    blob_nest_end(&b, s);
    if (ubus_start_request(ctx, &req, b.head, UBUS_MSG_INVOKE, UBUS_SYSTEM_OBJECT_EVENT) < 0)
        return UBUS_STATUS_INVALID_ARGUMENT;
    return ubus_complete_request(ctx, &req, 0);
}
References b, blob_buf_init(), blob_data(), blob_len(), blob_nest_end(), blob_nest_start(), blob_put_int32, blob_put_string(), blobmsg_add_field(), blobmsg_add_string(), BLOBMSG_TYPE_TABLE, ctx, blob_buf::head, UBUS_ATTR_DATA, UBUS_ATTR_METHOD, UBUS_ATTR_OBJID, ubus_complete_request(), UBUS_MSG_INVOKE, ubus_start_request(), UBUS_STATUS_INVALID_ARGUMENT, and UBUS_SYSTEM_OBJECT_EVENT.
Referenced by netifd_ubus_interface_event(), ubus_cli_send(), and ubus_lua_send().
ubus_shutdown()
void ubus_shutdown (struct ubus_context * ctx)
Definition at line 367 of file libubus.c.
{
    blob_buf_free(&b);
    if (!ctx)
        return;
    uloop_fd_delete(&ctx->sock);
    close(ctx->sock.fd);
    uloop_timeout_cancel(&ctx->pending_timer);
    free(ctx->msgbuf.data);
}
References b, blob_buf_free(), ctx, ubus_msghdr_buf::data, uloop_fd::fd, ubus_context::msgbuf, ubus_context::pending_timer, ubus_context::sock, uloop_fd_delete(), and uloop_timeout_cancel().
Referenced by ubus_auto_shutdown(), and ubus_free().
ubus_strerror()
const char * ubus_strerror (int error)
Definition at line 59 of file libubus.c.
{
    static char err[32];
    if (error < 0 || error >= __UBUS_STATUS_LAST)
        goto out;
    if (!__ubus_strerror[error])
        goto out;
    return __ubus_strerror[error];
out:
    sprintf(err, "Unknown error: %d", error);
    return err;
}
References __UBUS_STATUS_LAST, __ubus_strerror, and err.
Referenced by __bridge_config_init(), __do_bridge_reload(), client_main(), extdev_bridge_member_cb(), extdev_invocation_error(), extdev_lookup_id(), main(), netifd_add_object(), procd_bcast_event(), rpc_ucode_script_register(), server_main(), test_client_notify_cb(), test_watch(), ubus_cli_error(), ubus_cli_listen(), ubus_cli_subscribe(), and ubus_init_system().
Variable Documentation
__hidden
struct blob_buf b __hidden = {}
Definition at line 42 of file libubus.c.
{};
__ubus_strerror
const char* __ubus_strerror[__UBUS_STATUS_LAST]
Initial value:
= {
    [UBUS_STATUS_OK] = "Success",
    [UBUS_STATUS_INVALID_COMMAND] = "Invalid command",
    [UBUS_STATUS_INVALID_ARGUMENT] = "Invalid argument",
    [UBUS_STATUS_METHOD_NOT_FOUND] = "Method not found",
    [UBUS_STATUS_NOT_FOUND] = "Not found",
    [UBUS_STATUS_NO_DATA] = "No response",
    [UBUS_STATUS_PERMISSION_DENIED] = "Permission denied",
    [UBUS_STATUS_TIMEOUT] = "Request timed out",
    [UBUS_STATUS_NOT_SUPPORTED] = "Operation not supported",
    [UBUS_STATUS_UNKNOWN_ERROR] = "Unknown error",
    [UBUS_STATUS_CONNECTION_FAILED] = "Connection failed",
    [UBUS_STATUS_NO_MEMORY] = "Out of memory",
    [UBUS_STATUS_PARSE_ERROR] = "Parsing message data failed",
    [UBUS_STATUS_SYSTEM_ERROR] = "System error",
}
Definition at line 25 of file libubus.c.
{
    [UBUS_STATUS_OK] = "Success",
    [UBUS_STATUS_INVALID_COMMAND] = "Invalid command",
    [UBUS_STATUS_INVALID_ARGUMENT] = "Invalid argument",
    [UBUS_STATUS_METHOD_NOT_FOUND] = "Method not found",
    [UBUS_STATUS_NOT_FOUND] = "Not found",
    [UBUS_STATUS_NO_DATA] = "No response",
    [UBUS_STATUS_PERMISSION_DENIED] = "Permission denied",
    [UBUS_STATUS_TIMEOUT] = "Request timed out",
    [UBUS_STATUS_NOT_SUPPORTED] = "Operation not supported",
    [UBUS_STATUS_UNKNOWN_ERROR] = "Unknown error",
    [UBUS_STATUS_CONNECTION_FAILED] = "Connection failed",
    [UBUS_STATUS_NO_MEMORY] = "Out of memory",
    [UBUS_STATUS_PARSE_ERROR] = "Parsing message data failed",
    [UBUS_STATUS_SYSTEM_ERROR] = "System error",
};
Referenced by ubus_strerror().
event_method
const struct ubus_method event_method static
Initial value:
= {
    .name = NULL,
    .handler = ubus_event_cb,
}
Definition at line 220 of file libubus.c.
{
    .name = NULL,
    .handler = ubus_event_cb,
};
Referenced by ubus_register_event_handler().