zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/ustp/worker.h File Reference
worker.h File Reference
#include "mstp.h"
Classes
struct worker_event
Enumerations
enum worker_event_type {
WORKER_EV_SHUTDOWN , WORKER_EV_RECV_PACKET , WORKER_EV_BRIDGE_EVENT , WORKER_EV_BRIDGE_ADD ,
WORKER_EV_BRIDGE_REMOVE , WORKER_EV_ONE_SECOND
}
Functions
int worker_init (void)
void worker_cleanup (void)
void worker_queue_event (struct worker_event *ev)
Class Documentation
worker_event
struct worker_event
Definition at line 28 of file worker.h.
Class Members
CIST_BridgeConfig bridge_config
int bridge_idx
enum worker_event_type type
Enumeration Type Documentation
worker_event_type
enum worker_event_type
Enumerator
WORKER_EV_SHUTDOWN
WORKER_EV_RECV_PACKET
WORKER_EV_BRIDGE_EVENT
WORKER_EV_BRIDGE_ADD
WORKER_EV_BRIDGE_REMOVE
WORKER_EV_ONE_SECOND
Definition at line 19 of file worker.h.
                       {
    WORKER_EV_SHUTDOWN,
    WORKER_EV_RECV_PACKET,
    WORKER_EV_BRIDGE_EVENT,
    WORKER_EV_BRIDGE_ADD,
    WORKER_EV_BRIDGE_REMOVE,
    WORKER_EV_ONE_SECOND,
};
Function Documentation
worker_cleanup()
void worker_cleanup (void)
Definition at line 113 of file worker.c.
{
    struct worker_event ev = {
        .type = WORKER_EV_SHUTDOWN,
    };
    worker_queue_event(&ev);
    pthread_join(w_thread, NULL);
}
References w_thread, WORKER_EV_SHUTDOWN, and worker_queue_event().
Referenced by main().
worker_init()
int worker_init (void)
Definition at line 105 of file worker.c.
{
    w_timer.cb = worker_timer_cb;
    uloop_timeout_set(&w_timer, 1000);
    return pthread_create(&w_thread, NULL, worker_thread_fn, NULL);
}
References uloop_timeout::cb, uloop_timeout_set(), w_thread, w_timer, worker_thread_fn(), and worker_timer_cb().
Referenced by main().
worker_queue_event()
void worker_queue_event (struct worker_event * ev)
Definition at line 123 of file worker.c.
{
    struct worker_queued_event *evc;
    evc = malloc(sizeof(*evc));
    memcpy(&evc->ev, ev, sizeof(*ev));
    pthread_mutex_lock(&w_lock);
    list_add_tail(&evc->list, &w_queue);
    pthread_mutex_unlock(&w_lock);
    pthread_cond_signal(&w_cond);
}
References worker_queued_event::ev, worker_queued_event::list, list_add_tail(), w_cond, and w_lock.
Referenced by bridge_event_cb(), packet_event(), ubus_bridge_state(), worker_cleanup(), and worker_timer_cb().