zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/service/trigger.c File Reference
trigger.c File Reference
#include <sys/stat.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <libubox/blobmsg_json.h>
#include <libubox/json_script.h>
#include <libubox/runqueue.h>
#include <libubox/ustream.h>
#include <libubox/uloop.h>
#include <libubox/avl.h>
#include <libubox/avl-cmp.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdlib.h>
#include <libgen.h>
#include "../procd.h"
Classes
struct trigger
struct trigger_command
Functions
static LIST_HEAD (triggers)
static RUNQUEUE (q, 1)
static AVL_TREE (trigger_pending, avl_blobcmp, false, NULL)
static const char * rule_handle_var (struct json_script_ctx *ctx, const char *name, struct blob_attr *vars)
static struct json_script_file * rule_load_script (struct json_script_ctx *ctx, const char *name)
static void trigger_free (struct trigger *t)
static void trigger_command_complete (struct runqueue *q, struct runqueue_task *p)
static void trigger_command_run (struct runqueue *q, struct runqueue_task *t)
static void trigger_command_start (struct uloop_timeout *timeout)
static void trigger_command_add (struct trigger *t, struct blob_attr *data)
static void rule_handle_command (struct json_script_ctx *ctx, const char *name, struct blob_attr *exec, struct blob_attr *vars)
static void rule_handle_error (struct json_script_ctx *ctx, const char *msg, struct blob_attr *context)
static struct trigger * _trigger_add (char *type, struct blob_attr *rule, int timeout, void *id)
void trigger_add (struct blob_attr *rule, void *id)
void trigger_del (void *id)
static bool trigger_match (const char *event, const char *match)
void trigger_event (const char *type, struct blob_attr *data)
Class Documentation
trigger
struct trigger
Definition at line 34 of file trigger.c.
Class Members
struct blob_attr * data
void * id
struct json_script_ctx jctx
struct list_head list
struct blob_attr * rule
int timeout
char * type
trigger_command
struct trigger_command
Definition at line 47 of file trigger.c.
Class Members
struct avl_node avl
struct blob_attr data[]
struct uloop_timeout delay
struct json_script_ctx jctx
struct runqueue_process proc
bool requeue
Function Documentation
_trigger_add()
static struct trigger * _trigger_add (char * type, struct blob_attr * rule, int timeout, void * id) static
Definition at line 211 of file trigger.c.
{
    char *_t;
    struct blob_attr *_r;
    struct trigger *t = calloc_a(sizeof(*t), &_t, strlen(type) + 1, &_r, blob_pad_len(rule));
    t->type = _t;
    t->rule = _r;
    t->timeout = timeout;
    t->id = id;
    t->jctx.handle_var = rule_handle_var,
    t->jctx.handle_error = rule_handle_error,
    t->jctx.handle_command = rule_handle_command,
    t->jctx.handle_file = rule_load_script,
    strcpy(t->type, type);
    memcpy(t->rule, rule, blob_pad_len(rule));
    list_add(&t->list, &triggers);
    json_script_init(&t->jctx);
    return t;
}
References blob_pad_len(), calloc_a, json_script_ctx::handle_command, json_script_ctx::handle_error, json_script_ctx::handle_file, json_script_ctx::handle_var, id, trigger::id, trigger::jctx, json_script_init(), trigger::list, list_add(), trigger::rule, rule_handle_command(), rule_handle_error(), rule_handle_var(), rule_load_script(), timeout, trigger::timeout, trigger::type, and type.
Referenced by trigger_add().
AVL_TREE()
static AVL_TREE (trigger_pending , avl_blobcmp , false , NULL) static
LIST_HEAD()
static LIST_HEAD (triggers) static
rule_handle_command()
static void rule_handle_command (struct json_script_ctx * ctx, const char * name, struct blob_attr * exec, struct blob_attr * vars) static
Definition at line 190 of file trigger.c.
{
    struct trigger *t = container_of(ctx, struct trigger, jctx);
    if (!strcmp(name, "run_script")) {
        trigger_command_add(t, exec);
        return;
    }
}
References container_of, ctx, jctx, and trigger_command_add().
Referenced by _trigger_add().
rule_handle_error()
static void rule_handle_error (struct json_script_ctx * ctx, const char * msg, struct blob_attr * context) static
Definition at line 201 of file trigger.c.
{
    char *s;
    s = blobmsg_format_json(context, false);
    ERROR("ERROR: %s in block: %s\n", msg, s);
    free(s);
}
References blobmsg_format_json(), and ERROR.
Referenced by _trigger_add().
rule_handle_var()
static const char * rule_handle_var (struct json_script_ctx * ctx, const char * name, struct blob_attr * vars) static
Definition at line 62 of file trigger.c.
{
    return NULL;
}
Referenced by _trigger_add().
rule_load_script()
static struct json_script_file * rule_load_script (struct json_script_ctx * ctx, const char * name) static
Definition at line 68 of file trigger.c.
{
    struct trigger *t = container_of(ctx, struct trigger, jctx);
    if (strcmp(name, t->type) != 0)
        return NULL;
    return json_script_file_from_blobmsg(t->type, t->rule, blob_pad_len(t->rule));
}
References blob_pad_len(), container_of, ctx, jctx, json_script_file_from_blobmsg(), trigger::rule, and trigger::type.
Referenced by _trigger_add().
RUNQUEUE()
static RUNQUEUE (q , 1) static
trigger_add()
void trigger_add (struct blob_attr * rule, void * id)
Definition at line 235 of file trigger.c.
{
    struct blob_attr *cur;
    int rem;
    blobmsg_for_each_attr(cur, rule, rem) {
        struct blob_attr *_cur, *type = NULL, *script = NULL, *timeout = NULL;
        int _rem;
        int i = 0;
        if (blobmsg_type(cur) != BLOBMSG_TYPE_ARRAY)
            continue;
        blobmsg_for_each_attr(_cur, cur, _rem) {
            switch (i++) {
            case 0:
                if (blobmsg_type(_cur) == BLOBMSG_TYPE_STRING)
                    type = _cur;
                break;
            case 1:
                if (blobmsg_type(_cur) == BLOBMSG_TYPE_ARRAY)
                    script = _cur;
                break;
            case 2:
                if (blobmsg_type(_cur) == BLOBMSG_TYPE_INT32)
                    timeout = _cur;
                break;
            }
        }
        if (type && script) {
            int t = 0;
            if (timeout)
                t = blobmsg_get_u32(timeout);
            _trigger_add(blobmsg_get_string(type), script, t, id);
        }
    }
}
References _trigger_add(), blobmsg_for_each_attr, blobmsg_get_string(), blobmsg_get_u32(), BLOBMSG_TYPE_ARRAY, BLOBMSG_TYPE_INT32, BLOBMSG_TYPE_STRING, script, timeout, and type.
Referenced by instance_config_parse(), and service_update().
trigger_command_add()
static void trigger_command_add (struct trigger * t, struct blob_attr * data) static
Definition at line 158 of file trigger.c.
{
    struct trigger_command *cmd;
    int64_t remaining;
    cmd = avl_find_element(&trigger_pending, data, cmd, avl);
    if (cmd) {
        /* Command currently running? */
        if (!cmd->delay.pending) {
            cmd->requeue = true;
            return;
        }
        /* Extend timer if trigger timeout is bigger than remaining time */
        remaining = uloop_timeout_remaining64(&cmd->delay);
        if (remaining < t->timeout)
            uloop_timeout_set(&cmd->delay, t->timeout);
        return;
    }
    cmd = calloc(1, sizeof(*cmd) + blob_pad_len(data));
    if (!cmd)
        return;
    cmd->avl.key = cmd->data;
    cmd->delay.cb = trigger_command_start;
    memcpy(cmd->data, data, blob_pad_len(data));
    avl_insert(&trigger_pending, &cmd->avl);
    uloop_timeout_set(&cmd->delay, t->timeout > 0 ? t->timeout : 1);
}
References trigger_command::avl, avl_find_element, avl_insert(), blob_pad_len(), json_handler::cb, cmd, trigger_command::data, timeout, trigger::timeout, trigger_command_start(), uloop_timeout_remaining64(), and uloop_timeout_set().
Referenced by rule_handle_command().
trigger_command_complete()
static void trigger_command_complete (struct runqueue * q, struct runqueue_task * p) static
Definition at line 86 of file trigger.c.
{
    struct trigger_command *cmd = container_of(p, struct trigger_command, proc.task);
    if (cmd->requeue) {
        cmd->requeue = false;
        runqueue_task_add(q, p, false);
        return;
    }
    avl_delete(&trigger_pending, &cmd->avl);
    free(cmd);
}
References avl_delete(), cmd, container_of, trigger_command::proc, q, runqueue_task_add(), and runqueue_process::task.
Referenced by trigger_command_run(), and trigger_command_start().
trigger_command_run()
static void trigger_command_run (struct runqueue * q, struct runqueue_task * t) static
Definition at line 100 of file trigger.c.
{
    struct trigger_command *cmd = container_of(t, struct trigger_command, proc.task);
    struct blob_attr *cur;
    char **argv;
    pid_t pid;
    int n = 0;
    int rem;
    int fd;
    pid = fork();
    if (pid < 0) {
        trigger_command_complete(q, t);
        return;
    }
    if (pid) {
        runqueue_process_add(q, &cmd->proc, pid);
        return;
    }
    if (debug < 3 && (fd = open("/dev/null", O_RDWR)) >= 0) {
        dup2(fd, STDIN_FILENO);
        dup2(fd, STDOUT_FILENO);
        dup2(fd, STDERR_FILENO);
        if (fd > STDERR_FILENO)
            close(fd);
    }
    blobmsg_for_each_attr(cur, cmd->data, rem)
        n++;
    argv = alloca((n + 1) * sizeof(*argv));
    n = 0;
    blobmsg_for_each_attr(cur, cmd->data, rem)
        argv[n++] = blobmsg_get_string(cur);
    argv[n] = NULL;
    if (n > 0)
        execvp(argv[0], &argv[0]);
    exit(1);
}
References blobmsg_for_each_attr, blobmsg_get_string(), cmd, container_of, debug, trigger_command::proc, q, runqueue_process_add(), runqueue_process::task, and trigger_command_complete().
Referenced by trigger_command_start().
trigger_command_start()
static void trigger_command_start (struct uloop_timeout * timeout) static
Definition at line 144 of file trigger.c.
{
    static const struct runqueue_task_type trigger_command_type = {
        .run = trigger_command_run,
        .cancel = runqueue_process_cancel_cb,
        .kill = runqueue_process_kill_cb,
    };
    struct trigger_command *cmd = container_of(timeout, struct trigger_command, delay);
    cmd->proc.task.type = &trigger_command_type;
    cmd->proc.task.complete = trigger_command_complete;
    runqueue_task_add(&q, &cmd->proc.task, false);
}
References cmd, container_of, trigger_command::delay, q, runqueue_process_cancel_cb(), runqueue_process_kill_cb(), runqueue_task_add(), timeout, trigger_command_complete(), and trigger_command_run().
Referenced by trigger_command_add().
trigger_del()
void trigger_del (void * id)
Definition at line 277 of file trigger.c.
{
    struct trigger *t, *n;
    list_for_each_entry_safe(t, n, &triggers, list) {
        if (t->id != id)
            continue;
        trigger_free(t);
    }
}
References trigger::id, trigger::list, list_for_each_entry_safe, and trigger_free().
Referenced by instance_free(), service_stopped(), and service_update().
trigger_event()
void trigger_event (const char * type, struct blob_attr * data)
Definition at line 297 of file trigger.c.
{
    struct trigger *t;
    list_for_each_entry(t, &triggers, list) {
        if (!trigger_match(type, t->type))
            continue;
        json_script_run(&t->jctx, t->type, data);
    }
}
References trigger::data, trigger::jctx, json_script_run(), trigger::list, list_for_each_entry, trigger_match(), trigger::type, and type.
Referenced by service_handle_event(), service_instance_update(), and watch_notify_cb().
trigger_free()
static void trigger_free (struct trigger * t) static
Definition at line 78 of file trigger.c.
{
    json_script_free(&t->jctx);
    free(t->data);
    list_del(&t->list);
    free(t);
}
References trigger::data, trigger::jctx, json_script_free(), trigger::list, and list_del().
Referenced by trigger_del().
trigger_match()
static bool trigger_match (const char * event, const char * match) static
Definition at line 289 of file trigger.c.
{
    char *wildcard = strstr(match, ".*");
    if (wildcard)
        return !strncmp(event, match, wildcard - match);
    return !strcmp(event, match);
}
Referenced by trigger_event().