zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/netifd/ubus.h File Reference
ubus.h File Reference
Typedefs
typedef void(* procd_data_cb) (struct blob_attr *data)
Functions
int netifd_ubus_init (const char *path)
void netifd_ubus_done (void)
int netifd_extdev_invoke (uint32_t id, const char *method, struct blob_attr *msg, ubus_data_handler_t data_cb, void *data)
void netifd_ubus_add_interface (struct interface *iface)
void netifd_ubus_remove_interface (struct interface *iface)
void netifd_ubus_interface_event (struct interface *iface, bool up)
void netifd_ubus_interface_notify (struct interface *iface, bool up)
void netifd_ubus_device_notify (const char *event, struct blob_attr *data, int timeout)
void netifd_ubus_get_procd_data (const char *type, procd_data_cb cb)
Variables
struct ubus_context * ubus_ctx
Typedef Documentation
procd_data_cb
typedef void(* procd_data_cb) (struct blob_attr *data)
Definition at line 17 of file ubus.h.
Function Documentation
netifd_extdev_invoke()
int netifd_extdev_invoke (uint32_t id, const char * method, struct blob_attr * msg, ubus_data_handler_t data_cb, void * data)
Definition at line 1363 of file ubus.c.
{
    return ubus_invoke(ubus_ctx, id, method, msg, data_cb, data, 3000);
}
References ubus_ctx, and ubus_invoke().
Referenced by extdev_dump(), netifd_extdev_add(), netifd_extdev_create(), netifd_extdev_free(), netifd_extdev_prepare(), netifd_extdev_reload(), and netifd_extdev_remove().
netifd_ubus_add_interface()
void netifd_ubus_add_interface (struct interface * iface)
Definition at line 1420 of file ubus.c.
{
    struct ubus_object *obj = &iface->ubus;
    char *name = NULL;
    if (asprintf(&name, "%s.interface.%s", main_object.name, iface->name) == -1)
        return;
    obj->name = name;
    obj->type = &iface_object_type;
    obj->methods = iface_object_methods;
    obj->n_methods = ARRAY_SIZE(iface_object_methods);
    if (ubus_add_object(ubus_ctx, &iface->ubus)) {
        D(SYSTEM, "failed to publish ubus object for interface '%s'", iface->name);
        free(name);
        obj->name = NULL;
    }
}
References ARRAY_SIZE, D, iface_object_methods, iface_object_type, main_object, ubus_object::methods, ubus_object::n_methods, interface::name, ubus_object::name, ubus_object::type, interface::ubus, ubus_add_object(), and ubus_ctx.
Referenced by interface_update().
netifd_ubus_device_notify()
void netifd_ubus_device_notify (const char * event, struct blob_attr * data, int timeout)
Definition at line 424 of file ubus.c.
{
    ubus_notify(ubus_ctx, &dev_object, event, data, timeout);
}
References dev_object, timeout, ubus_ctx, and ubus_notify().
Referenced by __device_broadcast_event(), and bridge_stp_notify().
netifd_ubus_done()
void netifd_ubus_done (void)
Definition at line 1393 of file ubus.c.
{
    udebug_ubus_free(&udebug);
    ubus_free(ubus_ctx);
}
References ubus_ctx, and ubus_free().
Referenced by main().
netifd_ubus_get_procd_data()
void netifd_ubus_get_procd_data (const char * type, procd_data_cb cb)
Definition at line 1479 of file ubus.c.
{
    uint32_t id;
    if (ubus_lookup_id(ubus_ctx, "service", &id))
        return;
    blob_buf_init(&b, 0);
    blobmsg_add_string(&b, "type", type);
    ubus_invoke(ubus_ctx, id, "get_data", b.head, netifd_ubus_data_cb, cb, 30000);
}
References b, blob_buf_init(), blobmsg_add_string(), blob_buf::head, id, netifd_ubus_data_cb(), type, ubus_ctx, ubus_invoke(), and ubus_lookup_id().
Referenced by config_init_wireless().
netifd_ubus_init()
int netifd_ubus_init (const char * path)
Definition at line 1370 of file ubus.c.
{
    ubus_path = path;
    ubus_ctx = ubus_connect(path);
    if (!ubus_ctx)
        return -EIO;
    D(SYSTEM, "connected as %08x", ubus_ctx->local_id);
    ubus_ctx->connection_lost = netifd_ubus_connection_lost;
    netifd_ubus_add_fd();
    netifd_add_object(&main_object);
    netifd_add_object(&dev_object);
    netifd_add_object(&wireless_object);
    netifd_add_iface_object();
    udebug_ubus_init(&udebug, ubus_ctx, "netifd", netifd_udebug_config);
    return 0;
}
References ubus_context::connection_lost, D, dev_object, ubus_context::local_id, main_object, netifd_add_iface_object(), netifd_add_object(), netifd_ubus_add_fd(), netifd_ubus_connection_lost(), netifd_udebug_config(), path, ubus_connect(), ubus_ctx, and wireless_object.
Referenced by main().
netifd_ubus_interface_event()
void netifd_ubus_interface_event (struct interface * iface, bool up)
Definition at line 1400 of file ubus.c.
{
    blob_buf_init(&b, 0);
    blobmsg_add_string(&b, "action", up ? "ifup" : "ifdown");
    blobmsg_add_string(&b, "interface", iface->name);
    ubus_send_event(ubus_ctx, "network.interface", b.head);
}
References b, blob_buf_init(), blobmsg_add_string(), blob_buf::head, interface::name, ubus_ctx, and ubus_send_event().
Referenced by interface_queue_event().
netifd_ubus_interface_notify()
void netifd_ubus_interface_notify (struct interface * iface, bool up)
Definition at line 1409 of file ubus.c.
{
    const char *event = (up) ? "interface.update" : "interface.down";
    blob_buf_init(&b, 0);
    blobmsg_add_string(&b, "interface", iface->name);
    netifd_dump_status(iface);
    ubus_notify(ubus_ctx, &iface_object, event, b.head, -1);
    ubus_notify(ubus_ctx, &iface->ubus, event, b.head, -1);
}
References b, blob_buf_init(), blobmsg_add_string(), blob_buf::head, iface_object, interface::name, netifd_dump_status(), interface::ubus, ubus_ctx, and ubus_notify().
Referenced by interface_queue_event().
netifd_ubus_remove_interface()
void netifd_ubus_remove_interface (struct interface * iface)
Definition at line 1440 of file ubus.c.
{
    if (!iface->ubus.name)
        return;
    ubus_remove_object(ubus_ctx, &iface->ubus);
    free((void *) iface->ubus.name);
}
References ubus_object::name, interface::ubus, ubus_ctx, and ubus_remove_object().
Referenced by interface_do_free().
Variable Documentation
ubus_ctx
struct ubus_context* ubus_ctx extern
Definition at line 27 of file ubus.c.
Referenced by extdev_add_devtype(), extdev_ext_ubus_obj_wait(), extdev_lookup_id(), extdev_subscribe(), netifd_add_object(), netifd_extdev_invoke(), netifd_ubus_add_fd(), netifd_ubus_add_interface(), netifd_ubus_device_notify(), netifd_ubus_done(), netifd_ubus_get_procd_data(), netifd_ubus_init(), netifd_ubus_interface_event(), netifd_ubus_interface_notify(), netifd_ubus_reconnect_timer(), netifd_ubus_remove_interface(), wireless_complete_kill_request(), and wireless_device_process_kill_all().