zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/netifd/system-dummy.c File Reference
system-dummy.c File Reference
#include <sys/time.h>
#include <stdio.h>
#include <string.h>
#include <arpa/inet.h>
#include "netifd.h"
#include "device.h"
#include "system.h"
Macros
#define DEBUG
Functions
int system_init (void)
int system_bridge_addbr (struct device *bridge, struct bridge_config *cfg)
int system_bridge_delbr (struct device *bridge)
int system_bridge_addif (struct device *bridge, struct device *dev)
int system_bridge_delif (struct device *bridge, struct device *dev)
int system_bridge_vlan (const char *iface, uint16_t vid, int16_t vid_end, bool add, unsigned int vflags)
void system_bridge_set_stp_state (struct device *dev, bool val)
int system_bridge_vlan_check (struct device *dev, char *ifname)
int system_bonding_set_device (struct device *dev, struct bonding_config *cfg)
int system_bonding_set_port (struct device *dev, struct device *port, bool add, bool primary)
int system_link_netns_move (struct device *dev, int netns_fd, const char *target_ifname)
int system_netns_open (const pid_t target_ns)
int system_netns_set (int netns_fd)
int system_vlan_add (struct device *dev, int id)
int system_vlan_del (struct device *dev)
bool system_if_force_external (const char *ifname)
int system_if_up (struct device *dev)
int system_if_down (struct device *dev)
void system_if_get_settings (struct device *dev, struct device_settings *s)
void system_if_clear_state (struct device *dev)
int system_if_check (struct device *dev)
int system_if_resolve (struct device *dev)
struct device * system_if_get_parent (struct device *dev)
int system_if_dump_info (struct device *dev, struct blob_buf *b)
int system_if_dump_stats (struct device *dev, struct blob_buf *b)
void system_if_apply_settings (struct device *dev, struct device_settings *s, uint64_t apply_mask)
static int system_address_msg (struct device *dev, struct device_addr *addr, const char *type)
int system_add_address (struct device *dev, struct device_addr *addr)
int system_del_address (struct device *dev, struct device_addr *addr)
static int system_route_msg (struct device *dev, struct device_route *route, const char *type)
static int system_neighbor_msg (struct device *dev, struct device_neighbor *neighbor, const char *type)
int system_add_neighbor (struct device *dev, struct device_neighbor *neighbor)
int system_del_neighbor (struct device *dev, struct device_neighbor *neighbor)
int system_add_route (struct device *dev, struct device_route *route)
int system_del_route (struct device *dev, struct device_route *route)
int system_flush_routes (void)
bool system_resolve_rt_type (const char *type, unsigned int *id)
bool system_resolve_rt_proto (const char *type, unsigned int *id)
bool system_resolve_rt_table (const char *name, unsigned int *id)
bool system_is_default_rt_table (unsigned int id)
bool system_resolve_rpfilter (const char *filter, unsigned int *id)
int system_add_iprule (struct iprule *rule)
int system_del_iprule (struct iprule *rule)
int system_flush_iprules (void)
bool system_resolve_iprule_action (const char *action, unsigned int *id)
time_t system_get_rtime (void)
int system_del_ip_tunnel (const struct device *dev)
int system_add_ip_tunnel (const struct device *dev, struct blob_attr *attr)
int system_update_ipv6_mtu (struct device *dev, int mtu)
int system_macvlan_add (struct device *macvlan, struct device *dev, struct macvlan_config *cfg)
int system_macvlan_del (struct device *macvlan)
int system_veth_add (struct device *veth, struct veth_config *cfg)
int system_veth_del (struct device *veth)
int system_vlandev_add (struct device *vlandev, struct device *dev, struct vlandev_config *cfg)
int system_vlandev_del (struct device *vlandev)
Macro Definition Documentation
DEBUG
#define DEBUG
Definition at line 21 of file system-dummy.c.
Referenced by _add_mount(), _rc(), alloc_library(), alloc_library_path(), apply_rlimits(), apply_sysctl(), applyOCIcapabilities(), askconsole(), askfirst(), cgroups_apply(), cgroups_set(), child_exit(), create_dev_console(), create_devices(), do_mount(), elf_load_deps(), fork_worker(), hook_process_handler(), hook_process_timeout_cb(), install_syscall_filter(), jail_handle_signal(), jail_process_timeout_cb(), load_ldso_conf(), main(), make_dev(), mount_overlay(), parseOCIdevices(), parseOCIhook(), parseOCIlinuxns(), parseOCIlinuxseccomp(), parseOCImountopts(), parseOCIprocessuser(), post_poststart(), preinit(), procd_inittab(), procd_shutdown(), procd_state_next(), q_initd_complete(), q_initd_run(), run_hooklist(), signal_shutdown(), spawn_procd(), ubus_connect_cb(), watchdog_frequency(), watchdog_init(), watchdog_open(), watchdog_ping(), watchdog_print_status(), and watchdog_timeout().
Function Documentation
system_add_address()
int system_add_address (struct device * dev, struct device_addr * addr)
Definition at line 201 of file system-dummy.c.
{
    return system_address_msg(dev, addr, "add");
}
References system_address_msg().
Referenced by interface_ip_set_enabled(), interface_set_prefix_address(), and interface_update_proto_addr().
system_add_ip_tunnel()
int system_add_ip_tunnel (const struct device * dev, struct blob_attr * attr)
Definition at line 343 of file system-dummy.c.
{
    return 0;
}
Referenced by tunnel_set_state().
system_add_iprule()
int system_add_iprule (struct iprule * rule)
Definition at line 307 of file system-dummy.c.
{
    return 0;
}
Referenced by iprule_update_rule(), rule_in_cb(), rule_out_cb(), set_ip_lo_policy(), and set_ip_source_policy().
system_add_neighbor()
int system_add_neighbor (struct device * dev, struct device_neighbor * neighbor)
Definition at line 253 of file system-dummy.c.
{
    return system_neighbor_msg(dev, neighbor, "add");
}
References system_neighbor_msg().
Referenced by interface_ip_set_enabled(), and interface_update_proto_neighbor().
system_add_route()
int system_add_route (struct device * dev, struct device_route * route)
Definition at line 263 of file system-dummy.c.
{
    return system_route_msg(dev, route, "add");
}
References system_route_msg().
Referenced by __interface_update_route(), interface_handle_subnet_route(), interface_ip_set_enabled(), interface_ip_set_route_enabled(), interface_set_prefix_address(), interface_update_prefix(), and interface_update_proto_addr().
system_address_msg()
static int system_address_msg (struct device * dev, struct device_addr * addr, const char * type) static
Definition at line 189 of file system-dummy.c.
{
    char ipaddr[64];
    int af = system_get_addr_family(addr->flags);
    D(SYSTEM, "ifconfig %s %s %s/%u",
        dev->ifname, type, inet_ntop(af, &addr->addr.in, ipaddr, sizeof(ipaddr)),
        addr->mask);
    return 0;
}
References device_addr::addr, D, device_addr::flags, device::ifname, if_addr::in, device_addr::mask, system_get_addr_family(), and type.
Referenced by system_add_address(), and system_del_address().
system_bonding_set_device()
int system_bonding_set_device (struct device * dev, struct bonding_config * cfg)
Definition at line 78 of file system-dummy.c.
{
    return 0;
}
Referenced by bonding_set_active().
system_bonding_set_port()
int system_bonding_set_port (struct device * dev, struct device * port, bool add, bool primary)
Definition at line 83 of file system-dummy.c.
{
    return 0;
}
Referenced by bonding_disable_port(), and bonding_enable_port().
system_bridge_addbr()
int system_bridge_addbr (struct device * bridge, struct bridge_config * cfg)
Definition at line 33 of file system-dummy.c.
{
    D(SYSTEM, "brctl addbr %s vlan_filtering=%d",
      bridge->ifname, cfg->vlan_filtering);
    return 0;
}
References D, device::ifname, and bridge_config::vlan_filtering.
Referenced by bridge_enable_interface().
system_bridge_addif()
int system_bridge_addif (struct device * bridge, struct device * dev)
Definition at line 46 of file system-dummy.c.
{
    D(SYSTEM, "brctl addif %s %s", bridge->ifname, dev->ifname);
    return 0;
}
References D, and device::ifname.
Referenced by bridge_enable_member().
system_bridge_delbr()
int system_bridge_delbr (struct device * bridge)
Definition at line 40 of file system-dummy.c.
{
    D(SYSTEM, "brctl delbr %s", bridge->ifname);
    return 0;
}
References D, and device::ifname.
Referenced by bridge_disable_interface().
system_bridge_delif()
int system_bridge_delif (struct device * bridge, struct device * dev)
Definition at line 52 of file system-dummy.c.
{
    D(SYSTEM, "brctl delif %s %s", bridge->ifname, dev->ifname);
    return 0;
}
References D, and device::ifname.
Referenced by bridge_disable_member().
system_bridge_set_stp_state()
void system_bridge_set_stp_state (struct device * dev, bool val)
Definition at line 69 of file system-dummy.c.
{
}
Referenced by bridge_stp_init().
system_bridge_vlan()
int system_bridge_vlan (const char * iface, uint16_t vid, int16_t vid_end, bool add, unsigned int vflags)
Definition at line 58 of file system-dummy.c.
{
    D(SYSTEM, "brctl vlan %s %s %s vid=%d vid_end=%d pvid=%d untag=%d",
      add ? "add" : "remove",
      (vflags & BRVLAN_F_SELF) ? "self" : "master",
      iface, vid, vid_end,
      !!(vflags & BRVLAN_F_PVID),
      !!(vflags & BRVLAN_F_UNTAGGED));
    return 0;
}
References BRVLAN_F_PVID, BRVLAN_F_SELF, BRVLAN_F_UNTAGGED, and D.
Referenced by __bridge_set_member_vlan(), bridge_enable_interface(), bridge_enable_member(), bridge_hotplug_set_member_vlans(), bridge_member_add_extra_vlans(), and bridge_set_local_vlan().
system_bridge_vlan_check()
int system_bridge_vlan_check (struct device * dev, char * ifname)
Definition at line 73 of file system-dummy.c.
{
    return 0;
}
Referenced by bridge_member_check_cb().
system_del_address()
int system_del_address (struct device * dev, struct device_addr * addr)
Definition at line 206 of file system-dummy.c.
{
    return system_address_msg(dev, addr, "del");
}
References system_address_msg().
Referenced by interface_ip_set_enabled(), interface_set_prefix_address(), and interface_update_proto_addr().
system_del_ip_tunnel()
int system_del_ip_tunnel (const struct device * dev)
Definition at line 338 of file system-dummy.c.
{
    return 0;
}
Referenced by tunnel_set_state().
system_del_iprule()
int system_del_iprule (struct iprule * rule)
Definition at line 312 of file system-dummy.c.
{
    return 0;
}
Referenced by iprule_update_rule(), rule_in_cb(), rule_out_cb(), set_ip_lo_policy(), and set_ip_source_policy().
system_del_neighbor()
int system_del_neighbor (struct device * dev, struct device_neighbor * neighbor)
Definition at line 258 of file system-dummy.c.
{
    return system_neighbor_msg(dev, neighbor, "del");
}
References system_neighbor_msg().
Referenced by interface_ip_set_enabled(), and interface_update_proto_neighbor().
system_del_route()
int system_del_route (struct device * dev, struct device_route * route)
Definition at line 268 of file system-dummy.c.
{
    return system_route_msg(dev, route, "del");
}
References system_route_msg().
Referenced by __interface_update_route(), interface_handle_subnet_route(), interface_ip_set_enabled(), interface_ip_set_route_enabled(), interface_set_prefix_address(), interface_update_prefix(), and interface_update_proto_addr().
system_flush_iprules()
int system_flush_iprules (void)
Definition at line 317 of file system-dummy.c.
{
    return 0;
}
Referenced by iprule_update_start().
system_flush_routes()
int system_flush_routes (void)
Definition at line 273 of file system-dummy.c.
{
    return 0;
}
Referenced by interface_proto_event_cb(), and mark_interface_down().
system_get_rtime()
time_t system_get_rtime (void)
Definition at line 328 of file system-dummy.c.
{
    struct timeval tv;
    if (gettimeofday(&tv, NULL) == 0)
        return tv.tv_sec;
    return 0;
}
Referenced by interface_ip_add_route(), interface_ip_dump_address_list(), interface_ip_dump_prefix_assignment_list(), interface_ip_dump_prefix_list(), interface_ip_dump_route_list(), interface_ip_valid_until_handler(), interface_proto_event_cb(), interface_refresh_assignments(), interface_set_prefix_address(), interface_update_prefix(), interface_update_prefix_delegation(), netifd_dump_status(), parse_addr(), parse_address_item(), and parse_prefix_option().
system_if_apply_settings()
void system_if_apply_settings (struct device * dev, struct device_settings * s, uint64_t apply_mask)
Definition at line 179 of file system-dummy.c.
{
    apply_mask &= s->flags;
    if ((apply_mask & (DEV_OPT_MACADDR | DEV_OPT_DEFAULT_MACADDR)) && !dev->external) {
        D(SYSTEM, "ifconfig %s hw ether %s",
          dev->ifname, format_macaddr(s->macaddr));
    }
}
References D, DEV_OPT_DEFAULT_MACADDR, DEV_OPT_MACADDR, device::external, device_settings::flags, format_macaddr(), device::ifname, and device_settings::macaddr.
Referenced by bonding_port_cb(), bridge_member_cb(), and set_device_state().
system_if_check()
int system_if_check (struct device * dev)
Definition at line 144 of file system-dummy.c.
{
    if (dev->type == &simple_device_type)
        device_set_present(dev, true);
    device_set_link(dev, true);
    return 0;
}
References device_set_link(), device_set_present, simple_device_type, and device::type.
system_if_clear_state()
void system_if_clear_state (struct device * dev)
Definition at line 139 of file system-dummy.c.
{
    device_set_ifindex(dev, system_if_resolve(dev));
}
References device_set_ifindex(), and system_if_resolve().
Referenced by device_init().
system_if_down()
int system_if_down (struct device * dev)
Definition at line 129 of file system-dummy.c.
{
    D(SYSTEM, "ifconfig %s down", dev->ifname);
    return 0;
}
References D, and device::ifname.
Referenced by set_device_state().
system_if_dump_info()
int system_if_dump_info (struct device * dev, struct blob_buf * b)
Definition at line 166 of file system-dummy.c.
{
    blobmsg_add_u8(b, "link", dev->present);
    return 0;
}
References b, blobmsg_add_u8(), and device::present.
Referenced by bridge_dump_info(), device_dump_status(), macvlan_dump_info(), veth_dump_info(), and vlandev_dump_info().
system_if_dump_stats()
int system_if_dump_stats (struct device * dev, struct blob_buf * b)
Definition at line 173 of file system-dummy.c.
{
    return 0;
}
Referenced by device_dump_status().
system_if_force_external()
bool system_if_force_external (const char * ifname)
Definition at line 118 of file system-dummy.c.
{
    return false;
}
Referenced by device_create_default().
system_if_get_parent()
struct device * system_if_get_parent (struct device * dev)
Definition at line 160 of file system-dummy.c.
{
    return NULL;
}
Referenced by simple_device_set_state().
system_if_get_settings()
void system_if_get_settings (struct device * dev, struct device_settings * s)
Definition at line 135 of file system-dummy.c.
{
}
Referenced by set_device_state().
system_if_resolve()
int system_if_resolve (struct device * dev)
Definition at line 154 of file system-dummy.c.
{
    return 1;
}
Referenced by set_device_state(), and system_if_clear_state().
system_if_up()
int system_if_up (struct device * dev)
Definition at line 123 of file system-dummy.c.
{
    D(SYSTEM, "ifconfig %s up", dev->ifname);
    return 0;
}
References D, and device::ifname.
Referenced by set_device_state().
system_init()
int system_init (void)
Definition at line 28 of file system-dummy.c.
{
    return 0;
}
Referenced by main().
system_is_default_rt_table()
bool system_is_default_rt_table (unsigned int id)
Definition at line 296 of file system-dummy.c.
{
    return true;
}
Referenced by interface_ip_add_route().
system_link_netns_move()
int system_link_netns_move (struct device * dev, int netns_fd, const char * target_ifname)
Definition at line 88 of file system-dummy.c.
{
    D(SYSTEM, "ip link set %s name %s netns %d", dev->ifname, target_ifname, netns_fd);
    return 0;
}
References D, device::ifname, and netns_fd.
Referenced by interface_start_jail(), and interface_stop_jail().
system_macvlan_add()
int system_macvlan_add (struct device * macvlan, struct device * dev, struct macvlan_config * cfg)
Definition at line 353 of file system-dummy.c.
{
    return 0;
}
Referenced by macvlan_set_up().
system_macvlan_del()
int system_macvlan_del (struct device * macvlan)
Definition at line 358 of file system-dummy.c.
{
    return 0;
}
Referenced by macvlan_set_down(), and macvlan_set_up().
system_neighbor_msg()
static int system_neighbor_msg (struct device * dev, struct device_neighbor * neighbor, const char * type) static
Definition at line 241 of file system-dummy.c.
{
    char addr[64];
    int af = system_get_addr_family(neighbor->flags);
    inet_ntop(af, &neighbor->addr.in , addr, sizeof(addr));
    D(SYSTEM, "neigh %s %s%s%s %s", type, addr, neighbor->proxy ? "proxy " : "",
        (neighbor->flags & DEVNEIGH_MAC) ? format_macaddr(neighbor->macaddr) : "",
        neighbor->router ? "router": "");
    return 0;
}
References device_neighbor::addr, D, DEVNEIGH_MAC, device_neighbor::flags, format_macaddr(), if_addr::in, device_neighbor::macaddr, device_neighbor::proxy, device_neighbor::router, system_get_addr_family(), and type.
Referenced by system_add_neighbor(), and system_del_neighbor().
system_netns_open()
int system_netns_open (const pid_t target_ns)
Definition at line 94 of file system-dummy.c.
{
    D(SYSTEM, "open netns of pid %d", target_ns);
    return 1;
}
References D.
system_netns_set()
int system_netns_set (int netns_fd)
Definition at line 100 of file system-dummy.c.
{
    D(SYSTEM, "set netns %d", netns_fd);
    return 0;
}
References D, and netns_fd.
system_resolve_iprule_action()
bool system_resolve_iprule_action (const char * action, unsigned int * id)
Definition at line 322 of file system-dummy.c.
{
    *id = 0;
    return true;
}
Referenced by iprule_add(), and set_ip_source_policy().
system_resolve_rpfilter()
bool system_resolve_rpfilter (const char * filter, unsigned int * id)
Definition at line 301 of file system-dummy.c.
{
    *id = 0;
    return true;
}
Referenced by device_init_settings().
system_resolve_rt_proto()
bool system_resolve_rt_proto (const char * type, unsigned int * id)
Definition at line 284 of file system-dummy.c.
{
    *id = 0;
    return true;
}
Referenced by interface_handle_subnet_route(), and interface_ip_add_route().
system_resolve_rt_table()
bool system_resolve_rt_table (const char * name, unsigned int * id)
Definition at line 290 of file system-dummy.c.
{
    *id = 0;
    return true;
}
Referenced by interface_alloc(), interface_ip_add_route(), and iprule_add().
system_resolve_rt_type()
bool system_resolve_rt_type (const char * type, unsigned int * id)
Definition at line 278 of file system-dummy.c.
{
    *id = 0;
    return true;
}
Referenced by interface_ip_add_route().
system_route_msg()
static int system_route_msg (struct device * dev, struct device_route * route, const char * type) static
Definition at line 211 of file system-dummy.c.
{
    char addr[64], gw[64] = " gw ", devstr[64] = "";
    int af = system_get_addr_family(route->flags);
    int alen = system_get_addr_len(route->flags);
    static uint32_t zero_addr[4];
    if ((route->flags & DEVADDR_FAMILY) != DEVADDR_INET4)
        return -1;
    if (!route->mask)
        sprintf(addr, "default");
    else
        inet_ntop(af, &route->addr.in, addr, sizeof(addr));
    if (memcmp(&route->nexthop.in, (void *) zero_addr, alen) != 0)
        inet_ntop(af, &route->nexthop.in, gw + 4, sizeof(gw) - 4);
    else
        gw[0] = 0;
    if (dev)
        sprintf(devstr, " dev %s", dev->ifname);
    if (route->metric > 0)
        sprintf(devstr, " metric %d", route->metric);
    D(SYSTEM, "route %s %s%s%s", type, addr, gw, devstr);
    return 0;
}
References device_route::addr, D, DEVADDR_FAMILY, DEVADDR_INET4, device_route::flags, device::ifname, if_addr::in, device_route::mask, device_route::metric, device_route::nexthop, system_get_addr_family(), system_get_addr_len(), and type.
Referenced by system_add_route(), and system_del_route().
system_update_ipv6_mtu()
int system_update_ipv6_mtu (struct device * dev, int mtu)
Definition at line 348 of file system-dummy.c.
{
    return 0;
}
Referenced by interface_set_prefix_address().
system_veth_add()
int system_veth_add (struct device * veth, struct veth_config * cfg)
Definition at line 363 of file system-dummy.c.
{
    return 0;
}
Referenced by veth_set_up().
system_veth_del()
int system_veth_del (struct device * veth)
Definition at line 368 of file system-dummy.c.
{
    return 0;
}
Referenced by veth_set_down(), and veth_set_up().
system_vlan_add()
int system_vlan_add (struct device * dev, int id)
Definition at line 106 of file system-dummy.c.
{
    D(SYSTEM, "vconfig add %s %d", dev->ifname, id);
    return 0;
}
References D, and device::ifname.
Referenced by vlan_set_device_state().
system_vlan_del()
int system_vlan_del (struct device * dev)
Definition at line 112 of file system-dummy.c.
{
    D(SYSTEM, "vconfig rem %s", dev->ifname);
    return 0;
}
References D, and device::ifname.
Referenced by vlan_set_device_state().
system_vlandev_add()
int system_vlandev_add (struct device * vlandev, struct device * dev, struct vlandev_config * cfg)
Definition at line 373 of file system-dummy.c.
{
    return 0;
}
Referenced by vlandev_set_up().
system_vlandev_del()
int system_vlandev_del (struct device * vlandev)
Definition at line 378 of file system-dummy.c.
{
    return 0;
}
Referenced by vlandev_set_down(), and vlandev_set_up().