zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/ubus/libubus-sub.c File Reference
libubus-sub.c File Reference
#include "libubus.h"
#include "libubus-internal.h"
Functions
static int ubus_subscriber_cb (struct ubus_context *ctx, struct ubus_object *obj, struct ubus_request_data *req, const char *method, struct blob_attr *msg)
static void ubus_auto_sub_event_handler_cb (struct ubus_context *ctx, struct ubus_event_handler *ev, const char *type, struct blob_attr *msg)
static void ubus_auto_sub_lookup (struct ubus_context *ctx, struct ubus_object_data *obj, void *priv)
int ubus_register_subscriber (struct ubus_context *ctx, struct ubus_subscriber *s)
static int __ubus_subscribe_request (struct ubus_context *ctx, struct ubus_object *obj, uint32_t id, int type)
int ubus_subscribe (struct ubus_context *ctx, struct ubus_subscriber *obj, uint32_t id)
int ubus_unsubscribe (struct ubus_context *ctx, struct ubus_subscriber *obj, uint32_t id)
Variables
const struct ubus_method watch_method __hidden
Function Documentation
__ubus_subscribe_request()
static int __ubus_subscribe_request (struct ubus_context * ctx, struct ubus_object * obj, uint32_t id, int type) static
Definition at line 103 of file libubus-sub.c.
{
    struct ubus_request req;
    blob_buf_init(&b, 0);
    blob_put_int32(&b, UBUS_ATTR_OBJID, obj->id);
    blob_put_int32(&b, UBUS_ATTR_TARGET, id);
    if (ubus_start_request(ctx, &req, b.head, type, 0) < 0)
        return UBUS_STATUS_INVALID_ARGUMENT;
    return ubus_complete_request(ctx, &req, 0);
}
References b, blob_buf_init(), blob_put_int32, ctx, blob_buf::head, ubus_object::id, type, UBUS_ATTR_OBJID, UBUS_ATTR_TARGET, ubus_complete_request(), ubus_start_request(), and UBUS_STATUS_INVALID_ARGUMENT.
Referenced by ubus_subscribe(), and ubus_unsubscribe().
ubus_auto_sub_event_handler_cb()
static void ubus_auto_sub_event_handler_cb (struct ubus_context * ctx, struct ubus_event_handler * ev, const char * type, struct blob_attr * msg) static
Definition at line 35 of file libubus-sub.c.
{
    enum {
        EVENT_ID,
        EVENT_PATH,
        __EVENT_MAX
    };
    static const struct blobmsg_policy event_policy[__EVENT_MAX] = {
        [EVENT_ID] = { .name = "id", .type = BLOBMSG_TYPE_INT32 },
        [EVENT_PATH] = { .name = "path", .type = BLOBMSG_TYPE_STRING },
    };
    struct blob_attr *tb[__EVENT_MAX];
    struct ubus_subscriber *s;
    const char *path;
    int id;
    blobmsg_parse(event_policy, __EVENT_MAX, tb, blob_data(msg), blob_len(msg));
    if (!tb[EVENT_ID] || !tb[EVENT_PATH])
        return;
    path = blobmsg_get_string(tb[EVENT_PATH]);
    id = blobmsg_get_u32(tb[EVENT_ID]);
    list_for_each_entry(s, &ctx->auto_subscribers, list)
        if (s->new_obj_cb(ctx, s, path))
            ubus_subscribe(ctx, s, id);
}
References __EVENT_MAX, ubus_context::auto_subscribers, blob_data(), blob_len(), blobmsg_get_string(), blobmsg_get_u32(), blobmsg_parse(), BLOBMSG_TYPE_INT32, BLOBMSG_TYPE_STRING, ctx, event_policy, id, ubus_subscriber::list, list_for_each_entry, ubus_subscriber::new_obj_cb, path, and ubus_subscribe().
Referenced by ubus_register_subscriber().
ubus_auto_sub_lookup()
static void ubus_auto_sub_lookup (struct ubus_context * ctx, struct ubus_object_data * obj, void * priv) static
Definition at line 68 of file libubus-sub.c.
{
    struct ubus_subscriber *s = priv;
    if (s->new_obj_cb(ctx, s, obj->path))
        ubus_subscribe(ctx, s, obj->id);
}
References ctx, ubus_object::id, ubus_subscriber::new_obj_cb, ubus_subscriber::obj, ubus_object::path, and ubus_subscribe().
Referenced by ubus_register_subscriber().
ubus_register_subscriber()
int ubus_register_subscriber (struct ubus_context * ctx, struct ubus_subscriber * s)
Definition at line 77 of file libubus-sub.c.
{
    struct ubus_object *obj = &s->obj;
    int ret;
    INIT_LIST_HEAD(&s->list);
    obj->methods = &watch_method;
    obj->n_methods = 1;
    ret = ubus_add_object(ctx, obj);
    if (ret)
        return ret;
    if (s->new_obj_cb) {
        struct ubus_event_handler *ev = &ctx->auto_subscribe_event_handler;
        list_add(&s->list, &ctx->auto_subscribers);
        ev->cb = ubus_auto_sub_event_handler_cb;
        if (!ev->obj.id)
            ubus_register_event_handler(ctx, ev, "ubus.object.add");
        ubus_lookup(ctx, NULL, ubus_auto_sub_lookup, s);
    }
    return 0;
}
References ubus_context::auto_subscribe_event_handler, ubus_context::auto_subscribers, ubus_event_handler::cb, ctx, ubus_object::id, INIT_LIST_HEAD(), ubus_subscriber::list, list_add(), ubus_object::methods, ubus_object::n_methods, ubus_subscriber::new_obj_cb, ubus_event_handler::obj, ubus_subscriber::obj, ubus_add_object(), ubus_auto_sub_event_handler_cb(), ubus_auto_sub_lookup(), ubus_lookup(), ubus_register_event_handler(), and watch_method.
Referenced by extdev_add_devtype(), server_main(), ubus_cli_subscribe(), ubus_connect_handler(), ubus_lua_do_subscribe(), watch_ubus(), and watch_ubus_service().
ubus_subscribe()
int ubus_subscribe (struct ubus_context * ctx, struct ubus_subscriber * obj, uint32_t id)
Definition at line 118 of file libubus-sub.c.
{
    return __ubus_subscribe_request(ctx, &obj->obj, id, UBUS_MSG_SUBSCRIBE);
}
References __ubus_subscribe_request(), ctx, ubus_subscriber::obj, and UBUS_MSG_SUBSCRIBE.
Referenced by extdev_subscribe(), netifd_sub_cb(), test_watch(), ubus_auto_sub_event_handler_cb(), ubus_auto_sub_lookup(), ubus_auto_sub_lookup(), ubus_cli_subscribe(), ubus_lua_do_subscribe(), ubusd_handle_add_watch(), watch_subscribe_cb(), and watch_ubus_service().
ubus_subscriber_cb()
static int ubus_subscriber_cb (struct ubus_context * ctx, struct ubus_object * obj, struct ubus_request_data * req, const char * method, struct blob_attr * msg) static
Definition at line 17 of file libubus-sub.c.
{
    struct ubus_subscriber *s;
    s = container_of(obj, struct ubus_subscriber, obj);
    if (s->cb)
        return s->cb(ctx, obj, req, method, msg);
    return 0;
}
References ubus_subscriber::cb, container_of, ctx, and ubus_subscriber::obj.
ubus_unsubscribe()
int ubus_unsubscribe (struct ubus_context * ctx, struct ubus_subscriber * obj, uint32_t id)
Definition at line 123 of file libubus-sub.c.
{
    return __ubus_subscribe_request(ctx, &obj->obj, id, UBUS_MSG_UNSUBSCRIBE);
}
References __ubus_subscribe_request(), ctx, ubus_subscriber::obj, and UBUS_MSG_UNSUBSCRIBE.
Referenced by ubus_notify_unsubscribe(), and ubusd_handle_remove_watch().
Variable Documentation
__hidden
const struct ubus_method watch_method __hidden
Initial value:
= {
    .name = NULL,
    .handler = ubus_subscriber_cb,
}
Definition at line 29 of file libubus-sub.c.
{
    .name = NULL,
    .handler = ubus_subscriber_cb,
};