zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/jail/cgroups-bpf.c File Reference
cgroups-bpf.c File Reference
#include <assert.h>
#include <linux/bpf.h>
#include <sys/cdefs.h>
#include <sys/syscall.h>
#include <libubox/blobmsg.h>
#include <libubox/blobmsg_json.h>
#include <libubox/list.h>
#include "cgroups.h"
#include "cgroups-bpf.h"
#include "log.h"
Classes
struct dev_exception_item
Macros
#define BPF_ALU32_IMM(OP, DST, IMM)
#define BPF_LDX_MEM(SIZE, DST, SRC, OFF)
#define BPF_MOV64_REG(DST, SRC)
#define BPF_JMP_A(OFF)
#define BPF_JMP_IMM(OP, DST, IMM, OFF)
#define BPF_JMP_REG(OP, DST, SRC, OFF)
#define BPF_MOV64_IMM(DST, IMM)
#define BPF_MOV32_REG(DST, SRC)
#define BPF_EXIT_INSN()
#define DEVCG_DEV_ALL (BPF_DEVCG_DEV_BLOCK | BPF_DEVCG_DEV_CHAR)
#define DEVCG_ACC_ALL (BPF_DEVCG_ACC_READ | BPF_DEVCG_ACC_WRITE | BPF_DEVCG_ACC_MKNOD)
Enumerations
enum {
OCI_LINUX_CGROUPS_DEVICES_ALLOW , OCI_LINUX_CGROUPS_DEVICES_TYPE , OCI_LINUX_CGROUPS_DEVICES_MAJOR , OCI_LINUX_CGROUPS_DEVICES_MINOR ,
OCI_LINUX_CGROUPS_DEVICES_ACCESS , __OCI_LINUX_CGROUPS_DEVICES_MAX
}
enum devcg_behavior { DEVCG_DEFAULT_NONE , DEVCG_DEFAULT_ALLOW , DEVCG_DEFAULT_DENY }
Functions
static int syscall_bpf (int cmd, union bpf_attr *attr, unsigned int size)
static int add_default_exceptions (struct list_head *exceptions)
static void flush_exceptions (struct list_head *freelist)
int parseOCIlinuxcgroups_devices (struct blob_attr *msg)
int attach_cgroups_ebpf (int cgroup_dirfd)
Variables
static struct bpf_insn * program = NULL
static int bpf_total_insn = 0
static const char * license = "GPL"
static const struct bpf_insn pre_insn []
static const struct blobmsg_policy oci_linux_cgroups_devices_policy []
Class Documentation
dev_exception_item
struct dev_exception_item
Definition at line 120 of file cgroups-bpf.c.
Class Members
short access
bool allow
struct list_head list
uint32_t major
uint32_t minor
short type
Macro Definition Documentation
BPF_ALU32_IMM
#define BPF_ALU32_IMM (OP, DST, IMM)
Value:
    ((struct bpf_insn){ .code = BPF_ALU | BPF_OP (OP) | BPF_K, .dst_reg = DST, .src_reg = 0, .off = 0, .imm = IMM })
Definition at line 48 of file cgroups-bpf.c.
#define BPF_ALU32_IMM(OP, DST, IMM) \
    ((struct bpf_insn){ .code = BPF_ALU | BPF_OP (OP) | BPF_K, .dst_reg = DST, .src_reg = 0, .off = 0, .imm = IMM })
Referenced by parseOCIlinuxcgroups_devices().
BPF_EXIT_INSN
#define BPF_EXIT_INSN ()
Value:
    ((struct bpf_insn){ .code = BPF_JMP | BPF_EXIT, .dst_reg = 0, .src_reg = 0, .off = 0, .imm = 0 })
Definition at line 73 of file cgroups-bpf.c.
#define BPF_EXIT_INSN() \
    ((struct bpf_insn){ .code = BPF_JMP | BPF_EXIT, .dst_reg = 0, .src_reg = 0, .off = 0, .imm = 0 })
Referenced by parseOCIlinuxcgroups_devices().
BPF_JMP_A
#define BPF_JMP_A (OFF)
Value:
    ((struct bpf_insn){ .code = BPF_JMP | BPF_JA, .dst_reg = 0, .src_reg = 0, .off = OFF, .imm = 0 })
Definition at line 58 of file cgroups-bpf.c.
#define BPF_JMP_A(OFF) \
    ((struct bpf_insn){ .code = BPF_JMP | BPF_JA, .dst_reg = 0, .src_reg = 0, .off = OFF, .imm = 0 })
BPF_JMP_IMM
#define BPF_JMP_IMM (OP, DST, IMM, OFF)
Value:
    ((struct bpf_insn){ .code = BPF_JMP | BPF_OP (OP) | BPF_K, .dst_reg = DST, .src_reg = 0, .off = OFF, .imm = IMM })
Definition at line 61 of file cgroups-bpf.c.
#define BPF_JMP_IMM(OP, DST, IMM, OFF) \
    ((struct bpf_insn){ .code = BPF_JMP | BPF_OP (OP) | BPF_K, .dst_reg = DST, .src_reg = 0, .off = OFF, .imm = IMM })
Referenced by parseOCIlinuxcgroups_devices().
BPF_JMP_REG
#define BPF_JMP_REG (OP, DST, SRC, OFF)
Value:
    ((struct bpf_insn){ .code = BPF_JMP | BPF_OP (OP) | BPF_X, .dst_reg = DST, .src_reg = SRC, .off = OFF, .imm = 0 })
Definition at line 64 of file cgroups-bpf.c.
#define BPF_JMP_REG(OP, DST, SRC, OFF) \
    ((struct bpf_insn){ .code = BPF_JMP | BPF_OP (OP) | BPF_X, .dst_reg = DST, .src_reg = SRC, .off = OFF, .imm = 0 })
Referenced by parseOCIlinuxcgroups_devices().
BPF_LDX_MEM
#define BPF_LDX_MEM (SIZE, DST, SRC, OFF)
Value:
    ((struct bpf_insn){                    \
        .code = BPF_LDX | BPF_SIZE (SIZE) | BPF_MEM, .dst_reg = DST, .src_reg = SRC, .off = OFF, .imm = 0 })
Definition at line 51 of file cgroups-bpf.c.
#define BPF_LDX_MEM(SIZE, DST, SRC, OFF) \
    ((struct bpf_insn){                    \
        .code = BPF_LDX | BPF_SIZE (SIZE) | BPF_MEM, .dst_reg = DST, .src_reg = SRC, .off = OFF, .imm = 0 })
BPF_MOV32_REG
#define BPF_MOV32_REG (DST, SRC)
Value:
    ((struct bpf_insn){ .code = BPF_ALU | BPF_MOV | BPF_X, .dst_reg = DST, .src_reg = SRC, .off = 0, .imm = 0 })
Definition at line 70 of file cgroups-bpf.c.
#define BPF_MOV32_REG(DST, SRC) \
    ((struct bpf_insn){ .code = BPF_ALU | BPF_MOV | BPF_X, .dst_reg = DST, .src_reg = SRC, .off = 0, .imm = 0 })
Referenced by parseOCIlinuxcgroups_devices().
BPF_MOV64_IMM
#define BPF_MOV64_IMM (DST, IMM)
Value:
    ((struct bpf_insn){ .code = BPF_ALU64 | BPF_MOV | BPF_K, .dst_reg = DST, .src_reg = 0, .off = 0, .imm = IMM })
Definition at line 67 of file cgroups-bpf.c.
#define BPF_MOV64_IMM(DST, IMM) \
    ((struct bpf_insn){ .code = BPF_ALU64 | BPF_MOV | BPF_K, .dst_reg = DST, .src_reg = 0, .off = 0, .imm = IMM })
Referenced by parseOCIlinuxcgroups_devices().
BPF_MOV64_REG
#define BPF_MOV64_REG (DST, SRC)
Value:
    ((struct bpf_insn){ .code = BPF_ALU64 | BPF_MOV | BPF_X, .dst_reg = DST, .src_reg = SRC, .off = 0, .imm = 0 })
Definition at line 55 of file cgroups-bpf.c.
#define BPF_MOV64_REG(DST, SRC) \
    ((struct bpf_insn){ .code = BPF_ALU64 | BPF_MOV | BPF_X, .dst_reg = DST, .src_reg = SRC, .off = 0, .imm = 0 })
DEVCG_ACC_ALL
#define DEVCG_ACC_ALL (BPF_DEVCG_ACC_READ | BPF_DEVCG_ACC_WRITE | BPF_DEVCG_ACC_MKNOD)
Definition at line 112 of file cgroups-bpf.c.
Referenced by add_default_exceptions(), and parseOCIlinuxcgroups_devices().
DEVCG_DEV_ALL
#define DEVCG_DEV_ALL (BPF_DEVCG_DEV_BLOCK | BPF_DEVCG_DEV_CHAR)
Definition at line 111 of file cgroups-bpf.c.
Referenced by parseOCIlinuxcgroups_devices().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OCI_LINUX_CGROUPS_DEVICES_ALLOW
OCI_LINUX_CGROUPS_DEVICES_TYPE
OCI_LINUX_CGROUPS_DEVICES_MAJOR
OCI_LINUX_CGROUPS_DEVICES_MINOR
OCI_LINUX_CGROUPS_DEVICES_ACCESS
__OCI_LINUX_CGROUPS_DEVICES_MAX
Definition at line 90 of file cgroups-bpf.c.
     {
    OCI_LINUX_CGROUPS_DEVICES_ALLOW,
    OCI_LINUX_CGROUPS_DEVICES_TYPE,
    OCI_LINUX_CGROUPS_DEVICES_MAJOR,
    OCI_LINUX_CGROUPS_DEVICES_MINOR,
    OCI_LINUX_CGROUPS_DEVICES_ACCESS,
    __OCI_LINUX_CGROUPS_DEVICES_MAX,
};
devcg_behavior
enum devcg_behavior
Enumerator
DEVCG_DEFAULT_NONE
DEVCG_DEFAULT_ALLOW
DEVCG_DEFAULT_DENY
Definition at line 114 of file cgroups-bpf.c.
                    {
    DEVCG_DEFAULT_NONE,
    DEVCG_DEFAULT_ALLOW,
    DEVCG_DEFAULT_DENY,
};
Function Documentation
add_default_exceptions()
static int add_default_exceptions (struct list_head * exceptions) static
Definition at line 131 of file cgroups-bpf.c.
{
    int i, ret = 0;
    struct dev_exception_item *cur;
    /* from crun/src/libcrun/cgroup.c */
    const struct dev_exception_item defrules[] = {
        /* always allow mknod */
        { .allow = true, .type = BPF_DEVCG_DEV_CHAR,  .major = ~0,  .minor = ~0,  .access = BPF_DEVCG_ACC_MKNOD },
        { .allow = true, .type = BPF_DEVCG_DEV_BLOCK, .major = ~0,  .minor = ~0,  .access = BPF_DEVCG_ACC_MKNOD },
        /* /dev/null */
        { .allow = true, .type = BPF_DEVCG_DEV_CHAR,  .major = 1,   .minor = 3,   .access = DEVCG_ACC_ALL },
        /* /dev/random */
        { .allow = true, .type = BPF_DEVCG_DEV_CHAR,  .major = 1,   .minor = 8,   .access = DEVCG_ACC_ALL },
        /* /dev/full */
        { .allow = true, .type = BPF_DEVCG_DEV_CHAR,  .major = 1,   .minor = 7,   .access = DEVCG_ACC_ALL },
        /* /dev/tty */
        { .allow = true, .type = BPF_DEVCG_DEV_CHAR,  .major = 5,   .minor = 0,   .access = DEVCG_ACC_ALL },
        /* /dev/zero */
        { .allow = true, .type = BPF_DEVCG_DEV_CHAR,  .major = 1,   .minor = 5,   .access = DEVCG_ACC_ALL },
        /* /dev/urandom */
        { .allow = true, .type = BPF_DEVCG_DEV_CHAR,  .major = 1,   .minor = 9,   .access = DEVCG_ACC_ALL },
        /* /dev/console */
        { .allow = true, .type = BPF_DEVCG_DEV_CHAR,  .major = 5,   .minor = 1,   .access = DEVCG_ACC_ALL },
        /* /dev/pts/[0-255] */
        { .allow = true, .type = BPF_DEVCG_DEV_CHAR,  .major = 136, .minor = ~0,  .access = DEVCG_ACC_ALL },
        /* /dev/ptmx */
        { .allow = true, .type = BPF_DEVCG_DEV_CHAR,  .major = 5,   .minor = 2,   .access = DEVCG_ACC_ALL },
        /* /dev/net/tun */
        { .allow = true, .type = BPF_DEVCG_DEV_CHAR,  .major = 10,  .minor = 200, .access = DEVCG_ACC_ALL },
    };
    for (i = 0; i < (sizeof(defrules) / sizeof(struct dev_exception_item)); ++i) {
        cur = malloc(sizeof(struct dev_exception_item));
        if (!cur) {
            ret = ENOMEM;
            break;
        }
        /* add defaults to list in reverse order (last item will be first in list) */
        memcpy(cur, &defrules[i], sizeof(struct dev_exception_item));
        list_add(&cur->list, exceptions);
    }
    return ret;
}
References DEVCG_ACC_ALL, dev_exception_item::list, and list_add().
Referenced by parseOCIlinuxcgroups_devices().
attach_cgroups_ebpf()
int attach_cgroups_ebpf (int cgroup_dirfd)
Definition at line 423 of file cgroups-bpf.c.
{
    int prog_fd;
#if (__WORDSIZE == 64)
    uint64_t program_ptr = (uint64_t)program;
    uint64_t license_ptr = (uint64_t)license;
#elif (__WORDSIZE == 32)
    uint32_t program_ptr = (uint32_t)program;
    uint32_t license_ptr = (uint32_t)license;
#else
#error
#endif
    union bpf_attr load_attr = {
        .prog_type = BPF_PROG_TYPE_CGROUP_DEVICE,
        .license   = license_ptr,
        .insns     = program_ptr,
        .insn_cnt  = bpf_total_insn,
    };
    if (!program)
        return 0;
    prog_fd = syscall_bpf(BPF_PROG_LOAD, &load_attr, sizeof(load_attr));
    if (prog_fd < 0)
        return EIO;
    union bpf_attr attach_attr = {
        .attach_type = BPF_CGROUP_DEVICE,
        .target_fd = cgroup_dirfd,
        .attach_bpf_fd = prog_fd,
    };
    return syscall_bpf(BPF_PROG_ATTACH, &attach_attr, sizeof (attach_attr));
}
References bpf_total_insn, license, program, and syscall_bpf().
Referenced by cgroups_apply().
flush_exceptions()
static void flush_exceptions (struct list_head * freelist) static
Definition at line 179 of file cgroups-bpf.c.
{
    struct dev_exception_item *dl, *dln;
    if (!list_empty(freelist))
        list_for_each_entry_safe(dl, dln, freelist, list) {
            list_del(&dl->list);
            free(dl);
        }
}
References dev_exception_item::list, list_del(), list_empty(), and list_for_each_entry_safe.
Referenced by parseOCIlinuxcgroups_devices().
parseOCIlinuxcgroups_devices()
int parseOCIlinuxcgroups_devices (struct blob_attr * msg)
Definition at line 193 of file cgroups-bpf.c.
{
    struct blob_attr *tb[__OCI_LINUX_CGROUPS_DEVICES_MAX];
    struct blob_attr *cur;
    int rem, ret = 0;
    int bpf_type, bpf_access;
    unsigned char acidx;
    bool allow = false,
         has_access = false,
         has_type = false,
         has_major = false,
         has_minor = false;
    int total_ins = 0,
        cur_ins = 0,
        pre_insn_len = sizeof(pre_insn) / sizeof(struct bpf_insn),
        next_ins;
    char *access, *devtype;
    uint32_t devmajor, devminor;
    struct dev_exception_item *dl;
    struct list_head exceptions;
    enum devcg_behavior behavior = DEVCG_DEFAULT_ALLOW;
    INIT_LIST_HEAD(&exceptions);
    /* parse according to OCI spec */
    blobmsg_for_each_attr(cur, msg, rem) {
        blobmsg_parse(oci_linux_cgroups_devices_policy, __OCI_LINUX_CGROUPS_DEVICES_MAX,
                  tb, blobmsg_data(cur), blobmsg_len(cur));
        if (!tb[OCI_LINUX_CGROUPS_DEVICES_ALLOW]) {
            ret = EINVAL;
            goto out;
        }
        allow = blobmsg_get_bool(tb[OCI_LINUX_CGROUPS_DEVICES_ALLOW]);
        bpf_access = 0;
        if (tb[OCI_LINUX_CGROUPS_DEVICES_ACCESS]) {
            access = blobmsg_get_string(tb[OCI_LINUX_CGROUPS_DEVICES_ACCESS]);
            if ((strlen(access) > 3) || (strlen(access) == 0)) {
                ret = EINVAL;
                goto out;
            }
            for (acidx = 0; acidx < strlen(access); ++acidx) {
                switch (access[acidx]) {
                    case 'r':
                        bpf_access |= BPF_DEVCG_ACC_READ;
                        break;
                    case 'w':
                        bpf_access |= BPF_DEVCG_ACC_WRITE;
                        break;
                    case 'm':
                        bpf_access |= BPF_DEVCG_ACC_MKNOD;
                        break;
                    default:
                        ret = EINVAL;
                        goto out;
                }
            }
        }
        if (!bpf_access)
            bpf_access = DEVCG_ACC_ALL;
        bpf_type = 0;
        if (tb[OCI_LINUX_CGROUPS_DEVICES_TYPE]) {
            devtype = blobmsg_get_string(tb[OCI_LINUX_CGROUPS_DEVICES_TYPE]);
            switch (devtype[0]) {
                case 'c':
                    bpf_type = BPF_DEVCG_DEV_CHAR;
                    break;
                case 'b':
                    bpf_type = BPF_DEVCG_DEV_BLOCK;
                    break;
                case 'a':
                    bpf_type = DEVCG_DEV_ALL;
                    break;
                default:
                    ret = EINVAL;
                    goto out;
            }
        }
        if (!bpf_type)
            bpf_type = DEVCG_DEV_ALL;
        if (tb[OCI_LINUX_CGROUPS_DEVICES_MAJOR])
            devmajor = blobmsg_cast_u64(tb[OCI_LINUX_CGROUPS_DEVICES_MAJOR]);
        else
            devmajor = ~0;
        if (tb[OCI_LINUX_CGROUPS_DEVICES_MINOR])
            devminor = blobmsg_cast_u64(tb[OCI_LINUX_CGROUPS_DEVICES_MINOR]);
        else
            devminor = ~0;
        if (bpf_type == DEVCG_DEV_ALL) {
            /* wildcard => change default policy and flush all existing rules */
            flush_exceptions(&exceptions);
            behavior = allow?DEVCG_DEFAULT_ALLOW:DEVCG_DEFAULT_DENY;
        } else {
            /* allocate and populate record for exception */
            dl = malloc(sizeof(struct dev_exception_item));
            if (!dl) {
                ret = ENOSPC;
                break;
            }
            dl->allow = allow;
            dl->type = bpf_type;
            dl->access = bpf_access;
            dl->major = devmajor;
            dl->minor = devminor;
            /* push to exceptions list, last goes first */
            list_add(&dl->list, &exceptions);
        }
    }
    if (ret)
        goto out;
    /* add default rules */
    ret = add_default_exceptions(&exceptions);
    if (ret)
        goto out;
    /* calculate number of instructions to allocate */
    list_for_each_entry(dl, &exceptions, list) {
        has_access = dl->access != DEVCG_ACC_ALL;
        has_type = dl->type != DEVCG_DEV_ALL;
        has_major = dl->major != ~0;
        has_minor = dl->minor != ~0;
        total_ins += (has_type ? 1 : 0) + (has_access ? 3 : 0) + (has_major ? 1 : 0) + (has_minor ? 1 : 0) + 2;
    }
    /* acccount for loader instructions */
    total_ins += pre_insn_len;
    /* final accept/deny block */
    total_ins += 2;
    /* allocate memory for eBPF program */
    program = calloc(total_ins, sizeof(struct bpf_insn));
    if (!program) {
        ret = ENOMEM;
        goto out;
    }
    /* copy program loader instructions */
    memcpy(program, &pre_insn, sizeof(pre_insn));
    cur_ins = pre_insn_len;
    /* generate eBPF program */
    list_for_each_entry(dl, &exceptions, list) {
        has_access = dl->access != DEVCG_ACC_ALL;
        has_type = dl->type != DEVCG_DEV_ALL;
        has_major = dl->major != ~0;
        has_minor = dl->minor != ~0;
        next_ins = (has_type ? 1 : 0) + (has_access ? 3 : 0) + (has_major ? 1 : 0) + (has_minor ? 1 : 0) + 1;
        if (has_type) {
            program[cur_ins++] = BPF_JMP_IMM(BPF_JNE, BPF_REG_2, dl->type, next_ins);
            --next_ins;
        }
        if (has_access) {
            program[cur_ins++] = BPF_MOV32_REG(BPF_REG_1, BPF_REG_3);
            program[cur_ins++] = BPF_ALU32_IMM(BPF_AND, BPF_REG_1, dl->access);
            program[cur_ins++] = BPF_JMP_REG(BPF_JNE, BPF_REG_1, BPF_REG_3, next_ins - 2);
            next_ins -= 3;
        }
        if (has_major) {
            program[cur_ins++] = BPF_JMP_IMM(BPF_JNE, BPF_REG_4, dl->major, next_ins);
            --next_ins;
        }
        if (has_minor) {
            program[cur_ins++] = BPF_JMP_IMM(BPF_JNE, BPF_REG_5, dl->minor, next_ins);
            --next_ins;
        }
        program[cur_ins++] = BPF_MOV64_IMM(BPF_REG_0, dl->allow ? 1 : 0);
        program[cur_ins++] = BPF_EXIT_INSN();
    }
    /* default behavior */
    program[cur_ins++] = BPF_MOV64_IMM(BPF_REG_0, (behavior == DEVCG_DEFAULT_ALLOW)?1:0);
    program[cur_ins++] = BPF_EXIT_INSN();
    if (debug) {
        fprintf(stderr, "cgroup devices:\na > devices.%s\n",
            (behavior == DEVCG_DEFAULT_ALLOW)?"allow":"deny");
        list_for_each_entry(dl, &exceptions, list)
            fprintf(stderr, "%c %d:%d %s%s%s > devices.%s\n",
                (dl->type == DEVCG_DEV_ALL)?'a':
                    (dl->type == BPF_DEVCG_DEV_CHAR)?'c':'b',
                (dl->major == ~0)?-1:dl->major,
                (dl->minor == ~0)?-1:dl->minor,
                (dl->access & BPF_DEVCG_ACC_READ)?"r":"",
                (dl->access & BPF_DEVCG_ACC_WRITE)?"w":"",
                (dl->access & BPF_DEVCG_ACC_MKNOD)?"m":"",
                (dl->allow)?"allow":"deny");
        fprintf(stderr, "generated cgroup-devices eBPF program:\n");
        fprintf(stderr, " [idx]\tcode\t dest\t src\t off\t imm\n");
        for (cur_ins=0; cur_ins<total_ins; cur_ins++)
            fprintf(stderr, " [%03d]\t%02hhx\t%3hhu\t%3hhu\t%04hx\t%d\n", cur_ins,
                program[cur_ins].code,
                program[cur_ins].dst_reg,
                program[cur_ins].src_reg,
                program[cur_ins].off,
                program[cur_ins].imm);
    }
    assert(cur_ins == total_ins);
    bpf_total_insn = total_ins;
    ret = 0;
out:
    flush_exceptions(&exceptions);
    return ret;
}
References __OCI_LINUX_CGROUPS_DEVICES_MAX, dev_exception_item::access, add_default_exceptions(), dev_exception_item::allow, blobmsg_cast_u64(), blobmsg_data(), blobmsg_for_each_attr, blobmsg_get_bool(), blobmsg_get_string(), blobmsg_len(), blobmsg_parse(), BPF_ALU32_IMM, BPF_EXIT_INSN, BPF_JMP_IMM, BPF_JMP_REG, BPF_MOV32_REG, BPF_MOV64_IMM, bpf_total_insn, debug, DEVCG_ACC_ALL, DEVCG_DEFAULT_ALLOW, DEVCG_DEFAULT_DENY, DEVCG_DEV_ALL, flush_exceptions(), INIT_LIST_HEAD(), dev_exception_item::list, list_add(), list_for_each_entry, dev_exception_item::major, dev_exception_item::minor, OCI_LINUX_CGROUPS_DEVICES_ACCESS, OCI_LINUX_CGROUPS_DEVICES_ALLOW, OCI_LINUX_CGROUPS_DEVICES_MAJOR, OCI_LINUX_CGROUPS_DEVICES_MINOR, oci_linux_cgroups_devices_policy, OCI_LINUX_CGROUPS_DEVICES_TYPE, pre_insn, program, and dev_exception_item::type.
Referenced by parseOCIlinuxcgroups().
syscall_bpf()
static int syscall_bpf (int cmd, union bpf_attr * attr, unsigned int size) static
Definition at line 42 of file cgroups-bpf.c.
{
    return (int) syscall (__NR_bpf, cmd, attr, size);
}
References cmd.
Referenced by attach_cgroups_ebpf().
Variable Documentation
bpf_total_insn
int bpf_total_insn = 0 static
Definition at line 38 of file cgroups-bpf.c.
Referenced by attach_cgroups_ebpf(), and parseOCIlinuxcgroups_devices().
license
const char* license = "GPL" static
Definition at line 39 of file cgroups-bpf.c.
Referenced by attach_cgroups_ebpf().
oci_linux_cgroups_devices_policy
const struct blobmsg_policy oci_linux_cgroups_devices_policy[] static
Initial value:
= {
    [OCI_LINUX_CGROUPS_DEVICES_ALLOW] = { "allow", BLOBMSG_TYPE_BOOL },
    [OCI_LINUX_CGROUPS_DEVICES_TYPE] = { "type", BLOBMSG_TYPE_STRING },
    [OCI_LINUX_CGROUPS_DEVICES_MAJOR] = { "major", BLOBMSG_CAST_INT64 },
    [OCI_LINUX_CGROUPS_DEVICES_MINOR] = { "minor", BLOBMSG_CAST_INT64 },
    [OCI_LINUX_CGROUPS_DEVICES_ACCESS] = { "access", BLOBMSG_TYPE_STRING },
}
Definition at line 99 of file cgroups-bpf.c.
{
    [OCI_LINUX_CGROUPS_DEVICES_ALLOW] = { "allow", BLOBMSG_TYPE_BOOL },
    [OCI_LINUX_CGROUPS_DEVICES_TYPE] = { "type", BLOBMSG_TYPE_STRING },
    [OCI_LINUX_CGROUPS_DEVICES_MAJOR] = { "major", BLOBMSG_CAST_INT64 },
    [OCI_LINUX_CGROUPS_DEVICES_MINOR] = { "minor", BLOBMSG_CAST_INT64 },
    [OCI_LINUX_CGROUPS_DEVICES_ACCESS] = { "access", BLOBMSG_TYPE_STRING },
};
Referenced by parseOCIlinuxcgroups_devices().
pre_insn
const struct bpf_insn pre_insn[] static
Initial value:
= {
    BPF_LDX_MEM (BPF_W, BPF_REG_2, BPF_REG_1, 0),
    BPF_ALU32_IMM (BPF_AND, BPF_REG_2, 0xFFFF),
    BPF_LDX_MEM (BPF_W, BPF_REG_3, BPF_REG_1, 0),
    BPF_ALU32_IMM (BPF_RSH, BPF_REG_3, 16),
    BPF_LDX_MEM (BPF_W, BPF_REG_4, BPF_REG_1, 4),
    BPF_LDX_MEM (BPF_W, BPF_REG_5, BPF_REG_1, 8),
}
Definition at line 77 of file cgroups-bpf.c.
{
    /* type -> R2.  */
    BPF_LDX_MEM (BPF_W, BPF_REG_2, BPF_REG_1, 0),
    BPF_ALU32_IMM (BPF_AND, BPF_REG_2, 0xFFFF),
    /* access -> R3.  */
    BPF_LDX_MEM (BPF_W, BPF_REG_3, BPF_REG_1, 0),
    BPF_ALU32_IMM (BPF_RSH, BPF_REG_3, 16),
    /* major -> R4.  */
    BPF_LDX_MEM (BPF_W, BPF_REG_4, BPF_REG_1, 4),
    /* minor -> R5.  */
    BPF_LDX_MEM (BPF_W, BPF_REG_5, BPF_REG_1, 8),
};
Referenced by parseOCIlinuxcgroups_devices().
program
struct bpf_insn* program = NULL static
Definition at line 37 of file cgroups-bpf.c.
Referenced by attach_cgroups_ebpf(), and parseOCIlinuxcgroups_devices().