zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/signal.c File Reference
signal.c File Reference
#include <sys/reboot.h>
#include <sys/types.h>
#include <unistd.h>
#include "procd.h"
Functions
static void do_reboot (void)
static void signal_shutdown (int signal, siginfo_t *siginfo, void *data)
static void signal_crash (int signal, siginfo_t *siginfo, void *data)
static void signal_dummy (int signal, siginfo_t *siginfo, void *data)
void procd_signal (void)
Variables
struct sigaction sa_shutdown
struct sigaction sa_crash
struct sigaction sa_dummy
Function Documentation
do_reboot()
static void do_reboot (void) static
Definition at line 22 of file signal.c.
{
    LOG("reboot\n");
    fflush(stderr);
    sync();
    sleep(2);
    reboot(RB_AUTOBOOT);
    while (1)
    ;
}
References LOG.
Referenced by signal_crash().
procd_signal()
void procd_signal (void)
Definition at line 85 of file signal.c.
{
    signal(SIGPIPE, SIG_IGN);
    if (getpid() != 1)
        return;
    sigaction(SIGTERM, &sa_shutdown, NULL);
    sigaction(SIGINT, &sa_shutdown, NULL);
    sigaction(SIGUSR1, &sa_shutdown, NULL);
    sigaction(SIGUSR2, &sa_shutdown, NULL);
    sigaction(SIGPWR, &sa_shutdown, NULL);
    sigaction(SIGSEGV, &sa_crash, NULL);
    sigaction(SIGBUS, &sa_crash, NULL);
    sigaction(SIGHUP, &sa_dummy, NULL);
    sigaction(SIGKILL, &sa_dummy, NULL);
    sigaction(SIGSTOP, &sa_dummy, NULL);
#ifndef DISABLE_INIT
    reboot(RB_DISABLE_CAD);
#endif
}
References sa_crash, sa_dummy, and sa_shutdown.
Referenced by main().
signal_crash()
static void signal_crash (int signal, siginfo_t * siginfo, void * data) static
Definition at line 64 of file signal.c.
{
    ERROR("Rebooting as procd has crashed\n");
    do_reboot();
}
References do_reboot(), and ERROR.
signal_dummy()
static void signal_dummy (int signal, siginfo_t * siginfo, void * data) static
Definition at line 75 of file signal.c.
{
    ERROR("Got unexpected signal %d\n", signal);
}
References ERROR.
signal_shutdown()
static void signal_shutdown (int signal, siginfo_t * siginfo, void * data) static
Definition at line 33 of file signal.c.
{
    int event = 0;
    char *msg = NULL;
#ifndef DISABLE_INIT
    switch(signal) {
    case SIGINT:
    case SIGTERM:
        event = RB_AUTOBOOT;
        msg = "reboot";
        break;
    case SIGUSR1:
    case SIGUSR2:
    case SIGPWR:
        event = RB_POWER_OFF;
        msg = "poweroff";
        break;
    }
#endif
    DEBUG(1, "Triggering %s\n", msg);
    if (event)
        procd_shutdown(event);
}
References DEBUG, and procd_shutdown().
Variable Documentation
sa_crash
struct sigaction sa_crash
Initial value:
= {
    .sa_sigaction = signal_crash,
    .sa_flags = SA_SIGINFO
}
Definition at line 70 of file signal.c.
{
    .sa_sigaction = signal_crash,
    .sa_flags = SA_SIGINFO
};
Referenced by procd_signal().
sa_dummy
struct sigaction sa_dummy
Initial value:
= {
    .sa_sigaction = signal_dummy,
    .sa_flags = SA_SIGINFO
}
Definition at line 80 of file signal.c.
{
    .sa_sigaction = signal_dummy,
    .sa_flags = SA_SIGINFO
};
Referenced by procd_signal().
sa_shutdown
struct sigaction sa_shutdown
Initial value:
= {
    .sa_sigaction = signal_shutdown,
    .sa_flags = SA_SIGINFO
}
Definition at line 59 of file signal.c.
{
    .sa_sigaction = signal_shutdown,
    .sa_flags = SA_SIGINFO
};
Referenced by procd_signal().