zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/libubox/uloop.h File Reference
uloop.h File Reference
#include <sys/time.h>
#include <sys/types.h>
#include <stdbool.h>
#include <stdint.h>
#include <signal.h>
#include "list.h"
Classes
struct uloop_fd
struct uloop_timeout
struct uloop_process
struct uloop_interval
struct uloop_signal
union uloop_interval.priv
struct uloop_interval.priv.time
Macros
#define USE_EPOLL
#define ULOOP_READ (1 << 0)
#define ULOOP_WRITE (1 << 1)
#define ULOOP_EDGE_TRIGGER (1 << 2)
#define ULOOP_BLOCKING (1 << 3)
#define ULOOP_EVENT_MASK (ULOOP_READ | ULOOP_WRITE)
#define ULOOP_EVENT_BUFFERED (1 << 4)
#define ULOOP_ERROR_CB (1 << 6)
Typedefs
typedef void(* uloop_fd_handler) (struct uloop_fd *u, unsigned int events)
typedef void(* uloop_timeout_handler) (struct uloop_timeout *t)
typedef void(* uloop_process_handler) (struct uloop_process *c, int ret)
typedef void(* uloop_interval_handler) (struct uloop_interval *t)
typedef void(* uloop_signal_handler) (struct uloop_signal *s)
Functions
int uloop_fd_add (struct uloop_fd *sock, unsigned int flags)
int uloop_fd_delete (struct uloop_fd *sock)
int uloop_get_next_timeout (void)
int uloop_timeout_add (struct uloop_timeout *timeout)
int uloop_timeout_set (struct uloop_timeout *timeout, int msecs)
int uloop_timeout_cancel (struct uloop_timeout *timeout)
int uloop_timeout_remaining (struct uloop_timeout *timeout) __attribute__((deprecated("use uloop_timeout_remaining64")))
int64_t uloop_timeout_remaining64 (struct uloop_timeout *timeout)
int uloop_process_add (struct uloop_process *p)
int uloop_process_delete (struct uloop_process *p)
int uloop_interval_set (struct uloop_interval *timer, unsigned int msecs)
int uloop_interval_cancel (struct uloop_interval *timer)
int64_t uloop_interval_remaining (struct uloop_interval *timer)
int uloop_signal_add (struct uloop_signal *s)
int uloop_signal_delete (struct uloop_signal *s)
bool uloop_cancelling (void)
static void uloop_end (void)
int uloop_init (void)
int uloop_run_timeout (int timeout)
static int uloop_run (void)
void uloop_done (void)
Variables
bool uloop_cancelled
bool uloop_handle_sigchld
uloop_fd_handler uloop_fd_set_cb
Class Documentation
uloop_fd
struct uloop_fd
Definition at line 62 of file uloop.h.
Class Members
uloop_fd_handler cb
bool eof
bool error
int fd
uint8_t flags
bool registered
uloop_timeout
struct uloop_timeout
Definition at line 72 of file uloop.h.
Class Members
uloop_timeout_handler cb
struct list_head list
bool pending
struct timeval time
uloop_process
struct uloop_process
Definition at line 81 of file uloop.h.
Class Members
uloop_process_handler cb
struct list_head list
bool pending
pid_t pid
uloop_interval
struct uloop_interval
Definition at line 90 of file uloop.h.
Class Members
uloop_interval_handler cb
uint64_t expirations
union uloop_interval.priv priv
uloop_signal
struct uloop_signal
Definition at line 104 of file uloop.h.
Class Members
uloop_signal_handler cb
struct list_head list
struct sigaction orig
bool pending
int signo
uloop_interval.priv
union uloop_interval.priv
Definition at line 95 of file uloop.h.
Class Members
struct uloop_interval.priv.time time
struct uloop_fd ufd
uloop_interval.priv.time
struct uloop_interval.priv.time
Definition at line 97 of file uloop.h.
Class Members
int64_t fired
unsigned int msecs
Macro Definition Documentation
ULOOP_BLOCKING
#define ULOOP_BLOCKING (1 << 3)
Definition at line 50 of file uloop.h.
Referenced by luaopen_uloop(), ubus_add_uloop(), and uloop_fd_add().
ULOOP_EDGE_TRIGGER
#define ULOOP_EDGE_TRIGGER (1 << 2)
Definition at line 49 of file uloop.h.
Referenced by client_cb(), get_flags(), get_next_connection(), init_bridge_ops(), luaopen_uloop(), main(), packet_sock_init(), register_kevent(), register_poll(), register_poll(), ubus_msg_send(), uloop_fd_stack_event(), uloop_fetch_events(), ustream_fd_set_uloop(), and wireless_device_run_handler().
ULOOP_ERROR_CB
#define ULOOP_ERROR_CB (1 << 6)
Definition at line 60 of file uloop.h.
Referenced by create_event_socket(), create_hotplug_event_socket(), uloop_fetch_events(), uloop_fetch_events(), and ustream_fd_set_uloop().
ULOOP_EVENT_BUFFERED
#define ULOOP_EVENT_BUFFERED (1 << 4)
Definition at line 55 of file uloop.h.
Referenced by uloop_fd_stack_event().
ULOOP_EVENT_MASK
#define ULOOP_EVENT_MASK (ULOOP_READ | ULOOP_WRITE)
Definition at line 52 of file uloop.h.
Referenced by uloop_run_events().
ULOOP_READ
#define ULOOP_READ (1 << 0)
Definition at line 47 of file uloop.h.
Referenced by __ustream_fd_poll(), client_cb(), create_raw_event_socket(), dispatch_timer(), get_next_connection(), hotplug(), init_bridge_ops(), jail_network_start(), luaopen_uloop(), main(), packet_sock_init(), register_kevent(), register_poll(), run_server(), timer_register(), ubus_add_uloop(), ubus_handle_event(), ubus_init_hotplug(), ubus_msg_send(), ubus_poll_data(), udebug_add_uloop(), uloop_fd_add(), uloop_fetch_events(), uloop_fetch_events(), ustream_fd_poll(), ustream_fd_set_uloop(), waker_init(), and wireless_device_run_handler().
ULOOP_WRITE
#define ULOOP_WRITE (1 << 1)
Definition at line 48 of file uloop.h.
Referenced by __ustream_fd_poll(), client_cb(), luaopen_uloop(), register_kevent(), register_poll(), ubus_msg_send(), uloop_fd_add(), uloop_fetch_events(), uloop_fetch_events(), ustream_fd_poll(), and ustream_fd_set_uloop().
USE_EPOLL
#define USE_EPOLL
Definition at line 30 of file uloop.h.
Typedef Documentation
uloop_fd_handler
typedef void(* uloop_fd_handler) (struct uloop_fd *u, unsigned int events)
Definition at line 41 of file uloop.h.
uloop_interval_handler
typedef void(* uloop_interval_handler) (struct uloop_interval *t)
Definition at line 44 of file uloop.h.
uloop_process_handler
typedef void(* uloop_process_handler) (struct uloop_process *c, int ret)
Definition at line 43 of file uloop.h.
uloop_signal_handler
typedef void(* uloop_signal_handler) (struct uloop_signal *s)
Definition at line 45 of file uloop.h.
uloop_timeout_handler
typedef void(* uloop_timeout_handler) (struct uloop_timeout *t)
Definition at line 42 of file uloop.h.
Function Documentation
uloop_cancelling()
bool uloop_cancelling (void)
Definition at line 653 of file uloop.c.
{
    return uloop_run_depth > 0 && uloop_cancelled;
}
References uloop_cancelled, and uloop_run_depth.
Referenced by ubus_handle_data().
uloop_done()
void uloop_done (void)
Definition at line 686 of file uloop.c.
{
    uloop_setup_signals(false);
    if (poll_fd >= 0) {
        close(poll_fd);
        poll_fd = -1;
    }
    if (waker_pipe >= 0) {
        uloop_fd_delete(&waker_fd);
        close(waker_pipe);
        close(waker_fd.fd);
        waker_pipe = -1;
    }
    uloop_clear_timeouts();
    uloop_clear_processes();
}
References uloop_fd::fd, poll_fd, uloop_clear_processes(), uloop_clear_timeouts(), uloop_fd_delete(), uloop_setup_signals(), waker_fd, and waker_pipe.
Referenced by do_listen(), instance_start(), main(), main(), main(), post_poststart(), queue_next(), rpc_cgi_password_set(), rpc_exec(), rpc_file_exec_run(), ubus_cli_monitor(), ubus_cli_wait_for(), and uloop_init().
uloop_end()
static void uloop_end (void) inline static
Definition at line 140 of file uloop.h.
{
    uloop_cancelled = true;
}
References uloop_cancelled.
Referenced by local_cb(), netifd_handle_signal(), post_start_hook(), q_empty(), rc_init(), rc_list_exec(), run_netifd(), tracer_cb(), ubus_cli_listen_timeout(), ubus_default_connection_lost(), ul_end(), upgrade_proc_cb(), wait_check_object(), and wait_timeout().
uloop_fd_add()
int uloop_fd_add (struct uloop_fd * sock, unsigned int flags)
Definition at line 235 of file uloop.c.
{
    unsigned int fl;
    int ret;
    if (!(flags & (ULOOP_READ | ULOOP_WRITE)))
        return uloop_fd_delete(sock);
    if (!sock->registered && !(flags & ULOOP_BLOCKING)) {
        fl = fcntl(sock->fd, F_GETFL, 0);
        fl |= O_NONBLOCK;
        fcntl(sock->fd, F_SETFL, fl);
    }
    ret = register_poll(sock, flags);
    if (ret < 0)
        goto out;
    if (uloop_fd_set_cb)
        uloop_fd_set_cb(sock, flags);
    sock->flags = flags;
    sock->registered = true;
    sock->eof = false;
    sock->error = false;
out:
    return ret;
}
References uloop_fd::eof, uloop_fd::error, uloop_fd::fd, uloop_fd::flags, register_poll(), uloop_fd::registered, ULOOP_BLOCKING, uloop_fd_delete(), uloop_fd_set_cb, ULOOP_READ, and ULOOP_WRITE.
Referenced by client_cb(), create_raw_event_socket(), get_next_connection(), hotplug(), init_bridge_ops(), jail_network_start(), main(), packet_sock_init(), run_server(), timer_register(), ubus_add_uloop(), ubus_init_hotplug(), ubus_msg_send(), udebug_add_uloop(), ul_ufd_add(), ustream_fd_set_uloop(), waker_init(), and wireless_device_run_handler().
uloop_fd_delete()
int uloop_fd_delete (struct uloop_fd * sock)
Definition at line 265 of file uloop.c.
{
    int ret;
    int i;
    for (i = 0; i < cur_nfds; i++) {
        if (cur_fds[cur_fd + i].fd != fd)
            continue;
        cur_fds[cur_fd + i].fd = NULL;
    }
    if (!fd->registered)
        return 0;
    if (uloop_fd_set_cb)
        uloop_fd_set_cb(fd, 0);
    fd->registered = false;
    uloop_fd_stack_event(fd, -1);
    ret = __uloop_fd_delete(fd);
    fd->flags = 0;
    return ret;
}
References __uloop_fd_delete(), cur_fd, cur_fds, cur_nfds, uloop_fd_event::fd, uloop_fd_stack::fd, uloop_fd::flags, uloop_fd::registered, uloop_fd_set_cb, and uloop_fd_stack_event().
Referenced by __udebug_disconnect(), handle_client_disconnect(), handle_hotplug_event(), handler_nl_event(), hotplug_shutdown(), packet_rcv(), run_netifd(), timer_register(), ubus_reconnect(), ubus_shutdown(), ul_ufd_delete(), uloop_done(), uloop_fd_add(), uloop_fetch_events(), uloop_fetch_events(), ustream_fd_free(), and wireless_close_script_proc_fd().
uloop_get_next_timeout()
int uloop_get_next_timeout (void)
Definition at line 595 of file uloop.c.
{
    struct uloop_timeout *timeout;
    struct timeval tv;
    int64_t diff;
    if (list_empty(&timeouts))
        return -1;
    uloop_gettime(&tv);
    timeout = list_first_entry(&timeouts, struct uloop_timeout, list);
    diff = tv_diff(&timeout->time, &tv);
    if (diff < 0)
        return 0;
    if (diff > INT_MAX)
        return INT_MAX;
    return diff;
}
References list_empty(), list_first_entry, timeout, timeouts, tv_diff(), and uloop_gettime().
Referenced by uloop_run_timeout().
uloop_init()
int uloop_init (void)
Definition at line 150 of file uloop.c.
{
    if (uloop_init_pollfd() < 0)
        return -1;
    if (waker_init() < 0) {
        uloop_done();
        return -1;
    }
    uloop_setup_signals(true);
    return 0;
}
References uloop_done(), uloop_init_pollfd(), uloop_setup_signals(), and waker_init().
Referenced by do_listen(), exec_jail(), hotplug_run(), main(), main(), main(), run_server(), ubus_cli_monitor(), ubus_cli_wait_for(), ubus_connect_ctx(), ul_init(), and uxc_attach().
uloop_interval_cancel()
int uloop_interval_cancel (struct uloop_interval * timer)
Definition at line 458 of file uloop.c.
{
    return timer_remove(timer);
}
References timer_remove().
Referenced by ul_interval_free().
uloop_interval_remaining()
int64_t uloop_interval_remaining (struct uloop_interval * timer)
Definition at line 463 of file uloop.c.
{
    return timer_next(timer);
}
References timer_next().
Referenced by ul_interval_remaining().
uloop_interval_set()
int uloop_interval_set (struct uloop_interval * timer, unsigned int msecs)
Definition at line 453 of file uloop.c.
{
    return timer_register(timer, msecs);
}
References timer_register().
Referenced by ul_interval(), and ul_interval_set().
uloop_process_add()
int uloop_process_add (struct uloop_process * p)
Definition at line 391 of file uloop.c.
{
    struct uloop_process *tmp;
    struct list_head *h = &processes;
    if (p->pending)
        return -1;
    list_for_each_entry(tmp, &processes, list) {
        if (tmp->pid > p->pid) {
            h = &tmp->list;
            break;
        }
    }
    list_add_tail(&p->list, h);
    p->pending = true;
    return 0;
}
References uloop_process::list, list_add_tail(), list_for_each_entry, uloop_process::pending, uloop_process::pid, and processes.
Referenced by fork_worker(), hotplug_exec(), instance_start(), main(), netifd_start_process(), post_main(), preinit(), procd_coldplug(), queue_next(), rc_init(), rc_list_exec(), rpc_exec(), rpc_file_exec_run(), run_cmd(), run_hooklist(), runqueue_process_add(), sysupgrade(), tracer_cb(), and ul_process().
uloop_process_delete()
int uloop_process_delete (struct uloop_process * p)
Definition at line 412 of file uloop.c.
{
    if (!p->pending)
        return -1;
    list_del(&p->list);
    p->pending = false;
    return 0;
}
References uloop_process::list, list_del(), and uloop_process::pending.
Referenced by instance_free(), netifd_kill_process(), rc_list_exec(), rpc_exec_reply(), rpc_file_exec_reply(), rpc_list_exec_timeout_cb(), runqueue_process_kill_cb(), ul_process_free(), uloop_clear_processes(), and uloop_handle_processes().
uloop_run()
static int uloop_run (void) inline static
Definition at line 147 of file uloop.h.
{
    return uloop_run_timeout(-1);
}
References uloop_run_timeout().
Referenced by client_main(), do_listen(), exec_jail(), hotplug_run(), jail_network_start(), main(), main(), main(), post_create_runtime(), post_poststart(), run_hooklist(), run_server(), server_main(), sysupgrade(), ubus_cli_monitor(), ubus_cli_wait_for(), ul_run(), and uxc_attach().
uloop_run_timeout()
int uloop_run_timeout (int timeout)
Definition at line 658 of file uloop.c.
{
    int next_time = 0;
    uloop_run_depth++;
    uloop_status = 0;
    uloop_cancelled = false;
    do {
        uloop_process_timeouts();
        if (do_sigchld)
            uloop_handle_processes();
        if (uloop_cancelled)
            break;
        next_time = uloop_get_next_timeout();
        if (timeout >= 0 && (next_time < 0 || timeout < next_time))
                next_time = timeout;
        uloop_run_events(next_time);
    } while (!uloop_cancelled && timeout < 0);
    --uloop_run_depth;
    return uloop_status;
}
References do_sigchld, timeout, uloop_cancelled, uloop_get_next_timeout(), uloop_handle_processes(), uloop_process_timeouts(), uloop_run_depth, uloop_run_events(), and uloop_status.
Referenced by uloop_run().
uloop_signal_add()
int uloop_signal_add (struct uloop_signal * s)
Definition at line 550 of file uloop.c.
{
    struct list_head *h = &signals;
    struct uloop_signal *tmp;
    struct sigaction sa;
    if (s->pending)
        return -1;
    list_for_each_entry(tmp, &signals, list) {
        if (tmp->signo > s->signo) {
            h = &tmp->list;
            break;
        }
    }
    list_add_tail(&s->list, h);
    s->pending = true;
    sigaction(s->signo, NULL, &s->orig);
    if (s->orig.sa_handler != uloop_signal_wake) {
        sa.sa_handler = uloop_signal_wake;
        sa.sa_flags = 0;
        sigemptyset(&sa.sa_mask);
        sigaction(s->signo, &sa, NULL);
    }
    return 0;
}
References uloop_signal::list, list_add_tail(), list_for_each_entry, uloop_signal::orig, uloop_signal::pending, signals, uloop_signal::signo, and uloop_signal_wake().
Referenced by ul_signal().
uloop_signal_delete()
int uloop_signal_delete (struct uloop_signal * s)
Definition at line 581 of file uloop.c.
{
    if (!s->pending)
        return -1;
    list_del(&s->list);
    s->pending = false;
    if (s->orig.sa_handler != uloop_signal_wake)
        sigaction(s->signo, &s->orig, NULL);
    return 0;
}
References uloop_signal::list, list_del(), uloop_signal::orig, uloop_signal::pending, uloop_signal::signo, and uloop_signal_wake().
Referenced by ul_signal_free().
uloop_timeout_add()
int uloop_timeout_add (struct uloop_timeout * timeout)
Definition at line 298 of file uloop.c.
{
    struct uloop_timeout *tmp;
    struct list_head *h = &timeouts;
    if (timeout->pending)
        return -1;
    list_for_each_entry(tmp, &timeouts, list) {
        if (tv_diff(&tmp->time, &timeout->time) > 0) {
            h = &tmp->list;
            break;
        }
    }
    list_add_tail(&timeout->list, h);
    timeout->pending = true;
    return 0;
}
References uloop_timeout::list, list_add_tail(), list_for_each_entry, uloop_timeout::time, timeout, timeouts, and tv_diff().
Referenced by add_sleeper(), config_watch_notify_cb(), exec_jail(), handle_start(), inotify_read_handler(), jail_network_start(), main(), and uloop_timeout_set().
uloop_timeout_cancel()
int uloop_timeout_cancel (struct uloop_timeout * timeout)
Definition at line 348 of file uloop.c.
{
    if (!timeout->pending)
        return -1;
    list_del(&timeout->list);
    timeout->pending = false;
    return 0;
}
References list_del(), and timeout.
Referenced by __bridge_reload(), bridge_free_member(), button_free(), hook_process_handler(), hotplug_last_event(), instance_exit(), instance_free(), interface_cleanup(), jail_process_handler(), proto_shell_free(), proto_shell_task_finish(), rc_list_exec_running_cb(), rpc_exec_reply(), rpc_file_exec_reply(), rpc_session_destroy(), rpc_uci_confirm(), rpc_uci_do_rollback(), rpc_ucode_request_gc(), runqueue_kill(), runqueue_task_complete(), service_handle_watchdog(), ubus_auto_shutdown(), ubus_shutdown(), udebug_free(), ul_timer_free(), uloop_clear_timeouts(), uloop_process_timeouts(), uloop_timeout_set(), ustream_free(), watchdog_set_stopped(), wireless_device_free_state(), and wireless_start_pending().
uloop_timeout_remaining()
int uloop_timeout_remaining (struct uloop_timeout * timeout)
Definition at line 359 of file uloop.c.
{
    int64_t td;
    struct timeval now;
    if (!timeout->pending)
        return -1;
    uloop_gettime(&now);
    td = tv_diff(&timeout->time, &now);
    if (td > INT_MAX)
        return INT_MAX;
    else if (td < INT_MIN)
        return INT_MIN;
    else
        return (int)td;
}
References timeout, tv_diff(), and uloop_gettime().
uloop_timeout_remaining64()
int64_t uloop_timeout_remaining64 (struct uloop_timeout * timeout)
Definition at line 379 of file uloop.c.
{
    struct timeval now;
    if (!timeout->pending)
        return -1;
    uloop_gettime(&now);
    return tv_diff(&timeout->time, &now);
}
References timeout, tv_diff(), and uloop_gettime().
Referenced by rpc_session_to_blob(), trigger_command_add(), and ul_timer_remaining().
uloop_timeout_set()
int uloop_timeout_set (struct uloop_timeout * timeout, int msecs)
Definition at line 328 of file uloop.c.
{
    struct timeval *time = &timeout->time;
    if (timeout->pending)
        uloop_timeout_cancel(timeout);
    uloop_gettime(time);
    time->tv_sec += msecs / 1000;
    time->tv_usec += (msecs % 1000) * 1000;
    if (time->tv_usec > 1000000) {
        time->tv_sec++;
        time->tv_usec -= 1000000;
    }
    return uloop_timeout_add(timeout);
}
References timeout, uloop_gettime(), uloop_timeout_add(), and uloop_timeout_cancel().
Referenced by __bridge_reload(), __runqueue_start_next(), __udebug_disconnect(), add_sleeper(), bonding_config_init(), bonding_set_up(), bridge_check_retry(), bridge_member_cb(), child_exit(), client_main(), device_free_unused(), do_listen(), extdev_bridge_check_retry(), handle_button_complete(), hotplug_call(), hotplug_done(), hotplug_last_event(), instance_exit(), instance_restart(), instance_start(), instance_stop(), interface_ip_init_worker(), interface_ip_valid_until_handler(), jail_handle_signal(), netifd_device_remove_cb(), netifd_iface_remove(), netifd_restart(), netifd_sub_cb(), netifd_ubus_reconnect_timer(), post_poststart(), proto_shell_handler(), proto_shell_task_finish(), rc_list_exec(), rpc_exec(), rpc_file_exec_run(), rpc_session_from_blob(), rpc_touch_session(), rpc_uci_apply(), rpc_ucode_script_call(), rule_handle_command(), run_hooklist(), runqueue_start_next(), runqueue_task_cancel(), service_handle_watchdog(), test_client_notify_cb(), test_count(), test_hello(), test_hello_fd_reply(), timeout_retry(), trigger_command_add(), ubus_auto_connect_cb(), ubus_auto_disconnect_cb(), ubus_auto_reconnect_cb(), ubus_cli_wait_for(), ubus_connect_handler(), ubus_queue_msg(), udebug_reconnect_cb(), ul_timer(), ul_timer_set(), ustream_state_change(), watchdog_timeout_cb(), wireless_device_add_process(), wireless_device_check_script_tasks(), wireless_device_setup_cancel(), wireless_proc_poll_fd(), wireless_start_pending(), worker_init(), and worker_timer_cb().
Variable Documentation
uloop_cancelled
bool uloop_cancelled extern
Definition at line 63 of file uloop.c.
Referenced by handle_signal(), uloop_cancelling(), uloop_end(), uloop_handle_sigint(), and uloop_run_timeout().
uloop_fd_set_cb
uloop_fd_handler uloop_fd_set_cb extern
Definition at line 72 of file uloop.c.
Referenced by uloop_fd_add(), and uloop_fd_delete().
uloop_handle_sigchld
bool uloop_handle_sigchld extern
Definition at line 64 of file uloop.c.
Referenced by uloop_setup_signals().