zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/netifd/proto.h File Reference
proto.h File Reference
Classes
struct interface_proto_state
struct proto_handler
Enumerations
enum interface_proto_event { IFPEV_UP , IFPEV_DOWN , IFPEV_LINK_LOST , IFPEV_RENEW }
enum interface_proto_cmd { PROTO_CMD_SETUP , PROTO_CMD_TEARDOWN , PROTO_CMD_RENEW }
enum {
PROTO_FLAG_IMMEDIATE = (1 << 0) , PROTO_FLAG_NODEV = (1 << 1) , PROTO_FLAG_INIT_AVAILABLE = (1 << 2) , PROTO_FLAG_RENEW_AVAILABLE = (1 << 3) ,
PROTO_FLAG_FORCE_LINK_DEFAULT = (1 << 4) , PROTO_FLAG_LASTERROR = (1 << 5) , PROTO_FLAG_TEARDOWN_ON_L3_LINK_DOWN = (1 << 6) , PROTO_FLAG_NO_TASK = (1 << 7) ,
PROTO_FLAG_NODEV_CONFIG = (1 << 8)
}
Functions
void add_proto_handler (struct proto_handler *p)
void proto_init_interface (struct interface *iface, struct blob_attr *attr)
void proto_attach_interface (struct interface *iface, const char *proto_name)
int interface_proto_event (struct interface_proto_state *proto, enum interface_proto_cmd cmd, bool force)
unsigned int parse_netmask_string (const char *str, bool v6)
int proto_apply_static_ip_settings (struct interface *iface, struct blob_attr *attr)
int proto_apply_ip_settings (struct interface *iface, struct blob_attr *attr, bool ext)
void proto_dump_handlers (struct blob_buf *b)
void proto_shell_init (void)
Variables
const struct uci_blob_param_list proto_ip_attr
Class Documentation
interface_proto_state
struct interface_proto_state
Definition at line 46 of file proto.h.
Class Members
int(*)(struct interface_proto_state *, enum interface_proto_cmd cmd, bool force) cb
void(*)(struct interface_proto_state *) free
const struct proto_handler * handler
struct interface * iface
int(*)(struct interface_proto_state *, struct blob_attr *data) notify
void(*)(struct interface_proto_state *, enum interface_proto_event ev) proto_event
proto_handler
struct proto_handler
Definition at line 60 of file proto.h.
Class Members
struct interface_proto_state *(*)(const struct proto_handler *h, struct interface *iface, struct blob_attr *attr) attach
struct avl_node avl
const struct uci_blob_param_list * config_params
unsigned int flags
const char * name
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROTO_FLAG_IMMEDIATE (1 << 0)
PROTO_FLAG_NODEV (1 << 1)
PROTO_FLAG_INIT_AVAILABLE (1 << 2)
PROTO_FLAG_RENEW_AVAILABLE (1 << 3)
PROTO_FLAG_FORCE_LINK_DEFAULT (1 << 4)
PROTO_FLAG_LASTERROR (1 << 5)
PROTO_FLAG_TEARDOWN_ON_L3_LINK_DOWN (1 << 6)
PROTO_FLAG_NO_TASK (1 << 7)
PROTO_FLAG_NODEV_CONFIG (1 << 8)
Definition at line 34 of file proto.h.
     {
    PROTO_FLAG_IMMEDIATE = (1 << 0),
    PROTO_FLAG_NODEV = (1 << 1),
    PROTO_FLAG_INIT_AVAILABLE = (1 << 2),
    PROTO_FLAG_RENEW_AVAILABLE = (1 << 3),
    PROTO_FLAG_FORCE_LINK_DEFAULT = (1 << 4),
    PROTO_FLAG_LASTERROR = (1 << 5),
    PROTO_FLAG_TEARDOWN_ON_L3_LINK_DOWN = (1 << 6),
    PROTO_FLAG_NO_TASK = (1 << 7),
    PROTO_FLAG_NODEV_CONFIG = (1 << 8),
};
interface_proto_cmd
enum interface_proto_cmd
Enumerator
PROTO_CMD_SETUP
PROTO_CMD_TEARDOWN
PROTO_CMD_RENEW
Definition at line 28 of file proto.h.
{
    PROTO_CMD_SETUP,
    PROTO_CMD_TEARDOWN,
    PROTO_CMD_RENEW,
};
interface_proto_event
enum interface_proto_event
Enumerator
IFPEV_UP
IFPEV_DOWN
IFPEV_LINK_LOST
IFPEV_RENEW
Definition at line 21 of file proto.h.
{
    IFPEV_UP,
    IFPEV_DOWN,
    IFPEV_LINK_LOST,
    IFPEV_RENEW,
};
Function Documentation
add_proto_handler()
void add_proto_handler (struct proto_handler * p)
Definition at line 518 of file proto.c.
{
    if (!handlers.comp)
        avl_init(&handlers, avl_strcmp, false, NULL);
    if (p->avl.key)
        return;
    p->avl.key = p->name;
    avl_insert(&handlers, &p->avl);
}
References proto_handler::avl, avl_init(), avl_insert(), avl_strcmp(), avl_tree::comp, handlers, avl_node::key, and proto_handler::name.
Referenced by proto_shell_add_handler(), and static_proto_init().
interface_proto_event()
int interface_proto_event (struct interface_proto_state * proto, enum interface_proto_cmd cmd, bool force)
Definition at line 656 of file proto.c.
{
    enum interface_proto_event ev;
    int ret;
    ret = proto->cb(proto, cmd, force);
    if (ret || !(proto->handler->flags & PROTO_FLAG_IMMEDIATE))
        goto out;
    switch(cmd) {
    case PROTO_CMD_SETUP:
        ev = IFPEV_UP;
        break;
    case PROTO_CMD_TEARDOWN:
        ev = IFPEV_DOWN;
        break;
    case PROTO_CMD_RENEW:
        ev = IFPEV_RENEW;
        break;
    default:
        return -EINVAL;
    }
    proto->proto_event(proto, ev);
out:
    return ret;
}
References interface_proto_state::cb, cmd, proto_handler::flags, interface_proto_state::handler, IFPEV_DOWN, IFPEV_RENEW, IFPEV_UP, PROTO_CMD_RENEW, PROTO_CMD_SETUP, PROTO_CMD_TEARDOWN, interface_proto_state::proto_event, and PROTO_FLAG_IMMEDIATE.
parse_netmask_string()
unsigned int parse_netmask_string (const char * str, bool v6)
Definition at line 80 of file utils.c.
{
    struct in_addr addr;
    unsigned int ret;
    char *err = NULL;
    if (!strchr(str, '.')) {
        ret = strtoul(str, &err, 0);
        if (err && *err)
            goto error;
        return ret;
    }
    if (v6)
        goto error;
    if (inet_aton(str, &addr) != 1)
        goto error;
    return 32 - fls(~(ntohl(addr.s_addr)));
error:
    return ~0;
}
References err.
Referenced by interface_ip_add_route(), parse_address_item(), and proto_apply_static_ip_settings().
proto_apply_ip_settings()
int proto_apply_ip_settings (struct interface * iface, struct blob_attr * attr, bool ext)
Definition at line 481 of file proto.c.
{
    struct blob_attr *tb[__OPT_MAX];
    struct blob_attr *cur;
    int n_v4 = 0, n_v6 = 0;
    blobmsg_parse(proto_ip_attributes, __OPT_MAX, tb, blob_data(attr), blob_len(attr));
    if ((cur = tb[OPT_IPADDR]))
        n_v4 = parse_address_list(iface, cur, false, ext);
    if ((cur = tb[OPT_IP6ADDR]))
        n_v6 = parse_address_list(iface, cur, true, ext);
    if ((cur = tb[OPT_IP6PREFIX]))
        if (parse_prefix_list(iface, cur) < 0)
            goto out;
    if (n_v4 < 0 || n_v6 < 0)
        goto out;
    if ((cur = tb[OPT_GATEWAY])) {
        if (n_v4 && !parse_gateway_option(iface, cur, false))
            goto out;
    }
    if ((cur = tb[OPT_IP6GW])) {
        if (n_v6 && !parse_gateway_option(iface, cur, true))
            goto out;
    }
    return 0;
out:
    return -1;
}
References __OPT_MAX, blob_data(), blob_len(), blobmsg_parse(), OPT_GATEWAY, OPT_IP6ADDR, OPT_IP6GW, OPT_IP6PREFIX, OPT_IPADDR, parse_address_list(), parse_gateway_option(), parse_prefix_list(), and proto_ip_attributes.
Referenced by proto_shell_update_link().
proto_apply_static_ip_settings()
int proto_apply_static_ip_settings (struct interface * iface, struct blob_attr * attr)
Definition at line 411 of file proto.c.
{
    struct blob_attr *tb[__OPT_MAX];
    struct blob_attr *cur;
    const char *error;
    unsigned int netmask = 32;
    bool ip6deprecated;
    int n_v4 = 0, n_v6 = 0;
    struct in_addr bcast = {0,}, ptp = {0,};
    blobmsg_parse(proto_ip_attributes, __OPT_MAX, tb, blob_data(attr), blob_len(attr));
    if ((cur = tb[OPT_NETMASK])) {
        netmask = parse_netmask_string(blobmsg_data(cur), false);
        if (netmask > 32) {
            error = "INVALID_NETMASK";
            goto error;
        }
    }
    if ((cur = tb[OPT_BROADCAST])) {
        if (!inet_pton(AF_INET, blobmsg_data(cur), &bcast)) {
            error = "INVALID_BROADCAST";
            goto error;
        }
    }
    if ((cur = tb[OPT_PTPADDR])) {
        if (!inet_pton(AF_INET, blobmsg_data(cur), &ptp)) {
            error = "INVALID_PTPADDR";
            goto error;
        }
    }
    ip6deprecated = blobmsg_get_bool_default(tb[OPT_IP6DEPRECATED], false);
    if ((cur = tb[OPT_IPADDR]))
        n_v4 = parse_static_address_option(iface, cur, false,
            netmask, false, bcast.s_addr, ptp.s_addr, false);
    if ((cur = tb[OPT_IP6ADDR]))
        n_v6 = parse_static_address_option(iface, cur, true,
            128, false, 0, 0, ip6deprecated);
    if ((cur = tb[OPT_IP6PREFIX]))
        if (parse_prefix_list(iface, cur) < 0)
            goto out;
    if (n_v4 < 0 || n_v6 < 0)
        goto out;
    if ((cur = tb[OPT_GATEWAY])) {
        if (n_v4 && !parse_gateway_option(iface, cur, false))
            goto out;
    }
    if ((cur = tb[OPT_IP6GW])) {
        if (n_v6 && !parse_gateway_option(iface, cur, true))
            goto out;
    }
    return 0;
error:
    interface_add_error(iface, "proto", error, NULL, 0);
out:
    return -1;
}
References __OPT_MAX, blob_data(), blob_len(), blobmsg_data(), blobmsg_get_bool_default(), blobmsg_parse(), interface_add_error(), OPT_BROADCAST, OPT_GATEWAY, OPT_IP6ADDR, OPT_IP6DEPRECATED, OPT_IP6GW, OPT_IP6PREFIX, OPT_IPADDR, OPT_NETMASK, OPT_PTPADDR, parse_gateway_option(), parse_netmask_string(), parse_prefix_list(), parse_static_address_option(), and proto_ip_attributes.
Referenced by static_proto_setup().
proto_attach_interface()
void proto_attach_interface (struct interface * iface, const char * proto_name)
Definition at line 636 of file proto.c.
{
    const struct proto_handler *proto = &no_proto;
    const char *error = NULL;
    if (proto_name) {
        proto = get_proto_handler(proto_name);
        if (!proto) {
            error = "INVALID_PROTO";
            proto = &no_proto;
        }
    }
    iface->proto_handler = proto;
    if (error)
        interface_add_error(iface, "proto", error, NULL, 0);
}
References get_proto_handler(), interface_add_error(), no_proto, and interface::proto_handler.
Referenced by interface_alloc().
proto_dump_handlers()
void proto_dump_handlers (struct blob_buf * b)
Definition at line 587 of file proto.c.
{
    struct proto_handler *p;
    void *c;
    avl_for_each_element(&handlers, p, avl) {
        void *v;
        c = blobmsg_open_table(b, p->name);
        if (p->config_params && p->config_params->validate) {
            int i;
            v = blobmsg_open_table(b, "validate");
            for (i = 0; i < p->config_params->n_params; i++)
                blobmsg_add_string(b, p->config_params->params[i].name, uci_get_validate_string(p->config_params, i));
            blobmsg_close_table(b, v);
        }
        blobmsg_add_u8(b, "immediate", !!(p->flags & PROTO_FLAG_IMMEDIATE));
        blobmsg_add_u8(b, "no_device", !!(p->flags & PROTO_FLAG_NODEV));
        blobmsg_add_u8(b, "init_available", !!(p->flags & PROTO_FLAG_INIT_AVAILABLE));
        blobmsg_add_u8(b, "renew_available", !!(p->flags & PROTO_FLAG_RENEW_AVAILABLE));
        blobmsg_add_u8(b, "force_link_default", !!(p->flags & PROTO_FLAG_FORCE_LINK_DEFAULT));
        blobmsg_add_u8(b, "last_error", !!(p->flags & PROTO_FLAG_LASTERROR));
        blobmsg_add_u8(b, "teardown_on_l3_link_down", !!(p->flags & PROTO_FLAG_TEARDOWN_ON_L3_LINK_DOWN));
        blobmsg_add_u8(b, "no_task", !!(p->flags & PROTO_FLAG_NO_TASK));
        blobmsg_close_table(b, c);
    }
}
References proto_handler::avl, avl_for_each_element, b, blobmsg_add_string(), blobmsg_add_u8(), blobmsg_close_table(), blobmsg_open_table(), proto_handler::config_params, proto_handler::flags, handlers, proto_handler::name, PROTO_FLAG_FORCE_LINK_DEFAULT, PROTO_FLAG_IMMEDIATE, PROTO_FLAG_INIT_AVAILABLE, PROTO_FLAG_LASTERROR, PROTO_FLAG_NO_TASK, PROTO_FLAG_NODEV, PROTO_FLAG_RENEW_AVAILABLE, PROTO_FLAG_TEARDOWN_ON_L3_LINK_DOWN, and uci_get_validate_string().
Referenced by netifd_get_proto_handlers().
proto_init_interface()
void proto_init_interface (struct interface * iface, struct blob_attr * attr)
Definition at line 617 of file proto.c.
{
    const struct proto_handler *proto = iface->proto_handler;
    struct interface_proto_state *state = NULL;
    if (!proto)
        proto = &no_proto;
    state = proto->attach(proto, iface, attr);
    if (!state) {
        state = no_proto.attach(&no_proto, iface, attr);
        state->cb = invalid_proto_handler;
    }
    state->handler = proto;
    interface_set_proto_state(iface, state);
}
References proto_handler::attach, interface_proto_state::cb, interface_proto_state::handler, interface_proto_state::iface, interface_set_proto_state(), invalid_proto_handler(), no_proto, interface::proto_handler, and state.
Referenced by interface_do_reload(), and interface_update().
proto_shell_init()
void proto_shell_init (void)
Definition at line 947 of file proto-shell.c.
{
    proto_fd = netifd_open_subdir("proto");
    if (proto_fd < 0)
        return;
    netifd_init_script_handlers(proto_fd, proto_shell_add_handler);
}
References netifd_init_script_handlers(), netifd_open_subdir(), proto_fd, and proto_shell_add_handler().
Referenced by main().
Variable Documentation
proto_ip_attr
const struct uci_blob_param_list proto_ip_attr extern
Definition at line 73 of file proto.c.
{
    .n_params = __OPT_MAX,
    .params = proto_ip_attributes,
    .validate = proto_ip_validate,
    .info = proto_ip_attr_info,
};