zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/libubox/blobmsg.c File Reference
blobmsg.c File Reference
#include "blobmsg.h"
Functions
bool blobmsg_check_attr (const struct blob_attr *attr, bool name)
static bool blobmsg_check_name (const struct blob_attr *attr, bool name)
bool blobmsg_check_attr_len (const struct blob_attr *attr, bool name, size_t len)
int blobmsg_check_array (const struct blob_attr *attr, int type)
int blobmsg_check_array_len (const struct blob_attr *attr, int type, size_t blob_len)
bool blobmsg_check_attr_list (const struct blob_attr *attr, int type)
bool blobmsg_check_attr_list_len (const struct blob_attr *attr, int type, size_t len)
int blobmsg_parse_array (const struct blobmsg_policy *policy, int policy_len, struct blob_attr **tb, void *data, unsigned int len)
int blobmsg_parse (const struct blobmsg_policy *policy, int policy_len, struct blob_attr **tb, void *data, unsigned int len)
static struct blob_attr * blobmsg_new (struct blob_buf *buf, int type, const char *name, int payload_len, void **data)
static int attr_to_offset (struct blob_buf *buf, struct blob_attr *attr)
void * blobmsg_open_nested (struct blob_buf *buf, const char *name, bool array)
__attribute__ ((format(printf, 3, 0)))
__attribute__ ((format(printf, 3, 4)))
void * blobmsg_alloc_string_buffer (struct blob_buf *buf, const char *name, unsigned int maxlen)
void * blobmsg_realloc_string_buffer (struct blob_buf *buf, unsigned int maxlen)
void blobmsg_add_string_buffer (struct blob_buf *buf)
int blobmsg_add_field (struct blob_buf *buf, int type, const char *name, const void *data, unsigned int len)
Variables
static const int blob_type [__BLOBMSG_TYPE_LAST]
Function Documentation
__attribute__() [1/2]
__attribute__ ((format(printf, 3, 0)))
Definition at line 284 of file blobmsg.c.
{
    va_list arg2;
    char cbuf;
    char *sbuf;
    int len, ret;
    va_copy(arg2, arg);
    len = vsnprintf(&cbuf, sizeof(cbuf), format, arg2);
    va_end(arg2);
    if (len < 0)
        return -1;
    sbuf = blobmsg_alloc_string_buffer(buf, name, len);
    if (!sbuf)
        return -1;
    ret = vsnprintf(sbuf, len + 1, format, arg);
    if (ret < 0)
        return -1;
    blobmsg_add_string_buffer(buf);
    return ret;
}
References blobmsg_add_string_buffer(), blobmsg_alloc_string_buffer(), and buf.
__attribute__() [2/2]
__attribute__ ((format(printf, 3, 4)))
Definition at line 312 of file blobmsg.c.
{
    va_list ap;
    int ret;
    va_start(ap, format);
    ret = blobmsg_vprintf(buf, name, format, ap);
    va_end(ap);
    return ret;
}
References blobmsg_vprintf(), and buf.
attr_to_offset()
static int attr_to_offset (struct blob_buf * buf, struct blob_attr * attr) inline static
Definition at line 259 of file blobmsg.c.
{
    return (char *)attr - (char *) buf->buf + BLOB_COOKIE;
}
References BLOB_COOKIE, and buf.
Referenced by blobmsg_open_nested(), and blobmsg_realloc_string_buffer().
blobmsg_add_field()
int blobmsg_add_field (struct blob_buf * buf, int type, const char * name, const void * data, unsigned int len)
Definition at line 377 of file blobmsg.c.
{
    struct blob_attr *attr;
    void *data_dest;
    attr = blobmsg_new(buf, type, name, len, &data_dest);
    if (!attr)
        return -1;
    if (len > 0)
        memcpy(data_dest, data, len);
    return 0;
}
References blobmsg_new(), buf, blob_attr::data, and type.
Referenced by __buf_add_all(), blobmsg_add_blob(), blobmsg_add_double(), blobmsg_add_json_element(), blobmsg_add_string(), blobmsg_add_u16(), blobmsg_add_u32(), blobmsg_add_u64(), blobmsg_add_u8(), rpc_handle_get(), rpc_plugin_json_element_to_blob(), rpc_session_dump_data(), rpc_ucode_ucv_to_blob(), ubus_cli_get_monitor_data(), ubus_send_event(), and ubusd_reply_add().
blobmsg_add_string_buffer()
void blobmsg_add_string_buffer (struct blob_buf * buf)
Definition at line 361 of file blobmsg.c.
{
    struct blob_attr *attr;
    int len, attrlen;
    attr = blob_next(buf->head);
    len = strlen(blobmsg_data(attr)) + 1;
    attrlen = blob_raw_len(attr) + len;
    blob_set_raw_len(attr, attrlen);
    blob_fill_pad(attr);
    blob_set_raw_len(buf->head, blob_raw_len(buf->head) + blob_pad_len(attr));
}
References blob_fill_pad(), blob_next(), blob_pad_len(), blob_raw_len(), blob_set_raw_len(), blobmsg_data(), and buf.
Referenced by __attribute__(), eval_string(), interface_ip_dump_address_list(), interface_ip_dump_dns_server_list(), interface_ip_dump_neighbor_list(), interface_ip_dump_prefix_assignment_list(), interface_ip_dump_prefix_list(), interface_ip_dump_route_list(), rpc_file_md5(), rpc_file_read(), rpc_ustream_to_blobmsg(), rpc_ustream_to_blobmsg(), system_add_link_mode_name(), system_board(), and system_if_dump_info().
blobmsg_alloc_string_buffer()
void * blobmsg_alloc_string_buffer (struct blob_buf * buf, const char * name, unsigned int maxlen)
Definition at line 326 of file blobmsg.c.
{
    struct blob_attr *attr;
    void *data_dest;
    maxlen++;
    attr = blobmsg_new(buf, BLOBMSG_TYPE_STRING, name, maxlen, &data_dest);
    if (!attr)
        return NULL;
    blob_set_raw_len(buf->head, blob_pad_len(buf->head) - blob_pad_len(attr));
    blob_set_raw_len(attr, blob_raw_len(attr) - maxlen);
    return data_dest;
}
References blob_pad_len(), blob_raw_len(), blob_set_raw_len(), blobmsg_new(), BLOBMSG_TYPE_STRING, and buf.
Referenced by __attribute__(), eval_string(), interface_ip_dump_address_list(), interface_ip_dump_dns_server_list(), interface_ip_dump_neighbor_list(), interface_ip_dump_prefix_assignment_list(), interface_ip_dump_prefix_list(), interface_ip_dump_route_list(), rpc_file_md5(), rpc_file_read(), rpc_ustream_to_blobmsg(), rpc_ustream_to_blobmsg(), system_add_link_mode_name(), system_board(), and system_if_dump_info().
blobmsg_check_array()
int blobmsg_check_array (const struct blob_attr * attr, int type)
Definition at line 87 of file blobmsg.c.
{
    return blobmsg_check_array_len(attr, type, blob_raw_len(attr));
}
References blob_raw_len(), blobmsg_check_array_len(), and type.
Referenced by blobmsg_check_attr_list(), bridge_hotplug_set_member_vlans(), check_message(), check_table_a_entries(), and device_set_extra_vlans().
blobmsg_check_array_len()
int blobmsg_check_array_len (const struct blob_attr * attr, int type, size_t blob_len)
Definition at line 92 of file blobmsg.c.
{
    struct blob_attr *cur;
    size_t rem;
    bool name;
    int size = 0;
    if (type > BLOBMSG_TYPE_LAST)
        return -1;
    if (!blobmsg_check_attr_len(attr, false, blob_len))
        return -1;
    switch (blobmsg_type(attr)) {
    case BLOBMSG_TYPE_TABLE:
        name = true;
        break;
    case BLOBMSG_TYPE_ARRAY:
        name = false;
        break;
    default:
        return -1;
    }
    blobmsg_for_each_attr(cur, attr, rem) {
        if (type != BLOBMSG_TYPE_UNSPEC && blobmsg_type(cur) != type)
            return -1;
        if (!blobmsg_check_attr_len(cur, name, rem))
            return -1;
        size++;
    }
    return size;
}
References blob_len(), blobmsg_check_attr_len(), blobmsg_for_each_attr, BLOBMSG_TYPE_ARRAY, BLOBMSG_TYPE_LAST, BLOBMSG_TYPE_TABLE, BLOBMSG_TYPE_UNSPEC, and type.
Referenced by blobmsg_check_array(), blobmsg_check_attr_list_len(), and fuzz_blobmsg_parse().
blobmsg_check_attr()
bool blobmsg_check_attr (const struct blob_attr * attr, bool name)
Definition at line 28 of file blobmsg.c.
{
    return blobmsg_check_attr_len(attr, name, blob_raw_len(attr));
}
References blob_raw_len(), and blobmsg_check_attr_len().
Referenced by blobmsg_format_element(), blobmsg_list_fill(), fill_string_list(), interface_add_assignment_classes(), interface_add_data(), interface_add_dns_search_list(), interface_add_dns_server_list(), netifd_handle_alias(), netifd_ubus_data_cb(), proto_shell_notify_error(), rpc_ucode_blob_to_ucv(), ubus_create_obj_type(), ubus_lua_parse_blob(), and vlandev_qos_mapping_list_apply().
blobmsg_check_attr_len()
bool blobmsg_check_attr_len (const struct blob_attr * attr, bool name, size_t len)
Definition at line 58 of file blobmsg.c.
{
    const char *data;
    size_t data_len;
    int id;
    if (len < sizeof(struct blob_attr))
        return false;
    data_len = blob_raw_len(attr);
    if (data_len < sizeof(struct blob_attr) || data_len > len)
        return false;
    if (!blobmsg_check_name(attr, name))
        return false;
    id = blob_id(attr);
    if (id > BLOBMSG_TYPE_LAST)
        return false;
    if (!blob_type[id])
        return true;
    data = blobmsg_data(attr);
    data_len = blobmsg_data_len(attr);
    return blob_check_type(data, data_len, blob_type[id]);
}
References blob_check_type(), blob_id(), blob_raw_len(), blob_type, blobmsg_check_name(), blobmsg_data(), blobmsg_data_len(), BLOBMSG_TYPE_LAST, id, and blobmsg_hdr::name.
Referenced by blobmsg_check_array_len(), blobmsg_check_attr(), blobmsg_parse(), blobmsg_parse_array(), fuzz_blobmsg_parse(), and rpc_ucode_validate_call_args().
blobmsg_check_attr_list()
bool blobmsg_check_attr_list (const struct blob_attr * attr, int type)
Definition at line 130 of file blobmsg.c.
{
    return blobmsg_check_array(attr, type) >= 0;
}
References blobmsg_check_array(), and type.
Referenced by instance_config_parse_command(), instance_fill_array(), and test_blobmsg_procd_instance().
blobmsg_check_attr_list_len()
bool blobmsg_check_attr_list_len (const struct blob_attr * attr, int type, size_t len)
Definition at line 135 of file blobmsg.c.
{
    return blobmsg_check_array_len(attr, type, len) >= 0;
}
References blobmsg_check_array_len(), and type.
Referenced by fuzz_blobmsg_parse().
blobmsg_check_name()
static bool blobmsg_check_name (const struct blob_attr * attr, bool name) static
Definition at line 33 of file blobmsg.c.
{
    const struct blobmsg_hdr *hdr;
    uint16_t namelen;
    if (!blob_is_extended(attr))
        return !name;
    if (blob_len(attr) < sizeof(struct blobmsg_hdr))
        return false;
    hdr = (const struct blobmsg_hdr *)blob_data(attr);
    if (name && !hdr->namelen)
        return false;
    namelen = blobmsg_namelen(hdr);
    if (blob_len(attr) < (size_t)blobmsg_hdrlen(namelen))
        return false;
    if (hdr->name[namelen] != 0)
        return false;
    return true;
}
References blob_data(), blob_is_extended(), blob_len(), blobmsg_hdrlen(), blobmsg_namelen(), blobmsg_hdr::name, and blobmsg_hdr::namelen.
Referenced by blobmsg_check_attr_len().
blobmsg_new()
static struct blob_attr * blobmsg_new (struct blob_buf * buf, int type, const char * name, int payload_len, void ** data) static
Definition at line 227 of file blobmsg.c.
{
    struct blob_attr *attr;
    struct blobmsg_hdr *hdr;
    int attrlen, namelen;
    char *pad_start, *pad_end;
    if (!name)
        name = "";
    namelen = strlen(name);
    attrlen = blobmsg_hdrlen(namelen) + payload_len;
    attr = blob_new(buf, type, attrlen);
    if (!attr)
        return NULL;
    attr->id_len |= be32_to_cpu(BLOB_ATTR_EXTENDED);
    hdr = blob_data(attr);
    hdr->namelen = cpu_to_be16(namelen);
    memcpy(hdr->name, name, namelen);
    hdr->name[namelen] = '\0';
    pad_end = *data = blobmsg_data(attr);
    pad_start = (char *) &hdr->name[namelen];
    if (pad_start < pad_end)
        memset(pad_start, 0, pad_end - pad_start);
    return attr;
}
References be32_to_cpu, BLOB_ATTR_EXTENDED, blob_data(), blob_new(), blobmsg_data(), blobmsg_hdrlen(), buf, cpu_to_be16, blob_attr::id_len, blobmsg_hdr::name, blobmsg_hdr::namelen, and type.
Referenced by blobmsg_add_field(), blobmsg_alloc_string_buffer(), and blobmsg_open_nested().
blobmsg_open_nested()
void * blobmsg_open_nested (struct blob_buf * buf, const char * name, bool array)
Definition at line 266 of file blobmsg.c.
{
    struct blob_attr *head;
    int type = array ? BLOBMSG_TYPE_ARRAY : BLOBMSG_TYPE_TABLE;
    unsigned long offset = attr_to_offset(buf, buf->head);
    void *data;
    if (!name)
        name = "";
    head = blobmsg_new(buf, type, name, 0, &data);
    if (!head)
        return NULL;
    blob_set_raw_len(buf->head, blob_pad_len(buf->head) - blobmsg_hdrlen(strlen(name)));
    buf->head = head;
    return (void *)offset;
}
References attr_to_offset(), blob_pad_len(), blob_set_raw_len(), blobmsg_hdrlen(), blobmsg_new(), BLOBMSG_TYPE_ARRAY, BLOBMSG_TYPE_TABLE, buf, blob_attr::data, and type.
Referenced by blobmsg_open_array(), and blobmsg_open_table().
blobmsg_parse()
int blobmsg_parse (const struct blobmsg_policy * policy, int policy_len, struct blob_attr ** tb, void * data, unsigned int len)
Definition at line 166 of file blobmsg.c.
{
    const struct blobmsg_hdr *hdr;
    struct blob_attr *attr;
    uint8_t *pslen;
    int i;
    memset(tb, 0, policy_len * sizeof(*tb));
    if (!data || !len)
        return -EINVAL;
    pslen = alloca(policy_len);
    for (i = 0; i < policy_len; i++) {
        if (!policy[i].name)
            continue;
        pslen[i] = strlen(policy[i].name);
    }
    __blob_for_each_attr(attr, data, len) {
        if (!blobmsg_check_attr_len(attr, false, len))
            return -1;
        if (!blob_is_extended(attr))
            continue;
        hdr = blob_data(attr);
        for (i = 0; i < policy_len; i++) {
            if (!policy[i].name)
                continue;
            if (policy[i].type != BLOBMSG_TYPE_UNSPEC &&
                policy[i].type != BLOBMSG_CAST_INT64 &&
                blob_id(attr) != policy[i].type)
                continue;
            if (policy[i].type == BLOBMSG_CAST_INT64 &&
                (blob_id(attr) != BLOBMSG_TYPE_INT64 &&
                 blob_id(attr) != BLOBMSG_TYPE_INT32 &&
                 blob_id(attr) != BLOBMSG_TYPE_INT16 &&
                 blob_id(attr) != BLOBMSG_TYPE_INT8))
                continue;
            if (blobmsg_namelen(hdr) != pslen[i])
                continue;
            if (tb[i])
                continue;
            if (strcmp(policy[i].name, (char *) hdr->name) != 0)
                continue;
            tb[i] = attr;
        }
    }
    return 0;
}
References __blob_for_each_attr, blob_data(), blob_id(), blob_is_extended(), BLOBMSG_CAST_INT64, blobmsg_check_attr_len(), blobmsg_namelen(), BLOBMSG_TYPE_INT16, BLOBMSG_TYPE_INT32, BLOBMSG_TYPE_INT64, BLOBMSG_TYPE_INT8, BLOBMSG_TYPE_UNSPEC, blob_attr::data, blobmsg_hdr::name, and type.
Referenced by __bridge_reload(), __interface_add(), __reload(), __rpc_check_path(), acl_add(), acl_recv_cb(), blobmsg_parse_attr(), bonding_reload(), bridge_reload(), check_message(), check_table_a_entries(), checkblock(), config_find_blobmsg_attr(), config_parse_vlan(), config_watch_notify_cb(), container_handle_console(), container_handle_kill(), device_set_config(), dump_cb(), dump_message(), dump_message(), dump_message_cast_s64(), dump_message_cast_s64_json(), dump_message_cast_u64(), dump_message_cast_u64_json(), dump_message_json(), extdev_wait_ev_cb(), fuzz_blobmsg_parse(), get_wdev(), hotplug_call(), instance_config_parse(), instance_gen_setns_argstr(), instance_jail_parse(), interface_alloc(), interface_device_config_changed(), interface_ip_add_neighbor(), interface_ip_add_route(), iprule_add(), list_cb(), macvlan_reload(), netifd_add_dynamic(), netifd_add_host_route(), netifd_dev_status(), netifd_handle_alias(), netifd_handle_iface(), netifd_handle_set_state(), netifd_iface_handle_device(), netifd_netns_updown(), ocistate_cb(), parse_address_item(), parseOCI(), parseOCIcapabilities(), parseOCIdevices(), parseOCIhook(), parseOCIhooks(), parseOCIlinux(), parseOCIlinuxcgroups(), parseOCIlinuxcgroups_devices(), parseOCIlinuxcgroups_legacy_blockio(), parseOCIlinuxcgroups_legacy_cpu(), parseOCIlinuxcgroups_legacy_memory(), parseOCIlinuxcgroups_legacy_pids(), parseOCIlinuxns(), parseOCIlinuxseccomp(), parseOCImount(), parseOCIprocess(), parseOCIprocessuser(), parseOCIrlimit(), parseOCIroot(), parseOCIuidgidmappings(), proc_signal(), proto_apply_ip_settings(), proto_apply_static_ip_settings(), proto_shell_checkup_attach(), proto_shell_notify(), rc_init(), rc_list(), resolveuuid(), rpc_cgi_password_set(), rpc_file_exec(), rpc_handle_access(), rpc_handle_acl(), rpc_handle_create(), rpc_handle_destroy(), rpc_handle_get(), rpc_handle_list(), rpc_handle_login(), rpc_handle_set(), rpc_handle_unset(), rpc_iwinfo_assoclist(), rpc_iwinfo_open(), rpc_iwinfo_phyname(), rpc_session_from_blob(), rpc_sys_packagelist(), rpc_sys_upgrade_start(), rpc_uci_add(), rpc_uci_apply(), rpc_uci_changes(), rpc_uci_confirm(), rpc_uci_delete(), rpc_uci_getcommon(), rpc_uci_order(), rpc_uci_rename(), rpc_uci_revert_commit(), rpc_uci_rollback(), rpc_uci_set(), service_get_data(), service_handle_delete(), service_handle_event(), service_handle_list(), service_handle_set(), service_handle_signal(), service_handle_state(), service_handle_update(), service_handle_validate(), service_handle_watchdog(), service_validate_add(), settings_add(), simple_device_create(), system_add_gre_tunnel(), system_add_ip6_tunnel(), system_add_ip_tunnel(), system_add_sit_tunnel(), system_add_vti_tunnel(), system_add_vxlan(), system_add_xfrm_tunnel(), sysupgrade(), test_blobmsg(), test_blobmsg_procd_instance(), test_count(), test_count_data_cb(), test_hello(), test_watch(), tunnel_reload(), ubus_auto_sub_event_handler_cb(), ubus_bridge_state(), ubus_set_bridge_config(), ubusd_acl_add_access(), ubusd_acl_file_add(), ubusd_alloc_event_pattern(), ubusd_forward_event(), uxc_boot(), uxc_create(), uxc_delete(), uxc_kill(), uxc_list(), uxc_set(), uxc_state(), validate_firmware_image(), veth_reload(), vlandev_reload(), wait_event_cb(), watch_subscribe_cb(), and watchdog_set().
blobmsg_parse_array()
int blobmsg_parse_array (const struct blobmsg_policy * policy, int policy_len, struct blob_attr ** tb, void * data, unsigned int len)
Definition at line 140 of file blobmsg.c.
{
    struct blob_attr *attr;
    int i = 0;
    memset(tb, 0, policy_len * sizeof(*tb));
    __blob_for_each_attr(attr, data, len) {
        if (policy[i].type != BLOBMSG_TYPE_UNSPEC &&
            blob_id(attr) != policy[i].type)
            continue;
        if (!blobmsg_check_attr_len(attr, false, len))
            return -1;
        if (tb[i])
            continue;
        tb[i++] = attr;
        if (i == policy_len)
            break;
    }
    return 0;
}
References __blob_for_each_attr, blob_id(), blobmsg_check_attr_len(), BLOBMSG_TYPE_UNSPEC, blob_attr::data, and type.
Referenced by blobmsg_parse_array_attr(), fuzz_blobmsg_parse(), handle_if(), handle_makedev(), handle_rm(), json_get_tuple(), and test_blobmsg().
blobmsg_realloc_string_buffer()
void * blobmsg_realloc_string_buffer (struct blob_buf * buf, unsigned int maxlen)
Definition at line 343 of file blobmsg.c.
{
    struct blob_attr *attr = blob_next(buf->head);
    int offset = attr_to_offset(buf, blob_next(buf->head)) + blob_pad_len(attr) - BLOB_COOKIE;
    int required = maxlen + 1 - (buf->buflen - offset);
    if (required <= 0)
        goto out;
    if (!blob_buf_grow(buf, required))
        return NULL;
    attr = blob_next(buf->head);
out:
    return blobmsg_data(attr);
}
References attr_to_offset(), blob_buf_grow(), BLOB_COOKIE, blob_next(), blob_pad_len(), blobmsg_data(), and buf.
Referenced by eval_string().
Variable Documentation
blob_type
const int blob_type[__BLOBMSG_TYPE_LAST] static
Initial value:
= {
    [BLOBMSG_TYPE_INT8] = BLOB_ATTR_INT8,
    [BLOBMSG_TYPE_INT16] = BLOB_ATTR_INT16,
    [BLOBMSG_TYPE_INT32] = BLOB_ATTR_INT32,
    [BLOBMSG_TYPE_INT64] = BLOB_ATTR_INT64,
    [BLOBMSG_TYPE_DOUBLE] = BLOB_ATTR_DOUBLE,
    [BLOBMSG_TYPE_STRING] = BLOB_ATTR_STRING,
    [BLOBMSG_TYPE_UNSPEC] = BLOB_ATTR_BINARY,
}
Definition at line 18 of file blobmsg.c.
{
    [BLOBMSG_TYPE_INT8] = BLOB_ATTR_INT8,
    [BLOBMSG_TYPE_INT16] = BLOB_ATTR_INT16,
    [BLOBMSG_TYPE_INT32] = BLOB_ATTR_INT32,
    [BLOBMSG_TYPE_INT64] = BLOB_ATTR_INT64,
    [BLOBMSG_TYPE_DOUBLE] = BLOB_ATTR_DOUBLE,
    [BLOBMSG_TYPE_STRING] = BLOB_ATTR_STRING,
    [BLOBMSG_TYPE_UNSPEC] = BLOB_ATTR_BINARY,
};
Referenced by blobmsg_check_attr_len().