zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/netifd/interface-event.c File Reference
interface-event.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <libubox/uloop.h>
#include "netifd.h"
#include "interface.h"
#include "ubus.h"
Functions
static void task_complete (struct uloop_process *proc, int ret)
static void run_cmd (const char *ifname, const char *device, enum interface_event event, enum interface_update_flags updated)
static void call_hotplug (void)
static void interface_queue_event (struct interface *iface, enum interface_event ev)
static void interface_dequeue_event (struct interface *iface)
static void interface_event_cb (struct interface_user *dep, struct interface *iface, enum interface_event ev)
static void __init interface_event_init (void)
Variables
char * hotplug_cmd_path = DEFAULT_HOTPLUG_PATH
static struct interface * current
static enum interface_event current_ev
static struct list_head pending = LIST_HEAD_INIT(pending)
static struct uloop_process task
static const char *const eventnames []
static struct interface_user event_user
Function Documentation
call_hotplug()
static void call_hotplug (void) static
Definition at line 87 of file interface-event.c.
{
    const char *device = NULL;
    if (list_empty(&pending))
        return;
    current = list_first_entry(&pending, struct interface, hotplug_list);
    current_ev = current->hotplug_ev;
    list_del_init(&current->hotplug_list);
    if ((current_ev == IFEV_UP || current_ev == IFEV_UPDATE) && current->l3_dev.dev)
        device = current->l3_dev.dev->ifname;
    D(SYSTEM, "Call hotplug handler for interface '%s', event '%s' (%s)",
    current->name, eventnames[current_ev], device ? device : "none");
    run_cmd(current->name, device, current_ev, current->updated);
}
References current, current_ev, D, device_user::dev, eventnames, interface::hotplug_ev, interface::hotplug_list, IFEV_UP, IFEV_UPDATE, device::ifname, interface::l3_dev, list_del_init(), list_empty(), list_first_entry, interface::name, pending, run_cmd(), and interface::updated.
Referenced by interface_queue_event(), and task_complete().
interface_dequeue_event()
static void interface_dequeue_event (struct interface * iface) static
Definition at line 183 of file interface-event.c.
{
    if (iface == current)
        current = NULL;
    if (!list_empty(&iface->hotplug_list))
        list_del_init(&iface->hotplug_list);
}
References current, interface::hotplug_list, list_del_init(), and list_empty().
Referenced by interface_event_cb().
interface_event_cb()
static void interface_event_cb (struct interface_user * dep, struct interface * iface, enum interface_event ev) static
Definition at line 192 of file interface-event.c.
{
    switch (ev) {
        case IFEV_LINK_UP:
        case IFEV_UP:
        case IFEV_UP_FAILED:
        case IFEV_UPDATE:
        case IFEV_DOWN:
            interface_queue_event(iface, ev);
            break;
        case IFEV_FREE:
            interface_dequeue_event(iface);
            break;
        default:
            break;
    }
}
References IFEV_DOWN, IFEV_FREE, IFEV_LINK_UP, IFEV_UP, IFEV_UP_FAILED, IFEV_UPDATE, interface_dequeue_event(), and interface_queue_event().
interface_event_init()
static void __init interface_event_init (void) static
Definition at line 215 of file interface-event.c.
{
    interface_add_user(&event_user, NULL);
}
References event_user, and interface_add_user().
interface_queue_event()
static void interface_queue_event (struct interface * iface, enum interface_event ev) static
Definition at line 122 of file interface-event.c.
{
    D(SYSTEM, "Queue hotplug handler for interface '%s', event '%s'",
            iface->name, eventnames[ev]);
    if (ev == IFEV_UP || ev == IFEV_DOWN)
        netifd_ubus_interface_event(iface, ev == IFEV_UP);
    netifd_ubus_interface_notify(iface, ev != IFEV_DOWN);
    /* no hotplug.d calls for link up */
    if (ev == IFEV_LINK_UP)
        return;
    if (current == iface) {
        /* an event for iface is being processed */
        if (!list_empty(&iface->hotplug_list)) {
            /* an additional event for iface is pending   */
            /* overwrite pending event if it differs from */
            /* an update                                  */
            if (ev != IFEV_UPDATE)
                iface->hotplug_ev = ev;
        }
        else {
            /* no additional event for iface is pending */
            if (ev != current_ev || ev == IFEV_UPDATE) {
                /* only add the interface to the pending list if
                 * the event is different from the one being
                 * handled or if it is an update */
                iface->hotplug_ev = ev;
                /* Handle hotplug calls FIFO */
                list_add_tail(&iface->hotplug_list, &pending);
            }
        }
    }
    else {
        /* currently not handling an event or handling an event
         * for another interface */
        if (!list_empty(&iface->hotplug_list)) {
            /* an event for iface is pending */
            if (!(iface->hotplug_ev == IFEV_UP &&
                ev == IFEV_UPDATE)) {
                /* overwrite pending event, unless the incoming
                 * event is an ifupdate while the pending one
                 * is an ifup */
                iface->hotplug_ev = ev;
            }
        }
        else {
            /* an event for the interface is not yet pending,
             * queue it */
            iface->hotplug_ev = ev;
            /* Handle hotplug calls FIFO */
            list_add_tail(&iface->hotplug_list, &pending);
        }
    }
    if (!task.pending && !current)
        call_hotplug();
}
References call_hotplug(), current, current_ev, D, eventnames, interface::hotplug_ev, interface::hotplug_list, IFEV_DOWN, IFEV_LINK_UP, IFEV_UP, IFEV_UPDATE, list_add_tail(), list_empty(), interface::name, netifd_ubus_interface_event(), netifd_ubus_interface_notify(), pending, uloop_process::pending, and task.
Referenced by interface_event_cb().
run_cmd()
static void run_cmd (const char * ifname, const char * device, enum interface_event event, enum interface_update_flags updated) static
Definition at line 45 of file interface-event.c.
{
    char *argv[3];
    int pid;
    pid = fork();
    if (pid < 0) {
        task_complete(NULL, -1);
        return;
    }
    if (pid > 0) {
        task.pid = pid;
        uloop_process_add(&task);
        return;
    }
    setenv("ACTION", eventnames[event], 1);
    setenv("INTERFACE", ifname, 1);
    if (device)
        setenv("DEVICE", device, 1);
    if (event == IFEV_UPDATE) {
        if (updated & IUF_ADDRESS)
            setenv("IFUPDATE_ADDRESSES", "1", 1);
        if (updated & IUF_ROUTE)
            setenv("IFUPDATE_ROUTES", "1", 1);
        if (updated & IUF_PREFIX)
            setenv("IFUPDATE_PREFIXES", "1", 1);
        if (updated & IUF_DATA)
            setenv("IFUPDATE_DATA", "1", 1);
    }
    argv[0] = hotplug_cmd_path;
    argv[1] = "iface";
    argv[2] = NULL;
    execvp(argv[0], argv);
    exit(127);
}
References eventnames, hotplug_cmd_path, IFEV_UPDATE, ifname, IUF_ADDRESS, IUF_DATA, IUF_PREFIX, IUF_ROUTE, uloop_process::pid, task, task_complete(), and uloop_process_add().
Referenced by call_hotplug().
task_complete()
static void task_complete (struct uloop_process * proc, int ret) static
Definition at line 106 of file interface-event.c.
{
    if (current)
        D(SYSTEM, "Complete hotplug handler for interface '%s'", current->name);
    current = NULL;
    call_hotplug();
}
References call_hotplug(), current, D, and interface::name.
Referenced by run_cmd().
Variable Documentation
current
struct interface* current static
Definition at line 25 of file interface-event.c.
Referenced by call_hotplug(), interface_dequeue_event(), interface_prefix_assign(), interface_queue_event(), and task_complete().
current_ev
enum interface_event current_ev static
Definition at line 26 of file interface-event.c.
Referenced by call_hotplug(), and interface_queue_event().
event_user
struct interface_user event_user static
Initial value:
= {
    .cb = interface_event_cb
}
Definition at line 211 of file interface-event.c.
{
    .cb = interface_event_cb
};
Referenced by interface_event_init().
eventnames
const char* const eventnames[] static
Initial value:
= {
    [IFEV_DOWN] = "ifdown",
    [IFEV_UP] = "ifup",
    [IFEV_UP_FAILED] = "ifup-failed",
    [IFEV_UPDATE] = "ifupdate",
    [IFEV_FREE] = "free",
    [IFEV_RELOAD] = "reload",
    [IFEV_LINK_UP] = "iflink",
    [IFEV_CREATE] = "create",
}
Definition at line 33 of file interface-event.c.
{
    [IFEV_DOWN] = "ifdown",
    [IFEV_UP] = "ifup",
    [IFEV_UP_FAILED] = "ifup-failed",
    [IFEV_UPDATE] = "ifupdate",
    [IFEV_FREE] = "free",
    [IFEV_RELOAD] = "reload",
    [IFEV_LINK_UP] = "iflink",
    [IFEV_CREATE] = "create",
};
Referenced by call_hotplug(), interface_queue_event(), and run_cmd().
hotplug_cmd_path
char* hotplug_cmd_path = DEFAULT_HOTPLUG_PATH
Definition at line 24 of file interface-event.c.
Referenced by main(), and run_cmd().
pending
struct list_head pending = LIST_HEAD_INIT(pending) static
Definition at line 27 of file interface-event.c.
Referenced by call_hotplug(), cb_finish_event(), error_handler(), interface_queue_event(), system_if_clear_entries(), ubus_find_notify_id(), ubus_process_pending_msg(), and ubus_queue_msg().
task
struct uloop_process task static
Initial value:
= {
    .cb = task_complete,
}
Definition at line 30 of file interface-event.c.
{
    .cb = task_complete,
};
Referenced by interface_queue_event(), proto_shell_task_finish(), run_cmd(), runqueue_process_cancel_cb(), and runqueue_process_kill_cb().