zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/libubox/tests/test-b64.c File Reference
test-b64.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "utils.h"
Macros
#define BUF_LEN 255
Functions
static void test_b64_encode (const char *src)
static void test_b64_decode (const char *src)
int main ()
Macro Definition Documentation
BUF_LEN
#define BUF_LEN 255
Definition at line 7 of file test-b64.c.
Referenced by test_b64_decode(), and test_b64_encode().
Function Documentation
main()
int main ()
Definition at line 25 of file test-b64.c.
{
    test_b64_encode("");
    test_b64_encode("f");
    test_b64_encode("fo");
    test_b64_encode("foo");
    test_b64_encode("foob");
    test_b64_encode("fooba");
    test_b64_encode("foobar");
    test_b64_decode("");
    test_b64_decode("Zg==");
    test_b64_decode("Zm8=");
    test_b64_decode("Zm9v");
    test_b64_decode("Zm9vYg==");
    test_b64_decode("Zm9vYmE=");
    test_b64_decode("Zm9vYmFy");
    return 0;
}
References test_b64_decode(), and test_b64_encode().
test_b64_decode()
static void test_b64_decode (const char * src) static
Definition at line 17 of file test-b64.c.
{
    char *dst = malloc(BUF_LEN+1);
    int r = b64_decode(src, dst, BUF_LEN);
    fprintf(stdout, "%d %s\n", r, dst);
    free(dst);
}
References b64_decode(), BUF_LEN, and r.
Referenced by main().
test_b64_encode()
static void test_b64_encode (const char * src) static
Definition at line 9 of file test-b64.c.
{
    char *dst = malloc(BUF_LEN+1);
    int r = b64_encode(src, strlen(src), dst, BUF_LEN);
    fprintf(stdout, "%d %s\n", r, dst);
    free(dst);
}
References b64_encode(), BUF_LEN, and r.
Referenced by main().