zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/ubus/libubus-obj.c File Reference
libubus-obj.c File Reference
#include <unistd.h>
#include "libubus.h"
#include "libubus-internal.h"
Functions
static void ubus_process_unsubscribe (struct ubus_context *ctx, struct ubus_msghdr *hdr, struct ubus_object *obj, struct blob_attr **attrbuf, int fd)
static void ubus_process_notify (struct ubus_context *ctx, struct ubus_msghdr *hdr, struct ubus_object *obj, struct blob_attr **attrbuf, int fd)
static void ubus_process_invoke (struct ubus_context *ctx, struct ubus_msghdr *hdr, struct ubus_object *obj, struct blob_attr **attrbuf, int fd)
void __hidden ubus_process_obj_msg (struct ubus_context *ctx, struct ubus_msghdr_buf *buf, int fd)
static void ubus_add_object_cb (struct ubus_request *req, int type, struct blob_attr *msg)
static void ubus_push_method_data (const struct ubus_method *m)
static bool ubus_push_object_type (const struct ubus_object_type *type)
int ubus_add_object (struct ubus_context *ctx, struct ubus_object *obj)
static void ubus_remove_object_cb (struct ubus_request *req, int type, struct blob_attr *msg)
int ubus_remove_object (struct ubus_context *ctx, struct ubus_object *obj)
Function Documentation
ubus_add_object()
int ubus_add_object (struct ubus_context * ctx, struct ubus_object * obj)
Definition at line 209 of file libubus-obj.c.
{
    struct ubus_request req;
    int ret;
    blob_buf_init(&b, 0);
    if (obj->name && obj->type) {
        blob_put_string(&b, UBUS_ATTR_OBJPATH, obj->name);
        if (obj->type->id)
            blob_put_int32(&b, UBUS_ATTR_OBJTYPE, obj->type->id);
        else if (!ubus_push_object_type(obj->type))
            return UBUS_STATUS_INVALID_ARGUMENT;
    }
    if (ubus_start_request(ctx, &req, b.head, UBUS_MSG_ADD_OBJECT, 0) < 0)
        return UBUS_STATUS_INVALID_ARGUMENT;
    req.raw_data_cb = ubus_add_object_cb;
    req.priv = obj;
    ret = ubus_complete_request(ctx, &req, 0);
    if (ret)
        return ret;
    if (!obj->id)
        return UBUS_STATUS_NO_DATA;
    return 0;
}
References b, blob_buf_init(), blob_put_int32, blob_put_string(), ctx, blob_buf::head, ubus_object::id, ubus_object_type::id, ubus_object::name, ubus_request::priv, ubus_request::raw_data_cb, ubus_object::type, ubus_add_object_cb(), UBUS_ATTR_OBJPATH, UBUS_ATTR_OBJTYPE, ubus_complete_request(), UBUS_MSG_ADD_OBJECT, ubus_push_object_type(), ubus_start_request(), UBUS_STATUS_INVALID_ARGUMENT, and UBUS_STATUS_NO_DATA.
Referenced by add_subsystem(), client_main(), main(), netifd_add_object(), netifd_ubus_add_interface(), rpc_file_api_init(), rpc_iwinfo_api_init(), rpc_plugin_register_exec(), rpc_rc_api_init(), rpc_session_api_init(), rpc_sys_api_init(), rpc_uci_api_init(), rpc_ucode_script_register(), server_main(), ubus_connect_handler(), ubus_init_service(), ubus_init_system(), ubus_lua_add(), ubus_refresh_state(), ubus_register_event_handler(), and ubus_register_subscriber().
ubus_add_object_cb()
static void ubus_add_object_cb (struct ubus_request * req, int type, struct blob_attr * msg) static
Definition at line 160 of file libubus-obj.c.
{
    struct ubus_object *obj = req->priv;
    struct blob_attr **attrbuf = ubus_parse_msg(msg, blob_raw_len(msg));
    if (!attrbuf[UBUS_ATTR_OBJID])
        return;
    obj->id = blob_get_u32(attrbuf[UBUS_ATTR_OBJID]);
    if (attrbuf[UBUS_ATTR_OBJTYPE])
        obj->type->id = blob_get_u32(attrbuf[UBUS_ATTR_OBJTYPE]);
    obj->avl.key = &obj->id;
    avl_insert(&req->ctx->objects, &obj->avl);
}
References attrbuf, ubus_object::avl, avl_insert(), blob_get_u32(), blob_raw_len(), ubus_request::ctx, ubus_object::id, ubus_object_type::id, avl_node::key, ubus_context::objects, ubus_request::priv, ubus_object::type, UBUS_ATTR_OBJID, UBUS_ATTR_OBJTYPE, and ubus_parse_msg().
Referenced by ubus_add_object().
ubus_process_invoke()
static void ubus_process_invoke (struct ubus_context * ctx, struct ubus_msghdr * hdr, struct ubus_object * obj, struct blob_attr ** attrbuf, int fd) static
Definition at line 53 of file libubus-obj.c.
{
    struct ubus_request_data req = {
        .fd = -1,
        .req_fd = fd,
    };
    int method;
    int ret;
    bool no_reply = false;
    if (!obj) {
        ret = UBUS_STATUS_NOT_FOUND;
        goto send;
    }
    if (!attrbuf[UBUS_ATTR_METHOD]) {
        ret = UBUS_STATUS_INVALID_ARGUMENT;
        goto send;
    }
    if (attrbuf[UBUS_ATTR_NO_REPLY])
        no_reply = blob_get_int8(attrbuf[UBUS_ATTR_NO_REPLY]);
    req.peer = hdr->peer;
    req.seq = hdr->seq;
    req.object = obj->id;
    if (attrbuf[UBUS_ATTR_USER] && attrbuf[UBUS_ATTR_GROUP]) {
        req.acl.user = blobmsg_get_string(attrbuf[UBUS_ATTR_USER]);
        req.acl.group = blobmsg_get_string(attrbuf[UBUS_ATTR_GROUP]);
        req.acl.object = obj->name;
    }
    for (method = 0; method < obj->n_methods; method++)
        if (!obj->methods[method].name ||
            !strcmp(obj->methods[method].name,
                    blob_data(attrbuf[UBUS_ATTR_METHOD])))
            goto found;
    /* not found */
    ret = UBUS_STATUS_METHOD_NOT_FOUND;
    goto send;
found:
    if (!attrbuf[UBUS_ATTR_DATA]) {
        ret = UBUS_STATUS_INVALID_ARGUMENT;
        goto send;
    }
    ret = obj->methods[method].handler(ctx, obj, &req,
                       blob_data(attrbuf[UBUS_ATTR_METHOD]),
                       attrbuf[UBUS_ATTR_DATA]);
    if (req.req_fd >= 0)
        close(req.req_fd);
    if (req.deferred || no_reply)
        return;
send:
    ubus_complete_deferred_request(ctx, &req, ret);
}
References ubus_request_data::acl, attrbuf, blob_data(), blob_get_int8(), blobmsg_get_string(), ctx, ubus_request_data::deferred, ubus_request_data::fd, ubus_acl_key::group, ubus_method::handler, ubus_object::id, ubus_object::methods, ubus_object::n_methods, ubus_method::name, ubus_object::name, ubus_acl_key::object, ubus_request_data::object, ubus_msghdr::peer, ubus_request_data::peer, ubus_request_data::req_fd, ubus_msghdr::seq, ubus_request_data::seq, UBUS_ATTR_DATA, UBUS_ATTR_GROUP, UBUS_ATTR_METHOD, UBUS_ATTR_NO_REPLY, UBUS_ATTR_USER, ubus_complete_deferred_request(), UBUS_STATUS_INVALID_ARGUMENT, UBUS_STATUS_METHOD_NOT_FOUND, UBUS_STATUS_NOT_FOUND, and ubus_acl_key::user.
Referenced by ubus_process_obj_msg().
ubus_process_notify()
static void ubus_process_notify (struct ubus_context * ctx, struct ubus_msghdr * hdr, struct ubus_object * obj, struct blob_attr ** attrbuf, int fd) static
Definition at line 39 of file libubus-obj.c.
{
    if (!obj || !attrbuf[UBUS_ATTR_ACTIVE])
        return;
    obj->has_subscribers = blob_get_u8(attrbuf[UBUS_ATTR_ACTIVE]);
    if (obj->subscribe_cb)
        obj->subscribe_cb(ctx, obj);
    if (fd >= 0)
        close(fd);
}
References attrbuf, blob_get_u8(), ctx, ubus_object::has_subscribers, ubus_subscriber::obj, ubus_object::subscribe_cb, and UBUS_ATTR_ACTIVE.
Referenced by ubus_process_obj_msg().
ubus_process_obj_msg()
void __hidden ubus_process_obj_msg (struct ubus_context * ctx, struct ubus_msghdr_buf * buf, int fd)
Definition at line 115 of file libubus-obj.c.
{
    void (*cb)(struct ubus_context *, struct ubus_msghdr *,
           struct ubus_object *, struct blob_attr **, int fd);
    struct ubus_msghdr *hdr = &buf->hdr;
    struct blob_attr **attrbuf;
    struct ubus_object *obj;
    uint32_t objid;
    void *prev_data = NULL;
    attrbuf = ubus_parse_msg(buf->data, blob_raw_len(buf->data));
    if (!attrbuf[UBUS_ATTR_OBJID])
        return;
    objid = blob_get_u32(attrbuf[UBUS_ATTR_OBJID]);
    obj = avl_find_element(&ctx->objects, &objid, obj, avl);
    switch (hdr->type) {
    case UBUS_MSG_INVOKE:
        cb = ubus_process_invoke;
        break;
    case UBUS_MSG_UNSUBSCRIBE:
        cb = ubus_process_unsubscribe;
        break;
    case UBUS_MSG_NOTIFY:
        cb = ubus_process_notify;
        break;
    default:
        return;
    }
    if (buf == &ctx->msgbuf) {
        prev_data = buf->data;
        buf->data = NULL;
    }
    cb(ctx, hdr, obj, attrbuf, fd);
    if (prev_data) {
        if (buf->data)
            free(prev_data);
        else
            buf->data = prev_data;
    }
}
References attrbuf, ubus_object::avl, avl_find_element, blob_get_u32(), blob_raw_len(), buf, ctx, ubus_context::msgbuf, ubus_context::objects, ubus_msghdr::type, UBUS_ATTR_OBJID, UBUS_MSG_INVOKE, UBUS_MSG_NOTIFY, UBUS_MSG_UNSUBSCRIBE, ubus_parse_msg(), ubus_process_invoke(), ubus_process_notify(), and ubus_process_unsubscribe().
Referenced by ubus_process_msg().
ubus_process_unsubscribe()
static void ubus_process_unsubscribe (struct ubus_context * ctx, struct ubus_msghdr * hdr, struct ubus_object * obj, struct blob_attr ** attrbuf, int fd) static
Definition at line 19 of file libubus-obj.c.
{
    struct ubus_subscriber *s;
    if (!obj || !attrbuf[UBUS_ATTR_TARGET])
        return;
    if (obj->methods != &watch_method)
        return;
    s = container_of(obj, struct ubus_subscriber, obj);
    if (s->remove_cb)
        s->remove_cb(ctx, s, blob_get_u32(attrbuf[UBUS_ATTR_TARGET]));
    if (fd >= 0)
        close(fd);
}
References attrbuf, blob_get_u32(), container_of, ctx, ubus_object::methods, ubus_subscriber::obj, ubus_subscriber::remove_cb, UBUS_ATTR_TARGET, and watch_method.
Referenced by ubus_process_obj_msg().
ubus_push_method_data()
static void ubus_push_method_data (const struct ubus_method * m) static
Definition at line 177 of file libubus-obj.c.
{
    void *mtbl;
    int i;
    mtbl = blobmsg_open_table(&b, m->name);
    for (i = 0; i < m->n_policy; i++) {
        if (m->mask && !(m->mask & (1 << i)))
            continue;
        blobmsg_add_u32(&b, m->policy[i].name, m->policy[i].type);
    }
    blobmsg_close_table(&b, mtbl);
}
References b, blobmsg_add_u32(), blobmsg_close_table(), blobmsg_open_table(), ubus_method::mask, ubus_method::n_policy, blobmsg_policy::name, ubus_method::name, ubus_method::policy, and blobmsg_policy::type.
Referenced by ubus_push_object_type().
ubus_push_object_type()
static bool ubus_push_object_type (const struct ubus_object_type * type) static
Definition at line 194 of file libubus-obj.c.
{
    void *s;
    int i;
    s = blob_nest_start(&b, UBUS_ATTR_SIGNATURE);
    for (i = 0; i < type->n_methods; i++)
        ubus_push_method_data(&type->methods[i]);
    blob_nest_end(&b, s);
    return true;
}
References b, blob_nest_end(), blob_nest_start(), type, UBUS_ATTR_SIGNATURE, and ubus_push_method_data().
Referenced by ubus_add_object().
ubus_remove_object()
int ubus_remove_object (struct ubus_context * ctx, struct ubus_object * obj)
Definition at line 256 of file libubus-obj.c.
{
    struct ubus_request req;
    int ret;
    blob_buf_init(&b, 0);
    blob_put_int32(&b, UBUS_ATTR_OBJID, obj->id);
    if (ubus_start_request(ctx, &req, b.head, UBUS_MSG_REMOVE_OBJECT, 0) < 0)
        return UBUS_STATUS_INVALID_ARGUMENT;
    req.raw_data_cb = ubus_remove_object_cb;
    req.priv = obj;
    ret = ubus_complete_request(ctx, &req, 0);
    if (ret)
        return ret;
    if (obj->id)
        return UBUS_STATUS_NO_DATA;
    return 0;
}
References b, blob_buf_init(), blob_put_int32, ctx, blob_buf::head, ubus_object::id, ubus_request::priv, ubus_request::raw_data_cb, UBUS_ATTR_OBJID, ubus_complete_request(), UBUS_MSG_REMOVE_OBJECT, ubus_remove_object_cb(), ubus_start_request(), UBUS_STATUS_INVALID_ARGUMENT, and UBUS_STATUS_NO_DATA.
Referenced by netifd_ubus_remove_interface(), remove_subsystem(), ubus_unregister_event_handler(), ubus_unregister_subscriber(), and ustp_ubus_exit().
ubus_remove_object_cb()
static void ubus_remove_object_cb (struct ubus_request * req, int type, struct blob_attr * msg) static
Definition at line 240 of file libubus-obj.c.
{
    struct ubus_object *obj = req->priv;
    struct blob_attr **attrbuf = ubus_parse_msg(msg, blob_raw_len(msg));
    if (!attrbuf[UBUS_ATTR_OBJID])
        return;
    avl_delete(&req->ctx->objects, &obj->avl);
    obj->id = 0;
    if (attrbuf[UBUS_ATTR_OBJTYPE] && obj->type)
        obj->type->id = 0;
}
References attrbuf, ubus_object::avl, avl_delete(), blob_raw_len(), ubus_request::ctx, ubus_object::id, ubus_object_type::id, ubus_context::objects, ubus_request::priv, ubus_object::type, UBUS_ATTR_OBJID, UBUS_ATTR_OBJTYPE, and ubus_parse_msg().
Referenced by ubus_remove_object().