zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/netifd/interface.c File Reference
interface.c File Reference
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <sys/types.h>
#include <sys/wait.h>
#include "netifd.h"
#include "device.h"
#include "interface.h"
#include "interface-ip.h"
#include "proto.h"
#include "ubus.h"
#include "config.h"
#include "system.h"
#include "wireless.h"
Macros
#define FIELD_CHANGED_STR(field)
#define UPDATE(field, __var)
Enumerations
enum {
IFACE_ATTR_DEVICE , IFACE_ATTR_IFNAME , IFACE_ATTR_PROTO , IFACE_ATTR_AUTO ,
IFACE_ATTR_ZONE , IFACE_ATTR_JAIL , IFACE_ATTR_JAIL_DEVICE , IFACE_ATTR_JAIL_IFNAME ,
IFACE_ATTR_HOST_DEVICE , IFACE_ATTR_DEFAULTROUTE , IFACE_ATTR_PEERDNS , IFACE_ATTR_DNS ,
IFACE_ATTR_DNS_SEARCH , IFACE_ATTR_DNS_METRIC , IFACE_ATTR_RENEW , IFACE_ATTR_METRIC ,
IFACE_ATTR_INTERFACE , IFACE_ATTR_IP6ASSIGN , IFACE_ATTR_IP6HINT , IFACE_ATTR_IP4TABLE ,
IFACE_ATTR_IP6TABLE , IFACE_ATTR_IP6CLASS , IFACE_ATTR_DELEGATE , IFACE_ATTR_IP6IFACEID ,
IFACE_ATTR_FORCE_LINK , IFACE_ATTR_IP6WEIGHT , IFACE_ATTR_MAX
}
Functions
static LIST_HEAD (iface_all_users)
static void interface_set_main_dev (struct interface *iface, struct device *dev)
static void interface_event (struct interface *iface, enum interface_event ev)
static void interface_error_flush (struct interface *iface)
static bool interface_force_link (struct interface *iface)
static void interface_clear_errors (struct interface *iface)
void interface_add_error (struct interface *iface, const char *subsystem, const char *code, const char **data, int n_data)
static void interface_data_del (struct interface *iface, struct interface_data *data)
static void interface_data_flush (struct interface *iface)
int interface_add_data (struct interface *iface, const struct blob_attr *data)
int interface_parse_data (struct interface *iface, const struct blob_attr *attr)
static void interface_flush_state (struct interface *iface)
static void mark_interface_down (struct interface *iface)
static void __set_config_state (struct interface *iface, enum interface_config_state s)
static void __interface_set_down (struct interface *iface, bool force)
static int __interface_set_up (struct interface *iface)
static void interface_check_state (struct interface *iface)
static void interface_set_enabled (struct interface *iface, bool new_state)
static void interface_set_link_state (struct interface *iface, bool new_state)
static void interface_ext_dev_cb (struct device_user *dep, enum device_event ev)
static void interface_main_dev_cb (struct device_user *dep, enum device_event ev)
static void interface_l3_dev_cb (struct device_user *dep, enum device_event ev)
void interface_set_available (struct interface *iface, bool new_state)
void interface_add_user (struct interface_user *dep, struct interface *iface)
void interface_remove_user (struct interface_user *dep)
static void interface_add_assignment_classes (struct interface *iface, struct blob_attr *list)
static void interface_clear_assignment_classes (struct interface *iface)
static void interface_merge_assignment_data (struct interface *old, struct interface *new)
static void interface_alias_cb (struct interface_user *dep, struct interface *iface, enum interface_event ev)
static void interface_set_device_config (struct interface *iface, struct device *dev)
static void interface_claim_device (struct interface *iface)
static void interface_cleanup_state (struct interface *iface)
static void interface_cleanup (struct interface *iface)
static void interface_do_free (struct interface *iface)
static void interface_do_reload (struct interface *iface)
static void interface_handle_config_change (struct interface *iface)
static void interface_proto_event_cb (struct interface_proto_state *state, enum interface_proto_event ev)
void interface_set_proto_state (struct interface *iface, struct interface_proto_state *state)
struct interface * interface_alloc (const char *name, struct blob_attr *config, bool dynamic)
static bool __interface_add (struct interface *iface, struct blob_attr *config, bool alias)
bool interface_add (struct interface *iface, struct blob_attr *config)
bool interface_add_alias (struct interface *iface, struct blob_attr *config)
void interface_set_l3_dev (struct interface *iface, struct device *dev)
static int interface_remove_link (struct interface *iface, struct device *dev, struct blob_attr *vlan)
static int interface_add_link (struct interface *iface, struct device *dev, struct blob_attr *vlan, bool link_ext)
int interface_handle_link (struct interface *iface, const char *name, struct blob_attr *vlan, bool add, bool link_ext)
void interface_set_up (struct interface *iface)
void interface_set_down (struct interface *iface)
int interface_renew (struct interface *iface)
void interface_start_pending (void)
void interface_start_jail (int netns_fd, const char *jail)
void interface_stop_jail (int netns_fd)
static void set_config_state (struct interface *iface, enum interface_config_state s)
void interface_update_start (struct interface *iface, const bool keep_old)
void interface_update_complete (struct interface *iface)
static void interface_replace_dns (struct interface_ip_settings *new, struct interface_ip_settings *old)
static bool interface_device_config_changed (struct interface *if_old, struct interface *if_new)
static void interface_change_config (struct interface *if_old, struct interface *if_new)
static void interface_update (struct vlist_tree *tree, struct vlist_node *node_new, struct vlist_node *node_old)
static void __init interface_init_list (void)
Variables
struct vlist_tree interfaces
static const struct blobmsg_policy iface_attrs [IFACE_ATTR_MAX]
const struct uci_blob_param_list interface_attr_list
Macro Definition Documentation
FIELD_CHANGED_STR
#define FIELD_CHANGED_STR (field)
Value:
        ((!!if_old->field != !!if_new->field) ||        \
         (if_old->field &&                  \
          strcmp(if_old->field, if_new->field) != 0))
Referenced by interface_change_config().
UPDATE
#define UPDATE (field, __var)
Value:
        ({                      \
        bool __changed = (if_old->field != if_new->field);  \
        if_old->field = if_new->field;              \
        __var |= __changed;                 \
    })
Referenced by interface_change_config().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
IFACE_ATTR_DEVICE
IFACE_ATTR_IFNAME
IFACE_ATTR_PROTO
IFACE_ATTR_AUTO
IFACE_ATTR_ZONE
IFACE_ATTR_JAIL
IFACE_ATTR_JAIL_DEVICE
IFACE_ATTR_JAIL_IFNAME
IFACE_ATTR_HOST_DEVICE
IFACE_ATTR_DEFAULTROUTE
IFACE_ATTR_PEERDNS
IFACE_ATTR_DNS
IFACE_ATTR_DNS_SEARCH
IFACE_ATTR_DNS_METRIC
IFACE_ATTR_RENEW
IFACE_ATTR_METRIC
IFACE_ATTR_INTERFACE
IFACE_ATTR_IP6ASSIGN
IFACE_ATTR_IP6HINT
IFACE_ATTR_IP4TABLE
IFACE_ATTR_IP6TABLE
IFACE_ATTR_IP6CLASS
IFACE_ATTR_DELEGATE
IFACE_ATTR_IP6IFACEID
IFACE_ATTR_FORCE_LINK
IFACE_ATTR_IP6WEIGHT
IFACE_ATTR_MAX
Definition at line 33 of file interface.c.
     {
    IFACE_ATTR_DEVICE,
    IFACE_ATTR_IFNAME, /* Backward compatibility */
    IFACE_ATTR_PROTO,
    IFACE_ATTR_AUTO,
    IFACE_ATTR_ZONE,
    IFACE_ATTR_JAIL,
    IFACE_ATTR_JAIL_DEVICE,
    IFACE_ATTR_JAIL_IFNAME,
    IFACE_ATTR_HOST_DEVICE,
    IFACE_ATTR_DEFAULTROUTE,
    IFACE_ATTR_PEERDNS,
    IFACE_ATTR_DNS,
    IFACE_ATTR_DNS_SEARCH,
    IFACE_ATTR_DNS_METRIC,
    IFACE_ATTR_RENEW,
    IFACE_ATTR_METRIC,
    IFACE_ATTR_INTERFACE,
    IFACE_ATTR_IP6ASSIGN,
    IFACE_ATTR_IP6HINT,
    IFACE_ATTR_IP4TABLE,
    IFACE_ATTR_IP6TABLE,
    IFACE_ATTR_IP6CLASS,
    IFACE_ATTR_DELEGATE,
    IFACE_ATTR_IP6IFACEID,
    IFACE_ATTR_FORCE_LINK,
    IFACE_ATTR_IP6WEIGHT,
    IFACE_ATTR_MAX
};
Function Documentation
__interface_add()
static bool __interface_add (struct interface * iface, struct blob_attr * config, bool alias) static
Definition at line 950 of file interface.c.
{
    struct blob_attr *tb[IFACE_ATTR_MAX];
    struct blob_attr *cur;
    char *name = NULL;
    blobmsg_parse(iface_attrs, IFACE_ATTR_MAX, tb,
              blob_data(config), blob_len(config));
    if (alias) {
        if ((cur = tb[IFACE_ATTR_INTERFACE]))
            iface->parent_ifname = blobmsg_data(cur);
        if (!iface->parent_ifname)
            return false;
    } else {
        cur = tb[IFACE_ATTR_DEVICE];
        if (!cur)
            cur = tb[IFACE_ATTR_IFNAME];
        if (cur)
            iface->device = blobmsg_data(cur);
    }
    if (iface->dynamic) {
        name = strdup(iface->name);
        if (!name)
            return false;
    }
    iface->config = config;
    vlist_add(&interfaces, &iface->node, iface->name);
    if (name) {
        iface = vlist_find(&interfaces, name, iface, node);
        free(name);
        /* Don't delete dynamic interface on reload */
        if (iface)
            iface->node.version = -1;
    }
    return true;
}
References blob_data(), blob_len(), blobmsg_data(), blobmsg_parse(), config, interface::config, interface::device, interface::dynamic, IFACE_ATTR_DEVICE, IFACE_ATTR_IFNAME, IFACE_ATTR_INTERFACE, IFACE_ATTR_MAX, iface_attrs, interfaces, interface::name, interface::node, interface::parent_ifname, vlist_node::version, vlist_add(), and vlist_find.
Referenced by interface_add(), and interface_add_alias().
__interface_set_down()
static void __interface_set_down (struct interface * iface, bool force) static
Definition at line 324 of file interface.c.
{
    enum interface_state state = iface->state;
    switch (state) {
    case IFS_UP:
    case IFS_SETUP:
        iface->state = IFS_TEARDOWN;
        if (iface->dynamic)
            __set_config_state(iface, IFC_REMOVE);
        if (state == IFS_UP)
            interface_event(iface, IFEV_DOWN);
        interface_proto_event(iface->proto, PROTO_CMD_TEARDOWN, force);
        if (force)
            interface_flush_state(iface);
        break;
    case IFS_DOWN:
        if (iface->main_dev.dev)
            device_release(&iface->main_dev);
        break;
    case IFS_TEARDOWN:
    default:
        break;
    }
}
References __set_config_state(), device_user::dev, device_release(), interface::dynamic, IFC_REMOVE, IFEV_DOWN, IFS_DOWN, IFS_SETUP, IFS_TEARDOWN, IFS_UP, interface_flush_state(), interface::main_dev, interface::proto, PROTO_CMD_TEARDOWN, interface::state, and state.
Referenced by interface_set_available(), interface_set_down(), and set_config_state().
__interface_set_up()
static int __interface_set_up (struct interface * iface) static
Definition at line 353 of file interface.c.
{
    int ret;
    netifd_log_message(L_NOTICE, "Interface '%s' is setting up now\n", iface->name);
    iface->state = IFS_SETUP;
    ret = interface_proto_event(iface->proto, PROTO_CMD_SETUP, false);
    if (ret)
        mark_interface_down(iface);
    return ret;
}
References IFS_SETUP, L_NOTICE, mark_interface_down(), interface::name, netifd_log_message(), interface::proto, PROTO_CMD_SETUP, and interface::state.
Referenced by interface_check_state(), and interface_set_up().
__set_config_state()
static void __set_config_state (struct interface * iface, enum interface_config_state s) inline static
Definition at line 318 of file interface.c.
{
    iface->config_state = s;
}
References interface::config_state.
Referenced by __interface_set_down(), interface_check_state(), and set_config_state().
interface_add()
bool interface_add (struct interface * iface, struct blob_attr * config)
Definition at line 996 of file interface.c.
{
    return __interface_add(iface, config, false);
}
References __interface_add(), and config.
Referenced by config_parse_interface(), and netifd_add_dynamic().
interface_add_alias()
bool interface_add_alias (struct interface * iface, struct blob_attr * config)
Definition at line 1002 of file interface.c.
{
    if (iface->proto_handler->flags & PROTO_FLAG_NODEV)
        return false;
    return __interface_add(iface, config, true);
}
References __interface_add(), config, proto_handler::flags, PROTO_FLAG_NODEV, and interface::proto_handler.
Referenced by config_parse_interface().
interface_add_assignment_classes()
static void interface_add_assignment_classes (struct interface * iface, struct blob_attr * list) static
Definition at line 522 of file interface.c.
{
    struct blob_attr *cur;
    size_t rem;
    blobmsg_for_each_attr(cur, list, rem) {
        if (blobmsg_type(cur) != BLOBMSG_TYPE_STRING)
            continue;
        if (!blobmsg_check_attr(cur, false))
            continue;
        struct interface_assignment_class *c = malloc(sizeof(*c) + blobmsg_data_len(cur));
        memcpy(c->name, blobmsg_data(cur), blobmsg_data_len(cur));
        list_add(&c->head, &iface->assignment_classes);
    }
}
References interface::assignment_classes, blobmsg_check_attr(), blobmsg_data(), blobmsg_data_len(), blobmsg_for_each_attr, BLOBMSG_TYPE_STRING, interface_assignment_class::head, list_add(), and interface_assignment_class::name.
Referenced by interface_alloc().
interface_add_data()
int interface_add_data (struct interface * iface, const struct blob_attr * data)
Definition at line 205 of file interface.c.
{
    struct interface_data *n, *o;
    if (!blobmsg_check_attr(data, true))
        return UBUS_STATUS_INVALID_ARGUMENT;
    const char *name = blobmsg_name(data);
    unsigned len = blob_pad_len(data);
    o = avl_find_element(&iface->data, name, o, node);
    if (o) {
        if (blob_pad_len(o->data) == len && !memcmp(o->data, data, len))
            return 0;
        interface_data_del(iface, o);
    }
    n = calloc(1, sizeof(*n) + len);
    if (!n)
        return UBUS_STATUS_UNKNOWN_ERROR;
    memcpy(n->data, data, len);
    n->node.key = blobmsg_name(n->data);
    avl_insert(&iface->data, &n->node);
    iface->updated |= IUF_DATA;
    return 0;
}
References avl_find_element, avl_insert(), blob_pad_len(), blobmsg_check_attr(), blobmsg_name(), interface::data, interface_data::data, interface_data_del(), IUF_DATA, avl_node::key, interface_data::node, UBUS_STATUS_INVALID_ARGUMENT, UBUS_STATUS_UNKNOWN_ERROR, and interface::updated.
Referenced by interface_parse_data(), and proto_shell_parse_data().
interface_add_error()
void interface_add_error (struct interface * iface, const char * subsystem, const char * code, const char ** data, int n_data)
Definition at line 135 of file interface.c.
{
    struct interface_error *error;
    int i, len = 0;
    int *datalen = NULL;
    char *dest, *d_subsys, *d_code;
    /* if the configured protocol handler has the last error support capability,
           errors should only be added if the running protocol handler matches the
           configured one */
    if (iface->proto &&
        (iface->proto->handler->flags & PROTO_FLAG_LASTERROR) &&
        (iface->proto->handler->name != iface->proto_handler->name))
        return;
    if (n_data) {
        len = n_data * sizeof(char *);
        datalen = alloca(len);
        for (i = 0; i < n_data; i++) {
            datalen[i] = strlen(data[i]) + 1;
            len += datalen[i];
        }
    }
    error = calloc_a(sizeof(*error) + sizeof(char *) + len,
        &d_subsys, subsystem ? strlen(subsystem) + 1 : 0,
        &d_code, code ? strlen(code) + 1 : 0);
    if (!error)
        return;
    /* Only keep the last flagged error, prevent this list grows unlimitted in case the
       protocol can't be established (e.g auth failure) */
    if (iface->proto_handler->flags & PROTO_FLAG_LASTERROR)
        interface_error_flush(iface);
    list_add_tail(&error->list, &iface->errors);
    dest = (char *) &error->data[n_data + 1];
    for (i = 0; i < n_data; i++) {
        error->data[i] = dest;
        memcpy(dest, data[i], datalen[i]);
        dest += datalen[i];
    }
    error->data[n_data] = NULL;
    if (subsystem)
        error->subsystem = strcpy(d_subsys, subsystem);
    if (code)
        error->code = strcpy(d_code, code);
}
References calloc_a, interface_error::code, interface_error::data, interface::errors, proto_handler::flags, interface_proto_state::handler, interface_error_flush(), interface_error::list, list_add_tail(), proto_handler::name, interface::proto, PROTO_FLAG_LASTERROR, interface::proto_handler, and interface_error::subsystem.
Referenced by interface_set_up(), parse_gateway_option(), parse_static_address_option(), proto_apply_static_ip_settings(), proto_attach_interface(), and proto_shell_notify_error().
interface_add_link()
static int interface_add_link (struct interface * iface, struct device * dev, struct blob_attr * vlan, bool link_ext) static
Definition at line 1081 of file interface.c.
{
    struct device *mdev = iface->main_dev.dev;
    if (mdev == dev) {
        if (iface->state != IFS_UP) {
            interface_set_available(iface, false);
            if (dev->present)
                interface_set_available(iface, true);
        }
        return 0;
    }
    if (iface->main_dev.hotplug)
        interface_set_main_dev(iface, NULL);
    if (mdev) {
        if (mdev->hotplug_ops)
            return mdev->hotplug_ops->add(mdev, dev, vlan);
        else
            return UBUS_STATUS_NOT_SUPPORTED;
    }
    if (link_ext)
        device_add_user(&iface->ext_dev, dev);
    interface_set_main_dev(iface, dev);
    iface->main_dev.hotplug = true;
    return 0;
}
References device_hotplug_ops::add, device_user::dev, device_add_user(), interface::ext_dev, device_user::hotplug, device::hotplug_ops, IFS_UP, interface_set_available(), interface_set_main_dev(), interface::main_dev, device::present, interface::state, and UBUS_STATUS_NOT_SUPPORTED.
Referenced by interface_handle_link().
interface_add_user()
void interface_add_user (struct interface_user * dep, struct interface * iface)
Definition at line 501 of file interface.c.
{
    if (!iface) {
        list_add(&dep->list, &iface_all_users);
        return;
    }
    dep->iface = iface;
    list_add(&dep->list, &iface->users);
    if (iface->state == IFS_UP)
        dep->cb(dep, iface, IFEV_UP);
}
References interface_user::cb, interface_user::iface, IFEV_UP, IFS_UP, interface_user::list, list_add(), interface::state, and interface::users.
Referenced by generic_interface_cb(), interface_claim_device(), interface_event_init(), iprule_init_list(), proto_shell_add_host_dependency(), proto_shell_if_down_cb(), proto_shell_update_host_dep(), and register_interfaces().
interface_alias_cb()
static void interface_alias_cb (struct interface_user * dep, struct interface * iface, enum interface_event ev) static
Definition at line 601 of file interface.c.
{
    struct interface *alias = container_of(dep, struct interface, parent_iface);
    struct device *dev = iface->l3_dev.dev;
    switch (ev) {
    case IFEV_UP:
        if (!dev)
            return;
        interface_set_main_dev(alias, dev);
        interface_set_available(alias, true);
        break;
    case IFEV_DOWN:
    case IFEV_UP_FAILED:
        interface_set_available(alias, false);
        interface_set_main_dev(alias, NULL);
        break;
    case IFEV_FREE:
        interface_remove_user(dep);
        break;
    default:
        break;
    }
}
References container_of, device_user::dev, IFEV_DOWN, IFEV_FREE, IFEV_UP, IFEV_UP_FAILED, interface_remove_user(), interface_set_available(), interface_set_main_dev(), interface::l3_dev, and interface::parent_iface.
Referenced by interface_claim_device().
interface_alloc()
struct interface * interface_alloc (const char * name, struct blob_attr * config, bool dynamic)
Definition at line 818 of file interface.c.
{
    struct interface *iface;
    struct blob_attr *tb[IFACE_ATTR_MAX];
    struct blob_attr *cur;
    const char *proto_name = NULL;
    char *iface_name;
    bool force_link = false;
    iface = calloc_a(sizeof(*iface), &iface_name, strlen(name) + 1);
    iface->name = strcpy(iface_name, name);
    INIT_LIST_HEAD(&iface->errors);
    INIT_LIST_HEAD(&iface->users);
    INIT_LIST_HEAD(&iface->hotplug_list);
    INIT_LIST_HEAD(&iface->assignment_classes);
    interface_ip_init(iface);
    avl_init(&iface->data, avl_strcmp, false, NULL);
    iface->config_ip.enabled = false;
    iface->main_dev.cb = interface_main_dev_cb;
    iface->l3_dev.cb = interface_l3_dev_cb;
    iface->ext_dev.cb = interface_ext_dev_cb;
    blobmsg_parse(iface_attrs, IFACE_ATTR_MAX, tb,
              blob_data(config), blob_len(config));
    iface->zone = NULL;
    if ((cur = tb[IFACE_ATTR_ZONE]))
        iface->zone = strdup(blobmsg_get_string(cur));
    if ((cur = tb[IFACE_ATTR_PROTO]))
        proto_name = blobmsg_data(cur);
    proto_attach_interface(iface, proto_name);
    if (iface->proto_handler->flags & PROTO_FLAG_FORCE_LINK_DEFAULT)
        force_link = true;
    iface->autostart = blobmsg_get_bool_default(tb[IFACE_ATTR_AUTO], true);
    iface->renew = blobmsg_get_bool_default(tb[IFACE_ATTR_RENEW], true);
    iface->force_link = blobmsg_get_bool_default(tb[IFACE_ATTR_FORCE_LINK], force_link);
    iface->dynamic = dynamic;
    iface->proto_ip.no_defaultroute =
        !blobmsg_get_bool_default(tb[IFACE_ATTR_DEFAULTROUTE], true);
    iface->proto_ip.no_dns =
        !blobmsg_get_bool_default(tb[IFACE_ATTR_PEERDNS], true);
    if ((cur = tb[IFACE_ATTR_DNS]))
        interface_add_dns_server_list(&iface->config_ip, cur);
    if ((cur = tb[IFACE_ATTR_DNS_SEARCH]))
        interface_add_dns_search_list(&iface->config_ip, cur);
    if ((cur = tb[IFACE_ATTR_DNS_METRIC]))
        iface->dns_metric = blobmsg_get_u32(cur);
    if ((cur = tb[IFACE_ATTR_METRIC]))
        iface->metric = blobmsg_get_u32(cur);
    if ((cur = tb[IFACE_ATTR_IP6ASSIGN]))
        iface->assignment_length = blobmsg_get_u32(cur);
    /* defaults */
    iface->assignment_iface_id_selection = IFID_FIXED;
    iface->assignment_fixed_iface_id = in6addr_any;
    iface->assignment_fixed_iface_id.s6_addr[15] = 1;
    if ((cur = tb[IFACE_ATTR_IP6IFACEID])) {
        const char *ifaceid = blobmsg_data(cur);
        if (!strcmp(ifaceid, "random")) {
            iface->assignment_iface_id_selection = IFID_RANDOM;
        }
        else if (!strcmp(ifaceid, "eui64")) {
            iface->assignment_iface_id_selection = IFID_EUI64;
        }
        else {
            /* we expect an IPv6 address with network id zero here -> fixed iface id
               if we cannot parse -> revert to iface id 1 */
            if (inet_pton(AF_INET6,ifaceid,&iface->assignment_fixed_iface_id) != 1 ||
                    iface->assignment_fixed_iface_id.s6_addr32[0] != 0 ||
                    iface->assignment_fixed_iface_id.s6_addr32[1] != 0) {
                iface->assignment_fixed_iface_id = in6addr_any;
                iface->assignment_fixed_iface_id.s6_addr[15] = 1;
                netifd_log_message(L_WARNING, "Failed to parse ip6ifaceid for interface '%s', \
                            falling back to iface id 1.\n", iface->name);
            }
        }
    }
    iface->assignment_hint = -1;
    if ((cur = tb[IFACE_ATTR_IP6HINT]))
        iface->assignment_hint = strtol(blobmsg_get_string(cur), NULL, 16) &
                ~((1 << (64 - iface->assignment_length)) - 1);
    if ((cur = tb[IFACE_ATTR_IP6CLASS]))
        interface_add_assignment_classes(iface, cur);
    if ((cur = tb[IFACE_ATTR_IP6WEIGHT]))
        iface->assignment_weight = blobmsg_get_u32(cur);
    if ((cur = tb[IFACE_ATTR_IP4TABLE])) {
        if (!system_resolve_rt_table(blobmsg_data(cur), &iface->ip4table))
            D(INTERFACE, "Failed to resolve routing table: %s", (char *) blobmsg_data(cur));
    }
    if ((cur = tb[IFACE_ATTR_IP6TABLE])) {
        if (!system_resolve_rt_table(blobmsg_data(cur), &iface->ip6table))
            D(INTERFACE, "Failed to resolve routing table: %s", (char *) blobmsg_data(cur));
    }
    iface->proto_ip.no_delegation = !blobmsg_get_bool_default(tb[IFACE_ATTR_DELEGATE], true);
    iface->config_autostart = iface->autostart;
    iface->jail = NULL;
    if ((cur = tb[IFACE_ATTR_JAIL])) {
        iface->jail = strdup(blobmsg_get_string(cur));
        iface->autostart = false;
    }
    iface->jail_device = NULL;
    if ((cur = tb[IFACE_ATTR_JAIL_DEVICE]))
        iface->jail_device = strdup(blobmsg_get_string(cur));
    else if ((cur = tb[IFACE_ATTR_JAIL_IFNAME]))
        iface->jail_device = strdup(blobmsg_get_string(cur));
    iface->host_device = NULL;
    if ((cur = tb[IFACE_ATTR_HOST_DEVICE]))
        iface->host_device = strdup(blobmsg_get_string(cur));
    return iface;
}
References interface::assignment_classes, interface::assignment_fixed_iface_id, interface::assignment_hint, interface::assignment_iface_id_selection, interface::assignment_length, interface::assignment_weight, interface::autostart, avl_init(), avl_strcmp(), blob_data(), blob_len(), blobmsg_data(), blobmsg_get_bool_default(), blobmsg_get_string(), blobmsg_get_u32(), blobmsg_parse(), calloc_a, device_user::cb, config, interface::config_autostart, interface::config_ip, D, interface::data, interface::dns_metric, interface::dynamic, interface_ip_settings::enabled, interface::errors, interface::ext_dev, proto_handler::flags, interface::force_link, interface::host_device, interface::hotplug_list, IFACE_ATTR_AUTO, IFACE_ATTR_DEFAULTROUTE, IFACE_ATTR_DELEGATE, IFACE_ATTR_DNS, IFACE_ATTR_DNS_METRIC, IFACE_ATTR_DNS_SEARCH, IFACE_ATTR_FORCE_LINK, IFACE_ATTR_HOST_DEVICE, IFACE_ATTR_IP4TABLE, IFACE_ATTR_IP6ASSIGN, IFACE_ATTR_IP6CLASS, IFACE_ATTR_IP6HINT, IFACE_ATTR_IP6IFACEID, IFACE_ATTR_IP6TABLE, IFACE_ATTR_IP6WEIGHT, IFACE_ATTR_JAIL, IFACE_ATTR_JAIL_DEVICE, IFACE_ATTR_JAIL_IFNAME, IFACE_ATTR_MAX, IFACE_ATTR_METRIC, IFACE_ATTR_PEERDNS, IFACE_ATTR_PROTO, IFACE_ATTR_RENEW, IFACE_ATTR_ZONE, iface_attrs, IFID_EUI64, IFID_FIXED, IFID_RANDOM, INIT_LIST_HEAD(), interface_add_assignment_classes(), interface_add_dns_search_list(), interface_add_dns_server_list(), interface_ext_dev_cb(), interface_ip_init(), interface_l3_dev_cb(), interface_main_dev_cb(), interface::ip4table, interface::ip6table, interface::jail, interface::jail_device, interface::l3_dev, L_WARNING, interface::main_dev, interface::metric, interface::name, netifd_log_message(), interface_ip_settings::no_defaultroute, interface_ip_settings::no_delegation, interface_ip_settings::no_dns, proto_attach_interface(), PROTO_FLAG_FORCE_LINK_DEFAULT, interface::proto_handler, interface::proto_ip, interface::renew, system_resolve_rt_table(), interface::users, and interface::zone.
Referenced by config_parse_interface(), and netifd_add_dynamic().
interface_change_config()
static void interface_change_config (struct interface * if_old, struct interface * if_new) static
Definition at line 1287 of file interface.c.
{
    struct blob_attr *old_config = if_old->config;
    bool reload = false, reload_ip = false, update_prefix_delegation = false;
#define FIELD_CHANGED_STR(field)                    \
        ((!!if_old->field != !!if_new->field) ||        \
         (if_old->field &&                  \
          strcmp(if_old->field, if_new->field) != 0))
    if (FIELD_CHANGED_STR(parent_ifname)) {
        if (if_old->parent_iface.iface)
            interface_remove_user(&if_old->parent_iface);
        reload = true;
    }
    if (!reload && interface_device_config_changed(if_old, if_new))
        reload = true;
    if (FIELD_CHANGED_STR(device) ||
        if_old->proto_handler != if_new->proto_handler)
        reload = true;
    if (!if_old->proto_handler->config_params)
        D(INTERFACE, "No config parameters for interface '%s'",
          if_old->name);
    else if (!uci_blob_check_equal(if_old->config, if_new->config,
                       if_old->proto_handler->config_params))
        reload = true;
#define UPDATE(field, __var) ({                     \
        bool __changed = (if_old->field != if_new->field);  \
        if_old->field = if_new->field;              \
        __var |= __changed;                 \
    })
    if_old->config = if_new->config;
    if (if_old->config_autostart != if_new->config_autostart) {
        if (if_old->config_autostart)
            reload = true;
        if_old->autostart = if_new->config_autostart;
    }
    if_old->device_config = if_new->device_config;
    if_old->config_autostart = if_new->config_autostart;
    if (if_old->jail)
        free(if_old->jail);
    if_old->jail = if_new->jail;
    if (if_old->jail)
        if_old->autostart = false;
    if (if_old->jail_device)
        free(if_old->jail_device);
    if_old->jail_device = if_new->jail_device;
    if (if_old->host_device)
        free(if_old->host_device);
    if_old->host_device = if_new->host_device;
    if_old->device = if_new->device;
    if_old->parent_ifname = if_new->parent_ifname;
    if_old->dynamic = if_new->dynamic;
    if_old->proto_handler = if_new->proto_handler;
    if_old->force_link = if_new->force_link;
    if_old->dns_metric = if_new->dns_metric;
    if (if_old->proto_ip.no_delegation != if_new->proto_ip.no_delegation) {
        if_old->proto_ip.no_delegation = if_new->proto_ip.no_delegation;
        update_prefix_delegation = true;
    }
    if_old->proto_ip.no_dns = if_new->proto_ip.no_dns;
    interface_replace_dns(&if_old->config_ip, &if_new->config_ip);
    UPDATE(metric, reload_ip);
    UPDATE(proto_ip.no_defaultroute, reload_ip);
    UPDATE(ip4table, reload_ip);
    UPDATE(ip6table, reload_ip);
    interface_merge_assignment_data(if_old, if_new);
#undef UPDATE
    if (reload) {
        D(INTERFACE, "Reload interface '%s' because of config changes",
          if_old->name);
        interface_clear_errors(if_old);
        set_config_state(if_old, IFC_RELOAD);
        goto out;
    }
    if (reload_ip) {
        bool config_ip_enabled = if_old->config_ip.enabled;
        bool proto_ip_enabled = if_old->proto_ip.enabled;
        interface_ip_set_enabled(&if_old->config_ip, false);
        interface_ip_set_enabled(&if_old->proto_ip, false);
        interface_ip_set_enabled(&if_old->proto_ip, proto_ip_enabled);
        interface_ip_set_enabled(&if_old->config_ip, config_ip_enabled);
    }
    if (update_prefix_delegation)
        interface_update_prefix_delegation(&if_old->proto_ip);
    interface_write_resolv_conf(if_old->jail);
    if (if_old->main_dev.dev)
        interface_check_state(if_old);
out:
    if_new->config = NULL;
    interface_cleanup(if_new);
    free(old_config);
    free(if_new);
}
References interface::autostart, interface::config, interface::config_autostart, interface::config_ip, proto_handler::config_params, D, device_user::dev, interface::device, interface::device_config, interface::dns_metric, interface::dynamic, interface_ip_settings::enabled, FIELD_CHANGED_STR, interface::force_link, interface::host_device, interface_user::iface, IFC_RELOAD, interface_check_state(), interface_cleanup(), interface_clear_errors(), interface_device_config_changed(), interface_ip_set_enabled(), interface_merge_assignment_data(), interface_remove_user(), interface_replace_dns(), interface_update_prefix_delegation(), interface_write_resolv_conf(), interface::jail, interface::jail_device, interface::main_dev, interface::name, interface_ip_settings::no_delegation, interface_ip_settings::no_dns, interface::parent_iface, interface::parent_ifname, interface::proto_handler, interface::proto_ip, set_config_state(), and UPDATE.
Referenced by interface_update().
interface_check_state()
static void interface_check_state (struct interface * iface) static
Definition at line 368 of file interface.c.
{
    bool link_state = iface->link_state || interface_force_link(iface);
    switch (iface->state) {
    case IFS_UP:
    case IFS_SETUP:
        if (!iface->enabled || !link_state) {
            iface->state = IFS_TEARDOWN;
            if (iface->dynamic)
                __set_config_state(iface, IFC_REMOVE);
            interface_proto_event(iface->proto, PROTO_CMD_TEARDOWN, false);
        }
        break;
    case IFS_DOWN:
        if (!iface->available)
            return;
        if (iface->autostart && iface->enabled && link_state && !config_init)
            __interface_set_up(iface);
        break;
    default:
        break;
    }
}
References __interface_set_up(), __set_config_state(), interface::autostart, interface::available, config_init, interface::dynamic, interface::enabled, IFC_REMOVE, IFS_DOWN, IFS_SETUP, IFS_TEARDOWN, IFS_UP, interface_force_link(), interface::link_state, interface::proto, PROTO_CMD_TEARDOWN, and interface::state.
Referenced by interface_change_config(), interface_set_enabled(), interface_set_link_state(), and interface_set_up().
interface_claim_device()
static void interface_claim_device (struct interface * iface) static
Definition at line 643 of file interface.c.
{
    struct interface *parent;
    struct device *dev = NULL;
    if (iface->parent_iface.iface)
        interface_remove_user(&iface->parent_iface);
    if (iface->parent_ifname) {
        parent = vlist_find(&interfaces, iface->parent_ifname, parent, node);
        iface->parent_iface.cb = interface_alias_cb;
        interface_add_user(&iface->parent_iface, parent);
    } else if (iface->device &&
        !(iface->proto_handler->flags & PROTO_FLAG_NODEV)) {
        dev = device_get(iface->device, true);
        if (!(iface->proto_handler->flags & PROTO_FLAG_NODEV_CONFIG))
            interface_set_device_config(iface, dev);
    } else {
        dev = iface->ext_dev.dev;
    }
    if (dev)
        interface_set_main_dev(iface, dev);
    if (iface->proto_handler->flags & PROTO_FLAG_INIT_AVAILABLE)
        interface_set_available(iface, true);
}
References interface_user::cb, device_user::dev, interface::device, device_get(), interface::ext_dev, proto_handler::flags, interface_user::iface, interface_add_user(), interface_alias_cb(), interface_remove_user(), interface_set_available(), interface_set_device_config(), interface_set_main_dev(), interfaces, device::parent, interface::parent_iface, interface::parent_ifname, PROTO_FLAG_INIT_AVAILABLE, PROTO_FLAG_NODEV, PROTO_FLAG_NODEV_CONFIG, interface::proto_handler, and vlist_find.
Referenced by interface_do_reload(), and interface_update().
interface_cleanup()
static void interface_cleanup (struct interface * iface) static
Definition at line 685 of file interface.c.
{
    struct interface_user *dep, *tmp;
    uloop_timeout_cancel(&iface->remove_timer);
    device_remove_user(&iface->ext_dev);
    if (iface->parent_iface.iface)
        interface_remove_user(&iface->parent_iface);
    list_for_each_entry_safe(dep, tmp, &iface->users, list)
        interface_remove_user(dep);
    interface_clear_assignment_classes(iface);
    interface_ip_flush(&iface->config_ip);
    interface_cleanup_state(iface);
}
References interface::config_ip, device_remove_user(), interface::ext_dev, interface_user::iface, interface_cleanup_state(), interface_clear_assignment_classes(), interface_ip_flush(), interface_remove_user(), interface_user::list, list_for_each_entry_safe, interface::parent_iface, interface::remove_timer, uloop_timeout_cancel(), and interface::users.
Referenced by interface_change_config(), and interface_do_free().
interface_cleanup_state()
static void interface_cleanup_state (struct interface * iface) static
Definition at line 672 of file interface.c.
{
    interface_set_available(iface, false);
    interface_flush_state(iface);
    interface_clear_errors(iface);
    interface_set_proto_state(iface, NULL);
    interface_set_main_dev(iface, NULL);
    interface_set_l3_dev(iface, NULL);
}
References interface_clear_errors(), interface_flush_state(), interface_set_available(), interface_set_l3_dev(), interface_set_main_dev(), and interface_set_proto_state().
Referenced by interface_cleanup(), and interface_do_reload().
interface_clear_assignment_classes()
static void interface_clear_assignment_classes (struct interface * iface) static
Definition at line 541 of file interface.c.
{
    while (!list_empty(&iface->assignment_classes)) {
        struct interface_assignment_class *c = list_first_entry(&iface->assignment_classes,
                struct interface_assignment_class, head);
        list_del(&c->head);
        free(c);
    }
}
References interface::assignment_classes, interface_assignment_class::head, list_del(), list_empty(), and list_first_entry.
Referenced by interface_cleanup(), and interface_merge_assignment_data().
interface_clear_errors()
static void interface_clear_errors (struct interface * iface) static
Definition at line 125 of file interface.c.
{
    /* don't flush the errors in case the configured protocol handler matches the
           running protocol handler and is having the last error capability */
    if (!(iface->proto &&
          (iface->proto->handler->flags & PROTO_FLAG_LASTERROR) &&
          (iface->proto->handler->name == iface->proto_handler->name)))
        interface_error_flush(iface);
}
References proto_handler::flags, interface_proto_state::handler, interface_error_flush(), proto_handler::name, interface::proto, PROTO_FLAG_LASTERROR, and interface::proto_handler.
Referenced by interface_change_config(), interface_cleanup_state(), and interface_set_up().
interface_data_del()
static void interface_data_del (struct interface * iface, struct interface_data * data) static
Definition at line 189 of file interface.c.
{
    avl_delete(&iface->data, &data->node);
    free(data);
}
References avl_delete(), interface::data, and interface_error::data.
Referenced by interface_add_data(), and interface_data_flush().
interface_data_flush()
static void interface_data_flush (struct interface * iface) static
Definition at line 196 of file interface.c.
{
    struct interface_data *d, *tmp;
    avl_for_each_element_safe(&iface->data, d, node, tmp)
        interface_data_del(iface, d);
}
References avl_for_each_element_safe, interface::data, and interface_data_del().
Referenced by interface_flush_state().
interface_device_config_changed()
static bool interface_device_config_changed (struct interface * if_old, struct interface * if_new) static
Definition at line 1257 of file interface.c.
{
    struct blob_attr *ntb[__DEV_ATTR_MAX];
    struct blob_attr *otb[__DEV_ATTR_MAX];
    struct device *dev = if_old->main_dev.dev;
    unsigned long diff[2] = {};
    BUILD_BUG_ON(sizeof(diff) < __DEV_ATTR_MAX / 8);
    if (!dev)
        return false;
    if (if_old->device_config != if_new->device_config)
        return true;
    if (!if_new->device_config)
        return false;
    blobmsg_parse(device_attr_list.params, __DEV_ATTR_MAX, otb,
        blob_data(if_old->config), blob_len(if_old->config));
    blobmsg_parse(device_attr_list.params, __DEV_ATTR_MAX, ntb,
        blob_data(if_new->config), blob_len(if_new->config));
    uci_blob_diff(ntb, otb, &device_attr_list, diff);
    return diff[0] | diff[1];
}
References __DEV_ATTR_MAX, blob_data(), blob_len(), blobmsg_parse(), BUILD_BUG_ON, interface::config, device_user::dev, device_attr_list, interface::device_config, and interface::main_dev.
Referenced by interface_change_config().
interface_do_free()
static void interface_do_free (struct interface * iface) static
Definition at line 704 of file interface.c.
{
    interface_event(iface, IFEV_FREE);
    interface_cleanup(iface);
    free(iface->config);
    netifd_ubus_remove_interface(iface);
    avl_delete(&interfaces.avl, &iface->node.avl);
    if (iface->jail)
        free(iface->jail);
    if (iface->jail_device)
        free(iface->jail_device);
    if (iface->host_device)
        free(iface->host_device);
    free(iface);
}
References vlist_node::avl, vlist_tree::avl, avl_delete(), interface::config, interface::host_device, interface_user::iface, IFEV_FREE, interface_cleanup(), interfaces, interface::jail, interface::jail_device, netifd_ubus_remove_interface(), and interface::node.
Referenced by interface_handle_config_change().
interface_do_reload()
static void interface_do_reload (struct interface * iface) static
Definition at line 722 of file interface.c.
{
    interface_event(iface, IFEV_RELOAD);
    interface_cleanup_state(iface);
    proto_init_interface(iface, iface->config);
    interface_claim_device(iface);
}
References interface::config, interface_user::iface, IFEV_RELOAD, interface_claim_device(), interface_cleanup_state(), and proto_init_interface().
Referenced by interface_handle_config_change().
interface_error_flush()
static void interface_error_flush (struct interface * iface) static
Definition at line 103 of file interface.c.
{
    struct interface_error *error, *tmp;
    list_for_each_entry_safe(error, tmp, &iface->errors, list) {
        list_del(&error->list);
        free(error);
    }
}
References interface::errors, interface_error::list, list_del(), and list_for_each_entry_safe.
Referenced by interface_add_error(), interface_clear_errors(), and interface_event().
interface_event()
static void interface_event (struct interface * iface, enum interface_event ev) static
Definition at line 256 of file interface.c.
{
    struct interface_user *dep, *tmp;
    struct device *adev = NULL;
    list_for_each_entry_safe(dep, tmp, &iface->users, list)
        dep->cb(dep, iface, ev);
    list_for_each_entry_safe(dep, tmp, &iface_all_users, list)
        dep->cb(dep, iface, ev);
    switch (ev) {
    case IFEV_UP:
        interface_error_flush(iface);
        adev = iface->l3_dev.dev;
        fallthrough;
    case IFEV_DOWN:
    case IFEV_UP_FAILED:
        alias_notify_device(iface->name, adev);
        break;
    default:
        break;
    }
}
References alias_notify_device(), interface_user::cb, device_user::dev, fallthrough, IFEV_DOWN, IFEV_UP, IFEV_UP_FAILED, interface_error_flush(), interface::l3_dev, list_for_each_entry_safe, interface::name, and interface::users.
interface_ext_dev_cb()
static void interface_ext_dev_cb (struct device_user * dep, enum device_event ev) static
Definition at line 424 of file interface.c.
{
    if (ev == DEV_EVENT_REMOVE)
        device_remove_user(dep);
}
References DEV_EVENT_REMOVE, and device_remove_user().
Referenced by interface_alloc().
interface_flush_state()
static void interface_flush_state (struct interface * iface) static
Definition at line 282 of file interface.c.
{
    if (iface->l3_dev.dev)
        device_release(&iface->l3_dev);
    interface_data_flush(iface);
}
References device_user::dev, device_release(), interface_data_flush(), and interface::l3_dev.
Referenced by __interface_set_down(), interface_cleanup_state(), and mark_interface_down().
interface_force_link()
static bool interface_force_link (struct interface * iface) static
Definition at line 114 of file interface.c.
{
    struct device *dev = iface->main_dev.dev;
    if (dev && dev->settings.auth)
        return false;
    return iface->force_link;
}
References device_settings::auth, device_user::dev, interface::force_link, interface::main_dev, and device::settings.
Referenced by interface_check_state(), and interface_set_link_state().
interface_handle_config_change()
static void interface_handle_config_change (struct interface * iface) static
Definition at line 731 of file interface.c.
{
    enum interface_config_state state = iface->config_state;
    iface->config_state = IFC_NORMAL;
    switch(state) {
    case IFC_NORMAL:
        break;
    case IFC_RELOAD:
        interface_do_reload(iface);
        break;
    case IFC_REMOVE:
        interface_do_free(iface);
        return;
    }
    if (iface->autostart)
        interface_set_up(iface);
}
References interface::autostart, interface::config_state, interface_user::iface, IFC_NORMAL, IFC_RELOAD, IFC_REMOVE, interface_do_free(), interface_do_reload(), interface_set_up(), and state.
Referenced by interface_proto_event_cb(), and set_config_state().
interface_handle_link()
int interface_handle_link (struct interface * iface, const char * name, struct blob_attr * vlan, bool add, bool link_ext)
Definition at line 1114 of file interface.c.
{
    struct device *dev;
    dev = device_get(name, add ? (link_ext ? 2 : 1) : 0);
    if (!dev)
        return UBUS_STATUS_NOT_FOUND;
    if (!add)
        return interface_remove_link(iface, dev, vlan);
    interface_set_device_config(iface, dev);
    if (!link_ext)
        device_set_present(dev, true);
    return interface_add_link(iface, dev, vlan, link_ext);
}
References device_get(), device_set_present, interface_add_link(), interface_remove_link(), interface_set_device_config(), and UBUS_STATUS_NOT_FOUND.
Referenced by netifd_iface_handle_device(), wireless_interface_handle_link(), and wireless_vlan_handle_link().
interface_init_list()
static void __init interface_init_list (void) static
Definition at line 1429 of file interface.c.
{
    vlist_init(&interfaces, avl_strcmp, interface_update);
    interfaces.keep_old = true;
    interfaces.no_delete = true;
}
References avl_strcmp(), interface_update(), interfaces, vlist_tree::keep_old, vlist_tree::no_delete, and vlist_init().
interface_l3_dev_cb()
static void interface_l3_dev_cb (struct device_user * dep, enum device_event ev) static
Definition at line 466 of file interface.c.
{
    struct interface *iface;
    iface = container_of(dep, struct interface, l3_dev);
    if (iface->l3_dev.dev == iface->main_dev.dev)
        return;
    switch (ev) {
    case DEV_EVENT_LINK_DOWN:
        if (iface->proto_handler->flags & PROTO_FLAG_TEARDOWN_ON_L3_LINK_DOWN)
            interface_proto_event(iface->proto, PROTO_CMD_TEARDOWN, false);
        break;
    default:
        break;
    }
}
References container_of, device_user::dev, DEV_EVENT_LINK_DOWN, proto_handler::flags, interface::l3_dev, interface::main_dev, interface::proto, PROTO_CMD_TEARDOWN, PROTO_FLAG_TEARDOWN_ON_L3_LINK_DOWN, and interface::proto_handler.
Referenced by interface_alloc().
interface_main_dev_cb()
static void interface_main_dev_cb (struct device_user * dep, enum device_event ev) static
Definition at line 431 of file interface.c.
{
    struct interface *iface;
    iface = container_of(dep, struct interface, main_dev);
    switch (ev) {
    case DEV_EVENT_ADD:
        interface_set_available(iface, true);
        break;
    case DEV_EVENT_REMOVE:
        interface_set_available(iface, false);
        if (dep->dev && dep->dev->external && !dep->dev->sys_present)
            interface_set_main_dev(iface, NULL);
        break;
    case DEV_EVENT_UP:
        interface_set_enabled(iface, true);
        break;
    case DEV_EVENT_DOWN:
        interface_set_enabled(iface, false);
        break;
    case DEV_EVENT_AUTH_UP:
    case DEV_EVENT_LINK_UP:
    case DEV_EVENT_LINK_DOWN:
        interface_set_link_state(iface, device_link_active(dep->dev));
        break;
    case DEV_EVENT_TOPO_CHANGE:
        if (iface->renew)
            interface_proto_event(iface->proto, PROTO_CMD_RENEW, false);
        return;
    default:
        break;
    }
}
References container_of, device_user::dev, DEV_EVENT_ADD, DEV_EVENT_AUTH_UP, DEV_EVENT_DOWN, DEV_EVENT_LINK_DOWN, DEV_EVENT_LINK_UP, DEV_EVENT_REMOVE, DEV_EVENT_TOPO_CHANGE, DEV_EVENT_UP, device_link_active(), device::external, interface_set_available(), interface_set_enabled(), interface_set_link_state(), interface_set_main_dev(), interface::main_dev, interface::proto, PROTO_CMD_RENEW, interface::renew, and device::sys_present.
Referenced by interface_alloc().
interface_merge_assignment_data()
static void interface_merge_assignment_data (struct interface * old, struct interface * new) static
Definition at line 552 of file interface.c.
{
    bool changed = (old->assignment_hint != new->assignment_hint ||
            old->assignment_length != new->assignment_length ||
            old->assignment_iface_id_selection != new->assignment_iface_id_selection ||
            old->assignment_weight != new->assignment_weight ||
            (old->assignment_iface_id_selection == IFID_FIXED &&
             memcmp(&old->assignment_fixed_iface_id, &new->assignment_fixed_iface_id,
                sizeof(old->assignment_fixed_iface_id))) ||
            list_empty(&old->assignment_classes) != list_empty(&new->assignment_classes));
    struct interface_assignment_class *c;
    list_for_each_entry(c, &new->assignment_classes, head) {
        /* Compare list entries one-by-one to see if there was a change */
        if (list_empty(&old->assignment_classes)) /* The new list is longer */
            changed = true;
        if (changed)
            break;
        struct interface_assignment_class *c_old = list_first_entry(&old->assignment_classes,
                struct interface_assignment_class, head);
        if (strcmp(c_old->name, c->name)) /* An entry didn't match */
            break;
        list_del(&c_old->head);
        free(c_old);
    }
    /* The old list was longer than the new one or the last entry didn't match */
    if (!list_empty(&old->assignment_classes)) {
        interface_clear_assignment_classes(old);
        changed = true;
    }
    list_splice_init(&new->assignment_classes, &old->assignment_classes);
    if (changed) {
        old->assignment_hint = new->assignment_hint;
        old->assignment_length = new->assignment_length;
        old->assignment_iface_id_selection = new->assignment_iface_id_selection;
        old->assignment_fixed_iface_id = new->assignment_fixed_iface_id;
        old->assignment_weight = new->assignment_weight;
        interface_refresh_assignments(true);
    }
}
References interface::assignment_classes, interface::assignment_fixed_iface_id, interface::assignment_hint, interface::assignment_iface_id_selection, interface::assignment_length, interface::assignment_weight, interface_assignment_class::head, IFID_FIXED, interface_clear_assignment_classes(), interface_refresh_assignments(), list_del(), list_empty(), list_first_entry, list_for_each_entry, list_splice_init(), and interface_assignment_class::name.
Referenced by interface_change_config().
interface_parse_data()
int interface_parse_data (struct interface * iface, const struct blob_attr * attr)
Definition at line 235 of file interface.c.
{
    struct blob_attr *cur;
    size_t rem;
    int ret;
    iface->updated = 0;
    blob_for_each_attr(cur, attr, rem) {
        ret = interface_add_data(iface, cur);
        if (ret)
            return ret;
    }
    if (iface->updated && iface->state == IFS_UP)
        interface_event(iface, IFEV_UPDATE);
    return 0;
}
References blob_for_each_attr, IFEV_UPDATE, IFS_UP, interface_add_data(), interface::state, and interface::updated.
Referenced by netifd_handle_set_data().
interface_proto_event_cb()
static void interface_proto_event_cb (struct interface_proto_state * state, enum interface_proto_event ev) static
Definition at line 751 of file interface.c.
{
    struct interface *iface = state->iface;
    switch (ev) {
    case IFPEV_UP:
        if (iface->state != IFS_SETUP) {
            if (iface->state == IFS_UP && iface->updated)
                interface_event(iface, IFEV_UPDATE);
            return;
        }
        if (!iface->l3_dev.dev)
            interface_set_l3_dev(iface, iface->main_dev.dev);
        interface_ip_set_enabled(&iface->config_ip, true);
        interface_ip_set_enabled(&iface->proto_ip, true);
        system_flush_routes();
        iface->state = IFS_UP;
        iface->start_time = system_get_rtime();
        interface_event(iface, IFEV_UP);
        netifd_log_message(L_NOTICE, "Interface '%s' is now up\n", iface->name);
        break;
    case IFPEV_DOWN:
        if (iface->state == IFS_DOWN)
            return;
        netifd_log_message(L_NOTICE, "Interface '%s' is now down\n", iface->name);
        mark_interface_down(iface);
        interface_write_resolv_conf(iface->jail);
        if (iface->main_dev.dev && !(iface->config_state == IFC_NORMAL && iface->autostart && iface->available))
            device_release(&iface->main_dev);
        if (iface->l3_dev.dev)
            device_remove_user(&iface->l3_dev);
        interface_handle_config_change(iface);
        return;
    case IFPEV_LINK_LOST:
        if (iface->state != IFS_UP)
            return;
        netifd_log_message(L_NOTICE, "Interface '%s' has lost the connection\n", iface->name);
        mark_interface_down(iface);
        iface->state = IFS_SETUP;
        break;
    default:
        return;
    }
    interface_write_resolv_conf(iface->jail);
}
References interface::autostart, interface::available, interface::config_ip, interface::config_state, device_user::dev, device_release(), device_remove_user(), IFC_NORMAL, IFEV_UP, IFEV_UPDATE, IFPEV_DOWN, IFPEV_LINK_LOST, IFPEV_UP, IFS_DOWN, IFS_SETUP, IFS_UP, interface_handle_config_change(), interface_ip_set_enabled(), interface_set_l3_dev(), interface_write_resolv_conf(), interface::jail, interface::l3_dev, L_NOTICE, interface::main_dev, mark_interface_down(), interface::name, netifd_log_message(), interface::proto_ip, interface::start_time, interface::state, state, system_flush_routes(), system_get_rtime(), and interface::updated.
Referenced by interface_set_proto_state().
interface_remove_link()
static int interface_remove_link (struct interface * iface, struct device * dev, struct blob_attr * vlan) static
Definition at line 1059 of file interface.c.
{
    struct device *mdev = iface->main_dev.dev;
    if (mdev && mdev->hotplug_ops)
        return mdev->hotplug_ops->del(mdev, dev, vlan);
    if (dev == iface->ext_dev.dev)
        device_remove_user(&iface->ext_dev);
    if (!iface->main_dev.hotplug)
        return UBUS_STATUS_INVALID_ARGUMENT;
    if (dev != iface->main_dev.dev)
        return UBUS_STATUS_INVALID_ARGUMENT;
    interface_set_main_dev(iface, NULL);
    return 0;
}
References device_hotplug_ops::del, device_user::dev, device_remove_user(), interface::ext_dev, device_user::hotplug, device::hotplug_ops, interface_set_main_dev(), interface::main_dev, and UBUS_STATUS_INVALID_ARGUMENT.
Referenced by interface_handle_link().
interface_remove_user()
void interface_remove_user (struct interface_user * dep)
Definition at line 515 of file interface.c.
{
    list_del_init(&dep->list);
    dep->iface = NULL;
}
References interface_user::iface, interface_user::list, and list_del_init().
Referenced by deregister_interfaces(), interface_alias_cb(), interface_change_config(), interface_claim_device(), interface_cleanup(), proto_shell_clear_host_dep(), proto_shell_if_down_cb(), and proto_shell_update_host_dep().
interface_renew()
int interface_renew (struct interface * iface)
Definition at line 1179 of file interface.c.
{
    if (iface->state == IFS_TEARDOWN || iface->state == IFS_DOWN)
        return -1;
    return interface_proto_event(iface->proto, PROTO_CMD_RENEW, false);
}
References IFS_DOWN, IFS_TEARDOWN, interface::proto, PROTO_CMD_RENEW, and interface::state.
Referenced by netifd_handle_renew().
interface_replace_dns()
static void interface_replace_dns (struct interface_ip_settings * new, struct interface_ip_settings * old) static
Definition at line 1250 of file interface.c.
{
    vlist_simple_replace(&new->dns_servers, &old->dns_servers);
    vlist_simple_replace(&new->dns_search, &old->dns_search);
}
References interface_ip_settings::dns_search, interface_ip_settings::dns_servers, and vlist_simple_replace().
Referenced by interface_change_config().
interface_set_available()
void interface_set_available (struct interface * iface, bool new_state)
Definition at line 485 of file interface.c.
{
    if (iface->available == new_state)
        return;
    D(INTERFACE, "Interface '%s', available=%d", iface->name, new_state);
    iface->available = new_state;
    if (new_state) {
        if (iface->autostart && !config_init)
            interface_set_up(iface);
    } else
        __interface_set_down(iface, true);
}
References __interface_set_down(), interface::autostart, interface::available, config_init, D, interface_set_up(), and interface::name.
Referenced by interface_add_link(), interface_alias_cb(), interface_claim_device(), interface_cleanup_state(), interface_main_dev_cb(), interface_set_main_dev(), proto_shell_check_dependencies(), and proto_shell_set_available().
interface_set_device_config()
static void interface_set_device_config (struct interface * iface, struct device * dev) static
Definition at line 628 of file interface.c.
{
    if (!dev || !dev->default_config)
        return;
    if (!iface->device_config &&
        (!dev->iface_config || dev->config_iface != iface))
        return;
    dev->config_iface = iface;
    dev->iface_config = iface->device_config;
    device_apply_config(dev, dev->type, iface->config);
}
References interface::config, device::config_iface, device::default_config, device_apply_config(), interface::device_config, device::iface_config, and device::type.
Referenced by interface_claim_device(), and interface_handle_link().
interface_set_down()
void interface_set_down (struct interface * iface)
Definition at line 1166 of file interface.c.
{
    if (!iface) {
        vlist_for_each_element(&interfaces, iface, node)
            __interface_set_down(iface, false);
    } else {
        iface->autostart = false;
        wireless_check_network_enabled();
        __interface_set_down(iface, false);
    }
}
References __interface_set_down(), interface::autostart, interfaces, vlist_for_each_element, and wireless_check_network_enabled().
Referenced by interface_stop_jail(), netifd_handle_down(), and netifd_restart().
interface_set_enabled()
static void interface_set_enabled (struct interface * iface, bool new_state) static
Definition at line 396 of file interface.c.
{
    if (iface->enabled == new_state)
        return;
    netifd_log_message(L_NOTICE, "Interface '%s' is %s\n", iface->name, new_state ? "enabled" : "disabled");
    iface->enabled = new_state;
    interface_check_state(iface);
}
References interface::enabled, interface_check_state(), L_NOTICE, interface::name, and netifd_log_message().
Referenced by interface_main_dev_cb().
interface_set_l3_dev()
void interface_set_l3_dev (struct interface * iface, struct device * dev)
Definition at line 1011 of file interface.c.
{
    bool enabled = iface->config_ip.enabled;
    bool claimed = iface->l3_dev.claimed;
    if (iface->l3_dev.dev == dev)
        return;
    interface_ip_set_enabled(&iface->config_ip, false);
    interface_ip_set_enabled(&iface->proto_ip, false);
    interface_ip_flush(&iface->proto_ip);
    device_add_user(&iface->l3_dev, dev);
    if (dev) {
        if (claimed) {
            if (device_claim(&iface->l3_dev) < 0)
                return;
        }
        interface_ip_set_enabled(&iface->config_ip, enabled);
        interface_ip_set_enabled(&iface->proto_ip, enabled);
    }
}
References device_user::claimed, interface::config_ip, device_user::dev, device_add_user(), device_claim(), interface_ip_settings::enabled, interface_ip_flush(), interface_ip_set_enabled(), interface::l3_dev, and interface::proto_ip.
Referenced by interface_cleanup_state(), interface_proto_event_cb(), interface_set_main_dev(), proto_shell_update_link(), and static_proto_setup().
interface_set_link_state()
static void interface_set_link_state (struct interface * iface, bool new_state) static
Definition at line 407 of file interface.c.
{
    if (iface->link_state == new_state)
        return;
    netifd_log_message(L_NOTICE, "Interface '%s' has link connectivity %s\n", iface->name, new_state ? "" : "loss");
    iface->link_state = new_state;
    interface_check_state(iface);
    if (new_state && interface_force_link(iface) &&
        iface->state == IFS_UP && !iface->link_up_event) {
        interface_event(iface, IFEV_LINK_UP);
        iface->link_up_event = true;
    }
}
References IFEV_LINK_UP, IFS_UP, interface_check_state(), interface_force_link(), L_NOTICE, interface::link_state, interface::link_up_event, interface::name, netifd_log_message(), and interface::state.
Referenced by interface_main_dev_cb(), and interface_set_main_dev().
interface_set_main_dev()
static void interface_set_main_dev (struct interface * iface, struct device * dev) static
Definition at line 1035 of file interface.c.
{
    bool claimed = iface->l3_dev.claimed;
    if (iface->main_dev.dev == dev)
        return;
    interface_set_available(iface, false);
    device_add_user(&iface->main_dev, dev);
    if (!dev) {
        interface_set_link_state(iface, false);
        return;
    }
    if (claimed) {
        if (device_claim(&iface->l3_dev) < 0)
            return;
    }
    if (!iface->l3_dev.dev)
        interface_set_l3_dev(iface, dev);
}
References device_user::claimed, device_user::dev, device_add_user(), device_claim(), interface_set_available(), interface_set_l3_dev(), interface_set_link_state(), interface::l3_dev, and interface::main_dev.
Referenced by interface_add_link(), interface_alias_cb(), interface_claim_device(), interface_cleanup_state(), interface_main_dev_cb(), and interface_remove_link().
interface_set_proto_state()
void interface_set_proto_state (struct interface * iface, struct interface_proto_state * state)
Definition at line 802 of file interface.c.
{
    if (iface->proto) {
        iface->proto->free(iface->proto);
        iface->proto = NULL;
    }
    iface->state = IFS_DOWN;
    iface->proto = state;
    if (!state)
        return;
    state->proto_event = interface_proto_event_cb;
    state->iface = iface;
}
References interface_proto_state::free, IFS_DOWN, interface_proto_event_cb(), interface::proto, interface_proto_state::proto_event, interface::state, and state.
Referenced by interface_cleanup_state(), and proto_init_interface().
interface_set_up()
void interface_set_up (struct interface * iface)
Definition at line 1134 of file interface.c.
{
    int ret;
    const char *error = NULL;
    iface->autostart = true;
    wireless_check_network_enabled();
    if (iface->state != IFS_DOWN)
        return;
    interface_clear_errors(iface);
    if (iface->available) {
        if (iface->main_dev.dev) {
            ret = device_claim(&iface->main_dev);
            if (!ret)
                interface_check_state(iface);
            else
                error = "DEVICE_CLAIM_FAILED";
        } else {
            ret = __interface_set_up(iface);
            if (ret)
                error = "SETUP_FAILED";
        }
    } else
        error = "NO_DEVICE";
    if (error)
        interface_add_error(iface, "interface", error, NULL, 0);
}
References __interface_set_up(), interface::autostart, interface::available, device_user::dev, device_claim(), IFS_DOWN, interface_add_error(), interface_check_state(), interface_clear_errors(), interface::main_dev, interface::state, and wireless_check_network_enabled().
Referenced by interface_handle_config_change(), interface_set_available(), interface_start_pending(), and netifd_handle_up().
interface_start_jail()
void interface_start_jail (int netns_fd, const char * jail)
Definition at line 1199 of file interface.c.
{
    struct interface *iface;
    vlist_for_each_element(&interfaces, iface, node) {
        if (!iface->jail || strcmp(iface->jail, jail))
            continue;
        system_link_netns_move(iface->main_dev.dev, netns_fd, iface->jail_device);
    }
}
References device_user::dev, interfaces, interface::jail, interface::jail_device, interface::main_dev, netns_fd, system_link_netns_move(), and vlist_for_each_element.
Referenced by netifd_netns_updown().
interface_start_pending()
void interface_start_pending (void)
Definition at line 1188 of file interface.c.
{
    struct interface *iface;
    vlist_for_each_element(&interfaces, iface, node) {
        if (iface->autostart)
            interface_set_up(iface);
    }
}
References interface::autostart, interface_set_up(), interfaces, and vlist_for_each_element.
Referenced by config_init_all().
interface_stop_jail()
void interface_stop_jail (int netns_fd)
Definition at line 1212 of file interface.c.
{
    struct interface *iface;
    char *orig_ifname;
    vlist_for_each_element(&interfaces, iface, node) {
        orig_ifname = iface->host_device;
        interface_set_down(iface);
        system_link_netns_move(iface->main_dev.dev, netns_fd, orig_ifname);
    }
}
References device_user::dev, interface::host_device, interface_set_down(), interfaces, interface::main_dev, netns_fd, system_link_netns_move(), and vlist_for_each_element.
Referenced by netifd_netns_updown().
interface_update()
static void interface_update (struct vlist_tree * tree, struct vlist_node * node_new, struct vlist_node * node_old) static
Definition at line 1406 of file interface.c.
{
    struct interface *if_old = container_of(node_old, struct interface, node);
    struct interface *if_new = container_of(node_new, struct interface, node);
    if (node_old && node_new) {
        D(INTERFACE, "Update interface '%s'", if_new->name);
        interface_change_config(if_old, if_new);
    } else if (node_old) {
        D(INTERFACE, "Remove interface '%s'", if_old->name);
        set_config_state(if_old, IFC_REMOVE);
    } else if (node_new) {
        D(INTERFACE, "Create interface '%s'", if_new->name);
        interface_event(if_new, IFEV_CREATE);
        proto_init_interface(if_new, if_new->config);
        interface_claim_device(if_new);
        netifd_ubus_add_interface(if_new);
    }
}
References interface::config, container_of, D, IFC_REMOVE, IFEV_CREATE, interface_change_config(), interface_claim_device(), interface::name, netifd_ubus_add_interface(), proto_init_interface(), and set_config_state().
Referenced by interface_init_list().
interface_update_complete()
void interface_update_complete (struct interface * iface)
Definition at line 1244 of file interface.c.
{
    interface_ip_update_complete(&iface->proto_ip);
}
References interface_ip_update_complete(), and interface::proto_ip.
Referenced by proto_shell_update_link().
interface_update_start()
void interface_update_start (struct interface * iface, const bool keep_old)
Definition at line 1235 of file interface.c.
{
    iface->updated = 0;
    if (!keep_old)
        interface_ip_update_start(&iface->proto_ip);
}
References interface_ip_update_start(), interface::proto_ip, and interface::updated.
Referenced by proto_shell_update_link().
LIST_HEAD()
static LIST_HEAD (iface_all_users) static
mark_interface_down()
static void mark_interface_down (struct interface * iface) static
Definition at line 290 of file interface.c.
{
    enum interface_state state = iface->state;
    if (state == IFS_DOWN)
        return;
    iface->link_up_event = false;
    iface->state = IFS_DOWN;
    switch (state) {
    case IFS_UP:
    case IFS_TEARDOWN:
        interface_event(iface, IFEV_DOWN);
        break;
    case IFS_SETUP:
        interface_event(iface, IFEV_UP_FAILED);
        break;
    default:
        break;
    }
    interface_ip_set_enabled(&iface->config_ip, false);
    interface_ip_set_enabled(&iface->proto_ip, false);
    interface_ip_flush(&iface->proto_ip);
    interface_flush_state(iface);
    system_flush_routes();
}
References interface::config_ip, IFEV_DOWN, IFEV_UP_FAILED, IFS_DOWN, IFS_SETUP, IFS_TEARDOWN, IFS_UP, interface_flush_state(), interface_ip_flush(), interface_ip_set_enabled(), interface::link_up_event, interface::proto_ip, interface::state, state, and system_flush_routes().
Referenced by __interface_set_up(), and interface_proto_event_cb().
set_config_state()
static void set_config_state (struct interface * iface, enum interface_config_state s) static
Definition at line 1225 of file interface.c.
{
    __set_config_state(iface, s);
    if (iface->state == IFS_DOWN)
        interface_handle_config_change(iface);
    else
        __interface_set_down(iface, false);
}
References __interface_set_down(), __set_config_state(), IFS_DOWN, interface_handle_config_change(), and interface::state.
Referenced by interface_change_config(), and interface_update().
Variable Documentation
iface_attrs
const struct blobmsg_policy iface_attrs[IFACE_ATTR_MAX] static
Initial value:
= {
    [IFACE_ATTR_DEVICE] = { .name = "device", .type = BLOBMSG_TYPE_STRING },
    [IFACE_ATTR_PROTO] = { .name = "proto", .type = BLOBMSG_TYPE_STRING },
    [IFACE_ATTR_IFNAME] = { .name = "ifname", .type = BLOBMSG_TYPE_STRING },
    [IFACE_ATTR_AUTO] = { .name = "auto", .type = BLOBMSG_TYPE_BOOL },
    [IFACE_ATTR_ZONE] = { .name = "zone", .type = BLOBMSG_TYPE_STRING },
    [IFACE_ATTR_JAIL] = { .name = "jail", .type = BLOBMSG_TYPE_STRING },
    [IFACE_ATTR_JAIL_DEVICE] = { .name = "jail_device", .type = BLOBMSG_TYPE_STRING },
    [IFACE_ATTR_JAIL_IFNAME] = { .name = "jail_ifname", .type = BLOBMSG_TYPE_STRING },
    [IFACE_ATTR_HOST_DEVICE] = { .name = "host_device", .type = BLOBMSG_TYPE_STRING },
    [IFACE_ATTR_DEFAULTROUTE] = { .name = "defaultroute", .type = BLOBMSG_TYPE_BOOL },
    [IFACE_ATTR_PEERDNS] = { .name = "peerdns", .type = BLOBMSG_TYPE_BOOL },
    [IFACE_ATTR_METRIC] = { .name = "metric", .type = BLOBMSG_TYPE_INT32 },
    [IFACE_ATTR_DNS] = { .name = "dns", .type = BLOBMSG_TYPE_ARRAY },
    [IFACE_ATTR_RENEW] = { .name = "renew", .type = BLOBMSG_TYPE_BOOL },
    [IFACE_ATTR_DNS_SEARCH] = { .name = "dns_search", .type = BLOBMSG_TYPE_ARRAY },
    [IFACE_ATTR_DNS_METRIC] = { .name = "dns_metric", .type = BLOBMSG_TYPE_INT32 },
    [IFACE_ATTR_INTERFACE] = { .name = "interface", .type = BLOBMSG_TYPE_STRING },
    [IFACE_ATTR_IP6ASSIGN] = { .name = "ip6assign", .type = BLOBMSG_TYPE_INT32 },
    [IFACE_ATTR_IP6HINT] = { .name = "ip6hint", .type = BLOBMSG_TYPE_STRING },
    [IFACE_ATTR_IP4TABLE] = { .name = "ip4table", .type = BLOBMSG_TYPE_STRING },
    [IFACE_ATTR_IP6TABLE] = { .name = "ip6table", .type = BLOBMSG_TYPE_STRING },
    [IFACE_ATTR_IP6CLASS] = { .name = "ip6class", .type = BLOBMSG_TYPE_ARRAY },
    [IFACE_ATTR_DELEGATE] = { .name = "delegate", .type = BLOBMSG_TYPE_BOOL },
    [IFACE_ATTR_IP6IFACEID] = { .name = "ip6ifaceid", .type = BLOBMSG_TYPE_STRING },
    [IFACE_ATTR_FORCE_LINK] = { .name = "force_link", .type = BLOBMSG_TYPE_BOOL },
    [IFACE_ATTR_IP6WEIGHT] = { .name = "ip6weight", .type = BLOBMSG_TYPE_INT32 },
}
Definition at line 63 of file interface.c.
{
    [IFACE_ATTR_DEVICE] = { .name = "device", .type = BLOBMSG_TYPE_STRING },
    [IFACE_ATTR_PROTO] = { .name = "proto", .type = BLOBMSG_TYPE_STRING },
    [IFACE_ATTR_IFNAME] = { .name = "ifname", .type = BLOBMSG_TYPE_STRING },
    [IFACE_ATTR_AUTO] = { .name = "auto", .type = BLOBMSG_TYPE_BOOL },
    [IFACE_ATTR_ZONE] = { .name = "zone", .type = BLOBMSG_TYPE_STRING },
    [IFACE_ATTR_JAIL] = { .name = "jail", .type = BLOBMSG_TYPE_STRING },
    [IFACE_ATTR_JAIL_DEVICE] = { .name = "jail_device", .type = BLOBMSG_TYPE_STRING },
    [IFACE_ATTR_JAIL_IFNAME] = { .name = "jail_ifname", .type = BLOBMSG_TYPE_STRING },
    [IFACE_ATTR_HOST_DEVICE] = { .name = "host_device", .type = BLOBMSG_TYPE_STRING },
    [IFACE_ATTR_DEFAULTROUTE] = { .name = "defaultroute", .type = BLOBMSG_TYPE_BOOL },
    [IFACE_ATTR_PEERDNS] = { .name = "peerdns", .type = BLOBMSG_TYPE_BOOL },
    [IFACE_ATTR_METRIC] = { .name = "metric", .type = BLOBMSG_TYPE_INT32 },
    [IFACE_ATTR_DNS] = { .name = "dns", .type = BLOBMSG_TYPE_ARRAY },
    [IFACE_ATTR_RENEW] = { .name = "renew", .type = BLOBMSG_TYPE_BOOL },
    [IFACE_ATTR_DNS_SEARCH] = { .name = "dns_search", .type = BLOBMSG_TYPE_ARRAY },
    [IFACE_ATTR_DNS_METRIC] = { .name = "dns_metric", .type = BLOBMSG_TYPE_INT32 },
    [IFACE_ATTR_INTERFACE] = { .name = "interface", .type = BLOBMSG_TYPE_STRING },
    [IFACE_ATTR_IP6ASSIGN] = { .name = "ip6assign", .type = BLOBMSG_TYPE_INT32 },
    [IFACE_ATTR_IP6HINT] = { .name = "ip6hint", .type = BLOBMSG_TYPE_STRING },
    [IFACE_ATTR_IP4TABLE] = { .name = "ip4table", .type = BLOBMSG_TYPE_STRING },
    [IFACE_ATTR_IP6TABLE] = { .name = "ip6table", .type = BLOBMSG_TYPE_STRING },
    [IFACE_ATTR_IP6CLASS] = { .name = "ip6class", .type = BLOBMSG_TYPE_ARRAY },
    [IFACE_ATTR_DELEGATE] = { .name = "delegate", .type = BLOBMSG_TYPE_BOOL },
    [IFACE_ATTR_IP6IFACEID] = { .name = "ip6ifaceid", .type = BLOBMSG_TYPE_STRING },
    [IFACE_ATTR_FORCE_LINK] = { .name = "force_link", .type = BLOBMSG_TYPE_BOOL },
    [IFACE_ATTR_IP6WEIGHT] = { .name = "ip6weight", .type = BLOBMSG_TYPE_INT32 },
};
Referenced by __interface_add(), and interface_alloc().
interface_attr_list
const struct uci_blob_param_list interface_attr_list
Initial value:
= {
    .n_params = IFACE_ATTR_MAX,
    .params = iface_attrs,
}
Definition at line 92 of file interface.c.
{
    .n_params = IFACE_ATTR_MAX,
    .params = iface_attrs,
};
Referenced by config_parse_interface().
interfaces
struct vlist_tree interfaces
Definition at line 30 of file interface.c.
Referenced by __interface_add(), __interface_write_dns_entries(), alias_check_state(), config_init_all(), config_init_ip(), interface_claim_device(), interface_do_free(), interface_init_list(), interface_ip_add_neighbor(), interface_ip_add_route(), interface_ip_add_target_route(), interface_ip_valid_until_handler(), interface_set_down(), interface_start_jail(), interface_start_pending(), interface_stop_jail(), interface_update_prefix(), interface_update_prefix_assignments(), netifd_add_host_route(), netifd_handle_dump(), netifd_handle_iface(), netifd_iface_do_remove(), proto_shell_update_host_dep(), register_interfaces(), system_add_ip_tunnel(), vif_config_add_bridge(), wireless_check_interface(), wireless_interface_handle_link(), and wireless_vlan_handle_link().