zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/rpcd/include/rpcd/exec.h File Reference
exec.h File Reference
#include <libubus.h>
#include <libubox/blobmsg.h>
#include <libubox/ustream.h>
Classes
struct rpc_exec_context
Macros
#define RPC_EXEC_MAX_SIZE (4096 * 64)
#define RPC_EXEC_DEFAULT_TIMEOUT (120 * 1000)
#define ustream_for_each_read_buffer(stream, ptr, len)
#define ustream_declare_read(us, fd, name)
#define ustream_declare_write(us, fd, name)
Typedefs
typedef int(* rpc_exec_write_cb_t) (struct ustream *, void *)
typedef int(* rpc_exec_read_cb_t) (struct blob_buf *, char *, int, void *)
typedef int(* rpc_exec_done_cb_t) (struct blob_buf *, int, void *)
Functions
const char * rpc_exec_lookup (const char *cmd)
int rpc_exec (const char **args, rpc_exec_write_cb_t in, rpc_exec_read_cb_t out, rpc_exec_read_cb_t err, rpc_exec_done_cb_t end, void *priv, struct ubus_context *ctx, struct ubus_request_data *req)
Variables
int rpc_exec_timeout
Class Documentation
rpc_exec_context
struct rpc_exec_context
Definition at line 59 of file exec.h.
Class Members
struct blob_buf blob
bool blob_array
void * blob_cookie
struct ubus_context * context
struct ustream_fd epipe
char * err
int errlen
rpc_exec_done_cb_t finish_cb
struct ustream_fd ipipe
struct ustream_fd opipe
char * out
int outlen
void * priv
struct uloop_process process
struct ubus_request_data request
int stat
rpc_exec_read_cb_t stderr_cb
rpc_exec_write_cb_t stdin_cb
rpc_exec_read_cb_t stdout_cb
struct uloop_timeout timeout
Macro Definition Documentation
RPC_EXEC_DEFAULT_TIMEOUT
#define RPC_EXEC_DEFAULT_TIMEOUT (120 * 1000)
Definition at line 27 of file exec.h.
RPC_EXEC_MAX_SIZE
#define RPC_EXEC_MAX_SIZE (4096 * 64)
Definition at line 26 of file exec.h.
ustream_declare_read
#define ustream_declare_read (us, fd, name)
Value:
    do {                                                      \
        us.stream.string_data   = true;                       \
        us.stream.r.buffer_len  = 4096;                       \
        us.stream.r.max_buffers = RPC_EXEC_MAX_SIZE / 4096;   \
        us.stream.notify_read   = rpc_exec_##name##_read_cb;  \
        us.stream.notify_state  = rpc_exec_##name##_state_cb; \
        ustream_fd_init(&us, fd);                             \
    } while(0)
Definition at line 34 of file exec.h.
#define ustream_declare_read(us, fd, name)                    \
    do {                                                      \
        us.stream.string_data   = true;                       \
        us.stream.r.buffer_len  = 4096;                       \
        us.stream.r.max_buffers = RPC_EXEC_MAX_SIZE / 4096;   \
        us.stream.notify_read   = rpc_exec_##name##_read_cb;  \
        us.stream.notify_state  = rpc_exec_##name##_state_cb; \
        ustream_fd_init(&us, fd);                             \
    } while(0)
Referenced by rpc_exec().
ustream_declare_write
#define ustream_declare_write (us, fd, name)
Value:
    do {                                                      \
        us.stream.string_data   = true;                       \
        us.stream.w.buffer_len  = 4096;                       \
        us.stream.w.max_buffers = RPC_EXEC_MAX_SIZE / 4096;   \
        us.stream.notify_write  = rpc_exec_##name##_write_cb; \
        ustream_fd_init(&us, fd);                             \
    } while(0)
Definition at line 44 of file exec.h.
#define ustream_declare_write(us, fd, name)                   \
    do {                                                      \
        us.stream.string_data   = true;                       \
        us.stream.w.buffer_len  = 4096;                       \
        us.stream.w.max_buffers = RPC_EXEC_MAX_SIZE / 4096;   \
        us.stream.notify_write  = rpc_exec_##name##_write_cb; \
        ustream_fd_init(&us, fd);                             \
    } while(0)
Referenced by rpc_exec().
ustream_for_each_read_buffer
#define ustream_for_each_read_buffer (stream, ptr, len)
Value:
    for (ptr = ustream_get_read_buf(stream, &len);     \
         ptr != NULL && len > 0;                       \
         ustream_consume(stream, len), ptr = ustream_get_read_buf(stream, &len))
Definition at line 29 of file exec.h.
#define ustream_for_each_read_buffer(stream, ptr, len) \
    for (ptr = ustream_get_read_buf(stream, &len);     \
         ptr != NULL && len > 0;                       \
         ustream_consume(stream, len), ptr = ustream_get_read_buf(stream, &len))
Typedef Documentation
rpc_exec_done_cb_t
typedef int(* rpc_exec_done_cb_t) (struct blob_buf *, int, void *)
Definition at line 57 of file exec.h.
rpc_exec_read_cb_t
typedef int(* rpc_exec_read_cb_t) (struct blob_buf *, char *, int, void *)
Definition at line 56 of file exec.h.
rpc_exec_write_cb_t
typedef int(* rpc_exec_write_cb_t) (struct ustream *, void *)
Definition at line 55 of file exec.h.
Function Documentation
rpc_exec()
int rpc_exec (const char ** args, rpc_exec_write_cb_t in, rpc_exec_read_cb_t out, rpc_exec_read_cb_t err, rpc_exec_done_cb_t end, void * priv, struct ubus_context * ctx, struct ubus_request_data * req)
Definition at line 280 of file exec.c.
{
    pid_t pid;
    int ipipe[2];
    int opipe[2];
    int epipe[2];
    const char *cmd;
    struct rpc_exec_context *c;
    cmd = rpc_exec_lookup(args[0]);
    if (!cmd)
        return UBUS_STATUS_NOT_FOUND;
    c = malloc(sizeof(*c));
    if (!c)
        return UBUS_STATUS_UNKNOWN_ERROR;
    if (pipe(ipipe))
        goto fail_ipipe;
    if (pipe(opipe))
        goto fail_opipe;
    if (pipe(epipe))
        goto fail_epipe;
    switch ((pid = fork()))
    {
    case -1:
        goto fail_fork;
    case 0:
        uloop_done();
        dup2(ipipe[0], 0);
        dup2(opipe[1], 1);
        dup2(epipe[1], 2);
        close(ipipe[0]);
        close(ipipe[1]);
        close(opipe[0]);
        close(opipe[1]);
        close(epipe[0]);
        close(epipe[1]);
        if (execv(cmd, (char * const *)args))
            return rpc_errno_status();
    default:
        memset(c, 0, sizeof(*c));
        blob_buf_init(&c->blob, 0);
        c->stdin_cb  = in;
        c->stdout_cb = out;
        c->stderr_cb = err;
        c->finish_cb = end;
        c->priv      = priv;
        ustream_declare_read(c->opipe, opipe[0], opipe);
        ustream_declare_read(c->epipe, epipe[0], epipe);
        c->process.pid = pid;
        c->process.cb = rpc_exec_process_cb;
        uloop_process_add(&c->process);
        c->timeout.cb = rpc_exec_timeout_cb;
        uloop_timeout_set(&c->timeout, rpc_exec_timeout);
        if (c->stdin_cb)
        {
            ustream_declare_write(c->ipipe, ipipe[1], ipipe);
            rpc_exec_ipipe_write_cb(&c->ipipe.stream, 0);
        }
        else
        {
            close(ipipe[1]);
        }
        close(ipipe[0]);
        close(opipe[1]);
        close(epipe[1]);
        c->context = ctx;
        ubus_defer_request(ctx, req, &c->request);
    }
    return UBUS_STATUS_OK;
fail_fork:
    close(epipe[0]);
    close(epipe[1]);
fail_epipe:
    close(opipe[0]);
    close(opipe[1]);
fail_opipe:
    close(ipipe[0]);
    close(ipipe[1]);
fail_ipipe:
    free(c);
    return rpc_errno_status();
}
References rpc_exec_context::blob, blob_buf_init(), uloop_process::cb, uloop_timeout::cb, cmd, rpc_exec_context::context, ctx, rpc_exec_context::epipe, err, rpc_exec_context::finish_cb, rpc_exec_context::ipipe, rpc_exec_context::opipe, rpc_exec_context::out, uloop_process::pid, rpc_exec_context::priv, rpc_exec_context::process, rpc_exec_context::request, rpc_errno_status(), rpc_exec_ipipe_write_cb(), rpc_exec_lookup(), rpc_exec_process_cb(), rpc_exec_timeout, rpc_exec_timeout_cb(), rpc_exec_context::stderr_cb, rpc_exec_context::stdin_cb, rpc_exec_context::stdout_cb, ustream_fd::stream, rpc_exec_context::timeout, ubus_defer_request(), UBUS_STATUS_NOT_FOUND, UBUS_STATUS_OK, UBUS_STATUS_UNKNOWN_ERROR, uloop_done(), uloop_process_add(), uloop_timeout_set(), ustream_declare_read, and ustream_declare_write.
Referenced by rpc_plugin_call().
rpc_exec_lookup()
const char * rpc_exec_lookup (const char * cmd)
Definition at line 54 of file exec.c.
{
    struct stat s;
    int plen = 0, clen = strlen(cmd) + 1;
    char *search, *p;
    static char path[PATH_MAX];
    if (!stat(cmd, &s) && S_ISREG(s.st_mode))
        return cmd;
    search = getenv("PATH");
    if (!search)
        search = "/bin:/usr/bin:/sbin:/usr/sbin";
    p = search;
    do
    {
        if (*p != ':' && *p != '\0')
            continue;
        plen = p - search;
        if ((plen + clen) >= sizeof(path))
            continue;
        strncpy(path, search, plen);
        sprintf(path + plen, "/%s", cmd);
        if (!stat(path, &s) && S_ISREG(s.st_mode))
            return path;
        search = p + 1;
    }
    while (*p++);
    return NULL;
}
References cmd, and path.
Referenced by exec_self(), and rpc_exec().
Variable Documentation
rpc_exec_timeout
int rpc_exec_timeout extern
Definition at line 37 of file main.c.
Referenced by main(), and rpc_exec().