zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/libubox/udebug-priv.h File Reference
udebug-priv.h File Reference
#include "blobmsg.h"
#include "udebug.h"
#include "udebug-proto.h"
Macros
#define UDEBUG_TIMEOUT 1000
Functions
__hidden int udebug_buf_open (struct udebug_buf *buf, int fd, uint32_t ring_size, uint32_t data_size)
__hidden struct udebug_client_msg * udebug_send_and_wait (struct udebug *ctx, struct udebug_client_msg *msg, int *rfd)
static int32_t u32_sub (uint32_t a, uint32_t b)
static int32_t u32_max (uint32_t a, uint32_t b)
static void u32_set (void *ptr, uint32_t val)
static uint32_t u32_get (void *ptr)
Macro Definition Documentation
UDEBUG_TIMEOUT
#define UDEBUG_TIMEOUT 1000
Definition at line 25 of file udebug-priv.h.
Referenced by recv_retry().
Function Documentation
u32_get()
static uint32_t u32_get (void * ptr) inline static
Definition at line 47 of file udebug-priv.h.
{
    volatile uint32_t *v = ptr;
    return *v;
}
Referenced by rbuf_advance_read_head(), udebug_entry_add(), udebug_remote_buf_set_start_time(), and udebug_remote_buf_snapshot().
u32_max()
static int32_t u32_max (uint32_t a, uint32_t b) inline static
Definition at line 36 of file udebug-priv.h.
{
    return u32_sub(a, b) > 0 ? a : b;
}
References b, and u32_sub().
Referenced by udebug_buf_alloc().
u32_set()
static void u32_set (void * ptr, uint32_t val) inline static
Definition at line 41 of file udebug-priv.h.
{
    volatile uint32_t *v = ptr;
    *v = val;
}
Referenced by udebug_entry_add().
u32_sub()
static int32_t u32_sub (uint32_t a, uint32_t b) inline static
Definition at line 31 of file udebug-priv.h.
{
    return a - b;
}
References b.
Referenced by rbuf_advance_read_head(), u32_max(), udebug_remote_buf_set_start_time(), and udebug_remote_buf_snapshot().
udebug_buf_open()
__hidden int udebug_buf_open (struct udebug_buf * buf, int fd, uint32_t ring_size, uint32_t data_size)
Definition at line 424 of file udebug.c.
{
    udebug_init_page_size();
    INIT_LIST_HEAD(&buf->list);
    buf->ring_size = ring_size;
    buf->head_size = __udebug_headsize(ring_size);
    buf->data_size = data_size;
    if (buf->ring_size > (1U << 24) || buf->data_size > (1U << 29))
        return -1;
    if (__udebug_buf_map(buf, fd))
        return -1;
    if (buf->ring_size != buf->hdr->ring_size ||
        buf->data_size != buf->hdr->data_size) {
        munmap(buf->hdr, buf->head_size + 2 * buf->data_size);
        buf->hdr = NULL;
        return -1;
    }
    buf->fd = fd;
    return 0;
}
References __udebug_buf_map(), __udebug_headsize(), buf, INIT_LIST_HEAD(), and udebug_init_page_size().
Referenced by udebug_remote_buf_map().
udebug_send_and_wait()
__hidden struct udebug_client_msg * udebug_send_and_wait (struct udebug * ctx, struct udebug_client_msg * msg, int * rfd)
Definition at line 810 of file udebug.c.
{
    udebug_send_msg(ctx, msg, NULL, -1);
    return udebug_wait_for_response(ctx, msg, rfd);
}
References ctx, udebug_send_msg(), and udebug_wait_for_response().
Referenced by udebug_remote_buf_map(), and udebug_remote_get_handle().