zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/ubus/ubusd.c File Reference
ubusd.c File Reference
#include <sys/socket.h>
#include "ubusd.h"
Macros
#define USES_EXTERNAL_BUFFER ~0U
Functions
static struct ubus_msg_buf * ubus_msg_ref (struct ubus_msg_buf *ub)
struct ubus_msg_buf * ubus_msg_new (void *data, int len, bool shared)
void ubus_msg_free (struct ubus_msg_buf *ub)
ssize_t ubus_msg_writev (int fd, struct ubus_msg_buf *ub, size_t offset)
void ubus_msg_list_free (struct ubus_msg_buf_list *ubl)
static void ubus_msg_enqueue (struct ubus_client *cl, struct ubus_msg_buf *ub)
void ubus_msg_send (struct ubus_client *cl, struct ubus_msg_buf *ub)
Macro Definition Documentation
USES_EXTERNAL_BUFFER
#define USES_EXTERNAL_BUFFER ~0U
Definition at line 21 of file ubusd.c.
Referenced by ubus_msg_free(), ubus_msg_new(), and ubus_msg_ref().
Function Documentation
ubus_msg_enqueue()
static void ubus_msg_enqueue (struct ubus_client * cl, struct ubus_msg_buf * ub) static
Definition at line 143 of file ubusd.c.
{
    struct ubus_msg_buf_list *ubl;
    if (cl->txq_len + ub->len > UBUS_CLIENT_MAX_TXQ_LEN)
        return;
    ubl = calloc(1, sizeof(struct ubus_msg_buf_list));
    if (!ubl)
        return;
    INIT_LIST_HEAD(&ubl->list);
    ubl->msg = ubus_msg_ref(ub);
    list_add_tail(&ubl->list, &cl->tx_queue);
    cl->txq_len += ub->len;
}
References INIT_LIST_HEAD(), ubus_msg_buf::len, ubus_msg_buf_list::list, list_add_tail(), ubus_msg_buf_list::msg, ubus_client::tx_queue, ubus_client::txq_len, UBUS_CLIENT_MAX_TXQ_LEN, and ubus_msg_ref().
Referenced by ubus_msg_send().
ubus_msg_free()
void ubus_msg_free (struct ubus_msg_buf * ub)
Definition at line 67 of file ubusd.c.
{
    switch (ub->refcount) {
    case 1:
    case USES_EXTERNAL_BUFFER:
        if (ub->fd >= 0)
            close(ub->fd);
        free(ub);
        break;
    default:
        ub->refcount--;
        break;
    }
}
References ubus_msg_buf::fd, ubus_msg_buf::refcount, and USES_EXTERNAL_BUFFER.
Referenced by ubus_client_cmd_free(), ubus_msg_list_free(), ubus_notify_subscription(), ubus_notify_unsubscribe(), ubus_proto_send_msg_from_blob(), ubusd_monitor_message(), ubusd_proto_free_client(), ubusd_proto_receive_message(), ubusd_send_event(), and ubusd_send_hello().
ubus_msg_list_free()
void ubus_msg_list_free (struct ubus_msg_buf_list * ubl)
Definition at line 136 of file ubusd.c.
{
    list_del_init(&ubl->list);
    ubus_msg_free(ubl->msg);
    free(ubl);
}
References ubus_msg_buf_list::list, list_del_init(), ubus_msg_buf_list::msg, and ubus_msg_free().
Referenced by client_cb(), and handle_client_disconnect().
ubus_msg_new()
struct ubus_msg_buf * ubus_msg_new (void * data, int len, bool shared)
Definition at line 39 of file ubusd.c.
{
    struct ubus_msg_buf *ub;
    int buflen = sizeof(*ub);
    if (!shared)
        buflen += len;
    ub = calloc(1, buflen);
    if (!ub)
        return NULL;
    ub->fd = -1;
    if (shared) {
        ub->refcount = USES_EXTERNAL_BUFFER;
        ub->data = data;
    } else {
        ub->refcount = 1;
        ub->data = (void *) (ub + 1);
        if (data)
            memcpy(ub + 1, data, len);
    }
    ub->len = len;
    return ub;
}
References ubus_msg_buf::data, ubus_msg_buf::fd, ubus_msg_buf::len, ubus_msg_buf::refcount, and USES_EXTERNAL_BUFFER.
Referenced by client_cb(), ubus_msg_from_blob(), ubus_msg_ref(), ubusd_create_event_from_msg(), ubusd_create_object_event_msg(), ubusd_create_sequence_event_msg(), ubusd_monitor_message(), and ubusd_proto_init_retmsg().
ubus_msg_ref()
static struct ubus_msg_buf * ubus_msg_ref (struct ubus_msg_buf * ub) static
Definition at line 23 of file ubusd.c.
{
    struct ubus_msg_buf *new_ub;
    if (ub->refcount == USES_EXTERNAL_BUFFER) {
        new_ub = ubus_msg_new(ub->data, ub->len, false);
        if (!new_ub)
            return NULL;
        memcpy(&new_ub->hdr, &ub->hdr, sizeof(struct ubus_msghdr));
        new_ub->fd = ub->fd;
        return new_ub;
    }
    ub->refcount++;
    return ub;
}
References ubus_msg_buf::data, ubus_msg_buf::fd, ubus_msg_buf::hdr, ubus_msg_buf::len, ubus_msg_buf::refcount, ubus_msg_new(), and USES_EXTERNAL_BUFFER.
Referenced by ubus_msg_enqueue().
ubus_msg_send()
void ubus_msg_send (struct ubus_client * cl, struct ubus_msg_buf * ub)
Definition at line 162 of file ubusd.c.
{
    ssize_t written;
    if (ub->hdr.type != UBUS_MSG_MONITOR)
        ubusd_monitor_message(cl, ub, true);
    if (list_empty(&cl->tx_queue)) {
        written = ubus_msg_writev(cl->sock.fd, ub, 0);
        if (written < 0)
            written = 0;
        if (written >= (ssize_t) (ub->len + sizeof(ub->hdr)))
            return;
        cl->txq_ofs = written;
        cl->txq_len = -written;
        /* get an event once we can write to the socket again */
        uloop_fd_add(&cl->sock, ULOOP_READ | ULOOP_WRITE | ULOOP_EDGE_TRIGGER);
    }
    ubus_msg_enqueue(cl, ub);
}
References uloop_fd::fd, ubus_msg_buf::hdr, ubus_msg_buf::len, list_empty(), ubus_client::sock, ubus_client::tx_queue, ubus_client::txq_len, ubus_client::txq_ofs, ubus_msghdr::type, ubus_msg_enqueue(), UBUS_MSG_MONITOR, ubus_msg_writev(), ubusd_monitor_message(), ULOOP_EDGE_TRIGGER, uloop_fd_add(), ULOOP_READ, and ULOOP_WRITE.
Referenced by ubus_notify_subscription(), ubus_notify_unsubscribe(), ubus_proto_send_msg_from_blob(), ubusd_cmd_lookup(), ubusd_handle_response(), ubusd_monitor_message(), ubusd_proto_receive_message(), ubusd_send_event_msg(), ubusd_send_hello(), and ubusd_send_pong().
ubus_msg_writev()
ssize_t ubus_msg_writev (int fd, struct ubus_msg_buf * ub, size_t offset)
Definition at line 83 of file ubusd.c.
{
    uint8_t fd_buf[CMSG_SPACE(sizeof(int))] = { 0 };
    static struct iovec iov[2];
    struct msghdr msghdr = { 0 };
    struct ubus_msghdr hdr;
    struct cmsghdr *cmsg;
    ssize_t ret;
    int *pfd;
    msghdr.msg_iov = iov;
    msghdr.msg_iovlen = ARRAY_SIZE(iov);
    msghdr.msg_control = fd_buf;
    msghdr.msg_controllen = sizeof(fd_buf);
    cmsg = CMSG_FIRSTHDR(&msghdr);
    cmsg->cmsg_type = SCM_RIGHTS;
    cmsg->cmsg_level = SOL_SOCKET;
    cmsg->cmsg_len = CMSG_LEN(sizeof(int));
    pfd = (int *) CMSG_DATA(cmsg);
    msghdr.msg_controllen = cmsg->cmsg_len;
    *pfd = ub->fd;
    if (ub->fd < 0 || offset) {
        msghdr.msg_control = NULL;
        msghdr.msg_controllen = 0;
    }
    if (offset < sizeof(ub->hdr)) {
        hdr.version = ub->hdr.version;
        hdr.type = ub->hdr.type;
        hdr.seq = cpu_to_be16(ub->hdr.seq);
        hdr.peer = cpu_to_be32(ub->hdr.peer);
        iov[0].iov_base = ((char *) &hdr) + offset;
        iov[0].iov_len = sizeof(hdr) - offset;
        iov[1].iov_base = (char *) ub->data;
        iov[1].iov_len = ub->len;
    } else {
        offset -= sizeof(ub->hdr);
        iov[0].iov_base = ((char *) ub->data) + offset;
        iov[0].iov_len = ub->len - offset;
        msghdr.msg_iovlen = 1;
    }
    do {
        ret = sendmsg(fd, &msghdr, 0);
    } while (ret < 0 && errno == EINTR);
    return ret;
}
References ARRAY_SIZE, cpu_to_be16, cpu_to_be32, ubus_msg_buf::data, ubus_msg_buf::fd, ubus_msg_buf::hdr, ubus_msg_buf::len, ubus_msghdr::peer, ubus_msghdr::seq, ubus_msghdr::type, and ubus_msghdr::version.
Referenced by client_cb(), and ubus_msg_send().