zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/libubox/ulog.c File Reference
ulog.c File Reference
#include "ulog.h"
#include <stdio.h>
#include <stdarg.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
Functions
static const char * ulog_default_ident (void)
static void ulog_defaults (void)
__attribute__ ((format(printf, 2, 0)))
void ulog_udebug (struct udebug_buf *_udb)
void ulog_open (int channels, int facility, const char *ident)
void ulog_close (void)
void ulog_threshold (int threshold)
void ulog (int priority, const char *fmt,...)
Variables
static int _ulog_channels = -1
static int _ulog_facility = -1
static int _ulog_threshold = LOG_DEBUG
static int _ulog_initialized = 0
static const char * _ulog_ident = NULL
static struct udebug_buf * udb = NULL
Function Documentation
__attribute__()
__attribute__ ((format(printf, 2, 0)))
Definition at line 91 of file ulog.c.
{
    FILE *kmsg;
    if ((kmsg = fopen("/dev/kmsg", "r+")) != NULL) {
        fprintf(kmsg, "<%u>", priority);
        if (_ulog_ident)
            fprintf(kmsg, "%s: ", _ulog_ident);
        vfprintf(kmsg, fmt, ap);
        fclose(kmsg);
    }
}
References _ulog_ident, and priority.
ulog()
void ulog (int priority, const char * fmt, ...)
Definition at line 154 of file ulog.c.
{
    va_list ap;
    if (udb) {
        va_start(ap, fmt);
        udebug_entry_init(udb);
        udebug_entry_vprintf(udb, fmt, ap);
        udebug_entry_add(udb);
        va_end(ap);
    }
    if (priority > _ulog_threshold)
        return;
    ulog_defaults();
    if (_ulog_channels & ULOG_KMSG)
    {
        va_start(ap, fmt);
        ulog_kmsg(priority, fmt, ap);
        va_end(ap);
    }
    if (_ulog_channels & ULOG_STDIO)
    {
        va_start(ap, fmt);
        ulog_stdio(priority, fmt, ap);
        va_end(ap);
    }
    if (_ulog_channels & ULOG_SYSLOG)
    {
        va_start(ap, fmt);
        ulog_syslog(priority, fmt, ap);
        va_end(ap);
    }
}
References _ulog_channels, _ulog_threshold, priority, udb, udebug_entry_add(), udebug_entry_init(), udebug_entry_vprintf(), ulog_defaults(), ULOG_KMSG, ULOG_STDIO, and ULOG_SYSLOG.
Referenced by instance_console(), instance_console_client(), and instance_stdio().
ulog_close()
void ulog_close (void)
Definition at line 138 of file ulog.c.
{
    if (!_ulog_initialized)
        return;
    if (_ulog_channels & ULOG_SYSLOG)
        closelog();
    _ulog_initialized = 0;
}
References _ulog_channels, _ulog_initialized, and ULOG_SYSLOG.
Referenced by ulog_open().
ulog_default_ident()
static const char * ulog_default_ident (void) static
Definition at line 34 of file ulog.c.
{
    FILE *self;
    static char line[64];
    char *p = NULL;
    char *sbuf;
    if ((self = fopen("/proc/self/status", "r")) != NULL) {
        while (fgets(line, sizeof(line), self)) {
            if (!strncmp(line, "Name:", 5)) {
                strtok_r(line, "\t\n", &sbuf);
                p = strtok_r(NULL, "\t\n", &sbuf);
                break;
            }
        }
        fclose(self);
    }
    return p;
}
Referenced by ulog_defaults().
ulog_defaults()
static void ulog_defaults (void) static
Definition at line 55 of file ulog.c.
{
    char *env;
    if (_ulog_initialized)
        return;
    env = getenv("PREINIT");
    if (_ulog_channels < 0) {
        if (env && !strcmp(env, "1"))
            _ulog_channels = ULOG_KMSG;
        else if (isatty(1))
            _ulog_channels = ULOG_STDIO;
        else
            _ulog_channels = ULOG_SYSLOG;
    }
    if (_ulog_facility < 0) {
        if (env && !strcmp(env, "1"))
            _ulog_facility = LOG_DAEMON;
        else if (isatty(1))
            _ulog_facility = LOG_USER;
        else
            _ulog_facility = LOG_DAEMON;
    }
    if (_ulog_ident == NULL && _ulog_channels != ULOG_STDIO)
        _ulog_ident = ulog_default_ident();
    if (_ulog_channels & ULOG_SYSLOG)
        openlog(_ulog_ident, 0, _ulog_facility);
    _ulog_initialized = 1;
}
References _ulog_channels, _ulog_facility, _ulog_ident, _ulog_initialized, ulog_default_ident(), ULOG_KMSG, ULOG_STDIO, and ULOG_SYSLOG.
Referenced by ulog().
ulog_open()
void ulog_open (int channels, int facility, const char * ident)
Definition at line 129 of file ulog.c.
{
    ulog_close();
    _ulog_channels = channels;
    _ulog_facility = facility;
    _ulog_ident = ident;
}
References _ulog_channels, _ulog_facility, _ulog_ident, and ulog_close().
Referenced by instance_stdio(), main(), and state_enter().
ulog_threshold()
void ulog_threshold (int threshold)
Definition at line 149 of file ulog.c.
{
    _ulog_threshold = threshold;
}
References _ulog_threshold.
Referenced by main().
ulog_udebug()
void ulog_udebug (struct udebug_buf * _udb)
Definition at line 124 of file ulog.c.
{
    udb = _udb;
}
References udb.
Referenced by procd_udebug_set_enabled().
Variable Documentation
_ulog_channels
int _ulog_channels = -1 static
Definition at line 27 of file ulog.c.
Referenced by ulog(), ulog_close(), ulog_defaults(), and ulog_open().
_ulog_facility
int _ulog_facility = -1 static
Definition at line 28 of file ulog.c.
Referenced by ulog_defaults(), and ulog_open().
_ulog_ident
const char* _ulog_ident = NULL static
Definition at line 31 of file ulog.c.
Referenced by __attribute__(), ulog_defaults(), and ulog_open().
_ulog_initialized
int _ulog_initialized = 0 static
Definition at line 30 of file ulog.c.
Referenced by ulog_close(), and ulog_defaults().
_ulog_threshold
int _ulog_threshold = LOG_DEBUG static
Definition at line 29 of file ulog.c.
Referenced by ulog(), and ulog_threshold().
udb
struct udebug_buf* udb = NULL static
Definition at line 32 of file ulog.c.
Referenced by ulog(), and ulog_udebug().