zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/netifd/vlan.c File Reference
vlan.c File Reference
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <ctype.h>
#include "netifd.h"
#include "system.h"
Classes
struct vlan_device
Functions
static void free_vlan_if (struct device *iface)
static int __vlan_hotplug_op (struct device *dev, struct device *member, struct blob_attr *vlan, bool add)
static int vlan_hotplug_add (struct device *dev, struct device *member, struct blob_attr *vlan)
static int vlan_hotplug_del (struct device *dev, struct device *member, struct blob_attr *vlan)
static int vlan_hotplug_prepare (struct device *dev, struct device **bridge_dev)
static void vlan_hotplug_check (struct vlan_device *vldev, struct device *dev)
static int vlan_set_device_state (struct device *dev, bool up)
static void vlan_dev_cb (struct device_user *dep, enum device_event ev)
static void vlan_config_init (struct device *dev)
static struct device * get_vlan_device (struct device *dev, char *id_str, bool create)
static char * split_vlan (char *s)
struct device * get_vlan_device_chain (const char *ifname, int create)
Variables
static struct blob_buf b
Class Documentation
vlan_device
struct vlan_device
Definition at line 24 of file vlan.c.
Class Members
struct device_user dep
struct device dev
int id
device_state_cb set_state
Function Documentation
__vlan_hotplug_op()
static int __vlan_hotplug_op (struct device * dev, struct device * member, struct blob_attr * vlan, bool add) static
Definition at line 43 of file vlan.c.
{
    struct vlan_device *vldev = container_of(dev, struct vlan_device, dev);
    void *a;
    dev = vldev->dep.dev;
    if (!dev || !dev->hotplug_ops)
        return UBUS_STATUS_NOT_SUPPORTED;
    blob_buf_init(&b, 0);
    a = blobmsg_open_array(&b, "vlans");
    blobmsg_printf(&b, NULL, "%d:u", vldev->id);
    if (vlan && blobmsg_len(vlan))
        blob_put_raw(&b, blobmsg_data(vlan), blobmsg_len(vlan));
    blobmsg_close_array(&b, a);
    if (add)
        return dev->hotplug_ops->add(dev, member, blobmsg_data(b.head));
    else
        return dev->hotplug_ops->del(dev, member, blobmsg_data(b.head));
}
References device_hotplug_ops::add, b, blob_buf_init(), blob_put_raw(), blobmsg_close_array(), blobmsg_data(), blobmsg_len(), blobmsg_open_array(), blobmsg_printf(), container_of, device_hotplug_ops::del, vlan_device::dep, device_user::dev, vlan_device::dev, blob_buf::head, device::hotplug_ops, vlan_device::id, and UBUS_STATUS_NOT_SUPPORTED.
Referenced by vlan_hotplug_add(), and vlan_hotplug_del().
free_vlan_if()
static void free_vlan_if (struct device * iface) static
Definition at line 32 of file vlan.c.
{
    struct vlan_device *vldev;
    vldev = container_of(iface, struct vlan_device, dev);
    device_remove_user(&vldev->dep);
    device_cleanup(&vldev->dev);
    free(vldev);
}
References container_of, vlan_device::dep, vlan_device::dev, device_cleanup(), and device_remove_user().
Referenced by get_vlan_device(), and vlan_dev_cb().
get_vlan_device()
static struct device * get_vlan_device (struct device * dev, char * id_str, bool create) static
Definition at line 170 of file vlan.c.
{
    static struct device_type vlan_type = {
        .name = "VLAN",
        .config_params = &device_attr_list,
        .config_init = vlan_config_init,
        .free = free_vlan_if,
    };
    struct vlan_device *vldev;
    struct device_user *dep;
    char name[IFNAMSIZ];
    char *err = NULL;
    int id, *alias_id;
    id = strtoul(id_str, &err, 10);
    if (err && *err) {
        alias_id = kvlist_get(&dev->vlan_aliases, id_str);
        if (!alias_id)
            return NULL;
        id = *alias_id;
    }
    /* look for an existing interface before creating a new one */
    list_for_each_entry(dep, &dev->users.list, list.list) {
        if (dep->cb != vlan_dev_cb)
            continue;
        vldev = container_of(dep, struct vlan_device, dep);
        if (vldev->id != id)
            continue;
        return &vldev->dev;
    }
    if (!create)
        return NULL;
    if (snprintf(name, sizeof(name), "%s.%d", dev->ifname, id) >= (int)sizeof(name) - 1)
        return NULL;
    D(DEVICE, "Create vlan device '%s'", name);
    vldev = calloc(1, sizeof(*vldev));
    if (!vldev)
        return NULL;
    vldev->id = id;
    vldev->dev.hidden = dev->hidden;
    strcpy(vldev->dev.ifname, name);
    if (device_init(&vldev->dev, &vlan_type, NULL) < 0)
        goto error;
    vldev->dev.default_config = true;
    vldev->dev.config_pending = true;
    vldev->set_state = vldev->dev.set_state;
    vldev->dev.set_state = vlan_set_device_state;
    vldev->dep.cb = vlan_dev_cb;
    vlan_hotplug_check(vldev, vldev->dep.dev);
    device_add_user(&vldev->dep, dev);
    return &vldev->dev;
error:
    device_cleanup(&vldev->dev);
    free(vldev);
    return NULL;
}
References device_user::cb, device::config_pending, container_of, D, device::default_config, vlan_device::dep, device_user::dev, vlan_device::dev, device_add_user(), device_attr_list, device_cleanup(), device_init(), err, free_vlan_if(), device::hidden, id, vlan_device::id, device::ifname, kvlist_get(), device_user::list, safe_list::list, list_for_each_entry, device::set_state, vlan_device::set_state, device::users, device::vlan_aliases, vlan_config_init(), vlan_dev_cb(), vlan_hotplug_check(), and vlan_set_device_state().
Referenced by get_vlan_device_chain().
get_vlan_device_chain()
struct device * get_vlan_device_chain (const char * ifname, int create)
Definition at line 254 of file vlan.c.
{
    struct device *dev = NULL, *vldev;
    char *buf, *s, *next;
    buf = strdup(ifname);
    if (!buf)
        return NULL;
    s = split_vlan(buf);
    dev = __device_get(buf, create, false);
    if (!dev || !s)
        goto out;
    /* for the first split, we need to check if we're using an alias or
     * if the . separator isn't being used as a vlan separator (e.g. for
     * AP WDS VLANs */
    if (!isdigit(s[0])) {
        next = split_vlan(s);
        vldev = get_vlan_device(dev, s, create);
        if (!vldev) {
            s[-1] = '.';
            dev = __device_get(buf, create, false);
            if (!dev)
                goto out;
            if (next)
                next[-1] = '.';
        } else {
            dev = vldev;
            s = next;
        }
    }
    while (s) {
        next = split_vlan(s);
        dev = get_vlan_device(dev, s, create);
        if (!dev)
            break;
        s = next;
    }
out:
    free(buf);
    return dev;
}
References __device_get(), buf, get_vlan_device(), ifname, and split_vlan().
Referenced by __device_get().
split_vlan()
static char * split_vlan (char * s) static
Definition at line 242 of file vlan.c.
{
    s = strchr(s, '.');
    if (!s)
        return NULL;
    *s = 0;
    s++;
    return s;
}
Referenced by get_vlan_device_chain().
vlan_config_init()
static void vlan_config_init (struct device * dev) static
Definition at line 162 of file vlan.c.
{
    struct vlan_device *vldev;
    vldev = container_of(dev, struct vlan_device, dev);
    vlan_hotplug_check(vldev, vldev->dep.dev);
}
References container_of, vlan_device::dep, device_user::dev, vlan_device::dev, and vlan_hotplug_check().
Referenced by get_vlan_device().
vlan_dev_cb()
static void vlan_dev_cb (struct device_user * dep, enum device_event ev) static
Definition at line 131 of file vlan.c.
{
    char name[IFNAMSIZ];
    struct vlan_device *vldev;
    vldev = container_of(dep, struct vlan_device, dep);
    switch(ev) {
    case DEV_EVENT_ADD:
        device_set_present(&vldev->dev, true);
        break;
    case DEV_EVENT_REMOVE:
        device_set_present(&vldev->dev, false);
        break;
    case DEV_EVENT_UPDATE_IFNAME:
        vlan_hotplug_check(vldev, dep->dev);
        vldev->dev.hidden = dep->dev->hidden;
        if (snprintf(name, sizeof(name), "%s.%d", dep->dev->ifname,
                 vldev->id) >= (int)sizeof(name) - 1 ||
            device_set_ifname(&vldev->dev, name))
            free_vlan_if(&vldev->dev);
        break;
    case DEV_EVENT_TOPO_CHANGE:
        /* Propagate topo changes */
        device_broadcast_event(&vldev->dev, DEV_EVENT_TOPO_CHANGE);
        break;
    default:
        break;
    }
}
References container_of, vlan_device::dep, device_user::dev, vlan_device::dev, DEV_EVENT_ADD, DEV_EVENT_REMOVE, DEV_EVENT_TOPO_CHANGE, DEV_EVENT_UPDATE_IFNAME, device_broadcast_event, device_set_ifname(), device_set_present, free_vlan_if(), device::hidden, vlan_device::id, device::ifname, and vlan_hotplug_check().
Referenced by get_vlan_device().
vlan_hotplug_add()
static int vlan_hotplug_add (struct device * dev, struct device * member, struct blob_attr * vlan) static
Definition at line 66 of file vlan.c.
{
    return __vlan_hotplug_op(dev, member, vlan, true);
}
References __vlan_hotplug_op(), and vlan_device::dev.
Referenced by vlan_hotplug_check().
vlan_hotplug_check()
static void vlan_hotplug_check (struct vlan_device * vldev, struct device * dev) static
Definition at line 89 of file vlan.c.
{
    static const struct device_hotplug_ops hotplug_ops = {
        .prepare = vlan_hotplug_prepare,
        .add = vlan_hotplug_add,
        .del = vlan_hotplug_del
    };
    if (!dev || !dev->hotplug_ops || avl_is_empty(&dev->vlans.avl)) {
        vldev->dev.hotplug_ops = NULL;
        return;
    }
    vldev->dev.hotplug_ops = &hotplug_ops;
}
References vlist_tree::avl, avl_is_empty(), vlan_device::dev, device::hotplug_ops, vlan_hotplug_add(), vlan_hotplug_del(), vlan_hotplug_prepare(), and device::vlans.
Referenced by get_vlan_device(), vlan_config_init(), and vlan_dev_cb().
vlan_hotplug_del()
static int vlan_hotplug_del (struct device * dev, struct device * member, struct blob_attr * vlan) static
Definition at line 72 of file vlan.c.
{
    return __vlan_hotplug_op(dev, member, vlan, false);
}
References __vlan_hotplug_op(), and vlan_device::dev.
Referenced by vlan_hotplug_check().
vlan_hotplug_prepare()
static int vlan_hotplug_prepare (struct device * dev, struct device ** bridge_dev) static
Definition at line 78 of file vlan.c.
{
    struct vlan_device *vldev = container_of(dev, struct vlan_device, dev);
    dev = vldev->dep.dev;
    if (!dev || !dev->hotplug_ops)
        return UBUS_STATUS_NOT_SUPPORTED;
    return dev->hotplug_ops->prepare(dev, bridge_dev);
}
References container_of, vlan_device::dep, device_user::dev, vlan_device::dev, device::hotplug_ops, device_hotplug_ops::prepare, and UBUS_STATUS_NOT_SUPPORTED.
Referenced by vlan_hotplug_check().
vlan_set_device_state()
static int vlan_set_device_state (struct device * dev, bool up) static
Definition at line 106 of file vlan.c.
{
    struct vlan_device *vldev;
    int ret = 0;
    vldev = container_of(dev, struct vlan_device, dev);
    if (!up) {
        vldev->set_state(dev, false);
        system_vlan_del(dev);
        device_release(&vldev->dep);
        return 0;
    }
    ret = device_claim(&vldev->dep);
    if (ret < 0)
        return ret;
    system_vlan_add(vldev->dep.dev, vldev->id);
    ret = vldev->set_state(dev, true);
    if (ret)
        device_release(&vldev->dep);
    return ret;
}
References container_of, vlan_device::dep, device_user::dev, vlan_device::dev, device_claim(), device_release(), vlan_device::id, vlan_device::set_state, system_vlan_add(), and system_vlan_del().
Referenced by get_vlan_device().
Variable Documentation
b
struct blob_buf b static
Definition at line 22 of file vlan.c.
Referenced by __vlan_hotplug_op().