zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/libubox/lua/uloop.c File Reference
uloop.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <lua.h>
#include <lualib.h>
#include <lauxlib.h>
#include "../uloop.h"
#include "../list.h"
Classes
struct lua_uloop_fd
struct lua_uloop_timeout
struct lua_uloop_process
struct lua_uloop_interval
struct lua_uloop_signal
Macros
#define SIGNAME_CONST(signame)
Functions
static void * ul_create_userdata (lua_State *L, size_t size, const luaL_Reg *reg, lua_CFunction gc)
static void ul_timer_cb (struct uloop_timeout *t)
static int ul_timer_set (lua_State *L)
static int ul_timer_remaining (lua_State *L)
static int ul_timer_free (lua_State *L)
static int ul_timer (lua_State *L)
static void ul_ufd_cb (struct uloop_fd *fd, unsigned int events)
static int get_sock_fd (lua_State *L, int idx)
static int ul_ufd_delete (lua_State *L)
static int ul_ufd_add (lua_State *L)
static int ul_process_free (lua_State *L)
static int ul_process_pid (lua_State *L)
static void ul_process_cb (struct uloop_process *p, int ret)
static int ul_process (lua_State *L)
static void ul_interval_cb (struct uloop_interval *i)
static int ul_interval_set (lua_State *L)
static int ul_interval_expirations (lua_State *L)
static int ul_interval_remaining (lua_State *L)
static int ul_interval_free (lua_State *L)
static int ul_interval (lua_State *L)
static void ul_signal_cb (struct uloop_signal *s)
static int ul_signal_signo (lua_State *L)
static int ul_signal_free (lua_State *L)
static int ul_signal (lua_State *L)
static int ul_init (lua_State *L)
static int ul_run (lua_State *L)
static int ul_end (lua_State *L)
int luaopen_uloop (lua_State *L)
int luaclose_uloop (lua_State *L)
Variables
static lua_State * state
static const luaL_Reg timer_m []
static const luaL_Reg ufd_m []
static const luaL_Reg process_m []
static const luaL_Reg interval_m []
static const luaL_Reg signal_m []
static luaL_reg uloop_func []
Class Documentation
lua_uloop_fd
struct lua_uloop_fd
Definition at line 28 of file uloop.c.
Class Members
struct uloop_fd fd
int fd_r
int r
lua_uloop_timeout
struct lua_uloop_timeout
Definition at line 34 of file uloop.c.
Class Members
int r
struct uloop_timeout t
lua_uloop_process
struct lua_uloop_process
Definition at line 39 of file uloop.c.
Class Members
struct uloop_process p
int r
lua_uloop_interval
struct lua_uloop_interval
Definition at line 44 of file uloop.c.
Class Members
struct uloop_interval i
int r
lua_uloop_signal
struct lua_uloop_signal
Definition at line 49 of file uloop.c.
Class Members
int r
struct uloop_signal s
Macro Definition Documentation
SIGNAME_CONST
#define SIGNAME_CONST (signame)
Value:
    do { \
    lua_pushstring(L, #signame);    \
    lua_pushinteger(L, signame);    \
    lua_rawset(L, -3);              \
} while(0)
Referenced by luaopen_uloop().
Function Documentation
get_sock_fd()
static int get_sock_fd (lua_State * L, int idx) static
Definition at line 192 of file uloop.c.
{
    int fd;
    if(lua_isnumber(L, idx)) {
        fd = lua_tonumber(L, idx);
    } else {
        luaL_checktype(L, idx, LUA_TUSERDATA);
        lua_getfield(L, idx, "getfd");
        if(lua_isnil(L, -1))
            return luaL_error(L, "socket type missing 'getfd' method");
        /* if we have absolute, no need to adjust for getfield() call */
        lua_pushvalue(L, idx > 0 ? idx: idx - 1);
        lua_call(L, 1, 1);
        fd = lua_tointeger(L, -1);
        lua_pop(L, 1);
    }
    return fd;
}
References lua_uloop_fd::fd.
Referenced by ul_ufd_add().
luaclose_uloop()
int luaclose_uloop (lua_State * L)
Definition at line 747 of file uloop.c.
{
    lua_pushstring(L, "Called");
    return 1;
}
luaopen_uloop()
int luaopen_uloop (lua_State * L)
Definition at line 616 of file uloop.c.
{
    state = L;
    lua_createtable(L, 1, 0);
    lua_setglobal(L, "__uloop_cb");
    lua_createtable(L, 1, 0);
    lua_setglobal(L, "__uloop_fds");
    luaL_openlib(L, "uloop", uloop_func, 0);
    lua_pushstring(L, "_VERSION");
    lua_pushstring(L, "1.0");
    lua_rawset(L, -3);
    lua_pushstring(L, "ULOOP_READ");
    lua_pushinteger(L, ULOOP_READ);
    lua_rawset(L, -3);
    lua_pushstring(L, "ULOOP_WRITE");
    lua_pushinteger(L, ULOOP_WRITE);
    lua_rawset(L, -3);
    lua_pushstring(L, "ULOOP_EDGE_TRIGGER");
    lua_pushinteger(L, ULOOP_EDGE_TRIGGER);
    lua_rawset(L, -3);
    lua_pushstring(L, "ULOOP_BLOCKING");
    lua_pushinteger(L, ULOOP_BLOCKING);
    lua_rawset(L, -3);
#define SIGNAME_CONST(signame) do { \
    lua_pushstring(L, #signame);    \
    lua_pushinteger(L, signame);    \
    lua_rawset(L, -3);              \
} while(0)
#if defined(SIGINT)
    SIGNAME_CONST(SIGINT);
#endif
#if defined(SIGILL)
    SIGNAME_CONST(SIGILL);
#endif
#if defined(SIGABRT)
    SIGNAME_CONST(SIGABRT);
#endif
#if defined(SIGFPE)
    SIGNAME_CONST(SIGFPE);
#endif
#if defined(SIGSEGV)
    SIGNAME_CONST(SIGSEGV);
#endif
#if defined(SIGTERM)
    SIGNAME_CONST(SIGTERM);
#endif
#if defined(SIGHUP)
    SIGNAME_CONST(SIGHUP);
#endif
#if defined(SIGQUIT)
    SIGNAME_CONST(SIGQUIT);
#endif
#if defined(SIGTRAP)
    SIGNAME_CONST(SIGTRAP);
#endif
#if defined(SIGKILL)
    SIGNAME_CONST(SIGKILL);
#endif
#if defined(SIGPIPE)
    SIGNAME_CONST(SIGPIPE);
#endif
#if defined(SIGALRM)
    SIGNAME_CONST(SIGALRM);
#endif
#if defined(SIGSTKFLT)
    SIGNAME_CONST(SIGSTKFLT);
#endif
#if defined(SIGPWR)
    SIGNAME_CONST(SIGPWR);
#endif
#if defined(SIGBUS)
    SIGNAME_CONST(SIGBUS);
#endif
#if defined(SIGSYS)
    SIGNAME_CONST(SIGSYS);
#endif
#if defined(SIGURG)
    SIGNAME_CONST(SIGURG);
#endif
#if defined(SIGSTOP)
    SIGNAME_CONST(SIGSTOP);
#endif
#if defined(SIGTSTP)
    SIGNAME_CONST(SIGTSTP);
#endif
#if defined(SIGCONT)
    SIGNAME_CONST(SIGCONT);
#endif
#if defined(SIGCHLD)
    SIGNAME_CONST(SIGCHLD);
#endif
#if defined(SIGTTIN)
    SIGNAME_CONST(SIGTTIN);
#endif
#if defined(SIGTTOU)
    SIGNAME_CONST(SIGTTOU);
#endif
#if defined(SIGPOLL)
    SIGNAME_CONST(SIGPOLL);
#endif
#if defined(SIGXFSZ)
    SIGNAME_CONST(SIGXFSZ);
#endif
#if defined(SIGXCPU)
    SIGNAME_CONST(SIGXCPU);
#endif
#if defined(SIGVTALRM)
    SIGNAME_CONST(SIGVTALRM);
#endif
#if defined(SIGPROF)
    SIGNAME_CONST(SIGPROF);
#endif
#if defined(SIGUSR1)
    SIGNAME_CONST(SIGUSR1);
#endif
#if defined(SIGUSR2)
    SIGNAME_CONST(SIGUSR2);
#endif
    return 1;
}
References SIGNAME_CONST, state, ULOOP_BLOCKING, ULOOP_EDGE_TRIGGER, uloop_func, ULOOP_READ, and ULOOP_WRITE.
ul_create_userdata()
static void * ul_create_userdata (lua_State * L, size_t size, const luaL_Reg * reg, lua_CFunction gc) static
Definition at line 57 of file uloop.c.
{
    void *ret = lua_newuserdata(L, size);
    memset(ret, 0, size);
    lua_createtable(L, 0, 2);
    lua_pushvalue(L, -1);
    lua_setfield(L, -2, "__index");
    lua_pushcfunction(L, gc);
    lua_setfield(L, -2, "__gc");
    lua_pushvalue(L, -1);
    lua_setmetatable(L, -3);
    lua_pushvalue(L, -2);
    luaI_openlib(L, NULL, reg, 1);
    lua_pushvalue(L, -2);
    return ret;
}
Referenced by ul_interval(), ul_process(), ul_signal(), ul_timer(), and ul_ufd_add().
ul_end()
static int ul_end (lua_State * L) static
Definition at line 594 of file uloop.c.
{
    uloop_end();
    return 1;
}
References uloop_end().
ul_init()
static int ul_init (lua_State * L) static
Definition at line 578 of file uloop.c.
{
    uloop_init();
    lua_pushboolean(L, 1);
    return 1;
}
References uloop_init().
ul_interval()
static int ul_interval (lua_State * L) static
Definition at line 469 of file uloop.c.
{
    struct lua_uloop_interval *intv;
    unsigned int set = 0;
    int ref;
    if (lua_isnumber(L, -1)) {
        set = lua_tointeger(L, -1);
        lua_pop(L, 1);
    }
    if (!lua_isfunction(L, -1)) {
        lua_pushstring(L, "invalid arg list");
        lua_error(L);
        return 0;
    }
    lua_getglobal(L, "__uloop_cb");
    lua_pushvalue(L, -2);
    ref = luaL_ref(L, -2);
    intv = ul_create_userdata(L, sizeof(*intv), interval_m, ul_interval_free);
    intv->r = ref;
    intv->i.cb = ul_interval_cb;
    if (set)
        uloop_interval_set(&intv->i, set);
    return 1;
}
References uloop_interval::cb, lua_uloop_interval::i, interval_m, lua_uloop_interval::r, ul_create_userdata(), ul_interval_cb(), ul_interval_free(), and uloop_interval_set().
ul_interval_cb()
static void ul_interval_cb (struct uloop_interval * i) static
Definition at line 395 of file uloop.c.
{
    struct lua_uloop_interval *intv = container_of(i, struct lua_uloop_interval, i);
    lua_getglobal(state, "__uloop_cb");
    lua_rawgeti(state, -1, intv->r);
    lua_remove(state, -2);
    lua_call(state, 0, 0);
}
References container_of, lua_uloop_interval::i, lua_uloop_interval::r, and state.
Referenced by ul_interval().
ul_interval_expirations()
static int ul_interval_expirations (lua_State * L) static
Definition at line 425 of file uloop.c.
{
    struct lua_uloop_interval *intv;
    intv = lua_touserdata(L, 1);
    lua_pushinteger(L, intv->i.expirations);
    return 1;
}
References uloop_interval::expirations, and lua_uloop_interval::i.
ul_interval_free()
static int ul_interval_free (lua_State * L) static
Definition at line 443 of file uloop.c.
{
    struct lua_uloop_interval *intv = lua_touserdata(L, 1);
    uloop_interval_cancel(&intv->i);
    /* obj.__index.__gc = nil , make sure executing only once*/
    lua_getfield(L, -1, "__index");
    lua_pushstring(L, "__gc");
    lua_pushnil(L);
    lua_settable(L, -3);
    lua_getglobal(state, "__uloop_cb");
    luaL_unref(state, -1, intv->r);
    return 1;
}
References lua_uloop_interval::i, lua_uloop_interval::r, state, and uloop_interval_cancel().
Referenced by ul_interval().
ul_interval_remaining()
static int ul_interval_remaining (lua_State * L) static
Definition at line 434 of file uloop.c.
{
    struct lua_uloop_interval *intv;
    intv = lua_touserdata(L, 1);
    lua_pushnumber(L, uloop_interval_remaining(&intv->i));
    return 1;
}
References lua_uloop_interval::i, and uloop_interval_remaining().
ul_interval_set()
static int ul_interval_set (lua_State * L) static
Definition at line 406 of file uloop.c.
{
    struct lua_uloop_interval *intv;
    double set;
    if (!lua_isnumber(L, -1)) {
        lua_pushstring(L, "invalid arg list");
        lua_error(L);
        return 0;
    }
    set = lua_tointeger(L, -1);
    intv = lua_touserdata(L, 1);
    uloop_interval_set(&intv->i, set);
    return 1;
}
References lua_uloop_interval::i, and uloop_interval_set().
ul_process()
static int ul_process (lua_State * L) static
Definition at line 329 of file uloop.c.
{
    struct lua_uloop_process *proc;
    pid_t pid;
    int ref;
    if (!lua_isfunction(L, -1) || !lua_istable(L, -2) ||
            !lua_istable(L, -3) || !lua_isstring(L, -4)) {
        lua_pushstring(L, "invalid arg list");
        lua_error(L);
        return 0;
    }
    pid = fork();
    if (pid == -1) {
        lua_pushstring(L, "failed to fork");
        lua_error(L);
        return 0;
    }
    if (pid == 0) {
        /* child */
        int argn = lua_objlen(L, -3);
        int envn = lua_objlen(L, -2);
        char** argp = malloc(sizeof(char*) * (argn + 2));
        char** envp = malloc(sizeof(char*) * (envn + 1));
        int i = 1;
        if (!argp || !envp)
            _exit(-1);
        argp[0] = (char*) lua_tostring(L, -4);
        for (i = 1; i <= argn; i++) {
            lua_rawgeti(L, -3, i);
            argp[i] = (char*) lua_tostring(L, -1);
            lua_pop(L, 1);
        }
        argp[i] = NULL;
        for (i = 1; i <= envn; i++) {
            lua_rawgeti(L, -2, i);
            envp[i - 1] = (char*) lua_tostring(L, -1);
            lua_pop(L, 1);
        }
        envp[i - 1] = NULL;
        execve(*argp, argp, envp);
        _exit(-1);
    }
    lua_getglobal(L, "__uloop_cb");
    lua_pushvalue(L, -2);
    ref = luaL_ref(L, -2);
    proc = ul_create_userdata(L, sizeof(*proc), process_m, ul_process_free);
    proc->r = ref;
    proc->p.pid = pid;
    proc->p.cb = ul_process_cb;
    uloop_process_add(&proc->p);
    return 1;
}
References uloop_process::cb, lua_uloop_process::p, uloop_process::pid, process_m, lua_uloop_process::r, ul_create_userdata(), ul_process_cb(), ul_process_free(), and uloop_process_add().
ul_process_cb()
static void ul_process_cb (struct uloop_process * p, int ret) static
Definition at line 315 of file uloop.c.
{
    struct lua_uloop_process *proc = container_of(p, struct lua_uloop_process, p);
    lua_getglobal(state, "__uloop_cb");
    lua_rawgeti(state, -1, proc->r);
    luaL_unref(state, -2, proc->r);
    proc->r = LUA_NOREF;
    lua_remove(state, -2);
    lua_pushinteger(state, ret >> 8);
    lua_call(state, 1, 0);
}
References container_of, lua_uloop_process::p, lua_uloop_process::r, and state.
Referenced by ul_process().
ul_process_free()
static int ul_process_free (lua_State * L) static
Definition at line 276 of file uloop.c.
{
    struct lua_uloop_process *proc = lua_touserdata(L, 1);
    /* obj.__index.__gc = nil , make sure executing only once*/
    lua_getfield(L, -1, "__index");
    lua_pushstring(L, "__gc");
    lua_pushnil(L);
    lua_settable(L, -3);
    if (proc->r != LUA_NOREF) {
        uloop_process_delete(&proc->p);
        lua_getglobal(state, "__uloop_cb");
        luaL_unref(state, -1, proc->r);
        lua_remove(state, -1);
    }
    return 1;
}
References lua_uloop_process::p, lua_uloop_process::r, state, and uloop_process_delete().
Referenced by ul_process().
ul_process_pid()
static int ul_process_pid (lua_State * L) static
Definition at line 297 of file uloop.c.
{
    struct lua_uloop_process *proc = lua_touserdata(L, 1);
    if (proc->p.pid) {
        lua_pushnumber(L, proc->p.pid);
        return 1;
    }
    return 0;
}
References lua_uloop_process::p, and uloop_process::pid.
ul_run()
static int ul_run (lua_State * L) static
Definition at line 586 of file uloop.c.
{
    uloop_run();
    lua_pushboolean(L, 1);
    return 1;
}
References uloop_run().
ul_signal()
static int ul_signal (lua_State * L) static
Definition at line 546 of file uloop.c.
{
    struct lua_uloop_signal *sig;
    int signo = -1;
    int ref;
    if (lua_isnumber(L, -1)) {
        signo = lua_tointeger(L, -1);
        lua_pop(L, 1);
    }
    if (!lua_isfunction(L, -1) || signo <= 0 || signo > NSIG) {
        lua_pushstring(L, "invalid arg list");
        lua_error(L);
        return 0;
    }
    lua_getglobal(L, "__uloop_cb");
    lua_pushvalue(L, -2);
    ref = luaL_ref(L, -2);
    sig = ul_create_userdata(L, sizeof(*sig), signal_m, ul_signal_free);
    sig->r = ref;
    sig->s.cb = ul_signal_cb;
    sig->s.signo = signo;
    uloop_signal_add(&sig->s);
    return 1;
}
References uloop_signal::cb, lua_uloop_signal::r, lua_uloop_signal::s, signal_m, uloop_signal::signo, ul_create_userdata(), ul_signal_cb(), ul_signal_free(), and uloop_signal_add().
ul_signal_cb()
static void ul_signal_cb (struct uloop_signal * s) static
Definition at line 501 of file uloop.c.
{
    struct lua_uloop_signal *sig = container_of(s, struct lua_uloop_signal, s);
    lua_getglobal(state, "__uloop_cb");
    lua_rawgeti(state, -1, sig->r);
    lua_remove(state, -2);
    lua_pushinteger(state, sig->s.signo);
    lua_call(state, 1, 0);
}
References container_of, lua_uloop_signal::r, lua_uloop_signal::s, uloop_signal::signo, and state.
Referenced by ul_signal().
ul_signal_free()
static int ul_signal_free (lua_State * L) static
Definition at line 522 of file uloop.c.
{
    struct lua_uloop_signal *sig = lua_touserdata(L, 1);
    uloop_signal_delete(&sig->s);
    /* obj.__index.__gc = nil , make sure executing only once*/
    lua_getfield(L, -1, "__index");
    lua_pushstring(L, "__gc");
    lua_pushnil(L);
    lua_settable(L, -3);
    lua_getglobal(state, "__uloop_cb");
    luaL_unref(state, -1, sig->r);
    return 1;
}
References lua_uloop_signal::r, lua_uloop_signal::s, state, and uloop_signal_delete().
Referenced by ul_signal().
ul_signal_signo()
static int ul_signal_signo (lua_State * L) static
Definition at line 513 of file uloop.c.
{
    struct lua_uloop_signal *sig = lua_touserdata(L, 1);
    lua_pushinteger(L, sig->s.signo);
    return 1;
}
References lua_uloop_signal::s, and uloop_signal::signo.
ul_timer()
static int ul_timer (lua_State * L) static
Definition at line 141 of file uloop.c.
{
    struct lua_uloop_timeout *tout;
    int set = 0;
    int ref;
    if (lua_isnumber(L, -1)) {
        set = lua_tointeger(L, -1);
        lua_pop(L, 1);
    }
    if (!lua_isfunction(L, -1)) {
        lua_pushstring(L, "invalid arg list");
        lua_error(L);
        return 0;
    }
    lua_getglobal(L, "__uloop_cb");
    lua_pushvalue(L, -2);
    ref = luaL_ref(L, -2);
    tout = ul_create_userdata(L, sizeof(*tout), timer_m, ul_timer_free);
    tout->r = ref;
    tout->t.cb = ul_timer_cb;
    if (set)
        uloop_timeout_set(&tout->t, set);
    return 1;
}
References uloop_timeout::cb, lua_uloop_timeout::r, lua_uloop_timeout::t, timer_m, ul_create_userdata(), ul_timer_cb(), ul_timer_free(), and uloop_timeout_set().
ul_timer_cb()
static void ul_timer_cb (struct uloop_timeout * t) static
Definition at line 76 of file uloop.c.
{
    struct lua_uloop_timeout *tout = container_of(t, struct lua_uloop_timeout, t);
    lua_getglobal(state, "__uloop_cb");
    lua_rawgeti(state, -1, tout->r);
    lua_remove(state, -2);
    lua_call(state, 0, 0);
}
References container_of, lua_uloop_timeout::r, state, and lua_uloop_timeout::t.
Referenced by ul_timer().
ul_timer_free()
static int ul_timer_free (lua_State * L) static
Definition at line 116 of file uloop.c.
{
    struct lua_uloop_timeout *tout = lua_touserdata(L, 1);
    uloop_timeout_cancel(&tout->t);
    /* obj.__index.__gc = nil , make sure executing only once*/
    lua_getfield(L, -1, "__index");
    lua_pushstring(L, "__gc");
    lua_pushnil(L);
    lua_settable(L, -3);
    lua_getglobal(state, "__uloop_cb");
    luaL_unref(state, -1, tout->r);
    return 1;
}
References lua_uloop_timeout::r, state, lua_uloop_timeout::t, and uloop_timeout_cancel().
Referenced by ul_timer().
ul_timer_remaining()
static int ul_timer_remaining (lua_State * L) static
Definition at line 107 of file uloop.c.
{
    struct lua_uloop_timeout *tout;
    tout = lua_touserdata(L, 1);
    lua_pushnumber(L, uloop_timeout_remaining64(&tout->t));
    return 1;
}
References lua_uloop_timeout::t, and uloop_timeout_remaining64().
ul_timer_set()
static int ul_timer_set (lua_State * L) static
Definition at line 88 of file uloop.c.
{
    struct lua_uloop_timeout *tout;
    double set;
    if (!lua_isnumber(L, -1)) {
        lua_pushstring(L, "invalid arg list");
        lua_error(L);
        return 0;
    }
    set = lua_tointeger(L, -1);
    tout = lua_touserdata(L, 1);
    uloop_timeout_set(&tout->t, set);
    return 1;
}
References lua_uloop_timeout::t, and uloop_timeout_set().
ul_ufd_add()
static int ul_ufd_add (lua_State * L) static
Definition at line 238 of file uloop.c.
{
    struct lua_uloop_fd *ufd;
    int fd = 0;
    unsigned int flags = 0;
    int ref;
    int fd_ref;
    flags = luaL_checkinteger(L, 3);
    if (!flags) {
        lua_pushstring(L, "flags cannot be zero");
        lua_error(L);
    }
    luaL_checktype(L, 2, LUA_TFUNCTION);
    fd = get_sock_fd(L, 1);
    lua_getglobal(L, "__uloop_cb");
    lua_pushvalue(L, 2);
    ref = luaL_ref(L, -2);
    lua_pop(L, 1);
    lua_getglobal(L, "__uloop_fds");
    lua_pushvalue(L, 1);
    fd_ref = luaL_ref(L, -2);
    lua_pop(L, 1);
    ufd = ul_create_userdata(L, sizeof(*ufd), ufd_m, ul_ufd_delete);
    ufd->r = ref;
    ufd->fd.fd = fd;
    ufd->fd_r = fd_ref;
    ufd->fd.cb = ul_ufd_cb;
    uloop_fd_add(&ufd->fd, flags);
    return 1;
}
References lua_uloop_fd::fd, uloop_fd::fd, get_sock_fd(), ufd, ufd_m, ul_create_userdata(), ul_ufd_cb(), ul_ufd_delete(), and uloop_fd_add().
ul_ufd_cb()
static void ul_ufd_cb (struct uloop_fd * fd, unsigned int events) static
Definition at line 173 of file uloop.c.
{
    struct lua_uloop_fd *ufd = container_of(fd, struct lua_uloop_fd, fd);
    lua_getglobal(state, "__uloop_cb");
    lua_rawgeti(state, -1, ufd->r);
    lua_remove(state, -2);
    /* push fd object */
    lua_getglobal(state, "__uloop_fds");
    lua_rawgeti(state, -1, ufd->fd_r);
    lua_remove(state, -2);
    /* push events */
    lua_pushinteger(state, events);
    lua_call(state, 2, 0);
}
References container_of, events, lua_uloop_fd::fd, state, and ufd.
Referenced by ul_ufd_add().
ul_ufd_delete()
static int ul_ufd_delete (lua_State * L) static
Definition at line 210 of file uloop.c.
{
    struct lua_uloop_fd *ufd = lua_touserdata(L, 1);
    uloop_fd_delete(&ufd->fd);
    /* obj.__index.__gc = nil , make sure executing only once*/
    lua_getfield(L, -1, "__index");
    lua_pushstring(L, "__gc");
    lua_pushnil(L);
    lua_settable(L, -3);
    lua_getglobal(state, "__uloop_cb");
    luaL_unref(state, -1, ufd->r);
    lua_remove(state, -1);
    lua_getglobal(state, "__uloop_fds");
    luaL_unref(state, -1, ufd->fd_r);
    lua_remove(state, -1);
    return 1;
}
References uloop_fd::fd, state, ufd, and uloop_fd_delete().
Referenced by ul_ufd_add().
Variable Documentation
interval_m
const luaL_Reg interval_m[] static
Initial value:
= {
    { "set", ul_interval_set },
    { "expirations", ul_interval_expirations },
    { "remaining", ul_interval_remaining },
    { "cancel", ul_interval_free },
    { NULL, NULL }
}
Definition at line 461 of file uloop.c.
{
    { "set", ul_interval_set },
    { "expirations", ul_interval_expirations },
    { "remaining", ul_interval_remaining },
    { "cancel", ul_interval_free },
    { NULL, NULL }
};
Referenced by ul_interval().
process_m
const luaL_Reg process_m[] static
Initial value:
= {
    { "delete", ul_process_free },
    { "pid", ul_process_pid },
    { NULL, NULL }
}
Definition at line 309 of file uloop.c.
{
    { "delete", ul_process_free },
    { "pid", ul_process_pid },
    { NULL, NULL }
};
Referenced by ul_process().
signal_m
const luaL_Reg signal_m[] static
Initial value:
= {
    { "signo", ul_signal_signo },
    { "delete", ul_signal_free },
    { NULL, NULL }
}
Definition at line 540 of file uloop.c.
{
    { "signo", ul_signal_signo },
    { "delete", ul_signal_free },
    { NULL, NULL }
};
Referenced by ul_signal().
state
lua_State* state static
Definition at line 54 of file uloop.c.
Referenced by __device_set_present(), __interface_set_down(), _device_set_present(), alias_device_set_state(), b64_decode(), br_set_state(), device_refresh_present(), device_set_link(), dump_msg(), interface_handle_config_change(), interface_proto_event_cb(), interface_set_proto_state(), luaopen_uloop(), mark_interface_down(), proto_init_interface(), proto_shell_add_host_dependency(), proto_shell_attach(), proto_shell_block_restart(), proto_shell_check_dependencies(), proto_shell_checkup_attach(), proto_shell_checkup_timeout_cb(), proto_shell_clear_host_dep(), proto_shell_free(), proto_shell_handler(), proto_shell_if_down_cb(), proto_shell_kill_command(), proto_shell_notify(), proto_shell_notify_error(), proto_shell_run_command(), proto_shell_script_cb(), proto_shell_set_available(), proto_shell_setup_failed(), proto_shell_task_cb(), proto_shell_task_finish(), proto_shell_teardown_timeout_cb(), proto_shell_update_link(), set_device_state(), simple_device_set_state(), static_attach(), static_free(), static_handler(), static_proto_setup(), ul_interval_cb(), ul_interval_free(), ul_process_cb(), ul_process_free(), ul_signal_cb(), ul_signal_free(), ul_timer_cb(), ul_timer_free(), ul_ufd_cb(), ul_ufd_delete(), uxc_state(), and wdev_handle_config_change().
timer_m
const luaL_Reg timer_m[] static
Initial value:
= {
    { "set", ul_timer_set },
    { "remaining", ul_timer_remaining },
    { "cancel", ul_timer_free },
    { NULL, NULL }
}
Definition at line 134 of file uloop.c.
{
    { "set", ul_timer_set },
    { "remaining", ul_timer_remaining },
    { "cancel", ul_timer_free },
    { NULL, NULL }
};
Referenced by ul_timer().
ufd_m
const luaL_Reg ufd_m[] static
Initial value:
= {
    { "delete", ul_ufd_delete },
    { NULL, NULL }
}
Definition at line 233 of file uloop.c.
{
    { "delete", ul_ufd_delete },
    { NULL, NULL }
};
Referenced by ul_ufd_add().
uloop_func
luaL_reg uloop_func[] static
Initial value:
= {
    {"init", ul_init},
    {"run", ul_run},
    {"timer", ul_timer},
    {"process", ul_process},
    {"fd_add", ul_ufd_add},
    {"interval", ul_interval},
    {"signal", ul_signal},
    {"cancel", ul_end},
    {NULL, NULL},
}
Definition at line 600 of file uloop.c.
{
    {"init", ul_init},
    {"run", ul_run},
    {"timer", ul_timer},
    {"process", ul_process},
    {"fd_add", ul_ufd_add},
    {"interval", ul_interval},
    {"signal", ul_signal},
    {"cancel", ul_end},
    {NULL, NULL},
};
Referenced by luaopen_uloop().