zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/ubus.c File Reference
ubus.c File Reference
#include <sys/resource.h>
#include <stdlib.h>
#include <unistd.h>
#include <signal.h>
#include "procd.h"
Functions
static void procd_udebug_cb (struct udebug_ubus *ctx, struct blob_attr *data, bool enabled)
static void reset_timeout (void)
static void timeout_retry (void)
static void ubus_reconnect_cb (struct uloop_timeout *timeout)
static void ubus_disconnect_cb (struct ubus_context *ctx)
static void ubus_connect_cb (struct uloop_timeout *timeout)
void procd_connect_ubus (void)
Variables
char * ubus_socket = NULL
static struct ubus_context * ctx
static struct uloop_timeout ubus_timer
static int timeout
static struct udebug_ubus udebug
Function Documentation
procd_connect_ubus()
void procd_connect_ubus (void)
Definition at line 91 of file ubus.c.
{
    ubus_timer.cb = ubus_connect_cb;
    reset_timeout();
    timeout_retry();
}
References uloop_timeout::cb, reset_timeout(), timeout_retry(), ubus_connect_cb(), and ubus_timer.
Referenced by main(), and state_enter().
procd_udebug_cb()
static void procd_udebug_cb (struct udebug_ubus * ctx, struct blob_attr * data, bool enabled) static
Definition at line 29 of file ubus.c.
{
    procd_udebug_set_enabled(enabled);
}
References procd_udebug_set_enabled().
Referenced by ubus_connect_cb().
reset_timeout()
static void reset_timeout (void) static
Definition at line 34 of file ubus.c.
{
    timeout = 50;
}
References timeout.
Referenced by procd_connect_ubus(), ubus_connect_cb(), and ubus_disconnect_cb().
timeout_retry()
static void timeout_retry (void) static
Definition at line 39 of file ubus.c.
{
    uloop_timeout_set(&ubus_timer, timeout);
    timeout *= 2;
    if (timeout > 1000)
        timeout = 1000;
}
References timeout, ubus_timer, and uloop_timeout_set().
Referenced by procd_connect_ubus(), ubus_connect_cb(), ubus_disconnect_cb(), and ubus_reconnect_cb().
ubus_connect_cb()
static void ubus_connect_cb (struct uloop_timeout * timeout) static
Definition at line 67 of file ubus.c.
{
    ctx = ubus_connect(ubus_socket);
    if (!ctx) {
        DEBUG(4, "Connection to ubus failed\n");
        timeout_retry();
        return;
    }
    udebug_ubus_init(&udebug, ctx, "procd", procd_udebug_cb);
    ctx->connection_lost = ubus_disconnect_cb;
    ubus_init_hotplug(ctx);
    ubus_init_service(ctx);
    ubus_init_system(ctx);
    watch_ubus(ctx);
    DEBUG(2, "Connected to ubus, id=%08x\n", ctx->local_id);
    reset_timeout();
    ubus_add_uloop(ctx);
    procd_state_ubus_connect();
}
References ubus_context::connection_lost, ctx, DEBUG, ubus_context::local_id, procd_state_ubus_connect(), procd_udebug_cb(), reset_timeout(), timeout_retry(), ubus_add_uloop(), ubus_connect(), ubus_disconnect_cb(), ubus_init_hotplug(), ubus_init_service(), ubus_init_system(), ubus_socket, and watch_ubus().
Referenced by procd_connect_ubus().
ubus_disconnect_cb()
static void ubus_disconnect_cb (struct ubus_context * ctx) static
Definition at line 59 of file ubus.c.
{
    ubus_timer.cb = ubus_reconnect_cb;
    reset_timeout();
    timeout_retry();
}
References uloop_timeout::cb, reset_timeout(), timeout_retry(), ubus_reconnect_cb(), and ubus_timer.
Referenced by ubus_connect_cb().
ubus_reconnect_cb()
static void ubus_reconnect_cb (struct uloop_timeout * timeout) static
Definition at line 48 of file ubus.c.
{
    if (!ubus_reconnect(ctx, ubus_socket)) {
        ubus_add_uloop(ctx);
        return;
    }
    timeout_retry();
}
References ctx, timeout_retry(), ubus_add_uloop(), ubus_reconnect(), and ubus_socket.
Referenced by ubus_disconnect_cb().
Variable Documentation
ctx
struct ubus_context* ctx static
Definition at line 23 of file ubus.c.
timeout
int timeout static
Definition at line 25 of file ubus.c.
Referenced by __runqueue_empty_cb(), __runqueue_start_next(), __runqueue_task_timeout(), _trigger_add(), bonding_retry_ports(), bridge_dependency_retry(), bridge_retry_members(), extdev_bridge_retry_enable_members(), handle_button_complete(), handle_button_timeout(), hotplug_exec(), instance_timeout(), netifd_iface_do_remove(), netifd_ubus_device_notify(), poll_restart(), proto_shell_checkup_timeout_cb(), proto_shell_teardown_timeout_cb(), register_kevent(), reset_timeout(), rpc_exec_timeout_cb(), rpc_file_exec_timeout_cb(), rpc_handle_create(), rpc_handle_login(), rpc_list_exec_timeout_cb(), rpc_session_create(), rpc_uci_apply(), rpc_ucode_request_timeout(), test_client_notify_cb(), test_count(), test_hello_fd_reply(), test_hello_reply(), timeout_retry(), trigger_add(), trigger_command_add(), trigger_command_start(), ubus_auto_connect_cb(), ubus_auto_reconnect_cb(), ubus_complete_request(), ubus_invoke(), ubus_invoke_fd(), ubus_lua_connect(), ubus_notify(), ubus_poll_data(), ubus_process_pending_msg(), uloop_fetch_events(), uloop_fetch_events(), uloop_get_next_timeout(), uloop_init_pollfd(), uloop_run_events(), uloop_run_timeout(), uloop_timeout_add(), uloop_timeout_cancel(), uloop_timeout_remaining(), uloop_timeout_remaining64(), uloop_timeout_set(), usock_inet_timeout(), watchdog_set(), watchdog_timeout(), wireless_device_check_script_tasks(), wireless_device_setup_timeout(), and wireless_start_pending().
ubus_socket
char* ubus_socket = NULL
Definition at line 22 of file ubus.c.
Referenced by main(), ubus_connect_cb(), and ubus_reconnect_cb().
ubus_timer
struct uloop_timeout ubus_timer static
Definition at line 24 of file ubus.c.
Referenced by procd_connect_ubus(), timeout_retry(), and ubus_disconnect_cb().
udebug
struct udebug_ubus udebug static
Definition at line 26 of file ubus.c.