zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/jail/cgroups-bpf.h File Reference
cgroups-bpf.h File Reference
Functions
int parseOCIlinuxcgroups_devices (struct blob_attr *msg)
int attach_cgroups_ebpf (int cgroup_dirfd)
Function Documentation
attach_cgroups_ebpf()
int attach_cgroups_ebpf (int cgroup_dirfd)
Definition at line 423 of file cgroups-bpf.c.
{
    int prog_fd;
#if (__WORDSIZE == 64)
    uint64_t program_ptr = (uint64_t)program;
    uint64_t license_ptr = (uint64_t)license;
#elif (__WORDSIZE == 32)
    uint32_t program_ptr = (uint32_t)program;
    uint32_t license_ptr = (uint32_t)license;
#else
#error
#endif
    union bpf_attr load_attr = {
        .prog_type = BPF_PROG_TYPE_CGROUP_DEVICE,
        .license   = license_ptr,
        .insns     = program_ptr,
        .insn_cnt  = bpf_total_insn,
    };
    if (!program)
        return 0;
    prog_fd = syscall_bpf(BPF_PROG_LOAD, &load_attr, sizeof(load_attr));
    if (prog_fd < 0)
        return EIO;
    union bpf_attr attach_attr = {
        .attach_type = BPF_CGROUP_DEVICE,
        .target_fd = cgroup_dirfd,
        .attach_bpf_fd = prog_fd,
    };
    return syscall_bpf(BPF_PROG_ATTACH, &attach_attr, sizeof (attach_attr));
}
References bpf_total_insn, license, program, and syscall_bpf().
Referenced by cgroups_apply().
parseOCIlinuxcgroups_devices()
int parseOCIlinuxcgroups_devices (struct blob_attr * msg)
Definition at line 193 of file cgroups-bpf.c.
{
    struct blob_attr *tb[__OCI_LINUX_CGROUPS_DEVICES_MAX];
    struct blob_attr *cur;
    int rem, ret = 0;
    int bpf_type, bpf_access;
    unsigned char acidx;
    bool allow = false,
         has_access = false,
         has_type = false,
         has_major = false,
         has_minor = false;
    int total_ins = 0,
        cur_ins = 0,
        pre_insn_len = sizeof(pre_insn) / sizeof(struct bpf_insn),
        next_ins;
    char *access, *devtype;
    uint32_t devmajor, devminor;
    struct dev_exception_item *dl;
    struct list_head exceptions;
    enum devcg_behavior behavior = DEVCG_DEFAULT_ALLOW;
    INIT_LIST_HEAD(&exceptions);
    /* parse according to OCI spec */
    blobmsg_for_each_attr(cur, msg, rem) {
        blobmsg_parse(oci_linux_cgroups_devices_policy, __OCI_LINUX_CGROUPS_DEVICES_MAX,
                  tb, blobmsg_data(cur), blobmsg_len(cur));
        if (!tb[OCI_LINUX_CGROUPS_DEVICES_ALLOW]) {
            ret = EINVAL;
            goto out;
        }
        allow = blobmsg_get_bool(tb[OCI_LINUX_CGROUPS_DEVICES_ALLOW]);
        bpf_access = 0;
        if (tb[OCI_LINUX_CGROUPS_DEVICES_ACCESS]) {
            access = blobmsg_get_string(tb[OCI_LINUX_CGROUPS_DEVICES_ACCESS]);
            if ((strlen(access) > 3) || (strlen(access) == 0)) {
                ret = EINVAL;
                goto out;
            }
            for (acidx = 0; acidx < strlen(access); ++acidx) {
                switch (access[acidx]) {
                    case 'r':
                        bpf_access |= BPF_DEVCG_ACC_READ;
                        break;
                    case 'w':
                        bpf_access |= BPF_DEVCG_ACC_WRITE;
                        break;
                    case 'm':
                        bpf_access |= BPF_DEVCG_ACC_MKNOD;
                        break;
                    default:
                        ret = EINVAL;
                        goto out;
                }
            }
        }
        if (!bpf_access)
            bpf_access = DEVCG_ACC_ALL;
        bpf_type = 0;
        if (tb[OCI_LINUX_CGROUPS_DEVICES_TYPE]) {
            devtype = blobmsg_get_string(tb[OCI_LINUX_CGROUPS_DEVICES_TYPE]);
            switch (devtype[0]) {
                case 'c':
                    bpf_type = BPF_DEVCG_DEV_CHAR;
                    break;
                case 'b':
                    bpf_type = BPF_DEVCG_DEV_BLOCK;
                    break;
                case 'a':
                    bpf_type = DEVCG_DEV_ALL;
                    break;
                default:
                    ret = EINVAL;
                    goto out;
            }
        }
        if (!bpf_type)
            bpf_type = DEVCG_DEV_ALL;
        if (tb[OCI_LINUX_CGROUPS_DEVICES_MAJOR])
            devmajor = blobmsg_cast_u64(tb[OCI_LINUX_CGROUPS_DEVICES_MAJOR]);
        else
            devmajor = ~0;
        if (tb[OCI_LINUX_CGROUPS_DEVICES_MINOR])
            devminor = blobmsg_cast_u64(tb[OCI_LINUX_CGROUPS_DEVICES_MINOR]);
        else
            devminor = ~0;
        if (bpf_type == DEVCG_DEV_ALL) {
            /* wildcard => change default policy and flush all existing rules */
            flush_exceptions(&exceptions);
            behavior = allow?DEVCG_DEFAULT_ALLOW:DEVCG_DEFAULT_DENY;
        } else {
            /* allocate and populate record for exception */
            dl = malloc(sizeof(struct dev_exception_item));
            if (!dl) {
                ret = ENOSPC;
                break;
            }
            dl->allow = allow;
            dl->type = bpf_type;
            dl->access = bpf_access;
            dl->major = devmajor;
            dl->minor = devminor;
            /* push to exceptions list, last goes first */
            list_add(&dl->list, &exceptions);
        }
    }
    if (ret)
        goto out;
    /* add default rules */
    ret = add_default_exceptions(&exceptions);
    if (ret)
        goto out;
    /* calculate number of instructions to allocate */
    list_for_each_entry(dl, &exceptions, list) {
        has_access = dl->access != DEVCG_ACC_ALL;
        has_type = dl->type != DEVCG_DEV_ALL;
        has_major = dl->major != ~0;
        has_minor = dl->minor != ~0;
        total_ins += (has_type ? 1 : 0) + (has_access ? 3 : 0) + (has_major ? 1 : 0) + (has_minor ? 1 : 0) + 2;
    }
    /* acccount for loader instructions */
    total_ins += pre_insn_len;
    /* final accept/deny block */
    total_ins += 2;
    /* allocate memory for eBPF program */
    program = calloc(total_ins, sizeof(struct bpf_insn));
    if (!program) {
        ret = ENOMEM;
        goto out;
    }
    /* copy program loader instructions */
    memcpy(program, &pre_insn, sizeof(pre_insn));
    cur_ins = pre_insn_len;
    /* generate eBPF program */
    list_for_each_entry(dl, &exceptions, list) {
        has_access = dl->access != DEVCG_ACC_ALL;
        has_type = dl->type != DEVCG_DEV_ALL;
        has_major = dl->major != ~0;
        has_minor = dl->minor != ~0;
        next_ins = (has_type ? 1 : 0) + (has_access ? 3 : 0) + (has_major ? 1 : 0) + (has_minor ? 1 : 0) + 1;
        if (has_type) {
            program[cur_ins++] = BPF_JMP_IMM(BPF_JNE, BPF_REG_2, dl->type, next_ins);
            --next_ins;
        }
        if (has_access) {
            program[cur_ins++] = BPF_MOV32_REG(BPF_REG_1, BPF_REG_3);
            program[cur_ins++] = BPF_ALU32_IMM(BPF_AND, BPF_REG_1, dl->access);
            program[cur_ins++] = BPF_JMP_REG(BPF_JNE, BPF_REG_1, BPF_REG_3, next_ins - 2);
            next_ins -= 3;
        }
        if (has_major) {
            program[cur_ins++] = BPF_JMP_IMM(BPF_JNE, BPF_REG_4, dl->major, next_ins);
            --next_ins;
        }
        if (has_minor) {
            program[cur_ins++] = BPF_JMP_IMM(BPF_JNE, BPF_REG_5, dl->minor, next_ins);
            --next_ins;
        }
        program[cur_ins++] = BPF_MOV64_IMM(BPF_REG_0, dl->allow ? 1 : 0);
        program[cur_ins++] = BPF_EXIT_INSN();
    }
    /* default behavior */
    program[cur_ins++] = BPF_MOV64_IMM(BPF_REG_0, (behavior == DEVCG_DEFAULT_ALLOW)?1:0);
    program[cur_ins++] = BPF_EXIT_INSN();
    if (debug) {
        fprintf(stderr, "cgroup devices:\na > devices.%s\n",
            (behavior == DEVCG_DEFAULT_ALLOW)?"allow":"deny");
        list_for_each_entry(dl, &exceptions, list)
            fprintf(stderr, "%c %d:%d %s%s%s > devices.%s\n",
                (dl->type == DEVCG_DEV_ALL)?'a':
                    (dl->type == BPF_DEVCG_DEV_CHAR)?'c':'b',
                (dl->major == ~0)?-1:dl->major,
                (dl->minor == ~0)?-1:dl->minor,
                (dl->access & BPF_DEVCG_ACC_READ)?"r":"",
                (dl->access & BPF_DEVCG_ACC_WRITE)?"w":"",
                (dl->access & BPF_DEVCG_ACC_MKNOD)?"m":"",
                (dl->allow)?"allow":"deny");
        fprintf(stderr, "generated cgroup-devices eBPF program:\n");
        fprintf(stderr, " [idx]\tcode\t dest\t src\t off\t imm\n");
        for (cur_ins=0; cur_ins<total_ins; cur_ins++)
            fprintf(stderr, " [%03d]\t%02hhx\t%3hhu\t%3hhu\t%04hx\t%d\n", cur_ins,
                program[cur_ins].code,
                program[cur_ins].dst_reg,
                program[cur_ins].src_reg,
                program[cur_ins].off,
                program[cur_ins].imm);
    }
    assert(cur_ins == total_ins);
    bpf_total_insn = total_ins;
    ret = 0;
out:
    flush_exceptions(&exceptions);
    return ret;
}
References __OCI_LINUX_CGROUPS_DEVICES_MAX, dev_exception_item::access, add_default_exceptions(), dev_exception_item::allow, blobmsg_cast_u64(), blobmsg_data(), blobmsg_for_each_attr, blobmsg_get_bool(), blobmsg_get_string(), blobmsg_len(), blobmsg_parse(), BPF_ALU32_IMM, BPF_EXIT_INSN, BPF_JMP_IMM, BPF_JMP_REG, BPF_MOV32_REG, BPF_MOV64_IMM, bpf_total_insn, debug, DEVCG_ACC_ALL, DEVCG_DEFAULT_ALLOW, DEVCG_DEFAULT_DENY, DEVCG_DEV_ALL, flush_exceptions(), INIT_LIST_HEAD(), dev_exception_item::list, list_add(), list_for_each_entry, dev_exception_item::major, dev_exception_item::minor, OCI_LINUX_CGROUPS_DEVICES_ACCESS, OCI_LINUX_CGROUPS_DEVICES_ALLOW, OCI_LINUX_CGROUPS_DEVICES_MAJOR, OCI_LINUX_CGROUPS_DEVICES_MINOR, oci_linux_cgroups_devices_policy, OCI_LINUX_CGROUPS_DEVICES_TYPE, pre_insn, program, and dev_exception_item::type.
Referenced by parseOCIlinuxcgroups().