zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/jail/cgroups.h File Reference
cgroups.h File Reference
Functions
void cgroups_init (const char *p)
int parseOCIlinuxcgroups (struct blob_attr *msg)
void cgroups_apply (pid_t pid)
void cgroups_free (void)
void cgroups_prepare (void)
Function Documentation
cgroups_apply()
void cgroups_apply (pid_t pid)
Definition at line 102 of file cgroups.c.
{
    struct cgval *valp;
    char *cdir, *ent;
    int fd;
    size_t maxlen = strlen("cgroup.subtree_control");
    bool cpuset = false,
         cpu = false,
         hugetlb = false,
         io = false,
         memory = false,
         pids = false,
         rdma = false;
    char subtree_control[64] = { 0 };
    DEBUG("using cgroup path %s\n", cgroup_path);
    mkdir_p(cgroup_path, 0700);
    /* find which controllers need to be enabled */
    avl_for_each_element(&cgvals, valp, avl) {
        ent = (char *)valp->avl.key;
        if (strlen(ent) > maxlen)
            maxlen = strlen(ent);
        if (!strncmp("cpuset.", ent, 7))
            cpuset = true;
        else if (!strncmp("cpu.", ent, 4))
            cpu = true;
        else if (!strncmp("hugetlb.", ent, 8))
            hugetlb = true;
        else if (!strncmp("io.", ent, 3))
            io = true;
        else if (!strncmp("memory.", ent, 7))
            memory = true;
        else if (!strncmp("pids.", ent, 5))
            pids = true;
        else if (!strncmp("rdma.", ent, 5))
            rdma = true;
    }
    maxlen += strlen(cgroup_path) + 2;
    if (cpuset)
        strcat(subtree_control, "+cpuset ");
    if (cpu)
        strcat(subtree_control, "+cpu ");
    if (hugetlb)
        strcat(subtree_control, "+hugetlb ");
    if (io)
        strcat(subtree_control, "+io ");
    if (memory)
        strcat(subtree_control, "+memory ");
    if (pids)
        strcat(subtree_control, "+pids ");
    if (rdma)
        strcat(subtree_control, "+rdma ");
    /* remove trailing space */
    ent = strchr(subtree_control, '\0') - 1;
    *ent = '\0';
    ent = malloc(maxlen);
    if (!ent)
        exit(ENOMEM);
    DEBUG("recursively applying cgroup.subtree_control = \"%s\"\n", subtree_control);
    cdir = &cgroup_path[strlen(CGROUP_ROOT) - 2];
    while ((cdir = strchr(cdir + 1, '/'))) {
        *cdir = '\0';
        snprintf(ent, maxlen, "%s/cgroup.subtree_control", cgroup_path);
        DEBUG(" * %s\n", ent);
        if ((fd = open(ent, O_WRONLY)) < 0) {
            ERROR("can't open %s: %m\n", ent);
            continue;
        }
        if (write(fd, subtree_control, strlen(subtree_control)) == -1) {
            ERROR("can't write to %s: %m\n", ent);
            close(fd);
            continue;
        }
        close(fd);
        *cdir = '/';
    }
    avl_for_each_element(&cgvals, valp, avl) {
        DEBUG("applying cgroup2 %s=\"%s\"\n", (char *)valp->avl.key, valp->val);
        snprintf(ent, maxlen, "%s/%s", cgroup_path, (char *)valp->avl.key);
        fd = open(ent, O_WRONLY);
        if (fd < 0) {
            ERROR("can't open %s: %m\n", ent);
            continue;
        }
        if (dprintf(fd, "%s", valp->val) < 0) {
            ERROR("can't write to %s: %m\n", ent);
        };
        close(fd);
    }
    int dirfd = open(cgroup_path, O_DIRECTORY);
    if (dirfd < 0) {
        ERROR("can't open %s: %m\n", cgroup_path);
    } else {
        attach_cgroups_ebpf(dirfd);
        close(dirfd);
    }
    snprintf(ent, maxlen, "%s/%s", cgroup_path, "cgroup.procs");
    fd = open(ent, O_WRONLY);
    if (fd < 0) {
        ERROR("can't open %s: %m\n", cgroup_path);
    } else {
        dprintf(fd, "%d", pid);
        close(fd);
    }
    free(ent);
}
References attach_cgroups_ebpf(), cgval::avl, avl_for_each_element, cgroup_path, CGROUP_ROOT, cgvals, DEBUG, ERROR, avl_node::key, mkdir_p(), and cgval::val.
Referenced by post_main().
cgroups_free()
void cgroups_free (void)
Definition at line 88 of file cgroups.c.
{
    struct cgval *valp, *tmp;
    if (initialized) {
        avl_remove_all_elements(&cgvals, valp, avl, tmp) {
            free((void *)(valp->avl.key));
            free(valp->val);
            free(valp);
        }
        free(cgroup_path);
    }
}
References cgval::avl, avl_remove_all_elements, cgroup_path, cgvals, initialized, avl_node::key, and cgval::val.
Referenced by free_and_exit(), free_opts(), and main().
cgroups_init()
void cgroups_init (const char * p)
Definition at line 62 of file cgroups.c.
{
    avl_init(&cgvals, avl_strcmp, false, NULL);
    cgroup_path = strdup(p);
    initialized = true;
}
References avl_init(), avl_strcmp(), cgroup_path, cgvals, and initialized.
Referenced by parseOCIlinux().
cgroups_prepare()
void cgroups_prepare (void)
Definition at line 58 of file cgroups.c.
{
    initialized = false;
}
References initialized.
Referenced by main().
parseOCIlinuxcgroups()
int parseOCIlinuxcgroups (struct blob_attr * msg)
Definition at line 813 of file cgroups.c.
{
    struct blob_attr *tb[__OCI_LINUX_CGROUPS_MAX];
    int ret;
    blobmsg_parse(oci_linux_cgroups_policy, __OCI_LINUX_CGROUPS_MAX, tb, blobmsg_data(msg), blobmsg_len(msg));
    if (tb[OCI_LINUX_CGROUPS_HUGEPAGELIMITS] ||
        tb[OCI_LINUX_CGROUPS_INTELRDT] ||
        tb[OCI_LINUX_CGROUPS_NETWORK] ||
        tb[OCI_LINUX_CGROUPS_RDMA])
        return ENOTSUP;
    if (tb[OCI_LINUX_CGROUPS_BLOCKIO]) {
        ret = parseOCIlinuxcgroups_legacy_blockio(tb[OCI_LINUX_CGROUPS_BLOCKIO]);
        if (ret)
            return ret;
    }
    if (tb[OCI_LINUX_CGROUPS_CPU]) {
        ret = parseOCIlinuxcgroups_legacy_cpu(tb[OCI_LINUX_CGROUPS_CPU]);
        if (ret)
            return ret;
    }
    if (tb[OCI_LINUX_CGROUPS_DEVICES]) {
        ret = parseOCIlinuxcgroups_devices(tb[OCI_LINUX_CGROUPS_DEVICES]);
        if (ret)
            return ret;
    }
    if (tb[OCI_LINUX_CGROUPS_MEMORY]) {
        ret = parseOCIlinuxcgroups_legacy_memory(tb[OCI_LINUX_CGROUPS_MEMORY]);
        if (ret)
            return ret;
    }
    if (tb[OCI_LINUX_CGROUPS_PIDS]) {
        ret = parseOCIlinuxcgroups_legacy_pids(tb[OCI_LINUX_CGROUPS_PIDS]);
        if (ret)
            return ret;
    }
    if (tb[OCI_LINUX_CGROUPS_UNIFIED]) {
        ret = parseOCIlinuxcgroups_unified(tb[OCI_LINUX_CGROUPS_UNIFIED]);
        if (ret)
            return ret;
    }
    return 0;
}
References __OCI_LINUX_CGROUPS_MAX, blobmsg_data(), blobmsg_len(), blobmsg_parse(), OCI_LINUX_CGROUPS_BLOCKIO, OCI_LINUX_CGROUPS_CPU, OCI_LINUX_CGROUPS_DEVICES, OCI_LINUX_CGROUPS_HUGEPAGELIMITS, OCI_LINUX_CGROUPS_INTELRDT, OCI_LINUX_CGROUPS_MEMORY, OCI_LINUX_CGROUPS_NETWORK, OCI_LINUX_CGROUPS_PIDS, oci_linux_cgroups_policy, OCI_LINUX_CGROUPS_RDMA, OCI_LINUX_CGROUPS_UNIFIED, parseOCIlinuxcgroups_devices(), parseOCIlinuxcgroups_legacy_blockio(), parseOCIlinuxcgroups_legacy_cpu(), parseOCIlinuxcgroups_legacy_memory(), parseOCIlinuxcgroups_legacy_pids(), and parseOCIlinuxcgroups_unified().
Referenced by parseOCIlinux().