zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/netifd/proto-static.c File Reference
proto-static.c File Reference
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <arpa/inet.h>
#include <netinet/in.h>
#include "netifd.h"
#include "interface.h"
#include "interface-ip.h"
#include "proto.h"
#include "system.h"
Classes
struct static_proto_state
Functions
static bool static_proto_setup (struct static_proto_state *state)
static int static_handler (struct interface_proto_state *proto, enum interface_proto_cmd cmd, bool force)
static void static_free (struct interface_proto_state *proto)
static struct interface_proto_state * static_attach (const struct proto_handler *h, struct interface *iface, struct blob_attr *attr)
static void __init static_proto_init (void)
Variables
static struct proto_handler static_proto
Class Documentation
static_proto_state
struct static_proto_state
Definition at line 27 of file proto-static.c.
Class Members
struct blob_attr * config
struct interface_proto_state proto
Function Documentation
static_attach()
static struct interface_proto_state * static_attach (const struct proto_handler * h, struct interface * iface, struct blob_attr * attr) static
Definition at line 77 of file proto-static.c.
{
    struct static_proto_state *state;
    state = calloc(1, sizeof(*state));
    if (!state)
        return NULL;
    state->config = malloc(blob_pad_len(attr));
    if (!state->config)
        goto error;
    memcpy(state->config, attr, blob_pad_len(attr));
    state->proto.free = static_free;
    state->proto.cb = static_handler;
    return &state->proto;
error:
    free(state);
    return NULL;
}
References blob_pad_len(), state, static_free(), and static_handler().
static_free()
static void static_free (struct interface_proto_state * proto) static
Definition at line 67 of file proto-static.c.
{
    struct static_proto_state *state;
    state = container_of(proto, struct static_proto_state, proto);
    free(state->config);
    free(state);
}
References container_of, static_proto_state::proto, and state.
Referenced by static_attach().
static_handler()
static int static_handler (struct interface_proto_state * proto, enum interface_proto_cmd cmd, bool force) static
Definition at line 44 of file proto-static.c.
{
    struct static_proto_state *state;
    int ret = 0;
    state = container_of(proto, struct static_proto_state, proto);
    switch (cmd) {
    case PROTO_CMD_SETUP:
        if (!static_proto_setup(state))
            return -1;
        break;
    case PROTO_CMD_TEARDOWN:
    case PROTO_CMD_RENEW:
        break;
    }
    return ret;
}
References cmd, container_of, static_proto_state::proto, PROTO_CMD_RENEW, PROTO_CMD_SETUP, PROTO_CMD_TEARDOWN, state, and static_proto_setup().
Referenced by static_attach().
static_proto_init()
static void __init static_proto_init (void) static
Definition at line 110 of file proto-static.c.
{
    add_proto_handler(&static_proto);
}
References add_proto_handler(), and static_proto.
static_proto_setup()
static bool static_proto_setup (struct static_proto_state * state) static
Definition at line 34 of file proto-static.c.
{
    struct interface *iface = state->proto.iface;
    struct device *dev = iface->main_dev.dev;
    interface_set_l3_dev(iface, dev);
    return proto_apply_static_ip_settings(state->proto.iface, state->config) == 0;
}
References device_user::dev, interface_proto_state::iface, interface_set_l3_dev(), interface::main_dev, interface::proto, proto_apply_static_ip_settings(), and state.
Referenced by static_handler().
Variable Documentation
static_proto
struct proto_handler static_proto static
Initial value:
= {
    .name = "static",
    .flags = PROTO_FLAG_IMMEDIATE |
         PROTO_FLAG_FORCE_LINK_DEFAULT,
    .config_params = &proto_ip_attr,
    .attach = static_attach,
}
Definition at line 101 of file proto-static.c.
{
    .name = "static",
    .flags = PROTO_FLAG_IMMEDIATE |
         PROTO_FLAG_FORCE_LINK_DEFAULT,
    .config_params = &proto_ip_attr,
    .attach = static_attach,
};
Referenced by static_proto_init().