zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/libubox/safe_list.c File Reference
safe_list.c File Reference
#include "safe_list.h"
Classes
struct safe_list_iterator
Functions
static void __safe_list_set_iterator (struct safe_list *list, struct safe_list_iterator *i)
static void __safe_list_del_iterator (struct safe_list_iterator *i)
static void __safe_list_move_iterator (struct safe_list *list, struct safe_list_iterator *i)
int safe_list_for_each (struct safe_list *head, int(*cb)(void *ctx, struct safe_list *list), void *ctx)
void safe_list_add (struct safe_list *list, struct safe_list *head)
void safe_list_add_first (struct safe_list *list, struct safe_list *head)
void safe_list_del (struct safe_list *list)
Class Documentation
safe_list_iterator
struct safe_list_iterator
Definition at line 21 of file safe_list.c.
Class Members
struct safe_list_iterator ** head
struct safe_list * next
struct safe_list_iterator * next_i
Function Documentation
__safe_list_del_iterator()
static void __safe_list_del_iterator (struct safe_list_iterator * i) static
Definition at line 47 of file safe_list.c.
{
    *i->head = i->next_i;
    if (i->next_i)
        i->next_i->head = i->head;
}
References safe_list_iterator::head, safe_list::i, and safe_list_iterator::next_i.
Referenced by __safe_list_move_iterator(), and safe_list_for_each().
__safe_list_move_iterator()
static void __safe_list_move_iterator (struct safe_list * list, struct safe_list_iterator * i) static
Definition at line 55 of file safe_list.c.
{
    __safe_list_del_iterator(i);
    __safe_list_set_iterator(list, i);
}
References __safe_list_del_iterator(), __safe_list_set_iterator(), safe_list::i, and safe_list::list.
Referenced by safe_list_for_each().
__safe_list_set_iterator()
static void __safe_list_set_iterator (struct safe_list * list, struct safe_list_iterator * i) static
Definition at line 28 of file safe_list.c.
{
    struct safe_list_iterator *next_i;
    struct safe_list *next;
    next = list_entry(list->list.next, struct safe_list, list);
    next_i = next->i;
    next->i = i;
    i->next = next;
    i->head = &next->i;
    i->next_i = next_i;
    if (next_i)
        next_i->head = &i->next_i;
}
References safe_list_iterator::head, safe_list::i, safe_list::list, list_entry, list_head::next, safe_list_iterator::next, and safe_list_iterator::next_i.
Referenced by __safe_list_move_iterator(), and safe_list_for_each().
safe_list_add()
void safe_list_add (struct safe_list * list, struct safe_list * head)
Definition at line 83 of file safe_list.c.
{
    list->i = NULL;
    list_add_tail(&list->list, &head->list);
}
References safe_list::list, and list_add_tail().
Referenced by __device_add_user(), __runqueue_start_next(), and _runqueue_task_add().
safe_list_add_first()
void safe_list_add_first (struct safe_list * list, struct safe_list * head)
Definition at line 89 of file safe_list.c.
{
    list->i = NULL;
    list_add(&list->list, &head->list);
}
References safe_list::list, and list_add().
Referenced by _runqueue_task_add().
safe_list_del()
void safe_list_del (struct safe_list * list)
Definition at line 95 of file safe_list.c.
{
    struct safe_list_iterator *i, *next_i, **tail;
    struct safe_list *next;
    next = list_entry(list->list.next, struct safe_list, list);
    list_del(&list->list);
    if (!list->i)
        return;
    next_i = next->i;
    tail = &next->i;
    for (i = list->i; i; i = i->next_i) {
        tail = &i->next_i;
        i->next = next;
    }
    next->i = list->i;
    list->i->head = &next->i;
    *tail = next_i;
    if (next_i)
        next_i->head = tail;
    list->i = NULL;
}
References safe_list_iterator::head, safe_list::i, safe_list::list, list_del(), list_entry, list_head::next, safe_list_iterator::next, and safe_list_iterator::next_i.
Referenced by __runqueue_start_next(), device_remove_user(), device_replace(), and runqueue_task_complete().
safe_list_for_each()
int safe_list_for_each (struct safe_list * head, int(* cb)(void *ctx, struct safe_list *list), void * ctx)
Definition at line 62 of file safe_list.c.
{
    struct safe_list_iterator i;
    struct safe_list *cur;
    int ret = 0;
    for (cur = list_entry(head->list.next, struct safe_list, list),
         __safe_list_set_iterator(cur, &i);
         cur != head;
         cur = i.next, __safe_list_move_iterator(cur, &i)) {
        ret = cb(ctx, cur);
        if (ret)
            break;
    }
    __safe_list_del_iterator(&i);
    return ret;
}
References __safe_list_del_iterator(), __safe_list_move_iterator(), __safe_list_set_iterator(), ctx, safe_list::i, safe_list::list, list_entry, list_head::next, and safe_list_iterator::next.
Referenced by __device_broadcast_event(), _device_set_present(), device_cleanup(), runqueue_cancel_active(), and runqueue_cancel_pending().