zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/procd/container.h File Reference
container.h File Reference
#include <stdlib.h>
#include <stdbool.h>
#include <sys/stat.h>
Functions
static bool is_container ()
Function Documentation
is_container()
static bool is_container () inline static
Definition at line 21 of file container.h.
{
    struct stat s;
    int r = stat("/.dockerenv", &s);
    int pv_r = stat("/pantavisor", &s);
    return !!getenv("container") || r == 0 || pv_r == 0;
}
References r.
Referenced by early_mounts(), perform_halt(), and procd_coldplug().