zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/netifd/tunnel.c File Reference
tunnel.c File Reference
#include "netifd.h"
#include "device.h"
#include "config.h"
#include "system.h"
Classes
struct tunnel
Functions
static int tunnel_set_state (struct device *dev, bool up)
static enum dev_change_type tunnel_reload (struct device *dev, struct blob_attr *attr)
static struct device * tunnel_create (const char *name, struct device_type *devtype, struct blob_attr *attr)
static void tunnel_free (struct device *dev)
static void __init tunnel_device_type_init (void)
Variables
struct device_type tunnel_device_type
Class Documentation
tunnel
struct tunnel
Definition at line 19 of file tunnel.c.
Class Members
struct device dev
device_state_cb set_state
Function Documentation
tunnel_create()
static struct device * tunnel_create (const char * name, struct device_type * devtype, struct blob_attr * attr) static
Definition at line 64 of file tunnel.c.
{
    struct tunnel *tun;
    struct device *dev;
    tun = calloc(1, sizeof(*tun));
    if (!tun)
        return NULL;
    dev = &tun->dev;
    if (device_init(dev, devtype, name) < 0) {
        device_cleanup(dev);
        free(tun);
        return NULL;
    }
    tun->set_state = dev->set_state;
    dev->set_state = tunnel_set_state;
    device_apply_config(dev, devtype, attr);
    device_set_present(dev, true);
    return dev;
}
References tunnel::dev, device_apply_config(), device_cleanup(), device_init(), device_set_present, device::set_state, tunnel::set_state, and tunnel_set_state().
tunnel_device_type_init()
static void __init tunnel_device_type_init (void) static
Definition at line 106 of file tunnel.c.
{
    device_type_add(&tunnel_device_type);
}
References device_type_add(), and tunnel_device_type.
tunnel_free()
static void tunnel_free (struct device * dev) static
Definition at line 91 of file tunnel.c.
{
    struct tunnel *tun = container_of(dev, struct tunnel, dev);
    free(tun);
}
References container_of, and tunnel::dev.
tunnel_reload()
static enum dev_change_type tunnel_reload (struct device * dev, struct blob_attr * attr) static
Definition at line 44 of file tunnel.c.
{
    struct blob_attr *tb_dev[__DEV_ATTR_MAX];
    const struct uci_blob_param_list *cfg = dev->type->config_params;
    if (uci_blob_check_equal(dev->config, attr, cfg))
        return DEV_CONFIG_NO_CHANGE;
    memset(tb_dev, 0, sizeof(tb_dev));
    if (attr)
        blobmsg_parse(device_attr_list.params, __DEV_ATTR_MAX, tb_dev,
            blob_data(attr), blob_len(attr));
    device_init_settings(dev, tb_dev);
    return DEV_CONFIG_RESTART;
}
References __DEV_ATTR_MAX, blob_data(), blob_len(), blobmsg_parse(), device::config, device_type::config_params, DEV_CONFIG_NO_CHANGE, DEV_CONFIG_RESTART, device_attr_list, device_init_settings(), and device::type.
tunnel_set_state()
static int tunnel_set_state (struct device * dev, bool up) static
Definition at line 25 of file tunnel.c.
{
    struct tunnel *tun = container_of(dev, struct tunnel, dev);
    int ret;
    if (up) {
        ret = system_add_ip_tunnel(dev, dev->config);
        if (ret != 0)
            return ret;
    }
    ret = tun->set_state(dev, up);
    if (ret || !up)
        system_del_ip_tunnel(dev);
    return ret;
}
References device::config, container_of, tunnel::dev, tunnel::set_state, system_add_ip_tunnel(), and system_del_ip_tunnel().
Referenced by tunnel_create().
Variable Documentation
tunnel_device_type
struct device_type tunnel_device_type
Initial value:
= {
    .name = "tunnel",
    .config_params = &tunnel_attr_list,
    .reload = tunnel_reload,
    .create = tunnel_create,
    .free = tunnel_free,
}
Definition at line 98 of file tunnel.c.
{
    .name = "tunnel",
    .config_params = &tunnel_attr_list,
    .reload = tunnel_reload,
    .create = tunnel_create,
    .free = tunnel_free,
};
Referenced by proto_shell_create_tunnel(), and tunnel_device_type_init().