zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/netifd/handler.h File Reference
handler.h File Reference
#include <libubox/blobmsg_json.h>
#include <json-c/json.h>
#include "config.h"
Typedefs
typedef void(* script_dump_cb) (const char *script, const char *name, json_object *obj)
typedef void(* create_extdev_handler_cb) (const char *cfg_file, const char *name, const char *ubus_name, bool bridge, const char *br_prefix, json_object *config_obj, json_object *info_obj, json_object *stats_obj)
Functions
static json_object * json_check_type (json_object *obj, json_type type)
static json_object * json_get_field (json_object *obj, const char *name, json_type type)
int netifd_open_subdir (const char *name)
void netifd_init_script_handlers (int dir_fd, script_dump_cb cb)
void netifd_init_extdev_handlers (int dir_fd, create_extdev_handler_cb cb)
char * netifd_handler_parse_config (struct uci_blob_param_list *config, json_object *obj)
Typedef Documentation
create_extdev_handler_cb
typedef void(* create_extdev_handler_cb) (const char *cfg_file, const char *name, const char *ubus_name, bool bridge, const char *br_prefix, json_object *config_obj, json_object *info_obj, json_object *stats_obj)
Definition at line 22 of file handler.h.
script_dump_cb
typedef void(* script_dump_cb) (const char *script, const char *name, json_object *obj)
Definition at line 21 of file handler.h.
Function Documentation
json_check_type()
static json_object * json_check_type (json_object * obj, json_type type) inline static
Definition at line 28 of file handler.h.
{
    if (!obj)
        return NULL;
    if (json_object_get_type(obj) != type)
        return NULL;
    return obj;
}
References type.
Referenced by json_get_field(), netifd_handler_parse_config(), netifd_init_extdev_handler(), and netifd_init_script_handler().
json_get_field()
static json_object * json_get_field (json_object * obj, const char * name, json_type type) inline static
Definition at line 40 of file handler.h.
{
    return json_object_object_get_ex(obj, name, &obj) ?
            json_check_type(obj, type) : NULL;
}
References json_check_type(), and type.
Referenced by netifd_init_extdev_handler(), netifd_init_script_handler(), proto_shell_add_handler(), and wireless_add_handler().
netifd_handler_parse_config()
char * netifd_handler_parse_config (struct uci_blob_param_list * config, json_object * obj)
Definition at line 262 of file handler.c.
{
    struct blobmsg_policy *attrs;
    char *str_buf, *str_cur;
    char const **validate;
    int str_len = 0;
    int i;
    config->n_params = json_object_array_length(obj);
    attrs = calloc(1, sizeof(*attrs) * config->n_params);
    if (!attrs)
        return NULL;
    validate = calloc(1, sizeof(char*) * config->n_params);
    if (!validate)
        goto error;
    config->params = attrs;
    config->validate = validate;
    for (i = 0; i < config->n_params; i++) {
        json_object *cur, *name, *type;
        cur = json_check_type(json_object_array_get_idx(obj, i), json_type_array);
        if (!cur)
            goto error;
        name = json_check_type(json_object_array_get_idx(cur, 0), json_type_string);
        if (!name)
            goto error;
        type = json_check_type(json_object_array_get_idx(cur, 1), json_type_int);
        if (!type)
            goto error;
        attrs[i].name = json_object_get_string(name);
        attrs[i].type = json_object_get_int(type);
        if (attrs[i].type > BLOBMSG_TYPE_LAST)
            goto error;
        str_len += strlen(attrs[i].name) + 1;
    }
    str_buf = malloc(str_len);
    if (!str_buf)
        goto error;
    str_cur = str_buf;
    for (i = 0; i < config->n_params; i++) {
        const char *name = attrs[i].name;
        char *delim;
        attrs[i].name = str_cur;
        str_cur += sprintf(str_cur, "%s", name) + 1;
        delim = strchr(attrs[i].name, ':');
        if (delim) {
            *delim = '\0';
            validate[i] = ++delim;
        } else {
            validate[i] = NULL;
        }
    }
    return str_buf;
error:
    free(attrs);
    if (validate)
        free(validate);
    config->n_params = 0;
    return NULL;
}
References BLOBMSG_TYPE_LAST, config, json_check_type(), blobmsg_policy::name, blobmsg_policy::type, and type.
Referenced by extdev_add_devtype(), proto_shell_add_handler(), and wireless_add_handler().
netifd_init_extdev_handlers()
void netifd_init_extdev_handlers (int dir_fd, create_extdev_handler_cb cb)
Definition at line 249 of file handler.c.
{
    glob_t g;
    int prev_fd;
    prev_fd = netifd_dir_push(dir_fd);
    glob("*.json", 0, NULL, &g);
    for (size_t i = 0; i < g.gl_pathc; i++)
        netifd_parse_extdev_handler(g.gl_pathv[i], cb);
    netifd_dir_pop(prev_fd);
}
References netifd_dir_pop(), netifd_dir_push(), and netifd_parse_extdev_handler().
Referenced by extdev_init().
netifd_init_script_handlers()
void netifd_init_script_handlers (int dir_fd, script_dump_cb cb)
Definition at line 229 of file handler.c.
{
    glob_t g;
    int prev_fd;
    size_t i;
    prev_fd = netifd_dir_push(dir_fd);
    if (glob("./*.sh", 0, NULL, &g)) {
        netifd_dir_pop(prev_fd);
        return;
    }
    for (i = 0; i < g.gl_pathc; i++)
        netifd_parse_script_handler(g.gl_pathv[i], cb);
    netifd_dir_pop(prev_fd);
    globfree(&g);
}
References netifd_dir_pop(), netifd_dir_push(), and netifd_parse_script_handler().
Referenced by proto_shell_init(), and wireless_init().
netifd_open_subdir()
int netifd_open_subdir (const char * name)
Definition at line 44 of file handler.c.
{
    int prev_dir;
    int ret = -1;
    prev_dir = netifd_dir_push(-1);
    if (chdir(main_path)) {
        perror("chdir(main path)");
        goto out;
    }
    ret = open(name, O_RDONLY | O_DIRECTORY);
    if (ret >= 0)
        system_fd_set_cloexec(ret);
out:
    netifd_dir_pop(prev_dir);
    return ret;
}
References main_path, netifd_dir_pop(), netifd_dir_push(), and system_fd_set_cloexec().
Referenced by extdev_init(), proto_shell_init(), and wireless_init().