zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/ubus/ubusd_obj.h File Reference
ubusd_obj.h File Reference
#include "ubusd_id.h"
Classes
struct ubus_object_type
struct ubus_method
struct ubus_subscription
struct ubus_object
Functions
struct ubus_object * ubusd_create_object (struct ubus_client *cl, struct blob_attr **attr)
struct ubus_object * ubusd_create_object_internal (struct ubus_object_type *type, uint32_t id)
void ubusd_free_object (struct ubus_object *obj)
static struct ubus_object * ubusd_find_object (uint32_t objid)
void ubus_subscribe (struct ubus_object *obj, struct ubus_object *target)
void ubus_unsubscribe (struct ubus_subscription *s)
void ubus_notify_unsubscribe (struct ubus_subscription *s)
void ubus_notify_subscription (struct ubus_object *obj)
Variables
struct avl_tree obj_types
struct avl_tree objects
struct avl_tree path
Class Documentation
ubus_object_type
struct ubus_object_type
Definition at line 118 of file libubus.h.
Class Members
uint32_t id
struct ubus_id id
const struct ubus_method * methods
struct list_head methods
int n_methods
const char * name
int refcount
ubus_method
struct ubus_method
Definition at line 108 of file libubus.h.
Class Members
struct blob_attr data[]
ubus_handler_t handler
struct list_head list
unsigned long mask
int n_policy
const char * name
const struct blobmsg_policy * policy
unsigned long tags
ubus_subscription
struct ubus_subscription
Definition at line 38 of file ubusd_obj.h.
Class Members
struct ubus_object * subscriber
struct ubus_object * target
struct list_head list target_list
ubus_object
struct ubus_object
Definition at line 126 of file libubus.h.
Class Members
struct avl_node avl
struct ubus_client * client
int event_seen
struct list_head events
bool has_subscribers
uint32_t id
struct ubus_id id
unsigned int invoke_seq
struct list_head list
const struct ubus_method * methods
int n_methods
const char * name
const char * path
struct avl_node path
int(*)(struct ubus_client *client, struct ubus_msg_buf *ub, const char *method, struct blob_attr *msg) recv_msg
ubus_state_handler_t subscribe_cb
struct list_head subscribers target_list
struct ubus_object_type * type
Function Documentation
ubus_notify_subscription()
void ubus_notify_subscription (struct ubus_object * obj)
Definition at line 615 of file ubusd_proto.c.
{
    bool active = !list_empty(&obj->subscribers);
    struct ubus_msg_buf *ub;
    blob_buf_init(&b, 0);
    blob_put_int32(&b, UBUS_ATTR_OBJID, obj->id.id);
    blob_put_int8(&b, UBUS_ATTR_ACTIVE, active);
    ub = ubus_msg_from_blob(false);
    if (!ub)
        return;
    ubus_msg_init(ub, UBUS_MSG_NOTIFY, ++obj->invoke_seq, 0);
    ubus_msg_send(obj->client, ub);
    ubus_msg_free(ub);
}
References b, blob_buf_init(), blob_put_int32, blob_put_int8, ubus_object::client, ubus_object::id, ubus_object::invoke_seq, list_empty(), UBUS_ATTR_ACTIVE, UBUS_ATTR_OBJID, ubus_msg_free(), ubus_msg_from_blob(), ubus_msg_init(), UBUS_MSG_NOTIFY, and ubus_msg_send().
Referenced by ubus_subscribe(), and ubus_unsubscribe().
ubus_notify_unsubscribe()
void ubus_notify_unsubscribe (struct ubus_subscription * s)
Definition at line 633 of file ubusd_proto.c.
{
    struct ubus_msg_buf *ub;
    blob_buf_init(&b, 0);
    blob_put_int32(&b, UBUS_ATTR_OBJID, s->subscriber->id.id);
    blob_put_int32(&b, UBUS_ATTR_TARGET, s->target->id.id);
    ub = ubus_msg_from_blob(false);
    if (ub != NULL) {
        ubus_msg_init(ub, UBUS_MSG_UNSUBSCRIBE, ++s->subscriber->invoke_seq, 0);
        ubus_msg_send(s->subscriber->client, ub);
        ubus_msg_free(ub);
    }
    ubus_unsubscribe(s);
}
References b, blob_buf_init(), blob_put_int32, ubus_object::client, ubus_object::id, ubus_object::invoke_seq, ubus_subscription::subscriber, ubus_subscription::target, UBUS_ATTR_OBJID, UBUS_ATTR_TARGET, ubus_msg_free(), ubus_msg_from_blob(), ubus_msg_init(), ubus_msg_send(), UBUS_MSG_UNSUBSCRIBE, and ubus_unsubscribe().
Referenced by ubusd_free_object().
ubus_subscribe()
void ubus_subscribe (struct ubus_object * obj, struct ubus_object * target)
Definition at line 172 of file ubusd_obj.c.
{
    struct ubus_subscription *s;
    bool first = list_empty(&target->subscribers);
    s = calloc(1, sizeof(*s));
    if (!s)
        return;
    s->subscriber = obj;
    s->target = target;
    list_add(&s->list, &target->subscribers);
    list_add(&s->target_list, &obj->target_list);
    if (first)
        ubus_notify_subscription(target);
}
References list_add(), list_empty(), ubus_subscription::subscriber, ubus_subscription::target, ubus_object::target_list, ubus_subscription::target_list, and ubus_notify_subscription().
ubus_unsubscribe()
void ubus_unsubscribe (struct ubus_subscription * s)
Definition at line 190 of file ubusd_obj.c.
{
    struct ubus_object *obj = s->target;
    list_del(&s->list);
    list_del(&s->target_list);
    free(s);
    if (list_empty(&obj->subscribers))
        ubus_notify_subscription(obj);
}
References list_del(), list_empty(), ubus_subscription::target, ubus_subscription::target_list, and ubus_notify_subscription().
Referenced by ubusd_free_object().
ubusd_create_object()
struct ubus_object * ubusd_create_object (struct ubus_client * cl, struct blob_attr ** attr)
Definition at line 129 of file ubusd_obj.c.
{
    struct ubus_object *obj;
    struct ubus_object_type *type = NULL;
    if (attr[UBUS_ATTR_OBJTYPE])
        type = ubus_get_obj_type(blob_get_u32(attr[UBUS_ATTR_OBJTYPE]));
    else if (attr[UBUS_ATTR_SIGNATURE])
        type = ubus_create_obj_type(attr[UBUS_ATTR_SIGNATURE]);
    obj = ubusd_create_object_internal(type, 0);
    if (type)
        ubus_unref_object_type(type);
    if (!obj)
        return NULL;
    if (attr[UBUS_ATTR_OBJPATH]) {
        if (ubusd_acl_check(cl, blob_data(attr[UBUS_ATTR_OBJPATH]), NULL, UBUS_ACL_PUBLISH))
            goto free;
        obj->path.key = strdup(blob_data(attr[UBUS_ATTR_OBJPATH]));
        if (!obj->path.key)
            goto free;
        if (avl_insert(&path, &obj->path) != 0) {
            free((void *) obj->path.key);
            obj->path.key = NULL;
            goto free;
        }
        ubusd_send_obj_event(obj, true);
    }
    obj->client = cl;
    list_add(&obj->list, &cl->objects);
    return obj;
free:
    ubusd_free_object(obj);
    return NULL;
}
References avl_insert(), blob_data(), blob_get_u32(), ubus_object::client, ubus_object::list, list_add(), ubus_client::objects, path, ubus_object::path, type, UBUS_ACL_PUBLISH, UBUS_ATTR_OBJPATH, UBUS_ATTR_OBJTYPE, UBUS_ATTR_SIGNATURE, ubus_create_obj_type(), ubus_get_obj_type(), ubus_unref_object_type(), ubusd_acl_check(), ubusd_create_object_internal(), ubusd_free_object(), and ubusd_send_obj_event().
Referenced by ubusd_handle_add_object().
ubusd_create_object_internal()
struct ubus_object * ubusd_create_object_internal (struct ubus_object_type * type, uint32_t id)
Definition at line 103 of file ubusd_obj.c.
{
    struct ubus_object *obj;
    obj = calloc(1, sizeof(*obj));
    if (!obj)
        return NULL;
    if (!ubus_alloc_id(&objects, &obj->id, id))
        goto error_free;
    obj->type = type;
    INIT_LIST_HEAD(&obj->list);
    INIT_LIST_HEAD(&obj->events);
    INIT_LIST_HEAD(&obj->subscribers);
    INIT_LIST_HEAD(&obj->target_list);
    if (type)
        type->refcount++;
    return obj;
error_free:
    free(obj);
    return NULL;
}
References ubus_object::events, ubus_object::id, INIT_LIST_HEAD(), ubus_object::list, objects, ubus_object::target_list, type, ubus_object::type, and ubus_alloc_id().
Referenced by ubusd_acl_init(), ubusd_create_object(), ubusd_event_init(), and ubusd_monitor_init().
ubusd_find_object()
static struct ubus_object * ubusd_find_object (uint32_t objid) inline static
Definition at line 66 of file ubusd_obj.h.
{
    struct ubus_object *obj;
    struct ubus_id *id;
    id = ubus_find_id(&objects, objid);
    if (!id)
        return NULL;
    obj = container_of(id, struct ubus_object, id);
    return obj;
}
References container_of, id, objects, and ubus_find_id().
Referenced by ubusd_alloc_event_pattern(), ubusd_handle_add_watch(), ubusd_handle_remove_object(), ubusd_handle_remove_watch(), ubusd_handle_response(), and ubusd_reply_query().
ubusd_free_object()
void ubusd_free_object (struct ubus_object * obj)
Definition at line 202 of file ubusd_obj.c.
{
    struct ubus_subscription *s, *tmp;
    list_for_each_entry_safe(s, tmp, &obj->target_list, target_list) {
        ubus_unsubscribe(s);
    }
    list_for_each_entry_safe(s, tmp, &obj->subscribers, list) {
        ubus_notify_unsubscribe(s);
    }
    ubusd_event_cleanup_object(obj);
    if (obj->path.key) {
        ubusd_send_obj_event(obj, false);
        avl_delete(&path, &obj->path);
        free((void *) obj->path.key);
    }
    if (!list_empty(&obj->list))
        list_del(&obj->list);
    ubus_free_id(&objects, &obj->id);
    if (obj->type)
        ubus_unref_object_type(obj->type);
    free(obj);
}
References avl_delete(), ubus_object::id, ubus_object::list, list_del(), list_empty(), list_for_each_entry_safe, objects, path, ubus_object::path, ubus_object::target_list, ubus_subscription::target_list, ubus_object::type, ubus_free_id(), ubus_notify_unsubscribe(), ubus_unref_object_type(), ubus_unsubscribe(), ubusd_event_cleanup_object(), and ubusd_send_obj_event().
Referenced by ubusd_create_object(), ubusd_handle_remove_object(), and ubusd_proto_free_client().
Variable Documentation
obj_types
struct avl_tree obj_types extern
Definition at line 17 of file ubusd_obj.c.
Referenced by ubus_create_obj_type(), ubus_get_obj_type(), ubus_unref_object_type(), and ubusd_obj_init().
objects
struct avl_tree objects extern
Definition at line 18 of file ubusd_obj.c.
Referenced by ubusd_create_object_internal(), ubusd_find_object(), ubusd_free_object(), ubusd_handle_invoke(), ubusd_handle_notify(), and ubusd_obj_init().
path
struct avl_tree path extern
Definition at line 19 of file ubusd_obj.c.
Referenced by __rpc_check_path(), __ubusd_handle_lookup(), _add_mount_bind(), _rc(), add_2paths_and_deps(), add_mount_bind(), add_path_and_deps(), add_script_interp(), alloc_library(), alloc_library_path(), cbuf_alloc(), check_sysupgrade(), checkpath(), create_devices(), device_has_attribute(), device_list_insert(), elf_load_deps(), extdev_wait_ev_cb(), find_devs(), get_port_file(), handle_expr_isdir(), handle_firmware(), interface_write_resolv_conf(), is_bridge(), jshn_format_file(), jshn_parse_file(), lib_open(), make_dev(), netifd_ubus_init(), rc_check_script(), rc_init(), rc_list_readdir(), read_file(), rpc_blob_from_file(), rpc_blob_to_file(), rpc_canonicalize_path(), rpc_exec_lookup(), rpc_file_access(), rpc_file_exec_lookup(), rpc_file_list(), rpc_file_md5(), rpc_file_read(), rpc_file_remove(), rpc_file_remove_recursive(), rpc_file_stat(), rpc_file_write(), rpc_login_setup_acl_file(), rpc_plugin_api_init(), rpc_plugin_register_exec(), rpc_plugin_register_library(), rpc_session_freeze(), rpc_session_thaw(), rpc_uci_purge_dir(), rpc_uci_purge_savedir_cb(), rpc_uci_replace_savedir(), rpc_uci_set_savedir(), rpc_ucode_api_init(), rpc_ucode_init_script(), rpc_ucode_script_compile(), rpc_ucode_script_execute(), system_get_bridge(), sysupgrade(), sysupgrade_exec_upgraded(), ubus_auto_sub_event_handler_cb(), ubus_cli_list(), ubus_connect(), ubus_connect_ctx(), ubus_lookup(), ubus_lookup_id(), ubus_lua_call(), ubus_lua_objects(), ubus_lua_signatures(), ubus_reconnect(), ubusd_acl_load(), ubusd_create_object(), ubusd_free_object(), ubusd_obj_init(), udebug_auto_connect(), udebug_connect(), uxc_create(), uxc_set(), validate_firmware_image_call(), wait_check_object(), wait_event_cb(), watch_subscribe_cb(), and write_file().