zbus: /home/g41797/CLionProjects/github.com/g41797/zbus/src/libs/netifd/system.h File Reference
system.h File Reference
#include <net/if.h>
#include <sys/time.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include "device.h"
#include "interface-ip.h"
#include "iprule.h"
#include "utils.h"
Classes
struct bridge_config
struct macvlan_config
struct veth_config
struct vlan_qos_mapping
struct vlandev_config
struct bonding_config
Enumerations
enum tunnel_param {
TUNNEL_ATTR_TYPE , TUNNEL_ATTR_REMOTE , TUNNEL_ATTR_LOCAL , TUNNEL_ATTR_MTU ,
TUNNEL_ATTR_DF , TUNNEL_ATTR_TTL , TUNNEL_ATTR_TOS , TUNNEL_ATTR_LINK ,
TUNNEL_ATTR_DATA , __TUNNEL_ATTR_MAX
}
enum vxlan_data {
VXLAN_DATA_ATTR_ID , VXLAN_DATA_ATTR_PORT , VXLAN_DATA_ATTR_MACADDR , VXLAN_DATA_ATTR_RXCSUM ,
VXLAN_DATA_ATTR_TXCSUM , VXLAN_DATA_ATTR_SRCPORTMIN , VXLAN_DATA_ATTR_SRCPORTMAX , VXLAN_DATA_ATTR_LEARNING ,
VXLAN_DATA_ATTR_RSC , VXLAN_DATA_ATTR_PROXY , VXLAN_DATA_ATTR_L2MISS , VXLAN_DATA_ATTR_L3MISS ,
VXLAN_DATA_ATTR_GBP , VXLAN_DATA_ATTR_AGEING , VXLAN_DATA_ATTR_LIMIT , __VXLAN_DATA_ATTR_MAX
}
enum gre_data {
GRE_DATA_IKEY , GRE_DATA_OKEY , GRE_DATA_ICSUM , GRE_DATA_OCSUM ,
GRE_DATA_ISEQNO , GRE_DATA_OSEQNO , GRE_DATA_ENCAPLIMIT , __GRE_DATA_ATTR_MAX
}
enum vti_data { VTI_DATA_IKEY , VTI_DATA_OKEY , __VTI_DATA_ATTR_MAX }
enum xfrm_data { XFRM_DATA_IF_ID , __XFRM_DATA_ATTR_MAX }
enum sixrd_data { SIXRD_DATA_PREFIX , SIXRD_DATA_RELAY_PREFIX , __SIXRD_DATA_ATTR_MAX }
enum ipip6_data { IPIP6_DATA_ENCAPLIMIT , IPIP6_DATA_FMRS , __IPIP6_DATA_ATTR_MAX }
enum fmr_data {
FMR_DATA_PREFIX6 , FMR_DATA_PREFIX4 , FMR_DATA_EALEN , FMR_DATA_OFFSET ,
__FMR_DATA_ATTR_MAX
}
enum bridge_opt {
BRIDGE_OPT_AGEING_TIME = (1 << 0) , BRIDGE_OPT_ROBUSTNESS = (1 << 1) , BRIDGE_OPT_QUERY_INTERVAL = (1 << 2) , BRIDGE_OPT_QUERY_RESPONSE_INTERVAL = (1 << 3) ,
BRIDGE_OPT_LAST_MEMBER_INTERVAL = (1 << 4)
}
enum macvlan_opt { MACVLAN_OPT_MACADDR = (1 << 0) }
enum veth_opt { VETH_OPT_MACADDR = (1 << 0) , VETH_OPT_PEER_NAME = (1 << 1) , VETH_OPT_PEER_MACADDR = (1 << 2) }
enum vlan_proto { VLAN_PROTO_8021Q = 0x8100 , VLAN_PROTO_8021AD = 0x88A8 }
enum bonding_mode {
BONDING_MODE_BALANCE_RR , BONDING_MODE_ACTIVE_BACKUP , BONDING_MODE_BALANCE_XOR , BONDING_MODE_BROADCAST ,
BONDING_MODE_8023AD , BONDING_MODE_BALANCE_TLB , BONDING_MODE_BALANCE_ALB , __BONDING_MODE_MAX
}
Functions
static int system_get_addr_family (unsigned int flags)
static int system_get_addr_len (unsigned int flags)
int system_init (void)
int system_bridge_addbr (struct device *bridge, struct bridge_config *cfg)
int system_bridge_delbr (struct device *bridge)
int system_bridge_addif (struct device *bridge, struct device *dev)
int system_bridge_delif (struct device *bridge, struct device *dev)
int system_bridge_vlan (const char *iface, uint16_t vid, int16_t vid_end, bool add, unsigned int vflags)
int system_bridge_vlan_check (struct device *dev, char *ifname)
void system_bridge_set_stp_state (struct device *dev, bool val)
int system_bonding_set_device (struct device *dev, struct bonding_config *cfg)
int system_bonding_set_port (struct device *dev, struct device *port, bool add, bool primary)
int system_macvlan_add (struct device *macvlan, struct device *dev, struct macvlan_config *cfg)
int system_macvlan_del (struct device *macvlan)
int system_veth_add (struct device *veth, struct veth_config *cfg)
int system_veth_del (struct device *veth)
int system_vlan_add (struct device *dev, int id)
int system_vlan_del (struct device *dev)
int system_vlandev_add (struct device *vlandev, struct device *dev, struct vlandev_config *cfg)
int system_vlandev_del (struct device *vlandev)
void system_if_get_settings (struct device *dev, struct device_settings *s)
void system_if_clear_state (struct device *dev)
int system_if_up (struct device *dev)
int system_if_down (struct device *dev)
int system_if_check (struct device *dev)
int system_if_resolve (struct device *dev)
int system_if_dump_info (struct device *dev, struct blob_buf *b)
int system_if_dump_stats (struct device *dev, struct blob_buf *b)
struct device * system_if_get_parent (struct device *dev)
bool system_if_force_external (const char *ifname)
void system_if_apply_settings (struct device *dev, struct device_settings *s, uint64_t apply_mask)
void system_if_apply_settings_after_up (struct device *dev, struct device_settings *s)
int system_add_address (struct device *dev, struct device_addr *addr)
int system_del_address (struct device *dev, struct device_addr *addr)
int system_add_route (struct device *dev, struct device_route *route)
int system_del_route (struct device *dev, struct device_route *route)
int system_flush_routes (void)
int system_add_neighbor (struct device *dev, struct device_neighbor *neighbor)
int system_del_neighbor (struct device *dev, struct device_neighbor *neighbor)
bool system_resolve_rt_type (const char *type, unsigned int *id)
bool system_resolve_rt_proto (const char *type, unsigned int *id)
bool system_resolve_rt_table (const char *name, unsigned int *id)
bool system_is_default_rt_table (unsigned int id)
bool system_resolve_rpfilter (const char *filter, unsigned int *id)
int system_del_ip_tunnel (const struct device *dev)
int system_add_ip_tunnel (const struct device *dev, struct blob_attr *attr)
int system_add_iprule (struct iprule *rule)
int system_del_iprule (struct iprule *rule)
int system_flush_iprules (void)
bool system_resolve_iprule_action (const char *action, unsigned int *id)
time_t system_get_rtime (void)
void system_fd_set_cloexec (int fd)
int system_update_ipv6_mtu (struct device *dev, int mtu)
int system_link_netns_move (struct device *dev, const pid_t target_ns, const char *target_ifname)
int system_netns_open (const pid_t target_ns)
int system_netns_set (int netns_fd)
Variables
const struct uci_blob_param_list tunnel_attr_list
const struct uci_blob_param_list vxlan_data_attr_list
const struct uci_blob_param_list gre_data_attr_list
const struct uci_blob_param_list vti_data_attr_list
const struct uci_blob_param_list xfrm_data_attr_list
const struct uci_blob_param_list sixrd_data_attr_list
const struct uci_blob_param_list ipip6_data_attr_list
const struct uci_blob_param_list fmr_data_attr_list
const char *const bonding_policy_str [__BONDING_MODE_MAX]
Class Documentation
bridge_config
struct bridge_config
Definition at line 119 of file system.h.
Class Members
int ageing_time
bool bridge_empty
CIST_BridgeConfig config
enum bridge_opt flags
int forward_delay
int hash_max
int hello_time
bool igmp_snoop
int last_member_interval
int max_age
bool multicast_querier
struct avl_node node
unsigned short priority
int query_interval
int query_response_interval
int robustness
bool stp
bool stp_kernel
const char * stp_proto
uint32_t timestamp
bool vlan_filtering
macvlan_config
struct macvlan_config
Definition at line 148 of file system.h.
Class Members
enum macvlan_opt flags
unsigned char macaddr[6]
const char * mode
veth_config
struct veth_config
Definition at line 161 of file system.h.
Class Members
enum veth_opt flags
unsigned char macaddr[6]
unsigned char peer_macaddr[6]
char peer_name[IFNAMSIZ]
vlan_qos_mapping
struct vlan_qos_mapping
Definition at line 174 of file system.h.
Class Members
uint32_t from
struct vlist_simple_node node
uint32_t to
vlandev_config
struct vlandev_config
Definition at line 180 of file system.h.
Class Members
struct vlist_simple_tree egress_qos_mapping_list
struct vlist_simple_tree ingress_qos_mapping_list
enum vlan_proto proto
uint16_t vid
bonding_config
struct bonding_config
Definition at line 198 of file system.h.
Class Members
int ad_actor_sys_prio
const char * ad_actor_system
const char * ad_select
bool all_ports_active
bool arp_all_targets
struct blob_attr * arp_target
const char * arp_validate
int downdelay
bool dynamic_lb
const char * failover_mac
const char * lacp_rate
int lp_interval
int min_links
bool monitor_arp
int monitor_interval
int num_peer_notif
int packets_per_port
enum bonding_mode policy
const char * primary
const char * primary_reselect
int resend_igmp
int updelay
bool use_carrier
const char * xmit_hash_policy
Enumeration Type Documentation
bonding_mode
enum bonding_mode
Enumerator
BONDING_MODE_BALANCE_RR
BONDING_MODE_ACTIVE_BACKUP
BONDING_MODE_BALANCE_XOR
BONDING_MODE_BROADCAST
BONDING_MODE_8023AD
BONDING_MODE_BALANCE_TLB
BONDING_MODE_BALANCE_ALB
__BONDING_MODE_MAX
Definition at line 187 of file system.h.
                  {
    BONDING_MODE_BALANCE_RR,
    BONDING_MODE_ACTIVE_BACKUP,
    BONDING_MODE_BALANCE_XOR,
    BONDING_MODE_BROADCAST,
    BONDING_MODE_8023AD,
    BONDING_MODE_BALANCE_TLB,
    BONDING_MODE_BALANCE_ALB,
    __BONDING_MODE_MAX,
};
bridge_opt
enum bridge_opt
Enumerator
BRIDGE_OPT_AGEING_TIME (1 << 0)
BRIDGE_OPT_ROBUSTNESS (1 << 1)
BRIDGE_OPT_QUERY_INTERVAL (1 << 2)
BRIDGE_OPT_QUERY_RESPONSE_INTERVAL (1 << 3)
BRIDGE_OPT_LAST_MEMBER_INTERVAL (1 << 4)
Definition at line 110 of file system.h.
                {
    /* stp, forward delay, max age and hello time are always set */
    BRIDGE_OPT_AGEING_TIME          = (1 << 0),
    BRIDGE_OPT_ROBUSTNESS           = (1 << 1),
    BRIDGE_OPT_QUERY_INTERVAL       = (1 << 2),
    BRIDGE_OPT_QUERY_RESPONSE_INTERVAL  = (1 << 3),
    BRIDGE_OPT_LAST_MEMBER_INTERVAL     = (1 << 4),
};
fmr_data
enum fmr_data
Enumerator
FMR_DATA_PREFIX6
FMR_DATA_PREFIX4
FMR_DATA_EALEN
FMR_DATA_OFFSET
__FMR_DATA_ATTR_MAX
Definition at line 94 of file system.h.
              {
    FMR_DATA_PREFIX6,
    FMR_DATA_PREFIX4,
    FMR_DATA_EALEN,
    FMR_DATA_OFFSET,
    __FMR_DATA_ATTR_MAX
};
gre_data
enum gre_data
Enumerator
GRE_DATA_IKEY
GRE_DATA_OKEY
GRE_DATA_ICSUM
GRE_DATA_OCSUM
GRE_DATA_ISEQNO
GRE_DATA_OSEQNO
GRE_DATA_ENCAPLIMIT
__GRE_DATA_ATTR_MAX
Definition at line 60 of file system.h.
              {
    GRE_DATA_IKEY,
    GRE_DATA_OKEY,
    GRE_DATA_ICSUM,
    GRE_DATA_OCSUM,
    GRE_DATA_ISEQNO,
    GRE_DATA_OSEQNO,
    GRE_DATA_ENCAPLIMIT,
    __GRE_DATA_ATTR_MAX
};
ipip6_data
enum ipip6_data
Enumerator
IPIP6_DATA_ENCAPLIMIT
IPIP6_DATA_FMRS
__IPIP6_DATA_ATTR_MAX
Definition at line 88 of file system.h.
                {
    IPIP6_DATA_ENCAPLIMIT,
    IPIP6_DATA_FMRS,
    __IPIP6_DATA_ATTR_MAX
};
macvlan_opt
enum macvlan_opt
Enumerator
MACVLAN_OPT_MACADDR (1 << 0)
Definition at line 144 of file system.h.
                 {
    MACVLAN_OPT_MACADDR = (1 << 0),
};
sixrd_data
enum sixrd_data
Enumerator
SIXRD_DATA_PREFIX
SIXRD_DATA_RELAY_PREFIX
__SIXRD_DATA_ATTR_MAX
Definition at line 82 of file system.h.
                {
    SIXRD_DATA_PREFIX,
    SIXRD_DATA_RELAY_PREFIX,
    __SIXRD_DATA_ATTR_MAX
};
tunnel_param
enum tunnel_param
Enumerator
TUNNEL_ATTR_TYPE
TUNNEL_ATTR_REMOTE
TUNNEL_ATTR_LOCAL
TUNNEL_ATTR_MTU
TUNNEL_ATTR_DF
TUNNEL_ATTR_TTL
TUNNEL_ATTR_TOS
TUNNEL_ATTR_LINK
TUNNEL_ATTR_DATA
__TUNNEL_ATTR_MAX
Definition at line 26 of file system.h.
                  {
    TUNNEL_ATTR_TYPE,
    TUNNEL_ATTR_REMOTE,
    TUNNEL_ATTR_LOCAL,
    TUNNEL_ATTR_MTU,
    TUNNEL_ATTR_DF,
    TUNNEL_ATTR_TTL,
    TUNNEL_ATTR_TOS,
    TUNNEL_ATTR_LINK,
    TUNNEL_ATTR_DATA,
    __TUNNEL_ATTR_MAX
};
veth_opt
enum veth_opt
Enumerator
VETH_OPT_MACADDR (1 << 0)
VETH_OPT_PEER_NAME (1 << 1)
VETH_OPT_PEER_MACADDR (1 << 2)
Definition at line 155 of file system.h.
              {
    VETH_OPT_MACADDR = (1 << 0),
    VETH_OPT_PEER_NAME = (1 << 1),
    VETH_OPT_PEER_MACADDR = (1 << 2),
};
vlan_proto
enum vlan_proto
Enumerator
VLAN_PROTO_8021Q 0x8100
VLAN_PROTO_8021AD 0x88A8
Definition at line 169 of file system.h.
                {
    VLAN_PROTO_8021Q = 0x8100,
    VLAN_PROTO_8021AD = 0x88A8
};
vti_data
enum vti_data
Enumerator
VTI_DATA_IKEY
VTI_DATA_OKEY
__VTI_DATA_ATTR_MAX
Definition at line 71 of file system.h.
              {
    VTI_DATA_IKEY,
    VTI_DATA_OKEY,
    __VTI_DATA_ATTR_MAX
};
vxlan_data
enum vxlan_data
Enumerator
VXLAN_DATA_ATTR_ID
VXLAN_DATA_ATTR_PORT
VXLAN_DATA_ATTR_MACADDR
VXLAN_DATA_ATTR_RXCSUM
VXLAN_DATA_ATTR_TXCSUM
VXLAN_DATA_ATTR_SRCPORTMIN
VXLAN_DATA_ATTR_SRCPORTMAX
VXLAN_DATA_ATTR_LEARNING
VXLAN_DATA_ATTR_RSC
VXLAN_DATA_ATTR_PROXY
VXLAN_DATA_ATTR_L2MISS
VXLAN_DATA_ATTR_L3MISS
VXLAN_DATA_ATTR_GBP
VXLAN_DATA_ATTR_AGEING
VXLAN_DATA_ATTR_LIMIT
__VXLAN_DATA_ATTR_MAX
Definition at line 41 of file system.h.
                {
    VXLAN_DATA_ATTR_ID,
    VXLAN_DATA_ATTR_PORT,
    VXLAN_DATA_ATTR_MACADDR,
    VXLAN_DATA_ATTR_RXCSUM,
    VXLAN_DATA_ATTR_TXCSUM,
    VXLAN_DATA_ATTR_SRCPORTMIN,
    VXLAN_DATA_ATTR_SRCPORTMAX,
    VXLAN_DATA_ATTR_LEARNING,
    VXLAN_DATA_ATTR_RSC,
    VXLAN_DATA_ATTR_PROXY,
    VXLAN_DATA_ATTR_L2MISS,
    VXLAN_DATA_ATTR_L3MISS,
    VXLAN_DATA_ATTR_GBP,
    VXLAN_DATA_ATTR_AGEING,
    VXLAN_DATA_ATTR_LIMIT,
    __VXLAN_DATA_ATTR_MAX
};
xfrm_data
enum xfrm_data
Enumerator
XFRM_DATA_IF_ID
__XFRM_DATA_ATTR_MAX
Definition at line 77 of file system.h.
               {
    XFRM_DATA_IF_ID,
    __XFRM_DATA_ATTR_MAX
};
Function Documentation
system_add_address()
int system_add_address (struct device * dev, struct device_addr * addr)
Definition at line 201 of file system-dummy.c.
{
    return system_address_msg(dev, addr, "add");
}
References system_addr(), and system_address_msg().
Referenced by interface_ip_set_enabled(), interface_set_prefix_address(), and interface_update_proto_addr().
system_add_ip_tunnel()
int system_add_ip_tunnel (const struct device * dev, struct blob_attr * attr)
Definition at line 343 of file system-dummy.c.
{
    return 0;
}
References __TUNNEL_ATTR_MAX, blob_data(), blob_len(), blobmsg_data(), blobmsg_get_u32(), blobmsg_parse(), device_user::dev, device::ifindex, device::ifname, interfaces, interface::l3_dev, system_add_gre_tunnel(), system_add_ip6_tunnel(), system_add_proto_tunnel(), system_add_sit_tunnel(), system_add_vti_tunnel(), system_add_vxlan(), system_add_xfrm_tunnel(), system_link_del(), TUNNEL_ATTR_LINK, tunnel_attr_list, TUNNEL_ATTR_TTL, TUNNEL_ATTR_TYPE, and vlist_find.
Referenced by tunnel_set_state().
system_add_iprule()
int system_add_iprule (struct iprule * rule)
Definition at line 307 of file system-dummy.c.
{
    return 0;
}
References system_iprule().
Referenced by iprule_update_rule(), rule_in_cb(), rule_out_cb(), set_ip_lo_policy(), and set_ip_source_policy().
system_add_neighbor()
int system_add_neighbor (struct device * dev, struct device_neighbor * neighbor)
Definition at line 253 of file system-dummy.c.
{
    return system_neighbor_msg(dev, neighbor, "add");
}
References system_neigh(), and system_neighbor_msg().
Referenced by interface_ip_set_enabled(), and interface_update_proto_neighbor().
system_add_route()
int system_add_route (struct device * dev, struct device_route * route)
Definition at line 263 of file system-dummy.c.
{
    return system_route_msg(dev, route, "add");
}
References system_route_msg(), and system_rt().
Referenced by __interface_update_route(), interface_handle_subnet_route(), interface_ip_set_enabled(), interface_ip_set_route_enabled(), interface_set_prefix_address(), interface_update_prefix(), and interface_update_proto_addr().
system_bonding_set_device()
int system_bonding_set_device (struct device * dev, struct bonding_config * cfg)
Definition at line 78 of file system-dummy.c.
{
    return 0;
}
References bonding_config::ad_actor_sys_prio, bonding_config::ad_actor_system, bonding_config::ad_select, bonding_config::all_ports_active, bonding_config::arp_all_targets, bonding_config::arp_target, bonding_config::arp_validate, blobmsg_for_each_attr, blobmsg_get_string(), BONDING_MODE_8023AD, BONDING_MODE_BALANCE_ALB, BONDING_MODE_BALANCE_RR, BONDING_MODE_BALANCE_TLB, BONDING_MODE_BALANCE_XOR, bonding_policy_str, buf, dev_buf, bonding_config::downdelay, bonding_config::dynamic_lb, bonding_config::failover_mac, device::ifname, ifname, bonding_config::lacp_rate, bonding_config::lp_interval, bonding_config::min_links, bonding_config::monitor_arp, bonding_config::monitor_interval, bonding_config::num_peer_notif, bonding_config::packets_per_port, bonding_config::policy, bonding_config::primary_reselect, bonding_config::resend_igmp, sysfs_path, system_set_dev_sysfs(), system_set_dev_sysfs_int(), bonding_config::updelay, bonding_config::use_carrier, write_file(), and bonding_config::xmit_hash_policy.
Referenced by bonding_set_active().
system_bonding_set_port()
int system_bonding_set_port (struct device * dev, struct device * port, bool add, bool primary)
Definition at line 83 of file system-dummy.c.
{
    return 0;
}
References buf, device::ifname, port, system_if_down(), system_if_up(), and system_set_dev_sysfs().
Referenced by bonding_disable_port(), and bonding_enable_port().
system_bridge_addbr()
int system_bridge_addbr (struct device * bridge, struct bridge_config * cfg)
Definition at line 33 of file system-dummy.c.
{
    D(SYSTEM, "brctl addbr %s vlan_filtering=%d",
      bridge->ifname, cfg->vlan_filtering);
    return 0;
}
References bridge_config::ageing_time, BRIDGE_OPT_AGEING_TIME, BRIDGE_OPT_LAST_MEMBER_INTERVAL, BRIDGE_OPT_QUERY_INTERVAL, BRIDGE_OPT_QUERY_RESPONSE_INTERVAL, BRIDGE_OPT_ROBUSTNESS, D, DEV_OPT_MULTICAST_ROUTER, bridge_config::flags, device_settings::flags, bridge_config::forward_delay, bridge_config::hash_max, bridge_config::hello_time, device::ifname, bridge_config::igmp_snoop, bridge_config::last_member_interval, bridge_config::max_age, bridge_config::multicast_querier, device_settings::multicast_router, bridge_config::priority, bridge_config::query_interval, bridge_config::query_response_interval, bridge_config::robustness, sec_to_jiffies(), device::settings, bridge_config::stp, system_ifinfo_msg(), system_rtnl_call(), and bridge_config::vlan_filtering.
Referenced by bridge_enable_interface().
system_bridge_addif()
int system_bridge_addif (struct device * bridge, struct device * dev)
Definition at line 46 of file system-dummy.c.
{
    D(SYSTEM, "brctl addif %s %s", bridge->ifname, dev->ifname);
    return 0;
}
References device::bpdu_filter, buf, D, dev_buf, DEV_OPT_ISOLATE, DEV_OPT_LEARNING, DEV_OPT_MULTICAST_FAST_LEAVE, DEV_OPT_MULTICAST_ROUTER, DEV_OPT_UNICAST_FLOOD, device_settings::flags, device::ifname, device_settings::isolate, device_settings::learning, device_settings::multicast_fast_leave, device_settings::multicast_router, device::settings, system_bridge_if(), system_bridge_set_bpdu_filter(), system_bridge_set_isolated(), system_bridge_set_learning(), system_bridge_set_multicast_fast_leave(), system_bridge_set_multicast_router(), system_bridge_set_unicast_flood(), system_bridge_set_wireless(), system_get_bridge(), device_settings::unicast_flood, and device::wireless.
Referenced by bridge_enable_member().
system_bridge_delbr()
int system_bridge_delbr (struct device * bridge)
Definition at line 40 of file system-dummy.c.
{
    D(SYSTEM, "brctl delbr %s", bridge->ifname);
    return 0;
}
References D, device::ifname, and system_link_del().
Referenced by bridge_disable_interface(), and system_if_clear_state().
system_bridge_delif()
int system_bridge_delif (struct device * bridge, struct device * dev)
Definition at line 52 of file system-dummy.c.
{
    D(SYSTEM, "brctl delif %s %s", bridge->ifname, dev->ifname);
    return 0;
}
References D, device::ifname, and system_bridge_if().
Referenced by bridge_disable_member().
system_bridge_set_stp_state()
void system_bridge_set_stp_state (struct device * dev, bool val)
Definition at line 69 of file system-dummy.c.
{
}
References device::ifname, and system_set_dev_sysfs().
Referenced by bridge_stp_init().
system_bridge_vlan()
int system_bridge_vlan (const char * iface, uint16_t vid, int16_t vid_end, bool add, unsigned int vflags)
Definition at line 58 of file system-dummy.c.
{
    D(SYSTEM, "brctl vlan %s %s %s vid=%d vid_end=%d pvid=%d untag=%d",
      add ? "add" : "remove",
      (vflags & BRVLAN_F_SELF) ? "self" : "master",
      iface, vid, vid_end,
      !!(vflags & BRVLAN_F_PVID),
      !!(vflags & BRVLAN_F_UNTAGGED));
    return 0;
}
References __system_ifinfo_msg(), BRVLAN_F_PVID, BRVLAN_F_SELF, BRVLAN_F_UNTAGGED, D, and system_rtnl_call().
Referenced by __bridge_set_member_vlan(), bridge_enable_interface(), bridge_enable_member(), bridge_hotplug_set_member_vlans(), bridge_member_add_extra_vlans(), and bridge_set_local_vlan().
system_bridge_vlan_check()
int system_bridge_vlan_check (struct device * dev, char * ifname)
Definition at line 73 of file system-dummy.c.
{
    return 0;
}
References bridge_vlan_ack_cb(), bridge_vlan_check_cb(), bridge_vlan_error_cb(), bridge_vlan_port::check, bridge_vlan::hotplug_ports, bridge_vlan_check_data::ifindex, device::ifindex, bridge_vlan_port::ifname, ifname, bridge_vlan_hotplug_port::list, list_for_each_entry, bridge_vlan::n_ports, bridge_vlan_check_data::pending, port, bridge_vlan::ports, bridge_vlan_check_data::ret, sock_rtnl, device::vlans, and vlist_for_each_element.
Referenced by bridge_member_check_cb().
system_del_address()
int system_del_address (struct device * dev, struct device_addr * addr)
Definition at line 206 of file system-dummy.c.
{
    return system_address_msg(dev, addr, "del");
}
References system_addr(), and system_address_msg().
Referenced by interface_ip_set_enabled(), interface_set_prefix_address(), and interface_update_proto_addr().
system_del_ip_tunnel()
int system_del_ip_tunnel (const struct device * dev)
Definition at line 338 of file system-dummy.c.
{
    return 0;
}
References device::ifname, and system_link_del().
Referenced by tunnel_set_state().
system_del_iprule()
int system_del_iprule (struct iprule * rule)
Definition at line 312 of file system-dummy.c.
{
    return 0;
}
References system_iprule().
Referenced by iprule_update_rule(), rule_in_cb(), rule_out_cb(), set_ip_lo_policy(), and set_ip_source_policy().
system_del_neighbor()
int system_del_neighbor (struct device * dev, struct device_neighbor * neighbor)
Definition at line 258 of file system-dummy.c.
{
    return system_neighbor_msg(dev, neighbor, "del");
}
References system_neigh(), and system_neighbor_msg().
Referenced by interface_ip_set_enabled(), and interface_update_proto_neighbor().
system_del_route()
int system_del_route (struct device * dev, struct device_route * route)
Definition at line 268 of file system-dummy.c.
{
    return system_route_msg(dev, route, "del");
}
References system_route_msg(), and system_rt().
Referenced by __interface_update_route(), interface_handle_subnet_route(), interface_ip_set_enabled(), interface_ip_set_route_enabled(), interface_set_prefix_address(), interface_update_prefix(), and interface_update_proto_addr().
system_fd_set_cloexec()
void system_fd_set_cloexec (int fd)
Definition at line 134 of file system.c.
{
#ifdef FD_CLOEXEC
    fcntl(fd, F_SETFD, fcntl(fd, F_GETFD) | FD_CLOEXEC);
#endif
}
Referenced by netifd_dir_push(), netifd_open_subdir(), netifd_start_process(), netifd_ubus_add_fd(), and system_init().
system_flush_iprules()
int system_flush_iprules (void)
Definition at line 317 of file system-dummy.c.
{
    return 0;
}
References iprule::flags, IPRULE_INET4, IPRULE_INET6, IPRULE_LOOKUP, IPRULE_PRIORITY, iprule::lookup, iprule::priority, system_if_clear_entries(), and system_iprule().
Referenced by iprule_update_start().
system_flush_routes()
int system_flush_routes (void)
Definition at line 273 of file system-dummy.c.
{
    return 0;
}
References ARRAY_SIZE, dev_buf, and proc_path.
Referenced by interface_proto_event_cb(), and mark_interface_down().
system_get_addr_family()
static int system_get_addr_family (unsigned int flags) inline static
Definition at line 225 of file system.h.
{
    if ((flags & DEVADDR_FAMILY) == DEVADDR_INET6)
        return AF_INET6;
    else
        return AF_INET;
}
References DEVADDR_FAMILY, and DEVADDR_INET6.
Referenced by system_address_msg(), system_neighbor_msg(), and system_route_msg().
system_get_addr_len()
static int system_get_addr_len (unsigned int flags) inline static
Definition at line 233 of file system.h.
{
    if ((flags & DEVADDR_FAMILY) != DEVADDR_INET6)
        return sizeof(struct in_addr);
    else
        return sizeof(struct in6_addr);
}
References DEVADDR_FAMILY, and DEVADDR_INET6.
Referenced by system_route_msg().
system_get_rtime()
time_t system_get_rtime (void)
Definition at line 328 of file system-dummy.c.
{
    struct timeval tv;
    if (gettimeofday(&tv, NULL) == 0)
        return tv.tv_sec;
    return 0;
}
Referenced by interface_ip_add_route(), interface_ip_dump_address_list(), interface_ip_dump_prefix_assignment_list(), interface_ip_dump_prefix_list(), interface_ip_dump_route_list(), interface_ip_valid_until_handler(), interface_proto_event_cb(), interface_refresh_assignments(), interface_set_prefix_address(), interface_update_prefix(), interface_update_prefix_delegation(), netifd_dump_status(), parse_addr(), parse_address_item(), parse_prefix_option(), and system_addr().
system_if_apply_settings()
void system_if_apply_settings (struct device * dev, struct device_settings * s, uint64_t apply_mask)
Definition at line 179 of file system-dummy.c.
{
    apply_mask &= s->flags;
    if ((apply_mask & (DEV_OPT_MACADDR | DEV_OPT_DEFAULT_MACADDR)) && !dev->external) {
        D(SYSTEM, "ifconfig %s hw ether %s",
          dev->ifname, format_macaddr(s->macaddr));
    }
}
References device_settings::acceptlocal, device_settings::arp_accept, buf, D, device_settings::dadtransmits, DEV_OPT_ACCEPTLOCAL, DEV_OPT_ARP_ACCEPT, DEV_OPT_DADTRANSMITS, DEV_OPT_DEFAULT_MACADDR, DEV_OPT_DROP_GRATUITOUS_ARP, DEV_OPT_DROP_UNSOLICITED_NA, DEV_OPT_DROP_V4_UNICAST_IN_L2_MULTICAST, DEV_OPT_DROP_V6_UNICAST_IN_L2_MULTICAST, DEV_OPT_IGMPVERSION, DEV_OPT_IP6SEGMENTROUTING, DEV_OPT_IPV6, DEV_OPT_MACADDR, DEV_OPT_MASTER, DEV_OPT_MLDVERSION, DEV_OPT_MTU, DEV_OPT_MTU6, DEV_OPT_MULTICAST, DEV_OPT_NEIGHGCSTALETIME, DEV_OPT_NEIGHLOCKTIME, DEV_OPT_NEIGHREACHABLETIME, DEV_OPT_PROMISC, DEV_OPT_RPFILTER, DEV_OPT_SENDREDIRECTS, DEV_OPT_TXQUEUELEN, device_check_ip6segmentrouting(), device_settings::drop_gratuitous_arp, device_settings::drop_unsolicited_na, device_settings::drop_v4_unicast_in_l2_multicast, device_settings::drop_v6_unicast_in_l2_multicast, device::external, device_settings::flags, format_macaddr(), device::ifname, device_settings::igmpversion, device_settings::ip6segmentrouting, device_settings::ipv6, L_WARNING, device_settings::macaddr, device_settings::master_ifindex, device_settings::mldversion, device_settings::mtu, device_settings::mtu6, device_settings::multicast, device_settings::neigh4gcstaletime, device_settings::neigh4locktime, device_settings::neigh4reachabletime, device_settings::neigh6gcstaletime, device_settings::neigh6reachabletime, netifd_log_message(), device::orig_settings, device_settings::promisc, device_settings::rpfilter, device_settings::sendredirects, sock_ioctl, system_if_flags(), system_refresh_orig_macaddr(), system_set_acceptlocal(), system_set_arp_accept(), system_set_dadtransmits(), system_set_disable_ipv6(), system_set_drop_gratuitous_arp(), system_set_drop_unsolicited_na(), system_set_drop_v4_unicast_in_l2_multicast(), system_set_drop_v6_unicast_in_l2_multicast(), system_set_ethtool_settings(), system_set_igmpversion(), system_set_ip6segmentrouting(), system_set_master(), system_set_mldversion(), system_set_neigh4gcstaletime(), system_set_neigh4locktime(), system_set_neigh4reachabletime(), system_set_neigh6gcstaletime(), system_set_neigh6reachabletime(), system_set_rpfilter(), system_set_sendredirects(), system_update_ipv6_mtu(), and device_settings::txqueuelen.
Referenced by bonding_port_cb(), bridge_member_cb(), and set_device_state().
system_if_apply_settings_after_up()
void system_if_apply_settings_after_up (struct device * dev, struct device_settings * s)
Definition at line 2351 of file system-linux.c.
{
    system_set_ethtool_settings_after_up(dev, s);
}
References system_set_ethtool_settings_after_up().
Referenced by set_device_state().
system_if_check()
int system_if_check (struct device * dev)
Definition at line 144 of file system-dummy.c.
{
    if (dev->type == &simple_device_type)
        device_set_present(dev, true);
    device_set_link(dev, true);
    return 0;
}
References cb_if_check_ack(), cb_if_check_error(), cb_if_check_valid(), if_check_data::dev, device_set_link(), device_set_present, device::ifname, if_check_data::pending, if_check_data::ret, simple_device_type, sock_rtnl, and device::type.
system_if_clear_state()
void system_if_clear_state (struct device * dev)
Definition at line 139 of file system-dummy.c.
{
    device_set_ifindex(dev, system_if_resolve(dev));
}
References buf, D, device_set_ifindex(), device::external, device::ifindex, device::ifname, system_bridge_delbr(), system_bridge_if(), system_get_bridge(), system_if_clear_entries(), system_if_flags(), system_if_resolve(), system_is_bridge(), and system_set_disable_ipv6().
Referenced by device_init().
system_if_down()
int system_if_down (struct device * dev)
Definition at line 129 of file system-dummy.c.
{
    D(SYSTEM, "ifconfig %s down", dev->ifname);
    return 0;
}
References D, device::ifname, and system_if_flags().
Referenced by set_device_state(), and system_bonding_set_port().
system_if_dump_info()
int system_if_dump_info (struct device * dev, struct blob_buf * b)
Definition at line 166 of file system-dummy.c.
{
    blobmsg_add_u8(b, "link", dev->present);
    return 0;
}
References b, blobmsg_add_string(), blobmsg_add_string_buffer(), blobmsg_add_u8(), blobmsg_alloc_string_buffer(), blobmsg_close_array(), blobmsg_close_table(), blobmsg_open_array(), blobmsg_open_table(), ethtool_feature_value(), device::ifname, device::present, sock_ioctl, system_add_devtype(), system_add_ethtool_pause_an(), system_add_link_modes(), system_add_pause_modes(), and system_get_ethtool_pause().
Referenced by bridge_dump_info(), device_dump_status(), macvlan_dump_info(), veth_dump_info(), and vlandev_dump_info().
system_if_dump_stats()
int system_if_dump_stats (struct device * dev, struct blob_buf * b)
Definition at line 173 of file system-dummy.c.
{
    return 0;
}
References ARRAY_SIZE, b, blobmsg_add_u64(), dev_sysfs_path(), device::ifname, and read_uint64_file().
Referenced by device_dump_status().
system_if_force_external()
bool system_if_force_external (const char * ifname)
Definition at line 118 of file system-dummy.c.
{
    return false;
}
References dev_sysfs_path(), and ifname.
Referenced by device_create_default().
system_if_get_parent()
struct device * system_if_get_parent (struct device * dev)
Definition at line 160 of file system-dummy.c.
{
    return NULL;
}
References buf, device_get(), device::ifindex, device::ifname, system_get_dev_sysfs(), and system_if_resolve().
Referenced by simple_device_set_state().
system_if_get_settings()
void system_if_get_settings (struct device * dev, struct device_settings * s)
Definition at line 135 of file system-dummy.c.
{
}
References device_settings::acceptlocal, device_settings::arp_accept, buf, device_settings::dadtransmits, DEV_OPT_ACCEPTLOCAL, DEV_OPT_ARP_ACCEPT, DEV_OPT_DADTRANSMITS, DEV_OPT_DROP_GRATUITOUS_ARP, DEV_OPT_DROP_UNSOLICITED_NA, DEV_OPT_DROP_V4_UNICAST_IN_L2_MULTICAST, DEV_OPT_DROP_V6_UNICAST_IN_L2_MULTICAST, DEV_OPT_GRO, DEV_OPT_IGMPVERSION, DEV_OPT_IP6SEGMENTROUTING, DEV_OPT_IPV6, DEV_OPT_MACADDR, DEV_OPT_MASTER, DEV_OPT_MLDVERSION, DEV_OPT_MTU, DEV_OPT_MTU6, DEV_OPT_MULTICAST, DEV_OPT_NEIGHGCSTALETIME, DEV_OPT_NEIGHLOCKTIME, DEV_OPT_NEIGHREACHABLETIME, DEV_OPT_PROMISC, DEV_OPT_RPFILTER, DEV_OPT_SENDREDIRECTS, DEV_OPT_TXQUEUELEN, device_settings::drop_gratuitous_arp, device_settings::drop_unsolicited_na, device_settings::drop_v4_unicast_in_l2_multicast, device_settings::drop_v6_unicast_in_l2_multicast, device_settings::flags, device_settings::gro, device::ifname, device_settings::igmpversion, device_settings::ip6segmentrouting, device_settings::ipv6, device_settings::macaddr, device_settings::master_ifindex, device_settings::mldversion, device_settings::mtu, device_settings::mtu6, device_settings::multicast, device_settings::neigh4gcstaletime, device_settings::neigh4locktime, device_settings::neigh4reachabletime, device_settings::neigh6gcstaletime, device_settings::neigh6reachabletime, device_settings::promisc, device_settings::rpfilter, device_settings::sendredirects, sock_ioctl, system_get_acceptlocal(), system_get_arp_accept(), system_get_dadtransmits(), system_get_disable_ipv6(), system_get_drop_gratuitous_arp(), system_get_drop_unsolicited_na(), system_get_drop_v4_unicast_in_l2_multicast(), system_get_drop_v6_unicast_in_l2_multicast(), system_get_ethtool_gro(), system_get_igmpversion(), system_get_ip6segmentrouting(), system_get_mldversion(), system_get_neigh4gcstaletime(), system_get_neigh4locktime(), system_get_neigh4reachabletime(), system_get_neigh6gcstaletime(), system_get_neigh6reachabletime(), system_get_rpfilter(), system_get_sendredirects(), system_if_get_master_ifindex(), system_update_ipv6_mtu(), and device_settings::txqueuelen.
Referenced by set_device_state().
system_if_resolve()
int system_if_resolve (struct device * dev)
Definition at line 154 of file system-dummy.c.
{
    return 1;
}
References device::ifname, and sock_ioctl.
Referenced by set_device_state(), system_if_clear_state(), system_if_get_parent(), and system_link_netns_move().
system_if_up()
int system_if_up (struct device * dev)
Definition at line 123 of file system-dummy.c.
{
    D(SYSTEM, "ifconfig %s up", dev->ifname);
    return 0;
}
References D, device::ifname, and system_if_flags().
Referenced by set_device_state(), and system_bonding_set_port().
system_init()
int system_init (void)
Definition at line 28 of file system-dummy.c.
{
    return 0;
}
References cb_rtnl_event(), create_event_socket(), create_hotplug_event_socket(), create_socket(), handle_hotplug_event(), event_socket::sock, sock_ioctl, sock_rtnl, and system_fd_set_cloexec().
Referenced by main().
system_is_default_rt_table()
bool system_is_default_rt_table (unsigned int id)
Definition at line 296 of file system-dummy.c.
{
    return true;
}
Referenced by interface_ip_add_route().
system_link_netns_move()
int system_link_netns_move (struct device * dev, const pid_t target_ns, const char * target_ifname)
system_macvlan_add()
int system_macvlan_add (struct device * macvlan, struct device * dev, struct macvlan_config * cfg)
Definition at line 353 of file system-dummy.c.
{
    return 0;
}
References ARRAY_SIZE, D, macvlan_config::flags, device::ifindex, device::ifname, macvlan_config::macaddr, MACVLAN_OPT_MACADDR, macvlan_config::mode, system_ifinfo_msg(), and system_rtnl_call().
Referenced by macvlan_set_up().
system_macvlan_del()
int system_macvlan_del (struct device * macvlan)
Definition at line 358 of file system-dummy.c.
{
    return 0;
}
References device::ifname, and system_link_del().
Referenced by macvlan_set_down(), and macvlan_set_up().
system_netns_open()
int system_netns_open (const pid_t target_ns)
Definition at line 94 of file system-dummy.c.
{
    D(SYSTEM, "open netns of pid %d", target_ns);
    return 1;
}
References D.
system_netns_set()
int system_netns_set (int netns_fd)
Definition at line 100 of file system-dummy.c.
{
    D(SYSTEM, "set netns %d", netns_fd);
    return 0;
}
References D, and netns_fd.
system_resolve_iprule_action()
bool system_resolve_iprule_action (const char * action, unsigned int * id)
Definition at line 322 of file system-dummy.c.
{
    *id = 0;
    return true;
}
References iprule::action, and system_rtn_aton().
Referenced by iprule_add(), and set_ip_source_policy().
system_resolve_rpfilter()
bool system_resolve_rpfilter (const char * filter, unsigned int * id)
Definition at line 301 of file system-dummy.c.
{
    *id = 0;
    return true;
}
Referenced by device_init_settings().
system_resolve_rt_proto()
bool system_resolve_rt_proto (const char * type, unsigned int * id)
Definition at line 284 of file system-dummy.c.
{
    *id = 0;
    return true;
}
References buf, and type.
Referenced by interface_handle_subnet_route(), and interface_ip_add_route().
system_resolve_rt_table()
bool system_resolve_rt_table (const char * name, unsigned int * id)
Definition at line 290 of file system-dummy.c.
{
    *id = 0;
    return true;
}
References buf.
Referenced by interface_alloc(), interface_ip_add_route(), and iprule_add().
system_resolve_rt_type()
bool system_resolve_rt_type (const char * type, unsigned int * id)
Definition at line 278 of file system-dummy.c.
{
    *id = 0;
    return true;
}
References system_rtn_aton(), and type.
Referenced by interface_ip_add_route().
system_update_ipv6_mtu()
int system_update_ipv6_mtu (struct device * dev, int mtu)
Definition at line 348 of file system-dummy.c.
{
    return 0;
}
References buf, dev_sysctl_path(), and device::ifname.
Referenced by interface_set_prefix_address(), system_if_apply_settings(), and system_if_get_settings().
system_veth_add()
int system_veth_add (struct device * veth, struct veth_config * cfg)
Definition at line 363 of file system-dummy.c.
{
    return 0;
}
References D, veth_config::flags, veth_config::macaddr, veth_config::peer_macaddr, veth_config::peer_name, system_rtnl_call(), VETH_OPT_MACADDR, VETH_OPT_PEER_MACADDR, and VETH_OPT_PEER_NAME.
Referenced by veth_set_up().
system_veth_del()
int system_veth_del (struct device * veth)
Definition at line 368 of file system-dummy.c.
{
    return 0;
}
References system_link_del().
Referenced by veth_set_down(), and veth_set_up().
system_vlan_add()
int system_vlan_add (struct device * dev, int id)
Definition at line 106 of file system-dummy.c.
{
    D(SYSTEM, "vconfig add %s %d", dev->ifname, id);
    return 0;
}
References D, device::ifname, and system_vlan().
Referenced by vlan_set_device_state().
system_vlan_del()
int system_vlan_del (struct device * dev)
Definition at line 112 of file system-dummy.c.
{
    D(SYSTEM, "vconfig rem %s", dev->ifname);
    return 0;
}
References D, device::ifname, and system_vlan().
Referenced by vlan_set_device_state().
system_vlandev_add()
int system_vlandev_add (struct device * vlandev, struct device * dev, struct vlandev_config * cfg)
Definition at line 373 of file system-dummy.c.
{
    return 0;
}
References D, vlandev_config::egress_qos_mapping_list, vlan_qos_mapping::from, device::ifindex, device::ifname, vlandev_config::ingress_qos_mapping_list, L_WARNING, device_type::name, netifd_log_message(), vlandev_config::proto, system_rtnl_call(), vlan_qos_mapping::to, device::type, vlandev_config::vid, VLAN_PROTO_8021AD, and vlist_simple_for_each_element.
Referenced by vlandev_set_up().
system_vlandev_del()
int system_vlandev_del (struct device * vlandev)
Definition at line 378 of file system-dummy.c.
{
    return 0;
}
References device::ifname, and system_link_del().
Referenced by vlandev_set_down(), and vlandev_set_up().
Variable Documentation
bonding_policy_str
const char* const bonding_policy_str[__BONDING_MODE_MAX] extern
Definition at line 124 of file system.c.
{
    [BONDING_MODE_BALANCE_RR] = "balance-rr",
    [BONDING_MODE_ACTIVE_BACKUP] = "active-backup",
    [BONDING_MODE_BALANCE_XOR] = "balance-xor",
    [BONDING_MODE_BROADCAST] = "broadcast",
    [BONDING_MODE_8023AD] = "802.3ad",
    [BONDING_MODE_BALANCE_TLB] = "balance-tlb",
    [BONDING_MODE_BALANCE_ALB] = "balance-alb",
};
Referenced by bonding_apply_settings(), and system_bonding_set_device().
fmr_data_attr_list
const struct uci_blob_param_list fmr_data_attr_list extern
Definition at line 119 of file system.c.
{
    .n_params = __FMR_DATA_ATTR_MAX,
    .params = fmr_data_attrs,
};
Referenced by system_add_ip6_tunnel().
gre_data_attr_list
const struct uci_blob_param_list gre_data_attr_list extern
Definition at line 68 of file system.c.
{
    .n_params = __GRE_DATA_ATTR_MAX,
    .params = gre_data_attrs,
};
Referenced by system_add_gre_tunnel().
ipip6_data_attr_list
const struct uci_blob_param_list ipip6_data_attr_list extern
Definition at line 107 of file system.c.
{
    .n_params = __IPIP6_DATA_ATTR_MAX,
    .params = ipip6_data_attrs,
};
Referenced by system_add_ip6_tunnel().
sixrd_data_attr_list
const struct uci_blob_param_list sixrd_data_attr_list extern
Definition at line 97 of file system.c.
{
    .n_params = __SIXRD_DATA_ATTR_MAX,
    .params = sixrd_data_attrs,
};
Referenced by system_add_sit_tunnel().
tunnel_attr_list
const struct uci_blob_param_list tunnel_attr_list extern
Definition at line 30 of file system.c.
{
    .n_params = __TUNNEL_ATTR_MAX,
    .params = tunnel_attrs,
};
Referenced by system_add_ip_tunnel().
vti_data_attr_list
const struct uci_blob_param_list vti_data_attr_list extern
Definition at line 78 of file system.c.
{
    .n_params = __VTI_DATA_ATTR_MAX,
    .params = vti_data_attrs,
};
Referenced by system_add_vti_tunnel().
vxlan_data_attr_list
const struct uci_blob_param_list vxlan_data_attr_list extern
Definition at line 53 of file system.c.
{
    .n_params = __VXLAN_DATA_ATTR_MAX,
    .params = vxlan_data_attrs,
};
Referenced by system_add_vxlan().
xfrm_data_attr_list
const struct uci_blob_param_list xfrm_data_attr_list extern
Definition at line 87 of file system.c.
{
    .n_params = __XFRM_DATA_ATTR_MAX,
    .params = xfrm_data_attrs,
};
Referenced by system_add_xfrm_tunnel().